### ISSUE TITLE
[Unit Test] testSyncUA fails on main

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/firefox-ios#10013]
This unit test [testSyncUA](https://github.com/mozilla-mobile/firefox-ios/blob/0dab728a700df53fe5b9883d697a13ad59e1252e/ClientTests/ClientTests.swift#L15) is failing with error:

file:///Users/vagrant/git/ClientTests/ClientTests.swift:CharacterRangeLen=0&EndingLineNumber=22&StartingLineNumber=22 - XCTAssertTrue failed - Sync UA is as expected. Was Firefox-iOS-Sync/v98.0b1 (iPhone; iPhone OS 15.0) (Fennec (vagrant))

Please see build logs: https://app.bitrise.io/build/334804b6-d69b-4ac4-a186-55f1081ad27e#?tab=log

I think it started to fail after commit: 4e8f7049d3653bf701366df309a06afc4fde0536
cc @nbhasin2 (as author ;) )

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3761)

**Comment by nbhasin2** [comment]
@isabelrios I reverted the version number here https://github.com/mozilla-mobile/firefox-ios/commit/67d061d130a64c62d00a609ebe3e8666a6e75f3b

Lets see if this passess - https://app.bitrise.io/build/6242ca03-37fd-46cc-bbf0-255576542095#?tab=log

**Comment by isabelrios** [comment]
Yes, it passes, sorry I did not know that could be reverted, (I could have done by myself) thought the version number had to be that and so another fix needed.
Thanks for the quick patch.
I think we can close this now
