### ISSUE TITLE
The rating prompt is displayed too soon. CDOU value has not reached 5 of 7 days.

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#10011]
## Steps to reproduce
1. Clean install app from app store v97.0 (7635)
2. Launch app 
3. Go to "amazon.com" -> Tap on the lock icon - > Change tracking protection to "Strict" -> Close the app
4. Go to iOS settings -> Change date from 14.02 to 15.02
5. Open the app -> Open tabs tray -> Close the app
6. Go to iOS settings -> Change date from 15.02 to 16.02
7. Open the app -> Open tabs tray -> Close the app
8. Go to iOS settings -> Change date from 16.02 to 17.02
9. Open the app -> Open tabs tray -> Close the app
10. Go to iOS settings -> Change date from 17.02 to 18.02
11. Open the app -> Open tabs tray -> Close the app
### Expected behavior
- The rating prompt should be displayed after cumulative days of use counter value of 5 in the last 7 days.
### Actual behavior
- The rating prompt is displayed on the 5th launch after installing the app.
- The cumulative days of use counter value is incorrect. In my case the cumulative days of use counter is calculated in 5 days instead of 7.
### Device & build information
* Device: iPhone 13 (15.1.1)
* Build version: 96.0 (7635)
### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3759)

**Comment by SimonBasca** [comment]
Note: 
- The issue is also after changing the default search engine to Duck Duck Go from Google and following the STR.

**Comment by lmarceau** [comment]
@SimonBasca I'm not sure I understand 🤔 In your STR I see the following dates: 14.02, 15.02, 16.02, 17.02, 18.02. That would be five different days so that would be 5 days of use? Unless I misunderstood the requirements? Thanks!!

**Comment by SimonBasca** [comment]
> @SimonBasca I'm not sure I understand 🤔 In your STR I see the following dates: 14.02, 15.02, 16.02, 17.02, 18.02. That would be five different days so that would be 5 days of use? Unless I misunderstood the requirements? Thanks!!

@lmarceau you are right. The way I understand it is that we should wait 7 days and after we should check if the value has 5 days of CDOU. I guess in this case if we have 5 consecutive day there's no point in waiting 2 more to check the value.
