### ISSUE TITLE
Add Notifiable protocol

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#10014]
We currently handle notifications for KVO stuff in different ways. We should standardize it going forward, using a clear and simple interface for our needs.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3763)

**Comment by data-sync-user** [comment]
➤ Roux Buciu commented:

I’m doing this work as part of a separate ticket in the sprint (the home button ticket), but it’s technically its own thing so I’m separating the commits and creating a ticket/PR for this.

**Comment by lmarceau** [comment]
Link to PR: https://github.com/mozilla-mobile/firefox-ios/pull/10015
