### ISSUE TITLE
[RTL] The URL text stretches outside the URL bar and the "x" should be left aligned

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#10027]
## Steps to reproduce
1. Change language to arabic
2. Visit "netflix.com/ro-en/"
3. Tap on the URL bar
### Expected behavior
- The URL bar should have proper RTL support 
### Actual behavior
- The URL text stretches outside the URL bar
- The "x" should be left aligned 
### Device & build information
* Device: iPhone 12 Pro (15.2)
* Build version: 98.0 (8023)
### Notes
Attachments: 

![image](https://user-images.githubusercontent.com/32130829/154076898-1dea18cf-9b4c-4729-934d-2435e26cec2d.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3770)

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verifying as fix on main 7493300c088051ed0a06d54dd5e1a6ff21cdd8a3

**Comment by SimonBasca** [comment]
Verified fix on v99.0 (8544).
