### ISSUE TITLE
 Closing a tab in the tab view sometimes appears to close two tabs

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/firefox-ios#10024]
## Steps to reproduce
I don’t have reliable steps to reproduce the problem, but sometimes when closing a tab in the tab view, two tabs appear to close instead of one. I am not using the chronological tabs layout. 

The bug _might_ happen more often my phone is rotated to landscape orientation and/or when the closes tab is the last tab in a tab rope in the tab view.

### Expected behavior
Only one tab should close. 

### Actual behavior
Two tabs appear to close instead of one. Fortunately, only one tab is actually closed. The second tab appears after selecting a tab and then returning to the tab view. 

I first noticed this problem yesterday (2022-02-14), but TestFlight says my Beta 97.0 (7635) build was released on 2022-01-25 so I guess this is not a very recent regression. 

### Device & build information
* Device: iOS 15.3.1 on iPhone 12
* Build version: Beta 97.0 (7635)

### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3768)

**Comment by jacobsvante** [comment]
I don't know if I'm experiencing the same bug but sometimes when I try to close one tab, another one is closed instead. This seems to happen when Firefox has been running for a while.

**Comment by atamanroman** [comment]
> I don't know if I'm experiencing the same bug but sometimes when I try to close one tab, another one is closed instead. This seems to happen when Firefox has been running for a while.
> 
> Edit: I've only experienced it while "swipe closing".

I've seen this, too: https://github.com/mozilla-mobile/firefox-ios/issues/11528

**Comment by dnarcese** [comment]
Is this the same bug #10165 ?

**Comment by cpeterso** [comment]
> Is this the same bug #10165 ?

I think so, so I'll close this issue
