### ISSUE TITLE
Umlaut URLs not showing correctly

### ISSUE THREAD

**Issue by kelimuttu** [mozilla-mobile/firefox-ios#10023]
## Steps to reproduce
* Go to URL with umlaut (e.g. https://plötzlich-selbständig.de/)
* Look at the address bar

### Expected behavior
Address bar is showing URL with umlaut correctly

### Actual behavior
Address bar is not showing URL with umlaut correctly

### Device & build information
* Device: iOS 15.2.1 
* Build version: Daylight 97
  1. Notes
Attachments: 
Firefox for iOS
![photo](https://user-images.githubusercontent.com/4922388/154001382-1981f27c-fb3b-4dc2-a45e-ff6f68aa0c84.jpeg)UNITO-UNDERSCORE!2022-02-15 12 56 02!
Safari
![photo](https://user-images.githubusercontent.com/4922388/154001389-917c9209-a9bd-4656-921c-ade48cf5bbdb.jpeg)UNITO-UNDERSCORE!2022-02-15 12 56 04!

Based on user report: https://support.mozilla.org/en-US/questions/1367500

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3767)

**Comment by junbio** [comment]
Looks like it's blocked due to this https://bugzilla.mozilla.org/show_bug.cgi?id=1312294. But thanks to your report, I found another bug in Firefox with the example URL you provided. Thanks!
