### ISSUE TITLE
Crash if URL has a dash and is encoded with Punycode

### ISSUE THREAD

**Issue by junbio** [mozilla-mobile/firefox-ios#10036]
## Steps to reproduce
1. Type in URL with Punycode and a dash such as https://plötzlich-selbständig.de

### Expected behavior
App doesn't crash

### Actual behavior
App crashes

### Device & build information
* Device: iPhone X
* Build version: Fennec
### Notes
Since Punycode is disabled on the release version of Firefox, this only crashes on Fennec.
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3775)

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verified fix on Fennec main fe7143df48899790144e0a5240fd153d6a70f94a on iPhone 12 Pro (15.4).
