### ISSUE TITLE
Back arrow in QR code scanner points to wrong direction for RTL languages

### ISSUE THREAD

**Issue by junbio** [mozilla-mobile/firefox-ios#10033]
## Steps to reproduce
1. Tap URL bar
2. Tap QR button

### Expected behavior
Arrow points to right

### Actual behavior
Arrow points left

### Device & build information
* Device: iPhone X (iOS 15.3.1)
* Build version: v97 (7635)
### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3773)

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verifying as fix on main 7493300c088051ed0a06d54dd5e1a6ff21cdd8a3

**Comment by SimonBasca** [comment]
Verified fix on v99.0 (8544).
