### ISSUE TITLE
Title and close button missing in tabs overview for RTL languages

### ISSUE THREAD

**Issue by junbio** [mozilla-mobile/firefox-ios#10042]
## Steps to reproduce
1. Switch iPhone to Hebrew
2. Tap tabs button

### Expected behavior
Title visible and close button on left

### Actual behavior
Title missing and close button gone

### Device & build information
* Device: iPhone X (iOS 15.3.1)
* Build version: v97 (7635)
### Notes
Attachments: 
![IMG_4310](https://user-images.githubusercontent.com/66826029/154296297-ba1a7585-a791-447a-9f24-13ae607660d2.PNG)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3779)

**Comment by csuciu** [comment]
Verifying as fixed on latest master/iPhone 12 (15.3.1).
