### ISSUE TITLE
Suggestions being cut off in landscape for RTL languages

### ISSUE THREAD

**Issue by junbio** [mozilla-mobile/firefox-ios#10043]
## Steps to reproduce
1. Switch iPhone to Hebrew
2. Tap URL bar
3. Switch to landscape
4. Type query

### Expected behavior
Suggestions has margin for screen cutout

### Actual behavior
History suggestion cut off

### Device & build information
* Device: iPhone X (iOS 15.3.1)
* Build version: v97 (7635)
### Notes
Attachments: 
![IMG_4311](https://user-images.githubusercontent.com/66826029/154296920-15752dcd-5e2d-4fcb-a29f-5b8732e2db15.PNG)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3778)

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verified fix on v9000 (8716).
