### ISSUE TITLE
Previously opened page is not loading after +4 hours

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#10047]
## Steps to reproduce
1. Visit a page e.g "amazon.com"
2. Close the app
3. Change the time to 4h forward e.g (from 18:20 to 22:20)
4. Launch Firefox
5. Observe the opened tab
### Expected behavior
- A new home tab should be created and amazon.com should be opened.
### Actual behavior
- The opened tab is at Firefox home and the user is unable to go to the previously opened page, in this case "amazon.com".
### Device & build information
* Device: iPhone 13 mini (15.1)
* Build version:  98.0 (8023)
### Notes
Attachments: 

https://user-images.githubusercontent.com/32130829/154312712-8bd7c1d0-1622-4f00-b5ad-1972c16a7b8b.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3781)

**Comment by lmarceau** [comment]
@SimonBasca I think this is https://github.com/mozilla-mobile/firefox-ios/issues/9803 🤔

**Comment by SimonBasca** [comment]
For sure that's the one @lmarceau .Closing as duplicate of https://github.com/mozilla-mobile/firefox-ios/issues/9803
