### ISSUE TITLE
The login support page is missing.

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#10046]
## Steps to reproduce
1. Clean install Firefox
2. Go to Login screen
3. Tap on the "Learn more" button
### Expected behavior
- The support page should be displayed.
### Actual behavior
- The login support page is missing.
### Device & build information
* Device: iPhone 13 mini (15.1)
* Build version:  98.0 (8023)
### Notes
Attachments: 

https://user-images.githubusercontent.com/32130829/154312932-2a893d5f-f261-49cb-9d9f-7a9e33747342.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3780)

**Comment by junbio** [comment]
Looks like it's supposed to go to this page: https://support.mozilla.org/en-US/kb/manage-saved-passwords-firefox-ios but instead there's a placeholder4 string. Note that http://support.mozilla.org/1/mobile/97.0/iOS/en-US/tracking-protection-ios redirects to the correct page but the equivalent doesn't.

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verifying as fix on v9000 (8950).
