### ISSUE TITLE
Remove deferred in Pocket API

### ISSUE THREAD

**Issue by lmarceau** [mozilla-mobile/firefox-ios#10055]
1. Remove deferred from Pocket API in `PocketFeed.swift` → Maybe with Async/Await, or completion/closure? To be investigated.
1. Add unit tests to catch any issues with FxHomePocketViewModel or PocketFeed

I've also seen this crash pop up a couple of times - but couldn't get reproducible steps. I have hopes that removing deferred in Pocket could help fix it or help us gather more information on it. Worst case, that's one less deferred in our codebase.

![width=200,height=183](https://user-images.githubusercontent.com/11338480/154515236-0f67ea13-01e5-4d70-9a58-872db68a6414.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3787)

**Comment by data-sync-user** [comment]
➤ Laurie Marceau commented:

We have this crash in Sentry cloud as well: https://sentry.io/share/issue/bfbeb6191a334ca889db5c7f9d9ec9a8/ ( https://sentry.io/share/issue/bfbeb6191a334ca889db5c7f9d9ec9a8/|smart-link )

**Comment by data-sync-user** [comment]
➤ Laurie Marceau commented:

Turns out this task was done a while ago. There’s no more Deferred in the pocket code anymore.
