### ISSUE TITLE
Right click doesn't work for some sites

### ISSUE THREAD

**Issue by junbio** [mozilla-mobile/firefox-ios#10057]
## Steps to reproduce
1. Go to https://daringfireball.net
2. Right click any link

### Expected behavior
Context menu pops up

### Actual behavior
Firefox tries to select text

### Device & build information
![Simulator Screen Shot - iPad Pro (11-inch) (3rd generation) - 2022-02-17 at 08 56 43](https://user-images.githubusercontent.com/66826029/154531810-d74734a5-45cc-4020-b94f-7ca26cb5d554.png)

* Device: iPad Simulator (iPadOS 15.2)
* Build version: Fennec
### Notes
Same cause as #10026
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3789)

**Comment by lmarceau** [comment]
This issue still happens and was discussed on Element. The contributor noted:

> if you have a usb mouse and plug it in with a usb-c adapter, the mouse will work on ipados as well. i imagine bluetooth mice probably work as well — if there is still interest in getting this bug fixed hopefully that may help with testing :)


Here a video showing on iPad (first the behavior with Safari, then within Firefox).

https://user-images.githubusercontent.com/11338480/225334534-9dc31c48-02b0-46db-84f0-dbb2bbb48047.mp4
