### ISSUE TITLE
 After opening a new tab and immediately starting to type into the address bar, anything typed in the first half second after the tab is opened is deleted

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#10054]
## Steps to reproduce
1. Open the latest version of Firefox (as of 15th February, but this issue has been ongoing for several months)
1. Using the magic keyboard on an iPad Pro 2021, press CMD+T to open a new tab
1. Immediately start typing. You’ll notice the characters appear in the address bar
  1. Expected behavior

* The character typed in the first 0.5 second of a new tab opening should not be deleted
  1. Actual behavior
* After approximate 0.5 second, the tab appears to refresh and all characters previously entered into the address bar are removed. - Any further characters typed are entered as expected
  1. Device & build information
* Device: 
* Build version: v97.(8023) and main 440f1aee29106b71ba555658b167dadb2e069467
  1. Notes
Attachments: 

via https://bugzilla.mozilla.org/show_bug.cgi?id=1755442

Video: https://bugzilla.mozilla.org/attachment.cgi?id=9263911

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3786)

**Comment by dnarcese** [comment]
@SimonBasca are you able to reproduce this on newer builds?

**Comment by SimonBasca** [comment]
@dnarcese I was unable to reproduce this issue on v107 (21907) or latest main v9000 (21972). Let's reopen this issue when it's reproducible again.
