### ISSUE TITLE
Cannot build firefox-ios on intel Mac11.6.3 with Xcode13.2.1

### ISSUE THREAD

**Issue by ruchigupta19** [mozilla-mobile/firefox-ios#10066]
getting this error while trying to build firefox-ios project on intel Mac11:

```
build failed: The following build commands failed:
PhaseScriptExecution Run\ Script /Users/gruchi/Library/Developer/Xcode/DerivedData/Client-aqxthwdewqtqwzhivgirkzijrzwa/Build/Intermediates.noindex/Client.build/Fennec-iphoneos/Client.build/Script-4368F81027955AE80013419B.sh (in target 'Client' from project 'Client')
```

I made sure to check out the main branch

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3796)

**Comment by lmarceau** [comment]
Hi @ruchigupta19 
Can you try the following:
- Reset packages cache
- Resolve Package versions
- Clean build

Run the Fennec schema.
