### ISSUE TITLE
Back arrow in Library panel flipped for RTL languages

### ISSUE THREAD

**Issue by junbio** [mozilla-mobile/firefox-ios#10065]
## Steps to reproduce
1. Open app menu
2. Tap bookmarks button
3. Tap bookmarks folder

### Expected behavior
Back arrow points right

### Actual behavior
Back arrow points left

### Device & build information
* Device: iPhone X (iOS 15.3.1)
* Build version: v97 (7635)
### Notes
Attachments: 
![IMG_4317](https://user-images.githubusercontent.com/66826029/154754968-7dde9c0a-9419-4797-8384-07150e975c12.PNG)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3795)

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verified fix on v9000 (8716).
