### ISSUE TITLE
Shadows on "Jump Back In" card

### ISSUE THREAD

**Issue by topotropic** [mozilla-mobile/firefox-ios#10060]
- The shadow is cut off for the card – it would be great to find a way to not cut it off. 

- The card w the favicon on top of the card doesn't need a shadow, a simple border will do. 

Thanks!

<img width="1283" alt="image" src="https://user-images.githubusercontent.com/353960/154567390-33243548-29d8-46c1-934a-add16d8b0fa9.png">

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3793)

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verified fix on main a9ede72fce803e663c5ae71b7c1bd231ddc76b3d
