### ISSUE TITLE
Your Library disappeared from homepage

### ISSUE THREAD

**Issue by charger-john** [mozilla-mobile/firefox-ios#10070]
Device: iPhone 12 iOS 14.8.1
Build version: Firefox for iOS version 97.0
——
My home page has Shortcuts, Jump Back In, and Recommended by Pocket. But it doesn’t have Your Library anymore. 

Your Library was there when I installed the app. It disappeared for no apparent reason. I don’t see a setting (or any help topics) to get it back. Thank you~

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3799)

**Comment by dnarcese** [comment]
Hi, this is intentional. We are currently running experiments with these homepage sections.
