### ISSUE TITLE
[XCUITests] Full functional tests need to be updated after new browser tab menu lands

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/firefox-ios#10078]
There are a lot of changes with the removal of the POM and some of those options moved into BrowserTabMenu, other options have been deleted and there are a few new ones.
See PR #10072 

Tests for the Smoketest are updated in the same PR that lands with those changes so that Bitrise is green, but the rest of tests should be updated too.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3804)

**Comment by lmarceau** [comment]
Just to note, the option "No image" was moved to the settings instead of being accessed in a menu. It's now a toggle there!
