### ISSUE TITLE
URL bar message is cut 

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#10084]
## Steps to reproduce
1. Upgrade from v97.0 to 98.0 (8153)
OR
1. Clean install 98.0 (8153) on small screen devices e.g iPhone 13 mini
### Expected behavior
- The CFR message should be correctly displayed
### Actual behavior
- The CFR message is cut. 
### Device & build information
* Device: iPhone 12 pro (15.1) and iPhone 13 mini (15.1)
* Build version: 
### Notes
Attachments: 

## Issue when clean install  on iPhone 13 mini

![screenshot](https://user-images.githubusercontent.com/32130829/155519097-3a887ad5-19d0-4660-91a4-c95b363ebdcc.jpeg)

## Issue when upgrading on iPhone 12 pro

![Skype_Picture_2022_02_24T11_54_37_081Z](https://user-images.githubusercontent.com/32130829/155519650-90648ef4-c599-40b4-8bf5-782f3ecfc075.jpeg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3806)

**Comment by data-sync-user** [comment]
➤ Laurie Marceau commented:

This is the same issue as https://mozilla-hub.atlassian.net/browse/FXIOS-3809 ( https://mozilla-hub.atlassian.net/browse/FXIOS-3809|smart-link ) 👍

**Comment by lmarceau** [comment]
Update: On `main` this is now a bit better with latest PR. But still work to do. There should be no 3 dots on that CFR. Will work on that first thing tomorrow morning.

![Simulator Screen Shot - iPhone SE (2nd generation) - 2022-02-24 at 17 31 30](https://user-images.githubusercontent.com/11338480/155618522-725ce026-ceef-47d4-ad0d-6c0b5fc89136.png)

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verified fix on v98.0 (8219)
