### ISSUE TITLE
[iPad]Hide the toolbar settings for iPad

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#10083]
## Steps to reproduce
1. Install v97.0 
2. Upgrade to v98.0 (8153)
3. Tap on the "Toolbar Settings" button 
4. Tap on "bottom"

### Expected behavior
- In the design docs iPad support was not mentioned. Not sure if this should be supported or not.
- Design docs: https://www.figma.com/file/mauncxLvUBkgXNBICDPZbC/Bottom-Address-Bar?node-id=1021%3A50820
### Actual behavior
- The layout is broken.
- The option to move the URL bar to the top is not visible in Settings
### Device & build information
* Device: iPad Pro (15.2)
* Build version: 98.0 (8153)
### Notes
Attachments: 

https://user-images.githubusercontent.com/32130829/155523784-07c5341f-7026-41ec-9a92-8b5a56270879.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3805)

**Comment by lmarceau** [comment]
Just to note: Issue was that this CFR (purple popup) shouldn't show at all for iPad. By clicking on the button in that CFR we were able to access the toolbar settings that shouldn't be accessible at all on iPad. iPad should not have bottom search bar or it's setting in any occasion.

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verified fix on v98.0 (8184)
