### ISSUE TITLE
The "jump in " section is not immediately displayed

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#10098]
## Steps to reproduce
1. Clean install v98.0 (8184)
2. Visit a page
3. Open a new tab
### Expected behavior
- The "jump in" section should be displayed.
### Actual behavior
- The "jump in " section is not immediately displayed. After closing and re-opening the app it's visible.
### Device & build information
* Device: iPhone 12 Pro (15.2)
* Build version: 98.0 (8184)
### Notes
Attachments: 

https://user-images.githubusercontent.com/32130829/155691443-1b92a121-bde5-4d7a-a95a-92966c9435a2.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3815)

**Comment by dnarcese** [comment]
This could be because Nimbus hasn't loaded yet.
