### ISSUE TITLE
Onboarding is displayed a second time after first launch

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#10097]
## Steps to reproduce
1. Clean install v98.0 (8184)
1. Launch the app
1. Dismiss the onboarding by tapping outside the oboarding area
1. Close the app
1. Re-open the app
  1. Expected behavior

* Onboarding should be displayed only once
  1. Actual behavior
* Onboarding is displayed a second time after first launch
  1. Device & build information
* Device: iPad Pro (15.2)
* Build version: 98.0 (8184)
  1. Notes
Attachments: 

https://user-images.githubusercontent.com/32130829/155689116-7b99bc81-4e8b-42b1-a43f-d476ea662c29.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3814)

**Comment by lmarceau** [comment]
This bug happens if we click outside of the onboarding on iPad. If we click on the X the pref is correctly saved. So two solutions:
- We remove the ability the dismiss outside popover for this particular onboarding
- We save the pref that the onboarding was shown when we dismiss outside of it
