### ISSUE TITLE
Keyboard is showing on top of search bar

### ISSUE THREAD

**Issue by nbhasin2** [mozilla-mobile/firefox-ios#10095]
## Steps to reproduce
- Have swiftkey keyboard installed
- Open Firefox App (Beta or Normal) 
- Make sure Firefox has bottom url bar enabled
- The keyboard height is different so when we open Firefox home-page for the first time the keyboard is shown on top of bottom toolbar 
- NOTE: This also happens with emoji keyboard (Apple's regular keybord, see 2nd video) 

### Expected behavior
- Height of urlbar should be adjusted so it is anchored on top of keyboard

### Actual behavior
- Url bar is hidden 

### Device & build information
* Device: iPhone 11 pro
* Build version: 8173

### Notes
Attachments: 

<table>
  <tr>
    <td>
<video src='https://user-images.githubusercontent.com/8919439/155608742-709f42ea-5b93-4c11-9dc0-af56eee8e6bf.mov' width=180/>
</td>
    <td>
<video src='https://user-images.githubusercontent.com/8919439/155607999-72a1f49a-af21-4382-8d78-feb1c1e25b77.mov ' width=180/>
</td>
  </tr>
</table>

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3811)

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

I am still reproducing the issue on v98.0 (8219) and on latest main a9ede72fce803e663c5ae71b7c1bd231ddc76b3d after following the STR.

  1. Set swift keyboard as main keyboard
  2. Close app from app switcher
  3. Cold launch Firefox

!video.mp4|width=888,height=1920!

Laurie Marceau do you mind taking a look at this?

**Comment by data-sync-user** [comment]
➤ Laurie Marceau commented:

Thanks Simion Basca , I’ll have a look!

**Comment by lmarceau** [comment]
We'll revert this fix from v98 so regressions with #10116 and #10113 will only be on the main branch for now. We'll need to fix those for v99.

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verifying as fix on main 7493300c088051ed0a06d54dd5e1a6ff21cdd8a3

**Comment by SimonBasca** [comment]
Verified fix on v99.0 (8544).
