### ISSUE TITLE
[Landscape] Bottom URL bar doesn't respect the safe area

### ISSUE THREAD

**Issue by csuciu** [mozilla-mobile/firefox-ios#10116]
v98.0(8219)
iPhone 12 Pro (15.3.1)

1. Move the URL bar to the bottom.
2. Switch orientation to landscape.
3. Check the URL bar.

Expected: The URL bar respects the bottom screen safe area.

Actual:  The URL bar doesn't respect the bottom screen safe area.

Note: Safari shows the URL bar on top of the screen while in landscape mode.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3821)

**Comment by lmarceau** [comment]
Regression from https://github.com/mozilla-mobile/firefox-ios/issues/10095 as well. There's safe area that was put in place for the bottom url bar. Seems it being removed now.

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verifying as fix on main 7493300c088051ed0a06d54dd5e1a6ff21cdd8a3
