### ISSUE TITLE
Bottom URL bar is no longer displayed after swiching orientation

### ISSUE THREAD

**Issue by csuciu** [mozilla-mobile/firefox-ios#10113]
v98.0(8219)
iPhone 12 Pro (15.3.1)

1. Move the URL bar to the bottom.
2. While in portrait tap on the URL to enter edit mode.
3. Switch to landscape.
4. Switch back to portrait.

Expected: The URL bar should be displayed on top of the keyboard.

Actual: The URL bar is not displayed.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3818)

**Comment by lmarceau** [comment]
That's a regression from fixing https://github.com/mozilla-mobile/firefox-ios/issues/10095. Will have a look.

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verifying as fix on main 7493300c088051ed0a06d54dd5e1a6ff21cdd8a3
