### ISSUE TITLE
"Remove from shortcuts" menu action bug

### ISSUE THREAD

**Issue by lmarceau** [mozilla-mobile/firefox-ios#10120]
We should see "remove from shortcuts" action in the menu if the website is pinned. This bug was introduced by refactoring the page action menu to the combined menu.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3827)

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verified fix on main 6b01440f6274573f010b501a7c52de6d19c72bd3
