### ISSUE TITLE
Attentive mode should be dismissed when home page interacted with

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#10134]
## Steps to reproduce
1. Tap the address bar (or open a new tab). Search bar should be focused with keyboard up
2. Scroll the home page
3. Click on any blank space on the home page
### Expected behavior
In both 2 & 3, the address bar should be unfocused and keyboard should disappear, similar to what happens when you click the back arrow
### Actual behavior
Clicking on the home page does nothing. The address bar is still focused and keyboard still visible.
### Device & build information
* Device: iPhone 12 Pro
* Build version: 98.0 (8233)
### Notes
Previously fixed in https://github.com/mozilla-mobile/firefox-ios/issues/7608
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3840)

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verified fix on main 9eea0a004e02ebdce2a6acd4e48b841212aba05b
