### ISSUE TITLE
Bookmarks and history panels have extra lines

### ISSUE THREAD

**Issue by lmarceau** [mozilla-mobile/firefox-ios#10132]
## Steps to reproduce
- Open History or Bookmarks panels

### Expected behavior
- No white line artefact

### Actual behavior
- Bookmarks Menu, Toolbar and Unsorted cells have an extra short white line artefact. Bookmark cell as well.
- Mobile bookmarks cell has a long white line

### Device & build information
* Device: iPhone 11
* Build version: latest main 7c0aa2
### Notes
Attachments: 
![Image from iOS](https://user-images.githubusercontent.com/11338480/156262532-cdc7acf6-c07c-4f11-9289-828dd1fd7cff.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3838)

**Comment by lmarceau** [comment]
@nbhasin2 `bottomSeparatorView` was added for the inactive tabs it seems. Is it really necessary to have this custom separator or can we use the default one? I would like us to have a solution that works in all places as much as possible if behavior is similar.

**Comment by dnarcese** [comment]
dupe of #10144 ?

**Comment by nbhasin2** [comment]
I found the issue, it seems the comment was added but never actually made it hidden by default. We didn't use the default separator and added a custom one to accommodate `separatorInset` for everywhere else and a custom one for the inactive tab. Maybe we need to rethink this 🤔 but for now below are the options we have.

a) An easier change would be to make it hidden by default. 

We make the property hidden by default and mark it visible as part of the inactive tab. 

**Make the following change for the cell** 

https://github.com/mozilla-mobile/firefox-ios/blob/main/Client/Frontend/Widgets/OneLineCellAndFooter.swift#L62-L65

```
        //separator hidden by default
        separatorLine.isHidden = true
```        

**Make it visible for inactive tabs**

https://github.com/mozilla-mobile/firefox-ios/blob/main/Client/Frontend/Browser/Tabs/InactiveTabCell.swift#L132-L134

```
            cell.customization = .inactiveCell
            cell.bottomSeparatorView.isHidden = false
            cell.backgroundColor = .clear
```

b) There are other ways to make it better by having a custom separator with enums but I'll leave it out for this particular change. 

c) You could try subclassing it as well but we only need the change for inactive tab and that might be overkill. 

d) Lastly if you have a good way of using regular separators everywhere and get away with custom ones then I would highly support that and maybe standardize it everywhere.

**Note**: I am leaning towards a) for now with the minimal change and improve it when we end up standardizing separator everywhere in the app. 

cc @finebel let me know if you have any question(s)

**Comment by finebel** [comment]
I will look into option a) later.
