### ISSUE TITLE
Website Shortcut remains selected after tapping on the "search icon"

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#10143]
## Steps to reproduce
1. Tap on a website shortcut from homepage
1. Tap on the "Search icon" before the page loads
    1. Expected behavior

* Website Shortcut should not remain selected
    1. Actual behavior
* Website Shortcut remains selected. After closing the tab or visiting a site the website shortcut no longer remains selected.
    1. Device & build information
* Device: iPhone 12 Pro (15.3.1)
* Build version: 6b01440f6274573f010b501a7c52de6d19c72bd3
    1. Notes
Attachments: 

https://user-images.githubusercontent.com/32130829/156587286-02be8b73-37f6-47f3-bb9f-5c22746aeb3d.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3844)

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verified fix on v99.0 (8530) and main 38e92ba727ff
