### ISSUE TITLE
The deleted items from website data are not immediately cleared

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#10145]
## Steps to reproduce
1.  Go to Settings -> Data management -> Website Data
2. Tap on the search field
3. Type a letter that will display some results (e.g "g")
4. Tap on a result
5. Tap "Clear items" and confirm
### Expected behavior
- The items should be immediately cleared.
### Actual behavior
- The items are not immediately cleared. After the screen is refreshed the items are cleared.
### Device & build information
* Device: iPhone 12 Pro (15.3.1)
* Build version: 6b01440f6274573f010b501a7c52de6d19c72bd3
### Notes
Attachments: 

https://user-images.githubusercontent.com/32130829/156588819-00de63b3-6c54-4d54-b993-4281c14d469d.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3846)

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verifying as fix on main 9ecd93a5be10df8d663feebcd3cce14378a4e551.
