### ISSUE TITLE
[Investigate] - Review non weak delegate variables in code base

### ISSUE THREAD

**Issue by lmarceau** [mozilla-mobile/firefox-ios#10148]
Noticed we have some delegates that aren't marked as weak in the code. This has a potential of creating strong reference cycle. This task is to review those delegates to mark them as weak/and if weak can't be used then make sure there's no leaks by adding proper testing. 

To add tests for leaks in our code, please refer to `trackForMemoryLeaks` function in `TabManagerStoreTests`. This function could be made as an extension to XCTestCase so it's reusable in our different test code.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3848)

**Comment by IpyCreator** [comment]
Hi @Imarceau, can you please guide me on how can I contribute to this Technical debt by working on it.

**Comment by lmarceau** [comment]
List of delegates to review:

- [ ] TabLocationView
- [ ] BottomSheetViewController
- [ ] GroupedTabContainerCell
- [ ] Download
- [ ] DownloadQueue
- [ ] ReaderModeBarView
- [ ] ReaderMode
- [ ] SearchEnginePicker
- [ ] SearchBarSettingsViewModelTests
- [ ] TabManagerTests
- [ ] CredentialWelcomeViewController
- [ ] CredentialPasscodeRequirementViewController

**Comment by lmarceau** [comment]
@IpyCreator I would suggest having a look at https://github.com/mozilla-mobile/firefox-ios/issues/10175, we created it as a first step to tackle the delegation review.

**Comment by data-sync-user** [comment]
➤ Laurie Marceau commented:

Closing since we’ll track in epic https://mozilla-hub.atlassian.net/browse/FXIOS-5902 ( https://mozilla-hub.atlassian.net/browse/FXIOS-5902|smart-link )  instead
