### ISSUE TITLE
Clean up import of SwiftyJSON

### ISSUE THREAD

**Issue by lmarceau** [mozilla-mobile/firefox-ios#10151]
Let's remove imports of SwiftyJSON in files where it's not used. Files with import are listed here: https://github.com/mozilla-mobile/firefox-ios/issues/6885

Example: I think it's not needed in Account > KeyBundle.swift

Once that's done, let's checkmark that in #6885. Then we can create subsequent stories related to removal of SwiftyJSON.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3850)

**Comment by JeremyNW** [comment]
I would like to work on this issue!

**Comment by lmarceau** [comment]
@JeremyNW sounds good! Of you wanna look at it, you can open a PR when it's ready and we'll review
