### ISSUE TITLE
[l10n]"New tab" string should have localization

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#10156]
## Steps to reproduce
1. Change language to DE or other language
2. Launch Firefox
3. Visit a page
4. Open the hamburger menu
### Expected behavior
- "New tab" string should have localization
### Actual behavior
- "New tab" string is not localized 
### Device & build information
* Device: iPhone 12 Pro (15.3.1)
* Build version: main 7493300c088051ed0a06d54dd5e1a6ff21cdd8a3
### Notes
- The string is correctly localized on 98.0 (8233)
Attachments: 

![image](https://user-images.githubusercontent.com/32130829/156768326-21d7ea1f-b143-429d-b0b8-a602198207a6.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3853)

**Comment by dnarcese** [comment]
@SimonBasca can you verify this again

**Comment by SimonBasca** [comment]
@dnarcese This issue is not reproducible on v 99.0 (8654) and v9000 (8950) for French and German but it's still reproducible for Spanish localization.
