### ISSUE TITLE
Bookmarks - Bookmark isn’t disappearing from quick actions after deleting the bookmark

### ISSUE THREAD

**Issue by BigSamSampson** [mozilla-mobile/firefox-ios#10170]
## Steps to reproduce
1. Open the firefox browser.
2. Search “dfsfdsf”.
3. Add the website to the bookmarks.
4. Tap to the bookmarks icon.
5. Delete the bookmark.
6. Exit from the app.
7. Press hold on the app.
### Expected behavior
Bookmark is disappeared from quick actions.
### Actual behavior
Bookmark isn’t disappearing from quick actions menu.
### Device & build information
* Device: Apple iPhone 6S - iOS 15.2
* Build version: firefox daylight 97.0(7635)
### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3866)

**Comment by lmarceau** [comment]
This duplicates https://github.com/mozilla-mobile/firefox-ios/issues/8234 I think
