### ISSUE TITLE
Remove Snapkit from BackForwardList

### ISSUE THREAD

**Issue by lmarceau** [mozilla-mobile/firefox-ios#10173]
- [x] Client/Frontend/Browser/BackForwardListAnimator.swift
- [x] Client/Frontend/Browser/BackForwardListViewController.swift
- [x] Client/Frontend/Browser/BackForwardTableViewCell.swift

Once done please checkmark in https://github.com/mozilla-mobile/firefox-ios/issues/8592

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3869)

**Comment by data-sync-user** [comment]
➤ Laurie Marceau commented:

For QA, Back forward list can be tested to ensure there’s no regressions

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Verified as fixed on FF Daylight 9000 (9505) latest FF build with iPhone 13 Pro Max (15.1.1) and iPad mini 5 (14.7.1).

**Comment by abodea** [comment]
Also, the following:
` Client/Frontend/Browser/BackForwardListAnimator.swift`
 `Client/Frontend/Browser/BackForwardListViewController.swift`
` Client/Frontend/Browser/BackForwardTableViewCell.swift`
are now checked on the general issue.
