### ISSUE TITLE
Scrolling up does not reveal toolbar and tab bar when a Reddit post is opened

### ISSUE THREAD

**Issue by struq** [mozilla-mobile/firefox-ios#10187]
## Steps to reproduce
* Open a Reddit post, for example, https://www.reddit.com/r/firefox/comments/t6wkte/weekly_discussion_for_nightly_builds_for_20220305/
* Scroll down and then scroll up

### Expected behavior
When scrolling down, the toolbar and tab bar is hidden. When scrolling up, the toolbar and tab bar show up again.

Not exactly about the issue but ideally I would also prefer that the toolbar and tab bar can be set to always visible. See #10185 #10114 #6084 #3638 etc

### Actual behavior
When scrolling down, the toolbar and tab bar is hidden. But when scrolling up, the toolbar and tab bar remain hidden. Note that it also doesn't help even by trying to scroll in the parts of the page that are not moving, such as the shaded area on the left and right side, or the header of the page. (screen recording attached)

### Device & build information
* Device: iPad Pro 10.5"
* Build version: Firefox Daylight 98.0 (8233)
### Notes
Attachments: 

https://user-images.githubusercontent.com/2097707/157558547-9f1d5570-5580-4a9b-95a1-1a1378b05275.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3882)

**Comment by SimonBasca** [comment]
@struq thanks for the feedback. Are you using a hardware mouse or track pad to scroll or just the swipe up/down gesture?

**Comment by struq** [comment]
@SimonBasca This is just swiping on the screen. I didn't test a mouse or trackpad.

**Comment by lmarceau** [comment]
@SimonBasca Can you reproduce on your side? On an iPad mini with reddit.com I can't reproduce :( 

@struq When this issue happens, if you scroll down and up again, does the toolbar reappears? I see in the video you scroll up multiple times but not down I think. Just trying to learn more about this.

**Comment by struq** [comment]
@lmarceau No, scrolling down and up again does not make it appear again, neither does tapping the status bar. Clicking the "close" button in the page to go back to the list of posts works. The toolbar also shows up if I go to iOS home screen and then switch back to Firefox again.

I noticed that if I click the link directly it takes me to a different version of the page that does not exhibit this issue (the content of the post and the comments are not in a floating layer over the list of posts like in the recording). Could you maybe try go to https://www.reddit.com/r/firefox/ and then click the title of one of the posts to open it. That way it seems to consistently open the version of the page shown in the recording.

**Comment by lmarceau** [comment]
@struq Thanks I could reproduce it by going to [https://www.reddit.com/r/firefox/](https://www.reddit.com/r/firefox/) and clicking one of the title 👍

**Comment by struq** [comment]
not fixed yet
