### ISSUE TITLE
Tab bar missing after switching to dark mode from control center

### ISSUE THREAD

**Issue by struq** [mozilla-mobile/firefox-ios#10188]
## Steps to reproduce
- While iOS is in light mode, open Firefox
- Switch to dark mode from iOS control center

### Expected behavior
The tab bar should be visible after switching to dark mode.

### Actual behavior
The tab bar is missing. (screen recording attached)

### Device & build information
* Device: iPad Pro 10.5"
* Build version: Firefox Daylight 98.0 (8233)
### Notes
Attachments: 

https://user-images.githubusercontent.com/2097707/157559161-6b2f17d6-3265-47b6-bb20-aeea418f638e.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3883)

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verifying as fix on main 35e7f3d87fd9481abf33b168795379bb608c2019
