### ISSUE TITLE
The order is incorrect after switching to a tab after several tabs were opened in background

### ISSUE THREAD

**Issue by struq** [mozilla-mobile/firefox-ios#10191]
## Steps to reproduce
- Open more than two new tabs in the background by long-pressing links and select "Open in New Tab" in the context menu
- Close the current tab by clicking the cross button, or switch to a newly opened background tab by clicking on that tab

### Expected behavior
The order of the tabs should not change.

### Actual behavior
- When a link is opened in the background, the new tab is positioned right next to the current one. For example, if the tabs are opened in the order 1 2 3 4 5, they will line up in the tab bar as 0 5 4 3 2 1, with 0 being the current tab where links are opened from, i.e. newest tab first.
- After switching to any of the new tabs or just close the order of the tabs in the tab bar suddenly becomes (0) 1 2 3 4 5, i.e. oldest tab first. (screen recording attached)

### Device & build information
* Device: iPad Pro 10.5"
* Build version: Firefox Daylight 98.0 (8233)
### Notes
Attachments: 

https://user-images.githubusercontent.com/2097707/157562728-10b90426-05d0-4cdc-84b9-ca19048cd979.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3886)

**Comment by struq** [comment]
Possibly related issues: #9146

**Comment by SimonBasca** [comment]
Thanks for the feedback @struq. I am simplifying the STR:
1. Open a new tab
2. Long press on a top site shortcut (e.g Facebook)
3. Tap Open in New Tab
4. Long press on a top site shortcut (e.g Wikipedia)
5. Tap Open in New Tab
6. Long press on a top site shortcut (e.g Twitter)
7. Close the first tab, the empty tab

Actual results:
- The order of the tab is 1st tab (Facebook) 2nd tab (Wikipedia) 3rd tab (Twitter)

Expected results: 
- The order of the tab should be 1st tab (Twitter) 2nd tab (Wikipedia) 3rd tab (Facebook)

**Comment by SimonBasca** [comment]
Thanks for the feedback @struq. I am simplifying the STR:

1. Open a new tab
2. Long press on a top site shortcut (e.g Facebook)
3. Tap Open in New Tab
4. Long press on a top site shortcut (e.g Wikipedia)
5. Tap Open in New Tab
6. 7.Long press on a top site shortcut (e.g Twitter)
7. Close the first tab, the empty tab

Actual results:
- The order of the tab is 1st tab (Facebook) 2nd tab (Wikipedia) 3rd tab (Twitter)

Expected results:
- The order of the tab should be 1st tab (Twitter) 2nd tab (Wikipedia) 3rd tab (Facebook)
