### ISSUE TITLE
Toolbar Action menu has an empty space on xcode 13.3

### ISSUE THREAD

**Issue by gutley** [mozilla-mobile/firefox-ios#10194]
## Steps to reproduce
Open up the Toolbar Actions menu on an iPad. Below the "Settings" option there is a white gap that looks like something is missing. On iPhone, the equivalent gap is at the top (since the menu goes from the bottom). (Compare the two screenshots)

### Expected behavior
The overall menu should look symmetrical, without a gap at one end.

### Actual behavior
It just looks 'wrong'

### Device & build information
* Device: iPad mini and iPhone 13
* Build version:98.1 Branch
    1. Notes
Attachments: 
![Simulator Screen Shot - iPad mini (6th generation) - 2022-03-10 at 11 23 54](https://user-images.githubusercontent.com/2040690/157652209-6c4bf887-472c-464a-8217-3dc0386a7075.png)
![Simulator Screen Shot - iPhone 13 - 2022-03-10 at 11 32 32](https://user-images.githubusercontent.com/2040690/157653559-1ac5f647-5715-4734-9aec-87e34dff0497.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3889)

**Comment by gutley** [comment]
@lmarceau Yes  v98.1 56cdb3.

So I've been building and running with Xcode 3.3RC1. If I switch back to 3.2.1 then the issue goes away. Weird. So this is going to be an issue when 3.3 becomes the expected Xcode. Whether you close this now, or leave it as something to investigate as it will bite eventually is up to you.

**Comment by lmarceau** [comment]
@gutley Thanks! We'll keep this open for sure and investigate.

**Comment by lmarceau** [comment]
Tagging PR with fix https://github.com/mozilla-mobile/firefox-ios/pull/10814

**Comment by data-sync-user** [comment]
➤ Raluca Iordan commented:

Note for QA:

Please do check the context menu to see if it looks as expected on iPad, since the fix for this issue was merged in august 2022, just to be sure that everything still looks fine. Thank you!

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Verified as fixed on :Firefox: v112 (29529) with iPhone 13 Pro (15.7.1), and iPhone 14 (:iOS:16.1).
