### ISSUE TITLE
Tab Selection screen can't be intuitively dismissed on iPhone in Landscape

### ISSUE THREAD

**Issue by gutley** [mozilla-mobile/firefox-ios#10197]
## Steps to reproduce

- Create a few Tabs
- Rotate the phone to Landscape
- Open the Tab selection screen.
There is no "Done" button, nor can you pull the screen down to dismiss it (like you can in portrait). As such, the only way to dismiss the screen is to actually select one of the tabs. This is non-intuitive.
### Expected behavior
There should be an obvious way to dismiss the screen without having to actually select a tab
### Actual behavior
You are stuck in the screen until you select a Tab, or rotate the screen back to portrait.
### Device & build information
* Device: iPhone 13
* Build version: 98.1
### Notes
My suggestion would be to have an always-available "Done" button at the in the title bar of the screen.
Attachments: 

https://user-images.githubusercontent.com/2040690/157659187-a9b1fe4a-d3cf-495d-9fb8-e09bcc289e70.mov

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3891)

**Comment by lmarceau** [comment]
Note: This also happens on v97.0, can't swipe away tab tray.
