### ISSUE TITLE
[Iphone] Desktop site is not received using an iOS mobile device on whatsapp.com

### ISSUE THREAD

**Issue by softvision-raul-bucata** [mozilla-mobile/firefox-ios#10192]
## Steps to reproduce
1. Navigate to: https://www.whatsapp.com/.
2. Open the browser's menu.
3. Tap on the "Request Desktop site" option.
4. Observe the result.

### Expected behavior
The desktop version of the page is received, showing the QR code scan option.

### Actual behavior
The mobile version of the page is kept.

### Device & build information
* Device: Iphone 8 running iOS 15.3
* Build version: Firefox Daylight 98.0 (8233)
### Notes

1. Reproducible regardless of the status of ETP.
2. Reproducible on the latest build of Firefox Nightly.
3. Works as expected using Chrome.

Attachments: 

![whatsapp](https://user-images.githubusercontent.com/75027050/157478171-436f634f-c24f-482b-bcfb-8162b25d903f.gif)

The issue is still reproducible on mobile devices but works as expected on tablet devices

`tablet:`
![image_2022_03_09T16_16_41_884Z](https://user-images.githubusercontent.com/75027050/157483359-d78cef01-f6dd-4da2-b2d6-26a98771f84d.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3887)

**Comment by topotropic** [comment]
I could reproduce this with other sites as well – maybe it's a bigger issue cc @dnarcese
