### ISSUE TITLE
Keyboard suggestions are showing on top of URL bar when swiping to type

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#10202]
## Steps to reproduce
1. Move URL bar to bottom
2. Swipe to type on the URL bar
### Expected behavior
- URL bar should be displayed correctly
### Actual behavior
- Keyboard suggestions are showing on top of search bar
### Device & build information
* Device: iPhone 12 Pro 15.3.1
* Build version: 98.0 (8233) and main 9ecd93a5be10df8d663feebcd3cce14378a4e551
### Notes
Attachments: 

https://user-images.githubusercontent.com/32130829/157871402-a347a969-31d3-4e87-8e2b-3eeaaaefd24f.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3894)

**Comment by gutley** [comment]
I saw this too - But I can do the same thing in Safari so not sure there's much to do (apart from bug report to Apple)

**Comment by gutley** [comment]
A similar thing happens if you bring up the emoji keyboard. It seems the address bar isn't responding to keyboard layout changes and moving accordingly

**Comment by gutley** [comment]
BTW - One thing that menu doesn't do while scrolling is the normal 'over bounce' effect that other scrollable areas have when hitting the top or bottom. Certainly not a showstopper, but it makes it feel a bit 'wrong'. Not worth delaying anything for unless its a simple fix.

**Comment by SimonBasca** [comment]
Confirming that this issue is not reproducible on v98.1 (8367) and main 16a96c7e6e51
