### ISSUE TITLE
On iPads with hardware keyboards, support arrow keys to navigate search suggestions from address bar

### ISSUE THREAD

**Issue by gutley** [mozilla-mobile/firefox-ios#10205]
### User Problem
> With a hardware keyboard its possible to focus the address bar (Cmd-L) and start typing a search term, but in order to actually select one of the suggestions you have to touch the screen. If there are recent items or bookmarked items in the list then the arrow keys do let you navigate to them, but not for actual search suggestions. This is inconsistent with desktop browsers and Safari on iPad, where you can navigate the suggestions with the arrow keys (See recording from simulator with keyboard viewer showing))

### Ideas for Solution
> Basically implement it like Safari does, where up and down arrow move you up and down through all the suggestions, not just recent items and bookmarks

https://user-images.githubusercontent.com/2040690/157908369-7bff5ac2-b888-4b38-839d-14abca337fcb.mov

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3897)

**Comment by lmarceau** [comment]
This is more of a bug I think, relates to https://github.com/mozilla-mobile/firefox-ios/issues/8786

**Comment by data-sync-user** [comment]
➤ Matt Reagan commented:

This sounds like the same issue as https://mozilla-hub.atlassian.net/browse/FXIOS-2920 ( https://mozilla-hub.atlassian.net/browse/FXIOS-2920|smart-link ) , going to close as a Duplicate.
