### ISSUE TITLE
Filtered Website Data Fails to Clear

### ISSUE THREAD

**Issue by kelvins64** [mozilla-mobile/firefox-ios#10209]
## Steps to reproduce
Settings --> Data Management --> Website Data
Type a query in the filter search bar.
Select a website.
Press "Clear Items".

Selected items fail to clear, and selected items are not highlighted with checkmarks. 
Note that items are cleared successfully if search filters are not applied.

### Expected behavior
Selected items are removed (and are properly checked).

### Actual behavior
Selected items are not properly checked and fail to clear.

### Device & build information
* Device: iPhone 12 iOS 15.3.1
* Build version: Firefox Version 98.0
### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3898)

**Comment by finebel** [comment]
I think this bug is already tracked (see #10145).

**Comment by kelvins64** [comment]
Thanks, it does look like that's the case. Closing this issue.
