### ISSUE TITLE
"Remove Bookmark" still showing up in previous menu location

### ISSUE THREAD

**Issue by topotropic** [mozilla-mobile/firefox-ios#10214]
## Steps to reproduce
1. Add a site to your shortcuts
2. Add the same site to bookmarks

### Expected behavior
- remove option next to bookmarks
- remove shortcuts option in menu

### Actual behavior
- instead of "Remove Shortcut" it says "Remove bookmark" in the menu

<img width="375" alt="IMG_EC7A1F0BE70E-1" src="https://user-images.githubusercontent.com/353960/158140411-1ee89580-07cd-43b0-ac2b-437e3a4a46cd.png">

### Device & build information
* Device: iPhone 8, 15.3.1
* Build version: Firefox 98 (8233)
### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3900)

**Comment by SimonBasca** [comment]
Confirming that this issue is fixed on v98.1 (8367) through https://github.com/mozilla-mobile/firefox-ios/issues/10120.
@topotropic feel free to re-open if this is still an issue on your side.
