### ISSUE TITLE
[Investigation] - Review if Codable can replace NSCoding in TabGroupData and SavedData

### ISSUE THREAD

**Issue by yoanarios** [mozilla-mobile/firefox-ios#10235]
Investigate if is possible to replace NSCoding conformance from TabGroupData and SavedData with Codable

* Replace Codable from TabGroupData
* Replace Codable from SavedData
* Remove unnecessary code after conforming to Codable

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3921)

**Comment by lmarceau** [comment]
Closing since testing will be part of https://github.com/mozilla-mobile/firefox-ios/issues/9770
