### ISSUE TITLE
Can't scroll hamburger menu in landscape orientation

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/firefox-ios#10246]
## Steps to reproduce

1. Rotate your iPhone to landscape orientation.
2. Tap the hamburger menu button.
3. Try to scroll the opened hamburger menu.

### Expected behavior

I should be able to scroll the hamburger menu to select any of the menu items.

### Actual behavior

The hamburger menu only scrolls a little bit, revealing only the "New Tab" through "Find in Page" menu items. See the screenshot below.

### Device & build information

* Device: iPhone 12 running iOS 15.4
* Build version: Firefox iOS v98.0 (8233) TestFlight

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3930)

**Comment by cpeterso** [comment]
![7AB56ACB-B4F9-466B-A1E5-CE7CA3FEF2E5](https://user-images.githubusercontent.com/629193/158703417-e28153d3-4d87-4e92-a481-78d1b104c93e.png)

**Comment by csuciu** [comment]
@cpeterso This issue is fixed in the latest release (v98.1). Please see [#10196](https://github.com/mozilla-mobile/firefox-ios/issues/10196)
