### ISSUE TITLE
Keyboard opens on tab close

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/firefox-ios#10247]
## Steps to reproduce
Open the tab view and close a tab.
### Expected behavior
Do not show the keyboard.
### Actual behavior
Shows the keyboard preventing access to the lower buttons.
### Device & build information
* Device: iPhone 11
* Build version: 98.1
### Notes
Attachments: ![image](https://user-images.githubusercontent.com/67353333/158740413-b091b25a-6524-4e48-b522-8f05db8c3a2d.jpeg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3931)

**Comment by finebel** [comment]
Note: For me this behaviour is only reproducible if the previous tab (which gets selected after you deleted the tab) is a blank / empty tab.

**Comment by junbio** [comment]
Same root cause as #8982 I think.
