### ISSUE TITLE
 Closing tabs is slow

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#10240]
Steps to reproduce:

About a month there has been such problem at least it did not exist in 2021. Use Firefox version 40+ in IOS device for a week. Keep like 10 tabs open. Try to press cross to close a tab in tab list view.

Actual results:

You will feel delay about a second during touching screen and tab actually closing.

Expected results:

Tab should have closed as soon as I have lifted my finger from cross (close button).
When I close all tabs and close (end process) Firefox, for a while it works faster.

Via : https://bugzilla.mozilla.org/show_bug.cgi?id=1752513

Device: iPhone X
iOS: 15.3.1
Memory: 23,7/256 GB

[Jira issue](https://mozilla-hub.atlassian.net/browse/FXIOS-3926)

**Comment by SimonBasca** [comment]
Also reproducible on v99.0 (8615). I also experienced a crash while testing this. Note that the app was frozen until the tab selector switched to previous one and ultimately it crashed.

https://user-images.githubusercontent.com/32130829/160618497-0b031a5f-1565-4159-a49a-8fcba487128d.mp4

**Comment by data-sync-user** [comment]
➤ Ashley Thomas commented:

This is being investigated as part of https://mozilla-hub.atlassian.net/browse/FXIOS-3953 ( https://mozilla-hub.atlassian.net/browse/FXIOS-3953|smart-link )

**Comment by SimonBasca** [comment]
Marking as verified fix as part of https://mozilla-hub.atlassian.net/browse/FXIOS-3953. Also note that no crash was encountered during testing.
