### ISSUE TITLE
[L10n] `Sign in to Sync` string is not translated

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/firefox-ios#10255]
For example for French, even though the string is translated in pontoon and has been completed for a few weeks now, it still appears in English. 
Pontoon: https://pontoon.mozilla.org/fr/firefox-for-ios/firefox-ios.xliff/?search=sign+into+sync&string=242813
Code (I think this is the one): https://github.com/mozilla-mobile/firefox-ios/blob/f2f79a11c84400c5ca0deb65cb2e9374a6046bba/Shared/fr.lproj/Localizable.strings#L518
Screenshot (from main: da28cf2bc741fe9907090707a5c1a099d19d9f63):
<img width="414" alt="iPhone 11-MenuOnWebPage-03" src="https://user-images.githubusercontent.com/1897507/158981379-cb2e2d38-53a1-4c98-96be-570231ae88d9.png">

Same for Spanish, the string appears in English.

Could it be an error with that string, or a missing import? not sure but there might be an issue here.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3940)

**Comment by lmarceau** [comment]
@isabelrios We still need to do the string import for v99! This will be done monday and it should be good afterwards on the `main` branch.

**Comment by isabelrios** [comment]
oh sorry not sure the timing for that and opened the issue, cc @Delphine

**Comment by lmarceau** [comment]
I think this can be done after we do the v99 string freeze import on Monday 🤔 
cc: @dnarcese

**Comment by Delphine** [comment]
Thank you so much!

**Comment by isabelrios** [comment]
@lmarceau I was trying to run the import locally following the steps here: https://github.com/mozilla-mobile/firefox-ios/issues/10255 since I would like to automate that import process as we have it focus (https://github.com/mozilla-mobile/focus-ios/pull/3127) but even though I see the logs and that something is happening, when the process finishes, git diff does not return anything. 
I have Xcode named without spaces, as I see the comment about that causing issues.
I might ping you about this later today :)

**Comment by lmarceau** [comment]
@isabelrios String import was merged on `main`, I think this should be ok now!

**Comment by isabelrios** [comment]
I'm afraid that the string is still not translated:
<img width="628" alt="Captura de pantalla 2022-03-22 a las 11 16 38" src="https://user-images.githubusercontent.com/1897507/159458442-c180f704-e5e0-4d59-8ab8-a4252bf54ff8.png">

In addition to that we also have these ones in English:
-Help
-Customize Homepage

Which are in English

**Comment by isabelrios** [comment]
oh looks like those are not translated in pontoon yet at least for Spanish
![Captura de pantalla 2022-03-22 a las 16 16 48](https://user-images.githubusercontent.com/1897507/159516577-b296ac25-41bc-4a78-8b64-f986a020dc25.png)

**Comment by isabelrios** [comment]
In Frech this is correctly shown:
![Captura de pantalla 2022-03-22 a las 16 25 02](https://user-images.githubusercontent.com/1897507/159517739-8bf63649-8c0e-41ac-9678-70563edd328c.png)

Not sure if we can close the issue or wait until we have that string translated and imported for this or next release...cc @Delphine @dnarcese

**Comment by Delphine** [comment]
I think this issue can be closed for now.
@isabelrios: Should we open another issue to figure out how to get strings into screenshots, before they are merged into beta?
Or should we change the screenshots schedule so that l10n testing happens once strings are merged into Beta, and throughout the beta period?
@lmarceau : how often do you import latest strings back into Beta, before the release? If it's not already the case, it would make sense to do it a few times before release so localizers can check their strings - as well as their fixes to strings - against updated screenshots, during the beta cycle. LMK! :)

**Comment by isabelrios** [comment]
@Delphine I will open another issue to track the work to have the strings automatically imported into main, similar flow to the one we have on Focus-iOS and similar android projects.
