### ISSUE TITLE
When the address bar is set to bottom, scrolling down the page doesn't react immediately

### ISSUE THREAD

**Issue by ozeidan** [mozilla-mobile/firefox-ios#10268]
## Steps to reproduce
Configure the address bar to show on the bottom of the screen. Scroll down on a page (normally, by moving the page up with one finger).

### Expected behavior
The page should start moving immediately. After some scrolled distance, the address bar should hide.

### Actual behavior
The page only moves up after one has scrolled enough to fully hide the address bar. This delay is a bit annoying.

### Device & build information
* Device: iPhone 12 mini
* Build version: 8367
### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3945)

**Comment by lmarceau** [comment]
Thanks a lot for the feedback!

I tested and could reproduce, here's a video of the described issue. I scrolled at first slowly, then I scrolled fast to see the difference. So if you're a user wanting to scroll slow you would see this for sure.

https://user-images.githubusercontent.com/11338480/159276166-85196842-51bc-4131-aaee-0aedd0084ec9.MP4

**Comment by pashynskykh** [comment]
Any updates on this? It's already 5 months since this bug was reported.

**Comment by struq** [comment]
Not fixed yet in v115.0

**Comment by pashynskykh** [comment]
Yep, this bug is still not fixed. Can't imagine why it's still getting ignored, because it's very annoying. This bug is one of the reasons I've stopped using FF on mobile.

**Comment by pashynskykh** [comment]
Looks like this bug was fixed with v106.3 (33647)! Can anyone confirm this?

**Comment by ozeidan** [comment]
Yes it's fixed for me too
