### ISSUE TITLE
Firefox Crashes when clearing recent history -> Everything

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#10281]
## Steps to reproduce
1. Visit a page
2. Go to History Panel 
3. Tap "Clear Recent History"
4. Tap "Everything" 
### Expected behavior
- History should be cleared.
### Actual behavior
- Firefox Crashes
### Device & build information
* Device: iPad Pro (15.2)
* Build version: 38e92ba727ff74
### Notes
Attachments:

[Client-2022-03-22-140913.ips.zip](https://github.com/mozilla-mobile/firefox-ios/files/8324282/Client-2022-03-22-140913.ips.zip)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3950)

**Comment by lmarceau** [comment]
This is also on v99.0
cc: @dnarcese

**Comment by lmarceau** [comment]
It fails in HistoryPanelV2

![Screen Shot 2022-03-22 at 2 11 51 PM](https://user-images.githubusercontent.com/11338480/159547828-de7f165d-b8f0-4c64-bc1a-542fb5e22b88.png)

**Comment by data-sync-user** [comment]
➤ Laurie Marceau commented:

Simion Basca Were you on a Fennec developer build? From what I saw it should only happen on there, but want to confirm (so shouldn’t happen on Testflight or anywhere else).

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Laurie Marceau yes, the issue was reproduced on Fennec local build main branch 38e92ba727ff74. It was not reproduced on the TestFlight v99.0.

**Comment by data-sync-user** [comment]
➤ Catalin Suciu commented:

Confirming that the crash does not occur after disabling the  “search term groups“ feature. Will leave the github issue open until a proper fix lands.
