### ISSUE TITLE
The shortcut is removed after closing the tab.

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#10283]
## Steps to reproduce
1. Long press on a Top Site shortcut
2. Tap "Remove"
### Expected behavior
- The shortcut should be immediately removed.
### Actual behavior
- The shortcut is removed after closing the tab.
### Device & build information
* Device: iPhone 13 mini (15.3)
* Build version: 99.0 (8530)
### Notes
Attachments: 

https://user-images.githubusercontent.com/32130829/159512327-f3fc1295-14df-4d20-8bb5-b62b06524d46.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3952)

**Comment by SimonBasca** [comment]
Note: 
- Also reproducible when removing a pinned shortcut.

**Comment by check4ismail** [comment]
Hey @SimonBasca ,

I installed Mozilla Firebox latest version for iOS (99.6) - it seems the issue has been addressed with top sites being removed instantly after tapping on Delete. Feel free to confirm on your end if that's the case!

**Comment by lmarceau** [comment]
@SimonBasca This was fixed with https://github.com/mozilla-mobile/firefox-ios/issues/10278, on latest `main` and v99 #8544 this should be good.

**Comment by SimonBasca** [comment]
Confirming that this is fixed on latest main cd20fc4afd933
