### ISSUE TITLE
Firefox downloading DMS file, not connecting to website

### ISSUE THREAD

**Issue by imnotabr** [mozilla-mobile/firefox-ios#10288]
I'm using an older version of Firefox iOS.

When I try to visit https://conspiracies.win, the browser won't connect and instead it is downloading a DMS file conspiracies.win.dms.

Is this a Firefox issue or is this related to conspiraces.win?

Attached is photo of the problem:

![Firefox dms](https://user-images.githubusercontent.com/62814903/159579420-e6e103cf-09dd-4589-a0c4-d1930bc9ebcb.jpg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3956)

**Comment by lmarceau** [comment]
Can you specify which Firefox iOS version that is? Can't reproduce on my device with latest version.

**Comment by imnotabr** [comment]
Firefox iOS version 38 I believe.

**Comment by SimonBasca** [comment]
@imnotabr you could also try downloading the file in Safari to check if it's a site issue or a Firefox issue. Let us know if it's working in Safari.

**Comment by imnotabr** [comment]
Hi @SimonBasca 

I'm not trying to download a file, I'm trying to connect to the website https://www.conspiracies.win (yes the extension is .win not .com). Instead of connecting to the website, in this version of Firefox, it tries to download a file conspiraces.win.dms. In Safari there is no problem

**Comment by lmarceau** [comment]
@imnotabr Could you upgrade to latest version of Firefox iOS to see if you still have the issue there?

**Comment by imnotabr** [comment]
@lmarceau it works fine, but I'm trying to figure out how to fix it in this older version. Anyone have an idea as to the source of the problem?

**Comment by lmarceau** [comment]
Well, to fix the older version it would require a code update most probably, hence an update of version. So solution in this case is really just to use latest version?

**Comment by imnotabr** [comment]
@Imarceau I want to fix the version I have, I will change the code myself just need to know where the problem is coming from, if anybody knows

**Comment by imnotabr** [comment]
It looks like updating iOS 15.4 fixed the problem
