### ISSUE TITLE
History is not correctly cleared after "clearing recent history"

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#10282]
## Steps to reproduce
1. Visit a page
2. Close the tab
3. Go to History
4. Tap "Clear recent history"
5. Tap "Today"
6. Tap on the Bookmark panel
7. Tap on the History pane
### Expected behavior
- History should be cleared.
### Actual behavior
- History is not cleared.
### Device & build information
* Device: iPhone 13 Mini (15.3)
* Build version: 38e92ba727ff7
### Notes
Attachments: 

https://user-images.githubusercontent.com/32130829/159487687-bad71d8d-b927-487f-8485-96976e5d9160.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3951)

**Comment by lmarceau** [comment]
Seems to relate to https://github.com/mozilla-mobile/firefox-ios/issues/9624

**Comment by SimonBasca** [comment]
Verifying as fix on 9000(9248).
