### ISSUE TITLE
"Jump back in" and "Recently saved" sections are not displayed.

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#10296]
## Steps to reproduce
1. Launch Firefox 99.0 (8544)
2. Visit a webpage or bookmark a page
3. Open a new tab
### Expected behavior
- "Jump back in" and "Recently saved" section should be displayed.
### Actual behavior
- "Jump back in" and "Recently saved" section is not displayed.
### Device & build information
* Device: iPhone 13 mini (15.1) and iPad Pro 12(5.3.1)
* Build version: 99.0 (8544)
### Notes
- Not reproducible on v98.2 release
- Also reproducible on v99.0 (8516)
- The user seems to be enrolled correctly in the experiment group

![image](https://user-images.githubusercontent.com/32130829/159927103-3a7f1b8d-487d-42a7-a363-babac4564857.png)

Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3970)

**Comment by data-sync-user** [comment]
➤ Daniela Arcese commented:

Simion Basca Is this happening on Beta?

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Daniela Arcese Confirming that this issue is also reproducible on v99.0 (8544) Beta.

**Comment by data-sync-user** [comment]
➤ Roux Buciu commented:

Simion Basca This should be tested on beta/release for Nimbus fixes, and not nightly. This issue is…. weird.

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Roux Buciu I am still reproducing this issue on Test Flight version 99.0 (8615) on both the beta and the release channel. 
After clean install, going to the experiments will display this screen

!image-20220329-092913.png|width=563,height=1218!

After resetting the experiments and restarting the device I am seeing the correct experiments screen but the “Jump back in“ and “Recently saved“ sections are still not displayed after visiting a page or bookmarking a page.

!image-20220329-093003.png|width=473,height=1024!

**Comment by data-sync-user** [comment]
➤ Roux Buciu commented:

OK progress is being made in baby steps. Synced up with jhugman and we think we’ve ferreted out where the problem is happening. But haven’t figured out why.

It seems that the _variables in FxNimbus.HomescreenSection are getting returned as NilVariables, which they shouldn’t be. Investigating that from both AS side and the app side. Will update when we have more details.

**Comment by data-sync-user** [comment]
➤ Roux Buciu commented:

In digging on this issue, found other bugs with this, but have fixed those.
No further updates on the underlying cause of this - still investigating.
Have presented Daniela with some solutions for this to unblock `v99`

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verified fix on v99.0 (8654). The “Jump back in” and “Recently Saved” section are correctly displayed and are working as expected.
