### ISSUE TITLE
Remove Snapkit from HistoryPanel

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#10305]
* \[ ] Client/Frontend/Library/HistoryPanel.swift

Once done please checkmark in [https://github.com/mozilla-mobile/firefox-ios/issues/8592](https://github.com/mozilla-mobile/firefox-ios/issues/8592)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3979)

**Comment by lmarceau** [comment]
Closed since done with new history panel (currently called HistoryPanelWithGroups)
