### ISSUE TITLE
SUMO page is missing for login& passwords screen

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#10300]
## Steps to reproduce
1. Disable biometrics to unlock the device
2. Go to Login&Passwords screen
3. Tap on "Learn more"
### Expected behavior
- SUMO page should be displayed
### Actual behavior
- SUMO page is missing for login& passwords screen
### Device & build information
* Device: iPhone 13 mini
* Build version: 99.0 (8544)
### Notes
Attachments: 

![image](https://user-images.githubusercontent.com/32130829/160105240-4304cd4b-a032-4b06-9ce5-c211fadb8f31.png)

![image](https://user-images.githubusercontent.com/32130829/160105326-ddc5f19d-8779-4879-9121-35ce0a6a38e0.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3973)

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verified fix on 9000. (8716)
