### ISSUE TITLE
[Crash] Firefox crashes after steps when "Close Private Tabs" switch is enabled

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#10302]
## Steps to reproduce
1. Go to settings and enable "Close  Private Tabs when leaving private browsing"
1. Long press on tab counter -> Tap Private Browsing
1. Long press on tab counter -> Tap Normal Browsing
1. Tap on Tab Counter 
1. Tap on mask icon
1. Tap the "+" button to open a new private tab
### Expected behavior

* Firefox crashes
### Actual behavior
* Firefox should not crash and a new private tab should be open
### Device & build information
* Device: iPhone 13 mini (15.1)
* Build version: 99.0 (8544)
### Notes
* Only reproducible with "Close  Private Tabs when leaving private browsing" enabled
Attachments: 
[Client-2022-03-25-135432.ips.zip](https://github.com/mozilla-mobile/firefox-ios/files/8350300/Client-2022-03-25-135432.ips.zip)

https://user-images.githubusercontent.com/32130829/160117600-38f3b7e1-da71-412c-801b-beb74cb6ee06.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3976)

**Comment by lmarceau** [comment]
@SimonBasca I think this is the wrong video, I don't see the crash in action 🤔

**Comment by lmarceau** [comment]
This crash happens in v98 as well

**Comment by alinanico** [comment]
I was able to reproduce this issue using Firefox 110.2 (29283), iPhone 14 Plus (16.0.3) 

https://user-images.githubusercontent.com/125877504/223135199-1bdba6ae-5e49-4188-bf9b-b0abc87a43c6.MOV

**Comment by lmarceau** [comment]
I think this could relate to https://github.com/mozilla-mobile/firefox-ios/issues/12871 possible due to performChainedOperations crash
