### ISSUE TITLE
Autofill login screen is not populated

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#10303]
## Steps to reproduce
1. Enable Autofill passwords
2. Visit a login form and tap on the login field
3. Tap on the "Passwords" button 
### Expected behavior
- The login screen should be populated.
### Actual behavior
- The login screen is not populated.
### Device & build information
* Device: iPhone 12 Pro (15.4)
* Build version: 99.0 (8544)
### Notes
Attachments: 

https://user-images.githubusercontent.com/32130829/160120341-37703e0d-3e51-454e-9f81-ad8617b65c48.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3977)

**Comment by nbhasin2** [comment]
@SimonBasca is this working on v98.2?

**Comment by csuciu** [comment]
This issue no longer reproduces on v9000 (8591). Verifying as fixed on Beta.
