### ISSUE TITLE
[Top Sites][V99] Some of the icons in the homepage top sites are incorrectly displayed

### ISSUE THREAD

**Issue by csuciu** [mozilla-mobile/firefox-ios#10311]
v99.0 (8544)
iPhone 12 Pro (15.3.1)

1. Switch to dark mode.
2. Check the homepage default top sites.

Results: The amazon and wikipedia icons are darker than the others.

![Skype_Picture_2022_03_25T18_20_36_410Z](https://user-images.githubusercontent.com/1866605/160180561-30daa3fa-6672-4327-9673-90ecd5ffc725.png)

Note: Not reproducible on v98.2.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3992)

**Comment by lmarceau** [comment]
I think they are all the same. I added a square with the color of the top sites and it looks to be ok 🤔

![Screen Shot 2022-03-25 at 2 43 26 PM](https://user-images.githubusercontent.com/11338480/160182453-70d23977-fe70-4580-aeb2-b9ab81e3b98d.png)

**Comment by csuciu** [comment]
@lmarceau I'm talking about the actual icons, not the background. Please check the differences between v98 and v99 in this screenshot.
<img width="981" alt="Screenshot 2022-03-25 at 20 51 16" src="https://user-images.githubusercontent.com/1866605/160185119-f2ae83e3-a43f-477b-82b0-0a796116f54d.png">

**Comment by lmarceau** [comment]
This could be made part of https://mozilla-hub.atlassian.net/browse/FXIOS-3833

**Comment by lmarceau** [comment]
An attempt to fix this issue was made in the tagged PRs, but it introduced some issues (UI tests pending, meaning there was an underlying problem). The work will be on the ice for now.

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Laurie Marceau should we move this issue to “Open” since there it was not fixed?

**Comment by data-sync-user** [comment]
➤ Laurie Marceau commented:

Simion Basca Sorry I should’ve commented again on the issue. There was a PR opened to revert the initial change, so this bug should be fixed now. It should be testable on latest Nightly

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Thanks for clarifying Laurie. Marking as verified fix on main d52210f542ed63051219b687d322654564b4bf31.
