### ISSUE TITLE
Light mode on unlocking device when system mode set to dark

### ISSUE THREAD

**Issue by pietro1704** [mozilla-mobile/firefox-ios#10328]
## Steps to reproduce
Using dark mode on system and Firefox on foreground, lock the device. On unlock, Firefox is on light mode

### Expected behavior
Firefox should be on dark mode, according to system

### Actual behavior
Firefox is on light mode

### Device & build information
* Device: iPhone XR , iOS 15.4
* Build version: Firefox Daylight 98.2 (8475)
    1. Notes
Attachments:
![IMG](https://user-images.githubusercontent.com/45739756/160847217-b7b4e16e-7505-45a8-bcaa-eb615b27820a.jpeg)UNITO-UNDERSCORE!1FA146DE6D72-1!

https://user-images.githubusercontent.com/45739756/160846842-6dbae692-735e-4a7a-a4ce-1b79f5fc5731.MOV

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4002)

**Comment by lmarceau** [comment]
I can't reproduce @SimonBasca do you know more about this?
@pietro1704 which OS version do you have?

**Comment by pietro1704** [comment]
iOS 15.4

**Comment by SimonBasca** [comment]
@lmarceau I am also unable to reproduce this issue on iPhone 12 Pro (15.4).
@pietro1704 could you please add a video of the issue? Also a screenshot of the iOS Display settings and Firefox theme setting would be helpful. Thanks

**Comment by pietro1704** [comment]
I updated the issue description with a video and screenshot of the device's display settings

**Comment by piofusco** [comment]
Not sure if you meant to tag me, but here's what I see when I disable "Use System Light/Dark mode."

![image](https://user-images.githubusercontent.com/6620352/160906235-d1154e76-adeb-4089-8e94-8e2b393c496b.png)

**Comment by lmarceau** [comment]
Ah! I'm sorry it autocompleted to your username and I totally meant @pietro1704 😓 Sorry again to have bothered you!
