### ISSUE TITLE
Intermittent crash when pressing on "Close all tabs" icon in tabs tray

### ISSUE THREAD

**Issue by csuciu** [mozilla-mobile/firefox-ios#10333]
v99.0 (8614)
iPhone 12 Pro 15.3.1

I ran into this crash two times after pressing on the trashcan icon in tabs tray. I had under 10 tabs open when this happened.

I have no other info at this point. We'll try to find precise steps.
[Client-2022-03-29-173615.ips.zip](https://github.com/mozilla-mobile/firefox-ios/files/8372633/Client-2022-03-29-173615.ips.zip)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4006)

**Comment by SimonBasca** [comment]
Might be related to https://mozilla-hub.atlassian.net/browse/FXIOS-3953

**Comment by lmarceau** [comment]
Does this still happen @csuciu @SimonBasca ?

**Comment by csuciu** [comment]
I'm no longer able to reproduce this crash on latest v104.0 or main builds.
