### ISSUE TITLE
Password Autofill has to be run twice inside govt app

### ISSUE THREAD

**Issue by thisisnotmyrealname** [mozilla-mobile/firefox-ios#10346]
## Steps to reproduce
Open "MyAlbertaDigital ID" app
Touch username
click passwords prompt on top of keyboard
select desired L/P combo for this app.
App will accept input, and indicate credentials have been entered, but if you hit submit app will error with "required fields cannot be left blank."
Password entry field  goes blank
If you then touch in the password entry field, then touch the passwords prompt above the keyboard, and select the same credentials again, it will fill the password field a second time, and then you will be able to log in.

### Expected behavior
Only have to select the password to auto-fill once.

### Actual behavior
Have to select which credentials to use twice

### Device & build information
* Device: Apple iPhone 12 iOS 15.3.1
* Build version: Firefox Daylight 98.2 (8475)
### Notes
This "app" is basically just a wrapper around a website. Not sure who to complain to about the issue.
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4015)

**Comment by SimonBasca** [comment]
@thisisnotmyrealname Could  you try auto filling with Keychain and let me know if the issue is still reproducible?
