### ISSUE TITLE
Warning: linking against a dylib which is not safe for use in application extensions part 1 

### ISSUE THREAD

**Issue by lmarceau** [mozilla-mobile/firefox-ios#10342]
Investigate if this warning needs to be fixed and relevant. If it's not relevant can we find a way to remove it so this doesn't pollute our buildtime warnings navigator?

![Screen Shot 2022-03-29 at 5 08 55 PM](https://user-images.githubusercontent.com/11338480/160707567-ab62fdbe-74c8-4d7c-b860-f5281bb839ae.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4013)

**Comment by data-sync-user** [comment]
➤ Laurie Marceau commented:

For QA, we can test to ensure sync (syncing tabs) works properly, as well as some exploratory testing. Not to be tested for v101.

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verifying as fix on v9000 (9738). Sync and syncing tabs work as expected.
