### ISSUE TITLE
The quick action search engine are not displayed.

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#10349]
## Steps to reproduce
1. Open Fennec
2. Type something in the URL bar 
### Expected behavior
- The quick action search engine should be displayed.

![image](https://user-images.githubusercontent.com/32130829/160784049-a3f23ece-00a9-462a-b640-1c4cb0b84540.png)

### Actual behavior
- The quick action search engine are not displayed.

![image](https://user-images.githubusercontent.com/32130829/160784263-f55383eb-ac87-4c5c-8563-b8f781c0b672.png)

### Device & build information
* Device: iPhone 13 mini (15.3)
* Build version: main 500f6c95f86
### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4017)

**Comment by isabelrios** [comment]
Please note that this happened recently and was fix https://github.com/mozilla-mobile/firefox-ios/issues/9084. Also in case that helps with the solution.

**Comment by lmarceau** [comment]
Had a quick look, not sure what broke this but there's content size issues on `ButtonScrollView`, and it's height is of 0. Solving this will probably solve that it's not appearing.

<img width="410" alt="Screen Shot 2022-04-01 at 3 21 53 PM" src="https://user-images.githubusercontent.com/11338480/161328265-25914a9c-9426-4533-b597-fa57f29abe21.png">

**Comment by csuciu** [comment]
(fixed in https://github.com/mozilla-mobile/firefox-ios/commit/3dae8a0e3751d613c13d391c08fb9d0f59839ad9) 
This issue is no longer reproducible on v100.1 (9330). Verifying as as fixed.
