### ISSUE TITLE
Adjust separator width from 0.5 to 1/3 on phones with @3x scale

### ISSUE THREAD

**Issue by junbio** [mozilla-mobile/firefox-ios#10365]
On phones like the iPhone 6S/7/8 Plus/X/XS/11 Pro and 12 and 13 series, the display scale is 3x and the separator width is 1/3 accordingly. The border width used is 0.5 however, which is incorrect and would cause the layout to not be pixel perfect.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4030)

**Comment by lmarceau** [comment]
@junbio Which separator is this referring to?

**Comment by junbio** [comment]
I was investigating #10361 which is the PhotonActionSheet but there's a few locations with a hardcoded 0.5 border width.
