### ISSUE TITLE
Inactive tabs, add description to settings

### ISSUE THREAD

**Issue by topotropic** [mozilla-mobile/firefox-ios#10368]
Add a descriptive text to inactive tabs in settings. 

> Tabs you haven’t viewed for two weeks get moved to the inactive section.

<img width="642" alt="image" src="https://user-images.githubusercontent.com/353960/161146184-593b9ce6-daf1-425b-b926-4c909e6c12cb.png">
https://www.figma.com/file/am9EJGg6ow29PXWkc9jcOH/MR2-(2021)?node-id=2156%3A35691

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4033)

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verified fix on main 9eea0a004e02ebdce2a6acd4e48b841212aba05b
