### ISSUE TITLE
Beta v9000 is crashing at startup on iOS 14

### ISSUE THREAD

**Issue by csuciu** [mozilla-mobile/firefox-ios#10373]
v9000 (8693)
iPhone 14.2
iPad 14.0.1

Install Beta v9000 and try to open it.

Result: The app is crashing at startup.
[Client-2022-04-01-143227.ips.beta.zip](https://github.com/mozilla-mobile/firefox-ios/files/8397479/Client-2022-04-01-143227.ips.beta.zip)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4035)

**Comment by dnarcese** [comment]
@csuciu Is this still happening on newer 9000 builds?

**Comment by lmarceau** [comment]
I'll close this, please feel free to reopen if this shouldn't be closed.
