### ISSUE TITLE
values arent shown correctly

### ISSUE THREAD

**Issue by Niharsonu** [mozilla-mobile/firefox-ios#10378]
### Device & build information
* Device: ?
* Build version: ?
### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4038)

**Comment by lmarceau** [comment]
@Niharsonu Could you explain which values aren't showing correctly? How can we reproduce this? On which build/device is this happening?

**Comment by lmarceau** [comment]
Feel free to reopen if more information is provided
