### ISSUE TITLE
[Regression] Firefox offers to visit deleted bookmarks from iOS home screen 

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#10386]
## Steps to reproduce
1. Open homepage
2. Long press on a top site shortcut
3. Tap "bookmark"
4. Long press on the same shortcut
5. Tap "remove bookmark"
6. Background Firefox
7. Long press on the Firefox icon
### Expected behavior
- Firefox should not offer to visit a deleted bookmark.
### Actual behavior
- Firefox offers to visit the deleted bookmark.
### Device & build information
* Device: iPhone 12 Pro
* Build version: 9000 (8716)
### Notes
Attachments: 

https://user-images.githubusercontent.com/32130829/161537495-8bea3f3d-8781-45d4-a2bc-bf17d207e729.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4039)

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verified fix on v9000 (9284).

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verified fix on v106 (19965)
