### ISSUE TITLE
Sometimes the title is missing in inactive tabs

### ISSUE THREAD

**Issue by topotropic** [mozilla-mobile/firefox-ios#10389]
## Steps to reproduce
- move a few tabs to inactive 

### Expected behavior
- all inactive tabs have a title

### Actual behavior
- not all inactive tabs have a title
<img width="301" alt="image" src="https://user-images.githubusercontent.com/353960/161551991-82251969-2f45-4728-bdb6-081109d41b86.png">

Do we need a fallback here? 

### Device & build information
* Device: iPhone 8, 15.4.1
* Build version: 9000 (8686)
### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4042)

**Comment by csuciu** [comment]
I'm unable to reproduce this issue on v100 (9200). Verifying as fixed.
