### ISSUE TITLE
GleanPlumb: Telemetry for message interaction 

### ISSUE THREAD

**Issue by jhugman** [mozilla-mobile/firefox-ios#10395]
The GleanPlumb messaging system allows mozilla staff to send in-app messages to the user.

This issue covers the Glean telemetry messages associated with user-interaction of the messages.

Specifically sending events on

- message impression
- message interaction
- message dismissal
- malformed message
- message expiry i.e. neither clicked not dismissed.

Each message has a `message-key`.

The message interaction has an optional extra `action-uuid` which is randomly generated each time a message is tapped.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4047)

**Comment by jhugman** [comment]
# Request for data collection review form

All questions are mandatory. You must receive review from a data steward peer on your responses to these questions before shipping new data collection.

1. What questions will you answer with this data?
- How many users see each message
- How many users click each message
- How many users dismiss each message
- Which messages are malformed
- When a message was expired, i.e. neither clicked not dismissed.

2. Why does Mozilla need to answer these questions? Are there benefits for users? Do we need this information to address product or business requirements?
  * This will help us understand usage patterns around messages, and monitor the system health of the messaging system.
3. What alternative methods did you consider to answer these questions? Why were they not sufficient?
  * There are no other alternatives.
4. Can current instrumentation answer these questions?
  * No
5. List all proposed measurements and indicate the category of data collection for each measurement, using the Firefox data collection categories found on the Mozilla wiki.
Note that the data steward reviewing your request will characterize your data collection based on the highest (and most sensitive) category.

Measurement Description | Data Collection Category | Tracking Bug #
-- | -- | --
A message was pressed | Category 2 - interaction data | https://github.com/mozilla-mobile/firefox-ios/issues/10395
A message was clicked | Category 2 - interaction data | https://github.com/mozilla-mobile/firefox-ios/issues/10395
A message was dismissed | Category 2 - interaction data | https://github.com/mozilla-mobile/firefox-ios/issues/10395
A message was malformed  | Category 2 - interaction data | https://github.com/mozilla-mobile/firefox-ios/issues/10395
A message was expired  | Category 2 - interaction data | https://github.com/mozilla-mobile/firefox-ios/issues/10395

6. Please provide a link to the documentation for this data collection which describes the ultimate data set in a public, complete, and accurate way.
  * https://dictionary.telemetry.mozilla.org/apps/firefox_ios
7. How long will this data be collected? Choose one of the following:
  * This will expired on version 114, with the option to renew at that point.
8. What populations will you measure?
  * All channels, all locales, all countries
9. If this data collection is default on, what is the opt-out mechanism for users?
  * Default Glean SDK opt-out mechanism.
10. Please provide a general description of how you will analyze this data.
  * Glean and Amplitude.
11. Where do you intend to share the results of your analysis?
  * Only on Glean, Amplitude, and with mobile teams.
12. Is there a third-party tool (i.e. not Telemetry) that you are proposing to use for this data collection?
   * No third-party tools.

**Comment by nishant2718** [comment]
This PR is the one to look at - https://github.com/mozilla-mobile/firefox-ios/pull/10455. It's the exact same as the original, but with the base targeting a long running feature branch.

**Comment by data-sync-user** [comment]
➤ Nishant Patel commented:

Nightly build #9093 is the testable build for this work at the moment. When https://github.com/mozilla-mobile/firefox-ios/pull/10600 ( https://github.com/mozilla-mobile/firefox-ios/pull/10600|smart-link )  lands, this feature will be available to QA from main and on all nightly builds.
