### ISSUE TITLE
Fennec build fails to launch on actual device

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#10404]
## Steps to reproduce
1. Build Fennec 34117cd3e5815c8e77383424857e93a1bb2f30b5 on actual device
2. Launch Fennec
### Expected behavior
- Fennec should launch
### Actual behavior
- Fennec fails to launch
### Device & build information
* Device: iPhone 12 Pro (15.4) and iPad Pro (15.3)
* Build version: 34117cd3e5815c8e77383424857e93a1bb2f30b5
### Notes
- The build is working on simulator but not on actual device.
Attachments: 

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/32130829/161730192-510022f1-597c-4c64-ace4-90b42ce1de09.png">

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4056)

**Comment by electricRGB** [comment]
Heya. I've tried reproducing this sever times and it's working fine on my machine.
Do you have any more concrete steps to reproduce? Are you cleaning before building? Are you deleting the app before rebuilding? Just trying to figure out what's happening.

**Comment by SimonBasca** [comment]
@electricRGB just to clarify this is broken only on when building on actual device. It's working in simulator. The STR are
1. From terminal do: "git pull"
2. "sh ./bootstrap.sh"
3. Build on device from Xcode
4. Launch Fennec on device.

**Comment by electricRGB** [comment]
Yeah, I can't reproduce at all.

What version of Xcode are you on? 13.2.1?

**Comment by yoanarios** [comment]
I had that exact issue last week, in my case I was using Xcode 13.3. To fix it I downloaded Xcode 13.2.1 and the device builds started working again.
The weirdest thing is that after a successful device build with Xcode 13.2.1 ,Xcode 13.3 started working too so we couldn't pinpoint what the issue was

**Comment by SimonBasca** [comment]
> Yeah, I can't reproduce at all.
> 
> What version of Xcode are you on? 13.2.1?

13.3

**Comment by electricRGB** [comment]
Yep. We don't yet support 13.3, so this should work in 13.2.1.

**Comment by dnarcese** [comment]
@SimonBasca can you see if it is working for you in 13.3.1

**Comment by SimonBasca** [comment]
Working with both XCode 13.3 and 13.3.1
