### ISSUE TITLE
Empty to be deleted

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#10402]
**What information do we display in the address bar?**

Continue the effort to alight address bards across 4 mobile / tablet products: Firefox(ios & Android) + Focus (ios & Android)
Collaborate with: Desktop, Pro-client, and Mobile teams to arrive at unified address bar design.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4054)

**Comment by lmarceau** [comment]
Closing due to title being "Empty to be deleted"
