### ISSUE TITLE
Remove spacing at the top of tabs tray

### ISSUE THREAD

**Issue by topotropic** [mozilla-mobile/firefox-ios#10407]
Reduce the spacing at the top of the tabs tray to match margin left for tabs, see attached image. 

<img width="553" alt="image" src="https://user-images.githubusercontent.com/353960/161772925-77829e4b-6740-4673-a762-5a7913d205de.png">

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4057)

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verified fix on v9000 (8950).
