### ISSUE TITLE
Add undo tab close

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#10413]
This is a follow-up ticket for  [https://mozilla-hub.atlassian.net/browse/FXIOS-3953](https://mozilla-hub.atlassian.net/browse/FXIOS-3953|smart-link) 

In an earlier ticket, we implemented close all tabs in the background but in this ticket, we’ll add the functionality to undo closed tabs. 

The idea here is that we try an illusion and fully close the tabs once the undo toast goes away while doing a visual appeal that tabs are closed. 

This will make the UI faster.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4061)

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Marking as verified fix on Fennec main bdc1e009354679b7b811748a0d55383452b44ef4. The “undo close tabs” feature has proper functionality. 

Nishant Bhasin is there anything else that we need to check here before moving the issue to “Done”?

**Comment by lmarceau** [comment]
@SimonBasca can this be closed?

**Comment by SimonBasca** [comment]
Closing as fixed as the “undo close tabs” feature has proper functionality.
