### ISSUE TITLE
Drag and drop attachments stopped working - 99.0 (64-bit) Mac

### ISSUE THREAD

**Issue by mattlavis-transform** [mozilla-mobile/firefox-ios#10423]
## Steps to reproduce
Attempt to drag an attachment into an Outlook Web Access email on Firefox browser
Until the latest release, this was possible
Since the latest release it is not

### Expected behavior
File should load as an attachment

### Actual behavior
Nothing

### Device & build information
* Device:
Model Name:	MacBook Pro
Model Identifier:	MacBookPro17,1
Chip:	Apple M1
System Firmware Version:	7429.81.3
OS Loader Version:	7429.81.3

* Build version: ?
99.0 (64-bit)

### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4067)

**Comment by lmarceau** [comment]
Hi @mattlavis-transform 
I understand this ticket relates solely to the Firefox browser. This repository is dedicated to the Firefox for iOS application. Could you ask for support in the related [support page](https://support.mozilla.org/en-US/products/firefox) or post your bug in the [bugzilla page](https://bugzilla.mozilla.org/enter_bug.cgi)?
