### ISSUE TITLE
Words don’t rap around displayed in reading mode

### ISSUE THREAD

**Issue by mjhymowitz** [mozilla-mobile/firefox-ios#10441]
## Steps to reproduce
go to a website with a very long word and put it in reading mode
Example: 
Go to https://mtlnation.com/novel/level-1-player/chapter-125/
Go into reading mode
Look for the word: Wheeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee!

### Expected behavior
word raps around the screen in the designated space
Like this:
Wheeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-
eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-
eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee!

### Actual behavior
continuing in a straight line forcing you to zoom our or shift the screen to read the full word. (I know the example is not a word it’s just an example) Reading mode experience is a bit ruined due to this reaction to long words

### Device & build information
* Device: iPhone 11
* Build version: Firefox Daylight 98.2 (8475)
### Notes
Attachments: 
![C81E6C8A-9094-40C6-B9E1-087ED8FAFA6E](https://user-images.githubusercontent.com/9580326/162558433-be236b89-0fb7-403f-9636-8c0419315e79.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4076)

**Comment by lmarceau** [comment]
Not reproducible in Safari, so should be investigated
