### ISSUE TITLE
Long words going off screen

### ISSUE THREAD

**Issue by mjhymowitz** [mozilla-mobile/firefox-ios#10442]
## Steps to reproduce
Go to a website with a really long word
Example: https://mtlnation.com/novel/level-1-player/chapter-125/
Look for this word:

Wheeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee!

### Expected behavior
Text to wrap around the view able screen so the entire word can be read
something like this:
Wheeeeeeeeeeeeeeeeeeeeeee-
eeeeeeeeeeeeeeeeeeeeeeeeee-
eeeeeeeeeeeeeeeeeeeeeeeeee-
eeeeeeeeeeeeeeeeeeeeeeeeee-
eeeeeeeee!

### Actual behavior
Only first part of the word is displayed. The rest of the word goes off screen and it’s impossible to shift the website over to read the full word. You have to go into reading mode or highlight and copy the word into a text editor of some kind to read the full word. Image below

goes off screen so you can’t see the ! and there’s no way to shift the screen over to see it.
Wheeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee

### Device & build information
* Device: iPhone 11
* Build version: Firefox Daylight 98.2 (8475)

### Notes
Attachments: 
![EE688428-1B66-4C62-8736-D3F4B4624E32](https://user-images.githubusercontent.com/9580326/162558487-db8f2cf0-edb3-4e7b-96e4-456ff957bbed.png)
![EB6D9C2F-E470-4A97-A24E-ABD9D5A8E22C](https://user-images.githubusercontent.com/9580326/162558524-f743d4fe-cbb9-42a8-be07-4f919ddc9e0e.jpeg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4077)

**Comment by lmarceau** [comment]
This is reproducible on browser as well. Seems to be more of a website specific issue
