### ISSUE TITLE
Several spacing issue encountered

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#10465]
Several spacing issue encountered:
- Long press on tab counter
- Long press on website shortcuts from homepage
- Long press on URL bar after visiting a page
- Opening hamburger menu from homepage
- Opening hamburger menu after visiting a page
 
### Device & build information
* Device: iPhone 12 Pro (15.4)
* Build version: Fennec f1f25eee956d468f4b0e37537a5391cf46419486
### Notes
Attachments: 

![Skype_Picture_2022_04_11T12_19_37_720Z](https://user-images.githubusercontent.com/32130829/162938596-5a769299-4555-48c3-87fe-cd9322641304.jpeg)

![Skype_Picture_2022_04_11T12_19_33_736Z](https://user-images.githubusercontent.com/32130829/162938643-5f0b0e5e-8f7a-4b87-b596-697b22c2f25d.jpeg)

![Skype_Picture_2022_04_11T12_19_30_303Z](https://user-images.githubusercontent.com/32130829/162938666-e3954c80-04b8-40a0-b83e-3b9465431a06.jpeg)

![Skype_Picture_2022_04_11T12_19_26_120Z](https://user-images.githubusercontent.com/32130829/162938694-4d0c5ffd-38fa-4b8a-9bfe-d1c6f28db364.jpeg)

![Skype_Picture_2022_04_11T12_19_20_973Z](https://user-images.githubusercontent.com/32130829/162938700-56d806cc-e106-4ccb-a2da-fd7e9a9a7570.jpeg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4086)

**Comment by lmarceau** [comment]
@SimonBasca Are you on xcode 13.3 ? If so there's a ticket here for that https://github.com/mozilla-mobile/firefox-ios/issues/10194

**Comment by SimonBasca** [comment]
Yes @lmarceau, this is with Xcode 13.3. Thanks, I'll close this issue.
