### ISSUE TITLE
If "Tab Groups" enabled, closing a tab in Tab Tray crashes the app

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#10468]
STR:

1. Fresh install
1. Turn on Tab Groups from settings
1. Open up multiple tabs (tested with 10 websites open)
1. Open tab tray
1. Close a tab in the middle

Actual behaviour:

The app do crash.

Expected behaviour:

The tab closes, and the app doesn’t crash.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4087)

**Comment by electricRGB** [comment]
Looking at it and the steps to reproduce (after I ran through them), it's not the same crash as the stack trace is different. Thanks for looking out for it though!!! :D

**Comment by lmarceau** [comment]
@SimonBasca Can this be closed?

**Comment by SimonBasca** [comment]
This isssue is no longer reproducible. I think it got fixed by https://github.com/mozilla-mobile/firefox-ios/issues/10472.
