### ISSUE TITLE
Search history icon is not functional in grouped items in history

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#10469]
## Steps to reproduce
1. Have a few items grouped in history
1. Go to the grouped items in history
1. Tap the "magnifying" icon
    1. Expected behavior

* Search icon should be functional
    1. Actual behavior
* Search icon is not functional.
    1. Device & build information
* Device: iPhone 12 Pro (15.4)
* Build version: Fennec f1f25eee956d468f4b0e37537a5391cf46419486
    1. Notes
Attachments: 

https://user-images.githubusercontent.com/32130829/162978594-8b309aad-9d86-4325-be31-cfedfdaa623d.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4089)

**Comment by SimonBasca** [comment]
Note: After tapping on the "Search history" button, backgrounding and foregrounding the app will not display the "<" button. Also the "Done" button is not functional after this step.

![Screenshot](https://user-images.githubusercontent.com/32130829/162980055-baec34b1-d42b-4352-beca-5451ce22f4e5.jpeg)

**Comment by SimonBasca** [comment]
This is still reproducible on v9000 (9271)

**Comment by yoanarios** [comment]
@SimonBasca the solution for this bug was to remove the option to search inside a group, similar to the delete trash can. Can you confirm this is what you are getting or do you see the search icon and it doesn't work? Thank you

**Comment by SimonBasca** [comment]
@yoanarios I can confirm that the option to search inside a group has been removed but we've found another case where the issue is reproducible .See https://github.com/mozilla-mobile/firefox-ios/issues/10608
