### ISSUE TITLE
[Crash] When closing tabs in tab tray without "Tab Groups"

### ISSUE THREAD

**Issue by yoanarios** [mozilla-mobile/firefox-ios#10472]
## Steps to reproduce
- Open up multiple tabs (tested with 10 websites open)
- Open tab tray
- Close a tab in the middle

### Expected behavior
The tab closes, and the app doesn’t crash.

### Actual behavior
The app do crash.

### Device & build information
* Device: ?
* Build version: ?
### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4090)

**Comment by yoanarios** [comment]
Seems related to #10468

**Comment by SimonBasca** [comment]
@yoanarios is this issue fixed and ready to test?

**Comment by data-sync-user** [comment]
➤ Daniela Arcese commented:

Simion Basca that was only a partial fix, and there will be other things needed before this is completely fixed.

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Thanks Daniela Arcese. Just wanted to make sure since it has a PR attached.

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verifying as fix on main f3cd83904c617561ccf200228d33f0b94d0545ce. The issue is no longer reproducible following the STR.
