### ISSUE TITLE
Opening USDZ from iFrame invokes file download rather than display through AR QuickLook 

### ISSUE THREAD

**Issue by milesgreen** [mozilla-mobile/firefox-ios#10500]
## Steps to reproduce
- Visit a website that displays a link to view a USDZ, embedded within an iFrame. 
- Click on the HTML link in the iFrame to view the USDZ file. 

Demo:
https://usdz-iframe-test.glitch.me/
- Try the USDZ link in the top level Parent page (works)
- Try the USDZ link in the embedded iFrame Child page (does not work)

### Expected behavior
Link in iFrame should open USDZ in AR QuickLook.

### Actual behavior
File download dialog is invoked. USDZ file can be downloaded. Does not open AR QuickLook. 

### Device & build information
* Device: iPhone 12 Pro, iOS 15
* Build version: Firefox Daylight 99.0 (8654)
### Notes
Attachments: 
![IMG_4F4A304F4EEF-1](https://user-images.githubusercontent.com/53870482/163623648-b8ad7a90-46e4-4b24-9a80-803d001d385f.jpeg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4099)

**Comment by milesgreen** [comment]
This issue appears to still manifest in Firefox Daylight 100.1 (9384)
Was the fix in v 100?

**Comment by lmarceau** [comment]
@milesgreen No, the PR wasn't merged yet. You can see the status here: https://github.com/mozilla-mobile/firefox-ios/pull/10506

**Comment by milesgreen** [comment]
PR still not merged as of Firefox 104.1 (16952)?
Anything else need to be done?
How can I help?

**Comment by lmarceau** [comment]
Hello @milesgreen! This wasn't merged yet as there was some other related investigation going on. This isn't forgotten. We're currently working on v106, as v105 is already frozen.

**Comment by milesgreen** [comment]
Awesome. Thanks for the update @lmarceau.

**Comment by SimonBasca** [comment]
Tested on latest v9000 (19069). Note that the issue for the  the embedded iFrame Child page is still reproducible. 

@lmarceau could you please take a look. Thanks!

https://user-images.githubusercontent.com/32130829/190624768-5289fa40-3581-4098-bbce-eaaef641c371.mp4

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Please ignore previous comment. This issue is verified fixed on v9000 (19069).

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verified fix on v106.0 (19594)

**Comment by milesgreen** [comment]
Awesome news! I'm not on the beta program, so I'll have to wait for the public release. I'll keep an eye out for it. Thanks!
