### ISSUE TITLE
Fix Experiments not showing up in 99.1

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#10510]
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4102)

**Comment by csuciu** [comment]
Verifying as fixed on v99.1 (9096).

**Comment by data-sync-user** [comment]
➤ Richard Pappalardo commented:

Awesome, Catalin Suciu ! thank you!
