### ISSUE TITLE
Delete FxATelemetry; back fill tests where it was used

### ISSUE THREAD

**Issue by piofusco** [mozilla-mobile/firefox-ios#10528]
As I mentioned in [this issue](https://github.com/mozilla-mobile/firefox-ios/pull/10384), `FxATelemetry` is unnecessary since Codable is doing all of the work. My hope was to delete this class and the static function `parseTelemetry()` and replace it's two usages with the following:

```
guard let data = string.data(using: .utf8) else { return [] }

var telemetry: Telemetry?
do {
    telemetry = try JSONDecoder().decode(Telemetry.self, from: data)
} catch {
    print("Unable to decode telemetry: \(error)")
}

guard let telemetry = telemetry else { return [] }
let events = telemetry.events
```

Again, this method is only used in two places
- Profile.sendItem()
- FxAPushMessageHandler.handle()

Additionally, I was planning on back filling everything with tests to ensure nothing is broken. The trickiest part will be wrapping the singleton `RustFirefoxAccounts` with a protocol and injecting it into `BrowserProfile` and `FxAPushMessageHandler`. I'm pretty sure I can do this without affecting the other usages of this singleton and establish a good testing pattern for other classes that use it.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4114)

**Comment by piofusco** [comment]
@lmarceau would definitely love to get your feedback on this before I begin. I've asked about PRs that involve back filling tests in the past and gotten the go ahead. Just wanted to ensure I'm not overstepping my bounds as a open source contributor.

**Comment by piofusco** [comment]
@lmarceau - so I have run into a little hurdle. Are there any tests in the codebase that involve mocking `Deferred`? While I could use a real `Deferred`, I am having a hard time controlling `uponQueue()` and allowing my tests to run synchronously.

In `Profile.sendItem`, there's a usage of `RustFirefoxAccounts` that retrieves it's `accountManager` - which is a `Deferred<FxAccountManager>`.:

```
RustFirefoxAccounts.shared.accountManager.uponQueue(.main) { accountManager in
...
}
```

**Comment by piofusco** [comment]
Yup, I am very familiar with asynchronous tests and expectations and was hoping to avoid them, haha. I tried my best to keep things synchronous, but yea, it looks like it's just no possible (yet). Curious what we would use in place of deferred.

I'll try adding a completion to the signature, calling the deferred with the passed in completion, and writing some tests that wait.

**Comment by lmarceau** [comment]
@piofusco 
Instead of deferred we can use completion or closure, or at one point we could use async/await too. But I think it's only available on greater than 15.0. Not sure how if it's straightforward to replace Deferred in the current case, if it is you can have a look. If not just a completion for the test purpose is good to me.

**Comment by piofusco** [comment]
@lmarceau so I finally got another chance to try what you suggested, but I am still stuck.

The crux is that I cannot control the `Deferred<FxAccountManager>` that comes back when we call `RustFirefoxAccounts.shared.accountManager`.

Therefore I can't control whether the `account` has a `constellation` or not.

```
guard let constellation = accountManager.deviceConstellation() else {
    deferred.fill(Maybe(failure: NoAccountError()))
    return
}
```

All I can test is whether we get inside the completion block - which doesn't seem very valuable.

At this point, I feel like I've started at the wrong node. I am wondering if it would be more appropriate to take on reworking `RustFirefoxAccounts` first rather than trying to wrap tests around it as is. Then, I could circle back to this endeavor since it would likely involve adding tests everywhere it's used. 

I'm guessing this would probably be out of bounds for a contributor though 😄

**Comment by lmarceau** [comment]
We try to only refactor things that we're working on/heavily use. Some part of the code isn't always easily testable indeed, but if it works then sometimes it's better to leave it be until we play in that area (then we can properly introduce tests). Particularly with the Profile, it's used in many places and we need to be careful there! Since it turned out to be complicated, maybe something else would be preferable to work on? Let me know if you have some interests I can try to provide some more info.

**Comment by piofusco** [comment]
Understood. I definitely wouldn't wanna break anything in the process and appreciate you all would want a more dedicated effort to something this widely used. While I am definitely still interested in contributing something, I would love to help add tests where there are few or something similar. Got anything in mind?

**Comment by lmarceau** [comment]
@piofusco Yeah I do! It would be great to have tests for the view models in the Firefox home page. We'll have to add some features inside the home page soon and it would be great to increase our test coverage of existing code. You could maybe have a look at FirefoxHomeJumpBackInViewModel first? Would that be interesting?

**Comment by piofusco** [comment]
Yea, that sounds super cool! I'll take a look soon!

**Comment by lmarceau** [comment]
I opened the other issue here: https://github.com/mozilla-mobile/firefox-ios/issues/10607
I'll close this one for now, we can reopen at a later point if we want. thanks!
