### ISSUE TITLE
#enagic #kangen Water # Change Your Water Change Your life

### ISSUE THREAD

**Issue by Vietthang91** [mozilla-mobile/firefox-ios#10529]
### User Problem
> Why should we implement this? What is the user benefit?

### Ideas for Solution
> Let us know if you have an idea on how to solve this user problem

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4115)

**Comment by Vietthang91** [comment]
.

**Comment by lmarceau** [comment]
Hello! When filling an issue please provide details as to how this can help us improve Firefox for iOS. I'm closing this for now, feel free to comment if this was wrong.
