### ISSUE TITLE
The Recently Visited list is not updated with the newest history entries.

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#10533]
## Steps to reproduce
1. Enable Recently Visited
2. Visit 9 pages
3. Check the Recently Visited list
4. Visit a few more sites
5. Check the  Recently Visited list
### Expected behavior
- The Recently Visited list should be updated with the newest history entries.
### Actual behavior
- - The Recently Visited list is not updated with the newest history entries.
### Device & build information
* Device: iPhone 12 Pro (15.4)
* Build version: Fennec e51269efddb09a2dd17412f5d2d9eb1f3a9f68f9
### Notes
- In my case I have 3 new entries "test new 1", "test new 2", "test new 3" and the Recently Visited list is not updated with the newest entries.
Attachments: 

https://user-images.githubusercontent.com/32130829/164233169-cde4bc3b-d0d2-400d-81f6-0cce874f1923.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4117)

**Comment by yoanarios** [comment]
@SimonBasca Recently visited and history panel don't share the same data source so we might encounter cases like this one where the result don't match. At Recently visited we show the "weight highlights" based on  visited time this results are from A~S, so it could be the case that the results currently showing have more weight than the latest searches. I will investigate to confirm the we are showing the correct results

**Comment by heraclitusq** [comment]
Experiencing the same issue (Firefox Daylight 100.1 (9384)). Wondering what the status of this issue is now. Has it been fixed? Working in progress? Or won't fix?

**Comment by dnarcese** [comment]
This is intended behaviour. The 'Recently Visited' section is not just the last X items from your history, it is determined based on visit time and frequency.
