### ISSUE TITLE
Firefox should block app URLs loaded from an iframe

### ISSUE THREAD

**Issue by jonathangarelick** [mozilla-mobile/firefox-ios#10536]
Hi there --

A colleague of mine discovered this issue while browsing movieguide.org. While browsing the website, Firefox repeatedly prompts to open a not-useful app link (with scheme `ios-log`). This degrades the user experience. The cause is a WordPress plugin which loads these `ios-log` URLs through an iframe.

<img src="https://user-images.githubusercontent.com/41495718/164267718-b4d7e47c-2434-428a-ab15-fccb3642aedf.PNG" height="500">

To reproduce:
1. Go to movieguide.org
2. Click on a few internal links, and you should see this behavior

Here is how we handle it at Neeva ([issue](https://github.com/neevaco/neeva-ios/issues/3388#issuecomment-1103238418),  [code](https://github.com/neevaco/neeva-ios/blob/068f49d4448733455fbb2aa70be70dfb7dda21ff/Client/Frontend/Browser/BrowserViewController/BrowserViewController%2BWebViewDelegates.swift#L734)). This issue also indicates that Chrome has the same behavior (we actually learned it from their source).

Thanks :-)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4119)

**Comment by lmarceau** [comment]
Hi @jonathangarelick, thanks for opening this issue. We have an issue opened already for this here https://github.com/mozilla-mobile/firefox-ios/issues/10218

I'll close this one to keep the one already opened.
