### ISSUE TITLE
Recently Visited is not cleared after clearing all history 

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#10532]
## Steps to reproduce
1. Enable Recently Visited
2. Visit 9 pages
3. Clear all history
### Expected behavior
- Recently Visited should be cleared
### Actual behavior
- Recently Visited is not cleared.
### Device & build information
* Device: iPhone 12 Pro (15.4)
* Build version: Fennec e51269efddb09a2dd17412f5d2d9eb1f3a9f68f9
### Notes
Attachments: 

https://user-images.githubusercontent.com/32130829/164231155-9bd48cf7-bdfe-4609-b830-8a525827f91c.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4116)

**Comment by SimonBasca** [comment]
@yoanarios could https://github.com/mozilla-mobile/firefox-ios/pull/10535 also fix this issue?

**Comment by yoanarios** [comment]
@SimonBasca yes also includes the fix to clear history highlights when history is cleared. I will tag this issue in the PR

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verifying as fix on v9000 (9248)

**Comment by cars11** [comment]
Still doesn't clear recently visited

**Comment by SimonBasca** [comment]
@cars11 We still have an issue logged when clearing from the history list: https://github.com/mozilla-mobile/firefox-ios/issues/10745.
