### ISSUE TITLE
The history list is not correctly updated after visiting a second item

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#10534]
## Steps to reproduce
1. Clean install Fennec e51269efddb09a2dd17412f5d2d9eb1f3a9f68f9
2. Visit a page(e.g. Amazon) -> Observe the history list is correctly recording the entry
3. Visit another page (e.g Twitter)
### Expected behavior
- The history list should be correctly updated.
### Actual behavior
- The history list is not correctly updated. After restarting the app the visited page from step 3) will be displayed.
### Device & build information
* Device: iPhone 12 Pro (15.4)
* Build version: Fennec e51269efddb09a2dd17412f5d2d9eb1f3a9f68f9
### Notes
Attachments: 

https://user-images.githubusercontent.com/32130829/164239404-e4265812-7bf3-42a2-97b9-c675edfe8150.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4118)

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verifying as fix on v9000 (9248)
