### ISSUE TITLE
Inconsitent behaviour after tapping on the "search" icon in the History panel.

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#10541]
## Steps to reproduce
1. Go to the history panel
2. Tap on the "search" icon
3. Dismiss the history panel
4. Return to the history panel
### Expected behavior
- The behavior should be consistent. 
### Actual behavior
- When 1st visiting the history panel, the search field is not visible. After tapping on the search icon, the search filed will remain visible. The behavior is inconsistent.
### Device & build information
* Device: iPhone 12 Pro (15.4)
* Build version:  Fennec 489515c3c57337dc441e135d1ed3093dd54adf20
### Notes
Attachments: 

https://user-images.githubusercontent.com/32130829/164453441-c8ddf4f1-1bfb-4e90-8a6c-b1c3a96606d7.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4121)

**Comment by yoanarios** [comment]
@SimonBasca this is how it was implemented based on the acceptance criteria: The search state should be saved if the user navigates to a different panel.

**Comment by SimonBasca** [comment]
Thanks for clarifying @yoanarios. Closing the issue.
