### ISSUE TITLE
PhotoActionSheet.setMainMenuTableViewHeight goes recursive

### ISSUE THREAD

**Issue by gutley** [mozilla-mobile/firefox-ios#10548]
When running the app in the debugger, anytime the main menu is pressed, a log is output by UIKit as follows:

_2022~~04~~21 16:22:26.626525+0100 Client[45931:363276] [Assert] Attempted to access the table view's visibleCells while they were in the process of being updated, which is not allowed. Make a symbolic breakpoint at UITableViewAlertForVisibleCellsAccessDuringUpdate to catch this in the debugger and see what caused this to occur. Perhaps you are trying to ask the table view for the visible cells from inside a table view callback about a specific row? Table view: <UITableView: 0x7feb648a6200; frame = (0 0; 400 744); clipsToBounds = YES; gestureRecognizers = <NSArray: 0x600002170c00>; layer = <CALayer: 0x600002ea5420>; contentOffset: {0, 0}; contentSize: {400, 744}; adjustedContentInset: {0, 0, 0, 0}; dataSource: <Client.PhotonActionSheet: 0x7feb64749de0>>_

If you then set the breakpoint at UITableViewAlertForVisibleCellsAccessDuringUpdate as suggested and open the main menu you will break with this (collapsed) trace having called `tableView.visibleCells`:

![image](https://user-images.githubusercontent.com/2040690/164494256-e97b8040-4b61-41a4-aa15-2b1fcc1cb1eb.png)

If we look back up the trace to the earlier call to setMainMenuTableViewHeight we see that it too was at exactly the same line and was calling `tableView.visibleCells` :

![image](https://user-images.githubusercontent.com/2040690/164495823-6b965b3e-2e4d-4e54-bc01-1f2720db24a0.png)

And in the middle of the stack we can see that `PhotoActionSheet:observeValue(forKeyPath:...)` was triggered and it was trying to set the `preferredContentSize`:
![image](https://user-images.githubusercontent.com/2040690/164497003-8c119f9e-a0a4-479a-a04b-989d40a51b34.png)

This triggered the relayout of the view and the eventual nested call to `visibleCells` that isn't allowed during updating. Thankfully the OS is obviously used to seeing people do similar things and put a stop to anything nasty happening.

It would nice to avoid this completely if possible.

I am guessing this is related to 85a7667 done by @lmarceau back in February.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4129)

**Comment by lmarceau** [comment]
Yeah indeed, that menu need some more work. We need to override it's height (cutting so half a cell is visible, so user can know there's more content to scroll), while the view is still being layout. Changing height while laying out isn't exactly great. At the moment we can't know the menu height before it's layout, since dynamic type or longer languages can be involved and change content size. Happy to discuss more about it if you want.
