### ISSUE TITLE
Recently Visited group is changing when the homepage is reloaded

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#10551]
1. have 2 groups in recently visited
1. switch apps and come back to firefoc
1. notice the groups in recently visited change

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4132)

**Comment by csuciu** [comment]
I can't reproduce this issue on v100.0 (9200). Verifying as fixed.
