### ISSUE TITLE
Update 'Send Feedback' link

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#10556]
Should point to [https://connect.mozilla.org/](https://connect.mozilla.org/|smart-link)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4133)

**Comment by lmarceau** [comment]
Was merged with [PR](https://github.com/mozilla-mobile/firefox-ios/pull/10557/files) 
Send feedback refers to this action in the settings page
![Screen Shot 2022-05-02 at 10 06 32 AM](https://user-images.githubusercontent.com/11338480/166247686-d39c4d2e-a0ee-42ea-8a09-3fd4554b49d0.png)

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verifying as fix on 9000(9505).
