### ISSUE TITLE
FxIOS Swift Compile Error - import SwiftyJSON "Module Compiled with Swift 5.3.2 cannot be imported by the Swift 5.6 compiler"

### ISSUE THREAD

**Issue by imnotabr** [mozilla-mobile/firefox-ios#10550]
I'm working with Firefox iOS Version 38 build 50. 

When using Xcode 13 and running Firefox on an iPhone 13 with iOS 15.4,

a "Swift Compile Error" occurs when trying to import SwiftyJSON. The error reads as follows:

"Module compiled with Swift 5.3.2 cannot be imported by the Swift 5.6 compiled. /firefox-ios/Carthage/Build/iOS/SwiftyJSON.framework/Modules/SwiftyJSON.swiftmodule/arm64.swiftmodule.

Attached is a screenshot of the error

What is causing this error and how can it be fixed?

![SwiftyJSON Module compiled with Swift 5 3 2 cannot be imported by the Swift 5 6 compiler](https://user-images.githubusercontent.com/62814903/164546464-ba7466dc-0899-4ca6-8d11-513877c6e3bc.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4131)

**Comment by lmarceau** [comment]
Hello! We have moved away from Carthage to SPM. First things first, I would definitely suggest taking advantage of that by using latest version. If that's not possible, then I would say to reinstall dependencies by using `sh .bootstrap.sh --force`. This really looks like dependencies weren't install properly with Carthage.

**Comment by Reddnine** [comment]
Hi @lmarceau,

I tried reinstalling the dependencies using `sh .bootstrap.sh --force ` but then I get get the error:

```
***  Skipped installing application-services binary due to the error:
	"Incompatible Swift version - framework was built with 5.3.2 (swiftlang-1200.0.45 clang-1200.0.32.28) and the local version is 5.6 (swiftlang-5.6.0.323.62 clang-1316.0.20.8)."
```
![Skipped installing application-services binary due to the error](https://user-images.githubusercontent.com/43630873/165009973-990eceb5-3f06-4efd-8985-727f17bc2640.png)

If this can get this figured out I will send you a $100 tip, since I can't update to the latest version. I really appreciate you looking into it.

**Comment by Reddnine** [comment]
I also tried 

`carthage update --platform iOS --no-use-binaries` as suggested [here](https://stackoverflow.com/questions/58130048/module-compiled-with-swift-5-0-1-cannot-be-imported-by-the-swift-5-1-compiler) and that solved the above error but then I get the error `"No such module 'SwiftyJSON'"`

![No such module SwiftyJSON](https://user-images.githubusercontent.com/43630873/165022433-49f30c00-39c3-442d-b696-11fd806e2e64.png)

**Comment by lmarceau** [comment]
To avoid duplicating discussions, let close this one here since https://github.com/mozilla/application-services/issues/4923 has been opened with same issue.
