### ISSUE TITLE
WebServer class has no fallback if its port is in use by another app

### ISSUE THREAD

**Issue by gutley** [mozilla-mobile/firefox-ios#10565]
This is something I ran into recently when running my fork of Firefox alongside the 'normal' version in spilt screen mode on an iPad. (The same will happen if you run Firefox and Fennec together).

Because there is a hard-coded port number (6571), if that port is unavailable, then the Webserver can't start and all its functionality disappears. Normally this isn't a problem in non-split screen mode, as the app relinquishes the port when going to the background so the other app can get it when it comes to the front. But in Split screen mode, both apps can come to the front together and its a matter of timing as to which one gets the port and which one fails.

This might seem like an esoteric issue as it's unlikely in real life for there to be two 'versions' of the Firefox code running in two different apps. But there is still the possibility of another independent app grabbing that port number for itself before Firefox gets it

Ideally, the code should try a range or ports and use the first successful one, instead of abandoning starting the web server if 6571 is unavailable.

(I will shortly be submitting a PR that does just this)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4138)

**Comment by gutley** [comment]
PR submitted : https://github.com/mozilla-mobile/firefox-ios/pull/10566

**Comment by lmarceau** [comment]
Closing in favor of the feature request https://github.com/mozilla-mobile/firefox-ios/issues/11047
