### ISSUE TITLE
Dark mode stops working

### ISSUE THREAD

**Issue by Xepo125** [mozilla-mobile/firefox-ios#10564]
## Steps to reproduce
Turn on dark mode on ipad 
Use the browser for few seconds 
Get the result seen in the video 

### Expected behavior
Firefox dark mode should be consistent 

### Actual behavior
Dark mode doesnt stay consistent 

### Device & build information
* Device: iPad Pro (12.9-inch) (5th generation)
* Build version: 15.4
    1. Notes
Attachments: 

https://user-images.githubusercontent.com/104300332/164970593-f75e41a3-1d42-45c8-badc-1cbdfbd92105.MOV

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4137)

**Comment by lmarceau** [comment]
@Xepo125 
Hello thanks for opening the ticket. Could you let us know the following:
- If you go in Settings > Theme, what options have you there? Do you have system enabled, manual mode or automatic?
- Under the hamburger menu (three lines menu), do you have Night Mode enabled or not when this happens?
Thanks!

**Comment by Xepo125** [comment]
> @Xepo125 Hello thanks for opening the ticket. Could you let us know the following:
> 
>     * If you go in Settings > Theme, what options have you there? Do you have system enabled, manual mode or automatic?
> 
>     * Under the hamburger menu (three lines menu), do you have Night Mode enabled or not when this happens?
>       Thanks!

in settings the theme is set to system theme and the night mode is off :)
