### ISSUE TITLE
[Enhancement] Consider changing the position of the “Close All Inactive Tabs” button

### ISSUE THREAD

**Issue by heres-maria** [mozilla-mobile/firefox-ios#10587]
**[Affected Versions]:**
- Firefox Daylight 100.0 (Fennec)

**[Affected Platforms]:**
- iPhone 13, iOS 15.2 - Xcode Simulator

**[Prerequisites]:**
- Have a build enrolled in the Firefox iOS Inactive Tabs Rollout experiment/rollout.
- Have a lot of tabs displayed in the "Inactive Tabs" section.

**[Steps to reproduce]:**
1. Open the Tabs view.
2. Open the "Inactive Tabs" section.
3. Scroll through all the inactive tabs to reach the “Close All Inactive Tabs" button.

**[Proposed behavior]:**
- Have the “Close All Inactive Tabs” button displayed outside the "Inactive Tabs" dropdown (either on page/section or in the bar where the icon buttons for deleting all the tabs or creating a new one are displayed).
OR
- Have the “Close All Inactive Tabs” button displayed above the actual list of inactive tabs (as long as it can not be accidentally tapped while trying to close the section).
OR
- Change the way users can delete all the inactive tabs (option displayed at long press of the section or displayed at swipe).

**[Current behavior]:**
- The “Close All Inactive Tabs” button is displayed below all the inactive tabs. For users who leave a lot of tabs open, that could mean an uncomfortable amount of scrolling to reach the button.

**[Notes]:**
- Attached is a recording of the current behavior.

https://user-images.githubusercontent.com/53752296/165334132-9199e2d3-b8ae-4eb0-9c81-0e90eaf1ef17.mov

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4150)

**Comment by data-sync-user** [comment]
➤ Tiffanie Shakespeare commented:

tagging nicole to decide what to do here.

**Comment by data-sync-user** [comment]
➤ Nicole Weber commented:

Thanks for the feedback! I will close it for now but keep an eye on it.
