### ISSUE TITLE
Fennec crashes on start-up

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#10595]
## Steps to reproduce
1. Launch Fennec cddc8d654fea51257e1f4366acd99582225dcdf1 on actual device
OR
1. Build  Fennec cddc8d654fea51257e1f4366acd99582225dcdf1 on simulator
2. Close the simulator after it launches from XCode
3. Launch Fennec from simulator
### Expected behavior
- Fennec should function as expected and not crash
### Actual behavior
- Fennec crashes.
### Device & build information
* Device: iPhone 12 Pro (15.4) with XCode 13.3.1
* Build version: cddc8d654fea51257e1f4366acd99582225dcdf1
### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4154)

**Comment by lmarceau** [comment]
Note: Relates to discussion in thread https://forums.swift.org/t/swift-packages-in-multiple-targets-results-in-this-will-result-in-duplication-of-library-code-errors/34892/73

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

The issue is no longer reproducible on latest main 8db0439f8bc436162ee87a65120aa9a7bb42aba0
