### ISSUE TITLE
The default browser card should not be displayed after the user opted out of nimbus experiments

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#10604]
## Steps to reproduce
1. Clean install v9000 (9093)
2. Go to settings
3. Disable "Studies"
### Expected behavior
- The default browser card should not be displayed since the user opted out of nimbus experiments
### Actual behavior
- The default browser card is displayed.
### Device & build information
* Device: iPhone 13 mini (15.4.1)
* Build version: 9000 (9093)
### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4159)

**Comment by SimonBasca** [comment]
@nishant2718 @dnarcese is this and issue or only applies to custom messages and not the "Default browser card"?

**Comment by dnarcese** [comment]
Not an issue. The default browser card will show by default and is not dependent on experiments
