### ISSUE TITLE
[Experiment] The “Inactive Tabs” section is not displayed on Release with the feature enabled by an experiment

### ISSUE THREAD

**Issue by heres-maria** [mozilla-mobile/firefox-ios#10618]
**[Affected Versions]:**
- Firefox Release 100.0
- Firefox Release 99.3
- Firefox Release 99.0

**[Affected Platforms]:**
- iOS 15.3 (iPhone SE)
- iOS 15.3.1 (iPhone 11)

**[Prerequisites]:**
- Be enrolled in the Firefox iOS Inactive Tabs Rollout or the treatment branch of the Firefox iOS Inactive Tabs experiment.

**[Steps to reproduce]:**
1. Open a few tabs.
2. Close the app.
3. Change the date of the device to at least 2 weeks in the future.
4. Reopen the app.
5. Open the Tabs View and observe the sections displayed.

**[Expected result]:**
- The “Inactive Tabs” section is displayed.

**[Actual result]:**
- The “Inactive Tabs” section is not displayed.

**[Notes]:**
- Attached is a [recording of the issue](https://drive.google.com/file/d/1W_EkDXSIbznIlsV-Wzgs5pSbZ3hhNUkc/view?usp=sharing).

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4169)

**Comment by electricRGB** [comment]
Are you pasting the full, and correct experiment recipe directly into the JSON field and it's not working?

**Comment by heres-maria** [comment]
We have verified that the issue is no longer reproducible. The "Inactive Tabs" section is displayed using Nimbus experiments with the new form of the recipe. Tested on Firefox for iOS 100.0 RC using iOS 15.3 (iPhone SE).
