### ISSUE TITLE
Reader View address bar always shows insecure connection icon

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/firefox-ios#10623]
## Steps to reproduce
1. On a page that supports Reader View (such as this very GitHub page or https://www.mozilla.org/) and was loaded on an HTTPS secure connection, tap the Reader View button. 

### Expected behavior
Reader View’s address bar shows an insecure connection icon. 

### Actual behavior
Since the original page has a secure connection icon, I would expect the Reader View should also have a secure connection icon. 

### Device & build information
* Device: iPhone 12
* Build version: TestFlight 100.0 (9200)

### Notes
Attachments: 

![31EF4638-F689-4CC5-9EBE-47BB6261972A](https://user-images.githubusercontent.com/629193/166183192-c8e35533-1a3e-4e0c-a5af-b18826dcd9d6.jpeg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4172)

**Comment by csuciu** [comment]
This is fixed in the latest version.
