### ISSUE TITLE
Build Failed: Command CompileSwiftSources failed with a nonzero exit code

### ISSUE THREAD

**Issue by EdisonE3** [mozilla-mobile/firefox-ios#10626]
When I try to build Firefox, I meet some problems:
<img width="290" alt="image" src="https://user-images.githubusercontent.com/52118917/166228576-3aff34d8-6ba5-4e25-b655-035c685f5b49.png">
<img width="1082" alt="image" src="https://user-images.githubusercontent.com/52118917/166228585-ae3394f6-edfe-4fb5-9f91-f66e368ff37d.png">
Is there any way to solve this problem?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4173)

**Comment by lmarceau** [comment]
Hello! Which Xcode version are you using? Are you on the latest main branch? Have you tried resetting + resolving SPM package cache?

**Comment by EdisonE3** [comment]
After trying resetting + resolving for some times, the problem has been solved. Thanks!
