### ISSUE TITLE
How to add flags for compiler?

### ISSUE THREAD

**Issue by EdisonE3** [mozilla-mobile/firefox-ios#10638]
I want to remain the llvm ir generated from firefox-ios, so I need to add compiler flags such as **-emit-bc** and **-emit-ir**. I try to modify it in **build setting** shown as following, but it doesn't work:
<img width="991" alt="image" src="https://user-images.githubusercontent.com/52118917/166437979-620d6b56-01e3-4394-8e10-8d001b45ea15.png">
<img width="807" alt="image" src="https://user-images.githubusercontent.com/52118917/166438091-992bda5f-ee40-41c8-a2ab-6a155387d340.png">
So what can I do for getting llvm ir?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4179)

**Comment by lmarceau** [comment]
We use xcconfig files to setup Swift flags for our different targets. This is I think what you're searching for.
