### ISSUE TITLE
Firefox not respecting iOS password AutoFill preferences

### ISSUE THREAD

**Issue by ckeck** [mozilla-mobile/firefox-ios#10630]
## Steps to reproduce

Install and select 1Password as your only choice for password AutoFill on iOS. Attempt to log in to various websites via Firefox using the “Password” quick option on the keyboard bar.

### Expected behavior

Expect Firefox to trigger the 1Password dialog/modal box to verify and see available login options, as 1Password is the only AutoFill option selected in iOS settings.

### Actual behavior

Firefox iOS about 50-75% of the time will trigger the Firefox password manager pop up/modal instead of 1Password. This does not happen on every website, but more frequently than not, and I am not sure how or why. I do not have Firefox selected as an option for AutoFill in iOS settings at all, only 1Password.

This does not seem to happen on iOS/iPhone, but specifically Firefox on an iPad/iPad OS.

### Device & build information
* Device: Apple iPad Pro 11” (MU162LL/A)
* Build version: iOS/iPad OS 15.4.1
* FF Version: Firefox Daylight 99.3 (9185)
### Notes
Attachments: 

![81A29EBA-C1C1-44C7-B616-E15A1DBD88C0](https://user-images.githubusercontent.com/111589/166268541-e03647b4-5fc1-41b2-b692-addaaed73f48.png)
![BD945186-39A4-49D6-ACA3-F7F2DF51DFCE](https://user-images.githubusercontent.com/111589/166268567-5b2975e4-cbb8-4b64-90c2-374900cebfcd.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4178)

**Comment by ckeck** [comment]
I am not sure if it’s loading/popping up the Firefox password manager or Apple Keychain, but neither of these are selected in the iOS settings, only 1Password.

I should note that this behavior is not present in any other application or browser. Every other app and browser will properly load 1Password as expected, 100% of the time. This would seem to rule out both an iOS and a 1Password issue and seems to be something specific to Firefox on iPads.

**Comment by SimonBasca** [comment]
Hello and thanks for the patience. Is there any chance you can check if this scenario is working with Safari?

**Comment by elight** [comment]
It works in Safari. It doesn't work in Firefox.

**Comment by elight** [comment]
Password autofill does work. However, email autofill does not on, for example, Google authentication. The Auth page presents only an email prompt. Autofill doesn't seem to recognize a need to prompt here.

**Comment by SimonBasca** [comment]
@elight I noticed that you are using an older version of Firefox. Could you please upgrade to the latest version and let me know if the issue is still reproducible.

**Comment by elight** [comment]
iOS seems convinced that I'm current. v102.

behavior persists
