### ISSUE TITLE
Startup crash on older iOS versions

### ISSUE THREAD

**Issue by csuciu** [mozilla-mobile/firefox-ios#10645]
v100.1 (9338)
iPhone 6S 13.7
iPad Air 14.0.1
iPhone 11 14.2

1. Install Firefox.
1. Try to launch Firefox.

Result: The app can't be launched because it crashes at startup.
[Client-2022-05-03-182558.ips.beta.zip](https://github.com/mozilla-mobile/firefox-ios/files/8611749/Client-2022-05-03-182558.ips.beta.zip)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4185)

**Comment by csuciu** [comment]
The crash is not reproducible on iOS 14.7.1.

**Comment by nbhasin2** [comment]
@lmarceau has a fix coming up

**Comment by nbhasin2** [comment]
https://github.com/mozilla-mobile/firefox-ios/pull/10647 - Fixed

**Comment by csuciu** [comment]
No longer reproducible on v100.1 (9343). Verifying as fixed.
