### ISSUE TITLE
Some icons are missing in the "Recently saved" section

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#10644]
## Steps to reproduce
1. Visit "twitter.com"
2. Bookmark the page
3. Close the tab
4. Visit "Facebook.com"
5. Bookmark the page
6. Close the tab
7. Visit "Biziday.ro"
8. Bookmark the page
9. Close the tab
### Expected behavior
- The icons should be visible in the "Recently saved" section
### Actual behavior
- The icons for Twitter and Biziday are not visible in the "Recently saved" section
### Device & build information
* Device: iPhone 12 Pro (15.4)
* Build version: 100.1 (9338)
### Notes
Attachments: 

https://user-images.githubusercontent.com/32130829/166486323-74426d48-9c70-4dac-9d40-542a39783d70.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4184)

**Comment by lmarceau** [comment]
@SimonBasca I think this relates to https://github.com/mozilla-mobile/firefox-ios/issues/9687

**Comment by SimonBasca** [comment]
@lmarceau you are correct. Let's close this one as duplicate of https://github.com/mozilla-mobile/firefox-ios/issues/9687
