### ISSUE TITLE
Recently Visited list from the homepage is not cleared after clearing private data

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#10656]
## Steps to reproduce
1. Enable Recently Visited
2. Visit 9 pages
3. Close all tabs
4. Go to Settings- > Data Management -> Tap "Clear Private Data"
### Expected behavior
- Recently Visited  list from the homepage should be cleared
### Actual behavior
- Recently Visited list from the homepage is not cleared.
### Device & build information
* Device: iPhone 13 mini (15.4.1)
* Build version: 100.1 (9352)
### Notes
Was fixed in https://github.com/mozilla-mobile/firefox-ios/issues/10532
Attachments: 

https://user-images.githubusercontent.com/32130829/166684376-847d0c39-9a73-4b9c-9851-b3d1c8fe6a90.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4192)

**Comment by csuciu** [comment]
Verified as fixed on v100.1 (9384).
