### ISSUE TITLE
The sites visited in Private Browsing are recorded in "Recently visited" list

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#10659]
## Steps to reproduce
1. Go to Private browsing
2. Visit a few sites
3. Check the "Recently visited" list
### Expected behavior
- The sites visited in Private Browsing should not be recorded in "Recently visited" list
### Actual behavior
- The sites visited in Private Browsing are recorded in "Recently visited" list
### Device & build information
* Device: iPhone 12 Pro (15.4)
* Build version: 100.1 (9352)
### Notes
Attachments: 

https://user-images.githubusercontent.com/32130829/166729594-5230732b-961e-4778-bac8-e5e13147b99b.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4194)

**Comment by csuciu** [comment]
Verified as fixed on v100.1 (9384)
pull req https://github.com/mozilla-mobile/firefox-ios/pull/10668
