### ISSUE TITLE
The order in the "recently visited" list is not the same as in the History list.

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#10654]
## Steps to reproduce
1. Visit a few site in this order : facebook, twitter, amazon, wikipedia, google and a google search of "biziday".
2. Check the order in the History list
3. Check the order in the "Recently Viewed" list
### Expected behavior
- The order should be consistent in both lists.
### Actual behavior
- The order in the "recently visited" list is not consistent with the History list. 
### Device & build information
* Device: iPhone 13 mini (15.4.1)
* Build version: 100.1 (9352)
### Notes
Attachments: 

https://user-images.githubusercontent.com/32130829/166679104-9e6e39cf-38bb-4eae-8f38-fc223597aa3b.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4190)

**Comment by electricRGB** [comment]
Heya. This is the expected behaviour. The order of Recently Visited is done by a weight calculation and so will not be in chronological order. The title of the section is misleading and we do have an issue open for that. History will be chronological (mostly).

Ty! :D
