### ISSUE TITLE
 History is not correctly cleared after clearing "Today & Yesterday"

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#10652]
## Steps to reproduce
1. Visit one site
2. Go to History
3. Tap "Trash can" icon
4. Tap "Today & Yesterday"
### Expected behavior
- History should be cleared.
### Actual behavior
- History is not cleared.
### Device & build information
* Device: iPhone 13 mini (15.4.1)
* Build version: 100.1 (9352)
### Notes
Attachments: 

https://user-images.githubusercontent.com/32130829/166667108-e96e3e16-f2d0-452d-9a53-03aacb0a97bd.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4189)

**Comment by csuciu** [comment]
Verified as fixed on v100.1 (9384)
