### ISSUE TITLE
 History is not correctly cleared after clearing all private data

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#10655]
## Steps to reproduce
1. Visit one site
2. Go to Settings -> Data management -> Tap "Clear Private Data"
3. Visit another site
4. Go to Settings -> Data management -> Tap "Clear Private Data"
### Expected behavior
- All history items should be cleared.
### Actual behavior
- The items are not correctly cleared. After restarting the app they will be cleared.
### Device & build information
* Device: iPhone 13 mini (15.4.1)
* Build version: 100.1 (9352)
### Notes
Attachments: 

https://user-images.githubusercontent.com/32130829/166679860-15bc36c7-8c23-41ae-997f-524e4b2ec48f.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4191)

**Comment by csuciu** [comment]
Verified as fixed on v100.1 (9384)
