### ISSUE TITLE
Update package.json dependencies

### ISSUE THREAD

**Issue by lmarceau** [mozilla-mobile/firefox-ios#10671]
Update package.json dependencies

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4200)

**Comment by data-sync-user** [comment]
➤ Laurie Marceau commented:

For QA, let’s make sure there’s no behavior change on the web related features we have with javascript injections like: Nightmode, find in page, passwords autofill, tracking protection, downloading blob: files, no image mode, reader mode, printing a page, content blocker etc.
