### ISSUE TITLE
Inactive tabs is terrible idea - how to disable feature

### ISSUE THREAD

**Issue by yoDon** [mozilla-mobile/firefox-ios#10686]
## Steps to reproduce

A s someone who keeps lots of tabs in my browser, all I had to do was open my tab list.

### Expected behavior

I expect to scroll through my tabs list, see the pages, be reminded of content in them.

### Actual behavior

I see a huge list of FavIcons and Domain names. There's a dozen tabs that just say "Medium". Others just say "YouTube.com" or "ycombinator.com" for anything from hacker news.

It's hard to remember when a single UI "update" in any product I used subtracted as much value as this change has.
 
 Is there no way to turn this feature off? I've used Firefox for years on my iPhone, but if I'm going to have to go through and individually re-open and re-order every one of the tabs in my "inactive" tabs list, it will be to copy the URLs and transfer them to another browser. 
 
Single worst product update I have ever experienced. Huge negative impact on functionality. It's not even listed in the what's new feature list in the App Store. 

### Device & build information
* Device: iPhone 11
* Build version: App Store

### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4207)

**Comment by yoDon** [comment]
For those who find this page while trying to figure out how disable this feature, here's how to disable the Inactive Tabs feature in Firebox on iOS:

- Click on the the three-horizontal-lines icon (aka the "Hamburger" button)
- Click on Settings
- Click on Tabs
- Turn off "Inactive Tabs"
- Rejoice, your tabs are back
-

**Comment by jmooo** [comment]
There is no “Tabs” option in the Settings menu

**Comment by SimonBasca** [comment]
@jmooo do you see the "Inactive tabs" in tabs tray?

**Comment by gelsbern** [comment]
Tap the version info at the bottom 5 times.  You will see extra settings.  Inactive Tabs is there.

**Comment by cpeterso** [comment]
You can also disable inactive tabs functionality without using the secret settings. Open Settings > Browsing menu> uncheck Inactive Tabs.
