### ISSUE TITLE
TabContentScripts and TabContentsScripts both exist

### ISSUE THREAD

**Issue by gutley** [mozilla-mobile/firefox-ios#10691]
Both Client/FrontEnd/TabContentsScripts and Client/FrontEnd/TabContentScripts are still live in the repo, containing the same files.

Looking at the project file, I guess TabContentsScripts is the 'real' one, but leaving the other one there is confusing and has already resulted in an unneeded SwiftLint 'fix'.

Can we properly expunge the incorrect folder.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4209)

**Comment by lmarceau** [comment]
Sure, files in there are duplicated and aren't part of Xcode project. So the folder that isn't part of Xcode is the one that needs to be removed. Opened a PR for that https://github.com/mozilla-mobile/firefox-ios/pull/10695
