### ISSUE TITLE
Stop Littering the Documents folder with useless Wallpaper files

### ISSUE THREAD

**Issue by gutley** [mozilla-mobile/firefox-ios#10731]
Why are we saving all the wallpapers in the Documents folder, especially since the user can't do anything useful with them (i.e they can't be opened as images).

Surely these belong either in Application Support or the Caches folder, where they won't be noise to anyone in the Files app.

https://user-images.githubusercontent.com/2040690/168041233-92312ba9-268f-4bf0-a28b-92ee76ae7df4.MP4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4227)

**Comment by data-sync-user** [comment]
➤ Roux Buciu commented:

QA testing notes:

  * v101 → This PR
    * in 101, you should keep the app open so it can download the wallpapers
    * verify that the wallpapers folder is in the documents folder (Files → On My iPhone → Firefox)
    * Update to this PR
    * Verify that the folder is no longer there after updating & opening the app
    * verify that the two downloadable wallpapers are still available (Customize Homepage → Wallpapers → There should be 6 wallpapers in total)

  * fresh install
    * wallpapers should download as previously, BUT they shouldn’t show up in the Files app

**Comment by data-sync-user** [comment]
➤ Catalin Suciu commented:

* v101 → This PR
    * in 101, you should keep the app open so it can download the wallpapers 
    * verify that the wallpapers folder is in the documents folder (Files → On My iPhone → Firefox) ✅ 
    * Update to this PR
    * Verify that the folder is no longer there after updating & opening the app ✅ 
    * verify that the two downloadable wallpapers are still available (Customize Homepage → Wallpapers → There should be 6 wallpapers in total) ✅ 

  * fresh install
    * wallpapers should download as previously, BUT they shouldn’t show up in the Files app ✅ 

Verifying as fixed on v102.0 (11005)
