### ISSUE TITLE
Remove snapkit from reader mode

### ISSUE THREAD

**Issue by lmarceau** [mozilla-mobile/firefox-ios#10736]
For QA, we can make sure reader mode has no changes (stays the same behavior and UI wise)

Relates to https://github.com/mozilla-mobile/firefox-ios/issues/8592

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4230)

**Comment by gutley** [comment]
@lmarceau - Out of curiosity, why is SnapKit slowly being removed from the project? I find it far more friendly than the native APIs to use and read.

**Comment by gutley** [comment]
Fair enough.

"Another dependencies we wanna remove is SwiftyJSON, native works well too there" - I feel your pain, my fork brings in other packages, and several of them all also bring in their own JSON parsing/handling code.

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verified fix on main 9eea0a004e02ebdce2a6acd4e48b841212aba05b. Reader mode is functioning as expected.
