### ISSUE TITLE
The visited tab is visible in the jump back section

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/firefox-ios#10744]
## Steps to reproduce
1. Visit any webpage.
1. Open a new tab.
1. Open the tabs tray and close all tabs.
    1. Expected behavior
The visited website that was deleted from the tabs tray, should not be displayed in the jump back section anymore.
    1. Actual behavior
The visited tab is visible in the jump back section. 
    1. Device & build information

* Device: iPhone 12 Pro (15.4).
* Build version: 9000 (9536).
    1. Notes
After the homepage is refreshed the visited tab will no longer be displayed in the jump back section
Attachments: 

https://user-images.githubusercontent.com/42831109/168287379-71821bab-2388-476b-9a46-e07c29ebf1b4.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4234)

**Comment by lmarceau** [comment]
This is a recent regression I think. When you click on that jump back in cell it doesn't crash, it opens the tab.
