### ISSUE TITLE
Opening setting from contextual menu doesn't update the sponsored tiles state

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#10755]
Opening the Top sites settings menu from the contextual menu settings option on a sponsored tile doesn’t update the top sites section on the home page.

**Steps to reproduce**

1. Have sponsored tiles in your top sites
1. Long press on a sponsored tile
1. Click on the settings option
1. Disable the sponsored shortcuts
1. Click on “Done“

**Expected**

Sponsored tiles aren’t on the home page anymore

**Actual**

Sponsored tiles are still there

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4241)

**Comment by csuciu** [comment]
Verifying as fixed on v9000(9585).
