### ISSUE TITLE
Excessive use causes overheating?

### ISSUE THREAD

**Issue by mjhymowitz** [mozilla-mobile/firefox-ios#10765]
## Steps to reproduce
1. Have 150+ tabs in normal or private browsing mode with content loaded on them.
1. Use the app for extended period of time (in my case reading novels or manga)

### Expected behavior
Phone remains cool 
Using Status Lite app CPU usage remain under 15%
Functions normally with. No lag closing a tab.

### Actual behavior
After prolong usage the phone starts to heat up in the bottom right (SIM card area) causing discomfort to hold. Causing IOS to reduce max brightness of the device to counter the over heating issue. Forcing user to restart their phone or put down the phone for period of time to let it cool down.

Using Status Lite app CPU usage jumps to 30% and I have seen it reach as high as 58% usage.

I have also notice some lag when deleting tabs.

### Device & build information
* Device: iPhone 11
* Build version: Firefox Daylight 100.1 (9384)

### Notes
I am not 100% sure that Firefox ios app is the cause, but his has happen consistently when using the Firefox app for a prolong period of time. The odd thing is that making me question if Firefox is the cause is because the iOS battery setting doesn’t show that Firefox is using excessive amount of power. I have tried reinstalling the OS and the app already with no change to this issue. I can’t remember when this started, but i think it’s been happening since fall of 2021. (Been using the phone much more often since fall so the problem has stood out more.)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4245)

**Comment by drpoutine** [comment]
Issue is still persistant in the latest builds of Firefox-iOS on TestFlight using iPad on latest iPadOS beta at the time of this writing. Results in heavy battery drain and increase heat output

**Comment by edaniels** [comment]
Seeing this as well with one tab open (low res news site).
