### ISSUE TITLE
Address Bar isn't Minimum When Scrolling Page

### ISSUE THREAD

**Issue by MarkSky** [mozilla-mobile/firefox-ios#10767]
## Steps to reproduce
1. I use the Firefox in iPhone to open the [website](https://54dpf0.csb.app/)
1. I scroll the page, but the address bar isn't minimum.

### Expected behavior
The address bar should be minimum as it in Safari.

### Actual behavior
The address bar doesn't change.

### Device & build information
* Device: iPhone 13 mini
* Build version: Firefox Daylight 100.1(9384)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4247)

**Comment by lmarceau** [comment]
Hello! Thanks for opening this ticket. Do you mean that the address bar isn't minimized?

**Comment by MarkSky** [comment]
Yes. The address bar isn't minimized.
After scrolling the page, should be:
![S__2777181](https://user-images.githubusercontent.com/4032734/168937821-42244fa4-09b0-48b9-8b0f-9f48a33c6c26.jpg)

But it's not minimized:
![S__2777186](https://user-images.githubusercontent.com/4032734/168937935-bcc83ffd-35c1-49a2-beed-272ad26bd485.jpg)

I think there are some doms in position fixed, and address bar won't be minimized.
