### ISSUE TITLE
The entry is removed from the "Recently Viewed" list after opening it in a new private tab

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#10772]
## Steps to reproduce
1. Have some entries in "Recently Viewed"(e.g Wikipedia)
1. Go to the history panel 
1. Long press on the Wikipedia entry
1. Tap "Open in New Private Tab"
1. Check the "Recently Viewed" list
    1. Expected behavior

* The recent Wikipedia entry is removed from the "Recently Viewed" list.
    1. Actual behavior
* The recent Wikipedia entry should still be visible in the "Recently Viewed" list
    1. Device & build information
* Device: iPhone 12 Pro(15.4)
* Build version:  main df59f9502b4ea01a1a5e1fbf78eb4fe93ba4aee5
    1. Notes
Attachments: 

https://user-images.githubusercontent.com/32130829/168773261-6eb04fd1-ed23-49bd-802f-df580ce82605.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4249)

**Comment by dnarcese** [comment]
Was Wikipedia already visited in a normal tab? It looks like that is where the entry is coming from.
I tried opening a history item in a new private tab that is not already in Recently Visited, and it did not appear there.

**Comment by SimonBasca** [comment]
@dnarcese the issue I was seeing is that after visiting a page in normal browsing the entry was added to the recently saved list. After long pressing and opening it in a private tab the entry was removed. In my opinion the behavior is incorrect to remove the page from the recently saved list after visiting it in a private tab.
