### ISSUE TITLE
Firefox is unresponsive after scrolling the history list

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#10771]
## Steps to reproduce
1. Have some synced history
2. Go to history panel
3. Scroll the history list
### Actual behavior
- Firefox is unresponsive after a few scrolls.
### Device & build information
* Device: iPhone 13 mini(15.4.1)
* Build version: release 100.1 and main df59f9502b4ea01a1a5e1fbf78eb4fe93ba4aee5
### Notes
Attachments: 

https://user-images.githubusercontent.com/32130829/168772101-d5f118d1-b84b-4685-9942-3f24317b239f.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4250)

**Comment by data-sync-user** [comment]
➤ Yoana Rios Diaz commented:

Improvement fix for v101 to reduce risk for the release  (https://github.com/mozilla-mobile/firefox-ios/pull/10829 ( https://github.com/mozilla-mobile/firefox-ios/pull/10829|smart-link )) to cancel pending request improving the responsiveness. 

Another PR will be done to main adding a spinner (UIActivityIndicator) to fix the issue

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verifying as fix on v101 (9723).
