### ISSUE TITLE
Warning: linking against a dylib which is not safe for use in application extensions part 2

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#10783]
Investigate if this warning needs to be fixed and relevant. If it's not relevant can we find a way to remove it so this doesn't pollute our buildtime warnings navigator?

![Screen Shot 2022-03-29 at 5 08 55 PM](https://user-images.githubusercontent.com/11338480/160707567-ab62fdbe-74c8-4d7c-b860-f5281bb839ae.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4256)

**Comment by lmarceau** [comment]
Part 1 https://github.com/mozilla-mobile/firefox-ios/issues/10342 fixed some of those warnings (linking against dylib). Let's aim with part 2 to fix all of the remaining ones.
