### ISSUE TITLE
The left and right margin to the Shortcuts titles is too small

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#10797]
## Steps to reproduce
1. Have some shortcuts with long title synced
2. Check the left and right margin of the homepage shortcuts
### Expected behavior
- The left and right margin should be increased
### Actual behavior
- The left and right margin is too small
### Device & build information
* Device: iPhone 12 Pro (15.4)
* Build version: 101.0 (9619)
### Notes
Attachments: 

![image](https://user-images.githubusercontent.com/32130829/169039653-fec28d0f-1bfd-47ee-b639-7884d17261b7.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4263)

**Comment by data-sync-user** [comment]
➤ Daniela Arcese commented:

To mitigate this issue, I wonder if we can move where the pin icon is located

**Comment by data-sync-user** [comment]
➤ Laurie Marceau commented:

Daniela Arcese FYI In my latest PR ( https://github.com/mozilla-mobile/firefox-ios/pull/10895 ) I made sure there’s a spacing between labels (of 8 px). So this issue is mitigated.

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verifying as fix on main 64bf807289a0de0a8f60db903477cc68652de9d9
