### ISSUE TITLE
"contextual_menu" with an extra of "settings" event is not displayed

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#10803]
## Steps to reproduce
1. Have VPN set to one of the following locations: US, CA, UK, DE, FR.
2. Go to Homepage and long tap on a Sponsored tile and tap on the "Settings" button.
### Expected behavior
- An event ping is generated.
### Actual behavior
- The "contextual_menu" with an extra of "settings" event is not generated in the event ping.
### Device & build information
* Build version:  101.0 (9619)
### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4268)

**Comment by lmarceau** [comment]
When we click on settings in the contextual menu (from a sponsored tile), we should get the telemetry event: `contextual_menu` with an extra of `settings`. I'm confused where this `contile_settings` is coming from

**Comment by SimonBasca** [comment]
@lmarceau I assume that this event "contile_settings" will be triggered as this is what we used on Android. I will double check if `contextual_menu` with an extra of `settings` is triggered on our side and update the ticket accordingly. Thanks.

**Comment by lmarceau** [comment]
@SimonBasca we don't have a perfect match with Android settings at the moment, sorry for trouble!

**Comment by SimonBasca** [comment]
@lmarceau I've updated the ticket. I was unable to view the event `contextual_menu` with an extra of `settings` after long pressing on a sponsored tile and tapping "Settings".

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

I’ve recheck and was able to correctly see the event on v101.0 (9687). Sorry for the confusion. Closing the issue.
