### ISSUE TITLE
open_contile_in_private_tab is not generated

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#10802]
## Steps to reproduce
1. Have VPN set to one of the following locations: US, CA, UK, DE, FR.
2. Go to Homepage and long tap on a Sponsored tile and tap on the "settings" button.
### Expected behavior
- The event is not generated.
### Actual behavior
- An event ping is generated.
 "open_contile_in_private_tab"
### Device & build information
* Build version:  101.0 (9619)
### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4269)

**Comment by lmarceau** [comment]
@SimonBasca 
When we click on settings in the contextual menu, we should get the telemetry event: `contextual_menu` with an extra of `settings`. When we click on open in private tab in the contextual menu, there's no telemetry tracking in place at the moment so we should get any events

**Comment by SimonBasca** [comment]
Thanks for clarifying Laurie. Closing the issue.
