### ISSUE TITLE
"topsites-impression" ping is generated multiple times. 

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#10813]
## Steps to reproduce
1. Have VPN set to one of the following locations: US, CA, UK, DE, FR.
2. Go to Homepage and tap on a Sponsored tile
3. Generate the event ping
### Expected behavior
- `topsites-impression` ping is generated once.
### Actual behavior
- `topsites-impression` ping is generated multiple times. 
### Device & build information
* Device: iPhone 12 Pro (15.4)
* Build version: 101.0 (9652)
### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4272)

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verifying as fix on 101.0 (9723)
