### ISSUE TITLE
Page does not load at c00.adobe.com

### ISSUE THREAD

**Issue by softvision-raul-bucata** [mozilla-mobile/firefox-ios#10812]
## Steps to reproduce
1. Navigate to: https://c00.adobe.com/v3/b3367087-ad7f-456c-9391-f3e29902ec2c/start?a_dl=6193cc37ad495036acfe550d.
2. Observe the result.
### Expected behavior
The page loads
### Actual behavior
The page does not load
### Device & build information
* Device: iPhone 8 running iOS 15.4
* Build version: Firefox Daylight  Firefox Daylight 100.1 (9384)
### Notes
1. Reproducible regardless of the status of Tracking Protection.
2. Reproducible on the latest build of Firefox .
3. Works as expected using Safari.
4. Originally reported here: https://github.com/webcompat/web-bugs/issues/104561

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4271)

**Comment by StaberindeZA** [comment]
Just 1 additional note, I noticed that when previewing the URL, the page does load as well.

![image](https://user-images.githubusercontent.com/10620585/171946441-4dc2f2b8-c714-4317-aed8-acc60327ec53.png)

**Comment by data-sync-user** [comment]
➤ Laurie Marceau commented:

For QA, as a supplement to the STR above, we can also do some exploratory testing with navigation of web pages (loading webpages, back, forward navigation, etc)

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verifying as fix on main 10895c167d3b4ef944b89ae7037a42b4292a4d4c
