### ISSUE TITLE
Search group on tab screen defaults to showing the first tab in the search group instead of the current tab (in search group or not)

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/firefox-ios#10823]
## Steps to reproduce

1. Create a new search group by opening a new search tab and long pressing to open multiple search results in new tabs. 
2. Switch to one of the new tabs. 
3. Open the tab screen. 

### Expected behavior

The current tab should be visible on the tab screen, whether it is in a search group or not. 

### Actual behavior

If the current tab is in the search group, it is off screen because the search group defaults to showing only the first two tabs. You have to scroll the search group to see the current tab.

If the current tab is not in the search group, the tab screen stop shoes the search group instead of scrolling the tab screen down to shoes the current tab.

### Device & build information

* Device: iPhone 12
* Build version: 101.0 (9619)

### Notes

Attachments: 

![6823E703-E8A2-4D62-807D-4FBB56BBF4E3](https://user-images.githubusercontent.com/629193/169444491-065214c5-f38a-4b15-8b5b-30e7273f0a6a.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4279)

**Comment by SimonBasca** [comment]
I believe this is a duplicate of https://github.com/mozilla-mobile/firefox-ios/issues/9337.

**Comment by cpeterso** [comment]
> I believe this is a duplicate of #9337.

Thanks. As in originally described this bug in the first comment, I think this is a duplicate of #9337.

However, I think we should leave this big open because I have since noticed a new bug with almost the same description: when the current tab is not in the search group, the tab screen stop doesn't scroll the current tab into view. I think we can reuse this current bug report if edit my bug description a little.

**Comment by cpeterso** [comment]
Changeb of plans: I will close those bug as a duplicate of the bug you filed. The new bug I’m seeing is unrelated to search groups and is a new regression in v101.0.

**Comment by cpeterso** [comment]
Duplicate of #9337

**Comment by cpeterso** [comment]
New bug: #10857
