### ISSUE TITLE
No space between the top sites long titles

### ISSUE THREAD

**Issue by csuciu** [mozilla-mobile/firefox-ios#10832]
v101.0(9687)
iPhone 12 Pro (15.5)

* Have two consecutive long title entries in Top Sites.

Expected: There should be a space between the titles.

Result: There is no space between the titles.

Please see:
![Top Sites](https://user-images.githubusercontent.com/1866605/169549518-ea41b96d-3eab-4a09-ab3c-543695dbbab5.jpeg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4284)

**Comment by lmarceau** [comment]
I think this is the same as https://github.com/mozilla-mobile/firefox-ios/issues/10797

**Comment by lmarceau** [comment]
I'll close it as duplicate, please reopen if this is a mistake
