### ISSUE TITLE
App crashes to iOS Lock screen when interacting with the tabs tray

### ISSUE THREAD

**Issue by csuciu** [mozilla-mobile/firefox-ios#10854]
v101.0 (9723)
iPhone 12 Pro (15.5)

 - I had 8 normal tabs open and I opened another 50 via the option from the debug menu. 
 - I left the app in background for a few hours. In this time the app was killed by the OS. 
 - When I reopen it and tried to interact with the tabs tray by scrolling the tabs list or tap on a tab to open it, the app started to crash to the iOS Lock screen without showing the crash reporter or creating crash logs in the internal memory.

Will try to find proper STRs.

https://user-images.githubusercontent.com/1866605/170286547-ec85584f-ce8e-4bab-93b0-38bf9de27649.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4293)

**Comment by dnarcese** [comment]
This could be an iOS issue since it crashing to the lockscreen
