### ISSUE TITLE
Only one shortcut per domain can be added to Homepage

### ISSUE THREAD

**Issue by matthme** [mozilla-mobile/firefox-ios#10859]
## Steps to reproduce

1. Go to https://en.m.wikipedia.org/wiki/Firefox
2. Add it to Shortcuts via the burger menu in the bottom right corner
3. Go to https://en.m.wikipedia.org/wiki/Web_browser
4. Add it to Shortcuts via the burger menu in the bottom right corner

### Expected behavior

Both shortcuts are being displayed on the Homepage.

### Actual behavior

The first shortcut will be replaced by the second shortcut - assumingly because it is of the same domain. Same behavior appears with other domains.

### Device & build information
* Device: Iphon 6s
* Build version: Firefox Daylight 98.2 (8475)
### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4299)

**Comment by lmarceau** [comment]
Thanks @matthme, just opened a PR and the following case will now be possible (multiple pinned tiles with the same domain):
![Screen Shot 2022-05-26 at 2 27 22 PM](https://user-images.githubusercontent.com/11338480/170552515-856061a8-fc72-48fa-a360-8c2add6d140e.png)

**Comment by matthme** [comment]
Amazing, thanks! Judging from the screenshot your PR would also resolve issue #10860, am I right?

**Comment by lmarceau** [comment]
Well technically it's already done :) I think what you describe in https://github.com/mozilla-mobile/firefox-ios/issues/10860 was released in v100.1. I would suggest you upgrade to the latest version on the App Store to test it and see if this is what you described?

**Comment by matthme** [comment]
Indeed, you're right.

**Comment by doodooface** [comment]
This hug is still happening to me on Firefox Daylight 101.1 (10346)
