### ISSUE TITLE
Bitrise: SPM_Nightly_Beta_Only workflow does not work on M1

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/firefox-ios#10887]
We talked about changing the workflow to use M1 and Elite so that it runs faster to reduce credit usage. Unfortunately, that does not seem to work :/ 

See error: 
https://app.bitrise.io/build/f1e91e0a-9002-4d30-ad2c-7829d5c9f197

Opening this issue to go back to previous set up with Intel.
cc @nbhasin2 to let you know

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4312)

**Comment by nbhasin2** [comment]
@isabelrios this is a strange error that I have never encountered. 

I'll take a look at this and get back to you.

**Comment by isabelrios** [comment]
yeah, it started with the change to M1, I don't think we have tried that archive step before in a M1, haven't we? hope the PR fixes this for now by using again an Intel (g8 instead of g4, to at least increase the speed of the build)

**Comment by isabelrios** [comment]
Re-opening this issue, the workflow works because we went back to set Intel as it was working before, the issue with M1 has not been fixed
