### ISSUE TITLE
Avoid linebreak in words

### ISSUE THREAD

**Issue by topotropic** [mozilla-mobile/firefox-ios#10899]
## Steps to reproduce
Switch to german

### Expected behavior
No break in words

### Actual behavior
Break last letter of "Lesezeichen" ends up in new line
![IMG_F3361BC2025B-1](https://user-images.githubusercontent.com/353960/171612753-9b786da8-637a-4d22-b344-ef979a9957a9.jpeg)

Is there a way to programmatically prevent this from happening?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4319)

**Comment by lmarceau** [comment]
> There is one main solution to prevent this from happening, programatically speaking, and that's to allow the text to get small enough that it'll fit on the line. This means that that any label that needs to fit, size wise, will be smaller than the rest of the labels. However, there's a larger impart based on accessibility (ie, if someone sets their text to 5XL, this will probably happen anyway).

There's still this one ticket we have opened to change adapt the menu when there's not enough space https://github.com/mozilla-mobile/firefox-ios/issues/10119. We would wrap on two lines when for example in this case "Lesezeichen" and "Hinzufügen" cannot fully fit on one line. Not exactly straightforward to detect and adapt the menu, but theoretically possible. I would refrain from from allowing text to get smaller, this would look wonky in the menu (and as you said, for a11y it's not great).

**Comment by dnarcese** [comment]
Going to close this ticket in favor of #10119
