### ISSUE TITLE
Telephone = no

### ISSUE THREAD

**Issue by marcsangnier** [mozilla-mobile/firefox-ios#10919]
The following tag does not work :
<meta name="format-detection" content="telephone=no"/>

Latest version of Firefox for iOS.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4332)

**Comment by lmarceau** [comment]
@marcsangnier Thanks for opening the ticket. It seems information is missing on the ticket, would you mind explaining what you mean by tag and telephone? If you want to attach images on the ticket, please do so directly on the Github website.
