### ISSUE TITLE
[Accessibility] The address overlaps with the "Pin" button when longpressin on website shortcut

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#10924]
## Steps to reproduce
1. Increase Large text to maximum
1. Long press on a website shortcut.
  1. Actual behavior

* The address overlaps with the "Pin" button
  1. Device & build information
* Device: iPhone 12 Pro (15.4)
* Build version: main 176a0f8578a78e652407b322e5bf2176e616e636
  1. Notes
Attachments: 

![Context menu](https://user-images.githubusercontent.com/32130829/172160006-2fa9a989-c6ca-4c59-ac63-cc5680c697ed.jpeg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4337)

**Comment by data-sync-user** [comment]
➤ Sorin Paraipan commented:

Seems that it was fixed.

!screenshot.jpeg|width=1170,height=2532!
