### ISSUE TITLE
[Accessibility] The bookmark panel button is not correctly displayed.

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#10925]
## Steps to reproduce
1. Increase Large text to maximum
1. Bookmark a page
1. Open the hamburger menu
1. Scroll to the bookmark panel button 
### Expected behavior

* The bookmark panel button should be correctly displayed.
### Actual behavior
* The bookmark panel button is not correctly displayed.
### Device & build information
* Device: iPhone 12 Pro (15.4)
* Build version: 176a0f8578a78e652407b322e5bf2176e616e636
### Notes
Attachments: 

![Bookmark](https://user-images.githubusercontent.com/32130829/172160535-98da2d22-570a-4441-8257-e27b96939ad8.jpeg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4336)

**Comment by thatswinnie** [comment]
Another example: In my case the text (remove & add) is cut off
<img width="288" alt="Screenshot 2022-12-14 at 14 45 48" src="https://user-images.githubusercontent.com/4530/207699513-2ededf5b-e209-409a-ad01-1f4a1a7beaf0.png">

**Comment by data-sync-user** [comment]
➤ Norberto Andres Furlan commented:

Alina Moldovan can you check this one? It has been here for a while. I am adding the FX 127 label. Thanks!
