### ISSUE TITLE
The default browser card button is cut on samall screen devices

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#10920]
## Steps to reproduce
1. Clean install main 42bb8dc61447541b984f21b33c8ae72e996899ea on iPhone SE 1st gen
2. Check the default browser card
### Actual behavior
- The default browser card button is cut.
### Device & build information
* Device: iPhone SE 1st gen (14.8)
* Build version: Fennec main 42bb8dc61447541b984f21b33c8ae72e996899ea
### Notes
Attachments: 

![Screenshot](https://user-images.githubusercontent.com/32130829/172137080-bc0add5b-6274-47c1-a3dd-4856e4511a60.jpeg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4333)

**Comment by lmarceau** [comment]
@SimonBasca Could you try again on latest main? I merged a commit 176a0f8578a78e652407b322e5bf2176e616e636 that should fix this.
