### ISSUE TITLE
"Show all" button is not functional after tapping a second time on it

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#10937]
## Steps to reproduce
1. Have some sites in "Recently visited"
2. Tap on "Show all"
3. Tap "Done" to dismiss the screen
4. Tap on "Show all"
### Expected behavior
- "Show all" button should be functioning correctly
### Actual behavior
- "Show all" button is not functional after tapping a second time on it
### Device & build information
* Device: iPhone 12 Pro (15.4)
* Build version: 64bf807289a0de0a8f60db903477cc68652de9d9
### Notes
- Not reproducible on v101 (9723)
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4347)

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verified fix on main 28f94f7484c41d148b6c188ca5c446f2f045d1f2
