### ISSUE TITLE
favicon.ico is in / , it looks for favicon.ico in every directory except / .

### ISSUE THREAD

**Issue by crucifyer** [mozilla-mobile/firefox-ios#10939]
favicon.ico is in / , it looks for favicon.ico in every directory except / .
I thought it was a bot because there were too many useless 404s on the server, but it was iOS firefox.
please fix it quickly
thank you.

## Steps to reproduce
browse site.

### Expected behavior
query /favicon.ico

### Actual behavior
not query /favicon.ico
every directory /user/favicon.ico /bbs/favicon.ico ...

### Device & build information
* Device: iPhone 13 Pro Max
* Build version: Firefox Daylight 101.0 (9723)
### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4348)

**Comment by crucifyer** [comment]
This is still not resolved.
When viewing https://framework.xenosi.de/exams/inputtypes.html

It's not normal to see https://framework.xenosi.de/exams/inputtypes.html/favicon.ico

**Comment by crucifyer** [comment]
```x.x.x.x "KR" urlopen.link http [09/May/2024:18:58:13 +0900] "GET / HTTP/1.1" 200 973 "-" "Mozilla/5.0 (iPhone; CPU iPhone OS 17_4_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) FxiOS/125.3  Mobile/15E148 Safari/605.1.15" "-"
x.x.x.x "KR" urlopen.link http [09/May/2024:18:58:19 +0900] "GET /favicon.ico HTTP/1.1" 404 31 "-" "Client/41348 CFNetwork/1494.0.7 Darwin/23.4.0" "-"
x.x.x.x "KR" urlopen.link http [09/May/2024:18:58:19 +0900] "GET /favicon.ico HTTP/1.1" 404 31 "-" "Client/41348 CFNetwork/1494.0.7 Darwin/23.4.0" "-"
x.x.x.x "KR" urlopen.link http [09/May/2024:18:58:19 +0900] "GET /apple-touch-icon.png HTTP/1.1" 301 5 "-" "NetworkingExtension/8618.1.15.10.15 CFNetwork/1494.0.7 Darwin/23.4.0" "-"
x.x.x.x "KR" urlopen.link http [09/May/2024:18:58:19 +0900] "GET /favicon.ico HTTP/1.1" 404 31 "-" "Client/41348 CFNetwork/1494.0.7 Darwin/23.4.0" "-"
x.x.x.x "KR" urlopen.link http [09/May/2024:18:58:19 +0900] "GET /favicon.ico HTTP/1.1" 404 31 "-" "NetworkingExtension/8618.1.15.10.15 CFNetwork/1494.0.7 Darwin/23.4.0" "-"
x.x.x.x "KR" urlopen.link http [09/May/2024:18:58:19 +0900] "GET /apple-touch-icon-precomposed.png HTTP/1.1" 301 5 "-" "NetworkingExtension/8618.1.15.10.15 CFNetwork/1494.0.7 Darwin/23.4.0" "-"
x.x.x.x "KR" urlopen.link http [09/May/2024:18:58:19 +0900] "GET / HTTP/1.1" 200 973 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_1) AppleWebKit/601.2.4 (KHTML, like Gecko) Version/9.0.1 Safari/601.2.4 facebookexternalhit/1.1 Facebot Twitterbot/1.0" "-"
x.x.x.x "KR" urlopen.link http [09/May/2024:18:58:20 +0900] "GET / HTTP/1.1" 200 973 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.0 Safari/605.1.15" "-"
x.x.x.x "KR" urlopen.link http [09/May/2024:18:58:21 +0900] "GET //favicon.ico HTTP/1.1" 404 31 "-" "Client/41348 CFNetwork/1494.0.7 Darwin/23.4.0" "-"


x.x.x.x "KR" urlopen.link http [09/May/2024:18:58:27 +0900] "GET /karvonen/ HTTP/1.1" 200 2509 "-" "Mozilla/5.0 (iPhone; CPU iPhone OS 17_4_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) FxiOS/125.3  Mobile/15E148 Safari/605.1.15" "-"
x.x.x.x "KR" urlopen.link https [09/May/2024:18:58:28 +0900] "GET /karvonen/ HTTP/1.1" 200 2509 "http://urlopen.link/" "Mozilla/5.0 (iPhone; CPU iPhone OS 17_4_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) FxiOS/125.3  Mobile/15E148 Safari/605.1.15" "-"
x.x.x.x "KR" urlopen.link https [09/May/2024:18:59:45 +0900] "GET /karvonen/ HTTP/1.1" 200 2509 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_1) AppleWebKit/601.2.4 (KHTML, like Gecko) Version/9.0.1 Safari/601.2.4 facebookexternalhit/1.1 Facebot Twitterbot/1.0" "-"
x.x.x.x "KR" urlopen.link https [09/May/2024:18:59:46 +0900] "GET /karvonen/ HTTP/1.1" 200 2509 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.0 Safari/605.1.15" "-"
x.x.x.x "KR" urlopen.link https [09/May/2024:18:59:47 +0900] "GET /karvonen//favicon.ico HTTP/1.1" 404 31 "-" "Client/41348 CFNetwork/1494.0.7 Darwin/23.4.0" "-"
```

This is the log when I visit https://urlopen.link/ and https://urlopen.link/karvonen/
Why is the favicon being looked up under the name CFNetwork?
Why is it looking up //favicon.ico and /karvonen//favicon.ico when I didn't even specify the location of the icon in the HTML document?
What is Facebot Twitterbot and what is it collecting about my browser without my knowledge?

**Comment by crucifyer** [comment]
#12617 #12660 #13345

```$ git clone https://github.com/mozilla-mobile/firefox-ios.git
Cloning into 'firefox-ios'...
remote: Enumerating objects: 223408, done.
remote: Counting objects: 100% (996/996), done.
remote: Compressing objects: 100% (519/519), done.
remote: Total 223408 (delta 593), reused 801 (delta 463), pack-reused 222412
Receiving objects: 100% (223408/223408), 678.64 MiB | 12.65 MiB/s, done.
Resolving deltas: 100% (158635/158635), done.
Updating files: 100% (8910/8910), done.
$ ls
firefox-ios/
$ find -type f -exec grep -Hi Facebot {} \;
$ find -type f -exec grep -Hi facebookexternalhit {} \;
$ find -type f -exec grep -Hi NetworkingExtension {} \;
```

I'm not the only one with this issue, and I can't find the agent name in the published source code.
I'll delete the app and forget about it.

**Comment by knedl1k** [comment]
The problem still persists.

**Comment by mattreaganmozilla** [comment]
What I’ve been able to see in testing so far is that we have code which is attempting to fetch the favicon at an incorrect URL (the full website url with favicon.ico simply appended, rather than the root website directory). This should be fixed soon along with some additional work for https://github.com/mozilla-mobile/firefox-ios/issues/20871.

I wasn’t able to observe any other problems related to the favicon.ico paths, however. @knedl1k @crucifyer If you are seeing additional favicon path issues beyond what is described above please LMK, and if so it would be helpful if you could provide a few more details and steps to replicate. Thank you.

**Comment by crucifyer** [comment]
@mattreaganmozilla 

https://github.com/mozilla-mobile/firefox-ios/issues/10939#issuecomment-2102535140
I couldn't find this in the source code.
I don't use firefox-ios anymore.
I can't believe it.
Test it with a webpage where you can see the server logs.
thank you.

**Comment by data-sync-user** [comment]
➤ Matt Reagan commented:

Closing, will be addressed and tested in https://mozilla-hub.atlassian.net/browse/FXIOS-9427 ( https://mozilla-hub.atlassian.net/browse/FXIOS-9427|smart-link ) (https://github.com/mozilla-mobile/firefox-ios/issues/20871 ( https://github.com/mozilla-mobile/firefox-ios/issues/20871|smart-link ) )

**Comment by cpeterso** [comment]
#20871
