### ISSUE TITLE
Firefox crashes after disabling all homepage options

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#10948]
## Steps to reproduce
1. Go to Homepage settings and disable "Shortcuts", "Jump in", "Recently saved", "Recently visited", "Recommended by Pocket"
2. Dismiss the settings screen
### Expected behavior
- Homepage should be blank
### Actual behavior
- Firefox crashes after dismissing the settings screen
### Device & build information
* Device: iPhone 12 pro (15.4)
* Build version: 28f94f7484c41d148b6c188ca5c446f2f045d1f2
### Notes
Attachments: 

https://user-images.githubusercontent.com/32130829/172614336-4dff7265-20c5-4d71-a3b7-f854ecb74315.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4352)

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Marking as verified fix on main b83ce4fd11fcee4508a9dd83dd2c68473ca9c096.
