### ISSUE TITLE
The onboarding bullets are selected incorrectly when swiping to change to the next slide

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#10953]
## Steps to reproduce
1. Clean install Fennec 28f94f7484c41d148b6c188ca5c446f2f045d1f2
2. Swipe left to view the next slide
### Expected behavior
- The second onboarding bullet should be selected.
### Actual behavior
- The first onboarding bullet should is selected. After swiping again the last bullet will be selected.
### Device & build information
* Device: iPhone 12 Pro (15.4)
* Build version: 28f94f7484c41d148b6c188ca5c446f2f045d1f2
### Notes
Attachments: 

https://user-images.githubusercontent.com/32130829/172626141-654b1f7b-673d-4d31-b63c-2d8cbe35ee57.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4356)

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verifying as fix on v102.0 (10804)
