### ISSUE TITLE
The "x" button from the URL is no longer displayed after the keyboard has been dismissed with the URL still focused

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#10952]
## Steps to reproduce
1. Visit a page
2. Tap on the URL bar
3. Scroll on the homepage to dismiss the keyboard
4. Check the URL
### Expected behavior
- The "x" button from the URL should be displayed.
### Actual behavior
- The "x" button from the URL is no longer displayed after the keyboard has been dismissed.
### Device & build information
* Device: iPhone 12 Pro (15.4)
* Build version: 28f94f7484c41d148b6c188ca5c446f2f045d1f2
### Notes
Attachments: 

https://user-images.githubusercontent.com/32130829/172625075-95272d03-bcac-4aca-8cf0-943916dd1c47.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4355)

**Comment by dnarcese** [comment]
This behaviour is correct - the x should only be present when you are in edit mode. I think what we can fix here so it is less confusing is to remove the blue highlight around the address bar. I am going to close this and open a new bug
