### ISSUE TITLE
[iPad] The Onboarding view does not fit the screen without having to scroll

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#10958]
## Steps to reproduce
1. Clean install Fennec 28f94f7484c41d148b6c188ca5c446f2f045d1f2 on iPad
2. Swipe to the last slide
### Expected behavior
- The Onboarding view should fit the screen without having to scroll
### Actual behavior
- The Onboarding view does not fit the screen without having to scroll
### Device & build information
* Device: iPad Pro (15.4)
* Build version: 28f94f7484c41d148b6c188ca5c446f2f045d1f2
### Notes
Attachments: 

![Screen Shot 2022-06-08 at 16 52 22](https://user-images.githubusercontent.com/32130829/172633907-2112cdc3-8e00-43d5-a3eb-0477204a3c2a.png)

![Screen Shot 2022-06-08 at 16 49 37](https://user-images.githubusercontent.com/32130829/172633618-79847426-b892-4beb-b9e4-a3b4b37a305d.png)

[Jira issue](https://mozilla-hub.atlassian.net/browse/FXIOS-4358)

**Comment by data-sync-user** [comment]
➤ Yoana Rios Diaz commented:

thank you Simion Basca I will focus on this device to investigate

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Also encountered this issue on iPhone SE 1st generation (14.8) .

!Iphone SE 1st gen 14.8.jpeg|width=320,height=568!

!iPhone SE 1st gen 14.8.1.jpeg|width=320,height=568!

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Yoana Rios Diaz we’ve retested this with the devices we have on v9000 (10270).

Reproducible on:

  * iPhone SE 1st generation (14.8)
  * iPad Pro 3rd generation (11 inch) (15.4)

Not Reproducible on

  * iPhone 13 mini (15.4)
  * iPhone 12 Pro (15.4)
  * iPad mini 5 (7.9 inches) (14.8) 
  * iPhone 13 Max (15.1.1)
  * iPad Pro 12.9 inch
