### ISSUE TITLE
On-boarding: Missing functionality for wallpaper

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#10957]
## Steps to reproduce
1. Clean install Fennec 28f94f7484c41d148b6c188ca5c446f2f045d1f2
2. Swipe to the wallpaper slide
3. Tap "Set Wallpaper"
### Expected behavior
- Wallpaper functionality is added: previewing and setting as mentioned in the design docs and acceptance criteria [here](https://mozilla-hub.atlassian.net/browse/FXIOS-3981)
### Actual behavior
- The view will switch to the last slide.
### Device & build information
* Device: iPhone 12 Pro(15.4)
* Build version: 28f94f7484c41d148b6c188ca5c446f2f045d1f2
### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4357)

**Comment by data-sync-user** [comment]
➤ Yoana Rios Diaz commented:

Simion Basca just to clarify is the issue that the wallpaper is not set in HomeScreen after the onboarding is done or that when we tap “Set wallpaper“ we move to the last screen?

The way the functionality was build is that when we select a wallpaper is previewed only in this screen, is only applied when Set wallpaper is tapped also it moves to the next screen according to the arrow in Figma see image below.

!Screen Shot 2022-06-08 at 10.39.34 AM.png|width=384,height=366!

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Thanks for clarifying Yoana Rios Diaz. This functionality is implemented and working as expected.
