### ISSUE TITLE
An extra spacing can be observed above the "Bookmark" button and below the "Remove" button

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#10950]
## Steps to reproduce
1. Tap on the hamburger menu
or 
1. Long press on a top site shortcut
### Expected behavior
- There should be no extra spacing
### Actual behavior
- An extra spacing can be observed above the "Bookmark" button and below the "Remove" button
### Device & build information
* Device: iPhone 12 Pro (15.4)
* Build version: 28f94f7484c41d148b6c188ca5c446f2f045d1f2
### Notes
Attachments: 

![Screen1](https://user-images.githubusercontent.com/32130829/172618631-b5c79e3a-afcb-4e90-909c-e5092a8504c0.jpeg)

![screen2](https://user-images.githubusercontent.com/32130829/172618629-ef4c0ba1-dbe9-40f0-a5ce-75d79ac41ef2.jpeg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4354)

**Comment by lmarceau** [comment]
@SimonBasca I think this is the same as https://github.com/mozilla-mobile/firefox-ios/issues/10194 - We have a fix underway for it (a PR was opened), we just need to upgrade our Xcode version to merge it

**Comment by SimonBasca** [comment]
@lmarceau I agree, it's the same issue as https://github.com/mozilla-mobile/firefox-ios/issues/10194. Closing as duplicate of https://github.com/mozilla-mobile/firefox-ios/issues/10194
