### ISSUE TITLE
The wallpaper blue selector is not displayed when first going to the wallpaper slide.

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#10963]
## Steps to reproduce
1. Clean install Fennec 28f94f7484c41d148b6c188ca5c446f2f045d1f2
2. Swipe to the wallpaper slide
3. Observe the wallpaper buttons
### Expected behavior
- The wallpaper buttons should have a blue selector on the blank background. This will be more intuitive to the user that the wallpapers can be selected from the on-boarding
### Actual behavior
- The wallpaper buttons blue selector is not displayed. After tapping on a wallpaper the blue selector will be displayed.
### Device & build information
* Device: iPhone 12 Pro (15.4)
* Build version: Fennec 28f94f7484c41d148b6c188ca5c446f2f045d1f2
### Notes
Attachments: 

https://user-images.githubusercontent.com/32130829/172810992-de2d922b-b932-41a8-a0bb-ece4c2c219a0.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4360)

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verifying as fix on v102.0 (10804).
