### ISSUE TITLE
Remove makeDynamicHeightSupport button extension function in favor of ResizableButton class

### ISSUE THREAD

**Issue by lmarceau** [mozilla-mobile/firefox-ios#10979]
Remove makeDynamicHeightSupport button extension function in favor of ResizableButton class. To ensure we have consistent way of having self sizing button

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4373)

**Comment by data-sync-user** [comment]
➤ Laurie Marceau commented:

For QA, we can test that customize home page button and default browser card button (that appears on home page) are all good

**Comment by lmarceau** [comment]
PR was https://github.com/mozilla-mobile/firefox-ios/pull/10980

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verified fix on v102 (11395)
