### ISSUE TITLE
New tab opens every time Firefox is minimized

### ISSUE THREAD

**Issue by Floreadore** [mozilla-mobile/firefox-ios#10971]
## Steps to reproduce
With any number of tabs open, switch/multitask away from Firefox

### Expected behavior
Switching back to Firefox should return to last active tab

### Actual behavior
If away from Firefox for more than a couple seconds, Firefox will always open a new tab and switch to it, instead of returning to the last active tab

### Device & build information
* Device: iPhone 12 mini
* Build version: Firefox Daylight 101.0 (9723)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4368)

**Comment by SimonBasca** [comment]
@Floreadore Could you please check your homepage settings and share a screenshot?

**Comment by Floreadore** [comment]
Holy smokes I think I just had a setting wrong. All this damn time. 🙄 The "Opening Screen" setting under Settings > Homepage was set to "Homepage," when it should have been "Last tab," as in the attached screenshot. D'oh. Not sure how that got changed or whether it was a default.
![Firefox iOS homepage setting](https://user-images.githubusercontent.com/107228834/173162812-1c8ff04a-5887-4e50-a571-c159ea57a337.PNG)

**Comment by lmarceau** [comment]
@Floreadore By default (on a new install) this setting is set at "Homepage after four hours of inactivity"

**Comment by Floreadore** [comment]
Well I'll be. TMYK
