### ISSUE TITLE
Reading list welcome text appears when an item is present

### ISSUE THREAD

**Issue by lmarceau** [mozilla-mobile/firefox-ios#10970]
## Steps to reproduce
- Have nothing in your reading list
- Add an item to your reading list (either from reader mode or hamburger menu)
- Open reading list panel

### Expected behavior
- Welcome text wouldn't be there

### Actual behavior
- Welcome text is there

### Device & build information
* Device: iOS 15.2
* Build version: 5071597e239ce2d1c8ef6fc7791a37c193b01da0

### Notes
Attachments: 
![Simulator Screen Shot - iPhone 11 - 2022-06-09 at 14 34 41](https://user-images.githubusercontent.com/11338480/172942946-d11b4209-6a46-4fd5-95e3-54600a89f3d0.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4366)

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verifying as fix on main 6aaca8a5c4ba01029db4239fffe6fee63465c111
