### ISSUE TITLE
Firefox occasionally focuses very old open tab on launch

### ISSUE THREAD

**Issue by DHowett** [mozilla-mobile/firefox-ios#10991]
## Steps to reproduce
I do not have a consistent repro for this bug, but it has happened three times. On launch, Firefox for iOS occasionally selects a random tab from my “inactive tabs” section (of which I have many) and displays it as the currently selected tab.

### Expected behavior
Firefox follows my preference on whether to open the last viewed tab or the homepage on launch.

### Actual behavior
Firefox selects a random tab from my inactive tabs section and displays it.

### Device & build information
* Device: iPhone 11 Pro
* Build version: Daylight 101.0 (9723)
    1. Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4374)

**Comment by tech189** [comment]
I have the same issue on iPad on version Daylight 101.0 (9723). It’s happened a few times seemingly at random.

**Comment by beefstew** [comment]
This is just one of the frustrating UX bugs in the whole new set of [misguided] functionality to manage down my list of "open" tabs. I can no longer learn and rely on the visual position of tabs in my tab view, because Firefox is constantly shuffling them around.

**Comment by SimonBasca** [comment]
Thanks for the feedback. @DHowett could you please post a screenshot of your homepage settings? Also is the tab that get focused an empty tab that shows the homepage?

**Comment by DHowett** [comment]
Sure thing.

![image](https://user-images.githubusercontent.com/189190/175959004-042002d8-ac41-4b82-a15f-be872bf1e19c.png)

It is important for me to stress that it is *not* a tab hosting the homepage (which would suggest the "homepage after four hours of inactivity" option). It is one of my random open tabs, complete with a page loaded and its navigation history, sometimes from months ago. It is often the same one (!).
