### ISSUE TITLE
When rotating from portrait to landscape, a weird gap gets created in History Highlights

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#11002]
If you have more than 3 items in your History Highlights, then rotate from portrait to landscape, you will notice a weird large gap in the column.

Behold:

!Screen Shot 2022-06-13 at 3.17.14 PM.png|width=2519,height=1161!

Please to fix. yass.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4380)

**Comment by lmarceau** [comment]
![image](https://user-images.githubusercontent.com/11338480/180471494-2f65b9bf-09ee-4b3c-9850-f13e9cc0f594.png)

**Comment by data-sync-user** [comment]
➤ lmarceau commented:

image ( https://user-images.githubusercontent.com/11338480/180471494-2f65b9bf-09ee-4b3c-9850-f13e9cc0f594.png )

**Comment by SimonBasca** [comment]
This issue is reproducible on v104.0 (14880)

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Marking as verified fix on main . 

Note: While testing we’ve logged this issue https://github.com/mozilla-mobile/firefox-ios/issues/11623 ( https://github.com/mozilla-mobile/firefox-ios/issues/11623|smart-link )
