### ISSUE TITLE
Remove Snapkit from`CredentialProvider/Cell`

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#11028]
Remove snapkit from Credential Provider

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4400)

**Comment by lmarceau** [comment]
Relates to https://github.com/mozilla-mobile/firefox-ios/issues/8592

**Comment by data-sync-user** [comment]
➤ Laurie Marceau commented:

This was merged for v103

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verifying as fix on main 6aaca8a5c4ba01029db4239fffe6fee63465c111. No issues encountered while testing the login, saved passwords and autofill functionalities.
