### ISSUE TITLE
"Find in Page" search bar text don't respect dark theme

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#11026]
## Steps to reproduce
1. Enable Dark theme
1. Visit a page
1. Open the hamburger menu -> Tap "Find in Page"
    1. Expected behavior

* "Find in Page" search bar and text should have dark theme
    1. Actual behavior
* "Find in Page" search bar and text have light theme
    1. Device & build information
* Device: iPad Pro (15.4)
* Build version: 101.1 (10346)
    1. Notes
Attachments: 

![Screen Shot 2022-06-15 at 15 52 42](https://user-images.githubusercontent.com/32130829/173831904-4ba26db5-088a-4758-affe-4537872cc5d0.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4398)

**Comment by data-sync-user** [comment]
➤ Tiffanie Shakespeare commented:

Removing needs ux label. Agree all our components should match the theme set.

**Comment by lime124** [comment]
still an issue

**Comment by data-sync-user** [comment]
➤ Norberto Andres Furlan commented:

Alexandru Farcasanu can you take a look to this one?

**Comment by data-sync-user** [comment]
➤ Alexandru Farcasanu commented:

Norberto Andres Furlan based on this (https://mozilla-hub.atlassian.net/browse/FXIOS-5534 ( https://mozilla-hub.atlassian.net/browse/FXIOS-5534|smart-link )) and my investigations for this issue, seems to work fine.

I can’t see unexpected results… or maybe I am wrong? 🤔 

!Simulator Screenshot - iPhone 15 Pro Max - 2024-03-19 at 13.34.38.png|width=1290,height=2796!

!Simulator Screenshot - iPhone 15 Pro Max - 2024-03-19 at 13.34.11.png|width=1290,height=2796!

Tested on main branch.

**Comment by lime124** [comment]
For some reason I'm not seeing your screenshot Alexandru. 
This is what I see on my iphone. In dark theme I wouldn't expect this bright white bar and the contrast between the white bar background and the number count is very low. I'll reach out to design systems for help.

![IMG_C5855741AD3C-1](https://github.com/mozilla-mobile/firefox-ios/assets/287322/9beeb926-1579-488f-ac97-c9838a3fd6f0)

**Comment by data-sync-user** [comment]
➤ Norberto Andres Furlan commented:

I agree with Tiffanie Shakespeare. For example, in Chrome, it takes the color of the keyboard. Can we do something similar Alexandru Farcasanu ?

Light Mode:

!IMG_5879.PNG|width=25%!

Dark Mode:

!IMG_5878.PNG|width=25%!

**Comment by data-sync-user** [comment]
➤ Norberto Andres Furlan commented:

Alexandru Farcasanu we will get the color codes for you soon. Lets pause it until we have them. Thanks!

**Comment by cwzilla** [comment]
Hi, design systems here :)

Could we apply the following tokens to the find in page bar?
- Border: `borderPrimary`
- Background: `layer1`
- Search text: `textPrimary`
- findings #: `textSecondary`
- Up, down, close icons: `iconPrimary`
- If up/down icons are disabled, use `iconDisabled`

Here is a Figma file for [UI reference](https://www.figma.com/file/zEr9HBYt4CPz1tmYy8oq2N/Ongoing-Draft-(Public)?type=design&node-id=2%3A2898&mode=design&t=OlCBLPF6mdArS4dY-1). Thanks!

**Comment by dicarobinho** [comment]
@cwzilla sure. I will be back with updates!

**Comment by cwzilla** [comment]
@dicarobinho Looks great! Thank you so much.

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Verified as fixed on v9000 (40444) with iPhone 15 Pro (17.3).

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Verified as fixed on v125 (*40470*) with iPhone 15 Pro (17.3).
