### ISSUE TITLE
The prompt to save user and password is not displayed after logging in Private Browsing

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#11024]
## Steps to reproduce
1. Go to a login form in PB
2. Type a valid login and password
### Expected behavior
- A prompt to save user and password should be displayed.
### Actual behavior
- The prompt to save user and password is not displayed.
### Device & build information
* Device: iPad Pro (15.4)
* Build version: 101.1 (10346)
### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4395)

**Comment by gutley** [comment]
I'm not sure you should be able to save passwords in private browsing mode. I don't think Safari lets you. Not sure if Desktop Firefox does either. Doing so would leave a trace (via the existence of that info in autofill) that you visited the site.

**Comment by SimonBasca** [comment]
@gutley You might be right. Safari does not have this functionality in iOS and neither does Firefox desktop. Let's close this as invalid.
