### ISSUE TITLE
Search suggestions are not displayed in Private Browsing

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#11023]
## Steps to reproduce
1. Open a new private tab
2. Type something in the URL bar
### Expected behavior
- Search suggestions should be displayed.
### Actual behavior
- Search suggestions should are not displayed.
### Device & build information
* Device: iPad Pro (15.4)
* Build version: 101.1 (10346)
### Notes
Attachments: 

![Screen Shot 2022-06-15 at 15 48 00](https://user-images.githubusercontent.com/32130829/173830597-898c50d2-327f-48b5-a2b6-c43d3df62fa7.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4396)

**Comment by dnarcese** [comment]
Currently, this is intended behaviour. We do not show any suggestions from Google in private browsing mode for privacy reasons.
