### ISSUE TITLE
Improve DownloadHelper

### ISSUE THREAD

**Issue by mauriciomaniglia** [mozilla-mobile/firefox-ios#11022]
Description:

- Improve DownloadHelper by decoupling it from BrowserViewController and injecting a closure instead, for download button action. This also makes the component more easy to test.

- Implement unit test for DownloadHelper.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4397)

**Comment by mauriciomaniglia** [comment]
Closing issue.

**Comment by data-sync-user** [comment]
➤ Roux Buciu commented:

Testing:

  * downloads panel have the same behaviour and there’s no regression
