### ISSUE TITLE
Send tab is not functional when sending a tab from desktop to iOS

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#11020]
## Steps to reproduce
1. Login to FxA on desktop and iOS
2. Send tab from desktop to iOS

### Expected behavior
- Send tab should be functioning as expected.

### Actual behavior
- Send tab is not functional when sending a tab from desktop to iOS

### Device & build information
Device: iPad Pro (15.4)
Build version: 101.1 (10346)

### Notes
- Sending a tab from iOS to desktop is working as expected.
- I also experienced a single crash after trying to send a tab from iOS to desktop after previously sending a tab from desktop to iOS
Attachments: 

[Client-2022-06-15-123645.ips.zip](https://github.com/mozilla-mobile/firefox-ios/files/8908547/Client-2022-06-15-123645.ips.zip)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4394)

**Comment by dnarcese** [comment]
@SimonBasca When is the last version this worked in?

**Comment by SimonBasca** [comment]
@dnarcese This is working correctly on v101 (9723)

**Comment by lmarceau** [comment]
I am a bit confused since the only real change from v101 to v101.1 are the [sponsored tile changes](https://github.com/mozilla-mobile/firefox-ios/compare/v101.0...v101.1). I am not sure how it would affect the send tab functionality

**Comment by data-sync-user** [comment]
➤ Nishant Bhasin commented:

Simion Basca There is a fix that has been deployed to the backend (https://mozilla-hub.atlassian.net/browse/SVCSE-632?atlOrigin=eyJpIjoiNzI0ZTNkMzcyNjRjNDM4Mzg2NDk3MDRjZGMyMzQxZGQiLCJwIjoiamlyYS1zbGFjay1pbnQifQ ( https://mozilla-hub.atlassian.net/browse/SVCSE-632?atlOrigin=eyJpIjoiNzI0ZTNkMzcyNjRjNDM4Mzg2NDk3MDRjZGMyMzQxZGQiLCJwIjoiamlyYS1zbGFjay1pbnQifQ|smart-link ) ) 

Could you please test this on a real device and let us know if the notifications are working? 

Some folks from the team tested it and it worked well but we will await your final results. 

  * Open Desktop Tab
  * Make sure you are logged into Firefox iOS
  * Send Tab from Desktop To Firefox iOS
  * Tab send should work most times in a good internet condition

**Comment by pashynskykh** [comment]
Sending tab from desktop to iOS is not working for me either. 

Firefox v101.0.1 (build 20220608170832) on Windows 11 + Firefox v101.1 (10346) on iOS15.5, iPhone 11.

I logged in and synced on both browsers.

**Comment by nbhasin2** [comment]
@pashynskykh Does it work if you try to send the tab to all devices from the Desktop?

**Comment by pashynskykh** [comment]
> @pashynskykh Does it work if you try to send the tab to all devices from the Desktop?

It does not have an option to send a tab to "All devices". Maybe just because I currently have only two devices logged in.
![image](https://user-images.githubusercontent.com/14852335/175331482-d4c7655d-88fa-4d6f-ba71-db2a4929d44f.png)

**Comment by pashynskykh** [comment]
Also, just found, that "Synced tabs" are not synced on iOS. Even after doing force sync on both desktop and iOS, I do not see my open tabs from desktop.

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Nishant Bhasin shoudl we move this to re-open or should we log a new issue?

**Comment by nbhasin2** [comment]
@pashynskykh you might be experiencing something completely different and not just related to sync tab notification.

Have you tried a do a fresh install and while making sure in settings the Notifications Permissions are set to `Allow`?

**Comment by nbhasin2** [comment]
@SimonBasca can you confirm if the following is true or if it needs any more details

a) send tab from Desktop -> iOS -> works
b) send tab from iOS -> Desktop -> does not work
b) send tab from iOS -> iOS -> does not work

**Comment by SimonBasca** [comment]
@nbhasin2 confirming that the following is true:

a) send tab from Desktop -> iOS -> works
b) send tab from iOS -> Desktop -> does not work
b) send tab from iOS -> iOS -> does not work

Tested on v9000 (11853) and v102. 0 (11640)

**Comment by AshenPaladin** [comment]
I am encountering the same issue, and it has persisted despite an update for Firefox on both desktop and iOS.

For me it's like this:

a) send tab from Desktop -> iOS -> does not work
b) send tab from iOS -> Desktop -> works
b) send tab from iOS -> iOS -> does not work

Tested on Firefox version 102.0 for Windows Desktop, and Firefox Daylight 102.0 (11640) on iOS, on an iPhone and an iPad.

**Comment by pashynskykh** [comment]
> @SimonBasca can you confirm if the following is true or if it needs any more details

For me:
a) send tab from Desktop -> iOS -> does not work
b) send tab from iOS -> Desktop -> works
c) send tab from iOS -> iOS -> no second device to test

That's after updating desktop and iOS browser to v102.0 and iOS to

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Correcting my comment 
a) send tab from Desktop > iOS > does not work
b) send tab from iOS > Desktop > works
b) send tab from iOS > iOS > does not work

Tested on v9000 (11853)  v102. 0 (11640) 103.0 (12108)

Sorry for the confusion.

**Comment by nbhasin2** [comment]
Hi folks, just here to give an update on this issue. This is a much more complicated issue related to certs that we are working on which requires changes and updates on the backend side. Once those are deployed (which will take a while) we should see an improvement in send tab functionality. 

There isn't a set ETA for this but rest assured we are doing our best to get it resolved asap.

**Comment by wonderyann** [comment]
If it may take a while to fix it, please consider disabling send tab in iOS version to prevent people like me to lose time and gain frustration ignoring this ticket ;)

**Comment by Juraj-Masiar** [comment]
When this is fixed, will I receive all the send tabs or am I sending them to a black hole right now?

**Comment by lemero** [comment]
I can state that I receive from iPad & iPhone to PC, but none of my iOS devices can receive from anything else. Signing out, syncing, etc, nothing helped. Notifications are on!
Hoping for a speedy resolution, until I realized there is an issue, I lost lots of sent tabs which I forgot by the time I noticed they weren't arriving :(

**Comment by plwt** [comment]
User feedback:- 

https://support.mozilla.org/en-US/questions/1382528
https://support.mozilla.org/en-US/questions/1383388
https://support.mozilla.org/en-US/questions/1383531

**Comment by plwt** [comment]
User feedback:- https://support.mozilla.org/en-US/questions/1383620

**Comment by mgibson323** [comment]
This is a blocker for me and my daily usage. I am currently unable to send any tabs from desktop to iOS, although the reverse works without issue.

**Comment by plwt** [comment]
User feedback: https://support.mozilla.org/en-US/questions/1383880

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

This issue is still reproducible on v103.0 (13910)

**Comment by jasim-mohd** [comment]
This feature is a big deal breaker. I hope it get fixed soon until then I'm on Edge.

**Comment by Juraj-Masiar** [comment]
As a workaround, one can also use Pocket, since it's already integrated in Firefox and can be downloaded from App store or accessed directly in web app.

**Comment by jim-davenport** [comment]
It is working - at least it is right now…

**Comment by pashynskykh** [comment]
Desktop - 103.0.1.
iOS - 103.0 (13910).

Sending tab is started to work again.

**Comment by data-sync-user** [comment]
➤ Nishant Bhasin commented:

Simion Basca could you try again and let us know if this is still an issue, a fix went out recently on the backend side.

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verifying as fix on v9000 (15189) and v104.0 (14880). Send tab is functional from iOS → Desktop, Desktop → iOS and iOS → iOS.

**Comment by GMB23** [comment]
This appears to be an issue again. Can't send tab from Desktop to iOS - but I can send tab from iOS to Desktop.
