### ISSUE TITLE
No Git Tag for v101.1 release.

### ISSUE THREAD

**Issue by gutley** [mozilla-mobile/firefox-ios#11035]
I'm sure its just an oversight, but 101.1 hasn't been tagged yet

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4403)

**Comment by lmarceau** [comment]
Thanks @gutley! Indeed I had the release in draft but forgot to publish 🙈 Closing this issue since it's now [tagged](https://github.com/mozilla-mobile/firefox-ios/releases/tag/v101.1)
