### ISSUE TITLE
Keyboard stops working in Firefox

### ISSUE THREAD

**Issue by nasiralamreeki** [mozilla-mobile/firefox-ios#11033]
## Steps to reproduce
This is difficult to reproduce as it happens intermittently 

### Expected behavior
Keyboard input works smoothly on website and address bar for Firefox for iOS. 

### Actual behavior
Keyboard stops working when inputting text into forms and the Firefox address bar. This is only happening so far in Firefox for iOS and doesn't happen everytime but has reoccurred several times. I'm encountering this on iOS 16 Dev B1 but haven't seen this in other apps.

### Device & build information
* Device: iPhone 12 Pro
* Build version: Firefox Daylight 101.0 (9723)
* iOS Version: 16.0 Dev B1
    1. Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4402)

**Comment by dwsdws1** [comment]
This is also happening on Android.
