### ISSUE TITLE
Only 3 of the 5 wallpapers are displayed when first going to the onboarding

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#11040]
## Steps to reproduce
1. Install v102.0 (10804)
2. Go to the second slide
### Expected behavior
- All wallpapers should be displayed.
### Actual behavior
- Only 3 of the 5 wallpapers are displayed. After going to the onboarding from settings all the 5 wallpapers are displayed.
### Device & build information
* Device: iPad 11 Pro (15.4) / iPhone 13 mini (15.4)
* Build version: ?
### Notes
Attachments: 

![image](https://user-images.githubusercontent.com/32130829/174095974-6fbc72c2-77c9-466f-91c3-bec38770e508.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4405)

**Comment by dnarcese** [comment]
@SimonBasca This was intended behaviour for the first iteration. We are only showing the wallpapers that we ship with the app to avoid any network calls on the first launch. We will work on iterating on this in the future.
