### ISSUE TITLE
[Swiftlint] trailing whitespace rule is reporting a lot of errors after a recent commit

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/firefox-ios#11050]
If I'm not wrong and IIRC, the trailing whitespace rule was enabled some time ago and was not failing but I have realized that after this commit (ae0d13c45729bf404ec6f888d439b1af5a96a8fa) on main, swiftlint step is failing with 1255 errors found! See for example: https://github.com/mozilla-mobile/firefox-ios/runs/6922522013

Not sure what has happened.. cc @electricRGB

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4413)

**Comment by electricRGB** [comment]
Yep. I saw this and will fix it right away. Not sure what happened either.
