### ISSUE TITLE
 Update the color of the Loading bar 

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#11061]
Update iOS loading process line to ZAP color (see screen below)

![image](https://user-images.githubusercontent.com/11432165/174350478-556913cb-adc6-4661-b5cd-d0ed37801e67.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4108)

**Comment by data-sync-user** [comment]
➤ Daniela Arcese commented:

Ekaterina Galetski can we get the hex values of the purple, pink, and yellow

**Comment by data-sync-user** [comment]
➤ Ekaterina Galetski commented:

https://www.figma.com/file/oG6dMs0tS4Vlw1viTQ4CRh/Desktop-Styles?node-id=90%3A0 ( https://www.figma.com/file/oG6dMs0tS4Vlw1viTQ4CRh/Desktop-Styles?node-id=90%3A0|smart-link ) 

!Screen Shot 2022-06-17 at 11.46.09 AM.png|width=916,height=90!

!Screen Shot 2022-06-17 at 11.43.16 AM.png|width=1429,height=407!

Here you are!

**Comment by mozead1996** [comment]
@dnarcese i would like to contribute on this , any help with the starting point , thanks

**Comment by lmarceau** [comment]
@mozead1996 Thanks for having a look into this! The gradient needs to be from purple to pink to yellow following:
Purple `#9059FF 0%`, Pink `#FF4AA2 52.08%`, Yellow `#FFBD4F 100%`

The loading bar, or progress bar is currently implemented with the class `GradientProgressBar`. It seems there's an existing gradient in there so we could probably replace it with the new colors. Let me know if you need any more details 😄

**Comment by mozead1996** [comment]
@lmarceau  Thanks for the details , i see there are different colors for private and public browsing , so this will be applied to both or only to public browsing ?

**Comment by data-sync-user** [comment]
➤ Laurie Marceau commented:

Tagging Ekaterina Galetski for the question: “this will be applied to both public or private loading bar or only to public browsing?“

**Comment by data-sync-user** [comment]
➤ Ekaterina Galetski commented:

Laurie Marceau Only the normal / ordinary search needs the color update, the protest search has its own color and for now we would like to keep it..

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verifying as fix on main eb3dfcba028bf21e96193de732e2fe3a2681ae46
