### ISSUE TITLE
Firefox 102.0 RC crashes when entering “opend” in the address bar

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/firefox-ios#11077]
## Steps to reproduce

1. In Firefox version 102.0 RC (10804), type  “open” in the address bar.2. 
2. Wait a second, then type “d”.

I was trying to enter “opendream”, to find this page that was already in my browsing history:

https://github.com/wixoaGit/OpenDream

### Expected behavior

Firefox should show me my filtered browsing history. 

### Actual behavior

Firefox disappears, but doesn’t show a crash reporter dialog when the app disappears or when I next launch it. 

I tried entering lots of other strings that I know are in my browsing history, but “opend” is the only string that crashes. I assume there is nothing special about the string “opend”, but maybe some corrupted metadata in the matching pages in my browsing history.

### Device & build information

* Device: iPhone 12 running iOS 15.5
* Build version: 102.0 RC (10804)

### Notes

This crash is a regression in 102.0 RC (10804). I can reproduce this crash in that version and 102.0 Beta (11005). I can’t reproduce this crash in 101.1 (10346).

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4438)

**Comment by cpeterso** [comment]
I don’t see any crash logs in iOS Settings > Privacy > Analytics & Improvements > Analytics Data that begin with “Firefox”. Is there another place I should look for a crash log?

**Comment by cpeterso** [comment]
I’m no longer able to reproduce this crash using this STR. My browsing history metadata must have changed in some way that it no longer triggers the crash, but the bug is still surely there because I’m using the same build.

**Comment by dnarcese** [comment]
@SimonBasca could you help with trying to reproduce this?

**Comment by SimonBasca** [comment]
@dnarcese We tried reproducing on 102.0 RC (10804) were it was previously found. We also tried reproducing on the latest v102 (11640) and on main 51aeded43d3723793de1fd3334383fb5204b5fe6.

So far we were unable to reproduce the issue. 

Note: Similar reports of the issue https://github.com/mozilla-mobile/firefox-ios/issues/11144.

**Comment by cpeterso** [comment]
I can no longer reproduce this crash, but maybe there are crash logs still on my phone?

However, I don’t see any crash logs in iOS Settings > Privacy > Analytics & Improvements > Analytics Data that begin with “Firefox”. Is there another place I should look for Firefox crash logs?

**Comment by dnarcese** [comment]
@cpeterso can you search for "client-" in analytics data instead of "Firefox"? Then you can find the file with the date of the crash

**Comment by SimonBasca** [comment]
@cpeterso do you have "Shortcuts" disabled from Setting-> Homepage?

**Comment by cpeterso** [comment]
> @cpeterso do you have "Shortcuts" disabled from Setting-> Homepage?

No

> @cpeterso can you search for "client-" in analytics data instead of "Firefox"? Then you can find the file with the date of the crash

Sorry I didn't see this question sooner. I now have only one "Client-" log and it is for a different crash.

Since I am no longer experiencing this crash and I don't have a "Client-" log for this crash, I'll close this issue as inactionable.
