### ISSUE TITLE
Complete loss of webview interactivity loading cardano.org

### ISSUE THREAD

**Issue by koobs** [mozilla-mobile/firefox-ios#11076]
## Summary 

Loading https://cardano.org causes complete loss of webview interactivity during load.

Other chrome elements (eg: url bar, main menu, reload) remain usable.

## Steps to reproduce

 * Load https;//cardano.org
 * Scroll up and down while page loads until loss of interactivity is experienced.

### Expected behavior

 * Site loads and is interactive in an reasonable amount of time.

### Actual behavior

 * Multiple non contiguous page sections unrendered (white) during load
 * Loss of webview control interactivity (does not respond to touch / scroll).

### Device & build information

* Device: Apple iPhone 11 Pro Max (iOS 15.5)
* Firefox Build Version: 101.1 (10346) and 102.0 (11005)

### Notes

 * Issue does not reproduce in Safari.
 * After loss of interactivity, webview responds sporadically for very short periods of time (< 1 second) to some (unknown) touch/scroll events. I am unable to determine if a particular sequence or type of scroll/touch events trigger temporary response, or whether it is the browser 'trying to catch up' briefly.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4437)

**Comment by gutley** [comment]
I managed to reproduce the issue here on an iPhone 12 Pro Max. It took a few attempts to get it to fail, but when it does the symptoms are as described. Interestingly there is no CPU usage in the app while its frozen.

However, unlike the original poster. I was also able to reproduce in Safari, so not really a Firefox bug and probably not a lot we can do, apart from raise it with WebKit.org.

**Comment by gutley** [comment]
Does anybody have an Android phone they can try this on. It might just be a bug in the site itself and not WebKit specific.
(Desktop browsers work OK)

**Comment by data-sync-user** [comment]
➤ Nishant Bhasin commented:

This is an issue with Cardano itself. Safari also has issues and its likely one of the script warnings that the browser throws on loading is the issue.

If anything this seems more of a webcompact issue. 

Below are the warnings that I get when Cardano.org ( http://Cardano.org ) stops loading.

[Log] Google Analytics – {id: "Google Analytics", trackingID: "UA-101007627-3", options: {titleCase: false}} (05e4250316e7db542e460fb1ce37b7801220d0bb.js, line 1)
[Log] {breakpoints: Object, direction: "ltr", mixins: Object, overrides: Object, palette: Object, …} (05e4250316e7db542e460fb1ce37b7801220d0bb.js, line 1)
[Warning] The resource https://cardano.org/webpack-runtime-dc37cc38070f9f91514e.js was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it wasn't preloaded for nothing.
[Warning] The resource https://cardano.org/framework-e9a9a792077ab2b89238.js was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it wasn't preloaded for nothing.
[Warning] The resource https://cardano.org/d7eeaac4-de110e9a514229d8ad38.js was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it wasn't preloaded for nothing.
[Warning] The resource https://cardano.org/1bfc9850-4fd2a6ebce7e1235dbe8.js was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it wasn't preloaded for nothing.
[Warning] The resource https://cardano.org/95b64a6e-7e2c2690f8bb1555286b.js was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it wasn't preloaded for nothing.
[Warning] The resource https://cardano.org/252f366e-271a9ec1337e998f0927.js was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it wasn't preloaded for nothing.
[Warning] The resource https://cardano.org/app-fb58e52f71541eb3df38.js was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it wasn't preloaded for nothing.
[Warning] The resource https://cardano.org/f2a8eef57fbf96f5dfdd60d9ddf64c35b55dc17d-74aaf23244e3ee8de193.js was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it wasn't preloaded for nothing.
[Warning] The resource https://cardano.org/3a71c653f06bf35b4034f4bde5d95e450b552f9f-33c8f95275f264505e89.js was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it wasn't preloaded for nothing.
[Warning] The resource https://cardano.org/3319093fa9867f1c57cb725e629ffb43267dca49-bf1e9b776f74b95c05f9.js was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it wasn't preloaded for nothing.
[Warning] The resource https://cardano.org/component---src-pages-index-js-a028111ac8dcaf226d9f.js was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it wasn't preloaded for nothing.
[Warning] The resource https://cardano.org/page-data/index/page-data.json was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it wasn't preloaded for nothing.
[Warning] The resource https://cardano.org/page-data/app-data.json was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it wasn't preloaded for nothing.

**Comment by data-sync-user** [comment]
➤ Nishant Bhasin commented:

Daniela Arcese is there a way to move this issue to webcompact?

**Comment by softvision-raul-bucata** [comment]
@SimonBasca I am still unable to reproduce the issue, as per https://github.com/webcompat/web-bugs/issues/109582#issuecomment-1240065770. Any luck in reproducing the issue?

[inv_36/2022]
