### ISSUE TITLE
Link does not open the account details page of the device

### ISSUE THREAD

**Issue by softvision-raul-bucata** [mozilla-mobile/firefox-ios#11083]
## Steps to reproduce
1. Navigate to: https://buy.itunes.apple.com/WebObjects/MZFinance.woa/wa/accountSummary?mt=8
1. Observe the result.

### Expected behavior
The link opens the account summary page on the device.

### Actual behavior
An error message is displayed

### Device & build information
* Device: iPhone 8 iOS 15.5
* Build version: Firefox Daylight101.1 (10346)
  1. Notes

1. Reproducible on other browsers.
1. Safari works as expected.
1. Initially reported: https://github.com/webcompat/web-bugs/issues/106072.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4442)

**Comment by lmarceau** [comment]
Message on screen when trying to load the page:

![IMG_6395](https://user-images.githubusercontent.com/11338480/174638293-8a5ef34e-dc09-45af-804e-64c3a0b87e54.PNG)

**Comment by softvision-raul-bucata** [comment]
@lmarceau Safari is the only one that opens the account info page inside the device when the link is accessed, so this might be expected behavior from Firefox, since no other browsers beside Safari opens the account info page ?
