### ISSUE TITLE
[iPad] Firefox crashes when switching between session when the keyboard is displayed.

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#11096]
## Steps to reproduce
1. Clean install v102.0 (11255)
2. Visit a page (e.g youtube.com)
3. Tap on the URL bar
4. Tap on the Private Browsing button
### Expected behavior
- The view should be changed to Private Browsing
### Actual behavior
- Firefox crashes when switching between session when the keyboard is displayed.
### Device & build information
* Device: iPad Pro (15.4)
* Build version: v102.0 (11255)
### Notes
Attachments: 

[Client-2022-06-21-130754.ips.zip](https://github.com/mozilla-mobile/firefox-ios/files/8947970/Client-2022-06-21-130754.ips.zip)

https://user-images.githubusercontent.com/32130829/174777330-fc9dadc9-fb7c-4fcf-b0f8-faf4215c675f.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4448)

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verified fix on v102.0 (11395)
