### ISSUE TITLE
Launching with wrong tab

### ISSUE THREAD

**Issue by nmkeraj** [mozilla-mobile/firefox-ios#11108]
I have the list 90 opened tabs. I am on the 80th tab while closing the app. And then when I open the app I am on the 4th tab. It doesn’t keep the last open active tab.

**Comment by tobvr** [comment]
I also have this issue; I have 60 tabs open but every time I open Firefox, it starts at the 13th tab.

**Comment by SimonBasca** [comment]
@nmkeraj @tobvr could you please share a screenshot of your homepage settings? Also if you could add a video of the issue, that would be very helpful.

**Comment by nmkeraj** [comment]
Hi. This my screenshot. Thank to it I have found that opening website was turned to Homepage after 4 hours. And it was like that that starting tab was changed after some time. I don’t know what time it was but more than hour or more. If I close and open quickly (in few minute time) Firefox it opens on my last active tab properly. Anyway, my home page is different than the problem is occurring. My fourth tab is not a home page.






On Monday, June 27, 2022, 9:03 am, SimonBasca ***@***.***> wrote:




@nmkeraj @tobvr could you please share a screenshot of your homepage settings? Also if you could add a video of the issue, that would be very helpful.

**Comment by SimonBasca** [comment]
@nmkeraj so just to clarify your problem still exists after going to Settings -> Homepage and changing to "Last Tab"?

**Comment by nmkeraj** [comment]
Hi. FireFox is working good after changing Last Tab setting. The update should have changed it because I haven’t touched the settings for long time. 
  Regards




On Wednesday, June 29, 2022, 3:16 pm, SimonBasca ***@***.***> wrote:




@nmkeraj so just to clarify your problem still exists after going to Settings -> Homepage and changing to "Last Tab"?

**Comment by data-sync-user** [comment]
➤ Daniela Arcese commented:

We should check if https://mozilla-hub.atlassian.net/browse/FXIOS-3862 ( https://mozilla-hub.atlassian.net/browse/FXIOS-3862|smart-link ) fixes this. It will be released in v103

**Comment by nmkeraj** [comment]
Hi again. The firefox behaves strange again. If I close a tab in the mid of the list, it srolls me up to the beginning of the list.



On Monday, July 18, 2022, 11:27 am, Sbasca ***@***.***> wrote:




@dnarcese judging by the comment above the problem is fixed when changing "Homepage" to "Last Tab" setting. Based on comment #11108 (comment) I will close the issue as works for me. Let's re-open if the issue is reproducible again

**Comment by SimonBasca** [comment]
@nmkeraj please write submit a new issue with steps on how you are reproducing the issue. Thanks.
