### ISSUE TITLE
Remove scrollbar on Homepage

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#11102]
Remove the scrollbar on the firefox homepage.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4451)

**Comment by simonpojok** [comment]
@lmarceau Kindly explain why this issue was re-opened so I can fix it

**Comment by lmarceau** [comment]
@simonpojok Sorry there's nothing to fix, we let the QA close the task when it's tested :)

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verified fix on 3cb72444e03e4399bc2f4e171a0d3601217b4cb4.
