### ISSUE TITLE
Remove "Daylight" from the Settings menu

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/firefox-ios#11118]
The product name is "Firefox", not "Firefox Daylight".

https://github.com/mozilla-mobile/firefox-ios/search?q=Daylight&type=code

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4458)

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verifying as fix on main da7a6a4d1ed3630f60e307a623f3d8956e6184c3

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verifying as fix on v105.0 (16531)
