### ISSUE TITLE
Firefox crashes and will continue to crash on startup after enabling sponsored stories

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#11120]
## Steps to reproduce
1. Enable US vpn 
2. Install v102. 0 (11395) or v9000 (11556)
3. Go to Homepage -> Enable "sponsored stories"
4. Go to homepage
### Expected behavior
- Sponsored stories are correctly displayed.
### Actual behavior
- Firefox crashes and will continue to crash on start-up
### Device & build information
* Device: iPhone 12 Pro (15.4)
* Build version: v102. 0 (11395) or v9000 (11556)
### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4459)

**Comment by SimonBasca** [comment]
Video of the issue
https://user-images.githubusercontent.com/32130829/175276913-c97f8efe-ac27-4ba2-80c4-a47f8eb71b78.mp4

**Comment by data-sync-user** [comment]
➤ Roux Buciu commented:

The fix for this is to actually prevent Sponsored stories from showing up in the settings. They are not part of 102.

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verifying as fix.

  * on v102.0 (11640) the sponsored stories are no longer displayed.
  * on main 51aeded43d3723793de1fd3334383fb5204b5fe6 the crash is no longer reproducible.
