### ISSUE TITLE
Reopening bug: one shortcut per domain can be added to Homepage #10859

### ISSUE THREAD

**Issue by doodooface** [mozilla-mobile/firefox-ios#11143]
https://github.com/mozilla-mobile/firefox-ios/issues/10859#issue-1249553520

Device & build information

Device: iPhone 12 pro
Build version: Firefox Daylight 101.1 (10346)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4469)

**Comment by lmarceau** [comment]
@doodooface Do you have this issue with the exact same steps to reproduce as #10859? Is it happening on other websites?

**Comment by doodooface** [comment]
Yes exactly same problem across all different domains.

Just to add it seems the shortcuts from the same domain are added and can be removed from hamburger menu but the shortcuts from same domain just aren't displayed. Rather only the most recently added shortcut will be displayed.
