### ISSUE TITLE
Disable/enable edit toolbar action in Bookmarks panel for folder structure changes

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#11140]
Following folder structure changes [https://mozilla-hub.atlassian.net/browse/FXIOS-3106](https://mozilla-hub.atlassian.net/browse/FXIOS-3106|smart-link) it appears the toolbar menu edit actions in the library panel needs to be adjusted so in the following cases we can show/hide:

* Hide edit toolbar action when we’re in the desktop folder
* Show edit toolbar action when we’re in the “root“ folder which is now the mobile folder

This work is depending on the refactor of the library panel toolbar that will be done in [https://mozilla-hub.atlassian.net/browse/FXIOS-3920](https://mozilla-hub.atlassian.net/browse/FXIOS-3920|smart-link)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4467)

**Comment by data-sync-user** [comment]
➤ Laurie Marceau commented:

For QA, to test this you’ll need to either be on the branch epic-branch/bookmark-folders-changes or on the testflight #13592 ( https://app.bitrise.io/build/9ababb92-a865-425d-9541-81eeb9f0f021 ) 

We made multiple changes on this branch related to the four panels (history, downloads, reading list and bookmarks) and wanna make sure all is good before bringing the changes to main.

The stories included on this branch are the following:

  * https://mozilla-hub.atlassian.net/browse/FXIOS-3893 ( https://mozilla-hub.atlassian.net/browse/FXIOS-3893|smart-link ) 
  * https://mozilla-hub.atlassian.net/browse/FXIOS-3106 ( https://mozilla-hub.atlassian.net/browse/FXIOS-3106|smart-link ) 
  * https://mozilla-hub.atlassian.net/browse/FXIOS-3920 ( https://mozilla-hub.atlassian.net/browse/FXIOS-3920|smart-link ) 
  * https://mozilla-hub.atlassian.net/browse/FXIOS-4467 ( https://mozilla-hub.atlassian.net/browse/FXIOS-4467|smart-link ) 

This means the folder structure in bookmarks has changed. The root folder is now the mobile folder as per design ( https://www.figma.com/file/SO8Cd5lnmgNqJQY9KpORc9/History%2C-Bookmarks%2C-Downloads?node-id=2117%3A58734 ). The edit button needs to be accessible in the root/mobile folder so we can add for example bookmark in there. When we’re in the Desktop Bookmarks, edit button shouldn’t be there, unless I go into one of the desktop subfolders (ex: Unsorted Bookmarks).

Apart from those changes, nothing else should have changed in the four panels (history, downloads, reading list and bookmarks).

**Comment by isabelrios** [comment]
Thanks for the detailed explanation about the changes @lmarceau, there might be UI automated tests affected, I will open an issue to track that work. Thanks!

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Laurie Marceau we’ve started testing this issue and found several issues:

  * https://github.com/mozilla-mobile/firefox-ios/issues/11324 ( https://github.com/mozilla-mobile/firefox-ios/issues/11324|smart-link ) 
  * https://github.com/mozilla-mobile/firefox-ios/issues/11323 ( https://github.com/mozilla-mobile/firefox-ios/issues/11323|smart-link ) 
  * https://github.com/mozilla-mobile/firefox-ios/issues/11325 ( https://github.com/mozilla-mobile/firefox-ios/issues/11325|smart-link ) 
  * https://github.com/mozilla-mobile/firefox-ios/issues/11326 ( https://github.com/mozilla-mobile/firefox-ios/issues/11326|smart-link ) 
  * https://github.com/mozilla-mobile/firefox-ios/issues/11328 ( https://github.com/mozilla-mobile/firefox-ios/issues/11328|smart-link ) 
  * https://github.com/mozilla-mobile/firefox-ios/issues/11327 ( https://github.com/mozilla-mobile/firefox-ios/issues/11327|smart-link ) 

Most of the issue are related to bad UI and would require fixing before merging this into the main branch. We will continue our investigation and update if we find more issues.

**Comment by data-sync-user** [comment]
➤ Laurie Marceau commented:

Thanks Simion Basca , we’ll let you know when a next build is ready for test on this branch

**Comment by data-sync-user** [comment]
➤ Laurie Marceau commented:

Simion Basca We have a fix for most issues except https://github.com/mozilla-mobile/firefox-ios/issues/11327 ( https://github.com/mozilla-mobile/firefox-ios/issues/11327|smart-link ). If I don’t have a fix tomorrow I’ll make a new build so you can play around with the changes and see if at least we got the rest right.

**Comment by data-sync-user** [comment]
➤ Laurie Marceau commented:

Simion Basca Andrei Bodea 

New build #13962 ( https://app.bitrise.io/build/989e6a5d-c2f9-455b-97ac-be9e0a86a6a3 ) to test fixes for the following 5 issues:

  * https://github.com/mozilla-mobile/firefox-ios/issues/11324 ( https://github.com/mozilla-mobile/firefox-ios/issues/11324|smart-link )
  * https://github.com/mozilla-mobile/firefox-ios/issues/11323 ( https://github.com/mozilla-mobile/firefox-ios/issues/11323|smart-link )
  * https://github.com/mozilla-mobile/firefox-ios/issues/11325 ( https://github.com/mozilla-mobile/firefox-ios/issues/11325|smart-link )
  * https://github.com/mozilla-mobile/firefox-ios/issues/11326 ( https://github.com/mozilla-mobile/firefox-ios/issues/11326|smart-link )
  * https://github.com/mozilla-mobile/firefox-ios/issues/11328 ( https://github.com/mozilla-mobile/firefox-ios/issues/11328|smart-link )

The following will come in another build, as the solution hasn’t been found yet:

  * https://github.com/mozilla-mobile/firefox-ios/issues/11327 ( https://github.com/mozilla-mobile/firefox-ios/issues/11327|smart-link )

**Comment by data-sync-user** [comment]
➤ Laurie Marceau commented:

Simion Basca Andrei Bodea Catalin Suciu 

Turns out the final bug is fixed! New build on the way with Build #14029 ( https://app.bitrise.io/build/fa3ac935-09c8-46b0-88a3-fbd1171c160a ).

In other words, this build will have fixes for #11323 ( https://github.com/mozilla-mobile/firefox-ios/issues/11323 ), #11324 ( https://github.com/mozilla-mobile/firefox-ios/issues/11324 ), #11325 ( https://github.com/mozilla-mobile/firefox-ios/issues/11325 ), #11326 ( https://github.com/mozilla-mobile/firefox-ios/issues/11326 ), #11327 ( https://github.com/mozilla-mobile/firefox-ios/issues/11327 ), #11328 ( https://github.com/mozilla-mobile/firefox-ios/issues/11328 )

**Comment by data-sync-user** [comment]
➤ Laurie Marceau commented:

As those changes need to be part of v104 and that release branch is under soft freeze as of today, testing can be done directly on the v104 release candidate build.

**Comment by data-sync-user** [comment]
➤ Catalin Suciu commented:

Verifying as fixed on v104.0 (14834).

  * Hide edit toolbar action when we’re in the desktop folder ✅ 
  * Show edit toolbar action when we’re in the “root“ folder which is now the mobile folder ✅
