### ISSUE TITLE
Keyboard obstructs tabs when trying to close multiple tabs on iOS

### ISSUE THREAD

**Issue by eacoeytaux** [mozilla-mobile/firefox-ios#11156]
## Steps to reproduce

open up several tabs, then try to close them in succession

### Expected behavior

to be able to reach the "x" close button without a keyboard popping up that doesn't do anything

### Actual behavior

the keyboard pops up and blocks the bottom 1 or 2 tabs

### Device & build information
* Device: iPhone 11
* Build version: 15.5
### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4480)

**Comment by data-sync-user** [comment]
➤ Raluca Iordan commented:

Checked this today on the las version on main branch and it is fixed. I think it was solved by https://mozilla-hub.atlassian.net/browse/FXIOS-4018 ( https://mozilla-hub.atlassian.net/browse/FXIOS-4018|smart-link ) .  I think we can test it again Simion Basca . Thank you!

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

This issue is no longer reproducible on latest main 10895c167d3b4ef944b89ae7037a42b4292a4d4c
