### ISSUE TITLE
Bitrise - Upgrade to Xcode 14

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/firefox-ios#11160]
I have tried locally and the app builds successfully on Xcode 14. There are going to be a few issues though with UI and maybe unit tests too.

There is this new alert when pasting from clipboard
![Simulator Screen Shot - iPhone 11 - 2022-06-28 at 12 57 44](https://user-images.githubusercontent.com/1897507/176162988-d5b739db-df4a-494e-b87e-e021c225fe9a.png)
:

If I find something else I will document it here.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4482)

**Comment by isabelrios** [comment]
I'm seeing a wrong UI when running the app on Xcode14 Intel. Go to the tab tray and open one/two tabs:
![Simulator Screen Shot - iPhone 11 - 2022-06-30 at 11 28 43](https://user-images.githubusercontent.com/1897507/176717596-0744ee2a-ffdd-418a-82b2-d06327feaae1.png)
![Simulator Screen Shot - iPhone 11 - 2022-06-30 at 11 29 17](https://user-images.githubusercontent.com/1897507/176717609-1d36cd1f-3e0a-4391-ba37-e1bbf57dae35.png)

**Comment by lmarceau** [comment]
@isabelrios This is happening on `main` and is not just on Xcode 14. Investigating what's wrong..

**Comment by isabelrios** [comment]
> @isabelrios This is happening on `main` and is not just on Xcode 14. Investigating what's wrong..

oh I have not seen this before, you mean the tab preview issue or both? I will keep an eye in  case I reproduce on main and other xcode environments / iOS versions

**Comment by lmarceau** [comment]
I just opened an issue #11174, found the problem and will open a PR!

**Comment by isabelrios** [comment]
There may be an issue with the local web server... I need to investigate further but after running some tests on the Intel MacStadium instance I don't see the test pages availables in test-fixtures being loaded.

**Comment by isabelrios** [comment]
I have been reading some docs about this (thanks @thatswinnie) and tried a few things but don't understand what/where to change. 
- https://sarunw.com/posts/uipasteboard-privacy-change-ios16/
- https://blog.willbish.com/2022/08/02/using-uipastecontrol-in-a-uimenu-in-ios-16/
- https://blog.kylelanchman.com/how-to-use-uipastecontrol-in-ios-16/

Any directions or help would be more than welcome.. @nbhasin2 @lmarceau as you are familiar with the tests
cc @clarmso @jjSDET in case you have more ideas than me.

**Comment by isabelrios** [comment]
Let's close this for now, we are able to run the tests now
