### ISSUE TITLE
[Unit Tests] Push tests are failing

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/firefox-ios#11161]
These are the two tests that are failing very consistently:
- testClientRegistration: `/Users/vagrant/git/PushTests/LivePushClientTests.swift:35 - Asynchronous wait failed: Exceeded timeout of 120 seconds, with unfulfilled expectations: "no description provided".`
- testClientUpdate: `/Users/vagrant/git/PushTests/LivePushClientTests.swift:58 - Asynchronous wait failed: Exceeded timeout of 120 seconds, with unfulfilled expectations: "no description provided", "no description provided".`

See for example these two builds: https://app.bitrise.io/app/6c06d3a40422d10f/pipelines/57e2ee05-bec5-43d3-a249-3966b3156bf2

https://app.bitrise.io/app/6c06d3a40422d10f/pipelines/7c77d930-0606-429b-b1dc-9803c86b65f4

cc @lmarceau

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4483)

**Comment by nbhasin2** [comment]
@lmarceau I agree that those url sessions should be mocked as if at any point the session fails we'll be in a limbo of broken tests
