### ISSUE TITLE
Jump Back In CFR not showing up

### ISSUE THREAD

**Issue by dnarcese** [mozilla-mobile/firefox-ios#11164]
## Steps to reproduce
new install, but do not dismiss the “Default Browser” card.

1. open a top site
1. open a new tab

### Expected behavior
jump back in CFR should pop up

### Actual behavior
CFR not showing up.

If you dismiss the default browser card first, then on the next new tab, the CFR will show.

### Device & build information
* Device: ?
* Build version: v102 (11640)

*# 
*## Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4485)

**Comment by data-sync-user** [comment]
➤ Daniela Arcese commented:

Check if https://mozilla-hub.atlassian.net/browse/FXIOS-4419 ( https://mozilla-hub.atlassian.net/browse/FXIOS-4419|smart-link ) fixes this

**Comment by data-sync-user** [comment]
➤ Yoana Rios Diaz commented:

https://mozilla-hub.atlassian.net/browse/FXIOS-4419 ( https://mozilla-hub.atlassian.net/browse/FXIOS-4419|smart-link ) is available on 9000 (15288). I tested manually in the branch and I was able to see the Jump back in CFR

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verifying as fix on main e2e3d4216a3b55ad336a9af99729c4354764c54e
