### ISSUE TITLE
Tab view is too large

### ISSUE THREAD

**Issue by lmarceau** [mozilla-mobile/firefox-ios#11174]
![IMG_6470](https://user-images.githubusercontent.com/11338480/176753676-b56f4f70-2812-4894-8f1f-6afff47eda40.PNG)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4486)

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verifying as fix on main 10895c167d3b4ef944b89ae7037a42b4292a4d4c
