### ISSUE TITLE
App crashes when adding a new custom search enginge

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/firefox-ios#11187]
Main 51aeded43d3723793de1fd3334383fb5204b5fe6, iPhone 11 iOS 15.2

**Steps**:
Go to  Settings -> Search -> Add Search Engine
Search Engine: youtube, URL: https://youtube.com/search?q=%s
Tap on Save

**Actual**
The search engine is added

**Expected**
The app crashes upton clicking on Save

Automated test: https://github.com/mozilla-mobile/firefox-ios/blob/10895c167d3b4ef944b89ae7037a42b4292a4d4c/XCUITests/SearchSettingsUITest.swift#L58

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4491)

**Comment by isabelrios** [comment]
This is the line that errors: https://github.com/mozilla-mobile/firefox-ios/blob/10895c167d3b4ef944b89ae7037a42b4292a4d4c/ThirdParty/Deferred/Deferred/Deferred.swift#L34

**Comment by isabelrios** [comment]
This is reproducible on both simulator and real devices

**Comment by SimonBasca** [comment]
This issue is reproducible on v103.0 (13264)

**Comment by isabelrios** [comment]
This is still happening on main a6660fa  (Jul 21st)

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verifying as fix on main b66207372d2c8ed00bf937e3cc3d31caf99e8ef8

**Comment by SimonBasca** [comment]
@isabelrios not sure if this test was disabled or skipped but now since the issue is fixed we should re-enable it.

**Comment by data-sync-user** [comment]
➤ JR Johnson commented:

Hello, I wanted to confirm if this is resolved and fixed in the release version. So that we can notify users as needed.

**Comment by data-sync-user** [comment]
➤ Laurie Marceau commented:

JR Johnson The fix for this problem was merged for v105
