### ISSUE TITLE
Search query shows no results

### ISSUE THREAD

**Issue by csuciu** [mozilla-mobile/firefox-ios#11184]
## Steps to reproduce
1. Go to bbc.com
2. Long press on five articles and open them in new tabs.
3. Go to tabs tray and close all tabs.
4. Type "bbc" in the URL bar
### Expected behavior
The top 3 history highlights that are related to the search query should be displayed.
### Actual behavior
The search query shows no results.
### Device & build information
* Device: iPhone 12 Pro (15.5)
* Build version: v9000 (12322)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4490)

**Comment by cpeterso** [comment]
I see a similar problem and it appears to be a regression in v103 (12108).

### Steps to reproduce

1. Downgrade to Testflight build v102 (11640).
2. In the address bar, search for some random phrase that is not in your existing browsing history. I'll use $FOO as a placeholder in this STR.
3. Close $FOO search results page.
4. In the address bar, type $FOO but don't press "go".
5. As expected, you will see a search suggestion for the $FOO search results page.
6. Upgrade to Testflight build v103 (12108).
7. In v103's address bar, type $FOO but don't press "go".
8. As expected, you will see a search suggestion for the $FOO search results page, just like in v102.
9. In the address bar, search for a different random phrase that is not in your existing browsing history. I'll use $BAR as a placeholder in this STR.
10. Close $BAR search results page.
11. In the address bar, type $BAR but don't press "go".

### Expected result

You will see a search suggestion for the $BAR search results page, just like in v102.

### Actual result

You will not see a search suggestion for the $BAR search results page.

**Comment by csuciu** [comment]
Verifying as fixed on v103.0 (13264)
