### ISSUE TITLE
Just browsing the Tabs view can remove Private Tabs

### ISSUE THREAD

**Issue by gutley** [mozilla-mobile/firefox-ios#11208]
This is probably related to #11205 

## Steps to reproduce
Turn on "Close Private Tabs" in the Settings
Create a couple of Private Tabs
Open up the Tabs view - You will see the tabs you created above
In the Tab bar at the top of the screen (Tabs|Private|Synced) click "Tabs" or "Synced"
In the Tab bar at the top of the screen click "Private"

### Expected behavior
You should still see the Private tabs you created previously
### Actual behavior
The Private tabs have vanished and the view is empty

See Screen recording
### Device & build information
* Device: Any
* Build version: v102
### Notes
Attachments: 

https://user-images.githubusercontent.com/2040690/177557824-a8ef5613-7472-4fba-8f3c-7bb638736d36.mov

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4503)

**Comment by dnarcese** [comment]
The "Close Private Tabs" setting closes all private tabs when you switch browsing modes. This seems like intended behaviour unless I am misunderstanding your STR.

**Comment by gutley** [comment]
But i hadn't switched modes, i was only seeing what tabs i had open at the time. I never actually chose a tab from a different mode.
