### ISSUE TITLE
Closing most recent tab from tab index screen closes older tabs

### ISSUE THREAD

**Issue by rr99dlgp** [mozilla-mobile/firefox-ios#11216]
In Firefox iOS -> Open Tabs screen -> close most recent tab

Close most recent tab

Often closes an older tab, seems indiscriminate (not always first tab opened)

Iphone 12 pro, iOS 15.5
Firefox iOS: Firefox Daylight 102.0 (11640) and older versions

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4510)

**Comment by dnarcese** [comment]
This should have been fixed with #11092 which will be released in v103.
