### ISSUE TITLE
Update shavar lists for content blocker if needed

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/firefox-ios#11218]
We are using branch [89.0](https://github.com/mozilla-services/shavar-prod-lists/commits/89.0) from shavar repository (Nov 21) as defined in the [content-blocker](https://github.com/mozilla-mobile/firefox-ios/blob/85e502bff48e690f1c5009badaafd0ef4b9278db/content_blocker_update.sh#L10) script.
The newest branch is 102.0 (March 22)
We are falling behind the new lists, not sure if there are significant changes but worth checking. 

cc @nbhasin2

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4512)

**Comment by lmarceau** [comment]
Newest branch of shavar prod list is now 106.0.
