### ISSUE TITLE
Intermittent Unit Tests failures 

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/firefox-ios#11210]
The unit test workflow is much more stable now but it is causing most of the red builds still. This issue is open to track the tests that we see failing at some point.

- testAsyncDownloadCacheWithAuthenticationOfSetIcon. Build: https://app.bitrise.io/build/e8298c7d-2676-47c1-9607-cc677150aa98?tab=details
- AccountTests crash. Build: https://app.bitrise.io/build/499a4e98-230b-420b-b6a1-85d0197e0a59?tab=details
-

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4504)

**Comment by isabelrios** [comment]
- AccountTests crash. Build: https://app.bitrise.io/build/e522aea0-66bb-45a8-9a73-2c1d516236ea?tab=details

cc @lmarceau since it is seems to be reproducible frequently in the latest builds

**Comment by lmarceau** [comment]
I see the following in logs for that crash:
```
	AccountTests:
		Client (3042) encountered an error (Early unexpected exit, operation never finished bootstrapping - 
no restart will be attempted. (Underlying Error: Test crashed with signal abrt before starting test execution. 
If you believe this error represents a bug, please attach the result bundle at /Users/vagrant/git/xcodebuild.xcresult))
```

**Comment by isabelrios** [comment]
Thanks for looking into this. Yes, I don't think that gives a lot of info... I will try to reproduce locally to see if we can get more info there

**Comment by isabelrios** [comment]
Unit tests are stuck again while running. I have seen a few builds now... See for example this one I aborted after 22mins:
https://app.bitrise.io/app/6c06d3a40422d10f/pipelines/4d40dd26-cee9-4844-a70b-eaa246ecaa7c

cc @lmarceau

**Comment by isabelrios** [comment]
I'm afraid that even thought after tha PR unit tests look more stable, the issue when they stuck while running is still present, see error in build running on main after that patch landed:
https://app.bitrise.io/app/6c06d3a40422d10f/pipelines/6e80efc2-ef48-4ca3-a62a-f240f135412f

**Comment by lmarceau** [comment]
With the latest changes on reset tests, we get a failure on:
```
/Users/vagrant/git/Tests/ClientTests/ResetTests.swift:113: error: -[ClientTests.ResetTests testResetting] : Asynchronous wait failed: Exceeded timeout of 5 seconds, with unfulfilled expectations: "Action on engine fulfilled".
/Users/vagrant/git/Tests/ClientTests/ResetTests.swift:123: error: -[ClientTests.ResetTests testResetting] : XCTAssertEqual failed: ("[<RemoteClient GUID: abcdefghijkl, name: Remote, modified: 1657646628193, type: mobile, formfactor: tablet, OS: Windows, version: 55.0.1a, fxaDeviceId: fxa1>]") is not equal to ("[]")
2022-07-12 17:23:53.494 [Debug] [Profile.swift:424] deinit > Deiniting profile testResetTests.
```

as seen in https://app.bitrise.io/build/47781e7e-3ff7-4175-ab30-9e640feeb346

So it seems there's no more hanging problems at least, and we know what's failing

**Comment by isabelrios** [comment]
> With the latest changes on reset tests, we get a failure on:
> 
> ```
> /Users/vagrant/git/Tests/ClientTests/ResetTests.swift:113: error: -[ClientTests.ResetTests testResetting] : Asynchronous wait failed: Exceeded timeout of 5 seconds, with unfulfilled expectations: "Action on engine fulfilled".
> /Users/vagrant/git/Tests/ClientTests/ResetTests.swift:123: error: -[ClientTests.ResetTests testResetting] : XCTAssertEqual failed: ("[<RemoteClient GUID: abcdefghijkl, name: Remote, modified: 1657646628193, type: mobile, formfactor: tablet, OS: Windows, version: 55.0.1a, fxaDeviceId: fxa1>]") is not equal to ("[]")
> 2022-07-12 17:23:53.494 [Debug] [Profile.swift:424] deinit > Deiniting profile testResetTests.
> ```
> 
> as seen in https://app.bitrise.io/build/47781e7e-3ff7-4175-ab30-9e640feeb346
> 
> So it seems there's no more hanging problems at least, and we know what's failing

Great, good news then, thanks for your work with those tests! 🙏

**Comment by isabelrios** [comment]
Just to add more info here, I see the `testResetting` failing with this error too:
`/Users/vagrant/git/Tests/ClientTests/ResetTests.swift:113 - Asynchronous wait failed: Exceeded timeout of 5 seconds, with unfulfilled expectations: "Action on engine fulfilled".`

Build:https://app.bitrise.io/build/c829b826-0d36-499f-b867-26f06a5aa3f7?tab=details

**Comment by isabelrios** [comment]
Adding a new unit test intermittent failure:
`QuickActionsTest: testOpenBookmarkShortcut_externalSourceIsTrue` : - Crash: Client (3127) <external symbol>

Commit in main build: https://app.bitrise.io/build/b7ad58fa-20ae-42f9-b439-28c5158eae52?tab=details

**Comment by isabelrios** [comment]
`StorageTests: DiskImageStoreTests.testStore()` : - Crash: Client (3165) HomepageViewModel.reloadSection(_:with:)

PR commit: https://app.bitrise.io/build/d5e6245b-89c7-47f9-a27b-fe597c80a0d6

**Comment by isabelrios** [comment]
Today I have seen this test hanging to finish twice:
Test Case '-[ClientTests.SearchBarSettingsViewModelTests testNotificationSent_bottomIsReceived]' started.
See build: https://app.bitrise.io/build/bc6d0f29-e054-4de7-a592-05c79de0624a

Not sure if it will be fixed by PR mentioned above, commenting this just in case

**Comment by isabelrios** [comment]
yay! I have been looking at the builds and same as you, have not seen any issue with unit tests today 🤞  Let's keep an eye on the tests tomorrow and if everything looks as today, agreed, we can close this and if something happens, open a new one. This is getting long and a lot of work has been done

**Comment by isabelrios** [comment]
More than 20 green builds in a row! 🎉  
Closing this issue, I think as you said above @lmarceau that the hanging issues are fixed now! thanks for your hard work to get that done! 💪 👏
