### ISSUE TITLE
The "Yesterday", "Last week", "Last Month" sections are not immediately displayed after collapsing "Today"

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#11222]
## Steps to reproduce
1. Go to history
1. Collapse the "Today" section -> observe that the other sections are not displayed.
1. Expand the "Today" section and scroll the panel 
1. Collapse the "Today" section -> observe that the other sections are displayed.
    1. Expected behavior

* The "Yesterday", "Last week", "Last Month" sections should be displayed.
    1. Actual behavior
* The "Yesterday", "Last week", "Last Month" sections are not immediately displayed after collapsing "Today".
    1. Device & build information
* Device: iPad Pro 15.5
* Build version: 102.1 (12709)
    1. Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4516)

**Comment by data-sync-user** [comment]
➤ Daniela Arcese commented:

This is intended behaviour right now because we don’t fetch the next results until we scroll to the bottom of the list
