### ISSUE TITLE
[iPhone] Download prompt is not triggered at redditsave.com

### ISSUE THREAD

**Issue by softvision-raul-bucata** [mozilla-mobile/firefox-ios#11230]
## Steps to reproduce
1. Navigate to: https://redditsave.com/info?url=https%3A%2F%2Fwww.reddit.com%2Fr%2FMadeMeSmile%2Fcomments%2Fvu2gc2%2Fhockey_player_thinks_his_penalty_is_bullshit%2F
1. Scroll the page.
1. Tap on the "Download HD Video" button.
1. Observe the result.
### Expected behavior
A download prompt is triggered.
### Actual behavior
A new window opens, with a broken "Play" button.
### Device & build information

* Device: iPhone 8 Operating System: iOS 15.5
* Build version: Firefox Daylight 102.0 (11640) 
### Notes

1. Reproducible regardless of the status of ETP.
1. Works as expected using the latest build of Edge.
1. Initially reported here: https://github.com/webcompat/web-bugs/issues/107066

**Attachments:**

Firefox:
![Screenshot!UNITO-UNDERSCORE!16](https://user-images.githubusercontent.com/75027050/177990280-aedc639a-1f55-4851-9b53-3f929621c89a.jpg)

Edge:
![Screenshot!UNITO-UNDERSCORE!17](https://user-images.githubusercontent.com/75027050/177990305-bd428183-75f9-40d7-8b87-bdb6b2d89e61.jpg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4522)

**Comment by gutley** [comment]
FYI this is caused by the following being commented out inside DownloadHelper:

```
        // Bug 1474339 - Don't auto-download files served with 'Content-Disposition: attachment'
        // Leaving this here for now, but commented out. Checking this HTTP header is
        // what Desktop does should we ever decide to change our minds on this.
        // let contentDisposition = (response as? HTTPURLResponse)?.allHeaderFields["Content-Disposition"] as? String
        // let isAttachment = contentDisposition?.starts(with: "attachment") ?? (mimeType == MIMEType.OctetStream)

        guard isAttachment || !canShowInWebView || forceDownload else {
            return nil
        }
```

The response does indeed have a contentDisposition starting with "attachment" . Here's the full response:

```
<NSHTTPURLResponse: 0x292eb9c80> { URL: https://sd.redditsave.com/download.php?permalink=https://reddit.com/r/MadeMeSmile/comments/vu2gc2/hockey_player_thinks_his_penalty_is_bullshit/&video_url=https://v.redd.it/wkvpw0bsy9a91/DASH_720.mp4?source=fallback&audio_url=false } { Status Code: 200, Headers {
    "Alt-Svc" =     (
        "h3=\":443\"; ma=86400, h3-29=\":443\"; ma=86400"
    );
    "Cache-Control" =     (
        "must-revalidate, post-check=0, pre-check=0"
    );
    "Content-Disposition" =     (
        "attachment; filename=\"redditsave.com_hockey_player_thinks_his_penalty_is_bullshit-wkvpw0bsy9a91.mp4\""
    );
    "Content-Length" =     (
        3345316
    );
    "Content-Type" =     (
        "application/octet-stream"
    );
    Date =     (
        "Tue, 12 Jul 2022 14:37:23 GMT"
    );
    Expires =     (
        0
    );
    Pragma =     (
        public
    );
    "Report-To" =     (
        "{\"endpoints\":[{\"url\":\"https:\\/\\/a.nel.cloudflare.com\\/report\\/v3?s=Vw3w8QzmzYBTVLZMR63SylMNP1TSbzyQNECPgKYOFbCwcjjRwUUymBUZX4HuwGb%2FEztP3AizGoVxOrVg9OAM9t9ii9NKYJDo%2B7cumQvDzxcFlikBYVU3VkMF9%2BT7V6k0Iix0dQ%3D%3D\"}],\"group\":\"cf-nel\",\"max_age\":604800}"
    );
    Server =     (
        cloudflare
    );
    Vary =     (
        "Accept-Encoding"
    );
    "cf-cache-status" =     (
        DYNAMIC
    );
    "cf-ray" =     (
        "729a8421e99c7780-LHR"
    );
    "content-description" =     (
        "File Transfer"
    );
    "content-transfer-encoding" =     (
        Binary
    );
    "expect-ct" =     (
        "max-age=604800, report-uri=\"https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct\""
    );
    nel =     (
        "{\"success_fraction\":0,\"report_to\":\"cf-nel\",\"max_age\":604800}"
    );
} }
```

and the mimeType is video/mp4

**Comment by gutley** [comment]
FYI - Safari offers to either view or download the file (it also fails to load if viewed)
![image](https://user-images.githubusercontent.com/2040690/178518925-395e460b-4e3f-4a33-a23b-5b7f7f515e3e.png)

**Comment by gutley** [comment]
This issue still happens as we still do not respect the content disposition header
