### ISSUE TITLE
 Download prompt is dismissed when tapping on the file name

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#11249]
## Steps to reproduce
1. Visit [https://www.thinkbroadband.com/download](https://www.thinkbroadband.com/download)
1. Tap on file to download it
1. When the download prompt is displayed, tap on the file name

## 

    1. Expected behavior

* Download prompt should not be dismissed.

*# 
*## Actual behavior

* Download prompt is dismissed.

*# 
*## Device & build information

* Device: iPhone 12 Pro (15.4)
* Build version: 3cb72444e03e4399bc2f4e171a0d3601217b4cb4

*# 
*## Notes
Attachments: 

!image-20221122-183458.png|width=536,height=1162!

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4529)

**Comment by SimonBasca** [comment]
@gutley this has already been fixed on main in https://github.com/mozilla-mobile/firefox-ios/issues/10361

**Comment by data-sync-user** [comment]
➤ Catalin Suciu commented:

The prompt is no longer dismissed when tapping on the file name. Verifying as fixed on v9000 (24964).
