### ISSUE TITLE
Oval Firefox logo on the homepage

### ISSUE THREAD

**Issue by vojtz** [mozilla-mobile/firefox-ios#11244]
Just aesthetic. I notice that the Firefox logo on the homepage is oval in compare to the logo on the FF page. Something like incorrect scaling. The same on landscape mode and portrait as well.

### Device & build information
* Device: iPad Pro 11” 1st generation
* Build version: Firefox Daylight 102.0 (11640) on iPadOS 15.5

Attachments: 
![Ff ico](https://user-images.githubusercontent.com/28898355/178337060-8a45b9c6-6a1d-4a9e-b392-7c3454f7224b.jpg)

![039F95E6-497D-4298-8FF1-1614C4375F21](https://user-images.githubusercontent.com/28898355/178336426-b8cbd9ad-0079-461e-9a14-2b3d0fbd903d.jpeg)
![6BC75918-62F3-4F48-934B-25C800621325](https://user-images.githubusercontent.com/28898355/178336432-0888849f-8da6-44c8-b392-1e60bc87e16c.jpeg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4527)

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verifying as fix on main da7a6a4d1ed3630f60e307a623f3d8956e6184c3
