### ISSUE TITLE
The WebView goes outside the safe area in Landscape mode

### ISSUE THREAD

**Issue by Mara-d** [mozilla-mobile/firefox-ios#11257]
## Steps to reproduce
1. Launch Firefox in Landscape mode.
1. Open a new PB page.
1. From the Home page tap on the `youtube.com` page.
1. Dismiss the page's pop-up.
1. Press the Home button.
1. Tap on the `google.com` page.
1. Dismiss the page's pop-up.
### Expected behavior
In Landscape mode, the WebView should remain within the safe area.
### Actual behavior
The WebView goes over the safe area.
### Device & build information

* Device: iPhone 13 Mini (15.5), iPhone 11 Pro Max (15.5)
* Build version: 102.1 (127109), Latest main 9000 (13173)
### Notes

Attachments: 

https://user-images.githubusercontent.com/65923892/178727489-2eccd65f-5453-415c-bd6e-aa3b21bf3192.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4536)

**Comment by struq** [comment]
Not fixed yet. v116.1 (33291)
