### ISSUE TITLE
Search Term groups is not grouping on Recently visited, TabTray, JumpBack-In and HistoryPanel

### ISSUE THREAD

**Issue by yoanarios** [mozilla-mobile/firefox-ios#11256]
## Steps to reproduce
- Do a search and open links from the search to build a group
- Inspect Recently visited, TabTray, JumpBack-In and HistoryPanel

### Expected behavior
- Group should appear 

### Actual behavior
- Individual items are listed

### Device & build information
* Device: ?
* Build version: v103 and main
### Notes
Investigate if history metadata is being recorded properly because the bug is reproducible on every screen that has STG the root cause could be in the recording 
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4534)

**Comment by SimonBasca** [comment]
Verifying as fix on v103.0 (13264)

Note: We've logged one issue while testing this (https://mozilla-hub.atlassian.net/browse/FXIOS-4543)
