### ISSUE TITLE
Update JD URL in topsites for China edition

### ISSUE THREAD

**Issue by yliuu** [mozilla-mobile/firefox-ios#11265]
The current URL is:

https://union.click.jd.com/jdc?e=0&p=AyIHVCtaJQMiQwpDBUoyS0IQWlALHE4YDk5ER1xONwdJKVxASgI%2BeDkWfGJ6HEAOUmkbcjUXVyUBEQZRG1IXARQ3VhhaEQETBVweayVkbzcedVolBxIEUBxdFAoQN1UeXRQLGwFXHlsUABs3UisnS0lKWghLWBQCFzdlK2s%3D&t=W1dCFBBFC14NXAAECUte

The link has expired, pls help to update it to:

https://union-click.jd.com/jdc?e=618%7Cpc%7C&p=JF8BAKgJK1olXDYDZBoCUBVIMzZNXhpXVhgcCEEGXVRFXTMWFQtAM1hXWFttFkhAaihBfRN1XE5ZMipYVQ1uYwxAa1cZbQIHUV9bCUkQAF8LGFoRXgcAXVttOEsSMyRmGmsXXAcAXFdaAEwVM28PH10TVAMHVVpbDE8nBG8BKydLFl5fCQ5eCUsSM184GGsSXQ8WUiwcWl8RcV84G1slXTZdEAMAOEkWAmsBK2s

Thanks!

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4539)

**Comment by lmarceau** [comment]
I could test China top sites by making sure I had the `zh_CN` locale by changing the phone language. I also checked with the china toggle that all was good.

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Please note that this issue will be verified after https://github.com/mozilla-mobile/firefox-ios/issues/11584 ( https://github.com/mozilla-mobile/firefox-ios/issues/11584|smart-link )  is addressed

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verifying as fix on main 068cf4fc56facb45c0cc1c75b45eaedd7d27a434
