### ISSUE TITLE
FXIOS-4494 needs uplift

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#11270]
Issue https://mozilla-hub.atlassian.net/browse/FXIOS-4494 is still reproducible on v103.0 (13264). 

Please uplift https://github.com/mozilla-mobile/firefox-ios/pull/11212

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4542)

**Comment by csuciu** [comment]
Verified as fixed on v103.0 (13326)
