### ISSUE TITLE
Ipad crash when switching between normal and private browsing by pressing the mask button

### ISSUE THREAD

**Issue by DimonMobile** [mozilla-mobile/firefox-ios#11273]
## Steps to reproduce
Multiple fast taps on private button lead to crash
### Expected behavior
Successfully switching
### Actual behavior
Crash
### Device & build information
* Device: ipad pro 11inch 3rd
* Build version: Firefox Daylight 102.0 (11640)
### Notes
Attachments: 
![CB1F5010-FFB2-486C-8A5C-9E3E74C7B5A3](https://user-images.githubusercontent.com/35412039/179005914-197347ea-0356-4897-984f-8f5ac11c84a8.jpeg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4544)

**Comment by SimonBasca** [comment]
@DimonMobile I am unable to reproduce the issue on  102.0 (11640) or latest main eb3dfcba028bf21e96193de732e2fe3a2681ae46 . could you please share a video of the issue? Also could you please clarify the "expected results"?

**Comment by SimonBasca** [comment]
@DimonMobile the video is broken. could you please resend it? Also could you please clarify at what step is the app crashing? When pressing the "back", "forward" or "private browsing" button?

**Comment by gutley** [comment]
@SimonBasca If you download the video it plays just fine. Seems all he is doing is pressing the Private button a couple of times. No idea why he 'arrows' the back and forwards buttons in the screenshot.

**Comment by gutley** [comment]
Not sure its in the ups file, but here's the console log just before it crashes:

```
2022-07-19 10:34:27.469483+0100 Client[2071:1599180] *** Assertion failure in -[_UICollectionCompositionalLayoutSolver _queryClientForSectionDefinitionForSectionIndex:], _UICollectionCompositionalLayoutSolver.m:2927
2022-07-19 10:34:27.472448+0100 Client[2071:1599180] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid section definition. Please specify a valid section definition when content is to be rendered for a section. This is a client error.'
*** First throw call stack:
(0x1828b5d0c 0x19a0a6ee4 0x18405bc90 0x185340c60 0x185340d84 0x184e1c9d0 0x185071030 0x184e7edc8 0x184f0f2d4 0x184efd500 0x184d8bd14 0x1055b4914 0x105463578 0x104ff0714 0x10549a634 0x104ff0714 0x107bd4700 0x107bd5fc8 0x107be48ac 0x107be44fc 0x1828710c4 0x18282e5e8 0x182841240 0x1a314b988 0x18504141c 0x184ddab88 0x1056280c0 0x1078ac3d0)
libc++abi: terminating with uncaught exception of type NSException
dyld4 config: DYLD_LIBRARY_PATH=/usr/lib/system/introspection DYLD_INSERT_LIBRARIES=/Developer/usr/lib/libBacktraceRecording.dylib:/Developer/usr/lib/libMainThreadChecker.dylib:/Developer/Library/PrivateFrameworks/DTDDISupport.framework/libViewDebuggerSupport.dylib
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid section definition. Please specify a valid section definition when content is to be rendered for a section. This is a client error.'
terminating with uncaught exception of type NSException
```

Called from FirefoxHomeViewModel.reloadSection(_:with:) at the 
```
        collectionView.reloadData()
```
line

**Comment by DimonMobile** [comment]
Yes, problem is in private browsing button.
Using the arrows, I wanted to focus attention on the button, sorry if it was misleading
