### ISSUE TITLE
The "Recently visited" section is not updated with  the group

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#11271]
### Steps to reproduce
1. Visit a "biziday.com"
1. Long press on a link and open in new tab
1. Repeat step 2) three times
1. Observe the "Recently visited" and "History" section

### Expected behavior
* The group should be created in "History" and "Recently visited

*### Actual behavior

* The group should is not created in "History" and "Recently visited

### Device & build information
* Device: iPhone 13 mini (15.5)
* Build version: 103 (13264)

## Issue is reproducible only when opening links after loading "[http://biziday.ro](http://biziday.com|smart-link) " from the URL. If "biziday" is load from a google search, the groups are correctly created.
Attachments: 

[https://user-images.githubusercontent.com/32130829/178986847-e28554cb-c998-42e0-a6aa-bf16b760be65.mp4](https://user-images.githubusercontent.com/32130829/178986847-e28554cb-c998-42e0-a6aa-bf16b760be65.mp4)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4543)

**Comment by data-sync-user** [comment]
➤ Yoana Rios Diaz commented:

Simion Basca could you confirm if this is reproducible in previous versions? We based our grouping logic on search term groups that’s why it’s working when the site is open from a google search so this is how the feature was implemented so it could be a feature improvement

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Yoana Rios Diaz this is also reproducible on older builds e.g. 102.1 (12709)
