### ISSUE TITLE
Fix tabs sync metrics

### ISSUE THREAD

**Issue by lougeniaC64** [mozilla-mobile/firefox-ios#11286]
This is a duplicate of [SYNC-3237](https://mozilla-hub.atlassian.net/browse/SYNC-3237). We're updating the payload of the `temp-rust-tabs-sync` metrics to allow them to be submitted to Glean.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4553)

**Comment by dnarcese** [comment]
@lougeniaC64 is this completed? If not, is it something you would like our team to complete?

**Comment by lougeniaC64** [comment]
@dnarcese Yes, this was fixed in PR #11285.
