### ISSUE TITLE
Send tab from desktop opened in Safari instead of Firefox for iOS

### ISSUE THREAD

**Issue by kelimuttu** [mozilla-mobile/firefox-ios#11288]
## Steps to reproduce

* Login to FxA on desktop and iOS
* Send tab from desktop to iOS

### Expected behavior
* Tab opened in Firefox

### Actual behavior
* Tab opened in Safari

### Device & build information
* Device: iPhone 12 (15.5)
* Build version: 102.0 (11640)

### Notes
Attachments: see the following screen record: https://t.co/TcrFNjk83J

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4554)

**Comment by kelimuttu** [comment]
This was first reported to our support account on Twitter: https://twitter.com/Bromium_Ion/status/1546167102415011842

**Comment by kelimuttu** [comment]
I know we have https://github.com/mozilla-mobile/firefox-ios/issues/11020, but I'm not sure if it's the same issue, so I filed a new one.

**Comment by kelimuttu** [comment]
See also: https://bugzilla.mozilla.org/show_bug.cgi?id=1535677

**Comment by mhammond** [comment]
I *think* this is the expected behaviour if Safari is the default browser. At least on Android, we hand the URL to the OS because some URLs get handled by other apps (eg, google maps is the most obvious example), and if the URL ends up falling back to wanting to be opened by a browser, the OS opens the default browser. I had a quick look at the iOS code and I can't be sure that's also the case here, but it does look like it might be.

**Comment by kelimuttu** [comment]
@mhammond I have Firefox set as the default browser in this scenario.

**Comment by csuciu** [comment]
I've tried to reproduce this issue on latest version but wasn't able to. The tab sent from Firefox desktop is opened in Firefox iOS no matter which app (Firefox or Safari) is set as default browser.

**Comment by kelimuttu** [comment]
I wonder if my setting/preference might've caused it. But it's still happening to me until now.

**Comment by dnarcese** [comment]
@kelimuttu are you clicking the Safari popup at the bottom of the app switcher? Or are you clicking 'Send tab to device' from your Firefox desktop?

**Comment by kelimuttu** [comment]
@dnarcese Yes. I clicked the Safari pop up since I don't see any notification from Firefox.
