### ISSUE TITLE
Closing tabs quickly selects the wrong tab to close when swiping

### ISSUE THREAD

**Issue by ericswpark** [mozilla-mobile/firefox-ios#11297]
## Steps to reproduce

Swipe quickly when closing tabs.

### Expected behavior

The tab under your finger should close. 

### Actual behavior

If swiping very quickly, sometimes Firefox will start to scroll the tab view to fill the remaining space. While it is scrolling, when you put your finger on a tab and swipe left/right to close it, sometimes the tab on top will close instead.

So for example:

A B
C D
E F
G

After closing tab G, the rest of the tabs will slide down as Firefox gets rid of the extra overhang scroll area. While this is happening, if you put your finger on E and swipe, sometimes tab C will close instead. You can actually see the wrong tab move if you keep holding and do not swipe completely to close the tab.

Sometimes tab D will move back and forth instead even when my finger is on E. I think this is some sort of touch target check issue, where Firefox is not correctly checking where tabs are on the screen right now as the scrolling happens. This is incredibly jarring and frustrating if the wrong tab is closed, as I now have to go and manually find and re-open that tab from history.

### Device & build information
* Device: iPhone XS Max
* Build version: 102.1

### Notes

I'd like to do a screen recording demonstrating the problem but I can't figure out how to show touches inside the recording on iOS. It's easily reproducible, though.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4560)

**Comment by SimonBasca** [comment]
This should be fixed in v103 by https://github.com/mozilla-mobile/firefox-ios/pull/11092.
