### ISSUE TITLE
Can’t delete searched items from history

### ISSUE THREAD

**Issue by JimmysDev** [mozilla-mobile/firefox-ios#11290]
## Steps to reproduce

Open history, search for something and then try to delete it by swiping or long pressing.

### Expected behavior

If I open history, I can delete entries by swiping left on them; and I can get more options for an entry by long pressing.

### Actual behavior

If I search for a site or keyword in history, I am not able to swipe or long press on the search results, meaning I cannot delete them, or open them in new tabs/add them to shortcuts.

### Device & build information
* Device: iPhone 12 running iOS 15.4
* Build version: Firefox Daylight 102.0 (11640)
### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4556)

**Comment by SimonBasca** [comment]
Verifying as fix on main da7a6a4d1ed3630f60e307a623f3d8956e6184c3

Note that https://github.com/mozilla-mobile/firefox-ios/issues/10745 is still reproducible.
