### ISSUE TITLE
[iPhone] Reload button is not functional after focusing the URL bar

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#11298]
## Steps to reproduce
1. Visit a page
2. Tap on the URL bar to focus on it
3. Dismiss the URL bar focus
4. Tap the reload button
### Expected behavior
- Reload button should be functional
### Actual behavior
- Reload button is not functional
### Device & build information
* Device: iPhone 12 Pro (15.5)
* Build version: 103 (13326) and main eb3dfcba028bf21e96193de732e2fe3a2681ae46
### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4561)

**Comment by lmarceau** [comment]
Tested on iPad (also in multitasking) and iPhone that this had no other effect than the actual fix. Hopefully didn't miss anything else @SimonBasca

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verifying as fix on main ab7d82776b14b0a7898c791ac5f5841cf0309a7a
