### ISSUE TITLE
The view scrolls to the bottom of the list when adding a folder or bookmark via the "+" button

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#11324]
## Steps to reproduce
1. Go to bookmark folder
2. Tap on the "+" button
3. Tap "New folder" or "Bookmark"
4. Type a name
5. Tap "Done"
### Expected behavior
- The view should not scroll.
### Actual behavior
- The view scrolls to the bottom of the list.
### Device & build information
* Device: iPhone 13 mini (15.5)
* Build version: 9000 (13592)
### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4583)

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verifying as fix on v104.0 (14172).
