### ISSUE TITLE
No "save" button is displayed after editing a bookmark

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#11328]
## Steps to reproduce
1. Go to bookmark panel
2. Tap on "Edit"
3. Tap on a bookmark
4. Change the name or the URL
5. Save the changed
### Expected behavior
- Save button should be displayed.
### Actual behavior
- No "save" button is displayed. Note that the top "Done" button dismisses the bookmark panel.
### Device & build information
* Device: iPhone 13 mini (15.5)
* Build version: 9000 (13592)
### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4587)

**Comment by SimonBasca** [comment]
Verifying as fix on 104.0 (14172)

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verifying as fix on 104.0 (14172)
