### ISSUE TITLE
The Edit/Done button visibility is inconsistent due to the bottom section

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/firefox-ios#11327]
## Steps to reproduce
1. Go to bookmarks
2. Access the `desktop bookmarks` folder.
3. Access any of the `Unsorted, Toolbar, Menu bookmarks`.
4. Scroll down and up.
5. Observe the `Edit` button.
### Expected behavior
- The `Edit` button should be more visible and the bottom section should be more like a toolbar.
### Actual behavior
- The `Edit/Done` button visibility is inconsistent due to the bottom section.
### Device & build information
* Device: iPhone 13 Pro Max (15.1.1)
* Build version: 9000 (13592)
### Notes
Please note that if entering the edit mode and then closing with a swipe down the bookmark menu, when entering again, the bottom toolbar is there and the `Edit/Done` button is more visible.
Attachments: 

https://user-images.githubusercontent.com/42831109/179764634-02262523-8c2b-4104-b302-5590d5cc093f.mov

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4586)

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Verified as fixed on v104 (14172) with iPad mini 5 (14.7) and iPhone 15 Pro Max (15.1.1).
