### ISSUE TITLE
Bookmark folder buttons are not consistent while in "Edit" mode

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#11323]
## Preconditions
- Have one folder or bookmark created in Bookmarks
## Steps to reproduce
1. Go to bookmarks
2. Tap on "Edit" - > Observe the button changes to "Done"
3. Tap on the Folder or bookmark
4. Tap "<" button
5. Observe the bottom "Done" button is changed back to "Edit"
### Expected behavior
- The buttons should be consistent
### Actual behavior
- The buttons are not consistent after step 4
### Device & build information
* Device: iPhone 13 mini
* Build version: 9000 (13592)
### Notes
- Tapping again on "Edit" will display the bottom "Done" button and the user can exist edit mode
Attachments: 

https://user-images.githubusercontent.com/32130829/179749466-99c5e45f-016a-4a7a-8888-c00c2ae3f893.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4582)

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verifying as fix on v104.0 (14172)
