### ISSUE TITLE
Option to disable recent bookmarks in bookmarks menu

### ISSUE THREAD

**Issue by umbralOptimatum** [mozilla-mobile/firefox-ios#11336]
I don't find the Recent Bookmarks feature useful. As a matter of fact, I often find it quite distracting when opening the bookmarks menu to find specific to be bombarded by an unrelated selection of websites. I'd also prefer not to make a chunk of my recent browsing visible to anyone who looks over my shoulder. Could we have an option to turn off the recent bookmarks display?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4591)

**Comment by lmarceau** [comment]
@umbralOptimatum I can give you a sneak peak and say that this section will be removed soon :) So no settings needed in that case.
