### ISSUE TITLE
Update Back forward list theming

### ISSUE THREAD

**Issue by junbio** [mozilla-mobile/firefox-ios#11345]
## Steps to reproduce
1. Long press back button
2. Switch to dark mode 

### Expected behavior
Back forward list changes to dark mode

### Actual behavior
Back forward list remains in light mode

### Device & build information
* Device: iPhone X
* Build version: 102.1 12709
### Notes
Attachments: 
![IMG_5410](https://user-images.githubusercontent.com/66826029/180022859-68cb41c8-4a79-41f0-90b5-f9da8f036e27.PNG)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4599)

**Comment by data-sync-user** [comment]
➤ Laurie Marceau commented:

Changed the name of the task since updating to the new theming system should/need to fix this.

**Comment by data-sync-user** [comment]
➤ Catalin Suciu commented:

Verifying as fixed on v9000 (24964)
