### ISSUE TITLE
[Crash] When tapping on a letter and "X" icon at the same time

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#11340]
## Steps to reproduce
1. Tap on the URL bar
2. Type "r", "e"
3. When the autocomplete is displayed tap on the "X" button and on "e" at the same time
### Actual behavior
- Firefox crashes.
### Device & build information
* Device: iPhone 12 Pro
* Build version: eb3dfcba028bf21e96193de732e2fe3a2681ae46
### Notes
Attachments: 

https://user-images.githubusercontent.com/32130829/179998713-65cb8a03-7430-48c1-bec4-2a805f825722.mp4

[Client-2022-07-20-142047.ips.zip](https://github.com/mozilla-mobile/firefox-ios/files/9150312/Client-2022-07-20-142047.ips.zip)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4595)

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

This issue is no longer reproducible on v102.2 (13909). Marking as verified fix.
