### ISSUE TITLE
Tag 102.1 doesn't follow naming convention

### ISSUE THREAD

**Issue by gutley** [mozilla-mobile/firefox-ios#11357]
@lmarceau I just noticed that the tag for version 102.1 is "102.1" and not "v102.1" as was normal up until now.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4605)

**Comment by lmarceau** [comment]
Indeed, as Github wasn't letting me put the tag name as the name of the branch anymore.

**Comment by lmarceau** [comment]
Closing this as couldn't find a work around
