### ISSUE TITLE
Firefox crashes when syncing while shortcuts are disabled

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#11359]
## Steps to reproduce
1. Log in to FxA
2. Go to Settings -> Homepage -> Disable shortcuts
3. Open tabs tray 
4. Go to synced tabs or tap the sync button from settings
### Actual behavior
- Firefox crashes.
### Device & build information
* Device: iPhone 12 Pro (15.5)
* Build version: 103.0 (13677) and 102.2
### Notes
Attachments: 

[Client-2022-07-21-152313.ips.zip](https://github.com/mozilla-mobile/firefox-ios/files/9159331/Client-2022-07-21-152313.ips.zip)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4606)

**Comment by SimonBasca** [comment]
Might be related to :
- https://github.com/mozilla-mobile/firefox-ios/issues/11340
- https://github.com/mozilla-mobile/firefox-ios/issues/11233

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

This issue is no longer reproducible following the STR. Marking as verified fix on v102.2 (13909)
