### ISSUE TITLE
[Xcode 14 warnings] Non-'@objc' instance method in extensions in SQLiteRemoteClientsAndTabs

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#11378]
`Non-'@objc' instance method in extensions cannot be overriden; use 'public' instead`

in SQLiteRemoteClientsAndTabs.swift

!Screen Shot 2022-07-18 at 5.22.55 PM.png|width=1791,height=747!

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4616)

**Comment by lmarceau** [comment]
![Screen Shot 2022-07-18 at 5 22 55 PM](https://user-images.githubusercontent.com/11338480/180469921-6bf682bb-ab7e-4ac4-bdf2-31bfa8e2c6b5.png)
