### ISSUE TITLE
[Xcode 14 warnings] Non-'@objc' instance method in extensions in NSCoderExtensions

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#11379]
`Non-'@objc' instance method in extensions cannot be overriden; use 'public' instead`

in NSCoderExtensions.swift

!Screen Shot 2022-07-18 at 5.23.10 PM.png|width=1768,height=876!

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4617)

**Comment by lmarceau** [comment]
![Screen Shot 2022-07-18 at 5 23 10 PM](https://user-images.githubusercontent.com/11338480/180469968-36651ca6-a06d-4095-9711-5bde2a6f2ea3.png)
