### ISSUE TITLE
Recently Visited Cards Break in Landscape View

### ISSUE THREAD

**Issue by cwzilla** [mozilla-mobile/firefox-ios#11377]
## Steps to reproduce
1. Visit a few sites so links appear in Recently Visited section
2. Rotate phone to landscape and scroll through homepage

### Expected behavior
- A normal looking card

### Actual behavior
- The card looks broken, showing the wallpaper behind
- It isn't always broken in the same places, sometimes it's wider, sometimes it's more narrow

### Device & build information
* Device: iPhone 12 
* Build version: 102.1 (12709)
### Notes
Attachments: 
![IMG_6850](https://user-images.githubusercontent.com/87655586/180467872-c5b79461-f4e5-493d-8632-8080ce06eb0f.PNG)
![IMG_6851](https://user-images.githubusercontent.com/87655586/180467882-89909cec-ad39-475f-a15e-e55d8b781825.PNG)
![IMG_6852](https://user-images.githubusercontent.com/87655586/180467886-2403df30-99d8-49e9-8c0f-aabe272d759e.PNG)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4615)

**Comment by lmarceau** [comment]
Hello! Thanks for opening this ticket, we already have https://github.com/mozilla-mobile/firefox-ios/issues/11002 to track this so I'll close this one in favor of the other one.
