### ISSUE TITLE
[Xcode 14 warnings] Run scripts will be run during every build

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#11381]
`Run script [XXX] will be run during every build because it does not specify any outputs. [...]`

for ‘Swiftlint' and 'Conditionally Add Settings Bundle’ scripts

!Screen Shot 2022-07-18 at 5.24.10 PM.png|width=357,height=280!

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4619)

**Comment by lmarceau** [comment]
![Screen Shot 2022-07-18 at 5 24 10 PM](https://user-images.githubusercontent.com/11338480/180470156-bd4836f0-f7ff-4630-8deb-5b6dc49e3294.png)
