### ISSUE TITLE
'Show All' links don't align with the heading baseline

### ISSUE THREAD

**Issue by cwzilla** [mozilla-mobile/firefox-ios#11383]
## Steps to reproduce
1. View the Homepage
2. Observe all the section headings and the Show All links (Jump Back In, Recently Visited, etc...)

### Expected behavior
- Show All links should align with the Heading baseline

### Actual behavior
- It's lower than the Heading text and doesn't look aligned

### Device & build information
* Device: 12
* Build version: 102.1 (12709)
### Notes

Attachments: 
![Group 8](https://user-images.githubusercontent.com/87655586/180470586-b258db5a-e9ef-42f3-9aa1-a9dd28fbd119.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4621)

**Comment by lmarceau** [comment]
@thatswinnie I think you fixed this in your branch for https://github.com/mozilla-mobile/firefox-ios/issues/9982 ?

**Comment by thatswinnie** [comment]
@lmarceau correct, it was fixed in that PR

**Comment by lmarceau** [comment]
Great, then once merged I guess this can be brought to QA needed column 🎉

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verifying as fix on main da7a6a4d1ed3630f60e307a623f3d8956e6184c3
