### ISSUE TITLE
Why Official Firebox not support WebXR API?

### ISSUE THREAD

**Issue by pagongamedev** [mozilla-mobile/firefox-ios#11386]
### User Problem
> Why Official Firebox not support WebXR API?
But i can do in WebXR Viewer but it discontinued update

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4622)

**Comment by lmarceau** [comment]
Hi @pagongamedev, we have a webxr branch [here](https://github.com/mozilla-mobile/firefox-ios/tree/webxr)

**Comment by pagongamedev** [comment]
> Hi @pagongamedev, we have a webxr branch [here](https://github.com/mozilla-mobile/firefox-ios/tree/webxr)

WebXR Branch Not Update More than 2 years and not include in firefox ios but deploy to webxr viewer

why i ask official not include it in main firefox


<img width="902" alt="Screen Shot 2565-07-27 at 11 43 15" src="https://user-images.githubusercontent.com/18329411/181163222-bb89b186-1fa7-4e07-a2fc-5408ce7f1504.png">

**Comment by lmarceau** [comment]
As with any open source project supported by contributors and other teams, projects sometimes stop being under active development. Any contributors can make this branch alive again, but at the moment there's no active development on this project from the Firefox for iOS team.

**Comment by Thaina** [comment]
> As with any open source project supported by contributors and other teams, projects sometimes stop being under active development. Any contributors can make this branch alive again, but at the moment there's no active development on this project from the Firefox for iOS team.

I think the point is we see no reason why it not merged into the main branch so people can continued contribution with the assumption that it will be available eventually and not be neglected in the uncaring branch

**Comment by lmarceau** [comment]
I am unsure as to why that particular branch was never merged into `main`, as I wasn't being part of the project at point in time. Whatever the reason was, result is that we have this branch that cannot be directly merged into `main` without significant effort as the project significantly changed in the spawn of ~3 years. But any contributors can make this branch alive again if they wish.

**Comment by Creative-Ataraxia** [comment]
> > As with any open source project supported by contributors and other teams, projects sometimes stop being under active development. Any contributors can make this branch alive again, but at the moment there's no active development on this project from the Firefox for iOS team.
> 
> I think the point is we see no reason why it not merged into the main branch so people can continued contribution with the assumption that it will be available eventually and not be neglected in the uncaring branch

was wondering the same thing, I would like to test some XR apps on iOS but can't due to the fact that webxr viewer doesn't load https
