### ISSUE TITLE
Logo on Homepage is stretched vertically

### ISSUE THREAD

**Issue by cwzilla** [mozilla-mobile/firefox-ios#11382]
## Steps to reproduce
1. View the Homepage

### Expected behavior
- Normal height logo

### Actual behavior
- The logo looks squished, see attached photos for comparison

### Device & build information
* Device: iPhone 12
* Build version: 102.1 (12709)
### Notes
Attachments: 
![IMG_6848](https://user-images.githubusercontent.com/87655586/180468326-8a540d61-8772-4e78-ab6a-f4f951c70323.PNG)
<img width="1158" alt="Screen Shot 2022-07-22 at 11 11 16 AM" src="https://user-images.githubusercontent.com/87655586/180469500-531eda82-e3da-4205-a11c-59d30f0f08b9.png">

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4620)

**Comment by lmarceau** [comment]
Closing as duplicates of https://github.com/mozilla-mobile/firefox-ios/issues/11244
