### ISSUE TITLE
[Xcode 14 warnings] Cannot access property in deinitializer in GridTabViewController

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#11380]
`Cannot access property [XXX] here in deinitializer; this is an error in Swift 6`

in GridTabViewController.swift

!Screen Shot 2022-07-18 at 5.24.02 PM.png|width=1729,height=245!

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4618)

**Comment by lmarceau** [comment]
![Screen Shot 2022-07-18 at 5 24 02 PM](https://user-images.githubusercontent.com/11338480/180470119-85aa7a7f-905b-4539-bbf7-dae8b4d10268.png)
