### ISSUE TITLE
Duplicate build file warning file in Compile Sources

### ISSUE THREAD

**Issue by byaruhaf** [mozilla-mobile/firefox-ios#11461]
The files below appear twice in the Compile Sources build phase causing the warnings below.

- LibraryPanelHelper.swift
- PushCryptoTests.swift
- PushClientTests.swift

**Warnings**

![image](https://user-images.githubusercontent.com/4116539/181861804-f10a0a20-14be-4fcf-967e-846e07c79918.png)

![image](https://user-images.githubusercontent.com/4116539/181862825-1e3c1acc-b5b5-4773-950a-f6c065e6cad0.png)

**Duplicate File**

![image](https://user-images.githubusercontent.com/4116539/181861814-122b5905-ef1c-4769-b3e6-597aeb56bf4d.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4659)

**Comment by lmarceau** [comment]
Fixed by https://github.com/mozilla-mobile/firefox-ios/pull/11462
