### ISSUE TITLE
Update Baidu search code

### ISSUE THREAD

**Issue by l-hedgehog** [mozilla-mobile/firefox-ios#11465]
Hi, the Beijing office would like to update the Baidu search code in Firefox for iOS from `1000969b` to `1000969c`. I'll send a PR soon.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4661)

**Comment by data-sync-user** [comment]
➤ Nishant Patel commented:

Testing note from l-hedgehog ( https://github.com/l-hedgehog ); For testing, you should switch to zh-CN locale, perform a search with Baidu, and then look at the URL of the search engine result page.

**Comment by nishant2718** [comment]
v104 item, and pushed to QA.

**Comment by data-sync-user** [comment]
➤ Catalin Suciu commented:

Confirming that v104 build 14880 shows the updated (1000969c) search code for Baidu. Verifying as fixed.

**Comment by data-sync-user** [comment]
➤ Catalin Suciu commented:

Verified as fix on v103.1 also.
