### ISSUE TITLE
`Version/x.y.z` is missing in the FxiOS user agent string.

### ISSUE THREAD

**Issue by romainmenke** [mozilla-mobile/firefox-ios#11464]
Currently Firefox on iOS has a `FxiOS/x.y.z` part in the user agent string but it omits `Version/x.y.z`.
Brave by comparison does have `Version/x.y.z` which tells us that it can be included on a technical level.

The omission of `Version/x.y.z` makes it impossible to parse the user agent string from Firefox on iOS and determine what the underlying WebKit version is or what the browser capabilities are.

For polyfill.io we are now treating any FxiOS user agent as Safari 11 (the last version before the WebKit version was frozen).
This is obviously very bad and at the scale of polyfill.io this is impacting a lot of users and burning a lot of trees because response sizes are bigger and devices have to do more work to parse and execute polyfills for features they support natively.

`Sec-CH-UA` might also be used in the future but Firefox on iOS doesn't set this header.

Would it be possible to add `Version/x.y.z` as part of the user agent string in Firefox on iOS?

-------------

FxiOS : `Mozilla/5.0 (iPhone; CPU iPhone OS 15_5 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) FxiOS/102.2  Mobile/15E148 Safari/605.1.15`

Safari : `Mozilla/5.0 (iPhone; CPU iPhone OS 14_8_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.2 Mobile/15E148 Safari/604.1`

`Version/x.y.z` is missing in the FxiOS user agent string.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4660)

**Comment by cpeterso** [comment]
@romainmenke, thanks for reporting this problem. I see that Chrome iOS doesn't include the `Version/` token either (as mentioned in https://github.com/Financial-Times/polyfill-library/issues/1118).

I agree that, for maximum web compatibility, Firefox iOS's UA string should probably be a superset of Safari's, but I will check with Mozilla's Webcompat team. (I'm a module peer for Gecko's UA string.) We should probably send Safari's UA plus Firefox's `FxiOS/` token at the end (so it doesn't disrupt any UA parsers that make assumptions about the ordering of Safari's UA string tokens). Something like:

`Mozilla/5.0 (iPhone; CPU iPhone OS 15_5 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.5 Mobile/15E148 Safari/605.1.15 FxiOS/102.2`

For reference, these are the UA strings I see on my iPhone running iOS 15.5:

Safari:
`Mozilla/5.0 (iPhone; CPU iPhone OS 15_5 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.5 Mobile/15E148 Safari/604.1`

Firefox:
`Mozilla/5.0 (iPhone; CPU iPhone OS 15_5 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) FxiOS/102.2 Mobile/15E148 Safari/605.1.15`

Chrome:
`Mozilla/5.0 (iPhone; CPU iPhone OS 15_5 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/103.0.5060.63 Mobile/15E148 Safari/604.1`

Does WebKit's UA string omit the `Version/` token outside of Safari? Why do neither Firefox nor Chrome include the `Version/` token?

**Comment by romainmenke** [comment]
@cpeterso Thank you for the speedy response :)

One other thing I can not easily verify on my end is what happens when a user updates their iOS version and Safari is updated.

Does Firefox for iOS ship with its own version of WebKit as part of its binary or does it link with the OS version?

In other words can the WebKit version be updated separately from Firefox for iOS?

**Comment by cpeterso** [comment]
> One other thing I can not easily verify on my end is what happens when a user updates their iOS version and Safari is updated along with it.

Conveniently, I just updated my iPhone from iOS 15.5 to 15.6 after posting my comment above. I compared the UA strings before and after: in this update, the only difference was the `iPhone OS` version (`15_5` to `15_6`).

> Does Firefox for iOS ship with its own version of WebKit as part of its binary or does it link with the OS version?
> 
> In other words can the WebKit version be updated separately from Firefox for iOS?

Firefox for iOS doesn't bundle its own copy of WebKit, so an OS update can change the WebKit version used by apps. So the new WebKit version may have new features and bug fixes that have not been tested in Firefox by Mozilla QA (or in Chrome by Google QA, etc). We try to test iOS betas, but the final iOS release will still include bug fixes not in earlier betas.

**Comment by cpeterso** [comment]
Chrome iOS discussion about the `Version/` UA token: https://bugs.chromium.org/p/chromium/issues/detail?id=1348792

Brave iOS's UA string exactly matches Safari's, including the `Version/` token and no Brave-specific token.

**Comment by data-sync-user** [comment]
➤ Chris Peterson commented:

Note that this bug is bad for Firefox performance: sites that use the Financial Times' polyfill.io ( http://polyfill.io ) service mistakenly think Firefox is Safari 11 and they serve us unnecessary polyfill bundles. This increases site download size and executes slow polyfill functions instead of native WebAPIs supported that may be implemented in WebKit versions newer than Safari 11.

**Comment by denschub** [comment]
I'm slightly concerned about new potential edge-cases where sites correctly detect the browser as "Firefox", but then use the `Version/` snippet to determine the version. In this case, a site would see "Firefox 15.6" or something like that, and thus triggering a "deprecated browser" warning.

This class of issues was the primary motivation for aligning the FxiOS version numbers with their current desktop counterparts, and that change certainly relieved a lot of webcompat pain.

**Comment by romainmenke** [comment]
> potential edge-cases where sites correctly detect the browser as "Firefox", but then use the Version/ snippet to determine the version. In this case, a site would see "Firefox 15.6" or something like that, and thus triggering a "deprecated browser" warning.

> This class of issues was the primary motivation for aligning the FxiOS version numbers with their current desktop counterparts, and that change certainly relieved a lot of webcompat pain.

That is concerning :/

Could it be the same information but under a different key? `Not-Version/x.y.z`

**Comment by denschub** [comment]
> Is there any reference to these previous issues?

Issue #7309 was the original proposal, and that thread also includes a link to all Firefox iOS related UA-sniffing issues, which at this moment, are a total of 117 reports.

> This seems like a really bad pattern (of these sites) :/ It is also painful that this would stand in the way of a service like polyfill.io working properly.

Unfortunately, "bad patterns" are kind of what we in the Web Compatibility team have to deal with every day. And frequently there is no clean solution to a problem, and we only can pick between two different compromises with more or less expected breakage. Changes to the User Agent string of any nature are always messy, and regardless of what we do, something will break.

Please note that I'm not a product manager for iOS or anything - I just jumped into this thread to provide the perspective from the Web Compatibility team's point of view. Obviously, polyfill.io not working in Firefox for iOS would also be a significant WebCompat issue - and shipping unnecessary polyfills could result in performance issues. So this is another one of those situations where there are multiple outcomes, and all of them have downsides.

**Comment by romainmenke** [comment]
> Unfortunately, "bad patterns" are kind of what we in the Web Compatibility team have to deal with every day. And frequently there is no clean solution to a problem, and we only can pick between two different compromises with more or less expected breakage.

Indeed, when I am faced with similar choices I prefer not to change anything unless keeping the status quo is without any doubt much worse.

I do appreciate the hard work you all do for web compat ❤️ 

----

I tested the two examples (https://www.weremember.com/ and https://www.toutemonannee.com/) and was able to reproduce the initial issue by setting a low number (e.g. `FxiOS/10`).

Adding `Version/x.y.z FxiOS/a.b.c` didn't seem to trigger any adverse behaviour.
But these are just two samples, so that is basically meaningless :)

Is there any process to figure out how bad it would be to change this vs keeping everything as is?

I don't have access to polyfill.io stats but I could ask FT for a recent reqs/month.
It won't line up exactly with market share of Firefox on iOS but applying that share to the number of requests can give us an idea. (if that is useful)

**Comment by romainmenke** [comment]
This will have to be resolved by polyfill.io.
I've learned that everyone depends on the OS version for Safari on iOS.
This includes MDN compat data and Caniuse.

If polyfill.io is updated to use the OS version from user agent strings, the issue will be resolved without any browser needing to add `Version/x.y.z` to their user agent string.

Thank you for the feedback and insights on this issue 🙇

**Comment by cpeterso** [comment]
@romainmenke - Thanks for reporting this issue! I'm glad we found a resolution. The Firefox iOS team is still discussing whether we should change our UA string to omit the `FxiOS/` token and instead match Safari's UA string.

**Comment by romainmenke** [comment]
> whether we should change our UA string to omit the FxiOS/ token and instead match Safari's UA string.

That would be interesting and have obvious privacy benefits 🎉
