### ISSUE TITLE
Crash when switching from Firefox to a different app or the iOS home screen

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/firefox-ios#11485]
## Steps to reproduce

I don't have reliable STR for this crash, but I see it about once a day. The STR are the same as https://github.com/mozilla-mobile/firefox-ios/issues/10447 but the crash stack trace looks different.

1. Open some tabs in Firefox.
2. Swipe up to open iOS's app switcher.
3. Switch to a different app or the iOS home screen.

### Expected behavior

No crash.

### Actual behavior

Firefox will crash and show a dialog asking if I'd like to submit a crash report. When I reopen Firefox, it shows another dialog saying "This is embarrassing".

I have a client .ips crash log I can share, but I don't want to post it in a public GitHub issue.

Here's an excerpt:

"exception" : {"codes":"0x0000000000000000, 0x0000000000000000","rawCodes":[0,0],"type":"EXC_CRASH","signal":"SIGABRT"},
"ktriageinfo" : "VM - Fault hit memory shortage\n",
"asi" : {"libsystem_c.dylib":["abort() called"]},
"lastExceptionBacktrace" : [{"imageOffset":627336,"symbol":"__exceptionPreprocess","symbolLocation":220,"imageIndex":6},{"imageOffset":91972,"symbol":"objc_exception_throw","symbolLocation":60,"imageIndex":4},{"imageOffset":1254240,"symbol":"_userInfoForFileAndLine","symbolLocation":0,"imageIndex":11},{"imageOffset":2250612,"symbol":"-[UICollectionView _updateVisibleCellsNow:]","symbolLocation":5504,"imageIndex":8},{"imageOffset":2253952,"symbol":"-[UICollectionView _updateVisibleCellsNow:]","symbolLocation":8844,"imageIndex":8},{"imageOffset":1546884,"symbol":"-[UICollectionView layoutSubviews]","symbolLocation":320,"imageIndex":8},{"imageOffset":1621940,"symbol":"-[UIView(CALayerDelegate) layoutSublayersOfLayer:]","symbolLocation":2592,"imageIndex":8},{"imageOffset":265424,"symbol":"CA::Layer::layout_if_needed(CA::Transaction*)","symbolLocation":532,"imageIndex":19},{"imageOffset":209204,"symbol":"CA::Layer::layout_and_display_if_needed(CA::Transaction*)","symbolLocation":136,"imageIndex":19},{"imageOffset":293500,"symbol":"CA::Context::commit_transaction(CA::Transaction*, double, double*)","symbolLocation":452,"imageIndex":19},{"imageOffset":330096,"symbol":"CA::Transaction::commit()","symbolLocation":704,"imageIndex":19},{"imageOffset":206988,"symbol":"CA::Transaction::flush_as_runloop_observer(bool)","symbolLocation":88,"imageIndex":19},{"imageOffset":5497240,"symbol":"_UIApplicationFlushCATransaction","symbolLocation":72,"imageIndex":8},{"imageOffset":8227196,"symbol":"_UIUpdateSequenceRun","symbolLocation":84,"imageIndex":8},{"imageOffset":15068232,"symbol":"schedulerStepScheduledMainSection","symbolLocation":144,"imageIndex":8},{"imageOffset":15066128,"symbol":"runloopSourceCallback","symbolLocation":92,"imageIndex":8},{"imageOffset":766996,"symbol":"CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION","symbolLocation":28,"imageIndex":6},{"imageOffset":836000,"symbol":"__CFRunLoopDoSource0","symbolLocation":208,"imageIndex":6},{"imageOffset":22264,"symbol":"__CFRunLoopDoSources0","symbolLocation":368,"imageIndex":6},{"imageOffset":45148,"symbol":"__CFRunLoopRun","symbolLocation":828,"imageIndex":6},{"imageOffset":125896,"symbol":"CFRunLoopRunSpecific","symbolLocation":600,"imageIndex":6},{"imageOffset":4980,"symbol":"GSEventRunModal","symbolLocation":164,"imageIndex":7},{"imageOffset":5326408,"symbol":"-[UIApplication _run]","symbolLocation":1100,"imageIndex":8},{"imageOffset":2710928,"symbol":"UIApplicationMain","symbolLocation":364,"imageIndex":8},{"imageOffset":35864,"symbol":"main","symbolLocation":260,"imageIndex":9},{"imageOffset":105700,"symbol":"start","symbolLocation":520,"imageIndex":10}],

### Device & build information

* Device: iPhone 12 running iOS 15.5
* Build version: TestFlight Firefox 103.0 (13910)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4684)

**Comment by cpeterso** [comment]
See also #10467

**Comment by lmarceau** [comment]
I think this PR will fix this issue https://github.com/mozilla-mobile/firefox-ios/pull/11605

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

I was unable to reproduce this issue on main 0edd33a647a5efff980a9c4aa865d5c0d936a54e. Closing the issue a works for me. Let’s re-open if the issue still occurs.
