### ISSUE TITLE
[iPad] The magnifying icon is inactive on iPad

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#11502]
## Steps to reproduce
1. Open a new tab
2. Observe the "magnifying" icon near the navigation buttons
### Expected behavior
- The magnifying icon should be active
### Actual behavior
- The magnifying icon is inactive on iPad
### Device & build information
* Device: iPad pro (15.4)
* Build version: 104.0 and main da7a6a4d1ed3630f60e307a623f3d8956e6184c3
### Notes
Attachments: 

![image](https://user-images.githubusercontent.com/32130829/182617228-3e6c4cd3-9e66-4036-8b71-cc8e81c22c4d.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4695)

**Comment by dnarcese** [comment]
I see this issue in v101 as well. This search button should not even appear on iPad, so the fix should be removing it. Will need UX to determine new spacing.

**Comment by data-sync-user** [comment]
➤ Tiffanie Shakespeare commented:

Michael Verdi can you help out on this one?

**Comment by Verdi** [comment]
If we want to do something quickly, I suggest either making it active or removing it and letting the address bar take up the extra space. This is also an issue on iOS in landscape BTW. Otherwise I'd like to address this as part of the new UI and IA work.

**Comment by data-sync-user** [comment]
➤ Tiffanie Shakespeare commented:

let’s do the quick option and revisit if we need in the later work. which option do you suggest Michael Verdi making it active or removing it? 

when you make your final call, re-assign to daniela and she will pull it into a sprint to fix. thanks!

**Comment by data-sync-user** [comment]
➤ Michael Verdi commented:

Let’s remove it.

**Comment by data-sync-user** [comment]
➤ Winnie Teichmann commented:

Michael VerdiI don’t think we should be removing the search button. The button is changed to be the home button or reload depending on what is displayed (if we are on a website for example). I suggest we display the disabled reload icon instead as this will be probably displayed most of the time and be enabled once the user is a website.

**Comment by data-sync-user** [comment]
➤ Michael Verdi commented:

After talking this through with Winnie - the best approach here will be to make the search icon work as expected.
