### ISSUE TITLE
The "See all" buttons are not vertically aligned

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#11501]
## Steps to reproduce
1. Bookmark a page to make the Recently Saved section visible 
2. Visit a page to make the Jump back in section visible 
### Expected behavior
- The "See all" buttons should be vertically aligned
### Actual behavior
- The "See all" buttons are not vertically aligned
### Device & build information
* Device: iPhone and iPad
* Build version: main da7a6a4d1ed3630f60e307a623f3d8956e6184c3
### Notes
Attachments: 

![Picture_2022_08_03T12_48_56_324Z](https://user-images.githubusercontent.com/32130829/182611855-0c77f1c4-3f54-4333-9148-83cf6a8ebbef.jpeg)

![Picture_2022_08_03T12_49_04_465Z](https://user-images.githubusercontent.com/32130829/182611871-1e7a95d9-6e8e-48cf-8f68-94ea29e29c0c.jpeg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4694)

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verified fix on main 0edd33a647a5efff980a9c4aa865d5c0d936a54e
