### ISSUE TITLE
Swiping tabs left to close them in "Open Tabs" sometimes closes the wrong tab 

### ISSUE THREAD

**Issue by atamanroman** [mozilla-mobile/firefox-ios#11528]
## Steps to reproduce

- have open a lot of tabs (90 in my case with 80 inactive)
- use firefox for a while
- open "Open Tabs" view
- swipe a tab left to close it
- watch how the swipe-left animation is triggered for the wrong tab, which is then closed (usually same column and a few rows above)

### Expected behavior

Swiped tab is closed.

### Actual behavior

Wrong tab is closed.

### Device & build information
* Device: iPhone 12 Mini
* Build version: Firefox Daylight 103.0 (13910)

### Notes

Mentioned here before: https://github.com/mozilla-mobile/firefox-ios/issues/10024#issuecomment-1046522512

Does not happen after a fresh start.

I'll try to submit a screen recording when I see this again. I've seen this bug every week or so the last few months.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4714)

**Comment by dnarcese** [comment]
Is this the same bug #10165?
