### ISSUE TITLE
URL bar is not displayed after clean installing the app

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#11526]
## Steps to reproduce
1. Clean install v9000 (15185) and main fb24eab5caa18733ce01f893080ea7982ffdfe09
### Actual behavior
- URL bar is not displayed.
### Device & build information
* Device: iPhone 12 Pro (15.4)
* Build version: v9000 (15185) and main fb24eab5caa18733ce01f893080ea7982ffdfe09
### Notes
Attachments: 

![image](https://user-images.githubusercontent.com/32130829/183049132-ec8ee52b-21d4-413a-b751-9ea6e7abb6b2.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4713)

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verifying as fix on 104.0 (15278) and main ee2c4f19bc8a82a7fbe7ecf1309046ce2ae1b723.
