### ISSUE TITLE
The long name of iOS device overlaps with the arrow button in synced tabs

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#11547]
## Steps to reproduce
1. Sign in to sync on two iOS device
1. Go to "Synced tabs"
    1. Expected behavior

* No overlap should be displayed.
    1. Actual behavior
* The longer name of the iOS device overlaps with the arrow button
    1. Device & build information
* Device: iPhone 13 mini 15.4
* Build version: 104.0 (15278)
    1. Notes
Attachments: 

![Screenshot](https://user-images.githubusercontent.com/32130829/183644297-5a89da39-517f-4a6f-aeb0-74f7802dc0e3.jpeg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4726)

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verifying as fix on v9000 (18422)

**Comment by SimonBasca** [comment]
Verified fix on v106 (19763)

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verified fix on v106 (19763)
