### ISSUE TITLE
The option to close private tabs when leaving private browsing is not working

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/firefox-ios#11544]
We have an automated test that verifies this feature in Settings, the toggle to close private tabas when leaving private browsing. 
This test has started to fail. When the toggle is enabled, we have private tabs and leave the private browsing, those tabs are not closed.

This is the automated test: [testClosePrivateTabsOptionClosesPrivateTabs() ](https://github.com/mozilla-mobile/firefox-ios/blob/ee2c4f19bc8a82a7fbe7ecf1309046ce2ae1b723/Tests/XCUITests/PrivateBrowsingTest.swift#L83)
I have followed the steps manually on a simulator and the result is the same, the private tabs are not closed.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4724)

**Comment by lmarceau** [comment]
We have a unit tests that is also failing for the same reason `testPrivatePreference_togglePBMDeletesPrivate`. Due to https://github.com/mozilla-mobile/firefox-ios/issues/11536 we didn't catch it during PRs. I'll try to see what caused this issue.

**Comment by isabelrios** [comment]
That test was disabled in the UnitTest test plan that runs on Bitrise, my bad, it was failing on M1 consistently for other reason and we disabled it... then I never enabled it back when we change to run unit tests on Intel again :(

**Comment by lmarceau** [comment]
This broken change relates to PR https://github.com/mozilla-mobile/firefox-ios/pull/11451

**Comment by lmarceau** [comment]
> That test was disabled in the UnitTest test plan that runs on Bitrise, my bad, it was failing on M1 consistently for other reason and we disabled it... then I never enabled it back when we change to run unit tests on Intel again :(

Ohh ok! It ran for me locally so I got confused. But still 100% broken at the moment that's for sure.

**Comment by lmarceau** [comment]
@isabelrios So it turns out this is a wanted behavior change. We let the user peak at the tabs in the tabs tray and don't delete private tabs unless a normal tab is **selected**. Since it's wanted we'll need to adjust the tests accordingly.

**Comment by isabelrios** [comment]
Oh I see, I was not aware of that change... I'm closing this issue an opening a different one to re-write that test. Thank you for looking into this and clarify.
