### ISSUE TITLE
SVG Clip Path on Canvas breaks on Firefox on iPhone

### ISSUE THREAD

**Issue by josteint** [mozilla-mobile/firefox-ios#11542]
See [url](https://stackoverflow.com/questions/73275057/svg-clip-path-on-canvas-breaks-on-phone)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4723)

**Comment by lmarceau** [comment]
@josteint Hi thanks for opening this issue. Looking a this it seems to be more of a Webkit issue thought?

**Comment by josteint** [comment]
@lmarceau Yes I think you are right. I sent the same report to Apple.
