### ISSUE TITLE
Toggle for wallpaper change is partially out of the screen

### ISSUE THREAD

**Issue by pashynskykh** [mozilla-mobile/firefox-ios#11546]
## Steps to reproduce
"Change startpage" -> "Wallpaper".

### Expected behavior
The toggle is fully visible with the padding on the right side.

### Actual behavior
The toggle is cropped by the screen. 

### Device & build information
* Device: iPhone 11.
* Build version: 103.0 (13910)

### Notes
Attachments: 
![IMG_8960](https://user-images.githubusercontent.com/14852335/183645002-e7ceb26e-9f34-4353-a8d1-879d61171f2d.PNG)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4725)

**Comment by dnarcese** [comment]
This toggle is going to be removed shortly

**Comment by pashynskykh** [comment]
Thanks for the update, Daniela!
