### ISSUE TITLE
App crashes after opening tabs tray and tapping "Done"

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#11553]
## Steps to reproduce
1. Clean install v104.0 
2. Launch the app
3. Visit amazon.com
4. Tap "back" arrow
5. Open tabs tray
6. Tap "Done"
7. Repeat steps 5) and 6) a few times
### Expected behavior
- App crashes
### Device & build information
* Device: iPhone 13 mini
* Build version: 104.0 (15278)
### Notes
Attachments: 

https://user-images.githubusercontent.com/32130829/183661871-62e680be-a597-4a06-8b6c-36b0255b9c56.mp4

## Crashlog

[Client-2022-08-09-163935.ips.zip](https://github.com/mozilla-mobile/firefox-ios/files/9291223/Client-2022-08-09-163935.ips.zip)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4732)

**Comment by lmarceau** [comment]
This relates to homepage collection view crashes

**Comment by lmarceau** [comment]
This should be fixed with https://github.com/mozilla-mobile/firefox-ios/pull/11605

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verified fix on main 0edd33a647a5efff980a9c4aa865d5c0d936a54e
