### ISSUE TITLE
The tab selector is not longer displayed after closing a tab from the inactive list

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#11551]
## Steps to reproduce
1. Have the inactive list populated
1. Open 2 new tabs
1. Tap on the inactive list
1. Tap on an inactive tab to open it
1. Open tabs tray
1. Close the tab that was previously opened from the inactive list
    1. Expected behavior

* The tab selector should move to the next tab
    1. Actual behavior
* The tab selector is not longer displayed.
    1. Device & build information
* Device: iPhone 13 mini (15.4)
* Build version: 104.0 (15278)
    1. Notes
Attachments: 

https://user-images.githubusercontent.com/32130829/183655275-04a6b2fc-81be-4e0b-b754-2157b233a8c6.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4729)

**Comment by dnarcese** [comment]
If you close the tab tray after the steps then re-open it, is the correct tab selected?

**Comment by SimonBasca** [comment]
After closing and re-opening tabs tray the tab selector moves to a tab from the inactive list and the tab is removed from the inactive list.

**Comment by data-sync-user** [comment]
➤ Catalin Suciu commented:

Verifying as fixed on v9000 (22848)
