### ISSUE TITLE
Long pressing on a link occasionally shows a page preview without a context menu

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/firefox-ios#11565]
## Steps to reproduce
1. Load a page and long press on a link on the  page. 

### Expected behavior
A preview of the linked page should open with a context menu below the preview.

Screenshot:

![032B450B-C8EB-456B-A570-A984758B27AB](https://user-images.githubusercontent.com/629193/183803272-9e0547d0-13db-4e86-a3f1-bb12c2c3022a.png)

### Actual behavior
Occasionally, the preview will open but there will be no context menu. This only happens about 5% of the time and seems to happen most often when first launching the app or after waking up my phone. Seems like a race condition. 

Screenshot:

![7E0BF2E7-BA39-4616-A320-BFAB740738E2](https://user-images.githubusercontent.com/629193/183802967-7cc33ff3-a471-40dc-84ec-2be1a23140ae.png)

### Device & build information
* Device: iPhone 12
* Build version: Firefox Beta v104.0 (14880), but I’ve seen this bug for a long time (maybe a year or longer?) and only finally got around to filling this bug report.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4741)

**Comment by cpeterso** [comment]
https://github.com/mozilla-mobile/firefox-ios/issues/10026 looks like a similar problem, but I’m not using a trackpad, keyboard, or iPad.

**Comment by cpeterso** [comment]
I found a page and link that send to reproduce this bug reliably:

1. Open https://blog.pragmaticengineer.com/become-and-effective-software-engineering-manager-my-book-review/
2. Search for the text “I feel pretty strongly about this”.
3. Long press on the “I [feel pretty strongly about this](https://blog.pragmaticengineer.com/performance-reviews-for-software-engineers/#how-i-do-performance-reviews#delivering-the-review)”.

Even long pressing that link on this GitHub issue page, so the issue seems to be related to the page being previewed and not the page with the link?

![DE8DD58C-B611-4F1A-9681-2B1A7DE556EB](https://user-images.githubusercontent.com/629193/183834872-361bda23-ef83-4050-98d7-29818a4f49ef.png)

**Comment by morachimo** [comment]
Similar to #8892.

**Comment by cpeterso** [comment]
This issue is not stale. Two years after filing this bug, I still experience this bug nearly everyday.

**Comment by data-sync-user** [comment]
➤ Alexandru Farcasanu commented:

Hey, Chris Peterson . I am still trying and trying to reproduce the issue but is like impossible for me.
Do you think you have any more inputs here that may help? Or some hints… maybe some behaviours that can cause the issue.

Thank you!

**Comment by cpeterso** [comment]
Sorry, I don't have reliable STR. The STR in my 2022 comments were reliable for me at that time, but not today.

When the problem does happen, the problem doesn't go away until I reload the page. So the problem is associated with the current page, not with each attempt to open the long press menu. I don't recall if, when the problem does happen, if the problem happens for every link on the page or just one link.

Since the problem is intermittent, it is probably a race condition. It feels as if there is some state associated with the current page that prevents the long press menu from showing, but doesn't prevent the page previews. As such, maybe there is some long press menu state associated with the current page that is not initialized? Or something about loading the background page to capture the preview intermittently breaks some state of the current page?

**Comment by data-sync-user** [comment]
➤ Alexandru Farcasanu commented:

Thank you, Chris Peterson . I will continue to take a look.

**Comment by cpeterso** [comment]
> Are you using the AppStore version, right?

No, I'm using Nightly TestFlight version 9000 (43147). I haven't seen this bug in a few days, but I'm pretty certain I've seen it in a 9000 build more recently than 2 weeks ago.

If I do see this bug again, I'll comment here (and check whether the bug happens for every link on the page or just one link).

**Comment by data-sync-user** [comment]
➤ Alexandru Farcasanu commented:

Chris Peterson going to close this but feel free to leave a comment here and re-open it if the problem appear again. Thank you!

**Comment by cpeterso** [comment]
OK. I used to see this problem every day, but I think I've only seen it a couple times in the four weeks. So I don't know if the underlying bug has been fixed, but it's no longer a big problem

**Comment by MaeBee** [comment]
Still encountering this issue on 136.3.

The bug seems to appear at random (the next tab was fine again) and it seems be affecting every link in the bugged tab.
Following a link in the tab and attempting the same there yields the same result, so it must be related to the tab, independent of the page loaded. To confirm, I manually navigated to wiki and tried again, still persists.
Not even refreshing the affected tab has helped and turning the link preview off and on again in Settings only removes and returns the preview image, but doesn't return the expected options.
The entry point was a google search from the address bar.

My original search results page:
![Image](https://github.com/user-attachments/assets/d74ce44a-7242-434c-98c4-03e21a7ae8c4)

Links on the original page:
![Image](https://github.com/user-attachments/assets/0a5744e3-66b6-4986-860b-7fd2ba240500)
![Image](https://github.com/user-attachments/assets/db28d21c-9584-4df7-8355-953c861729da)

Link on a clicked-through-to page:
![Image](https://github.com/user-attachments/assets/525610f6-a003-4c91-8021-a9798f79e2f7)

Link on a manually navigated-to page:
![Image](https://github.com/user-attachments/assets/33800841-1e54-47b0-9982-a19cb47eec51)

**Comment by fowl2** [comment]
Experiencing something similar in Firefox 140.0 (56826), iPhone 16 Plus. 

Even though I have settings->browsing->show link previews "off" they sometimes appear. It seems like it's if I long press "too early" when loading a tab. Almost always the second attempt will show the context menu as normal, without the preview.
