### ISSUE TITLE
Firefox crash when restoring from background

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#11568]
## Steps to reproduce
1. Log in to FxA and have one synced tab on desktop
2. Launch Firefox iOS
3. Background Firefox iOS
4. Foreground Firefox iOS
### Expected behavior
- No crash should occur
### Actual behavior
- Firefox crash.
### Device & build information
* Device: iPhone 13 mini (15.4)
* Build version: main e2e3d4216a3b55ad336a9af99729c4354764c54e
### Notes
Attachments: 

https://user-images.githubusercontent.com/32130829/183940650-1c0494ef-8d52-4b84-bc7e-0c1aa701ceaf.mp4

## Crash log
[Client-2022-08-10-180647.ips.zip](https://github.com/mozilla-mobile/firefox-ios/files/9301330/Client-2022-08-10-180647.ips.zip)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4745)

**Comment by SimonBasca** [comment]
@lmarceau do you mind taking a look at the crash log and let me know if this is a new issue related to synced tabs or it's one of the other crashes we have logged. Thanks!

**Comment by SimonBasca** [comment]
Note:
- I suspect this might be related to the "Recently saved" section. After disabling "recently saved" the crash was not reproduced.

**Comment by lmarceau** [comment]
@SimonBasca This seems to relate to the same homepage crashes we've been having, although we can only confirm once other crashes are fixed so I would keep this open for now

**Comment by lmarceau** [comment]
This should be fixed with https://github.com/mozilla-mobile/firefox-ios/pull/11605

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Marking as verified fix on main 0edd33a647a5efff980a9c4aa865d5c0d936a54e
Note: We’ve found one issue while testing https://github.com/mozilla-mobile/firefox-ios/issues/11620 ( https://github.com/mozilla-mobile/firefox-ios/issues/11620|smart-link )
