### ISSUE TITLE
Docs: wrong link 

### ISSUE THREAD

**Issue by mozead1996** [mozilla-mobile/firefox-ios#11577]
the link of the new docs "docs/metrics.md" in [telemetry.md](https://github.com/mozilla-mobile/firefox-ios/blob/main/Docs/telemetry.md) doesn't exist   page not found 

<img width="916" alt="Screen Shot 2022-08-10 at 10 50 05 PM" src="https://user-images.githubusercontent.com/26047721/184017996-4f5a9b15-9e4a-4a8d-b063-ed1dcb9ab098.png">

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4749)

**Comment by lmarceau** [comment]
Fixed https://github.com/mozilla-mobile/firefox-ios/blob/main/Docs/telemetry.md
