### ISSUE TITLE
Section stretches past screen

### ISSUE THREAD

**Issue by josamontiel** [mozilla-mobile/firefox-ios#11578]
As per the photo below, the toggle button stretches beyond the edge of the screen.

When rotating to landscape it corrects, but when it reverts back to portrait it has the same issue. 

![IMAGE 2022-08-10 23:15:33](https://user-images.githubusercontent.com/91287801/184029917-b3f39278-8d49-477a-b18a-cf7a4af56b4f.jpg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4750)

**Comment by lmarceau** [comment]
Hi @josamontiel, thanks for opening this issue. It seems we already have an issue tracking this problem with https://github.com/mozilla-mobile/firefox-ios/issues/11546 so I'll close this one here.
