### ISSUE TITLE
China version homepage is broken

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#11584]
## Steps to reproduce
1. Switch to china version from debug menu
2. Observe the home is not loading
### Expected behavior
- Firefox homepage for China version should load.
### Actual behavior
- The homepage is broken
### Device & build information
* Device: iPhone 13 mini (15.4)
* Build version: 3176e232a4ab8a378a10e73d05440a7fdf0bd6ef
### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4755)

**Comment by SimonBasca** [comment]
https://user-images.githubusercontent.com/32130829/184126414-faa52173-12a2-423c-a7a0-346393b9e25d.mp4

**Comment by SimonBasca** [comment]
@lmarceau I opened the debug menu, tap on "Switch to china version" restart the app and observe the homepage. I think there is something wrong with the page at "https://mobile.firefoxchina.cn/?ios". I tried visiting the page by typing the link in the URL bar but the page won't load. Not sure what is wrong.

**Comment by lmarceau** [comment]
Mhh I tried again and the page "https://mobile.firefoxchina.cn/?ios" loads for me. Here's what I did:

https://user-images.githubusercontent.com/11338480/184376417-d45dc128-cedf-4abc-b6a2-75e970381427.MP4

To get the china top sites for #11265 I had to change my language to chinese on my phone, and change back from "https://mobile.firefoxchina.cn/?ios" to show the Firefox homepage in the settings.
