### ISSUE TITLE
Crash: org.mozilla.ios.Fennec crashed in closure #1 in HomepageViewController.reloadView 

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/firefox-ios#11583]
We are seeing this crash when running the automated tests. It is not reproducible in the tests whe have seen it, and in each execution, there are different tests affected.

Looking at the bitrise failures, my feeling is that the app crashes when it is being launched, the test needs to wait until the homescreen is completely loaded and the app in idle to start clicking on the url bar or the url bar cancel button. It is when trying to perform that click that the app crashes.

I have not been able to have crash log, but I got that from a test that failed on Bitrise:
<img width="524" alt="Screenshot 2022-08-09 at 11 21 24" src="https://user-images.githubusercontent.com/1897507/184123774-b4b08f78-7809-4620-9728-aa7fccc7f273.png">

Hope that helps, we are trying to gather more information about this.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4754)

**Comment by lmarceau** [comment]
Should be fixed with https://github.com/mozilla-mobile/firefox-ios/pull/11605

**Comment by SimonBasca** [comment]
@isabelrios let us know if we have a green build so we can close this as resolved. Thanks

**Comment by isabelrios** [comment]
looks like the issue is fixed, I have checked a few red builds but they are not failing due to this issue. The test builds and workflows are all green lately. 
We can close the issue for now. Thanks!
