### ISSUE TITLE
Reload icon is displayed on home page tab

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#11590]
## Steps to reproduce
1. Visit a page (e.g google.com)
2. Open a new tab
3. Open tab tray
4. Tap on the google tab
5. Open tab tray
6. Tap on the empty new tab
### Expected behavior
- Reload icon should not be displayed on home page tab
### Actual behavior
- Reload icon is displayed on home page tab
### Device & build information
* Device: iPhone 13 mini (15.4)
* Build version: ab7d82776b14b0a7898c791ac5f5841cf0309a7a
### Notes
Attachments: 

https://user-images.githubusercontent.com/32130829/184336438-1194f4c2-9cb8-4ecd-a92c-369711a80506.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4759)

**Comment by lmarceau** [comment]
That relates to https://github.com/mozilla-mobile/firefox-ios/issues/11298

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verifying as fix on main 0edd33a647a5efff980a9c4aa865d5c0d936a54e
