### ISSUE TITLE
iOS App Store Connect issues sent via email

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/firefox-ios#11596]
You may be already aware of these issues but I'm opening this issue to have a common place to discuss and understand their status.
@dsmithpadilla and her team are receiving emails with iOS errors for every build submission to App Store Connect.

Are those issues known and being tracked? If not, should we open them? 

This is also happening for focus-iOS.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4761)

**Comment by lmarceau** [comment]
Current status for this issue.
Most of the warnings relate to some localization problem with QuickLinkSelection. Example (but we get a warning for every locale): 
```
ITMS-90626: Invalid Siri Support - Localized title for custom intent: 'QuickLinkSelection' not found for locale: es
```

Other issues that relates to Credential Provider target with:
``` 
ITMS-90473: CFBundleVersion Mismatch - The CFBundleVersion value '1' of extension 'Client.app/PlugIns/CredentialProvider.appex' does not match the CFBundleVersion value '16188' of its containing iOS application 'Client.app'.

ITMS-90473: CFBundleShortVersionString Mismatch - The CFBundleShortVersionString value '104.0' of extension 'Client.app/PlugIns/CredentialProvider.appex' does not match the CFBundleShortVersionString value '9000' of its containing iOS application 'Client.app'. 
```

**Comment by lmarceau** [comment]
Merged a PR that should fix most warnings 🤞Let's monitor and improve if there's still some.

**Comment by lmarceau** [comment]
Update: Credential provider warnings are fixed, but Localization warnings are still present.

**Comment by lmarceau** [comment]
Update: Warnings are now only about custom intent: 'QuickAction'. Seems we should localize for some other locales.

**Comment by isabelrios** [comment]
Thanks @lmarceau for looking into this! 
@dsmithpadilla I hope this fixes most of the issues you were seeing..
