### ISSUE TITLE
Can't open e-mails at outlook.office.com

### ISSUE THREAD

**Issue by romraptor** [mozilla-mobile/firefox-ios#11591]
## Steps to reproduce
Login to outlook.office.com

### Expected behavior
My e-mails should open when I tap them

### Actual behavior
Nothing happens

### Device & build information
* Device: iPhone 13 Pro with iOS 15.6
* Build version: Firefox 103
### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4760)

**Comment by dnarcese** [comment]
@SimonBasca can you reproduce this?
