### ISSUE TITLE
Data Review Request for Awesomebar performance metrics

### ISSUE THREAD

**Issue by tarikeshaq** [mozilla-mobile/firefox-ios#11602]
# Request for data collection review form

**All questions are mandatory. You must receive review from a data steward peer on your responses to these questions before shipping new data collection.**

1) What questions will you answer with this data?
> - How long does the awesomebar take to query history and bookmarks on average 
> - Did a release regress the performance of the awesomebar
> - Is the performance of the awesomebar adequate for users
> - What does the distribution of awesomebar query time look like for our users

2) Why does Mozilla need to answer these questions?  Are there benefits for users? Do we need this information to address product or business requirements? Some example responses:

> * Establish a baseline for the performance of the awesomebar
> * Allows us to catch performance regressions early
> * Allows us to ensure that the performance is adequate for our users
  (based on [fenix performance](https://sql.telemetry.mozilla.org/dashboard/fenix-awesomebar-performance) we should be looking at 300ms as the number where users experience starts to degrade)

3) What alternative methods did you consider to answer these questions? Why were they not sufficient?
> Locally profiling the performance of the awesomebar
 >  - Not sufficient because it can't account for the variability in users devices in the wild

4) Can current instrumentation answer these questions?
> No. We currently do not have awesomebar performance metrics for iOS.

5) List all proposed measurements and indicate the category of data collection for each measurement, using the [Firefox data collection categories](https://wiki.mozilla.org/Data_Collection) found on the Mozilla wiki.   

For the implementation, look at the [pull request](https://github.com/mozilla-mobile/firefox-ios/pull/11601/files)

<table>
  <tr>
    <td>Measurement Description</td>
    <td>Data Collection Category</td>
    <td>Tracking Bug #</td>
  </tr>
  <tr>
    <td> The query time of the awesomebar, specifically, a time distribution of how long each query of the database takes for **both ** history and bookmarks</td>
    <td>Techincal Data</td>
    <td>https://mozilla-hub.atlassian.net/browse/SYNC-3261</td>
  </tr>
</table>

6) Please provide a link to the documentation for this data collection which describes the ultimate data set in a public, complete, and accurate way.
> **This collection is documented in the Glean Dictionary at https://dictionary.telemetry.mozilla.org/**

7) How long will this data be collected?  Choose one of the following:

> * I want to permanently monitor this data. Tarik Eshaq (@tarikeshaq: teshaq@mozilla.com)

8) What populations will you measure?

> **All channels in all countries in all locales, for firefox-ios users**

9) If this data collection is default on, what is the opt-out mechanism for users?

> **Standard Firefox-ios telemetry controls**, users can opt-out in the settings menu.

10) Please provide a general description of how you will analyze this data.

> **Observe the timing distribution of the query times of the awesomebar, we will also define averages. It will also help us analyze any changes to the awesomebar to verify we do not introduce any regressions over time. It will be looked at as a part of the Sync Team's triage rotation**

11) Where do you intend to share the results of your analysis?

> **The Sync and Firefox iOS teams**

12) Is there a third-party tool (i.e. not Glean or Telemetry) that you are proposing to use for this data collection? If so:

> No.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4764)

**Comment by travis79** [comment]
> # Request for data collection review form
> 
> **All questions are mandatory. You must receive review from a data steward peer on your responses to these questions before shipping new data collection.**
> 
>     1. What questions will you answer with this data?
> 
> 
> > * How long does the awesomebar take to query history and bookmarks on average
> > * Did a release regress the performance of the awesomebar
> > * Is the performance of the awesomebar adequate for users
> > * What does the distribution of awesomebar query time look like for our users
> 
>     2. Why does Mozilla need to answer these questions?  Are there benefits for users? Do we need this information to address product or business requirements? Some example responses:
> 
> 
> > * Establish a baseline for the performance of the awesomebar
> > * Allows us to catch performance regressions early
> > * Allows us to ensure that the performance is adequate for our users
> >   (based on [fenix performance](https://sql.telemetry.mozilla.org/dashboard/fenix-awesomebar-performance) we should be looking at 300ms as the number where users experience starts to degrade)
> 
>     3. What alternative methods did you consider to answer these questions? Why were they not sufficient?
> 
> 
> > Locally profiling the performance of the awesomebar
> > 
> > * Not sufficient because it can't account for the variability in users devices in the wild
> 
>     4. Can current instrumentation answer these questions?
> 
> 
> > No. We currently do not have awesomebar performance metrics for iOS.
> 
>     5. List all proposed measurements and indicate the category of data collection for each measurement, using the [Firefox data collection categories](https://wiki.mozilla.org/Data_Collection) found on the Mozilla wiki.
> 
> 
> For the implementation, look at the [pull request](https://github.com/mozilla-mobile/firefox-ios/pull/11601/files)
> Measurement Description 	Data Collection Category 	Tracking Bug #
> The query time of the awesomebar, specifically, a time distribution of how long each query of the database takes for **both ** history and bookmarks 	Techincal Data 	https://mozilla-hub.atlassian.net/browse/SYNC-3261
> 
>     6. Please provide a link to the documentation for this data collection which describes the ultimate data set in a public, complete, and accurate way.
> 
> 
> > **This collection is documented in the Glean Dictionary at [dictionary.telemetry.mozilla.org](https://dictionary.telemetry.mozilla.org/)**
> 
>     7. How long will this data be collected?  Choose one of the following:
> 
> 
> > * I want to permanently monitor this data. Tarik Eshaq (@tarikeshaq: [teshaq@mozilla.com](mailto:teshaq@mozilla.com))
> 
>     8. What populations will you measure?
> 
> 
> > **All channels in all countries in all locales, for firefox-ios users**
> 
>     9. If this data collection is default on, what is the opt-out mechanism for users?
> 
> 
> > **Standard Firefox-ios telemetry controls**, users can opt-out in the settings menu.
> 
>     10. Please provide a general description of how you will analyze this data.
> 
> 
> > **Observe the timing distribution of the query times of the awesomebar, we will also define averages. It will also help us analyze any changes to the awesomebar to verify we do not introduce any regressions over time. It will be looked at as a part of the Sync Team's triage rotation**
> 
>     11. Where do you intend to share the results of your analysis?
> 
> 
> > **The Sync and Firefox iOS teams**
> 
>     12. Is there a third-party tool (i.e. not Glean or Telemetry) that you are proposing to use for this data collection? If so:
> 
> 
> > No.
> 
> ┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4764)

# Data Review

1) Is there or will there be **documentation** that describes the schema for the ultimate data set in a public, complete, and accurate way?

Yes, through the metrics.yaml file and the [Glean Dictionary](https://dictionary.telemetry.mozilla.org/).

2) Is there a control mechanism that allows the user to turn the data collection on and off?

Yes, through the "Send Usage Data" preference in the application settings.

3) If the request is for permanent data collection, is there someone who will monitor the data over time?

Tarik Eshaq [teshaq@mozilla.com] to monitor the permanent collection of this data

4) Using the **[category system of data types](https://wiki.mozilla.org/Data_Collection)** on the Mozilla wiki, what collection type of data do the requested measurements fall under?

Category 1: Technical data

5) Is the data collection request for default-on or default-off?

Default-on

6) Does the instrumentation include the addition of **any *new* identifiers** (whether anonymous or otherwise; e.g., username, random IDs, etc.  See the appendix for more details)?

No

7) Is the data collection covered by the existing Firefox privacy notice?

Yes

8) Does the data collection use a third-party collection tool?

No

## Result

data-review+
