### ISSUE TITLE
CFR message is displayed on webpage after unlocking the device

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#11606]
## Steps to reproduce
1. Visit a page (e.g "amazon.com")
2. Lock the device
3. Unlock the device
### Expected behavior
- CFR message for the Jump back in section should be display on homepage
### Actual behavior
- CFR message is displayed on amazon.com after unlocking the device
### Device & build information
* Device: ?
* Build version: ?
### Notes
Attachments: 

https://user-images.githubusercontent.com/32130829/184873320-311278eb-5764-4bfd-bf19-c9161cba4117.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4767)

**Comment by dnarcese** [comment]
@SimonBasca was the site visited from the homepage? were the steps done quickly?

**Comment by lmarceau** [comment]
This is easily reproducible also with STR:
- Fresh install
- Open a webpage
- Open a homepage
- Jump back in section is there, but you click on a top sites for example to leave rapidly the homepage
- Jump back in CFR appears on top of a website

Looks like after the timer is done in `ContextualHintViewController`, we don't check if the homepage is still actually showing. Aka, we should just stop the timer if homepage isn't on top anymore. Easy fix for that would be through `recordHomepageDisappeared`, to just stop the timer.

This could have been a side effect of the homepage that isn't nullified as often as before. We keep a reference to it in BVC, so I just opened a PR to fix it.

**Comment by SimonBasca** [comment]
@dnarcese the steps were done in a normally manner and the site was visited from the homepage from a clean install. Also if a site is visited and the CFR message is reset from the debug menu, it will be displayed on the site.

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verified fix on main 927d11f0880bbe54389f0594969a6b8f261fa8f3
