### ISSUE TITLE
Firefox for iPadOS crashes whenever I add a custom search engine

### ISSUE THREAD

**Issue by mach21** [mozilla-mobile/firefox-ios#11600]
## Steps to reproduce
Add a custom search engine from Settings - Search -Add
Tap Save.
### Expected behavior
The search engine should be added and I should be able to search from the address bar. 
### Actual behavior
Firefox crashes and the search engine isnt saved
### Device & build information
* Device: iPad Pro (2021)
* Build version: Firefox Daylight 103.1 (15076)
### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4763)

**Comment by lmarceau** [comment]
Hi @mach21, we had an issue opened for this here https://github.com/mozilla-mobile/firefox-ios/issues/11187. This will be fixed in v105. Thank you!
