### ISSUE TITLE
App crashes on “add search engine” save

### ISSUE THREAD

**Issue by WeLoTech** [mozilla-mobile/firefox-ios#11619]
iOs: 15.6 
Firefox iOs: 103.1

settings - search - add search engine: 
Adding: 
Startpage
https://www.startpage.com/sp/search?query=%s

When I click save, it loads for a short time and then the app crashes.

tried to delete and install fresh - same problem.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4776)

**Comment by lmarceau** [comment]
Hi @WeLoTech, we had an issue opened for this here https://github.com/mozilla-mobile/firefox-ios/issues/11187. This will be fixed in v105. Thank you!
