### ISSUE TITLE
Firefox 103.1 (15076) on iOS crashes when adding a new search engine

### ISSUE THREAD

**Issue by Bok001** [mozilla-mobile/firefox-ios#11615]
## Steps to reproduce
Settings - search - add search engine - name: Startpage - URL: https://www.startpage.com/do/dsearch?q=%s - save
### Expected behavior
Added a new search engine, in this case Startpage.com
### Actual behavior
Firefox crashes, it shuts down. When restarted manually the search engine is nowhere to be found. 
### Device & build information
* Device: iPhone X
* Build version: 16.2 beta
### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4775)

**Comment by lmarceau** [comment]
Hi @Bok001, we had an issue opened for this here https://github.com/mozilla-mobile/firefox-ios/issues/11187. This will be fixed in v105. Thank you!

**Comment by Bok001** [comment]
Hi, I must have overlooked the issue. Thanx for the fast response!
