### ISSUE TITLE
Jump back in section layout breaks after restoring from background

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#11620]
## Preconditions
- Log in to FxA to have a synced tab from desktop on homepage 
OR 
- Have one open tab in "Jump back in" section
## Steps to reproduce
1. Open a new tab on homepage
2. Background the app
3. Foreground the app
### Actual behavior
- Jump back in section layout breaks
### Device & build information
* Device: iPhone 13 mini (15.4) 
* Build version: 0edd33a647a5efff980a9c4aa865d5c0d936a54e
### Notes
Attachments: 

https://user-images.githubusercontent.com/32130829/185135960-2ea3375d-a1e7-4e62-81bf-4e80c246046a.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4778)

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verified fix on main 3012efa1c26a05b238f348d5f2354e02e322bd59
