### ISSUE TITLE
Recently visited, Recently viewed, Jump back are not displayed on cold start

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#11622]
## Steps to reproduce
1. Cold start fennec 927d11f0880bbe54389f0594969a6b8f261fa8f3
### Expected behavior
- Recently visited, Recently viewed, Jump back in should be displayed.
### Actual behavior
- Recently visited, Recently viewed, Jump back are not displayed.
### Device & build information
* Device: iPhone / iPad
* Build version: 927d11f0880bbe54389f0594969a6b8f261fa8f3
### Notes
- The "recently visited" section is displayed only after visiting a webpage
- The "Jump back in" and "Recently Viewed" are displayed after opening a new tab.
Attachments: 

https://user-images.githubusercontent.com/32130829/185158811-bcdb607c-7040-4c9c-8643-952caccbd2e5.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4779)

**Comment by lmarceau** [comment]
Could only easily reproduce on real device. Found a fix for recently visited and history highlights, but in your example with jump back in this relates to issue https://github.com/mozilla-mobile/firefox-ios/issues/11582 with the sync tab. I couldn't see that particular issue if the jump back in contained only normal tabs.

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verified fix on main 3012efa1c26a05b238f348d5f2354e02e322bd59
