### ISSUE TITLE
The spacing between the "Recently Visited" columns is too large

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#11623]
## Steps to reproduce
1. Have some history in "Recently Visited" 
2. Change device orientation to landscape
3. Scroll to the "Recently Visited"
### Expected behavior
- See [design](https://www.figma.com/file/am9EJGg6ow29PXWkc9jcOH/MR2-(2021)?node-id=2703%3A48112) for proper spacing - 
### Actual behavior
- The spacing between the columns is too large
### Device & build information
* Device: iPhone 13 mini (15.4)
* Build version: 927d11f0880bbe54389f0594969a6b8f261fa8f3
### Notes
Attachments: 

![Screenshot](https://user-images.githubusercontent.com/32130829/185169467-4326d348-4929-42a8-8cb0-8276681fb85f.jpeg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4780)

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Marking as verified fix on v9000 (19690)
