### ISSUE TITLE
App crashes when startpage is added as a search engine

### ISSUE THREAD

**Issue by josamontiel** [mozilla-mobile/firefox-ios#11624]
Hello,

I am trying to add startpage as a search engine to my firefox app, when I add it the app crashes. It accepts startpage when using firefox focus though.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4781)

**Comment by csuciu** [comment]
Hi @josamontiel, this issue is tracked here #11187 and will be fixed in the next release.

**Comment by SimonBasca** [comment]
@josamontiel this issue has been resolved in https://github.com/mozilla-mobile/firefox-ios/issues/11187 and will be fixed in v105.0
