### ISSUE TITLE
Review unused strings exposed to localization

### ISSUE THREAD

**Issue by flodolo** [mozilla-mobile/firefox-ios#11639]
Pretty rough approach (searching for the ID in the repo), but I believe we have about 50 unused strings exposed for localization

This is the script generating it
https://gist.github.com/flodolo/7fa8c6b490eba78bc53e9a16257b4588

To fix this, I believe we need to remove these references from both en.lproj and en-US.lproj

Can someone take a look?

CC @roux @bcolsson

Potentially unused IDs (47):
  - Open Last Tab
  - After 1 hour
  - After 1 minute
  - After 5 minutes
  - After 10 minutes
  - After 15 minutes
  - Change Passcode
  - Enter Passcode
  - Enter a new passcode
  - Enter a passcode
  - Face ID & Passcode
  - Incorrect passcode. Try again (Attempts remaining: %d).
  - Incorrect passcode. Try again.
  - Maximum attempts reached. Please try again in an hour.
  - Maximum attempts reached. Please try again later.
  - New passcode must be different than existing code.
  - Passcode For Logins
  - Passcodes didn’t match. Try again.
  - Re-enter passcode
  - Require Passcode
  - Set Passcode
  - Touch ID & Passcode
  - Turn Passcode Off
  - Turn Passcode On
  - touchid.disable.reason.label
  - touchid.require.passcode.reason.label
  - FxA.SignIntoSync
  - FxA.SyncExplain
  - Menu.NoImageModeBlockImages.Label
  - ReopenClosedTab.KeyCodeTitle
  - Settings.TrackingProtectionOption.BlockListBasicDescription
  - Settings.TrackingProtectionOption.BlockListStrictDescription
  - SwitchToNonPBM.KeyCodeTitle
  - SwitchToPBM.KeyCodeTitle
  - TabTray.LastWeek.Header
  - TabTray.MoreMenu.Copy
  - TabTray.Older.Header
  - TabTray.OpenSelectedTab.KeyCodeTitle
  - TabTray.SwipeMenu.More
  - TabTray.Today.Header
  - TabTray.Yesterday.Header
  - Version %@ (%@)
  - fxa.signin.turn-on-sync
  - Menu.AddToReadingList.Title
  - Menu.Library.Title
  - Menu.OpenHomePageAction.Title
  - Menu.RemoveBookmarkAction.Title

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4786)

**Comment by flodolo** [comment]
#7903 seems relevant.

For example, `After 1 hour` used to be in strings.swift, but almost everything was removed in https://github.com/mozilla-mobile/firefox-ios/pull/9251

I wonder if the fact that you need to manually remove things from en.lproj and en-US.lproj is a side effect of en-US not being imported (which, AFAIK, lead to other issues).

**Comment by flodolo** [comment]
The tracking protection strings were commented out 3 years ago 😭 #5274

Filing a PR trying to remove these strings.

**Comment by flodolo** [comment]
Found 4 more that the 1st version of the script missed (some existed as `ID.vX` form, e.g. `HomePanel.ContextMenu.OpenInNewPrivateTab.v100`, which grep found and considered used)
- Immediately
- DefaultBrowserCard.Button
- HomePanel.ContextMenu.OpenInNewPrivateTab
- ScanQRCode.PermissionError.Message

**Comment by lmarceau** [comment]
This relates to https://github.com/mozilla-mobile/firefox-ios/issues/9979. @dnarcese had made a list of strings that were safe to remove. @flodolo maybe worth checking those

**Comment by flodolo** [comment]
> This relates to #9979. @dnarcese had made a list of strings that were safe to remove. @flodolo maybe worth checking this as well

Looking into it. My script wouldn't catch any of those, because the string ID in the XLIFF is indeed showing up in a swift file.
