### ISSUE TITLE
Data Review for number of visits in a user's history database

### ISSUE THREAD

**Issue by tarikeshaq** [mozilla-mobile/firefox-ios#11635]
# Request for data collection review form

**All questions are mandatory. You must receive a review from a data steward peer on your responses to these questions before shipping new data collection.**

1) What questions will you answer with this data?
> - How many visits does an average user have in their history database on iOS
> - What's a reasonable range of visits to test migrations to the new application-services database
> - Can we associate a large database with poor performance for awesomebar?
> - What does the distribution of visits look like for users? what are outliers?

2) Why does Mozilla need to answer these questions?  Are there benefits for users? Do we need this information to address product or business requirements? Some example responses:

> * Establish a baseline for what an average user's visit database size is like
> * Allows us to track any regressions on how user's databases grow
> * Allows us to identify any opportunities in pruning user's databases
> * Allows us to measure the upcoming migration to application-services and track its impact on the number of a user's visits.

3) What alternative methods did you consider to answer these questions? Why were they not sufficient?
> We don't currently have any data on the number of visits for a user's history database. If we have developers check their devices it would be purely speculative and skewed.

4) Can current instrumentation answer these questions?
> No. We currently do not have metrics that track the number of history items for iOS.

5) List all proposed measurements and indicate the category of data collection for each measurement, using the [Firefox data collection categories](https://wiki.mozilla.org/Data_Collection) found on the Mozilla wiki.   

For the implementation, look at the [pull request](https://github.com/mozilla-mobile/firefox-ios/pull/11634)

<table>
  <tr>
    <td>Measurement Description</td>
    <td>Data Collection Category</td>
    <td>Tracking Bug #</td>
  </tr>
  <tr>
    <td> The number of visits users have in their history database. </td>
    <td>Techincal Data</td>
    <td>https://mozilla-hub.atlassian.net/browse/SYNC-3260</td>
  </tr>
</table>

6) Please provide a link to the documentation for this data collection which describes the ultimate data set in a public, complete, and accurate way.
> **This collection is documented in the Glean Dictionary at https://dictionary.telemetry.mozilla.org/**

7) How long will this data be collected?  Choose one of the following:

> * I want to permanently monitor this data. Tarik Eshaq (@tarikeshaq: teshaq@mozilla.com)

8) What populations will you measure?

> **All channels in all countries in all locales, for firefox-ios users**

9) If this data collection is default on, what is the opt-out mechanism for users?

> **Standard Firefox-ios telemetry controls**, users can opt-out in the settings menu.

10) Please provide a general description of how you will analyze this data.

> **Observe the quantity of visits in users database. Derive averages, means and modes. Use the data to educate us on what reasonable values to test migrations would be.

11) Where do you intend to share the results of your analysis?

> **The Sync and Firefox iOS teams**

12) Is there a third-party tool (i.e. not Glean or Telemetry) that you are proposing to use for this data collection? If so:

> No.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4785)

**Comment by travis79** [comment]
> # Request for data collection review form
> 
> **All questions are mandatory. You must receive a review from a data steward peer on your responses to these questions before shipping new data collection.**
> 
>     1. What questions will you answer with this data?
> 
> 
> > * How many visits does an average user have in their history database on iOS
> > * What's a reasonable range of visits to test migrations to the new application-services database
> > * Can we associate a large database with poor performance for awesomebar?
> > * What does the distribution of visits look like for users? what are outliers?
> 
>     2. Why does Mozilla need to answer these questions?  Are there benefits for users? Do we need this information to address product or business requirements? Some example responses:
> 
> 
> > * Establish a baseline for what an average user's visit database size is like
> > * Allows us to track any regressions on how user's databases grow
> > * Allows us to identify any opportunities in pruning user's databases
> > * Allows us to measure the upcoming migration to application-services and track its impact on the number of a user's visits.
> 
>     3. What alternative methods did you consider to answer these questions? Why were they not sufficient?
> 
> 
> > We don't currently have any data on the number of visits for a user's history database. If we have developers check their devices it would be purely speculative and skewed.
> 
>     4. Can current instrumentation answer these questions?
> 
> 
> > No. We currently do not have metrics that track the number of history items for iOS.
> 
>     5. List all proposed measurements and indicate the category of data collection for each measurement, using the [Firefox data collection categories](https://wiki.mozilla.org/Data_Collection) found on the Mozilla wiki.
> 
> 
> For the implementation, look at the [pull request](https://github.com/mozilla-mobile/firefox-ios/pull/11634)
> Measurement Description 	Data Collection Category 	Tracking Bug #
> The number of visits users have in their history database. 	Techincal Data 	https://mozilla-hub.atlassian.net/browse/SYNC-3260
> 
>     6. Please provide a link to the documentation for this data collection which describes the ultimate data set in a public, complete, and accurate way.
> 
> 
> > **This collection is documented in the Glean Dictionary at [dictionary.telemetry.mozilla.org](https://dictionary.telemetry.mozilla.org/)**
> 
>     7. How long will this data be collected?  Choose one of the following:
> 
> 
> > * I want to permanently monitor this data. Tarik Eshaq (@tarikeshaq: [teshaq@mozilla.com](mailto:teshaq@mozilla.com))
> 
>     8. What populations will you measure?
> 
> 
> > **All channels in all countries in all locales, for firefox-ios users**
> 
>     9. If this data collection is default on, what is the opt-out mechanism for users?
> 
> 
> > **Standard Firefox-ios telemetry controls**, users can opt-out in the settings menu.
> 
>     10. Please provide a general description of how you will analyze this data.
> 
> 
> > **Observe the quantity of visits in users database. Derive averages, means and modes. Use the data to educate us on what reasonable values to test migrations would be.
> 
>     11. Where do you intend to share the results of your analysis?
> 
> 
> > **The Sync and Firefox iOS teams**
> 
>     12. Is there a third-party tool (i.e. not Glean or Telemetry) that you are proposing to use for this data collection? If so:
> 
> 
> > No.
> 
> ┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4785)

# Data Review

1) Is there or will there be **documentation** that describes the schema for the ultimate data set in a public, complete, and accurate way?

Yes, through the metrics.yaml file and the [Glean Dictionary](https://dictionary.telemetry.mozilla.org/).

2) Is there a control mechanism that allows the user to turn the data collection on and off?

Yes, through the "Send Usage Data" preference in the application settings.

3) If the request is for permanent data collection, is there someone who will monitor the data over time?

Tarik Eshaq <teshaq@mozilla.com> will monitor the permanent collection of this data 

4) Using the **[category system of data types](https://wiki.mozilla.org/Data_Collection)** on the Mozilla wiki, what collection type of data do the requested measurements fall under?

Category 1: Technical

5) Is the data collection request for default-on or default-off?

Default-on

6) Does the instrumentation include the addition of **any *new* identifiers** (whether anonymous or otherwise; e.g., username, random IDs, etc.  See the appendix for more details)?

No

7) Is the data collection covered by the existing Firefox privacy notice?

Yes

8) Does the data collection use a third-party collection tool?

No

## Result

data-review+
