### ISSUE TITLE
Extra space above the "New Tab" menu item

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/firefox-ios#11642]
## Steps to reproduce
1. Install TestFlight version >= v104.0 (14880).
1. Open the hamburger menu.
1. Scroll to the top of the menu to reach the "New Tab" menu item.

### Expected behavior
No extra space above "New Tab" menu item.

### Actual behavior
This is extra space above "New Tab" menu item. See the screenshot below.

This is a regression in TestFlight v104.0 (14880). There is no extra space in TestFlight v103.0 (13910).

### Device & build information
* Device: iPhone 12
* Build version: Nightly build 8/18. TestFlight 9000 (16188)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4788)

**Comment by cpeterso** [comment]
![DE9CC506-85F4-41D2-9ECF-FD9195468C83](https://user-images.githubusercontent.com/629193/185453443-71ff5892-8d8a-4eb1-8535-bb83b2ba7302.png)

**Comment by lmarceau** [comment]
There was a fix for this with opened issue https://github.com/mozilla-mobile/firefox-ios/issues/10194 but it seems it didn't entirely fix the problem. Basically, the menu appears fine in some occasion, but once it's scrolled the extra spacing is still there. cc: @dnarcese

**Comment by cpeterso** [comment]
I also see extra menu space below the “Settings” menu item in landscape orientation:

![025869DF-C979-40BB-A515-4E39777C388A](https://user-images.githubusercontent.com/629193/185730724-e074f543-8616-46b8-b95e-ad83d3889b83.png)

**Comment by data-sync-user** [comment]
➤ Laurie Marceau commented:

For QA, it should be tested on iPad and iPhone (with and without a notch) that the menu shows up properly without an extra space, in both portrait and landscape, with top and bottom URL bars. 

The contextual menus shown in different places throughout the app should also be checked. Some examples of contextual menus are:

  * Long press on the tab tray icon contextual menu
  * Long press on a top site contextual menu

All contextual menu shouldn’t have an extra space anymore.

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Validated on v9000 (37808), with iPhone 15 (17.0), iPhone SE (16.6) and with iPad Air 3rd Gen (17.3).

To be rechecked once the official v123 build is released.

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Validated on v123 (38000), with iPhone 15 (17.0), iPhone SE (16.6) and with iPad Air 3rd Gen (17.3).
