### ISSUE TITLE
Cannot add search engine

### ISSUE THREAD

**Issue by meichthys** [mozilla-mobile/firefox-ios#11697]
## Steps to reproduce
Try to add search engine
- add title
- add url
- tap save

### Expected behavior
Search engine is added

### Actual behavior
![image](https://user-images.githubusercontent.com/10717998/186407228-f0649da1-214f-477f-be58-bfefc2a13e25.jpeg)

### Device & build information
* Device: iPhone 12 mini
* Build version: 103.1 (15076)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4814)

**Comment by lmarceau** [comment]
@meichthys What is your search url? It might miss the search query `search?q=%s`

**Comment by meichthys** [comment]
Yep that was it. I was assuming that Firefox was adding the query parameter at the end. Thanks!
