### ISSUE TITLE
The app crashes after opening and closing one of the tabs

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#11696]
## Steps to reproduce
1. Open tab 1 and visit "biziday.ro"
2. Open tab 2 and visit "twitter.com"
3. Open tab 3 and visit "olx.ro"
4. Open empty tab 1
5. Open empty tab 2
6. Close empty tab 2
7. Close empty tab 1
8. Close tab 3 (olx.ro)
### Expected behavior
- The tabs should be closed
### Actual behavior
- The app crashes after closing one of the tabs
### Device & build information
* Device: iPad Air (15.4)
* Build version: 105.0 (16531)
### Notes
- Needs uplift of https://github.com/mozilla-mobile/firefox-ios/issues/11566
Attachments: 

https://user-images.githubusercontent.com/32130829/186381130-d2b432ab-b6c7-4695-a8b4-234569d222e9.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4813)

**Comment by SimonBasca** [comment]
I think this patch has not been uplifted to v105 https://github.com/mozilla-mobile/firefox-ios/pull/11605

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Marking as verified fix on 105.0 (16884)
