### ISSUE TITLE
Fix "Sync Now" tabs syncing in the Remote Tab Panel

### ISSUE THREAD

**Issue by lougeniaC64** [mozilla-mobile/firefox-ios#11702]
At the moment, clicking "Sync Now" from the Remote Tab Panel only syncs devices. This is due to a regression in the `syncClientsThenTabs` function that was introduced with the A-S tabs integration work for v103. The "Sync Now" functionality off of the Settings menu and timed syncing are functioning as expected.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4816)

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Note while testing this issue we’ve logged https://mozilla-hub.atlassian.net/browse/FXIOS-4823 ( https://mozilla-hub.atlassian.net/browse/FXIOS-4823|smart-link )
