### ISSUE TITLE
 Bookmarks are not correctly synced when tapping "Sync now" from the tabs tray #11713 

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#11713]
## Steps to reproduce
1. Log in on Desktop
2. Log in on iOS
3. On desktop, delete or bookmark a page
4. On iOS, go to tabs tray -> Synced tabs -> Tap "Sync now"
### Expected behavior
- The bookmarks from desktop should be correctly synced on iOS 
### Actual behavior
- The action from step 3) is not synced on iOS when syncing from the tabs tray. After tapping sync now from Firefox Setting, the bookmarks are correctly synced.
### Device & build information
* Device: iPad Pro (15.4)
* Build version: 105.0 (16844)
### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4823)

**Comment by lougeniaC64** [comment]
@SimonBasca @nbhasin2 Just an FYI, clicking "Sync Now" from the remote tabs panel syncs clients and tabs only by design, as under the hood `syncClientsThenTabs` is called rather than any of the full sync functions. This has been the case for years, well before the tabs integration work that was introduced in iOS v103 (see [here](https://github.com/mozilla-mobile/firefox-ios/blame/0daad9105698bdbd8d796a26a7fd25f2fff90db6/Client/Frontend/Browser/Tabs/RemoteTabsPanel.swift#L655) for details).

**Comment by lougeniaC64** [comment]
@SimonBasca I should qualify what I said. I don't see any evidence that clicking "Sync Now" from the remote tabs panel triggers a full sync based on my analysis of the iOS backend code. I'd definitely want Nish or someone on the iOS team to confirm that as I'm not as familiar with the frontend logic.

But from what I can see, clicking "Sync Now" from the remote tabs panel calls this [refreshTabs function](https://github.com/mozilla-mobile/firefox-ios/blob/b283b4393581ab5f279bd9597cbfd6f00bb9c598/Client/Frontend/Browser/Tabs/RemoteTabsPanel.swift#L655) in `RemoteTabsPanel.swift`. That function calls `syncClientsThenTabs` which (my v103 regression aside) syncs clients and tabs only. If a full sync were also triggered by that click I'd be surprised and slightly horrified 😬 .

**Comment by nbhasin2** [comment]
@lougeniaC64 I double-checked and the sync button inside settings is tied to `Sync Everything` however the sync button on the tab tray is only for syncing Clients And Tabs. 

@SimonBasca have you ever synced bookmarks using that button on Tab Tray? 🤔

**Comment by lougeniaC64** [comment]
Thanks, @nbhasin2!

To be fair, the fact that clicking "Sync Now" from the settings menu triggers a full sync while the same action in the remote tabs panel triggers a partial sync is probably the source of the confusion here. I think it would be within reason for a user to assume that a full sync is triggered in both places. An easy fix might be changing the wording to "Sync Tabs" on the remote tabs panel for clarity. But what happens next here (if anything) is probably a feature request driven by product and UI/UX consideration.

**Comment by SimonBasca** [comment]
@nbhasin2 I don't recall if bookmarks were synced using the button on Tab Tray but I agree with @lougeniaC64. We could change the string from tabs tray to "Sync tabs" or something else to make it more clear what we are syncing. I will leave the discussion open for the next triage meeting.

**Comment by dnarcese** [comment]
I created this #11845 to capture this work
