### ISSUE TITLE
The page is not immediately displayed in the Recently viewed section after tapping the home button

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#11723]
## Steps to reproduce
1. Visit a page
1. Tap the home button -> the page is not displayed in the recently visited
1. Background the app
1. Foreground the app -> the page is displayed in the recently visited
1. Tap on the page from the recently visited section
1. Tap on the Home button

## 

    1. Expected behavior

* The page should be displayed in the Recently viewed section

*# 
*## Actual behavior

* The page is not immediately displayed in the Recently viewed section after tapping the home button

*# 
*## Device & build information

* Device: iPhone 13 mini (15.4)
* Build version: 104.1 (16952)

*# 
*## Notes
Attachments: 

[https://user-images.githubusercontent.com/32130829/186908291-f2d1389a-d181-469f-a479-00f14498c78f.mp4](https://user-images.githubusercontent.com/32130829/186908291-f2d1389a-d181-469f-a479-00f14498c78f.mp4)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4827)

**Comment by data-sync-user** [comment]
➤ Raluca Iordan commented:

For QA: Plase check that after tapping on home button, he page is displayed in the Recently viewed section

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Verified as fixed on v9000 (30371) with iPhone 13 Pro (15.7.1).
