### ISSUE TITLE
Crash while closing a tab

### ISSUE THREAD

**Issue by ericswpark** [mozilla-mobile/firefox-ios#11722]
## Steps to reproduce
Not sure, Firefox crashed while trying to close a tab

### Expected behavior
Not crash

### Actual behavior
Crash

### Device & build information
* Device: iPhone XS Max
* Build version: 104.0 (15741)

### Notes
Attachments: 
[Client-2022-08-26-160734.zip](https://github.com/mozilla-mobile/firefox-ios/files/9430641/Client-2022-08-26-160734.zip)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4826)

**Comment by SimonBasca** [comment]
@ericswpark is this always reproducible? Could you send a screen recording of the issue?

**Comment by ericswpark** [comment]
@SimonBasca unfortunately not, it's sporadic. Happened to me twice though. Both times when closing tabs. Can't figure out the trigger.

(sorry for always reporting impossible-to-reproduce bugs)

**Comment by SimonBasca** [comment]
@ericswpark no worries 😄 . Could you please send me a screenshot of the homepage settings? Also when you are closing the tab you are closing it after doing some browsing or it's after cold launching Firefox?

**Comment by ericswpark** [comment]
@SimonBasca after using Firefox for some time. I've tried reproducing from cold boot by repeatedly opening and closing tabs but so far can't figure out how to repro. Home settings attached below:

![image](https://user-images.githubusercontent.com/13326074/186870978-2b9058ff-c344-4362-a8ad-cae298c2c2ee.png)

**Comment by lmarceau** [comment]
Hello! Thanks for opening this ticket. There's a new version 104.1 that will come your way that should fix this issue. When it comes your way it would be very helpful if you could tell us if this issue is solved or not. Thanks a lot!

**Comment by ericswpark** [comment]
Hi, so far I haven’t encountered this bug after updating, so I’ll close the issue now. Thanks!
