### ISSUE TITLE
The bookmark is not immediately  deleted from the Recently saved after deleting it from the bookmark panel

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#11724]
## Steps to reproduce
1. Bookmark a page
2. Go to bookmarks
3. Delete the bookmarked page
4. Check the Recently saved section
### Expected behavior
- The bookmark should be deleted from the Recently Saved after deleting it from the bookmark panel
### Actual behavior
- The bookmark is not immediately  deleted from the Recently Saved after deleting it from the bookmark panel
### Device & build information
* Device: iPhone 13 mini (15.4)
* Build version: 104.1 (16952)
### Notes
Attachments: 

https://user-images.githubusercontent.com/32130829/186911810-1f19d8cb-0c1a-4681-a213-7a0c8ad224c4.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4828)

**Comment by data-sync-user** [comment]
➤ Laurie Marceau commented:

We’re probably missing a case for the .ReadingListUpdated notification, so the reading list can be updated in that case.

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verifying as fix on 108 (22078)
