### ISSUE TITLE
Main menu does not have some translations in Spanish

### ISSUE THREAD

**Issue by alfonso-salces** [mozilla-mobile/firefox-ios#11729]
## Introduction
Home main menu **Customize Homepage** and **Help** translations to spanish are missing.

## Steps to reproduce
Open the app > Click hamburger menu icon

![image](https://user-images.githubusercontent.com/38917140/187028803-3c21d256-516b-45eb-a558-507c75f75974.png)

### Device info:
**model**: Iphone 12 mini
**SO version**: iOS 15.6.1
**lang**: es
### App info:
**version**: 104

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4829)

**Comment by lmarceau** [comment]
I'll close this issue in Firefox iOS since the translations needs to be submitted in the [Pontoon](https://pontoon.mozilla.org/en-CA/firefox-for-ios/) project. Once the translations are accepted, they will be imported to the project in the next string import that happens weekly. Thanks!

**Comment by lmarceau** [comment]
FYI, an example of string import PR done by our bot: https://github.com/mozilla-mobile/firefox-ios/pull/11732
