### ISSUE TITLE
App Consistently crashing whenever adding a custom search engine

### ISSUE THREAD

**Issue by BugZappa** [mozilla-mobile/firefox-ios#11731]
## Steps to reproduce

1) Open Firefox app

2) Visit settings tab

3) Visit “Search” tab

4) add search engine

5) Enter a custom search engine, personally I was trying to add StartPage using - https://startpage.com/sp/search?query=%s

### Expected behavior

Search engine gets added

### Actual behavior

App crashes

### Device & build information
* Device: iPhone 11 Pro
* Build version: IOS 15.6.1 (19G82)
### Notes
Attachments: 

I’ve attempted troubleshooting the app by uninstalling - reinstalling and clearing any cached data but no luck..

This issue was occurring both on Firefox v104 and v103.1

Edit: FireFox Focus adds custom search engines as intended without crashing, this issue is only on the main FireFox application.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4830)

**Comment by SimonBasca** [comment]
Thanks @BugZappa . This problem is fixed for v 105. https://github.com/mozilla-mobile/firefox-ios/issues/11187
