### ISSUE TITLE
[XCUITests] Sync int test China server page needs to be updated

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/firefox-ios#11743]
The test is failing as it is looking for "[Enter your email](https://github.com/mozilla-mobile/firefox-ios/blob/c3396d5d2d7ca9d4f7d3c29c6ad16ec24d52096a/Tests/XCUITests/IntegrationTests.swift#L95)" textField but for this site the textField is just "Email"

![Untitled](https://user-images.githubusercontent.com/1897507/187419108-250d7d92-7e34-4ca5-a0ce-17850453479a.png)

cc @clarmso

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4837)

**Comment by clarmso** [comment]
PR: https://github.com/mozilla-mobile/firefox-ios/pull/11781

**Comment by clarmso** [comment]
The PR has been merged. 🎉
