### ISSUE TITLE
Mobile bookmarks now in reverse order

### ISSUE THREAD

**Issue by weebler** [mozilla-mobile/firefox-ios#11753]
When I hit the bookmarks button (star) from the main menu my mobile bookmarks show in reverse alphabetical order. When go to settings menu (3 horizontal lines) and then click on bookmarks the order is correct (A-Z). Have tried syncing on PC and also on android mobile (all of which display fine) and then try syncing on ios again and nothing changes. This happens with version 104 and above.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4842)

**Comment by weebler** [comment]
> 

On my desktop, I have sorted all bookmarks in A->Z fashion this includes mobile bookmarks, anything in bookmarks folder etc., and any new bookmarks get placed at the bottom of the list. That is default and has always happened that way and is the same on multiple different devices as I have eveything synced.

But on my ipad, for whatever reason, the mobile bookmarks are in reverse order (Z->A from top to bottom) with any new bookmarks placed at the top of the list. When I go into desktop books list (on my ipad) the booksmarks show correctly A->Z from top to bottom. This change happened from 104 version and up and resyncing the bookmarks from my desktop pc or my android phone fixes the mobile bookmarks on my ipad.

**Comment by data-sync-user** [comment]
➤ Laurie Marceau commented:

For QA, it can be tested that new bookmarks are added at the top of the mobile folder. But existing order for mobile bookmarks is kept as is.

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verifying as fix on v9000 (18964). The newly added folders and bookmarks from desktop are in correct order on mobile. Existing order for mobile bookmarks is kept as is.

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verifying as fix on v106.0 (19594)
