### ISSUE TITLE
Screen is blured in private browsing after hovering mouse pointer at the top of the screen

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#11757]
## Steps to reproduce
1. Go to private browsing
1. visit a page
1. hover the mouse pointer at the top of the toolbar
    1. Actual behavior

* Private  browsing blurs the screen
    1. Device & build information
* Device: iPad Pro (15.4)
* Build version: main 
    1. Notes
Attachments: e7bf39ee0af8dbb8c2ca1f2a9ac4d9d0a2a1106b

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4845)

**Comment by SimonBasca** [comment]
https://user-images.githubusercontent.com/32130829/187688853-564d0f66-d3c9-4d3e-a1d0-2518493ad097.mp4

**Comment by dnarcese** [comment]
Can you highlight where the issue is?

**Comment by SimonBasca** [comment]
Sorry about that, the wrong video got attached. Here is the correct one.

https://user-images.githubusercontent.com/32130829/188404517-ea37aab9-0cbb-4762-9968-9da1e5e4b174.mp4
