### ISSUE TITLE
"Show first tab" and "Show last tab" shortcuts are in the "Tools" section

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#11758]
## Steps to reproduce
1. Press cmd on hdw keyboard
2. Scroll to the tools section
### Expected behavior

Design docs
![image](https://user-images.githubusercontent.com/32130829/187689174-f897ec0e-43a2-4dd3-9043-344b419dda77.png) 

### Actual behavior
- "Show first tab" and "Show last tab" shortcuts are in the "Tools" section

![image](https://user-images.githubusercontent.com/32130829/187689351-2397d381-0f7c-4517-bf03-3f025b49a72b.png)

### Device & build information
* Device: iPad Pro (15.4)
* Build version: e7bf39ee0af8dbb8c2ca1f2a9ac4d9d0a2a1106b

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4846)

**Comment by lmarceau** [comment]
@q2r5 would you want to have a look at this? 👀

**Comment by lmarceau** [comment]
PR https://github.com/mozilla-mobile/firefox-ios/pull/11770

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verifying as fix on main aeef46abeab95708f70551d57458b62e1a15bb98
