### ISSUE TITLE
Tab `lastUsed` property is being incorrectly set

### ISSUE THREAD

**Issue by lougeniaC64** [mozilla-mobile/firefox-ios#11769]
## Steps to reproduce

1. Sign into sync on desktop
2. Navigate to Firefox View and note the tabs in the Tab Pickup section
3. Open up Firefox Beta and sign into sync
4. Open up the tab tray
5. Open up a new tab
6. Navigate to a site
7. Navigate to Firefox View and note the tabs in the Tab Pickup section

### Expected behavior
The tab created in step 5 should be the most recent tab in the Tab Pickup section of Firefox View followed by the next most recent tabs noted in step 1.

### Actual behavior
The tab created in step 5 along with other open tabs in Firefox iOS appear in the Tab Pickup section with a last used time of "Just Now"

### Notes
The associated bug with the original STR are in [Bugzilla bug 1788111](https://bugzilla.mozilla.org/show_bug.cgi?id=1788111). I was able to reproduce this bug a few times, but not always.  I suspect that it stems from the [TabManager.saveTabs](https://github.com/mozilla-mobile/firefox-ios/blob/main/Client/Frontend/Browser/TabManager.swift#L299) call to [Tab.toRemoteTab](https://github.com/mozilla-mobile/firefox-ios/blob/f422c32b2035e4b8e9a25770114e4562d496a000/Client/Frontend/Browser/Tab.swift#L388), which creates the tabs records to be saved to storage but I'm not completely sure.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4851)

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verified fix on v105.0 (17614)
