### ISSUE TITLE
The border shadows are missing from the Jump Back In section and Recently Viewed  cards

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#11784]
## Steps to reproduce
1. Have the Jump Back In section and Recently viewed populated
2. Open homepage and observe the the Jump Back In section and Recently Viewed
### Expected behavior
- The Jump Back In section and Recently Viewed should have shadows on the border
### Actual behavior
- The border shadows are missing from the Jump Back In section and Recently Viewed  cards
### Device & build information
* Device: iPhone 12 Pro 
* Build version: main 8f592acb959b2ded1324de26ca7ea6d182b50bfb
### Notes
Attachments: 

![Screenshot](https://user-images.githubusercontent.com/32130829/188110602-a259124d-b8c2-4aa2-8ed0-50b31c1181c0.jpeg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4858)

**Comment by data-sync-user** [comment]
➤ Catalin Suciu commented:

Verifying as fixed on v9000 (18666).

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Marking as verified fix on v106.0 (19379) as this is no longer reproducible by following the steps to reproduce.  
Note that we still have one regression for this issue https://mozilla-hub.atlassian.net/browse/FXIOS-4982 ( https://mozilla-hub.atlassian.net/browse/FXIOS-4982|smart-link )
