### ISSUE TITLE
"Sync now" menu item missing?

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla-mobile/firefox-ios#11808]
## Steps to reproduce

I'm not sure what changed, but I don't see the "Sync now" button in my copy of Firefox iOS:

<img src="https://user-images.githubusercontent.com/96396/188724042-43d21203-c686-41d8-bdf3-bcec4bb66665.PNG" width="250">

Am I just missing something? Did that menu item move somewhere?

### Device & build information

* Device: iPhone 12 Pro
* Build version: Firefox 104.1 (16952)
### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4871)

**Comment by lmarceau** [comment]
Hello @jaredhirsch, thanks for opening this issue. Do you refer to this text?

![Screen Shot 2022-09-06 at 4 34 40 PM](https://user-images.githubusercontent.com/11338480/188732874-bd66694d-4015-4ea1-a9d0-adc2c1434b6e.png)


If so, once signed in this text is replaced by the account picture and name as you've showcased in the screenshot you shared.

You can sync your account in two places:
1. One directly in the settings, which sync everything related to your sync account.
![Screen Shot 2022-09-06 at 4 34 21 PM](https://user-images.githubusercontent.com/11338480/188732835-cbda6a98-2ed6-4f84-b039-793e5d692130.png)
2. The other place is in the tabs tray where you can sync your account tabs only.
![IMG_7162](https://user-images.githubusercontent.com/11338480/188733248-47af5391-318f-48c1-a34b-23ab853b84d1.PNG)

Let me know if this helps!

**Comment by jaredhirsch** [comment]
Oh, I see. That makes sense, thanks!
