### ISSUE TITLE
[Tabs Groups] The view is not scrolled to the seleted tab in tabs tray

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#11800]
## Steps to reproduce
1. Open a new tab
1. Repeat step 1) until the tab list is scrabble.
1. Dismiss tabs tray
1. Open tabs tray
    1. Expected behavior

* The view should be at the selected tab.
    1. Actual behavior
* The view is at the top of the list although the tab at the bottom of the list is selected 
    1. Device & build information
* Device: iPhone 12 Pro (15.4)
* Build version: 
    1. Notes
Attachments: 

https://user-images.githubusercontent.com/32130829/188632811-1b8cc09a-231d-459c-a267-f205429a2b73.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4866)

**Comment by data-sync-user** [comment]
➤ Nishant Bhasin commented:

I can’t reproduce this.

Simion Basca is this happening on v104.1 as well?

**Comment by data-sync-user** [comment]
➤ Daniela Arcese commented:

I also cannot reproduce.

**Comment by SimonBasca** [comment]
Confirming that this is not reproducible on the release channel 105.0 (17614). I was testing on the beta channel for v105.0 (17614) where Tab Groups are enabled from Settings. 

This issue is only reproducible when Tabs Groups are enabled. Sorry for the confusion
