### ISSUE TITLE
[iPad] Don't show the keyboard while the onbording screen is displayed

### ISSUE THREAD

**Issue by csuciu** [mozilla-mobile/firefox-ios#11812]
## Steps to reproduce
1. Clean install the app on an iPad.
2. Open the app while in landscape mode.
3. Check the home page.

### Expected behavior
The keyboard should not pop op while the onboarding screen is displayed.

### Actual behavior
The keyboard is displayed and it's covering part of the onboarding screen.

### Device & build information
* Device: iPad
* Build version: 9000 (17658)

### Notes
The keyboard is also shown in portrait mode but it's not covering the onbording screen

Attachments: 
![onboarding](https://user-images.githubusercontent.com/1866605/188842729-e6a33c9c-1e54-47af-ae1f-893b33c11e06.jpeg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4874)

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Verified as fixed on v106 (19594) with iPad mini 5 (14.7.1).
