### ISSUE TITLE
[XCUITests] Refactor History tests

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/firefox-ios#11815]
There are several tests in the [HistoryTests](https://github.com/mozilla-mobile/firefox-ios/blob/main/Tests/XCUITests/HistoryTests.swift) test suite that are failing due to changes mainly in the Recently Closed menu but there might be other due to latest changes.

We will need to update those. To have an idea about the failures, please see these Bitrise builds.

For iPhone: https://addons-testing.bitrise.io/builds/54dcaeb9-74b5-4b06-8ec6-b3bf49bb4e34/testreport/90fdbe02-feec-4e80-a680-d00b33fe56e9/testsuite/0/testcases?status=failed
For iPad: https://addons-testing.bitrise.io/builds/7fe7111b-6234-44f0-bed5-3191e1e6646b/testreport/74ec37d5-18d1-48a4-9285-d098232e383e/testsuite/0/testcases?status=failed

Sometimes the same fix applies for both platforms, but some others we need to use the if iPad() to change the user workflow depending on the device used.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4876)

**Comment by soumakumarpaul** [comment]
Hi @isabelrios Anyone currently working on this?
