### ISSUE TITLE
Firefox for iPadOS: some keyboard shortcuts don’t work

### ISSUE THREAD

**Issue by The-Phantom-Phreak** [mozilla-mobile/firefox-ios#11829]
## Steps to reproduce
0. Connect iPad to Magic Keyboard
1. Press `⌘` + `F`

### Expected behavior
- Search bar appears on bottom of screen

### Actual behavior
- nothing happens.

- Same process works fine in other apps on same device: Firefox Focus, Safari. There, pressing `⌘` + `F` brings up the search bar
- Some keyboard shortcuts work, like `⌘` + `T` for new tab
- Now that I remember, **the keyboard shortcut to “Find Again” did not work previously either (`⌘` + `G`)**

### Device & build information
* Device: iPad Pro 11-inch 3rd Generation
* Build version: Firefox 104.1

### Notes
- Also tried resetting machine, and uninstalling/reinstalling Firefox app
- Can still use “Find in Page” from the hamburger menu.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4888)

**Comment by lmarceau** [comment]
Hello! There was a bug indeed and this was fixed for v106. Thank you!

**Comment by lmarceau** [comment]
Fixed in PR https://github.com/mozilla-mobile/firefox-ios/pull/11711
