### ISSUE TITLE
Moving rows inside the mobile folder places the bookmarks at the wrong position

### ISSUE THREAD

**Issue by lmarceau** [mozilla-mobile/firefox-ios#11830]
## Steps to reproduce
1. Have some bookmarks in your mobile bookmarks
2. Go in edit mode
3. Click and drag a bookmark/folder to a new position
4. Close the bookmarks
5. Reopen it
6. The changed bookmark/folder isn’t at the position you saved it

### Expected behavior
Bookmark/folder should be in the right position they were moved

### Actual behavior
The changed bookmark/folder isn’t at the position you saved it

### Device & build information
* Device: Any
* Build version: Main, started in 104.0

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4889)

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Verified as fixed on the v9000 (18422) with iPhone 13 Pro (15.1.1).

Note that I verified this by closing the bookmark section by swiping and also by pressing the done button (and re-entering the bookmarks section).
