### ISSUE TITLE
[L10n] Generating screenshots on Bitrise is failing

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/firefox-ios#11855]
There is an issue within the L10n pull step:
Setting up new virtualenv...
`./ios-l10n-scripts/import-locales-firefox.sh: line 28: virtualenv: command not found`

Nothing has changed in the script step or its version, so investigating why this error has started now.
Failing build (Sept 9th): https://app.bitrise.io/build/61b0533e-fffb-4071-95dd-76abcfe0f6aa
Successful build (latest July 15th): https://app.bitrise.io/build/bcd5a5ce-bc23-4ea4-8dc7-e5cc6fedb0db

Until this is fixed we can't generate a new set of screenshots for the L10n team :( we will keep you posted. 
cc @Delphine 
cc @clarmso so that you are familiar with these issues in this environment, still not 100% explained to you, so no worries if there are a lot of unknowns.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4901)

**Comment by Delphine** [comment]
Thanks for flagging Isabel. I was wondering if this was also the case on Focus iOS? thank you

**Comment by isabelrios** [comment]
> Thanks for flagging Isabel. I was wondering if this was also the case on Focus iOS? thank you

No, Focus is not affected, we are getting the different locales from the project, so this step does not run there. Thanks for the heads up :)
