### ISSUE TITLE
String ID used with different values

### ISSUE THREAD

**Issue by flodolo** [mozilla-mobile/firefox-ios#11877]
Checked the logs this morning, and sure enough there are errors again.

```
--- WARNING: Key "Wallpaper.Download.Error.Title.v106" used with multiple values. Value "Couldn’t Download Wallpaper" kept. Value "Something went wrong with your download." ignored.
--- WARNING: Key "Wallpaper.Change.Error.Title.v106" used with multiple values. Value "Couldn’t Change Wallpaper" kept. Value "Something went wrong with this wallpaper." ignored.
--- WARNING: Key "Wallpaper.Change.Error.Title.v106" used with multiple comments "The message of the error displayed to a user when they trying to change a wallpaper failed." & "The title of the error displayed when changing wallpaper fails."
--- WARNING: Key "Wallpaper.Download.Error.Title.v106" used with multiple comments "The message of the error displayed to a user when they try change a wallpaper that failed downloading." & "The title of the error displayed if download fails when changing a wallpaper."
```

Would it be possible to create automated checks to avoid this? I even reviewed that PR, and only focused on the text and comments, completely missing the string IDs were duplicated.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4915)

**Comment by lmarceau** [comment]
@flodolo we get those warnings only when we run the import or export script right? Or do we get them somewhere else?

**Comment by lmarceau** [comment]
The export script is done through a Github action. I wonder if we could add a step in there to track down warnings for us. Manually checking is a pain.

**Comment by lmarceau** [comment]
From [last run](https://github.com/mozilla-l10n/firefoxios-l10n/actions/runs/3940502259/jobs/6741697542) of the export, it looks like this was solved. I think we can close this?

**Comment by flodolo** [comment]
> I wonder if we could add a step in there to track down warnings for us. Manually checking is a pain.

I guess you could search for `--- WARNING` in the log and raise an error somewhere, but it's not very scientific as a method (and extraction is very noisy, with 3 warnings still there)

**Comment by lmarceau** [comment]
The three warnings are:

```
2023-01-17 15:14:50 --- WARNING: bad entry in file /Users/runner/work/firefoxios-l10n/firefoxios-l10n/code_repo/WidgetKit/OpenTabs/OpenTabsWidget.swift (line = 94): Argument is not a literal string.

2023-01-17 15:14:54 --- WARNING: bad entry in file /Users/runner/work/firefoxios-l10n/firefoxios-l10n/code_repo/Client/Frontend/Strings.swift (line = 28): Argument is not a literal string.

2023-01-17 15:14:54 --- WARNING: bad entry in file /Users/runner/work/firefoxios-l10n/firefoxios-l10n/code_repo/Client/Frontend/Strings.swift (line = 34): Argument is not a literal string.
```

The first one relates to TodayWidget, which will remove soon when we drop iOS 13.0. So I wouldn't worry about that one.

The two others I'm unsure what to do since line 28 and line 34 points seems to point to [the following](https://github.com/mozilla-mobile/firefox-ios/blob/d437816e9d44bf68a8fe908680341f8190307c80/Client/Frontend/Strings.swift#L28-L34).
