### ISSUE TITLE
Reminder: import strings in v105 using manual action

### ISSUE THREAD

**Issue by flodolo** [mozilla-mobile/firefox-ios#11876]
Just trying to avoid surprises: string updates to v105 shouldn't be uplifted from the main branch, they should be imported manually triggering the action, and putting `v105.0` as parameter.
https://github.com/mozilla-mobile/firefox-ios/actions/workflows/import-strings.yml

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4914)

**Comment by flodolo** [comment]
The reason for this is that v105 has extra strings in Info.plist that would be removed, since they have been [changed in v106](https://github.com/mozilla-mobile/firefox-ios/pull/11720).

**Comment by lmarceau** [comment]
PR for this is [here](https://github.com/mozilla-mobile/firefox-ios/pull/11886)
