### ISSUE TITLE
[Accesibility] The spacing is to large between two items in the jump back in section

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#11880]
## Steps to reproduce
1. Increase text to maximum
2. Visit google.com
3. Visit amazon.com
4. Open a new tab and observe the Jump Back in section
### Actual behavior
- Spacing is to large between two items in the jump back in section
### Device & build information
* Device: iPhone 12 Pro (15.4)
* Build version: 9000 (18422)
### Notes
Attachments: 

![image](https://user-images.githubusercontent.com/32130829/189644614-ac1e3261-b3d9-4dbb-9562-9fd2b4624fa5.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4916)

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verified fix on main a07825b122cc5f6b63a77606fcdaca6a65f220cf

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verified fix on v106.0 (19594)
