### ISSUE TITLE
The Sync now button is missing and there is no error message that FxA is not connected.

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#11881]
## Steps to reproduce
1. Login to FxA
1. Disable network connection on device
1. Go to Firefox Setting 
    1. Expected behavior

* There should be an error message that FxA is not connected.
    1. Actual behavior
* The Sync now button is missing and there is no error message that FxA is not connected.
    1. Device & build information
* Device: iPhone 12 pro (15.4)
* Build version: 9000 (18422)
    1. Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4917)

**Comment by data-sync-user** [comment]
➤ Tiffanie Shakespeare commented:

tagging nicole for a decision - when the device is connected to the internet, there’s a ‘sync now’ button under the email address of the account. when the device is in airplane mode, that button completely disappears. / cc Emily Wachowiak 

!IMG_86DD6931DA9C-1.jpeg|width=375,height=812!

!IMG_D87D713578BE-1.jpeg|width=375,height=812!

**Comment by data-sync-user** [comment]
➤ Nicole Weber commented:

I agree that it would be nice to communicate the system status. That said, we should investigate how this is implemented and communicated across platforms and come up with a proposal.

**Comment by data-sync-user** [comment]
➤ Tiffanie Shakespeare commented:

sounds like it’s a bigger project that needs to be prioritized on our roadmap- removing needs-ux label. thanks nicole!
