### ISSUE TITLE
Enhance development workflow for initial experiments usage

### ISSUE THREAD

**Issue by jeddai** [mozilla-mobile/firefox-ios#11897]
The development workflow when developing and testing features tied into Nimbus has been made complicated by the `initial_experiments.json` file. 

While developing and testing changes, developer channel defaults as set in the `nimbus.fml.yml` can be overridden by the application enrolling in first run experiments. This can be particularly problematic when, for example, a control branch for a first run experiment sets the value for a feature to the same value as the default, but a treatment branch sets a different value. The state of the application is effectively non-deterministic at that point, and can lead to confusion when inspecting code for errors.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4925)

**Comment by dnarcese** [comment]
@jeddai is this issue still relevant?

**Comment by jeddai** [comment]
I'm honestly not sure what the reason for opening this was at this point, nah I'll close it.
