### ISSUE TITLE
The "Visualize password" button from the sign in to sync dialog is missplaced

### ISSUE THREAD

**Issue by csuciu** [mozilla-mobile/firefox-ios#11904]
## Steps to reproduce
1. Try to sign in to sync using your email.
2. When entering your password observe the "Visualize password" button. 

### Expected behavior
The button is correctly positioned in the password input field.

### Actual behavior
The button overlaps the "Sign in" button

### Device & build information
* Device: iPhone 12 Pro (15.6.1)
* Build version: v9000 (18666)
### Notes

Attachments: 
![34Z](https://user-images.githubusercontent.com/1866605/189911323-11022878-cea4-4dce-aa4e-51aa2c2fb6c6.jpeg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4929)

**Comment by dnarcese** [comment]
Sending this to the Accounts team as this page is not managed by us
