### ISSUE TITLE
The user should be directed to a marketing link after tapping on "Learn more"

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#11919]
## Steps to reproduce
1. Go to wallpaper settings
2. Tap on the "Learn more" link
### Expected behavior
- The user should be directed to a marketing link.
### Actual behavior
- The link is not functional.
### Device & build information
* Device: iPhone 12 Pro (15.7)
* Build version: 9000 (18790)
### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4938)

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Tested on latest main a07825b122cc5f6b63a77606fcdaca6a65f220cf.

Looking at the commit I assume that if no URL is present, the button will not be displayed. Currently I don’t think we have a marketing link and in consequence the “Learn more” button is not displayed. 

Am I getting this right Winnie Teichmann ?

**Comment by data-sync-user** [comment]
➤ Winnie Teichmann commented:

Simion Basca you are absolutely correct. If we have no URL, the link will not be displayed and currently we have no collection with a URL.

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Closing as fixed on a07825b122cc5f6b63a77606fcdaca6a65f220cf

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Marking this issue as verified fix since the implementation is correct. Note the “learn more” page is broken or not yet completed https://github.com/mozilla-mobile/firefox-ios/issues/12029 ( https://github.com/mozilla-mobile/firefox-ios/issues/12029|smart-link )
