### ISSUE TITLE
Homepage flickers when scrolled after restarting the app

### ISSUE THREAD

**Issue by csuciu** [mozilla-mobile/firefox-ios#11912]
## Steps to reproduce
1. Have all the Homepage sections enabled and populated.
2. While in the homepage, close the app.
3. Reopen the app and scroll the homepage.
### Expected behavior
No flicker is observed.

### Actual behavior
The homepage is flickering when scrolled

### Device & build information
* Device: iPhone 12 Pro (15.6.1)
* Build version: v9000 (18666)
### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4933)

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verifying as fix on v110 (26107)
