### ISSUE TITLE
 [Regression] Wallpaper onboarding not showing when expected 

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#11955]
## Steps to reproduce
1. Clean install v9000 (19069)
2. Visit a page
3. Open a new tab

Expected
- The wallpaper onboarding should show up on the next homepage visit after seeing all of the eligible CFRs.

Actual
- The wallpaper onboarding showed up before the Jump back in CFR

### Device & build information
* Device: iPhone 12 Pro
* Build version: v9000 (19069)
### Notes
Attachments: 

https://user-images.githubusercontent.com/32130829/190623016-b436d99e-c7b3-40a6-b353-bb71fbd52fe6.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4957)

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verifying as fix on v106 (19965)
