### ISSUE TITLE
Twitter

### ISSUE THREAD

**Issue by oneofthedamons** [mozilla-mobile/firefox-ios#11961]
Is anybody else seeing frequent crashes since version 104 when using Twitter ? How can I assist further?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4961)

**Comment by SimonBasca** [comment]
@oneofthedamons could you please share you're steps to reproduce? On what build is this issue occurring and what device? Also could share a video and screenshot of your homepage?

**Comment by oneofthedamons** [comment]
Hi @SimonBasca the most common failure mode is:
1. in Firefox load twitter.com
2. follow a link on Twitter which opens another tab in Firefox (which may in turn open an installed app associated with that URL)
3. once the page or app loads, go back to the Twitter tab or (if an app opened) use the iOS app switcher to go back to Firefox
4. Firefox then crashes
Sometimes several iterations of steps 2-4 are required to prompt the crash, but a crash is always inevitable.
Sometimes Firefox will freeze, other times it crashes without warning.
If I use Twitter on Safari but maintain using Firefox for other non-Twitter activity I don't run into these issues (neither Safari nor Firefox crashes).
This is a first edition iPad Pro (9.7-inch) (Wi-Fi + Cellular) a.k.a. _iPad6,4_ so getting a little long in the tooth, but I rarely if ever saw crashes prior to version 104. Current build is Firefox 104.2 (17705).
[Video of Firefox homepage](https://user-images.githubusercontent.com/20738560/191252341-474d0da4-0f64-477e-9d1c-00084b3a3470.mp4)
[Screenshot of Firefox homepage](https://user-images.githubusercontent.com/20738560/191252874-958946bb-e921-48d9-a571-b40245897620.jpeg)

Please let me know anything else I can do to assist.
