### ISSUE TITLE
First shortcut from the second row doesn't have a background after changing the wallpaper

### ISSUE THREAD

**Issue by csuciu** [mozilla-mobile/firefox-ios#11960]
## Steps to reproduce
1. Clean install the app.
2. Open the app and change the background.
3. Observe the Shortcuts section.
### Expected behavior
All shortcuts have blurred tile backgrounds
### Actual behavior
The background it's missing from the first shortcut from the second row.
### Device & build information
* Device: iPhone 12 Pro (15.6.1)
* Build version: v9000 (19073)
### Notes
Attachments: 
![000Z](https://user-images.githubusercontent.com/1866605/191028371-35ec9d49-c925-429c-baab-f1874c275de5.jpeg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4960)

**Comment by data-sync-user** [comment]
➤ Yoana Rios Diaz commented:

Available to test on main and it will be available on next build for v106 I will update the build # for v106 once is created
