### ISSUE TITLE
[XCTests] Tabs Perf tests: Pre-loaded tabs are not shown

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/firefox-ios#11963]
There is the [TabsPerformanceTest](https://github.com/mozilla-mobile/firefox-ios/blob/main/Tests/XCUITests/TabsPerformanceTests.swift) suite where we are launching the app and the tab tray with different number of tabs, from 1 to 1200. 
To run these tests we created some `.archive`[ files containing the tabs](https://github.com/mozilla-mobile/firefox-ios/blob/2887a4eede37591f5448c0030462ffbdc3f4c513/Tests/XCUITests/TabsPerformanceTests.swift#L5). 

Unfortunately after this commit 6a0b5048121eb1690d82fa2b13235af817857e67 the tabs are not shown in the simulator.

I see changes in the `TabManagerStore` which will be likely the cause of this.

@lmarceau (as author of that commit ;))  I'm afraid we need your help to fix this :(

Also @rpappalax as I remember you creating those .archive files, we may need your help too

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4963)

**Comment by lmarceau** [comment]
How can I run those tests locally? So I can debug this

**Comment by isabelrios** [comment]
> How can I run those tests locally? So I can debug this

These are regular tests, the only thing is to check that the tabs loaded are more than one. Anyway I have sent you detailed instructions on slack, hope that helps :) I am totally available on zoom if you want to debug this
