### ISSUE TITLE
Shortcuts reverted to default

### ISSUE THREAD

**Issue by dnarcese** [mozilla-mobile/firefox-ios#11968]
## Steps to reproduce
Upgrade to v105 beta
### Expected behavior
No change in shortcuts
### Actual behavior
Pinned shortcuts disappeared, default shortcuts showing instead
### Device & build information
* Device: ?
* Build version: ?
### Notes
Attachments: 
<img width="837" alt="image" src="https://user-images.githubusercontent.com/11432165/191296505-1976cc0b-43ab-4b86-9de2-c6e5a35fbe51.png">

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4966)

**Comment by nbhasin2** [comment]
@dnarcese I tried going from release v104.1 to v105.0 (testflight) and my shortcuts were still there

**Comment by csuciu** [comment]
I can't reproduce either.  I tried upgrading both Beta and Release from latest TF v104.2 to latest 105.0

**Comment by the-next-ceo** [comment]
Same, I can't reproduce either. It seems fine to me.
