### ISSUE TITLE
Fix crash when switching to device time in the past

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#11975]
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4968)

**Comment by lmarceau** [comment]
I think this duplicates https://github.com/mozilla-mobile/firefox-ios/issues/10331

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Marking as verified fix on v9000 (19771)
