### ISSUE TITLE
[Experiment] the Jump Back In CFR is not displayed for New and Existing users in the Treatment branch of the MR experiment

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla-mobile/firefox-ios#11979]
## Preconditions
- Have an older version of Firefox Beta installed through TestFlight (eg. 104.0 (15741)).
- Enroll in the Existing Users Onboarding experiment from the Nimbus Preview Collection [link](https://experimenter.services.mozilla.com/nimbus/qa-firefox-android-nightly-mr-existing-user-onboarding).

## Steps to reproduce
1. Restart the App to ensure that the Experiment changes have been set.
2. Navigate to a website and open a new tab.
3. Fully close Firefox.
4. Open TestFlight and update Firefox Beta to the latest 9000 version available (19247).
5. Open Firefox and skip the onboarding slides.
6. Observe the behavior.

### Expected behavior
- The Jump back in CFR message is displayed on the homepage.

### Actual behavior
- No message or panel is displayed.

### Device & build information
* Simulated Device: iPhone Xr - iOS 15.3.1
* Build version: Firefox Beta 104.0 (15741) upgrading to 9000 (19247)

### Notes
- The issue is also reproducible for New Users on the latest main using a simulated device.

Attachments: 
- Screen recording of the issue:

https://user-images.githubusercontent.com/18304511/191475520-03243508-33de-49bb-a0ae-2dd3732eadd1.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4971)

**Comment by dnarcese** [comment]
THe Jump Back In CFR will only show once. So for an existing user, they have probably already seen it before and thus it will not show up.

**Comment by SoftVision-CiprianMuresan** [comment]
I see, I was not aware of this need for the Jump Back In message to appear. The message did appear once I dismissed the default browser message. I'll close the issue out in this case.
