### ISSUE TITLE
[Experiment] The Wallpapers panel is not displayed for New Users on the latest Firefox build from main on a simulated device

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla-mobile/firefox-ios#11978]
## Preconditions
- Have a Firefox build set to point to the Nimbus Stage server.
- Have a New User Onboarding experiment LIVE on the Nimbus Stage server ([link to stage clone](https://stage.experimenter.nonprod.dataops.mozgcp.net/nimbus/qa-firefox-ios-mr-new-user-onboarding-stage-copy/details))
- Add the recipe from the experiment to the `initial_experiments.json` file.

## Steps to reproduce
1. Run Firefox on a simulator until you are enrolled in the Treatment branch.
2. Skip the Onboarding slides.
3. Close and reopen the app.
4. Observe the behavior.

### Expected behavior
- The Wallpaper selection panel is displayed.

### Actual behavior
- No message or panel is displayed.

### Device & build information
* Simulated Device: iPhone 11 - iOS 15.2
* Build version: Firefox build from the latest main (9c933ba)

### Notes
- The issue is not reproducible for Existing users on the latest Firefox Beta 9000 (19247) installed from Testflight.

Attachments: 
- Screen recording of the issue:

https://user-images.githubusercontent.com/18304511/191473955-bda95a37-b324-4f58-bac0-e66965a17efb.mov

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4970)

**Comment by electricRGB** [comment]
You're saying "simulated device". Just verifying that that means you're running in simulator by building from Xcode. In that case, no, this won't work, because the URL for the assets in not hardcoded into the app. It's added in the BR build phase.

**Comment by SoftVision-CiprianMuresan** [comment]
Yes, that's correct, I'm running the app on a simulator by building from Xcode. Is there a way I could make this work through Xcode? 
Asking this because testing the experiment for new users would be easier this way as I can switch the app over to the Nimbus Stage server and test the flows with LIVE experiments. Testing in Preview requires an extra app restart which would mark the locally read experiment as Complete.

**Comment by electricRGB** [comment]
Heya. Yep. I'll send you the link privately.
