### ISSUE TITLE
The theme is not changed to dark or light in the new onboarding

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/firefox-ios#11981]
## Steps to reproduce
1. Launch Firefox and observe the two new onboarding cards.
2. Switch from dark to light theme.
### Expected behavior
The theme is not changed and it's always displayed as dark.
### Actual behavior
The theme is not changed to dark or light in the new onboarding.
### Device & build information
* Device: **iPhone 13 Pro (15.1.1).**
* Build version: **9000 (19247).**
### Notes
This issue also occurs on  v106 (19218).
Attachments: 

https://user-images.githubusercontent.com/42831109/191494836-1f957c1c-9e40-4a73-be42-1628c66a261c.mov

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4973)

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Marking as verified fix on v106 (19594). The wallpaper theme correctly adapts to system theme.
