### ISSUE TITLE
Recently visited layout is incorrect

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#11985]
## Steps to reproduce
1. Have the recently visited list populated
2. Scroll the recently visited list
### Expected behavior
- Layout should be correct.
### Actual behavior
- The layout is incorrect
### Device & build information
* Device: iPhone 12 Pro
* Build version: 106.0 (19218)
### Notes
Attachments: 

![Screenshot](https://user-images.githubusercontent.com/32130829/191507441-8acc3211-84dc-4694-9337-3488fc3f5d67.jpg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4976)

**Comment by data-sync-user** [comment]
➤ Yoana Rios Diaz commented:

This could’ve been fix with some of the latest changes for wallpapers, I can't reproduce on the latest main or v106 branch. @SimonBasca can you check if is still reproducible for you?

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Yoana Rios Diaz this issue is still reproducible on latest 106 (19773)

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verifying as fix on v106 (19965)
