### ISSUE TITLE
Have you ever seen this: Apple is allowing the Gecko engine to be on the App Store!

### ISSUE THREAD

**Issue by H-A-M-G-E-R** [mozilla-mobile/firefox-ios#11990]
https://www.macrumors.com/2022/07/05/eu-approves-landmark-legislation-to-regulate-apple/

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4977)

**Comment by lmarceau** [comment]
Hi thanks @H-A-M-G-E-R, we're aware of the changes that might come our way. I'll close this issue for now.
