### ISSUE TITLE
The Jump Back In CFR is not displayed after the wallpaper screen selector on homepage

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/firefox-ios#11998]
## Steps to reproduce
1. Launch Firefox and access the homepage.
2. Open any website.
3. Access the tab tray and tap on the `+`
4. The previously opened page is still open and on the home screen, the wallpaper screen selector is displayed.
5. Dismiss the wallpaper screen selection.
### Expected behavior
The Jump Back In CFR should be displayed after closing the wallpaper screen selector.
### Actual behavior
The Jump Back In CFR is not displayed after the wallpaper screen selector on homepage.
### Device & build information
* Device: iPhone **13 Pro (15.1.1).**
* Build version: v**106 (19336).**
### Notes
Note that if going again on the tab tray and tapping on the `+` button as a webpage is still opened from the previous browsing, the Jump back In CFR will be displayed.
Attachments: 

https://user-images.githubusercontent.com/42831109/191775615-f9c1f1f2-c595-407f-877e-f859665bdcb1.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4983)

**Comment by dnarcese** [comment]
This is intended behaviour. We do not show more than message per homepage visit.
