### ISSUE TITLE
Shadows are not displayed for none of the cards after changing from wallpaper to no wallpaper

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#11997]
## Steps to reproduce
1. Have the Jump back in card display
2. Have the Recently visited card displayed.
3. Observe the shadows for the Jump Back in, Recently saved and some of the Top Sites shortcuts
4. Set a wallpaper
5. Change to no wallpaper
### Expected behavior
- Shadows should be displayed for both cards
### Actual behavior
- Shadows are not displayed for none of the cards
### Device & build information
* Device: iPhone 12 Pro (15.7)
* Build version: 106.0 (19336)
### Notes
Attachments: 

![Screenshot](https://user-images.githubusercontent.com/32130829/191767989-8647ccda-f842-4cb3-a524-d0da2bf4857a.jpg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4982)

**Comment by yoanarios** [comment]
This it’s fixed for all sections as part of [PR](https://github.com/mozilla-mobile/firefox-ios/pull/11988). Currently is available to test on main and will be part of the next v106 build

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Yoana Rios Diaz I am still reproducing this issue on latest 106.0 (19379). The shadows are not displayed after changing from a wallpaper to the default blank one. 

Note that the shadows appear after app restart. Backgrounding or opening the a new tab will not fix the issue

!Video.mp4|width=444,height=960!

**Comment by data-sync-user** [comment]
➤ Yoana Rios Diaz commented:

Simion Basca this fix has not been uplifted to v106 yet, it should be done today. Laurie Marceau Winnie Teichmann can you add the build # to verify this fix once is done, please

**Comment by data-sync-user** [comment]
➤ Winnie Teichmann commented:

Simion Basca the fix is in +build #19594+ ( https://app.bitrise.io/build/acefa5a3-4ac7-4cc8-9beb-9e59bb5ffe09 )
