### ISSUE TITLE
The tab picker is not displayed in the jump back in card on 106.0 (19336) RC

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#11993]
## Steps to reproduce
1. Launch Firefox 106.0 (19336) or previous version 106 (119218) RC
2. Log in to sync on iOS and desktop
### Expected behavior
- The tab picker should be displayed in the jump back in card
### Actual behavior
- The tab picker is not displayed in the jump back in card
### Device & build information
* Device: iPhone 12 Pro (15.7)
### Notes
- The tab picker is displayed on 106 beta channel
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4978)

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Daniela Arcese we are currently blocked from testing the tab picker feature on latest RC 106.0 (19379) due to this issue. Any info on why this is not displayed on the RC channel? Note that the tab picker is displayed on the beta channel.

**Comment by data-sync-user** [comment]
➤ Daniela Arcese commented:

Simion Basca can you provide a screenshot of what you mean by tab picker?

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

In am referring to the synced tab from desktop that should be displayed in the Jump back in section. On the release channel after login in to FxA, the synced tab from desktop is not displayed but it is displayed on a beta channel. 

!image-20221003-090214.png|width=585,height=1266!

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Marking verified fix on v106.0 (19763)
