### ISSUE TITLE
Office.com becomes practically unusable on iPad (and maybe other devices)

### ISSUE THREAD

**Issue by eran-rom** [mozilla-mobile/firefox-ios#12008]
## Steps to reproduce
1. Browse to Office.com
1. Login with a Microsoft account
1. Click on Word/Excel/PowerPoint
1. Repeat step 3 for 4-5 times
1. The page becomes unresponsive and the UI freezes for a decent amount of seconds

### Expected behavior
As per my comparison to other browsers, Google Chrome and Microsoft Edge (both Chromium based browsers) are able to render this webpage perfectly fine, providing the smooth and expected user experience I expected Firefox to provide.

### Actual behavior
The page becomes laggy, freezes the UI for a few seconds and makes the use of Office.com practically impossible.

### Device & build information
* Device: iPad Air (3rd Generation) / Simulator - iPad 9th Generation
* Build version: 105 / Local build of main at 613707d 

### Notes
Unfortunately the screen recording doesn't show my clicks, but trust me, I kept the clicking tempo as can be seen at the beginning of the recording.

Attachments: 

https://user-images.githubusercontent.com/84767503/191823439-228c25ac-dbb3-41a8-b8b1-c44074884a6c.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4988)

**Comment by gutley** [comment]
Same here, but I can't even click anything once it loads initially. com.apple.WebKit.WebContent process is pegged at 100%

**Comment by eranr-talon** [comment]
@gutley I was able to solve it by simply changing the User Agent to Chrome's (Edge's also worked). I'm guessing it's Office.com sending out different versions of their website.

**Comment by gutley** [comment]
Also, its not just iPad, I see similar behaviour on iPhone 14 Pro Max

**Comment by gutley** [comment]
I can also get similar unresponsiveness in Safari on macOS. Toggling between Word, Excel and PowerPoint soon brings everything to a crawl. Setting a different user-agent via Develop menu fixes it. So it seems Office.com probably needs a custom user agent set of it.

**Comment by eran-** [comment]
Or our friends at Microsoft could simply stop sending different responses according to User Agent. But, obviously, this is out of our hand.
