### ISSUE TITLE
Pocket cell image being set in wrong cell

### ISSUE THREAD

**Issue by lmarceau** [mozilla-mobile/firefox-ios#12003]
![Screen Shot 2022-09-20 at 11 27 34 AM](https://user-images.githubusercontent.com/11338480/191811431-2003035e-6386-4a48-99f4-118c4f77065b.png)

STR: Scroll in pocket section, sometimes but not always the image is duplicated.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4986)

**Comment by data-sync-user** [comment]
➤ Catalin Suciu commented:

Tested on v9000 (19634) and wasn’t able to reproduce the issue. Verifying as fixed.
