### ISSUE TITLE
[XCUITEST] M1 machines lose mime-type when serving local html files through GCDWebServer

### ISSUE THREAD

**Issue by jjSDET** [mozilla-mobile/firefox-ios#12001]
On M1 machines all `/test-fixtures/` html files served through GCDWebServer no longer detect mime-type, resulting in all tests requiring those assets to fail.

We need to implement a solution forcing a mime-type declaration and unpacking of the html file contents to be served via an explicit `GCDWebServerDataResponse` call instead.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4985)

**Comment by DiqahLer** [comment]
> On M1 machines all `/test-fixtures/` html files served through GCDWebServer no longer detect mime-type, resulting in all tests requiring those assets to fail.
> 
> We need to implement a solution forcing a mime-type declaration and unpacking of the html file contents to be served via an explicit `GCDWebServerDataResponse` call instead.
> 
> ┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4985)
> 
- - [ ] - tqqq https://github.com/mozilla-mobile/firefox-ios/pull/11970)
