### ISSUE TITLE
[iPad] The keyboard pops up while the onboarding is displayed after upgrading from 105 to 106

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#12026]
## Steps to reproduce
1. Install v105 (18490)
2. Dismiss 105 onbording
3. Close v105
4. Upgrade to v106.0 (19594)
### Expected behavior
- The URL bar should not be focused on the first run.
### Actual behavior
- The keyboard pops up while the onboarding is displayed.
### Device & build information
* Device: iPad Pro (15.4)
* Build version: 106.0 (19594)
### Notes
Attachments: 

https://user-images.githubusercontent.com/32130829/192274683-811969bc-f628-4e72-99b8-d4843b3f4ba0.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5000)

**Comment by data-sync-user** [comment]
➤ Catalin Suciu commented:

Verifying as fixed on v106.0 (19763) after upgrading from the latest v105.0 build.
