### ISSUE TITLE
The new onboarding is not displayed when updating from `v105` to `v106` without closing Firefox

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/firefox-ios#12027]
## Steps to reproduce
1. Install v105.x.
2. Dismiss 105 onboarding.
3. Do not close Firefox and update from `v105 to v106.`
4. After the update is done, restart the app.
### Expected behavior
The new onboarding is displayed on `v106.`
### Device & build information
* Device: iPad mini 5 (14.7).
* Build version: 105.x and 106 (19594).
### Notes
Attachments: 

https://user-images.githubusercontent.com/42831109/192290121-420d13cb-e1fb-46a8-bec6-e23620c1282b.mov

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5001)

**Comment by data-sync-user** [comment]
➤ Yoana Rios Diaz commented:

This is the expected behaviour the upgrade onboarding won’t be shown in the same session where the onboarding first run was shown. You need to close the app and run again
