### ISSUE TITLE
Wallpaper "Learn more" page is broken

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#12029]
## Steps to reproduce
1. Go to Homepage -> Wallpaper
2. Tap on the "learn more" link
### Expected behavior
- The page should be displayed
### Actual behavior
- The page is broken
### Device & build information
* Device: iPhone 12 Pro
* Build version: 106.0 (19594)
### Notes
Attachments: 

![image](https://user-images.githubusercontent.com/32130829/192301770-27ad5eda-4da7-47de-bc34-81f1487124af.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5003)

**Comment by data-sync-user** [comment]
➤ Daniela Arcese commented:

Known issue. The article is not yet live. But it should work by release

**Comment by lmarceau** [comment]
@SimonBasca I think this can be closed, works now
