### ISSUE TITLE
Old onboarding is displayed when clean installing v106 (19594)

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#12025]
## Steps to reproduce
1. Clean install v106.0 (19594)
### Expected behavior
- New onboarding card should be displayed.
### Actual behavior
- Old onboarding is displayed.

![image](https://user-images.githubusercontent.com/32130829/192269978-f2fa26b8-7c62-44d9-87f8-d33a30d3ee3b.png)

### Device & build information
* Device: iPad Pro (15.7)
* Build version: 106.0 (19594)
### Notes
- After upgrading from v105.0 to v106 (19594) the new onboarding is displayed.
Attachments: 

[Jira issue](https://mozilla-hub.atlassian.net/browse/FXIOS-4999)

**Comment by data-sync-user** [comment]
➤ Yoana Rios Diaz commented:

This feature is under experiment, is there a way to confirm the experiment is enabled in which case the user will see the old onboarding instead of the new one

**Comment by SimonBasca** [comment]
Confirming that the experiment is setup correctly:
- control group -> The old onboarding is shown
- treatment-a group -> the new onboarding group is shown
