### ISSUE TITLE
[Experiment] The same Toolbar CFR message is displayed on both the control and treatment branches of the Holdback experiment

### ISSUE THREAD

**Issue by Softvision-PatriciuPop** [mozilla-mobile/firefox-ios#12038]
Affected Platforms:
 - iPhone 11, iOS 15.5
 
Affected Versions:
 - Firefox for iOS, 106.0 (19336) RC
 
Prerequisites:
 - Have the Firefox 106.0 RC installed from TestFlight.
 
Steps to Reproduce:
1. Open the browser and dismiss the onboarding cards.
2. Observe the Homepage.

Expected results:
- The Updated Toolbar CFR message is displayed.

Actual Results:
- The "To make entering inf easier, the toolbar is now at the bottom by default. Toolbar Settings" message is displayed for both branches of the experiment.

Notes:
- Attached a screenshot of the issue:
![IMG_0077](https://user-images.githubusercontent.com/40393891/192766142-84ec32e3-95e8-4949-9f34-4e72f4f4f784.PNG)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5010)

**Comment by data-sync-user** [comment]
➤ Nishant Patel commented:

The expected string (and therefore, the logic as well) was missing earlier. The string for this bug has now been added (l10n pending, https://github.com/mozilla-l10n/firefoxios-l10n/pull/167/files ( https://github.com/mozilla-l10n/firefoxios-l10n/pull/167/files|smart-link )), and the logic is built in.
