### ISSUE TITLE
Random crashes on iPhone under iOS 16

### ISSUE THREAD

**Issue by phenomax** [mozilla-mobile/firefox-ios#12034]
## Steps to reproduce

Random, sporadic crashes when I launch Firefox and start typing or just browse the website.
First, the tab freezes and then the whole app crashes.

### Expected behavior

No crashes or freezes

### Actual behavior

App crashes. On re-open all tabs and the current view is restored without any warning or crash notification.

### Device & build information
* Device: iPhone 14 Pro @ iOS 16
* Build version: 105.0 (18490)
### Notes
Attachments: 
[Client-2022-09-24-223654.ips.zip](https://github.com/mozilla-mobile/firefox-ios/files/9649706/Client-2022-09-24-223654.ips.zip)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5007)

**Comment by Dogscat3831** [comment]
> ## Steps to reproduce
> 
> Random, sporadic crashes when I launch Firefox and start typing or just browse the website.
> First, the tab freezes and then the whole app crashes.
> 
> ### Expected behavior
> 
> No crashes or freezes
> 
> ### Actual behavior
> 
> App crashes. On re-open all tabs and the current view is restored without any warning or crash notification.
> 
> ### Device & build information
> * Device: iPhone 14 Pro @ iOS 16
> * Build version: 105.0 (18490)
> ### Notes
> Attachments: 
> [Client-2022-09-24-223654.ips.zip](https://github.com/mozilla-mobile/firefox-ios/files/9649706/Client-2022-09-24-223654.ips.zip)
> 
> ┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5007)
> 

![image](https://user-images.githubusercontent.com/100335577/192447103-5f3f69a7-b2bb-4df9-9ac3-a30e8cb9f3d7.png)
