### ISSUE TITLE
The phone gets too hot.

### ISSUE THREAD

**Issue by snz2** [mozilla-mobile/firefox-ios#12044]
## Steps to reproduce
Just open the web page with Firefox and simply do a few

### Actual behavior
Just open the web page with Firefox and simply do a few

### Device & build information
* Device: ? iPhone 12
* Build version: ? 102~105
    1. Notes
Attachments: 

The phone gets too hot. What was surprised is that this problem remains the same after three updates. Perhaps it's a problem after version 102. I hope that the verification of the development contribution will not be suspected and the build will not be raised. I have been using Firefox for iOS for more than five years, and Firefox has been using it for more than 20 years. Seriously, I have been moving to Safari for a while since version 102. Why is the Firefox iOS version so much problem?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5015)

**Comment by gutley** [comment]
@snz2 Am not seeing anything similar here. Can you give some example websites that you experience this issue with.

**Comment by snz2** [comment]
Not a matter of a specific site
There are about 10 sites I use, but before version 102, there was no problem at all, and there was no problem after version 102, and there was no problem in Safari and Chrome.

Currently, 50 taps are open. Synchronize with Firefox PC
And except for me, there are more reviews that the battery consumption and the phone have become hot after version 102.

**Comment by snz2** [comment]
The 105 version is also hot.

**Comment by snz2** [comment]
The 106 version is also hot.

**Comment by francisqueitor4** [comment]
me too get so hot in iphone 12 mini

**Comment by snz2** [comment]
The 106.1 version is also hot.

**Comment by snz2** [comment]
The 106.2 version is also hot.

**Comment by h-taylor** [comment]
I also have this issue with 106.2
I notice it more when looking at a site with a lot of media being loaded (images, video, etc) such as reddit

In addition to running hot I've noticed it drains the battery quickly vs using safari and it seems to sometimes "freeze" when trying to use the firefox app bottom navigation.

I don't think I had these issues before updating major ios versions (14 to 15)

**Comment by snz2** [comment]
The 107 version is also hot. 

Is this a problem that only a person with a specific case is a specific setting? Do I have to erase all the settings, initialize and write? Setting for 5 years?

**Comment by petcg** [comment]
109.0 is also hot here.

Device: iPhone SE 2nd
OS: iOS 16.2
