### ISSUE TITLE
Deleting an inactive tab scrolls back to the beginning of the Inactive Tabs list

### ISSUE THREAD

**Issue by sellout** [mozilla-mobile/firefox-ios#12043]
## Steps to reproduce

1. have a sizable list of inactive tabs. I like to keep a few thousand around 😄
2. scroll down the list a ways
3. swipe left on a tab
4. tap “Delete”

### Expected behavior

Deleted tab disappears, but I continue viewing the same position in the tab list. I’d even be happy if the deleted tab just left a blank entry in the list rather than collapsing it.

### Actual behavior

List scrolls all the way to the top, so I have to scroll back down to delete the next tab I want to get rid of. Rinse and repeat.

### Device & build information
* Device: iPhone 12 mini
* Build version: Firefox 105.0 (18490)
### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5014)

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verifying as fix on v109 (24498). After deleting a tab from the inactive list, the view does not scroll.
