### ISSUE TITLE
Tabs bar disappears on iPad OS

### ISSUE THREAD

**Issue by Halfhumanhalfvulcan** [mozilla-mobile/firefox-ios#12054]
## Steps to reproduce
Open Firefox on iPad OS, scroll down a web page, scroll back up
### Expected behavior
Tab and URL bar disappears when scrolling down web page, reappears upon scrolling back up
### Actual behavior
Bar does not reappear upon scrolling back up. Exiting the app or opening multitasking makes the bar reappear
### Device & build information
* Device: iPad Pro 4th gen
* Build version: 105.0
### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5024)

**Comment by dnarcese** [comment]
@Halfhumanhalfvulcan are you using a mouse or trackpad when this bug occurs?

**Comment by Halfhumanhalfvulcan** [comment]
I’m using the trackpad on the magic keyboard. I’ve had it work properly with touch controls since, but the problem persists with the trackpad.

**Comment by dnarcese** [comment]
Thanks, it is the same issue as this #9657
