### ISSUE TITLE
“Search Web” button in iOS 16’s selected text menu opens Safari even though Firefox is my default browser

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/firefox-ios#12053]
I just upgraded my iPhone from iOS 15.x to iOS 16.0. When I long press on selected text in an app other than Firefox, the context menu has a "Search Web” button. Even though Firefox is my default browser, tapping the “Search Web” button opens Safari, not Firefox. When I long press selected text in Firefox, the context menu has both a “Search Web” (i.e. Safari) and “Search with Firefox” button.

I’m pretty sure this behavior is a regression caused by iOS 16.0.

If we can’t fix the “Search Web” button to use the default browser, maybe we can remove the “Search Web” button from the menu or position the “Search with Firefox” button before “Search Web” when selecting text in on a web page in Firefox itself? When I select text in Firefox and want to search for it in a new tab, I have to scroll to the end of the context menu, past “Search Web” to find “Search with Firefox”. 

### Device & build information
* Device: iPhone 12
* Build version: Firefox TestFlight version 9000 (16188) on iOS 16.0

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5023)

**Comment by cpeterso** [comment]
Screenshots of the “Search Web” and “Search with Firefox” buttons:

![CB92B61A-3366-45D9-883F-745AB52E83E4](https://user-images.githubusercontent.com/629193/193392579-a5c69daa-d76d-4971-a8d5-00ae762d4f01.jpeg)

![7B885BF4-CA87-4772-8FD6-1A7C4A7AB447](https://user-images.githubusercontent.com/629193/193392584-62da892f-2b53-41d6-8810-7afa1f460434.jpeg)

**Comment by gutley** [comment]
Same issue here. Note that the "Search Web" option doesn't show up in Firefox on iOS 15 at all.

**Comment by not-available-username** [comment]
I was thinking that "Search with Firefox" was gone ad I just discovered that this is visible only with English language, in my language I have only "Search Web" that does nothing, please fix this!

**Comment by Prurite** [comment]
Similar issue. Maybe it’s some *intentional* behavior by apple to promote safari?

**Comment by ICHx** [comment]
Same issue, can we hide that instead

**Comment by cpeterso** [comment]
@ICHx What iOS versions are you using?

I can no longer reproduce this issue. I’m using iOS 17.4.1.

**Comment by not-available-username** [comment]
> @ICHx What iOS versions are you using?
> 
> I can no longer reproduce this issue. I’m using iOS 17.4.1.

Same, was this fixed recently? Great!

Although when trying “Search web” I discovered that #11337 is still not fixed. Firefox 124.3 (40336)

**Comment by cpeterso** [comment]
In that case, I think we can close this issue. Since the “Search Web” button is in an OS menu shown  in other apps, there was probably nothing Firefox code could do to fix the button.

**Comment by cpeterso** [comment]
> when trying “Search web” I discovered that https://github.com/mozilla-mobile/firefox-ios/issues/11337 is still not fixed. Firefox 124.3 (40336)

I’ll reopen that issue. The last comment (2023) in that issue even says the big “still happens on iPhone 12, iOS 15.7.7 and iOS 16, Firefox 115.1”.

https://github.com/mozilla-mobile/firefox-ios/issues/11337#issuecomment-1643311834

**Comment by ICHx** [comment]
> In that case, I think we can close this issue. Since the “Search Web” button is in an OS menu shown in other apps, there was probably nothing Firefox code could do to fix the button.

Yes, not fixed. Wonder if this also happens in Chrome iOS

**Comment by not-available-username** [comment]
> > In that case, I think we can close this issue. Since the “Search Web” button is in an OS menu shown in other apps, there was probably nothing Firefox code could do to fix the button.
> 
> Yes, not fixed. Wonder if this also happens in Chrome iOS
> 
> iPadOS: 17.4.1 Firefox: 124.3

it was fixed on the previous versions and also on 125.1 for me (iPhone 12 and iOS 17.4.1)

**Comment by andiwunder** [comment]
Can we hide `search web` or move `search Firefox` up?
