### ISSUE TITLE
App Switching Crash (can't login to anything with 2factor app)

### ISSUE THREAD

**Issue by nickchite** [mozilla-mobile/firefox-ios#12061]
## Steps to reproduce
1. Open Sign in to GitHub
1. Enter username and password
1. Switch to Gmail App to copy Device Verification Code
1. Switch back to Firefox App

### Expected behavior
When switching back to firefox, you should be able to paste in code and login

### Actual behavior
Firefox crashes when switching back and then GitHub shows a 404 error (link: "github.com/sessions/verified-device")

### Device & build information
* Device: iPhone XR
* Build version: 105
    1. Notes
This is a massive issue for me because when I log into my university account, I have to switch to the Duo Mobile app for 2-factor, which creates the same bug.

For the Github login to Gmail, Firefox won't crash if wait about 5 seconds before app-switching.  But for the Duo Mobile login, it crashes almost all of the time no matter what.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5029)

**Comment by SimonBasca** [comment]
@n736 I have tried reproducing but was unable to. Is there any chance you can post a video of the issue?

**Comment by dnarcese** [comment]
Marking low priority unless the volume of this crash increases

**Comment by NoahTheDuke** [comment]
I see this with gitlab consistently. I suspect it's related to the general crashing and instability. I'll try to get a video tomorrow.

**Comment by SimonBasca** [comment]
Similar reports here https://github.com/mozilla-mobile/firefox-ios/issues/12362
