### ISSUE TITLE
The Hamburger Menu Takes A Long Time To Open

### ISSUE THREAD

**Issue by GenderCompass** [mozilla-mobile/firefox-ios#12073]
## Steps to reproduce
Click on the hamburger menu while on a website

### Expected behavior
It opens instantly

### Actual behavior
It takes several seconds to open

### Device & build information
* Device: iPhone SE (2020)
* Build version: Firefox 105.0 (18490)
### Notes
I clicked the hamburger menu right as I started screen recording. It took 15 seconds for it to open.
Attachments: https://imgur.com/a/y5rg0iy

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5039)

**Comment by gutley** [comment]
Is this on every website you try?

**Comment by GenderCompass** [comment]
> Is this on every website you try?

No, it can happen on any website but it doesn't happen every time.

**Comment by SimonBasca** [comment]
@GenderCompass is this only specific to the hamburger menu or the entire UI is slow to respond ?

**Comment by GenderCompass** [comment]
> @GenderCompass is this only specific to the hamburger menu or the entire UI is slow to respond ?

Everything else responds immediately. It's only the hamburger menu that does this.

**Comment by dnarcese** [comment]
duplicate of #12235
