### ISSUE TITLE
App Crashes or Freezes When Switching Out Of It

### ISSUE THREAD

**Issue by GenderCompass** [mozilla-mobile/firefox-ios#12072]
## Steps to reproduce
This happens under multiple different circumstances:

1. Use an autofill feature to put in your username and password. That will either cause a freeze or a crash.

2. Switch out of the app for a few moments then switch back into it. The app will either freeze indefinitely, freeze for a couple of seconds or crash.

3. Pull up the control centre. That will cause the app to freeze sometimes.

4. Get a low power warning. That will cause the app to freeze for a couple of seconds or indefinitely.

### Expected behavior
Switching out of the app, getting a low power warning, pulling up the control centre or using the autofill feature doesn't cause a freeze or a crash.

### Actual behavior
Switching out of the app, getting a low power warning, pulling up the control centre or using the autofill feature causes a freeze or a crash.

### Device & build information
* Device: iPhone SE (2020)
* Build version: Firefox 105.0 (18490)
### Notes
The attached video shows two types of freezing and crashing. The first happens when I use the autofill feature. The app freezes for several seconds, but doesn't crash.

The second happens when I switch out of the app and go to the mail app. When I switch back to Firefox the app crashes.
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5038)

**Comment by GenderCompass** [comment]
I can't put the attachment in the post for some reason but here's the link: https://imgur.com/a/v636Evf

**Comment by dnarcese** [comment]
@GenderCompass hey, what version of iOS are you on?

**Comment by dnarcese** [comment]
@GenderCompass also curious if Bitwarden password manager is slow on any other browsers or just Firefox?

**Comment by GenderCompass** [comment]
> @GenderCompass hey, what version of iOS are you on?

iOS 16.0.2

**Comment by GenderCompass** [comment]
> @GenderCompass also curious if Bitwarden password manager is slow on any other browsers or just Firefox?

No it's much faster on other browsers.

**Comment by jbkempf** [comment]
I have the same bug I believe on iOS 16.1 _(have the issue since 16 I believe)_  and iPhone 13 Pro Max.

**Comment by jbkempf** [comment]
General freezing almost all the time, which makes the app almost unusable. Which is sad, since that's the app I use 2/3 of the time.

Every time the app gets focused out (or in), it needs to restore the tabs, like it has crashed before. Or was kicked out by the system, for OOM reasons. Tabs restorations is often lagging behind, which makes it more hard.

Pulling the control center does do the same freeze (around 15sec). Autofill does trigger it also, but not 100% reliable.

The menu takes around 15s to show the first time, btw. Extremely weird.

This is a normal Firefox, with iOS 16.1 _(I always use the betas from iOS)_ with no signed-in. Almost no tabs, since they crash all the time. Passwords are very few, 3rd party passwd sync is being used.

**Comment by DHowett** [comment]
I'm seeing this as well. All of the above listed actions trigger a 10-15 second freeze. It appears to be any action that triggers `-[UIApplicationDelegate application:willEnterBackground:]` (or similar.)

I have experienced this issue on iOS 16.0 and 16.1.

Curiously, I am using Firefox for my passwords. I am _not_ using a third-party password manager. Even so, launching the password sheet while inside Firefox will cause Firefox to hang for 10-15s.

**Comment by dnarcese** [comment]
Might be related to #11776. A new version 106.1 will be released next week - let us know if it fixes any of these problems.

**Comment by GenderCompass** [comment]
I just updated and it's still happening. Had to stop using the app because of this.On Oct 27, 2022, at 3:53 PM, Daniela Arcese ***@***.***> wrote:﻿
Might be related to #11776. A new version 106.1 will be released next week - let us know if it fixes any of these problems.

**Comment by lmarceau** [comment]
Thanks @GenderCompass, we have multiple reports of crashes and freezes currently and we're aware this is a problem. It's being investigated. Other related issues are https://github.com/mozilla-mobile/firefox-ios/issues/12260 and https://github.com/mozilla-mobile/firefox-ios/issues/12244
