### ISSUE TITLE
Tabs don't sync with the new device ID after reconnecting device

### ISSUE THREAD

**Issue by mhammond** [mozilla-mobile/firefox-ios#12070]
## Steps to reproduce
* Be signed in to FxA.
* Either: change the FxA password on another device, or: in Manage Account, sign the iOS device out
* Note you are asked to reconnect - do the reconnection
* Wait for the next sync, or force the next sync.
* In desktop, look for the tabs from the device, note they do not appear and that device is no longer listed.

### Expected behavior
* Tabs from the device continue to sync

### Actual behavior
* They don't - syncing continues, but with the incorrect device ID

Note:
* Upon reconnection, the device has a new FxA ID. However, the tabs continue to sync with the old FxA ID. Due to this mismatch, desktop etc do not see any tabs from this device.
* Upon restart of the browser, things work again correctly. So the problem is probably that the FxA device ID is cached in memory, so remains stale until the browser restarts.

cc @lougeniaC64

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5036)

**Comment by lougeniaC64** [comment]
@mhammond I wasn't able to reproduce this issue by either changing the password on another device or signing out of the device via Manage Account. After doing both in separate tests, I was able to see my iOS tabs on desktop. However, the native [Client Synchronizer](https://github.com/mozilla-mobile/firefox-ios/blob/main/Sync/Synchronizers/ClientsSynchronizer.swift#L318) is using a cached FxA device ID and the [tabs sync function]((https://github.com/mozilla-mobile/firefox-ios/blob/main/Providers/Profile.swift#L1002) from all appearances is not.

If this is the mismatch you're observing, resolution might be as simple as pulling the FxA device ID from the account manager instead of scratchpad.

```
--- a/Sync/Synchronizers/ClientsSynchronizer.swift
+++ b/Sync/Synchronizers/ClientsSynchronizer.swift
@@ -1,7 +1,7 @@
 // This Source Code Form is subject to the terms of the Mozilla Public
 // License, v. 2.0. If a copy of the MPL was not distributed with this
 // file, You can obtain one at http://mozilla.org/MPL/2.0
-
+import Account
 import UIKit
 import Shared
 import Storage
@@ -315,7 +315,8 @@ open class ClientsSynchronizer: TimestampedSingleCollectionSynchronizer, Synchro
         log.debug("Got \(records.count) client records.")
 
         let ourGUID = self.scratchpad.clientGUID
-        let ourFxaDeviceId = self.scratchpad.fxaDeviceId
+        let ourFxaDeviceId = RustFirefoxAccounts.shared.accountManager.peek()?.deviceConstellation()?.state()?.localDevice?.id
+
         var toInsert = [RemoteClient]()
         var ours: Record<ClientPayload>?
```

**Comment by lougeniaC64** [comment]
I also tried to repro with Firefox Release on desktop and Firefox Beta on my iPhone by doing the following:

- Sign into Firefox on both devices
- Sign out out of Firefox Beta via the Manage Account screen on desktop
- Re-enter my password on Firefox Beta
- Open a tab on Firefox Beta
- Sync Firefox Beta and Firefox on desktop

The result was that I could see the new tab in my synced tabs list. In about:sync under the clients tab I have three client objects (one for the desktop app, two for the beta app before and after being signed out) and two FxA devices (my laptop and my iPhone with the new device ID). And I have all the expected records under the tabs section.

I'm nearing my EOD but I'll try to repro by changing my password on the iOS device, and using my iPad tomorrow. For completeness, my previous attempts were done with a local build with my iPhone connected to my laptop.

**Comment by mhammond** [comment]
`ourFxaDeviceId` is always correct in my testing, but I can reliably reproduce the following:

The [code just below what you quoted](https://github.com/mozilla-mobile/firefox-ios/blob/eacf47a2ae7c9b141f8d875657ed9b129e6b04fe/Sync/Synchronizers/ClientsSynchronizer.swift#L360) is what decides whether to upload our record or not. 
* When being forced out via "manage account", we sign back in, and that code has `self.why = .didLogin`, so we do upload.
* When we change the password on the device, `self.why` is typically "scheduled", so that doesn't fire - and none of the other conditions are true, so we just skip the upload - even though the new ID doesn't appear on the server.

Adding a check for `ours == nil` is *almost* correct, but not quite - note that remains nil if we find our record with the same timestamp we expect - so we want something like a new bool `oursExists` which is unconditionally set true when `rec.id == ourFxaDeviceId` and then we should check that as part of determining whether we should force upload our record.

Note also that we [re-upload every 2 days unconditionally](https://github.com/mozilla-mobile/firefox-ios/blob/eacf47a2ae7c9b141f8d875657ed9b129e6b04fe/Sync/Synchronizers/ClientsSynchronizer.swift#L279) so this problem ends up fixing itself - but we should still fix it.

It's quite possible I was confused when writing up this bug, so I think we should assume this is the problem I saw but just mis-reported it.

**Comment by lougeniaC64** [comment]
Oh, makes sense! Changing the password on the device was the case I hadn't tried yet. Also REALLY glad you were able to reliably reproduce this. I'll be even happier when we can remove this code with the sync manager integration. Either way, I'll create a PR for this today.
