### ISSUE TITLE
Moving rows inside the mobile folder places the bookmarks one position lower 

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/firefox-ios#12082]
## Steps to reproduce
1. Sync in order to get bookmarks.
2. Go into edit mode while having 4 bookmarks and move the one that is 4th in the first place.
3. Close the edit mode and the bookmark section and then re-open it.
4. Notice the bookmarks.
### Expected behavior
The 4th bookmark position should be first and not second.
### Actual behavior
Moving rows inside the mobile folder place the bookmarks one position lower.
### Device & build information
* Device: **iPhone 13 Pro (15.1.1).**
* Build version: **v106 (19773).**
### Notes
Attachments: 

https://user-images.githubusercontent.com/42831109/194310504-b3042b28-1db1-4194-be1b-45bde2f2efec.mov

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5049)

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Verified as fixed on v9000 (20530) with iPhone 13 Pro (15.1.1).
