### ISSUE TITLE
[Accessibility] Increasing the Accessibility Large text breaks layout for Synced tabs in the Jump Back In section

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#12090]
## Steps to reproduce
1. Login to FxA
2. Go to iOS setting -> Increase Large text
3. Go to the homepage 
### Expected behavior
-  Increasing the Accessibility Large text should not break layout for Synced tabs in the Jump Back In section
### Actual behavior
-  Increasing the Accessibility Large text breaks layout for Synced tabs in the Jump Back In section
### Device & build information
* Device: iPad Pro (15.7)
* Build version: 9000 (19831)
### Notes
Attachments: 

https://user-images.githubusercontent.com/32130829/194523041-665fcf09-c477-451a-a227-b3f8e36008f3.mp4

![Screenshot](https://user-images.githubusercontent.com/32130829/194522979-6e4ac706-6585-49c4-9a66-08dcd5331d4f.jpg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5053)

**Comment by data-sync-user** [comment]
➤ Daniela Arcese commented:

Ekaterina Galetski do you see this as a bug or is it acceptable?

**Comment by data-sync-user** [comment]
➤ Ekaterina Galetski commented:

Winnie Teichmann and I have reviewd this type of the “bug” last week. We identified a solution that would truncate the  number of text per each line. Basically limiting the text to two lines each.

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verifying as fix on v109 (24441).
