### ISSUE TITLE
Prevent scrolling in onboarding

### ISSUE THREAD

**Issue by topotropic** [mozilla-mobile/firefox-ios#12091]
Would it be possible to re-scale the text/image or do some other magic to prevent scrolling in the tour? Thanks!

<img width="375" alt="image" src="https://user-images.githubusercontent.com/353960/194525145-bbdec9d5-e126-4942-80ac-3dbf91e21fbd.png">

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5054)

**Comment by lmarceau** [comment]
@topotropic on which device is that? I think this will help debugging this

**Comment by topotropic** [comment]
iPhone SE, 15.6.1

**Comment by data-sync-user** [comment]
➤ Daniela Arcese commented:

Ekaterina Galetski can you provide guidance on how you think we should resolve?
