### ISSUE TITLE
 Crash when opening bookmarks toolbar

### ISSUE THREAD

**Issue by artpoli** [mozilla-mobile/firefox-ios#12093]
In version 105.1 the browser crashes after trying to open bookmarks toolbar. Firefox Account is connected.
Steps to reproduce:

* Open the browser
* Open the bookmarks menu
* Tap on the computer bookmarks
* Choose the bookmarks toolbar
* Crash

It’s being reproduced when opening particularly bookmarks toolbar.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5055)

**Comment by gilbh** [comment]
I have the exact same bug. FF 105.0 and iOS 16.0.2

**Comment by SimonBasca** [comment]
Could you please share a video of the issue?

**Comment by data-sync-user** [comment]
➤ Daniela Arcese commented:

Simion Basca have you been able to repro this reliably?

We are not seeing this show up in our crash logs as high volume. We will continue to track.

**Comment by SimonBasca** [comment]
I was unable to reproduce this issue on 105.0 (18490) or 106 (20167). I suspect that the crash might be caused by a particular bookmark that's being synced from desktop.

@dnarcese do we have cash log for this? Any hints what is causing the crash?

@gilbh just curious, is the crash happening when the your VPN is disabled?

**Comment by gilbh** [comment]
it happens both when VPN is connect and disconnect

**Comment by a-polivanchuk** [comment]
Updating my report after investigating an issue on my side.
An attempt of reproducing it on other iOS devices was not successful – everything works normally.
So I moved all my bookmarks from toolbar to menu and the issue moved along with them to the menu :)
Obviously, the culprit is some particular bookmark and I caught it:
https://b2b.kyivstar.ua/tbmb/hierarchy/main/dashboard/show.do
It was my old bookmark for local mobile provider. After deleting it, the issue was not reproduced anymore.

**Comment by kelimuttu** [comment]
SUMO has been getting reports about this (6 reports in total so far since Nov 22) on Apps Store and forum: https://trello.com/c/c7qw3tPo/40-firefox-for-ios-crashes-when-accessing-the-bookmarks-section

**Comment by lmarceau** [comment]
@kelimuttu we've been trying to find a way to reproduce this crash. Any logs of this crash would be very helpful. Also note that I tried from the current issue thread adding the `b2b.kyivstar.ua` bookmark but it wasn't crashing for me sadly.

**Comment by kelimuttu** [comment]
@lmarceau We managed to get the log from one of the affected users on the forum: https://paste.mozilla.org/PAwjZxeg 

I hope this helps!

**Comment by kelimuttu** [comment]
Oh, keep in mind that the link is expiring in a week.

**Comment by lmarceau** [comment]
Thank you! This helps but would also be great to get the crash logs. I added a bit of information in [our wiki](https://github.com/mozilla-mobile/firefox-ios/wiki/How-to-get-your-device-logs) to explain the difference between the two, with methods on how to get them. Thanks!

**Comment by kelimuttu** [comment]
Aha, apologies. Let me see if the user still can reproduce this issue.

**Comment by lmarceau** [comment]
@tarikeshaq could you review the logs to see if there's anything that catches your eyes? There's a lot of RUST logs in there but I can't tell if those are expected, or if this could be a possible path we need to investigate.

**Comment by tarikeshaq** [comment]
Hmm there is a couple of

```
init(localName:syncDelegate:clear:) > [RUST][places::error] Unexpected error: SqlError(SqliteFailure(Error { code: ConstraintViolation, extended_code: 275 }, Some("CHECK constraint failed: place_id != referrer_place_id")))
```

Us seeing that constraint violation is probably a bug somewhere in history metadata (or how we use it) and if errors aren't caught, it's possible that it's leading a to crash, although it should be an error that gets caught.

I'm not sure how that'll be triggered on synced bookmarks though 🤔 I almost would expect the error when navigating tabs and noting history metadata

I'll timebox a little tomorrow to look into the logs, and file a ticket for the history metadata on our side. Generally though the other `RUST` logs are expected.

This could very well be some type of malformed bookmarks that get synced and the iOS app doesn't know how to handle them, but without a stack trace of some kind, it'll be hard to track down

**Comment by lmarceau** [comment]
Thanks @tarikeshaq ! That's a good point, I'll put some time on my side to see if we can add some logs to detect malformed bookmarks. Not sure if it's already logged/sent with proper priority log level.
