### ISSUE TITLE
[iPad] [Portrait]  Synced Tab layout is broken

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#12102]
## Steps to reproduce
1. Log in to FxA on desktop and iPad
2. change iPad orientation to portrait
3. Check the synced tab from desktop in the Jump Back in Section
### Expected behavior
- Layout should be like in the specifications from https://mozilla-hub.atlassian.net/browse/FXIOS-4593
### Actual behavior
- The layout seems broken
### Device & build information
* Device: iPad pro
* Build version: ?
### Notes
Possible duplicate of https://github.com/mozilla-mobile/firefox-ios/issues/12090
Attachments: 

![image](https://user-images.githubusercontent.com/32130829/194888148-eff022fe-1123-4f7a-8005-e6138d0f351d.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5061)

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

This issue was fixed as part of https://mozilla-hub.atlassian.net/browse/FXIOS-4593 ( https://mozilla-hub.atlassian.net/browse/FXIOS-4593|smart-link )
