### ISSUE TITLE
The Recently Visited button is not vertical aligned

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#12103]
## Steps to reproduce
1. Open homescreen
2. Observe the "See all" buttons
### Expected behavior
- The buttons should be vertical aligned
### Actual behavior
- The Recently Visited button is not vertical aligned
### Device & build information
* Device: iPhone and iPad
* Build version: 106.0 (19965)
### Notes
Attachments: 

![image](https://user-images.githubusercontent.com/32130829/194892178-627227c8-8a0d-4571-a35e-ec85b9f8fc25.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5062)

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verifying as fix on v9000 (20174)
