### ISSUE TITLE
[iPad]The synced tab is displayed only after closing a tab

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#12118]
## Steps to reproduce
1. Log in to FxA to populate the Jump Back in section with Synced tab from desktop
2. Go to Setting - > Trigger a manual sync
3. Dismiss Settings
4. Background the app
5. Restore the app to foreground and wait for the Synced tab to be displayed
### Expected behavior
- Synced tab should be displayed after the app is restored to foreground
### Actual behavior
- The synced tab is displayed only after closing a tab. Note that opening a new tab does not displayed the synced tab.
### Device & build information
* Device: iPad Pro (15.7)
* Build version: 106 (20167)
### Notes
- I was unable to reproduce on iPhone
Attachments: 

https://user-images.githubusercontent.com/32130829/195575504-d73ea267-4c62-475c-8ec2-0b489c799c9f.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5074)

**Comment by dnarcese** [comment]
@SimonBasca are you able to reproduce this 100% of the time? I wonder if the sync is just taking awhile and it happened to load when you closed the tab?

**Comment by SimonBasca** [comment]
@dnarcese I not able to reproduce this 100% of the time but it happens with high frequency . In the attached video it can be observed that sync has finished.  Note that after restoring the app to foreground I am experiencing a very slow response from the UI (possibly https://github.com/mozilla-mobile/firefox-ios/issues/12073)

https://user-images.githubusercontent.com/32130829/195833939-c3408455-b677-41a4-9a9e-535bd00336f9.mp4

**Comment by data-sync-user** [comment]
➤ Daniela Arcese commented:

Orla Mitchell should we add a trigger to reload the homepage data when you open a new tab?

**Comment by data-sync-user** [comment]
➤ Orla Mitchell commented:

It is supposed to reload on a new tab but it’s possible we just missed an iPad specific code path.

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verifying as fix on main 90000 (24587)
