### ISSUE TITLE
The synced tab card does not have the same height as the other Jump back in cards

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#12119]
## Steps to reproduce
1. Log in to FxA to populate the Jump Back in section with Synced tab from desktop
1. Open a few tabs to populate the Jump Back in section
1. Compare the height of the synced tab card with the other Jump back in cards
    1. Expected behavior

* According to the [design doc](https://www.figma.com/file/hJfV1KGZuOK7OYr29pooL5/Synced-tabs?node-id=1015%3A17312) the synced tab card should have the same height as the other Jump back in cards
    1. Actual behavior
* The synced tab card does not have the same height as the other Jump back in cards
    1. Device & build information
* Build version: 106 (20167)
    1. Notes
Attachments: 

### iPad Pro (11 inch screen)
![](https://user-images.githubusercontent.com/32130829/195576055-89c39165-a04e-4d98-80cc-342a6770e594.png)

### iPhone 
![IPhone](https://user-images.githubusercontent.com/32130829/195576102-89b6c33b-2fd4-419c-aebd-5741ea7c6ecf.jpeg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5075)

**Comment by data-sync-user** [comment]
➤ Daniela Arcese commented:

Yoana Rios Diaz was this a result of your latest fix?

**Comment by data-sync-user** [comment]
➤ Yoana Rios Diaz commented:

Daniela Arcese yes it could be a side effect unfortunately. We introduce a higher padding between the text and the sync button to avoid having to much space under text but it seems the number is not matching for all devices
