### ISSUE TITLE
Request spam for favicon and apple-touch icons on iOS 16 + Firefox 105

### ISSUE THREAD

**Issue by Tristan971** [mozilla-mobile/firefox-ios#12113]
## Steps to reproduce

Unclear at the moment

### Expected behavior

Firefox downloads the following website assets once, or maybe a few times at most:
- /favicon.ico
- /favicon.svg

Same for the more PWA-related ones
- /apple-touch-icon.png
- /apple-touch-icon-precomposed.png 
- /icon-512.png (etc, those are from our PWA meta headers)

### Actual behavior

For a few users, we receive an absurd amount of requests for these assets, causing users to get rate-limited and then temporarily IP banned.

We have a relatively small sample set so far, but they seem to all be on iOS 16 and using Firefox.

Here's a 30 seconds preview of the requests made by an affected user:

![2022-10-12 03_53_33](https://user-images.githubusercontent.com/875533/195238921-787d7f3d-98b3-4311-b18d-63e2dd490b3e.png)

While the browser may not perfectly cache these assets, I can't imagine that there is a strong need to re-download the site's favicon 160 times in 30 seconds.

Additionally, this is our cache policy on the favicon for example:
```bash
$ curl -v 'https://mangadex.org/favicon.ico' 2>&1 | grep 'cache-control'
< cache-control: public, max-age=31536000, immutable
```

We also don't directly use /apple-touch-icon{-precomposed}.png and rely on generic PWA meta headers (these are the /icon-XYZ.png in the lows below).

But since our website is an SPA, it always return a 200 no matter the path asked (as routing is done on the JS side of things and static assets are merely higher priority attempt as far as nginx is concerned, ie `try_files $uri $uri/index.html $uri/ /index.html;`).

### Device & build information

Here's 2 users from which we were able to get details:
- iOS 16.0 (20A362) + Firefox 105.0 (18490)
- iOS 16.0 (20A380) + Firefox 105.0 (18490)

### Notes

Attached is an excerpt from one such user's request logs over the offending period. The 429s is when the rate-limiter kicks in, and the 403s is when the user has been temporarily IP banned.

[logssorted.txt](https://github.com/mozilla-mobile/firefox-ios/files/9761149/logssorted.txt)

Also note that it *could* be a generic webkit iOS issue but that seems really doubtful given the low amount of reports (3) and the fact that they all have Firefox-on-iOS-16 as common factor.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5065)

**Comment by Tristan971** [comment]
We learned a bit more about it; it seems that another factor is the user having many (as in typically hundreds) of tabs in their application.

If Firefox was periodically refreshing all the tabs of the user, and this process wasn't cache-aware, it would explain the issue. Though that would be rather horrifying, considering the absurd waste of compute/data on a mobile device.

Another interesting aspect is that this seems to include things like opengraph twitter cards too.

Hopefully this helps you narrow down what is happening.

**Comment by Tristan971** [comment]
This is still a problem in the newer versions too. Same behaviour but I can see `FxiOS/106.1` user agent, which is at least an improvement over the previous extremely weird one.

**Comment by Tristan971** [comment]
For the record, it seems like it'd be a combination of #12287 and total ignoring of static assets caching headers during tab reloads (hence the spam of requests, and the fact that the same successful requests for those gets issued a bajillion times).

Also, there is still no valid reason for FF to fetch opengraph images for tabs anyway... At least not before at best the share action is initiated by the user.

**Comment by Tristan971** [comment]
For what it's worth, we **still** see this occuring, even for users running (or at least claiming to) 107 (which bundles the fix for #12287 according to your tracker).

Interestingly, such users' browsers do not consistently use the 106+ `FxiOS` header either, so I can only assume that something is still screwed up in that regard.

Either way, it is becoming increasingly clear that DoS behaviour isn't considered a bug even worth acknowledging, we won't bother you further about it and will simply encourage end-users to use browsers that are able to behave properly.

**Comment by lmarceau** [comment]
We're currently working on a refactor of favicons fetching solution with the goal of replacing current ones. This means this bug will normally be fixed or hopefully at least be improved as a result of that. If it's still not solved after the refactor then we'll investigate the issue behind it. We're focusing our energy on the way forward since we're trying to replace favicons solution asap as they're causing major issues in production (crashes among other things). Thank you for your contribution on the project!

**Comment by Tristan971** [comment]
It's good to at least hear back, thanks. Hope that refactor project pans out nicely then 👍

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

We did a full test suite on v110 (26279) including testing the favicon. We didn’t encountered any major issues while testing. We can mark this as completed and re-open if the issue is reproduced again.

**Comment by Tristan971** [comment]
Glad to hear that and looking forward to it being released!

On that note, we had a couple of such happenstances on Android as well, is the fix an iOS-only one or is it in some shared component?

**Comment by lmarceau** [comment]
@Tristan971 this is iOS only, so for an Android bug I would go to their [Github](https://github.com/mozilla-mobile/fenix) to see if they have an open issue for this, or create a new one.

**Comment by Tristan971** [comment]
Got it, thanks
