### ISSUE TITLE
Main menu could be scrolled (even if it fits the screen)

### ISSUE THREAD

**Issue by pashynskykh** [mozilla-mobile/firefox-ios#12122]
## Steps to reproduce
1. Open menu.
1. Try to scroll.

Please check attachments for video.

### Expected behavior
Menu is fitting the screen, so shouldn't be scrollable. 

### Actual behavior
Menu could be scrolled.

### Device & build information
* Device: iPhone 11, iOS 16.0.3.
* Build version: Firefox 105.1 (19787).

### Notes
Attachments: 
https://user-images.githubusercontent.com/14852335/195608031-d208eb5a-0e4b-49fa-a0ea-076e9d54b317.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5078)

**Comment by lmarceau** [comment]
This relates to https://github.com/mozilla-mobile/firefox-ios/issues/11642

**Comment by pashynskykh** [comment]
The issue seem to be fixed. Closing as completed.
