### ISSUE TITLE
The "Today" header is missing after closing a tab and going to History

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#12121]
## Steps to reproduce
1. Close the app from app switcher if previously opened
2. Launch the app
3. Visit a page
4. Close the tab
5. Go to history
### Expected behavior
- The "Today" header is missing
### Actual behavior
- Header should be visible
### Device & build information
* Device: iPhone 13 mini (15.7) 
* Build version: 106 (20167)
### Notes
Attachments: 

https://user-images.githubusercontent.com/32130829/195593023-efac199f-4f4e-4e27-afa8-865ad1f6e597.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5077)

**Comment by dnarcese** [comment]
@SimonBasca do they ever come back? Next time you open the app or history?

**Comment by SimonBasca** [comment]
@dnarcese It does not re-appear after backgrounding the app, switching between library panels or by opening tabs. It re-appears after closing the app from app switcher and re-launching.

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Verified as fixed on v9000 (20530) with iPhone 13 Pro (15.1.1).

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verifying as fix on v108 (22078)
