### ISSUE TITLE
iOS long-press Open Last Bookmark

### ISSUE THREAD

**Issue by mattlikespie** [mozilla-mobile/firefox-ios#12148]
I use FF iOS on iPhone 13 (all updates applied). I noticed something odd in the long-press launch option from my home screen. 

Issue 1. Even after deleting all website data and history and closing the app completely, the Open Last Bookmark option shows up with what appears to be a recently opened book mark.

I wouldn't expect this be happen if I've cleared all data. Is this how the feature is supposed to work? I would expect that all history (including recent bookmark info) would be purged.

Issue 2. Whether I delete all data as above or not, the hard-press menu bookmark doesn't actually show the last or most recent bookmark opened. Rather it opens the bookmark at the top of the bookmark list in the "hamburger" menu. Is this the expected behavior?

## Steps to reproduce

1. Long-press the FF icon
2. Note the Open Last Bookmark
3. Open FF normally
4. Click the "hamburger" menu (lower right) and open a bookmark that is not the top item
5. Close FF
6. Long-press the FF icon

### Device & build information
* iPhone 13, iOS v 16.0.3 (20A392)
* FF iOS build 105.1 (19787)

### Notes: An additional oddity, add a new bookmark. Open the bookmark using the long-press method. Now go back into the "hamburger" menu and delete the bookmark. Go back to the FF long-press function and the deleted bookmark will be listed. Further, even though the bookmark has been deleted, tapping the Open Last Bookmark option will open the deleted bookmark.

Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5090)

**Comment by mattlikespie** [comment]
The Note: section above appears to be a dup of https://github.com/mozilla-mobile/firefox-ios/issues/10386

**Comment by dnarcese** [comment]
@mattlikespie can you verify whether this has been fixed in v106? You should be able to update now in the app store

**Comment by mattlikespie** [comment]
Updated iOS to 16.1 (20B82) and the issue is still present.

**Comment by lmarceau** [comment]
The quick action will show the most recent bookmark. I had a look and indeed the quick action isn't reset after all website and data is deleted, I don't think this is intended.

**Comment by lmarceau** [comment]
Ok after further investigation, when we delete website and data we clear the following:
- history
- cache
- recently closed tabs
- cookies
- etc.

But we don't delete bookmarks, so this is why the shortcut isn't updated as it points to the most recent bookmark. If you delete all your bookmarks then there would be no more shortcuts. From what I understand you expected a way to delete all bookmarks from the data management menu? Maybe the feature can be improved upon in the future, so I'll add the tag for this on the ticket.

**Comment by mattlikespie** [comment]
To confirm, I was inititally expecting that, when I deleted all website data and history, the last bookmark would also be removed. I began down this road because the bookmark I was seeing in the Open Last Bookmark long-press menu was not the one I was expecting.

The issue, as I began testing the feature, appeared to be that the Open Last Bookmark option was referencing a bookmark that was not the most recently opened. After further review, I found that even a deleted bookmark would appear as the Open Last Bookmark.

I am now at the point where the Open Last Bookmark shows a deleted bookmark and I cannot get a different bookmark to appear in the long-press menu.

**Comment by lmarceau** [comment]
Hey @mattlikespie! Thanks for the comment, I had a look and with your explanation of the bug I have found an issue where the shortcut wasn't updated properly. I just opened a PR aiming at fixing that. If the fix is accepted then it should be normally out with v108. Thanks!

**Comment by mattlikespie** [comment]
Happy to help!

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Marking a verified fix on main 9000 (21404). Long-pressing on the FF icon will show the correct page under recently bookmarked

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verifying as fix on v108 (22078).
