### ISSUE TITLE
H

### ISSUE THREAD

**Issue by savcI5-gejhar-huqjex** [mozilla-mobile/firefox-ios#12142]
####- - [_**c@[_**![image](https://user-images.githubusercontent.com/115864261/196011256-a3f18cd3-0b21-4b06-b8e4-73dd4d7621a6.jpeg)**_]()**_]()

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5087)

**Comment by lmarceau** [comment]
@savcI5-gejhar-huqjex Could you explain what is the problem you're facing a little? Does it relate to QR code? How can you reproduce the issue and on which device? Thanks!
