### ISSUE TITLE
Samsung smart tv online videos for javascript YouTube videos google chrome account for Samsung smart tv online videos for Microsoft bing apps

### ISSUE THREAD

**Issue by Dogscat3831** [mozilla-mobile/firefox-ios#12158]
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5095)

**Comment by lmarceau** [comment]
Hey @Dogscat3831, without more details on this issue we'll need to close it. What is the issue here? What are the steps to reproduce and on which device? Thank you!
