### ISSUE TITLE
Swiftkey replaced by defaut keyboard

### ISSUE THREAD

**Issue by CaptainJimo** [mozilla-mobile/firefox-ios#12168]
## Steps to reproduce
Open firefox browser. Tap search to get the keyboard

### Expected behavior
SwiftKey keyboard appears and can type

### Actual behavior
Swiftkey appears for a seccond and is then replaced by default ios keyboard

### Device & build information
* Device: iphone se 2020 
* Build version: ios version 14.8.1
* Firefox version 106.0
### Notes
This issue began right after updating firefox to version 106.0
This only affects firefox browser. Does not affect other apps
Firefox is selected for Auto fill passwords, but even if auto fill is disabled, the issue persists 
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5104)

**Comment by dnarcese** [comment]
This would correlate to an iOS release as opposed to Firefox release, as we do not have control over which keyboard to show.

**Comment by CaptainJimo** [comment]
> This would correlate to an iOS release as opposed to Firefox release, as we do not have control over which keyboard to show.

I do not believe this correlates to an iOS release/update, because there was no release/update. Only the firefox app got updated and right after that the keyboard issue appeared. Also I havent found any other apps that have this issue.

**Comment by lmarceau** [comment]
Hey @CaptainJimo, I tried reproducing and not sure if I'm missing a step. I have SwiftKey installed and selected, I open v106.0 up, the url bar is selected automatically for me but the SwiftKey keyboard stays there (not changed to be another keyboard type). Any other step I should do?

![IMG_9102](https://user-images.githubusercontent.com/11338480/197060860-5d97e8f4-a2ae-4513-8cb3-87e940aa29fa.PNG)

![IMG_9103](https://user-images.githubusercontent.com/11338480/197060876-96471908-48c7-4a00-a9a6-bb6d7bdafad1.PNG)

**Comment by CaptainJimo** [comment]
@lmarceau, these are all the steps i do to get the issue, but my phone is on ios 14.8.1. During the screen recording it doesn't happen consistently. And in the picture it shows that I've selected swiftkey, but default keyboard is shown
![D44561B5-0E9A-4E6A-A18A-DCFF9B537729](https://user-images.githubusercontent.com/22193710/197068410-a1d80672-398b-432b-b75f-80203e71740a.png)

https://user-images.githubusercontent.com/22193710/197068423-171c9d12-2f5e-462b-bd5f-a63953c79b2d.MP4
