### ISSUE TITLE
Learn more button in ETP settings page showing up in wrong places

### ISSUE THREAD

**Issue by lmarceau** [mozilla-mobile/firefox-ios#12179]
## Steps to reproduce
1. Go to the ETP menu
2. Click on Strict mode
3. Change back to standard mode

### Expected behavior
Learn more button is only where it should be

### Actual behavior
Learn more button is actually showing up in multiple places

### Device & build information
* Device: iPhone 11
* Build version: v106.0

### Notes
Attachments: 

https://user-images.githubusercontent.com/11338480/196790475-5647f7f2-5c75-495c-b6ce-d8413d5a2b62.MP4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5112)

**Comment by MincDev** [comment]
@lmarceau please review my closed PR, the merged request does not fully resolve the issue as the 'Learn more' button is now in the wrong section and not visible unless the 'Strict' mode is selected. According to the comments in code, this is expected to be in the first section of the UITableView, not the second one.

**Comment by lmarceau** [comment]
@MincDev I'll have a look later today 👍

**Comment by nayushi** [comment]
> @lmarceau please review my closed PR, the merged request does not fully resolve the issue as the 'Learn more' button is now in the wrong section and not visible unless the 'Strict' mode is selected. According to the comments in code, this is expected to be in the first section of the UITableView, not the second one.

When I saw the video and the More Info button was displayed at the bottom of the second section, I keep it there but is easy to fix that and let at the first section. Doesn't need to change that much, just a section == 0 validation inside of the viewForFooterInSection function and inside put all the title, attribute and button things :)
I'm going to open a PR with that and @lmarceau decides which one suits better to fix the issue. 
And a suggestion, if it is possible, on layout issues maybe upload a reference screenshot would help hehe 😄

**Comment by MincDev** [comment]
> Ok so I had a look, and this is the behavior we have in production v106.0.
> 
> 
> 
> ### Standard mode
> 
> ![IMG_9117](https://user-images.githubusercontent.com/11338480/198138977-1c0f3abe-2d63-4fe9-95ac-d40ba4530e4c.PNG)
> 
> 
> 
> ### Strict mode
> 
> ![IMG_9118](https://user-images.githubusercontent.com/11338480/198138996-6301b438-9638-4597-8d53-90934b4b6382.PNG)
> 
> 
> 
> The issue I described only happened when clicking from Standard to Strict and vice-versa while being in that menu (a floating button out of place appears). Tagging @dnarcese for confirmation this is the behavior we want to keep (having the learn more when clicking in strict mode only, not appearing in standard mode). 
> 
> 
> 
> 

@lmarceau if you click on the button it takes you to a page that explains what ETP is, so surely that should live in the first section and not the second one. People will have the default protection level unless they switch to strict, so they will never see the learn more. There was also a comment in the code itself that said "learn more button should only appear in the first section" and then the code did not actually cater for that. 

Besides this, if you have a look at the fix I implemented, I added the ability to add a learn more button to a SectionSetting instead of overriding it in the tableview function. This makes it easy to reuse the functionality if ever there need to be a button in a table footer again.

In any case, I don't mind my pull request remaining closed, but I do believe the learn more button should he in the first section as it relates to ETP and not the permission levels. 

Thanks for taking the time to check it out! :)

**Comment by MincDev** [comment]
> > @lmarceau please review my closed PR, the merged request does not fully resolve the issue as the 'Learn more' button is now in the wrong section and not visible unless the 'Strict' mode is selected. According to the comments in code, this is expected to be in the first section of the UITableView, not the second one.
> 
> 
> 
> When I saw the video and the More Info button was displayed at the bottom of the second section, I keep it there but is easy to fix that and let at the first section. Doesn't need to change that much, just a section == 0 validation inside of the viewForFooterInSection function and inside put all the title, attribute and button things :)
> 
> I'm going to open a PR with that and @lmarceau decides which one suits better to fix the issue. 
> 
> And a suggestion, if it is possible, on layout issues maybe upload a reference screenshot would help hehe 😄 

@nayushi Yeah, I also saw it in the video, however the content of that button relates to the first section and the code indicates that it was supposed to live in the first section but was not working properly. I think if @lmarceau agrees then maybe you can just make it go to the first section as it shouldn't actually be hidden. The second section should have no effect on whether it is shown or not.

**Comment by dnarcese** [comment]
@lmarceau I am good with showing Learn More in both sections

**Comment by lmarceau** [comment]
@MincDev I'll have a look into those PRs later this week or next week, thanks!

**Comment by lmarceau** [comment]
Ok so for reference, this is what we'll have in the ETP menu with the latest changes.

![Simulator Screen Shot - iPhone 11 - 2022-10-28 at 15 30 36](https://user-images.githubusercontent.com/11338480/198718494-1b1539fd-5f08-45ce-a6a9-ba2d74c3d6ac.png)
![Simulator Screen Shot - iPhone 11 - 2022-10-28 at 15 30 41](https://user-images.githubusercontent.com/11338480/198718497-2e2cc9b4-2fb6-4381-a009-9627443c6fa4.png)

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verifying as fix on 9000 (21167)

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verifying as fix on v108 (22078)
