### ISSUE TITLE
Freezing when pressing home button or pulling notification centre

### ISSUE THREAD

**Issue by dayvan-cowboy** [mozilla-mobile/firefox-ios#12194]
### Device & build information
* Device: iPhone 6S IOS 15.7
* Build version:  Firefox 106.0 (20303)
### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5132)

**Comment by dnarcese** [comment]
This is a result of #11776
