### ISSUE TITLE
Firefox Suggest Cannot be Turned Off

### ISSUE THREAD

**Issue by Hooxi-Fan** [mozilla-mobile/firefox-ios#12195]
Despite the << show search suggestions >> option being off, the search suggestion still shows up on the iOS app.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5133)

**Comment by csuciu** [comment]
I tried to reproduce on Firefox v106 and v107 on iOS 16.0.2 but wasn't able to. 
@Hooxi-Fan Can you please let us know what Firefox and iOS versions are you using.
![13_24_845Z](https://user-images.githubusercontent.com/1866605/197480146-0cde6d74-4558-4faa-8d1d-b94f5ae74cfc.jpeg)
