### ISSUE TITLE
phantom 'q' in search bar

### ISSUE THREAD

**Issue by CaptainJimo** [mozilla-mobile/firefox-ios#12193]
### Device & build information
* Device: iPhone se 2020 & iPhone 5s
* Build version: se=14.8.1 (18H107)    5s=12.5.5 (16H62)
### Notes  This issue has persisted for about 3-4 years spanning multiple iOS releases - 5s from iOS 10 to 12.5.5
and then SE 2020 from iOS 13 to 14.8.1
I believe this is a firefox issue, because it does not happen in any other app i have used
Attachments: 

https://user-images.githubusercontent.com/22193710/197360681-e421c642-0de0-4388-a825-d5d11c558a3d.MP4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5131)

**Comment by jr-johnson-support** [comment]
Hello, 

Do you have this issue in Firefox with any other Keyboard integrations? If that were the case we would be able to investigate this further. 

If the issue is only present when using SwiftKey, then we suggest you reach out to SwiftKey to investigate this issue further.

**Comment by CaptainJimo** [comment]
> Hello,
> 
> Do you have this issue in Firefox with any other Keyboard integrations? If that were the case we would be able to investigate this further.
> 
> If the issue is only present when using SwiftKey, then we suggest you reach out to SwiftKey to investigate this issue further.

No. The issues got resolved (for now) by updating my iPhone to ios 16.1 (from 14.8). But it was strange, because this same issue was previously appeared in ios 12 and later disappeared in the final 12.5 update
