### ISSUE TITLE
Cannot browse when on cellular data - NSURLErrorDomain

### ISSUE THREAD

**Issue by birdsarah** [mozilla-mobile/firefox-ios#12204]
## Steps to reproduce
Use Firefox when not on Wifi connection

### Expected behavior
Connect to websites

### Actual behavior
![IMG_0307](https://user-images.githubusercontent.com/1796208/197592806-84dc9024-5482-4316-9a06-9729e92a9283.png)

The internet connection appears to be offline
NSURLErrorDomain

### Device & build information
* Device: iPhone 12
* Build version: 20303

### Notes
This started for me on Firefox v105 and has persisted now I'm on v106.

When I'm on Wifi, there's no problem. When I'm on cellular data that's when I have a problem.

It is an LTE connection. You can ping me on slack (birdsarah) for details about my cellular provider if needed.

Try Again button has no effect.

All other browsers: Safari, DDG, Focus work just fine when Firefox iOS is in this state.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5138)

**Comment by nbhasin2** [comment]
@birdsarah Does

What about reinstalling the browser? Have you tried that?

I can't think of a particular reason why this might be happening that too only on LTE 🤔 

But we'll look into it.

**Comment by birdsarah** [comment]
Uninstalling and reinstalling had no effect (other than me having to log into anything).

**Comment by birdsarah** [comment]
I am on iOS 15.6.1

**Comment by MincDev** [comment]
@birdsarah can you check the Firefox settings in the system settings? It looks like it may be set to not use Cellular Data. ![image](https://user-images.githubusercontent.com/18619993/198393410-14806961-559d-4ca7-835b-fc409e40b6ce.jpeg)

**Comment by birdsarah** [comment]
You are 100% correct! Thank you @MincDev.

We could close this ticket, but I think it should be changed to a request for an improved user message.

Below is the message I am used to receiving if cellular data is off, which is why I didn't even think of this option.

![signal-2022-10-29-164603](https://user-images.githubusercontent.com/1796208/198853605-7f2e5623-4dda-47c1-887f-3951a74d6af7.jpeg)

**Comment by MincDev** [comment]
I have opened a pull request as per your suggestion @birdsarah [here](https://github.com/mozilla-mobile/firefox-ios/pull/12263)

Let's hope it gets approved and merged into the app. :)

**Comment by lmarceau** [comment]
I had a look and turns out this is something already built-in
![IMG_9167](https://user-images.githubusercontent.com/11338480/199076268-a9f91062-a608-4030-b22f-9cb023b0e9ce.PNG)

**Comment by lmarceau** [comment]
@dnarcese should we keep this issue open or close it?

**Comment by MincDev** [comment]
@lmarceau can you advise how this is triggered as I can't seem to get the alert on my firefox browser. Currently I get the same as @birdsarah where it only shows the webpage indicating that connection is not possible. There is no alert. 

My implementation monitors for changes to the CoreTelephony cellular data and if it identifies that cellular data is "restricted" it will present the user with an alert, allowing them to click settings which will take them to the iOS settings to turn cellular data on.
