### ISSUE TITLE
Firefox prompts to download instead of open links

### ISSUE THREAD

**Issue by mconnormoz** [mozilla-mobile/firefox-ios#12202]
## Steps to reproduce
No fixed STR yet, seems to trigger after some period of time.  Occasionally clicking a different link will load properly, but generally the behaviour is stuck until the app is closed.  Happens across sites as well.

### Expected behavior
Links open like a regular web browser.

### Actual behavior
Prompted to [`download`|[url](![48F463FF-0709-412F-AEB7-53FA86A45E43](https://user-images.githubusercontent.com/1065799/197591429-e3e4398b-6f55-40d8-9bcc-fd2071aa4838.png])) the linked page.

### Device & build information
* Device: iPad Air 4th Gen + Magic Keyboard
* Build version: Firefox 106

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5136)

**Comment by dnarcese** [comment]
@mconnormoz could you please attach a screen recording if you are able to reproduce again?

**Comment by clemlesne** [comment]
Maybe related to https://github.com/mozilla-mobile/firefox-ios/issues/1405.

**Comment by clemlesne** [comment]
Maybe related to https://github.com/mozilla-mobile/firefox-ios/issues/14053.
