### ISSUE TITLE
Add settings page to toggle b/w WKWebview and Gecko

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#12210]
Add a settings page with tableview 

* Add view controller for settings page in a table view format 
* Add a toggle to the settings page to Enable / Disable the GeckoView 
* Also, add an empty view controller to be shown if a user toggles `Enable GeckoView` in the settings page

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5144)

**Comment by lmarceau** [comment]
@foss- no release, this is for a secondary project not in this repository.

**Comment by foss-** [comment]
Thanks, can't wait until EU clarifies situation and we can have proper Gecko Firefox on iOS.

**Comment by gutley** [comment]
Congratulations @lmarceau on your new-found fame :
https://www.theregister.com/2023/02/07/mozilla_google_apple_webkit/

**Comment by krystian3w** [comment]
For me, it is better to consider implementing add-ons rather than such a small switch, which does not guarantee that they will be easily available with iOS 17.4 or 18.
