### ISSUE TITLE
Performance Problem around Hamburger Menu

### ISSUE THREAD

**Issue by mgaudet** [mozilla-mobile/firefox-ios#12235]
## Steps to reproduce

Have Firefox iOS open for a while, then press hamburger menu button

### Expected behavior

Hamburger menu appear instantaneously 

### Actual behavior

Long delay in seeing appearance of hamburger menu -- sometimes tens of seconds. 

### Device & build information
* Device: iPhone 13 Pro
* Build version: 106.0 (20303) 

### Notes

Unfortunately I don't have a true STR; the problem occurs intermittently. When it happens it happens consistently for a while, but eventually stops. 

I suspect something is burning CPU too, as I've noticed my battery life is worse than usual, and the battery info panel is pointing the finger at Firefox iOS (of course, it's my most used app... so hard to say if it's _actually changed_). 

Attachments: 

In the below video I hit the hamburger button within a second of the start of the video, then it takes almost 5 seconds for the menu to appear. This is just the example of I have a screen recording of; actual examples have been worse for me. 

https://user-images.githubusercontent.com/2906003/198077260-d573dbbc-c1cf-4afe-bdbb-327ee065fefd.mov

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5159)

**Comment by mgaudet** [comment]
(Actually - I may be misremembering; that recording might actually be me having started recording _after_ hitting the button; I just noticed the blue button state re-watching it)

**Comment by lmarceau** [comment]
I think this duplicates https://github.com/mozilla-mobile/firefox-ios/issues/12234

**Comment by mgaudet** [comment]
Aha. You might be right on that: That gives me an STR. 

1. Kill Firefox. 
2. Open Firefox. 
3. Tap address bar, showing home page (with tiles)
4. Hit jump back in. (at this point, testing hamburger menu, and it's fast) 
5. Click a link. let page load.
6. Hit hamburger menu again: Hugely slow.

**Comment by mgaudet** [comment]
This video is a perfect example of the lag I see, from the above STR.

https://user-images.githubusercontent.com/2906003/198098941-ffdfbc5f-7508-444d-9cd5-a0e1f4955a53.mov

**Comment by marycatharinemartin** [comment]
I have also had this problem on my iPhone X, iOS 15.6.1, FireFox v106.0.

**Comment by jr-johnson-support** [comment]
CX team saw 16 users who noted this or a similar issue over iOS app store since Oct 28th. I'll update if we continue seeing users report this.

**Comment by NoahTheDuke** [comment]
If you need more reports, I see this as well.

**Comment by jr-johnson-support** [comment]
> If you need more reports, I see this as well. If you don't, my apologies for piling on.

if you can consistently reproduce this Noah, Drop us a screen recording.

**Comment by NoahTheDuke** [comment]
https://user-images.githubusercontent.com/603677/199580416-77613f67-b275-42cd-b907-fa9d847a7e73.MOV

I press the hamburger button after a reload and it takes two seconds. Then i click a link and press the hamburger button and then wait many seconds. During this time, I can scroll and interact with the site (including follow links), and pressing the hamburger button again doesn't make it appear any faster but does queue it reappearing.

**Comment by jr-johnson-support** [comment]
Thanks for the video Noah.
