### ISSUE TITLE
Firefox keep asking me cookies on google

### ISSUE THREAD

**Issue by M3MBAH** [mozilla-mobile/firefox-ios#12232]
Hello ! 

Please help me, this bug is so anoying ^^

## Steps to reproduce
Open firefox on IOS, the google page ask for cookie and privacy

Closing the tab, and opening a new tab, then google doesn't ask me for cookie etc.

Closing agin the tab, and I have the dark mode activated that I want.

### Expected behavior
So, I have to close 3 times to get the right configuration I want. (Google dark mode + without cookie asking, and logged in my google account).

### Actual behavior
Google asking for cookie and no dark mode and not logged in my google account...

### Device & build information
* Firefox IOS 106.0 (20303) on IOS 16.0
* Iphone 12 128GO

### Notes
I have uninstalled Firefox on IOS.
Reinstalled it, if I don't connect my firefox account for sync, the problem is not present.

If I connect my firefox account, the problem is present

Attachments: 

I have made a video I wou want : https://we.tl/t-v2K0I6IF1p

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5156)

**Comment by besil** [comment]
Same here, it’s annoying. I also noticed that at startup I’m not logged into my google account.
If you wait a few seconds and just hit refresh page, Firefox correctly loads both profile and cookies consent

**Comment by SimonBasca** [comment]
I thinks this might be the same issue as https://github.com/mozilla-mobile/firefox-ios/issues/12279

**Comment by skatsikeas** [comment]
It seems that there were some cookie related fixes on v.112 (#12740) but unfortunately this bug is still occurring at least for me.

It actually happens on the first tab that is opened after Firefox is started. So if I close Firefox with no tabs, then launch it again, the tab that opens does not load my cookies, if I open a second tab it load it properly. Another way of fixing this is by refreshing the page some times.

**Comment by skatsikeas** [comment]
I am back with a further update. I have reasonable suspicions that this problem occurs only when the "close private tabs" option (that closes the private tabs when leaving private mode) is enabled. Can somebody try?

What I did was:
1. I removed Firefox from my iPhone (iOS 16.4.1)
2. Re-installed Firefox v.112
3. Did not sign it to Sync
4. Opened some pages (e.g. Google.com, Google.gr) and accepted cookies
5. I signed in to my Sync account and I enabled the "Strict" protection from trackers

(All the above might be irrelevant but I report them just for completeness)

Then when I tried closing Firefox with the "close private tabs" enabled, the first tab opened after Firefox starts has this issue, if I disable it, it does not occur when I open Firefox.

I then tried re-enabling the "close private tabs" option, the issue occurs on the first tab.

**Comment by M3MBAH** [comment]
That worked for me !!!

Big thanks 🗡️

**Comment by wvreeven** [comment]
That works for me too. I didn't even have to reinstall Firefox. Just going to Settings and disabling "close private tabs" was enough for me.

**Comment by mcfilib** [comment]
this workaround does not work for me

**Comment by mcfilib** [comment]
is fixing this is a in the near future a priority?
