### ISSUE TITLE
Firefox hangs after restoring from background

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#12244]
## Steps to reproduce
1. Launch Firefox
2. Background Firefox
3. Restore Firefox to foreground
4. Scroll the homepage
5. Open the menu
6. Scroll the settings menu
### Actual behavior
- Firefox hangs for several seconds after restoring from background (~10 seconds).
### Device & build information
* Device: iPhone SE 1st generation (15.7)
* Build version: 106.1 (20911)
### Notes
- This behavior was also observed on iPhone 6s (15.7). 
- Firefox also hangs on iPhone 12 Pro (16.0.2) but the slow performance time is smaller (~2 seconds)
 Attachments: 

[Untitled.mp4.zip](https://github.com/mozilla-mobile/firefox-ios/files/9879947/Untitled.mp4.zip)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5164)

**Comment by SimonBasca** [comment]
@dnarcese 
- I was unable to reproduce this on v106.
- The issue still happens on v106.1 with only 2 rows of shortcuts but the hang time is much smaller (~1 second).

**Comment by ikt** [comment]
I have this issue, it's so bad that when I go into my email to get the code to sign into this website when I come back Firefox has crashed and the "enter your device code" page shows a 404, so I'm typing this on my pc.

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Marking as verified fix on v107.0 (21907)
