### ISSUE TITLE
Critical performance problems in v106

### ISSUE THREAD

**Issue by tirw** [mozilla-mobile/firefox-ios#12260]
Major delays for adding, closing and switching between tabs, and slow URL suggestions make the browser unusable after the v106 update. Screencap attached, all user inputs were immediate. The delays don’t appear after a force close right away, but reproducible consistently after a short while. Possibly related to the app getting backgrounded. 

Firefox v106, ~100 Tabs, iOS 15, A14 chip

https://user-images.githubusercontent.com/8298517/198750080-25056aa7-6b5d-40f0-8db5-d654c2a4b6e1.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5171)

**Comment by ocha** [comment]
might be related - my phone heats up and battery starts go down fast when using FF 106.

**Comment by lmarceau** [comment]
Relates to https://github.com/mozilla-mobile/firefox-ios/issues/12244 I believe

**Comment by aakay** [comment]
can confirm on an iphone x. it hangs up regularly, uses a lot of power and is very slow.

**Comment by lmarceau** [comment]
@tirw did you only had homepage tabs? I see a bunch of homepage in the video but wondering if there was some normal tabs in there too?

**Comment by eku1s** [comment]
I can confirm I’m also seeing similar issues using an iPhone XS. For me particularly, it’s performance and the app seems to either get quit by memory management or crash whilst open in the background. Sometimes just opening the app switcher causes it to crash so I’m not convinced this is wholly RAM related. Some sites are also unusable in Firefox - particularly ones which are JS heavy, like shopping sites and using filters. Starting to consider moving back to Safari until this is fixed, as it’s becoming unusable.

**Comment by idleherb** [comment]
FF 106.1 freezing randomly throughout the day on iPhone XR with iOS 15.6.1. I have to use the app switcher to kill it, works normally  for a while after starting it again.

**Comment by lmarceau** [comment]
Hello @idleherb, would you mind trying out the 106.2 version that was just released to tell us if you experience the same issue? Thank you!

**Comment by chris-chtrusch** [comment]
I can confirm the freezes on iOS 15.7.1/SE 1st gen., occur seemingly at random and last a few seconds. This is still in 106.2.

**Comment by mpepping** [comment]
Still an issue with v106.2 indeed.

**Comment by pezholio** [comment]
Yep, this is still an issue with 106.2. Seems especially prevalent when using a password manager (i.e 1Password)

**Comment by lmarceau** [comment]
@edaniels You can join the testflight beta [here](https://testflight.apple.com/join/JdsubPZs). Thank you!

**Comment by lmarceau** [comment]
You can send any logs to my work email address lmarceau@mozilla.com. Thank you!

**Comment by chris-chtrusch** [comment]
So far, I cannot reproduce this issue on v108.0 anymore.

**Comment by lmarceau** [comment]
We released some bugfixes related to this, but our current state on this is that there's multiple cause to the same symptoms. So some occurrences of the issue could be improved, while for some users there's no improvements. Rest assured that we're pursuing work to improve the app stability

**Comment by xTobyPlayZ** [comment]
Seems like it's mining crypto in the background or some shit

**Comment by Smartich0ke** [comment]
I have also had terrible performance issues in Firefox iOS on my iPhone 7 (ioS 15.7.1). 


The most problematic issue is that he keyboard very frequently locks up and freezes for at least 5 or so seconds at a time. I also have had regular crashes, slow performance when browsing websites, jerky/laggy scrolling, and I have noticed that my phone gets hotter.
I have had these issues for over roughly 2 months with no improvement from recent updates. 

I really love firefox, but the fact that something so frustrating and critical has been left unfixed for months is making me consider ditching the iOS app.

**Comment by lmarceau** [comment]
@Smartich0ke Hello! Thanks for your input. I assume when you talk about recent updates that you are on v109 (this can be checked at the bottom in the settings)? 

A couple of questions that could help us:
- How many tabs do you have opened? (is it more than infinite?)
    - If you have the possibility (do not feel obligated at all), does deleting your tabs make the application work normally?
- Are you logged into a sync account?
    - If so, does logging off makes your app works normally?

Thank you for your time.

**Comment by kvark** [comment]
For my case, it's 5-10 tabs, and I'm logged into sync. Will try your suggestions. Fully agree that this is somewhat critical and can easily sway people to switch browsers, unfortunately.

**Comment by Smartich0ke** [comment]
@lmarceau Yes I'm on v109.0. It always happens no matter what, whether its 5 tabs or 80. And I'm also logged into a sync account. I'll see how it goes when I'm logged out. Thanks for the help!

**Comment by Smartich0ke** [comment]
Unfortunately disconnecting from my sync account didn't seem to have much improvement.

**Comment by SimonBasca** [comment]
@Smartich0ke @kvark could you please share a screenshot of your home screen and your homes screen settings?

**Comment by Smartich0ke** [comment]
@SimonBasca Sorry I wasn't quite sure what you wanted but is this what you mean?
![image](https://user-images.githubusercontent.com/41409702/216012027-b51415d9-df46-4ca5-b8cb-8bf23da5f283.png)
![image](https://user-images.githubusercontent.com/41409702/216012108-327ac489-2582-415e-acf6-81102d1ca4e0.png)

**Comment by Smartich0ke** [comment]
Yep it so far I'm not getting any of the performance issues. Thanks to the developers for fixing this!
