### ISSUE TITLE
Firefox app crashes when try to open

### ISSUE THREAD

**Issue by Zaneehs** [mozilla-mobile/firefox-ios#12273]
## Steps to reproduce
Open Firefox 
### Expected behavior
Firefox stays open 
### Actual behavior
Firefox crashes immediately 
### Device & build information
* Device: iPhone 13
* Build version: not sure, running ios16.0.3
### Notes
Attachments: 
Firefox seems to work ok when I open a link from a different app and it automatically opens Firefox. But when I open the app from my home page it crashes.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5179)

**Comment by SimonBasca** [comment]
@Zaneehs could you please go to Firefox settings and scroll to the bottom and let us know the app version? Also if you are able to do a screen capture of the issue it would be very helpful.

**Comment by Zaneehs** [comment]
Hi,

It’s version 106.1 (most up to date in the App Store). I’m unable to open the app, here’s a video of what happens.

I’ve tried deleting the app and reinstalling but the issue persists.

(sent from mobile)

**Comment by SimonBasca** [comment]
@Zaneehs after clean installing 106.1 from the app store, does the app crashes on first launch(before seeing the on-boarding slides) or after doing something more specific?

**Comment by lmarceau** [comment]
@Zaneehs Also, on top of Simon's question - the video wasn't attached (it sadly doesn't work from an email to attach a file). Could you attach the video by going directly on the Github website? Thank you!

**Comment by glottisfaun0000** [comment]
This has been happening to me as well and after reinstalling it seems that I only get the crash behavior after signing in to my Firefox account on the app

**Comment by Zaneehs** [comment]
Ah yes, the app works fine for me as long as I do not sign in

**Comment by abodea** [comment]
Hello, @Zaneehs can you please check if your device time zone is set to automatic?

**Comment by Zaneehs** [comment]
Yes, it is set to automatic
S H E E N A  Z H A N G
she / her / hers
......................
RA, LEED AP BD+C, LFA
7 0 6 . 2 5 4 . 2 6 8 9

**Comment by pharan** [comment]
This is also happening to me but on an iPad Pro.
I try to open the app but it crashes shortly (about 1 second) after it opens.

iPadOS 16.1
Firefox 106.1

I've yet to try uninstalling and reinstalling.

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

We were unable to reproduce any crash on latest v110 (27761) following the STR.
