### ISSUE TITLE
Make sure wallpaper onboarding only shows up when on home

### ISSUE THREAD

**Issue by topotropic** [mozilla-mobile/firefox-ios#12275]
I updated Firefox and got the wallpaper selection overlay on a site. It would be great if we could make sure the selection overlay only shows up when home is in the background. Thanks!

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5181)

**Comment by data-sync-user** [comment]
➤ Daniela Arcese commented:

Let’s timebox and see if we can reliably reproduce.

**Comment by data-sync-user** [comment]
➤ Roux Buciu commented:

Was not able to reproduce reliably. Also, the check for the selector showing up already checks whether or not the homepage is showing, which would be the solution to this bug.
