### ISSUE TITLE
Typing in URL into a brand new tab consistently loses the first character or three

### ISSUE THREAD

**Issue by escapewindow** [mozilla-mobile/firefox-ios#12280]
## Steps to reproduce

iPad, magic keyboard: command-T to open a new tab. Type in a URL, e.g. `google.com`. Note that the address bar shows `ogle.com`. If you hit return you go to `ogle.com` which thankfully redirects you to noaa.gov.

### Expected behavior

If I type `google.com`, address bar shows `google.com` and hitting return sends you to google.com

### Actual behavior

The url loses the first character or three, e.g. google.com -> ogle.com

### Device & build information
* Device: iPad Pro M2 2022 11”
* Build version: Firefox 106.0 20303
### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5193)
┆Link To Issue: https://mozilla-hub.atlassian.net/browse/FXIOS-5193

**Comment by mgaudet** [comment]
I have a family member who has complained about this too; they have yet to be able to get a screen recording however.

**Comment by dnarcese** [comment]
@escapewindow is the behaviour you are seeing the same as #10054

**Comment by escapewindow** [comment]
> @escapewindow is the behaviour you are seeing the same as #10054?

Yes, this is probably the same issue.

**Comment by escapewindow** [comment]
Closing as a dup of #10054.
