### ISSUE TITLE
Inactive tabs become active after updating FF

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/firefox-ios#12287]
## Steps to reproduce
1. Install v105 and access 3 or more tabs.
2. Wait until they become inactive for ~14 days (I used the time manipulation).
3. Update to v106.
4. Open the tab tray to observe the inactive tabs.
### Expected behavior
Inactive tabs should remain inactive after any update.
### Actual behavior
Inactive tabs become active after updating FF.
### Device & build information
* Device: iPhone 13 Pro (15.1.1).
* Build version: 105, 106, 107.
### Notes
Please note that I used the 105 106 but it happens after any update. 
Attachments: 

https://user-images.githubusercontent.com/42831109/199482727-bd94961c-de49-45af-a20c-956f1e12953e.mov

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5197)
┆Link To Issue: https://mozilla-hub.atlassian.net/browse/FXIOS-5197

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

This issue is blocked by https://mozilla-hub.atlassian.net/browse/FXIOS-5223 ( https://mozilla-hub.atlassian.net/browse/FXIOS-5223|smart-link )

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Marking as verified fix on v107 (21907)
