### ISSUE TITLE
Capture memory warnings in Sentry

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#12291]
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5198)
┆Link To Issue: https://mozilla-hub.atlassian.net/browse/FXIOS-5198

**Comment by lmarceau** [comment]
PR was https://github.com/mozilla-mobile/firefox-ios/pull/12292
