### ISSUE TITLE
Firefox userAgent is returning Safari userAgent on iPad

### ISSUE THREAD

**Issue by dresosh** [mozilla-mobile/firefox-ios#12297]
## Steps to reproduce
navigator.userAgent

### Expected behavior
return fxios in userAgent string

### Actual behavior
returns safari in userAgent string for ipad

### Device & build information
* Device: ipad
* Build version: Firefox 106.0
### Notes
userAgent on mobile device is returning fxios for firefox but safari on ipad where chrome is returning crios on ipad. 
userAgent needs to be updated for firefox on ipad. 
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5200)
┆Link To Issue: https://mozilla-hub.atlassian.net/browse/FXIOS-5200

**Comment by lmarceau** [comment]
Hello @dresosh, this is expected as we serve desktop safari UA to have a broader compatibility with websites. I'll close this issue. Thanks!
