### ISSUE TITLE
Sent tabs from desktop are not opened on iOS if the user taps to open the tab from the notification

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/firefox-ios#12315]
Source: https://bugzilla.mozilla.org/show_bug.cgi?id=1799097
## Precondition
`Be connected to Sync with desktop and iOS device;`
## Steps to reproduce
1. Have iOS screen locked or unlocked but without Nightly opened;
2. From desktop, right-click on a tab and select the “Send tab to device” option;
3. Choose the iOS device and sent the tab to it;
4. Click on the received notification on iOS;
### Expected behavior
The received tab is successfully opened in Firefox.
### Actual behavior
The received tab is not opened, Firefox is opened but with the focus on the URL bar.
### Device & build information
* Device: `iPhone 13 Pro (15.1.1).`
* Build version:` 9000 (21615).`
### Notes
- If the device is unlocked and FF is in Foreground, the sent tab is successfully received.
- This is not reproducible on the latest Firefox 106.1 Rc on iOS.
Attachments: 

https://user-images.githubusercontent.com/42831109/200005227-df74e67c-45b4-4801-ba15-ae937995392c.mov

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5211)
┆Link To Issue: https://mozilla-hub.atlassian.net/browse/FXIOS-5211

**Comment by lmarceau** [comment]
@abodea Is this reproducible also on v107.0? Wondering when the issue would have got in.

**Comment by dnarcese** [comment]
@abodea can you please retest this on the latest 107 build?

**Comment by csuciu** [comment]
@lmarceau @dnarcese  The issue in not reproducible on latest v107.0 (21907). 
I was able to reproduce it only on v9000.

**Comment by data-sync-user** [comment]
➤ Nishant Bhasin commented:

We should close this if its not reproducible.
