### ISSUE TITLE
Some images on web-pages have wrong colors

### ISSUE THREAD

**Issue by arabesc** [mozilla-mobile/firefox-ios#12326]
## Steps to reproduce
Open some web-page, e.g.:
[https://www.yamaha-motor.eu/gb/en/products/motorcycles/adventure/](https://www.yamaha-motor.eu/gb/en/products/motorcycles/adventure/)

### Expected behavior
![IMG_4589](https://user-images.githubusercontent.com/2709027/200141204-bd168b23-8b9a-4008-b6cd-07b45512c351.jpg)

### Actual behavior
![IMG_4588](https://user-images.githubusercontent.com/2709027/200141212-8ba097ae-db65-4183-a3e7-389a64c5ca77.jpg)

### Device & build information
* Device: iPad Pro (12.9-inch) (5th generation), iPadOS 16.1 (20B82)
* Build version: Firefox 106.1 (20911)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5213)
┆Link To Issue: https://mozilla-hub.atlassian.net/browse/FXIOS-5213

**Comment by lmarceau** [comment]
Hello! Thanks for opening this ticket. We're tracking this already with https://github.com/mozilla-mobile/firefox-ios/issues/5819 so I'll close this one.
