### ISSUE TITLE
Firefox (iOS) app keeps crashing

### ISSUE THREAD

**Issue by Mine-Menace** [mozilla-mobile/firefox-ios#12344]
## Steps to reproduce
Open the app

### Expected behavior
The app not to crash

### Actual behavior
The app crashes within approximately 2 seconds of opening it

### Device & build information
* Device: iPhone SE (generation 2)
* Build version: iOS 16.1; Firefox version 106.2
### Notes
To fix this, I have done the hard shutoff on my iPhone, given it a software update, and uninstalled and reinstalled the Firefox app. None of this has changed anything. Sometimes it stays open for a bit longer (especially if I haven't tried to open the app for several minutes), but it crashes as soon as I attempt to do anything.
Attachments: 
[Client-2022-11-08-101327.ips.zip](https://github.com/mozilla-mobile/firefox-ios/files/9962894/Client-2022-11-08-101327.ips.zip)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5225)
┆Link To Issue: https://mozilla-hub.atlassian.net/browse/FXIOS-5225

**Comment by lmarceau** [comment]
Thanks @Mine-Menace for the logs, this helps a lot. This could relate to the crash from https://github.com/mozilla-mobile/firefox-ios/issues/12332 with the database lock.

```
0   Shared                        	       0x108492cb0 closure #1 in Deferred._fill(value:assertIfFilled:) + 236
1   Shared                        	       0x108492cb0 closure #1 in Deferred._fill(value:assertIfFilled:) + 236
2   Shared                        	       0x108488cdc partial apply for closure #1 in LockProtected.withWriteLock<A>(block:) + 92
3   Shared                        	       0x1084880fc CASSpinLock.withWriteLock<A>(block:) + 164
4   Shared                        	       0x108488c50 LockProtected.withWriteLock<A>(block:) + 156
5   Shared                        	       0x108491ee8 Deferred._fill(value:assertIfFilled:) + 476
6   Shared                        	       0x10841ddd4 CancellableDeferred.fill(_:) + 40
7   Sync                          	       0x107edc6ec closure #1 in SQLiteHistory.retrieveTopSiteSQLiteHistoryFaviconImage(faviconURL:) + 284
8   Shared                        	       0x10847ed60 partial apply for closure #1 in ImageLoadingHandler.getImageFromCacheOrDownload(with:limit:completion:) + 72
9   Shared                        	       0x10847fabc partial apply for closure #1 in ImageLoadingHandler.downloadImageOnly(with:limit:completion:) + 184
10  KingfisherDynamic             	       0x106954240 partial apply for closure #1 in ImageLoadingProgressSideEffect.onDataReceived(_:task:data:) + 28
```

**Comment by sobajic** [comment]
Just came here to post the same issue 

### Device & build information
    Device: iPhone 12 mini
    Build version: iOS 16.1; Firefox version 106.2

[Client.ips.zip](https://github.com/mozilla-mobile/firefox-ios/files/9964023/Client.ips.zip)

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

We were unable to reproduce any crash on latest v110 (27761) following the STR.
