### ISSUE TITLE
Website shows bottom toolbar when scrolling

### ISSUE THREAD

**Issue by thatswinnie** [mozilla-mobile/firefox-ios#12343]
## Steps to reproduce
1. Open https://montreal.lufa.com/en/marketplace/
1. Start scrolling

### Expected behavior
Bottom toolbar hides and stays hidden for as long as you are scrolling

### Actual behavior
Bottom toolbar is showing up whenever you get to a new category.

### Device & build information
* Device: iPhone 14 Pro
* Build version: 106.2

* 

### Notes
This might be related to the website loading the content for the new category.

Attachments: 
https://user-images.githubusercontent.com/4530/200610905-ad44bb81-0fb7-4929-82e1-72e1e98c6535.MP4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5224)

**Comment by data-sync-user** [comment]
➤ Matthew Reagan commented:

Read through Sorin Paraipan 's notes from https://mozilla-hub.atlassian.net/browse/FXIOS-6590 ( https://mozilla-hub.atlassian.net/browse/FXIOS-6590|smart-link ), will try implementing the proposed solution there

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v9000 (35002), with iPhone SE (16.6.1).

To be rechecked once the v120 build is officially released.

**Comment by data-sync-user** [comment]
➤ Stefan Vladut commented:

one of the changes related to this task created https://mozilla-hub.atlassian.net/browse/FXIOS-7497 ( https://mozilla-hub.atlassian.net/browse/FXIOS-7497|smart-link ), will revert that part to fix the regression
