### ISSUE TITLE
Previously opened tabs are closed after updating from 106.2 (21661) to 107 (21761)

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#12340]
## Steps to reproduce
1. Install 106.2 (21661)
2. Open a few tabs and load a few pages
3. Update to 107.0 (21761)
4. Launch Firefox
### Expected behavior
- Previously opened tabs should be displayed.
### Actual behavior
- Previously opened tabs are closed.
### Device & build information
* Device: iPad Pro / iPhone 12 Pro 
* Build version: 107 (21761)
### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5223)
┆Link To Issue: https://mozilla-hub.atlassian.net/browse/FXIOS-5223

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

107(21746) → first bad build
107(21688) → last good build

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Marking as verified fix on v107.0 (21907)
