### ISSUE TITLE
Top sites icon incorrect

### ISSUE THREAD

**Issue by mgaudet** [mozilla-mobile/firefox-ios#12356]
## Steps to reproduce

Unclear; I did delete a shortcut / top site icon, but I think this predates the icon issue. 

### Expected behavior

Site icons match the site. 

### Actual behavior

Site has incorrect icon.

### Device & build information
* Device: iPhone 13 Pro, iOS 16
* Build version: Firefox 106.1

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5230)

**Comment by lmarceau** [comment]
Hi @mgaudet, do you have a screenshot of the issue?

**Comment by dnarcese** [comment]
@mgaudet Can you also estimate how often this is happening for you?

**Comment by mgaudet** [comment]
Correct: (except globe and mail icon)
![B8691F0F-E5F5-4862-AA23-2370FF6B48CA](https://user-images.githubusercontent.com/2906003/201207692-b8915f4b-5178-4bab-8f33-c5fdf84043ac.jpeg)

Incorrect: 
![0EA801F9-6878-4369-820F-D77A13075B18](https://user-images.githubusercontent.com/2906003/201207580-3379a107-0445-4535-bafa-7df11d57d4a7.png)

as far as frequency, I would say in the last two weeks I have seen this 3-4 times.

**Comment by dnarcese** [comment]
@SimonBasca can you see if this is still an issue on 110?

**Comment by lmarceau** [comment]
@mgaudet 110 was released, could you check if this is still an issue? We've made changes to those icons in the app in that release.

**Comment by mgaudet** [comment]
All my icons are currently correct

**Comment by lmarceau** [comment]
@SimonBasca I think we can close this issue 🙏
