### ISSUE TITLE
Top site icon not showing black background

### ISSUE THREAD

**Issue by eliserichards** [mozilla-mobile/firefox-ios#12365]
## Steps to reproduce

Prereqs: I have dark mode enabled;  I have it set to go to the Home Screen whenever I open the browser; I have a homescreen background set

1. Open Firefox. See the default top sites on the homescreen. 
2. YouTube top site icon doesn't have the black bounding box around it like the other top sites do: 

![image](https://user-images.githubusercontent.com/43795363/201540739-8c7064c4-0c62-4914-b964-6a63e90a46f5.jpeg)

3. When you switch apps and go back, different top sites now have the same problem (I can't repro this consistently)

![image](https://user-images.githubusercontent.com/43795363/201540856-919911f8-088f-46b8-843f-91f1da7ac42d.jpeg)

4. When scrolling up and down on the homescreen it has the same problem (see YouTube and Google) (I also can't repro this consistently)

https://user-images.githubusercontent.com/43795363/201540989-80762126-df5c-4fd2-aea1-dee85aae2396.MOV 

### Expected behavior
All top sites look the same and do not change. 

### Actual behavior
- A single top site doesn't have the same black box as the rest of them. 
- Navigating away to another app and back sometimes makes the icon bounding boxes change. 
- Scrolling up and down on the homescreen sometimes makes the icon bounding boxes change. 

### Device & build information
* Device: 12 Pro, iOS 16.0.2
* Build version: Firefox 106.1 (20911)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5241)

**Comment by eliserichards** [comment]
I think this might be related to #12355, since I could only reproduce it when I got into the state where I see the default top sites 🤔

**Comment by dnarcese** [comment]
@thatswinnie was this something you recently fixed?

**Comment by thatswinnie** [comment]
@dnarcese @yoanarios fixed this. The fix is planned to go out with v108.

**Comment by eliserichards** [comment]
Awesome! I haven't been able to repro it since then, so I think this is safe to close 😄
