### ISSUE TITLE
Tabs not properly restored after crash

### ISSUE THREAD

**Issue by p4checo** [mozilla-mobile/firefox-ios#12364]
## Steps to reproduce

1. Have multiple tabs opened
1. Somehow make Firefox crash
1. Reopen Firefox
1. Tap **Okay** on the "Well ,this is embarrassing" crash alert:

![Screen Shot 2022-11-13 at 17 16 34](https://user-images.githubusercontent.com/1391324/201534849-65bd9b8e-77bd-4f83-90bc-11770fbab5c9.png)

### Expected behavior

- Firefox restores tabs 😌

### Actual behavior

- Firefox doesn't restore tabs 😭

### Device & build information
* Device: iPhone 13 Pro, iOS 16.0.3
* Build version: 106.1 (20911)

### Notes

Needless to say this is extremely frustrating... I had nearly 40 tabs opened in Firefox, some months old. Gladly I was able to recover most of them on my Mac's FF by not letting the Mac connect to the internet to sync the now 0 tabs from my device...  If I had not done this and let it sync, my tabs would have been permanently lost (or I would have to dig thru months of history to find them...)

The restore tabs process is IMO the most important feature following a crash, so I don't understand how it is completely broken, and there doesn't seem to be a way to restore them via settings or something (e.g. have a backup sessionstore.js or whatever for these cases that could be explicitly loaded by users as a last measure). Thankfully FF Sync "history" saved the day.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5240)

**Comment by data-sync-user** [comment]
➤ Roux Buciu commented:

Still actively working on this. Not fully done but I’m most of the way there… I think.
