### ISSUE TITLE
Keep dropping connection

### ISSUE THREAD

**Issue by Smokey365** [mozilla-mobile/firefox-ios#12363]
Hey there! Thanks for using Firefox!

If you are having issues with using Firefox make sure to check https://support.mozilla.org/en-US/products/ios first

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5239)

**Comment by lmarceau** [comment]
@Smokey365 Could you please describe the bug you're experiencing? Your title refer to "keep dropping connection"? How and when does that happen, on which device/build?
