### ISSUE TITLE
Context menu opens under the contents of a bookmark toolbar folder.

### ISSUE THREAD

**Issue by BaptisteUrgell** [mozilla-mobile/firefox-ios#12368]
## Steps to reproduce
1. Open Firefox Browser.
2. Click the menu button on the right side of the toolbar.
3. Click the full screen button.
4. Click View in the Firefox menu bar at the top of the screen. 
5. Go down to the Toolbars menu and select Bookmarks Toolbar.
6. Click the Always Show. 
7. Create a folder in the Bookmarks toolbar.
8. Add a Bookmark in the folder.
9. Open the folder from the Bookmarks toolbar and right click (Only tested with the pad) on the bookmark.

### Expected behavior
The context menu opens over the contents of the folder in full screen.

### Actual behavior
The context menu opens under the contents of the folder in full screen.

### Device & build information
* Device: MacBook Pro 13.0 (22A380)
* Build version: 106.0.5 (64 bits)

### Notes
Attachments: 
<img width="389" alt="full screen mode" src="https://user-images.githubusercontent.com/72963042/201676814-d2ddbeec-254e-40f7-9760-bfc3d0860c94.png">
<img width="389" alt="not full screen mode" src="https://user-images.githubusercontent.com/72963042/201676852-535a0d88-957c-4f7f-8869-1cc951475d22.png">

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5243)

**Comment by dnarcese** [comment]
Hi, this is a bug in Firefox Desktop so I have moved it here https://bugzilla.mozilla.org/show_bug.cgi?id=1803844. You can login to Bugzilla with your Github account and click Follow to get updates or provide more detail.
