### ISSUE TITLE
 [iPad] Top tabs and url theme breaks after enableing night mode

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#12374]
## Steps to reproduce
1. Have theme set to automatic
2. Enable Night mode
3. Background the app
4. Restore the app
### Actual behavior
- Top tabs and url theme breaks
### Device & build information
* Device: iPad Pro 15.7 
* Build version: 9000 (21972)
### Notes
Attachments: 

![image](https://user-images.githubusercontent.com/32130829/201683118-ef53f723-7c08-4f00-a2ed-5d35963f1fdd.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5246)

**Comment by data-sync-user** [comment]
➤ Catalin Suciu commented:

No longer reproducible on v108.0 (23470). Closing as fixed.
