### ISSUE TITLE
Fix Authenticator crash

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#12372]
!image-20221114-141112.png|width=908,height=190!

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5245)

**Comment by lmarceau** [comment]
I think this is the same as https://github.com/mozilla-mobile/firefox-ios/issues/8429

**Comment by data-sync-user** [comment]
➤ Orla Mitchell commented:

Duplicate of FXIOS-2869
