### ISSUE TITLE
PDFs don't work very well when switching back to Firefox

### ISSUE THREAD

**Issue by jrmuizel** [mozilla-mobile/firefox-ios#12380]
## Steps to reproduce
* Load a long pdf.
* Scroll down a ways.
* Switch to another app
* Switch back to Firefox

### Expected behavior
* The pdf should scroll normally

### Actual behavior
* The browser is very slow to respond as though input events are blocked. Later it starts scrolling without me doing scrolling.

### Device & build information
* Device: iPhone 14 mini iOS 15
* Build version: 106.2
### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5251)

**Comment by jrmuizel** [comment]
I'm unable to reproduce this issue in the simulator

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

This issue is no longer reproducible on latest main 9000 (25454) and v109 (25431). Closing for now. Let’s re-open if the issue is reproducible again.

**Comment by jrmuizel** [comment]
I still see this.
