### ISSUE TITLE
The theme is incorrect in tabs tray

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#12407]
## Steps to reproduce
1. Change to Night mode
2. Open tabs tray

Or

1. Open tabs tray
2. Change to dark theme from control center
### Actual behavior
- The theme is incorrect.
### Device & build information
* Device:  iPad Pro 
* Build version: 108 (22078)
### Notes
Attachments: 

https://user-images.githubusercontent.com/32130829/202171406-7e5ebebb-5a25-423e-807c-befffc196202.mp4

https://user-images.githubusercontent.com/32130829/202171411-ab900811-6d45-463b-8f8b-1f65131f350a.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5276)

**Comment by data-sync-user** [comment]
➤ Daniela Arcese commented:

test if this was fixed in 109

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

This issue is still reproducible in v109 (25431).

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verifying as fix on v110 (25952)
