### ISSUE TITLE
Extra spacing in the download panel

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#12404]
## Steps to reproduce
1. Download a page
2. Go to the download panel
### Expected behavior
- There should be no extra space from the header to the top panel
### Actual behavior
![image](https://user-images.githubusercontent.com/32130829/202146087-07bd7c43-752c-4622-bc68-68bdea4f173c.png)

### Device & build information
* Device: iPhone 12 Pro
* Build version: 108. (22078)
### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5273)

**Comment by data-sync-user** [comment]
➤ Catalin Suciu commented:

Verifying as fixed on v9000 (23491)

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verified fix on 109 (24441)
