### ISSUE TITLE
Recently closed panel is not accesible after closing a tab

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#12405]
## Steps to reproduce
1. Close the app if previously opened
2. Open the app
3. Visit a page
4. Close the tab
5. Go to History panel
### Expected behavior
- Recently closed should be accessible
### Actual behavior
- After tapping on the Today header, the Recently closed panel becomes populated with the previously closed tab
### Device & build information
* Device: iPhone 12 Pro (16.0)
* Build version: 108 (22078)
### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5274)

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verifying as fix on 109 (24441)
