### ISSUE TITLE
Theme is incorrect for search suggestions

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#12408]
## Steps to reproduce
1. Change to dark mode
2. Open the URL and type a letter
### Actual behavior
- Theme is incorrect for search suggestions
### Device & build information
* Device: iPhone 13 mini (16.0)
* Build version: 108 (22078)
### Notes
Attachments: 

![image](https://user-images.githubusercontent.com/32130829/202172906-73e691e2-d6b2-4297-84ee-51643e4d6e2c.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5277)

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verifying as fix on v108 (22599)
