### ISSUE TITLE
Firefox crashes after closing the app and sending the events ping a few times

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#12416]
## Steps to reproduce
1. Open Firefox
1. Open a new empty tab
1. Close Firefox from app switcher
1. From notes, tap on the events deep link
1. Repeat steps 3) and 4) a few times
    1. Actual behavior

* Firefox crashes
    1. Device & build information
* Device: iPhone 12 Pro (16.0)
* Build version: 108 (22078)
    1. Notes
Attachments:

[Client-2022-11-17-142344.ips.zip](https://github.com/mozilla-mobile/firefox-ios/files/10031490/Client-2022-11-17-142344.ips.zip)

https://user-images.githubusercontent.com/32130829/202447179-e0c2bc3b-9092-4c8e-87da-327ac4144ce9.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5282)

**Comment by OrlaM** [comment]
I can't reproduce this. I'll keep an eye on the crash logs and see if anything shows up that looks like it could be related.
