### ISSUE TITLE
The check mark is incorrectly positioned in protection settings after changing device orientation

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#12415]
## Steps to reproduce
1. visit a page
2. tap on the lock icon
3. tap "Protection settings"
4. Change device orientation to landscape
### Actual behavior
- The check mark is incorrectly positioned
### Device & build information
* Device: iPhone 12 Pro 
* Build version: 108 (22078)
### Notes
- If "Strict" is selected and you are changing to "Standard" after step 4) and changing the device orientation to portrait, an incorrect spacing is displayed.
Attachments: 

https://user-images.githubusercontent.com/32130829/202417919-e0b5a10b-c08f-4fb9-bca1-38f0fdc952ba.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5281)

**Comment by data-sync-user** [comment]
➤ Catalin Suciu commented:

Verifying as fixed on v9000 (22848).

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verified fix on v109 (24441)
