### ISSUE TITLE
Sharing to Firefox with “Load in Background” doesn’t work in 108.0

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/firefox-ios#12414]
## Steps to reproduce

1. In another app, open the iOS Share menu for some web link. 
2. Select Firefox Beta. 
3. Select “Load in Background”.
4. Switch to Firefox Beta. 

### Expected behavior

The shared link should open in a new tab. 

### Actual behavior

The shared tab doesn’t open. 

This bug is a regression in 108.0 (22078). If I  downgrade to 107.0 (21907), the link I tried to share in background to 108.0 (22078) suddenly opens in 107.0 (21907). Other links I share in background to 107.0 (21907) open as expected. 

### Device & build information

* Device: iPhone 12 and iOS 16.1
* Build version: 108.0 (22078)

### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5280)

**Comment by lmarceau** [comment]
I can reproduce reliably in Beta. All other options works like "Open in Firefox" works, but not "Load in Background".

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verifying as fix on 108 (22599)
