### ISSUE TITLE
Today header is missing and theme is not respected with Night mode in the history panel

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#12417]
## Steps to reproduce
1. Enable Night mode
1. Go to history panel
    1. Actual behavior

* The theme is not respected for the panel buttons
* Today header is missing from the list
    1. Device & build information
* Device: iPhone 12 Pro
* Build version: 108 (22078)
    1. Notes
Attachments: 

![Screenshot](https://user-images.githubusercontent.com/32130829/202469223-1e97ca55-6a07-4061-869d-8240452ad30d.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5283)

**Comment by data-sync-user** [comment]
➤ Alina Moldovan commented:

Validated this issue using iPad Air 3rd Gen (16.3.1) and iPhone 14+ (16.0.1) and FF v9000 (32297)

Issue doesn't reproduce anymore
