### ISSUE TITLE
No option to set page/text zoom on iOS

### ISSUE THREAD

**Issue by markojurkovic** [mozilla-mobile/firefox-ios#12464]
This sounds silly for a modern browser, but it looks like there is no option to increase text size, or to zoom into (entire) pages in Firefox on iOS.

This single thing prevents me from using Firefox legitimately on my phone, as text is just too small by default, as Firefox also apparently doesn't really take into account iOS text size setting

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5305)

**Comment by lmarceau** [comment]
@markojurkovic Thanks for opening this issue. We're already tracking this with the following issues https://github.com/mozilla-mobile/firefox-ios/issues/9618 and https://github.com/mozilla-mobile/firefox-ios/issues/3508 so I'll close this one for now.
