### ISSUE TITLE
Add Http/3 support

### ISSUE THREAD

**Issue by nasiralamreeki** [mozilla-mobile/firefox-ios#12468]
Add HTTP/3 support to Firefox for iOS

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5306)

**Comment by data-sync-user** [comment]
➤ Daniela Arcese commented:

This would be something Apple needs to support

**Comment by nasiralamreeki** [comment]
Apple does support it but Mozilla has not enabled it in
