### ISSUE TITLE
UI glitch in Tracking protection screen

### ISSUE THREAD

**Issue by yusanenko-vadim** [mozilla-mobile/firefox-ios#12470]
## Steps to reproduce
Open any website. Click on lock icon next to URL. Click on "Protection Settings". Duplicate "Learn more" link appears (see screenshot). If it is not present - just click original "Learn more" link at the bottom - new screen will appear. After going back - glitched copy will be present.

### Expected behavior
No artifacts and misplaced link duplicates appear.

### Actual behavior
Right under "Enhanced Tracking Protection" checkbox (see screenshot) "Learn more" link appears. This link also is present at the bottom of the screen and seems to be cloned and placed incorrectly. This upper duplicate does nothing on click.

### Device & build information
* Device: iPhone 13, iOS 16.1.1
* Build version: Firefox 107.1 (22302)
### Notes
Attachments: 
![photo_2022-11-23 16 09 57](https://user-images.githubusercontent.com/748882/203567636-da362217-02aa-4f58-beef-62c9a70c9b43.jpeg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5308)

**Comment by lmarceau** [comment]
Hello! This is tracked with issue https://github.com/mozilla-mobile/firefox-ios/issues/12179, it was already fixed and will be release with the 108 version. I'll close this issue for now, thank you!
