### ISSUE TITLE
Annoying flickering on app launch

### ISSUE THREAD

**Issue by gutley** [mozilla-mobile/firefox-ios#12478]
I'm not sure if this is a new thing as I've recently run 107.2 after not using FF for a few weeks, but the experience when launching FF nowadays is a flickery mess.

Please see enclosed screen recording

https://user-images.githubusercontent.com/2040690/203742806-37943ba9-a3cb-4782-9f11-0711b8329488.MP4

If you run that in realtime you will see what I mean.

If you scrub through it slowly you will see the various stages of this flickering:

1. The standard Launch screen shows.
2. The screen starts to fade while the keyboard starts to show.
3. Once the keyboard is fully shown and the background is black, the keyboard starts to disappear and the background goes completely white.
4. The Home Screen icons start to show up and the wallpaper starts to come in from the top-left.
5. The Recently Visited section shows up.
6. While the wallpaper continues to come in from the top-left, the Recently Visited section jumps up the screen a bit while the keyboard starts to show up again.
7. Once everything has settled down, the keyboard hides itself.
8. Everything stabilizes.

That seems an incredible lot of noise for an app launch, especially the keyboard showing and hiding itself twice.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5310)

**Comment by FranciscoSerrano** [comment]
I am not able reproduce this on 108.

**Comment by dnarcese** [comment]
Closing as fixed
