### ISSUE TITLE
Tapping on “firefox://google.com“ from notes opens Firefox but does not load “google.com”

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#12471]
## Steps to reproduce
1. From notes tap on “firefox://google.com”
    1. Expected behavior

* Firefox should open and google.com should be loaded
    1. Actual behavior
* Firefox is opened but google.com is not loaded
    1. Device & build information
* Device: iPhone 12 Pro (16.1)
* Build version: 108 (22599)
    1. Notes
Attachments: 

https://user-images.githubusercontent.com/32130829/203588362-8e9ff116-ed25-4ae1-94fe-e4ff8631d7e6.MOV

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5309)

**Comment by nishant2718** [comment]
Hiya! I don't think this works in Prod either - maybe not a v108 issue but one we should look into.

**Comment by dnarcese** [comment]
@SimonBasca did this work in previous versions?

**Comment by SimonBasca** [comment]
@dnarcese this is not working in previous versions. I’ve checked also on 105.1 and the behavior is the same. After tapping on “firefox://google.com” Firefox is opened but google.com is not loaded.

**Comment by dnarcese** [comment]
This should work firefox://open-url?url=google.com

**Comment by SimonBasca** [comment]
Tested on v109.0 (24441) with iPhone 12 Pro (16.0.1).
@dnarcese this is not working for "firefox://open-url?url=google.com". After tapping on "firefox://open-url?url=google.com" from notes, I can see the "google.com" address  in the URL for a second but the URL bar remains empty.
