### ISSUE TITLE
The download remains paused and does not resume after enabling internet connection

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#12480]
## Steps to reproduce
1. Download a large file
1. Turn off internet connection
1. Enable internet connection
### Expected behavior

* The download should be resumed when turning on internet connection
### Actual behavior
* The download remains paused and does not resume after enabling internet connection.
### Device & build information
* Device: ?
* Build version: 108 (22758)
### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5312)

**Comment by nishant2718** [comment]
Previously, downloads would resume if the app is made active again (https://github.com/mozilla-mobile/firefox-ios/pull/12241). With the scenes PR, this functionality was moved to `sceneDidBecomeActive`. 

I recommend testing backgrounding & foregrounding the app as well here. If this doesn't work, I suspect we may have to move it to `sceneWillEnterForeground`  🤔

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

I see no issue when backgrounding the app and restoring while the download is in progress. The only problem is when disconnecting and reconnecting the internet connection.

**Comment by data-sync-user** [comment]
➤ Razvan Litianu commented:

Simion Basca Nishant Patel I looked at the code and it seems an error is thrown when disconnecting the internet and it’s explicitly removed from the queue. It looks like it’s the intended behavior unless we ignore this error. What do you think we should do in this case?

!Screenshot 2023-02-09 at 16.32.41 1.png|width=566,height=169!

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Razvan Litianu in Safari when disconnecting the device from the internet while the download is in progress, the download is stopped but Safari has a way of resuming the download. 

The expected behavior for me would be to resumed when turning on internet connection or pause the download and have a “Retry” button.

**Comment by LeoniePhiline** [comment]
I've come across this discrepancy recently when trying to download large congress talk recordings on a flaky congress WLAN.

I've had frustrating days with Firefox, as downloads would abort very frequently and had to be restarted from scratch (no range requests) and even by opening the source webpage and finding the download link again.

- No resumability with range requests, causing already downloaded data to be lost.
- No UI for retrying, even though Firefox knows the url and target path, and could easily provide such UI.

I had to switch to Safari, which provides all the described functionality (and more).
