### ISSUE TITLE
Reordering Tabs will cause other Tabs to Jump Positions

### ISSUE THREAD

**Issue by Sync-67** [mozilla-mobile/firefox-ios#12481]
## Steps to reproduce

I've noticed this happening lately with a large amount of tabs open (~40-50). It may occur with other amounts as well, but I'm not sure.

1. Go to the "Open Tabs" menu.
2. Select a tab (Tab A) and drag it to the top left of the list. This tab moves position correctly.
3. Select a different tab (Tab B), and drag it to the second position in the list (ie. top right).
4. Visually, the tabs will appear to be ordered correctly. Tab A will appear to the left of Tab B.
5. Tap on Tab A. It will open a different tab (Tab X) from your current list of open tabs.
6. Reopening the tab menu will now show Tab A in a different position. Tab X will have taken the position that Tab A was moved to.

### Expected behavior

Tab A should remain at the top left of the list after Tab B is moved. Tab X should not take the position of Tab A.

### Actual behavior

Moving Tab B after moving Tab A will change the order of the tabs unexpectedly.

### Device & build information

* Device: iPhone 8 (iOS 16.1.1)
* Build version: Firefox version 107.0 

### Notes

Hopefully I've explained this in a way that makes sense. Please let me know if I can provide more information or clarify anything.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5313)

**Comment by nbhasin2** [comment]
Hi @SimonBasca, have you encountered this before? Could you confirm?

I wasn't able to reproduce this on iPad or iPhone unless I missed any step as shown in my video below:



https://user-images.githubusercontent.com/8919439/209757920-4bf1fba2-fa47-40a8-81e4-d28af194ad44.mov

**Comment by SimonBasca** [comment]
@nbhasin2 I can confirm that this issue is not reproducible on latest main 9000 (25310) or on latest RC 109.0 (24805).

@Sync-67 Could you please post a video of the issue?

**Comment by Sync-67** [comment]
@SimonBasca Hi, thanks for looking into this issue! I've tried to get it to happen again, but I've had no luck so far. I am testing on Firefox 108.1 (24234) now. I guess it's possible that the current version doesn't have the issue anymore.

I do kind of remember that having tabs in the "Inactive Tabs" section was a common factor when I had this issue a few times before, so I'm going to try to test it again once some of my tabs go inactive. I don't know of any way to force them into the inactive section other than waiting 2 weeks, so I'll have to get back to you once I test some more.

**Comment by lmarceau** [comment]
@Sync-67 I think one way to force tabs into the inactive tabs state is by changing your phone's date manually. Ideally we would have a debug option for this but I don't think we have one.

**Comment by Sync-67** [comment]
@SimonBasca @nbhasin2 Okay, I’ve managed to reproduce this bug. I tested on Firefox 109.0 (25841). Having at least one tab in the “Inactive Tabs” section was required. I’ve attached a video showing the issue. I’m tapping on the first tab (top left) each time after changing the order, in case that’s unclear in the video.

The second time, the correct tab opens, but one of the other tabs (Merriam-Webster Dictionary) has a phantom duplicate show up in the tab order just before. 
 
Please let me know if anything is unclear or if you need any other information from me!

**Comment by Sync-67** [comment]
Google Drive link because it's too big to upload here:
https://drive.google.com/drive/folders/1KrIG7RvjrognK0yb8wLw_VvFD6q56i-e?usp=share_link

**Comment by Sync-67** [comment]
Here's a shorter video:

https://user-images.githubusercontent.com/92419418/215997605-90fb48b2-c1a8-43ca-80bf-ad4a545953ec.mp4
