### ISSUE TITLE
Fix deprecation warnings in inactive tab area

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#12492]
We have deprecation warnings in the inactive tab area - more specifically in InactiveTabItemCellModel, InactiveTabHeader and CellWithRoundedButton. Currently Inactive Tabs are not adjusting correctly to Dynamic Text changes as the layout is done with fixed cell heights. This needs to be adjusted before the deprecation warnings can be addressed.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5320)

**Comment by data-sync-user** [comment]
➤ Winnie Teichmann commented:

This should be on hold until we drop iOS 13.

**Comment by bmihai23** [comment]
Hello, I would like to work on this task if it's available. Thank you!

**Comment by thatswinnie** [comment]
@bmihai23 thanks for wanting to fix this. The team is currently working on a refactor in this area which should fix this task as well. For that reason I removed the `Contributor OK` label from this task.

**Comment by data-sync-user** [comment]
➤ Laurie Marceau commented:

FYI this will be fixed once the Legacy tab tray is removed from the project.
