### ISSUE TITLE
Welcome screen shown when updating from 107.1 to 107.2

### ISSUE THREAD

**Issue by jrmuizel** [mozilla-mobile/firefox-ios#12490]
## Steps to reproduce
Update from 107.1 to 107.2
### Expected behavior
No welcome screen
### Actual behavior
Welcome screen
### Device & build information
* Device: iPhone 14
* Build version: ?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5319)

**Comment by yoanarios** [comment]
We need to update the logic to show Onboarding for existing users on `UpdateViewModel` `shouldShowUpdateSheet`
