### ISSUE TITLE
Fix warnings in Telemetry storage

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#12507]
!Screen Shot 2022-11-25 at 11.03.09 AM.png|width=2081,height=979!

![Screen Shot 2022-11-25 at 11 03 09 AM](https://user-images.githubusercontent.com/11338480/204025596-d6136ac8-f68d-4989-875c-2c3e0cb82c13.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5332)

**Comment by Ri-ishi** [comment]
Hi. I have cloned the project but am unable to make changes to this code in Telemetry.

**Comment by lmarceau** [comment]
Hello @Ri-ishi, this code is under the repository https://github.com/mozilla-mobile/telemetry-ios. Just realized this repo is archived. I am asking around if we should let this sit for now as we're supposedly to remove this dependency at one point. It would be preferable to look into other tickets I think. Thank you!
