### ISSUE TITLE
Xcode giving a lot of Runtime warnings during normal browsing

### ISSUE THREAD

**Issue by gutley** [mozilla-mobile/firefox-ios#12514]
This is something I've not noticed before, but with main (and 107.0.2) I am seeing one of these in Xcode almost everytime I load a page:

![](https://user-images.githubusercontent.com/2040690/204033608-900ff698-7ed2-4d84-a003-ae6839f756e3.png)

Its always the same stack trace and I'm sure its something new, since I've been building and running Firefox for over 2 years. Maybe something since 105.x, or iOS 16 has started triggering it.

The stack trace is not in our code, but it would be nice to se if they can be eliminated, since it obscures other such warnings.

Clicking the warning takes you to this in main.swift:

`_ = UIApplicationMain(CommandLine.argc, CommandLine.unsafeArgv, NSStringFromClass(UIApplication.self), appDelegate)
`

But I don't really think its calling that multiple times. I set a breakpoint and it only hits it at launch, so its not going recursive or anything.

Xcode 14.1 BTW

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5336)

**Comment by OrlaM** [comment]
I don't think a recent change caused this, I think it's XCode 14. There probably is a real issue underlying it tho, so we should try to get to the bottom of it.

**Comment by lmarceau** [comment]
Found [this thread](https://developer.apple.com/forums/thread/712074) & [this thread](https://developer.apple.com/forums/thread/713290) & [this thread](https://developer.apple.com/forums/thread/714467) which relate to this issue. Seems to be webkit related. 

The most important bit is in the third link, within an answer from Quinn.
> So, let’s break this down:
> - Modern versions of Xcode have a diagnostic feature that checks for potential hangs. Specifically, it looks for folks calling APIs on the main thread that might block waiting for a network request. That makes sense because, if the network is slow, such calls can cause your app to be unresponsive. In the worst case, it may even cause your app to be killed by the watchdog. See QA1693 [Addressing watchdog terminations](https://developer.apple.com/documentation/xcode/addressing-watchdog-terminations) for more on that.
> - SecTrustCopyCertificateChain is one such API. In order to build the chain of trust, the trust object may hit the network for various reasons.
> - WKWebView calls SecTrustCopyCertificateChain on the main thread (see frames 2 through 1 in the backtrace) and that raises this issue.
> - If you look deeper in the backtrace you’ll see that none of your code appears there, which is a strong indication that you’ve done nothing to trigger this.
> - This issue may or may not be a real problem depending on how the trust object is configured. You can configure the trust object to prevent any networking (SecTrustSetNetworkFetchAllowed).
> - You can also use SecTrustEvaluateAsync to avoid blocking. 
> - And if you evaluate the trust object asynchronously or on a secondary thread beforehand, your call to SecTrustCopyCertificateChain will never hit the network. 
> - But none of these are relevant here because it’s not your code doing the evaluation.
> - The Security tag on this issue doesn’t mean that it’s a security problem, but rather a problem associated with the Security framework.
> - The poor interaction between WKWebView, Security framework, and this Xcode feature is a known issue (r. 94019453). We plan to address it at some point but I don’t have any info to share as to when that’ll happen.
> - In the meantime, if you see an issue like this, look at its associate backtrace. If it’s made up entirely of system code (except for main) it’s likely that this isn’t your problem and you should feel free to ignore the issue.

This was posted a month ago.
