### ISSUE TITLE
Type URLSession does not conform to protocol LegacyWallpaperDownloadProtocol

### ISSUE THREAD

**Issue by TwizzyIndy** [mozilla-mobile/firefox-ios#12519]
## Steps to reproduce
I think I might be missing something before the compilation. It keeps me saying every time I try to compile `Type 'URLSession' does not conform to protocol 'LegacyWallpaperDownloadProtocol'`. Please let me know if I missed something. Thanks.

### Expected behavior
It should succeed in the compilation.

### Actual behavior
`Type 'URLSession' does not conform to protocol 'LegacyWallpaperDownloadProtocol'`

### Device & build information
* Xcode Version: 13.4.1
* Device: M1 Macbook Air
* Build version: 108.0
### Notes
Attachments: 

<img width="857" alt="Screen Shot 2022-11-27 at 10 47 10 PM" src="https://user-images.githubusercontent.com/6712795/204147831-3355ae36-5ef2-4049-8991-0ca4da10148e.png">

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5339)

**Comment by lmarceau** [comment]
@TwizzyIndy Running on Xcode 14.0.1 this is fine. We're discussing to upgrade our Xcode version in the readme. In the meantime if you want to run the app I would say upgrade to that version.
