### ISSUE TITLE
Tab icon has unwanted white background

### ISSUE THREAD

**Issue by LMattsson** [mozilla-mobile/firefox-ios#12546]
## Steps to reproduce
1. Open the attached test.html in Firefox on iPadOS
1. Observe the gray text on the favicon

### Expected behavior
The icon should appear with yellow text.

Using the attached test.html (and ICO and PNG), we can see this behaviour. The ICO and PNG are labelled with their image size. Icons in the ICO have yellow text, and the apple-touch-icon have gray text. We expect the regular ICO to be used here, not the apple-touch-icon.

### Actual behavior
The icon appears with gray text, i.e. the apple-touch-icon is used.

### Device & build information
* Device: iPad mini (6th generation)
* Build version: 107.0 (21907)

### Notes
The tab icon gets a white background despite the regular icon having a transparent background.

This issue is mostly visible in dark mode, the white background stems from apple-touch-icons. These icons have opaque backgrounds. 

As seen in the screenshot below, an apple-touch-icon is also used in the "Share" pop-up. 

Attachments: 
![firefox](https://user-images.githubusercontent.com/70215710/204806319-5183643c-aa77-4952-b988-e9a62adc1a28.png)UNITO-UNDERSCORE!ios!UNITO-UNDERSCORE!tab!UNITO-UNDERSCORE!and!UNITO-UNDERSCORE!share!
[test.zip](https://github.com/mozilla-mobile/firefox-ios/files/10123504/test.zip)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5361)

**Comment by lmarceau** [comment]
This relates to https://github.com/mozilla-mobile/firefox-ios/issues/9002, favicons have different styles which are inconsistent in the application. FYI we're working on a new solution for favicons that will normally fix this once it's replaced in all places in the app.

**Comment by LMattsson** [comment]
Note that the icon shown under "History" also uses an apple-touch-icon.
