### ISSUE TITLE
[Unit Test] TelemetryWrapperTests.test_syncLogin_NimbusIsCalled 

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/firefox-ios#12567]
This test is failing frequently since yesterday.

### Bitrise Test Run:
Provide a Bitrise test run report link here showcasing the problem
https://app.bitrise.io/build/6eeded6f-8ce2-44b6-8164-f6ca66b136b1

### Stacktrace:
/Users/vagrant/git/Tests/ClientTests/TelemetryWrapperTests.swift:428 - XCTAssertTrue failed

### Build:
main https://github.com/mozilla-mobile/firefox-ios/commit/fd3525a3114432813e2fa4bdca483ee6cd7494a7

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5368)

**Comment by isabelrios** [comment]
This is the commit where the test was added: https://github.com/mozilla-mobile/firefox-ios/commit/2a3e8ef1051688434c001406310bc6ad9cd71380#diff-9b7ff7406ea0975089d92c74335c5d0d63839396c1050dbfc10009b35db48bef

**Comment by lmarceau** [comment]
@jeddai it turns out the new tests are intermittently failing. Here's another example of [failure](https://app.bitrise.io/build/edc88317-c928-41c3-883b-2c34b7d68778). 

```
/Users/vagrant/git/Tests/ClientTests/TelemetryWrapperTests.swift:428: error: -[ClientTests.TelemetryWrapperTests test_syncLogin_NimbusIsCalled] : XCTAssertTrue failed

/Users/vagrant/git/Tests/ClientTests/TelemetryWrapperTests.swift:423: error: -[ClientTests.TelemetryWrapperTests test_appForeground_NimbusIsCalled] : XCTAssertTrue failed
```

I'll open a PR so we disable those tests until we investigate more what's up here.

**Comment by isabelrios** [comment]
Closing this issue as the test was disabled
