### ISSUE TITLE
"Close Private Tabs" does not close private tabs unless a tab in regular mode is opened

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#12564]
When the “Close Private Tabs” setting is on, the tabs under private mode are not closed by merely toggling to the regular mode (“Open Tabs” screen). 

Steps

1. Go to Settings > Privacy. Enable “Close Private Tabs”.
1. Click “Done”.
1. Open tab tray.
1. Click :eyeglasses: icon to open “Private Browsing”.
1. Open a tab under private browsing. Open a website (say “[www.example.com](http://www.example.com)” or “nohello.net”).
1. Open the tab tray again and click :one:  to enable regular mode.
1. Without maximizing a tab in the regular mode, click :eyeglasses: icon to open “Private Browsing” again.

Actual

* “Private Browsing” screen still lists the tabs opened in private mode.

Expected

* “Private Browsing” screen contains no opened tabs.

Workaround

* Maximize a tab in regular mode (step 7).

Please see the attached video for details. We do have an automated test to ensure that enabling the regular mode closes all tabs under private mode.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5349)

**Comment by data-sync-user** [comment]
➤ Daniela Arcese commented:

This is currently the correct behaviour. We do not change browsing modes until you actually open a tab in that mode.
We could improve on this functionality, though.

**Comment by data-sync-user** [comment]
➤ Clare So commented:

Isabel Rios Escobar I agree with Daniela Arcese that the current behaviour is not wrong. Since there’s an automated test on toggling between regular and private modes, switching back to regular mode without opening the tab closes all tabs under private modes. Should we update the existing test or to ask the developers to improve on the functionality?

**Comment by isabelrios** [comment]
yeah, agreed. We should update the test as commented in the issue that was open related to this https://github.com/mozilla-mobile/firefox-ios/issues/11557.
Thanks! Let's close this one
