### ISSUE TITLE
Private browsing mode isn't remebered when re opening Firefox

### ISSUE THREAD

**Issue by Tomatoshadow2** [mozilla-mobile/firefox-ios#12569]
## Steps to reproduce

Open Firefox, then open a private tab, browse or search for a random site. 

Close the browser, then re open it.

Firefox then displays in regular browsing mode. 

### Expected behavior

Firefox should re open a private tab in private browsing mode.

### Actual behavior

Firefox always opens a regular tab upon opening the browser.

### Device & build information
* Device: iPhone 11 Pro Max iOS 16.1.1
* Build version: Beta version 108.0 (23264)
### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5369)

**Comment by lmarceau** [comment]
Once I'm in private mode, it always reopen the browser in private for me. Any other steps you're doing to reproduce this? Could you send us a video of what you see? I can't get this issue in prod or developer mode.

**Comment by csuciu** [comment]
@Tomatoshadow2 Is your private tab still there if you go back to private mode after reopening the app?

**Comment by Tomatoshadow2** [comment]
@lmarceau @csuciu  Hi, thanks for the info and confirming, once I unchecked the feature of close private tabs, when closing private browsing, Firefox now says in Private mode, the feature was working as intended, I thought at the time, it would still reopen a private tab, when reopening the app, thanks! Sorry about opening this non-issue
