### ISSUE TITLE
Inconsistency in the way the long press context menu is triggered between Bookmarks and History panels

### ISSUE THREAD

**Issue by csuciu** [mozilla-mobile/firefox-ios#12585]
## Steps to reproduce
1. Go to the Bookmarks and History panels and long press in each on an item.
### Expected behavior
Long press on an item in each of the panels triggers the context menu in the same way.
### Actual behavior
In Bookmarks the context menu is triggered after releasing the long press while in History it's triggered while long pressing. 
I believe that the behaviour from the History panel is the correct one.
### Device & build information
* Device: iPhone 12 Pro (16.1.1)
* Build version: v108 (23470)
### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5374)

**Comment by data-sync-user** [comment]
➤ Raluca Iordan commented:

Note for QA: Please check that context menu from bookmarks panel should appear the same like history panel context menu and only allow re-ordering bookmarks in edit mode.

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Verified as fixed on v9000 (29660) with iPhone 13 Pro (15.7.1).

This issue will still be checked when an RC will be created for the fix version.

Raluca Iordancan you please set the fix version for this issue? 🙇‍♂️

**Comment by data-sync-user** [comment]
➤ Raluca Iordan commented:

Laurie helped and added v113 for fix version. Thank you, Andrei Bodea

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Verified as fixed on v113 (30043) with iPhone 13 Pro (15.7.1).
