### ISSUE TITLE
App crashes and tabs are lost after switching between the opening screen options

### ISSUE THREAD

**Issue by csuciu** [mozilla-mobile/firefox-ios#12593]
## Steps to reproduce
1. Go to the Homepage settings and select the "Homepage after four hours of inactivity" option.
2. Open a few sites in different tabs.
4. Restart de app a few times => each time the last tab opens correctly.
5. Go to the Homepage settings and select the "Homepage" option.
6. Exit settings.
7. Restart de app a few times.

### Expected behavior
No crash and no lost tabs.
### Actual behavior
If you quickly reopen the app after closing it, the new "Homepage" setting is not applied and the last tab still opens. After a few quick restarts if you leave the app closed for a few seconds before starting it, when it opens it shows the new Homepage tab. After one more restart the app crashes and all tabs are lost.

### Device & build information
* Device: iPhone 12 Pro (16.1.1)
* Build version: v108 (23530)
### Notes
Sentry ID for more crash reports: f49716f3ac67427c9dce07864f53aeb04e3c5c31
Attachments: 
[Client-2022-12-05-211356.ips.zip](https://github.com/mozilla-mobile/firefox-ios/files/10157539/Client-2022-12-05-211356.ips.zip)

https://user-images.githubusercontent.com/1866605/205735585-2eaa918d-f7a7-4f6a-b98e-e2e170da75bb.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5378)

**Comment by lmarceau** [comment]
From the `.ips` this seems to be crashing in BrowserViewController.foregroundBVC which relate to single scene setup. This is being worked at the moment so we don't use anymore this foregroundBVC method. Until there are no more foregroundBVC I think we can't get around this issue. What worries me thought is that this crash makes us unable to restore tabs. Tabs restoration should happen properly even when there's a crash.

cc: @nishant2718 I got this right?

**Comment by csuciu** [comment]
I'm no longer able to reproduce this issue. Closing as fixed in build 23855.
