### ISSUE TITLE
Firefox Sync counts one iPhone as two

### ISSUE THREAD

**Issue by Tomatoshadow2** [mozilla-mobile/firefox-ios#12595]
## Steps to reproduce

1. Sign into sync account from Firefox iOS

2. After signing in, you should get two of the same emails, regarding sign in.

3. Sync, lists two devices with different names for one iPhone.  

### Expected behavior

Sync should only display one device per sync sign in and use name listed on Sync page.

### Actual behavior

Sync displays two devices for one iPhone.

Attached is an image that displays the issue. Could this be related to the closed issues: https://github.com/mozilla-mobile/firefox-ios/issues/12069 and https://github.com/mozilla-mobile/firefox-ios/issues/8944 ? As when you want to manage your account from the app, it requires you to sign in again to view devices, when you already signed in once to sync. 

### Device & build information
* Device: iPhone 11 Pro Max iOS 16.1.2
* Build version: Beta Version 108 (23417)
![Sync pic](https://user-images.githubusercontent.com/34449219/205840910-c094fb02-88ea-44f7-9ac0-4f12c21a0de7.jpg)

### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5379)

**Comment by Tomatoshadow2** [comment]
Sync tabs now don't display on the iOS sync tabs page related to this closed issue https://github.com/mozilla-mobile/firefox-ios/issues/12357

**Comment by lmarceau** [comment]
Hello! So if you have a Beta application and the Prod application both will show. What I see there is expected.

**Comment by Tomatoshadow2** [comment]
@lmarceau Hi, thanks for the info, I only have the Beta application installed. So I should only see one entry, in Sync correct?

**Comment by lmarceau** [comment]
Just checked and it indeed seems like we see two (I tested on the Production application). I signed out of the one without the phone icon and it didn't signed me out in the app (while the other did sign me out). When I sign in again, both sign in were recreated.

**Comment by lmarceau** [comment]
Ok so just learned that this is on FxA side and there's an [existing bug for it.](https://bugzilla.mozilla.org/show_bug.cgi?id=1753785)
I'll close this issue here since it's already being tracked in the right place. 
Thank you!
