### ISSUE TITLE
History Metadata referrer URL is sometimes the URL of the site itself

### ISSUE THREAD

**Issue by tarikeshaq** [mozilla-mobile/firefox-ios#12631]
I haven't gotten as far as reproduce it, but we're seeing reports of this log:

```
init(localName:syncDelegate:clear:) > [RUST][places::error] Unexpected error: SqlError(SqliteFailure(Error { code: ConstraintViolation, extended_code: 275 }, Some("CHECK constraint failed: place_id != referrer_place_id")))
```

See: https://github.com/mozilla-mobile/firefox-ios/issues/12093#issuecomment-1340128287

This indicates that iOS is attempting to record metadata where the referrer is the same as the site. This is odd and shouldn't happen in practice (I site referring itself doesn't usually happen)

I found https://github.com/mozilla-mobile/firefox-ios/blob/b739d887d9efbde7ed8e41fc1f324d5693ead64e/Client/Frontend/Browser/BrowserViewController.swift#L1337-L1344

Which seems suspect in how it's setting what ends up being the referrer URL

I haven't dug deeper into this (and the piece of code I linked could very well be expected behaviour) - but depending on how often this is happening, our history metadata entries could be off.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5401)

**Comment by data-sync-user** [comment]
➤ Yoana Rios Diaz commented:

Found the error log on Sentry: https://sentry.io/organizations/mozilla/issues/3047954317/?project=6176941&query=is%3Aunresolved&referrer=issue-stream ( https://sentry.io/organizations/mozilla/issues/3047954317/?project=6176941&query=is%3Aunresolved&referrer=issue-stream )

**Comment by tarikeshaq** [comment]
Hmmm https://sentry.io/organizations/mozilla/issues/3047954317/?project=6176941&query=is%3Aunresolved&referrer=issue-stream seems to be catch-all for all rust logs (including the one this ticket is about!)

And we used to have so many of it, then suddenly we only get a few? Did we silence it because it was too noisy?


https://mozilla-hub.atlassian.net/browse/SYNC-3267 should help a lot here in isolating the sentry error, cc @bendk

**Comment by bendk** [comment]
I think iOS might be in a weird situation with Sentry errors right now.  We removed almost all of the `log::error` lines and replaced it with the new error handling.  However, I don't think that's wired up on iOS yet.  I'm pretty sure that's why you're seeing the drop and why there won't be any more reports coming until that error handling is wired up.
