### ISSUE TITLE
[Share Sheet] Invalid "Lockwise" devices in device list for "Send to Device"

### ISSUE THREAD

**Issue by FeBe95** [mozilla-mobile/firefox-ios#12650]
## Steps to reproduce
- Open any website and open the Firefox share dialog.
- Tap "Send to Device" and wait for the list to load (~2-3 seconds).

### Expected behavior
- The device list only contains devices names of actual Firefox installations.
- Devices named "Lockwise" shouldn't be in the list at all, as you can't send tabs to this app.
- The Lockwise app isn't even maintained anymore and is now integrated into Firefox itself.

### Actual behavior
- The device list shows additional "devices" for current and stale Lockwise versions.
- I remember needing to re-login manually after some time not using the Lockwise app.
- Maybe each manual login created a new Lockwise instance in this list?

### Device & build information
* Device: iPhone 13 Pro
* Build version: Firefox for iOS 107.3 (23248)
### Notes
- Over the years more and more instances of "Lockwise" appeared, to a total of 10 invalid devices until now.

Attachments:

![Firefox for iOS](https://user-images.githubusercontent.com/7470739/206734214-087b2ef5-3d8f-4f11-a2a9-e2847d64eebe.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5410)

**Comment by tarikeshaq** [comment]
In Firefox 109, we limit the send tab list to devices accessed in the last 21 days, **so as long as you haven't accessed lockwise in 21 days it should get rid of itself once you upgrade to 109**

However, we should keep this ticket open to filter devices that don't support send tab. 

The devices we get from FxA tell us if they support Send tab.

This can be done in https://github.com/mozilla-mobile/firefox-ios/blob/f68f9346c7387363880b9fd207f0fb6c919a1153/Client/Frontend/Extensions/DevicePickerViewController.swift#L132-L140


We can probably filter that based on the [device's capabilities](https://github.com/mozilla/application-services/blob/a4dfd1f4d3e370df62e779670f04cad10fbbdc0f/components/fxa-client/src/fxa_client.udl#L831) which is ignored in the above code.

There are other places `remoteDevices` is used, we should also make sure that if those end up being used for the purpose of send tab, we filter properly there too!

**Comment by FeBe95** [comment]
Just a short feedback: After updating to Firefox 109 the list is now cleaned up, with only my recent devices being shown. Although, as expected, Lockwise still re-appeared in the list right after I opened the app once again on my old iPhone.

**Comment by SimonBasca** [comment]
@FeBe95 should we mark this as completed?
