### ISSUE TITLE
External links open in new private tabs if any private tabs are open

### ISSUE THREAD

**Issue by garbofrogman** [mozilla-mobile/firefox-ios#12662]
## Steps to reproduce
-have Firefox set as default browser 
-have at least one private tab open
-switch to regular (non-private) tab 
-tap a link in another app that will open in Firefox 

### Expected behavior
Link opens in new regular tab

### Actual behavior
Link opens in new Private tab

### Device & build information
* Device: iPhone XS Max
* Build version: Firefox 107.3 (23248)
### Notes
After clearing cache and re-installing, the problem subsided for a little while (or i didn’t notice), but it’s back. 

Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5414)

**Comment by dnarcese** [comment]
This should be fixed in v108.
