### ISSUE TITLE
Up-to-date Firefox-iOS is rejected as out-of-date by some websites

### ISSUE THREAD

**Issue by AxelBoldt** [mozilla-mobile/firefox-ios#12668]
For instance, chess.com says "we stopped supporting browsers older than Chrome 79 and Firefox 75" when accessed with Firefox 107.2 on iPadOS 16.1.1. I get a similar message when I access our school's D2L Brightspace page.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5419)

**Comment by dnarcese** [comment]
@AxelBoldt is this still reproducible on v109?

**Comment by AxelBoldt** [comment]
The issue seems to be fixed in v109. Both chess.com and D2L work fine for me. I'm closing this. Thanks!
