### ISSUE TITLE
[Intermittent] Broken tab after closing the Inactive tabs

### ISSUE THREAD

**Issue by csuciu** [mozilla-mobile/firefox-ios#12684]
## Steps to reproduce
1. Open a few tabs.
2. Close the app then go to iOS settings and change the time two weeks fwd.
3. Open the app and see the tabs moved to the Inactive tabs section.
4. Close all inactive tabs.
                   => The user is returned to the default tab.
5. Type a site address in the URL bar and hit GO.
### Expected behavior
The site should load.
### Actual behavior
1. Nothing happens when pressing GO. When pressing the back button the page turns blank.
2. The tab counter still shows the number of tabs I had prior closing the inactive ones.
### Device & build information
* Device: iPhone 12 Pro (16.1.1)
* Build version: v108.0, v108.1, v109.0
### Notes The browser becomes usable only after opening a new tab.
Attachments: 
https://user-images.githubusercontent.com/1866605/207375847-bac865e3-5d72-4681-93f7-17c5de6edbb4.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5428)

**Comment by thatswinnie** [comment]
@csuciu I just tried to reproduce with v108 but can't. Are you using a fresh install? Are you logged into an account? Wondering if I am missing some magic/details to reproduce this.

**Comment by csuciu** [comment]
@thatswinnie I wasn't logged in and was using fresh installed & upgraded from 107.3 builds. Unfortunately, after a few clean installs done while testing something else, I'm no longer able to reproduce it either. Will tag this as intermittent while trying to reproduce and find better STRs

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Verified as fixed on v9000 (29426) with{color:#ffffff} {color}iPhone 13 Pro (15.7.1).
This issue will still be checked when an RC will be created for the fix version.

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Verified as fixed on :Firefox: v112 (29529) with iPhone 13 Pro (15.7.1), and iPhone 14 (:iOS:16.1).
