### ISSUE TITLE
Page stuck to loading content when first trying to open an item from the reading list

### ISSUE THREAD

**Issue by csuciu** [mozilla-mobile/firefox-ios#12685]
## Steps to reproduce
1. Open a reader mode compatible article.
1. Add it to the reading list via the hamburger menu option.
1. Open reading list and tap on the previously added article.
    1. Expected behavior
The article should open in the reader view.
    1. Actual behavior
The page is stuck showing the "Loading content" message.
    1. Device & build information

* Device: iPhone 12 Pro (16.1.1)
* Build version: 107.3, 108.0, 108.1
    1. Notes This only happens when trying to open an article for the first time after adding it to the reading list. The second time you are trying to open it, it opens correctly.
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5429)

**Comment by lmarceau** [comment]
Just to note the problem here what was comment in the linked PR;

> Had a look into this with nbhasin2, and it's confirmed that the issue is the reload message not sent from the ReaderViewLoading.html script. We can see this error from Safari inspector in the console.
![image](https://github.com/mozilla-mobile/firefox-ios/assets/11338480/c9e5490f-4d83-4f78-87c4-def2ecbb95e0)
> It looks like the webkit.messageHandlers method isn't available from this script. Since the script is part of that html file, maybe it should be handled another way to have access to that namespace.

So we should fix this problem at the root cause.

**Comment by data-sync-user** [comment]
➤ Nishant Patel commented:

It seems like the root issue is that the script is not returning after the script is run? We usually inject scripts to watch or execute on web pages to provide users with features like reader mode, night mode. We depend on the script to send a message back to us when it has executed and there’s data available to work with. If the script isn’t run for whatever reason, it seems trickier to react to something we know should’ve happened, but didn’t.

Going to table this for now and look into it with fresh eyes later.

**Comment by lmarceau** [comment]
Just commenting to put this information clearer;

The issue is the `ReaderViewLoading.html` script. It contains some JS, and it the call to `webkit.messageHandlers.localRequestHelper.postMessage` doesn't have any effect. 

To fix this at root cause, we need to play in that html file. Nish had proposed an idea that we can possibly handle the `messageHandlers` from a different place than a script in a html file. This means having a separate JS to inject, so the namespace is reachable (like we do with other scripts which we know can successfully call `webkit.messageHandlers`)

**Comment by data-sync-user** [comment]
➤ Alina Moldovan commented:

A new bug was logged to track this issue: https://mozilla-hub.atlassian.net/browse/FXIOS-11709 ( https://mozilla-hub.atlassian.net/browse/FXIOS-11709|smart-link )
