### ISSUE TITLE
[iPad] Focus jumps one tab ahead too many when closing a tab

### ISSUE THREAD

**Issue by badboy** [mozilla-mobile/firefox-ios#12690]
## Steps to reproduce

On an iPad

1. Open 3 tabs
2. Focus the first one (left-most)
3. Close it by clicking the little X on the tab

### Expected behavior

The 2nd tab, right next to the one being closed, is focused.

### Actual behavior

The last tab, formerly 3rd tab, is focused, skipping the expected one.

### Device & build information

* Device: iPad Pro
* Build version: 108.0 (23855), 109.0 (24271), but this bug existed for a while now

### Notes 

At the very least this is surprising behavior.
Feels to me like somewhere in the code we use the tab index and increment it before closing the tab, then using that new index to focus the specific tab.

Here I have 4 tabs open.
I close the first one (mozilla.org), which then brings fnordig.de in focus.
Then I go to the first one again (rbb24.de) and close it, which brings the last one into focus (zeit.de)

https://user-images.githubusercontent.com/2129/207559309-78010935-efaa-45d7-9fc4-027e4e91b462.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5439)

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verifying as fix on v9000 (27969)

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verifying as fix on v111 (28263)
