### ISSUE TITLE
Not all characters from the search suggestions are bold.

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#12698]
## Steps to reproduce
1. Tap on the URL bar and tap a character
### Expected behavior
- Search suggestions should be bold.
### Actual behavior
- Not all characters are bold.
### Device & build information
* Device: iPhone 12 Pro (16.0.2)
* Build version: 109 (24441)
### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5443)

**Comment by SimonBasca** [comment]
![0E461B11-4CEA-49A2-BB1F-2E043CCF559E](https://user-images.githubusercontent.com/32130829/207812267-c839734e-a223-47df-bc91-1a70c075da10.jpeg)

![48D80ADD-131B-4198-8970-DEC73DEB7ED7](https://user-images.githubusercontent.com/32130829/207812276-0247a47e-2a21-4ed9-b3e6-2a43aec8e5b0.jpeg)

**Comment by data-sync-user** [comment]
➤ Catalin Suciu commented:

Verifying as fixed on v9000 (24964)
