### ISSUE TITLE
Firefox crashes when scrolling "Recently visited" [lost my open tabs too!]

### ISSUE THREAD

**Issue by masterdezign** [mozilla-mobile/firefox-ios#12712]
## Steps to reproduce

Homepage: Recently visited -> Show All -> [scroll down]

### Expected behavior

Scrolling the list

### Actual behavior

Crashes

### Device & build information
* Device: Iphone 13 (Software version 15.7.1)
* Build version: 107.2 (22549)

### Notes
Attachments: 

Video (available temporarily) https://drive.google.com/file/d/19E-KdWX7EYiwmwcqZ4THqAezNdheANVq/view?usp=sharing

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5449)

**Comment by dnarcese** [comment]
@SimonBasca @masterdezign Is this still reproducible?

**Comment by masterdezign** [comment]
> @SimonBasca @masterdezign Is this still reproducible?

I don't observe this behavior on Firefox 108.1 (24234).
