### ISSUE TITLE
Add ProtonMail Option to MailApp Settings

### ISSUE THREAD

**Issue by ACK-J** [mozilla-mobile/firefox-ios#12714]
### User Problem
> Why should we implement this? What is the user benefit?

ProtonMail is a trusted mail application and has a similar ethos to the Mozilla foundation surrounding end user privacy. Many Firefox users likely use the ProtonMail app and thus I wanted to add the support for it.

### Ideas for Solution
> Let us know if you have an idea on how to solve this user problem

https://github.com/mozilla-mobile/firefox-ios/pull/12708

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5451)

**Comment by thatswinnie** [comment]
@ACK-J Thank you so much for adding support for ProtonMail!

Unfortunately opening ProtonMail from Firefox via a mailto link doesn't result in the email address being entered into the _to_ field. From what I could gather the [url scheme](https://github.com/ProtonMail/ios-mail/issues/27) that ProtonMail requires is different than what this PR is producing. The url scheme should be something like this
`"protonmail://mailto:foobar@foobar.org"`
while we produce
`"protonmail://to=foobar@foobar.org"`

Could you please address this?

**Comment by ACK-J** [comment]
@thatswinnie Thanks for digging that up. I'll make some modifications!

**Comment by ACK-J** [comment]
@thatswinnie I do not have the resources at the moment to build the application and verify if it works. But I believe it should solve the problem!

**Comment by data-sync-user** [comment]
➤ Catalin Suciu commented:

Verifying as fixed on latest v9000.
