### ISSUE TITLE
Library buttons color is not cyan in dark mode

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#12719]
### Steps to reproduce
1. Set theme to dark
2. Go to the bookmark pane
### Expected behavior
- “Done” and “Edit” button should have new color according to https://mozilla-hub.atlassian.net/browse/FXIOS-5371
### Actual behavior
- “Done and “Edit” have old color.
### Device & build information
* Device: iPhone 12 Pro (16.0.2)
* Build version: 109 (24441)
### Notes
Attachments: 

![20867F9B-575A-44BB-A302-FF265875AC7B](https://user-images.githubusercontent.com/32130829/208178941-266bd624-114f-4d91-9db6-b921b692f9e7.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5454)

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verifying as fix on v110 (26107)
