### ISSUE TITLE
The new tab does not open in attentive mode 

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#12728]
## Steps to reproduce
1. Visit a page
2. Open a new tab.
### Expected behavior
- The new tab should be opened in attentive mode with the keyboard displayed.
### Actual behavior
- The new tab is displayed.
### Device & build information
* Device: iPhone 12 Pro
* Build version: 109 (24633)
### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5458)

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Not reproducible on v109 (25480)
