### ISSUE TITLE
Option to move Tabs button to bottom

### ISSUE THREAD

**Issue by corv89** [mozilla-mobile/firefox-ios#1272]
Can we please get the option to move the Tabs button to the bottom right corner?

Anyone with a 'Plus' iPhone has a very hard time reaching for Tabs, which are essential to most people's browsing.

In my opinion bookmarking isn't important enough to justify placing it in the bottom right corner. Muscle memory from Safari will also serve many people well.

Thank you for your consideration.

**Comment by laeryn** [comment]
I second this

**Comment by splewako** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1242626

**Comment by Districtfine** [comment]
I'd like to see this feature as well, even putting a tabs option in the hamburger menu at the bottom would be a godsend

**Comment by teddybradford** [comment]
This would make browsing so much easier and faster, especially for people with large phones.

**Comment by yatli** [comment]
+1, not having bottom tab bottom makes it impossible for me to switch tabs with one hand.

**Comment by StefanoCecere** [comment]
this is solved in Firefox iOS 10 (beta today), right? can we close this issue?

**Comment by StefanoCecere** [comment]
QUESTION: are these GitHub issues useful? or should we use Bugzilla? to duplicate things is not good, right?
