### ISSUE TITLE
[iPad] The "Sync and Save Data" button should have proper size

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#12727]
## Steps to reproduce
1. Go to Tabs Tray
2. Go to Synced tab
### Actual behavior
- The "Sync and Save Data" button should have proper size.
### Device & build information
* Device: iPad Pro (16.0) 
* Build version: 109 (24498)
### Notes
Attachments: 

![Screen Shot 2022-12-19 at 15 41 18](https://user-images.githubusercontent.com/32130829/208439521-143e8ff3-703e-4749-a24b-f73952020b15.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5457)

**Comment by data-sync-user** [comment]
➤ Ekaterina Galetski commented:

Laurie MarceauCould we use the same size of the button both in landscape and portrait?

**Comment by data-sync-user** [comment]
➤ Raluca Iordan commented:

For QA: Please check that the button is centered as has a proper size, like in the pic from attachments. Thank you

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Verified as fixed in v9000 (29027) with iPhone 13 Pro (15.7.1).

To be re-checked when the official v112 will be built.Daniela Arcese Raluca Iordancan you please help me with the information regarding the Fix version and in what release this issue will be included?

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Verified as fixed in v110.2 (29283) with iPhone 13 Pro (15.7.1) and iPad mini 5 (14.7.1).
