### ISSUE TITLE
Firefox for iOS is forgetting login information and cookies after refreshing a tab

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#12740]
Users are reporting that Firefox for iOS is not consistently remembering their login details or cookie preferences in websites that require a login. Ex. forums, email providers, social media 

After you log in, if you switch to another app for a moment or refresh the tab, you'll appear logged out. 
Sometimes if you refresh the website several times, you'll appear logged back in. 

## Steps to reproduce
1. Open Firefox for iOS 
1. Go to a website and log in (ex. twitter) 
1. Switch to a different app OR switch to another tab OR refresh the tab 

### Expected behavior
Users should remain logged in since they haven't cleared their browsing data 

### Actual behavior
You appear logged out 

### Device & build information
OS 16.1 
Firefox v106 

### Notes
Continuation from #12279. Details below:

* Logic for caching credentials is fairly stringy and needs to be followed through. Original story wasn't enough time for this.
* Relevant files for investigation
  * begin with `BrowserViewController+WebViewDelegate` (which uses the `DownloadHelper` class and passes the webview's cookie store down)
  * `OpenInHelper`
  * `OpenPassbookHelper`
* What seems to be happening is that sometimes the cookie isn't saved properly when the site responds... but I'm not sure why and this requires further looking into
  * Not super easy to reproduce, but I've been able to reproduce in the following cases:
    * switching to a different app
    * switching to a different tab
    * refreshing the tab
    * force closing the app
  * I think there may be some delay in saving the cookie but I haven't been able to pin it down why
  * This doesn't happen on every site, but I've been able to reliably repro on beatport.com (as per @SimonBasca, and in Safari as well), and about 50% of the time on Twitter (but not in Safari)

Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5467)

**Comment by data-sync-user** [comment]
➤ Nishant Bhasin commented:

Make sure to check with Edge, Chrome and Brave to make sure this isn’t a WKWebview issue.

And we disabled a few items in the settings related to cross site tracking to check if it propagates to other apps

**Comment by esperecyan** [comment]
pixiv is easy to check because once it is in a logged out state, it does not restore even if I reload the tab.
https://www.pixiv.net/

I can reproduce this by force closing Firefox 109.0 (25841) with the pixiv tab open.

Doing the same with Google Chrome 110.0.5481.114 does not reproduce the problem.

**Comment by data-sync-user** [comment]
➤ Yoana Rios Diaz commented:

This PR ( https://github.com/mozilla-mobile/firefox-ios/pull/13472 ) is an attempt to improve the way we manage AuthenticationChallenge delegates from Webkit, using the default handler which should provide a behavior closer to Safari. After this improvements I couldn’t reproduce anymore the logout from Twitter (stayed login thought the weekend), however the issue is still easy to reproduce with http://beatport.com ( http://beatport.com|smart-link )  but because is also reproducible with Safari and other browsers I don’t is an issue on our side.

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Verified as fixed on v112 (29913) with iPhone 13 Pro (15.7.1).

I used: 

  * Linkedin
  * Twitter
  * Facebook
  * Discord

With multi-task to another app and also refresh of the tab but everything worked well.

**Comment by laptopleon** [comment]
This indeed has not been solved. I didn't want to say this immediately because I wanted to give it some time, to test it.

We have a [forum thread on tweakers.net discussing](https://gathering.tweakers.net/forum/list_messages/2147114) it (in Dutch) for half a year, but as users we can't do much about it.

**Comment by alcortazzo** [comment]
Here are two issues with a similar problem with cookies #13520 #14030

**Comment by pashynskykh** [comment]
This has not been fixed. After closing FF and locking the screen, I get logged out of the sites I use.

**Comment by locolau** [comment]
The issue is still there, please check, open and fix.

**Comment by mcfilib** [comment]
this is still broken. please consider re-opening the issue

**Comment by oubrecht-com** [comment]
I have the same problem too. Firefox 115.1 in iOS. 
I log to web app. I kill Firefox and all cokkies for page are lost.

**Comment by pashynskykh** [comment]
Is Firefox for iOS abandoned? It has been almost a year since this issue was reported. And FF still continues to delete cookies after you close a tab and lock your screen. It's like having a car with a GIANT hole in the gas tank. You can't drive such a car. And you can't use a browser with such a problem.

**Comment by oubrecht-com** [comment]
Firefox 129.1 has this bug again.

**Comment by arseniigorkin** [comment]
FF 129.1 on iOS 16.7.8 - after even has been reinstalled completely FF forgets cookies after every restart of the app.
Devs, please, answer!
