### ISSUE TITLE
Pages in Shift-JIS encoding do not render correctly

### ISSUE THREAD

**Issue by dbrock98** [mozilla-mobile/firefox-ios#12786]
## Steps to reproduce
Open a page in Firefox iOS that is encoded in Shift-JIS encoding.
Example: http://www.st.hirosaki-u.ac.jp/~earth_atmhyd/monthly2/pH.htm

### Expected behavior
Page renders correctly with Japanese characters. (Confirmed that the page loads correctly in Firefox 108.0.1 on Windows)

### Actual behavior
Page renders with a mix of garbled ASCII characters.

### Device & build information
* Device: iPhone 13 Pro
* Build version: 108.1 (24234)
### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5492)

**Comment by dnarcese** [comment]
This site is rendering the same way on Safari, so this is a WebKit issue and not something we can fix.
