### ISSUE TITLE
Firefox Account icon in the application menu is a black circle

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/firefox-ios#12785]
## Steps to reproduce

1. Install TestFlight build 109.0 (24498). 
2. Log into your Firefox Account. 
3. Open the application menu. 

### Expected behavior

The account icon should show my account picture. 

### Actual behavior

The account icon in the menu is a black circle:

![F42FDE5E-7228-48BF-A373-26B6F29284C4](https://user-images.githubusercontent.com/629193/209040475-8b5b85aa-3210-46e8-842b-a15b0ae21f0a.jpeg)

### Device & build information

* Device: iPhone 12 with iOS 16.1.2
* Build version: **This bug is a regression in v109.** I can reproduce this bug in 109.0 (24271) and 109.0 (24498), but not 108.0 (23855).

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5491)

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Marking this issue as verified fix on v109 (25580). 
Note that we’ve logged and issue while testing the account management picture: https://github.com/mozilla-mobile/firefox-ios/issues/12901 ( https://github.com/mozilla-mobile/firefox-ios/issues/12901|smart-link )
