### ISSUE TITLE
"Send Link to Device" on a page in reader view sends a `http://localhost:6571/reader-mode/` URL to the other device

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/firefox-ios#12807]
## Steps to reproduce

1. Install Firefox iOS TestFlight build 108.0 (23264) or later.
2. Log into a Firefox Sync account with a desktop computer registered.
3. Load a web page, such as https://blog.mozilla.org/en/products/firefox/firefox-tips/internet-safety-for-families-total-cookie-protection
4. Tap the Reader View button in the address bar.
5. Tap the Share button ⬆️ in the address bar.
6. Send the page to a desktop computer.

### Expected behavior

The page should open on the desktop computer with URL
`https://blog.mozilla.org/en/products/firefox/firefox-tips/internet-safety-for-families-total-cookie-protection/`.

### Actual behavior

The page opens on the desktop computer with the reader view URL `http://localhost:6571/reader-mode/page?url=https://blog.mozilla.org/en/products/firefox/firefox-tips/internet-safety-for-families-total-cookie-protection/`, which shows an error page: `Firefox can’t establish a connection to the server at localhost:6571.`

### Device & build information

* Device: iPhone 12 running iOS 16.2.3
* Build version: **This bug is a regression in build 108.0 (23264)**, the build where the Share button ⬆️ was added to the address bar. The previous build, 108.08 (22972), sends the correct page URL.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5501)

**Comment by data-sync-user** [comment]
➤ Catalin Suciu commented:

Yoana Rios Diaz This issue is still reproducible on latest v9000 and v110 builds.

**Comment by data-sync-user** [comment]
➤ Yoana Rios Diaz commented:

Catalin Suciu the issue should be properly fixed on latest v9000

**Comment by data-sync-user** [comment]
➤ Catalin Suciu commented:

Thanks Yoana Rios Diaz . Verifying as fixed on v9000 (27008).

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Verified as fixed on v111 (28263) with iPhone 13 Pro (15.7.1).

When I sent the link from the device it was correctly displayed on desktop.
