### ISSUE TITLE
Top sites' "Remove" menu item doesn't remove the site from the Firefox homepage

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/firefox-ios#12809]
## Steps to reproduce

1. On the Firefox homepage, long press on a top site that is not a pinned shortcut.
2. Select the "Remove" menu item in the popup dialog.
 
### Expected behavior

The top site should be removed.

### Actual behavior

Nothing happens. The top site is not removed.

Removing pinned shortcuts with the “Remove” menu item works correctly.

### Device & build information

* Device: iPhone 12 running iOS 16.2
* Build version: 109.0 but I can reproduce in older builds like 106.0.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5502)

**Comment by cpeterso** [comment]
![65D6B6F1-E002-42F4-9FF7-3C26D0D6B05D](https://user-images.githubusercontent.com/629193/209713298-7c8ee564-a340-48e8-b4a5-8df96ab3afba.jpeg)

**Comment by adudenamedruby** [comment]
Heya @cpeterso, do you have any other steps for reproducing? I've tried and can't reproduce on 108.1 prod build.

https://user-images.githubusercontent.com/11182210/209826109-2df500ac-7e7a-4a1e-8a1b-bde1165bf311.MOV

**Comment by cpeterso** [comment]
> Heya @cpeterso, do you have any other steps for reproducing? I've tried and can't reproduce on 108.1 prod build.

Sorry, I don't have any more details to the STR. Removing works on some of my devices, but not others.

* My iPhone 12: 108.1 prod works 😃 
* My iPhone 12: 109 and earlier TestFlight does not work ☹️
* My iPhone 13: 108.1 prod does not work ☹️
* My iPad: 107 and 108.1 prod works 😃

I wondered whether Firefox Sync might be part of the problem (resurrecting removed sites), so I disconnected and could still reproduce.

**Comment by data-sync-user** [comment]
➤ Daniela Arcese commented:

Let’s see if the migration to a-s Places fixes this. It should be rolling out in 110.

**Comment by cpeterso** [comment]
Verified fixed in Nightly 1/11. 👍🏻
