### ISSUE TITLE
Extreme Performance Issues in v108.1

### ISSUE THREAD

**Issue by greimers** [mozilla-mobile/firefox-ios#12814]
## Steps to reproduce

Since a few days, when I just browse the web (any website) Firefox will use almost all CPU capacity to the point that my phone gets hot and unresponsive. 

### Expected behavior

Browsing should not have unusual performance impact. 

### Actual behavior

First scrolling gets very laggy, then the app and the iPhone become unresponsive until Firefox is force quits. 

### Device & build information

* Device: iPhone 12 mini with iOS 16.2
* Build version: 108.1 (24234)

### Notes

I have this problem only in Firefox. Other browsers like Safari or Orion work fine. 

### Attachments

I wanted to make a screen recording but it didn't work because Firefox takes up so much CPU time that the recording would keep aborting.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5504)

**Comment by adudenamedruby** [comment]
Heya, this sounds rough. I took a brief look at 108.1's health in Xcode and nothing seems out of the ordinary. I've not experienced this at all either on my personal device.

However, thanks for filing this bug. This is something we'll keep an eye on, because it's definitely undesired behaviour.

Do you have more info on what's happening?
* How many tabs do you have open?
* If it's crashing, is it attempting to restore tabs and crashing during that process, or are tabs restoring fine, and then, in general use, it heats up and eventually crashes?

I'd be curious to know if you deleted Firefox and then reinstalled it, if the problem persists.

**Comment by greimers** [comment]
Yes, deleting and re-installing Firefox has solved the issue.
I really can't tell what might have triggered this problem. It just occurred from one day to the next and it did not resolve by itself (I tried for two days).

I could reproduce the issue with only a single tab open and after a few seconds of scrolling through any page (like NY Times, or Ars Technica). Firefox would not crash but become basically unusable, so I had to force quit it. It would even impact the responsiveness of the rest of iOS for a few seconds after Firefox was quit. (Maybe it's a memory leak and the system needed a few seconds to free the RAM again.)
I had also tried restarting the iPhone but the problem would just re-appear. 

I assume something got messed up with my local data.

**Comment by OrlaM** [comment]
Hi @greimers, that is really helpful info. Can you confirm if you were signed into sync when the issue was occurring and if you are now signed into sync after the issue has gone away?

**Comment by greimers** [comment]
Yes, I was signed into Sync and also signed back in right after re-installing Firefox. 
(BTW, it would be great if sync also stored the settings. But that's a different issue.)

One more info on this:
When the issue arised, I was on the train and had varying connection quality (between no network at all and perfect 5G). But it would not recover even when I was back home with fast and stable network.

**Comment by OrlaM** [comment]
Thanks for the update, this issue has been on our radar for a while so the detailed account of what was going on at the time is very helpful. Hopefully it doesn't reoccur, but if it does it would be great if you could capture some logs and share them with us.
https://github.com/mozilla-mobile/firefox-ios/wiki/How-to-get-your-device-logs

**Comment by dnarcese** [comment]
I am going to close this until we get more reports or get logs of the issue!
