### ISSUE TITLE
The spacing on the home page is sometimes very spread out

### ISSUE THREAD

**Issue by OrlaM** [mozilla-mobile/firefox-ios#12815]
## Steps to reproduce
Launch the app and view the home page. 
It only happens intermittent and usually scrolling around a little fixes the issue.

### Expected behavior
The spacing should be consistent and not very spread out.

### Actual behavior
The spacing is inconsistent and sometimes very spread out.

### Device & build information
* Device: iPhone 13
* Build version: 109

Attachments: 
![Screen Shot 2022-12-28 at 11 17 58 AM](https://user-images.githubusercontent.com/3929954/209841689-40a445a0-4309-4227-96d2-d5ba51cbffbc.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5505)

**Comment by data-sync-user** [comment]
➤ Daniela Arcese commented:

Could this be a result of https://mozilla-hub.atlassian.net/browse/FXIOS-4549 ( https://mozilla-hub.atlassian.net/browse/FXIOS-4549|smart-link )?

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Verified as fixed on v110 (26107) with iPhone 13 Pro (15.7.1).
