### ISSUE TITLE
Reader view caching

### ISSUE THREAD

**Issue by SeaKhaki** [mozilla-mobile/firefox-ios#12827]
## Steps to reproduce

Save a page to your reading list.

Specifically, do not open the page in reader view before doing this. In a regular window save via the hamburger menu. In a private window this behaviour is encountered regardless of how you save the page.

This step prevents the page data from being cached.

### Expected behavior

Upon opening the page from your reading list, it should load. This should apply both online and offline.

### Actual behavior

When opening the page from your reading list either online or offline, the page fails to load.

### Device & build information
* Device: *
* Build version: Latest App Store

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5512)

**Comment by SeaKhaki** [comment]
Additionally, reloading a page while in reader mode causes it to hang in the same state.

**Comment by lmarceau** [comment]
This duplicates https://github.com/mozilla-mobile/firefox-ios/issues/12685
