### ISSUE TITLE
Bugged Bookmark page 

### ISSUE THREAD

**Issue by Dav-Humph-874987** [mozilla-mobile/firefox-ios#12820]
## Steps to reproduce
Click on the Bookmark Icon 

### Expected behavior
Bookmark page shows up without crash

### Actual behavior
Firefox crashed 

### Device & build information
* Device: iPad Air (5th Generation)
* Build version: Firefox 108.1 (24234)
### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5507)

**Comment by lmarceau** [comment]
Hello @Dav-Humph-874987, 
does this happen on a specific bookmark only or on all bookmarks?

**Comment by dnarcese** [comment]
Duplicate of #12093
