### ISSUE TITLE
FxiOS crashing on startup

### ISSUE THREAD

**Issue by plwt** [mozilla-mobile/firefox-ios#12836]
## Logs
Further to a question in the SUMO support forum at https://support.mozilla.org/en-US/questions/1386255

Logs at https://paste.mozilla.org/wfN0hcM5  (valid for 3 weeks 2 days from today)

## Steps to reproduce
Crashing when a user opens FxiOS

### Device & build information
* Device: iPhone XS
* Build version: iOS 16.02, latest release of FxiOS

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5515)

**Comment by lmarceau** [comment]
Hello! Since this is a crash it would be helpful to get the crash log too, if ever possible. The link logs are Firefox logs. Thank you!

**Comment by plwt** [comment]
Crash log from user at https://paste.mozilla.org/DgzSWJHg

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Hello, Orla MitchellandLaurie Marceauas the user responded that after v109 he wasn’t experiencing the crash anymore, do you think we can close this one? 
Now we have a crash but is not related to this one (the glean one).

!image-20230301-131145.png|width=826,height=344!

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Thank you, Orla Mitchell.

Verified as fixed in v9000 (29027) with iPhone 13 Pro (15.7.1) and closing this based on the comments below.
