### ISSUE TITLE
The theme is broken after STR.

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#12831]
## Steps to reproduce
1. Change time to next day
2. Change theme from light - dark or vice-versa 
3. Open app
4. Open menu 
### Expected behavior
- The theme should be correctly displayed.
### Actual behavior
- The theme is broken after STR.
### Device & build information
* Device: iPhone 12 Pro (16.1
* Build version: 109 (24805)
### Notes
- The them is also broken in tabs tray and library panels
Attachments: 

![Screenshot](https://user-images.githubusercontent.com/32130829/210368747-e2cdae72-e076-4007-a465-ecaef20457db.jpg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5513)

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Marking as verified fix on v109.0 (25431)
