### ISSUE TITLE
Update theming in UpdateViewController

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#12855]
Update theming in UpdateViewController to use the new theming system following [guidelines](https://github.com/mozilla-mobile/firefox-ios/wiki/Theming-system)

* `Themeable` and `ThemeApplicable` are used where necessary.
* `UIColor.Photon`or `UIColor.theme` should not be called at all.
* LegacyThemeManager should not be used.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5531)

**Comment by bmihai23** [comment]
Hello, I would like to work on this ticket if it's still available.

**Comment by PARAIPAN9** [comment]
Sure, go ahead!! CC: @lmarceau

**Comment by data-sync-user** [comment]
➤ Sophie Amin commented:

Laurie Marceau It looks like this ticket has been done by a contributor and should be closed? 👀
