### ISSUE TITLE
Update theming in QR code view controller

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#12859]
Update theming in `QRCodeViewController` to use the new theming system following [guidelines](https://github.com/mozilla-mobile/firefox-ios/wiki/Theming-system).

* `Themeable` and `ThemeApplicable` are used where necessary.
* `UIColor.Photon` or `UIColor.theme` should not be called at all.
* LegacyThemeManager should not be used.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5535)

**Comment by data-sync-user** [comment]
➤ Sorin Paraipan commented:

Flash OFFFlash ONthumbnail ( https://github.com/mozilla-mobile/firefox-ios/assets/51127880/0579b93c-4f0b-4ec0-a659-8c3267e39c05 )thumbnail ( https://github.com/mozilla-mobile/firefox-ios/assets/51127880/626618f0-c86b-42ff-81a5-716b49d5f230 )For QA: The QR Scanner should look like screenshots above.

**Comment by DianaBarladeanu** [comment]
Verified as fixed on v9000 (33001) with iPhone SE (16.5).
