### ISSUE TITLE
Password manager non viable

### ISSUE THREAD

**Issue by magicman0978** [mozilla-mobile/firefox-ios#12866]
## Steps to reproduce
Enable Firefox as the password manager on iOS

### Expected behavior
I expect the password manager to pop up and allow me to auto fill immediately or within a couple of seconds

### Actual behavior
The password manager takes a full 15 seconds to load

### Device & build information
* Device: iOS 16.2 on iPhone 14 pro max 
* Build version: Firefox 108.1 (24234)
    1. Notes
I realize this seems like a small problem, but literally every other password manager of ever use loads up in under 2 seconds as evidenced in the attachment. This includes Firefox’s own Lockwise password manager. To discontinue a product that you make only to replace it with one that is significantly worse it’s not OK.
Attachments: 
[See Attached ](https://share.icloud.com/photos/05bi0vAxUYo1ZcIuUEZjS0GOg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5546)

**Comment by dnarcese** [comment]
I am seeing the attachment as a photo instead of a video. Could you try uploading a video directly to this issue? Thanks!
