### ISSUE TITLE
With sync on, crashes immediately upon starting

### ISSUE THREAD

**Issue by sridharb1** [mozilla-mobile/firefox-ios#12876]
Without sync, application works fine. The crash has only recently started happening, as in possibly the last couple of months.

crash report from phone attached. This is very reproducible, but sometimes it takes a little while for it to start crashing. But once it starts, the only remedy is to delete firefox along with its data, reinstall and not turn on sync. Very frustrating.

Please let me know if you need any more details.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5557)
[Client-2023-01-06-064028.ips.txt](https://github.com/mozilla-mobile/firefox-ios/files/10356679/Client-2023-01-06-064028.ips.txt)

**Comment by SimonBasca** [comment]
@sridharb1 thanks for the feedback. I will try to reproduce this issue. In the meantime could you share your sync options? Go to Settings -> Tap on the Account name and let me know if all the sync settings are turned on. Also could you check this on your desktop?

**Comment by sridharb1** [comment]
Thank you for the prompt response and I hope this is fixed as it was working a while ago (I have been having problems for about two months, not able to report it through firefox itself as it crashes before I can send the report and general inertia thinking that this is a common problem that will be resolved in the next version).

The sync in the desktop is working fine. Options shown below in the attachment. I have not customized the sync options on the mobile browser, but I can try. However, I believe I have been using it with it all turned on.

![image](https://user-images.githubusercontent.com/13346687/210972883-9f89799d-8f3d-4684-8022-be4c8e2559a0.png)

**Comment by lmarceau** [comment]
Thank you @sridharb1 for opening this crash issue and thank you for the log. This seems to be one of our most high occurrence crashes. There's a possible improvement for this issue in v109 that should be released around Jan 17th. It would be really helpful to us after upgrading to that version if you could tell us if you still experience this issue. Thank you!

Note: The important part of the stacktrace:
```
{"imageOffset":516944,"symbol":"closure #1 in Deferred._fill(value:assertIfFilled:)","symbolLocation":236,"imageIndex":0},
{"imageOffset":476028,"symbol":"partial apply for closure #1 in LockProtected.withWriteLock<A>(block:)","symbolLocation":92,"imageIndex":0},
{"imageOffset":472988,"symbol":"CASSpinLock.withWriteLock<A>(block:)","symbolLocation":164,"imageIndex":0},
{"imageOffset":475888,"symbol":"LockProtected.withWriteLock<A>(block:)","symbolLocation":156,"imageIndex":0},
{"imageOffset":513416,"symbol":"Deferred._fill(value:assertIfFilled:)","symbolLocation":476,"imageIndex":0},
{"imageOffset":33848,"symbol":"CancellableDeferred.fill(_:)","symbolLocation":40,"imageIndex":0},
{"imageOffset":465932,"symbol":"closure #1 in SQLiteHistory.retrieveTopSiteSQLiteHistoryFaviconImage(faviconURL:)","symbolLocation":284,"imageIndex":1},
{"imageOffset":435200,"symbol":"partial apply for closure #1 in ImageLoadingHandler.getImageFromCacheOrDownload(with:limit:completion:)","symbolLocation":72,"imageIndex":0},
{"imageOffset":438080,"symbol":"closure #2 in ImageLoadingHandler.downloadImageOnly(with:limit:completion:)","symbolLocation":212,"imageIndex":0},
{"imageOffset":506260,"symbol":"partial apply for closure #1 in closure #1 in ImageDownloader.createCompletionCallBack(_:)","symbolLocation":24,"imageIndex":2},
{"imageOffset":506292,"symbol":"partial apply for thunk for @escaping @callee_guaranteed (@guaranteed ImageDownloader, @in_guaranteed Result<ImageLoadingResult, KingfisherError>) -> ()","symbolLocation":20,"imageIndex":2},
{"imageOffset":506596,"symbol":"partial apply for specialized closure #1 in Delegate.delegate<A>(on:block:)","symbolLocation":104,"imageIndex":2},
{"imageOffset":504620,"symbol":"partial apply for closure #2 in closure #1 in closure #1 in ImageDownloader.startDownloadTask(context:callback:)","symbolLocation":128,"imageIndex":2},
{"imageOffset":611128,"symbol":"partial apply for closure #1 in CallbackQueue.execute(_:)","symbolLocation":20,"imageIndex":2},
{"imageOffset":611128,"symbol":"partial apply for closure #1 in CallbackQueue.execute(_:)","symbolLocation":20,"imageIndex":2},
{"imageOffset":41704,"symbol":"thunk for @escaping @callee_guaranteed () -> ()","symbolLocation":28,"imageIndex":2},
```

**Comment by sridharb1** [comment]
Thank you. Happy to try the new version. But, why the “possible fix” verbiage? Wondering if there are multiple problems here?

**Comment by lmarceau** [comment]
@sridharb1 We haven't been able to reproduce the problem on our side so far, hence I would not say this would be fixed entirely if I can't confirm. The fix has the possibility to resolve the problem, or at least help us debug what is going on there.

**Comment by sridharb1** [comment]
I can confirm that v109 fixes this problem. Thank you for working on it.
