### ISSUE TITLE
Fix deprecation warning 'requestReview()' was deprecated in iOS 14.0

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#12881]
We’re using requestReview() in the RatingPromptManager which is deprecated in iOS 14. We should migrate to using newest API while keeping same behavior, so the day we drop support for iOS 13.0 we’re already using the right API

!Screen Shot 2023-01-05 at 5.10.32 PM.png|width=523,height=61!

![Screen Shot 2023-01-05 at 5 10 32 PM](https://user-images.githubusercontent.com/11338480/211057083-59bdbd67-9ec8-4793-91c9-4ac3c9e97f7a.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5559)

**Comment by rossmassey** [comment]
Hi I am new to swift and contributing

I think this is the part triggering the warning: [Client/RatingPromptManager.swift, line 132](https://github.com/mozilla-mobile/firefox-ios/blob/5203aecbf22893d2e059a84885399474a899f819/Client/RatingPromptManager.swift#L132) (not able to access xcode atm)

It seems like `requestReview()` just needs to be replaced with `requestReview(in:)`
https://developer.apple.com/documentation/storekit/skstorereviewcontroller/3566727-requestreview

One [suggestion](https://stackoverflow.com/questions/63953891/requestreview-was-deprecated-in-ios-14-0) I found is to do it this way:
```swift
if let scene = UIApplication.shared.connectedScenes.first(where: { $0.activationState == .foregroundActive }) as? UIWindowScene {
    DispatchQueue.main.async { // claimed to be more reliable, not necessary
        SKStoreReviewController.requestReview(in: scene)
    }
}
```


I am not sure what would need to happen for the else (just do nothing?)

Let me know if this is the right track for this sort of task

**Comment by lmarceau** [comment]
Heya @rossmassey, sounds good! You'll need to use `if #available(iOS 14.0, *) {` in the meantime since we're still supporting iOS 13.0 and up, but your solution seems great to me. You can ask me for review whenever you open a PR for this 🙏

**Comment by rossmassey** [comment]
@lmarceau Hi I created a PR here: https://github.com/mozilla-mobile/firefox-ios/pull/12951

**Comment by data-sync-user** [comment]
➤ Laurie Marceau commented:

For QA, it can be tested that the rating prompt works as it was before on any device newer than iOS 14.0. Note that the rating prompt won’t appear on Testflight build, but will appear on builds that are installed from Xcode (dev builds).

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Hello, Laurie Marceauas the rating prompt is displayed only once/device it’s a little bit tricky or hard to manage. I’m not really sure how this affects the Xcode building if the date will be changed for the emulator in order for the Rating prompt to be displayed.

Is there something we can add in the app like a debug option to display the rating prompt in order to test it without problems? 
We will keep trying, maybe without too many changes we will be able to verify it on the emulator (without changing the date).

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Verified as fixed on the latest master. 

!image-20230308-122906.png|width=622,height=837!
