### ISSUE TITLE
The keyboard is quickly dismissed after opening the app after +4h of inactivity

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#12902]
## Steps to reproduce
1. Close the app if previously opened
2. Set time to + 4h
3. Launch the app
### Expected behavior
- The app opens and the keyboard is displayed with the URL bar focused
### Actual behavior
- The app opens with the keyboard displayed but it's quickly dismissed.
### Device & build information
* Device: iPhone 13 mini (16.0.2)
* Build version: 109 (25540)
### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5568)

**Comment by dnarcese** [comment]
Duplciate of #12884
