### ISSUE TITLE
The default account icon is displayed instead of account picture

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#12901]
## Steps to reproduce
1. Have an image set to the FxA account
2. Log in to FxA
3. Tap on the hamburger menu
4. Tap Settings
5. Observe the Firefox Account icon
### Expected behavior
- The account image should be diplated
### Actual behavior
- The default account icon is displayed.
### Device & build information
* Device: iPhone 13 mini (16.0)
* Build version: 109.0 (25540)
### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5567)

**Comment by data-sync-user** [comment]
➤ Winnie Teichmann commented:

Simion Basca I am unable to reproduce this. Could you please check if you still see that on main?

**Comment by SimonBasca** [comment]
@thatswinnie try these steps:
1. User is logged in to FxA
2. Close app from app switcher
3. Launch the app
4. Tap the hamburger menu
5. Tap "Settings"
6. Observe the Firefox Account icon

After some time the account picture is displayed but after restarting the app the the default icon is displayed again.

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verifying as fix on v9000 (26871)

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verified fix on v111.0 (28148)
