### ISSUE TITLE
[Experiment] The 3000 string is written as `3&thinsp;000` in the German version of the Treatment A branch message

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla-mobile/firefox-ios#12903]
## Preconditions
- Have the **Firefox Release 109 (25540)** available through TestFlight.
- Have the device language set to German.

## Steps to reproduce

1. Install Firefox Release from TestFlight and open it.
2. Navigate to the Settings menu and scroll down the page.
3. Tap the Firefox version 5 times and scroll down the page.
4. Tap the Experiments option and tap the `iOS Message Experiment: Default Browser Card` experiment option.
5. Tap the `treatment-a` option and fully close the app.
6. Open the Firefox browser and observe the homepage.

### Expected behavior
- The message is displayed without any string errors.

### Actual behavior
- An extra `&thinsp;` string is displayed in the number from the message.

## Device & build information
* Device: iPhone XR - iOS 16.2, iPad Air 2 - iOS 15.7.2, iPhone 11 - iOS 16.2
* Build version: Firefox Release 109 (25540), Firefox Release 109 (25480)

### Notes
- The issue is NOT reproducible on the other languages that the message will be going on.
- The issue is NOT reproducible on the other branches of the experiment with the German language.

Attachments: 

![7E89F977-031B-4865-9247-ECCF83F49C74](https://user-images.githubusercontent.com/18304511/211314608-a2222de2-53fe-4d45-aa1a-d9b0f3634653.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5569)

**Comment by Delphine** [comment]
Looks like a mistake. I updated the string in Pontoon and flagged the localizer. thank you

**Comment by dnarcese** [comment]
Build #25841 has the fix

**Comment by SoftVision-CiprianMuresan** [comment]
I have verified that the issue is no longer reproducible on the Fx 109 (25841) build.
