### ISSUE TITLE
Auto generate license comment in header for files created in BrowserKit

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#12908]
Auto generate the license comment that is at the top of every source file when creating a file for BrowserKit through XCode, similar to how it works when creating a file for the main app.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5571)

**Comment by nishant2718** [comment]
All signs point to making an `IDETemplateMacros.plist` located in `.swiftpm/xcode/package.xcworkspace/xcshareddata/` but this doesn't seem to work. 

This is a nice to have, so we can revisit when there's more information on this topic.

**Comment by data-sync-user** [comment]
➤ Razvan Litianu commented:

IDETemplateMacros.plist spent some time on Focus and it works when you put it inside Client.xcodeproj.
