### ISSUE TITLE
The "x" button is not tappable when running `testUpdateCounter`

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#12917]
We have one automated test that's failing `testUpdateCounter`. This test is covering the following scenario from the STR.

## Steps to reproduce
1. Open 3 tabs
2. Close the second tab
### Expected behavior
- Two tabs should be displayed
### Actual behavior
- Three tabs are displayed.
### Device & build information
* Device: iPad Pro (16.0)
* Build version:  6bdc4d83b2e5aca6d90efd38659a17fd6675948d
### Notes
- Note while running the test the "X" button from top tabs is not functional.
- I noticed with the accessibility inspector that there is and overlay over the "X" button see video.
- I was unable to reproduce this manually but I assume it can happen.
- Issue reproducible in the past https://github.com/mozilla-mobile/firefox-ios/issues/8613
Attachments: 

https://user-images.githubusercontent.com/32130829/211572759-2becfddf-16c6-474b-b18d-03060a840688.mov

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5578)

**Comment by clarmso** [comment]
I was investigating this test failure on closing tabs on iPad. The issue affects iOS 16.0 but not iOS 16.1. I suggest us to upgrade to XCode 14.1 together with iOS 16.1 and try again. 😄 
https://github.com/mozilla-mobile/firefox-ios/pull/12842

**Comment by SimonBasca** [comment]
Let's close this since it not reproducible on latest iOS version and it's not reproducible manually.
