### ISSUE TITLE
fire fox crashes everytime on launch

### ISSUE THREAD

**Issue by Chipbzd** [mozilla-mobile/firefox-ios#12924]
## Logs
You can help us by sending us either your crash logs or Firefox logs. Instructions on how to do this [here](https://github.com/mozilla-mobile/firefox-ios/wiki/How-to-get-your-device-logs).

## Steps to reproduce
just try to relaunch firfox
### Expected behavior
crashes get message about it crashed
### Actual behavior
When you try and launch firefox it immediately crashes. just started doing this yesterday. last phone update was last week. Firefox worked fine till yesterday....  Deleted app, rebooted phone, reinstalled app get same result. none of the other ideas worked
### Device & build information
* Device: ?  Iphone 13pro  running IOS16.2
* Build version: ? firefox 108.1

### Notes
Attachments: 
[browser.20230110T234118-0500.log](https://github.com/mozilla-mobile/firefox-ios/files/10393002/browser.20230110T234118-0500.log)
[browser.20230110T234124-0500.log](https://github.com/mozilla-mobile/firefox-ios/files/10393004/browser.20230110T234124-0500.log)
[sync.20230110T234124-0500.log](https://github.com/mozilla-mobile/firefox-ios/files/10393005/sync.20230110T234124-0500.log)
[browser.20230110T233202-0500.log](https://github.com/mozilla-mobile/firefox-ios/files/10393007/browser.20230110T233202-0500.log)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5585)

**Comment by dnarcese** [comment]
This crash should be fixed by v110. We will re-open it then if it is still not resolved.

**Comment by Chipbzd** [comment]
When is version 110 due to be released?

**Comment by dnarcese** [comment]
> When is version 110 due to be released?

Feb 14
