### ISSUE TITLE
Update nimbus-experiments action before Github action deprecation

### ISSUE THREAD

**Issue by jeddai** [mozilla-mobile/firefox-ios#12933]
Github is making a significant number of changes to the action workflow, and certain actions need to be updated as a result. 

See [here](https://github.com/mozilla-mobile/update-experiments/pull/3) for more details.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5587)

**Comment by lmarceau** [comment]
Work done in https://github.com/mozilla-mobile/firefox-ios/pull/12935
