### ISSUE TITLE
Shortcuts in iOS Broken

### ISSUE THREAD

**Issue by demgespenst** [mozilla-mobile/firefox-ios#12940]
## Steps to reproduce
Open a Webpage, Click share Button to add it to the startpage Shortcuts, but the side wont be added.
### Expected behavior
Shortcut should be added to startpage 
### Device & build information
* Device: iPhone 12 Pro
* Build version: iOS 16.2 20C65
Firefox Version 108.1 24234
### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5591)

**Comment by SimonBasca** [comment]
@demgespenst could you please specify on what Firefox version are you experiencing the issue? Also could you add a video of the issue?

**Comment by tarikeshaq** [comment]
This might be fixed in https://github.com/mozilla-mobile/firefox-ios/pull/12579 (i.e in Firefox 109)

**Comment by demgespenst** [comment]
> @demgespenst could you please specify on what Firefox version are you experiencing the issue? Also could you add a video of the issue?

Added the Firefox Version in the Post above. 
If the Issue persists in Version 109 i will add a Video

**Comment by demgespenst** [comment]
Version 109 fixed the issue.
