### ISSUE TITLE
Syncing issue on Firefox iOS/iPadOS

### ISSUE THREAD

**Issue by KevinW711** [mozilla-mobile/firefox-ios#12956]
## Steps to reproduce
Go to YouTube landing page and select a video to watch. Watch the video for 10 seconds or so (at which point a default tab sync-up normally occurs), and check to see if that tab is visible on other devices' sync chain. Instead of showing the correct page corresponding to the video, the tabs list will still show the YouTube landing page. The same problem occurs with several other sites, including Twitter (where you can navigate to the home page, then select a tweet, wait ten seconds, and check to see that the tabs list is accurate -- it won't be).

### Expected behavior
Navigating to a new page/video/tweet within Firefox should trigger a time-lapsed automatic sync that shows up on other devices on the sync chain.

### Actual behavior
Navigating links within sites like Twitter or YouTube does not trigger automatic syncing, thus displaying incorrect tabs on the sync chain.

### Device & build information
* Device: iPhone 13 mini and iPad Pro 9.7 inch running iOS 16.2
* Build version: Firefox 109

* 

### Notes
Please inform if others are able to reproduce this issue.

Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5600)

**Comment by dnarcese** [comment]
Tested this out, even after forcing a sync, it is still showing the youtube homepage. If I open a new tab and force sync, the youtube tab updates to the video.

**Comment by KevinW711** [comment]
> Tested this out, even after forcing a sync, it is still showing the youtube homepage. If I open a new tab and force sync, the youtube tab updates to the video.

Thanks. This aligns with what I have seen, and it also happens when browsing Twitter (and maybe other sites?). If you click on a specific tweet, the sync chain still just shows the Twitter home page and won't sync up properly unless you take additional steps like opening a new tab and force-syncing.
