### ISSUE TITLE
Remove Deferred from UIPasteboard+Extension 

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#12963]
General guidelines to remove deferred:

* Use completion handler where needed since this is “old code“ (in new code we might prefer async await).
* Add unit tests to ensure change is proper

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5605)

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verifying as fix v9000 (26871)

**Comment by SimonBasca** [comment]
Verifying as fix on v111 (28263)
