### ISSUE TITLE
Text indicator is not aligned with the placeholder text

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#12970]
## Steps to reproduce
1. Go to Settings -> Search Engine -> Tap “Add custom engine”
### Expected behavior
- Text indicator should be aligned with the placeholder text
### Actual behavior
- Text indicator is not aligned with the placeholder text
### Device & build information
* Device: iPad Pro (16.2)
* Build version: 110 (26107)
### Notes
Attachments: 

![18956DA5-31CD-48FB-9A8B-C450A7B47200](https://user-images.githubusercontent.com/32130829/213154717-376c36bc-838d-434e-b787-f9a9c24019b0.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5612)

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verifying as fix on v9000 (26871)

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verifying as fix on v111 (28148)
