### ISSUE TITLE
Tab is not scrolled into view when the inactive list is populated

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#13029]
## Steps to reproduce
1. Have the inactive list populated
1. Open a few tabs to enable scrolling on the tabs tray
1. Tap on the first tab from tabs tray
1. Close the selected tab
    1. Expected behavior

* The tab selector moves to the last tab and the tab is scrolled to view.
    1. Actual behavior
* The tab selector moves to the last tab but the tab is not scrolled to view.
    1. Device & build information
* Device: iPhone 13 mini (16.1)
* Build version: 110 (26279)
    1. Notes
Attachments: 

https://user-images.githubusercontent.com/32130829/214540875-58b52cde-3ede-46c8-a988-e5a96ed5860c.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5646)

**Comment by data-sync-user** [comment]
➤ Winnie Teichmann commented:

This should be fixed with https://mozilla-hub.atlassian.net/browse/FXIOS-5439 ( https://mozilla-hub.atlassian.net/browse/FXIOS-5439|smart-link ) (https://github.com/mozilla-mobile/firefox-ios/issues/12690 ( https://github.com/mozilla-mobile/firefox-ios/issues/12690|smart-link ) )

**Comment by data-sync-user** [comment]
➤ Winnie Teichmann commented:

Simion Bascacould you please check the nightly build if this issue is still reproducible?

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Winnie Teichmann it’s also reproducible on latest v9000 (27246). 

Note that the issue is also reproducible when opening multiple tabs when the inactive list is displayed in tabs tray. When opening tabs the view should scroll to the opened tab but it does not.

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Verified as fixed on v125 (40049) with iPhone 15 Pro (17.3).
