### ISSUE TITLE
Extend "Pull to Refresh" to open / close new tab

### ISSUE THREAD

**Issue by kenijo** [mozilla-mobile/firefox-ios#13049]
### User Problem
The "Pull to Refresh" functionality is very easy to use and I would love to see it expanded to make it even easier than 2 clicks (click the numbered square at the bottom, then the + sign) or click and hold.

### Ideas for Solution
When doing "Pull to Refresh", provide the option to open a new tab on the left side and close the tab on the right side.
Check the following screenshot:

![image](https://user-images.githubusercontent.com/5394591/215162728-9aee8462-1b13-46a1-a3e0-89e684ff4001.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5652)

**Comment by lmarceau** [comment]
Could relate to https://github.com/mozilla-mobile/firefox-ios/issues/11007 and https://github.com/mozilla-mobile/firefox-ios/issues/9701 to improve pull to refresh.

**Comment by kenijo** [comment]
> Could relate to #11007 and #9701 to improve pull to refresh.

It is related to the "Pull to Refresh" but it is not trying to achieve the same as those two. #11007 is a bug and #9701 is asking for an option to disable "Pull to Refresh" all together.
