### ISSUE TITLE
Firefox mobile iOS—  when clicking “Edit Bookmarks” there is no distinction between a main folder and sub-folder

### ISSUE THREAD

**Issue by dorfli** [mozilla-mobile/firefox-ios#13054]
I just upgraded to Firefox iOS mobile 109.0 and this issue is happening again:

https://github.com/mozilla-mobile/firefox-ios/issues/9789

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5655)

**Comment by ancillarymagnet** [comment]
Issue persists in 111.2 iOS mobile. As someone with nearly 100 bookmark folders, I would love to see not just indentation but a proper tree structure shown as accordion folders.

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v122 (36988), with iPhone 15 (17.1).
