### ISSUE TITLE
 String update needed: change "sites" to "pages"

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/firefox-ios#13069]
## Steps to reproduce

![image](https://user-images.githubusercontent.com/629193/215609383-526e2722-6cad-4616-863b-f3b5a30e919e.png)

See string: https://pontoon.mozilla.org/sl/firefox-for-android/all-resources/?string=232220

### Expected behavior

Delphine and emilyw say this screen should be changed from "sites" to "pages". Indeed, in the following case, there are not 11 websites, but rather 11 pages belonging to two sites.

See screenshot attached.

### Actual behavior

"sites"

### Notes

Firefox Android bug report for the same issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1813694

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5662)

**Comment by lmarceau** [comment]
Hey @cpeterso, I think this is a duplicate of https://github.com/mozilla-mobile/firefox-ios/issues/13065 ?

**Comment by cpeterso** [comment]
> I think this is a duplicate of #13065 ?

oops. You're right. I filed this bug because Delphine said this problem affected both Android and iOS. I didn't realize she also filed an iOS bug.
