### ISSUE TITLE
 String update needed: should be changed from "sites" to "pages"

### ISSUE THREAD

**Issue by Delphine** [mozilla-mobile/firefox-ios#13065]
See string "sites" on screenshot attached.

After talking with emilyw, we agreed this should be changed from "sites" to "pages". Indeed, in the following case, there are not 11 websites, but rather 11 pages belonging to two sites

(note: also happens on Android, filed a ticket for that too
![image (2)](https://user-images.githubusercontent.com/399020/215580605-06e3968e-ebc4-4ac2-8a30-e37e79b1ade4.png)
)

CC @dnarcese and CC @ewachowiak

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5658)

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Verified as fixed on v9000 (28760) with iPhone 13 Pro max (15.7.1).

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Verified as fixed on :Firefox: v112 (29529) with iPhone 13 Pro (15.7.1), and iPhone 14 (:iOS:16.1).
