### ISSUE TITLE
IOS firefox password warning but no explanation 

### ISSUE THREAD

**Issue by hhhhhhamerica** [mozilla-mobile/firefox-ios#13095]
For months now IOS firefox has been showing me red warning labels on a lot of my passwords sometimes the label will disappear and sometimes it comes back and shows almost every password of mine with this label. I really don't know what to do because the only person who answered the same question I had said it was a glitch/bug. So what are users supposed to do to make sure their passwords are safe if it's a glitch ? How do we know which ones are included in a breach or simply need a password reset? Firefox really needs to do something because this has been a problem for me for months and im assuming others too since someone finally made a post for the problem. The answer that was given still didn't explain how to go about this and what firefox is doing to update password protection or fix this bug. 
![66CCCB4F-99D5-48CE-A887-8D0B34C437EB](https://user-images.githubusercontent.com/124155198/216035341-68e8d622-69df-402f-a0fe-1cc94baa1518.jpeg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5680)

**Comment by dnarcese** [comment]
I am going to close this ticket and we will track in #12824.  The fix should be out in version 112.
