### ISSUE TITLE
The "Save to PDF" button is not displayed when the "Share" button is displayed in the URL bar

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#13128]
### Preconditions:
- Have the "share" button displayed in the URL bar
## Steps to reproduce
1. Go to a pdf example
2. Tap on the "Share" button
### Expected behavior
- The "Save to PDF" button should be displayed.
### Actual behavior
- The "Save to PDF" button is not displayed.
### Device & build information
* Device: iPhone 13 mini (16.1)
* Build version: v9000 (27348)
### Notes
Attachments: 

![image](https://user-images.githubusercontent.com/32130829/216602777-21cd62ff-54b7-4183-953c-1c34929cc511.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5696)

**Comment by dnarcese** [comment]
@SimonBasca Do you mean Save to Files is not there? Or Save to PDF? If the file you are sharing is already a PDF, would we expect Save to PDF to show up?

How does this behaviour differ from when the share menu was in the page action menu?

**Comment by SimonBasca** [comment]
The above screenshot is showing the button that is missing from  v9000 (27803). 

Here is a screenshot of the issue

![Skype_Picture_2023_02_10T09_49_47_935Z](https://user-images.githubusercontent.com/32130829/218060037-143e77d8-810e-4706-bfef-6009f75ab366.jpeg)

**Comment by dnarcese** [comment]
Closing as we are not rolling out this change.
