### ISSUE TITLE
Beta 110 (27314) crash continuously when entering URL

### ISSUE THREAD

**Issue by pjolt** [mozilla-mobile/firefox-ios#13137]
## Steps to reproduce
Open Firefox Beta, tap on url bar. Either it crashes right away upon tap other times i can enter a few letters before Firefox crashes. I have tried different settings for New tab and homepage to see if there is something there that triggers this crash, but not able to find source/solution.  

### Expected behavior
Should be able to enter URL 

### Actual behavior
Firefox crashes

### Device & build information
* Device: iPhone 13 Pro /16.3 (20D47)
* Build version: Firefox Beta 110 (27314)

### Notes
Attachments: [logs.zip](https://github.com/mozilla-mobile/firefox-ios/files/10610464/logs.zip)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5700)

**Comment by Dunvii** [comment]
Same problem

**Comment by SimonBasca** [comment]
I think this is a duplicate of https://github.com/mozilla-mobile/firefox-ios/issues/13139. I added some extra steps on how to reproduce this on https://github.com/mozilla-mobile/firefox-ios/issues/13139..

In my case it's reproducible after opening Firefox after a few hours of inactivity.

**Comment by lmarceau** [comment]
Thanks @SimonBasca, it's the same crash from the stack trace. This relates to an attempt to fix another crash we've made on the Beta. I'll revert that change for now. Thank you!

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verifying as fix on v110 (27451). I was unable to reproduce this issue while testing 110 (27451)
