### ISSUE TITLE
Firefox crash after restoring from older device

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#13140]
## Steps to reproduce
1. On a new device, follow the flow to restore from old iPhone 
2. On the new device, Firefox is not installed
3. Install v110 (27314) from Test Flight
4. Firefox crashes continuously. 
### Expected behavior
- Firefox should work as expected.
### Actual behavior
- Firefox crashes. 
### Device & build information
* Device: iPhone 13 mini (16.1)
* Build version: v110 (27314)
### Notes
Attachments: 

[Client-2023-02-06-125527.ips.zip](https://github.com/mozilla-mobile/firefox-ios/files/10662422/Client-2023-02-06-125527.ips.zip)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5702)

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verifying as fix on 110 (27451)
