### ISSUE TITLE
Firefox crashes when scrolling the history panel

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#13144]
## Steps to reproduce
1. Login to FxA
2. Go history panel
3. Scroll down the panel
### Expected behavior
- Firefox should load the history items correctly.
### Actual behavior
- Firefox crashes
### Device & build information
* Device: iPhone 13 mini (16.1)
* Build version: 110 (27314)
### Notes
Attachments: 

[Client-2023-02-12-062837.ips.zip](https://github.com/mozilla-mobile/firefox-ios/files/10664140/Client-2023-02-12-062837.ips.zip)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5703)

**Comment by lmarceau** [comment]
This should be fixed as well with https://github.com/mozilla-mobile/firefox-ios/pull/13147

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verifying as fix on v110 (27451)
