### ISSUE TITLE
`String.attributedText(boldString:font:)` only bolds the first occurrence of the substring

### ISSUE THREAD

**Issue by linabutler** [mozilla-mobile/firefox-ios#13151]
In https://github.com/linabutler/firefox-ios/blob/a06e7b308ae3030b6bc7a4e61887a38f7a34ec9f/Client/Frontend/Browser/SearchViewController.swift#L786-L805, I'm using the `attributedText(boldString:font:)` extension method to bold the remaining portion of the full keyword after the search query for Merino suggestions—copying how we bold the remainder of the string after the query for regular search suggestions.

I noticed that this doesn't work quite right if the remainder (after the search query) appears earlier in the full keyword. For example, if the search query is `amazon c` and the full keyword is `amazon co` (the remainder is just the last "o"), the method will incorrectly bold the _first_ "o" (`amaz_o_n co`), instead of the _last_ "o" (`amazon c_o_`).

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5707)

**Comment by data-sync-user** [comment]
➤ Laurie Marceau commented:

For QA, it can be tested that search suggestion when typing in the URL bar is bold as it should (as originally tested with https://mozilla-hub.atlassian.net/browse/FXIOS-5347 ( https://mozilla-hub.atlassian.net/browse/FXIOS-5347|smart-link ) )

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Verified as fixed on v9000 (28110) with iPhone 14 (16.1).

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Verified as fixed on v111 (28148) with iPhone 14 (16.1).
