### ISSUE TITLE
Firefox focus crashes iPhone after multiple Erased searches

### ISSUE THREAD

**Issue by MiloKlaus** [mozilla-mobile/firefox-ios#13155]
## Steps to reproduce
Clear app using bin multiple times without closing app (though you can switch between apps during process). This does not need to be consecutive; it can be done over hours, as long as app is not closed out of. 
### Expected behavior
Clearing tab and bringing user to new tab page
### Actual behavior
Crashes IPhone, turning screen black like it is being powered off
### Device & build information
* Device: Iphone 13 mini, IOS 16.1
* Build version: 109.0
### Notes: after 1-7 searches/deletes, the app will slow and then crash. Attached is a video demonstrating this, ending when my iphone crashed after attempting one final clear. I have not attempted to delete/reinstall app yet. Also, I don't think I could get the attach video feature to work, so here is a video demonstrating the process. 
Attachments: https://youtu.be/YnxdMB3q5Hk

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5709)

**Comment by lmarceau** [comment]
Hello @MiloKlaus, thanks for raising this issue. It seems the problem you are mentionning relates to Firefox Focus only. The repository you've just opened the issue on is only for **Firefox for iOS** which is a different application. Would you mind opening this issue on the [Focus iOS repository](https://github.com/mozilla-mobile/focus-ios) so it can be triaged accordingly? Thanks!
