### ISSUE TITLE
Build fails in StoragePerfTests.swift

### ISSUE THREAD

**Issue by whitelips** [mozilla-mobile/firefox-ios#13162]
## Steps to reproduce
1. Launch Xcode 
2. Select the target `Storage`
3. Build and Test `StoragePerfTests`
4. Build failed

### Expected behavior
Build success

### Actual behavior
Build failed with undefined symbol message
```
Undefined symbol: _$s18MozillaAppServices16VisitObservationV3url5title9visitType7isError0J14RedirectSource0j9PermanentlM02at8referrer0J6Remote15previewImageUrlACSS_SSSgAA0D10TransitionOSgSbSgA2Rs5Int64VSgAnrNtcfC
```

### Device & build information
* Device: Macbook Pro 14" (2021, M1 Pro, 10CPU)
* Build version: main branch, 02774844b155e8a075c0aef0f8edc52890db23e5
### Notes
Attachments: 
[Build Storage_2023-02-08T22-53-18.txt](https://github.com/mozilla-mobile/firefox-ios/files/10686224/Build.Storage_2023-02-08T22-53-18.txt)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5712)

**Comment by whitelips** [comment]
If someone confirms this could be fixed, I'm going to resolve build error.

**Comment by lmarceau** [comment]
@isabelrios do you know if we use those tests in Bitrise? `StoragePerfTests` only has 1 test in it, not sure it's used?

**Comment by isabelrios** [comment]
> @isabelrios do you know if we use those tests in Bitrise? `StoragePerfTests` only has 1 test in it, not sure it's used?

I am not sure if we need them or not what it is for sure is that they are not running on Bitrise at this moment. They are disabled in the project so in order to have that test running we need to enable it.
