### ISSUE TITLE
Wrong Localizable.korean word of Settings.DisplayTheme.SwitchSubtitle

### ISSUE THREAD

**Issue by whitelips** [mozilla-mobile/firefox-ios#13173]
## Steps to reproduce
1. Settings
2. Theme
3. Disable toggle switch `Use System Light/Dark Mode`
4. Check Autmatically(자동으로)'s description

### Expected behavior
화면 밝기에 따라 자동으로 변경됨

### Actual behavior
화면 밝기에 따라 자동으려 변경됨

### Device & build information
* Device: iPhone 13 Mini
* Build version: Firefox 109.0 (25841)
### Notes
Attachments: 
<img src="https://user-images.githubusercontent.com/65991887/217854565-24cf23c0-36fa-4810-9f5b-978d34bb7315.jpeg" width=375>

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5719)

**Comment by whitelips** [comment]
I want to fix this issue to replace "Settings.DisplayTheme.SwitchSubtitle" Korean value.

**Comment by lmarceau** [comment]
Hello! I just wanna make sure I understand the issue. Is it that the Korean text is the wrong translation? If I understood right then I will point out that we take our translations from [Pontoon](https://pontoon.mozilla.org/) and any corrections should be made there as that's our source of truth (in this case it would be nuder Team > Korean, Project > Firefox for iOS). Any contributor can suggest better translations for any part of the project! 🙏

**Comment by dnarcese** [comment]
cc @Delphine

**Comment by hyeonseok** [comment]
There is a typo error and I just fixed as https://pontoon.mozilla.org/ko/all-projects/all-resources/?search=%EC%9E%90%EB%8F%99%EC%9C%BC%EB%A0%A4&string=180198

@whitelips Thank you for participating!

**Comment by lmarceau** [comment]
I'll close this issue then. The string will be imported in next string import! Thanks to all!
