### ISSUE TITLE
Firefox seems to be reloading ALL Recently Visited pages

### ISSUE THREAD

**Issue by jhgarrison** [mozilla-mobile/firefox-ios#13187]
## Steps to reproduce
This problem was exposed when I used FF on iPad to "Whitelist" an email in a web interface for the Mailroute mail-forwarding and SPAM filter service.  Incoming messages pass through Mailroute and detected SPAM is diverted to a holding area where I can use a browser to examine held emails.  One of the options is "Recover", which forwards a copy to me as if had not been SPAM-tagged.

The issue here is that once I've done this, Firefox seems to remember (forever?) that URL and is reloading it every time I open the Firefox app on the iPad.  The end result is I keep getting duplicates of that one released message, as every GET for that URL causes Mailroute to re-send the message.

I realize this gets into a gray area around the definition of GET.  It is supposed to be "safe" in that it causes no state change on the server.  In this case, while the server's state doesn't change, it does result in an action with a side-effect (re--sending the message) so someone could argue they should be using a non-"Safe" method such as POST.

However, it's not clear why Firefox is (or should be) re-sending the GET repeatedly for a page I closed long ago, and which only appears in my recent history.

**_Note that I've been using Firefox for a long time, and this seems to be a recent change._**

### Expected behavior
FF does not reload pages in recent history unless requested

### Actual behavior
FF seems to be reloading pages in background, from recent history

### Device & build information
* Device: A1701 iPad Pro 10.5", iPadOS 16.3
* Build version: 109
### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5729)

**Comment by dnarcese** [comment]
@jhgarrison are you still seeing this issue recently?
