### ISSUE TITLE
Clearing history does not clear "recently visited" on the home page

### ISSUE THREAD

**Issue by jhgarrison** [mozilla-mobile/firefox-ios#13186]
## Steps to reproduce

Clear history

### Expected behavior

"Recently visited" items on the home page are gone

### Actual behavior

In the history browser recent items are gone, but on the home page they are still present. To clear them I tried:

- Closing and reopening the app
- Hard-rebooting the iPad

But neither of those worked.  The only solution I found was to delete and reinstall Firefox.

### Device & build information
* Device: A1701 iPad Pro 10.5", iPadOS 16.3
* Build version: 109
### Notes
Attachments: 

History pane after deleting all history:
![IMG_0439](https://user-images.githubusercontent.com/2840152/217974289-4cc7c14d-2bf7-4d84-8338-f86080f9cd63.PNG)

Home page (redacted) showing Recently Visited still present
![IMG_0438](https://user-images.githubusercontent.com/2840152/217974390-f92f942d-6b60-4568-915c-28b50d6d709d.PNG)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5728)

**Comment by SimonBasca** [comment]
@dnarcese I think this might be the same as https://github.com/mozilla-mobile/firefox-ios/issues/10745. Could we add a priority for both issues?

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Verified as fixed on v9000 (29966) with iPhone 13 Pro (15.7.1).
This issue will also be checked when an official RC build is created for the fix version.
