### ISSUE TITLE
Beta 110 (27761) going into tab overview does not keep focus on active tab

### ISSUE THREAD

**Issue by pjolt** [mozilla-mobile/firefox-ios#13197]
## Steps to reproduce
Open 8 tabs, go into tab 7 or 8 and switch to tab overview and it shows the first 6 tabs and is not highlighting the active tab you came from. 

### Expected behavior
Going into tab overview should highlight/keep focus on the tab you came from. As is the behaviour on release 109 (25841). 

### Actual behavior
It goes back up to show the first 6 tabs, so if you want to see tab 7 or higher where you came from then you have to scroll back down. 

### Device & build information
* Device: iPhone 13 Pro / 16.3 (20D47) 
* Build version: Beta 110 (27761)
    1. Notes
Testing done on fresh installed Beta (27761) not logged in to sync, and no settings modified from default. Also this is not a new issue i have seen this in Beta channel for a while now, unfortunately i can´t pinpoint more exact to when this started happening. 

https://user-images.githubusercontent.com/120338442/218186502-d8913583-c0db-431c-8d3f-2c9b55506e9c.mp4

Attachments: Screenrecording of this behaviour.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5734)

**Comment by SimonBasca** [comment]
I think this is the same as https://github.com/mozilla-mobile/firefox-ios/issues/11800. In the beta channel we have a feature called Tabs Groups. Could you disable this and let me know if the issue is still reproducible?

**Comment by pjolt** [comment]
> I think this is the same as https://github.com/mozilla-mobile/firefox-ios/issues/11800. In the beta channel we have a feature called Tabs Groups. Could you disable this and let me know if the issue is still reproducible?
> 
> 

Disabling tab groups results in correct behavior.
