### ISSUE TITLE
Send tab notification is received on iOS but the tab does not arrive when sending from desktop to iOS

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#13209]
## Steps to reproduce
1. Log in to existing FxA on v9000(27969)
2. Log in to FxA on desktop nightly 111.0a1 (2023-02-09) (64-bit)
3. Send tab from Desktop to iOS
### Expected behavior
- Send tab should work as expected.
### Actual behavior
- Send tab notification is received on iOS but the tab does not arrive. The tab is correctly sent from iOS to Dekstop.
### Device & build information
* Device: iPhone 14 Pro (16.2)
* Build version: v9000(27969)
### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5745)

**Comment by data-sync-user** [comment]
➤ Daniela Arcese commented:

Working for me on prod v109

**Comment by data-sync-user** [comment]
➤ Laurie Marceau commented:

Simion Basca following comment from Daniela, we can maybe retest on next Nightly? If this related to FXIOS-5766

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

This is no longer reproducible on v9000 (28508).
