### ISSUE TITLE
Firefox crashes when trying to search anything on a fresh install

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/firefox-ios#13211]
## Steps to reproduce
1. Launch FF and finish the onboarding.
2. Tap on the URL bar type anything and search for it.
### Expected behavior
The search is done without issues.
### Actual behavior
Firefox crashes when trying to search for anything on a fresh install
### Device & build information
* Device: iPhone 14 (16.1).
* Build version: 9000 (27969)
### Notes
Attachments: 

https://user-images.githubusercontent.com/42831109/218471699-ec650d1b-bafd-48a3-9d18-077d961fc890.mov

[crash.zip](https://github.com/mozilla-mobile/firefox-ios/files/10722699/crash.zip)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5747)

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Verified as fixed on v111 (28148) with iPhone 14 (16.1).
