### ISSUE TITLE
The option to reload the site without tracking protection is not displayed.

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#13210]
## Steps to reproduce
1. Visit a site
2. Long press on the "refresh" button
### Expected behavior
- The option to reload the site without tracking protection should be displayed.
### Actual behavior
- The option to reload the site without tracking protection is not displayed.
### Device & build information
* Device: iPhone 14 Pro (16.2)
* Build version: 9000 (27969)
### Notes
Attachments:

<img width="984" alt="Screen Shot 2023-02-13 at 14 43 15" src="https://user-images.githubusercontent.com/32130829/218460818-10b50658-7d55-499b-bd31-8dfcec5e9d5c.png">

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5746)

**Comment by dnarcese** [comment]
This bug is intended behaviour, but there is another bug that I found from this https://github.com/mozilla-mobile/firefox-ios/issues/13284
