### ISSUE TITLE
The last item in the synced tab list is not accessible

### ISSUE THREAD

**Issue by struq** [mozilla-mobile/firefox-ios#13234]
## Steps to reproduce
1. Have many tabs on synced devices such that list of the synced tabs is longer than screen height.
2. Open synced tab list and scroll to the bottom.

### Expected behavior
1. After scrolling to the bottom of the list the last tab should be visible.

### Actual behavior
1. The last tab is hidden behind the lower bar and is not accessible. It's only visible when over-scrolling. Screen recording attached.

### Device & build information
* Device: iPhone 12 mini
* Build version: 109.0 (25841)
### Notes
Attachments: 

https://user-images.githubusercontent.com/2097707/218652103-e78316ff-0f53-443c-8aef-be5e27a7a692.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5765)

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Verified as fixed on v9000 (29455) with{color:#ffffff} {color}iPhone 14 (16.1).
The last tab is displayed without issues when scrolling until the bottom.
This issue will still be checked when an RC will be created for the fix version.

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Verified as fixed on v111.2 (29672) with iPhone 13 Pro (15.7.1).
