### ISSUE TITLE
"Open in external app" prompt is incorrectly displayed.

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#13259]
## Steps to reproduce
1. Go to https://www.bilibili.com/video/BV1Kf4y1B751/?spm_id_from=autoNext
2. wait for the "open in external app" prompt
### Expected behavior
- In Safari going to https://www.bilibili.com/video/BV1Kf4y1B751/?spm_id_from=autoNext will display an error message:"Safari cannot open the page"
### Actual behavior
- "Open in external app" prompt is displayed and the prompt is not scrollable. 
### Device & build information
* Device: iPhone 14 Pro (16.2)
* Build version: 111 (28263)
### Notes
Attachments: 

![image](https://user-images.githubusercontent.com/32130829/219334367-65f302cd-2601-4ec0-8811-70c331ccd50c.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5776)

**Comment by dnarcese** [comment]
Let's make this view scrollable

**Comment by data-sync-user** [comment]
➤ Alina Moldovan commented:

Verified as fixed on Firefox v9000(29331), iPhone 14 Plus (16.0.3)

The view is scrollable now.
