### ISSUE TITLE
Search engine settings page show "Done" instead of "Edit" after a search engine has been removed

### ISSUE THREAD

**Issue by clarmso** [mozilla-mobile/firefox-ios#13253]
## Steps to reproduce
1. Tap hamburger menu.
1. Tap General > Search.
1. Tap "Add Search Engine". Add `https://youtube.com/search?q=%s` as the URL for YouTube. Click "Save".
1. Tap "Edit". 
1. Tap ⛔ icon next to "YouTube". Tap "Delete".

### Expected behavior
The upper right corner show "Edit" (enabled).

### Actual behavior
The upper right corner show "Done" (enabled).
![](https://user-images.githubusercontent.com/1740517/219171478-d7e16c67-99f5-4feb-b123-45dc1a1cb995.png)

### Device & build information
* Device: iOS Simulator (iPhone 14 and iPad Pro)
* Build version: Nightly
    1. Notes
This issue has been found by the automated XCUITest `SearchSettingsUITests/testDeletingLastCustomEngineExitsEditing()`. This test used to be passing. The behaviour is not completely wrong, but I'd like to know if the change has been intentional.

https://github.com/mozilla-mobile/firefox-ios/blob/main/Tests/XCUITests/SearchSettingsUITest.swift#L104

Here's the screen recording of the test run:
https://user-images.githubusercontent.com/1740517/219171680-1efe151a-d283-4f21-bee4-33f6cdfca6cf.mov

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5772)

**Comment by clarmso** [comment]
The test failure started on Feb 10.

**Comment by data-sync-user** [comment]
➤ Clare So commented:

The test failure started on Feb 10.
https://storage.googleapis.com/mobile-reports/public/firefox-ios-M1/FullFunctionalTests/result_123/build/reports/index.html ( https://storage.googleapis.com/mobile-reports/public/firefox-ios-M1/FullFunctionalTests/result_123/build/reports/index.html|smart-link )

**Comment by data-sync-user** [comment]
➤ Clare So commented:

This PR may be related. 🤔 
https://github.com/mozilla-mobile/firefox-ios/commit/dd949092d8c68d3b88944222e8c41ba9e6f99617 ( https://github.com/mozilla-mobile/firefox-ios/commit/dd949092d8c68d3b88944222e8c41ba9e6f99617|smart-link )

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Verified as fixed on v119 (34673) with iPhone 13 Pro (15.7.1).
