### ISSUE TITLE
The indicator that Tracking Protection is disabled is not visible in light theme

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#13261]
## Steps to reproduce
1. Visit a page
2. Tap on the "Lock icon"
3. Disable tracking protection
4. Observe the lock icon
### Expected behavior
- The indicator should be visible.
### Actual behavior
- The indicator that Tracking Protection is disabled is not visible in light theme
### Device & build information
* Device: iPhone 14 Pro (16.2)
* Build version: v111 (28263)
### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5777)

**Comment by dnarcese** [comment]
Is this a duplicate of #12664

**Comment by SimonBasca** [comment]
Closing in favor of https://github.com/mozilla-mobile/firefox-ios/issues/12664
