### ISSUE TITLE
Time and WiFi/battery indicator hard to read when Firefox open

### ISSUE THREAD

**Issue by lmarceau** [mozilla-mobile/firefox-ios#13269]
## [Bugzilla bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1815924)
When Firefox is open, the things on either side of my phone's notch (time, wifi, battery, etc.) are white text on an almost white background and are therefore hard to read. I'll attach a screenshot.

## Steps to reproduce
* Open a website and the status bar is of the wrong color.
* Once it happens, it's on any website.
* It seems intermittent, closing and reopening the app normally fixes the issue.

### Expected behavior
Status bar is of wrong color

### Actual behavior
![image](https://user-images.githubusercontent.com/11338480/219423802-03419af5-8df6-4f86-b900-38b3dcf63816.png)

### Device & build information
* Device: ?
* Build version: ?
    1. Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5785)

**Comment by data-sync-user** [comment]
➤ Daniela Arcese commented:

Catalin Suciu are you able to find reliable STR?

**Comment by alinanico** [comment]
@dnarcese 
I managed to reproduce this issue using the following steps: 
1. Set the device in Dark mode
2. Install the Firefox app 
3. Open the Firefox app and navigate to a web page 
4. Put the Firefox app in in background
5. Set the device in Light mode
6. Force close the Firefox app 
7. Reopen the Firefox app
8. Check the status bar 

Issue is reproducing using the following env:
     - version 109 (25841) 
     - iPhone 14 Plus
     - IOS Version 16.0.3 (20A392)

Notes: 
- Not able to reproduce the issue using the above steps for 110, 110.1 nor 111 versions
- the issue persists until the application is restarted
