### ISSUE TITLE
Weird frames displayed on `Add Search Engine` screen on darkmode

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/firefox-ios#13264]
#### Preconditions
The dark mode is enabled.

## Steps to reproduce
1. Launch FF and access Settigs>Search.
2. Access Add Search Engine section.
3. Observe the Title and URL frames.
### Expected behavior
The screen should be displayed correctly without any extra frames.
### Actual behavior
Weird frames displayed on `Add Search Engine` screen on darkmode.
### Device & build information
* Device: **iPhone 14 (16.1)**
* Build version: **v111 (28263).**
### Notes
Attachments: 
![image0 (6)](https://user-images.githubusercontent.com/42831109/219346439-695b8ca4-6852-476e-9441-583e3e04cb01.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5781)

**Comment by mleers** [comment]
Hi, I would like to try to fix this issue.

**Comment by lmarceau** [comment]
@mleers You can certainly have a look into it. It seems to me there are two colors on top of one another (one for the textfield, one for its container). If my theory is correct, then we can probably use the textfield color on both. We'll need UX review on it, but I'll tag the designer once the PR is opened. Thank you!

**Comment by lmarceau** [comment]
Reopening since needs QA

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Verified as fixed in v9000 (29027) with iPhone 13 Pro (15.7.1).

To be re-checked when the official v112 will be built.

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Verified as fixed on :Firefox: v112 (29529) with iPhone 13 Pro (15.7.1), and iPhone 14 (:iOS:16.1).
