### ISSUE TITLE
Request desktop site option is triggered after releasing the long press on Refresh button

### ISSUE THREAD

**Issue by Mara-d** [mozilla-mobile/firefox-ios#13262]
## Steps to reproduce
1. Launch Firefox
2. Go to www.youtube.com
3. Long press the Refresh button
### Expected behavior
The Request desktop site option is triggered via long press on the Refresh button
### Actual behavior
The Request desktop site option is triggered after releasing the long press on the Refresh button
### Device & build information
* Device: iPhone SE 15.4
* Build version: v9000 (28271), v111 (28263)
### Notes
Attachments: 

https://user-images.githubusercontent.com/65923892/219344519-a7d953c3-6fd6-405d-a634-aa6dbc249ff5.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5779)

**Comment by dnarcese** [comment]
This seems like intended behaviour. When you long press the reload button, we show a menu with 'request desktop site' and sometimes 'reload without tracking protection'.

Is the bug you are seeing around clicking the button?
