### ISSUE TITLE
Send to Device when in reader mode sends an invalid URL

### ISSUE THREAD

**Issue by mhammond** [mozilla-mobile/firefox-ios#13280]
STR:
* Open a page, enter reader mode
* Send to another device

Expected:
* Original URL opens

Actual:
* Other devices get something like `http://localhost:6571/reader-mode/page?url=https://www.apple.com/au/watch...`

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5791)

**Comment by dnarcese** [comment]
This should be fixed in our next release (111) (original issues #12807 )
