### ISSUE TITLE
The videos on `nba.com` are not playing

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/firefox-ios#13294]
## Steps to reproduce
1. Launch FF.
1. Access ```https://www.nba.com/watch/video/top-10-plays-from-all-star-saturday-night?plsrc=nba&collection=more-to-watch```
1. Play any video.
    1. Expected behavior
The videos from nba.com should start playing.
    1. Actual behavior
The videos on `nba.com` are not playing
    1. Device & build information

* Device: iPhone 13 Pro (15.7.1).
* Build version: v9000 (28390)
    1. Notes
Attachments: 

https://user-images.githubusercontent.com/42831109/220314835-39359a44-71e7-4249-9d55-d96ed6daa8d8.mov

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5811)

**Comment by Tomatoshadow2** [comment]
I can also confirm, video’s don’t play, after doing the above steps.

**Comment by dnarcese** [comment]
Works in other browsers

**Comment by data-sync-user** [comment]
➤ Nishant Bhasin commented:

You can sync with Nishant Bhasin for any support here!

**Comment by data-sync-user** [comment]
➤ Dianna Smith commented:

this is being reverted in 116.4

**Comment by cpeterso** [comment]
Now that the FxiOS UA change has been reverted in 116.4, I can reproduce this bug again in Firefox and Focus 116.4: instead of a video play button, the site shows a "WATCH ON NBA APP" button. The site allows Safari and Chrome iOS to play the video.

**Comment by cpeterso** [comment]
The nba.com video player still works correctly in Chrome and shows a "WATCH ON NBA APP" button in Firefox, but now it shows a streaming error in Safari.

**Comment by data-sync-user** [comment]
➤ Chris Peterson commented:

We can close this issue. I verified that nba.com ( http://nba.com ) videos play correctly in Firefox 133.3.
