### ISSUE TITLE
Crashing on Sync

### ISSUE THREAD

**Issue by j-likes-spicy** [mozilla-mobile/firefox-ios#13292]
## Steps to reproduce
1. Load Firefox app from iOS desktop

# 

1. Click the hamburger menu in the lower right hand corner of the screen

# 

1. Click on the "Sync and Save Data" menu option

# 

1. Prompt reading "Sign In with Your Camera" appears, with two buttons. The choices are: 1) Ready to Scan, 2) Use Email Instead

# 

1. Click on "Ready to Scan"

# 

1. Camera loader with QR reader appears

# 

1. Camera automatically captures QR code in Firefox browser on the desktop (macOS Big Sur, current with updates)

# 

1. The blank screen attached appears and does nothing; it is constantly blank. In this state, there is no way to access controls (Back, Forward, etc).

# 

1. Manually shut down the app by swiping upward.

# 

1. Opened support ticket to advise of issue in case anyone else is experiencing.
    1. Expected behavior

### Device & build information
* Device: (iPhone 14 iOS 16.3.1)
* Build version: ?
    1. Notes
Attachments: 
![Screenshot 2023-02-20 at 11 05 25 PM png](https://user-images.githubusercontent.com/77315222/220261723-96bb67fe-a945-4f72-95bd-bf9ec43578ec.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5810)

**Comment by lmarceau** [comment]
Hello! Since you experienced a crash, if you want you could share with us your crash logs which would help us investigate the problem. Here's a [wiki page](https://github.com/mozilla-mobile/firefox-ios/wiki/How-to-get-your-device-logs) on how to do so.

**Comment by gutley** [comment]
@lmarceau I don't think its a crash but there is something wrong going on as I can reproduce it here. After scanning the QR code from desktop Firefox, that Sync and Save Data screen is just blank. Not sure about "The blank screen attached appears and does nothing; it is constantly blank. In this state, there is no way to access controls". Its easy enough to use the back button to go back to this screen:
![image](https://user-images.githubusercontent.com/2040690/220622091-4b7b1c7f-6069-40e0-b010-d204107789c1.png)

iOS 16.3.1 on an iPhone 14 Pro Max here

**Comment by j-likes-spicy** [comment]
> Hello! Since you experienced a crash, if you want you could share with us your crash logs which would help us investigate the problem. Here's a [wiki page](https://github.com/mozilla-mobile/firefox-ios/wiki/How-to-get-your-device-logs) on how to do so.

Good Morning,

My apologies for the delayed response. First, I've followed the Wiki and attempted to search the log verbatim according to the instructions; no keywords/identifiers/etc related to Mozilla or Firefox. Furthermore, I've manually pulled and read through the logs; nothing printed in the files appear to reference either keyword. I've attempted to track down the log files for Mozilla/Firefox (tried to search with both keywords, no matches). The only logs that appear aren't Firefox related, unfortunately. I don't mind dropping in what I have, but the context doesn't exist. Please let me know if you'd like me to drop them in anyways. 

Thanks :)

**Comment by dnarcese** [comment]
I believe this is a duplicate of #12599
