### ISSUE TITLE
TopSite crash

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#13342]
!Screen Shot 2023-02-23 at 1.13.58 PM.png|width=848,height=239!

!Screen Shot 2023-02-23 at 1.14.56 PM.png|width=994,height=635!

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5833)

**Comment by data-sync-user** [comment]
➤ Laurie Marceau commented:

For QA we can do some testing around the homepage, checking for example with/without sync account that all homepage sections appears as it does (jump back in, top sites, recently visited, recently saved, etc) and no crash happens. We can also test to make sure the top sites blur/shadow under the tiles appears as it should with/without wallpapers

**Comment by data-sync-user** [comment]
➤ Alina Moldovan commented:

Verified this issue using FF v9000(33001) and iPhone SE (15.4) 

All sections look ok in both cases: user is logged or user is not logged in. No crash occurred. 

Laurie Marceau Relating to ‘the blur/shadow under the top sites titles’ could you please confirm that you are referring to the square around the site icon (like in picture below)?

!image-20230727-125047.png|width=400,height=710!

**Comment by data-sync-user** [comment]
➤ Laurie Marceau commented:

Alina Moldovan it’s a little bit easier to see in light mode:

Without wallpaper there’s a shadow below the different tiles on the homepage:

!Screenshot 2023-07-27 at 10.02.14 AM.png|width=205,height=216!

With a wallpaper there’s no shadow, but the card is blurred (transparent) a little bit.

!Screenshot 2023-07-27 at 10.02.21 AM.png|width=205,height=209!

**Comment by DianaBarladeanu** [comment]
> ➤ Laurie Marceau commented:
> 
> Alina Moldovan it’s a little bit easier to see in light mode:
> 
> Without wallpaper there’s a shadow below the different tiles on the homepage:
> 
> !Screenshot 2023-07-27 at 10.02.14 AM.png|width=205,height=216!
> 
> With a wallpaper there’s no shadow, but the card is blurred (transparent) a little bit.
> 
> !Screenshot 2023-07-27 at 10.02.21 AM.png|width=205,height=209!

Verified as fixed on v9000 (33082) with iPhone SE (16.5). 
No crash occurred with the user logged or the user not logged in.
I can confirm that in light mode the shadow is visible without a wallpaper and with a wallpaper the card is blurred/transparent.
