### ISSUE TITLE
Remove SnapKit from DevicePickerTableViewCell

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#13360]
* Remove SnapKit

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5848)

**Comment by bmihai23** [comment]
Hi @PARAIPAN9, I would like to work on this issue. Thank you!

**Comment by PARAIPAN9** [comment]
Of course!!

**Comment by data-sync-user** [comment]
➤ Roux Buciu commented:

QA Test notes:

  * the view is behaving correctly

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Verified as fixed on v122 (37313) with iPhone 15 Pro (17.1.2).
