### ISSUE TITLE
Remove SwiftyJSON from KeychainStore.swift

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#13377]
* Remove SwiftyJSON dependency
* Adjust any unit tests where needed
* Add unit tests to cover code not covered

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5859)

**Comment by mirscode** [comment]
I'll try to take this one up.

**Comment by data-sync-user** [comment]
➤ Orla Mitchell commented:

Stefan Vladut I notice you have this ticket in progress but a contributor already has a PR open for it. https://github.com/mozilla-mobile/firefox-ios/pull/13551 ( https://github.com/mozilla-mobile/firefox-ios/pull/13551|smart-link )

**Comment by data-sync-user** [comment]
➤ Orla Mitchell commented:

For QA please test some scenarios around signing in and out.

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Verified as fixed on v114 (30757) with iPhone 13 Pro (15.7.1).
