### ISSUE TITLE
Remove SwiftyJson from SyncMeta.swift

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#13375]
* Remove SwiftyJSON dependency from file
* Adjust existing unit tests (if they exist)
* Add unit tests to cover code not covered

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5857)

**Comment by lmarceau** [comment]
Closing as this file doesn't exists anymore
