### ISSUE TITLE
Remove SwiftyJSON from TokenServerToken.swift

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#13380]
* Remove SwiftyJSON dependency
* Adjust any unit tests where needed
* Add unit tests to cover code not covered

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5862)

**Comment by Ri-ishi** [comment]
Hi, I would like to take up this issue.

**Comment by imsanchit** [comment]
Hey @lmarceau I am looking to work on this issue, can I pick this one if yes, please suggest that in order to remove dependency on SwiftJSON would be a good option to use dictionaryObject `[String: Any]` wherever required (fromJSON, asJSON).

**Comment by lmarceau** [comment]
Hello @imsanchit, yes all removing `SwiftyJSON` dependency tasks can be worked on. Dictionary seems like a good solution here. The PR should be kept as small as possible, with unit tests. Let me know if there's anything! Also feel free to ask me those questions on [Element](https://chat.mozilla.org/#/room/#fx-ios:mozilla.org) in DM, it's easier to communicate that way.
