### ISSUE TITLE
'Zoom Page' Feature for Firefox-iOS

### ISSUE THREAD

**Issue by Piratesarereal** [mozilla-mobile/firefox-ios#13383]
Please read the product requirements for the feature.

**Accessing ‘Zoom’ Feature**

* The user will be able to access the ‘zoom’ feature from the app menu. Please view the app menu design in the shared files for the exact placement within the hierarchy. 

**Page Zoom Levels (increase or decrease)(in %)**

* Less than standard size - 50%, 75%, 90% 
* Standard size - 100%
* More than the standard size - 110%, 125%, 150%, 175%, 200%

**App Menu Update**

* Based on changes made to the zoom level, the last viewed/selected zoom level will be displayed in the ‘Zoom’ list item in the app menu. 
* For example,
* The user opens the app menu, and the user can see the ‘Zoom (100%)’ list item. The user opens the Zoom feature. 
* The user makes changes to the zoom level using ‘+' or '-' and makes it 110%.
* The user closes the zoom component using the 'X' button. 
* On the app menu, they would see the ‘Zoom (110%)’ list item which was the last updated zoom level. 
* Any subsequent changes to the zoom level of the page will update the 'Zoom ' list item to the last updated zoom level.

**Website Viewport**

* While the users are updating the zoom level, they will be able to scroll through the webpage if they want.

**Horizontal Scrolls**

* To avoid horizontal page scrolls (although not completely avoidable), the maximum zoom level should be 200%. 
* Certain accessibility guidelines recommend a zoom level of 200% of normal.

**Apply to all pages of the same domain**

* The changed zoom level is applied to any page/sub-page of the same domain. For example, if the user is on a Wikipedia article and moves to another Wikipedia article, the user will be able to see the updated zoom level reflected there as well. 
* This feature’s application would be similar to Firefox Desktop implementation. 
* Any newly opened website always starts at 100% unless it belongs to a domain with a modified zoom level.
* On refresh, maintain the updated zoom level and it stays the same unless the user changes it for that specific domain.

**Pinch to zoom** 

* Keep pinch to zoom enabled irrespective of zoom level.

**Conflict with Reader mode**

* Reader mode allows to change the text size, but changes in reader mode do not affect the non-reader mode 'zoom page' feature and vice versa.

**Closing the Page Zoom feature**

* Users can use the close 'X' button to close the page zoom level.

**Interactions with other functions visible on the page**

* Address bar - Interacting with any function doesn't dismiss the zoom level unless the user updates the URL. 
* Toolbar - If the user performs an action using <, >, Home, tabs or the app menu, it would dismiss the zoom component while performing the chosen action, but until the chosen action is done, the zoom component is visible. 

**Component Specifications**

* Please use the attached component specifications when working on the feature. 
[Component Specs.pdf](https://github.com/mozilla-mobile/firefox-ios/files/10842155/Component.Specs.pdf)

**Link to Prototypes:** 

* Light Mode Prototype - [Link](https://www.figma.com/proto/dIdFRmA0yACjkam2mb8eGq/Page-Zoom?page-id=715%3A1807&node-id=1815%3A4883&viewport=-1985%2C-112%2C0.4&scaling=min-zoom&starting-point-node-id=1815%3A4883&show-proto-sidebar=1&hide-ui=1)
* Dark Mode Prototype - [Link](https://www.figma.com/proto/dIdFRmA0yACjkam2mb8eGq/Page-Zoom?page-id=715%3A1807&node-id=1916%3A8190&viewport=-1985%2C-112%2C0.4&scaling=min-zoom&starting-point-node-id=1916%3A8190&show-proto-sidebar=1&hide-ui=1)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5865)

**Comment by lmarceau** [comment]
Implementing this work would close https://github.com/mozilla-mobile/firefox-ios/issues/7596 and https://github.com/mozilla-mobile/firefox-ios/issues/3508 I believe.

**Comment by data-sync-user** [comment]
➤ Laurie Marceau commented:

Note: this is the full design spec. Please see the epic ( https://mozilla-hub.atlassian.net/browse/FXIOS-5900 ) to ensure subtasks are done to enable this work.

**Comment by Prurite** [comment]
Hope to see this implemented (especially the zoom below 100% feature). Some websites just use way too large font for an ipad.
