### ISSUE TITLE
Google search header appearing when search suggestions are off

### ISSUE THREAD

**Issue by lmarceau** [mozilla-mobile/firefox-ios#13396]
## Steps to reproduce
- Turn off Google suggestions through settings > search > show search suggestions (off)
- Make a search in the URL bar

### Expected behavior
"Google search" header not appearing when Google suggestions are off

### Actual behavior
"Google search" header is appearing even if Google suggestions are off
![IMG_0178](https://user-images.githubusercontent.com/11338480/221952247-b59f59ed-514c-49f6-a02d-62bf297a8f10.PNG)

### Device & build information
* Device : Any device
* Build version: Main d38abc9f12be10703e69688158c511eef189ce60
* First seen version: When this "Google search" header was added, in v108 I think

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5872)

**Comment by mleers** [comment]
I think I know how to fix this one - Ill start working on it.

**Comment by lmarceau** [comment]
Reopening since needs QA

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Verified as fixed on v9000 (29455) with{color:#ffffff} {color}iPhone 14 (16.1).
This issue will still be checked when an RC will be created for the fix version.

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Verified as fixed on :Firefox: v112 (29529) with iPhone 13 Pro (15.7.1), and iPhone 14 (:iOS:16.1).
