### ISSUE TITLE
Crash when using arrow key to move down to the end of Firefox Suggest

### ISSUE THREAD

**Issue by Prurite** [mozilla-mobile/firefox-ios#13424]
## Logs
You can help us by sending us either your crash logs or Firefox logs. Instructions on how to do this [here](https://github.com/mozilla-mobile/firefox-ios/wiki/How-to-get-your-device-logs).
[Client-2023-03-02-102750.txt](https://github.com/mozilla-mobile/firefox-ios/files/10867074/Client-2023-03-02-102750.txt)

## Steps to reproduce
1. Type in address bar till Firefox Suggest appears
1. Keep pressing Arrow Down key on keyboard to scroll through the suggestions

### Expected behavior
1. The cursor stops at the last item of the suggestions

### Actual behavior
1. Firefox crashes

### Device & build information
* Device: iPad Air 5
* Build version: Firefox 109.0 (25841)

### Notes
Attachments: 
https://user-images.githubusercontent.com/44775584/222318527-8fecb784-3e5a-4513-9a76-a9e83de16bd6.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5890)

**Comment by cschumake** [comment]
Hi, I would like to work on this issue.

**Comment by OrlaM** [comment]
@cschumake It looks like a fix for this was recently merged but the developer forgot to link the PR.
#13611

**Comment by cschumake** [comment]
@OrlaM Got it, thank you!

**Comment by data-sync-user** [comment]
➤ Daniela Arcese commented:

Catalin Andrei Neculaide please add fix version
