### ISSUE TITLE
The user is not informed when the maximum limit is reached on shortcuts

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/firefox-ios#13431]
## Steps to reproduce
1. Launch Firefox.
1. Add 8 shortcuts on the homepage.
1. Attempt to add the 9th shortcut.
### Expected behavior
An error or something should appear on the screen informing the user he reached the maximum limit and his last shortcut will be replaced with the 9th one that he wanna add.
### Actual behavior
The user is not informed when the maximum limit is reached on shortcuts
### Device & build information

* Device: iPhone 13 Pro (15.7.1) 
* Build version: 9000 (29027) 
* First seen version: 9000 (29027) 
### Notes
Attachments: 

https://user-images.githubusercontent.com/42831109/222450941-66468981-c0d7-4805-a77e-8c54a536b52f.mov

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5895)

**Comment by lmarceau** [comment]
Note: The 9th tile would show if we increase the number of rows from the settings. Number of tiles per row changes per device, per orientation so any error shown would need to consider that. Unsure what this would look like if by changing orientation the tile then appears, the error shown could be confusing.
