### ISSUE TITLE
There are extra squares as placeholders for the shortcuts

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/firefox-ios#13434]
## Steps to reproduce
1. Launch FF and add any shortcut.
2. Observe the extra squares.
### Expected behavior
The square placeholders should not be displayed.
### Actual behavior
There are extra squares as placeholders for the shortcuts.
### Device & build information
* Device: iPhone 13 Pro (15.7.1) 
* Build version: 9000 (29027) 
* First seen version: 9000 (29027) 
### Notes
I added a screenshot from Focus too.
Attachments: 

![image0 (5)](https://user-images.githubusercontent.com/42831109/222456537-f712baf6-b23a-49bf-8422-94808a111f79.png)
![image1](https://user-images.githubusercontent.com/42831109/222456569-52515d3d-5276-4803-b558-086dced51ba2.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5898)

**Comment by lmarceau** [comment]
Note: The current behavior is that completely empty rows won't show (ex: user has 3 rows but only enough tiles to file 1 row and a half, the third row won't show). Empty spaces in not completely filled rows will be filled with empty squares. This is easy to change if we remove the outline of the empty square.

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Verified as fixed on v9000 (29455) with{color:#ffffff} {color}iPhone 13 Pro (15.7.1).
This issue will still be checked when an RC will be created for the fix version.

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Verified as fixed on v112 (29529) with iPhone 13 Pro (15.7.1), and iPhone 14 (16.1).
