### ISSUE TITLE
Stuck on the `Passwords` section as the `Done/Back` buttons are missing

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/firefox-ios#13447]
## Steps to reproduce
1. Launch FF and log in with a valid credential.
2. Access the Passwords section from the hamburger menu.
3. Observe the top of the section.
### Expected behavior
The `Done` button should be displayed or back in order to return to the main menu.
### Actual behavior
Stuck on the `Passwords` section as the `Done/Back` buttons are missing.
### Device & build information
* Device: iPhone 13 Pro (15.1.7) 
* Build version: v9000 (29238) 
* First seen version: N/A
### Notes
**Please note that the only workaround for this is to enter the edit mode -> tap on the cancel button -> the Done button appears.**
Please note that when accessing the `Passwords` section from the FF settings, the `Settings` back button is present.
Not reproducible on v111 (28916) and v110.2 (29283).
Attachments: 

https://user-images.githubusercontent.com/42831109/222722093-c0fbd437-17a6-443c-93c4-0f98512a9189.mov

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5907)

**Comment by abodea** [comment]
@nishant2718 I saw you assigned to https://github.com/mozilla-mobile/firefox-ios/issues/13454 but that is a duplicate after my issue.

**Comment by nbhasin2** [comment]
I am on build 28916 and can’t reproduce this and see the done button

**Comment by nbhasin2** [comment]
Attaching video for reference on 28916 build. I am logged into sync 

https://user-images.githubusercontent.com/8919439/223164656-882dadf9-db1c-43ed-983f-8aa7b8b14758.mov

**Comment by nbhasin2** [comment]
Attaching video for reference on 28916 build. I am logged into sync

https://user-images.githubusercontent.com/8919439/223164956-72bca426-eb52-46b6-bbd0-903a7bbff180.mov

**Comment by clarmso** [comment]
I can reproduce the issue when I'm logged in to the Firefox account as well.

**Comment by nbhasin2** [comment]
@abodea yeah I am not sure if there are other areas but if you find areas where it was broken before just try it 
- Opening passwords / logins from the hamburger menu (show done)
- Opening passwords / logins from settings menu (do not show done)

**Comment by data-sync-user** [comment]
➤ Alina Moldovan commented:

Verified as fixed on :Firefox: v112 (29529) with  iPhone 14 Plus (:iOS:16.0.3)

The following scenarios was validated: 

1. Done button is present while accessing the Password section from hamburger menu while FxA account is logged in 

2. Done button is present while accessing the Password section from hamburger menu while FxA account is NOT logged in

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Verified as fixed on v111.2 (29672) with iPhone 13 Pro (15.7.1), and iPad mini 5 (14.7.1).
