### ISSUE TITLE
 Screen Rotation Problem in Iphone  8 PLus

### ISSUE THREAD

**Issue by ArifulIslam99** [mozilla-mobile/firefox-ios#13458]
### Device & build information
* Device : ? 
* Build version: ? 
* First seen version: ? 
### Notes
Attachments: 

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5911)

**Comment by lmarceau** [comment]
Closing for now, please let us know if any other information can be provided.
