### ISSUE TITLE
Remove SpyNotificationCenter to use NotificationProtocol/MockNotificationCenter instead

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#13471]
`SpyNotificationCenter` was created before we had `NotificationProtocol`/`MockNotificationCenter`. The later is better and easier to assert for testing. Let’s remove `SpyNotificationCenter`.

### Acceptance criteria
- Remove `SpyNotificationCenter` from `TopSitesDataAdaptorTests`, `JumpBackInDataAdaptorTests` and `SearchBarSettingsViewModelTests` and replace existing tests cases with `MockNotificationCenter`. For the case of `SearchBarSettingsViewModel` you'll need to replace `NotificationCenter` with `NotificationProtocol` in the init and variable, so `MockNotificationCenter` can be used.
- Remove `SpyNotificationCenter` file
- Bonus point: you can add tests cases in the tests classes if you see some opportunities

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5929)

**Comment by Rrishii** [comment]
Hi! I am new to the project and would like to work on this issue.

**Comment by lmarceau** [comment]
Hi @Ri-ishi, sounds great! I added a little more details in the description. Let me know if there's anything.

**Comment by data-sync-user** [comment]
➤ Laurie Marceau commented:

Closing, nothing to QA since this affect mostly unit tests with mocks
