### ISSUE TITLE
The `Standard` and `Strict` ETP options are not grayed out when re-entering the ETP menu

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/firefox-ios#13485]
## Steps to reproduce
1. Launch FF.
2. Access any webpage.
3. Tap on the ETP shield.
4. Turn off ETP (the Standard and Strict options are grayed out).
5. Re-enter the ETP menu.
### Expected behavior
The `Standard` and `Strict ETP options should still be grayed out.
### Actual behavior
The `Standard` and `Strict ETP options are not grayed out when re-entering the ETP menu.
### Device & build information
* Device: iPhone 13 Pro (15.7.1) 
* Build version: v9000 (29331), v111 (29345) 
* First seen version: N/A 
### Notes
Attachments: 

https://user-images.githubusercontent.com/42831109/223476685-1e0f8538-1e35-4a7e-9675-5d49269b57a7.mov

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5934)

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Verified as fixed on v9000 (29455) with{color:#ffffff} {color}iPhone 14 (16.1).
This issue will still be checked when an RC will be created for the fix version.

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Verified as fixed on v111.2 (29672) with iPhone 13 Pro (15.7.1).
