### ISSUE TITLE
Selected passwords are different after filtering

### ISSUE THREAD

**Issue by orellazri** [mozilla-mobile/firefox-ios#13530]
## Steps to reproduce
Go into the password manager, click Edit, search for something in the Filter input, select some passwords, click Cancel.

### Expected behavior
Should see the same passwords selected when filtered

### Actual behavior
The selected passwords are different

### Device & build information
* Device : iPhone 12 Pro Max, iOS 16.3.1
* Build version: 110.2 (29283)
* First seen version: Only seen now
### Notes
Attachments: 

https://user-images.githubusercontent.com/32670283/224287158-fbb14f4e-0e65-439b-8bac-657d31df0c83.mov

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5955)

**Comment by data-sync-user** [comment]
➤ Alina Moldovan commented:

Validated this issue using iPad Air 3dr gen (16.3.1) and iPhone 14+ (16.0.1) and FF v9000 (32297)

Issue doesn't reproduce anymore
