### ISSUE TITLE
Cache "last page"

### ISSUE THREAD

**Issue by xxFlare** [mozilla-mobile/firefox-ios#1354]
I was wondering if you guys can make it possible for FireFox to cache the last page, so when you hit back button the page will load in a snap rather then refreshing!

**Comment by aterribili** [comment]
:+1:

**Comment by st3fan** [comment]
This is out of our control since we depend on WebKit. But having said that, a reload should not always happen. You should see the exact same behaviour as on Mobile Safari, which certainly caches pages.

Marking as needs bug so that we can investigate.

**Comment by farhanpatel** [comment]
if the back button is pressed quick enough then the page is cached.
