### ISSUE TITLE
Passwords screen crashes when filtering the list of passwords and then hitting Cancel

### ISSUE THREAD

**Issue by nishant2718** [mozilla-mobile/firefox-ios#13558]
## Steps to reproduce
1. Sign into Sync
2. Go to passwords and Logins screen from settings
3. Search your list of passwords by filtering in the textfield 
4. Select some passwords and hit cancel

### Expected behavior
The screen resets back to the original list of passwords
### Actual behavior
The app crashes due to race conditions caused by varying priority Dispatches.
### Device & build information
* Device: Tested on iPhone sim and iPhone12 mini on `main`
* Build version: `main`

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5965)

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Verified as fixed in v9000 (29574) with iPhone 13 Pro (15.7.1).

To be re-checked when the official release will be built.Nishant Patel can you please set the Fix version?

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Verified as fixed on v111.2 (29672) with iPhone 13 Pro (15.7.1), iPhone 14+ (16.0.1), and iPad mini 5 (14.7.1).
