### ISSUE TITLE
The sync is not performed after successfully logging in on `iOS 15.x.x`

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/firefox-ios#13560]
## Steps to reproduce
1. Launch FF.
2. Access settings and FF account.
3. Login.
4. Attempt to sync in settings or Synced tabs.
### Expected behavior
The sync should be performed without issues.
### Actual behavior
The sync is not performed after successfully logging in on `iOS 15.x.x`.
### Device & build information
* Device: iPhone 13 Pro (15.7.1) 
* Build version: v9000 (29455). 
* First seen version: N/A 
### Notes
Please note that I was not able to reproduce on iPhone 14 (16.1), iPhone 14 Plus (16.0.3), and iPhone SE (16.1)
It was very weird that when accessing Settings -> Manage Account & Devices it was displayed like I was not logged in. Even after typing there the email and password and logging again the sync still didn't work.
_**Please note that I'm able to reproduce it all the time on a fresh install on iPhone 13 Pro Max (15.7.1).**_
The time was set to automatically this is the only version I was able to reproduce.

Attachments: 

https://user-images.githubusercontent.com/42831109/224756411-aa1780f0-4a26-4e1e-a6b8-8a71c48de56e.mov

https://user-images.githubusercontent.com/42831109/224756441-fff1bfb6-03c7-4995-b2ec-e0fd359d00d4.mov

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5966)

**Comment by abodea** [comment]
After restarting the device, it looks like working again, not really sure of what happened.

**Comment by dnarcese** [comment]
@abodea I am going to close the issue for now, re-open if you see it again!
