### ISSUE TITLE
A lot of empty spaces in the context menu from tabs tray

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/firefox-ios#13573]
## Steps to reproduce
1. Launch FF.
1. Long tap on the tabs tray.
### Expected behavior
There should not be so much empty space in the context menu and below the `Close tab`.
### Actual behavior
A lot of empty spaces in the context menu from the tabs tray
### Device & build information

* Device: **iPhone 13 Pro Max (15.7.1).** 
* Build version: **v9000 (29455)** 
* First seen version: N/A 
### Notes
Attachments: 

![IMG!UNITO-UNDERSCORE!0295](https://user-images.githubusercontent.com/42831109/225030108-1ae41a9b-4039-422e-9acd-5c433b8b4813.PNG)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5972)

**Comment by lmarceau** [comment]
IMO the space to the right of the labels is fine. The space that shouldn't be there I believe is the one below the "Close Tab". This extra space is present on all PhotonActionSheet menu, and it shouldn't.
