### ISSUE TITLE
Shared or sent tabs can arrive behind the search screen and be replaced by the search result

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/firefox-ios#13603]
## Steps to reproduce

1. In another app, such as Twitter, use the iOS share feature to share a link to Firefox and “Load in background.”
2. Switch to Firefox. 
3. Quickly open a new tab and start typing into the address bar. You should see some search suggestions, but don’t select  them or press return.
4. Wait a few seconds.

### Expected behavior

The shared link should open in a new background tab. 

### Actual behavior

The shared link opens in the current “new” tab behind the search suggestions. If you don’t notice the loading progress bar flash, you can select a search suggestion or press return, thus unknowingly navigating away from the shared page.

This bug is a corner case, but I’ve been bitten by this bug quote a few times because this bug affects both links shared from other apps and tabs sent from Firefox desktop (which might arrive at some surprising delayed time).

### Device & build information

* Device : iPhone 12 running iOS 16.3.2
* Build version: TestFlight 9000 (29455) 3/12 build
* First seen version: I don’t remember. I think this is a long-standing bug.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5992)

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Verified as fixed on v114 (31032) with iPhone 13 Pro (15.7.1).
