### ISSUE TITLE
Hero images are being re-used

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#13617]
!image-20230315-211750.png|width=720,height=554!

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5997)

**Comment by data-sync-user** [comment]
➤ Orla Mitchell commented:

For QA the underlying issue is pretty difficult to reproduce so just ensuring there are no regressions in favicon behaviour is probably enough for this ticket.

**Comment by DianaBarladeanu** [comment]
Verified as fixed on v9000 (32297) with iPhone SE (15.4)
