### ISSUE TITLE
Firefox 111 on iOS crashes continuously 

### ISSUE THREAD

**Issue by eagle1701a** [mozilla-mobile/firefox-ios#13618]
Since last update, Firefox 111 on iOS 16.3.1 , iPhone 14 Pro, crashes in any conditions, even if it’s not navigating.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5998)

**Comment by abodea** [comment]
Hello, @eagle1701a I had no issues on v111, can you please give more details or add a crash log?

**Comment by eagle1701a** [comment]
Hi,It happens mainly if I open the menu, but also during navigation. I’ve reinstalled it three times.Where can i find the crash log?Il giorno 16 mar 2023, alle ore 10:17, Andrei Bodea ***@***.***> ha scritto:﻿
Hello, @eagle1701a I had no issues on v111, can you please give more details or add a crash log?

**Comment by abodea** [comment]
> Hi, It happens mainly if I open the menu, but also during navigation. I’ve reinstalled it three times. Where can I find the crash log?

Hello, @eagle1701a tomorrow morning I will get back to you and try to help on how to get the crash log, thank you for responding!

**Comment by eagle1701a** [comment]
here is the log:

[Firefox.log](https://github.com/mozilla-mobile/firefox-ios/files/10993024/Firefox.log)

**Comment by eagle1701a** [comment]
HI,

I haver no crash logs at all...

**Comment by lmarceau** [comment]
Oh interesting, reinstalling the application probably removed them. If you encounter the crash again you should see the crash logs thought. Let us know if any part of the wiki page isn't clear on how to retrieve those logs. Thanks a lot for your time!
