### ISSUE TITLE
Save and X buttons are missing from Edit Bookmark view 

### ISSUE THREAD

**Issue by alinamoldovan84** [mozilla-mobile/firefox-ios#13623]
## Steps to reproduce
1. open a new tab and load a webpage 
2. open the hamburger menu and choose to add bookmark 
3. From the toast notification choose Edit 
4. Check the edit view and perform some changes 

### Expected behavior
Save and X buttons should be available, user is not able to save the changes or close the view

### Actual behavior
Save and X buttons are missing - user is not able to complete th

### Device & build information
* Device : iPhone 14 Plus (16.0.3) 
* Build version:  v112 (29529)  
* First seen version: v112 
### Notes
The bug doesn't preproduce using v111.1  version 
The workaround is to close the view by swiping down 
The bug doesn't reproduce if the edit action is triggered from the bookmarks list.  
 
Attachments: 

![Skype_Picture_2023_03_16T17_15_25_508Z](https://user-images.githubusercontent.com/124251579/225699765-5c1b75b5-d968-49c5-ae37-3d024e8789a1.jpeg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6001)

**Comment by cschumake** [comment]
I do not see any pull requests for this issue. I will attempt to fix it.

**Comment by data-sync-user** [comment]
➤ Nishant Bhasin commented:

Contrib PR: https://github.com/mozilla-mobile/firefox-ios/pull/13648 ( https://github.com/mozilla-mobile/firefox-ios/pull/13648|smart-link )

**Comment by data-sync-user** [comment]
➤ Alina Moldovan commented:

Verified as fixed on :Firefox: v9000 (29784) with iPhone 14 Plus (16.0.3).

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Verified as fixed on v113 (30043) with iPhone 13 Pro (15.7.1).

**Comment by FEER0** [comment]
Issue still present on
iPhone 11
iOS 16.3.1
Firefox version 112.2 (30158)

**Comment by lmarceau** [comment]
@FEER0 the fix will be part of version 113. Thank you and let us know if that version doesn't fix the problem!
