### ISSUE TITLE
Autofill background Color doesn't properly reflect the theme

### ISSUE THREAD

**Issue by aalaaeid** [mozilla-mobile/firefox-ios#13620]
### Steps to reproduce

1. Type in address bar till autofill text appears 
2. switch device appearance to light mode while Firefox in the background
3. open FireFox again 
4. Autofill background Color won't reflect until scrolling

![225579513-0d07386a-27d5-4431-bee7-6f1f44d53667](https://user-images.githubusercontent.com/42831109/225659068-5013475f-8bd5-40ad-b105-da545d9637bb.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5999)

**Comment by abodea** [comment]
Hello, @aalaaeid thank you for adding this issue, I can also reproduce it on v112 (29529) with iPhone 13 Pro (15.7.1).

**Comment by lmarceau** [comment]
The theming system wasn't entirely updated in the URL bar area, so this should be theoretically be fixed when https://github.com/mozilla-mobile/firefox-ios/issues/12851 and https://github.com/mozilla-mobile/firefox-ios/issues/12850 are done I believe.

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Verified as fixed on v9000 (29988) with iPhone 13 Pro (15.7.1).
This issue will also be checked when an official RC build is created for the fix version.
