### ISSUE TITLE
Problems in auto split screen. 

### ISSUE THREAD

**Issue by ArifulIslam99** [mozilla-mobile/firefox-ios#13633]
### Device & build information
* Device : ? 
* Build version: ? 
* First seen version: ? 
### Notes
Attachments: 

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6005)

**Comment by lmarceau** [comment]
@ArifulIslam99 could you provide more information on the issue you are experiencing with auto split screen? I.e. what is happening, what are the steps to get the issue, can you provide a video/screenshot, on which device/OS is this happening? Thank you
