### ISSUE TITLE
Wrong text displayed on `Touch ID` unlock Biometrics

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/firefox-ios#13636]
## Steps to reproduce
1. Set a passcode and a Touch ID as biometrics.
2. Access FF and access the passwords section.
3. Observe the Biometrics screen.
### Expected behavior
The Fingerprint Biometrics text should be `Use your fingerprint to access passwords now` and `Use your fingerprint to access passwords now` when the fingerprint is wrong.
### Actual behavior
Wrong text displayed on `Touch ID` unlock Biometrics
### Device & build information
* Device : iPad mini 5 (14.7.1) 
* Build version: 9000 (29574) 
* First seen version: N/A 
### Notes
It cannot show add your passcode when your biometric is fingerprint, the text is misleading. 

Attachments: 

![image1 (3)](https://user-images.githubusercontent.com/42831109/226342962-c34fb844-a36b-486c-9063-dd3f27276b94.png)

@nishant2718 Please note that before the fix it was like this

![image0](https://user-images.githubusercontent.com/42831109/226343088-75d170d5-be65-4365-988f-c9d5641179bc.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6006)

**Comment by data-sync-user** [comment]
➤ Emily Wachowiak commented:

Please update the string to: “Authenticate to access passwords.”

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Verified as fixed on v115 (31834) with iPad mini 5 (14.7.1).
