### ISSUE TITLE
Saving animated gifs

### ISSUE THREAD

**Issue by lmarceau** [mozilla-mobile/firefox-ios#13646]
Originally reported with https://github.com/mozilla-mobile/firefox-ios/issues/7774 but was staled. Reopening since user reported this is still an issue.

## Issue
The browser is no longer saving animated gifs when save image is selected

### Expected behavior
The image should be animated when viewed in the photos app

### Actual behavior
A static image of the animated gif is saved

Note: Potentially only reproducible on iPad, to be confirmed.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6009)

**Comment by VPaulV** [comment]
On waylald firefox I cannot copy gif as well, only one frame

**Comment by tisumi99** [comment]
### Before

https://github.com/mozilla-mobile/firefox-ios/assets/98071325/8a701c52-76ff-4a5a-bc28-68e244c3e42a

### After

https://github.com/mozilla-mobile/firefox-ios/assets/98071325/2141225e-c9f0-4e1d-a871-cfb44ca73103

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Verified as fixed on v9000 (43298) with iPhone 15 Pro (17.5.1).

**Comment by data-sync-user** [comment]
➤ Adina Petridean commented:

Verified as fixed on Firefox 132.0(46208) with iPhone 14 Pro Max (iOS 16.2).
