### ISSUE TITLE
Firefox crashes when adding a bookmark without the URL in a newly created folder `EXC_BAD_ACCESS BookmarksPanel.flashRow`

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/firefox-ios#13673]
## Sentry
https://mozilla.sentry.io/issues/3527127945/?project=6176941&referrer=release-issue-stream
## Steps to reproduce
1. Launch Firefox.
2. Access the bookmarks section.
3. Create a new folder in the bookmark sections.
4. Enter edit mode and add a bookmark without adding the `URL` only the `Title`.
### Expected behavior
An error should be returned that the bookmark cannot be created without URL.
### Actual behavior
Firefox crashes when adding a bookmark without the URL in a newly created folder.
 * Device : iPhone 13 Pro (15.7.1) 
* Build version: v9000 (29633) 
### Notes
**Please note that I'm able to reproduce this issue only after creating a new folder and in that folder adding a new bookmark without a URL.**
I was able to reproduce it while being logged in too.
Attachments: 

https://user-images.githubusercontent.com/42831109/226904778-1cf0fc6d-25f1-4713-9ab2-9bed94c21401.mov

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6025)

[Crashlogs.zip](https://github.com/mozilla-mobile/firefox-ios/files/11039927/Crashlogs.zip)

**Comment by cschumake** [comment]
Hi, I do not see a pull request for this issue. I will try and fix it.

**Comment by lmarceau** [comment]
@dnarcese 🙏 ^^

**Comment by dnarcese** [comment]
@cschumake for now let's just disable the save/done button if the URL field is blank.

**Comment by data-sync-user** [comment]
➤ Alina Moldovan commented:

Verified as fixed in v9000 (29966) with iPhone 14 Plus (16.0.3).

The current behavior is that the Save button is disabled if “http://“ or “https://“ is mossing from the link.
