### ISSUE TITLE
Sites visited on private appearing on suggested and tab markers keep disappearing IOS app after update 

### ISSUE THREAD

**Issue by xxkd23** [mozilla-mobile/firefox-ios#13689]
### Device & build information
* Device : iPad 8, iOS version 15.4.1 
* Build version: ? Firefox 110.2 (29283)
* First seen version: ? New to the version
### Notes
Attachments: 

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6039)

**Comment by dnarcese** [comment]
Can you please provide steps of how you are seeing this and screenshots of the issue if possible.

**Comment by xxkd23** [comment]
Hi Daniela,

 

thank you for getting back to me it happens when I go to the private mode on my iPad and then start typing in the url be, sites that I have visited when on private are now suggested sites as I type.

 

i can also search for them in my history but nothing happens when I swipe to deleted, they disappear momentarily and then reappear when I type the url or name of the site 

 

this happened after the recent update 

 

as for the tabs they the test and markers disappear when I press the home button or go to another app and then come back 

 

please fix these issues 

 

thanks

 

Sent: Thursday, March 23, 2023 at 6:59 PM
