### ISSUE TITLE
Review Download.swift file delegate to be weak

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#13690]
Noticed we have some delegates that aren't marked as weak in the code. Delegates should normally be weak to avoid reference cycles. This task is to review Download.swift delegate to mark it as weak, and add tests for it.

To add tests for leaks in our code, you can use `trackForMemoryLeaks`.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6040)

**Comment by parthv21** [comment]
I can't find the `Download.swift` file. Can someone help me locate it? Thanks!

**Comment by lmarceau** [comment]
Hello, turns out the file is named `DownloadQueue.swift`, but the class is `Download` with it's delegate being `var delegate: DownloadDelegate?`

**Comment by parthv21** [comment]
Created a pull request. Please take a look and let me know if it looks good.

**Comment by data-sync-user** [comment]
➤ Laurie Marceau commented:

For QA it can be tested that Downloads under the downloads panel works as expected

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Validated on v124(38904), with iPhone 15(17.0).
