### ISSUE TITLE
Review CredentialPasscodeRequirementViewController delegate to be weak 

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#13693]
Noticed we have some delegates that aren't marked as weak in the code. Delegates should normally be weak to avoid reference cycles. This task is to review CredentialPasscodeRequirementViewController delegate to mark it as weak, and add tests for it.

To add tests for leaks in our code, you can use `trackForMemoryLeaks`.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6043)

**Comment by Ri-ishi** [comment]
Hi, I would like to try to fix this issue.

**Comment by bmihai23** [comment]
Hi @PARAIPAN9, I would like to work on this issue. Thank you!

**Comment by PARAIPAN9** [comment]
Sure, no problem!!
