### ISSUE TITLE
v111.1 (and main) fails to reload multi-word searches on launch

### ISSUE THREAD

**Issue by gutley** [mozilla-mobile/firefox-ios#13729]
## Steps to reproduce
On an iPad with a fresh install of Firefox 
Launch the app
In the address bar, enter "cheese sandwich" and run the search
The tab get named "cheese sandwich" and the web view shows the search results
Quit the app
Relaunch the app
### Expected behavior
The app launches with a single tab called "cheese sandwich" and the web view shows the search results
### Actual behavior
The app launches with a single tab called "cheese sandwich" and the web view shows the Firefox home page.
See screen recording
### Device & build information
* Device : Any iPad (simulated or not)
* Build version: ? v111.1 App Store and branch release/111.0 TOT (2c4b70bef743fe7ddac67253633dd3884ab4fd61)
* First seen version: ? Not seen it before 111.x
### Notes
Actually iPhones will do the same thing so its not just iPad.

If you create other tabs they also have the issue.

Also happens on main branch too.

Attachments: 

https://user-images.githubusercontent.com/2040690/227514448-65c55106-3d70-464e-9324-cfc3ef545812.mov

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6062)

**Comment by gutley** [comment]
BTW - Both those versions of getQuery pass all the unit tests in NSURLExtensionTests

**Comment by thatswinnie** [comment]
Thanks so much @gutley for reporting this and coming up with 2 possible fixes. I'll take a look at it and get this fixed soon.
