### ISSUE TITLE
[Crash] Firefox crashes when opening a link from Notes - only on iOS 14

### ISSUE THREAD

**Issue by alinamoldovan84** [mozilla-mobile/firefox-ios#13731]
## Centry 
https://mozilla.sentry.io/issues/3082240160/?project=6176941&referrer=release-issue-stream
https://mozilla.sentry.io/releases/org.mozilla.ios.Firefox%4098.0%2B8233/?project=6176941

## Steps to reproduce

1. Launch Firefox iOS and navigate to the Home screen. 
2. Open the hamburger menu and choose Settings 
3. Tap the "Set as default Browser" option 
4. Tap "Default Browser App" and set Firefox as the default browser 
5. From notes, tap on "www.google.com"

### Expected behavior
The "www.google.com" webpage is lunched in Firefox 

### Actual behavior
Firefox crashes 

### Device & build information
* Device : iPad Air 3rd Gen (14.0.1) 
* Build version: V112 (29676) / v9000 (29677) 
* First seen version: 98.0 (8233) 

### Notes
Issue is not reproduceable using the following: 

- iPad mini 5 - iOS 14.7
- iPhone 14 Plus - iOS (16.0.3) 
- iPhone 13 Pro - iOS (15.7.1) 

iPad Air 3rd Gen (14.0.1) is the only device I was able to reproduce this bug. 

Attachments: 

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6066)

**Comment by dnarcese** [comment]
Closing as not reproducible anymore.
