### ISSUE TITLE
URL bar Image area doesn't reflect when changing the default search engine

### ISSUE THREAD

**Issue by aalaaeid** [mozilla-mobile/firefox-ios#13745]
## Steps to reproduce

1. Launch FF and reach settings.
2. Access the Search section.
3. change default search engine  
4. back to setting then tap done to save change

### Expected behavior
URL bar Image should reflect immediately to the new search engine image 

### Actual behavior
URL bar Image won't reflect until tapping on bar 

### Device & build information
* Device : iPhone 11

Attachments: 

https://user-images.githubusercontent.com/37640295/227653710-ff6eeee0-4ad0-47cb-a5c8-d57ad25ef8b4.MP4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6070)

**Comment by data-sync-user** [comment]
➤ Raluca Iordan commented:

This issue was fixed when I was in PTO by this PR https://github.com/mozilla-mobile/firefox-ios/pull/13906 ( https://github.com/mozilla-mobile/firefox-ios/pull/13906|smart-link ) 

I checked it and now it is working properly. Moved the ticket QA Needed. Thank you!

**Comment by data-sync-user** [comment]
➤ Alina Moldovan commented:

Verified this issue using the v9000 (30588) FF build and iPhone 14 Plus (16.0.3). Not able to reproduce this issue anymore.

**Comment by data-sync-user** [comment]
➤ Alina Moldovan commented:

Verified this issue using FF v114 (30757) and iPhone 14 Plus (16.0.3). Not able to reproduce this issue anymore.

**Comment by data-sync-user** [comment]
➤ Laurie Marceau commented:

Putting back to QA verified since I see in the comments it was verified. Let me know if that’s not ok Alina Moldovan

**Comment by data-sync-user** [comment]
➤ Alina Moldovan commented:

Laurie Marceau since this issue still reproduces for tablets we can either reopen this bug or create another one specific for tablets. Please tell me how you prefer.

**Comment by data-sync-user** [comment]
➤ Laurie Marceau commented:

I think we can maybe create a new one and link to this one? 🙏 Thank you!

**Comment by data-sync-user** [comment]
➤ Alina Moldovan commented:

Laurie Marceau the issue was logged separately Please see here ( https://github.com/mozilla-mobile/firefox-ios/issues/14914 ).  Thank you!
