### ISSUE TITLE
Documents folder once again littered with cruft

### ISSUE THREAD

**Issue by gutley** [mozilla-mobile/firefox-ios#13751]
I while back I raised an issue around wallpapers being downloaded to the user's documents folder when they didn't belong there. Today (on v111.x) I notice that other stuff is now ending up in Documents that would be better placed elsewhere:

- favicon-url-cache
- change-ua-set-of-hosts.xcarchive
- safelist

None of these files has any value being in there other than to polute the Documents folder in the Files app

<img width="626" alt="image" src="https://user-images.githubusercontent.com/2040690/227975662-f6e92b09-c307-4db4-a581-a596ba658480.png">

Please can we stop putting inappropriate stuff in Documents and use a better location that won't be seen by users. Suggest either .cachesDirectory or .applicationSupportDirectory.

The only files which should end up in Documents are the Downloads and any files copied there via the Debug options ("copy databases to app container", "copy log files to app container" etc)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6072)

**Comment by lmarceau** [comment]
Yeah great point, I'll create one issue for the favicon and one issue for the user-agent. 

Favicon ticket: https://github.com/mozilla-mobile/firefox-ios/issues/13753
UA ticket: https://github.com/mozilla-mobile/firefox-ios/issues/13754

**Comment by lmarceau** [comment]
Closing this issue since this will be handled in other tickets.
