### ISSUE TITLE
Change folder to cache for favicon-url-cache

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#13753]
!image-20230327-173732.png|width=1252,height=724!

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6073)

**Comment by gutley** [comment]
@lmarceau - FYI - My original issue also mentioned the 'safelist' file as also erroneously going in Documents, but I think you missed that when you created the two child issues.

**Comment by lmarceau** [comment]
@gutley here's the other task for this case https://github.com/mozilla-mobile/firefox-ios/issues/13761

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Verified as fixed on :Firefox: v113 (300010) with iPhone 13 Pro (15.7.1) and iPad mini 5 (14.7.1).
