### ISSUE TITLE
Change folder to cache for safelistFileURL

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#13761]
The safelistFileURL for ContentBlocker currently save the file under the documentDirectory. Let’s change this to be under the cache folder.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6079)

**Comment by cschumake** [comment]
Hi, I do not see a pull request for this issue. I will attempt to make the necessary updates.

**Comment by lmarceau** [comment]
@cschumake forgot to note in the task, we should ensure we can migrate files for this. You can look at how it was done for https://github.com/mozilla-mobile/firefox-ios/issues/13753 (there's two PRs)

**Comment by cschumake** [comment]
@lmarceau Got it, thanks!

**Comment by data-sync-user** [comment]
➤ Roux Buciu commented:

For QA, please verify that the safelist file is no longer in the document directory. To verify you will need to run an older version of the app and then update to the latest and launch the app.

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Verified as fixed on v122 (37686) with iPhone 15 Pro (17.1.2).
