### ISSUE TITLE
Private browsing - login details are kept 

### ISSUE THREAD

**Issue by alinamoldovan84** [mozilla-mobile/firefox-ios#13760]
## Steps to reproduce
1. Open a private Firefox tab 
1. Go to https://bugzilla.mozilla.org 
1. Log into the app with valid credentials 
1. Close the tab 
1. Open a new private tab 
1. Go to  https://bugzilla.mozilla.org 

### Expected behavior
User is logged out 

### Actual behavior
User is still logged in

### Device & build information
* Device : iPhone 14 Plus (16.0.3) iPad Air 3rd gen (16.3.1) 
* Build version: v111.2 (29672)  
* First seen version: ? 
### Notes
* Able to reproduce this issue using  iPhone 14 Plus (16.0.3) iPad Air 3rd gen (16.3.1) 
* Not able to reproduce this issue using: iPhone 13 Pro (15.7.1), iPad mini 5 (14.7), iPhone 14 (16.0.1)

Attachments: 

https://user-images.githubusercontent.com/124251579/228258659-8d109542-d35e-47e0-b6af-87599d3c7b53.MP4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6078)

**Comment by data-sync-user** [comment]
➤ Alina Moldovan commented:

This issue still reproduces using v139 (54672)
