### ISSUE TITLE
When adding a new log in the text cursor is positioned on the opposite side while typing on RTL locale (`ar`)

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/firefox-ios#13799]
## Steps to reproduce
1. Set the language to AR.
1. Launch FF and access the passwords section.
1. Add a new login.
1. Type anything in any field: `website` `username`. 
### Expected behavior
While typing the text cursor should be on the opposite side.
### Actual behavior
When adding a new log in the text cursor is positioned on the opposite side while typing on RTL locale (`ar`).
### Device & build information

* Device: iPhone 13 Pro (15.7.1). 
* Build version: v9000 (29812) 
* First seen version: N/A 
### Notes
Note that for passwords the behavior is correct.
Attachments: 

![image0 (4)](https://user-images.githubusercontent.com/42831109/228870672-81653222-1aa4-4720-bda0-eb6513df7bcd.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6099)

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v9000 (39777), with iPhone 15 (17.0).

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v125 (39935), with iPhone SE (16.6).
