### ISSUE TITLE
The newly created login is not correctly aligned in RTL locale (`ar`)

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/firefox-ios#13797]
## Steps to reproduce
1. Set the language to AR.
2. Launch FF and access the passwords section.
3. Create a new login.
4. Observe the newly created login position.
### Expected behavior
The position of the newly created login should be aligned with the rest of the options on the screen.
### Actual behavior
The newly created login is not correctly aligned in RTL locale (`ar`).
### Device & build information
* Device: iPhone 13 Pro (15.7.1). 
* Build version: v9000 (29812) 
* First seen version: N/A 
### Notes
Attachments: 

![image](https://user-images.githubusercontent.com/42831109/228867839-64cca2bf-8912-438c-8ad9-2d90e8421fef.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6097)

**Comment by DianaBarladeanu** [comment]
Verified as fixed on v9000 (32311) with iPhone SE (15.4).
