### ISSUE TITLE
The `Not now` button overlaps the 3 dots at the bottom on certain languages

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/firefox-ios#13796]
## Steps to reproduce
1. Launch FF.
2. Observe the notification onboarding card after the sync card.
### Expected behavior
The text/elements on the card should not overlap with the 3 dots at the bottom.
### Actual behavior
The `Not now` button overlaps the 3 dots at the bottom on certain languages### Device & build information
* Device: iPad Pro (16.2) simulator 
* Build version: Latest main (v112.1)
* First seen version: N/A 
### Notes
Please note I tried on: Spanish, German, and French and I was able to reproduce it but I think it's reproducible in the languages that have longer words/characters.

Attachments: 

![image](https://user-images.githubusercontent.com/42831109/228856322-eec54dcf-345c-43af-bd59-d27245d894f6.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6096)

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Re-opened in v113 (30385)/9000 (30398) with iPhone 13 Pro (15.7.1) / iPad mini 5 (14.7).
please note that the bottom of the button Skip and Notw now are cut off the screen and now 2 of the onboarding cards are scrollable…
Aarjav PandyaI saw your comment on the PR but the behavior now is inconsistent and having to scroll in 2 onboarding cards from 3 is not really something consistent and having only on two cards from 2 the bottom cutoff…
Sorin ParaipanDaniela Arcesecan you please help with the fix version?

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Verified as fixed on v114 (31032) with iPad Pro (16.4.1).
