### ISSUE TITLE
Update toast messages to be displayed in camel case 

### ISSUE THREAD

**Issue by alinamoldovan84** [mozilla-mobile/firefox-ios#13801]
## Steps to reproduce
1. Navigate to cnn.com 
2. Long tap an article 
3. Chose to open it in a new private tab
4. Check the toast message 

### Expected behavior
"New Private Tab Opened" message is displayed in camel case 

### Actual behavior
"New Private Tab opened" message is displayed

### Device & build information
* Device: iPhone  14 Plus (16.0.3) 
* Build version: V9000 (29812) 
* First seen version: V9000 (29812)  
### Notes
Attachments: 

![Skype_Picture_2023_03_30T17_41_09_826Z](https://user-images.githubusercontent.com/124251579/228919772-cd32f21b-89da-4a22-bf89-b6885cb5b6f1.jpeg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6100)

**Comment by data-sync-user** [comment]
➤ Alina Moldovan commented:

Verified as fixed in v9000 (29966) with iPhone 14 Plus (16.0.3).

A new issue was logged for the normal tab case: FXIOS-6150

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Verified as fixed on :Firefox: v113 (300010) with iPhone 13 Pro (15.7.1) and iPad mini 5 (14.7.1).
