### ISSUE TITLE
Add show tour with coordinators

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#13813]
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6105)

**Comment by data-sync-user** [comment]
➤ Laurie Marceau commented:

This will be handled with settings coordinator changes

**Comment by DianaBarladeanu** [comment]
> ➤ Laurie Marceau commented:
> 
> For QA, can be tested show tour still works as expected

Verified as fixed on v9000 (32311) with iPhone SE (15.4).
