### ISSUE TITLE
Unable to create new tabs after tab delete

### ISSUE THREAD

**Issue by flg** [mozilla-mobile/firefox-ios#13833]
## Steps to reproduce
With at least two tabs open, from an open tab, tap the tabs button to show all tabs. Swipe a tab out to delete it.

### Expected behavior
The bottom bar should not disappear and creating new tabs should be possible. The keyboard should probably not be shown until a tab is selected and the address bar is shown where the text is entered.

### Actual behavior
The keyboard is shown and the bottom bar (where the delete and the "+" button are shown) disappears. It's now impossible to create a new tab.

### Device & build information
* Device: Iphone SE 2, 16.3.1
* Build version: 20D67
* First seen version: It's been here since I've had this phone a few years ago.

### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6118)

**Comment by abodea** [comment]
Thank you for adding this issue, can you re-attach the video, please?
https://github.com/mozilla-mobile/firefox-ios/issues/13462 is this the issue you are encountering?

**Comment by flg** [comment]
https://user-images.githubusercontent.com/325736/229452795-fc26aa39-c2c8-479a-ac27-9ff4115fa961.mov

**Comment by flg** [comment]
#13462 does not seem to describe this specific problem. Not sure I understood everything though.

**Comment by flg** [comment]
Github does not seem happy with displaying the video but if I download it back from GH I can play it. Let me know if it works for you.

Thanks for looking into this issue.

**Comment by flg** [comment]
I noticed that the problem seems to occur *only* when, after the tab is removed by swiping, the focus falls on a unused tab (unused meaning that no web page was visited and the address bar is empty).

**Comment by dnarcese** [comment]
@abodea we landed fixes to attentive mode today, can you recheck this issue on tonight's nightly, please?

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v9000 (41759), with iPhone 15 (17.4).

**Comment by data-sync-user** [comment]
➤ Catalin Suciu commented:

Closing as it’s been verified as fixed on v127.0b1 also.
