### ISSUE TITLE
[Experiment] The Survey Screen text is cut off on some languages while using the Zoomed view

### ISSUE THREAD

**Issue by heres-maria** [mozilla-mobile/firefox-ios#13857]
**[Affected Versions]:**
- Firefox 112.0 (29913)

**[Affected Platforms]:**
- iOS 15.6 (iPhone 13 mini)

**[Prerequisites]:**
- Have the Settings > Display & Brightness > Display Zoom > View option set to Zoomed.
- Have the device language set to one of:  fr, es, pl, ja, pt-PT, ru, zh-TW.
- You have just installed the app and dismissed the onboarding.
- You have enrolled in treatment-a of the iOS Research Surface Experiment.

**[Steps to reproduce]:**
1. Restart the app once after seeing the checkmark next to the branch from prerequisites.
2. Change the device time to 24 hours + 1 minute in the future.
3. Open the app.
4. Close the app and reopen it again.
5. Observe the text of the Survey screen.

**[Expected result]:**
- The text of the Survey screen is not cut off when using the Zoom device option.

**[Actual result]:**
- The text of the Survey screen is cut off for fr, es, pl, ja, pt-PT, and ru languages when using the Zoom option.

**[Notes]:**
- The issue was not reproducible on en, de, zh-CN or pt-BR.
- Attached is a screenshot of the issue. 

![IMG_DDE65DB2FDB1-1](https://user-images.githubusercontent.com/53752296/229752790-1b740b5f-e937-4462-b224-8b38a061f1d9.jpg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6127)

**Comment by data-sync-user** [comment]
➤ Roux Buciu commented:

Testable in build 29961

**Comment by heres-maria** [comment]
This issue is no longer reproducible. The text is not cut off anymore. Tested on Firefox Release 112.29961 on iOS 15.6 (iPhone 13 mini).
