### ISSUE TITLE
[regression] Some tab thumbnails are blurry

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/firefox-ios#13855]
## Steps to reproduce

I don’t have reliable STR, but I think when Firefox is launched, some of the tab thumbnails that were saved in the previous session are blurry or upscaled. If you select the tab and view its page, the blurry thumbnail is replaced with a normal, high resolution thumbnail. 

### Expected behavior

Tab thumbnails should not be blurry. 

### Actual behavior

Some tab thumbnails are blurry. 

### Device & build information
* Device:  iPhone 12 running iOS 16.3.1 
* Build version: 9000 (29872) 
* First seen version: I think build 9000 (29741) 
### Notes
Attachments: 

![8BFCAE1C-AD6C-482B-A57D-00144D93807E](https://user-images.githubusercontent.com/629193/229673814-289ce7e7-c5f0-449d-9b1f-a94c97bd3ce0.jpeg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6126)

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Verified as fixed on v114 (30840) with iPhone 13 Pro (15.7.1).
