### ISSUE TITLE
Adjust information is not set if all metrics are not available

### ISSUE THREAD

**Issue by fbertsch** [mozilla-mobile/firefox-ios#13868]
## Steps to reproduce

1. Retrieve attribution from Adjust that does not have all fields available; for example, missing `network`.
2. Check that the Glean attribution metrics are set.

### Expected behavior

We expect that even when not all fields are available, we will still submit whatever attribution information we have. Specifically for ASA Search Match campaigns, which do not have the `creative` field set.

### Actual behavior

The data is not sent through unless all fields are available. We should send data if _any_ fields are available.

https://github.com/mozilla-mobile/firefox-ios/blob/main/Client/AdjustTelemetryHelper.swift#L35

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6141)

**Comment by data-sync-user** [comment]
➤ Orla Mitchell commented:

I don’t know if QA have a process for testing Adjust events but if not then this has no other product impact so can probably be closed.
