### ISSUE TITLE
[Experiment] The “message_surface” extra mistakenly records the message key of surveys

### ISSUE THREAD

**Issue by heres-maria** [mozilla-mobile/firefox-ios#13865]
**[Affected Versions]:**
- Firefox 112.0 (29913)

**[Affected Platforms]:**
- iOS 15.6 (iPhone 13 mini)

**[Prerequisites]:**
- You have just installed the app and dismissed the onboarding.
- You have enrolled in “treatment-a” of the “iOS Research Surface Experiment”.

**[Steps to reproduce]:**
1. Restart the app once after seeing the checkmark next to the branch from prerequisites.
2. Change the device time to 24 hours + 1 minute in the future.
3. Open the app.
4. Close the app and reopen it again using a telemetry command for events (e.g. firefox://glean?logPings=true&sendPing=events&debugViewTag=MH-1).
5. Send the app to the background a few times.
6. Go to the Glean viewer and observe the extras of the events sent.

**[Expected result]:**
- The extras of message events for the experiment display “message-surface”:”survey”.

**[Actual result]:**
- The extras of message events for the experiment display “message_surface”:“viewpoint-invitation-message-h123-<language_code>”.

**[Notes]:**
- The issue is reproducible for the "shown", "dismissed", "expired", "clicked", and "malformed" events.
- Attached is a screenshot of some of the pings affected.

![after click](https://user-images.githubusercontent.com/53752296/229850083-45d13ee7-c0c4-450f-9f26-b213b7e3dcc6.PNG)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6139)

**Comment by data-sync-user** [comment]
➤ Roux Buciu commented:

Testable in build 29961

**Comment by heres-maria** [comment]
This issue is no longer reproducible. The pings display the "message_surface": "survey" extra now. Tested on Firefox Release 112.29962 on iOS 15.6 (iPhone 13 mini).

**Comment by data-sync-user** [comment]
> **Roux Buciu** commented from Jira:

Testable in build 29961

**Comment by data-sync-user** [comment]
> **Data Sync** commented from Jira:

➤ *heres-maria commented:*

This issue is no longer reproducible. The pings display the "message_surface": "survey" extra now. Tested on Firefox Release 112.29962 on iOS 15.6 (iPhone 13 mini).
