### ISSUE TITLE
[Experiment] A “malformed” event is sent for the Survey message after it is clicked or dismissed

### ISSUE THREAD

**Issue by heres-maria** [mozilla-mobile/firefox-ios#13862]
**[Affected Versions]:**
- Firefox 112.0 (29913)

**[Affected Platforms]:**
- iOS 15.6 (iPhone 13 mini)

**[Prerequisites]:**
- You have just installed the app and dismissed the onboarding.
- You have enrolled in “treatment-a” of the “iOS Research Surface Experiment”.

**[Steps to reproduce]:**
1. Restart the app once after seeing the checkmark next to the branch from prerequisites.
2. Change the device time to 24 hours + 1 minute in the future.
3. Open the app.
4. Close the app and reopen it again using a telemetry command for events (e.g. firefox://glean?logPings=true&sendPing=events&debugViewTag=MH-1).
5. Tap “Take Survey”.
6. Send the app to the background a few times.
7. Go to the Glean viewer and observe the events sent.

**[Expected result]:**
- A “malformed” event is not sent for the Survey message.

**[Actual result]:**
- A “malformed” event is sent for the Survey message after the button is tapped.

**[Notes]:**
- The issue is also reproducible when tapping the “No Thanks” button.
- Attached is a screenshot of the ping sent after the action. 

![after click](https://user-images.githubusercontent.com/53752296/229813145-79c23ac8-d369-4ced-ac72-d3c6daab52e3.PNG)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6135)

**Comment by data-sync-user** [comment]
➤ Roux Buciu commented:

Testable in build 29961

**Comment by heres-maria** [comment]
The issue is no longer reproducible. The malformed messages are no longer sent for the STR. That being said, several of them are sent for the Control branch. You can find that issue here: https://github.com/mozilla-mobile/firefox-ios/issues/13894. Tested using Firefox Release 112.29962 on iOS 15.6 (iPhone 13 mini).
