### ISSUE TITLE
[Experiment] The Viewpoint survey message does not trigger an "exposed" event

### ISSUE THREAD

**Issue by Softvision-PatriciuPop** [mozilla-mobile/firefox-ios#13875]
### Prerequisites
- Have the Firefox Release 112.0 (29913) TestFlight build installed.
- Enroll the profile in the treatment branch of the "Viewpoint Mobile Messaging Experiment" study.
## Steps to reproduce
1. Close the Firefox app.
2. Change the system time to 24h in the future.
3. Open Safari and enter the following command "firefox://glean?logPings=true&sendPing=events&debugViewTag=<debugtag>"
4. Tap the "Open" option from the "Open this page in "Firefox"" dialog.
5. Tap the "No thanks" button from the survey and send the app in the background.
6. Close the Firefox app.
7. Navigate to the "https://debug-ping-preview.firebaseapp.com/" page and search for the debug tag used in step 3.
8. Observe the generated events.
### Expected behavior
- An exposure event for the survey is displayed.
### Actual behavior
- No exposure events are generated.
### Device & build information
* Device: iPhone 11 (iOS 16.2)
* Build version: Firefox for iOS Release 112.0 (29913)
### Notes
- This issue is reproducible on the control branch of the experiment as well.
- Attached a screenshot of the issue:

![no_exposure](https://user-images.githubusercontent.com/40393891/230065172-c4558f75-2e24-4ac1-8e51-8091278883d4.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6144)

**Comment by data-sync-user** [comment]
➤ Roux Buciu commented:

Testable in build 29961

**Comment by Softvision-PatriciuPop** [comment]
I've verified that this issue is no longer reproducible on the treatment branch, an "exposed" event is correctly generated. However the event is not present on the control branch, instead several malformed events are generated. I've logged #13894 to track this. Tested using Firefox Release Version 112.0 (29962), iPhone 11 (iOS 16.2).

**Comment by adudenamedruby** [comment]
Needs to be retested on any TF build that's higher that higher than 29978. :)

**Comment by Softvision-PatriciuPop** [comment]
I've verified that this issue is no longer reproducible, the "exposed" event is correctly generated. Tested using Firefox Release Version 112.0 (29983), iPhone 11 (iOS 16.2).
