### ISSUE TITLE
[Experiment] Several malformed events are generated on the control branch of the Viewpoint survey experiment

### ISSUE THREAD

**Issue by Softvision-PatriciuPop** [mozilla-mobile/firefox-ios#13894]
###Prerequisites
- Have the Firefox Release 112.0 (29962) TestFlight build installed.
- Enroll the profile in the control branch of the "Viewpoint Mobile Messaging Experiment" study.
## Steps to reproduce
1. Close the Firefox app.
2. Change the system time to 24h in the future.
3. Open Safari and enter the following command "firefox://glean?logPings=true&sendPing=events&debugViewTag=<debugtag>"
4. Tap the "Open" option from the "Open this page in "Firefox"" dialog.
5. Navigate to we website and close the Firefox app.
6. Navigate to the "https://debug-ping-preview.firebaseapp.com/" page and search for the debug tag used in step 3.
7. Observe the generated events.
### Expected behavior
- An exposure event for the survey is displayed.
### Actual behavior
- 11 "malformed" events are generated, one for each survey locale.
### Device & build information
* Device: iPhone 11 (iOS 16.2)
* Build version: Firefox for iOS Release 112.0 (29962)
### Notes
- This issue is not reproducible on the treatment branch of the experiment.
- The bundle of 11 malformed events is sent every time the user would trigger the "exposed" event.
- Attached a screenshot of the issue:

![malformed](https://user-images.githubusercontent.com/40393891/230366955-055f6725-20b2-4020-8492-6a2283235fd7.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6151)

**Comment by data-sync-user** [comment]
➤ Roux Buciu commented:

I’m 99% sure that this is because the experiment control is malformed. A message requires the following elements: action, style, surface, text, trigger. The others, like button-label, and is-control, etc., are optional. In the control, we are missing action and text. If these are added, the spam will be no more.

El Shallalwill be updating the experiment, and, when that’s done, this can be verified as fixed.

**Comment by data-sync-user** [comment]
➤ El Shallal commented:

The experiment config should be accurately updated now- https://experimenter.services.mozilla.com/nimbus/viewpoint-mobile-messaging-experiment/summary ( https://experimenter.services.mozilla.com/nimbus/viewpoint-mobile-messaging-experiment/summary )

**Comment by adudenamedruby** [comment]
Needs to be tested on any TF build that's higher that higher than 29978.

**Comment by Softvision-PatriciuPop** [comment]
I've verified that this issue is no longer reproducible, the "malformed" events are no longer generated. Tested using Firefox Release Version 112.0 (29983), iPhone 11 (iOS 16.2).
