### ISSUE TITLE
firefox iOS not syncing logins

### ISSUE THREAD

**Issue by hotglu** [mozilla-mobile/firefox-ios#13909]
### Device & build information
* Device: iPad Pro 10.5 inch running iOS 16.2
* Build version: ? Firefox 111.1 (29556)
* First seen version: ? 
### Notes
Attachments: 

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6157)

**Comment by abodea** [comment]
Hello, @hotglu thank you for your report!
Please ensure the time is set to automatically on both devices. Mac and iPad?
And also let us know of those were set automatically or manual.

**Comment by hotglu** [comment]
After a couple days the automatic syncing seems to have worked. Still not sure why a manual sync request failed, thanks!
