### ISSUE TITLE
Consider adding a "bookmarks toolbar" like is availble on desktop and in Mobile Safari

### ISSUE THREAD

**Issue by bwoodruff** [mozilla-mobile/firefox-ios#1390]
Please consider adding a toolbar much like the one available in Safari by enabling
`Settings > Safari > Show Favorites Bar`

Bookmarklets are much less convenient with the current design, which requires at least three taps instead of one to execute a bookmarklet.

**Comment by stek29** [comment]
But mobile screen is pretty small, and adding more bars would be strange solution.
I'm sure that adding button near tabs or long tap on star would be better.

**Comment by farhanpatel** [comment]
TopSites appear when you tap the URL bar. I don't think we plan on adding a specific bar for favourites. As stek29 suggested. Space is limited so we have to make choices 😢

**Comment by MS047** [comment]
Hey,

I'm bringing this issue back up - this coud defo be done on Ipad version of firefox.

In particular, it is pretty annoying to need to click on 4 buttons (star icon>Desktop Bookmarks>Bookmarks Toolbar> list of bookmarks) to access the bookmarks present on your firefox desktop's toolbar when you surf in firefox iOS. Having a dedicated toolbar pulling up these toolbar bookmarks like on the dektop app would be a major step forward.

**Comment by fedemengo** [comment]
> Hey,
> 
> I'm bringing this issue back up - this could definitely be done on the Ipad iOS version of firefox.
> 
> In particular, it is pretty annoying to need to click on 4 buttons (star icon>Desktop Bookmarks>Bookmarks Toolbar> list of bookmarks) to access the bookmarks present on your firefox desktop's toolbar when you surf in firefox iOS. Having a dedicated toolbar pulling up these toolbar bookmarks like on the dektop app would be a major step forward.

Same opinion here. Do you think this is something you might consider in the iPad version?

**Comment by Profitsarts** [comment]
the only reason I never got back into Firefox from Safari is that. Getting to favs is really annoying frustrating and is too far to get there.
There's another thing I'd love to get, obviously, iCloud tabs, but maybe that is Apple's own tech locked up.

Anyone knows extensions alternative?

**Comment by AKDub** [comment]
Suppose I will bump this up. 

After my latest quarterly return to firefox on my ipad this is the main issue taking me back to safari. Having the bookmark buried in a menu, which is itself split up  (menu, toolbar, unsorted, mobile) seems to add so many touches to my general browsing.

Could it be an option? I know some people are worried about space, but it could be like the desktop where you can toggle it on or off.

Is it the same on Android?

**Comment by kmai-universe** [comment]
This really needs to be implemented for ipad! I too use Firefox on my desktop and my iPhone. But I simply can't use it on my 12" ipad pro without the bookmarks bar, which safari has.

This is a very important feature if you want to get people to use Firefox on ipads.
