### ISSUE TITLE
The URL bar is not focused when clean installing  or when cold starting Fennec.

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#13913]
## Steps to reproduce
1. Clean install Fennec 9aff4cd1444726bee7f682c3070861892507dfd7 or Firefox v9000 (29995)
1. Launch Fennec
### Expected behavior

* The URL bar should be focused
### Actual behavior
* The URL bar is not focused when clean installing  or when cold starting Fennec.
### Device & build information
* Device: iPhone 14 Pro 16.2
* Build version: Fennec 9aff4cd1444726bee7f682c3070861892507dfd7
* First seen version: Fennec 9aff4cd1444726bee7f682c3070861892507dfd7
### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6160)

**Comment by clarmso** [comment]
The issue is possibly caused by this recent change. I'm working to resolve the issue.
https://github.com/mozilla-mobile/firefox-ios/pull/13778
