### ISSUE TITLE
Toolbar shown when it should be hidden due to scrolling

### ISSUE THREAD

**Issue by alinamoldovan84** [mozilla-mobile/firefox-ios#13911]
## Steps to reproduce
1. the toolbar is set to be displayed at the bottom pf the page 
2. Open a web page 
3. Scroll down a bit so the toolbar is hidden 
4. Scroll up so the toolbar is opened 
5. Focus the link so the keyboard is opened  
6. Scroll down 

### Expected behavior
The toolbar is hidden 

### Actual behavior
The toolbar disappears for a few seconds and after that it is displayed

### Device & build information
* Device: iPhone 14 Plus (16.0.3) 
* Build version: 9000 (29966) 
* First seen version: ? 
### Notes
Attachments: 

https://user-images.githubusercontent.com/124251579/230849407-2ea11d8a-626e-4eaf-9ee0-308e1cb35b3c.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6159)

**Comment by dnarcese** [comment]
Not reproducible
