### ISSUE TITLE
[Experiment] The Notification opt-in card is not translated on several locales

### ISSUE THREAD

**Issue by Softvision-PatriciuPop** [mozilla-mobile/firefox-ios#13915]
### Prerequisites
- Have the Firefox Release 112.1 (29908) TestFlight build installed.
- Enroll the profile in any of the treatment branches of the "iOS Notification Opt-in Prompt" experiment.
- Have your iPhone language set to Polish.
## Steps to reproduce
1. Open the Firefox app.
2. Go through the onboarding cards and observe the notification opt-in card.
### Expected behavior
- The Notification opt-in card is correctly localized in the selected language.
### Actual behavior
- The card's text defaults to the English language.
### Device & build information
* Device: iPhone 11 (iOS 16.2)
* Build version: Firefox for iOS Release 112.1 (29908)
### Notes
- This issue is reproducible using the following locales: PL, JA
- Attached a screen recording of the issue:

https://user-images.githubusercontent.com/40393891/230925479-0cdb31f1-1e2c-4878-9b35-557b0202d063.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6161)

**Comment by dnarcese** [comment]
@Delphine is this a normal occurrence? Do we just accept that some locales do not get translated?

Here is the commit where we landed them on feb 22 so I figure there was enough time given to localizers. https://github.com/mozilla-mobile/firefox-ios/commit/0539246b0efc9d2285fbf0498313e87858113da7

**Comment by Delphine** [comment]
Since Mozilla has chose a community volunteer model to translate products, we don't expect all locales to reach 100% completion on strings for any given release.
Indeed, we have made a compromise because the model itself has a lot more [benefits](https://mozilla-l10n.github.io/documentation/localization/globalization_best_practices.html#community) than negatives.
So yes, this is accepted. But I can reach out to these two locales if that can help.

**Comment by Delphine** [comment]
Hmm I checked and both pl and ja locales have that string translated for a while back now:
* https://pontoon.mozilla.org/ja/firefox-for-ios/firefox-ios.xliff/?search=notifications+help+you+do+more&string=275985 (more than a month ago)
* https://pontoon.mozilla.org/pl/firefox-for-ios/firefox-ios.xliff/?search=notifications+help+you+do+more&string=275985 (2 weeks ago)

We are talking about this string ID right:  `Onboarding.Notification.Title.v112`
Could there be something wrong with l10n string imports?

**Comment by Softvision-PatriciuPop** [comment]
I've verified that this issue is no longer reproducible, the Notification opt-in card is now correctly translated. Tested using Firefox Release Version 112.1 (30078), iPhone 11 (iOS 16.2).
