### ISSUE TITLE
The tabs sent from the desktop open only after a manual sync, push notifications are missing.

### ISSUE THREAD

**Issue by alinamoldovan84** [mozilla-mobile/firefox-ios#13936]
## Steps to reproduce
1. Open Firefox and make sure you are logged in with a valid account and Notifications are allowed 
2. From desktop (same FXA) send a tab to the device 
3. Check for the push Notification 
4. Check the Home screen 'Jump Back In' section, 'Tab pickup'
5. Navigate to settings and manually Sync  

### Expected behavior
3. A push notification is received informing abut the sent tab and the tab is opened  

### Actual behavior
step 3. Push notification is not received 
step 4. "Tab pickup" is updated with the tab sent from desktop 
step 5. After a manual sync the tab sent from desktop is opened on the device 

### Device & build information
* Device: iPhone 14 Plus (16.0.3) V 
* Build version: 113 (30010) 
* First seen version: ? 
### Notes
The issue doesn't reproduce using 112 (29983) FF version 
Attachments: 

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6177)

**Comment by dmcg10** [comment]
Can confirm same issues on my 14 Pro using latest Firefox for iOS build on the App Store.

Manual sync works around the issue.

**Comment by csuciu** [comment]
I'm not able to reproduce this issue using Firefox v116.3/iPhone 14 Pro running iOS 16.6.

@alinamoldovan84 @dmcg10, please re-open if you are still having this problem.
