### ISSUE TITLE
www.deusinmachina.net - Page is stuck in a loading state 

### ISSUE THREAD

**Issue by softvision-raul-bucata** [mozilla-mobile/firefox-ios#13954]
As reported in https://github.com/webcompat/web-bugs/issues/120635, the page is stuck in a loading state.
This issue is specific to Firefox iOS as Android devices load the page as expected.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6187)

**Comment by gregstoll** [comment]
As the webcompat bug notes, this seems to happen for all Substack sites, which is pretty annoying...
