### ISSUE TITLE
Favicons flicker when taping on URL bar

### ISSUE THREAD

**Issue by jrmuizel** [mozilla-mobile/firefox-ios#13960]
## Steps to reproduce

It doesn't reproduce reliably but sometimes when you tap on the url the favicons on the home screen flicker.

### Expected behavior

No flickering

### Device & build information
* Device: iPhone mini 14
* Build version: 111.2

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6191)

**Comment by jrmuizel** [comment]
Why was this closed?

**Comment by OrlaM** [comment]
It will be fixed when v119 is released.

**Comment by jrmuizel** [comment]
What commit fixed it?

**Comment by OrlaM** [comment]
https://github.com/mozilla-mobile/firefox-ios/pull/16343

**Comment by jrmuizel** [comment]
I still see flickering in 119
