### ISSUE TITLE
CryptPad can't load in v111.0 (29345)

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/firefox-ios#13975]
Hello!

Since Firefox iOS v111.0 (29345), CryptPad is again broken and can't be loaded on Firefox. We fixed some issue on #10463 (PR https://github.com/mozilla-mobile/firefox-ios/pull/11679) but the problem is back. Apparently it wouldn't be the exact same one tho:

> mthld I think it's better to create a new issue and link to this one, since it's probably not the exact same issue happening. The bugfix made on this ticket is still part of the codebase.

_Originally posted by lmarceau in https://github.com/mozilla-mobile/firefox-ios/issues/10463#issuecomment-1470303324_

Is there something I can do to investigate an provide potential error logs? If someone has some time to spare you can try by accessing our flagship instance at https://cryptpad.fr

Thanks in advance!

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6202)

**Comment by lmarceau** [comment]
Thanks @mthld, a good first step would be to run the app on a simulator and debug with Safari web inspector to get the error (as explained [here](https://github.com/mozilla-mobile/firefox-ios/issues/10463#issuecomment-1220889412))

**Comment by dnarcese** [comment]
@mthld can you screenshot what the issue you are seeing is with the site?
