### ISSUE TITLE
TiddlyWiki based sites not working at all

### ISSUE THREAD

**Issue by ociu** [mozilla-mobile/firefox-ios#13971]
## Steps to reproduce
Load any TiddlyWiki based site, for example https://tiddlywiki.com/

### Expected behavior
Internal menus and links working. Page not reloading automatically.

### Actual behavior
No reaction. Style of pressed links might change but no effect.

From time to time page automatically reloads.

### Device & build information
* Device: iPhone 12 mini. iOS 16.3.1
* Build version: Firefox 111.2 (29672)
* First seen version: Firefox 111.2 (29672)
### Notes
Attachments: 

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6198)

**Comment by dnarcese** [comment]
not reproducible
