### ISSUE TITLE
'Jump Back in'  and 'Recently Visited' sections disappear after a specific scenario

### ISSUE THREAD

**Issue by alinamoldovan84** [mozilla-mobile/firefox-ios#13996]
## Steps to reproduce

1. Make sure the 'Jump Back in'  and 'Recently Visited' sections are visible on home screen 
2. Switch to private browsing 
3. Open a web page in a private tab 
4. While in private browsing open the hamburger menu and choose to open a new tab 
5. Home screen opens in normal browsing mode

### Expected behavior
'Jump Back in'  and 'Recently Visited' sections are visible  

### Actual behavior
'Jump Back in'  and 'Recently Visited' sections disappear  

### Device & build information
* Device: iPhone 14 Plus (16.0.3) 
* Build version: 112.1 (30078)
* First seen version: ? 
### Notes
 - Able to reproduce this issue using FF version 112 (29983)
 - FF must be restarted in order for the two section to be displayed again
Attachments: 

https://user-images.githubusercontent.com/124251579/232840137-5a511701-ffc0-4926-b567-ef1d6857b128.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6209)

**Comment by dnarcese** [comment]
The fact that New Tab is opening in normal mode is also a bug. Will file. Fixing that may fix this
