### ISSUE TITLE
Reader View icon resets its blue “enabled” color to grey after switching tabs

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/firefox-ios#14052]
## Steps to reproduce
1. Open two Reader View compatible pages (e.g. Wikipedia articles) in two tabs. 
1. Enable Reader View for one of the tabs. 
1. See that the toolbar’s Reader View icon changes color from grey to blue, as expected since Reader View is now enabled. 
1. Switch to the second tab. 
1. See that the toolbar’s Reader View icon is grey, as expected since Reader View is not enabled on the second tab. 
1. Switch back to the first tab. 

### Expected behavior
The first tab’s Reader View icon should be blue since Reader View is enabled. 

### Actual behavior
The first tab’s Reader View icon is grey even though Reader View is enabled. 

If you enable Reader View in both tabs and switch between them, the tabs’ Reader View icons stay blue.

### Device & build information
* Device: iPhone 12 running iOS 16.4.1 
* Build version: 9000 (29872) 
* First seen version: This OS not a recent regression. I can reproduce it in the oldest TestFlight version available to me, v110. 

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6236)

**Comment by data-sync-user** [comment]
➤ Chris Peterson commented:

This bug has been fixed. I can’t reproduce it in Firefox 130.
