### ISSUE TITLE
Send to device (device names not readable)

### ISSUE THREAD

**Issue by rootsandstones** [mozilla-mobile/firefox-ios#14054]
## Steps to reproduce
1. Open website in Safari
1. Share website to Firefox
1. Send to device
### Expected behavior
See list of devices to send to
### Actual behavior
Can't read name of devices (white text on white background)
### Device & build information

* Device: iPhone 13 iOS 16.3.1
* Build version: Firefox 112.0 (29983)
* First seen version: Not sure
### Notes
Attachments: 

![20230421!UNITO-UNDERSCORE!064235810!UNITO-UNDERSCORE!iOS](https://user-images.githubusercontent.com/80270427/233595975-dfbd0bce-4f5c-44ea-95c2-8042592a2248.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6238)

**Comment by lmarceau** [comment]
This seems to be a theming problem.

**Comment by rootsandstones** [comment]
> This seems to be a theming problem.

I‘m using the system theme in firefox and automatic light/dark on iOS. If I set it to dark manually then it‘s fine.

**Comment by tisumi99** [comment]
Took a while to figure out a way to reproduce this consistently.  Detailed steps to reproduce:

1.  Set system display mode to light mode.
2. Close any running instances of Firefox and Safari.
3. Start Safari.
4. Click on the share icon in Safari.  
5. Note that the ShareTo extension is in light mode as expected.
6. Click on the Send to Device link in the ShareTo extension.  
7. Note that the list of devices is readable in light mode as expected.
8. Click the cancel link in the ShareTo extension.
9. Go to system settings and change display mode to dark mode.
10. Go back to Safari and click on the share icon.  
11. Note that the ShareTo extension is still in light mode which is unexpected.
12. Note that the web page name and URL that should be displayed below the Firefox icon is not visible.
13. Click on the Send to Device link in the ShareTo extension.  
14. Note that the device list is not visible.
15. Note that the device list background is black.

Also reproducible when going from dark mode to light mode.

https://github.com/mozilla-mobile/firefox-ios/assets/98071325/9d599ce6-05c8-4b53-9f30-64ff576bad21

Couple of different causes driving this issue:

1. When switching from light to dark mode, the ShareTo extension does not pick up on the change and remains in light mode.  Not sure why.
2. There is some inconsistency with the styling of the device list.  The device list text is actually present but retains the light mode text color which is a dark color from the Firefox theme.  The background of the device list changed to black (not from the Firefox theme), so we end up with dark text text on a black background.  So even though the first tab of the ShareTo extension is stuck in light mode, the Device List tab is partly stuck in light mode (text color from the Firefox theme) and partly swtiched over to dark mode (the background color from the system or Safari).

I don't know how to fix the first cause, but I will submit a new issue for the second cause as I already have a fix for it.  With the UI fix, the ShareTo extension will be consistently in all dark mode or all light mode and styled from the Firefox theme even if the extension doesn't pick up on changes to the display mode.  At least the device list will be readable.

**Comment by tisumi99** [comment]
Issue opened for the UI inconsistencies.
https://github.com/mozilla-mobile/firefox-ios/issues/18331
