### ISSUE TITLE
The keyboard is not raised up when New tab is set as "blank page" and the tab is open from tab tray

### ISSUE THREAD

**Issue by alinamoldovan84** [mozilla-mobile/firefox-ios#14098]
## Steps to reproduce
1. Navigate to settings -> New tab
1. Set blank page 
1. Tap on tab tray counter and choose '+' button

### Expected behavior
The keyboard should be raised up

### Actual behavior
1. The keyboard is not raised up for iPads 
1. On iPhone if the tab in focus is empty while choosing + button the keyboard is not raised, but if a web page is loaded the Keyboard is raised up.

### Device & build information
* Device: 4 Plus (16.0.1), iPad 3rd gen (16.3.1) 
* Build version: 113 (30257) 
* First seen version: ? 

**Notes**
**Attachments:** 

!Skype_Video7.mp4|width=888,height=1920!

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6253)

**Comment by data-sync-user** [comment]
➤ Alina Moldovan commented:

Validated this issue using v9000 (30333) and iPhone 14 Plus (16.0.3) and iPad Air 3rd Gen (16.3.1)

The issue is not preproducing on iPhone but it still reproduces on iPad

**Comment by data-sync-user** [comment]
➤ Alina Moldovan commented:

Validated this issue using v113 (30370) and iPhone 14 Plus (16.0.3) and iPad Air 3rd Gen (16.3.1)
