### ISSUE TITLE
The `100%` text should be more visible/another color in Light Mode on the Zoom bar

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/firefox-ios#14093]
## Steps to reproduce
1. Launch FF.
2. Access any webpage.
3. Open the Zoom Bar and observe the default `100%` text.
### Expected behavior
The `100%` text should be more visible/another color in Light Mode.
### Actual behavior
The `100%` text can cause visibility issues based on the current color.
### Device & build information
* Device:  
* Build version: 9000 (30256) 
* First seen version: N/A 
### Notes
Attachments: 

![image1](https://user-images.githubusercontent.com/42831109/234008580-bdf20e2c-a958-493e-a372-46490bb6314b.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6249)

**Comment by data-sync-user** [comment]
➤ Daniela Arcese commented:

Aarjav Pandya thoughts here?

**Comment by Piratesarereal** [comment]
The colour choice for 100% text is deliberate to indicate that it is not clickable hence we are using Disabled state colour from Mozilla [design system](https://acorn.firefox.com/latest/styles/color.html#section-text-c2).
