### ISSUE TITLE
Feature request: support "Add to Home Screen" on iOS/iPadOS 16.4

### ISSUE THREAD

**Issue by tantek** [mozilla-mobile/firefox-ios#14095]
iOS/iPadOS 16.4 (released 2023-03-27) have APIs for third-party browsers to support an “Add to Home Screen” menu item / share option like the same feature in Mobile Safari. Several iOS browsers have already shipped with support including Microsoft Edge for iOS, according to: [https://ios.gadgethacks.com/how-to/these-browsers-let-you-add-web-apps-and-bookmarks-your-iphones-home-screen-0385351/](https://ios.gadgethacks.com/how-to/these-browsers-let-you-add-web-apps-and-bookmarks-your-iphones-home-screen-0385351/). Firefox for iOS &amp; iPadOS should similarly support "Add to Home Screen", preferably as a menu item in the existing menu shown after choosing "Share" from the main ≡ menu in the bottom right corner.

See prototype and implementation details explored in discussion [Add to Home Screen support in iOS 16.4 #13281](https://github.com/mozilla-mobile/firefox-ios/discussions/13281) for feasibility.

Chrome on iOS does not yet (as of version 112) have an "Add to Home Screen" feature. I would expect it to be implemented soon however, as it’s a path to installable web apps which Chrome on Android and desktop already support: [MDN: Installing and uninstalling web apps: Add to home screen](https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Installing#add_to_home_screen).

This feature is both useful for users and helps incremental user interface parity with Safari and Edge on iOS (and likely soon Chrome).

In addition, adding a web app to the home screen is a necessary step towards implementing the user interaction aspects of Web Push API and Notifications API support for web apps launched in Firefox. These two APIs were recently added to WebKit, also in iOS 16.4: [2023-02-16 Web Push for Web Apps on iOS and iPadOS](https://webkit.org/blog/13878/web-push-for-web-apps-on-ios-and-ipados/)

(Originally published at: https://tantek.com/2023/114/b1/)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6251)

**Comment by lmarceau** [comment]
This relates to https://github.com/mozilla-mobile/firefox-ios/issues/14131. The feature was implemented and will be released with 114, so I'll close this ticket for now. Thank you!
