### ISSUE TITLE
Pair FxA with QR code from another "mobile" device

### ISSUE THREAD

**Issue by zcorpan** [mozilla-mobile/firefox-ios#14091]
### User Problem
> Why should we implement this? What is the user benefit?

I installed Firefox on my iPad and wanted to log in to my FxA using scan QR code option. I only had my Android phone nearby, and being logged in there I expected to be able to use it for pairing the iPad.

Going to firefox.com/pair on my Android phone it didn't show a QR code but instead said to go to that address using a computer.

### Ideas for Solution
> Let us know if you have an idea on how to solve this user problem

Show QR code regardless of device.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6248)

**Comment by dnarcese** [comment]
@zcorpan thank you for the request. I have sent this to the FxA team.
