### ISSUE TITLE
The keyboard is raised up when New tab is set as "Blank page " and the new tab is NOT open from tab tray

### ISSUE THREAD

**Issue by alinamoldovan84** [mozilla-mobile/firefox-ios#14099]
## Steps to reproduce
1. Navigate to settings -> New tab
1. Set to blank page 
1. Open the Hamburger menu
1. choose to add a new tab

### Expected behavior
The keyboard should be raised up

### Actual behavior
1. The keyboard is raised on iPads 
1. On iPhone if the tab in focus is empty while choosing + button the keyboard is not raised, but if a web page is loaded the Keyboard is raised up.

### Device & build information
* Device: 4 Plus (16.0.1), iPad 3rd gen (16.3.1) 
* Build version: 113 (30257) 
* First seen version: ? 

**Notes**

* Issue reproduces for both private and normal browsing 
* Issue reproduces when the new tab is opened from tab tray context menu,   FF icon context menu and widgets

**Attachments:** 

!Skype_Video8.mp4|width=888,height=1920!

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6254)

**Comment by data-sync-user** [comment]
➤ Yoana Rios Diaz commented:

The keyboard should be raised for all cases to Open a new tab when New Tab Settings is Blank page

**Comment by data-sync-user** [comment]
➤ Alina Moldovan commented:

Validated this issue using v9000 (30333) and iPhone 14 Plus (16.0.3) and iPad Air 3rd Gen (16.3.1)

The issue doesn't reproduce  anymore 

Yoana Rios Diaz  can we close it as fixed?

**Comment by data-sync-user** [comment]
➤ Yoana Rios Diaz commented:

yes I was waiting to move all the tickets together to Needs QA but yes this was already fix and backported to v113 pending new build waiting for the other Attentive mode fixes

**Comment by data-sync-user** [comment]
➤ Alina Moldovan commented:

Validated this issue using v9000 (30333) and iPhone 14 Plus (16.0.3) and iPad Air 3rd Gen (16.3.1)

The issue doesn't reproduce anymore
