### ISSUE TITLE
The keyboard is raised up when New tab is set as "custom URL" and the new tab is opened from outside of the FF app 

### ISSUE THREAD

**Issue by alinamoldovan84** [mozilla-mobile/firefox-ios#14096]
## Steps to reproduce
1. Navigate to settings -> New tab 
1. Set a custom URL
1. Put the FF app in background 
1. long press on FF app icon -> Context menu opens 
1. Choose to open a new tab and check the keyboard behavior

### Expected behavior
The keyboard should not raise up 

### Actual behavior
The keyboard is raised up 

### Device & build information
* Device: iPhone 14 Plus (16.0.1), iPad 3rd gen (16.3.1) 
* Build version: 113 (30257) 
* First seen version: ? 

**Notes**

* Issue reproduces for private browsing also 
* Issue reproduces when FF is opened using the widgets for both normal and private browsing 

**Attachments:**

!Skype_Video9.mp4|width=888,height=1920!

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6252)

**Comment by data-sync-user** [comment]
➤ Alina Moldovan commented:

Validated this issue using v9000 (30333) and iPhone 14 Plus (16.0.3) and iPad Air 3rd Gen (16.3.1). the issue reproduces for both devices. 

May be related with this issue: [[FXIOS-5870] #13392 ⁃ Custom web page is not loaded correctly when opening a new tab - Jira (atlassian.net)|https://mozilla-hub.atlassian.net/browse/FXIOS-5870]

**Comment by data-sync-user** [comment]
➤ Alina Moldovan commented:

Validated this issue using the FF v9000 (30521) and iPhone 14 Plus (16.0.3) & iPad Air 3rd Gen (16.3.1). 

The issue doesn’t reproduce anymore

**Comment by data-sync-user** [comment]
➤ Alina Moldovan commented:

Validated this issue using V114( 30757) and iPhone 14 Plus (16.0.3) and iPad 3rd gen (16.3.1). the issue doesn’t reproduce anymore
