### ISSUE TITLE
Wiki pages: Minor grammar errors in 'A Brief Overview of Accessibility'

### ISSUE THREAD

**Issue by skiing-gecko** [mozilla-mobile/firefox-ios#14107]
When I was looking over the accessibility page of the Wiki, I think I found some mistakes in the writing:

In the **`accessibilityHint`** [section](https://github.com/mozilla-mobile/firefox-ios/wiki/A-Brief-Overview-of-Accessibility#accessibilityhint) there are two 'the's:

> Hints can be turned off by the the users, but aren't less useful to give more context as to what an element on the screen does.

In the **Grouping Elements** [section](https://github.com/mozilla-mobile/firefox-ios/wiki/A-Brief-Overview-of-Accessibility#grouping-elements), there is a space between 'm' and 'ore' in the word 'more':

> As a user, it's much m ore preferable to have the whole cell selectable with Voice Over...

In the **`accessibilityIdentifier`** [section](https://github.com/mozilla-mobile/firefox-ios/wiki/A-Brief-Overview-of-Accessibility#accessibilityidentifier), there seems to be an 'or' in place of an 'of':

> An easy way or organizing reusable identifiers can be found...

I also thought that the sentence

> In that case, the labels in that cells needs their accessibilityElement turned off, and the parent cell needs it's accessibilityElement turned on, and it's accessibility label can be set as the combined text of the title and the description.

Might be better written as:

In that case, the labels in `those` cells `need` their accessibilityElement turned off, and the parent cell needs `its` accessibilityElement turned on, and `its` accessibility label can be set as the combined text of the title and the description.

I imagine this is very low on the list of things to do, but I thought it might be helpful to point it out :)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6259)

**Comment by lmarceau** [comment]
@skiing-gecko do you want to open a PR to improve the wiki page?

**Comment by dfperry5** [comment]
Is it OK if i take this on? I can go and update it if @skiing-gecko  hasn't had a chance to get around to it :)

**Comment by lmarceau** [comment]
@dfperry5 there's no PR open for it, so I would say go for it 🙏

**Comment by sandramsc** [comment]
Hello! I noticed its been a moment since the last try to fix this issue, if it's still open I'd be happy to try and tackle it?

**Comment by rajparad** [comment]
Hello @lmarceau, I guess still there is no PR for this. I am not sure is there any PR option for WIKI? But in my forked repo I have update the page. 

Here is the link of my repo: https://github.com/rajparad/firefox-ios.wiki.git
and page with changes: https://github.com/rajparad/firefox-ios/wiki/A-Brief-Overview-of-Accessibility

Let me know if something needs to be changed.

**Comment by lmarceau** [comment]
I just took a look and there doesn't seem to be any options to have PR for wiki pages on `main`. I made changes [on the page](https://github.com/mozilla-mobile/firefox-ios/wiki/A-Brief-Overview-of-Accessibility) as you did them @rajparad :) Let me know if you see anything else, otherwise I'll close this issue for now. Thank you!
