### ISSUE TITLE
iPad - The keyboard is not raised up when New tab is set as "Firefox Home" and the new tab is opened from tab tray

### ISSUE THREAD

**Issue by alinamoldovan84** [mozilla-mobile/firefox-ios#14108]
## Steps to reproduce

1. Navigate to settings -> New tab
2. Set Firefox Home 
3. Open tabs tray 
4. choose + to open a new tab 

### Expected behavior
The keyboard should be raised up

### Actual behavior
The keyboard is NOT be raised up

### Device & build information
* Device: iPad 3rd gen (16.3.1) 
* Build version: 113 (30257) 
* First seen version: ? 
### Notes
- issue is not preproducing for iPhones 
- issue reproduces for private browsing also  
Attachments: 

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6260)

**Comment by data-sync-user** [comment]
➤ Alina Moldovan commented:

Validated this issue using v113 (30370) and iPad Air 3rd Gen (16.3.1)

The issue doesn’t reproduce anymore.
