### ISSUE TITLE
The keyboard is NOT raised up when New tab is set as "Firefox Home" and the new tab is opened from hamburger menu

### ISSUE THREAD

**Issue by alinamoldovan84** [mozilla-mobile/firefox-ios#14109]
## Steps to reproduce
1. Navigate to settings -> New tab
1. Set Firefox Home
1. Have a web page already loaded 
1. Open the hamburger menu and choose to open a new tab 

### Expected behavior
The keyboard should be raised up

### Actual behavior
The keyboard is NOT raised up

### Device & build information
* Device: 4 Plus (16.0.1), iPad 3rd gen (16.3.1) 
* Build version: 113 (30257) 
* First seen version: ? 

**Notes**

* the issue reproduces for both private and normal browsing 
* issue doesn't preproduce if the new tab is opened from the tab tray’s context menu (long press on tab tray count until the context menu opens), from the widgets nor FF icon 3D menu

Attachments: 

<

!--- Screenshots or screen recordings are very helpful for reproducing|width=200,height=183!

-->

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6261)

**Comment by data-sync-user** [comment]
➤ Yoana Rios Diaz commented:

Alina Moldovan is this the bug where the Keyboard is not open from the widgets or FF icon? because the name and the steps to reproduce are confusing

The keyboard should always open for Homepage settings for all flows of opening a New tab

**Comment by data-sync-user** [comment]
➤ Alina Moldovan commented:

Yoana Rios Diaz updated the steps to match the correct behavior 

Validated this issue using v9000 (30333) and iPhone 14 Plus (16.0.3) and iPad Air 3rd Gen (16.3.1)

The issue reproduces for both devices above (normal and private browsing).

**Comment by data-sync-user** [comment]
➤ Alina Moldovan commented:

Validated this issue using v113(30370) and iPhone 14 Plus (16.0.3) and iPad Air 3rd Gen (16.3.1)

The issue doesn’t reproduce anymore
