### ISSUE TITLE
The Zoom Bar is not centered like on iPad or iPhone landscape

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/firefox-ios#14119]
## Steps to reproduce
1. Launch FF and access any webpage.
2. Tap on the hamburger menu and then on Zoom.
3. Observe the Zoom Bar placement.
### Expected behavior
The Zoom Bar should be centered like it is on iPad or iPhone landscape.
### Actual behavior
The Zoom Bar is not centered like on iPad or iPhone landscape.
### Device & build information
* Device: iPhone 13 Pro (15.7.1). 
* Build version: 9000 (30301) 
* First seen version: N/A 
### Notes
Attachments: 

![image0 (1)](https://user-images.githubusercontent.com/42831109/234264938-29718e41-64aa-49ae-8f03-659877699050.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6270)

**Comment by data-sync-user** [comment]
➤ Daniela Arcese commented:

This is according to design https://www.figma.com/file/dIdFRmA0yACjkam2mb8eGq/Page-Zoom?type=design&node-id=1926-40657&t=H3BOs1tSSfRrt3Xd-0 ( https://www.figma.com/file/dIdFRmA0yACjkam2mb8eGq/Page-Zoom?type=design&node-id=1926-40657&t=H3BOs1tSSfRrt3Xd-0|smart-link )
