### ISSUE TITLE
Zoom bar doesn't disappear when scrolling up together with the URL bar

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/firefox-ios#14112]
## Steps to reproduce
1. Launch FF and access any webpage.
2. Tap on the hamburger menu and then on Zoom.
3. While the Zoom Bar is displayed scroll up.
### Expected behavior
The Zoom Bar should disappear with the URL Bar.
### Actual behavior
Zoom bar doesn't disappear when scrolling up together with the URL bar
### Device & build information
* Device: iPhone 13 Pro (15.7.1). 
* Build version: 9000 (30301) 
* First seen version: N/A 
### Notes
Attachments: 

https://user-images.githubusercontent.com/42831109/234246330-9293d04f-e3b4-40b4-ae03-b8e2688626ad.mov

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6263)

**Comment by data-sync-user** [comment]
➤ Daniela Arcese commented:

Answer to this comment will solve this bug https://mozilla-hub.atlassian.net/browse/FXIOS-6264?focusedCommentId=677283 ( https://mozilla-hub.atlassian.net/browse/FXIOS-6264?focusedCommentId=677283|smart-link )
