### ISSUE TITLE
Weird shadow displayed for Light/Dark theme while Zoom Bar is enabled

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/firefox-ios#14118]
## Steps to reproduce
1. Launch FF and access any webpage.
2. Tap on the hamburger menu and then on Zoom.
3. While the Zoom Bar is displayed scroll up and down (try this in both Dark And Light Themes).
### Expected behavior
There should not be displayed any shadow from the Zoom Bar.
### Actual behavior
Weird shadow displayed for Light/Dark theme while Zoom Bar is enabled.
### Device & build information
* Device: iPhone 13 Pro (15.7.1). 
* Build version: 9000 (30301) 
* First seen version: N/A 
### Notes
When the Dark theme is enabled - the shadow is Light
When the Light theme is enabled 
- the shadow is Dark.
Attachments: 

https://user-images.githubusercontent.com/42831109/234262364-67fb6ea4-0e1f-4ecb-a774-78fcdbc70614.mov

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6269)

**Comment by dnarcese** [comment]
Do you mean the shadow at the top of the zoom bar? That is per design

**Comment by abodea** [comment]
Yes, @dnarcese feels like it is blocking the user on different websites I'm not really sure how to say it but the contrast of the shadow is too strong.

**Comment by dnarcese** [comment]
Closing as won't do
