### ISSUE TITLE
The Zoom bar disappears when a cookie banner is displayed

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/firefox-ios#14116]
## Steps to reproduce
1. Launch FF.
2. Access a webpage and then fast open the hamburger menu and tap on Zoom.
3. The Zoom Bar is displayed.
4. Observe the Zoom Bar after the cookie banner is displayed.
### Expected behavior
The Zoom Bar should not disappear. 
### Actual behavior
The zoom bar disappears when a cookie banner is displayed.
### Device & build information
* Device: iPhone 13 Pro (15.7.1). 
* Build version: 9000 (30301) 
* First seen version: N/A 
### Notes
You can see at the bottom the Zoom Bar for 1-second flashing.
Attachments: 

https://user-images.githubusercontent.com/42831109/234258393-67367cdb-06d5-494c-9d13-2d6e311f1aa3.mov

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6267)

**Comment by data-sync-user** [comment]
➤ Daniela Arcese commented:

This will be fixed by https://mozilla-hub.atlassian.net/browse/FXIOS-6264 ( https://mozilla-hub.atlassian.net/browse/FXIOS-6264|smart-link )
