### ISSUE TITLE
The Zoom bar is not long enough while in landscape mode on iPhone

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/firefox-ios#14115]
## Steps to reproduce
1. Launch FF and access any webpage.
2. Tap on the hamburger menu and then on Zoom.
3. While the Zoom Bar is displayed rotate in the landscape.
### Expected behavior
The Zoom bar is fully displayed in landscape mode.
### Actual behavior
The Zoom bar is not long enough while in landscape mode on iPhone.
### Device & build information
* Device: iPhone 13 Pro (15.7.1). 
* Build version: 9000 (30301) 
* First seen version: N/A 
### Notes
Note that on iPad it's fully displayed in landscape mode.
Attachments: 

![image1](https://user-images.githubusercontent.com/42831109/234253699-bddf6fa0-5e6f-45b3-a091-85d45e7bdaa6.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6266)

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Verified as fixed on v114 (31032) with iPad Pro (16.4.1).
