### ISSUE TITLE
The Zoom bar doesn't follow the Toolbar's Top position

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/firefox-ios#14114]
## Prerequisites
Set the Toolbar to the top.
## Steps to reproduce
1. Launch FF and access any webpage.
2. Tap on the hamburger menu and then on Zoom.
3. Observe the Zoom Bar.
### Expected behavior
The Zoom Bar should be together with the Toolbar Top or Bottom.
### Actual behavior
The zoom bar doesn't follow the Toolbar's Top position
### Device & build information
* Device: iPhone 13 Pro (15.7.1). 
* Build version: 9000 (30301) 
* First seen version: N/A 
### Notes
Please note that on iPad where the only position for the Toolbar is top, the Zoom bar is at the top.
Attachments: 

![image0](https://user-images.githubusercontent.com/42831109/234250069-5391f493-cd70-4da3-a9cf-45e57fad9c42.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6265)

**Comment by data-sync-user** [comment]
➤ Daniela Arcese commented:

This is per design https://www.figma.com/file/dIdFRmA0yACjkam2mb8eGq/Page-Zoom?type=design&node-id=1926-40657&t=bT1W7nrzvqLtwKcW-0 ( https://www.figma.com/file/dIdFRmA0yACjkam2mb8eGq/Page-Zoom?type=design&node-id=1926-40657&t=bT1W7nrzvqLtwKcW-0|smart-link )
