### ISSUE TITLE
The Zoom Bar doesn't disappear when switching to a new tab on `iPad`

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/firefox-ios#14120]
## Steps to reproduce
1. Launch FF.
2. Open 3 tabs.
3. On the first tab open a website and the Zoom Bard (let the other 2 empty or access a website)
4. Tap on the hamburger menu and then on Zoom.
5. While the Zoom Bar from the top bar swap between opened tabs.
### Expected behavior
The Zoom Bar should disappear when changing to a new tab.
### Actual behavior
The Zoom Bar doesn't disappear when switching to a new tab on iPad.
### Device & build information
* Device: iPad mini 5 (14.7). 
* Build version: 9000 (30301) 
* First seen version: N/A 
### Notes
Please note that if tapping on the + button to open a new page or on the tabs tray the Zoom Bar will always go away.
Attachments: 

https://user-images.githubusercontent.com/42831109/234266986-1e0c1c5f-8509-4eb9-9666-a90d010a39b5.mov

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6271)

**Comment by dnarcese** [comment]
Let's keep this behaviour consistent with iPhone
