### ISSUE TITLE
The Zoom Bar is not fully hidden while scrolling on `iPad`

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/firefox-ios#14122]
## Steps to reproduce
1. Launch FF and access any webpage.
2. Tap on the hamburger menu and then on Zoom.
3. While the Zoom Bar is displayed scroll up.
### Expected behavior
The Topside should be fully hidden.
### Actual behavior
A small part of the Zoom Bar is still displayed.
### Device & build information
* Device: iPad mini 5 (14.7). 
* Build version: 9000 (30301) 
* First seen version: N/A 
### Notes
Attachments: 

https://user-images.githubusercontent.com/42831109/234268494-303309e9-7fd7-4a1c-839b-04e5751f4c04.mov

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6272)

**Comment by data-sync-user** [comment]
➤ Sorin Paraipan commented:

Andrei Bodea I couldn’t reproduce it anymore. I will let it for another QA check. 

!Video.mov|thumbnail!

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

I’m still able to reproduce it on v114 (31032) with iPad Pro (16.4.1).
Might be the resolution?

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Verified as fixed on v9000 (31138) with iPad Pro (16.4.1)
To be checked when the new v114 build will be created.
