### ISSUE TITLE
The Zoom Bar doesn't disappear when switching from `Private` to `Normal` Browsing on `iPad`

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/firefox-ios#14124]
## Steps to reproduce
1. Launch FF.
2. Open a few tabs.
3. Switch to private browsing and open any website.
4. Tap on the hamburger menu and then on Zoom.
5. Switch to normal browsing.
### Expected behavior
The Zoom bar should disappear after switching to normal browsing.
### Actual behavior
The Zoom Bar doesn't disappear when switching from `Private` to `Normal` Browsing on `iPad`.
### Device & build information
* Device: iPad mini 5 (14.7). 
* Build version: 9000 (30301) 
* First seen version: N/A 
### Notes
Attachments: 

https://user-images.githubusercontent.com/42831109/234271968-57e697df-c873-48a5-ab2c-df35329ca4ed.mov

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6273)

**Comment by data-sync-user** [comment]
➤ Daniela Arcese commented:

Aarjav Pandya what should the behaviour be?

**Comment by data-sync-user** [comment]
➤ Aarjav Pandya commented:

The zoom component should be tab specific. 

  * If the user switches away from the tab in which the zoom component was accessed, hide the zoom component irrespective of browsing mode or website domain. 
  * For example, the user has 2 tabs open, both are new york times but of different articles. The user has changed the zoom level but not closed it on one of the tabs, when the user switches between the tabs
    * Save the current zoom level for the domain. 
    * Close the zoom component when the user switches(not closes) the tab. 
    * Update the 2nd tab to match the zoom level saved on the 1st tab.

**Comment by data-sync-user** [comment]
➤ Daniela Arcese commented:

This may be fixed by https://mozilla-hub.atlassian.net/browse/FXIOS-6271 ( https://mozilla-hub.atlassian.net/browse/FXIOS-6271|smart-link ) . Let’s check it again after that is fixed.

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Verified as fixed on v114 (31032) with iPad Pro (16.4.1).
