### ISSUE TITLE
Send Tab not working on version 1403

### ISSUE THREAD

**Issue by fjaguero** [mozilla-mobile/firefox-ios#1415]
Hi,

I just updated to the latest release via TestFlight and the Send Tab feature is not working. I can view all my tabs from my other 5 devices but when I tap on "Send Tab", the loading spinners stay there and sometime it even freezes. I don't know if it has something to do with my config. Closing and opening again didn't fixed the issue.

**Steps to reproduce:**
- Open Firefox
- Tap on the paypal.com tile
[ Site is loaded ]
- Tap on share
- Tap on Send Tab
-- The screen is freezed with the spinner icon also freezed

**Device:**
iPod Touch 5 Gen
iOS 9.2 (13C75)

**Screenshot:**
![screenshot](https://cloud.githubusercontent.com/assets/716123/12184443/8c19a870-b595-11e5-85e1-5ed35d98fe83.png)

**Comment by AaronMT** [comment]
This works for me. I see all available devices available to select from. @rnewman what sort of logging can @fjaguero check for here?

**Comment by rnewman** [comment]
This is really hard to debug. 

What happens if you try to share while in Airplane Mode?

Do the usual logs (exported via Xcode's bundle fetch) show any errors?
