### ISSUE TITLE
Can't edit a bookmark from the edit prompt in Firefox for iOS

### ISSUE THREAD

**Issue by kelimuttu** [mozilla-mobile/firefox-ios#14152]
## Steps to reproduce
1. Go to a website
2. Click the hamburger menu and choose to Add the page as a bookmark
3. A prompt will appear that says that a new bookmark has been added. Click on the Edit button that appears in the same prompt
4. Edit the bookmark detail

### Expected behavior
I should be able to save the bookmark after I modify the detail

### Actual behavior
There should be a Save button

### Device & build information
* Device: iPhone 12
* Build version: 112.2
* First seen version: Not sure

### Notes
Attachments: 
![gambar](https://user-images.githubusercontent.com/4922388/234649476-b3a3dedb-93a6-4952-b86c-def5b74d3b6f.png)

This first reported to @FirefoxSupport on Twitter

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6289)

**Comment by lmarceau** [comment]
Hello @kelimuttu, this was reported in ticket https://github.com/mozilla-mobile/firefox-ios/issues/13623. This will be fixed with v113. Please tell us if this next version doesn't fix the problem for you. Thank you!

**Comment by abodea** [comment]
Thank you for adding this issue @kelimuttu closing it as a duplicate based on the comment above.
