### ISSUE TITLE
delete button in inactive tabs section worrisome

### ISSUE THREAD

**Issue by lime124** [mozilla-mobile/firefox-ios#14164]
## Steps to reproduce
Pre condition - have some tabs in the inactive tabs section

1. Open the tab tray, go to the inactive tab section
2. Swipe across a tab to close it
3. observe

### Expected behavior
The action button reflects the expected action of closing the tab

### Actual behavior
The button says 'delete' which makes me wonder if something more is happening than just closing the open tab. Is it also being deleted from my browsing history?

Other considerations:
If we change this behaviour on ios - what updates needs to be made to android UI

![File](https://user-images.githubusercontent.com/287322/234905885-f7de43eb-3ae8-40e9-889c-a9a42051e74a.jpg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6293)

**Comment by dnarcese** [comment]
@lime124 do you suggest it say 'Close' instead?

**Comment by lime124** [comment]
oh hey @dnarcese ! :) i passed this bug to the mobile ux team for them to take a look it and provide the recommendation. thanks for triaging so quickly!

**Comment by ewachowiak** [comment]
I agree, we could update the copy to "Close" to better reflect what is happening.

**Comment by data-sync-user** [comment]
➤ Alina Moldovan commented:

Validated as fixed using FF V9000 (31186) and iPhone 14+ (16.0.3) & iPad Air 3rd Gen (16.3.1).
