### ISSUE TITLE
Toast message with the undo option is not displayed when a tab in a tab group is closed

### ISSUE THREAD

**Issue by alinamoldovan84** [mozilla-mobile/firefox-ios#14177]
## Steps to reproduce
1. Have some tabs grouped in a tab group
1. Open the tab tray 
1. Close a tab in the tab group

### Expected behavior
A toast confirmation message containing the Undo option should be displayed

### Actual behavior
The toast message is not displayed 

### Device & build information
* Device: iPhone 14 Plus (16.0.3), iPad Air 3dr Gen (16.3.1)  
* Build version: v9000 (30398) 
* First seen version: ? 
    1. Notes
Attachments: 

https://user-images.githubusercontent.com/124251579/235120273-5ca7fef3-bfa3-4861-a45f-0cd4d62659d8.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6301)

**Comment by data-sync-user** [comment]
➤ Yoana Rios Diaz commented:

Daniela Arcese Alina Moldovan as discussed with UX undo toast for Tab group was not implemented in this task
