### ISSUE TITLE
On opening a new tab the url bar remains populated with the url for the previous tab

### ISSUE THREAD

**Issue by OrlaM** [mozilla-mobile/firefox-ios#14190]
## Steps to reproduce
* Visit any website
* Select the URL bar to bring up the keyboard
* Scroll on the page so the keyboard is dismissed
* Select the tab tray
* Add a new tab

### Expected behavior
The url bar is empty on the new tab

### Actual behavior
The url bar contains the url of the most recent active tab

### Device & build information
* Device: Any
* Build version: v113 prod
* First seen version: v113 prod but not sure if it was present in an older version

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6309)

**Comment by abodea** [comment]
Hello, @dnarcese please note that I tried on the latest 9000 (30588) with iPhone 13 Pro (15.7.1) and I was not able to reproduce this issue I tried at list 10 times.

**Comment by OrlaM** [comment]
I discovered there is slightly more to the repo steps.

- Visit any website
- Select the URL bar to bring up the keyboard
- Scroll on the page so the keyboard is dismissed
- Select the tab tray
- Add a new tab

The url bar remains populated after these steps.
Even worse is if the user takes the same steps on a search and then opens a new tab the entire search page is still displayed on the new tab.

**Comment by data-sync-user** [comment]
➤ Yoana Rios Diaz commented:

Daniela Arcese what’s the priority for this ticket, what release should I aim to fix it?
