### ISSUE TITLE
Home Screen - Alignment issue with 'Recently Saved' list items when scrolling to the right 

### ISSUE THREAD

**Issue by alinamoldovan84** [mozilla-mobile/firefox-ios#14214]
## Steps to reproduce
1. have 10 elements in Recently Saved list (5 bookmarks and 5 items in reading list)
1. Scroll to the right 
1. Check the elements alignment  for both portrait and landscape orientation 

### Expected behavior
The first visible element in the list is aligned with the rest of the elements on the homepage

### Actual behavior
The reading list items are not aligned with the rest of the elements on the page (margins are not respected)

### Device & build information
* Device: iPhone 14 Plus (16.0.3) 
* Build version: 113 (30434) 
* First seen version: ? 
### Notes
Attachments: 

https://user-images.githubusercontent.com/124251579/235889875-050477a7-4f6a-4ce0-acfc-d6f0d669d4e9.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6315)

**Comment by dnarcese** [comment]
@alinamoldovan84 can you provide a screenshot and highlight where the misalignment is please? Having trouble seeing it

**Comment by data-sync-user** [comment]
➤ Alina Moldovan commented:

here are the screenshots

!Skype_Picture_1.jpeg|width=1284,height=2778!

!Skype_Picture_2.jpeg|width=2778,height=1284!
