### ISSUE TITLE
String casing on research surface incorrect

### ISSUE THREAD

**Issue by lime124** [mozilla-mobile/firefox-ios#14213]
We're mixing casing on the research surface screen and the casing should be consistent. I believe for technical reasons, we have to use the same string on ios and android which is causing the button to sentencue case "Take survey". The negative button should match the casing even though it is atypical of platform conventions.  @ewachowiak for confirmation that i have that correct! :)

![IMG_1223](https://user-images.githubusercontent.com/287322/235802313-4eb2429e-5600-4ab6-be18-982f7156e24b.PNG)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6314)

**Comment by ewachowiak** [comment]
In a slack discussion I asked that both buttons be in Title Case, acknowledging that this is not an Android convention. Please update first button to "Take Survey". Thanks.

**Comment by el-moz** [comment]
There are a few surveys currently running - one for validation and others that launch and close weekly for baselining. It looks like this update was made for validation but wasn't made to the baselining survey for the weeklies. I've updated the next weekly that launches today, so the incorrect ones will all be closed. Thanks for pointing this out!

**Comment by el-moz** [comment]
Feel free to assign to me and close as it's been corrected :)
