### ISSUE TITLE
Replace use of DefaultStandardFont with preferredFont

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#14269]
Replace `DefaultStandardFont` with `DefaultDynamicFontHelper.preferredFont(withTextStyle:size:weight:)`.

* `defaultStandardFontSize` can be assumed to be 17.
* `textStyle` should be chosen considering on the UI element it is used in - in most cases it will be `.body`.
* `weight` should be `.regular`.
* `DefaultStandardFont` in DynamicFontHelper should be deleted.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6349)

**Comment by data-sync-user** [comment]
➤ Winnie Teichmann commented:

For QA: Please test that settings, sync now and search still look correct.

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v9000 (33983) with iPhone SE (16.5).

**Comment by atfelix** [comment]
@thatswinnie:  I may have missed a disguised call to `DefaultStandardFont` in the following lines:

https://github.com/mozilla-mobile/firefox-ios/blob/36bf038af6b0abb250667444c022f40d4e50d799/Client/Frontend/Settings/Main/Account/SyncNowSetting.swift#L114-L116

Should I reopen this issue or open a separate issue?

**Comment by thatswinnie** [comment]
> @thatswinnie: I may have missed a disguised call to `DefaultStandardFont` in the following lines:
> 
> https://github.com/mozilla-mobile/firefox-ios/blob/36bf038af6b0abb250667444c022f40d4e50d799/Client/Frontend/Settings/Main/Account/SyncNowSetting.swift#L114-L116
> 
> Should I reopen this issue or open a separate issue?

@atfelix I don't see any calls to `DefaultStandardFont` in the code anymore. What you are referencing is a call to `DefaultStandardFontSize` which is still used in a couple of places. That is ok and nothing to worry about. It will be removed in the future. So no need to reopen or creating a new issue. Thanks for checking!
