### ISSUE TITLE
Replace use of DefaultStandardFontBold with preferredFont

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#14270]
Replace `DefaultStandardFontBold` with `DefaultDynamicFontHelper.preferredFont(withTextStyle:size:weight:)`.

* `defaultStandardFontSize` can be assumed to be 17.
* `textStyle` should be chosen considering on the UI element it is used in - in most cases it will be `.body`.
* `weight` should be `.semibold`.
* `DefaultStandardFontBold` in DynamicFontHelper should be deleted.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6350)

**Comment by atfelix** [comment]
@thatswinnie:  I was looking at this issue and is I use `preferredBoldFont`, then the account row on the settings page changes to a heavier bold font.  Currently, you are using `boldSystemFont` which uses a semi-bold text style (or a bold text style when `Bold Text` is enabled in the accessibility settings).  Should I use `preferredFont` instead with a `.semibold` text style or use the `preferredBoldFont` or something else altogether?

| Bold Text setting | Before | After with `preferredFont` with `.semibold` text style | After with `preferredBoldFont` |
|-|-|-|-|
| Disbled | ![Account status setting row with email@example.com, the text style is semi-bold](https://github.com/mozilla-mobile/firefox-ios/assets/16291501/a8b6ac34-95da-40e3-b785-3a221fd96257) | ![Account status setting row with email@example.com, the text style is semi-bold](https://github.com/mozilla-mobile/firefox-ios/assets/16291501/a821bf4b-ceea-4d30-ac98-168828277714) | ![Account status setting row with email@example.com, the text style is bold](https://github.com/mozilla-mobile/firefox-ios/assets/16291501/b8d02b7e-1099-4d95-b555-88eb0be589b3) |
| Enabled | ![Account status setting row with email@example.com, the text style is bold](https://github.com/mozilla-mobile/firefox-ios/assets/16291501/d73f1658-8203-4340-8365-1ee2fe0f73e3) | ![Account status setting row with email@example.com, the text style is bold](https://github.com/mozilla-mobile/firefox-ios/assets/16291501/9df4dc7c-27fa-40a4-9d7b-81bcc32381fa) | ![Account status setting row with email@example.com, the text style is heavy](https://github.com/mozilla-mobile/firefox-ios/assets/16291501/3a20fc3c-73b8-40d6-9393-c7292a2c3ace) |

**Comment by thatswinnie** [comment]
@atfelix good catch. Thanks for investigating this. Let's use `.semibold` like you suggested.

**Comment by thatswinnie** [comment]
@atfelix please use `preferredFont` with `.semibold` (I updated the task accordingly). Updating `preferredBoldFont` could have unintended consequences in other areas.

**Comment by data-sync-user** [comment]
➤ Winnie Teichmann commented:

For QA: please verify that the Firefox account name is displayed correctly in settings.

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified on v9000 (34131), with iPhone SE (16.6.1).

To be rechecked once the v119 build is officially released.
