### ISSUE TITLE
The `What's new` page is not displayed on v112.2 (30158) `(App Store build)`

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/firefox-ios#14283]
## Steps to reproduce
1. Open the hamburger menu.
1. Access the `What's New` page.

### Expected behavior
The button should link to `https://www.mozilla.org/en-US/firefox/ios/notes/`

### Actual behavior
Page Not Found displayed

### Device & build information
* Device: iPhone 13 Pro (15.7.1). 
* Build version: 112.2 (30158) 
* First seen version: 112.2 (30158) 

*# 
*## Notes
Attachments: 
![width=200,height=183](https://user-images.githubusercontent.com/42831109/236783939-d3e25307-ee9b-45c1-89f1-6c8480d47ea9.PNG)

<

!--- Screenshots or screen recordings are very helpful for reproducing|width=200,height=183!

-->

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6361)

**Comment by data-sync-user** [comment]
➤ Catalin Andrei Neculaide commented:

The link is the correct one in the app, I think it’s a backend problem, because if it’s a dot version (example 113.1), then the link wont work.

**Comment by data-sync-user** [comment]
➤ Nishant Bhasin commented:

For every dot version, we should always point to major version link as we do not support dot version links
