### ISSUE TITLE
Toast message is not displayed when user closes a tab from tab tray's context menu  

### ISSUE THREAD

**Issue by alinamoldovan84** [mozilla-mobile/firefox-ios#14293]
## Steps to reproduce
1. Have multiple tabs opened 
1. Long press on the tab tray to pen the tab context menu
1. Choose to close the tab

### Expected behavior
Toast message is not displayed informing the user that the tab is closed and having the Undo option 

### Actual behavior
the toast notification is not displayed 

### Notes 
On tablet the same issue reproduces when user close the tab from the bar 

### Device & build information
* Device:  iPhone 14 Plus (16.0.3) iPad Air 3rd Gen (16.3.1) 
* Build version: V9000 (30588) 
* First seen version: ? 
### Notes
Attachments: 

https://user-images.githubusercontent.com/124251579/236849728-28b1cf3a-e944-4216-a838-7d4234cbd876.MP4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6363)

**Comment by data-sync-user** [comment]
➤ Yoana Rios Diaz commented:

Alina Moldovan Daniela Arcese this original implementation was to add the undo toast only on the TabTray if we want to allow this option outside of TabTray we need to create separate tickets.
It didn’t include the work on closing tabs on TopTabs (iPad only) or long press and context menu from the app toolbar

**Comment by data-sync-user** [comment]
➤ Adina Petridean commented:

Verified as fixed on v9000(40702), with iPhone 14 Pro Max (16.2).

!undo.mp4|width=886,height=1920,alt="undo.mp4"!

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v126 (40774), with iPhone 15 (17.4).
