### ISSUE TITLE
Swapped favicons on the home page

### ISSUE THREAD

**Issue by lmfra** [mozilla-mobile/firefox-ios#14325]
## Steps to reproduce
* (Not exactly known, but it is happening several times a day)
* Pin links (4 on my phone) to the links bar on home page
* Restart Firefox 
* Sometimes the problem occurs

### Expected behavior
Displaying the right favicons for the respective link text/ target link

### Actual behavior
Swapped favicons at the pinned links bar, but links are linking to the title/expected link target 
->In my case, Qwant has a fast.com icon, Fast speedtest has qwant.com icon (see attached image)

### Device & build information
* Device: iPhone SE 2020, iPad 9th Gen
* Build version: ? 113.0 (30633) 
* First seen version: 112.1
### Notes
Attachments: 
![IMG_4556](https://github.com/mozilla-mobile/firefox-ios/assets/97810383/467954e7-221c-44b0-94c4-6473d05ec3ff)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6379)

**Comment by lmfra** [comment]
Got another issue with the pinned links. Now the first two links show the favicons for the second link. 
![IMG_4559](https://github.com/mozilla-mobile/firefox-ios/assets/97810383/f26561ad-d806-4d54-a592-0168d3b1ed57)

**Comment by lmarceau** [comment]
Thank you, yes that's the same issue. We'll look into that soon 🙏

**Comment by lmfra** [comment]
![image](https://github.com/mozilla-mobile/firefox-ios/assets/97810383/4ce8c1b2-2e8b-4775-8f2c-c30ef13465c8)
**Issue appeared again today.**

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v9000(32131), with iPhone SE (16.6.1).

To be rechecked once the v119 build is officially released.
