### ISSUE TITLE
domain-zoom-levels.json should be stored in the caches directory

### ISSUE THREAD

**Issue by OrlaM** [mozilla-mobile/firefox-ios#14357]
## Steps to reproduce
Use the page zoom feature

### Expected behavior
The file to store the domain level zoom should be in the caches directory

### Actual behavior
The file is in the documents directory

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6388)

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Verified as fixed in v114 (31183) with iPhone 13 Pro (15.7.1).

Nothing was stored in the documents directory.
