### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by iiasceri** [mozilla-mobile/firefox-ios#14382]
Showing Recent Messages
CpResource /Users/nick/Library/Developer/Xcode/DerivedData/Client-begfrayvtfuxembulsuiejemsaep/Build/Products/Fennec-iphonesimulator/Client.app/disconnect-block-fingerprinting.json /Users/nick/Downloads/firefox-ios/content-blocker-lib-ios/Lists/disconnect-block-fingerprinting.json (in target 'Client' from project 'Client')
    cd /Users/nick/Downloads/firefox-ios
    builtin-copy -exclude .DS_Store -exclude CVS -exclude .svn -exclude .git -exclude .hg -resolve-src-symlinks /Users/nick/Downloads/firefox-ios/content-blocker-lib-ios/Lists/disconnect-block-fingerprinting.json /Users/nick/Library/Developer/Xcode/DerivedData/Client-begfrayvtfuxembulsuiejemsaep/Build/Products/Fennec-iphonesimulator/Client.app

error: /Users/nick/Downloads/firefox-ios/content-blocker-lib-ios/Lists/disconnect-block-fingerprinting.json: No such file or directory (in target 'Client' from project 'Client')

/Users/nick/Downloads/firefox-ios/content-blocker-lib-ios/Lists/disconnect-block-fingerprinting.json: No such file or directory

CpResource /Users/nick/Library/Developer/Xcode/DerivedData/Client-begfrayvtfuxembulsuiejemsaep/Build/Products/Fennec-iphonesimulator/Client.app/disconnect-block-social.json /Users/nick/Downloads/firefox-ios/content-blocker-lib-ios/Lists/disconnect-block-social.json (in target 'Client' from project 'Client')
    cd /Users/nick/Downloads/firefox-ios
    builtin-copy -exclude .DS_Store -exclude CVS -exclude .svn -exclude .git -exclude .hg -resolve-src-symlinks /Users/nick/Downloads/firefox-ios/content-blocker-lib-ios/Lists/disconnect-block-social.json /Users/nick/Library/Developer/Xcode/DerivedData/Client-begfrayvtfuxembulsuiejemsaep/Build/Products/Fennec-iphonesimulator/Client.app

error: /Users/nick/Downloads/firefox-ios/content-blocker-lib-ios/Lists/disconnect-block-social.json: No such file or directory (in target 'Client' from project 'Client')

/Users/nick/Downloads/firefox-ios/content-blocker-lib-ios/Lists/disconnect-block-social.json: No such file or directory

CpResource /Users/nick/Library/Developer/Xcode/DerivedData/Client-begfrayvtfuxembulsuiejemsaep/Build/Products/Fennec-iphonesimulator/Client.app/disconnect-block-cookies-social.json /Users/nick/Downloads/firefox-ios/content-blocker-lib-ios/Lists/disconnect-block-cookies-social.json (in target 'Client' from project 'Client')
    cd /Users/nick/Downloads/firefox-ios
    builtin-copy -exclude .DS_Store -exclude CVS -exclude .svn -exclude .git -exclude .hg -resolve-src-symlinks /Users/nick/Downloads/firefox-ios/content-blocker-lib-ios/Lists/disconnect-block-cookies-social.json /Users/nick/Library/Developer/Xcode/DerivedData/Client-begfrayvtfuxembulsuiejemsaep/Build/Products/Fennec-iphonesimulator/Client.app

error: /Users/nick/Downloads/firefox-ios/content-blocker-lib-ios/Lists/disconnect-block-cookies-social.json: No such file or directory (in target 'Client' from project 'Client')

/Users/nick/Downloads/firefox-ios/content-blocker-lib-ios/Lists/disconnect-block-cookies-social.json: No such file or directory

CpResource /Users/nick/Library/Developer/Xcode/DerivedData/Client-begfrayvtfuxembulsuiejemsaep/Build/Products/Fennec-iphonesimulator/Client.app/disconnect-block-cryptomining.json /Users/nick/Downloads/firefox-ios/content-blocker-lib-ios/Lists/disconnect-block-cryptomining.json (in target 'Client' from project 'Client')
    cd /Users/nick/Downloads/firefox-ios
    builtin-copy -exclude .DS_Store -exclude CVS -exclude .svn -exclude .git -exclude .hg -resolve-src-symlinks /Users/nick/Downloads/firefox-ios/content-blocker-lib-ios/Lists/disconnect-block-cryptomining.json /Users/nick/Library/Developer/Xcode/DerivedData/Client-begfrayvtfuxembulsuiejemsaep/Build/Products/Fennec-iphonesimulator/Client.app

error: /Users/nick/Downloads/firefox-ios/content-blocker-lib-ios/Lists/disconnect-block-cryptomining.json: No such file or directory (in target 'Client' from project 'Client')

/Users/nick/Downloads/firefox-ios/content-blocker-lib-ios/Lists/disconnect-block-cryptomining.json: No such file or directory

CpResource /Users/nick/Library/Developer/Xcode/DerivedData/Client-begfrayvtfuxembulsuiejemsaep/Build/Products/Fennec-iphonesimulator/Client.app/disconnect-block-cookies-content.json /Users/nick/Downloads/firefox-ios/content-blocker-lib-ios/Lists/disconnect-block-cookies-content.json (in target 'Client' from project 'Client')
    cd /Users/nick/Downloads/firefox-ios
    builtin-copy -exclude .DS_Store -exclude CVS -exclude .svn -exclude .git -exclude .hg -resolve-src-symlinks /Users/nick/Downloads/firefox-ios/content-blocker-lib-ios/Lists/disconnect-block-cookies-content.json /Users/nick/Library/Developer/Xcode/DerivedData/Client-begfrayvtfuxembulsuiejemsaep/Build/Products/Fennec-iphonesimulator/Client.app

error: /Users/nick/Downloads/firefox-ios/content-blocker-lib-ios/Lists/disconnect-block-cookies-content.json: No such file or directory (in target 'Client' from project 'Client')

/Users/nick/Downloads/firefox-ios/content-blocker-lib-ios/Lists/disconnect-block-cookies-content.json: No such file or directory

CpResource /Users/nick/Library/Developer/Xcode/DerivedData/Client-begfrayvtfuxembulsuiejemsaep/Build/Products/Fennec-iphonesimulator/Client.app/disconnect-block-cookies-analytics.json /Users/nick/Downloads/firefox-ios/content-blocker-lib-ios/Lists/disconnect-block-cookies-analytics.json (in target 'Client' from project 'Client')
    cd /Users/nick/Downloads/firefox-ios
    builtin-copy -exclude .DS_Store -exclude CVS -exclude .svn -exclude .git -exclude .hg -resolve-src-symlinks /Users/nick/Downloads/firefox-ios/content-blocker-lib-ios/Lists/disconnect-block-cookies-analytics.json /Users/nick/Library/Developer/Xcode/DerivedData/Client-begfrayvtfuxembulsuiejemsaep/Build/Products/Fennec-iphonesimulator/Client.app

error: /Users/nick/Downloads/firefox-ios/content-blocker-lib-ios/Lists/disconnect-block-cookies-analytics.json: No such file or directory (in target 'Client' from project 'Client')

/Users/nick/Downloads/firefox-ios/content-blocker-lib-ios/Lists/disconnect-block-cookies-analytics.json: No such file or directory

CpResource /Users/nick/Library/Developer/Xcode/DerivedData/Client-begfrayvtfuxembulsuiejemsaep/Build/Products/Fennec-iphonesimulator/Client.app/disconnect-block-cookies-advertising.json /Users/nick/Downloads/firefox-ios/content-blocker-lib-ios/Lists/disconnect-block-cookies-advertising.json (in target 'Client' from project 'Client')
    cd /Users/nick/Downloads/firefox-ios
    builtin-copy -exclude .DS_Store -exclude CVS -exclude .svn -exclude .git -exclude .hg -resolve-src-symlinks /Users/nick/Downloads/firefox-ios/content-blocker-lib-ios/Lists/disconnect-block-cookies-advertising.json /Users/nick/Library/Developer/Xcode/DerivedData/Client-begfrayvtfuxembulsuiejemsaep/Build/Products/Fennec-iphonesimulator/Client.app

error: /Users/nick/Downloads/firefox-ios/content-blocker-lib-ios/Lists/disconnect-block-cookies-advertising.json: No such file or directory (in target 'Client' from project 'Client')

/Users/nick/Downloads/firefox-ios/content-blocker-lib-ios/Lists/disconnect-block-cookies-advertising.json: No such file or directory

CpResource /Users/nick/Library/Developer/Xcode/DerivedData/Client-begfrayvtfuxembulsuiejemsaep/Build/Products/Fennec-iphonesimulator/Client.app/disconnect-block-analytics.json /Users/nick/Downloads/firefox-ios/content-blocker-lib-ios/Lists/disconnect-block-analytics.json (in target 'Client' from project 'Client')
    cd /Users/nick/Downloads/firefox-ios
    builtin-copy -exclude .DS_Store -exclude CVS -exclude .svn -exclude .git -exclude .hg -resolve-src-symlinks /Users/nick/Downloads/firefox-ios/content-blocker-lib-ios/Lists/disconnect-block-analytics.json /Users/nick/Library/Developer/Xcode/DerivedData/Client-begfrayvtfuxembulsuiejemsaep/Build/Products/Fennec-iphonesimulator/Client.app

error: /Users/nick/Downloads/firefox-ios/content-blocker-lib-ios/Lists/disconnect-block-analytics.json: No such file or directory (in target 'Client' from project 'Client')

/Users/nick/Downloads/firefox-ios/content-blocker-lib-ios/Lists/disconnect-block-analytics.json: No such file or directory

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6398)

**Comment by lmarceau** [comment]
Hello @iiasceri, when does this issue happen? When trying to build the application in Xcode? If so, please make sure to run successfully the commands in our `https://github.com/mozilla-mobile/firefox-ios#building-the-code`. This is where the files you are missing in your build get generated.
