### ISSUE TITLE
Graphic inconsistency in tabs tray when switching tabs order and changing from normal to private mode in landscape view

### ISSUE THREAD

**Issue by alinamoldovan84** [mozilla-mobile/firefox-ios#14409]
## Steps to reproduce

1. Have multiple tabs opened in normal browsing mode
2. Have multiple tabs opened in private browsing mode
3. Open the tabs tray 
4. Switch order for some tabs 
5. Move to private browsing mode
6. . Switch order for some tabs 
7. Check the tabs thumbnails 

### Expected behavior
Tabs thumbnails should be correctly displayed  

### Actual behavior
Graphic inconsistency  in displaying the tabs thumbnails. Please see the attached video and screenshot   

### Device & build information
* Device: iPhone 14 Plus (16.0.1) 
* Build version: 113.1 (30885

https://github.com/mozilla-mobile/firefox-ios/assets/124251579/fa998b14-5ceb-45ef-87af-65187b5bede7

![Skype_Picture_22](https://github.com/mozilla-mobile/firefox-ios/assets/124251579/b8c7403b-5e7f-4fd0-8311-5b9844f69421)
) 
* First seen version: ? 
### Notes
Attachments: 

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6407)

**Comment by data-sync-user** [comment]
➤ Nishant Bhasin commented:

NOTE: Giving this to Catalin Andrei Neculaide but you have no objections on completing it as you are only here for 1/2 sprint!!

**Comment by DianaBarladeanu** [comment]
Verified as fixed on v9000 (32311) with iPhone SE (15.4).
