### ISSUE TITLE
The privacy policy link from onboarding redirect is to `MacRumors` instead of a privacy link

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/firefox-ios#14428]
## Steps to reproduce
1. Install and launch FF.
2. Observe the onboarding card with the privacy policy link.
3. Tap on the Privacy link.
### Expected behavior
The link should redirect the user to the privacy page.
### Actual behavior
The privacy policy link from onboarding redirect is to `MacRumors` instead of a privacy link
### Device & build information
* Device: iPhone 13 Pro (15.7.1). 
* Build version: v114 (30951).
* First seen version: v114 (30951).
### Notes
Attachments: 

https://github.com/mozilla-mobile/firefox-ios/assets/42831109/144082fb-a0e1-47a1-8a3c-2777d21b4ea3

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6420)

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Verified as fixed on v114 (31254) with iPhone 13 Pro (15.7.1).
