### ISSUE TITLE
The first `Welcome` onboarding card is dismissed after closing the Privacy Link notice

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/firefox-ios#14431]
## Steps to reproduce
1. Launch FF and observe the first onboarding card.
2. Tap on the Privacy link.
3. Close the privacy link by tapping on the Done button.
4. Observe the behavior.
### Expected behavior
The privacy section should be closed and the displayed onboarding card should still be the same aka the first one.
### Actual behavior
The first `Welcome` onboarding card is dismissed after closing the Privacy Link notice and the next onboarding card is displayed.
### Device & build information
* Device: iPhone 13 Pro (15.7.1). 
* Build version: v114 (30951).
* First seen version: v114 (30951).
### Notes
Attachments: 

https://github.com/mozilla-mobile/firefox-ios/assets/42831109/19c7608f-d5d2-4f1f-8e33-3ce387c1b09e

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6422)

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Verified as fixed on v114 (31254) with iPhone 13 Pro (15.7.1).
