### ISSUE TITLE
Update mobile icons to new style pt1

### ISSUE THREAD

**Issue by cwzilla** [mozilla-mobile/firefox-ios#14455]
Hi iOS team,

All our mobile icons have recently been redesigned. It's a subtle redesign, some of the changes include: increasing the line width from 1.5px to 1.75px, removing the "cut" off of corners, and some icons have been simplified to include less detail. To be clear, these are just **style** changes, and the size of the icons still remain the same. Here is an example of these changes:

![icon-redesign-example](https://github.com/mozilla-mobile/firefox-ios/assets/87655586/9d26c21e-5761-4d61-96e1-0a0ae85e7986)

Apart from style changes, some icon names have also been renamed to improve consistency.

The updated icons can all be found in our newly launched [Acorn Icons](https://github.com/FirefoxUX/acorn-icons) repo. Going forward, any icon changes or updates can be found here. The [icon library](https://www.figma.com/file/Kv7wWr8vH6AQrGhu9vmjdE/Mobile-Icons?type=design&node-id=0%3A1&t=cW2uj9EjZHHH89xR-1) in Figma will also be maintained as well, these new style and naming changes are already updated in there.

Some things to note particularly for iOS:
- Icons in the repo will all be provided in PDF format
- Names in the repo will appear differently than they are in Figma. In Figma, we have 3 standard icon sizes of 16, 20, and 24 where we include the size as a suffix in the icon name (for example: bookmark-tray-24). @nbhasin2 and I have discussed naming conventions for iOS in the repo and instead of using numbers, we will convert them to Small, Medium and Large. 16 is Small, 20 is Medium and 24 is Large. An example PDF icon in the repo will be named: bookmarkTrayLarge.

I have also created a doc that highlights the naming changes here that show the previous and new name (if applicable): [https://docs.google.com/spreadsheets/d/1kn04zBo6sBdI9X6xUVLqHnFTZozhWOo-x7L9T1Lg_zA/edit?usp=sharing](https://docs.google.com/spreadsheets/d/1kn04zBo6sBdI9X6xUVLqHnFTZozhWOo-x7L9T1Lg_zA/edit?usp=sharing)

Please let me know if you have any questions. Thank you!

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6430)

**Comment by data-sync-user** [comment]
➤ Winnie Teichmann commented:

For QA: Please check the app for any missing icons or wrong color of them (light & dark mode).

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Verified as fixed on v116 (32618) with iPhone 13 Pro (15.7.1).

**Comment by cwzilla** [comment]
Hi team, I have a small request with the icon updates.

For all the private-related icons, could we hold off on updating these icons? We're redesigning this icon and would like to just continue using the current/old icon in the meantime until we have the new one. This overlaps a bit with the Private Browsing Mode work and we've left a comment in there to not update the icon as well. We will file a bug later on when the new icon is ready to be updated.

These are the private icons I'm referring to:
- https://github.com/FirefoxUX/acorn-icons/blob/main/icons/mobile/20/pdf/privateModeCircleFillMedium.pdf
- https://github.com/FirefoxUX/acorn-icons/blob/main/icons/mobile/24/pdf/privateModeCircleFillLarge.pdf
- https://github.com/FirefoxUX/acorn-icons/blob/main/icons/mobile/24/pdf/privateModeLarge.pdf

Thank you! cc: @topotropic

**Comment by thatswinnie** [comment]
`privateModeLarge` has already been updated and will be part of the v117. The other private mode icons have not been updated yet.
