### ISSUE TITLE
New account does not recieve push notifications for Sync, when setting is ON

### ISSUE THREAD

**Issue by tarikeshaq** [mozilla-mobile/firefox-ios#14467]
## Steps to reproduce
- Fresh install of Firefox iOS
- Sign in to sync through onboarding
- Tap "Allow" when asked to enable push notifications
- Go to Settings -> Notification -> Sync (and verify that it's ON, don't change it)
- Close or move app to background
- Send a tab from any other device

### Expected behaviour
- Push notification arrives for the tab
### Actual behaviour
- No push notification
- But when changing the Settings -> Notification -> Sync to OFF, and then back to ON send tabs work again

### Device & build information
* Device: iPhone 14
* Build version: Firefox 113 (30633)
### Notes
The Firefox Accounts servers are seeing many send tabs not triggering push notifications for iOS devices and suspect this is the issue

cc @dnarcese @thatswinnie : could this be related to the new setting we added? The behavior suggests that although the setting is ON, the client isn't sending it's push subscription to FxA

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6434)

**Comment by data-sync-user** [comment]
➤ Nishant Bhasin commented:

Nishant Patel Timebox this please because we don’t know whats broken 🤷‍♂️

**Comment by nishant2718** [comment]
Linked issue, https://mozilla-hub.atlassian.net/browse/FXIOS-6471

**Comment by lucas3332** [comment]
"Hello there, Nishant Patel! I kindly request your expertise in troubleshooting the concerns pertaining to Imebox. The [app](https://modlonely.com/bgmi-apk/) seems to be experiencing a glitch, and we're uncertain about the exact cause. Your insightful investigation and problem-solving skills would be immensely valuable in unraveling this mystery. Your assistance in resolving this perplexing issue would be greatly appreciated!"
