### ISSUE TITLE
Onboarding incorrect values are being shown on Firefox iOS Beta v114

### ISSUE THREAD

**Issue by nbhasin2** [mozilla-mobile/firefox-ios#14469]
## Steps to reproduce
- Fresh install Firefox iOS beta 
- Open app with no internet connection

### Expected behavior
- Proper onboarding should be shown

### Actual behavior
- Incorrect onboarding is shown

### Device & build information
* Device: iPhone 14 Pro 
* Build version: 31007
* First seen version: Firefox iOS Beta
### Notes
Attachments: 

https://github.com/mozilla-mobile/firefox-ios/assets/8919439/c27ac9cb-e669-4277-b291-5d0c4b7f7b30

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6436)

**Comment by adudenamedruby** [comment]
Can you please provide clearer steps to reproduce. I've tried reproducing, and cannot on 9000.31007 in Beta. Please see the video for more details.


https://github.com/mozilla-mobile/firefox-ios/assets/11182210/980b3ed3-4541-4ffc-995a-a318db5cc74e

**Comment by nbhasin2** [comment]
But those are the steps!!

**Comment by nbhasin2** [comment]
FYI: Synced with Roux and it turns out that this is a localization issue

**Comment by adudenamedruby** [comment]
L10N & Nimbus team contacted to find a resolution.

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Verified as fixed on v114 (31069) with iPhone 13 Pro (15.7.1).
