### ISSUE TITLE
Tabs disappeared in the tabs tray after creating the same website more times `related to Tab Groups)`

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/firefox-ios#14481]
## Steps to reproduce
1. Launch FF and open more tabs with the same websites to create a Tab Group.
1. The tabs disappear from the tabs tray.
    1. Expected behavior
The tabs should always be displayed.
    1. Actual behavior
Tabs disappeared in the tabs tray after creating the second one
    1. Device & build information

* Device: **iPhone 13 Pro (15.7.1).** 
* Build version: **114 (31032) / v9000 (31034).** 
* First seen version: **113 (30010).** 
    1. Notes
I was able to reproduce on the v9000 and v114 constantly.
It's a weird behavior and I think it's related to Tab Groups. 

Attachments: 

https://github.com/mozilla-mobile/firefox-ios/assets/42831109/a07bbac5-6e71-4527-8e0d-261b402a0e34

https://github.com/mozilla-mobile/firefox-ios/assets/42831109/0a3318ba-ea37-4764-b2ef-80733111a12f

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6442)

**Comment by nbhasin2** [comment]
@abodea Is this happening on Release or Beta?

Tab groups shouldn't be enabled for release but if they are then we will look into it 🙂

**Comment by abodea** [comment]
Hello, @nishant2718 it's about the Beta build (beta channel), as today was beta 6 we were testing. 
I cannot reproduce the issue on the TF Release channel as the Tab Groups are not enabled there).
