### ISSUE TITLE
Zoom page bar shadow overlays bottom toolbar

### ISSUE THREAD

**Issue by q2r5** [mozilla-mobile/firefox-ios#14506]
## Steps to reproduce
* Set Toolbar to 'Bottom'
* Navigate to any webpage
* Open Zoom bar

### Expected behavior
* Shadow should overlay web content

### Actual behavior
* Shadow overlays toolbar

### Device & build information
* Device: iPhone 14 Pro, iOS 16.6b1
* Build version: 114.0 (31069)
* First seen version: 114.0 (31032)
### Notes
Attachments: 
![image](https://github.com/mozilla-mobile/firefox-ios/assets/650804/2a68a735-9412-46e9-816e-c5c7410daafe)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6451)

**Comment by FilippoZazzeroni** [comment]
Hi i didn't understand if the shadow should overlay the whole web content plus the url bar or just the web content ? thank you in advance.

**Comment by lmarceau** [comment]
It should overlay only the web content.

Top url bar with zoom looks like this:
![IMG_1283](https://github.com/mozilla-mobile/firefox-ios/assets/11338480/d933073e-9bcf-4f34-a8c8-2ee0bd862f9c)

Bottom url bar with zoom looks like this:
![IMG_1284](https://github.com/mozilla-mobile/firefox-ios/assets/11338480/f84232a8-81e0-4a89-970b-147dd8d34231)

**Comment by FilippoZazzeroni** [comment]
Ok thank you, i'm working on it to solve it.
