### ISSUE TITLE
Images inverted on certain websites

### ISSUE THREAD

**Issue by abpahl** [mozilla-mobile/firefox-ios#14505]
## Steps to reproduce
1. Navigate to certain websites on iOS Firefox (example, https://support.apple.com or hurricaneaquasports.com)
2. View the images and look at the colors

### Expected behavior
Images look normal

### Actual behavior
The images appear to be inverted/using incorrect colors. Blacks are white, and vise versa. Same images displays correct in Windows Firefox and Safari on the iPhone.

### Device & build information
* Device: iPhone XR, iOS 16.3.1
* Build version: Firefox 113.0 (30633)
* First seen version: Unknown, but I started noticing it relatively recently

### Notes
Attachment showing incorrect colors:
![IMG_3542](https://github.com/mozilla-mobile/firefox-ios/assets/20516733/1ed26d13-7874-42f6-b4cb-c0aa1daca95b)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6450)

**Comment by lmarceau** [comment]
This duplicates https://github.com/mozilla-mobile/firefox-ios/issues/5819, I'll close for now
