### ISSUE TITLE
Url shown over navigation bar

### ISSUE THREAD

**Issue by bkochendorfer** [mozilla-mobile/firefox-ios#14501]
## Steps to reproduce
This just happened, I'm not sure I have a way to reproduce.

### Expected behavior
The URL should be placed behind the navigation bar

### Device & build information
* Device:  iPhone 11 / iOS 16.4.1 9a)
* Build version:  Firefox 113.1 (30885)

### Notes
Attachments: 
![File](https://github.com/mozilla-mobile/firefox-ios/assets/1072933/5b7f2e0b-da2f-421c-8f52-ecbe6d8d65a9)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6448)

**Comment by abodea** [comment]
@dnarcese I tried on iPhone 13 Pro (15.7.1) with many app versions 113.1, 114, and 115 but I never saw the control bar that is always at the bottom to move to the top. 
I will keep investigating and update here if I find anything.
