### ISSUE TITLE
Subtitles in Settings are being clipped

### ISSUE THREAD

**Issue by gutley** [mozilla-mobile/firefox-ios#14532]
## Steps to reproduce
This is on main, 3c0920b5, any device

Open the Settings and look at the setting options with long subtitles (e.g. Close Private Tabs, Send Usage data and the options in the Tracking Protection screen)

### Expected behavior
The subtitles for these options should be fully readable
### Actual behavior
The subtitles get clipped. See screenshots:
![image](https://github.com/mozilla-mobile/firefox-ios/assets/2040690/09358de5-c7d6-40b0-9ed7-3ecad2b252b2)

![image](https://github.com/mozilla-mobile/firefox-ios/assets/2040690/d299d7c7-5e9a-439f-bc47-1f3def6c0dfa)

### Device & build information
* Device: ? Any on iOS 16 - Haven't tried previousOS versions
* Build version: ? main branch
* First seen version: ? unknown. First time I've pulled main in a while - 3c0920b5
### Notes
Attachments: 

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6461)

**Comment by lmarceau** [comment]
@dnarcese I believe this was caused by https://github.com/mozilla-mobile/firefox-ios/issues/13539 https://mozilla-hub.atlassian.net/browse/FXIOS-5959. IMO we shouldn't truncate on any cells in settings. Text should just adjust to whatever length we need to show.

**Comment by data-sync-user** [comment]
➤ Laurie Marceau commented:

For QA, please make sure settings cell content is not clipped, nor overflow if we have long names in the search engine box. i.e like:

!Simulator Screenshot - iPhone 14 - 2023-05-24 at 11.05.11.png|width=1170,height=2532!
