### ISSUE TITLE
[Experiment] The "Not Now" button is cut off on the "Onboarding - Set to Default"

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-mobile/firefox-ios#14553]
**Prerequisites**
- Have a Nimubs iOS Set to Default in Onboarding experiment launched.
- Have a browser profile enrolled in the treatment branch of the Onboarding experiment.
- Firefox is not set as the default app.

**Steps to reproduce**
1. Open the Firefox app with the profile from the prerequisites.
2. Observe the buttons of the "Onboarding - Set to Default" first card.

**Expected behavior**
- The "Set as Default Browser" and "Skip" buttons are correctly displayed in the view.

**Actual behavior**
- The "Not Now" button is not displayed in the view (seems to be cut off), and the screen needs to be scrolled in order to see the "Not Now" button.

**Device & build information**
- Device
	- iPhone 13 mini (iOS 16.2)
	- iPhone 11 (iOS 16.2)
	
- Build version:
	- Firefox for iOS Beta 114.0 (31168)
	
	
**Notes**
- Here is a screen recording of the issue: [Gdrive](https://drive.google.com/file/d/1Vu17qqaaxoOU2_yU6Nf18jnm5JZkecfC/view?usp=share_link).

- Here is also a screenshot of how the onboarding is displayed:
![Not now button cut off](https://github.com/mozilla-mobile/firefox-ios/assets/19226534/41d93186-7812-46c8-904f-9087781f554b)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6468)

**Comment by SoftVision-CosminMuntean** [comment]
The issue is more visible in languages that have long strings. For example on the Italian build, the "Set as Default Browser" is also cut off and is not visible. 
The issue is reproducible of the other cards if using a language that has long strings.

**Comment by adudenamedruby** [comment]
Sorry, I'm not sure I understand the issue: is the card not scrollable for you? I ran it on the simulator and the scroll worked fine, so I'm trying to identify what the actual bug is. If it's that it's cut off, then that's not a bug and is the expected design for small screen with longer/larger text.

**Comment by SoftVision-CosminMuntean** [comment]
Hi, @adudenamedruby sorry for the confusion. The card is scrollable, but looking over the [Figma](https://www.figma.com/file/7J6gh5D8DbGTExxskKdn3T/Mobile-Onboarding?type=design&node-id=6170-58775), at Device Sizes, on all devices both buttons are visible and you don't need to scroll to see the "Not Now" button, so that's why I have logged this. Here is a screenshot from the Figma doc:

![image](https://github.com/mozilla-mobile/firefox-ios/assets/19226534/d95005ac-e09a-4b3b-8723-3a9493935271)

**Comment by adudenamedruby** [comment]
ah, I see. I didn't work on this part, so I don't have full context, and the person who did is no longer here.

@piratesarereal what were the final conclusions when the dev reached out regarding this?

**Comment by Piratesarereal** [comment]
So the conversation I had was about the design of the [iPad](https://github.com/mozilla-mobile/firefox-ios/pull/13988#issue-1672906679), I haven't had a conversation about this specifically. 

As the screenshot shared by cosminmuntean from Figma, **_ideally_**, the illustration would resize to fit all the elements on the screen properly. As I do not have a phone of this size, not sure if I can test it. But by looking at the screenshot shared here, I feel extra top padding is added to the whole card compared to the designs which might be causing the issue. More specifically, the Close button is a bit lower than the designs. 

I have an iPhone SE, and on it, the card seems to have the elements spaced properly except for the bottom 3 dots component which doesn't have enough padding from the 'not now' button assuming the card has been developed to fit all the elements on the card. 
![File](https://github.com/mozilla-mobile/firefox-ios/assets/111372416/8b2a592f-d730-4808-836e-575649547a70)

**Comment by dnarcese** [comment]
@adudenamedruby no

**Comment by data-sync-user** [comment]
➤ Aarjav Pandya commented:

Roux Buciu if I tweak the illustrations such that they are the same size and dimensions, so you could export those, do you think that will help mitigate this issue?

**Comment by data-sync-user** [comment]
➤ Roux Buciu commented:

Aarjav Pandya Yes. If I have images that are all the same size, I can write a proper auto-layout thing that will fix this issue. If you do so, please keep in mind what the size of the CTD images are as well, as those will also be affected.

**Comment by data-sync-user** [comment]
➤ Aarjav Pandya commented:

Roux Buciu So each of the illustrations would not be of size 327 (W) X 318 (H) - To match the size of illustrations for the CTD campaign. To make it easier to export the correct layer. Here are the links to specific files. 
Card 1 ( https://www.figma.com/file/7J6gh5D8DbGTExxskKdn3T/Mobile-Onboarding?type=design&node-id=7864-76884&mode=design&t=gEk2ZLTKpDC6GdHz-4 )
Card 2 ( https://www.figma.com/file/7J6gh5D8DbGTExxskKdn3T/Mobile-Onboarding?type=design&node-id=7864-76830&mode=design&t=gEk2ZLTKpDC6GdHz-4 )
Card 3 ( https://www.figma.com/file/7J6gh5D8DbGTExxskKdn3T/Mobile-Onboarding?type=design&node-id=7864-76832&mode=design&t=gEk2ZLTKpDC6GdHz-4 )

**Comment by Softvision-PatriciuPop** [comment]
I've retested this and the issue is still reproducible, the second button remains partially cut off on several screen sizes. Tested using iPhone 13 mini using Firefox Beta 115.0 (32222) and 9000 (32225). As well as the latest v115 built locally using the iPhone 12 mini simulator.

**Comment by adudenamedruby** [comment]
With the way the screen is designed and built, there's no real way to fix this issue currently. I've made a note of this to be redone in #15174 in order to properly address the issue.

The big problem here is that the button gets cut off because of the privacy link's existence, but that's affected by weird padding issues that are hardcoded.
