### ISSUE TITLE
Use TelemetryWrapper in RustLogins

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#14563]
* [ ] Add relevant telemetry calls to TelemetryWrapper
* [ ] Add unit tests for new TelemetryWrapper calls
* [ ] Remove the `import Glean` in the RustLogins

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6478)

**Comment by elemanhillary** [comment]
@lmarceau is Glean replaced by TelemetryWrapper?

**Comment by lmarceau** [comment]
It's not replacing it, the `TelemetryWrapper` is just a wrapper to abstract the Glean dependency from our codebase.

**Comment by elemanhillary** [comment]
Though as i understand Storage is a static library, wouldn't this be hard to access TelemetryWrapper class.

**Comment by elemanhillary** [comment]
IMO, TelemetryWrapper should be a static lib. Tested and it worked like that, will make a WIP
