### ISSUE TITLE
Handle coordinatorBrowserViewController case in login list view controller

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#14574]
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6486)

**Comment by data-sync-user** [comment]
➤ Orla Mitchell commented:

For QA please test all password settings flows.

**Comment by DianaBarladeanu** [comment]
> ➤ Orla Mitchell commented:
> 
> For QA please test all password settings flows.

Verified as fixed on v9000 (32375) with iPhone SE (15.4).

**Comment by data-sync-user** [comment]
➤ Alina Moldovan commented:

Verified as fixed on v116 (32475) with iPhone 14+ (16.0.3)
