### ISSUE TITLE
[iPad]: "New tab opened" notification is not displayed when user opens a new web page using "Open in New Tab" option 

### ISSUE THREAD

**Issue by alinamoldovan84** [mozilla-mobile/firefox-ios#14587]
## Steps to reproduce

1. Go to cnn.com and long-tap on an article link.
2. Choose 'Open in New Tab' or "Open in New Private Tab"

### Expected behavior
"New tab opened" notification" with Switch option is displayed 

### Actual behavior
the notification is not displayed 

### Device & build information
* Device: iPad Air 3rd gen (16.3.1) 
* Build version: 114 (31217) 
* First seen version: ? 
### Notes
* This issue is not reproducing on iPhones 
* Reproducers for both normal and private browsing 

Attachments: 

https://github.com/mozilla-mobile/firefox-ios/assets/124251579/5445ac51-4e69-4186-8e9d-afe1442ab5f7

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6495)

**Comment by dnarcese** [comment]
This feels like the correct behaviour for the iPad, since you can easily switch tabs compared to the iPhone experience.
