### ISSUE TITLE
After force closing FF in order to check scroll position FF doesn't launch `only build #31207`

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/firefox-ios#14589]
## Steps to reproduce
1. Install [#31207](https://app.bitrise.io/build/cf2ac836-6ec7-4315-bcfb-1a736b43dc23).
2. Launch FF and access any article from Wikipedia.
3. Scroll to any position different from the top (default one).
4. Force close FF
5. Re-launch FF.
### Expected behavior
FF should start without problems.
### Actual behavior
After force closing FF in order to check scroll position FF doesn't launch `only build #31207`
### Device & build information
* Device: iPhone 13 Pro (15.7.1). 
* Build version: 9000 (31207) 
* First seen version: 9000 (31207) 
### Notes
@OrlaM please note that after launching the second time the position on the website was still displayed correctly.
I was not able to see any crash, no message prompt like it's when FF crashes. 
Attachments: 

https://github.com/mozilla-mobile/firefox-ios/assets/42831109/86a43536-3bf3-415c-a2e0-fa8a05e485ad

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6498)

**Comment by lmarceau** [comment]
@abodea do you have a crash log for this issue? 🙏

**Comment by abodea** [comment]
Hello, @lmarceau I'm not really sure if it's a crash or not, I'm trying to look now into the device, please note that this is linked with https://mozilla-hub.atlassian.net/browse/FXIOS-6395

**Comment by data-sync-user** [comment]
➤ Orla Mitchell commented:

Andrei Bodea Does this happen 100% of the time for you? I was unable to reproduce it using the steps provided.

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Hello, Orla Mitchellplease note that I was not able to reproduce it all the time, for example I tried again today but could not reproduce it. 

I also did some tries with updating the app but was still not able to reproduce it.

**Comment by data-sync-user** [comment]
➤ Orla Mitchell commented:

It’s possible it was fixed indirectly by another change. I’ve put it in the needs QA state, up to you if you want to keep it there to monitor or just mark it as done.
