### ISSUE TITLE
Show BackForwardList from coordinator

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#14599]
This task depends on https://github.com/mozilla-mobile/firefox-ios/issues/17624 first

For each of those points, we can have a separate PR:
- We should have a feature flag for the BackForwardList coordinator changes. 
- Either create the BackForwardList coordinator, or integrate the VC directly in the BrowserCoordinator, depending on what makes more sense after the decoupling of BVC.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6505)

**Comment by lmarceau** [comment]
Reopened since task wasn't completed yet entirely (done in two PRs)
