### ISSUE TITLE
Show QRCodeViewController from coordinator

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#14601]
Third task in the QR code coordinator epic.

Make sure the following code uses the new coordinator to show the QR code, by protecting the old code path with the feature flag (i.e. if the feature flag is OFF then we use the old code path).

* [FirefoxAccountSignInViewController](https://github.com/mozilla-mobile/firefox-ios/blob/56f95853ed47e12077bcb05f0f9813751b7f57c2/RustFxA/FirefoxAccountSignInViewController.swift#L257-L260)
* [BrowserViewController+URLBarDelegate](https://github.com/mozilla-mobile/firefox-ios/blob/56f95853ed47e12077bcb05f0f9813751b7f57c2/Client/Frontend/Browser/BrowserViewController/BrowserViewController%2BURLBarDelegate.swift#L125-L128)
* [BrowserViewController](https://github.com/mozilla-mobile/firefox-ios/blob/56f95853ed47e12077bcb05f0f9813751b7f57c2/Client/Frontend/Browser/BrowserViewController.swift#L1445-L1448)

**Notes**

* Make sure the coordinator properly deinit after the QR code view is dismissed
* Make sure if a user clicks more than once the view is shown once (ex: handled [this way](https://github.com/mozilla-mobile/firefox-ios/blob/56f95853ed47e12077bcb05f0f9813751b7f57c2/Client/Coordinators/Browser/BrowserCoordinator.swift#L379-L381) fo fakespot coordinator)
* Write unit tests for coordinator code cases (at least those)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6507)

**Comment by Mayank-84** [comment]
Hi FilippoZazzeroni, I am an external open source contributor. Do you know how I can get access to JIRA? Is it restricted to org people only?

**Comment by FilippoZazzeroni** [comment]
Hi Mayank, i'm not inside JIRA as well, i think is for organization people. I will ask once they review my PR.

**Comment by data-sync-user** [comment]
➤ Laurie Marceau commented:

For QA it can be tested that the QR code works as expected in the three following cases:

  * Using QR code from the URL bar
  * Using QR code from a long press on the application icon (from the iOS homescreen)
  * Using QR code from the onboarding to sign in to sync

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Validated on v122 (36988), with iPhone 15 (17.1).
