### ISSUE TITLE
Call ETP coordinator from browser coordinator

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#14600]
This is the third task in the coordinator ETP work. `EnhancedTrackingProtectionMenuVC` is shown from the `BrowserViewController` within the `urlBarDidTapShield` method. Let's show it from the coordinator instead.

We want to show the ETP coordinator from another coordinator, so we can keep a reference to it as a child coordinator ([example](https://github.com/mozilla-mobile/firefox-ios/blob/42e9f2debcf8e9625cf63dc6cd10c27cf2ff51bb/Client/Coordinators/Browser/BrowserCoordinator.swift#L240) with SettingsCoordinator presented from BrowserCoordinator). To do this we can add a new method on the `BrowserNavigationHandler` to show the ETP menu. 

1. Add new method on `BrowserNavigationHandler`
1. Call this method from `urlBarDidTapShield`, making sure to use the feature flag so we keep the old code in the mean time.
1. Implement the new method in BrowserCoordinator so we ask to start the ETP coordinator. This will do nothing for now since we’ll implement the action in the next task.
1. Add a unit test for this new method in BrowserCoordinator (so we assert we add the child ETP coordinator properly)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6506)

**Comment by data-sync-user** [comment]
➤ Laurie Marceau commented:

For QA it can be tested that the Enhanced Tracking Protection bottom sheet menu is appearing as expected when clicking on the lock icon in the URL bar

**Comment by DianaBarladeanu** [comment]
> Collaborator



> ➤ Laurie Marceau commented:
> 
> For QA it can be tested that the Enhanced Tracking Protection bottom sheet menu is appearing as expected when clicking on the lock icon in the URL bar

Verified as fixed on v9000 (32311) with iPhone SE (15.4).
