### ISSUE TITLE
Toolbar option is missing from settings when running automated tests

### ISSUE THREAD

**Issue by dragosb01** [mozilla-mobile/firefox-ios#14625]
## Steps to reproduce
1. Run any automated test that reaches settings (testImageOnOff)
### Expected behavior
Toolbar options should be visible between Theme and Siri Shortcuts options
### Actual behavior
Toolbar option is missing
### Device & build information

* Device: iPhone 14 Pro
* Build version: 115.0(1)
* First seen version: N/A
### Notes
This issue is not reproducing when opening the app manually on the simulator
Attachments: 
![Screenshot 2023-05-30 at 10 59 21](https://github.com/mozilla-mobile/firefox-ios/assets/134391433/2d579489-ff5a-48e9-b2df-2dd5ba2b6e07)
![Screenshot 2023-05-30 at 10 59 35](https://github.com/mozilla-mobile/firefox-ios/assets/134391433/ec31cf2d-2700-4f47-8cc6-d7473fb9e2cf)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6521)

**Comment by dnarcese** [comment]
@dragosb01 is this still an issue?

**Comment by dragosb01** [comment]
> @dragosb01 is this still an issue?

@dnarcese yes it is

**Comment by dicarobinho** [comment]
@nbhasin2 (I know it is an old implementation but maybe you have something to say here🤞)

I have started to look on this issue and found this:

<img width="843" alt="Screenshot 2024-04-09 at 15 14 53" src="https://github.com/mozilla-mobile/firefox-ios/assets/61138287/1e8cc1ab-9e33-4e59-86db-1e164c5af2f0">

It seems, this behaviour was intended and it has been pushed [here](https://github.com/mozilla-mobile/firefox-ios/pull/10019).

If I remove that condition **!AppConstants.isRunningUITests**, Toolbar option is also visible for the UnitTests.

cc: @dragosb01 @dnarcese

**Comment by data-sync-user** [comment]
➤ Alexandru Farcasanu commented:

Should be verified by Dragos Bigu

**Comment by dragosb01** [comment]
Issue fixed
