### ISSUE TITLE
In landscape, if the Zoom Bar is on the screen and the url Bar is at the bottom, the height of the url bar shoudn't be adjusted

### ISSUE THREAD

**Issue by PARAIPAN9** [mozilla-mobile/firefox-ios#14651]
## Steps to reproduce
1. Make sure landscape mode is enabled
1. Set url Bar to the bottom
1. Open setting and tap Zoom
1. Turn the phone in ladscape
### Expected behavior
The url Bar height should not be adjusted
### Actual behavior
The url Bar is adjusted
### Device & build information

* Device: iPhone 13, iOS 16.0

### Notes
Attachments: 
![photo](https://github.com/mozilla-mobile/firefox-ios/assets/51127880/cd549758-c6a8-4380-9e4b-536b9ac6fcec)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6538)

**Comment by cpeterso** [comment]
@PARAIPAN9 , can this issue be closed? Your PR looks like it has been merged: https://github.com/mozilla-mobile/firefox-ios/pull/14652

**Comment by data-sync-user** [comment]
➤ Sorin Paraipan commented:

Yes
