### ISSUE TITLE
Lingering background gradient on scroll in Zoom Feature along with some other bugs 

### ISSUE THREAD

**Issue by Piratesarereal** [mozilla-mobile/firefox-ios#14666]
Hey @PARAIPAN9 @dnarcese @adudenamedruby , I was able to test the released version of the zoom feature and there are still some issues with the implementation.

**// When the zoom component is at the TOP**
- When I scroll slowly, the gradient is still sticking to the bottom.
    [Top_Address Bar.webm](https://github.com/mozilla-mobile/firefox-ios/assets/111372416/656e1606-c7d6-4799-a131-3d287c1fb3d8)

**// When the zoom component is at the BOTTOM**
- When I scroll slowly, the gradient is still sticking to the bottom.
- When looking at the screen, from Top->Bottom, the order of components should be Zoom Component - Address Bar - Tab bar and not Address bar - Zoom Component- Tab bar. I have added the designs [here](https://www.figma.com/file/dIdFRmA0yACjkam2mb8eGq/Page-Zoom?type=design&node-id=3525-26193&t=0qJaRI2himwt3mCW-4). 
- When scrolling the Address bar seems to move faster than the bottom zoom and tab bar component. All 3 components move simultaneously.
    [Bottom_Address Bar.webm](https://github.com/mozilla-mobile/firefox-ios/assets/111372416/d98290b3-ead3-439f-aea5-62a627df525c)
    
This comment was also shared in this [ticket](https://github.com/mozilla-mobile/firefox-ios/pull/14328#issuecomment-1570719397).

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6550)

**Comment by adudenamedruby** [comment]
@Piratesarereal and @dnarcese and @PARAIPAN9 , I think there might need to be a meeting setup to get some alignment on how to resolve some of the things - specifically, the toolbar animation and positioning at the bottom. Given that there's some engineering issues around the toolbar, we should agree what the solution is from a design/PM/engineering perspective, before we go ahead and implement anything, just so we're all aligned.

Maybe add me as an optional invite to that meeting. :)
