### ISSUE TITLE
'Autofill Credit Cards' position in settings incorrect

### ISSUE THREAD

**Issue by jeffreygee** [mozilla-mobile/firefox-ios#14686]
## Steps to reproduce
Open Settings / 

### Expected behavior
Location in settings should be positioned under Passwords and above Data Management. 

### Actual behavior
Currently positioned below Data Management

### Device & build information
* Device: iPhone 12 Pro / 16.4.1
* Build version: 31246
* First seen version: 
### Notes
Attachments: 
<img width="322" alt="Screenshot 2023-06-01 at 4 11 13 PM" src="https://github.com/mozilla-mobile/firefox-ios/assets/93741573/d38cf3a8-91fa-45a0-939e-3e118cf1062e">

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6559)

**Comment by nbhasin2** [comment]
Fixed here: https://github.com/mozilla-mobile/firefox-ios/pull/14679

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Verified as fixed on v9000 (31546) with iPhone 13 Pro (15.7.1).

To be checked when official v115 will be created containing this fix.
