### ISSUE TITLE
Update credit card logo sizes to 48x48

### ISSUE THREAD

**Issue by jeffreygee** [mozilla-mobile/firefox-ios#14693]
## Steps to reproduce
1. Add a card and save

### Expected behavior
Credit card icons displayed at 48x48

### Actual behavior
Credit card icons currently displayed at 24x24

### Device & build information
* Device: iPhone 12 Pro / 16.4.1
* Build version: 31246

### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6565)

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Verified as fixed on v9000 (31606) with iPhone 13 Pro (15.7.1).

To be checked when official v115 will be created containing this fix.
