### ISSUE TITLE
Blank toast appearing when viewing/editing cards

### ISSUE THREAD

**Issue by jeffreygee** [mozilla-mobile/firefox-ios#14690]
## Steps to reproduce
1. Go to Autofill Credit Cards
2. Add a card with (+) button
3. Hit 'Close' instead of adding a card

### Expected behavior
Would go back to previous page, no toast necessary

### Actual behavior
Empty blue toast appears

### Device & build information
* Device: iPhone 12 Pro / 16.4.1
* Build version: 31246

### Notes
Attachments: 
<img width="226" alt="Screenshot 2023-06-01 at 4 26 28 PM" src="https://github.com/mozilla-mobile/firefox-ios/assets/93741573/6d4a549d-76f1-4fdf-98de-eee162a7cebd">

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6563)

**Comment by nbhasin2** [comment]
Fixed here: https://github.com/mozilla-mobile/firefox-ios/pull/14679

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Verified as fixed on v9000 (31641) with iPhone 13 Pro (15.7.1).

To be checked when the official v116 official version will be sent to QA
