### ISSUE TITLE
Error state on credit card number/expiration validation

### ISSUE THREAD

**Issue by jeffreygee** [mozilla-mobile/firefox-ios#14691]
## Steps to reproduce
1. Go to Autofill Credit Cards
2. Hit the (+) to add a card
3. Start typing in the credit card or expiration fields

### Expected behavior
When a user taps out of the field before meeting requirements, trigger error state. 

### Actual behavior
Errors appear right away with any tapping, before the user has a chance to finish entering data. This is super disruptive as a user experience, has accessibility issues. 

### Device & build information
* Device: iPhone 12 Pro / 16.4.1
* Build version: 31246

### Notes
Attachments: 
<img width="922" alt="Screenshot 2023-06-01 at 4 29 52 PM" src="https://github.com/mozilla-mobile/firefox-ios/assets/93741573/2435c8af-ce32-496a-b00f-090a01ca85e8">

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6564)

**Comment by data-sync-user** [comment]
➤ Nishant Bhasin commented:

Stefan Vladut since you are running low on tickets, want to take this on?

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Verified as fixed on v116 (32820) with iPhone 13 Pro (15.7.1).
