### ISSUE TITLE
Expiration date is not in correct format on the saved cards list

### ISSUE THREAD

**Issue by jeffreygee** [mozilla-mobile/firefox-ios#14692]
## Steps to reproduce
1. Add a credit card and save

### Expected behavior
User sees Expiration date in proper MM/YYYY format 

### Actual behavior
Current format is YY instead of MM / YYYY

### Device & build information
* Device: iPhone 12 Pro / 16.4.1
* Build version: 31246

### Notes
Attachments: 
<img width="433" alt="Screenshot 2023-06-01 at 4 31 12 PM" src="https://github.com/mozilla-mobile/firefox-ios/assets/93741573/d38ab08f-31bd-4e8d-bc71-57e2a4c9ab3e">

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6566)

**Comment by nbhasin2** [comment]
fixed here: https://github.com/mozilla-mobile/firefox-ios/pull/14679

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Verified as fixed on v9000 (31836) with iPhone 13 Pro (15.7.1).

This issue will be also checked when the official build for v116 will be sent to QA.
