### ISSUE TITLE
Update dark mode theming in Autofill Credit Cards Settings

### ISSUE THREAD

**Issue by jeffreygee** [mozilla-mobile/firefox-ios#14694]
## Steps to reproduce
1. Turn device mode into Dark Mode
1. Go to Autofill Credit Cards

### Expected behavior
1. Default credit card icon displaying as black instead of Dark mode color, and not very visible
1. The ‘Close’, 'Cancel’, ‘Edit’, and ‘Save’ actions on Dark Mode are not using the Dark Mode color.

### Actual behavior
1. Icon displayed in dark mode icon color
1. Link texts are using dark mode theming.
1. Disabled link texts updated to 'TextDisabled' 

### Device & build information
* Device: iPhone 12 Pro / 16.4.1
* Build version: 31246

### Notes
Attachments: 
Link texts:
![](https://github.com/mozilla-mobile/firefox-ios/assets/93741573/f39c7ad5-e8cd-45d9-9b1e-c60c6cec282a)

Dark icon:
![](https://github.com/mozilla-mobile/firefox-ios/assets/93741573/1b591315-29dc-4ccd-9cb0-8f995f487c09)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6567)

**Comment by nbhasin2** [comment]
Fixed here: https://github.com/mozilla-mobile/firefox-ios/pull/14679

Note: The card for `visa` small icon will get fixed in another ticket as that might require a new icon or us changing how we handle template image color
