### ISSUE TITLE
URLBar/toolbar colors doesn't follow night mode as rest of the app

### ISSUE THREAD

**Issue by lmarceau** [mozilla-mobile/firefox-ios#14727]
## Steps to reproduce
1. Click "Turn on Nightmode"
2. Observe the color of the URL bar/tool bar. 

### Expected behavior
URLBar and toolbar should follow the dark mode theme when night mode is ON, like the rest of the app.

### Actual behavior
The toolbar/URL bar color is inverted than the rest of the app

### Device & build information
* Device: Simulator iPhone 14 iOS 16.4
* Build version: c2ff742d13295806f85c7d949be5febe47bc78c1, but this will be on v115 if not fixed
* First seen version: 115

### Notes
Attachments: 
![Simulator Screenshot - iPhone 14 - 2023-06-05 at 10 15 24](https://github.com/mozilla-mobile/firefox-ios/assets/11338480/4fb0a473-b78d-4315-91ed-3ed840355bd4)
![Simulator Screenshot - iPhone 14 - 2023-06-05 at 10 16 20](https://github.com/mozilla-mobile/firefox-ios/assets/11338480/4480f809-cfa3-402d-ab5b-8de1207ff155)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6582)

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Verified as fixed on v115 (31736) with iPhone 13 Pro (15.7.1).
