### ISSUE TITLE
A synced CC from the desktop is not valid as the expiration date is not valid

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/firefox-ios#14747]
## Preconditions
Save a few credit cards on the desktop Firefox.

## Steps to reproduce
1. Launch FF and perform a sync.
1. Access the Autofill CC section.
1. Check the synced cards.

### Expected behavior
The expiration date should be correctly displayed.

### Actual behavior
A synced CC from the desktop is not valid as the expiration date is not valid.

### Device & build information
* Device: iPhone 13 Pro (15.7.1). 
* Build version: 9000 (31461). 
* First seen version: N/A 
    1. Notes
@nbhasin2 Please note that when saving a CC on FF for desktop the Expiration date is in this format MM / YY `04 / 2030` but on iOS is MM / YY `04 / 23`.
Please note that if I sync a CC saved on iOS, on the desktop CC section it will be displayed with 04 / 23, instead of 04 / 203 so probably a sync with the desktop team to decide wich way is correct might help.
Attachments: 

![IMG](https://github.com/mozilla-mobile/firefox-ios/assets/42831109/fdf267c2-d3a8-4afd-ab1c-97598071f2ca)UNITO-UNDERSCORE!0379!
![image](https://github.com/mozilla-mobile/firefox-ios/assets/42831109/1bfcd6e1-bfe7-4de5-8ab6-83d600cb1c56)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6588)

**Comment by DianaBarladeanu** [comment]
Verified as fixed on v116 (32873) with iPhone SE (16.5).
