### ISSUE TITLE
There is an empty blue pop-up at the bottom when doing any action in CC section

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/firefox-ios#14743]
## Steps to reproduce
1. Launch FF and access the Autofill CC section.
1. Perform any action like: 

* Tap on the `+` button and then cancel
* Tap on any saved card and then close.
* or any other action in the CC section.
    1. Expected behavior
A concrete message should be displayed at the bottom not only an empty blue pop-up.
    1. Actual behavior
A blue pop-up is displayed at the bottom.
    1. Device & build information
* Device: iPhone 13 Pro (15.7.1). 
* Build version: 9000 (31461). 
* First seen version: N/A 
    1. Notes
Attachments: 

https://github.com/mozilla-mobile/firefox-ios/assets/42831109/941f7c81-51f7-433e-8d2c-53b79284ad80

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6585)

**Comment by nbhasin2** [comment]
This should be fixed in the main / v116 branch

**Comment by DianaBarladeanu** [comment]
Verified as fixed on v116 (32873) with iPhone SE (16.5).
