### ISSUE TITLE
"Missing parameter: client_id" error message is displayed when user tries to access account management page

### ISSUE THREAD

**Issue by alinamoldovan84** [mozilla-mobile/firefox-ios#14775]
## Steps to reproduce
1. Fresh install the FF app 
2. Log into the FF with a valid account 
3. Navigate to settings and open the account management page 
4. Enter the FxA password and sign in 

### Expected behavior
User is correctly signed into the account management page  

### Actual behavior
"Missing parameter: client_id" error message is displayed. Login works correctly if user navigates back and retries to access the account management page.  

### Device & build information
* Device: iPhone 14+ (16.0.3), iPad Air 3rd Gen (16.3.1) 
* Build version: V115 (31516) 
* First seen version: ?

 
### Notes
Attachments: 

https://github.com/mozilla-mobile/firefox-ios/assets/124251579/092bf783-98a3-4192-8f2c-64dabad971e7

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6601)

**Comment by quinnaissance** [comment]
Had the same issue here.

- Device: iPhone 11 Pro Max (16.3.1)
- Build version: 114.3 (31916)

Seemed to be fixed after disconnecting then reconnecting Sync.

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v9000(33889), with iPhone SE (16.5).
