### ISSUE TITLE
There is a gap between the gradient shadow and the `urlBar` when rotating in landscape mode

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/firefox-ios#14774]
## Steps to reproduce
1. Launch FF and access any webpage.
2. Open Zoom Bar.
3. Rotate the device in landscape mode.
### Expected behavior
Observe the gap between the gradient shadow and the URL bar.
### Actual behavior
There is a gap between the gradient shadow and the `urlBar` when rotating in landscape mode.
### Device & build information
* Device: iPhone 13 Pro (15.7.1). 
* Build version: 9000 (31518). 
* First seen version: 9000 (31518).
### Notes
Please note that this occurs only if adding the Zoom bar while being in portrait mode and then when rotating to landscape the issue occurs. If opening the zoom bar while in landscape mode, it doesn't occur.
I was able to reproduce only on iOS 15.x.x but not on 16.x.x
Attachments: 

https://github.com/mozilla-mobile/firefox-ios/assets/42831109/d08574e0-b824-465c-ab90-66167ba45b83

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6600)

**Comment by data-sync-user** [comment]
➤ Alina Moldovan commented:

verified this issue using v116 (16.0.3) and iPhone 14+ (16.0.3). 

Not able to reproduce this issue anymore. 

!Skype_Video31.mp4|width=888,height=1920!
