### ISSUE TITLE
"Added to shortcuts" toast message not visible/partially visible after user adds bookmark to shortcuts

### ISSUE THREAD

**Issue by DianaBarladeanu** [mozilla-mobile/firefox-ios#14776]
**Steps to reproduce**

1. Fresh install the FF app
2. Log into the FF with a valid account
3. Have several bookmarks and several folders synced on FxA
4. Long press on a bookmark to open context menu
4. Choose a bookmark title, tap on "Add it to shortcuts" and observe

**Expected behavior**
A toast notification should be displayed on the bottom page informing that the bookmark was "added to shortcuts"

**Actual behavior**
Only a margin of the toast notification is visible or is completely missing.

**Device & build information**
- Device: iPhone SE (15.4.1)
- Build version: V115 (31516)
-  First seen version: ? 

**Notes**

https://github.com/mozilla-mobile/firefox-ios/assets/133357955/fc66ac73-b3bb-47cc-8b67-ba844651d545

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6602)

**Comment by data-sync-user** [comment]
➤ Alina Moldovan commented:

validated this issue using FF v 116 (32373) and iPhone 14+ (16.0.3). The issue doesn’t reproduce anymore.
