### ISSUE TITLE
Handle ShareExtensionHelper from library with coordinator

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#14785]
There’s now a Share extension coordinator done from epic [https://mozilla-hub.atlassian.net/browse/FXIOS-6847](https://mozilla-hub.atlassian.net/browse/FXIOS-6847|smart-link)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6609)

**Comment by lucas3332** [comment]
You can get help by this post [bgmi latest update](https://modlonely.com/bgmi-apk/)

**Comment by lmarceau** [comment]
Was done in #15863
