### ISSUE TITLE
Handle RecentlyClosedTabsPanel from library with coordinator

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#14784]
Shown from History panel

Present from coordinator instead of VC

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6608)

**Comment by data-sync-user** [comment]
➤ Razvan Litianu commented:

I was taking a look at the LibraryViewController today and try to understand how panels are handled. It looks like the LibraryViewController is embedded inside a UINavigationController (our router), but every panned is added a child view controller and is held by a LibraryPanelDescriptor which holds both the panel view controller (in our case HistoryPanel) and another UINavigationController. 

So the conclusion is every panel has it’s own UINavigationController and it does not play well with the Coordinator Router architecture. Presenting Recently Closed Tabs from LibraryCoordinator will use and push from it’s own router.

Unless we have a coordinator for every panel? With its own Router? Seems a bit of an overhead.

I’m curious what you think Laurie Marceau. 

+-------------------------+
 UINavigationController     +-------------------------+
↓

+------------------------+
 LibraryViewController     +------------------------+
↓

+-----------------------+
 LibraryPanelDescriptor +-----------------------+
↓

+----------------+------------------+
 HistoryPanel   UINavigationController +----------------+------------------+

**Comment by data-sync-user** [comment]
➤ Laurie Marceau commented:

Mh, yeah as you explained it sounds like each panel needs its own coordinator. Each of them would be really small from what I understand, so I don’t see this as an issue. It also enables showing different subviews from panels more easily.

**Comment by FilippoZazzeroni** [comment]
Solving PRS #15654 #15824 #15863 #15959

**Comment by data-sync-user** [comment]
➤ Laurie Marceau commented:

For QA it can be tested the Recently closed tab in history panel works as expected.

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v118(33767) with iPhone SE (16.5)
