### ISSUE TITLE
Theme problem; Top URL bar has a gray line that disappears

### ISSUE THREAD

**Issue by lmarceau** [mozilla-mobile/firefox-ios#14788]
## Steps to reproduce
- Be in dark mode, with URL bar at the top
- Open the app on a homepage

### Expected behavior
The URL bar theme shouldn't have a light gray line under it

### Actual behavior
It has a light gray line, which disappears when we interact with the URL bar

### Device & build information
* Device: iPhone 11
* Build version: v115 31516
* First seen version: v115
### Notes
Attachments: 
![IMG_1349](https://github.com/mozilla-mobile/firefox-ios/assets/11338480/6b7d758e-eaec-4a56-be47-d0af7a270c54)

https://github.com/mozilla-mobile/firefox-ios/assets/11338480/3ad88e97-1916-4700-814e-170167535f6c

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6611)

**Comment by lmarceau** [comment]
I assumed we don't want that gray line, but to be confirmed. Either it stays there and it's consistent, or it's never there? cc @cwzilla

**Comment by lmarceau** [comment]
There's potentially two problems here:
1. The line disappears when it shouldn't? Do we want that line or not?
2. Is the color proper in light & dark mode? The color seems off in dark mode?

![Screenshot 2023-06-12 at 4 37 07 PM](https://github.com/mozilla-mobile/firefox-ios/assets/11338480/d5e17f47-c144-4772-a45a-ce86eac40fc1)
![Screenshot 2023-06-12 at 4 37 30 PM](https://github.com/mozilla-mobile/firefox-ios/assets/11338480/a464ab84-4aed-45ea-82f9-35e71b016702)

**Comment by cwzilla** [comment]
I think we want to keep the line for some separation. The dark mode screenshot looks a bit off though, it should be a bit more subtle.

In Figma, I used a 0.5px line with borderPrimary applied. Here's the reference: [Light](https://www.figma.com/file/K9m9aQx40RmWnXnIc1GDeQ/iOS-%26-iPad-UI?type=design&node-id=824%3A89020&t=jXMWoNrqHbL9yA7I-1), [Dark](https://www.figma.com/file/K9m9aQx40RmWnXnIc1GDeQ/iOS-%26-iPad-UI?type=design&node-id=824%3A89020&t=jXMWoNrqHbL9yA7I-1)

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Verified as fixed on v116 (32373) with iPhone 13 Pro (15.7.1).

Laurie Marceau The line looks different and better, can you confirm this is the fix we wanted?

!image0 (6).png|width=1125,height=2436!

!image1 (2).png|width=1125,height=2436!

!image3.png|width=1125,height=2436!

!image2.png|width=1125,height=2436!

**Comment by data-sync-user** [comment]
➤ Alina Moldovan commented:

Validated this issue using FF v116 (32373) and iPhone 16+ (16.0.3)

The grey line is present for all cases: toolbar is set at the top or at the bottom, theme is light  or dark. The line persists when user interacts with the URL bar
