### ISSUE TITLE
Handle LoginsSetting in coordinator

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#14796]
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6616)

**Comment by data-sync-user** [comment]
➤ Orla Mitchell commented:

For QA please verify the passwords list and it’s onboarding screen work as expected.

**Comment by DianaBarladeanu** [comment]
> ➤ Orla Mitchell commented:
> 
> For QA please verify the passwords list and it’s onboarding screen work as expected.

Tested as instructed above, no issues encountered.
Device: iPhone SE (15.4)
Build: v9000 (32297)

**Comment by data-sync-user** [comment]
➤ Alina Moldovan commented:

Verified as fixed on v9000 (32297) with iPhone SE (15.4).
Tested as instructed above.
