### ISSUE TITLE
When in Private Browsing Mode, the hamburger menu option to open a new private tab should be named "New Private Tab" 

### ISSUE THREAD

**Issue by alinamoldovan84** [mozilla-mobile/firefox-ios#14807]
## Steps to reproduce
1. Make sure you are in Private Browsing Mode
1. Open the hamburger menu and check the option naming

### Expected behavior
"New private tab" option should be present instead of "New Tab" 
Please note that the "New Tab" option opens a private tab (please see [FXIOS-6234](https://mozilla-hub.atlassian.net/browse/FXIOS-6234)). Also the naming should be consistent with the tabs tray context menu (Please see the screenshots). 

### Actual behavior
"New tab" option is present 

### Device & build information
* Device: iPhone 14+ (16.0.3) & iPad Air 3rd Gen (16.3.1) 
* Build version: v115 (31516)  
* First seen version: ? 
### Notes
Attachments: 

![Skype!UNITO-UNDERSCORE!Picture!UNITO-UNDERSCORE!12](https://github.com/mozilla-mobile/firefox-ios/assets/124251579/43c384b5-8eb4-43b4-acfe-253cd2253ffc)
![Skype!UNITO-UNDERSCORE!Picture!UNITO-UNDERSCORE!13](https://github.com/mozilla-mobile/firefox-ios/assets/124251579/df3577df-0952-4807-a2e9-058f2a2900ef)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6621)

**Comment by swantanbarua** [comment]
Hi. Since no one's assigned in this issue, can I work on this?

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Validated on v9000 (43238), with iPhone 15 (17.5).

!ImportedPhoto.741794121.346304.jpeg|width=1179,height=2556,alt="ImportedPhoto.741794121.346304.jpeg"!

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Validated on v129 (43354), with iPhone 15 (17.5).
