### ISSUE TITLE
The `Add/Update/Remove` CC toast has a weird animation when fading

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/firefox-ios#14810]
## Preconditions
Have some CC saved.

## Steps to reproduce
1. Launch FF and access the CC.
2. Attepmt to: 
 - Add a credit card
 - Update credit card
 - Remove credit card

### Expected behavior
The toast should smoothly disappear/fade.
### Actual behavior
The `Add/Update/Remove` CC toast has a weird animation when fading.
### Device & build information
* Device: iPhone 13 Pro (15.7.1). 
* Build version: 9000 (31461). 
* First seen version: N/A 
### Notes
Please note this occurs for all 3  `Add/Update/Remove` toat's.
Attachments: 

https://github.com/mozilla-mobile/firefox-ios/assets/42831109/8328af02-998c-41ff-82fd-73936452217b

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6624)

**Comment by data-sync-user** [comment]
➤ Sorin Paraipan commented:

This issue was addressed inhttps://mozilla-hub.atlassian.net/browse/FXIOS-6602 ( https://mozilla-hub.atlassian.net/browse/FXIOS-6602|smart-link )

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Verified as fixed on v9000 (32311) with iPhone 13 Pro (15.7.1).
