### ISSUE TITLE
Investigate placement of back/forward arrows in URL bar

### ISSUE THREAD

**Issue by Piratesarereal** [mozilla-mobile/firefox-ios#14818]
Hey @nbhasin2 @dnarcese,

I am creating this ticket to investigate issues with placing a back & forward arrow to the URL bar like [this](https://www.figma.com/file/8fsCvtnweBkWGZ9NfL907l/Mobile-IA?type=design&node-id=2509-63604&t=lw1aN03Cqi24I9Gd-4). 

Nishant mentioned there are potentially 2 issues: 

* Security Issues (Higher Risk) 
* Usability Issues (Lower Risk) 

Just wanted to check, if it is feasible to place them in the URL bar for a potentially better experience or if is something we shouldn't consider.

┆Issue is synchronized with this [Jira Spike](https://mozilla-hub.atlassian.net/browse/FXIOS-6626)

**Comment by data-sync-user** [comment]
➤ Laurie Marceau commented:

I think this can be closed considering the document was done here ( https://docs.google.com/document/d/1TcKljBNUke5RxZSnwc6kvbC-BTz4xtDH9zYx2kZtHZI/edit )?

**Comment by data-sync-user** [comment]
➤ Nishant Bhasin commented:

Laurie Marceau Yes, marking this as done
