### ISSUE TITLE
Theming System - Light Mode -  URL Bar buttons don't change their color when they are tapped 

### ISSUE THREAD

**Issue by alinamoldovan84** [mozilla-mobile/firefox-ios#14862]
## Steps to reproduce
1. Fresh install the FF app while device is in Light mode
2. Open a web page
3. Tap on the tabs tray button

### Expected behavior
A visual feedback should be in place for the user to mark his/her gesture. Also the behavior should be consistent with the dark mode were the visual feedback is in place (please see the attached videos)  

### Actual behavior
No visual feedback is displayed on buttons tapping  

### Device & build information
* Device: iPhone 14+ (16.0.3) 
* Build version: 115 (31602) 
* First seen version: ? 
### Notes
- same issue reproduces for private browsing 
- issue reproduces for both toolbar display on top or on bottom of the page 

### Attachments: 

https://github.com/mozilla-mobile/firefox-ios/assets/124251579/5d4a7041-00fc-4a5c-84e7-6e93b2d0d60c

https://github.com/mozilla-mobile/firefox-ios/assets/124251579/bfe7faa9-0c46-4bf4-9294-d86ef178a6de

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6650)

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Verified as fixed on v116 (32373) with iPhone 13 Pro (15.7.1).
