### ISSUE TITLE
The iOS Re-engagement Notifications are not displayed on iOS simulator

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla-mobile/firefox-ios#14866]
**[Affected versions]:**

* Firefox Nightly 116.0 (1)

**[Affected Platforms]:**

* iOS 16.4

**[Prerequisites]:**

* Have "Xcode" installed on your device.
* Have the iOS simulator opened.
* Have the latest Firefox Nightly installed on the IOS simulator.

**[Steps to reproduce]:**

1. Open the browser and tap the hamburger menu button from the bottom-right part of the screen.
1. Select the "Settings" option and scroll down to the bottom part of the menu.
1. Tap the "Firefox 116.0 (1)" option 5 times.
1. Scroll down to the "Debug" section and select the "Experiments" option.
1. Tap the "Release iOS re-engagement notifications A/B experiment 114" experiment and select any treatment branch.
1. Send the Firefox app to the background.
1. Change the system time to 2 days and 2 minutes in the future.
1. Observe the behavior.

**[Expected result]:**

* A notification is triggered.

**[Actual result]:**

* No notifications are triggered.

**[Notes]:**

* This issue blocks us from testing the “[QA-1886] Feature configuration testing for notifications on iOS” request as we cannot trigger any notifications on an iOS simulator. We are trying to test this feature configuration on an iOS simulator because we cannot test recipes created on the “Stage” environment using a physical device.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6654)

**Comment by thatswinnie** [comment]
This is not a bug. Apple's background fetch which the re-engagement notification is based on is not running in simulator. This can only be tested on device.
