### ISSUE TITLE
Can't scroll suggested search results after typing in location bar

### ISSUE THREAD

**Issue by jonoflayham** [mozilla-mobile/firefox-ios#14878]
## Steps to reproduce
Open Firefox.  Tap in the location bar.  Type **news**.  Observe a list of suggested web sites in both the 'Google search' section and the 'Firefox Suggest' section.  Drag the list up in an attempt to to see more.

### Expected behavior
The list of entries should scroll, then allow an entry to be chosen by tapping it.

### Actual behavior
No scrolling happens; both lists of web sites disappear, and the display is taken back to the state it was in before you typed **news**

### Device & build information
* Device: iPhone 14 Pro Max, iOS 16.5
* Build version: Firefox 114.1 (31594)
* First seen version: I believe I first noticed this at version 112, but it may have been earlier.
### Notes
Attachments: 

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6657)

**Comment by mihaitabamburic** [comment]
I also have this issue and it is incredibly frustrating from an UX perspective
It is a bug introduced more recently, because I remember this functionality working fine in a previous version (which one that is I do not recall)

**Comment by elemanhillary** [comment]
I tested this, and it seems its no longer happening

**Comment by jonoflayham** [comment]
Still a problem for me on Firefox 115.1 (32781) / IOS.

**Comment by elemanhillary** [comment]
update to 116 and see if it persists

**Comment by jonoflayham** [comment]
Sure, will do. 116 not yet being offered to me through App Store updates.

**Comment by jonoflayham** [comment]
Hooray!  116 has landed for me, and the issue has been fixed; can scroll
through suggestions with repeated scroll actions, and choose the desired
entry when it appears.

**Comment by elemanhillary** [comment]
Then mark it closed @jonoflayham

**Comment by edmondburnett** [comment]
This seems to be a regression in 139.1.
