### ISSUE TITLE
Theming System -  URL Bar - Switching from dark to light mode from FF setting doesn't take effect immediately

### ISSUE THREAD

**Issue by alinamoldovan84** [mozilla-mobile/firefox-ios#14882]
## Steps to reproduce
1. Fresh install the FF app while device is in Light mode
1. Open a web page
1. Navigate to FF settings -> Theme ~~> Manually~~ > Dark mode 
1. Check the URL Bar behavior 

### Expected behavior
The URL Bar theme changes to dark mode immediately

### Actual behavior
The URL Bar theme remains in light mode until a new action is performed

### Device & build information
* Device: iPhone 14+ (16.0.3) 
* Build version: v115 (31643) 
* First seen version: ? 
    1. Notes
The same issue reproduces when switching from Dark to Light mode

### Attachments: 

https://github.com/mozilla-mobile/firefox-ios/assets/124251579/1692f3ec-74a5-4b35-876b-e8ff4dd77486

https://github.com/mozilla-mobile/firefox-ios/assets/124251579/7d909bc5-6fc9-4245-9b7b-8e0416a40392

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6658)

**Comment by lmarceau** [comment]
I think this relates to https://github.com/mozilla-mobile/firefox-ios/issues/14727

**Comment by data-sync-user** [comment]
➤ Laurie Marceau commented:

Putting this in QA needed as I think this should be fixed by now by other theming tickets that were done in that area.
