### ISSUE TITLE
Credit cards aren't showing the correct updated values for update bottom sheet flow

### ISSUE THREAD

**Issue by nbhasin2** [mozilla-mobile/firefox-ios#14911]
## Steps to reproduce
- Save credit card using regular bottom sheet by checking out a purchase 
- Perform another purchase but this time change the expiry date so that we get an update flow

### Expected behavior
- Update flow should show newly updated values for expiry date by still keeping old card number

### Actual behavior
- Update flow shows old date 

### Device & build information
* Device: iPhone 11 pro
* Build version: v9000 (31690)
* First seen version: v9000 (31690)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6679)

**Comment by abodea** [comment]
I can still reproduce this issue and when updating the expiration date I don't even have the update card prompt anymore...

https://github.com/mozilla-mobile/firefox-ios/assets/42831109/1c7140ae-68f4-4cea-8e7b-f3c1dbd9ca3a

**Comment by nbhasin2** [comment]
@abodea I tried again and am getting the prompt plus the update

https://github.com/mozilla-mobile/firefox-ios/assets/8919439/14164f39-b895-4070-ab4f-46d9edc442f9

I am on latest `main` with commit 21346890d53df14451407cb7681d3bdb29edf993

**Comment by abodea** [comment]
Hello, @nbhasin2 I'm not really sure but on v116 (32820) with iPhone 13 Pro (15.7.1) the CC is still not updated. 

https://github.com/mozilla-mobile/firefox-ios/assets/42831109/f6f2a2cd-ec0c-41d3-95c6-30bd09d744ee

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Verified as fixed on 116.0 (32958) with iPhone 13 Pro (15.7.1).
