### ISSUE TITLE
New Tap settings is not correctly aligned in RTL locale (ar)

### ISSUE THREAD

**Issue by aalaaeid** [mozilla-mobile/firefox-ios#14918]
## Steps to reproduce
1. Set the language to AR.
1. Launch FF and open menu ~~> Settings~~ > New Tab
1. Observe the Custom URL position (if a custom url is typed in; if not, type in a custom url)

### Expected behavior
The position of the Custom URL  should be aligned with the rest of the options on the screen.

### Actual behavior
The Custom URL is not correctly aligned in RTL locale (ar).

### Device & build information
* Device:  iPhone 11
* Build version: v114.1 (31594)
* First seen version: N/A

*# 
*## Notes
Attachments: 
![width=200,height=183](https://github.com/mozilla-mobile/firefox-ios/assets/37640295/bed7ad98-67f8-4515-9ac9-1b0ec0a5ed80)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6684)

**Comment by data-sync-user** [comment]
➤ Roux Buciu commented:

For testing, please check the STR.

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Validated on v9000 (37808), with iPhone 15 (17.0).

To be rechecked once the official v123 build is released.

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v123 (38000), with iPhone SE (16.0).
