### ISSUE TITLE
Search is not correctly aligned in RTL locale (ar) 

### ISSUE THREAD

**Issue by aalaaeid** [mozilla-mobile/firefox-ios#14919]
## Steps to reproduce
1. Set the language to AR.
1. Launch FF
1. Tap search
1. Observe the text alignment of search.

### Expected behavior
The position of the Search should be Correctly aligned to the right.

### Actual behavior
The position of the Search is not correctly aligned in RTL locale `(ar)`.

### Device & build information
* Device: iPhone 11
* Build version: v114.1 (31594)
* First seen version: N/A
### Notes
Attachments: 

![IMG!UNITO-UNDERSCORE!8799](https://github.com/mozilla-mobile/firefox-ios/assets/37640295/c8e4accb-4f60-471d-a418-30b8a3e771d7)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6685)

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v122 (37175), with iPhone 15 (17.1).
