### ISSUE TITLE
Add Search Engine is not correctly aligned in RTL locale (ar)

### ISSUE THREAD

**Issue by aalaaeid** [mozilla-mobile/firefox-ios#14917]
## Steps to reproduce

1. Set the language to AR.
2. Launch FF and open menu -> settings -> Search
3. Add Search Engine
4. Observe the text alignment of placeholders.

### Expected behavior

The text alignment of placeholders should be the same as they appear in LTR locale.

### Actual behavior

The text alignment of placeholders are not correctly aligned in RTL locale (ar).

### Device & build information
* Device: iPhone 11
* Build version: v114.1 (31594)
* First seen version: N/A
### Notes
Attachments: 
![IMG_8816](https://github.com/mozilla-mobile/firefox-ios/assets/37640295/edf84d89-a990-431a-8a7a-cb8163e511d7)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6683)

**Comment by purifier1990** [comment]
Hi firefox owners
I'm new joined this repo and just raised a PR today for this, have read the PR guideline and code guideline, no idea if that meets the requirement, let me know if this works, thanks!

**Comment by lmarceau** [comment]
@purifier1990 Thank you for the PR! It will get reviewed shortly by one of my colleagues 🙌

**Comment by data-sync-user** [comment]
➤ Alina Moldovan commented:

Validated as fixed using FF v116 (32475) and iPhone 14+ (16.0.3) and iPad Air 3rd Gen (16.3.1) 

!Skype_Picture_17.jpeg|width=428,height=926!
