### ISSUE TITLE
Bookmarks arrow direction is not correctly directed  in RTL locale (ar)

### ISSUE THREAD

**Issue by aalaaeid** [mozilla-mobile/firefox-ios#14926]
## Steps to reproduce

1. Set the language to AR.
2. Launch FF -> menu
3. Tap Bookmarks
4. Observe the arrow direction of Bookmarks.

### Expected behavior
The direction of the arrow should be to the left.

### Actual behavior
The direction of the arrow is not correctly directed in RTL locale (`ar`).

### Device & build information
* Device: iPhone 11
* Build version: v114.1 (31594)
* First seen version:  N/A

### Notes
![IMG_8802](https://github.com/mozilla-mobile/firefox-ios/assets/37640295/ebd35f2c-c970-47af-88d5-d15de42b8938)
![IMG_8803](https://github.com/mozilla-mobile/firefox-ios/assets/37640295/fb749438-c1ae-4c9f-b349-01bd6181d94f)

Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6691)

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v9000 (33699), on iPhone SE (16.4). I can confirm that the direction of the arrows is to the left.
