### ISSUE TITLE
Settings top/bottom space changed in RTL locale (ar)

### ISSUE THREAD

**Issue by aalaaeid** [mozilla-mobile/firefox-ios#14921]
## Steps to reproduce

1. Set the language to AR.
2. Launch FF -> settings
3. Observe the spacing of settings.

### Expected behavior
The top/bottom space of settings cells should be the same as they appear in LTR locale.

### Actual behavior

The top/bottom space of settings cells changed in RTL locale (`ar`).

### Device & build information
* Device: iPhone 11
* Build version: v114.1 (31594)
* First seen version: N/A

### Notes
Attachments: 
![IMG_8814](https://github.com/mozilla-mobile/firefox-ios/assets/37640295/24f0a755-52cf-423d-8138-d16afe5b145b)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6687)

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Verified as fixed on v116 (32530) with iPhone 13 Pro (15.7.1).
