### ISSUE TITLE
Shortcuts top/bottom space changed in RTL locale (ar)

### ISSUE THREAD

**Issue by aalaaeid** [mozilla-mobile/firefox-ios#14922]
## Steps to reproduce
1. Set the language to AR.
1. Launch FF -> settings -> Homepage
1. tap Shortcuts
1. Observe the top/bottom space of Rows cell.

### Expected behavior
The top/bottom space of Rows cell should be the same as they appear in LTR locale.

### Actual behavior
The top/bottom space of Rows cell changed in RTL locale (`ar`).

### Device & build information
* Device: iPhone 11
* Build version: v114.1 (31594)
* First seen version: N/A

### Notes
Attachments: 
![IMG!UNITO-UNDERSCORE!8805](https://github.com/mozilla-mobile/firefox-ios/assets/37640295/a5efcc91-379a-4fce-adeb-1fb1b2542a54)

![IMG!UNITO-UNDERSCORE!8806](https://github.com/mozilla-mobile/firefox-ios/assets/37640295/e67c1aff-a8b2-4d69-8c86-d9f340a663f1)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6688)

**Comment by lmarceau** [comment]
I'm wondering if fixing https://github.com/mozilla-mobile/firefox-ios/issues/14921 will fix this one as well 🤞

**Comment by aalaaeid** [comment]
> I'm wondering if fixing #14921 will fix this one as well 🤞

Yeah, I think they are related, but I'm not sure, so I opened two separately. 👀
