### ISSUE TITLE
Placeholder text doesn't react to theme change in URL bar 

### ISSUE THREAD

**Issue by lmarceau** [mozilla-mobile/firefox-ios#14933]
## Steps to reproduce
- Be in light or dark mode
- Change to the other theme
- Observe the text placeholder color in the URL bar

### Expected behavior
It's the right color

### Actual behavior
It doesn't change with the theme when application is live. You need to restart the app to get the right color

### Device & build information
* Device: iPhone 14, any
* Build version: 37c754c2050a23900f914f277fbf41b20124c3ae
* First seen version: 115
### Notes
Attachments: 
With the wrong color in dark mode (harder to read)
![Screenshot 2023-06-13 at 2 19 57 PM](https://github.com/mozilla-mobile/firefox-ios/assets/11338480/28f72973-88d0-4773-bb69-847fdf5be1d3)

With the right color in dark mode
![Screenshot 2023-06-13 at 1 49 41 PM](https://github.com/mozilla-mobile/firefox-ios/assets/11338480/832a67f2-543e-4f10-88a7-2149205b22e2)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6694)

**Comment by lmarceau** [comment]
Relates to https://github.com/mozilla-mobile/firefox-ios/issues/14882

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Verified as fixed on v116 (32475) with iPhone 13 Pro (15.7.1).
