### ISSUE TITLE
Could not build on XCode due to AutofillAllFramesAtDocumentStart.js missing.

### ISSUE THREAD

**Issue by Standard8** [mozilla-mobile/firefox-ios#14944]
## Steps to reproduce

1. Check out the latest version of the repository (I used 12cf8dd2cdaafdd085302c82a3bfa2cb74ec8f76)
2. Try and build it via XCode

### Expected behavior

The build should be successful.

### Actual behavior

Build fails due to:

```
error: /Users/mark/dev/firefox-ios/Client/Assets/AutofillAllFramesAtDocumentStart.js: No such file or directory (in target 'Client' from project 'Client')
```

### Device & build information
* XCode: 14.3.1
* Device: macOS 13.4
### Notes

The file was removed in #14298 but Client.xcodeproj/project.pbxproj didn't get updated for the removals (other files were added). cc @nbhasin2

Manually removing from the project worked.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6699)

**Comment by Standard8** [comment]
Filed #14945 to hopefully fix this.

**Comment by OrlaM** [comment]
As mentioned in the PR, this file is still used. Running bootstrap.sh for the root folder should fix the error.

**Comment by Standard8** [comment]
Sorry, that was a little confusing. Not sure how that could be made easier to realise. Maybe it is just a learning process.

**Comment by OrlaM** [comment]
No worries, this hopefully should be a rare occurrence, but I'll add a note to our contribution guide to try running bootstrap.sh as a potential resolution step to try if things aren't working for others who might run into this.
