### ISSUE TITLE
Deleting Last Inactive Tab Crashes App

### ISSUE THREAD

**Issue by jstvincent** [mozilla-mobile/firefox-ios#14955]
## Steps to reproduce

Have one tab remaining in Inactive Tabs. Open to expand Inactive Tabs. Swipe to show Delete toggle. Press Delete button.

### Expected behavior

Tab is deleted.

### Actual behavior

App crashes.

[Screen recording of bug.](https://youtube.com/shorts/kkRZJxaS7cQ?feature=share) 

### Device & build information
* Device: ? 
* Build version: ? 
* First seen version: ? 
### Notes
Attachments: 

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6702)

**Comment by jstvincent** [comment]
Updates - tried to edit OP, but site was erroring out save edits.


### Device & build information
* Device: iPhone 14 Pro Max, iOS 16.5
* Build version: 114.1 (31594)
* First seen version: 114.1 (31594)

### Notes
Attachments: 
[Screen recording of bug.](https://youtube.com/shorts/kkRZJxaS7cQ?feature=share)

**Comment by yoanarios** [comment]
Closing this issue because its a duplicate from #14924. Thanks for creating this issue
