### ISSUE TITLE
[Experiment] iOS Notifications that use the OPEN_SETTINGS_* actions to not display the appropriate sub pages if the Settings page is already open

### ISSUE THREAD

**Issue by Softvision-PatriciuPop** [mozilla-mobile/firefox-ios#14954]
### [Prerequisites]:
* Have a browser profile enrolled in a Nimbus experiments using a "OPEN_SETTINGS_SEARCH_ENGINE" notification action.

### [Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Tap the Hamburger menu and tap the “Settings” option.
3. Send the app to the background.
4. Open the device’s settings and change the system time to 2 days and 2 minutes in the future.
5. Tap the Firefox notification and observe the behavior.

### [Expected result]:
* The browser is focused and the Settings > Search page is displayed.

### [Actual result]:
* The browser is focused and the main Settings page is displayed.

### [Device & build information]:
* Device: iPhone 11 - iOS 16.2

### [Affected versions]:
* Firefox Beta 9000 (31738)

### [Notes]:
* The issue is not reproducible if the homepage or a website is opened before the notification is triggered.
* The issue is reproducible with all the actions that launch the Settings subpages: OPEN_SETTINGS_FXA, OPEN_SETTINGS_EMAIL, OPEN_SETTINGS_HOMESCREEN, OPEN_SETTINGS_NEW_TAB, OPEN_SETTINGS_PRIVACY, OPEN_SETTINGS_SEARCH-ENGINE, OPEN_SETTINGS_WALLPAPERS.
* Tested using the <thing> preview experiment.
* Attached a screen recording of the issue:

https://github.com/mozilla-mobile/firefox-ios/assets/40393891/8b99288d-f9f4-4e71-9630-7ac4af6564b6

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6701)

**Comment by lmarceau** [comment]
Whoever works on this we should sync - since this relates to settings and there's ongoing work for the settings coordinator.

**Comment by data-sync-user** [comment]
➤ Daniela Arcese commented:

Laurie Marceau this can wait until 116.

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Laurie Marceau Daniela Arcese hello, does this needs to be re-open? I see it QA Verified but I’m pretty sure no one verified this bug.

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Hello, Laurie Marceau should we set this fix version for 117 given the fact that the settings coordinator is delayed?

**Comment by data-sync-user** [comment]
➤ Laurie Marceau commented:

This was a fix for the notification experiment. So you can test that this is fixed in v116, with the notification experiment (if there’s one available, I am unsure about this part).

**Comment by Softvision-PatriciuPop** [comment]
I've verified that this issue is no longer reproducible, the correct pages are now opened according to the configured action. Verified using Firefox for iOS Beta 9000 (33434) on iOS 16.2 (iPhone 11).
