### ISSUE TITLE
URLBarView and Toolbar should be ThemeApplicable

### ISSUE THREAD

**Issue by lmarceau** [mozilla-mobile/firefox-ios#14976]
We're currently relying on BVC to manually update those views. URLBarView and toolbar are neither ThemeApplicable or Themeable, which means they don't get updated. Following the guidelines we established in the [wiki](https://github.com/mozilla-mobile/firefox-ios/wiki/Theming-system), view controllers are the ones getting updates from theme changes, which then automatically trickles down the changes to any subviews following the ThemeApplicable protocol. Themeable views should not hold a reference to theme manager, since that reference will not get updated on theme change.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6707)

**Comment by data-sync-user** [comment]
➤ Laurie Marceau commented:

For QA, it can be tested the URL bar/tool bar theme is working as it should in dark and light mode. We also theme properly when we change from dark to light and vice versa.

**Comment by data-sync-user** [comment]
➤ Alina Moldovan commented:

Validated this change using FF v116 (16.0.3) and iPhone 16+ (16.0.3).
