### ISSUE TITLE
Update theming system in SearchInputView

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#14981]
Use the new theming system following [guidelines](https://github.com/mozilla-mobile/firefox-ios/wiki/Theming-system)

* `Themeable` and `ThemeApplicable` are used where necessary.
* `UIColor.Photon or UIColor.theme` should not be called at all.
* LegacyThemeManager should not be used.
* LegacyNotificationThemeable should not be used.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6711)

**Comment by lmarceau** [comment]
Seems the class `SearchInputView` is never instantiated anywhere so we can remove it. Nice find @FilippoZazzeroni 🙏

**Comment by FilippoZazzeroni** [comment]
@lmarceau thank you.
