### ISSUE TITLE
[Experiment] The 2nd onboarding card is not displayed after tapping the "Set as default browser" button.

### ISSUE THREAD

**Issue by Softvision-PatriciuPop** [mozilla-mobile/firefox-ios#15017]
## [Prerequisites]:
- Have a browser profile enrolled in the CTD iOS experiment using the nimbus-cli tool.

## [Steps to reproduce]:
1. Open the browser with the profile from the prerequisites.
2. Tap the "Set as default browser" (Als Standardbrowser festlegen) button from the first onboarding card.
3. Tap the "< Fennec" button to return to the browser.
4. Observe the onboarding cards.

## [Expected result]:
- The second onboarding card is displayed.

## [Actual result]:
- The first onboarding card remains displayed.

## [Device & build information]:
- iPhone 11 - iOS 16.2 (simulated)
- iPhone 14 - iOS 16.2 (simulated)

## [Affected versions]:
- latest Firefox v115

## [Notes]:
- The issue is reproducible only with the 1st onboarding card.
- The concern here is that users who get stuck on the first card will either close the onboarding or tap the "Skip" button, affecting the experiment's telemetry.
- Attached a screen recording of the issue:

https://github.com/mozilla-mobile/firefox-ios/assets/40393891/9dd017e5-6c73-4fe8-b92b-d0bbfb704535

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6748)

**Comment by adudenamedruby** [comment]
Hello. I'm going to close this issue because it's not actually an issue. This behaviour is exactly what's currently expected. The going to the next page for the "Set as default browser" button on the first card sends you to the settings, but doesn't paginate. Pagination only occurs from the Default Browser instructions card.

If we want to add this behaviour, we need to create a ticket for it. @dnarcese

**Comment by data-sync-user** [comment]
➤ Daniela Arcese commented:

Emily Wachowiak Aarjav Pandya what should the behaviour be when we do not have the instruction card?

**Comment by data-sync-user** [comment]
➤ Aarjav Pandya commented:

Daniela Arcese 
This was decided on the original Onboarding experiment over here ( https://www.figma.com/file/7J6gh5D8DbGTExxskKdn3T/Mobile-Onboarding?type=design&node-id=6512-63646&t=RcqWjOrxg9INYnQu-4 ). 

  * After changing/not changing the default browser, the screen automatically switches to the next card when the user returns to the app from the default browser app settings in less than 500ms (hopefully <2s).

**Comment by adudenamedruby** [comment]
Ok. I've updated it so it behaves like that. I'm gonna re-open this ticket for the work, so I don't have to open up another ticket. lol

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Should we change the status to Open for this issue? Roux Buciu

**Comment by data-sync-user** [comment]
➤ Roux Buciu commented:

Negative. This needs separate testing from that one. You’ll need to test with https://experimenter.services.mozilla.com/nimbus/ios-set-to-default-instructions-no-x-copy/summary ( https://experimenter.services.mozilla.com/nimbus/ios-set-to-default-instructions-no-x-copy/summary ) experiment (control), for this one.

**Comment by Softvision-PatriciuPop** [comment]
This issue is no longer reproducible, the 2nd card is correctly displayed after returning to the Firefox app. Tested using Firefox Beta 115.0 (32093) on iPhone 11 (iOS 16.2).
