### ISSUE TITLE
[regression] The address bar’s cursor is blurry and a light gray color, making it hard to see

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/firefox-ios#15037]
## Steps to reproduce

1. Tap focus to the address bar. 
2. Long press on the keyboard’s space bar to activate the keyboard trackpad mode to move the cursor.
3. While continuing to hold down your finger, move it left and right over the keyboard to move the cursor in the address bar. 

### Expected behavior

The address bar’s cursor should be a dark color, like the cursor in web content’s text fields. 

### Actual behavior

Starting with build 9000 (31787), the address bar’s cursor is blurry and a very light gray color, making it hard to see. In the attached screenshot, you can barely see the cursor between the ‘p’ and ‘s’ of “https:” in the address bar. 

### Device & build information

Device: iPhone 12 running iOS 16.5
Build version: 9000 (31868)
First seen version: 9000 (31787)

### Notes

![image](https://github.com/mozilla-mobile/firefox-ios/assets/629193/ee3d551d-d858-403a-8ca9-d7c522a10cb4)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6755)

**Comment by lmarceau** [comment]
That is a repercussion of https://github.com/mozilla-mobile/firefox-ios/issues/14857. The cursor is the same color as the selected and suggestion autofill color, so we either reverta and put `actionPrimary` back or change the color to something else more visible? @cwzilla 
<img width="469" alt="Screenshot 2023-06-19 at 12 08 00 PM" src="https://github.com/mozilla-mobile/firefox-ios/assets/11338480/04ab1a4f-4c10-4ff2-a2be-357e5129200a">
<img width="452" alt="Screenshot 2023-06-19 at 12 08 15 PM" src="https://github.com/mozilla-mobile/firefox-ios/assets/11338480/9c564b19-b43c-4560-a7e2-1f8382ab52bc">

**Comment by cwzilla** [comment]
@lmarceau if we revert back to `actionPrimary`, will that change the highlight colour as well? or will it only affect the text cursor?

**Comment by lmarceau** [comment]
> @lmarceau if we revert back to `actionPrimary`, will that change the highlight colour as well? or will it only affect the text cursor?

It will change the highlight color as well. It's one color for all

**Comment by Tomatoshadow2** [comment]
@lmarceau the first top screenshot you posted, the one with the brighter highlight color, I think would be better as you can see better what you’re highlighting in the address bar.

**Comment by lmarceau** [comment]
Note; there's an issue with #14229 that we can fix with this ticket I think.

**Comment by lmarceau** [comment]
Discussed with Crystal, and we'll revert to `actionPrimary` for now. There's potentially some work to come on private mode, so we eventually improve on https://github.com/mozilla-mobile/firefox-ios/issues/14857.

**Comment by data-sync-user** [comment]
➤ Laurie Marceau commented:

For QA, it can be tested the color is back to the one it was in https://github.com/mozilla-mobile/firefox-ios/issues/14857 ( https://github.com/mozilla-mobile/firefox-ios/issues/14857|smart-link )

**Comment by data-sync-user** [comment]
➤ Alina Moldovan commented:

Validated this issue using v9000 (32311) 

The following colors are used: 

  * Normal browsing mode: 
    * dark theme:

  * !image-20230703-144547.png|width=526,height=170!
    * light mode: 

  * !image-20230703-144850.png|width=445,height=183!
  * Private browsing mode: 
    * dark theme 
    * !image-20230703-145520.png|width=445,height=197!
      * light theme

    * !image-20230703-145321.png|width=522,height=181!

Laurie Marceau  To me, the colors don’t look consistent (especially for private browsing mode), but please let me know if there colors are expected to be used. Thank you!

**Comment by data-sync-user** [comment]
➤ Laurie Marceau commented:

Alina Moldovan yes you’re right, but for now design decided we’ll stick with those colors until there’s some work done again on the URL bar 🙏Thank you!

**Comment by data-sync-user** [comment]
➤ Alina Moldovan commented:

Laurie Marceau thank you for the clarification. I will move the ticket in “QA verified“ for now.
