### ISSUE TITLE
Open last bookmark doesn't work when it is opened from 3D Touch menu if the FF app was previously closed

### ISSUE THREAD

**Issue by alinamoldovan84** [mozilla-mobile/firefox-ios#15040]
## Steps to reproduce
1. Load a web page
1. Force close the FF app
1. Long tap on FF icon
1. Tap "Open last bookmark"

### Expected behavior
The latest saved bookmark opens 

### Actual behavior
Home-screen opens

### Device & build information
* Device: iPad Air 3rd Gen (16.3.1), iPhone 14+(16.0.3) 
* Build version: v115 (31878) 
* First seen version: ? 
### Notes
Attachments: 

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6757)

**Comment by data-sync-user** [comment]
➤ Catalin Suciu commented:

This is working as expected on the latest main.
