### ISSUE TITLE
[Experiment] The default "Default Homepage Banner" is re-displayed after dismissing the treatment's specific massage 

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-mobile/firefox-ios#15045]
**[Notes]**
- The issue is also reproducible after interacting with the banner and setting Firefox as default browser. 

**[Affected versions]:**
- Firefox Release 114.2 (31625) build from TestFlight
- Firefox Release 113.2 (31081) build from TestFlight

**[Affected Platforms]:**
- iOS 15.6 - iPhone 13 mini
- iOS 16.2 - iPhone SE

**[Steps to reproduce]:**
1. Open the browser and tap the hamburger menu button from the bottom-right part of the screen.
2. Select the "Settings" option and scroll down to the bottom part of the menu.
3. Tap the "Firefox 114.2 (31625)" option 5 times.
4. Scroll down to the "Debug" section and select the "Experiments" option.
5. Tap the "Edit" button from the top-right part of the screen.
6. Tap on the "Use Preview Collection" radio button and restart the app.
7. Repeat steps from 1 to 5.
8. Tap the "Reset" button from the bottom part of the screen.
9. Tap the "Back" button from the top-left part of the page.
10. Tap the "Mobile default browser homepage banner copy test - iOS" experiment and select the "treatment-a" branch.
11. Restart the app and dismiss the "Default Homepage Banner" displayed for treatment-a.
12. Restart the Firefox app and observe the behavior.

**[Expected results]:**
- NO "Default Homepage Banner" message is displayed.

**[Actual results]:**
- The default "Default Homepage Banner" message is re-displayed.

**[Additional Notes]**:
- Here is a screen recording of the issue: [Gdoc](https://drive.google.com/file/d/11lBCiYzIK4ffoenDYaB2Rbxso64ppiIG/view?usp=sharing).

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6760)

**Comment by adudenamedruby** [comment]
This isn't a bug but intended behaviour. An investigation into the experiment reveals that the message ID is different that the ID for the default browser, which means that both messages will show.

<img width="313" alt="Screenshot 2023-08-04 at 11 12 28 AM" src="https://github.com/mozilla-mobile/firefox-ios/assets/11182210/f11faf52-465a-45c0-b79e-fa18de5ed44f">
