### ISSUE TITLE
Telemetry events do not appear in the Debug Ping Viewer using a physical device on the latest Beta

### ISSUE THREAD

**Issue by Softvision-PatriciuPop** [mozilla-mobile/firefox-ios#15048]
## [Steps to reproduce]:
1. Open Safari and enter the following command "firefox://glean?logPings=true&sendPing=events&debugViewTag=<customtag>".
2. Go through the onboarding flow.
3. Send the app to the background and then close it.
4. Open the Glean Ping Viewer and search for the chosen tag. (https://debug-ping-preview.firebaseapp.com/)

## [Expected result]:
- The chosen tag is displayed in the list and it contains several telemetry events.

## [Actual result]:
- The chosen tag is not displayed in the list.

## [Device & build information]:
- iPhone 11 - iOS 16.2

## [Affected versions]:
- Firefox Beta v115 (31625)
- Firefox Beta 9000 (31874)

## [Notes]:
- The telemetry events seem to be generated correctly as experiment enrollment and unenrollment events appear on the Looker dashboard.
- The issue is not reproducible on Beta 114.2 (31625)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6762)

**Comment by adudenamedruby** [comment]
I'm not sure what's going on:  if we're receiving Glean events for enrollment, I'm not sure why we wouldn't be receiving events for anything else. No code's changed in 115 from 114 regarding telemetry that is being sent (and you're also verified you can't repro on 114.2). I'll take a brief look.... but I genuinely don't know what would be happening here.

**Comment by adudenamedruby** [comment]
I've just ran through all the events for onboarding and everything is getting recorded fine. I'm not sure what's happening.

**Comment by Softvision-PatriciuPop** [comment]
The issue is no longer reproducible on the latest Beta 115 (32059) build, marking this issue as resolved.
