### ISSUE TITLE
The opened website thumbnails are not displayed in the tabs tray

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/firefox-ios#15044]
## Steps to reproduce
1. Launch FF and access any website.
2. Long tap on any link and open in a new tab.
3. Open the tabs tray.
### Expected behavior
The new website thumbnail should be displayed.
### Actual behavior
The opened website thumbnails are not displayed in the tabs tray.
### Device & build information
* Device: iPhone 13 Pro (15.7.1) 
* Build version: 115 (31878) also occurs on v9000 latest Nightly 
* First seen version: N/A 
### Notes
Attachments: 

https://github.com/mozilla-mobile/firefox-ios/assets/42831109/682a1b90-039c-4a17-a1a8-98ff048e928d

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6759)

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Verified as fixed on v115 (31980) with iPhone 13 Pro (15.7.1).
