### ISSUE TITLE
Credit card bottom sheet select / remember / update table cell background color incorrect

### ISSUE THREAD

**Issue by nbhasin2** [mozilla-mobile/firefox-ios#15056]
Dark mode modal for credit card bottom sheet has incorrect text color, and background of card need to be updated

### Steps to reproduce
- Make sure to turn on dark mode in Firefox iOS
- Go to a website that allows for checkout flow in terms of credit card
- Enter card info for the card you already have saved but change date or name
- This will show the update flow after you submit

### Expected behavior
- The background color is black for the cell in bottom sheet

### Actual behavior
- Button color text: # 15141A
- Card background: update to ‘fxColorDarkGrey40’ // Dark/Layer/iOS/5

### Device & build information
* Device: iPhone 14 pro
* Build version: v9000 (31868)
* First seen version: v9000 (31868)
### Notes
Attachments: 

<img width="1098" alt="image" src="https://github.com/mozilla-mobile/firefox-ios/assets/8919439/1e29bd93-e684-4e32-8bc9-267fca32520e">

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6764)

**Comment by DianaBarladeanu** [comment]
Verified as fixed on v116 (32873) with iPhone SE (16.5).
