### ISSUE TITLE
Spacing on update credit card / save a card is incorrect

### ISSUE THREAD

**Issue by nbhasin2** [mozilla-mobile/firefox-ios#15055]
Spacing on ‘Update this Card’ modal - Spacing is very cramped on this right now. This can cause some touch target/accessibility issues if too small. 
Current vs. Mock with padding highlighted:

### Steps to reproduce
- Go to a website that allows for checkout flow in terms of credit card
- Enter card info for the card you already have saved but change date or name
- This will show the update flow after you submit

### Expected behavior
- Spacing is incorrect in the update flow

### Actual behavior
- Spacing should be how the mocks are (in the middle) 
- Mock: https://www.figma.com/file/cSKRUEvfJSzNBv2Mp65Pdv/Mobile-CC-Autofill?type=design&node-id=3097-121048&t=xZJezY7iEYS6LdCP-4

### Device & build information
* Device: iPhone 14 pro
* Build version: v9000 (31868)
* First seen version: v9000 (31868)
### Notes
Attachments: 

<img width="1153" alt="Screenshot 2023-06-19 at 11 13 54 AM" src="https://github.com/mozilla-mobile/firefox-ios/assets/8919439/32c7c18d-6d5d-4dd4-b613-4a438b05abfb">

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6763)

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Verified as fixed on v9000 (32311) with iPhone 13 Pro (15.7.1).
