### ISSUE TITLE
"Sync and Save Data" from the "Synced Tabs" page is not responding

### ISSUE THREAD

**Issue by clarmso** [mozilla-mobile/firefox-ios#15066]
## Steps to reproduce
1. Open a new tab on Firefox and close the keyboard.
2. Tap the tabs button to open the tab tray.
3. Go to the "Synced Tabs" tab from the tab tray (see screenshot).
4. Tap "Sync and Save Data" button (see screenshot).

### Expected behavior
Some Firefox Account login options are presented.

### Actual behavior
The button does not do anything.

Workaround: 
1. Tap hamburger icon to open the menu.
2. Tap "Sync and Save Data" menu item.

### Device & build information
* Device: iPhone 14 simulator
* Build version: 116.0 (1)
* First seen version: June 17-ish
### Notes
Attachments: 

![Simulator Screenshot - iPhone 14 - 2023-06-19 at 16 17 59](https://github.com/mozilla-mobile/firefox-ios/assets/1740517/6d6ca976-7619-476c-bc06-5ae24a414a16)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6769)

**Comment by data-sync-user** [comment]
➤ Alina Moldovan commented:

Validated this issue using v116 (32820) and iPhone 14+(16.0.3) This issue doesn’t  reproduce anymore.
