### ISSUE TITLE
[Experiment] Validation Error at features when enrolling in the “ios-set-to-default-instructions-no-x” experiment. 

### ISSUE THREAD

**Issue by Carmentataru** [mozilla-mobile/firefox-ios#15071]
[Prerequisites]:
- Have an ios simulator Firefox v115 build created. 
- Have the latest version of nimubs-cli installed.
- Have the nimbus.cli command for the ios-set-to-default-instructions-no-x experiment. (nimbus-cli --app firefox_ios --channel developer enroll ios-set-to-default-instructions-no-x --branch treatment-a

[Steps to reproduce]:
1. Use the command for prerequisites and enroll on the treatment a branch of the experiment.
2. Observe the error displayed in the terminal. 

[Expected result]:
The user is be enrolled in the selected branch of the experiment. 

[Actual result]:
- The following errors are displayed in the terminal: 
treatment-a     onboarding-framework-feature: Validation Error at features/onboarding-framework-feature.cards['dismissable']: Mismatch between type Object("NimbusOnboardingCardData") and default false
❎ treatment-b     onboarding-framework-feature: Validation Error at features/onboarding-framework-feature.cards['dismissable']: Mismatch between type Object("NimbusOnboardingCardData") and default true
❎ treatment-c     onboarding-framework-feature: Validation Error at features/onboarding-framework-feature.cards['dismissable']: Mismatch between type Object("NimbusOnboardingCardData") and default false

[Device & build information]
- Iphone 12 Pro Max (iOS 14.2)

[Build version]
- Firefox for iOS 116.0
- Firefox for iOS v115

[Notes]:
- Using the “--no-validate” argument we are able to enroll in the experiment, however the branch configuration is not applied.
- This issues could not be reproduced on a physical device, an update will be provided when a build version will be available. 

<img width="1206" alt="Screenshot 2023-06-20 at 14 59 39" src="https://github.com/mozilla-mobile/firefox-ios/assets/112865359/a6d8413d-86fa-4640-a497-c9fc1bbcfc3b">

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6771)

**Comment by data-sync-user** [comment]
➤ Daniela Arcese commented:

Roux Buciu I suspect the problem is where I have the dismissable in the branch setup. I think it needs to be a level higher

**Comment by data-sync-user** [comment]
➤ Daniela Arcese commented:

I setup a new experiment with the fix https://experimenter.services.mozilla.com/nimbus/ios-set-to-default-instructions-no-x-copy/summary ( https://experimenter.services.mozilla.com/nimbus/ios-set-to-default-instructions-no-x-copy/summary )

**Comment by Carmentataru** [comment]
I have verified this issue with the new Experiment and is no longer reproducible.
