### ISSUE TITLE
Credit card autofill toggle broken

### ISSUE THREAD

**Issue by nbhasin2** [mozilla-mobile/firefox-ios#15096]
## Steps to reproduce
- Disable the toggle to autofill / save credit cards
- Go to a page with checkout and enter credit card info
- Hit submit
- No prompt should be shown to remember / save / update credit card

### Expected behavior
- No prompt should be shown to remember / save / update credit card

### Actual behavior
- prompt shown to remember / save credit card

### Device & build information
* Device: iPhone 14 pro
* Build version: v9000 (31868)

### Notes
Attachments: 

https://github.com/mozilla-mobile/firefox-ios/assets/8919439/483d3bca-1b83-43eb-9cb6-07998face5c9

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6777)

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Verified as fixed on v9000 (32311) with iPhone 13 Pro (15.7.1).
