### ISSUE TITLE
All opened tabs are closed when user chooses to open a new tab from the widget or 3D Menu if the FF app was previously closed 

### ISSUE THREAD

**Issue by alinamoldovan84** [mozilla-mobile/firefox-ios#15103]
## Steps to reproduce
1. Make sure you have multiple tab opened 
2. Force close the FF app
3. Choose "search in Firefox " from FF widgets or "New tab" from FF 3D touch menu (long press on FF app icon to open the context menu)

### Expected behavior
A new tab should open. The already open tabs should be available in tabs tray

### Actual behavior
Already opened tabs are closed 

### Device & build information
* Device: iPhone 14+ (16.0.3) 
* Build version: v115 (31980) 
* First seen version: v115 (31980) 
### Notes
Not reproducible on Beta 6 and Beta 7.
Attachments: 

https://github.com/mozilla-mobile/firefox-ios/assets/124251579/a981d052-6364-4564-847d-f4205f8263dd

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6781)

**Comment by data-sync-user** [comment]
➤ Laurie Marceau commented:

For QA, since the coordinator refactor was turned off in v115, we should test this problem is fixed:

  * When the experiment is OFF (now the default state)
  * When the experiment is ON (which can be changed from the experiment debug menu)

**Comment by data-sync-user** [comment]
➤ Alina Moldovan commented:

Laurie Marceau for v115 we are not able to see the “iOS coordinator Rollout“ under experiments. Will it be enabled for the next version?

**Comment by data-sync-user** [comment]
➤ Laurie Marceau commented:

Indeed I don’t see it. Let me ask around.

**Comment by data-sync-user** [comment]
➤ Laurie Marceau commented:

Ok it was disabled, it should be reenabled soon! Alina Moldovan

**Comment by data-sync-user** [comment]
➤ Alina Moldovan commented:

Verified this issue using FF v115 (32059) and iPhone 14+(16.0.3)

Cannot reproduce the issue if the coordinator is ON. 

If Coordinator is Off the tabs are available, the new tab opens but the focus is not on the new tab, but on the latest opened tab (please see the attached video) 

!Skype_Video26.mp4|width=888,height=1920!
