### ISSUE TITLE
Search group items view should have full length lines

### ISSUE THREAD

**Issue by lmarceau** [mozilla-mobile/firefox-ios#15105]
See comment from our designer [here
](https://github.com/mozilla-mobile/firefox-ios/pull/15093#issuecomment-1599480010)

The first line and the last line should be full width when we're showing the `SearchGroupedItemsViewController`.
Please make sure to test landscape, and iPad (with multitasking windows and without)
![247230509-2553bc61-3c32-4cac-9e00-417d7126cd94](https://github.com/mozilla-mobile/firefox-ios/assets/11338480/7a7e2ba5-ecdf-4899-8056-4e0a2913ca39)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6783)

**Comment by elemanhillary** [comment]
This can only be solved using custom view separator

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Verified as fixed on v117 (33235) with iPhone 13 Pro (15.7.1).
