### ISSUE TITLE
[Experiment] The next onboarding card is displayed when the application is sent in background in control and treatment A branches of the experiment

### ISSUE THREAD

**Issue by Carmentataru** [mozilla-mobile/firefox-ios#15104]
[Prerequisites]:
- Have an ios simulator Firefox v115 build created. 
- Have the latest version of nimubs-cli installed.
- Have the nimbus.cli command for the ios-set-to-default-instructions-no-x experiment. (nimbus-cli --app firefox_ios --channel developer enroll ios-set-to-default-instructions-no-x --branch treatment-a

[Steps to reproduce]:
1. Use the command for prerequisites and enroll on the control or  treatment A branch of the experiment.
2. Tap the “Set as default Browser” primary button. 
3. Send the application into the background. 
4. Open the application.
5. Send the application into the background again. 
6. Observe the results.

[Expected result]:
- The same card should be displayed when the application is focused again. 

[Actual result]:
- The next cards are displayed when the application is sent in background. 

[Device & build information]
- Iphone 12 Pro Max (iOS 14.2)

[Build version]
- Firefox for iOS v115

[Notes]:
- This issue is not reproducible in the treatment B and C of the experiment.
- This issue may be related to issue [15017](https://github.com/mozilla-mobile/firefox-ios/issues/15017).

https://github.com/mozilla-mobile/firefox-ios/assets/112865359/622ec9bd-10e3-4ab7-89db-f3e5ca059614

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6782)

**Comment by Softvision-PatriciuPop** [comment]
I have verified that this issue is no longer reproducible, verified using Firefox Beta 115.0 (32222) on iPhone 11 (iOS 16.2).
