### ISSUE TITLE
Often used tabs crashes after many restarts

### ISSUE THREAD

**Issue by flygarn12** [mozilla-mobile/firefox-ios#15112]
## Steps to reproduce
If I have for example 10tabs open and 3 tabs is used a lot of times per day these 3 will crash if I restart Firefox (shut down Firefox and restart it) about 3 to 5 times. The other tabs not used that often will continue functioning and load when opened.
If Firefox is only minimized and not restarted then it will go on for ever without problem.

I have tried reinstall Firefox without solving it. I have tried clean the browse cache with the tabs open without solving it, it only survives some more restarts before crashing. I have tried closing all tabs including the "inactive tabs" and clean browser cache and iPad reboot and still crash after the third restart of Firefox.

### Expected behavior
All the tabs should open when clicked on and load the last page on that tab before the restart.

### Actual behavior
The often used tabs flashes and it looks like it tries reload but goes blank and the forward and reverse arrow is lit and they doesn't work and reload page doesn't work since the tab has no memory of any earlier page. But still the not so much used tabs work as expected.

### Device & build information
* Device: iPad Air 5th gen, iPadOS 16.5
* Build version: Firefox 114.2 (31625)
* First seen version: This came the same day the first install of iPadOS 16.1 was upgraded from iPadOS 15.
### Notes
Attachments: 

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6784)

**Comment by dnarcese** [comment]
@flygarn12 Are you still experiencing this issue?

**Comment by flygarn12** [comment]
The issue was fixed with a update a short time after my report.
