### ISSUE TITLE
The `Use saved card` text background is displayed in both Dark and Light mode

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/firefox-ios#15127]
## Preconditions
Have some CC saved.

## Steps to reproduce
1. Launch FF.
1. Go to a page with checkout and enter credit card info.
1. Tap on the Card information field and then check the `Use saved card`.

### Expected behavior
The `Use saved card` text background should not be displayed.

### Actual behavior
The `Use saved card` text background is displayed.

### Device & build information
* Device: iPhone 13 Pro (15.7.1). 
* Build version: 9000 (32023). 
* First seen version: N/A 
    1. Notes

Attachments: 

![image](https://github.com/mozilla-mobile/firefox-ios/assets/42831109/14406cd8-3484-4c37-a3be-988f09398ca8)

![image](https://github.com/mozilla-mobile/firefox-ios/assets/42831109/cda20cf4-fb01-4fff-9a0d-284c7b8cc835)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6790)

**Comment by nbhasin2** [comment]
@abodea slightly confused, could you explain why the background should not be displayed?
Is this still a bug?

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Verified as fixed on v118 (33974) with iPhone 14 (17.0)
