### ISSUE TITLE
The user is redirected to Firefox settings instead of the checkout webpage

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/firefox-ios#15128]
## Steps to reproduce
1. Access any website with a credit card form and tap on the credit card number/ credit card name field to trigger the "Select credit card" prompt (for example https://checkout.stripe.dev/preview)).
1. The "Select credit card" prompt is displayed.
1. Expand the prompt.
1. Tap on the "Manage credit cards" option.
1. The user is redirected to the "Credit cards" section in Settings.
1. Tap the back button on the Credit cards page, or on the device.

### Expected behavior
The user is returned to the webpage in step 1. The prompt is dismissed.

### Actual behavior
The user is redirected to Firefox settings instead of the checkout webpage.

### Device & build information
* Device: iPhone 13 Pro (15.7.1). 
* Build version: 9000 (32023). 
* First seen version: N/A 
    1. Notes
Attachments: 

https://github.com/mozilla-mobile/firefox-ios/assets/42831109/8ad76d05-5299-4b28-a5fa-5ccfdcdcc89d

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6791)

**Comment by nbhasin2** [comment]
This isn't a bug afaik, because we are sending the user to Settings > AutoFill (push action) so when a user fails to authenticate they can try again by tapping on the autofill area.

**Comment by data-sync-user** [comment]
➤ Nishant Bhasin commented:

Closing this with the comment mentioned before. We can come back to it if its no longer the case and changes are required
