### ISSUE TITLE
Cannot scroll when trying to autofill while having more credit cards saved

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/firefox-ios#15126]
## Preconditions
Have some CC saved.

## Steps to reproduce
1. Launch FF.
2. Go to a page with checkout and enter credit card info.
3. Tap on the Card information field and then on the `Use saved card`.
4. Attempt to scroll in the list.
### Expected behavior
The section should be scrollable if having more credit cards saved.
### Actual behavior
Cannot scroll when trying to autofill while having more credit cards saved.
### Device & build information
* Device: iPhone 13 Pro (15.7.1). 
* Build version: 9000 (32023). 
* First seen version: N/A 
### Notes

Attachments: 

https://github.com/mozilla-mobile/firefox-ios/assets/42831109/aff214ee-bc34-40fe-951b-bc7ffa3767cf

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6789)

**Comment by abodea** [comment]
I'm still able to reproduce this issue in v9000 (32311) with iPhone 13 Pro (15.7.1) and now I can reproduce it in the CC menu from the settings. At the bottom of the video, it can be seen that there is one more CC I can't reach.

https://github.com/mozilla-mobile/firefox-ios/assets/42831109/e79420d8-1005-4277-800d-2c4e5605d815

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Verified as fixed on v116 (32618) with iPhone 13 Pro (15.7.1).
