### ISSUE TITLE
The `Save` button is not grayed out in CC section if any of `Name/Number/Date` are not set

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/firefox-ios#15133]
## Steps to reproduce
1. Access the CC section.
2. Edit or add a new credit card, but don't add the CC number.
3. Check the `Save` button.
### Expected behavior
The animation when reaching the CC list should be smooth.
### Actual behavior
Weird animation after editing a CC. 
### Device & build information
* Device: iPhone 13 Pro (15.7.1). 
* Build version: 9000 (32023). 
* First seen version: N/A 
### Notes
Please note that the credit card information cannot be saved without any of the following: `Name/Number/Date`. So it's more like a visual bug.
Attachments: 

![image](https://github.com/mozilla-mobile/firefox-ios/assets/42831109/bde007e2-efa9-4158-b79d-dbd47a67f0ac)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6796)

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Verified as fixed on v9000 (32297) with iPhone 13 Pro (15.7.1).

This will also be checked when the official v116 build will be created
