### ISSUE TITLE
The same credit card cand be added more times

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/firefox-ios#15130]
## Steps to reproduce
1. Access the CC section.
1. Add the same credit cards 2 or more times with exact same information (Name, Card number, and expiration date).
    1. Expected behavior
The user should be allowed to add only one credit card with the same exact information.
    1. Actual behavior
The user is able to add duplicate CC with the exact same data.
    1. Device & build information

* Device: iPhone 13 Pro (15.7.1). 
* Build version: 9000 (32023). 
* First seen version: N/A 
    1. Notes
Attachments: 

![image0](https://github.com/mozilla-mobile/firefox-ios/assets/42831109/57282808-1789-4144-aee4-bd1cd3afd05a)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6792)

**Comment by nbhasin2** [comment]
@abodea This is by design to support cases such as when a user is syncing Firefox account which has the same credit card number but a different date and locally they added the same credit card as well. So in order to not override two cards we save them separately.
