### ISSUE TITLE
Biometrics can be bypassed and Credit Card section data can be accessed

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/firefox-ios#15134]
## Steps to reproduce
1. Launch FF and save a few cards.
2. Access any card and tap Edit.
3. Tap on the remove button -> `Remove This Card?` prompt is displayed.
4. Add FF to the background.
5. Resume FF and cover the camera in order for the `Face Not Recognized` prompt to be displayed.
6. Tap Cancel on that prompt.
7. Check the credit card section.
### Expected behavior
The credit cards section should never be unlocked, bypassing biometrics.
### Actual behavior
The CC section is unlocked even tho it's blurred tapping on any of the saved CC, the data of it can be accessed.
### Device & build information
* Device: iPhone 13 Pro (15.7.1). 
* Build version: 9000 (32023). 
* First seen version: N/A 
### Notes
Please note that the deleting of all the data from the Name/Number/Date has nothing to do with reproducing this issue.
Attachments: 

https://github.com/mozilla-mobile/firefox-ios/assets/42831109/6408f760-0338-4830-9da5-fff3ccef9e55

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6797)

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Verified as fixed on v116 (32745) with iPhone 13 Pro (15.7.1).
