### ISSUE TITLE
[Experiment] The “X” (close button) is displayed after restarting the application

### ISSUE THREAD

**Issue by Carmentataru** [mozilla-mobile/firefox-ios#15141]
[Prerequisites]:

* Have an ios simulator Firefox v115 build created. 
* Have the latest version of nimubs-cli installed.
* Have the nimbus.cli command for the ios-set-to-default-instructions-no-x experiment. (nimbus-cli --app firefox_ios --channel developer enroll ios-set-to-default-instructions-no-x --branch treatment-a

[Steps to reproduce]:

1. Use the command for prerequisites and enroll on the treatment A or C branch of the experiment.
1. Close the application.
1. Open the application. 
1. Observe the upper right part of the card. 

[Expected result]:

* On the treatment A and C of the experiment the “X” (close) button is not displayed. 

[Actual result]:

* The “X” (close) button is displayed after restarting the application.

[Device & build information]
Iphone 12 Pro Max - iOS 14.2 (simulated)

[Build version]

* Firefox for iOS 116.0
* Firefox for iOS v115

https://github.com/mozilla-mobile/firefox-ios/assets/112865359/91d423df-87fd-4575-9cc1-c09c43b02234

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6801)

**Comment by adudenamedruby** [comment]
Hmmm. This is strange. I changed the FML locally and built with it, and I can't reproduce the bug that way, which makes me think this may not be a bug with the code? I'll have to take a deeper look to see what's happening, though: is this a `nimbus-cli` related issue, a bug in the code, something else?

I've asked @dnarcese to prioritize. :)
