### ISSUE TITLE
The card information is not auto filled on iPads

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/firefox-ios#15145]
## Steps to reproduce
1. Launch FF and save a few cards.
2. Access https://checkout.stripe.dev/preview and try to perform a payment.
3. Tap on the Card information field.
4. From the saved cards, select any in order to autofill.

### Expected behavior
The card information should be auto-filled.
### Actual behavior
The card information is not auto-filled.
### Device & build information
* Device: iPad Pro (16.4.1) 
* Build version: 9000 (32023). 
* First seen version: N/A 
### Notes
Please note that I was able to reproduce this issue only on iPads.
Attachments: 

https://github.com/mozilla-mobile/firefox-ios/assets/42831109/b611ea03-e15e-4f8b-91a4-c17a07fe8510

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6802)

**Comment by nbhasin2** [comment]
This looks like a JS script error 
```
Printing description of err:
Error Domain=WKErrorDomain Code=4 "A JavaScript exception occurred" UserInfo={WKJavaScriptExceptionLineNumber=1, WKJavaScriptExceptionMessage=TypeError: null is not an object (evaluating 'this.fieldDetailsManager.activeHandler.autofillFormFields'), WKJavaScriptExceptionColumnNumber=35233, WKJavaScriptExceptionSourceURL=user-script:5, NSLocalizedDescription=A JavaScript exception occurred}
```

**Comment by nbhasin2** [comment]
Tagging @issammani for more info in case we need to modify something

**Comment by data-sync-user** [comment]
➤ Nishant Bhasin commented:

Credit card injection should work on both iPad and iPhone now

cc Andrei Bodea
