### ISSUE TITLE
Remove horizontal line in 'Update this Card' modal

### ISSUE THREAD

**Issue by jeffreygee** [mozilla-mobile/firefox-ios#15157]
## Steps to reproduce
Checkout with a saved card that is slightly updated to trigger the 'Update this Card' modal

### Expected behavior
(See screenshot)

### Actual behavior
<img width="280" alt="Screenshot 2023-06-22 at 4 24 20 PM" src="https://github.com/mozilla-mobile/firefox-ios/assets/93741573/ddb4a02e-1293-49f2-b3c1-9c14e5927b8d">
(Horizontal line appears below card - carrying over from component)

### Device & build information
* Device: iPhone 12  Pro / 16.4.1
* Build version: 31868

### Notes
Attachments: 

<img width="421" alt="Screenshot 2023-06-22 at 4 23 52 PM" src="https://github.com/mozilla-mobile/firefox-ios/assets/93741573/1d9d9760-394d-4a85-8014-56f4cd8de87d">
(No horizontal line below card)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6807)

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Blockinghttps://mozilla-hub.atlassian.net/browse/FXIOS-6789 ( https://mozilla-hub.atlassian.net/browse/FXIOS-6789|smart-link ) .

**Comment by data-sync-user** [comment]
➤ Stefan Vladut commented:

!image-20230703-123840.png|width=1218,height=260!

The changes here might affect scrolling when the drag gesture starts on the cell in the screens that use this cell

**Comment by data-sync-user** [comment]
➤ Nishant Bhasin commented:

This should be merged. Andrei Bodea can you verify this on main / v116

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Verified as fixed on v116 (32694) with iPhone 13 Pro (15.7.1).
