### ISSUE TITLE
String updates

### ISSUE THREAD

**Issue by jeffreygee** [mozilla-mobile/firefox-ios#15154]
Didn't see a ticket for string updates for the future releases so adding them all to one ticket. Please disregard if already exists

1. Confirmation toast for updating a card should say “Card Information Updated” instead of “Card information updated” - Needs to be title case
2. “Save and autofill credit cards” → Should be “Save and Autofill Credit Cards”
3.  Update the title ‘View Credit Card’ to ‘View Card’ 
4. Need to use title case on 3 toasts. They should be: 
New Card Saved
Card Information Updated
Card Removed
5. Update biometrics prompt: “Firefox requires Face ID to access this information.” The title of this alert can remain the same, just update the body copy.

### Device & build information
* Device: iPhone 12
* Build version: 31868
* First seen version: 31246

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6804)

**Comment by data-sync-user** [comment]
➤ Daniela Arcese commented:

Nishant Bhasin we need to fix these for the 116 string freeze

**Comment by nbhasin2** [comment]
Hi @jeffreygee sent you pm regarding
a) Save and autofill credit cards
b) Firefox requires Face ID to access this information

**Comment by data-sync-user** [comment]
➤ Nishant Bhasin commented:

Emily Wachowiak For the second string I have made, let me know if that's not right? 

Save and autofill cards -> Save and Autofill Cards

**Comment by data-sync-user** [comment]
➤ Nishant Bhasin commented:

Confirmed new string for Face ID (pt5)

Firefox requires Face ID to access your saved logins and encrypted cards.
