### ISSUE TITLE
Tab closing is broken in current TestFlight

### ISSUE THREAD

**Issue by rnewman** [mozilla-mobile/firefox-ios#15161]
[See video](https://youtube.com/shorts/o51GdDYDvBQ?feature=share). 

Here I’m using the long-press menu to close the current tab. 

It’s left in a bad state: a subsequent tab is selected, but the closed tab’s URL is shown, and the content is blank.

This, coupled with losing all of my tabs, marks a five-year low for Firefox iOS reliability; not sure what’s going on…

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6810)

**Comment by lmarceau** [comment]
Hello @rnewman, could you tell us in which version of the application this is happening? Is this on a TestFlight build (if so having the build number would be very helpful), if not is this in a production build?

**Comment by rnewman** [comment]
I see this in TF v32059. One or two previous versions, too.

**Comment by lmarceau** [comment]
Hello! I think this relates to https://github.com/mozilla-mobile/firefox-ios/issues/15029. We're investigating, thank you for raising the problem!

**Comment by OrlaM** [comment]
Confirmed this is related to #15029 and will be fixed by #15204

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Verified as fixed on v115 (32222) with iPhone 13 Pro (15.7.1), iPad Air (15.7), and iPhone 14 (16.4.1).

I was able to close the tabs and the content was displayed correctly for the rest of the open tabs.
