### ISSUE TITLE
[regression] Audio continues to play after the tab is closed

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/firefox-ios#15162]
## Steps to reproduce

1. Open a page that has looping audio or video, such as this tweet: https://twitter.com/shouldhaveanima/status/1671456689424572416/mediaViewer
2. Play the video. 
3. Close the tab while the video is still playing. 

### Expected behavior

The tab’s audio should stop playing, like it does in Safari, Chrome, and Firefox build 9000 (30588) and earlier. 

### Actual behavior

This tab’s audio continues to play. The only way to stop it is to force quit Firefox. 

### Device & build information

**This bug is a regression starting in build 9000 (31007).** In build 9000 (30588) and earlier, audio stops when the tab is closed.

* Device: iPhone 12 running iOS 16.5.1
* Build version: 9000 (32868)
* First seen version: 9000 (31007)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6811)

**Comment by dayana-galeano** [comment]
We've seen a couple of users reporting in App Store reviews that they're experiencing this issue in Firefox for iOS, version 115. We can also confirm that it's still reproducible when testing on our end. 

https://github.com/mozilla-mobile/firefox-ios/assets/108423161/794c0d76-ca24-4457-bb65-f976ae7a3cb5

**Comment by data-sync-user** [comment]
➤ Laurie Marceau commented:

I’ll close this issue so we have only one issue to track this problem. Please see https://mozilla-hub.atlassian.net/browse/FXIOS-7075 ( https://mozilla-hub.atlassian.net/browse/FXIOS-7075|smart-link ) https://github.com/mozilla-mobile/firefox-ios/issues/15722 ( https://github.com/mozilla-mobile/firefox-ios/issues/15722|smart-link ) for progress and QA on the matter.
