### ISSUE TITLE
Incorrect behavior when user chooses to open a new private tab from widgets or 3D touch menu

### ISSUE THREAD

**Issue by alinamoldovan84** [mozilla-mobile/firefox-ios#15165]
## Steps to reproduce

1. Have multiple tabs opened in normal browsing mode 
2. While in normal browsing mode Force close the FF app
3. Open the FF 3D menu and choose "New private tab"

### Expected behavior
A new private tab should open and should be in focus 

### Actual behavior
FF app opens. The latest visited tab is in focus, in our case the latest tab visited in normal browsing mode. The private browsing tab is created  

### Device & build information
* Device:  iPhone 14+ (16.0.3) 
* Build version: v115 (32059) 
* First seen version: v115 (32059) 
### Notes
- Issue reproduces for both cases when Coordinator is On and when coordinator is OFF
- Issue reproduces for normal browsing mode. 
- Issue doesn't reproduce if user opens the app by tapping the FF icon 
- Issue doesn't reproduce if the application was previously in background not force closed  

Attachments: 

https://github.com/mozilla-mobile/firefox-ios/assets/124251579/453d498b-42f3-4fea-9359-587a6dbddd8b

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6813)

**Comment by lmarceau** [comment]
I think this potentially relates to the tab refactor. When I turn the feature flag OFF I can't reproduce this issue anymore.
