### ISSUE TITLE
Create password manager coordinator

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#15193]
Create password manager coordinator

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6821)

**Comment by data-sync-user** [comment]
➤ Orla Mitchell commented:

For QA please test all password settings flows.

**Comment by DianaBarladeanu** [comment]
> ➤ Orla Mitchell commented:
> 
> For QA please test all password settings flows.

Verified as fixed on v9000 (32375) with iPhone SE (15.4).
