### ISSUE TITLE
No "update this card?" prompt after modifying the expiration month

### ISSUE THREAD

**Issue by DianaBarladeanu** [mozilla-mobile/firefox-ios#15191]
**Steps to reproduce**
1. Access https://checkout.stripe.dev and fill in the form with the details of an already saved credit card.
2. Modify the expiration month.
3. Tap on "Pay".

**Expected behavior**
The "Update this card?" prompt is displayed.

**Actual behavior**
The "Update this card?" prompt is NOT displayed.

Device & build information
* Device: iPhone SE (15.4)
* Build version: v9000 (32090)

* First seen version: ? 

**Notes**
!!Please note that the update prompt is displayed after modifying the month if you modify the card name, too.

Attachments: 

https://github.com/mozilla-mobile/firefox-ios/assets/133357955/c47c1a29-00ce-4143-9790-f0b89e5550e8

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6819)

**Comment by nbhasin2** [comment]
@abodea is that still the case for new builds for v116?

**Comment by data-sync-user** [comment]
➤ Stefan Vladut commented:

tested today and couldn’t reproduce this issue

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v118 (33781) with iPhone SE (16.5)

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v118 (33781) with iPhone SE (16.5).
