### ISSUE TITLE
Crash when select all logins in password manager

### ISSUE THREAD

**Issue by FilippoZazzeroni** [mozilla-mobile/firefox-ios#15219]
## Steps to reproduce

Go to password manager in settings, set the view in editing mode and select add all. The crash should happen when there are many cells. 

### Expected behavior
not to crash

### Actual behavior
it crashes 

### Device & build information
* Device: iphone 14 pro 16.4
* Build version: 116

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6831)

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Verified as fixed on v116 (32618) with iPhone 13 Pro (15.7.1).
