### ISSUE TITLE
SKAN Activation Postback should use coarse grained value

### ISSUE THREAD

**Issue by fbertsch** [mozilla-mobile/firefox-ios#15218]
When we [implemented the activation criteria for SKAN](https://github.com/mozilla-mobile/firefox-ios/pull/14370/files), it set the fine grained value to `1` (from `0`, which is what the `first-run` SKAN postback uses).

Now the issue is the postback timings. The first postback is sent after 2 days, and since it's impossible to activate within 2 days, the value will always be (Coarse: Low, Fine: 0).

When the user activates (after 7 days, at least), we will set the values to (Coarse: Low, Fine: 1). The earliest postback this can be sent in is the _second_ one. The problem is that [the second and third postbacks do not include fine-grained values](https://developer.apple.com/documentation/storekit/skadnetwork/receiving_postbacks_in_multiple_conversion_windows#4103230).

If instead we use coarse-grained values (I would say set it to high), that would alleviate this issue.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6830)

**Comment by OrlaM** [comment]
@fbertsch Just to confirm the only change that is required here is to update the post back to use a coarse value of high?

**Comment by data-sync-user** [comment]
➤ Orla Mitchell commented:

This is an SKAdNetwork change, not sure if there is anything to QA here but moving to QA needed just to be sure.

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Verified as fixed on v115 (32222) with iPhone 13 Pro (15.7.1).
