### ISSUE TITLE
iPad/iPhone js ‘prompt’ function immediately returns

### ISSUE THREAD

**Issue by pushcx** [mozilla-mobile/firefox-ios#15244]
## Steps to reproduce
Call `var result = prompt(‘prompt text’);` in js.

### Expected behavior
Javascript execution blocks and the user-entered text is assigned to the `result` variable, [per MDN](https://developer.mozilla.org/en-US/docs/Web/API/Window/prompt) documentation and behavior of every other browser I have available to test.

### Actual behavior
Empty string (or the default text, if provided in the `prompt` call) is _immediately_ assigned to `result` and js execution continues even before the user interacts with the prompt modal. User-supplied text is not assigned to `result`.

### Device & build information
* Device: iPad Pro 2, iPhone 13 Mini
* Build version: Firefox 114.2 (31625), Firefox 114.3 (31916)
* First seen version: ?

### Notes
https://www.javatpoint.com/oprweb/test.jsp?filename=javascript-prompt-dialog-box2

This js example site demonstrates the bug. If you click the `Click me` button on the demo, you’ll see the output page update to say ‘Welcome to javatpoint.com’ before you can interact with the modal dialog. (Depending on screen size, you may need to delete the `<h1>` and `<h2>` and click `Run` at the top to be able to see the output with the keyboard open.)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6840)

**Comment by lmarceau** [comment]
https://github.com/mozilla-mobile/firefox-ios/issues/22650 should fix this
