### ISSUE TITLE
Update theming in Snackbar

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#15269]
Update theming in `Snackbar` and `SnackButton` to use the new theming system following [guidelines](https://github.com/mozilla-mobile/firefox-ios/wiki/Theming-system).

* `Themeable` and `ThemeApplicable` are used where necessary.
* `UIColor.Photon` or `UIColor.theme` should not be called at all.
* LegacyThemeManager should not be used.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6850)

**Comment by imsanchit** [comment]
Hello @data-sync-user, thanks for raising this issue. I have been working on this one in terms of removing dependency on LegacyThemeManager, LegacyTheme, and LegacyDarkTheme and using Themeable with FXColors. There are a few components for which color codes/styles are not specified in ThemeColourPalette and its conforming classes. They are Snackbar, Browser, TableView, and Tab tray. Can someone help me with those colors?

**Comment by imsanchit** [comment]
@lmarceau raised PR for the same, please have a look.
- Removed dependency on `LegacyTheme` and `LegacyThemeManager`.
- Added those new properties in `ThemeColourPalette` for color/style missing.
- Added new requirements in structures `LightTheme` and `DarkTheme`.
- Mentioned previous color codes being used at those places in comments against the new properties in structs.

**Comment by bmihai23** [comment]
Hello @lmarceau, I just want to ask if this task is still available because I would like to work on it. Thank you!

**Comment by data-sync-user** [comment]
➤ Laurie Marceau commented:

For QA it can be tested the snack bar appears properly in light and dark mode

!image-20231113-161332.png|width=754,height=1633!

!image-20231113-161337.png|width=761,height=1635!

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v9000 (36077), with iPhone SE (16.6.1).
