### ISSUE TITLE
Awesomebar suggestions are no longer scrollable

### ISSUE THREAD

**Issue by rnewman** [mozilla-mobile/firefox-ios#15276]
Type something in the URL bar that produces more than three hits. 

Try to scroll the list. It instantly disappears. 

This is broken in current TestFlight, and has been broken for many releases. 

Video attached.

https://github.com/mozilla-mobile/firefox-ios/assets/91722/9623e58c-5a12-453a-a52e-e844fad91084

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6854)

**Comment by nate-gehringer** [comment]
_See also_ #14878

**Comment by lmarceau** [comment]
Hello! I see you have a blank page instead of the homepage, this could be fixed by https://github.com/mozilla-mobile/firefox-ios/issues/14608 ?

**Comment by rnewman** [comment]
@lmarceau not related: I'm talking about the history and bookmark suggestions — "Firefox Suggest" — that pop up for the typed text. Unfortunately you can't see my taps/swipes in the screen recording, because it's from a real device.

That list was scrollable when we built it in ~2015 and for years afterward; some time in the last few months it broke, and now instantly disappears when you try to scroll it.

**Comment by dnarcese** [comment]
CLosing as duplicate as #14608
