### ISSUE TITLE
UPS tracking does not work in Firefox on MacOS

### ISSUE THREAD

**Issue by RandyInNashua** [mozilla-mobile/firefox-ios#15279]
## Steps to reproduce
Enter a tracking number at https://www.ups.com/track?loc=en_US&requester=ST/

### Expected behavior
tracking information is displayed

### Actual behavior
a tracking error is displayed or the page will not load at all.  Page loads fine in Safari and Chrome.

### Device & build information
* Device: ? <iMac 18,3 running macOS Monterey v 12.5
* Build version: ? <114.0.2>
* First seen version: ? <not sure, but this has been happening for at least a few months>

### Notes
Attachments: 

![image](https://github.com/mozilla-mobile/firefox-ios/assets/45078749/f4cb6710-6394-470d-b710-900c676b5efc)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6855)

**Comment by Tomatoshadow2** [comment]
@RandyInNashua please file this on Bugzilla as this is the place to file bugs for Firefox on Mac
