### ISSUE TITLE
Tabs UI does not scroll to current tab but at the first

### ISSUE THREAD

**Issue by clemlesne** [mozilla-mobile/firefox-ios#15283]
## Steps to reproduce
1. Create many tabs, enough to fill multiple vertical screens in the « tabs » view
1. Switch to one of the latest tabs
1. Click on the « tabs » button

### Expected behavior
The scroll should be positioned on the current tab.

### Actual behavior
The scroll is positioned on the first tab. Extremely frustrating wish many tabs.

### Device & build information
* Device: ? iPhone 13 Pro Max, iOS 16.5.1
* Build version: 115.0 (32242)
* First seen version: Many weeks ago, cannot say

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6857)

**Comment by clemlesne** [comment]
This is extremely painful when many pages are open. It has been 4 months since the issue creation, any comments?

**Comment by lmarceau** [comment]
@clemlesne Hello! Thank you for reporting this issue. We are currently working on a refactor of the tabs tray. Once released this will fix this issue 🙏 Have a nice day!

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v125 (40398), with iPhone 15 (17.0).
