### ISSUE TITLE
[Regression] Firefox forgets cookies in first tab

### ISSUE THREAD

**Issue by wvreeven** [mozilla-mobile/firefox-ios#15308]
## Steps to reproduce
Go to a website that requires you to login. Close the tab. Kill Firefox by swiping up from the bottom. Reopen Firefox and go to the same site. You need to login again but don't do this yet!. Go to a different site and then go to the first site again. You're logged in now. 

### Expected behavior
To be logged in when the site is opened the first time. 
### Device & build information
* Device: ? 
iPhone 14 with latest iOS and FF 115.
* Build version: ? 
Firefox 115.0 (32242)
* First seen version: ? 
New
### Notes
Attachments: 

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6873)

**Comment by wvreeven** [comment]
This was (silently?) fixed in Firefox 116.0 (33174).

**Comment by wvreeven** [comment]
Sorry, I was wrong. This regression bug also is present in Firefox 116.0 (33174).

**Comment by lmarceau** [comment]
@wvreeven there's a first bugfix that should help with this issue with the next release https://github.com/mozilla-mobile/firefox-ios/issues/11994

**Comment by wvreeven** [comment]
Duplicate of #11994 .

**Comment by wvreeven** [comment]
This was fixed in Firefox 116.1 (33291). See the linked ticket.
