### ISSUE TITLE
Move BottomSheet to Component library

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#15304]
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6871)

**Comment by data-sync-user** [comment]
➤ Laurie Marceau commented:

For QA, it can be verified that the bottom sheet for credit card autofill and wallpaper works as expected (only the appearance and look of it).

**Comment by DianaBarladeanu** [comment]
Verified as fixed on v9000 (33001) with iPhone SE (16.5). 
I can confirm that the bottom sheet for credit card autofill and wallpaper have the expected appearance.
