### ISSUE TITLE
Missing "Use saved card" option for credit card autofill when switching between fields on a webpage

### ISSUE THREAD

**Issue by nbhasin2** [mozilla-mobile/firefox-ios#15317]
## Steps to reproduce
- Foxfooding Bug: 6/30/2023 12:12:10
- No particular steps
- Foxfooding Notes
- Switching away from the form and go to settings or another tab and then come back, I don't get the "Use saved card" option; when I select another field I see it

### Expected behavior
- "Use saved card" should show when switching to correct field

### Actual behavior
- don't get the "Use saved card" option; when I select another field I see it

### Device & build information
* Device: iPhone
* Build version: 32291
* First seen version: ? 
### Notes
Attachments: 
<img width="317" alt="image" src="https://github.com/mozilla-mobile/firefox-ios/assets/8919439/f90d6e41-5009-4efb-b02e-b3f3a29533b0">

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6876)

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Verified as fixed on v116 (32745) with iPhone 13 Pro (15.7.1).
