### ISSUE TITLE
The font for expiration label looks off for credit card edit screen

### ISSUE THREAD

**Issue by nbhasin2** [mozilla-mobile/firefox-ios#15316]
## Steps to reproduce
- Foxfooding Bug: 6/30/2023 11:52:29
- No particular steps
- Go to Card Autofill Settings
- Tap on an existing card to edit

### Expected behavior
- The expiration font should match other fonts

### Actual behavior
- The font for expiration label looks off

### Device & build information
* Device: iPhone
* Build version: 32291
* First seen version: ? 
### Notes
Attachments: 
<img width="297" alt="image" src="https://github.com/mozilla-mobile/firefox-ios/assets/8919439/03ccb0c1-0a5d-4e0d-aba3-28e862368ee6">

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6874)

**Comment by PARAIPAN9** [comment]
Just checked, and the font is the same as the rest of the labels, maybe because it has capital letters, it gives the illusion that is off.
