### ISSUE TITLE
Improper credit card settings screen constraints

### ISSUE THREAD

**Issue by nbhasin2** [mozilla-mobile/firefox-ios#15315]
## Steps to reproduce
- Foxfooding Bug: 6/30/2023 11:51:49
- No particular steps but from what was mentioned that backgrounding and foregrounding the app when a user has single credit card and they are in Credit Card Autofill Settings, the constraints are incorrect

### Expected behavior
- Constraints should show enable / disable credit card toggle

### Actual behavior
- Incorrect constraints 

### Device & build information
* Device: iPhone
* Build version: 32291
* First seen version: ? 
### Notes
Attachments: 
<img width="316" alt="image" src="https://github.com/mozilla-mobile/firefox-ios/assets/8919439/74ad61bb-4848-4073-a860-7a9732ad9ce4">

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6875)

**Comment by data-sync-user** [comment]
➤ Nishant Bhasin commented:

Closing as there are no particular steps to reproduce it
