### ISSUE TITLE
A11Y - poor color contrast for "Yes" button label in remember the card flow for credit card

### ISSUE THREAD

**Issue by nbhasin2** [mozilla-mobile/firefox-ios#15323]
## Steps to reproduce
- Foxfooding Bug: 6/30/2023 15:41:40 
- No particular steps
- Foxfooding Notes
- Try to perform a remember your card flow for credit card
- (a11y S2, build 9000) The color contrast for "Yes" button label white text against its blue background is not sufficient for any text - it's only 2.4:1 while 4.5:1 or higher is expected for regular text of its size. Note: the measurement was made from a screen shot while on Dark Mode

### Expected behavior
- Requires UX input

### Actual behavior
-  The color contrast for "Yes" button label white text against its blue background is not sufficient for any text

### Device & build information
* Device: iPhone
* Build version: 32291
* First seen version: ? 
### Notes
Attachments: 
<img width="815" alt="image" src="https://github.com/mozilla-mobile/firefox-ios/assets/8919439/5c2d883b-fb15-4da7-820f-d474569d8d94">

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6882)

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Verified as fixed on v117 (33597) with iPhone 13 Pro (15.7.1).
