### ISSUE TITLE
A11Y - The main heading of the bottom sheet has touch area that overlaps with the "X" Close for credit card autofill

### ISSUE THREAD

**Issue by nbhasin2** [mozilla-mobile/firefox-ios#15321]
## Steps to reproduce
- Foxfooding Bug: 6/30/2023 15:35:14
- No particular steps
- Foxfooding Notes
- Try to perform a remember your card flow for credit card
- (a11y low severity, build 9000) The main heading/title of the drawer has active/touch area that overlaps with the "X" Close button's active/touch area that has a low risk to interfere with receiving by the button a tap event emitted by Switch Control or other alternative input device or technology (accessibility ActivationPoint). It's recommended to correct the size of the heading view (accessibilityFrame, likely)

### Expected behavior
-  The main heading of the bottom sheet has touch area that should not overlaps with the "X" Close 

### Actual behavior
-  The main heading of the bottom sheet has touch area that overlaps with the "X" Close 

### Device & build information
* Device: iPhone
* Build version: 32291
* First seen version: ? 
### Notes
Attachments: 
<img width="401" alt="image" src="https://github.com/mozilla-mobile/firefox-ios/assets/8919439/4b031b8b-838c-4a59-97f5-2212617f06a9">

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6881)

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Verified as fixed on v116 (32873) with iPhone 13 Pro (15.7.1).

**Comment by data-sync-user** [comment]
➤ Alina Moldovan commented:

Verified as fixed on v116.1 (33291) with iPhone 14+ (16.0.3).
