### ISSUE TITLE
A11Y - "Save your card information" in for credit card bottom sheet is incorrectly marked as heading 

### ISSUE THREAD

**Issue by nbhasin2** [mozilla-mobile/firefox-ios#15322]
## Steps to reproduce
- Foxfooding Bug: 6/30/2023 15:38:02
- No particular steps
- Foxfooding Notes
- Try to perform a remember your card flow for credit card
- (a11y low severity, build 9000) The "Save your card information..." static text is marked up as heading while it is neither visually nor semantically appears to be such. It's recommended to remove a heading trait from it to avoid including it in the rotor action (navigation by headings) since the heading above it does provide general information about the drawer's functionality (is a heading semantically)

### Expected behavior
-  The "Save your card information..." static text should not be marked up as heading. It's recommended to remove a heading trait from it to avoid including it in the rotor action (navigation by headings) since the heading above it does provide general information about the drawer's functionality (is a heading semantically)

### Actual behavior
-  The "Save your card information..." static text is marked up as heading

### Device & build information
* Device: iPhone
* Build version: 32291
* First seen version: ? 
### Notes
Attachments: 
<img width="392" alt="image" src="https://github.com/mozilla-mobile/firefox-ios/assets/8919439/e793b852-218a-4a77-bd6e-f6e8035f3f5d">

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6880)

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Verified as fixed on v116 (32694) with iPhone 13 Pro (15.7.1).
