### ISSUE TITLE
Notifications settings - Sync notification setting must mimic the Firefox notification setting when the user logs in for the first time

### ISSUE THREAD

**Issue by alinamoldovan84** [mozilla-mobile/firefox-ios#15336]
## Steps to reproduce

1. The Fxa account is not connected
2. Make sure the Firefox notification are On
3. Log into the app using a valid FxA account 
4. check the Notification settings

### Expected behavior
The sync toggle is ON

### Actual behavior
The sync toggle is OFF

### Device & build information
* Device: iPhone 14+ (16.0.3)
* Build version: 116 (32373) 
* First seen version: 114 
### Notes
Attachments: 

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6891)

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v9000 (34235), with iPhone SE (16.6.1).

To be rechecked once the v119 build is officially released.
