### ISSUE TITLE
[Regression] Close last tab and kill FF doesn't really close the tab

### ISSUE THREAD

**Issue by wvreeven** [mozilla-mobile/firefox-ios#15331]
## Steps to reproduce
Open FF and browse to any site. Close the tab and then kill FF before the "reopen tab" button has disappeared. Open FF again and the site will be opened again. This used to work fine in FF 114.

### Expected behavior
FF should start on the home page.

### Actual behavior
FF opens the site that was previously closed. 

### Device & build information
* Device: ? 
iPhone 14 with latest iOS.
* Build version: ? 
Firefox 115.0 (32242)
* First seen version: ? 
Firefox 115.0 (32242). This worked fine in FF 114.
### Notes
Attachments: 

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6887)

**Comment by abodea** [comment]
I was able to reproduce this issue like before when re-opening FF quickly:
on v115.1 (32583) with iPhone 13 Pro (15.7.1), iPhone SE (15.4).

https://github.com/mozilla-mobile/firefox-ios/assets/42831109/587de411-b733-4780-83a5-21d913dea557

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Verified as fixed on v115.1 (32781) with iPhone 13 Pro (15.7.1).

**Comment by wvreeven** [comment]
Thanks for the quick fix. FF is now behaving again as expected.
