### ISSUE TITLE
Change in the navigation for History Recently Closed screen

### ISSUE THREAD

**Issue by dragosb01** [mozilla-mobile/firefox-ios#15333]
## Steps to reproduce
1. Follow the steps from testOpenInNewPrivateTabRecentlyClosedItem() automated steps.
2. Reach the point were the recently closed tab is opened in a new private tab
### Expected behavior
The expected behavior should be determined
### Actual behavior
Starting 116 after pressing Open in Private Tab, the history screen closes and homepage has the focus. See 116.mov attached.
The old behavior was that after pressing Open in Private tab, the history screen remained in focus. See 115.mov attached.
### Device & build information
* iPad Air (5th generation), ios 16.4
* Build version: 116
* First seen version: 116
### Notes: This issues breaks 2 automated tests.
Attachments: 

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6889)

**Comment by dragosb01** [comment]
https://github.com/mozilla-mobile/firefox-ios/assets/134391433/b2943447-3897-43db-b146-667070d45cab


https://github.com/mozilla-mobile/firefox-ios/assets/134391433/db5429ac-83d4-403d-a59f-61566a76bbbe

**Comment by data-sync-user** [comment]
➤ Daniela Arcese commented:

Let’s keep this as the new behaviour
