### ISSUE TITLE
[Regression] Sync and save data button doesn't work

### ISSUE THREAD

**Issue by dragosb01** [mozilla-mobile/firefox-ios#15334]
## Steps to reproduce
1. Run testTapSignInShowsFxAFromRemoteTabPanel automated test
2. Reach Synced tab and select Sync and Save Data button. See attached image.
### Expected behavior
Sync and save data screen should open
### Actual behavior
Selecting Sync and save data button doesn't work
### Device & build information
*iPad Air (5th generation), ios 16.4
Build version: 116
First seen version: 116
### Notes
Attachments: 

![Screenshot 2023-07-05 at 15 32 03](https://github.com/mozilla-mobile/firefox-ios/assets/134391433/77baaf5b-4d74-4217-9f61-9490f2d3ca25)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6890)

**Comment by lmarceau** [comment]
I think this is the same as https://github.com/mozilla-mobile/firefox-ios/issues/15066 ?

**Comment by isabelrios** [comment]
oh right... looks like it is the same @clarmso

**Comment by clarmso** [comment]
Ditto. I have reported the same issue last week.

**Comment by isabelrios** [comment]
Closing as dup of https://github.com/mozilla-mobile/firefox-ios/issues/15066
