### ISSUE TITLE
Page indicator merged with skip button. [UX]

### ISSUE THREAD

**Issue by rkramvs** [mozilla-mobile/firefox-ios#15337]
## Steps to reproduce
Open the application for the first time after a fresh install

### Expected behavior
The page indicator should be placed below the skip button.

### Actual behavior
The page indicator bottom was aligned with the skip button bottom.

### Device & build information
* Device: iPhone 13 Pro Max, iOS 17 beta
* Build version:  115.0
* First seen version: 115.0
### Notes
Attachments: 
<img src="https://github.com/mozilla-mobile/firefox-ios/assets/119879192/7bbeae71-b10c-4a73-946c-6d6c2cdcf11e" width=300>

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6892)

**Comment by data-sync-user** [comment]
➤ Daniela Arcese commented:

Roux Buciu does this relate to https://mozilla-hub.atlassian.net/browse/FXIOS-6468 ( https://mozilla-hub.atlassian.net/browse/FXIOS-6468|smart-link ) ?

**Comment by adudenamedruby** [comment]
@dnarcese  Yes

Though this is a very weird bug.

@rkramvs is this reproducible consistently for you? I've tried to repro but cannot on simulator or either of my devices. And I don't have a Max device to test on a physical.

**Comment by OrlaM** [comment]
It's most likely an iOS 17 bug. Could resolve itself as the beta's progress or we might need to take a look at a workaround closer to the release.

**Comment by rkramvs** [comment]
@adudenamedruby I can’t reproduce it now.

**Comment by rkramvs** [comment]
> It's most likely an iOS 17 bug. Could resolve itself as the beta's progress or we might need to take a look at a workaround closer to the release.

I thought also.

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v118 (33781) with iPhone SE (16.5).
