### ISSUE TITLE
Homepage settings may not be updated right away

### ISSUE THREAD

**Issue by clarmso** [mozilla-mobile/firefox-ios#15363]
## Steps to reproduce
1. Tap hamburger menu.
2. Tap "Settings ⚙️ " menu item.
3. Tap "New Tab".
4. On the "New Tab" page, enter a new URL.
5. Tap "Settings" from upper right corner.

### Expected behavior
The "New Tab" setting is "Custom".

### Actual behavior
The "New Tab" setting has not been changed.

### Device & build information
* Device: iOS Simulator (iPhone 14, iOS 16.4)
* Build version: 117.0 (1)
* First seen version: July 5, 2023 (new this day)
### Notes

Workaround: Navigate away from the settings page and come back. Note that the video includes the workaround.

Attachments: 

https://github.com/mozilla-mobile/firefox-ios/assets/1740517/42d7ddd6-aed0-4082-a58b-8c4dd92409fc

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6905)

**Comment by data-sync-user** [comment]
➤ Laurie Marceau commented:

For QA, this can be tested with the experiment settings coordinator in preview. Checking with the experiment ON and OFF this is solved would be perfect.
