### ISSUE TITLE
Reading list link now opens right away

### ISSUE THREAD

**Issue by clarmso** [mozilla-mobile/firefox-ios#15364]
## Steps to reproduce
1. Enter a URL on the awesome bar to open a website.
2. Click 📜 icon on the awesome bar to enable reading mode.
3. Click "+ 📜 " icon to add the page to the reading list.
4. Tap hamburger menu.
5. Tap "Reading List" menu item.
6. Long press on the newly added page's title.
7. Tap "+" icon from the modal.

### Expected behavior
Old behaviour is that we need to tap the "Done" button on the Reading List first to navigate back to the opened tab.

### Actual behavior
Without tapping "Done", the opened tab is displayed.

### Device & build information
* Device: iOS Simulator (iPhone 14, iOS 16.4)
* Build version: After https://github.com/mozilla-mobile/firefox-ios/commit/1eed6a8202782de52c4e6e2130b1b24bf1c3c1c0
* First seen version: July 1?
### Notes
Attachments: 

https://github.com/mozilla-mobile/firefox-ios/assets/1740517/76a5c0e4-c909-43e6-b2ff-028dbe89bb8f

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6906)

**Comment by data-sync-user** [comment]
➤ Daniela Arcese commented:

Let’s leave this as the new behaviour.
