### ISSUE TITLE
"Your passwords are now protected ..." screen appears in wrong place

### ISSUE THREAD

**Issue by clarmso** [mozilla-mobile/firefox-ios#15361]
## Steps to reproduce
1. Erase all settings from the simulator and install iOS app.
2. Open Firefox.
3. Tap hamburger menu.
4. Tap "Settings ⚙️ ".
5. Scroll down to "Privacy". Tap "Passwords".
6. Enter a random string as the password.
7. Tap "Continue" on the "Your passwords are now protected" screen.
8. Enter a new login.
9. Once on the passwords screen, tap "Password" from the upper left corner.

### Expected behavior
"Your passwords are now protected..." screen is supposed to appear after the password is entered. (Steps 6 and 7 should be reversed

### Actual behavior
1. "Your password are now protected..." screen appears after the password is entere.
2. On the "Passwords" screen, tapping "Passwords" brings me back to the "Your password are now protected..." screen.

### Device & build information
* Device: iOS Simulator (iPhone 14, iOS 16.4)
* Build version: July 5, 2023
* First seen version: First week of July(ish?)
### Notes
Attachments: 

https://github.com/mozilla-mobile/firefox-ios/assets/1740517/0bb1aad8-8175-46a2-b112-294678ac0d89

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6904)

**Comment by lmarceau** [comment]
I think this relates to the changes with settings coordinator. I'll have a look

**Comment by data-sync-user** [comment]
➤ Laurie Marceau commented:

For QA, this can be tested with the experiment settings coordinator in preview. Checking with the experiment ON and OFF this is solved would be perfect.

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Verified as fixed on v116 (32745) with iPhone 13 Pro (15.7.1).

With both coordinators off and on the Your passwords are now protected ... screen appears in the correct place. 

But when opening the passwords from the hamburger menu somehow it can be seen that the redirection is done to the settings (settings is open) but no impact with this.

Laurie Marceaucan you please confirm if this is the correct behavior, I think before when accessing passwords from the hamburger menu the redirection was done to the settings but we were unable to see it, now that the menu is changed (aka we can swipe down to close settings) the way it was changed we can see that it goes to the settings.

**Comment by data-sync-user** [comment]
➤ Laurie Marceau commented:

Andrei Bodea I just realized that in the “before“ we were showing the passwords view without the main settings page, hence why we weren’t seeing it (so clicking the done button brings us back to the webpage we were and there is no way of seeing the main settings page from there). 

Daniela Arcese I guess we want to keep this behavior of showing the passwords without the main settings page?

With coordinators, showing the main page from the hamburger menu to get to passwords

[^without_coordinator_before.MP4]

Without coordinators, showing the passwords directly, can’t go back to the main settings page. Only dismiss.

[^with_coordinator.MP4]

**Comment by data-sync-user** [comment]
➤ Daniela Arcese commented:

Laurie Marceau I am okay with showing the main settings page behind
