### ISSUE TITLE
Credit card logo on the dark mode for empty state in settings does not match theme

### ISSUE THREAD

**Issue by nbhasin2** [mozilla-mobile/firefox-ios#15426]
## Steps to reproduce
- Go to credit card autofill settings 
- Have no cards there 
- See the logo presented while you are in the empty state

### Expected behavior
- Logo should be coloured according to the theme 

### Actual behavior
- Logo does not have correct color and is shown dark for dark theme

### Device & build information
* Device: iPhone
* Build version: 32472
* First seen version: 32472
### Notes
Attachments: 

![image](https://github.com/mozilla-mobile/firefox-ios/assets/8919439/c77bbd2c-5077-4bfb-a5ae-7ec8b3f0452a)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6944)

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Verified as fixed on v116 (32618) with iPhone 13 Pro (15.7.1).
