### ISSUE TITLE
ios端无法登录，提示密码错误

### ISSUE THREAD

**Issue by Seazer-x** [mozilla-mobile/firefox-ios#15450]
### Expected behavior
ios端登录成功

### Actual behavior
提示密码错误

### Device & build information
* Device: iPhone x 16.5
* Build version: 144.4（32125）
* First seen version:  144.4（32125）
### Notes
Attachments: 
![图片](https://github.com/mozilla-mobile/firefox-ios/assets/62045004/57f6622c-8ef9-4f12-be26-6d4ec8c24d10)
![图片](https://github.com/mozilla-mobile/firefox-ios/assets/62045004/9a736193-7d4a-4f40-924b-81ef5a487272)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6949)

**Comment by lmarceau** [comment]
Hello @Seazer-x, would you kindly write the issue you are having in English, with the steps to reproduce the issue? So we make sure we understand what the problem here is. Thank you!

**Comment by clarmso** [comment]
> 



> Hello @Seazer-x, would you kindly write the issue you are having in English, with the steps to reproduce the issue? So we make sure we understand what the problem here is. Thank you!

The user could not log in. The error message saying that the password was incorrect.
