### ISSUE TITLE
Tab will reopen after being closed if app is closed too quickly

### ISSUE THREAD

**Issue by AWiryaman** [mozilla-mobile/firefox-ios#15493]
## Steps to reproduce
1. Open a website in a tab
2. Close the tab
3. Quickly close out the app via the app switcher (I think you need to do this before the "Tab Closed" banner appears
4. Reopen Firefox

### Expected behavior
The closed tab has been closed

### Actual behavior
The tab will still be opened

### Device & build information
* Device: iPhone 12 Pro iOS 16.5.1
* Build version: Firefox 115.0 (32242)
* First seen version: I think this is the first time I've been seeing it
### Notes
Attachments: 

https://github.com/mozilla-mobile/firefox-ios/assets/9123170/b4cd5d9f-144d-4238-8894-5e1babe42e3e

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6980)

**Comment by lmarceau** [comment]
Hello! I believe this duplicates https://github.com/mozilla-mobile/firefox-ios/issues/15331. There's a fix coming for this in v115.1, thank you

**Comment by AWiryaman** [comment]
@lmarceau ah perfect will close ty
