### ISSUE TITLE
Send tab to Firefox on iOS or iPadOS not functional

### ISSUE THREAD

**Issue by glottisfaun0000** [mozilla-mobile/firefox-ios#15506]
## Steps to reproduce
1. Open url in Firefox on macOS
2. Right click tab -> send tab to device -> iPhone or iPad instance of Firefox
### Expected behavior
Notifcation of url received if app closed on iOS/iPadOS, or url opens immediately in a new tab if app is open
### Actual behavior
No notification or url opening on iOS/iPadOS
### Device & build information
* Device: macOS Ventura 13.4.1 (Apple Silicon), iOS/iPadOS 16.5.1
* Build version: macOS: Firefox 155.0.1 (64-bit), iOS Firefox 115.0 (32242)
* First seen version: Has happened in the past https://github.com/mozilla-mobile/firefox-ios/issues/11020 , was fixed
### Notes
Attachments: 

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6985)

**Comment by dnarcese** [comment]
@glottisfaun0000 can you please check what the Firefox settings > Notifications are set to?

**Comment by glottisfaun0000** [comment]
Working now with sync notfications turned on manually! Thanks.
