### ISSUE TITLE
Private Tabs persisted despite closing and reopening app through App Switcher

### ISSUE THREAD

**Issue by maditya-github** [mozilla-mobile/firefox-ios#15549]
## Steps to reproduce
1. Open Firefox app. In settings, make sure "Close Private Tabs When Leaving Private Browsing" is enabled
2. Create one or more Private Tabs and navigate to any website on each one
3. Swipe up from bottom of screen to open the App Switcher
4. Swipe-close Firefox app
5. Reopen Firefox app

### Expected behavior
1. Previously opened Private Tabs should no longer be there when FF is reopened after swipe-close

### Actual behavior
2. Previously opened Private Tabs are open and whatever page they are at reloads 

### Device & build information
* Device: iPhone 12 Pro Max,iOS 16.5.1
* Build version: Firefox 115.0 (32242)
* First seen version: Firefox 115.0 (32242)

### Notes
Attachments: 

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7005)

**Comment by maditya-github** [comment]
Note: The private tabs persist even if I shutdown my phone and tuen it back on

**Comment by lmarceau** [comment]
Thank you @maditya-github for opening this bug. It's being investigated 🙏

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Verified as fixed on v115.1 (32781) with iPhone 13 Pro (15.7.1).

**Comment by maditya-github** [comment]
Works like a charm. Thanks for the quick fix!
