### ISSUE TITLE
Fix image loading nil URL

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#15541]
In Sentry we were sometimes seeing a bunch of `"No letter found for site, which should never happen"` logs, which we don’t want to happen since this means the URL to load the image from is empty.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7003)

**Comment by data-sync-user** [comment]
➤ Laurie Marceau commented:

For QA it can be checked that the tabs tray favicons and images load as expected, as well as the favicons in the search view (when there’s suggestions appearing when we type in the URL bar)

**Comment by DianaBarladeanu** [comment]
Verified as fixed on v9000 (33001) with iPhone SE (16.5). 
The tabs tray fav icons and images load as expected as well as the fav icons in the search view.
