### ISSUE TITLE
Partner code for DuckDuckGo is incorrect

### ISSUE THREAD

**Issue by Standard8** [mozilla-mobile/firefox-ios#15558]
## Steps to reproduce
1. Perform a search on DuckDuckGo
1. Observe the URL (you may need to copy & paste it).

### Expected behavior
The search URL should have `t=ffip` in it.

### Actual behavior
The search URL has `t=fpas` in it.

### Background
This issue was caused by https://github.com/mozilla-mobile/firefox-ios/commit/8b7be4a2c1e299147ad5d5cb404bb721b2b1b7fb

Although `ffip` is listed in duckduckgo.xml, that file is not used.

Only [ddg.xml](https://github.com/mozilla-mobile/firefox-ios/blob/a01deaa081c98434ffcb678a9720723356f099b2/Client/Assets/Search/SearchPlugins/ddg.xml) is used.

[list.json](https://github.com/mozilla-mobile/firefox-ios/blob/a01deaa081c98434ffcb678a9720723356f099b2/Client/Assets/Search/SearchPlugins/list.json) references both `ddg` and `duckduckgo` however, `duckduckgo` is only referenced in  `experimental-hidden` sections that aren't used.

### Proposed Solution
What we should do is:

* Drop all `experimental-hidden` sections from `list.json`, to avoid confusion.
* Remove duckduckgo.xml
* Drop the [drop the `x-moz-tabletsearch` section](https://github.com/mozilla-mobile/firefox-ios/blob/a01deaa081c98434ffcb678a9720723356f099b2/Client/Assets/Search/SearchPlugins/ddg.xml#L18C6-L21) from ddg.xml
  * that section is not used and not required.
* Change the code in ddg.xml to be `ffip`.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7008)

**Comment by dnarcese** [comment]
@Standard8 what is the priority for this?

**Comment by Standard8** [comment]
@dnarcese We think it should be a "as soon as reasonably possible" so that we're using the correct partner code.

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v118 (33781) with iPhone SE (16.5).
