### ISSUE TITLE
Telemetry when system theme toggle is changed does nothing

### ISSUE THREAD

**Issue by lmarceau** [mozilla-mobile/firefox-ios#15565]
When we click the following toggle
![Screenshot 2023-07-13 at 12 42 33 PM](https://github.com/mozilla-mobile/firefox-ios/assets/11338480/20422a71-a1d6-49b6-82a5-a23db9a40607)
Telemetry wrapper [is called](https://github.com/mozilla-mobile/firefox-ios/blob/49e9ff6f90098426d788d5f5a9d2159932c6934b/Client/Frontend/Settings/ThemeSettings/ThemeSettingsController.swift#L134-L138), but not implemented since we get a `"Uninstrumented metric recorded"`.

Do we want this telemetry or should we remove it? @dnarcese

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7012)

**Comment by dnarcese** [comment]
Let's remove it
