### ISSUE TITLE
Settings isn't full page anymore

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#15564]
On iPad, the settings are wrong (see screenshot) with settings coordinator enabled

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXIOS-7011)

**Comment by data-sync-user** [comment]
➤ Laurie Marceau commented:

I was using it on iPhone, and it’s not as fullpage as well. But I kind of like it like that 😆 Daniela Arcese would we want to keep this look on iPhone, but make it full page on iPad? It’s easier to dismiss the settings that way (so a user can dismiss swipping away rather than having to click the Done button).

!Simulator Screenshot - iPhone 14 Pro - 2023-07-13 at 12.51.27.png|width=1179,height=2556!

**Comment by data-sync-user** [comment]
➤ Daniela Arcese commented:

What caused this change? Can you screenshot the iPad experience as well

**Comment by data-sync-user** [comment]
➤ Laurie Marceau commented:

Daniela Arcese it’s cause by the settings coordinator changes (which aren’t released). 

On iPad, so it looks very different that current implementation

!image-20230713-182838.png|width=1640,height=2360!

**Comment by data-sync-user** [comment]
➤ Daniela Arcese commented:

Aarjav Pandya do you have a preference here for both iPhone and iPad?

**Comment by data-sync-user** [comment]
➤ Aarjav Pandya commented:

I would agree with Laurie, and keep the new look for iPhone and Full-Page on iPad.

**Comment by Tomatoshadow2** [comment]
Yes it would be good if on iPhone the settings wasn’t full page, as Lauire mentions, would be a lot easier to swipe away, instead of having to press the done button each time.

**Comment by data-sync-user** [comment]
➤ Alina Moldovan commented:

Validated this issue using the iPhone 14+ (16.0.3) and FF v116 (32873). 

Current behavior is incorrect:  Settings menu is Full screen when coordinator settings is OFF and not Full when coordinator settings is ON 

!Skype_Video (4) (1).mp4|width=1440,height=1920!

**Comment by data-sync-user** [comment]
➤ Alina Moldovan commented:

Validated this issue using FF v116 (32781), iPhone 14+ (16.0.3) and iPad Air 3rd Gen (16.3.1)

With the current implementation (coordinator settings is OFF) Settings menu is displayed full screen for both devices. 

In case the coordinator settings  is ON the Settings menu is full-screen on iPad and not full-screen on iPhone.
