### ISSUE TITLE
Header is cut off on most/all forums running Discourse

### ISSUE THREAD

**Issue by wezm** [mozilla-mobile/firefox-ios#15602]
## Steps to reproduce

1. Visit a [Discourse](https://discourse.org/) forum in Firefox for iOS
2. Attempt to interact with the top header

Example forums:

- https://users.rust-lang.org/
- https://community.openhab.org/
- https://community.keyboard.io/
- https://meta.discourse.org/

### Expected behavior

The header should be visible and able to be interacted with.

### Actual behavior

The website header is under the header of Firefox so it is hidden and untappable.

Note these pages work in Safari.

### Device & build information

* Device: iPhone 14 Pro iOS 16.5.1 (c)
* Build version: 115.0 (32242)
* First seen version: Seems like a new issue (in the last week or so) but can't say for sure.

### Notes

Attachments: 

Screen recording demonstrating issue:

https://github.com/mozilla-mobile/firefox-ios/assets/21787/8e78e646-4f4e-41bc-aaa7-782d63d9ec3b

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7021)

**Comment by lmarceau** [comment]
Hello! Thank you for opening this issue, we have a fix coming your way with https://github.com/mozilla-mobile/firefox-ios/issues/15116

**Comment by wezm** [comment]
Excellent, thank you.
