### ISSUE TITLE
Increase in errors for `tabs.cumulative_count`

### ISSUE THREAD

**Issue by badboy** [mozilla-mobile/firefox-ios#15609]
Since 2023-07-11 we're seeing an increase in `invalid_value` errors from the [`tabs.cumulative_count`](https://dictionary.telemetry.mozilla.org/apps/firefox_ios/metrics/tabs_cumulative_count) metric on release.
This happens if the counter is incremented by `0` or a negative value.

The metric is recorded [in the TelemetryWrapper](https://github.com/mozilla-mobile/firefox-ios/blob/f722d8c53f8160308476f24f55cad538aad275b5/Client/Telemetry/TelemetryWrapper.swift#L237-L241).
The code is unchanged in years, so it must be some other factor.

The increase is visible [in this Looker Explore](https://mozilla.cloud.looker.com/explore/firefox_ios/metrics?qid=tiyaiXYwdShu36AbH45DVE&origin_space=746&toggle=vis).
The fraction of affected clients has a similar uptick (see [the dashboard](https://mozilla.cloud.looker.com/dashboards/977?Channel=release&Submission+Date=14+day+ago+for+14+day)), so this seems to affect users across the board.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7026)

**Comment by nishant2718** [comment]
@dnarcese  Given that we have a quantity metric recording of tabs (normal active, inactive, and private), is this cumulative count telemetry still relevant?

**Comment by data-sync-user** [comment]
➤ Daniela Arcese commented:

Ruoxi Zhao is the cumulative_count metric still useful for you?

**Comment by data-sync-user** [comment]
➤ Nishant Patel commented:

Hi! I don’t know if cumulative_count resets at the end of the day - it doesn’t seem like it. I guess you can restrict to counting for the date you’re interested in, but we have other means available as well. 

I would consider using other options like tabs.open (labeled counter) to track the tabs opened and restrict for the date you’re interested in, https://github.com/mozilla-mobile/firefox-ios/blob/adbc7b871abc4269a5dffb757efe84cb16b97ce3/Client/metrics.yaml#L2794 ( https://github.com/mozilla-mobile/firefox-ios/blob/adbc7b871abc4269a5dffb757efe84cb16b97ce3/Client/metrics.yaml#L2794 ). You can ascertain the totally daily tabs, including whether they’re normal or private as well.
