### ISSUE TITLE
Tapping "Customize homepage" in homescreen doesn't work correctly 

### ISSUE THREAD

**Issue by alinamoldovan84** [mozilla-mobile/firefox-ios#15603]
## Steps to reproduce

1. Fresh install FF
2. Scroll to the bottom of the homescreen  and tap "Customize homepage" 
3. Close the settings 
4. Repeat the second step

### Expected behavior
The home homescreen settings menu opens 

### Actual behavior
"Customize homepage" it doesn’t work second time. "Customize homepage" from homepage only works the first time after Firefox is restarted

### Device & build information
* Device: iPhone 14+(16.0.1) 
* First seen version: ? 
### Notes
Attachments: 

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7022)

https://github.com/mozilla-mobile/firefox-ios/assets/124251579/0c91b50b-a551-4792-892d-0841f78e9b1d

**Comment by data-sync-user** [comment]
➤ Laurie Marceau commented:

This problem can only be reproduced with a fresh install without making any modifications to experiments related to coordinators, so we fall into the default case of 116.

**Comment by data-sync-user** [comment]
➤ Alina Moldovan commented:

Validated as fixed using FF v116 (32820) and iPhone 14+ (16.0.3)
