### ISSUE TITLE
Refactor SensitiveViewController's blurred background with UIVisualEffectView

### ISSUE THREAD

**Issue by FilippoZazzeroni** [mozilla-mobile/firefox-ios#15614]
The blurred background of the `SensitiveViewController` is now done by applying a blur to a screenshot of the a background and is very costly regarding the memory allocation, it would be nice to refactor it as it was done for the `PhotonActionSheet`, with a `UIVisualEffectView`. 
[Related PR](https://github.com/mozilla-mobile/firefox-ios/pull/15555)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7028)

**Comment by utsavDave97** [comment]
@FilippoZazzeroni @lmarceau You guys mind if I take this, I'd love to contribute. Thank you.

**Comment by utsavDave97** [comment]
@FilippoZazzeroni I have the code ready I was just wondering as to how do I test it out in the sense that how do I produce the blur inside Credit Card or Passwords screen? Thank you

**Comment by FilippoZazzeroni** [comment]
@utsavDave97 you just need to background the app, and then open the task manager, you should see the app blurred. Make sure to delete as well the old blur implementation is inside third part source

**Comment by utsavDave97** [comment]
> @utsavDave97 you just need to background the app, and then open the task manager, you should see the app blurred. Make sure to delete as well the old blur implementation is inside third part source

Appreciate it thanks.

**Comment by FilippoZazzeroni** [comment]
you're welcome

**Comment by data-sync-user** [comment]
➤ Laurie Marceau commented:

Reopening since QA wasn’t done. It can be tested that when going to background, credit card and password views are correctly blurred.
