### ISSUE TITLE
Private browsing mode not remembered on beta build

### ISSUE THREAD

**Issue by Tomatoshadow2** [mozilla-mobile/firefox-ios#15625]
## Steps to reproduce

Launch Firefox

open a new private tab.

browse to any site, close tab

Open a new private tab. Close Firefox.

### Expected behavior

Firefox should remain in private browsing mode, until switched to normal browsing mode.

### Actual behavior

Private browsing mode is forgotten on relaunch and normal browsing mode is active.

### Device & build information
* Device: ? iPhone 11 Pro Max on iOS 16.5.1 (c) 
* Build version: ?  Test flight beta build 32745 
* First seen version: ? 32745

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7031)

**Comment by Tomatoshadow2** [comment]
Still spotty on 32873, stays in private mode few times, or will switch to regular browsing mode after reopening from close

**Comment by data-sync-user** [comment]
➤ Daniela Arcese commented:

Yoana Rios Diaz did you fix something in this area recently?

**Comment by yoanarios** [comment]
I worked on the [fix](https://github.com/mozilla-mobile/firefox-ios/pull/15570) for this bug which is partially related. @Tomatoshadow2 can you check if in Settings you have the option **Close Private tabs when leaving private browsing** enabled.
If this option is enabled would explain the behaviour of opening the app on regular tabs
![IMG_5A67496347B1-1](https://github.com/mozilla-mobile/firefox-ios/assets/18538058/25bbe212-1bcb-4f79-a60f-0626426a5dd8)

**Comment by Tomatoshadow2** [comment]
@yoanarios No I have this option turned off

**Comment by Tomatoshadow2** [comment]
Going to close this for now, as first test flight version of 117 works as expected.

**Comment by data-sync-user** [comment]
➤ Alina Moldovan commented:

Verified as fixed on v116.1 (33291) with iPhone 14+ (16.0.3).
