### ISSUE TITLE
Telemetry - bookmarks

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#15620]
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7030)

**Comment by data-sync-user** [comment]
➤ Nishant Patel commented:

The metric types of metrics.mobile_bookmarks_count and metrics.desktop_bookmarks_count are better represented as quantity amounts instead of counters.

**Comment by data-sync-user** [comment]
➤ Nishant Patel commented:

Been looking into this and wanted to point out that to get the quantity & has_desktop telemetry would get reported when a user navigates into subFolders containing bookmarks. That’s the only time codePaths lead into fetching them from the profile.places DB.

**Comment by data-sync-user** [comment]
➤ Nishant Patel commented:

Hello! Some questions around this telemetry ticket, and the relevant context. 

A blanket “hasDesktopBookmarks“ is difficult to report because of our bookmarks setup. We have three kinds of desktop folders that are not deletable (Unsorted bookmarks, bookmarks toolbar, and bookmarks menu). Each folder can contain a single bookmark OR another folder (created by the user). A user can create an indefinite amount of folders before adding a single bookmark to the last folder (the leaf). 

We would have to navigate and count all bookmarks in each subDirectory to have an all encompassing “hasDesktopBookmarks“ data. I consider this a risky operation because it opens a DB connection and utilizes deferred for it. Defered use needs to be minimized as much as possible since it’s a source of cryptic crashes for us. 

What we can do as an alternative is count the number of bookmarks in a given directory a user navigates into (from those two fixed folders). We can report a hasDesktopBookmarks this way, but the problem is that we won’t have a true quantity recording of desktop bookmarks. We only know how many bookmarks are there in that directory. For example, a user can create 12 subdirectories and add 1 bookmark at each level. But we won’t know there’s 12 bookmarks - we’ll only know of them one at a time (or not at all if the user doesn’t navigate down the tree of directories). 

It might be possible to report a bookmarks per subDirectory, if this is useful. 

What’s are your thoughts? Daniela Arcese

**Comment by data-sync-user** [comment]
➤ Nishant Patel commented:

Another question - for reporting +bookmarks.open+ ( https://dictionary.telemetry.mozilla.org/apps/firefox_ios/metrics/bookmarks_open ) via a top site, it might make more sense to be reported under TopSites category, https://github.com/mozilla-mobile/firefox-ios/blob/64dc7ea0e86312301cfbbaa66543a01198fcb601/Client/metrics.yaml#L899 ( https://github.com/mozilla-mobile/firefox-ios/blob/64dc7ea0e86312301cfbbaa66543a01198fcb601/Client/metrics.yaml#L899 ). 

Bookmarks opened from the awesomeBar is being done that way as well, https://github.com/mozilla-mobile/firefox-ios/blob/64dc7ea0e86312301cfbbaa66543a01198fcb601/Client/metrics.yaml#L3473 ( https://github.com/mozilla-mobile/firefox-ios/blob/64dc7ea0e86312301cfbbaa66543a01198fcb601/Client/metrics.yaml#L3473 ). 

I recommend following this approach (and correcting the description of bookmarks.open so it’s not misleading in a different ticket).

Is this okay? Daniela Arcese

**Comment by data-sync-user** [comment]
➤ Daniela Arcese commented:

Ruoxi Zhao can you please answer these 2 questions based on the data you are looking for, thanks

**Comment by data-sync-user** [comment]
➤ Ruoxi Zhao commented:

Daniela Arcese Nishant Patel Here’s the dashboard ( https://sql.telemetry.mozilla.org/dashboard/ios-awesomebar-investigation ). 

  1. The proportion of clients with recorded Awesomebar locations is notably below 100%.
  2. iPad users consistently have a significantly lower Awesomebar location coverage than iPhone users.
  3. Firefox on iOS 13 records awesomebar location for averaging over 90% clients, while on iOS 12  the coverage is less than 1% for 6k DAU.

**Comment by data-sync-user** [comment]
➤ Nishant Patel commented:

Hi Ruoxi Zhao ! Thanks you for providing that info - I'll take a look and see if there’s more questions and get back to you. 

Could you also provide answers for questions regarding bookmarks when you get the chance? There’s two questions, commented below. Thanks!

**Comment by data-sync-user** [comment]
➤ Nishant Patel commented:

Hello Ruoxi Zhao ! Just wondering if you can get to the couple questions below sometime today? Thanks!

**Comment by data-sync-user** [comment]
➤ Ruoxi Zhao commented:

Nishant Patel Thank you for compiling everything. I have a few questions and remarks for clarification:

  1. Will the 'hasDesktopBookmarks' report as false on a particular day if a user didn't access a bookmark directory, even if they possess desktop bookmarks?
  2. If we can't obtain a precise count of desktop bookmarks, it might be best not to introduce the probe to prevent any misunderstandings.
  3. Are you indicating that we have a probe named topsites.bookmark_opened in addition to +bookmarks.open+ ( https://dictionary.telemetry.mozilla.org/apps/firefox_ios/metrics/bookmarks_open )?

**Comment by data-sync-user** [comment]
➤ Nishant Patel commented:

1. No in this case, a ping will not get sent at all if a user doesn’t navigate to the bookmarks panel, and click into one of those three folders. 
  2. That’s right - we won’t be able to get a precise count of desktop bookmarks. We can only get what shows up in the directory they navigate to. 
    1. So just to confirm, do we want to skip adding a probe for desktop bookmarks and the count of them?

  3. No we currently don’t have a topSites.bookmark_opened probe. What I meant to say was that I recommend implementing it that way, instead of adding another label to bookmarks.open ( https://dictionary.telemetry.mozilla.org/apps/firefox_ios/metrics/bookmarks_open ).

**Comment by data-sync-user** [comment]
➤ Ruoxi Zhao commented:

Nishant Patel 

1 & 2. If we can't obtain the precise data we need, then it's best to refrain from adding probes for both 'has_desktop_bookmarks' and 'desktop_bookmarks_count'.

3. Would it be clearer to include the count of topsite bookmarks under 'bookmarks.open'? This would centralize the information and prevent overlooking the topsite bookmark, especially if it's not categorized under 'bookmark.open'.

**Comment by data-sync-user** [comment]
➤ Nishant Patel commented:

Sure that works! Thank you for answering these questions!

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v9000 (33746) with iPhone SE (16.5).

To be rechecked once the official v118 build is released.

bookmarks.folder_add(/)  

"category": "bookmarks",
      "name": "folder_add",
      "timestamp": 4556390
    }More details here ( https://glean-debug-view-dev-237806.firebaseapp.com/pings/Diana/2678fc6d-60c9-4f5c-8d73-e5dd0202728a )

metrics.mobile_bookmarks_count ✅      

"quantity": {95      "bookmarks.mobile_bookmarks_count": 40,

More details here

metrics.has_mobile_bookmarks(/) 

"metrics": {47    "boolean": {48      "bookmarks.has_mobile_bookmarks": true,

More details here ( https://glean-debug-view-dev-237806.firebaseapp.com/pings/Diana/2678fc6d-60c9-4f5c-8d73-e5dd0202728a )

+bookmarks.open+ ( https://dictionary.telemetry.mozilla.org/apps/firefox_ios/metrics/bookmarks_open ) ✅ 

"labeled_counter": {
      "bookmarks.open": {
        "__other__": 3,
        "bookmarks-panel": 3More details here ( https://glean-debug-view-dev-237806.firebaseapp.com/pings/Diana/2678fc6d-60c9-4f5c-8d73-e5dd0202728a )

**Comment by joanne6601** [comment]
thank you . this was helpful

**Comment by data-sync-user** [comment]
➤ Ruoxi Zhao commented:

Stefan Vladut for bookmarks.has_mobile_bookmarks ( https://dictionary.telemetry.mozilla.org/apps/firefox_ios/metrics/bookmarks_has_mobile_bookmarks/ ) and bookmarks.mobile_bookmarks_count ( https://dictionary.telemetry.mozilla.org/apps/firefox_ios/metrics/bookmarks_mobile_bookmarks_count/ ), it has been confirmed that these are currently triggered when a user explicitly goes to the Bookmarks page. However, we need these probes to be sent at startup. Please adjust the probes to reflect this change.

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Validated on v9000 (39856), with iPhone 15 (17.0).

Here are the probes sent at startup:

"category": "firefox_home_page",
58 "extra": {
59 "bookmark_count": "5",
60 "glean_timestamp": "1710758664598"},
62 "name": "recently_saved_bookmark_view",
63 "timestamp": 65963

**Comment by data-sync-user** [comment]
➤ Ruoxi Zhao commented:

Stefan Vladut Diana Andreea Barladeanu Thank you. When will the modified probes (sent at app startup) go live?

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Validated on v125 (40222), with iPhone 15 (17.0).
