### ISSUE TITLE
Crash when "clear private data" is selected from settings

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#15666]
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7046)

**Comment by data-sync-user** [comment]
➤ Laurie Marceau commented:

Happened as well when deleting tab then rapidly scroll on the homepage

**Comment by data-sync-user** [comment]
➤ Laurie Marceau commented:

Same QA comment as for https://mozilla-hub.atlassian.net/browse/FXIOS-5833 ( https://mozilla-hub.atlassian.net/browse/FXIOS-5833|smart-link )

**Comment by DianaBarladeanu** [comment]
Verified as fixed on v9000 (33082) with iPhone SE (16.5).

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Verified as fixed on v117 (33126) with iPhone 13 Pro (15.7.1).
