### ISSUE TITLE
Add test db creation/seeding support for test automation

### ISSUE THREAD

**Issue by jjSDET** [mozilla-mobile/firefox-ios#15662]
We need a helper to create and seed test data for our test automation to use during test execution. This will allow us to start data-driving our tests that use any `places.db` and prepare us for more dynamic test case creation/execution for future tests.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7045)

**Comment by isabelrios** [comment]
I think we can close this as done as you already implemented the script
