### ISSUE TITLE
Adding new folder bookmark or new bookmark omits last character

### ISSUE THREAD

**Issue by FilippoZazzeroni** [mozilla-mobile/firefox-ios#15676]
## Steps to reproduce
Navigate to the Bookmark Panel and create a new bookmark folder or a new bookmark item.

### Expected behavior
The full title assigned to the folder or item is visible.

### Actual behavior
The last character of the title is not visible.

### Device & build information
* Device: Simulator Iphone 14 pro 16.4
* Build version: 117 (1)
* First seen version: ? 
### Notes
Attachments: 

https://github.com/mozilla-mobile/firefox-ios/assets/55580351/a6b68937-d5e8-47b3-a7e5-f49431904dbf

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7050)

**Comment by lmarceau** [comment]
That seems to be something new, I don't get this on v116 or v115

**Comment by FilippoZazzeroni** [comment]
Me neither can't reproduce on the production version

**Comment by FilippoZazzeroni** [comment]
From tests, it seems that the error appears only on simulators, meanwhile on real device it works correctly.

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v9000 (35049), with iPhone SE (16.6.1).
