### ISSUE TITLE
Add debug setting to toggle between Fakespot's prod and staging servers

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/firefox-ios#15691]
QA would like a setting so they can test clients against Fakespot's staging server.

Android issue: [https://bugzilla.mozilla.org/show_bug.cgi?id=1844629](https://bugzilla.mozilla.org/show_bug.cgi?id=1844629)

Desktop issue: [https://bugzilla.mozilla.org/show_bug.cgi?id=1844579](https://bugzilla.mozilla.org/show_bug.cgi?id=1844579)

**Staging backend**
relay: [https://mozilla-ohttp-dev.fastly-edge.com/](https://mozilla-ohttp-dev.fastly-edge.com/)
gateway: [https://stage.ohttp-gateway.nonprod.webservices.mozgcp.net/ohttp-configs](https://stage.ohttp-gateway.nonprod.webservices.mozgcp.net/ohttp-configs)
analysis server: [https://staging.trustwerty.com/](https://staging.trustwerty.com/)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7058)

**Comment by data-sync-user** [comment]
➤ Richard Pappalardo commented:

Are these staging switches in place now (for Android and Desktop)?

**Comment by data-sync-user** [comment]
➤ Winnie Teichmann commented:

Richard Pappalardo they are for iOS - not sure about the other platforms.

**Comment by cpeterso** [comment]
> Are these staging switches in place now (for Android and Desktop)?

Here is the Android bug for a Fakespot prod/staging setting: https://bugzilla.mozilla.org/show_bug.cgi?id=1844629
