### ISSUE TITLE
Status bar no longer has a background in Beta build 32873

### ISSUE THREAD

**Issue by lolrepeatlol** [mozilla-mobile/firefox-ios#15709]
## Steps to reproduce
- Open a webpage (with URL bar on bottom)
- Scroll down

### Expected behavior
- A white bar appears in the background of the status bar

### Actual behavior
- No background for the status bar is present 

### Device & build information
* Device: iPhone X, 16.5.1(c)
* Build version: 32873
* First seen version: I believe this is new in 32873
### Notes
Attachments: 
![image](https://github.com/mozilla-mobile/firefox-ios/assets/17863082/8b04ae34-3b08-4eb2-8f97-f3121b2aa401)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7068)

**Comment by data-sync-user** [comment]
➤ Laurie Marceau commented:

For QA, please make sure

On iPhone, for all 9 combinations:

  * With and without wallpaper
  * With bottom and URL bar
  * On homepage and on a webpage

The status bar works properly has expected. The status bar is opaque only in the case that we have a wallpaper, we’re on homepage, with the bottom URL bar.

On iPad, for all 4 combinations:

  * With and without wallpaper
  * On homepage and on a webpage

The status bar is always opaque.
