### ISSUE TITLE
Customize homepage settings menu is not displayed is a consistent way (iOS coordinator settings - OFF) 

### ISSUE THREAD

**Issue by alinamoldovan84** [mozilla-mobile/firefox-ios#15703]
## Steps to reproduce
1. Fresh install FF 
2. Choose 'Customize homepage' from hamburger menu
3. Choose 'Customize homepage' from homescreen 
4. Check the way the Customize homepage settings menu is not displayed

### Expected behavior
 The Customize homepage settings menu should be displayed in a consistent way 

### Actual behavior
step 2. Customize homepage settings menu is displayed directly. Done button is available 
step 3: The Settings page is displayed for a few than the Customize homepage settings menu is displayed. Done button is not displayed 

### Device & build information
* Device: iPhone 14+ (16.0.3) 
* Build version: 116 (32873) 
* First seen version: 116 
### Notes
Attachments: 

https://github.com/mozilla-mobile/firefox-ios/assets/124251579/898fb4ca-3c42-4941-b7e3-2b922adaa2b7

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7066)

**Comment by DianaBarladeanu** [comment]
Verified as fixed on v117 (33331) with iPhone SE (16.5).
