### ISSUE TITLE
Firefox opens a new blank tab when opening a YouTube video in the YouTube app. (Safari does not.)

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/firefox-ios#15718]
## Steps to reproduce

1. Install the YouTube app from the App Store. 
2. Open a page with an embedded YouTube video, such as https://boardgamegeek.com/video/148204/twilight-imperium-fourth-edition/miami-dice-twilight-imperium-4
3. Tap the video’s play button to play it. 
4. Tap the video’s “YouTube” button to open the video in the YouTube app.
5. Close the YouTube app and switch back to Firefox.

### Expected behavior

The current tab should be the page with the embedded YouTube video, just like Safari. 

### Actual behavior

The current tab is blank. Open the tabs tray and you will see that the original page of still open in a separate tab and Firefox opened a new blank tab when opening the YouTube app. Chrome iOS 114 has this same behavior, opening a new blank tab. 

Why do Firefox and Chrome open blank tabs but Safari does not?

### Device & build information
* Device: iPhone 12 running iOS 16.5.1 (c)
* Build version: 9000 (32853)
* First seen version: I don’t remember; I’ve seen this bug for a long time (maybe even years?), but only reported it now when I saw that Safari behaved differently.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7072)

**Comment by palms** [comment]
Occurring with any of the 3 "opening screen" selections - homepage, last tab or homepage after four hours of inactivity still cause oldest tab to be appear upon opening app.

**Comment by lmarceau** [comment]
Visually this is what it looks like in the tab tray, with the `about:blank` tab being selected.
![IMG_2001](https://github.com/mozilla-mobile/firefox-ios/assets/11338480/84e631d5-985b-4dbd-b087-3bda87617f66)

**Comment by cpeterso** [comment]
Closing this issue about the YouTube app in favor of issue https://github.com/mozilla-mobile/firefox-ios/issues/17571 about links opened in any external app.
