### ISSUE TITLE
New Firefox instance opens first tab

### ISSUE THREAD

**Issue by 371089** [mozilla-mobile/firefox-ios#15715]
## Steps to reproduce

- Select "'last tab" in Firefox settings for "opening screen" in homepage section.
- Have multiple tabs open.
- Close app completely with swipe up from app switcher.
- Re-open Firefox app and it automatically opens the first tab in the tab list, not the latest tab.

### Expected behavior

Previous and assumed normal behavior is Firefox opening last used tab upon clean start when the "last tab" option is checked in settings for homepage.

### Actual behavior

Firefox IOS opening first tab in list, for example, if you have 6 tabs open and the app will open the first tab ever created that exists on the tab view screen instead of the last used tab.

### Device & build information
* Device: Iphone 12 (16.4.1 (a))
* Build version: 32781
* First seen version: 32781

Notes: N/A

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7070)

**Comment by palms** [comment]
Occurring with any of the 3 "opening screen" selections - homepage, last tab or homepage after four hours of inactivity still cause oldest tab to be appear upon opening app.

**Comment by wavygoten** [comment]
Having the same issue on clean start of Firefox ios app. Opens first tab instead of last recently used tab. Bug started occurring this week for myself.

**Comment by data-sync-user** [comment]
➤ Orla Mitchell commented:

This has the same underlying issue as https://mozilla-hub.atlassian.net/browse/FXIOS-7031 ( https://mozilla-hub.atlassian.net/browse/FXIOS-7031|smart-link )  and will be fixed by the same PR.

**Comment by data-sync-user** [comment]
➤ Alina Moldovan commented:

Verified as fixed on v116.1 (33291) with iPhone 14+ (16.0.3).

**Comment by palms** [comment]
Unfortunately issue persists on Firefox 116.0 (33174), iPhone 13 iOS 16.6
