### ISSUE TITLE
Unit Test Intermittent Failure: PocketSponsoredStoriesProviderTests

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/firefox-ios#15725]
This test is failing intermittently both on main and PRs. 

Build
https://app.bitrise.io/build/d8643743-33d3-4c80-9352-241e3acd1150

Failure
~/Tests/ClientTests/Frontend/Home/Pocket/PocketSponsoredStoriesProviderTests.swift:107 - XCTAssertNil failed: "<NSURLCache: 0x6000025696b0>" - Instance should have been deallocated, potential memory leak.

ccing @OrlaM and @adudenamedruby as latest people modifying the test file where this test is.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7076)

**Comment by lmarceau** [comment]
@isabelrios I think we'll be able to close this following work in #15512

**Comment by isabelrios** [comment]
Test stable now. Closing this issue
