### ISSUE TITLE
Audio from Tik Tok auto-played videos doesn't stop after closing the tab

### ISSUE THREAD

**Issue by DrynnBavis** [mozilla-mobile/firefox-ios#15720]
## Steps to reproduce
1. Open a Tik Tok link from any source, in my case it's from another app, Telegram.
2. Watch the clip and let it finish. By default, Tik Tok will begin auto playing a second video right after, usually with something really annoying and loud or generally unpleasant to watch.
3. Try to close that tab in the Firefox iOS app. App closes **but the audio of the auto-played Tik Tok video does not stop**.
4. Only force closing the entire Firefox app will actually stop the audio from playing. Or you can try to tap the auto-played clip to pause it, but instead it opens up the app store to install Tik Tok.

### Expected behavior
Closing the tab that Tik Tok is on will stop the audio from playing.

### Actual behavior
Closing the tab that Tik Tok is on doesn't stop the audio, it continues to play.

### Device & build information
* Device: ?  iPhone 12 mini MJQ03LL/A, 16.5.1 (c)
* Build version: ?  Firefox 115.1 (32781)
* First seen version: ?  Honestly can't recall if this was happening earlier or not.
### Notes
What's interesting is if you close the tab on the ORIGINAL video from the link, it closes just fine and the audio stops as expected. It's specifically the auto-played videos that annoyingly continue past the tab being closed.
Attachments: 

Here's a clip of the bug occurring, happens 100% of the time. Also just a warning the auto played clips after can be triggering, first one contains gun fire and the second one has someone freaking out and swearing.

clip: https://www.youtube.com/shorts/6C5yRlwXYjE

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7073)

**Comment by data-sync-user** [comment]
➤ Laurie Marceau commented:

I’ll close this issue so we have only one issue to track this problem. Please see https://mozilla-hub.atlassian.net/browse/FXIOS-7075 ( https://mozilla-hub.atlassian.net/browse/FXIOS-7075|smart-link ) https://github.com/mozilla-mobile/firefox-ios/issues/15722 ( https://github.com/mozilla-mobile/firefox-ios/issues/15722|smart-link ) for progress and QA on the matter.
