### ISSUE TITLE
Youtube videos keep playing after tab was closed

### ISSUE THREAD

**Issue by tonischumacher1337** [mozilla-mobile/firefox-ios#15722]
## Steps to reproduce
Go to youtube.com. Open any video. Start the video playback. After a couple of seconds, close the tab that had the video playing while the video is playing.
### Expected behavior
The tab closes and video playback stops.
### Actual behavior
The video keeps playing in the background. Or at least the audio does. The only way to stop it is to forcefully kill the app.
### Device & build information
* Device: ?  Ipad 8th gen. IpadOS 16.5
* Build version: ?  Firefox 115.0 (32242)
* First seen version: ?  Firefox 115.0 (32242) idk if its new but i haven‘t noticed it before.
### Notes
Attachments: 

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7075)

**Comment by lmarceau** [comment]
Relates to https://github.com/mozilla-mobile/firefox-ios/issues/15720 and https://github.com/mozilla-mobile/firefox-ios/issues/15599

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Verified as fixed on v116 (33117) with iPhone 13 Pro (15.7.1), iPhone 14+ (16.0.3).

Please note that we added https://github.com/mozilla-mobile/firefox-ios/issues/15837 ( https://github.com/mozilla-mobile/firefox-ios/issues/15837|smart-link )

**Comment by data-sync-user** [comment]
➤ Alina Moldovan commented:

Verified as fixed on v116.1 (33291) with iPhone 14+ (16.0.3).

**Comment by michaelblight** [comment]
This is back as of April 2024

**Comment by data-sync-user** [comment]
➤ Matt Reagan commented:

Note: this issue has regressed but is now being tracked by https://mozilla-hub.atlassian.net/browse/FXIOS-8891 ( https://mozilla-hub.atlassian.net/browse/FXIOS-8891|smart-link )
