### ISSUE TITLE
Alexander just

### ISSUE THREAD

**Issue by alexjalonso** [mozilla-mobile/firefox-ios#15743]
Hey there! Thanks for using Firefox!

If you are having issues with using Firefox make sure to check https://support.mozilla.org/en-US/products/ios first

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7082)

**Comment by lmarceau** [comment]
Hello, I'll close this issue for now as there doesn't seem to be one. Thanks.
