### ISSUE TITLE
Update the setupPanel function in LibraryViewController

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#15773]
Update the setupPanel function in LibraryViewController to use the list of view controllers and a switch statement to determine which view controller to switch to instead of reaching into the view model

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7099)

**Comment by FilippoZazzeroni** [comment]
@lmarceau oh I forgot those I have to add them, I'll do that tomorrow
