### ISSUE TITLE
Small widgets telemetry not implemented 

### ISSUE THREAD

**Issue by lmarceau** [mozilla-mobile/firefox-ios#15798]
Realized we call `TelemetryWrapper` for  `widgetSmallQuickLinkOpenCopied` (with `smallQuickActionClosePrivate`) and `widgetSmallQuickLinkClosePrivateTabs` (with `smallQuickActionClosePrivate`), but it's never actually sent.

Either we implement the missing telemetry so we can make a distinction between small and medium widgets usage, or we revert the code as it was before (it was removed in this [PR](https://github.com/mozilla-mobile/firefox-ios/pull/15637/files#diff-d06f25dcdfed8ee09a88c8334e75264fe121c4bbaee67e33ab6cf16b74a650e7), see `NavigationRouter.swift`). Before we would send the same telemetry call for both medium and small widgets.

dnarcese what would we want?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7112)

**Comment by dnarcese** [comment]
Let's implement!
