### ISSUE TITLE
Telemetry not implemented for lock icon pressed

### ISSUE THREAD

**Issue by lmarceau** [mozilla-mobile/firefox-ios#15799]
Realized we are not sending telemetry when [we are pressing the lock icon](https://github.com/mozilla-mobile/firefox-ios/blob/e168acd0852cb1c12b08d404065089c9484dcf0c/Client/Frontend/Browser/BrowserViewController/BrowserViewController%2BURLBarDelegate.swift#L143) in the URL bar. 

We have telemetry to know if the user has Strict or Standard, or if it's enabled or disabled already.

Either we implement this telemetry, or we remove it. dnarcese what do you think?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7113)

**Comment by dnarcese** [comment]
Let's implement. It may be helpful in the menu restructure to know how often users are using urlbar icons.
