### ISSUE TITLE
CC Expiry date for credit card autofill returns 0/0

### ISSUE THREAD

**Issue by issammani** [mozilla-mobile/firefox-ios#15839]
## Steps to reproduce

See [Bugzilla link](https://bugzilla.mozilla.org/show_bug.cgi?id=1845171#c0).
### Device & build information
* Device: ? 
* Build version: ? 
* First seen version: ? 
### Notes
Attachments: 

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7128)

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Verified as fixed on v117 (33235) with iPhone 13 Pro (15.7.1).
