### ISSUE TITLE
Tab order not retained

### ISSUE THREAD

**Issue by Vollbart** [mozilla-mobile/firefox-ios#15852]
## Steps to reproduce
1. Open Firefox. 
2. Add several tabs. 
3. Change tab order. 
4. Open some tab. 
5. Open tab view. 

### Expected behavior
Tab order is retained. 

### Actual behavior
Tab order is lost and goes back to initial order. 

### Device & build information
* Device: 8 Plus, 16.1.2
* Build version: Firefox 115.1 (32781)
* First seen version: New to this version
### Notes
Attachments: 

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7133)

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

I was not able to reproduce this issue on v117 (33331) with iPhone 13 Pro (15.7.1).

**Comment by Vollbart** [comment]
I can’t reproduce in a private session, but it’s consistent in my regular session. If it helps, some of the tabs have been open for months or longer.
