### ISSUE TITLE
Tabs lost after updating Firefox app for iOS to version 116

### ISSUE THREAD

**Issue by wintmath** [mozilla-mobile/firefox-ios#15883]
* updated Firefox app yesterday via AppStore to version 116
* opened the updated app
* all of my tabs (30-40) were lost
* was signed in to my Firefox account
* re-start of app and iPhone did not help
* iPhone XR, iOS 16.4.1 (c)
* expected solution: get all tabs back

Thanks in advance!

Mathias

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7142)

**Comment by jeremylow** [comment]
Same issue. iPhone 12 Mini.

**Comment by lmarceau** [comment]
Hello, thank you for opening this issue and sorry this happened to you. We have another opened issue to track this [here](https://github.com/mozilla-mobile/firefox-ios/issues/15989).
