### ISSUE TITLE
Disable shopping experience in private browsing mode

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/firefox-ios#15892]
We don't want to show the Fakespot UI or communicate with the Fakespot servers in PBM.

Firefox Android bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1847063

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7149)

**Comment by thatswinnie** [comment]
@cpeterso thanks for creating this. It was actually already done in https://github.com/mozilla-mobile/firefox-ios/issues/15648
