### ISSUE TITLE
Default search engines appear to almost always be reported as "custom" rather than the actual engine

### ISSUE THREAD

**Issue by Standard8** [mozilla-mobile/firefox-ios#15902]
## Steps to reproduce
From monitoring the [default search engine telemetry](https://dictionary.telemetry.mozilla.org/apps/firefox_ios/metrics/search_default_engine) since March, there is a significant trend where it appears nearly all users have search engines being reported as "custom".

In the 111 release #13145 landed, which touched the telemetry code and is likely to have caused this issue. In particular [these changes seem suspect](https://github.com/mozilla-mobile/firefox-ios/pull/13145/files#diff-524f55546265ad910ac7d316533e83ddf19bdd9ae945f65c23f2f5c14306d80e) because there should always be a default engine - if the search engines haven't loaded yet, we should probably be waiting for that to happen before reporting.

### Expected behavior
Telemetry should be reporting the user's actual engine, and only reporting `custom` if it is a third party engine.

### Actual behavior
Telemetry appears to be reporting `custom` all the time.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7153)

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Verified as fixed on v121 (36782) with iPhone 15 Pro Max (17.2).

I was able to find the event and it shows the correct search engine that was selected "string": {55 "search.default_engine": "google-b-1-m".

**Comment by data-sync-user** [comment]
➤ Preethi Issac commented:

Curtis Morales FYI
