### ISSUE TITLE
Firefox for iOS crashes continuously

### ISSUE THREAD

**Issue by andreag87** [mozilla-mobile/firefox-ios#15919]
Hello
Lately I’ve a lot of troubles with Firefox for iOS, I’m currently using iOS 16.6 on iPad and iPhone and Firefox version 116 but this issue was appearing also with previous versions 

once I set the Firefox account in order to synchronize the various devices the app starts to crash sometimes immediately sometimes after 1-2 minutes. This is happening on both devices and here I tried to extract the Firefox log from my iPad 

https://pastebin.mozilla.org/Ltb6w565

do you have an idea on how to solve this issue ? Of course if I remove the Firefox account the app seems to work fine but I really like to have my devices synchronized (so I assume the issue is on the sync part)

thank you very much
Andrea

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7161)

**Comment by andreag87** [comment]
I’ve noticed that the link is expired 

new link https://pastebin.mozilla.org/gfLse2OD

**Comment by lmarceau** [comment]
Hello @andreag87, do you happen to also have access to your [crash log](https://github.com/mozilla-mobile/firefox-ios/wiki/How-to-get-your-crash-logs)? This would be helpful in investigating this issue. Thank you!

**Comment by StefanoCecere** [comment]
i stopped using Firefox iOS because of continue crashes.. since a few months..

i didn't try do logout from Firefox account... i'll try

**Comment by andreag87** [comment]
Hi 
I've tried in the last days to reproduce the error. I still get some crashes time to time but I can't find any crash log on my device. if I search "Client" in Privacy & Security > Analytics & Improvements > Analytics Data I can see only the very old crashes. do you have any suggestions on how I can extract this info? 

thanks!

**Comment by lmarceau** [comment]
@andreag87 I've had instances where I had no crash log whenever the application was crashing on launch, but not when the app was actively running 🤔 Do you want to try the following; crashing the app from a hidden menu to see if you can capture the crash log of that one.
1. Open the settings menu
2. Click 5 times on the app version
3. Click on "Force crash 💥"
4. Just in case, let's make sure to close the iOS settings before getting to the `Analytics Data`. You should hopefully see that crash there.

**Comment by andreag87** [comment]
Hi! Yes doing like that I can see the crash log
[Client-2023-08-18-111015 .txt](https://github.com/mozilla-mobile/firefox-ios/files/12377619/Client-2023-08-18-111015.txt)

let me know if you need other info from my side 
Thanks !
