### ISSUE TITLE
Firefox iOS blocks popup tab

### ISSUE THREAD

**Issue by clarmso** [mozilla-mobile/firefox-ios#15914]
## Steps to reproduce
1. Run a simple webserver that include the following file. Example command: `python3 -m http.server --cgi 8080 --directory test-fixtures`:
https://github.com/mozilla-mobile/firefox-ios/blob/main/test-fixtures/test-window-opener.html
2. Open `http://localhost:8080/test-window-opener.html` using Firefox.

### Expected behavior

The content of the popup page is shown.
![Simulator Screenshot - iPhone 14 - 2023-08-04 at 14 02 59](https://github.com/mozilla-mobile/firefox-ios/assets/1740517/93c21e8a-e88f-4e23-943c-743311b79f24)

### Actual behavior
A blank page is shown.
![Simulator Screenshot - iPhone 14 - 2023-08-04 at 14 53 06](https://github.com/mozilla-mobile/firefox-ios/assets/1740517/d885489f-fc3e-415c-a20c-e5947bdea6c2)

### Device & build information
* Device: iPhone 14 simulator
* Build version: Aug 4 2023
* First seen version: https://github.com/mozilla-mobile/firefox-ios/pull/15889
### Notes
Attachments:

**Comment by isabelrios** [comment]
I think this is the same as the one reported here: https://github.com/mozilla-mobile/firefox-ios/issues/15903, if that's the case I'm closing the latter because this has the PR assigned.

**Comment by data-sync-user** [comment]
➤ Alina Moldovan commented:

Validated this issue using FF v116.1 (33291) and iPhone 14+ (16.0.3). 

The following scenario was verified: 

  * Go to Settings > Block Popup Windows. → The option is enabled.
  * Go to https://deliver.courseavenue.com/PopupTest.aspx ( https://deliver.courseavenue.com/PopupTest.aspx|smart-link )  and tap "Test Pop-up". → The website loads correctly and no popups are displayed.
  * Go to Settings > Block Popup Windows and disable this option. → The option can be disabled.
  * Go to https://deliver.courseavenue.com/PopupTest.aspx ( https://deliver.courseavenue.com/PopupTest.aspx|smart-link )  and tap "Test Pop-up". → Popup is opened in new tab.

The behavior is correct

Isabel Rios Escobar could you please regress this issue with the exact scenario in the bug? thank you!

**Comment by data-sync-user** [comment]
➤ Alina Moldovan commented:

Thank you Isabel Rios Escobar marking this issue as QA Verified.
