### ISSUE TITLE
No way to detect FxiOS from user agent

### ISSUE THREAD

**Issue by zpao** [mozilla-mobile/firefox-ios#15938]
### Expected behavior
UA contains _something_ identifying the browser as Firefox OR identical matching with Mobile Safari so it's treated the same.

### Actual behavior
UA is `Mozilla/5.0 (iPhone; CPU iPhone OS 16_5_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 Safari/605.1.15`

This doesn't match Mobile Safari nor does it uniquely identify as Firefox. This is the worst of both worlds.

### Device & build information
* Device: iPhone 13, iOS 16.5.1
* Build version: 33174
* First seen version: 116

### Notes
See also https://github.com/mozilla-mobile/firefox-ios/pull/15142#issuecomment-1668349828 where this blames to. I commented there but filing an issue for increased visibility.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7169)

**Comment by cpeterso** [comment]
On my iPhone running iOS 16.6, Firefox iOS's UA is: 

`Mozilla/5.0 (iPhone; CPU iPhone OS 16_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 Safari/605.1.15`

And Safari's UA is:

`Mozilla/5.0 (iPhone; CPU iPhone OS 16_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.6 Mobile/15E148 Safari/604.1`

The only differences are that Safari's UA has a different Safari version number and includes `Version/16.6`.

Are you recommending that Firefox use the same Safari version and include `Version/16.6`? I think the Safari version number is based on the underlying WebKit version, so reporting a different version might cause new webcompat issues. For an earlier discussion about adding the  `Version/` token, see https://github.com/mozilla-mobile/firefox-ios/issues/11464.

For comparison, Chrome's UA has the same Safari version as Firefox and also omits `Version/`:

`Mozilla/5.0 (iPhone; CPU iPhone OS 16_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/115.0.5790.160 Mobile/15E148 Safari/604.1`

**Comment by zpao** [comment]
> On my iPhone running iOS 16.6, Firefox iOS's UA is:
> 
> `Mozilla/5.0 (iPhone; CPU iPhone OS 16_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 Safari/605.1.15`

Right. Note that there is now no way to identify the browser as Firefox. At best, UA detectors are identifying this as an unknown version of Mobile Safari (or even just Safari running on iPhone).

> And Safari's UA is:
> 
> `Mozilla/5.0 (iPhone; CPU iPhone OS 16_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.6 Mobile/15E148 Safari/604.1`
> 
> The only differences are that Safari's UA has a different Safari version number and includes `Version/16.6`.

Right. This `Version/16.6` is how many UA detectors actually detect this as Mobile Safari. This seems to be a common way to differentiate from Chrome.

> Are you recommending that Firefox use the same Safari version and include `Version/16.6`? I think the Safari version number is based on the underlying WebKit version, so reporting a different version might cause new webcompat issues. For an earlier discussion about adding the `Version/` token, see #11464.

I'm recommending that _if_ you don't have any other Firefox identifier, which is now the case. Personally, I'd probably prefer reverting to previous behavior and put `FxiOS/...` back in there. But as you noted in that issue, Brave uses the exact UA as Mobile Safari. Arc for iPhone does that too. There is precedent.

> For comparison, Chrome's UA has the same Safari version as Firefox and also omits `Version/`:
> 
> `Mozilla/5.0 (iPhone; CPU iPhone OS 16_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/115.0.5790.160 Mobile/15E148 Safari/604.1`

This is what I think should be brought back for Firefox as well in an ideal world since it has another major player doing it to establish a pattern.

While we're here, let's look at Edge, which actually keeps `Version/` and adds `EdgiOS/`:

`Mozilla/5.0 (iPhone; CPU iPhone OS 16_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) EdgiOS/115.0.1901.203 Version/16.0 Mobile/15E148 Safari/604.1`

**Comment by jscher2000** [comment]
This was changed intentionally to fix the following: https://github.com/mozilla-mobile/firefox-ios/issues/13294

**Comment by zpao** [comment]
> This was changed intentionally to fix the following: https://github.com/mozilla-mobile/firefox-ios/issues/13294

I linked the PR in the issue. I recognize that it was intentional but it results in issues.

**Comment by cpeterso** [comment]
Here is a recent webcompat issue with Firefox iOS, even after we removed `FxiOS/` from Firefox iOS's UA string: https://webcompat.com/issues/126114

I don't have strong feelings about adding or removing `FxiOS/`, as long as websites work in Firefox iOS. I think we should test whether adding `Version/` in https://github.com/mozilla-mobile/firefox-ios/issues/11464 fixes some of these websites.

**Comment by softvision-raul-bucata** [comment]
See also: https://github.com/mozilla-mobile/firefox-ios/issues/16118 and https://github.com/mozilla-mobile/firefox-ios/issues/16020

**Comment by cpeterso** [comment]
To further complicate comparisons, Edge on iOS's UA includes both `EdgiOS/` and `Version/` (though a different version, `16.0`, than Safari's `16.6`, even though they report `AppleWebKit/605.1.15` and `Safari/604.1`:

`Mozilla/5.0 (iPhone; CPU iPhone OS 16_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) EdgiOS/116.0.1938.56 Version/16.0 Mobile/15E148 Safari/604.1`

Looks like the `Safari/604.1` token has been a frozen version for years in Safari and now Chrome and Edge. Firefox should follow the precedent.

**Comment by cpeterso** [comment]
Has this issue been resolved by  https://github.com/mozilla-mobile/firefox-ios/pull/16176? Firefox iOS v117.2’s UA string has the “FxiOS” token again. Can we close this issue now?

I’ve documented the unexpected differences between Firefox’s and Focus’s (moving and desktop) UA string and Safari’s, Chrome’s , and Edge’s and will file a follow-up issue to fix them.

**Comment by zpao** [comment]
From my quick testing, that looks good! Thanks for taking a look. I'll leave this for y'all to close since it's your tracker <3
