### ISSUE TITLE
The thumbnails of the opened tabs are not loaded correctly or cutoff

### ISSUE THREAD

**Issue by Bosturk** [mozilla-mobile/firefox-ios#15943]
## Steps to reproduce
* Have multiple tabs opened
* Force close the FF app
* Open the FF app
* Open the tab tray and check the thumbnails

### Expected behavior
All thumbnails are correctly loaded

### Actual behavior
Some thumbnails are not loaded correctly or cutoff. Please see the attached video

### Device & build information
* Device: iPhone 13 Pro iOS 16.6
* Build version: Firefox 116.0 v33174
* First seen version: Firefox 115

*# 
*## Notes
Similar issue as logged in #15240 and closed in #15166, but without the extra steps.

Attachments: 

<

!--- Screenshots or screen recordings are very helpful for reproducing|width=200,height=183!

-->

[https://github.com/mozilla-mobile/firefox-ios/assets/10183790/40907339-9ed4-43fb-85b6-6a4003b27909](https://github.com/mozilla-mobile/firefox-ios/assets/10183790/40907339-9ed4-43fb-85b6-6a4003b27909)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7174)

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v125 (40222), with iPhone 15 (17.0).
