### ISSUE TITLE
Unable to use password manager on most pages

### ISSUE THREAD

**Issue by Affection4036** [mozilla-mobile/firefox-ios#15964]
## Steps to reproduce
1. Go to a random website (e.g. portal.office.com, reddit.com, etc.)
1. Press to username field.

### Expected behavior
I am expecting my iOS keyboard to offer me to use my 3rd party password manager.

### Actual behavior
Firefox for iOS doesn't offer the 'Passwords..' option. It does offer it when I am tapping the password field, which is not always available on some services. It makes it difficult to use a password manager and proxy e-mails as every password and username/log-in is different. I always have to manually paste the username/e-mailaddress first before I can auto-fill my password and OTP.

### Device & build information
* Device: iPhone XS Max running iOS 16.6
* Build version: 116.1 (33291)
* First seen version: This problem has been there for several months, but it started to bother me so I decided to make a post.
### Notes
Attachments: 
I can only share the screenshot of me missing the option. My iPhone hides the Password field within the iOS keyboard when I try to make a screenshot.
![2023-08-07-10-48-34-16c368](https://github.com/mozilla-mobile/firefox-ios/assets/15652274/58b9b64b-9076-4c11-b047-27e6b89b2007)

Before posting this report I tried asking the same question on [support.mozilla.org](https://support.mozilla.org/en-US/questions/1420527). I think it is a bug, but I tried the following myself to solve the issue:

* Reboot iPhone
* Reinstall Firefox for iOS
* Try another password manager (tried Enpass and Bitwarden)
* Re-enable the password manager within the iOS settings
* Empty cache and other data within Firefox for iOS

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7197)

**Comment by asclepiadae** [comment]
Commenting to confirm that this is an ongoing issue that I experience as well. An example I can think of is patreon.com - the password field is not shown until after the login username is entered. This is the same behaviour as my bank (which is the most frustrating culprit for me! I just would rather not share which bank I use publicly ;-) ) and means entering my username manually, then using the keyboard->password manager pathway once it proceeds to the login's second stage.

**Comment by data-sync-user** [comment]
➤ Daniela Arcese commented:

Notes: 

  * this works in Safari but not in other browsers
  * Safari is probably doing some custom detecting
  * Chrome and Edge offer their browser password manager in these cases (as opposed to system password manager)
