### ISSUE TITLE
ETP says it's ON although it's not selected

### ISSUE THREAD

**Issue by Delphine** [mozilla-mobile/firefox-ios#15981]
Note: this was noticed on iOS screenshots for v117 that the l10n team gets for testing. I was not able to get a hold of an iOS device to test it on an actual device.

Notice the Enhanced Tracking Protection toggle is not selected, however, the string reads "Protections are ON for this site".

I assume it should read "Protections are OFF for this site".

CC @lmarceau and @clarmso 

![iPhone 14-TrackingProtectionDisabledPerSite-03](https://github.com/mozilla-mobile/firefox-ios/assets/399020/3962bc73-9787-4f82-8acc-99abe296331d)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7201)

**Comment by lmarceau** [comment]
So turns out, the string updates if you close and reopen that menu. Still a problem thought so I'll open a quick PR to fix it.

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified on v9000 (33699) with iPhone SE (16.4).

I can confirm that the string updates accordingly when switching the toggle OFF/ON, but if you tap on “Protection Settings”, the Enhanced Tracking Protection toggle is ON even if it was set as OFF in the previous menu. 

I’ve attached a relevant video.

!IMG_0118.MOV|width=272,height=480!

**Comment by data-sync-user** [comment]
➤ Laurie Marceau commented:

So in this case, the ETP is turned off for this website only. It’s a way to white list some websites. So I think this is the expected behavior Diana Andreea Barladeanu

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Thanks Laurie Marceau . 

We’ll recheck it once the official v118 build is released.
