### ISSUE TITLE
[Spike] Investigate if we can script a solution to remove unused strings

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#15991]
It’s only safe to remove strings from current version - 2 because strings continue to get imported into releases that are still being worked on.

Define a process and build a script to automate removing unused strings.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7206)

**Comment by lmarceau** [comment]
This investigation is triggered by conversation in https://github.com/mozilla-mobile/firefox-ios/issues/12157

**Comment by DonalMe** [comment]
As a follow-up requested during the weekly iOS Eng meeting, here is some info on the Firefox Desktop process:
Doc: https://firefox-source-docs.mozilla.org/l10n/crosschannel/index.html
Code: https://searchfox.org/mozilla-central/source/python/l10n/mozxchannel
Supported repos: https://searchfox.org/mozilla-central/source/python/l10n/mozxchannel/__init__.py#39-42
