### ISSUE TITLE
Cleanup RustFxA and Accounts folders

### ISSUE THREAD

**Issue by tarikeshaq** [mozilla-mobile/firefox-ios#16005]
As we prepare to remove the OpenSSL bindings in #16004, we should remove some of the last unused files in the `Accounts` folder, and move the `RustFxA` files into the `Accounts` folder

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7214)

**Comment by data-sync-user** [comment]
➤ Sammy Khamis commented:

This has successfully landed in https://github.com/mozilla-mobile/firefox-ios/pull/17222 ( https://github.com/mozilla-mobile/firefox-ios/pull/17222|smart-link )
