### ISSUE TITLE
The settings menu cannot be accessed after changing the wallpaper and tapping the "View" toast message

### ISSUE THREAD

**Issue by alinamoldovan84** [mozilla-mobile/firefox-ios#16015]
## Steps to reproduce
1. Go to Settings -> Select Firefox Home -> Wallpapers
2. Tap on a wallpaper.
3. Tap "View".
4. Go to Settings menu again 

### Expected behavior
Settings menu opens 

### Actual behavior
Settings menu doesn't open. Also, "Customize Homepage" button on the homepage is not working. 
FF needs restart in order for settings menu to be displayed again. 

### Device & build information
* Device: 14+ (16.0.3), SE (16.4) 
* Build version: 117 (33432) 
* First seen version: 117 (33126) 
### Notes
* issue reproduces only if the user choses to return by tapping "view" button 

Attachments: 

https://github.com/mozilla-mobile/firefox-ios/assets/124251579/452e7ff1-e1eb-4708-aca3-5e5191c92ae1

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7221)

**Comment by rvandermeulen** [comment]
@OrlaM Can you help find someone to investigate this?

**Comment by lmarceau** [comment]
@rvandermeulen it's assigned and in progress already - this is my next priority after the incident.

**Comment by data-sync-user** [comment]
➤ Alina Moldovan commented:

Validated this issue using FF  v117 (33562) and iPhone 14+ (16.0.3). the issue doesn't reproduce anymore
