### ISSUE TITLE
Editing a search phrase loads the first search result at google.se

### ISSUE THREAD

**Issue by softvision-raul-bucata** [mozilla-mobile/firefox-ios#16019]
## Steps to reproduce
1. Navigate to: http://www.google.se/
1. Perform a search query.
1. After the search query is performed, tap inside the search field to edit the query.
1. Observe the result.
### Expected behavior
The tap allows the search query to be edited.
### Actual behavior
The tap triggers the very first search result
### Device & build information

* Device: iPhone SE 2020 running iOS 16
* Build version: Firefox Daylight 116.1 (33291)
* First seen version: Firefox Daylight 116.1 (33291)
### Notes
See: https://github.com/webcompat/web-bugs/issues/125684

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7224)

**Comment by lmarceau** [comment]
This problem potentially has the same cause as https://github.com/mozilla-mobile/firefox-ios/issues/16035
