### ISSUE TITLE
All open tabs are closed in iOS

### ISSUE THREAD

**Issue by noloman** [mozilla-mobile/firefox-ios#16013]
## Logs
Apologies if this is not the right place!
Yesterday it was the third time in like a month that ALL my open tabs (every time it happened, I had 50+ open tabs) got accidentally closed by Firefox. I wasn't doing anything wrong and there's not a fixed pattern with which I could tell you that Firefox closed all of my apps, but last night I was in a flight and I reopened Firefox after disconnecting the flight mode (perhaps this helps?). This is very annoying and I can't afford having my browser close all my open tabs as I need them for work, so unfortunately I will need to move on to another browser (although I don't want to :cry:).

### Device & build information
* Device: iPhone 11
* Build version: 116.1

### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7220)

**Comment by lmarceau** [comment]
Hello, thank you for opening this issue and sorry this happened to you. We have another opened issue to track this [here](https://github.com/mozilla-mobile/firefox-ios/issues/15989).

**Comment by narFnarF** [comment]
@lmarceau The link you provided talks about updating to 116.1. But I can confirm that I lost all my tabs at least 3 times in the past year, so it's not exclusive to this specific version. I lost hundreads of tabs this way :(

I'm not sure but it seems to be related to using the "Send tab to device..." feature to send a tab from my computer to my phone, and they you tap on the notification while Firefox is in the background (or maybe when it's not?)

Device: iPhone 6s, currently running iOS 15.7.8

Workaround: I unplugged my internet modem and used another computer to look at the sync tabs and reopen them. But sometime that doesn't work if you're not quick enough.
