### ISSUE TITLE
When shutting down and restarting phone, first saved tab becomes frozen

### ISSUE THREAD

**Issue by jjSDET** [mozilla-mobile/firefox-ios#16025]
## Steps to reproduce
logged into sync (though may persist without being logged in)

1. Open multiple tabs and private tabs
1. shutdown/restart phone
1. open browser and view the first tab
only the first tab is inactive/frozen
the site, regardless of domain (www.google.com, www.amazon.com, etc) is flagged as having an insecure connection
all other tabs including private tabs work fine

Edit: This seems to occur with the tab that was open while closing the browser and isn't always the first tab in the tab view.

### Expected behavior
The tab should load and not be flagged as an insecure connection

### Actual behavior
The tab is frozen/non-interactable

### Device & build information
* Device: iPhone 14, iOS 16.6
* Build version: 117.0 (33424)
* First seen version: 115.0 (33242) though may happen earlier
### Notes
Attachments: 

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7228)

**Comment by fowl2** [comment]
think this was previously reported here: https://github.com/mozilla-mobile/firefox-ios/issues/16018
