### ISSUE TITLE
Google search 

### ISSUE THREAD

**Issue by RaiseDennis** [mozilla-mobile/firefox-ios#16030]
## Steps to reproduce
Idk just search google I guess 

### Expected behavior
Just pressing the Google search bar should work

### Actual behavior
It weirdly does something 

### Device & build information
* Device: ? iPhone 14 pro max 16.6
* Build version: Firefox 116.1 (33291) 
* First seen version:  Firefox 116.1 (33291)  
### Notes
Attachments: 

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7229)

**Comment by cpeterso** [comment]
I just reported a similar bug: https://github.com/mozilla-mobile/firefox-ios/issues/16035

Is that the same Google behavior you are seeing?
