### ISSUE TITLE
app locks up

### ISSUE THREAD

**Issue by Elliott599** [mozilla-mobile/firefox-ios#16043]
### Device & build information
* Device: ? 16.6
* Build version: ? 116.0 (33174)
* First seen version: ? yes
### Notes
Attachments: 

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7233)

**Comment by Billstevenson9** [comment]
Same issue here, began with the latest update.

**Comment by dnarcese** [comment]
@Elliott599 are you still running into this issue?

**Comment by Elliott599** [comment]
No, thank you for asking.  But I am having a new issue.  I posted on the help forum and have not heard back.  When I view this page - www.rogerebert.com/reviews/ and any review posted, the page continues to refresh every 20s or so and takes me back to the top.  It only happens on that page.  I have given up using Firefox IOS for this page and instead view it in Safari with no problems.  Shall I post this here at Github?

**Comment by dnarcese** [comment]
@Elliott599 yes, please create a new Github issue for it

**Comment by Elliott599** [comment]
thank you
