### ISSUE TITLE
Can't unsubscribe from Testflight mails

### ISSUE THREAD

**Issue by jakobkappel** [mozilla-mobile/firefox-ios#16053]
## Steps to reproduce
* Click link "Unsubscribe" in mail from no_reply@email.apple.com (mailto:firefox-ios-feedback@mozilla.com...)

### Expected behavior
* Be unsubscribed from mails concerning Testflight for Firefox iOS
* Receive confirmation mail

### Actual behavior
* Get mail from mailer-daemon@googlemail.com with the message 

> Your message wasn't delivered to firefox-ios-feedback@mozilla.com because the address couldn't be found, or is unable to receive mail.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7238)

**Comment by data-sync-user** [comment]
➤ Norberto Andres Furlan commented:

This is on Apple side. We can’t do anything about it. Can you try contacting Apple Support? Thanks!
