### ISSUE TITLE
Deeplinks sometimes don't happen when app has been in background for a long period of time

### ISSUE THREAD

**Issue by lmarceau** [mozilla-mobile/firefox-ios#16079]
## Steps to reproduce
1. Install the app
2. Have the application in background for a lot of time (multiple hours)
3. Open the application from a deeplink (example Spotlight search when the application is default browser)

### Expected behavior
The deeplink is opened

### Actual behavior
The deeplink is not opened and you need to try it a second time

### Device & build information
* Device: Any
* Build version: Any
* First seen version: Been a while

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7251)

**Comment by data-sync-user** [comment]
➤ Daniela Arcese commented:

Andrei Bodea can you please test with WhatsApp as well and see if this bug can be closed.https://mozilla-hub.atlassian.net/browse/FXIOS-7312 ( https://mozilla-hub.atlassian.net/browse/FXIOS-7312|smart-link )

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Hello, I will look into it!

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Hello, please note that we tested this with iPhone 13 Pro (16.0.4) on v118 (33974) and everything worked well as expected, even after letting FF in the background over the weekend. 
Can we close this one Daniela Arcese? And maybe re-open in case someone can reproduce again?
