### ISSUE TITLE
Onboarding cards - two cards are displayed for the user to set the default browser 

### ISSUE THREAD

**Issue by alinamoldovan84** [mozilla-mobile/firefox-ios#16082]
## Steps to reproduce
1. Fresh install FF app 
2. Check the 'Set the default browser' onboarding card 

### Expected behavior
'Set the default browser' onboarding card is correctly displayed 

### Actual behavior
'Set the default browser' onboarding card is displayed twice 

### Device & build information
* Device: iPhone 14+ (16.0.3) 
* Build version: 117 (33562) 
* First seen version: 117 (33235)? 
### Notes
* same issue reproduces if user navigates trough onboarding cards using "Show tour" option 
Attachments: 

https://github.com/mozilla-mobile/firefox-ios/assets/124251579/a248f996-1e63-4f6b-8b1d-b9b06f773096

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7254)

**Comment by data-sync-user** [comment]
➤ Daniela Arcese commented:

Roux Buciu any idea what is happening here?

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v118 (33781) with iPhone SE (16.5).
