### ISSUE TITLE
Toast with "Switch" button does not appear on iPad

### ISSUE THREAD

**Issue by clarmso** [mozilla-mobile/firefox-ios#16101]
## Steps to reproduce
(Note: The issue is for iPad only.)

1. Open https://www.example.com.
1. Long press "More information..." link.
1. From the context menu, tap "Open in New Private Tab".

The issue occurs on both normal and private tabs and is reproducible using `testSwitchBetweenPrivateTabsToastButton()` XCUITest.

### Expected behavior
"Switch" button appear on the bottom of the screen. (Same for both normal and private modes.)
![Simulator Screenshot - iPhone 14 - 2023-08-17 at 11 12 18](https://github.com/mozilla-mobile/firefox-ios/assets/1740517/aec761fe-99ff-4d80-99b9-d38a06b6f852)

### Actual behavior
No "Switch" button. A new tab is opened.
![Simulator Screenshot - iPad Air (5th generation) - 2023-08-17 at 11 27 40](https://github.com/mozilla-mobile/firefox-ios/assets/1740517/7da30dd9-f3a9-4118-8d7d-5e22ea416717)

### Device & build information
* Device: iPad Air 5th generation simulator
* Build version: 118.0 (1)
* First seen version: Aug 15, 2023
### Notes
Attachments: 

Behaviour on iPhone (no issue):
https://github.com/mozilla-mobile/firefox-ios/assets/1740517/2f0a865b-2f77-44e6-ba89-4eee37cbc60f

Behaviour on iPad:
https://github.com/mozilla-mobile/firefox-ios/assets/1740517/a52d59c2-8b0b-43e7-a8b6-43497dd8d700

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7258)

**Comment by clarmso** [comment]
The new test is added recently here: https://github.com/mozilla-mobile/firefox-ios/commit/adbc7b871abc4269a5dffb757efe84cb16b97ce3

**Comment by clarmso** [comment]
🤣 The test is supposed to be disabled in iPad. Let me update the test then.
https://github.com/mozilla-mobile/firefox-ios/commit/adbc7b871abc4269a5dffb757efe84cb16b97ce3#diff-530e5105ddd6c2a604069159b93b2c1e6abd1e65dbee2670f08af89c3916db3eR205

**Comment by data-sync-user** [comment]
➤ Norberto Andres Furlan commented:

Clare So is this still an issue or can we close it?

**Comment by clarmso** [comment]
> ➤ Norberto Andres Furlan commented:
> 
> Clare So is this still an issue or can we close it?

Let's close this issue. After reviewing the test, the behaviour of the "Switch" button is applicable to iPhone only.
