### ISSUE TITLE
Firefox with VoiceOver: the left side of the screen is not usable

### ISSUE THREAD

**Issue by francescotissera1211** [mozilla-mobile/firefox-ios#16114]
## Steps to reproduce
1. Turn on VoiceOver through the accessibility page.
2. Open FF, in this case the latest version, 116.0.
### Expected behavior
When navigating the browser's interface the user should be able to navigate it regardless of which side of the screen he touches.
### Actual behavior
When navigating the browser's interface VoiceOver treats the left side of the screen as empty space, while the right side behaves normally.
### Device & build information
* Device: Ipad pro released in 2022 with IOS 16.6
* Build version: ? 
* First seen version: 16.6, f=Firefox 116.0
### Notes
Attachments: 

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7264)

**Comment by lmarceau** [comment]
Hello! Thank you for opening this ticket, we have someone working on [this issue](https://github.com/mozilla-mobile/firefox-ios/issues/16069) right now (I believe it's the same, let us know if it's not).

**Comment by francescotissera1211** [comment]
Thank you for being so prompt! It is still the same, I can confirm.

**Comment by francescotissera1211** [comment]
Update: the issue seems to be fixed with Ff 116.3.

**Comment by lmarceau** [comment]
I'll close this issue for now, thank you!
