### ISSUE TITLE
Integrate application-services that uses NSS backend for OHTTP

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/firefox-ios#16111]
Waiting for @moztcampbell to land https://github.com/mozilla/application-services/pull/5781

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7262)

**Comment by data-sync-user** [comment]
➤ Ted Campbell commented:

This is now merged into firefox-ios.
https://github.com/martinthomson/ohttp/pull/51 ( https://github.com/martinthomson/ohttp/pull/51|smart-link ) 
https://github.com/mozilla/application-services/pull/5781 ( https://github.com/mozilla/application-services/pull/5781|smart-link ) 
https://github.com/mozilla-mobile/firefox-ios/pull/16219 ( https://github.com/mozilla-mobile/firefox-ios/pull/16219|smart-link )
