### ISSUE TITLE
Add a Nimbus config variable that can remotely override the default OHTTP relay URL with a new URL

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/firefox-ios#16112]
https://github.com/mozilla-mobile/firefox-ios/blob/main/nimbus-features/fakespotFeature.yaml

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7263)

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Verified as fixed on v9000 (35319) with iPhone 13 Pro (15.7.1).

Please note that fakespot works as before, no regressions were found based on the URL change in the code.
