### ISSUE TITLE
Make CFRs dismissible only with the close button 

### ISSUE THREAD

**Issue by Verdi** [mozilla-mobile/firefox-ios#16140]
### User Problem
> Current CFRs are too easy to dismiss before I've had a chance to read them.

### Ideas for Solution
> Instead of dismissing them with a tap outside, make them dismiss only if you tap on the close X button. 

Note: we just made this change in Android.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7270)

**Comment by data-sync-user** [comment]
➤ Alina Moldovan commented:

Verified as fixed using V9000 (34750) and iPhone 14+ (16.0.3).

Confirming the the CFR can be dismissed only by taping the X button .
