### ISSUE TITLE
Missing pinned links on the home page

### ISSUE THREAD

**Issue by lmfra** [mozilla-mobile/firefox-ios#16142]
Sometimes the pinned links on the home page are randomly missing after freshly opening Firefox. It only appears after removing Firefox from the app switcher. 

## Steps to reproduce
Issue occurs only sometimes after opening Firefox. It is important to remove Firefox from the app switcher before. 

### Expected behavior
Display the pinned link shortcuts. 

### Actual behavior
Sometimes displaying random visited sites. 

### Device & build information
* Device: iPhone 13 mini, iOS 16.6
* Build version: 116.2 33536
* First seen version: Furst appeared on 113
### Notes
Attachments: 
Should display the pinned shortcuts
![image](https://github.com/mozilla-mobile/firefox-ios/assets/97810383/f9b1c93c-a9ce-403c-a52c-64a1f521ac5e)
Does this instead:
![image](https://github.com/mozilla-mobile/firefox-ios/assets/97810383/728ecd97-cdab-4dc5-80b7-6b48c1ad3e6c)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7271)

**Comment by data-sync-user** [comment]
➤ Norberto Andres Furlan commented:

Andrei Bodea can you confirm that this issue is not happening anymore? Thanks!

**Comment by abodea** [comment]
Hello, @afurlan-firefox please note the following:
iPhone 15 Pro Max (17.1.2) with 118.1 (34739) `the oldest one I had available on TF` and `v9000 (36897)` but I was not able to reproduce this in 50+ tries.
@lmfra can you please check or let us know if this issue is still reproducible to you?
