### ISSUE TITLE
URL bar issues in Firefox 116

### ISSUE THREAD

**Issue by umbralOptimatum** [mozilla-mobile/firefox-ios#16167]
I've noticed several issues with the URL bar since the latest update. I'm not able to reproduce all of them consistently, but they happen often enough that one or more happens per browsing session.

* I have the URL bar set to appear at the top of the screen. Intermittently, when rotating the device to portrait orientation or switching back to Firefox from other apps, the URL bar and navigation bar are superimposed at the top of the screen. Rotating the device fixes this.
* When viewing the New Tabs menu, the active tab is displayed with the title of the first Private Browsing tab. I've noticed this happening both when opening the app and when switching from private browsing. Usually the tab also previews a blank page instead of its actual contents, even when just a homepage, and sometimes opening it just displays the blank page until refreshed somehow.
* When closing a tab with the URL bar focused, the next tab is brought up with the URL bar still focused and displaying its previous contents (i.e. the URL of the previous tab if not edited). This one happens very consistently.

### Device & build information
* Device: iPhone 11, iOS 16.5.1
* Build version: Firefox 116.2 (33536)
* First seen version: unsure, definitely began within the last couple weeks (I update within a day or two of release)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7283)

**Comment by dnarcese** [comment]
Closing as I split this up into individual bugs
