### ISSUE TITLE
Wrong favicon color startpage (dark mode)

### ISSUE THREAD

**Issue by lmfra** [mozilla-mobile/firefox-ios#16188]
## Steps to reproduce
Open a tab with Firefox start page. Open the tab overview. The favicon has a wrong color (dark mode).

### Expected behavior
White colored icon. 

### Actual behavior
Black colored icon on grey background. 

### Device & build information
* Device: iPhone 13 mini, iOS 16.6
* Build version: Firefox 116.4 (33723)
* First seen version: 114 I think
### Notes
Attachments: 
![image](https://github.com/mozilla-mobile/firefox-ios/assets/97810383/1abc5688-9fb3-4a25-9bd7-3496d6d3334c)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7291)

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v9000(32131), with iPhone SE (16.6.1).

To be rechecked once the v119 build is officially released.
