### ISSUE TITLE
LOSE ALL my tabs opened AGAIN and AGAIN from 115.x to 116.4 and not been fixed !

### ISSUE THREAD

**Issue by tp01-gogogo** [mozilla-mobile/firefox-ios#16193]
## Steps to reproduce
Just launch the Firefox
### Expected behavior
all my tabs opened are still there
### Actual behavior
LOSE ALL of the them AGAIN and AGAIN !
### Device & build information
* Device:  iPhone XS, iOS 16.6
* Build version: 116.4(33723) 
* First seen version:  from version 115.x (the issue is ALWAYS there)
### Notes
Lost ALL my tabs on Firefox iOS again and again, come on guys test your stuff before releasing it to the public !!! The issue persists for several versions , and not completely fixed !!! What are you guys busy with? Do you use Firefox in your daily life ? I am very upset. I feel bad, I don't have a lot of time so l like to open tabs of my interesting articles and leave the tabs there for later, and Firefox ruins everything.
Attachments: 
none.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7294)

**Comment by dnarcese** [comment]
Hi @tp01-gogogo this has now been fixed in the 117.1 release. Please let us know if you are still experiencing it.

**Comment by lmarceau** [comment]
Note: The fix was in the 117.2 release!
