### ISSUE TITLE
iOS Firefox home screen favicons shuffled

### ISSUE THREAD

**Issue by TGranny** [mozilla-mobile/firefox-ios#16201]
## Steps to reproduce
Launch Firefox, tap Home button (usually only happens on first launch or relaunch)

### Expected behavior
Home Screen should appear with pinned items with their matching favicons

### Actual behavior
Home Screen appears with items in correct order but favicons are all mismatched. Clicking one and then returning to Home Screen restores proper favicons. 

### Device & build information
* Device: ? iPad 6th gen, iOS 16.6
* Build version: ? Firefox 116.4 (33723)
* First seen version: ? Seen many versions ago
### Notes
Attachments: 

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7297)

**Comment by jens-siebert** [comment]
Just my 2 cents: I've observed the same behaviour on my iPhone 11 and iPad Pro at least for Firefox 116 and 117. However, it is my impression that this shifting also happens during a browsing session when returning to Firefox Home and not only when starting the app. I have no idea how to reproduce this exactly, but it seems to me that the favicons get shuffled whenever the order of the most visited pages changes (e.g. when a new page is added to the list of most visited pages).

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v9000(32131), with iPhone SE (16.6.1).

To be rechecked once the v119 build is officially released.
