### ISSUE TITLE
Links from WhatsApp sometimes don't open on first attempt

### ISSUE THREAD

**Issue by t-p-white** [mozilla-mobile/firefox-ios#16238]
## Steps to reproduce

1. Have Firefox set as the default browser
2. Open a link for a website from a WhatsApp message

### Expected behavior
The link is opened in Firefox

### Actual behavior
The previous tab is still displayed

I have to re-open it again for the link to work as expected. Worth noting, WhatsApp is protected by Screen Lock.

### Device & build information
* Device: iPhone 13 iOS 16.6
* Build version: 117.0
* First seen version: ? Not sure 
### Notes
Attachments: 

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7312)

**Comment by dnarcese** [comment]
This should be fixed in v118. We can re-open if it is not
