### ISSUE TITLE
Home page in iOS has the icons mixed up for recent searches

### ISSUE THREAD

**Issue by cowbells** [mozilla-mobile/firefox-ios#16230]
## Steps to reproduce
Visit a couple of web pages and open a new tab
### Expected behavior
The recent searches show up with the current icons next to them
### Actual behavior
The icons are mixed up. Not always repro’able though
### Device & build information
* Device: ? iPhone 14, version 16.6
* Build version: ? Firefox 116.4 (33723)
* First seen version: ? New
### Notes
Attachments: 

![image](https://github.com/mozilla-mobile/firefox-ios/assets/17821113/b05e8e9d-b2d4-4743-9217-2e83e13cee07)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7308)

**Comment by lmarceau** [comment]
This relates to https://github.com/mozilla-mobile/firefox-ios/issues/14325 (other section, same issue)

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v9000 (34098), with iPhone SE (16.6.1).

To be rechecked once the v119 build is officially released.
