### ISSUE TITLE
Firefox IOS Bug Report

### ISSUE THREAD

**Issue by Teknevra** [mozilla-mobile/firefox-ios#16239]
## Steps to reproduce:
Open Tabs and then leave the App and then return 

### Expected behavior:
Tabs stay open after leaving the App and then returning

### Actual behavior:
Tabs close when leaving app and then returning, i don't lose any of my web pages, but i do have to reopen the Tabs every single time.

### Device & build information
* Device: IPhone 11 
* Build version: iOS 16.6 (20G75)

### Notes
Attachments: 

https://www.dropbox.com/scl/fi/073t9kvj3pxxuixwhz9g3/Firefox.log?rlkey=3zsj0jpbcv8hymu2jwxl276uf&dl=0

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7313)

**Comment by dnarcese** [comment]
Hello, this should be fixed in version 117.1, please let us know if you are still encountering it.
