### ISSUE TITLE
Firefox retains data from Private Browsing Mode

### ISSUE THREAD

**Issue by dmytrodrfv** [mozilla-mobile/firefox-ios#16244]
## Steps to reproduce
1. (Optional) Clear the history/data
1. Open some website in a Private tab
1. Close the tab and return to Normal Mode
### Expected behavior
Firefox shouldn't retain any data from Private Browsing Mode
### Actual behavior
Firefox retains some data
### Device & build information

* Device: iPhone 13 (iOS 16.6)
* Build version: Firefox 117.0 (33736)
* First seen version: Unknown
### Notes
Attachments: 

https://github.com/mozilla-mobile/firefox-ios/assets/144054676/99843aca-d880-44e1-b5a5-54a693e95ce3

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7317)

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v9000 (34959), with iPhone SE (16.6.1).

To be rechecked once the v120 build is officially released.
