### ISSUE TITLE
The recently visited websites are not displayed in the History section

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/firefox-ios#16242]
## Steps to reproduce
1. Launch FF and search for a few websites.
2. Tap on the hamburger menu and access the history section.
### Expected behavior
The History section should be populated with the recently visited websites.
### Actual behavior
The recently visited websites are not displayed in the History section.
### Device & build information
* Device: iPhone 13 Pro (15.7.1) 
* Build version: v9000 (33889) 
* First seen version: N/A 
### Notes
Please note that there are no issues with v118 builds.
Attachments: 

https://github.com/mozilla-mobile/firefox-ios/assets/42831109/896e1fdf-b487-4790-a34c-43f4d1f68628

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7316)

**Comment by isabelrios** [comment]
We realized that the performance tests loading several history items were failing: `PerformanceTests.testPerfHistory100openMenu`

**Comment by clarmso** [comment]
We have numerous tests failing because history is not displayed including DatabaseFixtureTest, HistoryTests.

**Comment by clarmso** [comment]
My investigation indicates that the issue starts at https://github.com/mozilla-mobile/firefox-ios/commit/ad5eba30ce35f7c4fd0462c88bbaeb0f17963301

**Comment by lmarceau** [comment]
@FilippoZazzeroni 👀 Would you want to take a look into this issue?

**Comment by FilippoZazzeroni** [comment]
@lmarceau yes sure, I'm finishing the issue you posted me and then I'll do this one. Thank you

**Comment by FilippoZazzeroni** [comment]
@clarmso unfortunately no, i couldn't work on it this week, i'll try to catch up on the weekend or the first days of the next week

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v9000(32131), with iPhone SE (16.6.1).

To be rechecked once the v119 build is officially released.
