### ISSUE TITLE
Firefox closed all my tabs and is working in a destructive way

### ISSUE THREAD

**Issue by MrHughZ** [mozilla-mobile/firefox-ios#16246]
Hey there! Thanks for using Firefox!

If you are having issues with using Firefox make sure to check https://support.mozilla.org/en-US/products/ios first

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7319)

**Comment by MrHughZ** [comment]
/

**Comment by MrHughZ** [comment]
Apologies, I did not mean to close the issue. My log file is 120mb and not able to be uploaded (every time I try it cancels). I am not very experienced with GitHub, please can you suggest anything?

**Comment by lmarceau** [comment]
@MrHughZ you could maybe try with https://wetransfer.com/ ? It's free for under 2GB

**Comment by MrHughZ** [comment]
[Firefox.zip](https://github.com/mozilla-mobile/firefox-ios/files/12528145/Firefox.zip)

I managed to compress it to a zip - please let me know if this is what you need. Appreciate your help :)

**Comment by lmarceau** [comment]
Thank you very much @MrHughZ !

**Comment by MrHughZ** [comment]
No worries - does anyone have an update for me about why this happened or how I can recover my tabs?

**Comment by OrlaM** [comment]
Very sorry this happened. The issue has been fixed in the latest version 117.1. Unfortunately there is no way to recover the lost tabs. Your history should still be intact so searching there may help find some of them.

**Comment by MrHughZ** [comment]
No worries at all, thank you for taking the time.
