### ISSUE TITLE
Firefox is an unsupported browser at therokuchannel.roku.com

### ISSUE THREAD

**Issue by softvision-raul-bucata** [mozilla-mobile/firefox-ios#16245]
## Steps to reproduce
1. Navigate to: therokuchannel.roku.com
1. Observe the result
    1. Expected behavior
The page loads
    1. Actual behavior
Firefox is not supported
    1. Device & build information

* Device: iPhone Se 2020 iOS 16.0
* Build version: Firefox 117.0 (33736)
* First seen version: 116.4
    1. Notes
Valid location set to US is needed
See also: https://github.com/webcompat/web-bugs/issues/126427

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7318)

**Comment by cpeterso** [comment]
### Steps to reproduce:

1. In Firefox or Focus iOS 116.4, load https://therokuchannel.roku.com/
2. Tap the "X" button to dismiss the "Create a free account" dialog. You don't need an account watch the Roku Channel online, but you do need to be in the US.
3. Tap the "More Details" button for some show.
4. Tap the "Play S1 E1" button.

### Expected Result:

Video playback should work in Firefox and Focus iOS, just like it does in Safari, Chrome, and Edge on iOS.

### Actual Result:

An error message: "This browser isn't supported. FXIOS on iOS is not supported. Try these supported browser(s) instead."

Roku is blocking playback when it sees `FxiOS` in Firefox's UA string.

**Comment by data-sync-user** [comment]
➤ Chris Peterson commented:

Good news! I no longer get an "unsupported browser" error when I log into http://therokuchannel.roku.com ( http://therokuchannel.roku.com|smart-link ) .
