### ISSUE TITLE
favorites searching bug

### ISSUE THREAD

**Issue by smallashash** [mozilla-mobile/firefox-ios#16277]
## Steps to reproduce
enter keywords in the address bar to search for favorites

### Expected behavior
 View all matching favorites or  Provide another favorites search function 

### Actual behavior
the search result list can only display 2 items and cannot be dropped down. 

### Device & build information
* Device: iphone8plus ios16.6
* Build version: firefox117.2(33911)
* 

### Notes
Attachments: 
![_cgi-bin!UNITO-UNDERSCORE!mmwebwx-bin!UNITO-UNDERSCORE!webwxgetmsgimg  MsgID=328360867560234938 skey=@crypt!UNITO-UNDERSCORE!fe8f849b!UNITO-UNDERSCORE!c573888634619e9c5f86decf28bb1452 mmweb!UNITO-UNDERSCORE!appid=wx!UNITO-UNDERSCORE!webfilehelper](https://github.com/mozilla-mobile/firefox-ios/assets/23293847/26af5ed9-a6a0-4433-bab4-7ba0fc63ac46)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7352)

**Comment by dnarcese** [comment]
Hi @smallashash, are there more results if you scroll down? Are you expecting to see more favorites with that keyword?

**Comment by data-sync-user** [comment]
➤ Daniela Arcese commented:

Closing until we get more info.
