### ISSUE TITLE
Lock icon has wrong label

### ISSUE THREAD

**Issue by clarmso** [mozilla-mobile/firefox-ios#16297]
## Steps to reproduce
Sorry, the label can be seen only via automated test.

1. Run `testLockIconSecureConnection()`.

This test opens a website that is secure (https://www.mozilla.org), checks the lock icon, opens an insecured website (https://www.badssl.com) and check the lock icon.

### Expected behavior
`app.buttons[AccessibilityIdentifiers.Toolbar.trackingProtection].label` should contain "Connection not secure".

### Actual behavior
`app.buttons[AccessibilityIdentifiers.Toolbar.trackingProtection].label` contains "Secure Connection".

### Device & build information
* Device: iPhone 14 simulator
* Build version: 9000 (nightly?)
* First seen version: Sept 6-ish
### Notes

The issue is exposed via https://github.com/mozilla-mobile/firefox-ios/pull/16237

Attachments: 

Here's the screenshot with the wrong label.
![Simulator Screenshot - iPhone 14 - 2023-09-07 at 11 26 51](https://github.com/mozilla-mobile/firefox-ios/assets/1740517/19fd7231-d5cf-44e2-b764-7c723a64294c)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7358)

**Comment by clarmso** [comment]
I'll open a PR. Hold tight!!

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v9000 (35002), with iPhone SE (16.6.1).

To be rechecked once the v120 build is officially released.
