### ISSUE TITLE
Cannot move tabs in iPadOS

### ISSUE THREAD

**Issue by adix** [mozilla-mobile/firefox-ios#16333]
Move open tab and then select a different tab and the moved tab reverts to original position.

A moved tab should stay where moved to.

* Device: iPad Pro 10.5 v7.0
* Build version: 117.2
* First seen version: not sure this has ever worked correctly

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7368)

**Comment by data-sync-user** [comment]
➤ Clare So commented:

I confirm that Safari on iPad allows the users to rearrange the tabs. Firefox on iPad does not have such a functionality.

**Comment by adix** [comment]
> ➤ Clare So commented:
> 
> I confirm that Safari on iPad allows the users to rearrange the tabs. Firefox on iPad does not have such a functionality.

Tab can be rearranged in Firefox…they just don’t stay where you put them…this is a bug not a missing function.

**Comment by chrisban** [comment]
Can confirm this is still an issue using latest iPad iOS and Firefox app versions

Demo of said bug: https://share.icloud.com/photos/0f9ZdSyIF7N_o5B9sL3hmz4pg

**Comment by razvanlitianu** [comment]
I can confirm the reorder is buggy, as you can see in the video. 
But tab reorder seems to work meaning the state is preserved and the rearange does not happen. Any tips on how I can reproduce that?

https://github.com/mozilla-mobile/firefox-ios/assets/26011662/f3c8beee-21e7-4eac-badb-41bbf0f1a0b5

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v125 (39935), with iPad Air 3rd gen (17.3).

!original-316256E4-7C0E-4CDD-A4E8-D3B10CD31D15.mp4|width=144,height=192!
