### ISSUE TITLE
Search bar partly covered by keyboard on New Tab page

### ISSUE THREAD

**Issue by markojurkovic** [mozilla-mobile/firefox-ios#16340]
## Steps to reproduce
With toolbar set to appear on the bottom of Firefox rather than the top, tap on the tab preview icon and click on the "plus" sign in the bottom right corner of the screen.

### Expected behavior
New tab page opens, a search bar is fully visible on the bottom of the app, and the (iOS) keyboard appears right under it.

### Actual behavior
Firefox search bar is partly covered by the iOS keyboard, as visible on the attached screenshot.

### Device & build information
* Device: iPhone 12 Pro Max 
* Build version: 117.2 (33911) 
* First seen version: Have seen it with previous versions 
    1. Notes
Attachments: 
![IMG](https://github.com/mozilla-mobile/firefox-ios/assets/9203900/58643dab-8925-4c01-86d1-a03fcd79d2b4)UNITO-UNDERSCORE!1851!

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7373)

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Verified as fixed on v120 (35616) with iPhone 13 Pro (15.7.1) and iPad Pro (16.4).

Please note that I had no issues in all orientations, top/bottom.
