### ISSUE TITLE
Renew Focus / Firefox expired telemetry probes

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/firefox-ios#16358]
The DS team asked that we:

1. Renew the following expired telemetry probes.
1. Set these probes to never expire. We may need to get a new fx-ios-data-stewards review for this.

The expired probes:

* `app.opened_as_default_browser`(expired on 2023-03-14) [Focus] [Firefox]
* `browser_menu.browser_menu_action`(expired on 2023-02-02) [Focus]
* `mozilla_products.has_firefox_installed`(expired on 2022-09-01) [Focus]
* `search_suggestions.autocomplete_arrow_tapped`(expired on 2023-02-14) [Focus]
* `search_suggestions.search_tapped`(expired on 2023-02-14) [Focus]
* `search_suggestions.suggestion_tapped`(expired on 2023-02-14) [Focus]
* `settings_screen.set_as_default_browser_pressed`(expired on 2023-07-20) [Focus] [Firefox]
* `show_search_suggestions.changed_from_settings`(expired on 2023-02-14) [Focus]
* `show_search_suggestions.disabled_from_panel`(expired on 2023-02-14) [Focus]
* `show_search_suggestions.enabled_from_panel`(expired on 2023-02-14) [Focus]

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7380)

**Comment by cpeterso** [comment]
I see that I accidentally reported this Focus bug in the firefox-ios issue tracker. 😅 But we should remove these probes' expiry dates in both Firefox and Focus.

**Comment by nbhasin2** [comment]
Renew events are in Firefox iOS 

Below are the only events on Firefox iOS, I am making an issue on Focus to renew the above mentioned events.

* `app.opened_as_default_browser`(expired on 2023-03-14) [Firefox]
* `settings_screen.set_as_default_browser_pressed`(expired on 2023-07-20) [Firefox]

Will be renewing these for any new events for Firefox iOS it would be best to add ticket for the corresponding events

**Comment by nbhasin2** [comment]
Focus: https://github.com/mozilla-mobile/focus-ios/issues/3854
Firefox: https://github.com/mozilla-mobile/firefox-ios/issues/16374

**Comment by data-sync-user** [comment]
➤ Nishant Bhasin commented:

Firefox iOS PR: https://github.com/mozilla-mobile/firefox-ios/pull/16375 ( https://github.com/mozilla-mobile/firefox-ios/pull/16375|smart-link ) 

Focus iOS PR: https://github.com/mozilla-mobile/focus-ios/pull/3855 ( https://github.com/mozilla-mobile/focus-ios/pull/3855|smart-link )

**Comment by cpeterso** [comment]
@nbhasin2 Can we close this meta issue? It looks like the Firefox and Focus PRs have been merged.

**Comment by nbhasin2** [comment]
Marked as done
