### ISSUE TITLE
Renew events in Firefox iOS

### ISSUE THREAD

**Issue by nbhasin2** [mozilla-mobile/firefox-ios#16374]
Below are the only events on Firefox iOS, I am making an issue on Focus to renew the above mentioned events.

* `app.opened_as_default_browser`(expired on 2023-03-14) [Firefox]
* `settings_screen.set_as_default_browser_pressed`(expired on 2023-07-20) [Firefox]

Will be renewing these for any new events for Firefox iOS it would be best to add ticket for the corresponding events

_Originally posted by nbhasin2 in https://github.com/mozilla-mobile/firefox-ios/issues/16358#issuecomment-1718506671_

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7387)

**Comment by cpeterso** [comment]
@nbhasin2 Can we close this issue? It looks like the PR has been merged.
