### ISSUE TITLE
Replace RoundedButtons(s) in FirefoxAccountSignInViewController

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#16394]
Replace scanButton and emailButton in FirefoxAccountSignInViewController with primary and secondary rounded button from the component library.

Note that scanButton uses setImage, so we could add an optional image to configure the button with the view model.

PR will be similar to [https://github.com/mozilla-mobile/firefox-ios/pull/16417](https://github.com/mozilla-mobile/firefox-ios/pull/16417|smart-link)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7397)

**Comment by akshat3358** [comment]
Do we also need to use setImage in case of primary?

I am not able to understand the issue , can you please explain this.

**Comment by lmarceau** [comment]
Yes the behavior that currently exists in the application should stay the same. We can integrate setting the image through the viewModel of the primaryButton, but that's not mandatory. We can setImage directly on the class as well.

**Comment by JOELPOG** [comment]
So basically we have to replace ResizableButton with primary and secondary button models (with their respective customization which of course includes the setImage customization you mentioned) in scanButton and emailButton, respectively?

**Comment by pelumy** [comment]
@lmarceau,  Is it okay to pick this up? I can see the previous PR has almost finished the task but it has not been reopened for over 3 weeks.

**Comment by data-sync-user** [comment]
➤ Laurie Marceau commented:

For QA it can be tested that the buttons in the sync and save data page are themed properly in light and dark mode and works as expected.

!Screenshot 2023-11-01 at 10.03.17 AM.png|width=475,height=1025!
