### ISSUE TITLE
Add "BETA" label to Review Checker bottom sheet

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/firefox-ios#16398]
![image](https://github.com/mozilla-mobile/firefox-ios/assets/629193/59ffa6a2-6636-483c-82e8-8351fbda3cb2)

Figma: https://www.figma.com/file/VE5xayz3yOSB5qOATUU9Im/Mobile-Shopping-Experience-MVP?type=design&node-id=2678-62307&mode=design&t=1xIKrnNfLC2NWDdX-0

Like desktop bug https://bugzilla.mozilla.org/show_bug.cgi?id=1853071

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7400)

**Comment by OrlaM** [comment]
Just as an FYI this will get rejected by Apple if they spot it during app store submissions. Their terms of service stipulate that you cannot label any part of your app Beta.

**Comment by cpeterso** [comment]
@OrlaM, thanks for the heads up! I've escalated this to UX. They will review alternative labels and update this issue.

The Android team doesn't know if Google has a similar requirement (probably not), but we'll make the same design change on Android to be safe and for consistency.
