### ISSUE TITLE
Replace RoundedButton in DefaultBrowserOnboardingViewController

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#16396]
Replace goToSettingsButton in DefaultBrowserOnboardingViewController with primary button from the component library

PR will be similar to [https://github.com/mozilla-mobile/firefox-ios/pull/16417](https://github.com/mozilla-mobile/firefox-ios/pull/16417|smart-link)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7399)

**Comment by SwiftyTushar** [comment]
Hi, I am beginner in open source and looking forward to contribute. How can access jira task?

**Comment by OrlaM** [comment]
@SwiftyTushar you don't need to access Jira. It's just a copy of the github task used for internal planning.

**Comment by pelumy** [comment]
[FXIOS-Replace-goToSettingsButton-DefaultBrowserOnboardingViewController](https://github.com/pelumy/firefox-ios/tree/FXIOS-Replace-goToSettingsButton-DefaultBrowserOnboardingViewController)

**Comment by data-sync-user** [comment]
➤ Winnie Teichmann commented:

For QA: Please test that the default browser instructions show the button correctly.

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v9000 (35105), with iPhone SE (16.6.1).

To be rechecked once the v120 build is officially released.
