### ISSUE TITLE
URL Bar and Tab bar don't implement `UILargeContentViewerItem` or `UILargeContentViewerInteractionDelegate`

### ISSUE THREAD

**Issue by atfelix** [mozilla-mobile/firefox-ios#16422]
## Steps to reproduce
1. Enable larger accessibility sizes in the settings app
1. Select the largest accessibility font size
1. Navigate to Firefox
1. Navigate to a website with reader mode like en.wikipedia.org
1. Long press on each of the tab bar items, reader mode button, reload button, secure lock button, search engine button or scan QR code button

### Expected behavior
There should be a large content viewer in the middle of the screen displaying some text or icon relaying what the button does

### Actual behavior
Nothing happens

### Device & build information
* Device: iPhone X
* Build version: Firefox 117.2 (33911)

### Notes
You can see the content view in Safari or tap on the open tabs button and long press on the done button, the screen header (`Open Tabs`) in English, the close all tabs button, the add tab button or the segmented control (tabs, private mask, mobile / desktop sync).

Attachments: 

| App | | | | | |
|----|----|----|----|----|----|
| Firefox successful long press |![Open tabs](https://github.com/mozilla-mobile/firefox-ios/assets/16291501/238ca830-125d-40be-ba1b-9d6ccf7bd879) |![Done](https://github.com/mozilla-mobile/firefox-ios/assets/16291501/cfe65db1-9b74-4ec4-bbb2-f3f6811a02ee) |![Plus button](https://github.com/mozilla-mobile/firefox-ios/assets/16291501/999c4303-7ca9-4230-8e17-6fb843bd79ea) |![Close all tabs button](https://github.com/mozilla-mobile/firefox-ios/assets/16291501/dab6d98a-5175-4e3a-a098-2b59657f229a) |![Tabs / private browsing / sync segmented control](https://github.com/mozilla-mobile/firefox-ios/assets/16291501/29be80f3-b392-404a-bf13-331421304f86) |
| Safari |![Back button](https://github.com/mozilla-mobile/firefox-ios/assets/16291501/aad9549b-7e2b-41c9-808e-c355b6788240) |![Voice search button](https://github.com/mozilla-mobile/firefox-ios/assets/16291501/32fb1d20-d384-4b7d-813c-5f3987b5cbcf) |![Reload button](https://github.com/mozilla-mobile/firefox-ios/assets/16291501/2b427c40-ef02-4400-b3f6-cba64030683f) |![aA Menu button](https://github.com/mozilla-mobile/firefox-ios/assets/16291501/de8619e1-b2dc-4a60-8dc6-79078485776a) |![Tabs button](https://github.com/mozilla-mobile/firefox-ios/assets/16291501/c68cce1f-6202-49ba-803b-58147d4100e9) |

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7408)

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v122 (37131), with iPhone 15 (17.0).
