### ISSUE TITLE
IOS Firefox / unprompted new tab opens 

### ISSUE THREAD

**Issue by virtualme01** [mozilla-mobile/firefox-ios#16421]
Starting on a open tab in Firefox, every time I switch to a different app or screen of any kind (Notes, Text, Camera etc), and then return to Firefox — the Firefox tab being returned to flashes quickly and then opens a new blank tab (whereas my intention is to return to the most recently used tab, etc). 

IOS 16.1
Firefox 117.3

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7407)

**Comment by lmarceau** [comment]
Hello! Thank you for opening this bug, could you tell us which option you have set under Settings > Homepage > Opening Screen? It's either `Homepage`, `Last tab` or `Homepage after four hours of inactivity`

**Comment by lmarceau** [comment]
Awesome thank you, I'll close this issue then!
