### ISSUE TITLE
When opening a webpage in Firefox from an external app, Firefox doesn’t automatically switch to said webpage

### ISSUE THREAD

**Issue by rcstyl** [mozilla-mobile/firefox-ios#16425]
## Steps to reproduce

1. Find a link in an app other than Firefox
2. Click on the link

### Expected behavior
Firefox should open a new tab with the webpage from the link and switch over to it.

### Actual behavior
Firefox opens the tab, but it doesn’t switch over to it, instead opening a different tab (usually the last one that was open)

### Device & build information
* Device: iPhone 13 Pro Max, iOS 16.6.1
* Build version: 117.3 (34056)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7410)

**Comment by lmarceau** [comment]
This is normally fixed with v118, with bugfix https://github.com/mozilla-mobile/firefox-ios/issues/16079

**Comment by OrlaM** [comment]
Closing because it's a duplicate.
