### ISSUE TITLE
Incorrect bookmark title is saved when user is undoing a bookmark deletion 

### ISSUE THREAD

**Issue by alinamoldovan84** [mozilla-mobile/firefox-ios#16501]
## Steps to reproduce
1.  Add web page as bookmark 
1. Check the bookmark details: Title, URL and folder 
1. Remove the bookmark 
1. Undo the bookmark deletion
1. Check the bookmark details again 

### Expected behavior
The bookmark details at step 5 should match the bookmark details at step 2. 

### Actual behavior
The web address is saved in both Title and URL fields 

### Device & build information
* Device: iPad Air 3rd gen (17.0) iPhone 14+ (16.0.3) 
* Build version: 118 (34352) 
* First seen version: 114 
### Notes
Attachments: 

https://github.com/mozilla-mobile/firefox-ios/assets/124251579/b8974e22-3faa-4692-9df8-4b7aa095857f

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7446)

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v9000 (36131), with iPhone SE (16.6.1).
