### ISSUE TITLE
Firefox icon is all white on widget

### ISSUE THREAD

**Issue by lmarceau** [mozilla-mobile/firefox-ios#16535]
## Steps to reproduce
* Have a widget with the four actions on your iPhone

### Expected behavior
Firefox icon should be with color

### Actual behavior
Firefox icon has no color
![](https://github.com/mozilla-mobile/firefox-ios/assets/11338480/2aa7b30c-e5cd-4c69-ba0f-ce7914e7df0e)

### Device & build information
* Device: Simulator iPhone 14 pro
* Build version: latest main 7cdea5fb1690a0aef3182c4fa3d685fbbb392291
* First seen version: v119

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7456)

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v9000 (35319), with iPhone SE (16.6.1).

To be rechecked once the v120 build is officially released.
