### ISSUE TITLE
Github repository menu is perma-open on Firefox for iPad

### ISSUE THREAD

**Issue by escapewindow** [mozilla-mobile/firefox-ios#16542]
## Steps to reproduce
Open a Github page while logged in.

### Expected behavior
UI appears normal.

### Actual behavior
UI appears normal, but the menu for "New repository..." is perma-open.
(See attachments)

### Device & build information
* Device: M2 iPad Pro with Magic Keyboard, iPadOS 17.0.1
* Build version:117.3 (34056)
* First seen version: Probably this one, first noticed this this week
### Notes
Attachments: 

![](https://github.com/mozilla-mobile/firefox-ios/assets/826343/f30ec365-4018-4c73-bb0f-c69cd4877b7c)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7459)

**Comment by escapewindow** [comment]
Appears to show up landscape or portrait mode, with or without the magic keyboard attached. It doesn't show up if I'm logged out of Github.

**Comment by DanBurkhardt** [comment]
Reporting the same, for at least two weeks. 

Device:
- iPad Pro Gen 3
- iPadOS 17 (latest)
- Firefox browser (latest)

reproduce:
- reproducible in any orientation, before, and after logging in and out

**Comment by thinkontheclock** [comment]
Reproduced here, also. 

- iPad 7th gen
- iPadOS 17 Beta
- Firefox latest
