### ISSUE TITLE
Mozilla Account screen's title "account" is not capitalized

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/firefox-ios#16559]
## Steps to reproduce

1. Log into your Firefox/Mozilla Account in Firefox.
2. Open Firefox menu.
3. Open your account menu item.

### Expected behavior

The screen title should be capitalized "Account".

### Actual behavior

The screen title is "account", not capitalized. See the attached screenshot.

### Device & build information

* Device: iPhone 15 Plus running iOS 17.0.2
* Build version: **This bug is a regression in TestFlight build 9000 (34412).** I tested the previous build, 9000 (33293), and the account screen's title was capitalized "Firefox Account".
* First seen version: 9000 (34412)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7464)

**Comment by cpeterso** [comment]
![image](https://github.com/mozilla-mobile/firefox-ios/assets/629193/2d71970a-e066-4735-9ac3-104fbdff2b4d)

**Comment by cpeterso** [comment]
Before:

![image](https://github.com/mozilla-mobile/firefox-ios/assets/629193/6ccb398f-5488-4cbc-b40b-2a4077c360d9)

**Comment by Chirag57** [comment]
<img width="328" alt="Screenshot 2023-09-24 at 11 47 50 PM" src="https://github.com/mozilla-mobile/firefox-ios/assets/89180722/d4ded0e1-15d1-4909-bb3d-6f2453cd3e33">

Device: Simulator iPhone 15 Plus running iOS 17.0

**Comment by cpeterso** [comment]
This bug is fixed in build 9000 (34498). 🎉
