### ISSUE TITLE
GitHub’s “New repository” drop-down menu opens automatically in landscape orientation

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/firefox-ios#16562]
## Steps to reproduce
1. Log into a GitHub account. 
1. Rotate phone to landscape orientation. 

### Expected behavior
GitHub’s “New repository” drop-down menu should not open automatically. 

### Actual behavior
GitHub’s “New repository” drop-down menu opens automatically. See the attached screenshot. 

i can also reproduce in Focus 117.0 (17203), but I can’t reproduce this in Safari, Chrome, or Edge. What is different about Firefox and Focus? I can still reproduce if I turn off Tracking Protection, so it doesn’t seem to be caused by some script being blocked. Does the User-Agent string make a difference?

### Device & build information
* Device: iPhone 15 Plus running iOS 17.0.2
* Build version: TestFlight build 9000 (34412)
* First seen version: i don’t know but I can reproduce in 117.3 (34506).

### Notes
Attachments: 
![image](https://github.com/mozilla-mobile/firefox-ios/assets/629193/48ab8620-cb6e-435f-9577-5125e17639d2)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7465)

**Comment by lmarceau** [comment]
Relates to https://github.com/mozilla-mobile/firefox-ios/issues/16542

**Comment by data-sync-user** [comment]
➤ Chris Peterson commented:

I can no longer reproduce this bug. I’m testing build 9000 (45624) on iOS 18.0.
