### ISSUE TITLE
[Experiment] No expose events are generated for the ECO messaging Nimbus experiment

### ISSUE THREAD

**Issue by Softvision-PatriciuPop** [mozilla-mobile/firefox-ios#16579]
## [Prerequisites]:
* Have the latest Release 118.0 Testflight build installed.
* Have a profile enrolled in the "mobile-default-browser-homepage-banner-copy-test-ios" experiment.

## [Steps to reproduce]:
1. Open the Firefox app with the Glean telemetry command and open a new tab.
1. Tap the "Learn how" and "Go to Settings" buttons.
1. Close Firefox and navigate to https://debug-ping-preview.firebaseapp.com/
1. Search for the chosen tag and observe the telemetry events.

## [Expected result]:
* An exposed event is displayed for the experiment.

## [Actual result]:
* No exposed events are generated.

## [Device & build information]:
* iPhone 11 - iOS 16.2
* iPhone SE - iOS 16.2

## [Affected versions]:
* Firefox Release 118.0 (34465)
* Firefox Release 117.3 (34465)

## [Notes]:
* The issue is not reproducible on Firefox 116.4 (33723)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7469)

**Comment by dnarcese** [comment]
@Softvision-PatriciuPop is the only problem that the exposure event is not generated? Does the correct message still get shown?

**Comment by Softvision-PatriciuPop** [comment]
Yes, the correct messages are displayed, only the exposure events are not showing up.
