### ISSUE TITLE
Only the "Fakespot by Mozilla" text in "Review checker is powered by Fakespot by Mozilla" should be linked

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/firefox-ios#16590]
## Steps to reproduce

1. Open the Fakespot bottom sheet.
2. Scroll to the bottom and look at the "Review checker is powered by Fakespot by Mozilla." text.

### Expected behavior

On Android and desktop, only the "Fakespot by Mozilla" text is linked, like "Review checker is powered by [Fakespot by Mozilla](https://www.fakespot.com/)."

### Actual behavior

On iOS, the entire sentence is linked, like "[Review checker is powered by Fakespot by Mozilla](https://www.fakespot.com/)."

### Device & build information

* Device: iPhone 15 Plus running iOS 17.0.2
* Build version: 9000 (34498)

Firefox desktop screenshot:
![image](https://github.com/mozilla-mobile/firefox-ios/assets/629193/d07a6298-1434-4901-8d14-a985539e0960)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7474)

**Comment by cpeterso** [comment]
iOS screenshot:
![image](https://github.com/mozilla-mobile/firefox-ios/assets/629193/6a7eb9d4-ec0c-4dd0-b0c0-540b265a80bf)

**Comment by data-sync-user** [comment]
➤ Winnie Teichmann commented:

Chris Peterson this is correct for iOS: For us the whole string is a link. You can find this in the design for iOS as well.
