### ISSUE TITLE
Fakespot - Update info card - Incorrect text is displayed on the card 

### ISSUE THREAD

**Issue by alinamoldovan84** [mozilla-mobile/firefox-ios#16615]
## Steps to reproduce
1. Navigate to amazon.com/walmart.com/bestbuy.com
1. Search for a product with no fakespot review. e.g. https://www.amazon.com/adidas-Originals-X_PLR-Running-Metallic/dp/B07HFCGNFH/ref=mp_s_a_1_7?content-id=amzn1.sym.14b29e6f-a06f-45b5-a439-5150af06ee11%3Aamzn1.sym.14b29e6f-a06f-45b5-a439-5150af06ee11&keywords=adidas+originals&pd_rd_r=562f5eb0-8109-4ad5-abf7-b98c5951e2ba&pd_rd_w=9FBD4&pd_rd_wg=rIbIF&pf_rd_p=14b29e6f-a06f-45b5-a439-5150af06ee11&pf_rd_r=SPBHRJQQZWCNDJH6FE66&qid=1695813466&refinements=p_89%3Aadidas+Originals&s=apparel&sr=1-7&wi=us-slds-sp-2-t1-a2_1
1. Unanalyzed card card is displayed
1. Tap "Check Review Quality" button 
1. Loading info card is displayed 
1. Check the text on the card 

### Expected behavior
"This could take about 60 seconds." message should be displayed

### Actual behavior
"Checking review quality" message is displayed twice.

### Device & build information
* Device: iPhone 14+ (16.0.3) 
* Build version:  V9000 (34584) 
* First seen version: V9000 (34584)  
### Notes
Attachments: 

![Skype!UNITO-UNDERSCORE!Picture!UNITO-UNDERSCORE!2023!UNITO-UNDERSCORE!09!UNITO-UNDERSCORE!27T13!UNITO-UNDERSCORE!36!UNITO-UNDERSCORE!28!UNITO-UNDERSCORE!002Z](https://github.com/mozilla-mobile/firefox-ios/assets/124251579/483d67b5-9ab9-4de3-9855-d881fe54d69a)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7484)

**Comment by data-sync-user** [comment]
➤ Winnie Teichmann commented:

Was fixed in https://mozilla-hub.atlassian.net/browse/FXIOS-7454 ( https://mozilla-hub.atlassian.net/browse/FXIOS-7454|smart-link ) (PR #16746 ( https://github.com/mozilla-mobile/firefox-ios/pull/16746 ))

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v9000 (35165), with iPhone SE (16.6.1).
