### ISSUE TITLE
Fakespot - Unanalyzed card - Incorrect text is displayed on the card  

### ISSUE THREAD

**Issue by alinamoldovan84** [mozilla-mobile/firefox-ios#16614]
## Steps to reproduce
1. Navigate to amazon.com/walmart.com/bestbuy.com
2. Search for a product with no fakespot review. e.g. https://www.amazon.com/adidas-Originals-X_PLR-Running-Metallic/dp/B07HFCGNFH/ref=mp_s_a_1_7?content-id=amzn1.sym.14b29e6f-a06f-45b5-a439-5150af06ee11%3Aamzn1.sym.14b29e6f-a06f-45b5-a439-5150af06ee11&keywords=adidas+originals&pd_rd_r=562f5eb0-8109-4ad5-abf7-b98c5951e2ba&pd_rd_w=9FBD4&pd_rd_wg=rIbIF&pf_rd_p=14b29e6f-a06f-45b5-a439-5150af06ee11&pf_rd_r=SPBHRJQQZWCNDJH6FE66&qid=1695813466&refinements=p_89%3Aadidas+Originals&s=apparel&sr=1-7&wi=us-slds-sp-2-t1-a2_1  
3. Unanalyzed card card is displayed 
4. Check the text displayed on the card

### Expected behavior
"To know whether this product’s reviews are reliable, check the review quality. It only takes 60 seconds." should be displayed 

### Actual behavior
"To know whether this product’s reviews are reliable, check the review quality. It only takes about 60 seconds." text is displayed 

### Device & build information
* Device: iPhone 14+ (16.0.3) 
* Build version: V9000 (34584) 
* First seen version: V9000 (34584) 
### Notes
Attachments: 

![Skype_Picture_2023_09_27T13_09_26_037Z](https://github.com/mozilla-mobile/firefox-ios/assets/124251579/ff8ea298-d60f-4e08-875a-4af0f1552a16)

![Skype_Picture_2023_09_27T13_09_40_286Z](https://github.com/mozilla-mobile/firefox-ios/assets/124251579/d00d08bf-07ab-471b-9369-74e16d4852f4)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7483)

**Comment by data-sync-user** [comment]
➤ Alina Moldovan commented:

After checking the +string inventory+ ( https://docs.google.com/spreadsheets/d/1FQUU2pqhKkAXRHNbmK9dhObwvevWoR3N6BOh3fu2skE/edit#gid=64342838 ) document, it looks that the text is correct. The[ Figma|https://www.figma.com/file/VE5xayz3yOSB5qOATUU9Im/Mobile-Shopping-Experience-MVP?node-id=7032%3A34493&mode=dev] design is not updated.
