### ISSUE TITLE
Fakespot - Incorrect order of sections displayed in the "Highlights from recent reviews" card   

### ISSUE THREAD

**Issue by alinamoldovan84** [mozilla-mobile/firefox-ios#16637]
## Steps to reproduce
1. Navigate to a product detail page  having multiple reviews. e.g. https://www.amazon.com/AmazonBasics-Stemless-Wine-Glasses-15-Ounce/dp/B07376L9FC/ref=mp_s_a_1_1_ffob_sspa?crid=2QIW2WSJG54V9&keywords=wine+glasses&qid=1695902980&sprefix=wine+glass%2Caps%2C206&sr=8-1-spons&sp_csd=d2lkZ2V0TmFtZT1zcF9waG9uZV9zZWFyY2hfYXRm&psc=1
1. Open the review quality checker 
1. Verify the order of the sections in the "Highlights from recent reviews" card 

### Expected behavior
The order should be: Price, Quality, Shipping,  Competitiveness, Packaging

### Actual behavior
The order is: Price, Quality, Competitiveness, Shipping,  Packaging

### Device & build information
* Device: iPhone 14+ (16.0.3) 
* Build version: 9000 (34632)  
* First seen version: 9000 (34632)  
### Notes
Attachments: 

![Skype!UNITO-UNDERSCORE!Picture!UNITO-UNDERSCORE!2023!UNITO-UNDERSCORE!09!UNITO-UNDERSCORE!28T12!UNITO-UNDERSCORE!14!UNITO-UNDERSCORE!19!UNITO-UNDERSCORE!978Z](https://github.com/mozilla-mobile/firefox-ios/assets/124251579/e1119403-13cb-4651-895a-258f1180cfa3)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7495)

**Comment by data-sync-user** [comment]
➤ Alina Moldovan commented:

Verified as fixed using V9000 (34750) and iPhone 14+ (16.0.3).

!image-20231003-153718.png|width=389,height=799!
