### ISSUE TITLE
Tab thumbnails are mostly blank black

### ISSUE THREAD

**Issue by stuartlangridge** [mozilla-mobile/firefox-ios#16662]
## Steps to reproduce

Use Firefox for iOS, it seems

### Expected behavior

The tabs in the list all have thumbnails.

### Actual behavior

Most tabs do not have thumbnails.

### Device & build information
* Device: iPhone 13 mini, iOS 16.6.1
* Build version: Firefox 117.3 (34056)
* First seen version: Not new to this version; it's been happening for a while.
### Notes
Attachments: 
![2023-09-30 09 01 17](https://github.com/mozilla-mobile/firefox-ios/assets/4356350/af0ef76a-f5e4-4ef0-bfd2-64f6d88a5ba2)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7503)

**Comment by data-sync-user** [comment]
➤ Yoana Rios Diaz commented:

Duplicated of https://mozilla-hub.atlassian.net/browse/FXIOS-7809 ( https://mozilla-hub.atlassian.net/browse/FXIOS-7809|smart-link ) and fixed in this PR ( https://github.com/mozilla-mobile/firefox-ios/pull/17441 )

**Comment by data-sync-user** [comment]
➤ Yoana Rios Diaz commented:

Closing as duplicated of https://mozilla-hub.atlassian.net/browse/FXIOS-7809 ( https://mozilla-hub.atlassian.net/browse/FXIOS-7809|smart-link )  and fix in this PRhttps://github.com/mozilla-mobile/firefox-ios/pull/17441 ( https://github.com/mozilla-mobile/firefox-ios/pull/17441|smart-link )
