### ISSUE TITLE
Update VisitType to match Desktop and Rust implementations

### ISSUE THREAD

**Issue by skhamis** [mozilla-mobile/firefox-ios#16706]
application-services is moving away from VisitTransition and using only VisitType to simplify implementation across the board. iOS unfortunately has it's own version of VisitType https://github.com/mozilla-mobile/firefox-ios/blob/379e732863a14ba07061768076ec696f83e87087/Storage/Visit.swift#L11-L35 which is slightly diverged from it's desktop/android counterparts. We should try to bring iOS back into the fold and see if we can have it rely on the same implementation as Fenix.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7522)

**Comment by Anierws** [comment]
T Williams
