### ISSUE TITLE
Fakespot - review drawer doesn't open after a specific scenario 

### ISSUE THREAD

**Issue by alinamoldovan84** [mozilla-mobile/firefox-ios#16715]
## Steps to reproduce
1. Navigate to a PDP and open the Fakespot  review drawer 
2. From another device send a tab containing a PDP 
3. Open the Fakespot  review drawer 

### Expected behavior
Fakespot  review drawer opens 

### Actual behavior
Fakespot  review drawer doesn't open

### Device & build information
* Device: iPhone 14+ (16.0.3) 
* Build version: v9000 (34778) 
* First seen version: ? 
### Notes
Attachments: 

https://github.com/mozilla-mobile/firefox-ios/assets/124251579/10cf002c-df02-45ab-ab75-a20cbca3e3e7

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7523)

**Comment by data-sync-user** [comment]
➤ Winnie Teichmann commented:

This can also reproduced when using this deep-link in step 2: firefox://deep-link?url=homepanel/new-tab

This happens because the coordinators still have the FakespotCoordinator in the hierarchy and we don’t open the FakespotViewController in this case.

**Comment by data-sync-user** [comment]
➤ Alina Moldovan commented:

Verified as fixed using V9000 (35165) and iPhone 14+ (16.0.3).
