### ISSUE TITLE
Firefox iOS APP about:blank window streched over the whole window

### ISSUE THREAD

**Issue by mrmr420** [mozilla-mobile/firefox-ios#16719]
## Steps to reproduce
Fist I use a pihole to block some sites. The issue usually appears when an advertisement redirects me to another site which is blocked. Firefox usually promts a about:blank tab if it cant resolve the DNS name, which I would consider as expected behaviour. But sometimes, and completely random, the white part of the about:blank tab is stretched around the whole screen. I cxant see the taskbar anymore. The only way to resolve this would be to restart the app. Another way is to halve close the app, I mean entering the menue where to see al the open apps, and going back to the app.

### Expected behavior
about:blank tab is shown in complete size including the taskbar and context menues

### Actual behavior
about:blank tab is shown as a complete white window 

### Device & build information
* Device: ? 
* Build version: ? 
* First seen version: ? 
### Notes
Attachments: 

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7526)

**Comment by lmarceau** [comment]
Hello @mrmr420, thanks for opening this issue. Do you also happen to have a screenshot of the problem?

**Comment by mrmr420** [comment]
Hello Imarceau,thank you for your response. The following picture describes what I mean. It will look like this directly after the redirect happens. Somehow its not always like this. In most of the cases the taskbar is shown as expected. GreetingsMaxAm 10/10/2023 um 19:47 schrieb lmarceau ***@***.***>:﻿
Hello @mrmr420, thanks for opening this issue. Do you also happen to have a screenshot of the problem?

**Comment by lmarceau** [comment]
Hello @mrmr420, to attach a picture to the issue you need to go on the GitHub website directly to attach it. Replying from email doesn't attach the picture to the issue sadly.

**Comment by data-sync-user** [comment]
➤ Daniela Arcese commented:

Andrei Bodea are you able to reproduce this?

**Comment by mrmr420** [comment]
> Hello @mrmr420, to attach a picture to the issue you need to go on the GitHub website directly to attach it. Replying from email doesn't attach the picture to the issue sadly.

Hi, picture attached!
Greetings

![IMG_0108](https://github.com/mozilla-mobile/firefox-ios/assets/147154049/70fec2cf-d79e-48a4-8c7b-d1b819cc0eef)

**Comment by abodea** [comment]
Hello, @mrmr420 thank you for the picture! Can you please give some website examples I would like to try with the same ads?  Can mention your iOS version and device?

**Comment by mrmr420** [comment]
Hello,one example link:Episode 49 Staffel 17 von One Pieceaniworld.toBut you have to keep in mind that I use a pihole blocking ads on DNS level. GreetingsAm 13/10/2023 um 15:56 schrieb Andrei Bodea ***@***.***>:﻿
Hello, @mrmr420 thank you for the picture! Can you please give some website examples I would like to try with the same ads?  Can mention your iOS version and device?

**Comment by mrmr420** [comment]
Hello, any updates? IOS 17.0.3

Greetings

**Comment by data-sync-user** [comment]
➤ Norberto Andres Furlan commented:

Andrei Bodea can you give us the steps to reproduce?

**Comment by abodea** [comment]
@mrmr420 can you please let me know if your device is Jailbreak?

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Hello, Norberto Andres Furlanplease note that I tried with the step from the description but I was not able to reproduce it on the latest v9000 (36168) but I never used a Pihole as I believe you need the infrastructure and another PC running Linux, also note that there is an app Pihole in the App Store but it’s not free so you need to buy it.
So I’m not really sure if anyone from our side can reproduce it.  And if the reporter device is Jailbreak I don’t think this is normal user behavior.

**Comment by mrmr420** [comment]
Hello all,the device is not jailbroken and completely stock.For a pihole you need at least a raspberry pi or a virtualization platform like vmware esxi. Ice noticed that this behavior only occurs if the dns cant be resolved by the dns server and the browser reacts with a about:blank page.GreetingsMaxAm 20/11/2023 um 15:40 schrieb Data Sync User ***@***.***>:﻿
➤ Andrei Bodea commented:
Hello, Norberto Andres Furlanplease note that I tried with the step from the description but I was not able to reproduce it on the latest v9000 (36168) but I never used a Pihole as I believe you need the infrastructure and another PC running Linux, also note that there is an app Pihole in the App Store but it’s not free so you need to buy it.
So I’m not really sure if anyone from our side can reproduce it.  And if the reporter device is Jailbreak I don’t think this is normal user behavior.
