### ISSUE TITLE
Fall off in the number of home page views following v115 and v116.

### ISSUE THREAD

**Issue by OrlaM** [mozilla-mobile/firefox-ios#16726]
The number of home page views being reported has dropped off significantly following the release of v116 and prior to that fell less significantly following v115.

This also impacts the sponsored top sites impressions.

![image](https://github.com/mozilla-mobile/firefox-ios/assets/3929954/3deb74e3-cf5a-473c-87c5-c6cfb32a8ed6)

![image](https://github.com/mozilla-mobile/firefox-ios/assets/3929954/fc9bb04c-2f45-46fc-b3a5-9457ee4bc685)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7529)

**Comment by data-sync-user** [comment]
➤ Laurie Marceau commented:

For QA it can be checked that start at home works as expected (all three options: Last tab, Homepage and Homepage after four hours).

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Verified as fixed on v119 (35097) with iPhone 13 pro (15.7.1).

I’ve let the device 4h but also on another device I manipulated the time (set it to manual) and moved forward 4h and 1m, everything looks good I’m not sure if there is something more that I can check, Laurie Marceaucan you please confirm that this verification is good/enough?

**Comment by data-sync-user** [comment]
➤ Laurie Marceau commented:

If the homepage shows (and you were on a website tab before closing and making that verification) then all should be 👍
