### ISSUE TITLE
Fakespot - Incorrect card is displayed in case the prod analyze is in progress but it was started from a different device  

### ISSUE THREAD

**Issue by alinamoldovan84** [mozilla-mobile/firefox-ios#16766]
## Steps to reproduce
1. Search for a product that has been never analyzed 
2. From another device or directly trough the API call start analyze the prod
3. Check the card displayed while the analyze is in progress 
  
### Expected behavior
"Checking review quality" card should be displayed 

### Actual behavior
"Not enough reviews yet" card is displayed 

### Device & build information
* Device: iPhone 14+ (16.0.3) 
* Build version: V9000 (34959) 
* First seen version: ? 
### Notes
Attachments: 

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7540)

**Comment by data-sync-user** [comment]
➤ Razvan Litianu commented:

For QA, when we trigger the check for reviews flow the logic is to wait 30 secs until we poll for a new analysis status. On the second device, the analysis might be either completed or failed so it might show a different product analysis. 

To check this you can dismiss the sheet from the first device (in a 30 sec window) and bring it up again. The first device now should reflect the second device state.

**Comment by data-sync-user** [comment]
➤ Alina Moldovan commented:

Verified as fixed using V9000 (35445) and iPhone 14+ (16.0.3).

Confirming the fix.
