### ISSUE TITLE
[a11y] The webpage elements are read behind the `review quality check bottom sheet`

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/firefox-ios#16762]
### Preconditions
`Make sure that the Turn VoiceOver is enabled.`

## Steps to reproduce
1. Navigate to a product detail page on amazon.com, walmart.com, or bestbuy.com and tap the Price tag icon.
2. Review quality check bottom sheet/sidebar opens.
3. Expand the review quality check bottom sheet.
4. Tap through the lines.
### Expected behavior
The webpage elements behind the review quality check bottom sheet should not be read.
### Actual behavior
The webpage elements are read behind the review quality check bottom sheet
### Device & build information
* Device: iPhone 13 Pro (15.7.1). 
* Build version: 9000 (34959) 
* First seen version: N/A 
### Notes
Please note that this issue is not reproducible on iOS 17.
Attachments: 

https://github.com/mozilla-mobile/firefox-ios/assets/42831109/463acb25-9716-4067-bf1a-ffe9491e2963

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7539)

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Verified as fixed on v9000 (35281) with iPhone 13 Pro (15.7.1).
