### ISSUE TITLE
Onboarding screen includes an implicit heading

### ISSUE THREAD

**Issue by anna-yeddi** [mozilla-mobile/firefox-ios#16843]
## Steps to reproduce
1. Ensure VoiceOver is running 
1. Open Fx for the first time
1. Navigate to the "Make Firefox your to-go browser" text and observe the announcement 

### Expected behavior
"Make Firefox your go-to browser, heading" (heading is a role trait that would be announced/added by VoiceOver when the trait is programmatically set). VO rotor could navigate to this element when navigating by headings

### Actual behavior
No heading is announced. Rotor cannot navigate to this implicit heading

### Device & build information
* Device: ?  iPhone 12 Pro, iOS  16.6.1
* Build version: ?  beta 9000 (35165)

### Notes
Attachments: 

![image](https://github.com/mozilla-mobile/firefox-ios/assets/40773610/97dce1bd-579d-4993-b4ae-d5e78ab96680)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7569)

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v121(36341), with iPhone SE (16.6.1).
