### ISSUE TITLE
When next onboarding screen is opened, VoiceOver does not update the focus position

### ISSUE THREAD

**Issue by anna-yeddi** [mozilla-mobile/firefox-ios#16844]
## Steps to reproduce
1. Ensure VoiceOver is running
1. Open the Fx for the first time
1. Navigate to the "Skip" button and activate it with double tap
1. While the view is being changed, observe the VO focus position and if the screen reader announced the change in content 

### ~Expected~ Actual behavior
Skip button is announced again, while the content above it is changed. A blind user won't be aware that there was, in fact, new content on the page and is likely miss it.

### ~Actual~ Expected behavior
New heading is focused with a screen reader and it is announced (as the first updated content in the reading order). Or Close button as the first element in the reading order

### Device & build information
* Device: ?  iPhone 12 Pro, iOS  16.6.1
* Build version: ?  beta 9000 (35165)

### Notes
Attachments: 

[image](https://github.com/mozilla-mobile/firefox-ios/assets/40773610/b03600d4-8215-443c-8b2e-98671e6abc36)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7570)

**Comment by lmarceau** [comment]
PR for this work was https://github.com/mozilla-mobile/firefox-ios/pull/17525, it was tagged for another task by mistake

**Comment by imsanchit** [comment]
hey @anna-yeddi a quick check on the expected behavior here, is there any specific reason why we want the user to focus on the Skip button instead of the new content (heading) first?

**Comment by anna-yeddi** [comment]
> hey @anna-yeddi a quick check on the expected behavior here, is there any specific reason why we want the user to focus on the Skip button first instead of the new content (heading)?

Oh my! Thank you for clarifying it'd @imsanchit! I mixed the expected and actual behavior headings in the report... it's fixed now. My apologies for the confusion.

We do want to move the focus to the topmost element so the user could continue reading the content without the need to go back up

**Comment by imsanchit** [comment]
Thanks for clarifying this, the expected behavior is already in place in the latest build. I think [this](https://github.com/mozilla-mobile/firefox-ios/issues/16842) ticket is somewhat related to it

**Comment by csuciu** [comment]
Closing based on the latest comments.
