### ISSUE TITLE
Close button on onboarding screen lacks accessible label

### ISSUE THREAD

**Issue by anna-yeddi** [mozilla-mobile/firefox-ios#16841]
## Steps to reproduce
1. Open the Firefox iOS for the first time.
1. Ensure VoiceOver is running. 
1. Navigate to the "x" button and observe the announcement 

### Expected behavior
"Close, button"

### Actual behavior
"Cross circle fill extra large, Button"

### Device & build information
* Device: ?  iPhone 12 Pro, iOS  16.6.1
* Build version: ?  beta 9000 (35165)

### Notes
Attachments: 

![image](https://github.com/mozilla-mobile/firefox-ios/assets/40773610/24f1966a-38a9-46c3-bb83-423bc6986e4b)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7567)

**Comment by anna-yeddi** [comment]
The announcement finishes with "close" but it feels like it's a hint not a label. Refer to the "show names" command output from Voice Control to confirm the label of the button is not correct ![image](https://github.com/mozilla-mobile/firefox-ios/assets/40773610/55e207ee-f76a-4c33-b13e-75a0794a1aa4)

**Comment by data-sync-user** [comment]
➤ Cyndi Chin commented:

Update expected behavior to Close and exit Firefox onboarding, button
Confirmed with Emily Wachowiak

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v121(36341), with iPhone SE (16.6.1).
