### ISSUE TITLE
Share This Page and Secure Connection url bar buttons are not included in the logical focus order

### ISSUE THREAD

**Issue by anna-yeddi** [mozilla-mobile/firefox-ios#16857]
## Steps to reproduce
1. Ensure VoiceOver is running
1. Navigate to any page, I.e. Amazon.com
1. Navigate to the url bar and review the buttons within it while using logical navigation gestures (swiping right/left with one finger) and observe the visual VO focus movement

### Expected behavior
1. VO focus order is following the visual reading order of the url bar controls

### Actual behavior
1. The url bar controls are receiving focus of VO in two cycles: first, the Share This Page button and Secure Connection button are skipped (May be presumed disabled by a sighted user but even disabled/dimmed controls are expected to be focused and announced as such by VO), then the focus circles the url bar area once again, only focusing these two controls. This would create confusion for users with cognitive difficulties, users with dyslexia, neurodiverse users who rely on a screen reader to access the on-screen content. Also VO users with low vision and Switch Control and keyboard-only users with limited mobility may find it confusing because the focus order is not predictable.

### Device & build information
* Device: ?  12 pro 16.6.1
* Build version: ?  9000

### Notes
Attachments: 

![image](https://github.com/mozilla-mobile/firefox-ios/assets/40773610/cd9802e0-4aa0-4a81-b660-59d5c261634b)![image](https://github.com/mozilla-mobile/firefox-ios/assets/40773610/503dd75e-fabb-4b64-8615-040825d5fe2b)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7573)

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Verified as fixed on v122 (37367) with iPhone 15 Pro (17.1.2).

Everything is read with voice-over without issues, even the Share This Page button and Secure Connection buttons.
