### ISSUE TITLE
Fakespot - The "Learn more" link does not open when tapped 

### ISSUE THREAD

**Issue by alinamoldovan84** [mozilla-mobile/firefox-ios#16854]
## Steps to reproduce
1. Open the Fakespot Opt-in card 
1. Tap 'Learn more' link 

### Expected behavior
Links opens in a new tab 

### Actual behavior
User must tap the link several times in order to open it 

### Device & build information
* Device: 14+ (16.0.3) 
* Build version: V9000 (35165) 
* First seen version: ? 
### Notes
Attachments: 

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7572)

**Comment by data-sync-user** [comment]
➤ Chris Peterson commented:

Razvan Litianu will investigate

**Comment by data-sync-user** [comment]
➤ Winnie Teichmann commented:

There is a contributor PR ( https://github.com/mozilla-mobile/firefox-ios/pull/16870 ) open for this. Unfortunately the PR doesn’t solve the issue completely. I reached out to the designers to change the layout so the buttons can have the correct height specified in the HIG. Ekaterina Galetski is working on the design update.

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v120 (35966), on iPhone SE (16.6.1).
