### ISSUE TITLE
Review Checker drawer has no programmatic headings but includes implicit headings

### ISSUE THREAD

**Issue by anna-yeddi** [mozilla-mobile/firefox-ios#16861]
## Steps to reproduce
1. Ensure VoiceOver is running
1. Open any PDP page on Amazon, I.e. [Utz cheese balls](https://www.amazon.com/Utz-Delightfully-Cholesterol-Trans-Fat-Certified/dp/B09F8ST2ZS/ref=mp_s_a_1_2_maf_2?crid=HLL7RB8BPC9Z&keywords=utz+cheese+balls&qid=1697313083&sprefix=utz%2Caps%2C65&sr=8-2)
1. Navigate to the url bar and activate the Review Checker button
1. Review the Review Checker dialog, try navigate using Rotor > Headings and then swiping up/down with one finger

### Expected behavior
1. User can navigate to the main title/heading of the view by Rotor action. On the opted-in view of the Checker, ideally, the text next to the chevrons (expand/collapse buttons) would be navigable by the heading rotor gestures
1. "Review checker Beta", main heading (the largest text on the view) and card headings (next to chevrons) are announced as headings by VO

### Actual behavior
1. No headings is found by the VO rotor
1. Visually important text (implicit headings) is not announced as a heading

### Device & build information
* Device: ?  12 pro with iOS 16.6.1
* Build version: ?  9000

### Notes
Attachments: 

![image](https://github.com/mozilla-mobile/firefox-ios/assets/40773610/e9a4126e-f214-45ef-ba85-c226b864d675)
![image](https://github.com/mozilla-mobile/firefox-ios/assets/40773610/3c670712-450f-46e0-873d-cfd08ec3621e)
![image](https://github.com/mozilla-mobile/firefox-ios/assets/40773610/6bf2c3d4-7577-40da-af23-c4cc47c55de6)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7575)

**Comment by data-sync-user** [comment]
➤ Alina Moldovan commented:

Verified as fixed using V9000 (35936) and iPhone 14+ (16.0.3).
