### ISSUE TITLE
Replace link buttons in FakespotOptInCardView

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#16863]
Replace the following buttons

* learnMoreButton
* privacyPolicyButton
* termsOfUseButton
* secondaryButton

in `FakespotOptInCardView` with the `LinkButton` class from the component library (created with https://github.com/mozilla-mobile/firefox-ios/issues/16390%7Csmart-link )

PR will be similar to https://github.com/mozilla-mobile/firefox-ios/pull/16417%7Csmart-link.

* Remove duplicated setup code from the linkButton in FakespotOptInCardView, since it now lives in the component library
* addTarget stays in OnboardingCardViewController
* setTitle and font should be done with the configure method as done with linkButton

Please add screenshot of dark and light mode changes, before and after on your PR.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7576)

**Comment by alentvinsent** [comment]
im working on this

**Comment by lmarceau** [comment]
@alentvinsent I believe @imsanchit is also looking into this issue as we chatted about it on Element 🤔 Could you maybe sync with him?

**Comment by data-sync-user** [comment]
➤ Laurie Marceau commented:

For QA it can be checked the buttons in those views are themed properly in dark and light mode, and works as expected

!image-20231106-190908.png|width=1058,height=2132!

!image-20231106-190942.png|width=1058,height=2132!

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified on v120 (35966), with iPhone SE (16.6.1).

The Fakespot buttons look and work properly, but I am unable to see and test the onboarding button due to https://github.com/mozilla-mobile/firefox-ios/issues/17227 ( https://github.com/mozilla-mobile/firefox-ios/issues/17227|smart-link )
