### ISSUE TITLE
VoiceOver focus is inconsistently jumping when a card is opened on Review Checker

### ISSUE THREAD

**Issue by anna-yeddi** [mozilla-mobile/firefox-ios#16872]
## Steps to reproduce
1. Ensure VoiceOver is running
2. Open any PDP page on Amazon, I.e. [Utz cheese balls](https://www.amazon.com/Utz-Delightfully-Cholesterol-Trans-Fat-Certified/dp/B09F8ST2ZS/ref=mp_s_a_1_2_maf_2?crid=HLL7RB8BPC9Z&keywords=utz+cheese+balls&qid=1697313083&sprefix=utz%2Caps%2C65&sr=8-2)
3. Navigate to the url bar and activate the Review Checker button
4. Navigate to and activate "How We Determine..." button to expand the card
5. Using logical navigation gestures (swiping left/right with one finger) navigate to the "Settings" and then back to the title of the Checker
6. Navigate to "Show more" button and activate it
7. Repeat step 5 and observe the VoiceOver focus behavior 

### Expected behavior
1. All content is focused and announced in a logical order (left-to-right top-to-bottom for English). The VO focus order follows the visual reading order and is predictable

### Actual behavior
1. The VO focus may not proceed past the D, E ratings to their description. To escape the trap, try to explore-by-touch to focus the Unreliable reviews
2. While trying to navigate further or backwards, the focus would skip part of the content, mostly the card title "How we..." or/and star rating or/and highlights - the results are different for different directions of swiping and are differ between Fx restarts... 

### Device & build information
* Device: ?  iOS 16.6.1 iPhone 12 Pro
* Build version: ?  9000
* First seen version: ? 
### Notes
Attachments: 

![image](https://github.com/mozilla-mobile/firefox-ios/assets/40773610/4e434157-a8c4-4dd8-9c61-0872dfb90354)
https://github.com/mozilla-mobile/firefox-ios/assets/40773610/0f1c4fac-8252-4aa2-a29c-c4f922086d83

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7582)

**Comment by anna-yeddi** [comment]
Since the behavior affects all screen reader users who tries to learn more about the rating system and that this information is important for the initial offering, I'm marking it as access-s2 while the workaround (explore-by-touch) is available - the workaround would not be clear to use because for a blind user it would be announcing like the end of the scree and using this feature for a non-sighted user would not obvious.

Attached is another video of the behavior where I was not using the explore-by-touch and only navigated forward and backward (swiping left/right with one finger) which is an expected behavior for a non-power user of a screen reader.https://github.com/mozilla-mobile/firefox-ios/assets/40773610/fca1a314-ff58-42a2-a4fb-ffec72e9b9f3

**Comment by abodea** [comment]
Verified as fixed on v9000 (35348) with iPhone 13 Pro (15.7.1).

https://github.com/mozilla-mobile/firefox-ios/assets/42831109/5497749f-88fa-4125-8c73-7d632ce90517
