### ISSUE TITLE
Replace Padded switch in BoolSetting

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#16888]
The BoolSetting class should use the PaddedSwitch from the component library

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7587)

**Comment by jigmetdadul** [comment]
Can I take this issue?

**Comment by lmarceau** [comment]
This is still up for grabs BTW in anyone is interested

**Comment by data-sync-user** [comment]
➤ Matthew Reagan commented:

Alina Moldovan This is a refactor and so it just requires regression testing of the related bool switches (Settings > Sync Notifications, Settings > Tips and Features, Search Settings).

**Comment by data-sync-user** [comment]
➤ Alina Moldovan commented:

Verified as fixed using FF v123 (37946) and iPhone 15+ (17.0.2)
