### ISSUE TITLE
Fakespot - When there are no more highlights to display in expanded mode, do not show the "Show more" button

### ISSUE THREAD

**Issue by alinamoldovan84** [mozilla-mobile/firefox-ios#16899]
## Steps to reproduce
1. Search for a product having only one highlight group and it contains two one-line reviews: https://www.amazon.com/Simple-Joys-Carters-Snug-Fit-Halloween/dp/B083XK7SJR/
1. Check the highlights card 

### Expected behavior
"Show more" button should not be displayed

### Actual behavior
"Show more" button is displayed

### Device & build information
* Device: iPhone 14+(16.0.3) 
* Build version: v9000 (35230) 
* First seen version: ? 
### Notes
Attachments: 

https://github.com/mozilla-mobile/firefox-ios/assets/124251579/68efa58b-7a2a-47bb-a3bf-13f4dbf90b3d

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7595)

**Comment by data-sync-user** [comment]
➤ Alina Moldovan commented:

Validated this issue using FF V9000 (36138) and iPhone 14+ (16.0.3)

Not able to reproduce this issue anymore.
