### ISSUE TITLE
Fakespot - CFR is not displayed when the device is in landscape mode 

### ISSUE THREAD

**Issue by alinamoldovan84** [mozilla-mobile/firefox-ios#16909]
## Steps to reproduce
1. Make sure the user is not opted in 'review the quality check' provided by Fakespot. (Clean install FF app)
1. Change the device orientation to be landscape view
1. Navigate for the first time to a product detail page on amazon.com, walmart.com, or bestbuy.com/ page
1. Check the CFR 

### Expected behavior
The CFR announcing the Fakespot feature should be displayed. 

Please note that this issue happens for both Fakespot CFRs 

### Actual behavior
The CFR is not triggered. Please note that if users changes the orientation to portrait mode the CFR is displayed; CFR is displayed if users changes the orientation back to landscape mode. 

### Device & build information
* Device: iPhone 14+ (16.0.3) 
* Build version: V9000 (35381) 
* First seen version: V9000 (35381) 

*# 
*## Notes
Attachments: 
<
!--- Screenshots or screen recordings are very helpful for reproducing|width=200,height=183!
 -->

[https://github.com/mozilla-mobile/firefox-ios/assets/124251579/01643dad-a25d-41ea-a638-ed1be66fcfe3](https://github.com/mozilla-mobile/firefox-ios/assets/124251579/01643dad-a25d-41ea-a638-ed1be66fcfe3)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7599)

**Comment by data-sync-user** [comment]
➤ Alina Moldovan commented:

Verified as fixed using V9000 (35445) and iPhone 14+ (16.0.3).

CFRs are correctly displayed in landing mode.
