### ISSUE TITLE
Fakespot - Incorrect font in ReliabilityCardView

### ISSUE THREAD

**Issue by DianaBarladeanu** [mozilla-mobile/firefox-ios#16907]
**Steps to reproduce**
1. Open "Review Checker"
2. Scroll to "How we determine review quality" card and observe "The adjusted rating" font

 **Expected behavior**
Only "adjusted rating" should be bolded according to Figma.

**Actual behavior**
"The" from the "The adjusted rating" is also bolded.

**Device & build information**
* Device: iPhone SE (16.6.1)
* Build version: v9000 (35281)
* First seen version: ? 
* 
**Notes**
**Attachments:** 
 
![IMG_0136(1)](https://github.com/mozilla-mobile/firefox-ios/assets/133357955/775e7cf7-f322-4077-9de9-e5fc2c12c4db)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7598)

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v9000 (35319), with iPhone SE (16.6.1).
