### ISSUE TITLE
Fakespot - Reader mode button is present for a specific scenario on walmart.com 

### ISSUE THREAD

**Issue by alinamoldovan84** [mozilla-mobile/firefox-ios#16911]
## Steps to reproduce
Issue doesn't reproduce constantly 
1. Make sure you have no other tabs opened 
2. Restart FF app 
3. Make sure the toolbar is set at the bottom  
4. Navigate to the walmart.com 
5. Scroll up so that the tollbar is not visible anymore 
6. Open a product detail page 
7. Scroll for the toolbar to be visible 

### Expected behavior
Reader mode button should not be present 

### Actual behavior
Reader mode button is present

### Device & build information
* Device: iPhone 14+ (16.0.3) 
* Build version: v9000 (35381) 
* First seen version: ? 
### Notes
Attachments: 

https://github.com/mozilla-mobile/firefox-ios/assets/124251579/24ab28dd-1f64-4f7a-b775-bf10edd7a56d

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7600)

**Comment by data-sync-user** [comment]
➤ Alina Moldovan commented:

Verified as fixed using V9000 (35445) and iPhone 14+ (16.0.3).

Not able to reproduce it anymore.
