### ISSUE TITLE
Force Sync/Sync Now doesn't work for Bookmarks and History

### ISSUE THREAD

**Issue by jjSDET** [mozilla-mobile/firefox-ios#16916]
Be warned, I'm including some speculation as flavor text. Maybe it'll be useful, maybe not. Who am I to judge such things?

Also, I apologize for the grossly embiggened screencaps...

I think there is a problem related to duplicate device references on the desktop side, causing synchronization issues for history and bookmarks; tab syncing seems to work correctly. This is specifically with regard to the `Force Sync`/`Sync Now` feature, but manifests itself in a number of ways that make the feature appear erratic and broken.

I've noticed deleting and reinstalling the mobile app creates new device entries in the mobile view, but not the desktop view.

For example:

iOS
![4AB5DFD7-40D1-4FEA-A79E-8AD0D73D4CAD](https://github.com/mozilla-mobile/firefox-ios/assets/107960801/6d2d19d6-ed8c-4ee7-aa21-632058048f19)

Desktop
![Screenshot 2023-10-18 at 11 52 06 AM](https://github.com/mozilla-mobile/firefox-ios/assets/107960801/45cc6450-9514-4f94-b964-c392de492de6)

Curiously, tab syncing works even though Bookmarks and History do not. When looking at the `Synced Tabs` view, however, we see it actually shows the previously connected device that was used for my very first sync, which hints at it's ability to parse the various tab data stores that are being sent from the desktop instance. It seems Bookmarks and History are not handled the same way. The `Synced Tabs` view seem to update immediately when refreshed and also works with `Sync Now`.

![C064170D-8ED7-4296-8B53-DFF3F9A6194C](https://github.com/mozilla-mobile/firefox-ios/assets/107960801/d60c33c5-2e80-438e-ae67-4f380a3e606f)

I've also noticed the desktop instance doesn't receive data from the mobile device, possibly because it's expecting it from the device seen in the `Synced Tabs` view, but that's not the device we are using to try to sync to desktop. So I suppose that makes sense then, kind of, that we're sending an empty sync data object to desktop since that's not the device/session/instance we currently have our sync data in. 

I'd expect the communication from Desktop to Mobile to have issues because the desktop sync view only shows one connected device, even though it's not the correct reference to the current sync session/instance, which seems to make sense that it's pushing it's history, bookmarks, and tab data to the wrong device (well, correct device, but wrong session or instance).

The data does eventually sync, though. Whatever timed trigger exists eventually pushes the data to all devices; however, it takes longer than expected. It took somewhere between 20-30 minutes to see the bookmarks and history on mobile. I'm not sure when the timed trigger tries to sync, and maybe that's exactly as long as you'd expect. If it's a timed event after, say, 10 minutes, though, then it seems like it took multiple triggers, perhaps even one trigger for each connected device (again, that may also be expected behavior).

I don't know how to delete the duplicate device references that are being carried over from desktop; so I can't verify testing from a blank slate unless I test with two simulators, which I haven't - sorry.

## Steps to reproduce
Login to your sync account on Desktop.

Download Install Firefox for iOS, and login with either email or QR code.

Verify and observe your desktop data syncs and is present in Tabs, Bookmarks, and History.

Open a tab and visit any website.

Verify your mobile device has synced with desktop.

Any combination of these seems to reproduce the issue, I'm not sure it actually matters:
Sign out of sync on Firefox iOS, Delete the App, and/or redownload Firefox for iOS.

Verify you are not signed in to sync and have no Bookmarks, History, or Tab data synced.

You see different symptoms of this bug depending on which adventure you chose:

The most exciting is to login with QR code, which requires selecting `Sync New Device` on Desktop in your Sync Settings.
You can also observe a more mundane version of the bug when logging in with email.

Navigate to `Synced Tabs` and observe the connected device referencing your last sync session

If you logged in with QR code, then you'll notice your desktop Sync Setting dropdown still only lists one device.

Open a new Tab on desktop, and observe the tab immediately update on mobile, while neither Bookmarks or History update for 10 minutes or so. Trying to `Sync Now` doesn't seem to work.

If you repeat the above steps and login with QR multiple times, the update delay seems to take longer than just 10 minutes.

If you login multiple times with email, you'll still get multiple devices being connected, resulting in the same issues:

![Screenshot 2023-10-18 at 2 07 17 PM](https://github.com/mozilla-mobile/firefox-ios/assets/107960801/b2455e95-682f-4235-8294-4b078c0da59f)

The only different is on desktop, you'll see an updated list of which devices it thinks it's connected to.

### Device & build information
* Device: iPhone 14 iOS 16.6
* Build version: Desktop 118.0.2, iOS 119
* First seen version: About a month ago

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7602)

**Comment by data-sync-user** [comment]
➤ Norberto Andres Furlan commented:

Lougenia Bailey can you take a look at this?

**Comment by data-sync-user** [comment]
➤ Lougenia Bailey commented:

Norberto Andres Furlan I think a number of things are being conflated here. For instance there isn’t a force sync button or functionality that I’m aware of and the send tab list (the first screenshot) wouldn’t be indicative of whether bookmarks and history can sync. In short, other than the duplicate device entry on the send tab screen and maybe latency issues, I’m not sure what other issues there may be.

**Comment by data-sync-user** [comment]
➤ Daniela Arcese commented:

Lougenia Bailey is the time it is taking to sync a bug? Or is it normal to take 20 minutes?

**Comment by data-sync-user** [comment]
➤ Lougenia Bailey commented:

Daniela Arcese Firefox iOS determines how often timed syncs are triggered. For iOS it’s 15 minutes (see here ( https://github.com/mozilla-mobile/firefox-ios/blob/73c121eb0ec2b1f582f554740fba1a55a919cb7b/Providers/RustSyncManager.swift#L108 ) for details).

**Comment by data-sync-user** [comment]
➤ Daniela Arcese commented:

Is that the same for clicking the Sync Now button in settings? I think that is what is meant by force sync

**Comment by data-sync-user** [comment]
➤ Lougenia Bailey commented:

In the above write up the delay seems to refer to the timed syncs. However, if a sync is triggered from the settings menu the results should be seen relatively immediately. If not we would need the user logs to troubleshoot.

**Comment by lougeniaC64** [comment]
@jjSDET Are you meaning to say that there is sync latency after connecting to sync on desktop, installing Firefox iOS, and connecting to sync there? If so, we'd need more data to determine where the issue originates (this might not be an iOS issue). First, if you could send your sync logs that would be helpful. Secondly, if you could download the about sync extension on desktop, navitage to `about:sync`, and verify that the tabs, history, and bookmarks you expect to see are reflected in the displayed tables that would be extremely helpful.
