### ISSUE TITLE
Hi! You are the best, thank you :) I have a small problem with the interface on the iphone 5s. The on/off buttons is so small that it's very difficult to hit. See screenshot attached:

### ISSUE THREAD

**Issue by Citizen2023** [mozilla-mobile/firefox-ios#16946]
Hi! You are the best, thank you :) I have a small problem with the interface on the iphone 5s. The on/off buttons is so small that it's very difficult to hit. See screenshot attached:

![photo_2023-09-07_17-44-32](https://github.com/confirmedcode/Lockdown-iOS/assets/107152491/419ea8f8-7da3-48bf-894d-130e599a149c)

_Originally posted by @v0ltmn in https://github.com/confirmedcode/Lockdown-iOS/issues/154_

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7614)

**Comment by OrlaM** [comment]
This isn't Firefox
