### ISSUE TITLE
Revert shopping CFR behavior

### ISSUE THREAD

**Issue by Verdi** [mozilla-mobile/firefox-ios#16986]
### User Problem
In Issues #16148 https://github.com/mozilla-mobile/firefox-ios/issues/16140 we made the shopping CFRs only dismissible by clicking the close button. This inadvertently makes everything else inactive giving Firefox the appearance of being frozen.

### Ideas for Solution
Let's change the behavior back so that the shopping CFRs work like other CFRs are are dismissible by tapping outside.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7623)

**Comment by data-sync-user** [comment]
➤ Chris Peterson commented:

Michael Verdi is talking to PM and will try to get a decision about whether we should show the more-easily dismissable CFRs more often or more frequently. Will we be able to uplift to 120?

**Comment by data-sync-user** [comment]
➤ Michael Verdi commented:

I filed this issue for the new timing https://github.com/mozilla-mobile/firefox-ios/issues/17010 ( https://github.com/mozilla-mobile/firefox-ios/issues/17010|smart-link )

**Comment by data-sync-user** [comment]
➤ Alina Moldovan commented:

Verified as fixed using V9000 (35575) and iPhone 14+ (16.0.3).

Confirming that the CFRs are  dismissible by tapping outside
