### ISSUE TITLE
No "Switch Your Default Browser" banner displayed on Home screen

### ISSUE THREAD

**Issue by DianaBarladeanu** [mozilla-mobile/firefox-ios#16981]
**Steps to reproduce**
1. Clean install Firefox iOS
2. Launch Firefox iOS and navigate to the Home screen

**Expected behavior**
The banner to set Firefox as your default browser is correctly displayed on the Home screen.

**Actual behavior**
No banner to set Firefox as your default browser is displayed on the Home screen.

**Device & build information**

* Device: iPhone SE (16.6.1)
* Build version: v120(35427)
* First seen version: v120(35427)

**Notes** 
This issue occurs after fresh install.

Attachments:

https://github.com/mozilla-mobile/firefox-ios/assets/133357955/3b040d36-f017-482a-86da-f18c3fd497cd

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7620)

**Comment by adudenamedruby** [comment]
Hi! The behaviour you're seeing is the new behaviour, and is indended. This is not a bug. This banner should now show only on/after the fourth launch. See #16640 . :D
