### ISSUE TITLE
Amazon tab doesn't load when switching back from the Amazon app

### ISSUE THREAD

**Issue by Verdi** [mozilla-mobile/firefox-ios#17012]
## Steps to reproduce
1. Switch to an unloaded Amazon product page tab OR open an amazon product page tab, force quit Firefox and re-launch it
1. You will be forwarded to the Amazon app
1. Switch back to Firefox

### Expected behavior
The amazon tab is viewable and usable

### Actual behavior
The amazon tab is blank and will never load

### Device & build information
* Device: ? iPhone 15 Pro, iOS 17.0.3
* Build version: ? Firefox 118.2 (34971)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7634)

**Comment by lmarceau** [comment]
Hello! Seems this relates to https://github.com/mozilla-mobile/firefox-ios/issues/16885 which is being worked on. We can double-check that flow works after the fix is out 🙏

**Comment by cpeterso** [comment]
I think this Amazon bug is the same as this YouTube bug: https://github.com/mozilla-mobile/firefox-ios/issues/15718
