### ISSUE TITLE
Change the timing of the Review Checker onboarding CFR

### ISSUE THREAD

**Issue by Verdi** [mozilla-mobile/firefox-ios#17010]
The current onboarding CFR is set to show the first time someone lands on a product detail page. If the user dismisses the CFR and does not opt-in, we show it on the next product detail page after at least 24 hours have elapsed.

We'd like to change this, showing the CFR up to 3X (instead of 2) with at least 12 hrs in-between (instead of 24).

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7633)

**Comment by data-sync-user** [comment]
➤ Chris Peterson commented:

Winnie Teichmann said she would investigate.

**Comment by data-sync-user** [comment]
➤ Alina Moldovan commented:

Verified as fixed using V9000 (35678) and iPhone 14+ (16.0.3).

Confirming that the 2nd CFR is displayed after 12 hours, but  the 3rd CFR is not displayed (a separate issue is logged to track this defect - FXIOS-7646)
