### ISSUE TITLE
Autofill Credit Cards input fields are not labeled programmatically

### ISSUE THREAD

**Issue by anna-yeddi** [mozilla-mobile/firefox-ios#17027]
1. Ensure VoiceOver screen reader is running 
1. Open Firefox iOS 
1. Navigate to Menu > Settings menu
1. Navigate to and activate Autofill Credit Cards button
1. Navigate to and activate "+" button
1. Try to navigate the form with the screen reader
Also:
1. With Voice Control running, try to activate these fields by calling their on-screen names
And:
1. Without any assistive technology, tap the on-screen label to activate the associated input field

Error state:

1. Trigger an error state to either of fields
1. Navigate to the field in error with VoiceOver and observe the announcement 

### Expected behavior
1. Input fields are programmatically labeled: 

* VoiceOver announces the on-screen label as a part of the input field announcement and takes only one swipe to pass through each field. VO would also indicate that there is an error in the field while focusing this field
* Voice Control activates the text field when it's on-screen label is called
* without any AT, tapping on the in-screen label activates the input field

### Actual behavior
1. Input fields are unlabeled and their on-screen labels are not programmatically associated with these fields:

* VO does not announce the label when the field is focused, it takes an extra swipe to pass through the field because the label and the field are focused separately. VO does not indicate any errors while the field is focused, the user has to navigate past the field to learn that their input above was not correct. Users with cognitive difficulties may not be able to make the connection between the error text and that specific text field too
* VC does not recognize the label of the field, it does not react to "Tap Name on Card" command, for example 
* Without any AT, Tapping the label does not focus the associated input

### Device & build information
* Device: iPhone 12 Pro iOS 16.6.1
* Build version: 118.2 (34971)

### Notes
Attachments: 
The VoiceOver does not announce the label of the field. It also requires to have an additional swipe to pass by each field because the on-screen labels are not programmatically associated with their corresponding fields, each takes one swipe to navigate to. ![image](https://github.com/mozilla-mobile/firefox-ios/assets/40773610/d8ca1da8-198d-4876-bebd-2106f9baa31d)
Voice Control does not know labels for these fields and they are just "text"
![image](https://github.com/mozilla-mobile/firefox-ios/assets/40773610/f5b6f9c3-ce05-4a6f-b129-835a84aad2db)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7638)

**Comment by anna-yeddi** [comment]
While the lack of programmatic labels is a major accessibility issue, because this form is short (only 3 fields) and the on-screen labels are present, the severity could be set to access-s3

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Verified as fixed on v122 (37502) with iPhone 15 Pro (17.1.2).
