### ISSUE TITLE
Autofill Credit Cards "+" button is unlabeled

### ISSUE THREAD

**Issue by anna-yeddi** [mozilla-mobile/firefox-ios#17028]
1. Ensure VoiceOver is running
1. Open Firefox iOS 
1. Navigate to Menu > Settings menu
1. Navigate to and activate Autofill Credit Cards button
1. Navigate to "+" button and observe the announcement 
And:
1. With Voice Control, try to activate the "+" button by calling its name

### Expected behavior
1. The image button has proper programmatic label that is describing its functionality: I.e. "Add"

### Actual behavior
1. Voice Control and VoiceOver think the label for the button is "PlusLarge" which is the file name of the icon and is not a predictable label for the action.
1. VoiceOver would add "Add" at the end of the announcement which is likely a Hint, but it's not a label - thus, the access-severity is lowered to S3

### Device & build information
* Device: iPhone 12 Pro iOS 16.6.1
* Build version: 118.2 (34971)

### Notes
Attachments: 
Voice Control thinks the label for the button is "PlusLarge" which is the file name of the icon
![image](https://github.com/mozilla-mobile/firefox-ios/assets/40773610/1878a5ea-493e-46a3-9580-ee080a79579e)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7639)

**Comment by data-sync-user** [comment]
➤ Cyndi Chin commented:

Update expected behavior to Add Card instead of Add
Confirmed with Emily Wachowiak

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v121(36383), on iPhone SE (16.6.1).
