### ISSUE TITLE
Card auto fill Add Credit Card fields are too small to easily tap on

### ISSUE THREAD

**Issue by anna-yeddi** [mozilla-mobile/firefox-ios#17026]
## Steps to reproduce
1. Open Firefox iOS 
1. Navigate to Menu > Settings menu
1. Navigate to and activate Autofill Credit Cards button
1. Navigate to and activate "+" button
1. Try to fill the form by tapping on input fields with a regular sized thumb 

### Expected behavior
1. Input fields are easy to locate, activate and fill

### Actual behavior
1. Input fields take some precision of tapping to activate
1. It is hard to locate the specific area where to tap. Tapping the label does not focus the associated input (separate bug to be filed)

Note: minimum active area should be 24x24 per WCAG 2.2 Level AA criteria but the best practice is to have it at least 48x48 dp or 7x7 mm if measured on the screen. (level AAA and general pattern for more delightful experience for all users)

### Device & build information
* Device: iPhone 12 Pro iOS 16.6.1
* Build version: 118.2 (34971)

### Notes
Attachmentss: 
Size of the active, tappable areas for the field is outlined by VoiceOver to visualize the fields size
![image](https://github.com/mozilla-mobile/firefox-ios/assets/40773610/bd14fe5b-0a1c-4282-952a-8809d4c2c3b0)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7637)

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Verified as fixed on v122 (37071) with iPhone 15 Pro (17.1.2).
