### ISSUE TITLE
Update of Fakespot design and string to accomodate for localizations

### ISSUE THREAD

**Issue by Delphine** [mozilla-mobile/firefox-ios#17044]
Currently, this string (and the design) doesn't work for most languages:
String ID: `Shopping.OptInCard.Disclaimer.Title.v120`
String: `By selecting “Yes, Try It” you agree to the %@:`

What comes after the colon are buttons reading "Privacy policy" and "Terms and conditions" (see screenshot) - so the way the current string and design are constructed assume that languages work like English in terms of plurals and construction of sentences, which is rarely the case. Since the sentence is in isolation, that results in even more awkward translations.

On Android, the design worked around and used this string: `By selecting “Yes, try it” you agree to %1$s by Mozilla’s %2$s and %3$s.`, where the first parameter is the Fakespot product name, and the following parameters are for clickable texts defined in review_quality_check_contextual_onboarding_privacy_policy and review_quality_check_contextual_onboarding_terms_use. (and all this is called out in l10n comments for clarity).
Note: I know the "Fakespot by Mozilla" will get updated to "Fakespot" in Android, but the workaround remains the same

Should we update the design and string like in Android to fix this?

Cc ewachowiak and klowermoz for Content Design input, and CC thatswinnie for iOS dev visibility.
![Contextual Onboarding](https://github.com/mozilla-mobile/firefox-ios/assets/399020/309d7662-ca9f-49eb-a039-8735ade26a19)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7642)

**Comment by klowermoz** [comment]
Hi @Delphine - We are actually planning to change the Android strings to be more like iOS because of an accessibility issue with having both links in one sentence. (And, for iOS having two links in one sentence is not possible from an eng standpoint.)

Would any of the following phrasings be 'better'? Or, is the colon followed by a list of items generally NOT going to work for localization?
 
1
By selecting "Yes, Try It" you agree to:
Fakespot's privacy policy
Fakespot's terms of use 

2
By selecting "Yes, Try It" you agree to these items:
Fakespot's privacy policy
Fakespot's terms of use

3
By selecting "Yes, Try It" you agree to the following from Fakespot:
Privacy policy
Terms of use

**Comment by Delphine** [comment]
I think that option 3 avoids most possible issues with plural/gender/sentence construction, and is easier to workaround.
The trade-off is that it's a bit longer and may require more text space. If space is a concern, option 2 is a good compromise.

**Comment by data-sync-user** [comment]
➤ Chris Peterson commented:

Kate says this issue is on hold because the L10n team raised some new issues with the proposed design.

**Comment by klowermoz** [comment]
Thanks @Delphine. I've updated our string inventory and the mobile Figma files to go with option 3 and will suggest this as a localization note for engineers: After the colon, what appears are two links, each on their own line. The first link is to a Privacy policy. The second link is to Terms of use.

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Verified as fixed on v120 (35966) with iPhone 13 Pro (15.7.1).

The correct text is displayed: By selecting "Yes, Try It" you agree to the following from Fakespot:.

Please note that I added a bug ( https://github.com/mozilla-mobile/firefox-ios/issues/17258 ) regarding the space between Privacy policy and Terms of use hyperlink buttons.
