### ISSUE TITLE
Fakespot - the 3rd CFR is not displayed 

### ISSUE THREAD

**Issue by alinamoldovan84** [mozilla-mobile/firefox-ios#17062]
## Steps to reproduce
1. Clean install the FF 
1. Navigate to a PDP 
1. Check the CFR -> The 1st CFR is correctly displayed 
1. From settings move the time 12h forward 
1. Navigate to a PDP 
1. Check the CFR -> The 2nd CFR is correctly displayed 
1. From settings move the time 12h forward 
1. Check the CFR

### Expected behavior
The 3rd  CFR is correctly displayed 

### Actual behavior
The 3rd  CFR is NOT displayed 

### Device & build information
* Device: iPhone 14+ (16.0.3) 
* Build version: V9000 (35650) 
* First seen version: V9000 (35650) 
### Notes
Attachments: 

https://github.com/mozilla-mobile/firefox-ios/assets/124251579/cef7ca05-6c9a-42b3-a0b5-bee23586b27e

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7646)

**Comment by data-sync-user** [comment]
➤ Chris Peterson commented:

Will Rocklin Are we now supposed to show the Fakespot CFR three times? Is this documented somewhere?

**Comment by data-sync-user** [comment]
➤ Will Rocklin commented:

Chris Peterson Yes, 3x each time spaced out by 12 hours. Added this to both Review Checker PRDs based on our convo in slack today:

  * https://docs.google.com/document/d/1jLgwNWkzPEPhUa73d8PCKh7Yfqq8dcbdkIJajywfufU/edit#heading=h.bumg12zg9cle ( https://docs.google.com/document/d/1jLgwNWkzPEPhUa73d8PCKh7Yfqq8dcbdkIJajywfufU/edit#heading=h.bumg12zg9cle|smart-link ) 
  * https://docs.google.com/document/d/1pUaNzZAM3eNMfg9oFzTiOSOxAnskFIsAvkV9ZSBj9iM/edit#bookmark=id.plkfrd3jnbo0 ( https://docs.google.com/document/d/1pUaNzZAM3eNMfg9oFzTiOSOxAnskFIsAvkV9ZSBj9iM/edit#bookmark=id.plkfrd3jnbo0|smart-link )

**Comment by data-sync-user** [comment]
➤ Sorin Paraipan commented:

I've tried several times to reproduce this bug with no success on the latest Nightly 9000 (35678) build. Yoana worked on a CFR-related bug, so maybe that also fixed the shopping CFR, even though I don't see any connection between them.

**Comment by data-sync-user** [comment]
➤ Alina Moldovan commented:

Revalidated this issue using v9000 (35678). the issue is still preproducing.

**Comment by data-sync-user** [comment]
➤ Alina Moldovan commented:

Validated this issue using v120 (35966). Not able to reproduce this issue anymore.
