### ISSUE TITLE
CFR shown on homepage

### ISSUE THREAD

**Issue by alinamoldovan84** [mozilla-mobile/firefox-ios#17063]
## Steps to reproduce
1.  Clean install the FF 
1. Make sure you have “Homepage after four hours of inactivity” activated. Hamburger Menu → Settings → Homepage → check Homepage after four hours of inactivity
1. Navigate to a PDP 
1. Check the CFR -> The 1st CFR is correctly displayed 
1. From settings move the time 12h forward 
1. Foreground the FF App 

### Expected behavior
Homepage is displayed and the CFR should be closed 

### Actual behavior
Homepage is displayed and the CFR is displayed

### Device & build information
* Device:  14+ (16.0.3 
* Build version: V9000 (35650)  
* First seen version: V9000 (35650) 

### Notes
Attachments: 

![image](https://github.com/mozilla-mobile/firefox-ios/assets/124251579/9de3a3de-ddb3-48dc-8d03-16b0a6e087fc)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7647)

**Comment by data-sync-user** [comment]
➤ Alina Moldovan commented:

Please note that the same issue reproduces for review checker bottom sheet

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Verified as fixed on v9000 (35936) with iPhone 13 Pro (15.7.1).

To be checked when the official v120 build will be created with this fix.

Please note that I was able to verify this for both top and bottom toolbars.
