### ISSUE TITLE
Remove SwiftyJSON from RemoteDevices.swift

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#17100]
* Remove SwiftyJSON dependency
* Remove import SwiftyJSON
* Adjust any unit tests where needed
* Add unit tests to cover code not covered

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7667)

**Comment by alentvinsent** [comment]
can i start working on this

**Comment by lmarceau** [comment]
There are PRs opened for this already, so I would say hold off on this work @alentvinsent
