### ISSUE TITLE
Remove SnapKit from FindInPage

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#17108]
* Remove SnapKit from FindInPageBar.swift and BrowserViewController+FindInPage.swift and replace with normal constraints
* Make sure that view still works, add screenshot or video on your PR

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7672)

**Comment by bmihai23** [comment]
Hello, can I work on this issue?

**Comment by lmarceau** [comment]
Yes it can be worked on 😄 There's Contributor OK label, and there's no PR opened for it 👍

**Comment by data-sync-user** [comment]
➤ Laurie Marceau commented:

For QA it can be checked that the find in page bar appears as expected in portrait and landscape on iPhone and iPad

!image-20231113-162708.png|width=1179,height=2556!

!image-20231113-162713.png|width=2556,height=1179!

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v121(36484), with iPhone SE(16.6.1) and iPad Air (15.7).
