### ISSUE TITLE
Remove SnapKit from SearchViewController

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#17109]
* Remove SnapKit from SearchViewController.swift and BrowserViewController.swift with `searchController.view.snp.makeConstraints` and replace with normal constraints
* Make sure that view still works, add screenshot or video on your PR

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7673)

**Comment by pelumy** [comment]
#17420

**Comment by data-sync-user** [comment]
➤ Laurie Marceau commented:

For QA, it can be tested that the search suggestion view appears and works as intended in the following cases:

  * Top and bottom URL on iPhone. You can select search suggestions, dismiss them, and so on.
  * With iPad and in multitasking mode, the search suggestions show and works as expected
  * In all of those cases, the search engine bar at the bottom of the suggestions page should behave as expected too.

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Validated on v9000 (36897) with iPhone 15 (17.1) and with iPad Air 3rd gen(17.3).

To be rechecked once the v122 build is officially released.

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Validated on v122 (36988), with iPhone 15 (17.1) and with iPad Air 3rd gen (17.3).
