### ISSUE TITLE
Remove SnapKit from TabPeekViewController

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#17110]
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7674)

**Comment by bmihai23** [comment]
Hi @PARAIPAN9, I would like to work on this issue! Thank you.

**Comment by lmarceau** [comment]
Go for it @bmihai23 🙌

**Comment by data-sync-user** [comment]
➤ Yoana Rios Diaz commented:

Note to QA: Confirm that the preview for Tabs long press and actions continues to work as expected in the TabTray

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Verified as fixed on v9000 (36863) with iPhone 15 Pro Max (17.1.2).

Please note that this issue will be closed when the official build v122 is created and verified on that

https://github.com/mozilla-mobile/firefox-ios/issues/13556 ( https://github.com/mozilla-mobile/firefox-ios/issues/13556|smart-link )  Yoana Rios Diaz This is pretty old but might be related to this.

**Comment by data-sync-user** [comment]
➤ Yoana Rios Diaz commented:

Andrei Bodea yes it's worth double checking maybe the removal of SnapKit fix the issue

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Well, I did test on the latest v9000 that has this fix and it’s the same as that video from today (where the issue is). 
So looks like it’s not fixed by this or I’m wrong?

**Comment by data-sync-user** [comment]
➤ Yoana Rios Diaz commented:

Sorry I missed the update with today’s videos, so let’s keep the issue open and check if it is present in the refactoring once it is done. I will add to Tab Tray refactor epic
