### ISSUE TITLE
Remove SnapKit from SettingsContentViewController

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#17112]
* Remove SnapKit from SettingsContentViewController and replace with normal constraints
* Make sure that view still works, add screenshot or video on your PR

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7675)

**Comment by bmihai23** [comment]
Hi, I would like to work on this issue! Thank you

**Comment by data-sync-user** [comment]
➤ Laurie Marceau commented:

For QA it can be checked the About your rights page, and the Licenses page under settings are showing as expected 

!image-20231116-152633.png|width=1179,height=2556!

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v121(36341), with iPhone SE (16.6.1).
