### ISSUE TITLE
CSS `vh` units on element `height` breaks page scrolling

### ISSUE THREAD

**Issue by valler** [mozilla-mobile/firefox-ios#17142]
## Steps to reproduce
Visit one of the repro sandboxes, which ever works best for you:

* StackBlitz: https://stackblitz.com/edit/vh-scroll-bug-repro-repo?file=index.html
* CodeSandbox: https://codesandbox.io/s/viewport-height-scroll-bug-firefox-ios-g9xdzs

### Expected behavior
Page A in the sandbox demos the expected behaviour.
Scrolling back up from the bottom of the page works just like scrolling back up from anywhere else within the page.

### Actual behavior
Scroll to the bottom of page B and try to scroll back up. The viewport will stop scrolling almost instantly. Scrolling back up from anywhere else within the page still works as expected.

### Device & build information
* Device: iPhone, iOS 16.2
* Build version: 119.1
* First seen version: ?

### Notes
As mentioned in the sandbox, this bug occurs with different  height and viewport height related properties and units.
The repro shows one particular scenario.

Scripting has to be enabled for this demo to work, but the bug is reproducible with HTML and CSS alone.
All the script does is to set the height of an element to a value bigger than the viewport height.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7686)

**Comment by lmarceau** [comment]
This seems to relate to https://github.com/mozilla-mobile/firefox-ios/issues/11574
