### ISSUE TITLE
Fix contentEdgeInsets in FakespotMessageCardView

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#17184]
LinkButton and primaryButton are subclass of LegacyResizableButton. They should instead be

* LinkButton should be a subclass of LinkButton from the ComponentLibrary
* primaryButton should be a subclass of PrimaryRoundedButton from the ComponentLibrary
* All `contentEdgeInsets` and other warnings should be fixed
* Add screenshots of your changes before/after on the PR

```java
⚠️  'contentEdgeInsets' was deprecated in iOS 15.0: This property is ignored when using UIButtonConfiguration
        roundedButton.contentEdgeInsets = UIEdgeInsets(
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7704)

**Comment by data-sync-user** [comment]
➤ Alina Moldovan commented:

Winnie Teichmann could you please add more details for the QA team to know what should test here?

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Validated on v123(38163), with iPhone 15 (17.0).

The re-analysis card looks correct and is accessible.

The “Report back in stock” button is accessible, but it has an incorrect font color in dark mode. It is white instead of black.

!dark.jpeg|width=295,height=640!

**Comment by lmarceau** [comment]
@bmihai23 would you might having a look into last comment? 

Here's the attached image
![dark](https://github.com/mozilla-mobile/firefox-ios/assets/11338480/d8b2386e-d809-465c-b7f2-b2e1538f6dbc)

**Comment by bmihai23** [comment]
@lmarceau, I checked and run the app on two versions of iOS 17 and this is how it looks. I didn't find anything suspect in my code

<img width="758" alt="Screenshot 2024-01-29 at 8 34 43 PM" src="https://github.com/mozilla-mobile/firefox-ios/assets/74779930/daa02360-2a19-43f2-86bf-3e09c3792040">

**Comment by lmarceau** [comment]
@alinamoldovan84 could you help us to know what would need to change here? Thank you 🙏

**Comment by data-sync-user** [comment]
➤ Winnie Teichmann commented:

Alina Moldovan The screenshot you posted looks exactly like the card should look like in dark mode according to Figma ( https://www.figma.com/file/VE5xayz3yOSB5qOATUU9Im/Mobile-Shopping-Experience-MVP?type=design&node-id=5283-77854&mode=dev ). The button text should be white in light and dark mode.
