### ISSUE TITLE
Remove legacy color from ReaderModeBarView

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#17208]
ReaderModeBarView is using `UIColor.Photon.Grey50` for a line color

Let’s use the new theming system instead following [guidelines](https://github.com/mozilla-mobile/firefox-ios/wiki/Theming-system).

* `UIColor.Photon` or `UIColor.theme` should not be called at all.
* LegacyThemeManager should not be used.

Please add screenshots of your changes on the PR

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7717)

**Comment by bmihai23** [comment]
Hi @PARAIPAN9, I would like to work on this issue. Thank you!

**Comment by PARAIPAN9** [comment]
Yes, sure, go ahead!!

**Comment by data-sync-user** [comment]
➤ Yoana Rios Diaz commented:

Note to QA: Confirm that ReaderModeBarView theming works as expected. This is the bar shown when ReaderMode is active where the font can be changed and add items to reader list

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Validated on v9000(36863), with iPhone 15 (17.1).

To be rechecked once the v122 build is officially released.

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Validated on v122 (36988), with iPhone 15 (17.1).
