### ISSUE TITLE
The title and description from the onboarding cards are missing

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/firefox-ios#17227]
## Steps to reproduce
1. Install v120 (35899).
2. Launch FF and observe all 3 onboarding cards.
### Expected behavior
The title and description from the onboarding cards should be correctly displayed
### Actual behavior
The title and description from the onboarding cards are missing
### Device & build information
* Device: iPhone 13 Pro (15.7.1) 
* Build version: v120 (35899) 
* First seen version: v120 (35899). 
### Notes
Attachments: 

https://github.com/mozilla-mobile/firefox-ios/assets/42831109/de2771ee-865a-4b2d-9262-8990a14c003b

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7725)

**Comment by data-sync-user** [comment]
➤ Daniela Arcese commented:

Joseph Rahme can you please take a look at this

**Comment by data-sync-user** [comment]
➤ Daniela Arcese commented:

This is happening because the strings have not been imported yet. It should be fixed on the next import which is scheduled for 11/13

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Thank you, Daniela, this means that next week with the RC build we will receive this one will be fixed? As there will be no more beta builds.

**Comment by data-sync-user** [comment]
➤ Alina Moldovan commented:

Validated this issue as fixed using FF v120 (36066) and iPhone SE (16.6) and iPhone 14+ (16.0.3)
