### ISSUE TITLE
"RustMozillaAppServices" Library not found for -ld_classic 

### ISSUE THREAD

**Issue by adityagi02** [mozilla-mobile/firefox-ios#17231]
Tried building this app, getting error as:
`Library not found for -ld_classic` ❌ 
`Linker command failed with exit code 1 (use -v to see invocation)`
for package **RustMozillaAppServices**

Any help will be appreciated.

### Device & build information
* Device: iPhone 14, iOS 14
* XCode version: 14.3.1
### ss
<img width="970" alt="Screenshot 2023-11-08 at 7 44 51 PM" src="https://github.com/mozilla-mobile/firefox-ios/assets/77538183/364b3510-c3f7-43a5-920e-2d100216c09e">

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7727)

**Comment by lmarceau** [comment]
Hello! I see in your screenshot the deployment being set as 14.0. We support 15.0 and up, and we also set the deployment target through [configuration](https://github.com/mozilla-mobile/firefox-ios/blob/main/Client/Configuration/Common.xcconfig) files (so not directly in the Info page as you've done here). If you revert this change, can you build the app? Please make sure to follow the [readme guidelines](https://github.com/mozilla-mobile/firefox-ios#building-the-code) on how to build the code
