### ISSUE TITLE
On iOS when clicking “Edit Bookmarks” there is no distinction between a main folder and sub-folder

### ISSUE THREAD

**Issue by dorfli** [mozilla-mobile/firefox-ios#17249]
Hi,
There is no indentation on subfolders when editing bookmarks.

I am on iOS 17, using iPhone 12 mini, Firefox 118.1 (34739).

Here is an image of the issue (and below that is what it should look like):

Issue:
https://user-images.githubusercontent.com/11338480/149828346-5b5db5f9-26b4-447f-9db9-b390690b89cd.png

Should look like this:
https://user-images.githubusercontent.com/11338480/149828381-f33dd8d7-1f0e-4b76-ab3a-6056d12244c5.png

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7733)

**Comment by lmarceau** [comment]
Hello, this is the same as opened issue https://github.com/mozilla-mobile/firefox-ios/issues/13054 I believe.

**Comment by lmarceau** [comment]
@dorfli A contributor has opened a fix which will be part of the v122 release. Let us know when you get that release if this issue is fixed or not, thank you!

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Validated on v9000(36897), with iPhone 15 (17.1).

To be rechecked once the v122 build is officially released.

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Validated on v122 (36988), with iPhone 15 (17.1).
