### ISSUE TITLE
The Review Checker button turns blue but cannot be opened after certain steps `(works after restart)`

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/firefox-ios#17259]
#### Preconditions
Make sure that The Homepage options is set to: `Homepage after four hours of inactivity` to be open.

## Steps to reproduce
1. Install FF and access any product page from amazon.com.
2. Open the `Review checker`.
3. Add FF to background > go to device settings and fast forward 4h and 1m.
4. Return to FF (the Review Checker is dismissed) and the Home Screen is correctly displayed.
5. Access again any product from amazon.com and tap on the Review Checker button.
### Expected behavior
The review checker should be correctly opened and the bottom sheet should be displayed.
### Actual behavior
The Review Checker is not opened after certain steps.
### Device & build information
* Device: `iPhone 13 Pro (15.7.1)` 
* Build version: `v120 (35966)` 
* First seen version: `v120 (35966)` 
### Notes
**Please note that this works after a restart and the review checker can be correctly opened.**
Attachments: 

https://github.com/mozilla-mobile/firefox-ios/assets/42831109/3722f7a0-148f-4d7d-ae45-f94272abb7af

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7737)

**Comment by data-sync-user** [comment]
➤ Alina Moldovan commented:

Validated this issue using FF v9000 (36105) and iPhone 14+ (16.0.3)

Not able to reproduce this issue anymore.
