### ISSUE TITLE
[regression] Restoring a recently-closed page opens it two tabs

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/firefox-ios#17268]
## Steps to reproduce
1. Open any web page, such as example.com. 
1. Close that tab. 
1. Open a new tab or switch to a different tab. 
1. Open Firefox’s hamburger menu > History menu > “Recently Closed” sub-menu. 
1. Select a recently-closed page, such as that example.com page. 
1. After the page loads, open Firefox’s tab view to look at all the tabs currently open. 

### Expected behavior
The recently-closed page should be loaded in the current tab. 

### Actual behavior
The recently-closed tab _is_ loaded in the current tab, but a second copy is also opened in a new tab. 

This bug is not reproduce when restoring closed pages in Firefox’s regular History menu, _only_ pages in the History menu’s “Recently Closed” sub-menu. 

### Device & build information
* Device: iPhone 15 Plus running iOS 17.1.1
* Build version: TestFlight 9000 (35991)
* First seen version:  I bisected older TestFlight builds. **This bug is a regression in build 9000 (35002). This bug is not reproducible in the previous build, 9000 (34959).**

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7741)

**Comment by lmarceau** [comment]
This might have been caused by some work in https://github.com/mozilla-mobile/firefox-ios/issues/14641, will look into this

**Comment by data-sync-user** [comment]
➤ Matthew Reagan commented:

PR with possible related changes https://github.com/mozilla-mobile/firefox-ios/pull/17194/files ( https://github.com/mozilla-mobile/firefox-ios/pull/17194/files|smart-link )

**Comment by cpeterso** [comment]
Closing because I can no longer reproduce this bug. Presumably it was fixed by PR #17194
