### ISSUE TITLE
Incorrect color of search engines toggles

### ISSUE THREAD

**Issue by DianaBarladeanu** [mozilla-mobile/firefox-ios#17273]
**Steps to reproduce**
1. Go to search engines section from FF settings
2. Observe

**Expected behavior**
Search engines toggles' color is blue.

**Actual behavior**
Search engines toggles' color is green.

**Device & build information**
* Device: iPhone SE (16.6.1)
* Build version: v9000(35991)
* First seen version: ? 

**Notes**
Every other toggle in settings is blue.

Attachments: 
<img width="288" alt="Screen Shot 2023-11-13 at 3 19 23 PM" src="https://github.com/mozilla-mobile/firefox-ios/assets/133357955/d903239c-0514-4f98-baa6-9a3a8f99ad37">

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7742)

**Comment by lmarceau** [comment]
This might have been caused by https://github.com/mozilla-mobile/firefox-ios/issues/16892. This means the problem is only in v121. @jigmetdadul do you want to investigate the problem?

**Comment by jigmetdadul** [comment]
> This might have been caused by #16892. This means the problem is only in v121. @jigmetdadul do you want to investigate the problem?

Sure, looking into it!

**Comment by jigmetdadul** [comment]
I have created a request!

**Comment by data-sync-user** [comment]
➤ Alina Moldovan commented:

Validated this issue using FF v9000 (36105) and iPhone 14+ (16.0.3) and iPad 3rd gen (17.0)

!image-20231116-135511.png|width=16.666666666666668%!
