### ISSUE TITLE
The `Learn more in our privacy notice` link is missing from the onboarding card

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/firefox-ios#17288]
## Steps to reproduce
1. Install and Launch FF.
2. Observe the onboarding card.
### Expected behavior
The `learn more in our privacy notice` link should be displayed.
### Actual behavior
The `Learn more in our privacy notice` link is missing from the onboarding card.
### Device & build information
* Device: iPhone 13 Pro (15.7.1) 
* Build version: v9000 (36028) / v120 (36024) 
* First seen version: v9000 (36028) / v120 (36024) 
### Notes
Attachments: 

![image0](https://github.com/mozilla-mobile/firefox-ios/assets/42831109/cbd5cb61-4338-4324-bc47-8b9df6d74e42)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7747)

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v120 (36066), with iPhone SE (16.6.1).
