### ISSUE TITLE
Website icons not showing or blurry in Google search results on multiple devices

### ISSUE THREAD

**Issue by Ashishprasa** [mozilla-mobile/firefox-ios#17287]
When I search for something on Google, the search results show all the websites related to the topic, which is good. However, the website icons are either not showing or are blurry. This issue is happening on all of my devices.

**Steps to reproduce:**

1. On any device, go to Google.
2. Search for a topic.
3. Observe the search results.

**Expected behavior:**

The website icons should be displayed clearly on all devices.

**Actual behavior:**

The website icons are either not showing or are blurry on all devices.

**Device & build information**

| Device | Build version |
|---|---|
| Android phone | FireFox Version 119.0 |
| Windows computer | FireFox Version 119.0.1 |

**Notes:**

This problem is happening on all websites, not just specific ones.

**Attachments:**

* Screenshot of blurry website icons in Google search results on Android phone running Android 6.0
![Screenshot_2023-11-14-13-16-08-40](https://github.com/mozilla-mobile/firefox-ios/assets/105356967/db445976-4522-4702-a926-4f18096b91d4)

* Screenshot of blurry website icons in Google search results on Windows computer running Windows 11
![image](https://github.com/mozilla-mobile/firefox-ios/assets/105356967/e2cf2344-06dc-4a7e-88a6-55cc82fcb8ae)

**Request:**

Please investigate this problem and fix it.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7746)

**Comment by lmarceau** [comment]
Hello, if this is for Android and Desktop then this bug should be opened at the proper places so the right people look at the problem. This repository is only for **Firefox iOS** tickets. I think this should be reported on [Bugzilla](https://bugzilla.mozilla.org/home) instead or you can also open a ticket on the [support forum](https://support.mozilla.org/en-US/). Thank you!
