### ISSUE TITLE
No tab restore after force crash

### ISSUE THREAD

**Issue by DianaBarladeanu** [mozilla-mobile/firefox-ios#17291]
**Steps to reproduce**
1. Load a few webpages in different tabs in both normal and private browsing.
2. Go to FF secret menu and tap on "Force Crash".

**Expected behavior**
Firefox closes.
After reopening FF, a message prompt to restore tabs is displayed. 
After tapping "OK", all previous normal and private tabs are correctly restored. 

**Actual behavior**
"No restore tabs" prompt is displayed after reopening FF, no tabs are restored.

**Device & build information**
* Device: iPhone SE (16.6.1)
* Build version: v120 (36024)
* First seen version: 

Notes
Attachments: 

https://github.com/mozilla-mobile/firefox-ios/assets/133357955/b8d73fea-c083-42c9-b1fd-235dfe6bf77e

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7749)

**Comment by OrlaM** [comment]
Is this just on v120 or also on v119?

**Comment by DianaBarladeanu** [comment]
> Is this just on v120 or also on v119?

Only on v120.

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v120 (36066), with iPhone SE (16.6.1).
