### ISSUE TITLE
Background push notifications showing messageIncoplete error

### ISSUE THREAD

**Issue by skhamis** [mozilla-mobile/firefox-ios#17315]
This regression was introduced in https://github.com/mozilla-mobile/firefox-ios/pull/17222 due to us moving the Viaduct initialization out of RustFirefoxAccounts which `NotificationService` was relying on. 

## Steps to reproduce
1. Have firefox in the background
2. Send a notification from another device

### Expected behavior
1. The push notification shows up with the sent tab (or signed in notification)

### Actual behavior
![image](https://github.com/mozilla-mobile/firefox-ios/assets/436430/59ea2b75-b8f6-45b1-a7cf-e3fccfdebc42)

Semi-related issue: https://github.com/mozilla-mobile/firefox-ios/issues/17313#issue-1993591091
Related issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1864480

### Device & build information
* Device: ? 
* Build version: ? 
* First seen version: ? 
### Notes
Attachments: 

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7761)

**Comment by cpeterso** [comment]
The first Firefox iOS build with this messageIncomplete error is build 9000 (35974). The previous build, 9000 (35936), correctly shows a notification with the sent URL.
