### ISSUE TITLE
Telemetry - password manager

### ISSUE THREAD

**Issue by alinamoldovan84** [mozilla-mobile/firefox-ios#17321]
[~accountid:63e40eb4c2b1cb6b3474280b], remove the following metrics:

* logins.password_detected  =>  A username and password pair was detected
* logins.autofill_prompt_shown   =>  Password autofill prompt was shown
* logins.autofill_prompt_dismissed  =>  Password autofill prompt was dismissed.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7764)

**Comment by data-sync-user** [comment]
➤ Alina Moldovan commented:

the latest comments on the original ticket related to these events: 

!image-20231115-164049.png|width=1316,height=553!

**Comment by data-sync-user** [comment]
➤ Norberto Andres Furlan commented:

Due to current Password Auto fill implementation, we can’t implement the following events:

  * logins.autofill_prompt_shown => Password autofill prompt was shown
  * logins.autofill_prompt_dismissed => Password autofill prompt was dismissed.

**Comment by data-sync-user** [comment]
➤ Stefan Vladut commented:

Norberto Andres Furlan for the logins.password_detected event should it happen when either of those 2 pop-ups with Save/Update credentials show up?

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Verified as fixed on v122 (37367) with iPhone 15 Pro (17.1.2).
