### ISSUE TITLE
CFRs are not displayed correctly in landscape mode (device specific) 

### ISSUE THREAD

**Issue by alinamoldovan84** [mozilla-mobile/firefox-ios#17333]
## Steps to reproduce
1. Trigger a CFR (except the fakespot CFRs). You can use (Meet your personalized homepage (...) or "Your tabs are syncing (...) ")
1. Put the device in landscape mode 
1. Observe the CFRs

### Expected behavior
The CFRs are correctly displayed 

### Actual behavior
The CFRs are displayed on full screen

### Notes: 
* Issue reproducers only using iPhone 14+ (16.0.3) and 14 Pro Max (16.2)
* Not able to reproduce this issue using: iPhone SE (16.6.1), iPhone S (16.6), iPad 3th gen (17.0) nor iPhone 14 Pro (16.6) 
* This issue doesn't reproduce for Fakespot CRFs

### Device & build information
* Device: iPhone 14+ (16.0.3) 
* Build version: v9000 (36105) 
* First seen version: v120 (36066) 

*# 
*## Notes
Attachments: 
<
!--- Screenshots or screen recordings are very helpful for reproducing|width=200,height=183!
 -->

[https://github.com/mozilla-mobile/firefox-ios/assets/124251579/bae2cd4b-93d6-4499-98b1-e027a5e84b7a](https://github.com/mozilla-mobile/firefox-ios/assets/124251579/bae2cd4b-93d6-4499-98b1-e027a5e84b7a)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7768)

**Comment by data-sync-user** [comment]
➤ Dianna Smith commented:

https://github.com/mozilla-mobile/firefox-ios/pull/17338 ( https://github.com/mozilla-mobile/firefox-ios/pull/17338|smart-link )

**Comment by data-sync-user** [comment]
➤ Alina Moldovan commented:

Validated this issue using FF v9000(36137) & FF v120(36138) the following devices: iPhone 14+ (16.0.3), 14 Pro Max (16.2), iPhone S (16.6) and iPad 3th gen (17.0)

Not able to reproduce this issue anymore.
