### ISSUE TITLE
CFR is incorrectly triggerd over webpage (intermittent)

### ISSUE THREAD

**Issue by DianaBarladeanu** [mozilla-mobile/firefox-ios#17334]
**Steps to reproduce**
1. Open a webpage and after that one is loaded go to tabs tray and open another one.
2. Observe

**Expected behavior**
The "Meet your personalized homepage (..)" CFR is displayed after the second webpage is loaded and the user returns to homepage.

**Actual behavior**
The CFR is displayed while the second webpage is loading and remains displayed on the respective webpage.

**Device & build information**
* Device: iPhone SE (16.6.1)
* Build version: v120 (36066)
* First seen version: v120 (36066)

Attachments: 

https://github.com/mozilla-mobile/firefox-ios/assets/133357955/4cb8484f-3190-4475-9205-f6a1605d7086

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7769)

**Comment by data-sync-user** [comment]
➤ Norberto Andres Furlan commented:

Andrei Bodea can we check how often is this happening? And steps to reproduce.  Thanks

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Hello, Norberto Andres Furlansorry for the delay, last week when you tagged me I was in PTO.

Please note that I discussed with Diana the reporter of the issues, she will update the steps in few minutes. 

We were not able to reproduce this issue on v121 (36341) - with different devices. 
The bug might still be there but it is very hard to reproduce as you can see: 

  * A webpage was opened
  * Tap on tabs tray
  * Tap on the + to open a new tab
  * Write fast a new website name and access it

In this time when the loading is happening there is a small transition where the homepage is displayed (including the CFR) and then the CFR remains on the newly opened webpage. 

I would say it’s worth to keep it open for now and in case we will reproduce it again or find better steps we add more info to the bug.

**Comment by DianaBarladeanu** [comment]
This bug randomly reproduced one time out of about 6 fresh installs on v121(36383) in the conditions described above.
