### ISSUE TITLE
Long pressing the build/version info doesn’t actually copy it to the clipboard.

### ISSUE THREAD

**Issue by bloup** [mozilla-mobile/firefox-ios#17364]
## Steps to reproduce
Open settings. Scroll down to the version field. Long press on the version number. You will get a popup saying “copied to clipboard”. Try to paste.

### Expected behavior
It should paste the version and build number

### Actual behavior
It pastes whatever the last thing on your clipboard was.

### Device & build information
* Device: ? 17.2 iPhone 14 Plus
* Build version: ? 119.2 35843
* First seen version: ? This one. Never tried to copy version information from Firefox before until the previous bug report I sent. Ironically also about pasting.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7786)

**Comment by ddh4r4m** [comment]
Can we close this, since it's fix is already merged ?

**Comment by lmarceau** [comment]
@ddh4r4m Issues are closed once they are reviewed and tested by our QA team. Merging the PR doesn't necessarily always mean in the work is done in our workflow :)

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v9000 (41169), with iPhone 15 (17.4).

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v127 (41083), with iPhone 15 (17.4).

!RPReplay_Final1716361649.mp4|width=590,height=1280,alt="RPReplay_Final1716361649.mp4"!
