### ISSUE TITLE
Onboarding shows the "Set as default browser" screen even when Firefox is already the default browser

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/firefox-ios#17396]
## Steps to reproduce
1. Uninstall Firefox.
1. In system settings, set Safari as the default browser.
1. Install Firefox from the App Store.
1. Before running Firefox for the first time, in system settings, set Firefox as the default browser.
1. Now run Firefox for the first time.

### Expected behavior
Firefox onboarding should not show the "Set as default browser" screen, since Firefox is already the default browser.

### Actual behavior
Firefox onboarding does show the "Set as default browser" screen.

### Device & build information
* Device: iPhone 15 Plus running iOS 17.1.1
* Build version: Firefox 120.0 (36138)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7800)

**Comment by lmarceau** [comment]
There's no API from Apple to know we are the default browser. We deduce it from deep links (when Firefox is opened from another application as default), but there's no way to guarantee that information is 1. still true if the user removes us, and 2. dependent that the user opens us from deep links.

**Comment by data-sync-user** [comment]
➤ Roux Buciu commented:

The investigation concluded that there’s no real good way to know if we’re set to default on first run.

I’ve asked Norberto Andres Furlan about possibly extending the idea of this ticket to a better project to cover the needs this ticket implies.

**Comment by data-sync-user** [comment]
➤ Norberto Andres Furlan commented:

Closing this ticket and opening a new one to create an improved logic. Also, will monitor if Apple launches any API to inform about default browsers.
