### ISSUE TITLE
Fakespot - Tablet - Review drawer - incorrect behavior when switching from landscape to portrait   

### ISSUE THREAD

**Issue by alinamoldovan84** [mozilla-mobile/firefox-ios#17406]
## Steps to reproduce
1. Open a PDP page while in portrait mode 
2. Open a new tab (homepage or load a web page)
3. Switch from portrait mode to landscape and than to portrait mode again  

### Expected behavior
The review drawer is closed and the home page/ web page is correctly displayed  

### Actual behavior
The review drawer opens over the homepage/webpage 

### Device & build information
* Device: 121 (36211) 
* Build version: iPad 3rd gen (16.0.3) 
* First seen version: ? 
### Notes
Attachments: 

https://github.com/mozilla-mobile/firefox-ios/assets/124251579/c109147b-414c-4c8b-b5e4-c27b1c4afb2f

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7806)

**Comment by data-sync-user** [comment]
➤ Winnie Teichmann commented:

For QA: This should be fixed with https://mozilla-hub.atlassian.net/browse/FXIOS-7804 ( https://mozilla-hub.atlassian.net/browse/FXIOS-7804|smart-link )

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Verified as fixed on v121 (36341) with iPad Air (15.7).

Please note that after switching between tabs exactly like in the video attachment, on the 2nd webpage there was no review checker displayed as I was not on a webpage with a product. It works well for both landscape and portrait mode.
