### ISSUE TITLE
Address bar icons overlaps after a specific scenario and for specific devices

### ISSUE THREAD

**Issue by alinamoldovan84** [mozilla-mobile/firefox-ios#17403]
## Steps to reproduce
1. Make sure Fakespot is enabled 
2. Navigate to a web page while device is in portrait mode
3. Check the address bar icons => refresh, share, Fakespot price tag/reader mode  icons are present 
4. Open another tab 
5. Put the device in landscape mode 
6. Put the device in portrait mode
7. From tab tray, open the webpage in step 2 
8. Check the address bar icons 

### Expected behavior
All icons are correctly displayed 

### Actual behavior
Address bar icons overlaps

### Notes 
- the issue reproduces only if Fakespot feature is enabled 
- the issue reproduces for the following devices: iPhone 14, iPhone SE si iPhone 14+(16.0.3)  
- the issue doesn't reproduce for tablets, iPhone 13 Pro Max, iPhone 6s (15.7)
- Issue reproducers even if the Fakespot price tag icon is not present   
- The icons are correctly displayed if uses switches again to landscape mode and than to portrait mode  

### Device & build information
* Build version: 121 (36211) 
* First seen version: ? 
### Notes
Attachments: 

https://github.com/mozilla-mobile/firefox-ios/assets/124251579/4791be8e-3b1c-4997-926d-aec71d66616b

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7803)

**Comment by alinamoldovan84** [comment]
video here: 
https://github.com/mozilla-mobile/firefox-ios/assets/124251579/4791be8e-3b1c-4997-926d-aec71d66616b

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v121(36484), with iPhone SE(16.6.1).
