### ISSUE TITLE
New tab with homepage is duplicated when browser is opened again

### ISSUE THREAD

**Issue by pashynskykh** [mozilla-mobile/firefox-ios#17405]
## Steps to reproduce
1. Close all tabs.
1. Close browser.

### Expected behavior
After opening Firefox you have a single tab - homepage.

### Actual behavior
After opening Firefox you have TWO tabs with homepages.

### Device & build information
* Device: iPhone 11, iOS 17.1.1 
* Build version: 120.0 (36138) 

### Notes
Video record:
https://imgur.com/a/q47dvon

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7805)

**Comment by weebler** [comment]
I also have this issue. Ipad OS 120

**Comment by lmarceau** [comment]
Hello! Could you tell us what is your setting for the homepage? So if you go in `Settings` > `Homepage` > and tell us what's your option under `Opening Screen`?

**Comment by pashynskykh** [comment]
Hi @lmarceau
This is happening no matter what is set there (Homepage/Last tab/Homepage after four hours of inactivity). I showed this on the screen record.

**Comment by pashynskykh** [comment]
Looks like this is fixed in v121.0 (36782). Can anyone else confirm this?
