### ISSUE TITLE
Fakespot - iPad - sidebar open/close state resets itself when user changes from landscape to portrait mode  

### ISSUE THREAD

**Issue by alinamoldovan84** [mozilla-mobile/firefox-ios#17419]
## Steps to reproduce
1. Open a PDP while in landscape mode 
2. Review checker sidebar automatically opens 
3. Close the review checker 
4. Switch from landscape mode to portrait mode and than to landscape again 
5. Observe the PDP 

### Expected behavior
Review checker is closed 

### Actual behavior
Review checker is opened 

### Device & build information
* Device: iPad Pro 4th gen (16.6) 
* Build version: 121 (36255) 
* First seen version: ? 
### Notes
Attachments: 

https://github.com/mozilla-mobile/firefox-ios/assets/124251579/eb3fa8d8-9632-44b7-8bce-0e053974e286

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7812)

**Comment by data-sync-user** [comment]
➤ Alina Moldovan commented:

Validated this issue using the following env. v121 (36782) and iPad Pro 4th Gen (16.6)

Not able to reproduce anymore.
