### ISSUE TITLE
Intermittent - Fakespot - iPad - Settings menu cannot be accessed 

### ISSUE THREAD

**Issue by alinamoldovan84** [mozilla-mobile/firefox-ios#17423]
Steps are not clear yet:

## Steps to reproduce
1. Have the sidebar opened while in landscape mode
2. Rotate the device from landscape to portrait mode multiple times (put the app in background?)
3. tap the hamburger menu and try to access the settings menu 

### Expected behavior
Settings menu opens 

### Actual behavior
Setting menu doesn't open  

Notes: 

- Able to reproduce this bug twice 
- Every time I was reproducing the bug, the device was previously in standby  
- Only the options that redirects to setting menu are not working 

### Device & build information
* Device: iPad Pro 4th gen (16.6) 
* Build version: 121 (36255) 
* First seen version: ? 
### Notes
Attachments: 

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7815)

**Comment by alinamoldovan84** [comment]
video here: 

https://github.com/mozilla-mobile/firefox-ios/assets/124251579/0cb28ce8-fd2c-44d5-bc28-dc2c4a6ea393

**Comment by data-sync-user** [comment]
➤ Alina Moldovan commented:

Validated this issue using the following env. v121 (36782) and iPad Pro 4th Gen (16.6)

Not able to reproduce anymore.
