### ISSUE TITLE
"Wallpapers" section missing from homepage settings

### ISSUE THREAD

**Issue by DianaBarladeanu** [mozilla-mobile/firefox-ios#17427]
**Steps to reproduce**
1. Tap on "Customize homepage" button from homepage or go to "Homepage" settings from hamburger menu
2. Observe

**Expected behavior**
"Wallpapers" section is displayed in homepage settings

**Actual behavior**
"Wallpapers" section is NOT displayed in homepage settings

**Device & build information**
* Device: iPhone SE (16.6.1)
* Build version: v121(36255)
* First seen version: ? 

Attachments: 

https://github.com/mozilla-mobile/firefox-ios/assets/133357955/34e8f74c-4dfc-4760-b996-dc9a325070d6

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7816)

**Comment by adudenamedruby** [comment]
I am very confused. I just downloaded and looked that build and it's there.... ????

https://github.com/mozilla-mobile/firefox-ios/assets/11182210/10fdca40-7b97-4be8-8013-40f3ed6ce8ce

**Comment by abodea** [comment]
Hello, @adudenamedruby can you try with a fresh install, there is a high chance you updated the version from the test flight.

**Comment by afurlan-firefox** [comment]
I verified with a fresh install. I can confirm I don't see the wallpaper options.

**Comment by adudenamedruby** [comment]
yeah, verified with a fresh install as well.

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v121(36341), with iPhone SE (16.6.1).
