### ISSUE TITLE
Intermittent  - Fakespot  - iPad - Sometimes the sidebar is displayed while PDP is opened in portrait mode 

### ISSUE THREAD

**Issue by alinamoldovan84** [mozilla-mobile/firefox-ios#17421]
Steps are not clear yet: 

## Steps to reproduce
1. Have the sidebar opened while in landscape mode 
1. Rotate the device from landscape to portrait mode multiple times  (put the app in background?)
1. Check the PDP page while in portrait mode 

### Expected behavior
Review drawer is displayed 

### Actual behavior
Side bar is displayed 

### Device & build information
* Device: iPad Pro 4th gen (16.6) 
* Build version: 121 (36255) 
* First seen version: ? 

*# 
*## Notes
Attachments: 
<
!--- Screenshots or screen recordings are very helpful for reproducing|width=200,height=183!
 -->
![width=200,height=183](https://github.com/mozilla-mobile/firefox-ios/assets/124251579/902c441a-668d-4c2a-a4bd-1c1d4ceb0c21)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7813)

**Comment by data-sync-user** [comment]
➤ Alina Moldovan commented:

Validated this issue using the following env. v121 (36782) and iPad Pro 4th Gen (16.6)

Not able to reproduce anymore.
