### ISSUE TITLE
Fakespot window shows in Help page

### ISSUE THREAD

**Issue by clarmso** [mozilla-mobile/firefox-ios#17439]
## Steps to reproduce
1. Open `www.amazon.com`.
2. Search for a product (say "shoe").
3. Open the product's page.
4. Tap "tag" icon from the awesome bar.
5. (Enable Review Checker.)
6. Close Review Checker.
7. Tap 🍔 Hamburger menu ➡️ Settings .
8. Tap Support ➡️ Help.

### Expected behavior
Review Checker is not displayed.

### Actual behavior
Review checker is displayed.
![Simulator Screenshot - iPhone 15 Plus - 2023-11-22 at 14 43 58](https://github.com/mozilla-mobile/firefox-ios/assets/1740517/e48e22a3-fdcd-44ae-9f03-193ab4ecbaec)

### Device & build information
* Device: iPhone 15 Plus simulator
* Build version: 122.0 (1)
* First seen version: Not sure
### Notes
Attachments: 

https://github.com/mozilla-mobile/firefox-ios/assets/1740517/7994b615-a5ff-4e50-b136-7d911baaf586

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7821)

**Comment by data-sync-user** [comment]
➤ Winnie Teichmann commented:

Clare So this should be fixed on main and in the latest beta build. Could you please verify?

**Comment by data-sync-user** [comment]
➤ Clare So commented:

Winnie Teichmann I can no longer reproduce the bug today. Let’s close this ticket.

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v121(36383), with iPhone SE (16.6.1).
