### ISSUE TITLE
Remove dead code related to context menu in BVC

### ISSUE THREAD

**Issue by lmarceau** [mozilla-mobile/firefox-ios#17450]
Investigating https://github.com/mozilla-mobile/firefox-ios/issues/17349, it seems that the context menu helper delegate calls in BVC are never used. The context menu is shown from the webview delegate call [here](https://github.com/mozilla-mobile/firefox-ios/blob/bdcc9748917adbdb226973df03ee8dd3c44cc791/Client/Frontend/Browser/BrowserViewController/BrowserViewController%2BWebViewDelegates.swift#L106-L110). So it seems the dead code can be removed.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7822)

**Comment by data-sync-user** [comment]
➤ Laurie Marceau commented:

For QA it can be tested the webview long press contextual menu appears and works as expected (i.e. if you are on a wiki page and long press on a link, a preview and menu appears).

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v9000(36863), with iPhone 15 (17.1).

To be rechecked once the v122 build is officially released.

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v122 (36988), with iPhone 15 (17.1).
