### ISSUE TITLE
Unable to send link through Firefox extension option

### ISSUE THREAD

**Issue by DianaBarladeanu** [mozilla-mobile/firefox-ios#17461]
**Steps to reproduce**

1. Log in with a valid FxA account and sync with at least one device.
1. Open a webpage and from hamburger menu tap on "Share" menu.
1. Select the Firefox extension.
1. Tap on "Send to device" and observe.

**Expected behavior**
The list of available devices is displayed and the link is correctly sent to the selected device.

**Actual behavior**
No connected device is found.

**Device & build information**

* Device: iPhone SE (16.6.1)
* Build version: v121 (36341)
* First seen version: v121 (36341)
Notes
Attachments: 

https://github.com/mozilla-mobile/firefox-ios/assets/133357955/fe0f555c-a68a-4239-addb-571ade35896e

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7826)

**Comment by dicarobinho** [comment]
@DianaBarladeanu trying to reproduce it but no success.
https://github.com/mozilla-mobile/firefox-ios/assets/61138287/3ce0a74e-c625-4cd0-a452-b138abde2da9

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v127 (42300), with iPhone 15 (17.4).
