### ISSUE TITLE
iPad - The url bar doesn't get the focus when opening a new tab

### ISSUE THREAD

**Issue by dragosb01** [mozilla-mobile/firefox-ios#17476]
## Steps to reproduce
Open the app on iPad and open a new tab
### Expected behavior
The url bar should have the focus with the keyboard up
### Actual behavior
The url bar doesn't get the focus
### Device & build information
* Device: ? <iPad mini iOS 17.0>
* Build version: ? <122.0(1), 121.0>
* First seen version: ? Yes
### Notes
**There is a spike of failures on the automation side caused by this issue**
Attachments: 
<img width="546" alt="Screenshot 2023-11-27 at 09 32 03" src="https://github.com/mozilla-mobile/firefox-ios/assets/134391433/6931ef96-0ac8-468a-af3d-4506fdc8592a">

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7832)

**Comment by data-sync-user** [comment]
➤ Alina Moldovan commented:

Validated this issue using FF v121 (36679) and iPad Air 3rd gen (17.0)  & iPad Pro 4th Gen (16.6).

Not able to reproduce this issue anymore.
