### ISSUE TITLE
[regression] After “open in new tab”, the current tab’s title changes to match the new tab’s title

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/firefox-ios#17474]
## Steps to reproduce

1. Open a web page that has links to other pages, such as your favorite news site’s home page.  
2. Open Firefox’s tab tray view and take note of the current tab’s title. 
3. Return to the page view. 
4. Long press on a link to another page and select “Open in New Tab”.
5. When Firefox asks if you’d like to switch to the new tab, you can switch tabs or ignore the prompt. It makes no difference for reproducing this bug. 
6. Open Firefox’s tab tray view and take note of the original tab’s and the new tab’s titles. 

### Expected behavior

The original tab’s title should not have changed. 

### Actual behavior

The original tab’s title has changed to match the new tab’s title. 

### Device & build information

* Device: iPhone 15 Plus running iOS 17.1.1
* First seen version: This bug is a regression in build 9000 (36316). The previous build, 9000 (36259), doesn’t have this bug.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7830)

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v121(36484), with iPhone SE(16.6.1).
