### ISSUE TITLE
Swipe left/right on the address bar to quickly switch to another tab

### ISSUE THREAD

**Issue by peterge1998** [mozilla-mobile/firefox-ios#17472]
### User Problem
> Why should we implement this? What is the user benefit?

I am coming from Fennec on Android, and I am missing the feature to quickly switch to a previous/next tab that I have opened. 

### Ideas for Solution
> Let us know if you have an idea on how to solve this user problem
Just add the swipe detection on the toolbar. Thanks!

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7829)

**Comment by lmarceau** [comment]
Hello, we already have a feature request for that [here](https://github.com/mozilla-mobile/firefox-ios/issues/9095) so I'll close this one as duplicate. Thank you!
