### ISSUE TITLE
Tab tray's page thumbnails skip the top portion of the page visible in the tab

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/firefox-ios#17488]
## Steps to reproduce
1. Load a page with a distinctive header at the top of the page.
1. Open Firefox's tab tray view.
1. Look at the tab tray's thumbnail for the page.

### Expected behavior
The tab tray's page thumbnails should show the top portion of the page visible in the tab.

### Actual behavior
The tab tray's page thumbnails show a portion of the page skipping the top portion of the page visible in the tab.

It's almost as if the page thumbnail is trying to skip the height of the top toolbar, but I can reproduce this bug with both the top and bottom toolbar placement.

### Device & build information
* Device: iPhone 15 Plus running iOS 17.1.1
* Build version: TestFlight build 9000 (36380)
* First seen version: I don't know. This bug is not a recent regression. I can reproduce it in the oldest TestFlight build I have on my phone: build 9000 (34412).

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7837)

**Comment by cpeterso** [comment]
This screenshot of this page shows the GitHub page header and the bug title at the top:

![image](https://github.com/mozilla-mobile/firefox-ios/assets/629193/27273d44-35f1-4aae-9efa-61507dcdee7d)

**Comment by cpeterso** [comment]
But this screenshot of this page’s tab tray thumbnail skips the GitHub header and cuts off post of the bug title:

![image](https://github.com/mozilla-mobile/firefox-ios/assets/629193/6ed1faaa-c55e-4f7b-85f2-d1446b4bc3b8)

**Comment by dnarcese** [comment]
The screenshot depends on where you are scrolled on the page, and then it will start behind the title of the tab. This is what allows the transparency on the tab title. If we wanted to change this behaviour it would be a design change.

**Comment by cpeterso** [comment]
I see. Even if the page is scrolled down, I still think the tab thumbnail should show the top of the page's scrolled viewport, right below the thumbnail's tab title.

**Comment by data-sync-user** [comment]
➤ Laurie Marceau commented:

This will be fixed by the new tab tray, specifically task https://mozilla-hub.atlassian.net/browse/FXIOS-8114 ( https://mozilla-hub.atlassian.net/browse/FXIOS-8114|smart-link )  normally fixed this issue

**Comment by cpeterso** [comment]
Fixed by https://github.com/mozilla-mobile/firefox-ios/issues/18061
