### ISSUE TITLE
Search in Firefox widget does not focus the url bar

### ISSUE THREAD

**Issue by nbhasin2** [mozilla-mobile/firefox-ios#17530]
## Steps to reproduce
- Open Firefox iOS
- Add small search widget by long pressing on iOS System home page
- Tap on the small search widget 

### Expected behavior
- It should open Firefox iOS app and Focus on url bar for user to perform search

### Actual behavior
- Only opens Firefox iOS

### Device & build information
* Device: iPhone 14 Pro
* Build version: 35843
* First seen version: 119.2
Attachments: 
N/A

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7852)

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v9000(36863), with iPhone 15 (17.1).

To be rechecked once the v122 build is officially released.

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v122 (36988), with iPhone 15 (17.1).
