### ISSUE TITLE
Widgets have a white or black outline 

### ISSUE THREAD

**Issue by lmarceau** [mozilla-mobile/firefox-ios#17535]
## Steps to reproduce
Have widgets on your home screen

### Expected behavior
Widgets do not have that white or black outline. Outline is black or white depending of the theme of the OS.

### Actual behavior
![Screenshot 2023-11-29 at 5 10 23 PM](https://github.com/mozilla-mobile/firefox-ios/assets/11338480/4bfe57f2-f29d-48da-b871-fec65767aa49)

### Device & build information
* Device: iPhone and iPad
* Build version: 1731a4405aa9e9d38f5f27ea449d8c70640aa551
* First seen version: v120
*  First seen version in Nightly: 9000(35049)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7854)

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v9000(36863), with iPhone 15 (17.1) and iPad Air 3rd gen (17.0).

To be rechecked once the v122 build is officially released.

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v122 (36988), with iPhone 15 (17.1) and with iPad Air 3rd gen (17.3).
