### ISSUE TITLE
Weird button on account management page

### ISSUE THREAD

**Issue by DianaBarladeanu** [mozilla-mobile/firefox-ios#17584]
**Steps to reproduce**
1. Sign in with a valid FxA account
2. Log in to the account management page and observe

**Expected behavior**
No weird turquoise button showing at the top of the page.

**Actual behavior**
Weird turquoise button shown on the top of the page, doesn't seem to be linked to anything. Tapping on "x" makes it disappear but if you go back to "Account" settings and return to the account management page, it shows up again.

**Device & build information**
* Device: iPhone SE (16.6.1)
* Build version: 121(36567)
* First seen version: 121(36567)

Attachments: 

https://github.com/mozilla-mobile/firefox-ios/assets/133357955/ff460cc1-89d2-4846-b54e-8a5cbc4c471b

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7878)

**Comment by data-sync-user** [comment]
➤ Lauren Zugai commented:

This is a bug on the FxA side and will be taken care of in https://mozilla-hub.atlassian.net/browse/FXA-8723 ( https://mozilla-hub.atlassian.net/browse/FXA-8723|smart-link ).
