### ISSUE TITLE
Improve BackForwardList to decouple from BVC

### ISSUE THREAD

**Issue by lmarceau** [mozilla-mobile/firefox-ios#17624]
FilippoZazzeroni will work on this task

`BackForwardList` VC is currently using BVC for a couple of functionalities. This task is so we decouple the `BackForwardList` from BVC. Part of this ticket is to investigate solutions on how to do that, then open a PR to make the changes to improve that VC.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7889)

**Comment by data-sync-user** [comment]
➤ Laurie Marceau commented:

For QA it can be tested that the backforward list (when long pressing on the back and forward button in the URL bar) works as expected.

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Validated on v9000 (37853), with iPhone 15 (17.0).

To be rechecked once the official v123 build is released.

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Validated on v123 (37946), with iPhone 15 (17.0).
