### ISSUE TITLE
Review Checker's advertised products' price should be formatted with "$", not "USD" prefix

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/firefox-ios#17627]
## Steps to reproduce

1. In a TestFlight build >= version 9000 (36622), open an Amazon page for a standing desk, such as https://www.amazon.com/dp/B0BZ7GXM4M/?th=1
2. Open the Review Checker bottom sheet.
3. Scroll down to see the bottom sheet's ad.

### Expected behavior

The advertised product's price should be formatted with `$`, like this screenshot from Firefox desktop:

![image](https://github.com/mozilla-mobile/firefox-ios/assets/629193/d3c93ed5-d128-4e09-8af0-acb95d1bb806)

### Actual behavior

The advertised product's price is formatted with `USD` and not `$`. See this screenshot from Firefox iOS:

![image](https://github.com/mozilla-mobile/firefox-ios/assets/629193/a315983d-dca9-4275-8fb6-040bb24d07ea)

### Device & build information

* Device: iPhone 15 Plus running iOS 17.1.2
* Build version: build version 9000 (36622)
* First seen version: ? 

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7890)

**Comment by data-sync-user** [comment]
➤ Winnie Teichmann commented:

We are now formatting the ad price according to the users preferences set on the phone so for an iPhone in English and the region United States the price will be shown as $219.99 while for an phone in English but region Germany it will be 219,99 US$.

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v122 (37404), with iPhone 15 (17.0). 

Advertised products' prices are shown with “$” formatting.
