### ISSUE TITLE
FF reverts to non- private browser in spite of proper settings

### ISSUE THREAD

**Issue by gatehealing** [mozilla-mobile/firefox-ios#17742]
## Steps to reproduce
1) Get proper settings for private browsing to always be the default.
2) be sure iPhone and FF are completely up to date.
3) Get into a FF private browsing window and surf around.
4) Close FF for several hours (overnight tends to be most consistent).
5) After several hours (or overnight) open Firefox. Notice that your previously private browser is no longer private.
6) Note: this issue is intermittent, but regular; and is more likely the longer you leave FF closed (not just inactive, but swiped up closed)

### Expected behavior
Given everything is up to date and settings are confirmed as correct, it should always open to private browsing window.

### Actual behavior
After extended closed time, it reverts to Non private browser.

### Device & build information
* Device: ? Iphone 14 max pro; 17.2
* Build version: ?  Thus is not where these directions say it is and I cannot find it.
* First seen version: ?  the happened in iOS 17.1.2 and previous iOS versions as well. Cannot find the build version if that’s what you’re talking about.
### Notes
Attachments: 

Imagine seeing the purple mask icon for private. Then opening FF and not seeing that anymore.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7959)

**Comment by abodea** [comment]
> ➤ Norberto Andres Furlan commented:
> 
> Andrei Bodea can you check this issue and find the steps to reproduce it? Is it happening regularly?

Hello, @afurlan-firefox please note that I did try to let a device with ~2h, and with the steps from the description I tried to repro but had no success, I also moved the time manually a few hours forward to see what is happening but I still had the PB tabs like before. 

I will keep investigating and tonight I will do the steps from the description and try to simulate it over night to see if I can repro it. I will update this in case I find more details.

**Comment by gatehealing** [comment]
Sometimes it’ll be ok for a few days, even a week once, but usually it won’t stay fixed for more than a couple of days at most

Jonathan F. Anderson, LPC-Supervisor (TX), LCMHC (NC)
Texas State Board Approved Supervisor
Licensed Clinical Mental Health Counselor

https://gatehealing.com/

(512) 771-7621
***@***.***

3939 Bee Caves Rd, Ste. A-203
West Lake Hills, Tx 78746

—Notice—
The information transmitted is intended only for the person or entity to which it is addressed and may contain confidential and/or privileged material, the disclosure of which is governed by applicable law.  Any review, retransmission, dissemination or other use of, or taking of any action in reliance upon, this information by persons or entities other than the intended recipient is prohibited. If you received this email in error, please contact the sender and destroy the materials contained in this message.

On Dec 21, 2023, at 7:50 AM, Andrei Bodea ***@***.***> wrote:

﻿

➤ Norberto Andres Furlan commented:

Andrei Bodea can you check this issue and find the steps to reproduce it? Is it happening regularly?

Hello, @afurlan-firefox<https://github.com/afurlan-firefox> please note that I did try to let a device with ~2h, and with the steps from the description I tried to repro but had no success, I also moved the time manually a few hours forward to see what is happening but I still had the PB tabs like before.

I will keep investigating and tonight I will do the steps from the description and try to simulate it over night to see if I can repro it. I will update this in case I find more details.

**Comment by bpsib** [comment]
The last update also closed all my private tabs. I have noticed a setting called "Close Private Tabs When Leaving Private Browsing" which I have turned off. It seems that setting is not properly respected when off.

**Comment by dicarobinho** [comment]
Investigated this behaviour for a while and I successfully reproduced it only once.

Based on "After several hours (or overnight) open Firefox. Notice that your previously private browser is no longer private." (check description), I left Firefox app in private mode, overnight and it happened but only for this time.

After that I left the app in private mode over the weekend and no success. I gave it another chance, overnight, again, but this time no success.

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified on v127 (42183), with iPhone 15 (17.4) and iPhone SE (16.6).

I left the FF app in PB mode over the weekend, no issue encountered. 

Closing the ticket as fixed. Will open a new one if the issue  reappears.
