### ISSUE TITLE
Fix cognitive complexity in first guard of handleDecryptedMessage method at FxAPushMessageHandler

### ISSUE THREAD

**Issue by jvlcapi** [mozilla-mobile/firefox-ios#17759]
Cognitive complexity was identified in the first guard at the _handleDecryptedMessage_ method through static code analysis using Sonar. [Cognitive Complexity](https://www.sonarsource.com/docs/CognitiveComplexity.pdf) is a measure of how hard the control flow of a function is to understand. Functions with high Cognitive Complexity will be difficult to maintain.

Sonar analysis can be found at: https://sonarcloud.io/project/issues?impactSeverities=HIGH&resolved=false&id=lucasasantana_firefox-ios&open=AYqGC7mV6JcGxmGjR1Bl

![Captura de Tela 2023-12-13 às 21 09 44](https://github.com/mozilla-mobile/firefox-ios/assets/37554851/523eefab-bae1-4004-b42d-337b8e485138)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7966)

**Comment by OrlaM** [comment]
This is not a strategy we use to determine areas of the code that should be refactored. You are welcome to open PR's with improvements to areas like this but tickets requesting those changes are not needed. Thanks 🙏
