### ISSUE TITLE
Refactor token(:) function at SyncAuthState to reduce its Cognitive Complexity

### ISSUE THREAD

**Issue by lucasasantana** [mozilla-mobile/firefox-ios#17758]
Cognitive complexity was identified in the first guard at the open method at Account/SyncAuthState.swift through static code analysis using Sonar. [Cognitive Complexity](https://www.sonarsource.com/docs/CognitiveComplexity.pdf) is a measure of how hard the control flow of a function is to understand. Functions with high Cognitive Complexity will be difficult to maintain.

Sonar analysis can be found at: https://sonarcloud.io/project/issues?open=AYqGC7md6JcGxmGjR1Bz&id=lucasasantana_firefox-ios

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7965)

**Comment by OrlaM** [comment]
This is not a strategy we use to determine areas of the code that should be refactored. You are welcome to open PR's with improvements to areas like this but tickets requesting those changes are not needed. Thanks 🙏
