### ISSUE TITLE
The `Credit Card` section is not displayed at launch on a fresh install `(only after 1-2 restarts)`

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/firefox-ios#17766]
## Steps to reproduce
1. Install and Launch FF.
2. Check the settings for the CC section.
### Expected behavior
The CC section should be displayed right after the installation.
### Actual behavior
The `Credit Card` section is not displayed at launch on a fresh install `(only after 1-2 restarts)`
### Device & build information
* Device: iPhone 15 Pro Max (17.1.2) 
* Build version: v121 (36782) 
* First seen version: N/A 
### Notes
Attachments: 

https://github.com/mozilla-mobile/firefox-ios/assets/42831109/07392cfe-0f57-4f1c-9667-0e2f02b8388c

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7969)

**Comment by OrlaM** [comment]
This is expected behaviour. The credit card feature is still an experiment and it is not a first run experiment. To fix this the feature either needs to remove the flag making it permanent or turn it on in the local nimbus config making it a first run experiment.
