### ISSUE TITLE
Review Checker is not scrolling with VoiceOver from Highlights to Show More

### ISSUE THREAD

**Issue by anna-yeddi** [mozilla-mobile/firefox-ios#17764]
## Steps to reproduce
1. Open Firefox, ensure VoiceOver is running
1. Navigate to any amazon product page and open the Review Checker
1. Use logical VoiceOver navigation gestures (one finger swipes right - forward, our left - backward) to navigate to the "Show More" button and observe the VO behavior

### Expected behavior
1. VO user can get to the "Show more" button by navigating from top to bottom, in this case, after hearing the Highlights text (that is on-screen), they can swipe with one finger right and the VO focus would move to the "Show more" button and it will be announced
1. Navigating backward from the bottom of the sheet, from "Show more" the swipe left would move the VO focus to the Highlights text

### Actual behavior
1. Swiping right from the Highlights text indicates that it is the end of the view (the VO beeps when swiping), focus does not move to the "Show more" and the user would have to use explore-by-touch to access the lower part of the sheet, while it is not expected since there is no indication that there is, in fact, anything is presented below the highlights
1. Navigating from the bottom of the sheet up, moves the focus (with a swipe left) from the "Show more" to the "X" close button which is visually removed from the control, missing a half of the content of the Checker, including the grade and adjusted rating.
While it is not fully blocked for a VoiceOver user, the behavior is very cumbersome and confusing. I'd mark it as access-S3, but it is high-access-S3 that is very close to be an access-S2.

### Device & build information
* Device: iPhone 12pro, iOS 17.1.2
* Build version: Fx Beta 9000 (36796)
  1. Notes
Attachments: 
Video of VoiceOver navigation with one finger swipes left/right from the "Close" button directly to the "Show more" and from Highlights not moving down (beeping like it is the end of the view)

https://github.com/mozilla-mobile/firefox-ios/assets/40773610/f6f16443-3c09-4e32-9b29-f43114f971f8

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7970)

**Comment by razvanlitianu** [comment]
hey, I did some testing both on Simulator and Device and I can't seem to reproduce it. Can I get some more context?

Simulator

https://github.com/mozilla-mobile/firefox-ios/assets/26011662/97c856fd-16a8-4125-9dfb-9101bd19af60

Device iPhone 14 Pro iOS 17.

https://github.com/mozilla-mobile/firefox-ios/assets/26011662/cedb8a95-58d0-411b-966d-40831dde5e21

**Comment by dicarobinho** [comment]
I tested this behaviour and I can't reproduce it...
Device: iPhone 12 Pro Max, iOS 16.1.2

https://github.com/mozilla-mobile/firefox-ios/assets/61138287/85f7d60b-a9fb-4be1-ad80-0eb6cae3e982

**Comment by anna-yeddi** [comment]
> I tested this behaviour and I can't reproduce it... Device: iPhone 12 Pro Max, iOS 16.1.2
> FullSizeRender.1.mov

Great news! Thank you for retesting it, @razvanlitianu and @dicarobinho!

AFAIK there was some work done with the Review Checker on iOS since I've originally tested it - whatever was done likely fixed the underlying problem here as well. The original issue was very apparent, both of you would have had encountered it, if it would still be here. 

Let me close this issue with a "yay" :) Thanks again!
