### ISSUE TITLE
Fakespot - Sidebar incorrectly opens on a non-PDP page after a specific scenario 

### ISSUE THREAD

**Issue by alinamoldovan84** [mozilla-mobile/firefox-ios#17776]
## Steps to reproduce
1. Open a PDP and open the sidebar 
1.  Open a new tab and search for a product (or open a section of products)
1. Long tap on a product and choose to open it's PDP in a new tab 
1. Observe the changes on the current tab 

### Expected behavior
Sidebar should not be displayed in a non -PDP page 

### Actual behavior
Sidebar opens on the search page 

### Device & build information
* Device: iPad Pro 4th Gen (16.6) 
* Build version: v121 (36782) 
* First seen version:  v121 (36782) 
### Notes
Attachments: 

https://github.com/mozilla-mobile/firefox-ios/assets/124251579/50bbab8f-580e-4013-9cb4-50e19f16aef0

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7977)

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified on v122 (37131), with iPad Air 3rd gen. The issue is still reproducible.

**Comment by data-sync-user** [comment]
➤ Alina Moldovan commented:

Verified as fixed using V9000 (37808) using iPad Pro 4th Gen (16.6)

**Comment by data-sync-user** [comment]
➤ Alina Moldovan commented:

Validated as fixed using FF v123 (38283) and iPad Pro 4th Gen (16.6)
