### ISSUE TITLE
Improve PasswordManagerOnboardingViewController

### ISSUE THREAD

**Issue by lmarceau** [mozilla-mobile/firefox-ios#17839]
bmihai23 wants to work on the following improvement in PasswordManagerOnboardingViewController:

* onboardingMessageLabel, learnMoreButton and continueButton are not declared using .build, 
* a deprecation message for 'titleEdgeInsets'
* There is no private struct UX to hold constant values

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7995)

**Comment by Hari318** [comment]
Replacing learnMore button with .build makes the button color white with below code.

`private lazy var learnMoreButton: UIButton = .build { [weak self] button in
        button.titleLabel?.font = DefaultDynamicFontHelper.preferredFont(withTextStyle: .body, size: 19)
        button.titleLabel?.adjustsFontForContentSizeCategory = true
        button.setTitle(.LoginsOnboardingLearnMoreButtonTitle, for: .normal)
        button.addTarget(self, action: #selector(self?.learnMoreButtonTapped), for: .touchUpInside)
    }`
    
Any suggestion on how to make text color blue, do we need to conform to `Themable` protocol and set color for that button?

**Comment by lmarceau** [comment]
@Hari318 Hello! There's already a PR opened for this issue, so I would say it's preferable for you to work on another issue marked as "Contributor OK". Thank you!

**Comment by Hari318** [comment]
Okay, My Bad, I thought the issue was re-opened. Thank you.

**Comment by data-sync-user** [comment]
➤ Alina Moldovan commented:

Laurie Marceau could you please add some details for the QA team to know what to test?  Thank you!

**Comment by data-sync-user** [comment]
➤ Cyndi Chin commented:

Alina Moldovan Please see these screenshots on where to validate the UI. This is the onboarding screen on the Passwords page  in Settings. Let me know if more details are needed!

!image-20240119-150157.png|width=857,height=1177!

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Validated on v123(38120), with iPhone 15 (17.0).
