### ISSUE TITLE
Remove Deferred usage from ContentBlocker

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#17887]
Remove `Deferred` usage from `ContentBlocker`. In particular, the following code section should be using completion handlers instead of `Deferred` object for async:

```
    func removeAllRulesInStore(completion: @escaping () -> Void) {
        ruleStore?.getAvailableContentRuleListIdentifiers { [weak self] available in
            guard let available = available else {
                completion()
                return
            }
            let deferreds: [Deferred<Void>] = available.map { filename in
                let result = Deferred<Void>()
                self?.ruleStore?.removeContentRuleList(forIdentifier: filename) { _ in
                    result.fill(())
                }
                return result
            }
            all(deferreds).uponQueue(.main) { _ in
                completion()
            }
        }
    }
```

Add unit tests as well if possible.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-8016)

**Comment by ddh4r4m** [comment]
What do you mean ? are you asking to replace this with dispatch group ? 

```
func removeAllRulesInStore(completion: @escaping () -> Void) {
    let group = DispatchGroup()

    ruleStore?.getAvailableContentRuleListIdentifiers { [weak self] available in
        guard let available = available else {
            completion()
            return
        }

        for filename in available {
            group.enter()
            self?.ruleStore?.removeContentRuleList(forIdentifier: filename) { _ in
                group.leave()
            }
        }

        group.notify(queue: DispatchQueue.main) {
            completion()
        }
    }
}
```

**Comment by data-sync-user** [comment]
➤ Sophie Amin commented:

QA: When V122 is released please test Ad Tracker Blocking

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Validated on v122 (37313), with iPhone 15 (17.0).

**Comment by data-sync-user** [comment]
➤ Laurie Marceau commented:

Hola! Just checking, I think this was merged for v123 Diana Andreea Barladeanu Sophie Amin (as this was merged to main yesterday, and we’re currently building v123 on main. v122 is on a release branch)

**Comment by data-sync-user** [comment]
➤ Sophie Amin commented:

Diana Andreea Barladeanu Laurie Marceau Whoops, thank you for catching that! Yes this is still unreleased.
