### ISSUE TITLE
Fix closeButton warnings in TabCell

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#17883]
Fix `closeButton` warnings in `TabCell`. Please include screenshot of before/after your changes on the PR.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-8012)

**Comment by Prathameshchakote** [comment]
Hi @lmarceau ,
I want to contribute to this task. can you please help me to get access to Jira task?
thanks

**Comment by lmarceau** [comment]
@Prathameshchakote Hello! The JIRA task doesn't contain more information than the GitHub ticket. JIRA is only used for internal purposes - like using JIRA boards to triage and organize tasks. Let me know if the task is unclear or require more information, I'm happy to add some more!

**Comment by Prathameshchakote** [comment]
Hi @lmarceau ,
Thank you for the clarification. I got the issue. So I am replacing 
` button.imageEdgeInsets = UIEdgeInsets(equalInset: LegacyGridTabViewController.UX.closeButtonEdgeInset)
`

with following. right?

```
button.configuration?.imagePadding = LegacyGridTabViewController.UX.closeButtonEdgeInset
        button.configuration?.contentInsets =  NSDirectionalEdgeInsets(top: LegacyGridTabViewController.UX.closeButtonEdgeInset,
                                                                       leading: LegacyGridTabViewController.UX.closeButtonEdgeInset,
                                                                       bottom: LegacyGridTabViewController.UX.closeButtonEdgeInset,
                                                                       trailing: LegacyGridTabViewController.UX.closeButtonEdgeInset)
```

**Comment by lmarceau** [comment]
@Prathameshchakote That seems like the logical change yes 😄 You can open a PR and add some screenshots of before and after your changes 🙏 Thank you!
