### ISSUE TITLE
Scroll position not preserved when going back

### ISSUE THREAD

**Issue by jrmuizel** [mozilla-mobile/firefox-ios#17922]
## Steps to reproduce
- Load https://news.ycombinator.com
- Scroll to the bottom
- load the comments link at the bottom
- Hit the back button

### Expected behavior
- Scroll position on https://news.ycombinator.com should be the same as it previously was

### Actual behavior
- Scroll position is at the top of https://news.ycombinator.com

### Device & build information
* Device: ? iPhone 14 Mini iOS 17.1.2
* Build version: Firefox 121.0 (36782) (Toolbar at the top)
* First seen version: ? I don't think this was happening before

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-8033)

**Comment by lmarceau** [comment]
Duplicates https://github.com/mozilla-mobile/firefox-ios/issues/16643 so I'll close this one here for now
