### ISSUE TITLE
Significant delay when opening new private tab from Home Screen quick action menu

### ISSUE THREAD

**Issue by TollyH** [mozilla-mobile/firefox-ios#17951]
## Steps to reproduce

- Hold down the Firefox app icon on the Home Screen
- Click "New Private Tab"
- The issue does not always occur. The delay seems to be proportional to the speed of the current internet connection. Closing the app from the app switcher first may make the issue more consistent

### Expected behavior

A new private tab is opened more or less instantaneously, with no risk of starting a search in a normal tab

### Actual behavior

A noticeable delay before the new private tab opens, especially noticeable on slower internet connections, in which time any searches made will happen in a regular tab (i.e. online search suggestions will be shown)

### Device & build information
* Device: iPhone 13 Pro Max, iOS 17.2.1 (21C66)
* Build version: Firefox 121.0 (36782)
* First seen version: Unsure of exact version, but it has only been occurring for the last couple of weeks or so
### Notes
Attachments: 
https://github.com/mozilla-mobile/firefox-ios/assets/34184902/6f7f73fc-aef5-4b52-9a86-1a2aec7c7b92
https://github.com/mozilla-mobile/firefox-ios/assets/34184902/5677069d-2823-4d31-8853-d91ef0dbe0b4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-8050)

**Comment by dnarcese** [comment]
Thanks for reporting. I am going to close this as we are tracking these in different issues
#10054
#17787
