### ISSUE TITLE
Firefox on iOS crashes when closing all tabs.

### ISSUE THREAD

**Issue by zishan4k** [mozilla-mobile/firefox-ios#17957]
## Steps to reproduce
Close all tabs on firefox for iOS

### Expected behavior
Close all existing tabs and open one new tab of homepage

### Actual behavior
Firefox abruptly closes, and when reopen, firefox message displays saying "Firefox unexpectedly crashed. Do you want to restore tabs?". To which you have the option to restore tabs, or start a new tab. 

### Device & build information
* Device: ? iPhone 14 Pro Max. iOS 17.2
* Build version: ? 935044
* First seen version:  About a month ago.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-8053)

**Comment by zishan4k** [comment]
Correction: iOS version is 17.1.2

**Comment by data-sync-user** [comment]
➤ Norberto Andres Furlan commented:

Andrei Bodea I was not able to reproduce it on nightly and v121. Can you try to reproduce it?

**Comment by zishan4k** [comment]
It happens to me around 70% of the time when i close all tabs on Firefox mobile for iOS. This is what I see when i reopen Firefox after it crashes. 

![IMG_0889](https://github.com/mozilla-mobile/firefox-ios/assets/96551820/62627562-d6ec-42e8-a294-e57f419b8815)

**Comment by zishan4k** [comment]
I reinstalled Firefox again on my iPhone and the issue has seemed to have gone! I will be closing this issue now
