### ISSUE TITLE
Firefox is unresponsive on cold start

### ISSUE THREAD

**Issue by Verdi** [mozilla-mobile/firefox-ios#17960]
## Steps to reproduce
1. Make sure Firefox is not running
1. Start Firefox

### Expected behavior
Firefox should display the homepage or a website and be fully responsive right away. 

### Actual behavior
Firefox opens and appears frozen for approximately 20 seconds.

### Device & build information
* Device: iPhone 12 Pro, iOS 17 (I also viewed this happening on an iPhone 15, iOS 17) 
* Build version: 121.0 (36782)
* First seen version: Don't know - says it's been happening for weeks or longer.
### Notes
Attachments: 

https://github.com/mozilla-mobile/firefox-ios/assets/107992/05d1023b-835c-47a4-af94-476b15665d72

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-8056)

**Comment by mladen5000** [comment]
I am having a similar issue. The freezing will begin only when I tap the url bar however. This began for me a few weeks ago.

**Comment by lmarceau** [comment]
I think this issue was fixed in v122?

**Comment by Verdi** [comment]
The start up freeze seems to be fixed in 122 but I just reproduced the same freeze as @mladen5000 when tapping the address bar. 

https://github.com/mozilla-mobile/firefox-ios/assets/107992/83602fc7-2147-4c66-964f-14de7de87932

**Comment by lmarceau** [comment]
@Verdi I think then this relates to the following conversation https://mozilla.slack.com/archives/C05C9RET70F/p1706289800580929 👀

**Comment by nbhasin2** [comment]
https://mozilla-hub.atlassian.net/browse/FXIOS-8107 verified here
