### ISSUE TITLE
iOS preferred language change fails to update Firefox search key labels

### ISSUE THREAD

**Issue by Zippy3514** [mozilla-mobile/firefox-ios#17987]
![IMG_2268](https://github.com/mozilla-mobile/firefox-ios/assets/155667837/0e46ca15-faa6-4e3e-a5ac-d984b179bca5)
![IMG_2267](https://github.com/mozilla-mobile/firefox-ios/assets/155667837/65d3e952-702c-47a5-810b-8fc75feb58ff)
![IMG_2266](https://github.com/mozilla-mobile/firefox-ios/assets/155667837/42a01031-2836-44eb-9c34-f460284d8f03)
### Steps to reproduce

Steps to re-create problem:

1) iPhone preferred language originally set up to use English:

Settings-> General-> Language & Region-> Preferred Languages -> iPhone Language -> "English"

2) Change iPhone preferred language to Spanish: 

Settings-> General-> Language & Region-> Preferred Languages -> iPhone Language -> "Spanish (Latin America)/Espańol (Latinoamérica)"

NOTE: The Firefox search screen "Space" bar and "Go" key are now re-labeled with Spanish text:

"Space" -> "**espacio**"
"Go" ->    "**ir**"

4) Change the "Preferred language" back to English in iOS "Settings".

5) Open Firefox app and initiate a search.

### Expected behavior

1) Anytime iOS preferred language is changed (back-and-forth) in iOS "Settings" the text labels on the Firefox "Space" bar and "Go" button should be updated to reflect the new language model.

2) Total re-install of Firefox iOS app should overwrite any previously-set language artifacts with the newly installed preferred language.

### Actual behavior

1) Space bar is still labeled "**espacio**" and the Go button is still labeled "**ir**" after changing language back to English.

2) Firefox app un-install/re-install (2 times) has not fixed the key labels. They are still in Spanish:

- Firefox icon long press (iPhone Home screen) -> "Remove App" -> "Delete App"
- Re-install

### Device & build information

* Device: ? 
* Build version: ? 
* First seen version: ? 

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-8073)

**Comment by Zippy3514** [comment]
Device & build information

Device: iPhone Xs (Model MT8W2LL/A), iOS version 17.2.1
Build version: Firefox 121.0 (36782)
First seen version: Seen it before

**Comment by dnarcese** [comment]
It seems that you are referring to the iOS keyboard. If you click the globe can you change it back to English? Does that solve your problem?

**Comment by Zippy3514** [comment]
Well, Daniela, now I feel pretty silly. Yes, toggling the globe "fixed" my problem. I never even noticed it down there before. 

Thank you for responding to my issue. I appreciate it.
