### ISSUE TITLE
Send Tab no longer working IOS to other devices

### ISSUE THREAD

**Issue by Tamerlanchiques** [mozilla-mobile/firefox-ios#17982]
## Steps to reproduce

– Tap the share function on your app. (Example from Twitter);
– Choose Firefox on the list of apps to share to;
– Select Send to device;
– Choose the device you want to send to.

### Expected behavior

– Tap the share function on your app. (Example from Twitter);
– Choose Firefox on the list of apps to share to;
– Select Send to device;
– Choose the device you want to send to;
– The page will open in a new tab when you open Firefox. 

_As described in [this article](https://support.mozilla.org/en-US/kb/send-tab-from-another-mobile-app-to-firefox)._

### Actual behavior

You will see that no device to share found:
![IMAGE 2024-01-04 15:28:06](https://github.com/mozilla-mobile/firefox-ios/assets/11006352/796be6d0-2201-4b63-900f-15a1d1190945)

But if we try to share a tab inside Firefox iOS app then we will see that there are devices available to tab send:
![IMAGE 2024-01-04 15:34:15](https://github.com/mozilla-mobile/firefox-ios/assets/11006352/de93b22e-67af-4474-86fb-a74e1f6afa0a)

### Device & build information
* Device: iPhone 12 Pro Max 
* Build version: 17.2.1 
* First seen version: 17.2.1 

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-8069)

**Comment by abodea** [comment]
Hello, @Tamerlanchiques thank you for adding this issue.
https://github.com/mozilla-mobile/firefox-ios/issues/17789 is this issue similar to your problem? From what I see I would say yes, but I want to confirm it with you. 
If that is the case make sure you update FF to the latest version and you should already see it work again.

**Comment by Tamerlanchiques** [comment]
Yes, I confirm that this issue fixed in latest update.

**Comment by abodea** [comment]
Thanks, @Tamerlanchiques dupe of https://github.com/mozilla-mobile/firefox-ios/issues/17789.
