### ISSUE TITLE
Fakespot - iPad - Review checker info is not refreshing for a specific scenario 

### ISSUE THREAD

**Issue by alinamoldovan84** [mozilla-mobile/firefox-ios#18008]
## Steps to reproduce
1. Make sure you are using an iPad in landscape mode 
1. Open a PDP =>  Review checker sidebar is opened 
1. From another device send a PDP 
1. The new PDP opens in a different tab -> Review checker sidebar is opened 
1. Check the Review checker info 

### Expected behavior
The info displayed should match the info for the PDP sent from the other device 

### Actual behavior
The info displayed matches the info of the PDP already opened while receiving the new PDP 
Refreshing the PDP will not update the review checker  data
Closing the sidebar and reopen it will update the data 

### Device & build information
* Device: iPad Pro 4th gen (16.6) 
* Build version: FF v122 (37367) 
* First seen version: ? 
### Notes
* Issue reproduces when user opens a new PDP by tapping a link from a 3rd party app 
* Issue doesn't if review checker is displayed as bottom sheet 

Attachments: 

https://github.com/mozilla-mobile/firefox-ios/assets/124251579/6caec66d-ce82-4195-8fb7-45303cc5bae1

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-8093)

**Comment by data-sync-user** [comment]
➤ Alina Moldovan commented:

Verified as fixed using V9000 (37808) using iPad Pro 4th Gen (16.6)

**Comment by data-sync-user** [comment]
➤ Alina Moldovan commented:

Validated as fixed using FF v123 (38283) and iPad Pro 4rh gen (16.6)
