### ISSUE TITLE
Hide sponsored suggestions from history, bookmarks, and synced tabs when "show sponsored suggestions" is enabled in Firefox for iOS

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#18018]
shadow ticket for [https://mozilla-hub.atlassian.net/browse/DISCO-2666](https://mozilla-hub.atlassian.net/browse/DISCO-2666|smart-link)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-8098)

**Comment by annie-gupta** [comment]
Hi @data-sync-user , Please assign this issue to me. Thank you.
