### ISSUE TITLE
URL-bar paste dialog asks for paste permission too early (e.g. even when user intends to copy)

### ISSUE THREAD

**Issue by ahunt** [mozilla-mobile/firefox-ios#18023]
## Steps to reproduce
1. Open any other app, copy some text.
1. Open Firefox
1. Long-press URL bar

### Expected behavior
* Paste menu shows up with "Paste & Go", "Paste", "Copy Address".
* Selecting either of the paste options shows the iOS paste dialog (see next item)

### Actual behavior
iOS immediately shows the '"Firefox Beta" would like to paste from "APP"' dialog (even before I've expressed any desire to paste)

### Device & build information
* Device: ? iPhone 12 Pro, iOS 17.1.2
* Build version: ? Beta/TestFlight - Firefox 122.0 (37367)
* First seen version: ? Not sure - have seen this for quite some time (with older iOS versions too).

### Notes
* This appears to be different to https://github.com/mozilla-mobile/firefox-ios/issues/13265 which is about the "Offer to go to copied link" feature (this bug affects all users even without this feature etc.)
* I imagine that this is related to not using the presence APIs as explained at https://developer.apple.com/documentation/uikit/uipasteboard/#2107139 "Use the following properties to avoid user notifications and alerts when the system doesn’t establish user intent:"
* My wild guess is that it's this code: https://github.com/mozilla-mobile/firefox-ios/blob/df19156597027d25760f3d62315b895bdd99a71e/firefox-ios/Client/Frontend/Widgets/PhotonActionSheet/PhotonActionSheetProtocol.swift#L69-L73
* Blame shows that this was written 7 years ago, i.e. well before the iOS 14 paste permission changes

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-8099)

**Comment by ahunt** [comment]
(I'd like to try and contribute a fix because it _looks_ like a simple enough 1-liner. I'm a little cautious about promising anything however as I don't have an iOS development environment available.)

**Comment by data-sync-user** [comment]
➤ Adina Petridean commented:

Verified as fixed on v9000(40522), with iPhone 14 Pro Max (16.2).

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v127(41813), with iPhone 15 (17.4).

!RPReplay_Final1715849144.mp4|width=590,height=1280,alt="RPReplay_Final1715849144.mp4"!
