### ISSUE TITLE
Fakespot - Firefox crashes if user changes from portrait to landscape mode while review drawer is opened and an ad is displayed  

### ISSUE THREAD

**Issue by alinamoldovan84** [mozilla-mobile/firefox-ios#18026]
## Steps to reproduce
1. While in Portrait mode open the Fakespot - Review Drawer - make sure an ad is displayed 
2. Change from portrait to landscape

### Expected behavior
The Fakespot - Review Drawer is correctly displayed on landscape mode 

### Actual behavior
Firefox crashes. 
Review drawer is only displayed on half the screen, the app freezes and Firefox crashes 

### Device & build information
* Device: iPhone 14+ (16.0.1), 15+ (17.0.2), iPhone SE  
* Build version: v122 (37367), v9000(37404)  
* First seen version: ? 
### Notes
Attachments: 

https://github.com/mozilla-mobile/firefox-ios/assets/124251579/fa0f70e3-aabb-402c-bd23-6194e0b9d067

Logs: 
[Client-2024-01-05-180151.txt](https://github.com/mozilla-mobile/firefox-ios/files/13859620/Client-2024-01-05-180151.txt)
[Client-2024-01-05-180224.txt](https://github.com/mozilla-mobile/firefox-ios/files/13859622/Client-2024-01-05-180224.txt)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-8100)

**Comment by data-sync-user** [comment]
➤ Alina Moldovan commented:

Validated this issue using FF v122 (37615) and iPhone 14+ (16.0.3), iPhone 15+ (17.0.2), iPhone 15 (17.0) and iPhone SE (16.3)
