### ISSUE TITLE
[121.1 regression] "Send to Device" sometimes fails to list devices

### ISSUE THREAD

**Issue by ronjouch** [mozilla-mobile/firefox-ios#18037]
This is a follow-up of https://github.com/mozilla-mobile/firefox-ios/issues/17789#issuecomment-1881298149 .

## Steps to reproduce

Try to send a tab to a device (e.g. from Safari, hit `Share` → `Firefox`)

### Expected behavior

A submenu appears and list devices

### Actual behavior

- The Devices submenu doesn't appear, and the user is blocked (I waited for minutes).
- Cancelling and trying again often works

## Device & build information

* Device: iPhone XS on iOS 17.2.1, iPad on iPadOS 17.2
* Build version: 121.1
* First seen version: 121.1

## Notes

Copy-pasta of reports from 2 other users:

https://github.com/mozilla-mobile/firefox-ios/issues/17789#issuecomment-1881298149 :

> Since 121.1 the feature works again, but with a glitch in my personal case.
>
> I use firefox iOS from iPad (iPadOS 17.2 - last) and iPhone (iOS 17.2.1), and both suffers identical glitch. Sometimes, when I click in "Send to device" firefox context menu, does nothing. I can only cancel and retry the sharing action, and then works (and shows the devices submenu).
>
> The first time it happened to me was after updating to 121.1, and I thought it was a problem of lack of recent synchronization of my firefox account. But this continues to happen randomly without any associable cause or correlation in my opinion.

https://github.com/mozilla-mobile/firefox-ios/issues/17789#issuecomment-1881349550

> I confirm this. Had the same problem a couple of times. Clicking on "Send to Device" from the context menu sometimes does nothing - the context menu for selecting the device does not open.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-8105)

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v121.2 (37524), with iPhone 15 (17.0.)

**Comment by ronjouch** [comment]
Verified as fixed on 121.2 with an iPhone XS (17.2.1): shared 4 tabs from 2 apps. The Firefox button does appear in the share sheet, devices display, and the tab is received in the receiving device.

@afurlan-firefox @mattreaganmozilla however, one thing I noticed for the first time: after clicking the Firefox icon in the Share sheet, the first Firefox screen (the one with [ Open in Firefox, Load in Background, ... Send to Device ]) sometimes takes quite the time to display, like three to five seconds. It's not a deal breaker and I'd rather have this than the broken Devices screen, but it doesn't make for a great experience:

https://github.com/mozilla-mobile/firefox-ios/assets/522085/7b4d0849-037a-4948-b13c-caa9188c3273

When I read the above patch fixes a race, I was expecting incurring a couple milliseconds wait, but I'm surprised of that much delay.

Does it make sense that the delay happen before this first screen, and is such an amount of time expected with the 121.2 fix? Or am I conflating this delay with something pre-existing, and the race you fixed is between "initial Firefox screen" and "second Firefox/Devices screen"?

iPhone XS on iOS 17.2.1

**Comment by pashynskykh** [comment]
The problems seem to be fixed for me in 121.2. But I also noticed the delay before the content is shown in the FF popup. Can't call it a problem because there's a spinner, but there was no delay at all in previous versions. Just mentioning it in case.
