### ISSUE TITLE
Enable BackForward list feature flag to true

### ISSUE THREAD

**Issue by lmarceau** [mozilla-mobile/firefox-ios#18041]
The `back-forward-list-coordinator-refactor-feature` should be set to true for all channels

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-8108)

**Comment by data-sync-user** [comment]
➤ Alina Moldovan commented:

Validated as fixed using V9000 (37853) using iPhone 15+(17.0.2) & iPad Pro 4th Gen (16.6).

No issues were found

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Validated on v123 (37946), with iPhone 15 (17.0)
