### ISSUE TITLE
Navigating back to previous page doesn’t persist previous position on webpage

### ISSUE THREAD

**Issue by sadaaithal** [mozilla-mobile/firefox-ios#18072]
### Device & build information
* Device: 
iPhone 14pro, 17.1.2
* Build version:  121.1 , 185942
* First seen version: 121.1 , 185942
### Notes
Attachments: 
Two screen recordings: firefox vs safari

https://github.com/mozilla-mobile/firefox-ios/assets/30702253/1a025040-d14f-4d20-9ade-95d61c4a6f3c

https://github.com/mozilla-mobile/firefox-ios/assets/30702253/8a06f9c6-3e5c-46bf-925d-07cb57b7e5ee

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-8118)

**Comment by lmarceau** [comment]
Hello, there [will be a fix](https://github.com/mozilla-mobile/firefox-ios/issues/16643) for this issue in v121.2. Since this is already being tracked I'll close this bug here. Thank you!
