### ISSUE TITLE
Add secret setting to enable QA to test new FxA web app refactor

### ISSUE THREAD

**Issue by tarikeshaq** [mozilla-mobile/firefox-ios#18103]
FxA's sign-up page was re-written recently, to help QA test the new page, we should add a secret setting in Firefox ios that appends forceExperiment=generalizedReactApp&forceExperimentGroup=react to the query parameters of the content URL.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-8135)

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Hello Tarik Eshaq Can you give some details about what should QA test here? Thanks!

**Comment by data-sync-user** [comment]
➤ Tarik Eshaq commented:

Thanks for the tag Diana Andreea Barladeanu ! I should have clarified that this is mostly helpful for FxA QA to test and not actionable by mobile QA so I’m moving to done - cc Lauren Zugai 

This adds a secret settings button in the sync secret settings that forces the new React sign up page for FxA.

When enabled, then navigating to the sync sign up page a new version of the page will be loaded, and we’d want to make sure it works the same with or without that toggle.
