### ISSUE TITLE
Fakespot - ads - Stars look bigger compare to the size of the price 

### ISSUE THREAD

**Issue by alinamoldovan84** [mozilla-mobile/firefox-ios#18119]
## Steps to reproduce
1. While in landscape view, open a PDP - Make sure the ad is displayed
2. Observe the ad's stars 

### Expected behavior
The size of the starts should match the size of the price 

### Actual behavior
Stars look bigger compare to the size of the price

### Device & build information
* Device: iPhone 14+ (16.0.3), iPhone 15+ (17.0.2) 
* Build version: 122 (37615) 
* First seen version: ? 
### Notes
Attachments: 
![image](https://github.com/mozilla-mobile/firefox-ios/assets/124251579/8a92d80c-21b8-477c-a0d5-01073f4988b3)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-8141)

**Comment by data-sync-user** [comment]
➤ Alina Moldovan commented:

Verified as fixed using V9000 (37808) using iPhone 14+ (16.0.3), iPhone 15+ (17.0.2), iPad Pro 4th Gen (16.6) 

!image-20240118-123328.png|width=25%!
