### ISSUE TITLE
Fakespot - iPad - the ad link is not displayed correctly for a specific scenario 

### ISSUE THREAD

**Issue by alinamoldovan84** [mozilla-mobile/firefox-ios#18118]
## Steps to reproduce
1. While in landscape view, open a PDP - Make sure the ad is displayed 
1. The ad link is displayed on 3 rows 
1. Open the hamburger menu and close it 
1. Observe the ad link 

### Expected behavior
The link is correctly displayed on 3 rows 

### Actual behavior
The link is displayed on one row 

### Device & build information
* Device: iPad Air 3rd gen (17.0), iPad Pro 4th Gen (16.6)  
* Build version: 122 (37615) 
* First seen version: ? 
### Notes
Attachments: 

https://github.com/mozilla-mobile/firefox-ios/assets/124251579/4aa05b8d-3cae-4099-8fdb-5ce1e90a4ec9

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-8140)

**Comment by data-sync-user** [comment]
➤ Alina Moldovan commented:

Verified as fixed using V9000 (37808) using iPad Pro 4th Gen (16.6)
