### ISSUE TITLE
Felt Privacy - Incorrect theming color when user navigates from the private browsing mode   

### ISSUE THREAD

**Issue by alinamoldovan84** [mozilla-mobile/firefox-ios#18147]
## Steps to reproduce

1. Make sure iOS Felt Privacy experiment is enabled
2. Navigate to a Private Browsing tab -> homepage is displayed in purple shades
3. Tap the Fire icon -> Check the pop-up theming
4. Perform a Google search and long tap a link to open the menu ->  Check the pop-up theming

### Expected behavior
In both case the menu should be displayed in dark purple 

### Actual behavior
In both cases the menu is displayed in white/black color 

### Device & build information
* Device: iPad Pro 4th Gen (16.6), iPhone 15 Pro 
* Build version: 122 (37615) 
* First seen version: 122 (37615) 
### Notes
Attachments: 

![image](https://github.com/mozilla-mobile/firefox-ios/assets/124251579/7f93e79f-01a9-41e6-90a0-71496c704a35)
![image](https://github.com/mozilla-mobile/firefox-ios/assets/124251579/fe180066-6292-463e-819c-3610d233bf93)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-8150)

**Comment by adudenamedruby** [comment]
This is not a bug. This is expected behaviour. We are using the system alerts, rather than custom alerts, and thus, it isn't possible to modify the colour for them.
