### ISSUE TITLE
Felt Privacy - Incorrect color of the private browsing tab after changing the theme 

### ISSUE THREAD

**Issue by alinamoldovan84** [mozilla-mobile/firefox-ios#18145]
## Steps to reproduce
1. Make sure iOS Felt Privacy  experiment is enabled 
1. Navigate to a Private Browsing tab -> homepage is displayed in  purple shades
1. Go to settings and change the theme from dark to light or viceversa 
1. Observe the  Private Browsing colors 

### Expected behavior
Homepage is displayed in purple shades

### Actual behavior
Homepage is displayed in white/black shades. Opening a new private tab will restore the correct color 

### Device & build information
* Device: iPad Pro 4th Gen (16.6), iPhone 15 Pro    
* Build version: 122 (37615) 
* First seen version: 122 (37615) 
### Notes
Attachments: 

https://github.com/mozilla-mobile/firefox-ios/assets/124251579/abb494c7-ab51-4a9e-acc8-d4421cccc6e6

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-8148)

**Comment by data-sync-user** [comment]
➤ Roux Buciu commented:

Spoke with Juhee Jain and verified that the behaviour we want is for the private theme to remain. Further improvement will be made to clarify why this isn’t changing (in private mode) in a further ticket.

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v9000 (38310), with iPhone 15 (17.0).

I can confirm that the purple theming is kept even after changing the theme from FF settings.

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v123 (38592), with iPhone 15 (17.0).
