### ISSUE TITLE
Felt Privacy - The deleted tabs via Fire Icon cannot be undone

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/firefox-ios#18143]
## Steps to reproduce
1. Launch FF and access PB.
2. Open one or more tabs.
3. Tap on the fire Icon.
### Expected behavior
The `Undo` option is not present on the `Private Browsing Data Erased snackbar`.
### Actual behavior
Private Browsing Data Erased snackbar is displayed.
### Device & build information
* Device: iPhone 15 Pro (17.1.2). 
* Build version: v122 (37615) 
* First seen version: v122 (37615) 
### Notes
Attachments: 

https://github.com/mozilla-mobile/firefox-ios/assets/42831109/7279e9c6-dbdb-414e-adf7-5d9d2d38bfb2

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-8147)

**Comment by adudenamedruby** [comment]
Just to clarify, this option is **not** expected to be there. So this is not a bug. :)
