### ISSUE TITLE
 Mailto URI Scheme Stopped Working with Microsoft Outlook

### ISSUE THREAD

**Issue by bendk** [mozilla-mobile/firefox-ios#18235]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1874322:

> The mailto URI scheme no longer works with [Microsoft Outlook](https://apps.apple.com/app/microsoft-outlook/id951937596). If you go to a page with a clickable email address such as https://www.thunderbird.net/en-US/contact/ and open it with Safari, tapping either [partnerships@thunderbird.net](mailto:partnerships@thunderbird.net) or [press@thunderbird.net](mailto:press@thunderbird.net) will open Outlook for iOS with the new message pane and the email address in the recipient field as expected.
> 
> Now, if you repeat this with Firefox for iOS, you will only see the Outlook home screen. I've already reported this issue to Microsoft 365 Premium Support for Outlook, and they have confirmed after testing that this is not an issue on their end. Tested on iOS 17.2.1 using Firefox 121.1 (37312) on an iPhone 13 mini.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-8207)

**Comment by data-sync-user** [comment]
➤ Norberto Andres Furlan commented:

Andrei Bodea are you still able to reproduce this one?

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Hi Norberto Andres Furlan, Andrei is on PTO this week so I took a look at this issue. I wasn’t able to reproduce it. The only difference between Safari and FF is that on FF we have the permission prompt.

[^RPReplay_Final1706167427.MP4]

**Comment by remingtonc** [comment]
I experience this issue consistently on Firefox 152.3 (73911) and iOS 26. The notable difference from the UI is purely in prompt - Safari seems to resolve Outlook as the name, Firefox just asks whether to open the default. My Outlook app has multiple mail accounts, if that is somehow important.

From Safari:
<img width="295" height="639" alt="Image" src="https://github.com/user-attachments/assets/35efcfc1-5799-47dd-964e-4da3cf76f3a3" />

The mailto is correctly drafted:
<img width="295" height="639" alt="Image" src="https://github.com/user-attachments/assets/ab63bbc1-39fe-4ca5-9d46-d260ad9372cc" />

From Firefox:
<img width="295" height="639" alt="Image" src="https://github.com/user-attachments/assets/095bd379-8d98-4af8-9974-06e3d8da4917" />

The mailto leads just to inbox. Broken link.
