### ISSUE TITLE
CC Autofill - Credit card autofill doesn't work on https://fill.dev/form/credit-card-simple

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/firefox-ios#18239]
## Steps to reproduce

1. Have some credit card in your Firefox iOS's Payment Methods settings. I have three cards synced from Firefox desktop.
2. Load https://fill.dev/form/credit-card-simple
3. Tap focus to any of the credit card form's fields.

### Expected behavior

Firefox should offer to autofill my saved credit cards like Firefox desktop does for this site.

### Actual behavior

The iOS keyboard opens, but there is no offer to autofill my saved credit cards. This site works correctly in Firefox desktop.

### Device & build information

* Device: iPhone 15 Plus running iOS 17.21
* Build version: TestFlight version 9000 (37808)
* First seen version: ? 

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-8211)

**Comment by data-sync-user** [comment]
➤ Norberto Andres Furlan commented:

Issam Mani can you check this issue? Is it related to iFrame issue?

**Comment by issammani** [comment]
This PR #18406 fixes the issue.

### Screen recording of the fixed behaviour


https://github.com/mozilla-mobile/firefox-ios/assets/26678795/2df15f78-ab34-4b89-8d15-dd76e43cc0d6
