### ISSUE TITLE
Fix theme on SearchEngine Settings screen

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#18255]
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-8217)

**Comment by Tomer42** [comment]
To address the issue with the Search Engine Settings screen, developers must identify and rectify any coding or design issues affecting the theme's appearance. Testing and refining the theme will ensure a visually cohesive and functional interface.

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Validated on v127 (41813), with iPhone 15 (17.4).
