### ISSUE TITLE
Night mode coming on without setting it

### ISSUE THREAD

**Issue by nicvagn** [mozilla-mobile/firefox-ios#18274]
## Steps to reproduce
Reboot iPad, start Firefox IOS. For me, it will be in night mode. 

### Expected behavior
Night mode off by default

### Actual behavior
Night mode on by default

### Device & build information:
iPad (7th generation)

* Device: ? 
* Build version: ? 
* First seen version: ?  
I don't know.
I have seen it for a while, I am not sure tho.
    1. Notes
Attachments: 

It just boots in night mode.

Thanks friend. Take care

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-8224)

**Comment by data-sync-user** [comment]
➤ Norberto Andres Furlan commented:

Fixed.
