### ISSUE TITLE
Record Category 2.5 impressions for sponsored and non-sponsored suggestions from Firefox Suggest

### ISSUE THREAD

**Issue by linabutler** [mozilla-mobile/firefox-ios#18272]
Shadow ticket for https://mozilla-hub.atlassian.net/browse/DISCO-2665; more info to come in the PR!

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-8223)

**Comment by data-sync-user** [comment]
➤ Lina Butler commented:

Hi Daniela Arcese! Could I trouble you for a data review on this, please? Here’s the request form: https://github.com/mozilla-mobile/firefox-ios/pull/18273#issuecomment-1905170052 ( https://github.com/mozilla-mobile/firefox-ios/pull/18273#issuecomment-1905170052|smart-link )

**Comment by linabutler** [comment]
Long testing post ahead! 😅🧪 Here are the scenarios that should send a ping:

1. A sponsored Firefox Suggestion is visible on the screen, and the user taps on it.
2. A non-sponsored Firefox Suggestion is visible on the screen, and the user taps on it.
3. A sponsored Firefox Suggestion is visible on the screen, and the user navigates to a different page by tapping on a different suggestion, or typing a URL or a search term and then tapping "Go".
4. A non-sponsored Firefox Suggestion is visible on the screen, and the user navigates to a different page.

And here are the cases that shouldn't:

* A Firefox Suggestion (sponsored or non-sponsored) is off screen. For example, if the user types `nike`—which would show a sponsored suggestion—but that suggestion is hidden behind the keyboard, Firefox should not record an impression. (But if the user then hides the keyboard by scrolling the results, and the Nike suggestion becomes visible, then Firefox should record an impression for that suggestion).
* A Firefox Suggestion is shown before the user finishes typing. For example, if the user types `nike`, then deletes and changes their query to `athl`—which hides the suggestion for Nike, and shows one for Athleta instead—and then taps on a suggestion or on the "Go" button, Firefox should only record an impression / click for Athleta, not Nike.
* If a Firefox Suggestion is visible on the screen, and the user dismisses the URL bar, Firefox should not send any pings for that suggestion.

Before testing, I configured Glean to log and tag metrics, following [these instructions](https://mozilla.github.io/glean/book/user/debugging/ios.html#using-the-command-line). Here's the command I used for a development build of Firefox running in the Simulator:

```sh
xcrun simctl openurl booted "fennec://glean?logPings=true&debugViewTag=lina-debug"
```

(I think the scheme might be `firefox-internal://` instead of `fennec://` for a non-development build? 🤔) Here's the [debug ping view for my tag](https://debug-ping-preview.firebaseapp.com/pings/lina-debug).

To switch on sponsored and non-sponsored suggestions:

1. Open Settings, scroll down to the "About" section, and tap the version number 5 times to show the debug settings.
2. Scroll down and tap on "Firefox Suggest".
3. Switch on "Enable Firefox Suggest", and tap "Ingest new suggestions now" to download the dataset.
4. Tap back to Settings, scroll up to the "General" section, and tap on "Search".
5. Switch on "Suggestions from Firefox" and "Suggestions from sponsors".

### Scenario 1

1. Type `nike` into the URL bar. Verify that a sponsored Nike suggestion appears in the Firefox Suggest section, and is visible on the screen.
2. Tap on the sponsored Nike suggestion.
3. Verify that two `fx-suggest` Glean pings are sent: one impression ping with a `ping_type` of `fxsuggest-impression`, and one click ping with a `ping_type` of `fxsuggest-click`.

The impression ping for a sponsored suggestion looks like this:

```json
{
  "metrics": {
    "boolean": {
      "fx_suggest.is_clicked": true
    },
    "quantity": {
      "fx_suggest.block_id": 128,
      "fx_suggest.position": 5
    },
    "string": {
      "fx_suggest.advertiser": "nike",
      "fx_suggest.iab_category": "22 - Shopping",
      "fx_suggest.ping_type": "fxsuggest-impression"
    },
    "url": {
      "fx_suggest.reporting_url": "https://imp.mt48.net/static?v=2&partner=firefox_cla&sub1=nike&sub2=us&adv-id=74521&custom-data=128"
    },
    "uuid": {
      "fx_suggest.context_id": "68f4458a-3a6d-46ec-a148-b57502016be6"
    }
  }
}
```

And the click ping looks like this:

```json
{
  "metrics": {
    "boolean": {
      "fx_suggest.is_clicked": true
    },
    "quantity": {
      "fx_suggest.block_id": 128,
      "fx_suggest.position": 5
    },
    "string": {
      "fx_suggest.advertiser": "nike",
      "fx_suggest.iab_category": "22 - Shopping",
      "fx_suggest.ping_type": "fxsuggest-click"
    },
    "url": {
      "fx_suggest.reporting_url": "https://mozillacla.ampxdirect.com/nike?sub1=nike&sub2=us&custom-data=128&ctag=318370984us1282024012420"
    },
    "uuid": {
      "fx_suggest.context_id": "68f4458a-3a6d-46ec-a148-b57502016be6"
    }
  }
}
```

### Scenario 2

1. Type `cali` into the URL bar. Verify that a Wikipedia suggestion titled "Wikipedia - California" appears in the Firefox Suggest section, and is visible on the screen.
2. Tap on the Wikipedia suggestion.
3. Verify that two `fx-suggest` Glean pings, an impression and a click, are sent.

The impression ping for a Wikipedia suggestion looks like this:

```json
{
  "metrics": {
    "boolean": {
      "fx_suggest.is_clicked": true
    },
    "quantity": {
      "fx_suggest.position": 5
    },
    "string": {
      "fx_suggest.advertiser": "wikipedia",
      "fx_suggest.ping_type": "fxsuggest-impression"
    },
    "uuid": {
      "fx_suggest.context_id": "68f4458a-3a6d-46ec-a148-b57502016be6"
    }
  }
}
```

And the click ping:

```json
{
  "metrics": {
    "boolean": {
      "fx_suggest.is_clicked": true
    },
    "quantity": {
      "fx_suggest.position": 5
    },
    "string": {
      "fx_suggest.advertiser": "wikipedia",
      "fx_suggest.ping_type": "fxsuggest-click"
    },
    "uuid": {
      "fx_suggest.context_id": "68f4458a-3a6d-46ec-a148-b57502016be6"
    }
  }
}
```

### Scenario 3

1. Type `nike` into the URL bar. Verify that a sponsored Nike suggestion appears in the Firefox Suggest section, and is visible on the screen.
2. Tap on a different suggestion, or tap the "Go" button on the keyboard to trigger a search.
3. Verify that only an `fx-suggest` impression ping is sent, with a `ping_type` of `fxsuggest-impression`.

Here's an example of that impression ping. Note that `is_clicked` is now `false`:

```json
{
  "metrics": {
    "boolean": {
      "fx_suggest.is_clicked": false
    },
    "quantity": {
      "fx_suggest.block_id": 128,
      "fx_suggest.position": 6
    },
    "string": {
      "fx_suggest.advertiser": "nike",
      "fx_suggest.iab_category": "22 - Shopping",
      "fx_suggest.ping_type": "fxsuggest-impression"
    },
    "url": {
      "fx_suggest.reporting_url": "https://imp.mt48.net/static?v=2&partner=firefox_cla&sub1=nike&sub2=us&adv-id=74521&custom-data=128"
    },
    "uuid": {
      "fx_suggest.context_id": "68f4458a-3a6d-46ec-a148-b57502016be6"
    }
  }
}
```

### Scenario 4

1. Type `cali` into the URL bar. Verify that a Wikipedia suggestion titled "Wikipedia - California" appears in the Firefox Suggest section, and is visible on the screen.
2. Tap on a different suggestion, or tap the "Go" button on the keyboard to trigger a search.
3. Verify that only an `fx-suggest` impression ping is sent.

Here's an example of the impression ping:

```json
{
  "metrics": {
    "boolean": {
      "fx_suggest.is_clicked": false
    },
    "quantity": {
      "fx_suggest.position": 6
    },
    "string": {
      "fx_suggest.advertiser": "wikipedia",
      "fx_suggest.ping_type": "fxsuggest-impression"
    },
    "uuid": {
      "fx_suggest.context_id": "68f4458a-3a6d-46ec-a148-b57502016be6"
    }
  }
}
```

**Comment by data-sync-user** [comment]
➤ Lina Butler commented:

Diana Andreea BarladeanuHi! I wanted to call this one out for testing, too, in case you wanted to add it to the iOS test plan. I think the Android test plan ( https://testrail.stage.mozaws.net/index.php?/runs/view/78600 ) had a few cases for these, but I’m not sure if you usually test telemetry for features on iOS, too 😊 Thanks!

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Lina Butler Hi! I’ll take a look and include it. Yes, we test telemetry for iOS features, too 🙂 Thanks!
