### ISSUE TITLE
iPAD-auto: Changed string for remove custom search engine

### ISSUE THREAD

**Issue by dragosb01** [mozilla-mobile/firefox-ios#18278]
## Steps to reproduce
1. Navigate to Settings/Search on iPad
1. Add a new custom search engine (ex youtube.com)
1. Tap Edit
### Expected behavior
The expected string is "Remove youtube"
### Actual behavior
The string for remove button has changed to "Remove Learn more about Firefox Suggest"
See screenshots.
### Device & build information

* Device: ? <Ipad Air (5th generation, iOS 17.2>
* Build version: ? <124.0>
* First seen version: ? <yes>
### Notes
This issue impacts automation, only on iPad. The functionality has not changed:
Tests affected: testCustomSearchEngineIsEditable, testDeletingLastCustomEngineExitsEditing
Attachments: 
![](https://github.com/mozilla-mobile/firefox-ios/assets/134391433/e0845a9b-504b-4e0d-a361-d2265780cfa7)
![](https://github.com/mozilla-mobile/firefox-ios/assets/134391433/c7f6566d-4c91-4356-ab18-6d8152805298)
![](https://github.com/mozilla-mobile/firefox-ios/assets/134391433/19dba4c7-9b51-42c6-9e49-3d97f8740cc0)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-8226)

**Comment by dragosb01** [comment]
Issue is not reproducing anymore. Closing

**Comment by data-sync-user** [comment]
➤ Dragos Bigu commented:

Issue is not reproducing anymore. Closing
