### ISSUE TITLE
Fakespot bottom sheet's 'highlights' section should remember their expanded state for the current page 

### ISSUE THREAD

**Issue by alinamoldovan84** [mozilla-mobile/firefox-ios#18281]
## Steps to reproduce
1. Load a PDP.
1. Open the Fakespot bottom sheet.
1. Expand the highlights sections
1. Close the bottom sheet.
1. Reopen the bottom sheet.

### Expected behavior
The "Show more" highlights  section should remember whether they were expanded or closed on the current page. 

### Actual behavior
The "Show more" highlights  section is closed.

### Device & build information
* Device: iPhone 15+ (17.0.2) 
* Build version: FF v9000 (37808) 
* First seen version: ? 
### Notes
Attachments: 

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-8227)

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v9000(39074), with iPhone (17.0).

!original-13DEDD93-05E5-4D09-99AE-CE5C44EAD37F.mp4|width=444,height=960!

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Hi Razvan Litianu! I am unable to see this fix in the 124 build. Please advise! Thanks!

**Comment by data-sync-user** [comment]
➤ Razvan Litianu commented:

hey Diana Andreea Barladeanu the bug is fixed by this PR https://github.com/mozilla-mobile/firefox-ios/pull/18763 ( https://github.com/mozilla-mobile/firefox-ios/pull/18763|smart-link ) . Which is marked as 125. I wonder if we can uplift this to 124 https://mozilla-hub.atlassian.net/browse/FXIOS-8414 ( https://mozilla-hub.atlassian.net/browse/FXIOS-8414|smart-link ) .
cc: Norberto Andres Furlan

**Comment by data-sync-user** [comment]
➤ Norberto Andres Furlan commented:

Diana Andreea Barladeanu should we close this one?

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

HiNorberto Andres Furlan, we should move it to the 125 fix version.

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v125 (39935), with iPhone 15 (17.0).

The "Show more" highlights section remembers whether they were expanded or closed on the current page.
