### ISSUE TITLE
"Autofill Addresses" enabled on v123 build

### ISSUE THREAD

**Issue by DianaBarladeanu** [mozilla-mobile/firefox-ios#18305]
**Steps to reproduce**
1. Fresh install FF
2. Force close FF and reopen it
3. Go to the FF settings menu and observe

**Expected behavior**
"Autofill Addresses" section **should not** be visible.

**Actual behavior**
"Autofill Addresses" section is visible.

**Device & build information**
* Device: iPhone 15 (17.0)
* Build version: v123 (37946)
* First seen version: v123 (37946)

Notes
"Addresses" section is also visible on account sync settings.

Attachments: 
<img width="389" alt="Screen Shot 2024-01-23 at 5 31 11 PM" src="https://github.com/mozilla-mobile/firefox-ios/assets/133357955/b6d69b42-eea5-4594-8ec0-ee89f007434b">

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-8237)

**Comment by adudenamedruby** [comment]
Verified that the flags in code running from dev builds are behaving as expected.

Ran test with Testflight build listed in ticket, but don't see this:

https://github.com/mozilla-mobile/firefox-ios/assets/11182210/35503396-26b0-449b-91eb-5f0919288d9c

**Comment by data-sync-user** [comment]
➤ Roux Buciu commented:

Heya. We’ve looked into this, and we’ve found the problem. An experiment is live and rolled out. You can find it here ( https://experimenter.services.mozilla.com/nimbus/address-autofill-ios-beta-rollout/summary ). It needs to be turned off and then life will be rosy once more.

**Comment by data-sync-user** [comment]
➤ Norberto Andres Furlan commented:

Roux Buciu Diana Andreea Barladeanu Experiments cancelled.

**Comment by Dennismn** [comment]
Why are we not allowed to have the option to turn this off after multiple requests?

**Comment by adudenamedruby** [comment]
I can verify the issue has been resolved. Cloisg ticket.
