### ISSUE TITLE
The "Request Desktop Site" message is wrongly displayed if a long tap action is performed on the refresh button

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#18376]
**[Prerequisites]:**

* Have the Firefox Beta 9000 (28085) installed through TestFlight.

**[Steps to reproduce]:**

1. Start the Firefox App .
1. Perform a search.
1. Long tap the "Refresh" button from the URL bar.
1. Observe the behavior.

**[Expected result]:**

* Nothing happens.

**[Actual result]:**

* The "Request Desktop Site" message is displayed.

**[Device & build information]:**

* Device: iPhone 13 mini - iOS 16.5 and iPhone 13 mini - iOS 16.5
* Build version: Firefox 122.0 (37615) and Firefox Firefox Beta 9000 (28085)

**[Notes]:**

* Attached a screen recording of the issue:
* 
https://github.com/mozilla-mobile/firefox-ios/assets/11338480/71d6c491-c81a-4c06-849f-d6ee1e1d5eef

!Long tab on refresh button.mp4|width=886,height=1920!

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXIOS-8282)

**Comment by lmarceau** [comment]
https://github.com/mozilla-mobile/firefox-ios/assets/11338480/71d6c491-c81a-4c06-849f-d6ee1e1d5eef

**Comment by kmohan97** [comment]
@lmarceau As per the code, this seems to be an intended behaviour.
Could you please confirm if this should not be the case.

**Comment by data-sync-user** [comment]
➤ Winnie Teichmann commented:

Cosmin Muntean this is intended behaviour. This is not a bug.
