### ISSUE TITLE
Top sites are no longer displayed after closing onboarding

### ISSUE THREAD

**Issue by dragosb01** [mozilla-mobile/firefox-ios#18370]
## Steps to reproduce
1. Start Firefox with a clean profile.
2. Go through every step till the end
3. Close onboarding
### Expected behavior
Top sites area should be displayed
### Actual behavior
The top sites are missing
### Device & build information
* Device: ? < iPhone 15 Pro, iOS 17.2 >
* Build version: ? < 124.0 >
* First seen version: ? < Yes >
### Notes
Automation tests affected: testCloseTour, testFirstRunTour
Actions like putting the app in background, or going to setting/homepage tap done without any modifications would make the top sites visible.
Attachments: 
<img width="375" alt="Screenshot 2024-01-25 at 09 23 23" src="https://github.com/mozilla-mobile/firefox-ios/assets/134391433/5a0099f3-1461-4e2f-8e0e-60b319689258">

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-8278)

**Comment by dragosb01** [comment]
Workaround for testCloseTour, testFirstRunTour tests should be removed after the issue is fixed.

**Comment by lmarceau** [comment]
@dragosb01 I think I fixed this issue on latest `main`, can it be confirmed? 🙏

**Comment by dragosb01** [comment]
@lmarceau validated in the latest main. Issue has been fixed.

**Comment by dragosb01** [comment]
Closing issue
