### ISSUE TITLE
BrowserKit tests not running on Bitrise

### ISSUE THREAD

**Issue by lmarceau** [mozilla-mobile/firefox-ios#18384]
As brought up in https://github.com/mozilla-mobile/firefox-ios/pull/18365#issuecomment-1908916784, I think the BrowserKit tests aren't running anymore as part of our CI. Maybe due to file path changes? In all cases, I noticed this as well in Xcode (from the UnitTests test plan)

![Screenshot 2024-01-25 at 10 39 01 AM](https://github.com/mozilla-mobile/firefox-ios/assets/11338480/74d98ad9-2544-4d2e-ad0d-833aab6e7dd8)

isabelrios could I get your help on this issue? Thank you!

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-8288)

**Comment by isabelrios** [comment]
oh sorry I have not realized about that... let me take a look and see... it maybe related to the big PR to move files around... 
cc @clarmso
