### ISSUE TITLE
Re-merge refactor of iOS logins key logic

### ISSUE THREAD

**Issue by lougeniaC64** [mozilla-mobile/firefox-ios#18405]
This is a tracking ticket for [SYNC-4087](https://mozilla-hub.atlassian.net/browse/SYNC-4087). 

The logic being re-introduced was backed out in PR #17954 after the logins incident and was **not** the logic that caused the incident. The problematic code, the verification logic introduced in #17355, is being re-worked and will be added in a later release.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-8297)

**Comment by data-sync-user** [comment]
➤ Laurie Marceau commented:

Lougenia Bailey anything our QA team can do to test those changes in v124?

**Comment by data-sync-user** [comment]
➤ Lougenia Bailey commented:

Laurie Marceau Testing logins sync functionality to ensure it’s working as intended would be great. Emulating the keychain data loss that the steps in the PR description outline is probably a bridge too far.

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Verified as fixed on v124 (39359) with iPhone 15 Pro (17.3).
