### ISSUE TITLE
Fakespot - Incorrect "Fakespot's terms of use" link 

### ISSUE THREAD

**Issue by DianaBarladeanu** [mozilla-mobile/firefox-ios#18417]
**Steps to reproduce**

1. Make sure the user is not opted in 'review the quality check' provided by Fakespot.
1. Navigate for the first time to a product detail page on amazon.com, walmart.com, or bestbuy.com page. The shopping icon is displayed on the address bar
1. Tap the Price tag icon. The contextual onboarding screen is correctly displayed. 
1. Tap the “Fakespot's terms of use” link on the contextual opt-in screen and observe the webpage content.

**Expected behavior**
The following webpage is opened: https://www.fakespot.com/terms

**Actual behavior**
This incorrect webpage is opened instead: https://www.fakespot.com/privacy-policy

**Device & build information**

* Device:  iPhone 15 (17.0)
* Build version: v123 (38120)
* First seen version: v123 (38120)

**Notes:**
The incorrect webpage seems to be the old webpage from the privacy policy link.

Attachments: 

https://github.com/mozilla-mobile/firefox-ios/assets/133357955/51f19b9d-9ce0-4e49-8fa3-52a80266298d

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-8304)

**Comment by data-sync-user** [comment]
➤ Winnie Teichmann commented:

Diana Andreea Barladeanu according to this task the Fakespot's terms of use was to be changed to https://www.fakespot.com/privacy-policy?utm_source=review-checker&utm_campaign=privacy-policy&utm_medium=in-product&utm_term=opt-in-screen ( https://www.fakespot.com/privacy-policy?utm_source=review-checker&utm_campaign=privacy-policy&utm_medium=in-product&utm_term=opt-in-screen|smart-link ) . This would undo this change which would make the link incorrect. 
Chris Peterson could you please confirm that this above link is correct and should not be changed?

**Comment by data-sync-user** [comment]
➤ Chris Peterson commented:

Will Rocklin What is the correct URL for the Review Checker bottom sheet’s “Fakespot's terms of use” link? Should it be https://www.fakespot.com/terms? Firefox desktop’s “terms of use” link points to https://www.fakespot.com/terms?utm_source=review-checker&utm_campaign=terms-of-use&utm_medium=in-product&utm_term=opt-in-screen. Mobile’s link doesn’t include any utm parameters.

**Comment by data-sync-user** [comment]
➤ Winnie Teichmann commented:

After speaking with Chris Peterson we decided to make this change and use https://www.fakespot.com/terms as the Fakespot's terms of use URL.

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v9000 (38639), with iPhone 15 (17.0).

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v124(38968), with iPhone 15 (17.0).
