### ISSUE TITLE
Payment Methods & Settings menus can no longer be opened after a specific scenario

### ISSUE THREAD

**Issue by alinamoldovan84** [mozilla-mobile/firefox-ios#18425]
## Steps to reproduce
1. Make sure the face recognition is enabled 
2. Open the hamburger menu and tap on the settings  
3. Tap on the Passwords 
4. Tap on "< Settings" option to go back to Settings menu
5. Tap on Payment Methods -> check the app behavior 
6. Open the hamburger menu and tap on the settings  -> check the app behavior 

### Expected behavior
Step 5 -> Payment Methods opens 
Step 6 -> Settings menu  opens 

### Actual behavior
Step 5 -> the menu is closed, Payment Methods doesn't open 
Step 6 -> Settings menu doesn't open 
=> User must restart the App in order fir the settings menu to work again. 

### Device & build information
* Device: iPhone 15+ (17.0.2), iPhone 14+ (16.0.3) 
* Build version: v123 (38120), V9000 (38130) 
* First seen version: ? 

### Notes
Attachments: 

https://github.com/mozilla-mobile/firefox-ios/assets/124251579/0bb00ff9-013c-4c35-bc39-c3f95eadf174

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-8312)

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v9000 (38639), with iPhone 15 (17.0).

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v124(38904) with iPhone 15 (17.0).
