### ISSUE TITLE
Garbled Fonts in iOS v122.0

### ISSUE THREAD

**Issue by paulied67** [mozilla-mobile/firefox-ios#18424]
## Steps to reproduce
Upgrade to 122.0 (from 121.0, which had no issues, chose "Replace")
Open Firefox

### Expected behavior
Browser displayed in my chosen language and font.

### Actual behavior
The characters displayed are not English characters.  This appears in the address bar, the settings page, on tabs, etc.
![Screenshot 2024-01-26 at 10 31 01 AM](https://github.com/mozilla-mobile/firefox-ios/assets/7193510/842f07d1-4343-4743-89f9-a40af0c39328)

If I copy the text out of the address par and paste it into a text editor, the text is readable.  For example, on the settings page, if I grab the address and put it in a text editor, the resulting paste is correct:  about:preferences

I tried changing fonts and that did not affect the display. The dropdown, however, has readable characters in it.
![Screenshot 2024-01-26 at 10 40 40 AM](https://github.com/mozilla-mobile/firefox-ios/assets/7193510/4e6744e3-fe35-4236-904d-232652ae0f07)

Pages have the unknown font, as well.
![Screenshot 2024-01-26 at 10 41 04 AM](https://github.com/mozilla-mobile/firefox-ios/assets/7193510/9dfa2507-9f09-40c6-89b9-93f04c364ba0)

### Device & build information
* Device: OS Ventura
* Build version:13.4 (22F66)
* First seen version: 13.4 (22F66)
### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-8311)

**Comment by paulied67** [comment]
Not all pages are affected, as might be expected with pages that dictate a font
![Screenshot 2024-01-26 at 10 48 21 AM](https://github.com/mozilla-mobile/firefox-ios/assets/7193510/8d0ded91-29c2-4f7f-a15b-2a0c1d159844)

**Comment by lmarceau** [comment]
Hello @paulied67, this appears to be Firefox MacOS. The current repository is solely for the iOS application. To make sure the right people see this issue, you can either go to the [Mozilla support forum](https://support.mozilla.org/en-US/), or open a [Bugzilla](https://bugzilla.mozilla.org/home). I'll close this issue here for now. Thank you!
