### ISSUE TITLE
Multiple “open link in external app?” prompts can stack up, covering the web page

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/firefox-ios#18438]
## Steps to reproduce

0. Install the YouTube app. 
1. Load https://m.youtube.com
2. Tap to watch any video other than a YouTube Short. 
3. Tap the video player’s “Open App” button. If you are logged into a YouTube account, you might need to log out to see the “Open App” button.
4. You should see a prompt asking if you’d like to open the link in an external app. 
5. Do not dismiss the prompt by tapping its “Open” or “Cancel” buttons! Instead tap the page’s “Open App” button again multiple times. 

### Expected behavior

The first prompt should be replaced by the new prompt. 

### Actual behavior

Multiple prompts will stack up.

Thus behavior isn’t reproducible in Safari or Chrome on iOS because their “open in external app?” prompts are modal, so you can’t open a second prompt until you dismiss the first prompt. 

### Device & build information

* Device: iPhone 15 Plus running iOS 17.2.1.
* Build version: TestFlight version 9000 (38130)
* First seen version: This bug isn’t a regression; I can reproduce it in the oldest TestFlight build I have on my phone, version 9000 (35678). 

### Notes

Attachments:

![image](https://github.com/mozilla-mobile/firefox-ios/assets/629193/7b593d8f-8583-4ae9-9715-56686b43c5f4)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-8320)

**Comment by lmarceau** [comment]
This bug relates to https://github.com/mozilla-mobile/firefox-ios/issues/10218 and https://github.com/mozilla-mobile/firefox-ios/issues/10536.

**Comment by data-sync-user** [comment]
➤ Norberto Andres Furlan commented:

Sorin Paraipan can you take a look to this one?

**Comment by data-sync-user** [comment]
➤ Sorin Paraipan commented:

Yes, I can.

**Comment by data-sync-user** [comment]
➤ Sorin Paraipan commented:

Hey, I've just found in the codebase that this is an intended behavior and is permitted a maximum of three stacks. Should we change that to just one snackbar? CC: Norberto Andres Furlan

**Comment by data-sync-user** [comment]
➤ Norberto Andres Furlan commented:

Sorin Paraipan lets check with the team if there is any reason for that, before changing it. Thanks!

**Comment by data-sync-user** [comment]
➤ Laurie Marceau commented:

I think https://github.com/mozilla-mobile/firefox-ios/issues/10218 ( https://github.com/mozilla-mobile/firefox-ios/issues/10218|smart-link ) needs to be fixed before changing that number.

**Comment by data-sync-user** [comment]
➤ Sorin Paraipan commented:

Unfortunately, this is an approximately two-year-old bug. That Google option does not exist anymore, but yes, I also don’t see the point in letting these snack bars stack up.

**Comment by data-sync-user** [comment]
➤ Laurie Marceau commented:

Sorin Paraipan I can still get the ios-log one from an iframe it seems (#10536)

!Screenshot 2024-02-02 at 10.39.13 AM.png|width=448,height=185!

And can get the Google one through, but the Google one is like the current bug case (#10218 is a duplicate).  

!Screenshot 2024-02-02 at 10.41.41 AM.png|width=1110,height=355!

**Comment by data-sync-user** [comment]
➤ Sorin Paraipan commented:

Norberto Andres Furlan , I’ve reduced the number of Snackbars to one per tab, the rest of the behavior it remained the same. Is this ok?

**Comment by data-sync-user** [comment]
➤ Chris Peterson commented:

{quote}I will close this ticket and open a new feature request.{quote}

Norberto Andres Furlan , did you file a new issue for replacing the snack bar with a native modal component?
