### ISSUE TITLE
Show sponsored and non-sponsored suggestions by default if the Firefox Suggest feature is enabled

### ISSUE THREAD

**Issue by linabutler** [mozilla-mobile/firefox-ios#18431]
Shadow ticket of https://mozilla-hub.atlassian.net/browse/DISCO-2730.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-8316)

**Comment by data-sync-user** [comment]
➤ Laurie Marceau commented:

Lina Butler anything our QA team could do to test those changes?

**Comment by data-sync-user** [comment]
➤ Lina Butler commented:

Laurie Marceau We’re still wrapping up the last batch of changes to sponsored and non-sponsored suggestions for our 124 experiment, so this will get a full QA pass then—I don’t think there’s any testing needed for this specific ticket now.
