### ISSUE TITLE
CC Autofill - UK - Credit card autofill is not available for https://www.tesco.com/

### ISSUE THREAD

**Issue by alinamoldovan84** [mozilla-mobile/firefox-ios#18448]
## Steps to reproduce

1. Have some credit card in your Firefox iOS's Payment Methods settings.
2. Use a vpn to set the region to UK
3. Load https://www.tesco.com/ and choose to buy a product
4. Tap to any of the credit card form's fields

### Expected behavior
The option to open the saved cards is displayed
### Actual behavior
The option to open the saved cards is NOT displayed
### Device & build information
* Device: Phone 15+ (17.0.2) 
* Build version: v123 (38163) 
* First seen version: ? 
### Notes
Attachments: 

https://github.com/mozilla-mobile/firefox-ios/assets/124251579/a68cc49a-a3ad-4e62-afd3-9d1934d21faa

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-8325)

**Comment by data-sync-user** [comment]
➤ Alina Moldovan commented:

Invalid issue, Marking it as Closed
