### ISSUE TITLE
Redux unit tests failing

### ISSUE THREAD

**Issue by lmarceau** [mozilla-mobile/firefox-ios#18459]
It was discovered that some BrowserKit unit tests weren't running anymore recently. This was fixed with https://github.com/mozilla-mobile/firefox-ios/issues/18384 but redux unit tests have a compile issue that prevent the unit tests to be reenabled again. 

With this issue:
- Fix the redux package unit tests
- Add redux package back to be ran as part of our CI pipeline (see https://github.com/mozilla-mobile/firefox-ios/pull/18444 for more details on how to do that).

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-8330)

**Comment by data-sync-user** [comment]
➤ Matthew Reagan commented:

Moving to Done since this doesn’t have any user-facing changes (fix for unit tests). cc Laurie Marceau
