### ISSUE TITLE
FF doesn't save the automatic theme setting after restart

### ISSUE THREAD

**Issue by DianaBarladeanu** [mozilla-mobile/firefox-ios#18450]
**Steps to reproduce**
1. Go to FF settings-->Theme--> turn off "Use System Light/Dark Mode" toggle
2. Set the switch mode to "Automatically"
3. Restart the app and observe the theme settings

**Expected behavior**
The automatic switch mode is kept after restart.

**Actual behavior**
The automatic switch mode is NOT kept after restart, the "Use System Light/Dark Mode" toggle is re-enabled.

**Device & build information**
* Device: iPhone 15 (17.0)
* Build version: v123 (38613)/v9000 (38156)
* First seen version: v123 (38613)
Notes
Attachments: 

https://github.com/mozilla-mobile/firefox-ios/assets/133357955/b81cf67e-659d-4a05-8588-6a824486e765

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-8327)

**Comment by data-sync-user** [comment]
➤ Roux Buciu commented:

I’ve tested this on the latest main with my changes for removing LegacyThemeManager and this problem is resolved. This change will make it into v123.

**Comment by data-sync-user** [comment]
➤ Alina Moldovan commented:

Validated as fixed using FF v123 (38283) and iPhone 15+ (17.0.2)

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v123 (38491), with iPhone 15 (17.0).
