### ISSUE TITLE
Theming threshold becomes inoperative after multiple theming changes

### ISSUE THREAD

**Issue by DianaBarladeanu** [mozilla-mobile/firefox-ios#18451]
**Steps to reproduce**
1. Go to FF settings and play with theming: set it to manually, then to automatically, change it from dark to light and viceversa, play with the toggle, with the threshold etc.
2. Restart the app and return to theming section. 
3. Set switch mode to "automatically" and try to change the theming from dark to light using the threshold.

**Expected behavior**
The theming can be changed from dark to light using the threshold (moving the cursor next to the moon icon).

**Actual behavior**
Light theme cannot be set using the threshold.

**Device & build information**
* Device: iphone 15 (17.0)
* Build version: v123 (38163) / v9000(38156)
* First seen version: v123 (38163) / v9000(38156)
Notes

Attachments: 

https://github.com/mozilla-mobile/firefox-ios/assets/133357955/2d3d094e-f5fc-42a7-8268-56fb74941631

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-8328)

**Comment by data-sync-user** [comment]
➤ Alina Moldovan commented:

Validated as fixed using FF v123 (38283) and iPhone 15+ (17.0.2)

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v123(38491), with iPhone 15 (17.0).
