### ISSUE TITLE
Password requirements are overlapping the other text fields on sync and save data

### ISSUE THREAD

**Issue by dragosb01** [mozilla-mobile/firefox-ios#18468]
## Steps to reproduce
1. Go to settings/ sync and save data
1. Reach Set your password screen
1. Tap password text field and leave it empty
1. Try to go to Repeat password text field
    1. Expected behavior
The password requirements info should be dismissed
    1. Actual behavior
The password requirements info is overlapping the other text fields 
    1. Device & build information

* Device: ? <iPad mini 6th generation iOS 17.0, iPhone 15 - iOS 17.2>
* Build version: ? <122.1, 124.0>
* First seen version: ? <Yes>
    1. Notes
Automation test affected: testTypeOnGivenFields
Attachments: 
![](https://github.com/mozilla-mobile/firefox-ios/assets/134391433/78c8d3ec-2ba1-44d1-9a4c-fae687eb6ccb)
![](https://github.com/mozilla-mobile/firefox-ios/assets/134391433/f7b2a354-f343-415f-aa31-7471c5e64c13)
![](https://github.com/mozilla-mobile/firefox-ios/assets/134391433/11e3cd3c-e3f7-4c88-a79b-38899d499781)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-8333)

**Comment by clarmso** [comment]
@tarikeshaq Since the issue may be related to the new page from Mozilla Account, should we move the discussion to somewhere else (different repo or just in Bugzilla)?

**Comment by tarikeshaq** [comment]
@clarmso keeping the bug in bugzilla is good - we can close this one noting that it duplicates https://bugzilla.mozilla.org/show_bug.cgi?id=1877479, looks like the FxA team is triaging it!

**Comment by dragosb01** [comment]
Closing as duplicate
