### ISSUE TITLE
Felt Privacy - Theme picker checkbox is missing while user is in Private mode 

### ISSUE THREAD

**Issue by alinamoldovan84** [mozilla-mobile/firefox-ios#18492]
## Steps to reproduce
1. Make sure Felt Privacy feature is enabled 
2. While in normal browsing mode go to Settings -> Theme -> Use system Light/Dark  Mode: disabled -> choose Manually -> check Dark/Light 
3. Switch to private mode 
4. Navigate to theme settings and check the  Theme picker checkbox

### Expected behavior
Theme picker  is set with the value in step 2

### Actual behavior
Theme picker checkbox is missing. At this  point user is not able to chose any option. 

### Device & build information
* Device: iPhone 15+ (17.0.2) 
* Build version: v123 (38283)  
* First seen version: ? 
### Notes
Attachments: 

https://github.com/mozilla-mobile/firefox-ios/assets/124251579/a40ca8b4-ff51-4911-8397-c4b1176612a3

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-8354)

**Comment by adudenamedruby** [comment]
LOL this is hilarious. I know exactly what's happening but oh boy, this is funny.

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v9000 (38484), with iPhone 15 (17.0).

Theme picker checkbox is now functional. It sets the normal browsing mode theme either light or dark.

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v123 (38592), with iPhone 15 (17.0).
