### ISSUE TITLE
Felt Privacy - Some menus/screens are displayed in gray instead of following the PB purple theme

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/firefox-ios#18520]
## Steps to reproduce
1. Turn on Felt Privacy Simplified Nav.
1. Check the following menus/screens:

* **1 -> Home Screen** 
  * No changes. It is a system prompt
* 2 **~~> History~~ > Current background is gray**
  * Update Color Token: Layer 1 / DS
* **3 ~~> Download~~ > Current background is gray**
  * Update Color Token: Layer 1 / DS
* **4 ~~> Reading list~~ > Current background is gray**
  * Update Color Token: Layer 1 / DS
* **5 ~~> Account~~ > Disconnect account**
  * No changes. System prompt.
* **6 -> Find in page buttons**
  * No changes. System prompt.
* **7 -> Password** 
  * No changes. System prompt.
* **8 -> Share menu**
  * No changes. System prompt.
* **9 -> Data management** 
  * No changes. System prompt.
* **10 -> Data management**
  * No changes. System prompt.
* **11 ~~> End your private session pop~~up**
  * No changes. System prompt.
* **12 ~~> Long tap on a link /picture~~ > context menu**
  * No changes. System prompt.
* **13 ->History ~~> Delete~~ > Current menu is gray**
  * No changes. System prompt.
* **14 → Bookmarks**
  * Update Color Token: Layer 1 / DS

* **Expected behavior:**
  * If it is a system prompt (like a confirmation dialog) we keep the OS system
  * If not, we should match the Felt Privacy theme -> Purple.

* **Actual behavior**
  * Some menus/screens are displayed in gray instead of following the PB purple theme.
* Device & build information
* Device: iPhone 15 Pro Max (iOS 17.1.2). 
* Build version: v9000 (38344) 

![width=200,height=183](https://github.com/mozilla-mobile/firefox-ios/assets/42831109/e758a917-4aee-476b-8e13-75464a165c3b)

![width=200,height=183](https://github.com/mozilla-mobile/firefox-ios/assets/42831109/cd38651d-bded-4521-a789-a1c61f10d65b)

!IMG_5257.jpg|width=16.666666666666664%!

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-8366)

**Comment by data-sync-user** [comment]
➤ Norberto Andres Furlan commented:

Andrei Bodea We defined the following, to follow the best practices:

  * If it is a system prompt (like a confirmation dialog) we keep the OS system
  * If not, we should match the Felt Privacy theme -> Purple.

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Thank you, Norberto Andres Furlan. This means all of the mentioned by you will be fixed in this ticket and when it is ready you will set the QA Needed?

**Comment by data-sync-user** [comment]
➤ Cyndi Chin commented:

The fix was merged into v124 and can be test on the nightly, but will also go out in v123.1 and that hasn’t been merged yet.

PR (merged) for main: [Bugfix FXIOS-8366 [v123.1] Update background color for panels|https://github.com/mozilla-mobile/firefox-ios/pull/18616]

The backport PR for release/v123 (not merged): [+Bugfix FXIOS-8366 [v123.1] Update background color for panels (backport #18616)+|https://github.com/mozilla-mobile/firefox-ios/pull/18626]

I will make sure to add a comment to my tickets to specify in advance next time, thank you!

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified on v123.1 (38978), with iPhone 15 (17.0).

The bug is still reproducible on this build.

!original-507C9DE0-00DA-4380-8682-7D5397370B65.mp4|width=444,height=960!

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v123.2 (39233), with iPhone 15 (17.0)

!original-45E6536B-92AC-4DB4-B57E-BB1081F89784.mp4|width=444,height=960!
