### ISSUE TITLE
Drag tab to different location, seems to stick then seconds later appears in original location

### ISSUE THREAD

**Issue by Aquind** [mozilla-mobile/firefox-ios#18563]
### Device & build information: 
* Device: MK663LL/A (9th gen)  iOS v17.2
* Build version: Firefox 122.0 (37686)
* First seen version: Firefox 122.0 (37686)
### Notes
Attachments: 

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-8378)

**Comment by data-sync-user** [comment]
➤ Sophie Amin commented:

Fixed as a part of this work for the tab tray refactor: https://mozilla-hub.atlassian.net/browse/FXIOS-6838 ( https://mozilla-hub.atlassian.net/browse/FXIOS-6838|smart-link )
