### ISSUE TITLE
Can’t scroll homepage when offline. Homepage switches to “ The Internet connection appears to be offline.” error page. 

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/firefox-ios#18579]
## Steps to reproduce
1. Load Firefox homepage. 
1. Disable the Internet by enabling iOS airplane mode. 
1. On the homepage, tap to try to load any shortcut. 
1. You should see a “The Internet connection appears to be offline.” error page. 
1. Tap the address bar to go back to the homepage. 
1. Try to scroll the homepage. 

### Expected behavior
I should be able to scroll the homepage even when offline. 

### Actual behavior
When I touch the homepage to try to scroll, the homepage switches back to the “The Internet connection appears to be offline.” error page. 

### Device & build information
* Device: iPhone 15 Plus running iOS 17.3.
* Build version: TestFlight version 9000 (38442)
* First seen version: I don’t know. This bug isn’t a recent regression. I was able to repro in the oldest TestFlight build I have access to, version 9000 (35909).

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-8382)

**Comment by data-sync-user** [comment]
➤ Norberto Andres Furlan commented:

Andrei Bodea do you know if this was happening on previous versions too? Can you check? Thanks!

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Hello, Norberto Andres Furlanplease note that I was able to repro this one in v120 (36024). So it’s not a recent regression as Chris mentioned.

**Comment by data-sync-user** [comment]
➤ Alina Moldovan commented:

Verified as fixed using v9000(39744) and iPhone 15+ (17.4).

**Comment by data-sync-user** [comment]
➤ Chris Peterson commented:

Alina Moldovan Can this issue be closed note? You briefed e the fix, but the issue’s status is still “QA Needed”.

**Comment by data-sync-user** [comment]
➤ Norberto Andres Furlan commented:

Alina Moldovan can we close this issue?

**Comment by data-sync-user** [comment]
➤ Alina Moldovan commented:

Norberto Andres Furlan Fix version is missing. it was not validated using a beta or RC build so it is not ready to be closed. Was this fixed added to a release branch?

**Comment by data-sync-user** [comment]
➤ Norberto Andres Furlan commented:

It was merged on 125.

**Comment by data-sync-user** [comment]
➤ Alina Moldovan commented:

Validated as fixed using FF v125 (40715) and iPhone 15+ (17.4.1)

!2024-04-12_11h39_07.mp4|width=424,height=926,alt="2024-04-12_11h39_07.mp4"!
