### ISSUE TITLE
Swipe to close tab does not work anymore

### ISSUE THREAD

**Issue by badboy** [mozilla-mobile/firefox-ios#18589]
## Steps to reproduce

1. Have a couple of tabs open
2. Go to the "Open Tabs" overview
3. Touch and swipe left on a tab

### Expected behavior

Closes the selected tab.

### Actual behavior

Tab just snaps back into position after releasing touch.

### Device & build information
* Device: iPhone 14 Pro, iOS 17.3
* Build version: Firefox 9000, build 38442
* First seen version: new in this build (or a build before maybe)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-8385)

**Comment by rajparad** [comment]
I checked the issue you mentioned, and as expected behaviour it closes the tab with touch and swipe left. I checked on iPhone 15, iOS 17.2 and from **main branch**. I am new to open source contribution, so sorry if I misunderstood something :)

**Comment by badboy** [comment]
https://github.com/mozilla-mobile/firefox-ios/assets/2129/9f7f8b78-d052-4610-bb5c-a3ccf738434a

**Comment by data-sync-user** [comment]
➤ Sophie Amin commented:

This works fine in the version where the TabTrayRefactor is disabled, confirmed by testing.
However this wasn’t in our epic for implementation, so I’ve added it here to be added in a future release: https://mozilla-hub.atlassian.net/browse/FXIOS-8418 ( https://mozilla-hub.atlassian.net/browse/FXIOS-8418|smart-link )
