### ISSUE TITLE
Move ActionFooterView to Fakespot code

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#18594]
The `ActionFooterView` is currently part of the `ComponentLibrary`. As it is only used once in, it shouldn’t be treated as a component and be moved to where it is used.

Tasks that need to be done:

* Rename `ActionFooterView` to `FakespotActionFooterView`
* Rename `ActionFooterViewModel` to `FakespotActionFooterViewModel`
* Move `FakespotActionFooterView` to Client/Frontend/Fakespot/Views
* Remove documentation for `ActionFooterView` from `ComponentLibrary`
* Remove `ActionFooterComponentViewModel` and `ActionFooterViewController` from `SampleComponentLibraryApp`

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-8388)

**Comment by bmihai23** [comment]
Hi @PARAIPAN9, I would like to work on this issue. Thanks 🙏🏻

**Comment by PARAIPAN9** [comment]
Sure, go ahead!!

**Comment by data-sync-user** [comment]
➤ Winnie Teichmann commented:

For QA: please test that the footer link under the Fakespot settings section still looks and behaves correctly.

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Validated on v124(38968), with iPhone 15 (17.0).
