### ISSUE TITLE
Signing in to sync using email and password creates a duplicate entry in manage accounts

### ISSUE THREAD

**Issue by tarikeshaq** [mozilla-mobile/firefox-ios#18599]
## Steps to reproduce
* Sign in to Sync using email and password
* Go to manage accounts

### Expected behaviour
* Only one entry for the firefox-ios device

### Actual behaviour
* Two entries, one representing the web session and another the device itself

I'm putting up a patch for this that depends on https://github.com/mozilla/application-services/pull/6111

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-8389)

**Comment by data-sync-user** [comment]
➤ Norberto Andres Furlan commented:

Nishant Bhasin do we need this one on the next weekly or can we move to 125? If we need it for 124.3 we should add the backport when approved. Thanks!

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Verified as fixed on v9000 (40522) with iPhone 15 Pro (17.3).

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v126 (40744), with iPhone 15 (17.4).

!RPReplay_Final1713258180.mp4|width=590,height=1280,alt="RPReplay_Final1713258180.mp4"!
