### ISSUE TITLE
Rename Variables with Firefox suffix

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/firefox-ios#18610]
Since we will have similar Variables and Secrets in the same repo, we are going to rename those that we use in Focus that exists in firefox but that they have different value.

```java
SENTRY_DSN_FIREFOX
SENTRY_AUTH_TOKEN_FIREFOX
```

See all the info in this [doc](https://docs.google.com/document/d/1Q1dRnJWUMDopoIKYUHuJWdl0BVOB3RxUXDb_ZH0aQlw/edit)
We will create those one with the same value they have in Bitrise UI and change the name in the bitrise.yml file where they are used.

We will be doing this in Focus too [https://github.com/mozilla-mobile/focus-ios/issues/4034](https://github.com/mozilla-mobile/focus-ios/issues/4034)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-8394)

**Comment by data-sync-user** [comment]
➤ Isabel Rios Escobar commented:

This is done in this PR: https://github.com/mozilla-mobile/firefox-ios/pull/18611 ( https://github.com/mozilla-mobile/firefox-ios/pull/18611|smart-link )
