### ISSUE TITLE
The `shopping.surface_displayed` event is not generated in glean

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/firefox-ios#18649]
## Steps to reproduce
1. Access Fakespot.
1. Visit a product and tap on the Fakespot button so that the surface (bottom sheet) is displayed.
1. Generate the telemetry events and check the glean dashboard.
### Expected behavior
The `shopping.surface_displayed` event should be generated in glean.
### Actual behavior
The `shopping.surface_displayed` event is not generated in glean.
### Device & build information

* Device: iPhone 15 Pro (17.3). 
* Build version: v123 (38665) 
* First seen version: N/A 
### Notes
Check [glean dashboard](https://glean-debug-view-dev-237806.firebaseapp.com/pings/Shamy21) for more details.
Attachments: 

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-8414)

**Comment by data-sync-user** [comment]
➤ Alina Moldovan commented:

verified this issue using FF v9000 (39713) and iPhone 15+(17.4)

The following events are generated when bottom sheet is displayed: 

    {
      "category": "shopping",
      "extra": {
        "size": "full-view"
      },
      "name": "surface_displayed",
      "timestamp": 40814
    } {
      "category": "shopping",
      "extra": {
        "size": "half-view"
      },
      "name": "surface_displayed",
      "timestamp": 52209
    }

**Comment by data-sync-user** [comment]
➤ Alina Moldovan commented:

Verified as issue using FF v9000 (39713) and iPhone 14+(16.0.3)

{
      "category": "shopping",
      "extra": {
        "glean_timestamp": "1710952312244",
        "size": "full-view"
      },
      "name": "surface_displayed",
      "timestamp": 33463
    },{
      "category": "shopping",
      "extra": {
        "glean_timestamp": "1710952319335",
        "size": "half-view"
      },
      "name": "surface_displayed",
      "timestamp": 40554
    },
