### ISSUE TITLE
Implement Swiping Left to Delete Tabs in Tab Tray

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#18664]
## Steps to reproduce
1. Swipe left on an open tab in the tab tray

### Expected behavior
The tab should be deleted

### Actual behavior
The tab moves in the direction of the swipe but cannot be deleted this way.

Note on implementation: The new Tab Tray needs to implement the `SwipeAnimationDelegate` for this to work.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-8418)

**Comment by brendanjones** [comment]
This is working for me, I can’t reproduce it. 🤷

**Comment by abodea** [comment]
> This is working for me, I can’t reproduce it. 🤷

Hi, did you have the Tabs Tray refactor experiment enabled? On what version did you check this?
