### ISSUE TITLE
[Tab tray refactor] Incorrect behavior of "Undo" button and toast message 

### ISSUE THREAD

**Issue by DianaBarladeanu** [mozilla-mobile/firefox-ios#18673]
**Prerequisites**
Go to FF secret settings ---> Experiments ---> enable “Rollout of tab tray refactor - iOS" feature

**Steps to reproduce**

1. Make sure you have several tabs opened in tabs tray.
1. Close all the tabs and then tap on "Undo".
1. Observe the undoing process.

**Expected behavior**
The closed tabs are correctly restored in tabs tray.
"Undo" button behaves correctly, toast message displays the correct number of restored tabs.

**Actual behavior**
"Undo" toast message is repetitive and it displays an incorrect number of restored tabs.

**Device & build information**

* Device: iPhone 15 (17.0)
* Build version: v9000 (38710), v123 (38665)
* First seen version: v9000 (38710), v123 (38665)
* 

**Notes**

**Please note that these issues also apply on private browsing.**

Attachments: 

https://github.com/mozilla-mobile/firefox-ios/assets/133357955/32fa7839-aa6b-4846-a4ae-00f06b65a44a

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-8422)

**Comment by data-sync-user** [comment]
➤ Alina Moldovan commented:

Verified as fixed using v9000 (39744) using iPhone 14+ (16.0.3) and iPad Pro 4th gen (17.2)

**Comment by data-sync-user** [comment]
➤ Norberto Andres Furlan commented:

Fixed by https://github.com/mozilla-mobile/firefox-ios/pull/18886 ( https://github.com/mozilla-mobile/firefox-ios/pull/18886 )
