### ISSUE TITLE
[Tab tray refactor] New "blank page" tabs import favicon from previously opened website

### ISSUE THREAD

**Issue by DianaBarladeanu** [mozilla-mobile/firefox-ios#18705]
**Prerequisites**

Go to FF secret settings ---> Experiments ---> enable “Rollout of tab tray refactor - iOS" feature.
Set new tab as blank page from FF settings.

 **Steps to reproduce**
1. Open a website, e.g. "amazon.com".
2. From tabs tray, open a new tab (either in normal browsing or in private browsing), do not type any URL. Repeat this 2-3 times, return to tabs tray and observe the thumbnails.

**Expected behavior**
New tabs' thumbnails should be blank, with no favicons.

**Actual behavior**
New tabs' thumbnail's have the favicon of the previously opened website (in this case, amazon.com).

**Device & build information**
* Device: iPhone SE (16.6)
* Build version: v123 (38749)
* First seen version: ?
Notes
Attachments: 

https://github.com/mozilla-mobile/firefox-ios/assets/133357955/d672c27a-8694-4f5b-bcb2-2c40c287682d

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-8433)

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v9000 (39777), with iPhone 15 (17.0).
