### ISSUE TITLE
Missing tab when reopening a closed one from History Recently Closed 

### ISSUE THREAD

**Issue by dragosb01** [mozilla-mobile/firefox-ios#18726]
## Steps to reproduce
1. Open a website and close the tab after that
2. Go to History Recently Closed 
3. Long press on the item to open the context menu
4. Tap on Open in New Tab
or
run the automation test from notes
### Expected behavior
The website should open in a new and should be visible on open tabs screen
### Actual behavior
The newly opened tab is not visible on open tabs, although the tab count shows 2
### Device & build information
* Device: ?  iPhone 15, 17.2
* Build version: ? 124.0
* First seen version: ? Yes
### Notes
Test case affected: https://testrail.stage.mozaws.net/index.php?/cases/view/2307484
Automation test affected: XCUITests/HistoryTests#testOpenInNewTabRecentlyClosedItem
Attachments: 

https://github.com/mozilla-mobile/firefox-ios/assets/134391433/53ebd04c-1608-4a2b-be9f-c8123a10d5b0

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-8443)

**Comment by dragosb01** [comment]
This issue might be related to this: https://github.com/mozilla-mobile/firefox-ios/issues/18725

**Comment by dragosb01** [comment]
Automation affected test on iPad: testOpenInNewPrivateTabRecentlyClosedItem

**Comment by data-sync-user** [comment]
➤ Alina Moldovan commented:

duplicates: [[FXIOS-8426] #18679 ⁃ [Tab tray refactor] New tabs opened through context menu are displayed as inactive tabs - Jira (atlassian.net)|https://mozilla-hub.atlassian.net/browse/FXIOS-8426]
