### ISSUE TITLE
Payment methods dissappear from settings after enabling "Use preview collection" in experiments

### ISSUE THREAD

**Issue by DianaBarladeanu** [mozilla-mobile/firefox-ios#18729]
**Steps to reproduce**
1. Install FF then restart the app, in order for payment methods to be displayed in settings.
2. Go to secret settings-->experiments--->edit--->enable "use preview collection"--->restart
3. Repeat edit--->enable "use preview collection"---> restart

 **Expected behavior**
"Payment methods" section is still displayed in settings.

**Actual behavior**
"Payment methods" section is not visible anymore.

**Device & build information**
* Device: iPhone 15 (17.0)
* Build version:v123 (38891)
* First seen version: ? 

Attachments: 

https://github.com/mozilla-mobile/firefox-ios/assets/133357955/7d7bfe19-b647-4db9-98a8-fbaf8d218aca

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-8444)

**Comment by data-sync-user** [comment]
➤ Norberto Andres Furlan commented:

Diana Andreea Barladeanu this is the expected behavior. The Payment Methods is currently an experiment (for all users all countries), so when you enable the Preview Mode experiments you get unenrolled from all the other experiments.
