### ISSUE TITLE
Drag and drop tabs on private mode is no longer working

### ISSUE THREAD

**Issue by dragosb01** [mozilla-mobile/firefox-ios#18724]
## Steps to reproduce
1. Open 2 websites in private mode
1. Try and rearrange the tabs using drag and drop
### Expected behavior
The user should be able to rearrange the tabs on private mode
### Actual behavior
The position of the tabs is not changing on drag and drop
### Device & build information

* Device: ? iPhone 15, 17.2
* Build version: ? 124.0
* First seen version: ? Yes
### Notes
Test case affected: https://testrail.stage.mozaws.net/index.php?/cases/view/2361193
Automation test affeced: XCUITests/DragAndDropTests#testRearrangeTabsPrivateModeTabTray
Attachments: 

https://github.com/mozilla-mobile/firefox-ios/assets/134391433/af16b12e-245f-4194-9f98-85bae410e31d

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-8441)

**Comment by clarmso** [comment]
@dragosb01 Could you still reproduce this bug on iPhone 15 iOS 17.2 simulator? I found an issue on drag-and-drop and am not sure and the issues are related.

**Comment by dragosb01** [comment]
> @dragosb01 Could you still reproduce this bug on iPhone 15 iOS 17.2 simulator? I found an issue on drag-and-drop and am not sure and the issues are related.

this issue is not reproducing anymore. Tested on iPhone15 17.2 simulator.

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v125 (40222), with iPhone 15 (17.0.).
