### ISSUE TITLE
After closing a private tab private browsing should remain in focus

### ISSUE THREAD

**Issue by dragosb01** [mozilla-mobile/firefox-ios#18728]
## Steps to reproduce
1. Open a website on private mode and close the tab
or
run the automation tests from notes
### Expected behavior
Private Browsing should remain open after closing the tab - see videos attached with the old behaviour
### Actual behavior
Homescreen opens 
When there are 2 tabs opens, after closing one, the other one opens

* See videos attached with the new behaviour
### Device & build information
* Device: ? iPhone 15, 17.2
* Build version: ? 124.0
* First seen version: ? Yes
### Notes
Affected test cases: https://testrail.stage.mozaws.net/index.php?/cases/view/2307475
https://testrail.stage.mozaws.net/index.php?/cases/view/2307486
Automation tests affected: XCUITests/HistoryTests#testRecentlyClosedPrivateMode
XCUITests/HistoryTests#testPrivateClosedSiteDoesNotAppearOnRecentlyClosed
Attachments: 

https://github.com/mozilla-mobile/firefox-ios/assets/134391433/0f84f5c2-6ba8-409c-aaaa-93f221667193

https://github.com/mozilla-mobile/firefox-ios/assets/134391433/a181192a-7804-4055-ae31-fdfadaa314f1

https://github.com/mozilla-mobile/firefox-ios/assets/134391433/93c2531e-6560-4519-8aac-0efc19cde58a

https://github.com/mozilla-mobile/firefox-ios/assets/134391433/365e93eb-4d3f-41cd-b798-16797dc0b51a

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-8445)

**Comment by dragosb01** [comment]
Automation test affected on iPad: testCloseAllTabsPrivateMode

**Comment by data-sync-user** [comment]
➤ Alina Moldovan commented:

This issue still reproducers using v9000 (39865) and iPhone 15+ (17.4) while Tab tray refactor experiment is ON

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v125 (40250), with iPhone 15 (17.0).
