### ISSUE TITLE
Desktop mode view on private mode affects regular mode

### ISSUE THREAD

**Issue by dragosb01** [mozilla-mobile/firefox-ios#18723]
## Steps to reproduce
1. Open a website
2. Switch to private browsing and open a website
3. Tap 'Request Desktop Site' - The desktop version of the sites is loaded for private mode
4. Open a tab in regular mode
or run the automation test from notes 
### Expected behavior
The mobile version of the sites is loaded for private mode
### Actual behavior
The desktop version of the sites is loaded for regular mode
### Device & build information
* Device: ? iPhone 15, 17.2 
* Build version: ? 124.0
* First seen version: ? Yes
### Notes
Affected test case: https://testrail.stage.mozaws.net/index.php?/cases/view/2306857
Affected automation test: XCUITests/DesktopModeTests/testPrivateModeOnHasNoAffectOnNormalMode
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-8440)

**Comment by clarmso** [comment]
I have taken a video of the test. The test website has been replaced with "https://www.youtube.com" for clarity.
https://github.com/mozilla-mobile/firefox-ios/assets/1740517/34fafd7a-bc71-4d19-b5ed-046c097ec3ec

Note the following actual behaviour:
* I can still toggle between desktop and mobile sites on the private tab.
* When I tried to toggle back to private mode on the regular tab, the page refreshes to desktop mode.

**Comment by dragosb01** [comment]
> I have taken a video of the test. The test website has been replaced with "https://www.youtube.com" for clarity. https://github.com/mozilla-mobile/firefox-ios/assets/1740517/34fafd7a-bc71-4d19-b5ed-046c097ec3ec
> 
> Note the following actual behaviour:
> 
> * I can still toggle between desktop and mobile sites on the private tab.
> * When I tried to toggle back to private mode on the regular tab, the page refreshes to desktop mode.

i believe your video is more related to drag and drop rather than desktop and mobile, am i mistaken? There is definitely and issue there.

**Comment by dragosb01** [comment]
Issue fixed
