### ISSUE TITLE
Missing tab opened when using open in new tab option

### ISSUE THREAD

**Issue by dragosb01** [mozilla-mobile/firefox-ios#18725]
## Steps to reproduce
1. Open a website that has a link
2. Long tap on the link to open the context menu
3. Select Open in New Tab option
4. Go to open tabs screen
or
run the automation test from notes
### Expected behavior
A second tab should be visible
### Actual behavior
The newly added tab is not visible on open tabs, although the tab count shows 2 
### Device & build information
* Device: ? iPhone 15, 17.2
* Build version: ? 124.0
* First seen version: ? Yes
### Notes
Affected test cases: https://testrail.stage.mozaws.net/index.php?/cases/view/2441772
https://testrail.stage.mozaws.net/index.php?/cases/view/2354300
Affected automation tests: XCUITests/NavigationTest#testOpenInNewTab
XCUITests/TopTabsTest#testAddTabFromContext
Attachments: 

https://github.com/mozilla-mobile/firefox-ios/assets/134391433/afb1c8c4-bcb7-4630-babf-356feb1ae619

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-8442)

**Comment by data-sync-user** [comment]
➤ Alina Moldovan commented:

duplicates [[FXIOS-8426] #18679 ⁃ [Tab tray refactor] New tabs opened through context menu are displayed as inactive tabs - Jira (atlassian.net)|https://mozilla-hub.atlassian.net/browse/FXIOS-8426]
