### ISSUE TITLE
[Tab tray refactor] Tab tray becomes untappable if device enters in standby mode whey tab-tray is opened 

### ISSUE THREAD

**Issue by alinamoldovan84** [mozilla-mobile/firefox-ios#18747]
## Steps to reproduce
1. Have some open tabs 
1. Open the tab tray 
1. Wait for the device to enter the standby mode
1. wait another 10+sec 
1. Open the device and check the app 

### Expected behavior
Tab tray is opened. User should be able to close and reopen the tab tray 

### Actual behavior
Sometimes the tab tray is closed and a new homepage is opened. Tab tray becomes untappable until the app is restarted.

### Notes 
Issue reproduces for both cases with felt-Privacy on and off. 

### Device & build information
* Device: iPhone 14+ (16.0.3), iPhone 15+ (17.4 - beta) 
* Build version: v123 (348801), v9000 (38860) 
* First seen version: ? 
### Notes
Attachments: 

https://github.com/mozilla-mobile/firefox-ios/assets/124251579/efda4701-35b6-4c6b-afa2-670c9fb68fb9

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-8454)

**Comment by data-sync-user** [comment]
➤ Matthew Reagan commented:

I don’t have a physical device to test this currently; I tried to repro on sim and wasn’t able to see any issues when switching to standby mode, waiting, then reopening app.

Alina Moldovan (cc Andrei Bodea) Can you let me know if you’re still seeing this issue?

**Comment by data-sync-user** [comment]
➤ Alina Moldovan commented:

Confirming that this issue still reproduces using v9000 (39744)

**Comment by data-sync-user** [comment]
➤ Alina Moldovan commented:

Not able to reproduce this issue anymore using v125 (40398)
