### ISSUE TITLE
[Tab tray refactor] Incorrect tabs are displayed  in tab tray after a private tab is closed 

### ISSUE THREAD

**Issue by alinamoldovan84** [mozilla-mobile/firefox-ios#18740]
### Scenario 1: 
1. Have 3 normal browsing tabs opened 
1. Have 3 private browsing tabs opened
1. Open the tab tray -> Navigate to the private browsing 
1. Close one Private tab 
1. Check the thumbnails  that are displayed

### Scenario 2: 
1. Have 1 normal browsing tabs opened 
1. Have 3 private browsing tabs opened
1. Open the tab tray -> Navigate to the private browsing 
1. Close one Private tab 
1. Check the behavior 
1. Repeat the steps 3->5 to close all private tabs 

### Expected behavior
Scenario 1: 

Private tab thumbnails should be displayed 

Scenario 2: 
Tab tray should stay opened. 

### Actual behavior
Scenario 1: 

Normal tab thumbnails are displayed be displayed under the Private tab section.

Scenario 2: 
Tab tray closes and the latest private tab opens. When the last private tab is closed the normal tab opens. 

Notes:

Same issue reproduces while felt-privacy experiment is on  

### Device & build information
* Device: iPhine 14+ (16.0.2) 
* Build version: 123 (38801) & v9000 (38860) 
* First seen version: ? 

*# 
*## Notes
Attachments: <
!--- Screenshots or screen recordings are very helpful for reproducing|width=200,height=183!
 -->

[https://github.com/mozilla-mobile/firefox-ios/assets/124251579/f9b19770-d3d5-4b76-bbf5-6315cc5525e9](https://github.com/mozilla-mobile/firefox-ios/assets/124251579/f9b19770-d3d5-4b76-bbf5-6315cc5525e9)

[https://github.com/mozilla-mobile/firefox-ios/assets/124251579/e3385b68-283c-40be-97a0-512b202883dc](https://github.com/mozilla-mobile/firefox-ios/assets/124251579/e3385b68-283c-40be-97a0-512b202883dc)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-8450)

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

To be rechecked on the 124 build.

ccNorberto Andres Furlan

**Comment by data-sync-user** [comment]
➤ Alina Moldovan commented:

Verified as fixed using v9000 (39865) and iPhone 15+ (17.4) while Tab tray refactor experiment is ON
