### ISSUE TITLE
[Tab tray refactor] Normal tabs are closed instead of private tabs

### ISSUE THREAD

**Issue by DianaBarladeanu** [mozilla-mobile/firefox-ios#18757]
**Prerequisites**
Go to FF secret settings ---> Experiments ---> enable “Rollout of tab tray refactor - iOS" feature.

**Steps to reproduce**
1. Have 5 normal tabs and 5 private tabs in tabs tray.
2. Go to private tabs section and start closing the tabs by tapping on the "x" button.
3. Observe the closing behavior.

**Expected behavior**
The private tabs are correctly closed and tabs tray is updated accordingly.
Private tabs tray is displayed.

**Actual behavior**
Only the first private tab is correctly closed.
Although it seems that you are still in private tabs tray  (private section icon is focused), normal tabs tray is displayed and the normal tabs are ones closed instead of the private.

**Device & build information**
* Device: iPad Air 3rd gen (17.3)
* Build version: v123(38801)
* First seen version: ? 

**Notes**
We have logged another related bug [here](https://github.com/mozilla-mobile/firefox-ios/issues/18740).
It is also reproducible with Felt privacy feature.

**Attachments:** 

https://github.com/mozilla-mobile/firefox-ios/assets/133357955/55b844a8-58ea-4ec6-b1d4-40e0be7e308d

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-8460)

**Comment by data-sync-user** [comment]
➤ Sophie Amin commented:

Fixed by Orla Mitchell as part of this PR https://github.com/mozilla-mobile/firefox-ios/pull/18800 ( https://github.com/mozilla-mobile/firefox-ios/pull/18800|smart-link )
