### ISSUE TITLE
iPad - keyboard not raised up when switching to private mode

### ISSUE THREAD

**Issue by dragosb01** [mozilla-mobile/firefox-ios#18754]
## Steps to reproduce
Run the automation test:
XCUITests/NewTabSettingsTest#testKeyboardRaisedWhenTabOpenedFromTabTray
### Expected behavior
The keyboard is not raised up when switching to private browsing
### Actual behavior
The keyboard should raise up
### Device & build information
* Device: iPad Air (5th generation) iOS 17.2 simulator
* Build version: 124.0
* First seen version: Yes
### Notes
Test case: https://testrail.stage.mozaws.net/index.php?/cases/view/2306877
This issue is reproducing only when running the automation test
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-8458)

**Comment by data-sync-user** [comment]
➤ Norberto Andres Furlan commented:

Andrei Bodea can you check that this one is fixed?

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Hello, please note that I was not able to reproduce this issue, I switched to PB and then opened a new tab and the keyboard was raised up. 
v124 (39092) with iPhone 15 Pro (17.1.2).

**Comment by dragosb01** [comment]
This issue happens only when running the automation test mentioned on the steps.

**Comment by dragosb01** [comment]
Closing task. Issue is not reproducing anymore.

**Comment by data-sync-user** [comment]
➤ Dragos Bigu commented:

Closing task. Issue is not reproducing anymore.
