### ISSUE TITLE
PWA support in the EU

### ISSUE THREAD

**Issue by niutech** [mozilla-mobile/firefox-ios#18752]
### User Problem
Apple is [ceasing support for PWAs](https://www.theregister.com/2024/02/16/apple_web_apps/) in the EU. Web apps on the home screen will be mere bookmarks opened in the default web browser. Please restore the PWA support in Firefox when it is a default web browser on iOS.

### Ideas for Solution
One workaround is drafted in this diagram (X being Firefox):

![PWA workaround](https://github.com/mozilla-mobile/firefox-ios/assets/384997/354c6483-9f3e-49bc-9562-7b24db5b03a0)

If Firefox detects a PWA (by heuristics such as some URL query param or hash or web app manifest), then it could hide its chrome, providing a fullscreen view.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-8457)

**Comment by data-sync-user** [comment]
➤ Norberto Andres Furlan commented:

We don’t have control over this.

**Comment by neongreen** [comment]
Apple reversed course and is no longer dropping support for PWAs.
