### ISSUE TITLE
Investigate UI changes necessary for swiping between tabs

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#18774]
* Most of the UI work will need to be done in `AddressToolbarContainer`.
  * We need to add a stack view to hold new compact toolbar instances and a scroll view to implement the swiping mechanism.
  * We also need to make the web pages swipe alongside the address bar.

┆Issue is synchronized with this [Jira Spike](https://mozilla-hub.atlassian.net/browse/FXIOS-8463)

**Comment by Tomatoshadow2** [comment]
adding to this feature request, another reddit user on the Firefox subreddit would like this also https://www.reddit.com/r/firefox/comments/1byaiyf/swipe_toolbar_to_change_tabs_on_ios/

**Comment by FormularSumo** [comment]
This would be great! And is pretty standard on other browsers, including Firefox for Android.
