### ISSUE TITLE
Issues with Navigation

### ISSUE THREAD

**Issue by mgaudet** [mozilla-mobile/firefox-ios#18793]
## Steps to reproduce
Unfortunately I don't have a reliable STR here. 

### Expected behavior
Navigation works correctly swiping between pages

### Actual behavior
In the below video you can see navigation both failing and also coming unstuck from the address bar, such that it doesn't match the displayed page. 

https://github.com/mozilla-mobile/firefox-ios/assets/2906003/21dcd3ce-2c8c-4479-8cda-ccf27a1789db

This seems to be 'correctable' by some amount of navigating backwards and forwards; but it's really unpleasant. 

### Device & build information
* Device: iPhone 13 
* Build version: 122.2 (38550)
* First seen version: I don't have a good answer for how long this has been going on.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-8471)

**Comment by mgaudet** [comment]
Oh, one other note: occasionally, I'll get the white screen for... 2-3 seconds, and then finally the page will render.

**Comment by data-sync-user** [comment]
➤ Norberto Andres Furlan commented:

It should be fixed on the next weekly release.

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v9000 (41100), with iPhone 15 (17.4).

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v127 (41813), with iPhone 15 (17.4).
