### ISSUE TITLE
Private homepage icon issue with RTL

### ISSUE THREAD

**Issue by lmarceau** [mozilla-mobile/firefox-ios#18838]
## Steps to reproduce
Run the application in private mode having an RTL language turned ON, and make sure you navigate to the homepage

### Expected behavior
Any right to left language should have properly spaced icons

### Actual behavior
The Firefox logo and the new private icon on the homepage are glued together and there's no spacing

### Device & build information
* Device: iPhone 15, iOS 17
* Build version: Latest main
* First seen version: ?

### Notes
Attachments: 
![Simulator Screenshot - iPhone 15 - 2024-02-23 at 11 39 19](https://github.com/mozilla-mobile/firefox-ios/assets/11338480/4508ef9d-ca2c-4062-9773-b0e580adaee8)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-8482)

**Comment by darkCavalier11** [comment]
I am new to swift, and want to work on this. I need to confirm what should be an ideal design, 
* is it moving the private tab icon to right, or
* Add a spacing to the right of the private tab icon

**Comment by lmarceau** [comment]
@darkCavalier11 My best guess would be to mirror the design from the LTR:

![Screenshot 2024-02-23 at 4 31 19 PM](https://github.com/mozilla-mobile/firefox-ios/assets/11338480/95156956-8e6b-42de-b0aa-fe8f879af3f2)

This means the private mask icon would stay at its same position, but the Firefox logo would be at the complete right (in the green square I drew on this screenshot)

![Screenshot 2024-02-23 at 4 28 33 PM](https://github.com/mozilla-mobile/firefox-ios/assets/11338480/a69668be-a348-4ff8-8d5c-209ab3e6c6f4)

Let me know if there's anything 🙏

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v9000 (39817), with iPhone 15 (17.0).

!BBF125D2-3C9F-4DA4-9DB7-FE8C60826679 Medium.jpeg|width=295,height=640!

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v125 (39935), with iPhone 15 (17.0).
