### ISSUE TITLE
[Tab tray refactor] Tab tray shows “Inactive Tabs” UI even when the “Inactive Tabs” setting is off

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/firefox-ios#18844]
## Steps to reproduce
1. Have some old, would-be inactive tabs open. 
1. Turn OFF the Settings > Tabs > Inactive Tabs setting. 
1. Open the tab tray. 

### Expected behavior
The tab tray should not show the “Inactive Tabs” UI when I have turned off the “Inactive Tabs” setting. 

### Actual behavior
The tab tray shows the “Inactive Tabs” UI even though I have turned off the “Inactive Tabs” setting. 

### Device & build information
* Device: iPhone 15 Plus running iOS 17.3.1.
* First seen version: This bug is a regression in TestFlight version 9000 (38793).

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-8483)

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v125 (40398), with iPhone 15 (17.0).
