### ISSUE TITLE
Remove Deferred from CredentialProviderPresenter

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#18917]
### Prerequisite
This task can be tackled once the needed `RustLogins` functions have been added on the `RustLogins` class. See Deferred tasks [here](https://github.com/mozilla-mobile/firefox-ios/issues?q=is%3Aissue+is%3Aopen+label%3ADeferred).

### Context
`RustLogins` is used as part of the `profile` object in multiple places throughout the codebase. As a first step to remove `Deferred`, we can remove it from the high level production code, leaving us with an interface that doesn’t depend on this legacy object. 

For this current task, this means adding a using the new completion handlers method added on the `RustLogins` object through the `LoginsProtocol`.

### Acceptance criteria
Use the new methods on the `LoginsProtocol` so the `CredentialProviderPresenter` class is not using `Deferred` anymore.

### Contributor note
This a contributor task, if you plan on working on this ticket please write so as a comment under this task so others can know this is being worked on.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-8518)

**Comment by bmihai23** [comment]
Hello @PARAIPAN9, I want to work on this issue. Thanks 🙏

**Comment by PARAIPAN9** [comment]
Sure thing!! Thank You!!

**Comment by data-sync-user** [comment]
➤ Cyndi Chin commented:

Please test around our Credential Logins lists.

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Validated on v126 (40917), with iPhone 15 (17.4).
