### ISSUE TITLE
Can no longer share to Firefox

### ISSUE THREAD

**Issue by YX42** [mozilla-mobile/firefox-ios#18929]
## Steps to reproduce
With the latest update Firefox has disappeared from the share options: e.g. open a website in Safari, tap on share symbol
### Expected behavior
Firefox should be an option to share to
### Actual behavior
Firefox can‘t be found
### Device & build information
* Device: iPad Air, 17.3.1 
* Build version: 123.2 (39233) 
* First seen version: 123.2 (39233) 
### Notes
Attachments: 

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-8521)

**Comment by afurlan-firefox** [comment]
Hi! Thank you for reporting it. Can you provide more info and the steps to reproduce? Is this happening from an external app or inside Firefox? Thanks!

**Comment by YX42** [comment]
The issue no longer persist. It appeared when sharing links from external apps such as Safari
