### ISSUE TITLE
Update Fonts in PrivateMessageCardCell to use FXFontStyles

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#18942]
Please update how we set fonts in `PrivateMessageCardCell` to use `FXFontStyles` instead of calling `DefaultDynamicFontHelper` directly. Provide before and after screenshots of the UI.

For example:
`FXFontStyles.Regular.headline.scaledFont()`

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-8528)

**Comment by darkCavalier11** [comment]
I want a bit of clarification on this one. Currently there is no class called `FXFontStyles` or am i missing something.

**Comment by cyndichin** [comment]
hi @darkCavalier11, the ticket is referring to this class here: https://github.com/mozilla-mobile/firefox-ios/blob/main/BrowserKit/Sources/Common/Utilities/FXFontStyles.swift

It was recently merged, so may need to update to latest if that's the issue. Let me know if you still don't see it!

**Comment by data-sync-user** [comment]
➤ Cyndi Chin commented:

This work has been merged in v125, please verify that the private message card cell fonts are scaled properly.
See PR for screenshots: https://github.com/mozilla-mobile/firefox-ios/pull/18974 ( https://github.com/mozilla-mobile/firefox-ios/pull/18974|smart-link )

**Comment by data-sync-user** [comment]
➤ Alina Moldovan commented:

Validated this issue using V9000 (39713) and iPhone 14+ (16.0.3). 

Comparing with the latest released version (124) the font size increased from 15 to 17. Please see the attached video. 

!Skype_Video52.mp4|width=33.33333333333333%!

Note: Cyndi Chin will confirm the changes with the design team.

**Comment by data-sync-user** [comment]
➤ Alina Moldovan commented:

Update: We got the design approval:  

!image-20240315-161508.png|width=16.666666666666664%!
