### ISSUE TITLE
Firefox crash after experiment is enabled

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#19031]
* Install Firefox v124
* Enable Enhanced Cross-Platform Firefox Suggest Experiment
* Access to the Search Settings
* Open a few tabs.
* Close the app.
* Open the app.
* You will see the crash Alert Dialog (See video)

[^RPReplay_Final1709683392.MP4]

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-8561)

**Comment by data-sync-user** [comment]
➤ Norberto Andres Furlan commented:

Alina Moldovan Andrei Bodea to check if the crash is related to the settings or other improvement.

**Comment by data-sync-user** [comment]
➤ Norberto Andres Furlan commented:

Probably related with https://mozilla-hub.atlassian.net/browse/FXIOS-8416 ( https://mozilla-hub.atlassian.net/browse/FXIOS-8416|smart-link )

**Comment by data-sync-user** [comment]
➤ Matthew Reagan commented:

Based on the stacktrace this is a different issue from https://mozilla-hub.atlassian.net/browse/FXIOS-8416 ( https://mozilla-hub.atlassian.net/browse/FXIOS-8416|smart-link ) 

An exception is being thrown after BackgroundFirefoxSuggestIngestUtility submitBackgroundTaskRequest(), after we submit the request for the BGProcessingTaskRequest

(Relevant snippet below)

Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Termination Reason: SIGNAL 6 Abort trap: 6
Terminating Process: Client [4229]

Triggered by Thread:  0

Application Specific Information:
abort() called

Last Exception Backtrace:
0   CoreFoundation                	       0x1921da678 __exceptionPreprocess + 164
1   libobjc.A.dylib               	       0x18a463c80 objc_exception_throw + 60
2   Foundation                    	       0x191738d38 _userInfoForFileAndLine + 0
3   BackgroundTasks               	       0x208907d6c -[BGTaskScheduler _unsafe_submitTaskRequest:error:] + 636
4   BackgroundTasks               	       0x208907aac -[BGTaskScheduler submitTaskRequest:error:] + 172
5   Client                        	       0x1013152c8 specialized BackgroundFirefoxSuggestIngestUtility.submitBackgroundTaskRequest() + 220
6   Client                        	       0x101314714 BackgroundFirefoxSuggestIngestUtility.scheduleTaskOnAppBackground() + 272
7   Client                        	       0x1013151e0 protocol witness for BackgroundUtilityProtocol.scheduleTaskOnAppBackground() in conformance BackgroundFirefoxSuggestIngestUtility + 28
8   Client                        	       0x100d6e9c0 BackgroundFetchAndProcessingUtility.scheduleOnAppBackground() + 96
9   Client                        	       0x10102e8a8 specialized AppDelegate.applicationDidEnterBackground(_:) + 1428

**Comment by ncloudioj** [comment]
Should be fixed by #19054, the uplift was attempted.

**Comment by data-sync-user** [comment]
➤ Norberto Andres Furlan commented:

Matthew Reagan can you correct the PR? Should be for 124, as the experiment needs to be run there. Thanks!

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v124 (39709), with iPhone 15 (17.0).
