### ISSUE TITLE
[Tab tray refactor] App crashes when closing multiple tabs

### ISSUE THREAD

**Issue by dragosb01** [mozilla-mobile/firefox-ios#19037]
## Logs
[Crash report.zip](https://github.com/mozilla-mobile/firefox-ios/files/14507630/Crash.report.zip)

## Steps to reproduce
1. Open a website in the first tab
1. Open 4 more empty tabs
1. Start closing the tabs in a quick session starting from the last one

### Expected behavior
All the tabs should be closed without any problems

### Actual behavior
When closing the tab that has the website opened the app crashes. The crash is intermittently.

### Device & build information
* Device:  iPhone 15 simulator, iOS 17.2
* Build version: 125.0

### Notes
Test case: https://testrail.stage.mozaws.net/index.php?/cases/view/2306868
Issue discovered while creating new automation test. This is a blocker for automation.
Attachments: 

https://github.com/mozilla-mobile/firefox-ios/assets/134391433/24602785-d2c2-4ea3-b941-64cc1ce8d54c

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-8563)

**Comment by data-sync-user** [comment]
➤ Orla Mitchell commented:

I wasn’t able to repo this one, please reopen if it’s still happening.

**Comment by data-sync-user** [comment]
➤ Dragos Bigu commented:

Orla Mitchell i could reproduce this issue running XCUITests/TopTabsTest#testTabTrayCloseMultipleTabs

The test fails intermittently, so it needs to run repeatedly a few times, but at some point it fails with a crash.

I removed the workaround and enabled the part where it fails so you can run it and reproduce it.

!Screenshot 2024-05-08 at 10.14.41.png|width=988,height=143,alt="Screenshot 2024-05-08 at 10.14.41.png"!

**Comment by data-sync-user** [comment]
➤ Alina Moldovan commented:

Not able to reproduce this issue anymore. Validated both manual and using automation testing

**Comment by dragosb01** [comment]
Closing ticket, issue is not reproducing anymore.
