### ISSUE TITLE
[Enhanced FF suggest settings] - Missing uppercase

### ISSUE THREAD

**Issue by DianaBarladeanu** [mozilla-mobile/firefox-ios#19058]
Prerequisites
Go to FF secret settings ---> Experiments ---> enable Enhanced Cross-Platform Suggest [iOS] experiment treatment b

**Steps to reproduce**
Go to FF settings --> Search and observe "Suggestions from sponsors" toggle.

**Expected behavior**
"Sponsors" should be written with uppercase as per design.

**Actual behavior**
"Sponsors" is written with lowercase.

Device & build information
* Device: iPhone 15 (17.0)
* Build version: v124(39464)
* First seen version: ?

Attachments: 

![4B9A2464-D521-49F7-A1EA-2AD49A93DBAC](https://github.com/mozilla-mobile/firefox-ios/assets/133357955/0b7cf14e-f0b6-4773-8ddf-5b9408b5ac86)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-8585)

**Comment by data-sync-user** [comment]
➤ Norberto Andres Furlan commented:

Sorin Paraipan can you change the string for v125?

**Comment by data-sync-user** [comment]
➤ Sorin Paraipan commented:

This was also fixed in this: https://github.com/mozilla-mobile/firefox-ios/pull/18938 ( https://github.com/mozilla-mobile/firefox-ios/pull/18938|smart-link )

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v9000 (39777), with iPhone 15 (17.0).

!C574AF86-C8B0-4F34-BB60-F613F72D74F9 Medium.jpeg|width=295,height=640!

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Validated on v125 (39892), with iPhone 15 (17.0).
