### ISSUE TITLE
[Enhanced FF suggest settings] - Missing description string for "Show in Private Sessions" toggle (Address Bar)

### ISSUE THREAD

**Issue by DianaBarladeanu** [mozilla-mobile/firefox-ios#19057]
Prerequisites
Go to FF secret settings ---> Experiments ---> enable Enhanced Cross-Platform Suggest [iOS] experiment treatment b

**Steps to reproduce**
Go to FF settings --> Search and observe the toggles.

**Expected behavior**
"Show in Private Sessions. Show suggestions from Firefox Suggest in private sessions” is correctly displayed.

**Actual behavior** 
The description string for "Show in Private Sessions" toggle is missing.

**Device & build information**
* Device: iPhone 15 (17.0)
* Build version: v124 (39464)
* First seen version: ? 
Notes

Attachments: 
![6251EFA5-A97A-4773-BA60-21EB5379BD47](https://github.com/mozilla-mobile/firefox-ios/assets/133357955/72ed8aaa-88d2-4f7d-8027-72b845bc4dd8)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-8584)

**Comment by data-sync-user** [comment]
➤ Norberto Andres Furlan commented:

Sorin Paraipan I think you already added this string, but can you confirm? If so, close the ticket.

**Comment by data-sync-user** [comment]
➤ Sorin Paraipan commented:

Yes Norberto Andres Furlan, it was added int this PR: https://github.com/mozilla-mobile/firefox-ios/pull/18938 ( https://github.com/mozilla-mobile/firefox-ios/pull/18938|smart-link )

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed in v9000 (39777), with iPhone 15 (17.0).

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v125 (39892), with iPhone 15 (17.0).
