### ISSUE TITLE
Deeplinks are incorrectly opened in private/normal mode 

### ISSUE THREAD

**Issue by alinamoldovan84** [mozilla-mobile/firefox-ios#19092]
## Steps to reproduce
1. Make sure FF is set as default browser
1. Open a tab in Private Mode 
1. While using Private Mode Force Close the app 
1. Open a webpage from an external app 
1. The link correctly opens in Private mode 
1. Switch to Normal browsing mode 
1. Put the app in background 
1. Open a webpage from an external app  => webpage incorrectly opens in Private Mode 
1. Switch to Normal browsing mode 
1. While using Normal browsing mode Force close the app 
1. Open a webpage from an external app 
1.  The link correctly opens in Normal browsing mode
1.  Switch to Private browsing mode 
1. Put the app in background 
1. Open a webpage from an external app  => webpage incorrectly opens in Normal Mode

### Expected behavior
When user opens link from an external app, FF should open the webpage using the latest navigation mode the user used (Private/Normal navigation mode)
Step8: Link should be open in Normal Mode

Step15: Link should be open in Private Mode

### Actual behavior
When user opens a web page from an external application, FF uses the navigation mode used when the application was last force closed 
Step8: Link should be open in Normal Mode

Step15: Link should be open in Private Mode

### Device & build information
* Device: 14+ (16.0.3) 
* Build version: 123.4 (39582) 
* First seen version: 123 or older 
### Notes
Attachments: 

https://github.com/mozilla-mobile/firefox-ios/assets/124251579/44512fe5-11d6-492a-87a4-2d910f68711a

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-8601)

**Comment by data-sync-user** [comment]
➤ Norberto Andres Furlan commented:

Sorin Paraipan didn’t you work on this one before? I can’t recall if it was fixed or if you told me it was something pending.

**Comment by data-sync-user** [comment]
➤ Sorin Paraipan commented:

This was the issue: https://mozilla-hub.atlassian.net/browse/FXIOS-7586. Was about deeplinks that are handled whitin the app.

**Comment by data-sync-user** [comment]
➤ Norberto Andres Furlan commented:

Got it! Thanks!

**Comment by data-sync-user** [comment]
➤ Nishant Bhasin commented:

When you mention `Switch to Normal browsing mode` have you opened a tab in Normal mode and selected it?

**Comment by data-sync-user** [comment]
➤ Sorin Paraipan commented:

Can confirm I’ve reproduced the issue in both modes. Switching from Private Browsing to Normal Browsing as described in the ticket and vice-versa. I suspect the state is not updated when the app goes to background. Still investigating the problem…

**Comment by data-sync-user** [comment]
➤ Sorin Paraipan commented:

Update: I’ve found the problem, and the reason is somehow related to what I was previously mentioning. The browsing state is being saved when going to the background, but the deeplink handler, the one that handles deeplinks when the app is in background, does not update to the latest browsing state. I’ll soon come up with a fix.

**Comment by data-sync-user** [comment]
➤ Alina Moldovan commented:

Confirming the fix in nightly build v9000 (40232) but the fix is not added in v125 (40222). Moving the status back to in progress.

**Comment by data-sync-user** [comment]
➤ Alina Moldovan commented:

Validated as fixed using FF v125 (40398) and iPhone 15+ (17.4)

**Comment by AWiryaman** [comment]
Hi! It looks like this bug might be back? Happy to open a new issue if that's helpful

https://github.com/user-attachments/assets/362fd768-834b-4ccf-b820-d6e46d2bb419

Device: 15 Pro (18.6.2)
Build version: 142.1 (60552)

**Comment by lmarceau** [comment]
@AWiryaman Could you open a new ticket (and link to the ticket here)? This way we can properly triage it 🙏 Thank you!
