### ISSUE TITLE
Missing toast messages from context menu

### ISSUE THREAD

**Issue by DianaBarladeanu** [mozilla-mobile/firefox-ios#19095]
**Steps to reproduce**

1. Make sure you have jump back in section enabled and populated on FF homepage (or the pocket section).
2. Long tap on one of the jump back in homepage links to open context menu.
3. Tap on "Bookmark" and observe.
4. Tap on Remove Bookmark and observe.

**Expected behavior**
"Added to bookmarks" toast message pops up when adding the link to bookmarks.
"Bookmark removed" toast message pops up when removing the link from bookmarks.

**Actual behavior**
None of the above mentioned toast message pops up.

Device & build information
* Device: iPhone 15 (17.0)
* Build version: v124 (39587)
* First seen version: ? 

 Notes

Attachments: 

https://github.com/mozilla-mobile/firefox-ios/assets/133357955/cf8ce1a9-562b-4db7-84a2-e4efd1443179

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-8604)

**Comment by MattLichtenstein** [comment]
Hello, I would like to take a stab at a fix for this 🙂

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v125 (39892), with iPhone 15 (17.0).
