### ISSUE TITLE
Intermittent  - Strange behavior when loading a webpage from History - Recently Closed section - 

### ISSUE THREAD

**Issue by alinamoldovan84** [mozilla-mobile/firefox-ios#19100]
## Steps to reproduce
1. App was clean installed and FF account logged in 
2. Multiple tabs opened and closed 
3. Navigate to History - Recently Closed section 
4. Tap a link 

### Expected behavior
The webpage is correctly loaded

### Actual behavior
Tab glitches while the webpage is loading (the loading process never ends)
Try to open the tab tray => the tab tray opens but closes immediately 
Try to open settings => the settings menu opens nut closes immediately 
open home screen -> this makes the page to load correctly 
Force close the app and repeat the above step => the issue is still reproducible 

### Device & build information
* Device: iPhone 14+ (16.0.3); iPhone XS (17.2.1); iPhone 15 (17.0) 
* Build version: 124 (39587);  123.2  
* First seen version: ? 
### Notes
Attachments: 

https://github.com/mozilla-mobile/firefox-ios/assets/124251579/f89c3d37-ec01-465d-9bc1-6b21903e100a

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-8605)

**Comment by data-sync-user** [comment]
➤ Alina Moldovan commented:

Validated this issue using v124 (39709) and iPhone 14+ (16.0.3), iPhone 15+ (17.4), iPhone 15 (17.0), iPhone 15 Pro max (17.1.3), iPhone 13 Pro (15.71)

We are not able to reproduce this issue anymore.
