### ISSUE TITLE
firefox on macos, smileys closing immedatiely after cmd+.

### ISSUE THREAD

**Issue by Serotonindude** [mozilla-mobile/firefox-ios#19123]
## Steps to reproduce
try inserting a smiley with cmd+.

### Expected behavior
keeping the emojiwindow open to insert, to selec an emoji

### Actual behavior
the moji window opens and closes immedateiely

### Device & build information
* Device: ? 
* Build version: ? 
* First seen version: ? 
    1. Notes
just fix it :open_mouth:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-8618)

**Comment by mattreaganmozilla** [comment]
@Serotonindude It looks like this is a bug ticket for Firefox for Mac, can you please [file a ticket in Bugzilla](https://support.mozilla.org/en-US/kb/file-bug-report-or-feature-request-mozilla)? (This repo is for Firefox iOS)
