### ISSUE TITLE
Undoing a bookmark removal re-adds incorrect bookmark

### ISSUE THREAD

**Issue by MattLichtenstein** [mozilla-mobile/firefox-ios#19126]
## Steps to reproduce
* Open to a webpage with a link (eg Amazon.com)
* Long press a link
* Press "Bookmark Link" from the context menu
* Long press the same link again
* Press "Remove Bookmark" from the context menu
* Press "Undo" from the "Removed Bookmark" toast message
* Go to your bookmarks (eg via Main Menu in the toolbar)
* Inspect recently added bookmark

### Expected behavior
* A bookmark should be added for the link that was long pressed

### Actual behavior
* A bookmark was added for the current page

### Device & build information
* Device: iPhone 15 Pro, iOS 17.4
* Build version: ? 125.0 (1)
* First seen version: ? N/A
### Notes
* This only happens as a result of undoing a bookmark removal. Adding a bookmark via the context menu (like in step 3) works just fine

### Attachments: 
https://github.com/mozilla-mobile/firefox-ios/assets/15353801/dfd583d1-fb73-4df2-a120-6950dd152db9

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-8619)

**Comment by MattLichtenstein** [comment]
> Hey, @MattLichtenstein, I want to work on this one. Thank you.

@dicarobinho That's great! I'm not currently working on the issue but probably best to wait from someone internal to give you the go-ahead 🙂

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v125 (40222), with iPhone 15 (17.0).
