### ISSUE TITLE
Telemetry - Incorrect "n_results" and "results" values are displayed  for urlbar.abandonment & urlbar.engagement & urlbar.impression

### ISSUE THREAD

**Issue by alinamoldovan84** [mozilla-mobile/firefox-ios#19140]
## Steps to reproduce
1. Make sure the device is set for you to be able to monitor the telemetry 
1. Perform some searches in URl Bar that retunes, both types of suggestions Google and Firefox suggest
1. Check the events details for the following: urlbar.abandonment & urlbar.engagement & urlbar.impression

### Expected behavior 
"n_results" should return the number of visible suggestions 
"results" should return the suggestion type for each visible suggestions 

### Actual behavior
a bigger number is return for both "n_results" and "results"

### Device & build information
* Device: iPhone 14+ (17.4) 
* Build version: 124 (39587) 
* First seen version: ? 
### Notes
Attachments: 

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-8622)

**Comment by data-sync-user** [comment]
➤ Stefan Vladut commented:

this issue happened because the PR that solves this was ported after the RC build was done, it should be ok on the latest builds

**Comment by data-sync-user** [comment]
➤ Alina Moldovan commented:

The counter is still displayed incorrectly 

Even if the total number of visible suggestions is 7 I got the following recordings. 11 seems to be the number of the suggestions including the ones under the keyboard. 

Stefan Vladut 

"category": "urlbar",
      "extra": {
        "glean_timestamp": "1712592854318",
        "groups": "search_suggest,search_suggest,search_suggest,search_suggest,heuristic,heuristic,remote_tab",
        "interaction": "typed",
        "n_chars": "2",
        "n_results": "8",
        "n_words": "1",
        "reason": "pause",
        "results": "search_suggest,search_suggest,search_suggest,search_suggest,tab,tab,remote_tab,bookmark",
        "sap": "urlbar_newtab",
        "search_mode": "tabs"
      },
      "name": "impression",
      "timestamp": 21646
    }{
      "category": "urlbar",
      "extra": {
        "engagement_type": "tap",
        "glean_timestamp": "1712592800462",
        "groups": "search_suggest,search_suggest,search_suggest,search_suggest,heuristic,remote_tab",
        "interaction": "refined",
        "n_chars": "2",
        "n_results": "11",
        "n_words": "1",
        "provider": "none",
        "results": "search_suggest,search_suggest,search_suggest,search_suggest,tab,remote_tab,bookmark,bookmark,bookmark,bookmark,history",
        "sap": "urlbar_newtab",
        "search_mode": "tabs",
        "selected_result": "bookmark",
        "selected_result_subtype": "bookmark"
      },
      "name": "engagement",
      "timestamp": 107767
    }{
      "category": "urlbar",
      "extra": {
        "glean_timestamp": "1712592662488",
        "groups": "search_suggest,search_suggest,search_suggest,search_suggest,heuristic,heuristic",
        "interaction": "pasted",
        "n_chars": "3",
        "n_results": "11",
        "n_words": "1",
        "results": "search_suggest,search_suggest,search_suggest,search_suggest,tab,tab,bookmark,bookmark,bookmark,history,history",
        "sap": "urlbar_newtab",
        "search_mode": "tabs"
      },
      "name": "abandonment",
      "timestamp": 122188
    }

**Comment by data-sync-user** [comment]
➤ Stefan Vladut commented:

Alina Moldovan for counting the visited cells we are using the SDK method willDisplayCell: which can sometimes load some extra cells in memory or count the barely visible cell as fully visible so it’s expected to sometimes have more results than shown on screen.
