### ISSUE TITLE
[Enhanced FF suggest settings] - Incorrect toggle name string

### ISSUE THREAD

**Issue by DianaABarladeanu** [mozilla-mobile/firefox-ios#19170]
Prerequisites
Go to FF secret settings ---> Experiments ---> enable Enhanced Cross-Platform Suggest [iOS] experiment treatment b

**Steps to reproduce**
Go to FF settings --> Search and observe the toggles.

 **Expected behavior**
"Search Synced Tabs" is displayed as per [figma](https://www.figma.com/file/Tr5V91qdlhds6MhH1CCjp5/Cross-platform-suggest?type=design&node-id=768-85188&mode=design&t=u2vpZQ50laD6eARe-0) design.

**Actual behavior**
"Search Synchronised Tabs" is displayed.

Device & build information

* Device: iPhone 15 (17.0).
* Build version: v124 (39709)

Notes
Attachments: 
![8C080E93-484A-43CA-B87C-0F46D61C58A7](https://github.com/mozilla-mobile/firefox-ios/assets/151131988/46a119a6-30aa-44de-a1ab-fc0e2a315fe7)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-8644)

**Comment by data-sync-user** [comment]
➤ Alexandru Farcasanu commented:

Norberto Andres Furlan 

Quick question here. 

Do we need to change the localization text here? (Search Syncronised Tabs). As I can see in the code, there are 2 translations for this switch title. For en-GB is Search Synchronised Tabs and for en-US is already Search Synced Tabs.

In Figma file, may be the US version and in the screenshot from Attachments, is the GB one.

**Comment by data-sync-user** [comment]
➤ Norberto Andres Furlan commented:

Diana Andreea Barladeanu can you check this? I think it is ok if English US is Sync Tabs as we have in the design, but the English-UK was translated like Syncronised (that I think it is the english UK version). How we can request a translation review? Thanks!

**Comment by data-sync-user** [comment]
➤ Delphine Lebedel commented:

Hi and thanks for flagging!

en-US strings are expected to stay as is, and other locales (such as en-GB, which is “English-UK” ) may wish to translate to something more appropriate to their language and culture. I checked on Pontoon (our Translation Management System) and indeed that is the way the localizer chose to translate.

So this should be all good 🙂

**Comment by data-sync-user** [comment]
➤ Alexandru Farcasanu commented:

No changes need to be done here!
Closed!
