### ISSUE TITLE
Intermittent - 'No internet connection' error is not displayed when trying to load a webpage while in airplane mode

### ISSUE THREAD

**Issue by alinamoldovan84** [mozilla-mobile/firefox-ios#19192]
## Steps to reproduce
1. Load Firefox homepage. 
1. Disable the Internet by enabling iOS airplane mode. 
1. On the homepage, tap to try to load any shortcut. 
1. You should see a “ The Internet connection appears to be offline.” error page

### Expected behavior
 “ The Internet connection appears to be offline.” should be displayed 

### Actual behavior
Sometimes it behave correct, the error is displayed.

Sometimes the webpage starts to load but remains stuck in this view, sometimes the homepage remains in the view even if the webpage URL is updated on the URL bar

### Device & build information
* Device: iPhone 15+ (17.4), iPhone 14+ (16.0.3) 
* Build version: v9000 (39744) 
* First seen version: ? 
### Notes
Attachments: 

https://github.com/mozilla-mobile/firefox-ios/assets/124251579/d66937d3-0a2e-4457-b233-6217037658a9

https://github.com/mozilla-mobile/firefox-ios/assets/124251579/eef4ac3d-bc2b-4cc6-8467-5871bb3ed112

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-8652)

**Comment by data-sync-user** [comment]
➤ Norberto Andres Furlan commented:

Razvan Litianu Can it be related with this change ( https://mozilla-hub.atlassian.net/browse/FXIOS-8556 )?

**Comment by data-sync-user** [comment]
➤ Alexandru Farcasanu commented:

I have tested this behaviour and I can’t reproduce it but I found something else.

1. Open FF
2. Turn on airplane mode
3. Trigger that No internet connection view by loading a page
4. Force close the app
5. Open app

It seems like something is broken… the No internet connection view is no more visible and the page is not working. Also, if you enable the internet again, the problem still be there until you close the current tab and open a new one.

Norberto Andres Furlan what dou you think? Is this a problem? Thank you.

!no internet.mp4|width=720,height=1280,alt="no internet.mp4"!

**Comment by data-sync-user** [comment]
➤ Alexandru Farcasanu commented:

Norberto Andres Furlan I’m going to open PR for this. May you add a fix version? Thank you.

ps: somehow I reproduced this issue and got a fix for it. 🤞

**Comment by data-sync-user** [comment]
➤ Norberto Andres Furlan commented:

Alexandru Farcasanu is it easy to backport it to 125? If so, lets put fix version 125, if not, we can do 126. Let me know what works best.

**Comment by data-sync-user** [comment]
➤ Alexandru Farcasanu commented:

Norberto Andres Furlan it may be easy to backport it to 125, there are only few changes.

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v126 (40774), with iPhone 15 (17.4).
