### ISSUE TITLE
Cannot run Focus using Xcode 15.3

### ISSUE THREAD

**Issue by clarmso** [mozilla-mobile/firefox-ios#19190]
## Steps to reproduce
1. Download Xcode 15.3 release (15E204a).
1. Ensure that Xcode 15.3 is used: `sudo xcode-select -s /Applications/Xcode_15.3app/Contents/Developer`
1. On Xcode, create at iPhone 15 iOS 17.4 simulator.
1. `rm -fr focus-ios/shavar-prod-lists`
1. `./checkout.sh`
1. `cd focus-ios`
1. Build focus: `xcodebuild build-for-testing -project Blockzilla.xcodeproj -scheme Focus -configuration FocusDebug -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.4'`
1. Run some tests: `xcodebuild test-without-building -scheme Focus -target XCUITest -configuration FocusDebug -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.4' -testPlan UnitTests`

### Expected behavior
Focus iOS can be installed. The tests start after the app is installed.

### Actual behavior
The compilation finishes without any errors, but the app _cannot_ be installed to the simulator.
![Simulator Screenshot - iPhone 15 - 2024-03-13 at 09 51 15](https://github.com/mozilla-mobile/firefox-ios/assets/1740517/fa157a96-6447-418a-a53c-c938e4514c6b)

Here's the error message on the terminal. Note the references to `MozillaRustComponents`:

```
Testing failed:
        App installation failed: Unable to Install “Firefox Focus”
        Firefox Focus encountered an error (Failed to install or launch the test runner. (Underlying Error: App installation failed: Unable to Install “Firefox Focus”. Please try again later. Failed to load Info.plist from bundle at path /Users/cso/Library/Developer/CoreSimulator/Devices/24A91751-58D6-4B84-B2E6-CE47E9C92BF1/data/Library/Caches/com.apple.mobile.installd.staging/temp.bGHgSA/extracted/Firefox Focus.app/Frameworks/MozillaRustComponents.framework; Extra info about "/Users/cso/Library/Developer/CoreSimulator/Devices/24A91751-58D6-4B84-B2E6-CE47E9C92BF1/data/Library/Caches/com.apple.mobile.installd.staging/temp.bGHgSA/extracted/Firefox Focus.app/Frameworks/MozillaRustComponents.framework/Info.plist": Couldn't stat /Users/cso/Library/Developer/CoreSimulator/Devices/24A91751-58D6-4B84-B2E6-CE47E9C92BF1/data/Library/Caches/com.apple.mobile.installd.staging/temp.bGHgSA/extracted/Firefox Focus.app/Frameworks/MozillaRustComponents.framework/Info.plist: No such file or directory. (Underlying Error: Unable to Install “Firefox Focus”. Please try again later. Failed to load Info.plist from bundle at path /Users/cso/Library/Developer/CoreSimulator/Devices/24A91751-58D6-4B84-B2E6-CE47E9C92BF1/data/Library/Caches/com.apple.mobile.installd.staging/temp.bGHgSA/extracted/Firefox Focus.app/Frameworks/MozillaRustComponents.framework; Extra info about "/Users/cso/Library/Developer/CoreSimulator/Devices/24A91751-58D6-4B84-B2E6-CE47E9C92BF1/data/Library/Caches/com.apple.mobile.installd.staging/temp.bGHgSA/extracted/Firefox Focus.app/Frameworks/MozillaRustComponents.framework/Info.plist": Couldn't stat /Users/cso/Library/Developer/CoreSimulator/Devices/24A91751-58D6-4B84-B2E6-CE47E9C92BF1/data/Library/Caches/com.apple.mobile.installd.staging/temp.bGHgSA/extracted/Firefox Focus.app/Frameworks/MozillaRustComponents.framework/Info.plist: No such file or directory. (Underlying Error: Failed to load Info.plist from bundle at path /Users/cso/Library/Developer/CoreSimulator/Devices/24A91751-58D6-4B84-B2E6-CE47E9C92BF1/data/Library/Caches/com.apple.mobile.installd.staging/temp.bGHgSA/extracted/Firefox Focus.app/Frameworks/MozillaRustComponents.framework; Extra info about "/Users/cso/Library/Developer/CoreSimulator/Devices/24A91751-58D6-4B84-B2E6-CE47E9C92BF1/data/Library/Caches/com.apple.mobile.installd.staging/temp.bGHgSA/extracted/Firefox Focus.app/Frameworks/MozillaRustComponents.framework/Info.plist": Couldn't stat /Users/cso/Library/Developer/CoreSimulator/Devices/24A91751-58D6-4B84-B2E6-CE47E9C92BF1/data/Library/Caches/com.apple.mobile.installd.staging/temp.bGHgSA/extracted/Firefox Focus.app/Frameworks/MozillaRustComponents.framework/Info.plist: No such file or directory))))
```

### Device & build information
* Device: iPhone 15 iOS 17.4 simulator
* Build version: March 12, 2024
* First seen version: ? 
### Notes
Firefox can be compiled and installed using Xcode 15.3. Focus still works with Xcode 15.2.

I have cleared `DerivedData/` folder, reset package caches and got the same error from Focus.

Attachments: 

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-8651)

**Comment by razvanlitianu** [comment]
hey @clarmso does this https://github.com/mozilla-mobile/firefox-ios/pull/19251 fixes this issue?

**Comment by clarmso** [comment]
> hey @clarmso does this #19251 fix this issue? I'm able to compile and run the steps with success. The only thing after running /.checkout I have this added to commit. 

@razvanlitianu Yes, #19251 fixes the issue. 🎉
