### ISSUE TITLE
Autofill cannot be done on the fields that previously were populated (and deleted)

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/firefox-ios#19272]
### Preconditions
https://63p8v.csb.app/ save an account for this.

## Steps to reproduce
1. Launch FF and access https://63p8v.csb.app/.
1. Tap on the username and perform an autofill (autofill is done without problems).
1. Delete the username, and make sure the password is still there or vice versa.
1. Tap on username and then on the `use saved password` button.
1. Select from the list the saved account for https://63p8v.csb.app/.
### Expected behavior
The autofill should be done without problems.
### Actual behavior
Autofill cannot be done on the fields that previously were populated (and deleted)
### Device & build information

* Device: iPhone 15 Pro (17.3) 
* Build version: v124 (39709) 
* First seen version: N/A 
### Notes
Attachments: 

https://github.com/mozilla-mobile/firefox-ios/assets/42831109/c2ecb793-ee0b-45de-bc89-3629ed24e79f

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-8688)

**Comment by data-sync-user** [comment]
➤ Norberto Andres Furlan commented:

Issam Mani do you have a fix for this weekly release or should we push it for the other one?

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Unable to verify this issue since the password autofill in not functional, at the moment, as per this bug ticket: https://mozilla-hub.atlassian.net/browse/FXIOS-8792 ( https://mozilla-hub.atlassian.net/browse/FXIOS-8792|smart-link )

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v9000 (40331), with iPhone 15 (17.0).

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v9000 (40331), with iPhone 15 (17.0).
