### ISSUE TITLE
[Intermittent] The keyboard was not displayed when tapping on the username or password field in order to autofill

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/firefox-ios#19275]
## Steps to reproduce
1. Launch FF and save a login to https://63p8v.csb.app/.
1. Go to https://63p8v.csb.app/. tap on the username or password field.
1. Observe the keyboard.
### Expected behavior
The keyboard should be displayed without problems.
### Actual behavior
The keyboard was not displayed when tapping on the username or password field in order to autofill.
### Device & build information

* Device: iPhone 15 Pro (17.3) 
* Build version: v124 (39709) 
* First seen version: N/A 
### Notes
Attachments: 

https://github.com/mozilla-mobile/firefox-ios/assets/42831109/7f400249-4e17-4c11-92c2-51fbfe42e5be

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-8689)

**Comment by data-sync-user** [comment]
➤ Norberto Andres Furlan commented:

Razvan Litianu can you take a look to this one? Thanks!

**Comment by data-sync-user** [comment]
➤ Norberto Andres Furlan commented:

Andrei Bodea is the keyboard that is not showing or the accessory view? Because on the video we can see the keyboard. Can you confirm?

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Hi, it’s about this part in the video for some good amount of seconds the keyboard was not displayed at all.

!image-20240321-151352.png|width=335,height=665!

**Comment by data-sync-user** [comment]
➤ Razvan Litianu commented:

Checked with Andrei Bodea and it seems it’s a recording feature to not allow viewers to see the password while typing.
