### ISSUE TITLE
Increase in errors for metrics `tabs.tab_switch` and `webview.page_load`

### ISSUE THREAD

**Issue by badboy** [mozilla-mobile/firefox-ios#19298]
Since 2024-02-20 (probably release day?) we see an uptick in `invalid state` errors reported by Glean for two metrics:

* [`tabs.tab_switch`](https://dictionary.telemetry.mozilla.org/apps/firefox_ios/metrics/tabs_tab_switch)
* [`webview.page_load`](https://dictionary.telemetry.mozilla.org/apps/firefox_ios/metrics/webview_page_load)

This error can happen when a non-existing or stopped timer is stopped again ([docs](https://mozilla.github.io/glean/book/reference/metrics/timing_distribution.html#recorded-errors)).
I haven't checked the code yet myself.

The data [can be seen in Looker](https://mozilla.cloud.looker.com/explore/firefox_ios/metrics?qid=aYiB05LvhzNxv6d5zJfd1O&origin_space=746&toggle=fil,vis).
It affects up to 36% (page_load) / 13% (tab_switch) of clients.
Note that this of course doesn't affect correctly running timers and that data is still reported without issues.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-8704)

**Comment by data-sync-user** [comment]
➤ Stefan Vladut commented:

for QA, when I tested I managed to reproduce these errors here ( https://glean-debug-view-dev-237806.firebaseapp.com/pings/StefanVPageLoad ) and then after applying the fix did another test here ( https://glean-debug-view-dev-237806.firebaseapp.com/pings/SVCheck ) where I couldn’t reproduce those errors again.
