### ISSUE TITLE
Update Fonts in SnackBar to use FXFontStyles

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#19318]
_This task is part of a series of tasks to standardizing fonts to start using_ `FXFontStyles`_._ 

**Background Context:**
Previously, we were using `DefaultDynamicFontHelper` and setting the text style, size and weight for each font, which sometimes did not match our design system. By using `FXFontStyles`, we can standardize our fonts and be more aligned with the design system.

**Task:**
Please update how we set fonts in 

`SnackBar`

**Acceptance Criteria:**

* Replace usage of  `DefaultDynamicFontHelper` with `FXFontStyles`
* If there are discrepancies in terms of replacing the old fonts with the new standard, we will need to bring design in to approve the PR.
* Please provide before and after screenshots of the UI.

**Reference:**

Usage example:
`FXFontStyles.Regular.headline.scaledFont()`

See this PR for example of standardizing fonts for Primary Button: 

[https://github.com/mozilla-mobile/firefox-ios/pull/18711/files](https://github.com/mozilla-mobile/firefox-ios/pull/18711/files|smart-link)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-8711)

**Comment by rojinpra7** [comment]
I would like to work on this issue.

**Comment by cyndichin** [comment]
thanks @rojinpra7!

**Comment by data-sync-user** [comment]
➤ Cyndi Chin commented:

Please verify fonts have not changed for our snack bar view:

!Simulator Screenshot - iPhone 15 Pro - 2024-03-21 at 13.40.56.png|width=1179,height=2556!
