### ISSUE TITLE
Update actionSecondary and actionSecondaryHover token

### ISSUE THREAD

**Issue by cwzilla** [mozilla-mobile/firefox-ios#19320]
Hi team,

I'd like to make some changes to the `actionSecondary` and `actionSecondaryHover` token. Currently, the token uses a light grey colour which is more suited for light mode, however it looks out of place for dark mode.

These are the changes I'm proposing:

`actionSecondary`

* BG: ~~Dark Grey 10~~ Dark Grey 05
* Text: `textPrimary`

`actionSecondaryHover`

* BG: ~~Dark Grey 05~~ Light Grey 90
* Text: `textPrimary`

These changes are recorded in the [changelog](https://docs.google.com/spreadsheets/d/1T_f73XoWN7ZZlhoDz6dzHsjSdte4s3NKdVXvI7jh1AI/edit?usp=sharing) (line 49 & 50) and in [Figma](https://www.figma.com/file/pEyGeE4KV5ytYHeXMfLcEr/Mobile-Styles?type=design&node-id=5446%3A15666&mode=design&t=N3XdK5Bw09ovBYeg-1). Thanks!

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-8712)

**Comment by data-sync-user** [comment]
➤ Cyndi Chin commented:

This update does not only change the SecondaryRoundedButton, but also impacts other UI. See more details in the Figma File link:

https://www.figma.com/file/wUAdBkTBofyIYzMiS7iOCN/ActionSecondaryAudit?type=design&node-id=0-1&mode=design&t=h7qAuAHDrvJpJhGE-0 ( https://www.figma.com/file/wUAdBkTBofyIYzMiS7iOCN/ActionSecondaryAudit?type=design&node-id=0-1&mode=design&t=h7qAuAHDrvJpJhGE-0|smart-link )

**Comment by data-sync-user** [comment]
➤ Crystal Wong commented:

Hi Cyndi Chin, sorry I’m going to be annoying and modify what I originally proposed. After looking at the screenshots in Figma (for the rounded buttons particularly), the contrast looks too low against the card bg with the new colours. 

New proposal for the background is dark grey 05 and in hover state light grey 90. The text can stay as textPrimary. Sorry for the inconvenience!

**Comment by data-sync-user** [comment]
➤ Cyndi Chin commented:

No worries Crystal Wong , I updated the Figma File with the updated screenshots. I left some comments, let me know if there’s anything else you would like me to update!

**Comment by data-sync-user** [comment]
➤ Cyndi Chin commented:

Please verify UI with in FINAL section in Figma file and that colors match. Let me know if you have any questions verifying. Thank you!

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Hi, Cyndi Chincan you please let me know if there is anything to be checked for QA? or how this issue should be verified?

**Comment by data-sync-user** [comment]
➤ Cyndi Chin commented:

Hi Andrei Bodea , could you verify that the colors match in the following screens?

!image-20240408-143633.png|width=743,height=780,alt="image-20240408-143633.png"!

See FINAL section in Figma: https://www.figma.com/file/wUAdBkTBofyIYzMiS7iOCN/ActionSecondaryAudit?type=design&node-id=0-1&mode=design&t=h7qAuAHDrvJpJhGE-0 ( https://www.figma.com/file/wUAdBkTBofyIYzMiS7iOCN/ActionSecondaryAudit?type=design&node-id=0-1&mode=design&t=h7qAuAHDrvJpJhGE-0|smart-link )
