### ISSUE TITLE
Update Fonts related to SyncNow to use FXFontStyles

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#19337]
_This task is part of a series of tasks to standardizing fonts to start using_ `FXFontStyles`_._ 

**Background Context:**
Previously, we were using `DefaultDynamicFontHelper` and setting the text style, size and weight for each font, which sometimes did not match our design system. By using `FXFontStyles`, we can standardize our fonts and be more aligned with the design system.

**Task:**
Please update how we set fonts related:

`SyncNowSetting`

**Acceptance Criteria:**

* Replace usage of  `DefaultDynamicFontHelper` with `FXFontStyles`
* If there are discrepancies in terms of replacing the old fonts with the new standard, we will need to bring design in to approve the PR.
* Please provide before and after screenshots of the UI.

**Reference:** 

Usage example:
`FXFontStyles.Regular.headline.scaledFont()`

See this PR for example of standardizing fonts for Primary Button: 

[https://github.com/mozilla-mobile/firefox-ios/pull/18711/files](https://github.com/mozilla-mobile/firefox-ios/pull/18711/files|smart-link)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-8725)

**Comment by AhmedFitoh** [comment]
Could you assign this one to me ?

**Comment by cyndichin** [comment]
@AhmedFitoh Yes, thank you for your interest, assigned!

**Comment by data-sync-user** [comment]
➤ Cyndi Chin commented:

Please verify fonts scaled properly for our Sync Now settings. See screenshots in PR for more details.

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Verified as fixed on v9000 (40522) with iPhone 15 Pro (17.3).

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v126 (40846), with iPhone 15 (17.4).
