### ISSUE TITLE
Update Fonts related to FakeSpot to use FXFontStyles (Part II)

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#19335]
_This task is part of a series of tasks to standardizing fonts to start using_ `FXFontStyles`_._ 

**Background Context:**
Previously, we were using `DefaultDynamicFontHelper` and setting the text style, size and weight for each font, which sometimes did not match our design system. By using `FXFontStyles`, we can standardize our fonts and be more aligned with the design system.

**Task:**
Please update how we set fonts related to FakeSpot feature. Changes should be made in the following areas:
`FakespotOptInCardView`
`FakespotReliabilityCardView`
`FakespotReliabilityScoreView`
`FakespotReviewQualityCardView`
`FakespotSettingsCardView`
`FakespotOptInCardViewModel`
`FakespotViewController`

**Acceptance Criteria:**

* Replace usage of  `DefaultDynamicFontHelper` with `FXFontStyles`
* If there are discrepancies in terms of replacing the old fonts with the new standard, we will need to bring design in to approve the PR.
* Please provide before and after screenshots of the UI.

**Reference:** 

Usage example:
`FXFontStyles.Regular.headline.scaledFont()`

See this PR for example of standardizing fonts for Primary Button: 

[https://github.com/mozilla-mobile/firefox-ios/pull/18711/files](https://github.com/mozilla-mobile/firefox-ios/pull/18711/files|smart-link)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-8723)

**Comment by bmihai23** [comment]
Hi @cyndichin, I would like to continue working on the second issue related to Fakespot Fonts update. Thank you 🙏

**Comment by cyndichin** [comment]
thank you @bmihai23, assigned! :)

**Comment by data-sync-user** [comment]
➤ Cyndi Chin commented:

Please verify that fonts scaled property and match screenshots attached to the Github issue.

**Comment by data-sync-user** [comment]
➤ Adina Petridean commented:

Verified as fixed on v9000(40720), with iPhone 14 Pro Max (16.2).

!ReviewChecker.png|width=1148,height=1008,alt="ReviewChecker.png"!
