### ISSUE TITLE
Update Fonts related to FakeSpot to use FXFontStyles (Part I)

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#19334]
_This task is part of a series of tasks to standardizing fonts to start using_ `FXFontStyles`_._ 

**Background Context:**
Previously, we were using `DefaultDynamicFontHelper` and setting the text style, size and weight for each font, which sometimes did not match our design system. By using `FXFontStyles`, we can standardize our fonts and be more aligned with the design system.

**Task:**
Please update how we set fonts related to FakeSpot feature. Changes should be made in the following areas:
`FakespotActionFooterView`
`FakespotAdjustRatingView`
`FakespotAdView`
`FakespotHighlightsCardView`
`FakespotHighlightGroupView`
`FakespotMessageCardView`
`FakespotMessageCardButton`
`FakespotNoAnalysisCardView`

**Acceptance Criteria:**

* Replace usage of  `DefaultDynamicFontHelper` with `FXFontStyles`
* If there are discrepancies in terms of replacing the old fonts with the new standard, we will need to bring design in to approve the PR.
* Please provide before and after screenshots of the UI.

**Reference:** 

Usage example:
`FXFontStyles.Regular.headline.scaledFont()`

See this PR for example of standardizing fonts for Primary Button: 

[https://github.com/mozilla-mobile/firefox-ios/pull/18711/files](https://github.com/mozilla-mobile/firefox-ios/pull/18711/files|smart-link)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-8722)

**Comment by bmihai23** [comment]
Hi @cyndichin, I would like to work on this issue. Thank you 🙏

**Comment by cyndichin** [comment]
great @bmihai23! assigned to you :) thanks!

**Comment by data-sync-user** [comment]
➤ Cyndi Chin commented:

Please verify fonts scaled appropriately for the screenshots provided in the Github issue. Thank you!

**Comment by data-sync-user** [comment]
➤ Adina Petridean commented:

Verified as fixed on v9000(40720), with iPhone 14 Pro Max (16.2).

!Settings.png|width=1148,height=1009,alt="Settings.png"!

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v126 (40846), with iPhone 15 (17.4).
