### ISSUE TITLE
Bug on twitter/X when opening a link

### ISSUE THREAD

**Issue by teleter** [mozilla-mobile/firefox-ios#19355]
## Steps to reproduce
open a link in web version of twitter/x in any tweet and it will redirect you a about:blank page instead it happens almost every other link click 

### Expected behaviour
New tab to open with the hyperlinked article etc

### Actual behaviour
only a about:blank tab is opened nothing else

### Device & build information
* iPhone 12 Pro Max / iOS 17.4 (21E219)
* Firefox 124.0 (39709)
* New to me on this version

*# 
*## Notes
Attachments: 

[https://github.com/mozilla-mobile/firefox-ios/assets/121882223/ee19a254-16cb-4555-9123-d383225533fd](https://github.com/mozilla-mobile/firefox-ios/assets/121882223/ee19a254-16cb-4555-9123-d383225533fd)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-8730)

**Comment by afurlan-firefox** [comment]
@teleter This issue is fixed in 124.2. Can you update and let us know? Thanks!
