### ISSUE TITLE
Inconsistency in Sync Now icon animation

### ISSUE THREAD

**Issue by mytiadorofieiev** [mozilla-mobile/firefox-ios#19360]
The Sync Now icon in the settings has arrows that are oriented counter-clockwise. However, the animation for the Sync Now icon spins the icon clockwise, which appears unnatural and inconsistent.

### Steps to reproduce
1. Navigate to the settings.
1. Observe the direction of the arrows on the Sync Now icon.
1. Trigger the Sync Now action to see the animation of the icon spinning.
### Expected behavior
The animation of the Sync Now icon should spin in a counter-clockwise direction to match the orientation of the arrows on the icon.
### Actual behavior
The animation of the Sync Now icon spins clockwise, which is inconsistent with the icon's design.
### Device & build information

* Device: iPhone 13 mini, iOS 17.4.1
* Build version: Firefox 124.0 (39709)
* First seen version: unknown
### Notes
This inconsistency affects the visual experience of the application and should be addressed to maintain design consistency.

Attachments: 
![firefox!UNITO-UNDERSCORE!sync!UNITO-UNDERSCORE!bug](https://github.com/mozilla-mobile/firefox-ios/assets/164520905/b34c432e-1e0c-47a0-88b5-5353c9bc9fcb)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-8731)

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v9000 (40444), with iPhone 15 (17.0).

The animation of the Sync Now icon spins in a counter-clockwise direction.

!original-64D96DC4-AF9E-4CA6-A5BF-C6BE0D61A44D.mp4|width=444,height=960,alt="original-64D96DC4-AF9E-4CA6-A5BF-C6BE0D61A44D.mp4"!

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v125 (49470), with iPhone 15 (17.0).
