### ISSUE TITLE
Fix Button to match our standard buttons in Switch Your Default Browser view

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#19402]
The button on the screen below doesn't look like our standard button (it's slightly taller). Please fix the UI so that the button is more aligned with our other standard buttons. We should be relying on the `PrimaryRoundedButton` for styling.

**Issue:**
See button in this view for “Go to Settings”, which does not match out standard buttons.

!image-20240327-140919.png|width=1179,height=2556,alt="image-20240327-140919.png"!

**Expected:**
See button in this view for “Go to Settings” matches our standard buttons.

!image-20240327-141023.png|width=1179,height=2556,alt="image-20240327-141023.png"!

Reference:
[https://github.com/mozilla-mobile/firefox-ios/pull/19003#discussion_r1515166944](https://github.com/mozilla-mobile/firefox-ios/pull/19003#discussion_r1515166944|smart-link)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-8751)

**Comment by MattLichtenstein** [comment]
Hello, I'd like to take a look at this one!

**Comment by data-sync-user** [comment]
➤ Adina Petridean commented:

Verified as fixed on v9000(40522), with iPhone 14 Pro Max (16.2).

!DB.png|width=1016,height=1005,alt="DB.png"!

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v126 (40719), with iPhone 15 (17.4).
