### ISSUE TITLE
Focus can't be run on iOS 15

### ISSUE THREAD

**Issue by clarmso** [mozilla-mobile/firefox-ios#19418]
## Steps to reproduce
1. Install Xcode 15.2.
1. Create iPhone 13 iOS 15.x Simulator on Xcode.
1. (Run `./checkout.sh` on the command line.)
1. Open Focus project (Blockzilla) on Xcode.
1. Open one of the Full Functional tests.
1. Select the iPhone 13 iOS 15.x simulator created in step 2.
1. Run one test.

### Expected behavior
Focus is launched on the simulator.

### Actual behavior
The simulator stuck on this screen.
![Simulator Screenshot - iPhone 13 - 2024-03-27 at 11 44 15](https://github.com/mozilla-mobile/firefox-ios/assets/1740517/e4f07963-0f15-49c3-9661-55ae70a06872)

The following error is shown on Xcode:

```
dyld[79379]: Symbol not found: _$s10Foundation12URLQueryItemVMa
  Referenced from: /Users/cso/Library/Developer/Xcode/DerivedData/Blockzilla-gzvnoyhldqblgvaluydggsulyiew/Build/Products/FocusDebug-iphonesimulator/RustMozillaAppServices.framework/RustMozillaAppServices
  Expected in: /Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 15.4.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/Foundation.framework/Foundation
```

### Device & build information
* Device: iPhone 13 iOS 15.4 
* Build version: After https://github.com/mozilla-mobile/firefox-ios/pull/19251
* First seen version: https://github.com/mozilla-mobile/firefox-ios/pull/19251
### Notes

Firefox iOS can be launched on iOS 15.

Same error shown on Xcode 15.3.

Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-8755)

**Comment by data-sync-user** [comment]
➤ Razvan Litianu commented:

Fixed by https://github.com/mozilla-mobile/firefox-ios/pull/19635 ( https://github.com/mozilla-mobile/firefox-ios/pull/19635|smart-link )
