### ISSUE TITLE
[regression] Tab tray shows placeholder letters instead of tab thumbnail images

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/firefox-ios#19427]
## Steps to reproduce
1. Install TestFlight version 9000 (40044)
1. Open some pages in new tabs.
1. Open the tab try.

### Expected behavior
The tab tray should show tab thumbnail images.

### Actual behavior
The tab tray shows placeholder letters instead of thumbnail images. See the screenshot below.

### Device & build information
* Device: iPhone 15 Plus running iOS 17.3.1.
* First seen version: This bug is a regression in TestFlight version 9000 (40044). The previous build, version 9000 (40010), shows the tab thumbnails correctly.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-8758)

**Comment by cpeterso** [comment]
![image](https://github.com/mozilla-mobile/firefox-ios/assets/629193/9d411728-a461-4400-9079-9a19ab4c8953)

**Comment by data-sync-user** [comment]
➤ Alina Moldovan commented:

Sophie Amin Norberto Andres Furlan 

Please note that this issue also reproduces using FF 125 (40641) while Tab Tray refactor experiment if OFF.

**Comment by data-sync-user** [comment]
➤ Norberto Andres Furlan commented:

Intermittent or always?

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v125 (40715), with iPhone 15 (17.4) and iPad Air 3rd gen (17.3).

The issue was fixed when opening new tabs from context menu, shortcuts, external apps etc, but it still reproduces intermitently when opening new tabs through “+” button and with hamburger menu.
