### ISSUE TITLE
Intro onboarding modal shown again after being dismissed on iPad

### ISSUE THREAD

**Issue by MattLichtenstein** [mozilla-mobile/firefox-ios#19426]
## Steps to reproduce
* Open the client for the first time such that the "Intro" onboarding is shown
* Dismiss the modal by either swiping it down or clicking outside of it
* Re-launch the app

### Expected behavior
* The "Intro" onboarding modal does NOT appear and the user is taken to the browser homepage

### Actual behavior
* The "Intro" onboarding modal appears again over the browser homepage

### Device & build information
* Device: iPad Air (5th gen), iOS 17.4
* Build version: 126.0 (1)
* First seen version: N/A

### Notes
* Affects iPad only because the modal is fullscreen on other devices and therefore cannot be swiped away
* Modal "Dismissal" telemetry is not recorded 

Attachments: 

https://github.com/mozilla-mobile/firefox-ios/assets/15353801/1ae6443b-b79d-4039-9101-89465c835aed

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-8757)

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v9000 (405220, with iPad Air 3rd Gen (17.3).

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v126 (40774), with iPad Air 3rd gen (17.3).
