### ISSUE TITLE
[Password Autofill] The autofill can be done only on one field at a time on `Netflix.com` even when having a username and password on the same webpage

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/firefox-ios#19448]
## Steps to reproduce
1. Launch FF and save a login for netflix.com.
2. Access netflix.com and then sign in.
3. Tap on the username and then on the `Use saved password`.
4. Select the account in order to autofill.
### Expected behavior
Both password and username fields are auto-filled without a problem.
### Actual behavior
The autofill can be done only on one field at a time on `Netflix.com` even when having a username and password on the same webpage.
### Device & build information
* Device: iPhone 15 Pro (17.3). 
* Build version: 125 (40129) 
* First seen version: N/A 
### Notes
Attachments: 

https://github.com/mozilla-mobile/firefox-ios/assets/42831109/0a175606-7d1a-4621-ae67-f166a16220dd

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-8778)

**Comment by data-sync-user** [comment]
➤ Norberto Andres Furlan commented:

Issam Mani same with this one.
