### ISSUE TITLE
[Password Autofill] The autofill is not done on some websites 

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/firefox-ios#19450]
## Steps to reproduce
1. Launch FF and save an account and password for a website.
1. Tap on the username or password fields.
1. Tap on the `Use saved password`.
1. Select the saved account for the website and attempt to autofill.
### Expected behavior
The autofill is done without problems.
### Actual behavior
 The autofill is not done on some websites.
### Device & build information

* Device: iPhone 15 Pro (17.3). 
* Build version: 125 (40129) 
* First seen version: N/A 
### Notes

|` Website` | `Use saved password button` appear? | `Autofill Done?` |
| :-------------: | :-------------: | :-------------: |
| `Accounts.google.com`  |:white_check_mark:|    :x:  |
| `youtube.com`             |        :white_check_mark:            |        :x:            |
|`baidu.com`                |         :white_check_mark:           |        :x:            |
| `wipipedia.org`               |        :white_check_mark:            |         :x:           |
| `yandex.ru`               |          :white_check_mark:          |        :x:            |
| `tiktok.com`               |         :white_check_mark:           |        :x:            |
| `openai.com`               |        :white_check_mark:            |     :x:               |
| `netflix.com`               |      :white_check_mark:              |        :x:            |
| `office.com`               |        :white_check_mark:            |        :x:            |
| `dzen.ru`               |          :white_check_mark:          |         :x:           |
| `zoom.us`               |        :white_check_mark:            |        :x:            |
| `naver.com`               |      :white_check_mark:              |      :x:              |
| `mail.ru`               |             :white_check_mark:       |         :x:           |
|  `ebay.com`              |         :white_check_mark:           |      :x:              |

Attachments: 

https://github.com/mozilla-mobile/firefox-ios/assets/42831109/668858f9-1d18-4014-b5a6-37d858779ee0

https://github.com/mozilla-mobile/firefox-ios/assets/42831109/39399d1c-f66d-42fc-99d4-e92098c7d070

https://github.com/mozilla-mobile/firefox-ios/assets/42831109/ea78f476-1bc1-4215-b477-6cec883b1730

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-8779)

**Comment by data-sync-user** [comment]
➤ Norberto Andres Furlan commented:

Issam Mani can you take a look to this one?

**Comment by data-sync-user** [comment]
➤ Issam Mani commented:

Norberto Andres Furlan this PR ( https://github.com/mozilla-mobile/firefox-ios/pull/19490 ) should fix most issues. Note that for office.com we can’t fix it right now since they use two separate domains for the username form and password form. I did check all websites except  http://baidu.com ( http://baidu.com|smart-link ) ,  yandex.ru ( http://yandex.ru ) and http://dzen.ru ( http://dzen.ru|smart-link ).

**Comment by data-sync-user** [comment]
➤ Norberto Andres Furlan commented:

Alina Moldovan to check.

**Comment by abodea** [comment]
Verified as fixed on v9000 (40522) with iPhone 15 Pro (17.3).
I was able to autofill on all the following websites:
|` Website` | `Use saved password button` appear? | `Autofill Done?` |
| :-------------: | :-------------: | :-------------: |
| `Accounts.google.com`  |:white_check_mark:|    :white_check_mark:     |
| `youtube.com`             |        :white_check_mark:            |       :white_check_mark:            |
|`baidu.com`                |         :white_check_mark:           |      :white_check_mark:           |
| `wipipedia.org`               |        :white_check_mark:            |          :white_check_mark:            |
| `yandex.ru`               |          :white_check_mark:          |        :white_check_mark:             |
| `tiktok.com`               |         :white_check_mark:           |        :white_check_mark:              |
| `openai.com`               |        :white_check_mark:            |     :white_check_mark:               |
| `netflix.com`               |      :white_check_mark:              |         :white_check_mark:            |
| `office.com`               |        :white_check_mark:            |      :white_check_mark:              |
| `dzen.ru`               |          :white_check_mark:          |        :white_check_mark:             |
| `zoom.us`               |        :white_check_mark:            |      :white_check_mark:            |
| `naver.com`               |      :white_check_mark:              |    :white_check_mark:               |
| `mail.ru`               |             :white_check_mark:       |         :white_check_mark:             |
|  `ebay.com`              |         :white_check_mark:           |     :white_check_mark:            |
