### ISSUE TITLE
[Tabs tray refactor] -Tab tray button becomes untappable after closing tabs tray by swiping down

### ISSUE THREAD

**Issue by DianaABarladeanu** [mozilla-mobile/firefox-ios#19464]
**Steps to reproduce**

1. Have some open tabs.
1. Go to tab tray and close it by swiping down.
1. Tap on tab tray button and observe.

**Expected behavior**
Tab tray is opened. User should be able to close and reopen the tab tray.

**Actual behavior**
Tab tray button becomes untappable until the app is restarted.

**Device & build information**

* Device: iPhone 15 (17.0)
* Build version: v125 (40222)
* First seen version: ? 

Notes:
The issue is also reproducible with private mode.

Attachments: 

https://github.com/mozilla-mobile/firefox-ios/assets/151131988/bf8d255b-1266-495b-a484-0ab117f44fa0

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-8784)

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v9000 (40408), with iPhone 15 (17.0).

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v125 (40470), with iPhone 15 (17.0).
