### ISSUE TITLE
Address Autofill Foxfooding Bugs: Street Address doesn't fill + CDW.com doesn't work

### ISSUE THREAD

**Issue by ewachowiak** [mozilla-mobile/firefox-ios#19470]
## Steps to reproduce
Street address does not fill when using Address Autofill on the following websites:
-https://designsystem.digital.gov/templates/form-templates/address-form/
-asos.com

Address autofill does not work at all when using guest checkout on CDW.com

See attached videos for more detail.

### Device & build information
* Device: iPhone 13, iOS 17.3.1
* Build version: 125.0 (Firefox Beta)
* First seen version: ?125.0 (Firefox Beta) 

https://github.com/mozilla-mobile/firefox-ios/assets/105799839/c99d2519-c941-49f8-825e-d5482d0b7861

https://github.com/mozilla-mobile/firefox-ios/assets/105799839/f6bc68a8-2dbc-422d-bc07-f875bc56aa72

https://github.com/mozilla-mobile/firefox-ios/assets/105799839/1fcd9ad9-a93c-423c-8ac1-f605cf8ba42d

### Notes
Attachments: 

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-8785)

**Comment by data-sync-user** [comment]
➤ Issam Mani commented:

Thanks Emily Wachowiak  for reporting. It seems that this PR ( https://github.com/mozilla-mobile/firefox-ios/pull/19223 ) is not part of the foxfooding build. I tested again on main and both https://designsystem.digital.gov/templates/form-templates/address-form/ ( https://designsystem.digital.gov/templates/form-templates/address-form/|smart-link ) and https://www.asos.com/us/ ( https://www.asos.com/us/|smart-link )  are working. There seems to be an issue withhttp://cdw.com ( http://cdw.com|smart-link )  though. I will take a look later.

!Screen Recording 2024-04-02 at 19.42.29.mov|width=922,height=1916,alt="Screen Recording 2024-04-02 at 19.42.29.mov"!

!Screen Recording 2024-04-02 at 19.55.17.mov|width=864,height=1894,alt="Screen Recording 2024-04-02 at 19.55.17.mov"!

**Comment by data-sync-user** [comment]
➤ Issam Mani commented:

I have a patch ( https://phabricator.services.mozilla.com/D206398 ) for the http://cdw.com/ ( http://cdw.com/|smart-link )  issue 😄

**Comment by data-sync-user** [comment]
➤ Norberto Andres Furlan commented:

Diana Andreea Barladeanu Alina Moldovan  can you check this one?

**Comment by data-sync-user** [comment]
➤ Issam Mani commented:

Norberto Andres Furlan let’s wait for this PR ( https://github.com/mozilla-mobile/firefox-ios/pull/19631 ) to be merged first. Then we can have a build with the fix for QA 😄

**Comment by data-sync-user** [comment]
➤ Alina Moldovan commented:

Validated as fixed using FF v125 (40715) and iPhone 15+ (17.4.1)
