### ISSUE TITLE
NotificationService can crash if push decrypted data includes bytes with a high-bit set

### ISSUE THREAD

**Issue by tarikeshaq** [mozilla-mobile/firefox-ios#19494]
This is a little hard to reproduce and would need non-ascii data in a send tab URL or a device name but shouldn't be impossible and we have reports of that happening when users sign into a new device, or when sending tabs.

See https://bugzilla.mozilla.org/show_bug.cgi?id=1882829 for more details

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-8791)

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Verified as fixed on v125 (40715) with iPhone 15 Pro (17.4.1).
Please note that I’ve sent more than 20 tabs, the message was correctly displayed and no crashes.
