### ISSUE TITLE
[Password Autofill] The autofill cannot be done on any website

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/firefox-ios#19500]
## Steps to reproduce
1. Launch FF go to https://63p8v.csb.app/ and save a login.
2. Refresh the page and tap on the username.
3. Tap on the Use saved password.
4. Select the account from the prompt in order to autofill.
### Expected behavior
The autofill is done without issues.
### Actual behavior
The autofill cannot be done on any website.
### Device & build information
* Device: iPhone 15 Pro (17.3) 
* Build version: v124.3 (40285) 
* First seen version:  v124.3 (40285) 
### Notes
Please note that we were able to repro this bug on v125 (40250) beta 7 but not on v125 (40222) beta 6.
Attachments: 

https://github.com/mozilla-mobile/firefox-ios/assets/42831109/279377d0-3860-4323-8d9d-674b566b513e

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-8792)

**Comment by data-sync-user** [comment]
➤ Issam Mani commented:

Let’s wait for https://github.com/mozilla-mobile/firefox-ios/pull/19490 ( https://github.com/mozilla-mobile/firefox-ios/pull/19490|smart-link )  to be backported to 124.

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Hi, Issam Manithis morning for QA the new build was ready 124.3 ( https://mozilla.slack.com/archives/C03PKCHHSSD/p1711998286964329 ) you can check I added the slack conversation.

**Comment by data-sync-user** [comment]
➤ Issam Mani commented:

Hey Andrei Bodea ,  https://github.com/mozilla-mobile/firefox-ios/pull/19490 ( https://github.com/mozilla-mobile/firefox-ios/pull/19490|smart-link ) was only merged today morning and backported to 125 not 124. So it’s still not available for you to test against 😄

**Comment by data-sync-user** [comment]
➤ Norberto Andres Furlan commented:

Andrei Bodea can I close this one?
