### ISSUE TITLE
[Password autofill] "Use saved password" prompt not displayed after two field deletions 

### ISSUE THREAD

**Issue by DianaABarladeanu** [mozilla-mobile/firefox-ios#19513]
**Steps to reproduce**

1. Launch FF and go to a website for which you have a saved login.
1. Tap on the username/email address.
1. Tap on Use saved password button.
1. Select the login for autofill.
1. Delete the email address/username.
1. Tap again on Use saved password button and select again the login for autofill.
1. Delete the email address/username again and observe.

**Expected behavior**
The "Used saved password" prompt is displayed again/still displayed.

 **Actual behavior**
The "Used saved password" prompt is NOT displayed anymore after the second deletion of the username/email address.
There is also a glitch happening when tapping repeatedly on the email/username field.

**Device & build information**

* Device: iPhone 15 (17.0)
* Build version: v124.3 (40336)
* First seen version: ?

Notes
We have a logged another bug with a similar issue, but a different scenario [here](https://github.com/mozilla-mobile/firefox-ios/issues/19502).

Attachments: 

https://github.com/mozilla-mobile/firefox-ios/assets/151131988/5f706981-461b-4e83-8bf2-6a930dedb5c2

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-8802)

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v126 (40917), with iPhone 15 (17.4).
