### ISSUE TITLE
[Address Autofill] - Change Autofill Address String

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#19614]
“Autofill Addresses” to be, simply, “Addresses”

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-8890)

**Comment by adudenamedruby** [comment]
this has been addressed with this [PR](https://github.com/mozilla-mobile/firefox-ios/pull/19620) and will get closed once QA validates it.

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Verified as fixed on v9000 (40573) with iPhone 15 (17.3).

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v126 (40846), with iPhone 15 (17.4).

!7AD75719-A057-455E-AB98-21ADA73AA854.jpg|width=944,height=2048,alt="7AD75719-A057-455E-AB98-21ADA73AA854.jpg"!
