### ISSUE TITLE
[regression] Audio continues to play after the tab is closed

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/firefox-ios#19616]
## Steps to reproduce
1. Open a page that has looping audio or video, such as this tweet: https://twitter.com/shouldhaveanima/status/1671456689424572416/mediaViewer
1. Play the video. 
1. Close the tab while the video is still playing. 

### Expected behavior
The tab’s audio should stop playing, like it does in Safari, Chrome, and Firefox build 9000 (39713) and earlier. 

### Actual behavior
This tab’s audio continues to play. The only way to stop it is to force quit Firefox. 

### Device & build information
**This bug is a regression starting in build 9000 (39744).** In build 9000 (39713) and earlier, audio stops when the tab is closed.

I reported a similar regression last year: https://github.com/mozilla-mobile/firefox-ios/issues/15162. 

* Device: iPhone 15 Plus running iOS 17.4.1
* First seen version: 9000 (39744)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-8891)

**Comment by data-sync-user** [comment]
➤ Norberto Andres Furlan commented:

Chris Peterson is this happening with the tab tray refactor on?

**Comment by data-sync-user** [comment]
➤ Norberto Andres Furlan commented:

Sophie Amin can you take a look to this one?

**Comment by cpeterso** [comment]
> ➤ Norberto Andres Furlan commented:
> 
> Chris Peterson is this happening with the tab tray refactor on?

I can reproduce this bug with or without the tab tray refactor (preview experiment "Rollout of tab tray refactor (Nightly)").

**Comment by data-sync-user** [comment]
➤ Norberto Andres Furlan commented:

Related ticket:

https://mozilla-hub.atlassian.net/browse/FXIOS-7073 ( https://mozilla-hub.atlassian.net/browse/FXIOS-7073|smart-link )

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v125.1 (40778), with iPhone 15 (17.4).

The audio stops playing after closing the tab with “x” button, through swipe and through context menu. 

The audio keeps playing for several seconds if you close the tab with “close all“ button, as per this bug ( https://github.com/mozilla-mobile/firefox-ios/issues/17336 ) ticket.

!RPReplay_Final1713251965.mp4|width=590,height=1280,alt="RPReplay_Final1713251965.mp4"!

**Comment by chrisban** [comment]
This absolutely still happens in iPadOS 18.5, Firefox 139.2 (56579). It is absolutely infuriating, doesn’t matter if you close every tab or refresh everything the audio stream plays magically in the background, impossible to stop it without killing the entire app.

This happens ALL THE TIME just with closing single tabs
