### ISSUE TITLE
[a11y] Address autofill - Save and Fill Addresses switch button is incorrectly announced   

### ISSUE THREAD

**Issue by alinamoldovan84** [mozilla-mobile/firefox-ios#19617]
## Steps to reproduce
1. Make sure you have Voice Over set to ON
1. Open FF, navigate to settings -> Autofill Addresses menu 
1. Check for the  Save and Fill Addresses switch button 

### Expected behavior
The "Save and Fill Addresses" should be announced as a switch button including it's state (On/Off)

### Actual behavior
The "Save and Fill Addresses" is announced as a button. It's state is not announced 

### Device & build information
* Device: iPhone 15+ (17.4) 
* Build version: v125 (40250) 
* First seen version: ? 
### Notes
Attachments: 

https://github.com/mozilla-mobile/firefox-ios/assets/124251579/287ab08c-57a2-4a96-af9a-d0a76bc1ad49

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-8892)

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v126 (41303), with iPhone 15 (17.4).
