### ISSUE TITLE
Closing a private tab - tab tray should remain in focus

### ISSUE THREAD

**Issue by dragosb01** [mozilla-mobile/firefox-ios#19672]
## Steps to reproduce
Open 2 websites on private mode and close the first tab
or
run the automation test from notes
### Expected behavior
Tab tray should remain in focus having the second tab remaining in view
### Actual behavior
The second tab opens after closing the first tab. See recording.
### Device & build information
* Device: ? iPhone 15, 17.2
* Build version: 126.0
* First seen version: No
### Notes
Issue reproducing on both iPhone and iPad devices
XCUITests/HistoryTests#testPrivateClosedSiteDoesNotAppearOnRecentlyClosed
Attachments: 

https://github.com/mozilla-mobile/firefox-ios/assets/134391433/a0a163b8-79db-47b0-a888-2031cce9c00a

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-8909)

**Comment by data-sync-user** [comment]
➤ Norberto Andres Furlan commented:

Dragos Bigu is this happening with the tab tray refactor enabled?

**Comment by dragosb01** [comment]
> ➤ Norberto Andres Furlan commented:
> 
> Dragos Bigu is this happening with the tab tray refactor enabled?

Yes with tab tray enabled
