### ISSUE TITLE
 Add signing config for RustMozillaAppServices

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#19698]
{quote}`CreateBuildDescription Build description signature: fd3939f909a98052fabae17dda5d88d8 Build description path: /Users/vagrant/Library/Developer/Xcode/DerivedData/Blockzilla-dobrvacznxoyqggqvqbhcqmgtrry/Build/Intermediates.noindex/ArchiveIntermediates/Focus/IntermediateBuildFilesPath/XCBuildData/fd3939f909a98052fabae17dda5d88d8.xcbuilddata /Users/vagrant/git/focus-ios/Blockzilla.xcodeproj: error: RustMozillaAppServices has conflicting provisioning settings. RustMozillaAppServices is automatically signed for development, but a conflicting code signing identity iPhone Distribution has been manually specified. Set the code signing identity value to "Apple Development" in the build settings editor, or switch to manual signing in the Signing & Capabilities editor. (in target 'RustMozillaAppServices' from project 'Blockzilla') /Users/vagrant/git/focus-ios/Blockzilla.xcodeproj: warning: DEFINES_MODULE was set, but no umbrella header could be found to generate the module map (in target 'RustMozillaAppServices' from project 'Blockzilla') note: Run script build phase 'Nimbus Feature Manifest Generator Script' will be run during every build because the option to run the script phase "Based on dependency analysis" is unchecked. (in target 'Blockzilla' from project 'Blockzilla') note: Run script build phase 'Run Script (Copy Wordmark)' will be run during every build because the option to run the script phase "Based on dependency analysis" is unchecked. (in target 'Blockzilla' from project 'Blockzilla') note: Run script build phase 'Run Swiftlint' will be run during every build because the option to run the script phase "Based on dependency analysis" is unchecked. (in target 'Blockzilla' from project 'Blockzilla') ** ARCHIVE FAILED **`{quote}

Issue building Focus Nightly

* `RustMozillaAppServices has conflicting provisioning settings. RustMozillaAppServices is automatically signed for development, but a conflicting code signing identity iPhone Distribution has been manually specified. Set the code signing identity value to "Apple Development" in the build settings editor, or switch to manual signing in the Signing & Capabilities editor`
* `/Users/vagrant/git/focus-ios/Blockzilla.xcodeproj: error: No signing certificate "iOS Development" found: No "iOS Development" signing certificate matching team ID "43AQ936H96" with a private key was found. (in target 'RustMozillaAppServices' from project 'Blockzilla')`

cc [~accountid:6047c1da0b784000691f4ad8]

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-8915)

**Comment by JohanLorenzo** [comment]
ℹ️ The new certificate required a bump of the Bitrise step "Certificate and profile installer". More info in https://bugzilla.mozilla.org/show_bug.cgi?id=1890492

**Comment by data-sync-user** [comment]
➤ Nishant Bhasin commented:

Can we close this Isabel Rios Escobar ?

**Comment by data-sync-user** [comment]
➤ Nishant Bhasin commented:

Actually closing it as I see it merged here https://github.com/mozilla-mobile/firefox-ios/pull/19697 ( https://github.com/mozilla-mobile/firefox-ios/pull/19697|smart-link )
