### ISSUE TITLE
[Customization onboarding] - Wrong button on intro card (treatment c)

### ISSUE THREAD

**Issue by DianaABarladeanu** [mozilla-mobile/firefox-ios#19708]
Prerequisites
User is enrolled in "App Customization in Onboarding" experiment on treatment c.

**Steps to reproduce**

1. Fresh install FF.
1. From FF settings, go to Show tour.
1. Observe the first onboarding card (Firefox puts you in control).

**Expected behavior**
The card has two buttons: "Customize Firefox" and "Skip".

**Actual behavior**
The card has "Start browsing" button instead of "Skip" button.

**Device & build information**

* Device: iPhone 15 (17.0), iPhone SE (16.6), iPad Air 3rd gen (17.3)
* Build version: v9000 (40573)
* First seen version: v9000 (40573)

Notes
Attachments: 

https://github.com/mozilla-mobile/firefox-ios/assets/151131988/8ab1fb5a-b9b4-4fb2-b36f-490d7e3854ad

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-8919)

**Comment by data-sync-user** [comment]
➤ Alina Moldovan commented:

Verified as fixed using v9000 (40927) and iPhone 15+ (17.4.1)

!image-20240419-142731.png|width=25%,alt="image-20240419-142731.png"!

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v125.2 (41035).
