### ISSUE TITLE
[Customization onboarding] - Toolbar placement card can't be used on iPad

### ISSUE THREAD

**Issue by DianaABarladeanu** [mozilla-mobile/firefox-ios#19706]
Prerequisites
User is enrolled in "App Customization in Onboarding" experiment on treatment a.

**Steps to reproduce**

1. Fresh install FF.
1. From FF settings, go to Show tour.
1. Go to the 4th card ("Pick a toolbar placement").
1. Select the "Bottom" option.
1. Close the onboarding tour and go to FF homepage.

**Expected behavior**
Toolbar is displayed on bottom.

**Actual behavior**
We don't have the bottom toolbar option on iPad, so the onboarding card can't customize anything.

Device & build information

* Device: iPad Air 3rd gen (17.3)
* Build version: v9000 (40573)
* First seen version: v9000 (40573)

Notes
This applies to all 3 experiment variants.

Attachments: 

https://github.com/mozilla-mobile/firefox-ios/assets/151131988/77c2baec-23bb-4687-afd5-357cdf65efc2

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-8918)

**Comment by data-sync-user** [comment]
➤ Roux Buciu commented:

Targeting has been added ( https://github.com/mozilla/experimenter/pull/10553#event-12425224977 ) to Nimbus, but I don’t know of often it updates. Norberto Andres Furlan you’ll have to set up the targeting for iPhone only in the frontend.

**Comment by data-sync-user** [comment]
➤ Roux Buciu commented:

Have made a second PR ( https://github.com/mozilla/experimenter/pull/10582 ) for the targeting.

**Comment by data-sync-user** [comment]
➤ Alice Varro commented:

We’ve verified this issue after the advanced targeting of the “App Customization iOS ( https://experimenter.services.mozilla.com/nimbus/app-customization-in-onboarding-ios/summary )” experiment was changed to “First-run users on Firefox for iOS on iPhones” and we can confirm that we are no longer enrolled in the experiment using an iPad Air 2 device (iOS 15.8).

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v125.2 (41035), with iPad Air 3rd gen (17.3).

The customization onboarding cards are NOT displayed on iPad.

!RPReplay_Final1714028312.mp4|width=720,height=960,alt="RPReplay_Final1714028312.mp4"!
