### ISSUE TITLE
[Customization onboarding] - Incorrect behavior of "Start browsing" button (Intro card)

### ISSUE THREAD

**Issue by DianaABarladeanu** [mozilla-mobile/firefox-ios#19703]
Prerequisites
User is enrolled in "App Customization in Onboarding" experiment treatment b.

 **Steps to reproduce**

1. Fresh install FF.
1. From FF settings, go to Show tour.
1. Go to the 4th onboarding card ("Firefox puts you in control").
1. Tap on "Start browsing".

**Expected behavior**
The onboarding tour closes, FF homepage is opened.

**Actual behavior**
The "Pick a toolbar placement" card is opened.

**Device & build information**

* Device: iPhone 15 (17.0)
* Build version: v9000 (40573)
* First seen version: v9000 (40573) 

Notes

Attachments: 

https://github.com/mozilla-mobile/firefox-ios/assets/151131988/0329994c-7b87-4687-8de4-82200b738aab

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-8916)

**Comment by data-sync-user** [comment]
➤ Roux Buciu commented:

For testing, this needs to be done in the nimbus config.

**Comment by data-sync-user** [comment]
➤ Alina Moldovan commented:

Verified as fixed using FF 126 (40927) and iPhone 15+ (17.4.1)

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v125.2 (41035), with iPhone 15 (17.4).
