### ISSUE TITLE
Firefox crashes on launch when the onboarding is displayed

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/firefox-ios#19711]
## Steps to reproduce
1. Fresh install FF.
2. Open FF.
3. Observe the onboarding.
### Expected behavior
The onboarding should correctly be displayed and FF should not crash.
### Actual behavior
Firefox crashes on launch when the onboarding is displayed
### Device & build information
* Device: iPhone 15 Pro (17.3). 
* Build version: v9000 (40626) 
* First seen version: v9000 (40626) 
### Notes
Please note that this issue can be reproduced also via Show Tour in settings.
Not reproducible on v9000 (40573).
Attachments: 

[Sentry](https://mozilla.sentry.io/issues/3914209929/?environment=Nightly&environment=Production&environment=production&project=6176941&query=release%3Aorg.mozilla.ios.Firefox%40124.3%2B%2840336%29&referrer=release-issue-stream)

https://github.com/mozilla-mobile/firefox-ios/assets/42831109/087ca49e-0025-4fd5-bbbc-01144394070c

[Client-2024-04-09-155204.zip](https://github.com/mozilla-mobile/firefox-ios/files/14918954/Client-2024-04-09-155204.zip)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-8921)

**Comment by data-sync-user** [comment]
➤ Nishant Bhasin commented:

Note: A~S or glean changes caused this issue which is resolved now.
