### ISSUE TITLE
[Multi-window refactor] [Felt privacy] - Incorrect theming of empty history window

### ISSUE THREAD

**Issue by DianaABarladeanu** [mozilla-mobile/firefox-ios#19787]
Steps to reproduce

1. Install FF and make sure you don't have any recorded history.
1. From private browsing---> hamburger menu--->history.
1. Observe.

Expected behavior
The empty history window with the message "Websites you've visited recently will show up here." is purple themed.

Actual behavior
The empty history window is dark grey themed.

Device & build information

* Device: iPhone 15 (17.4)
* Build version: v9000 (40735)
* First seen version: ?

Notes
Attachments: 

![8DA91701-8521-4D68-B62C-77A4063B1B73](https://github.com/mozilla-mobile/firefox-ios/assets/151131988/7caa808d-57a6-497a-b93c-ba74a315a887)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-8957)

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v9000 (46731), with iPhone 15 (17.4).

!FD48A76C-CDAC-4DD8-A2F0-CFDA6843FA04.jpg|width=944,height=2048,alt="FD48A76C-CDAC-4DD8-A2F0-CFDA6843FA04.jpg"!

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v127 (41813), with iPhone 15 (17.4).
