### ISSUE TITLE
App crashes when tapping reader view button

### ISSUE THREAD

**Issue by dragosb01** [mozilla-mobile/firefox-ios#19783]
## Logs
Issue is only reproducing when running our daily jobs on jenkins machine. 

Crash report attached taken from jenkins.

Locally, when running manually, the tests passes.

## Steps to reproduce
Open website that can be added to reader view

Tap on reader view button

### Expected behavior
The reader view mode should open

### Actual behavior
The app crashes. See attached screen recording taken from the jenkins machine.

### Device & build information
* Device: iPhone 15, iOS 17.2
* Build version: 126.0

### Notes
path to the html test report for ReadingListTests:

[https://storage.googleapis.com/mobile-reports/public/firefox-ios-M1/FullFunctionalTests/result_847/build/reports/index.html](https://storage.googleapis.com/mobile-reports/public/firefox-ios-M1/FullFunctionalTests/result_847/build/reports/index.html)
Attachments: 

[https://github.com/mozilla-mobile/firefox-ios/assets/134391433/182b109d-a927-4a2d-9309-1b91a769842f](https://github.com/mozilla-mobile/firefox-ios/assets/134391433/182b109d-a927-4a2d-9309-1b91a769842f)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-8953)

**Comment by isabelrios** [comment]
Since this issue is 100% reproducible with our automated tests and there are some new crashes related to reader view, it may be worth investigating it further. 
Even though manually we can't reproduce this crash, there might be something unveiled in the crash logs or while debugging that could give an idea to fix the other crashes.

**Comment by dragosb01** [comment]
[Crash report.pdf](https://github.com/user-attachments/files/16244946/Crash.report.pdf)

**Comment by isabelrios** [comment]
Thanks @PARAIPAN9 for taking a look at this!

**Comment by dragosb01** [comment]
Issue fixed

**Comment by data-sync-user** [comment]
➤ Dragos Bigu commented:

Issue fixed
