### ISSUE TITLE
When trying to print using web sites built in print button, Firefox crashes

### ISSUE THREAD

**Issue by jc-frosty** [mozilla-mobile/firefox-ios#19839]
## Logs
[Client-2024-04-17-091215.zip](https://github.com/mozilla-mobile/firefox-ios/files/15014784/Client-2024-04-17-091215.zip)

## Steps to reproduce
Open Firefox on iPad
Open a website that has a print button built in like:
[Link 1](https://www.nationalreview.com/corner/national-conservatism-isnt-winning/)
Or 
[Link 2](https://www.nationalreview.com/2024/04/the-coming-democratic-civil-war-over-pugnacious-hegemonic-neoliberalism/)
Click on the print button
For a few seconds a AirPrint window is opened up

### Expected behavior
An AirPrint window is opened up

### Actual behavior
For a few seconds an AirPrint window is opened up
Then Firefox crashes

### Device & build information
* Device: iPad Pro 12.9inch 4th gen v16.6.1
* Build version: Firefox 124.3 (40336)

### Notes
None

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-8986)

**Comment by data-sync-user** [comment]
➤ Norberto Andres Furlan commented:

Andrei Bodea is this intermittent or happening all the time? Thanks!

**Comment by dicarobinho** [comment]
Hi, @jc-frosty 

I did this steps and everything seems to work fine. 

May you test it again, please and see how it is working now? If the problem still be there, may you do a quick demo with it?
Thank you.

Firefox version: 126.1
iPad Air 4th Generation, iOS 17.1.1.

https://github.com/mozilla-mobile/firefox-ios/assets/61138287/4afaae2f-c6dd-436a-b528-6164d19473ba

**Comment by data-sync-user** [comment]
➤ Alexandru Farcasanu commented:

Also, move it to the QA team. Hope will get some results.

**Comment by jc-frosty** [comment]
The problem seems to be fixed.

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v127 (42213), with iPad Air 3rd gen (17.5). Wasn’t able to reproduce this issue. 

Will open a new ticket if it reappears.

!RPReplay_Final1716968417.mp4|width=720,height=960,alt="RPReplay_Final1716968417.mp4"!

!RPReplay_Final1716968371.mp4|width=720,height=960,alt="RPReplay_Final1716968371.mp4"!
