### ISSUE TITLE
Unauthorized access for http authentication prompt

### ISSUE THREAD

**Issue by dragosb01** [mozilla-mobile/firefox-ios#19912]
## Steps to reproduce
1. Acces https://jigsaw.w3.org/HTTP/Basic/
### Expected behavior
An authentication prompt should be displayed. See 126 screenshot
### Actual behavior
Unauthorized access message is displayed instead. See 127 screenshot
### Device & build information

* Device: iPhone 15, iOS 17.2
* Build version: 127.0
* First seen version: Yes
### Notes
Automation test affected: AuthenticationTest/testBasicHTTPAuthenticationPromptVisible
Attachments: 
![](https://github.com/mozilla-mobile/firefox-ios/assets/134391433/f4e8a3dd-0535-453c-bcfa-bfa8265f40f9)
![](https://github.com/mozilla-mobile/firefox-ios/assets/134391433/952ab592-c75a-4e57-a1d8-d4ca352a8b31)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-9014)

**Comment by dragosb01** [comment]
@afurlan-firefox FYI for priority

**Comment by isabelrios** [comment]
@dragosb01 do we have another site to test this? just to verify there is not an issue with the website... Thanks!

**Comment by dragosb01** [comment]
@isabelrios i coudn't find another site to test this, but the link works locally in the desktop browser, it work on 126 release app, so something changed on 127.

**Comment by clarmso** [comment]
I can reproduce the issue with https://authenticationtest.com/HTTPAuth/.

**Comment by clarmso** [comment]
Note that this issue also affects the L10n screenshot test `testWebViewAuthenticationDialog`. This test tries to take a screenshot of the basic auth dialog.

**Comment by data-sync-user** [comment]
➤ Norberto Andres Furlan commented:

Alexandru Farcasanu can you take a look to this one? Might be related with some deeplink changes.

**Comment by data-sync-user** [comment]
➤ Alexandru Farcasanu commented:

Norberto Andres Furlan after investigations, this issue was introduced with this PR https://github.com/mozilla-mobile/firefox-ios/pull/19780 ( https://github.com/mozilla-mobile/firefox-ios/pull/19780|smart-link ) . Going to find a fix for it.

**Comment by data-sync-user** [comment]
➤ Norberto Andres Furlan commented:

Alexandru Farcasanu Can you backport to 126 after it is reviewed? Thanks

**Comment by data-sync-user** [comment]
➤ Dragos Bigu commented:

Verified in 127, issue fixed.
