### ISSUE TITLE
Print 

### ISSUE THREAD

**Issue by usego1** [mozilla-mobile/firefox-ios#19911]
## Steps to reproduce
Any website send me a pdf for print !! But no possibility to print in FF for IOS newst version !!!! Safari no problem to print the same pdf !!! BUG??? :ant: shame on FF !!!:rage::rage::rage:

### Device & build information
* Device: ? 
* Build version: ? 
* First seen version: ? 
### Notes
Attachments: 

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-9013)

**Comment by data-sync-user** [comment]
➤ Norberto Andres Furlan commented:

Hi! Thanks for reporting this. We don’t have the option to print inside directly on our menu (hamburger menu), but if you tap “Share”, you will be able to Print the website.
