### ISSUE TITLE
Wrong coloring of secondary buttons in dark mode

### ISSUE THREAD

**Issue by DianaABarladeanu** [mozilla-mobile/firefox-ios#19948]
**Steps to reproduce**

1. Set theming to dark from iOS settings, install and open FF.
1. Observe the onboarding tour.
1. From hamburger menu, go to "sync and save data" and observe.

**Expected behavior**
The secondary buttons in dark mode have black font on light grey background.

**Actual behavior**
The secondary buttons in dark mode have white font on light grey background.

Device & build information

* Device: iPhone 15 (17.4)
* Build version: v125.2 (41035)
* First seen version: ? 

Notes
Attachments: 

![05818A7C-EAFE-4B32-A15F-9F84134BF086](https://github.com/mozilla-mobile/firefox-ios/assets/151131988/91507c68-9597-4439-892c-898819e6f853)

![61337A63-26CC-4C55-8312-E2108E0A3492](https://github.com/mozilla-mobile/firefox-ios/assets/151131988/2eb032f7-2461-4a24-973f-e39ff45f4fa6)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-9032)

**Comment by abodea** [comment]
Reproducible on v125.3 (41348).

**Comment by data-sync-user** [comment]
➤ Roux Buciu commented:

So, I tested this on main and it’s not reproducible. I also tested on 126.0 (41303) as well as nightly and it’s not reproducible there either.

What I’m pretty sure happened is that when we were doing backports for customization, Matt’s very large theme PR landed, and there were a ton of conflicts between main and 125 backports relating to theme issues. In trying to fix backport conflicts, something there probably got messed up.

Norberto Andres Furlan what’s the priority of fixing this? Do we need a hotfix ? Do we wait till 126 goes out? If we need a hotfix, I can probably figure out what’s happening within a day; but that’s a 125 only fix, not a main fix so we’ll have divergence there.

**Comment by data-sync-user** [comment]
➤ Norberto Andres Furlan commented:

Andrei Bodea can you tell me the impact of this? What other screens are we impacting? We are two weeks to 126, so it is a lot of time if this is affecting all secondary buttons.

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Hi there, the screens that this issue is reproducible are the same as the attachments: On the onboarding and the Settings>Synchronise and Save Data for use email instead. 

v125.2 and v125.3 but not reproducible on v126.

**Comment by data-sync-user** [comment]
➤ Roux Buciu commented:

Norberto Andres Furlan what’s happening with this ticket? Do I put it in closed?

**Comment by data-sync-user** [comment]
➤ Roux Buciu commented:

No one has replied here, so, given that the last comment is that it’s not reproducible on 126 or above, I’mma mark it as closed for now.
