### ISSUE TITLE
Incorrect redirect to default browser instead of native app

### ISSUE THREAD

**Issue by DianaABarladeanu** [mozilla-mobile/firefox-ios#20016]
**Steps to reproduce**

1. Make sure Chrome is the device default browser and that amazon app is installed.
1. Install FF-->open amazon.com-->go to a product page.
1. From hamburger menu-->tap on Share-->find products on Amazon-->choose to open in Amazon app when prompted.
1. Observe

**Expected behavior**
The user is redirected to amazon app.

**Actual behavior**
The user is redirected to default browser page, in this case, to Chrome.

**Device & build information**

* Device: iphone 15 (17.4)
* Build version: v126 (41124)
* First seen version: ? 

Notes
Attachments: 

https://github.com/mozilla-mobile/firefox-ios/assets/151131988/ce3685e6-2c45-442d-b10e-2ba38caa07c3

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-9051)

**Comment by afurlan-firefox** [comment]
@DianaABarladeanu this is not Firefox problem.
