### ISSUE TITLE
After pressing home button, old tab name still appears

### ISSUE THREAD

**Issue by FormularSumo** [mozilla-mobile/firefox-ios#20148]
## Steps to reproduce
Press the home button on an active tab
Press on the tabs button to see open tabs

### Expected behavior
The tab which I pressed home on now says "start page" or similar

### Actual behavior
The tab which I pressed home on now still says the name of the previous website that was open

### Device & build information
* Device: iPhone 13, iOS 17.5 beta 4
* Build version: 125.2 (41035)
* First seen version: At least 2 years ago, not sure what version
### Notes
Attachments: [test.webm](https://github.com/mozilla-mobile/firefox-ios/assets/36278229/7f8fb6bf-09ca-4fe8-b3b7-d769fa03709c)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-9089)

**Comment by data-sync-user** [comment]
➤ Norberto Andres Furlan commented:

Sophie Amin can you take a look to this one and see if it is related to tab tray? It is happening even with the experiment disabled. Thanks!

**Comment by data-sync-user** [comment]
➤ Sophie Amin commented:

Norberto Andres Furlan I’ll take a look!

**Comment by data-sync-user** [comment]
➤ Sophie Amin commented:

Norberto Andres Furlan Looks like this one was probably happening even before the tab tray refactor - I can take this and try and fix it

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v9000 (42224), with iPhone 15 (17.4.1), tested both with and without tab tray refactor enabled.

!RPReplay_Final1716812549.mp4|width=590,height=1280,alt="RPReplay_Final1716812549.mp4"!

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v126.2 (42205), with iPhone 15 (17.4).

**Comment by FormularSumo** [comment]
The fix has now rolled out to stable it seems as the issue is gone for me, thanks for looking into!
