### ISSUE TITLE
Products recommended by Firefox are not visible in Fakespot  anymore 

### ISSUE THREAD

**Issue by alinamoldovan84** [mozilla-mobile/firefox-ios#20177]
## Steps to reproduce
1. Check for an amazon product having a Product recommended by firefox associated: https://www.amazon.com/MINOSYS-Computer-Desk-Monitors-Adjustable/dp/B0BYSDSR3K
1. Open the Fakespot review drawer and check for the Product recommended by Firefox
1. Go to settings and enable /disable the ads 
 
### Expected behavior
The Product recommended by Firefox is visible 
### Actual behavior
The Product recommended by Firefox is not visible 
### Device & build information

* Device: iPhone 15+(17.4.1), iPad Air 3rd Gen (17.5)  
* Build version: 126 (41600) 
* First seen version: ? 
### Notes
Attachments: 

https://github.com/mozilla-mobile/firefox-ios/assets/124251579/d67b7dbe-626f-4a62-b714-24a57a2ca289

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-9099)

**Comment by data-sync-user** [comment]
➤ Norberto Andres Furlan commented:

Experiment will be disabled after SUMO articles get updated.
