### ISSUE TITLE
Browsing history doesn't seem to be considered in address bar suggestions

### ISSUE THREAD

**Issue by jens-siebert** [mozilla-mobile/firefox-ios#20255]
## Steps to reproduce
- visit some projects/repos on Github
- open a new tab and start to enter "github.com" in the address bar

### Expected behavior
previously visited Github repos should appear in the address bar suggestions (as in the desktop version, see screenshot)

### Actual behavior
only the base URL is being shown in the address bar suggestions (see screenshot)

### Device & build information
* Device: iPhone 15 Pro Max, iOS 17.5
* Build version: 126.0 (41677)
* First seen version: 125.3 (probably also in earlier versions, just returned from Vivaldi with 125.3 😉) 

### Notes

Attachments: 

Suggestions as shown in the desktop version of Firefox (126.0)
![Bildschirmfoto 2024-05-14 um 18 00 38](https://github.com/mozilla-mobile/firefox-ios/assets/143868460/5ec67dd5-eb24-4679-9668-ce55407b833c)

Suggestions as shown in the iOS version of Firefox (125.x/ 126.0)
![IMG_2749](https://github.com/mozilla-mobile/firefox-ios/assets/143868460/07289f2a-9ca8-4822-aa6b-97e97411a3e6)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-9143)

**Comment by nbhasin2** [comment]
Hi, @jens-siebert could I request a small test and see if that works. 
When you visit a few websites and the links along with the name doesn't show up in autocompletion for url bar could you completely close the app i.e. swipe up and launch the app again. 

Please try this and let me know if you see the results like desktop on Firefox iOS

Thanks

**Comment by jens-siebert** [comment]
Hey @nbhasin2,

I visited the following URLs:

https://github.com/mozilla-mobile/firefox-ios
https://github.com/system76/firmware-open/
https://github.com/alire-project/alire

After this, I've visited another website and the started typing 'gith' in the address bar again but only the base URL is shown in the suggestions (like in the screenshot of the app above).

The behaviour is the same after restarting the app.

**Comment by jens-siebert** [comment]
@nbhasin2 this seems to be fixed with 126.2! Closing this issue... Thanks!

**Comment by data-sync-user** [comment]
➤ Norberto Andres Furlan commented:

Nishant Bhasin to reach out to Lina to see status on unified search.
