### ISSUE TITLE
Remove support for {moz:locale} parameter replacements in search URLs

### ISSUE THREAD

**Issue by Standard8** [mozilla-mobile/firefox-ios#20261]
In [bug 1836804](https://bugzilla.mozilla.org/show_bug.cgi?id=1836804) we have removed support for the `{moz:locale}` parameter replacement in search URLs. The only case of it being used was Bing, [which no longer needs it](https://bugzilla.mozilla.org/show_bug.cgi?id=1836803).

Hence we should remove support on iOS as well.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-9146)

**Comment by Standard8** [comment]
@cyndichin should I close this issue now that the PR is merged, or is there another step first?

**Comment by cyndichin** [comment]
@Standard8 thanks for following up! I moved it over to QA to do a sanity check on the search. Once they check this, then they'll move the ticket to verified, which should automatically close this issue.

**Comment by data-sync-user** [comment]
➤ Adina Petridean commented:

Verified as fixed on v9000(42096) with a sanity check on search. Device used: iPhone 14 Pro Max (iOS 16.2).

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Validated on v128 (42870), with iPhone 15 (17.5).
