### ISSUE TITLE
New private tab is forgotten if I first switch to a non-private tab

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/firefox-ios#20279]
## Steps to reproduce

1. Open two regular, non-private web pages. 
2. Long press on a link on one of those page and select “Open in New Private Tab”, _but do not switch to that new private tab yet_!
3. Open the tab tray view and switch to the other **non-private** tab.
4. Open the tab tray again and switch to its private tab view. 

### Expected behavior

The private tab we opened in the background should be listed. 

### Actual behavior

The private tab we opened in the background _is not_ listed.

Switching to a non-private before switching to the new private tab causes Firefox to forget about the new private tab. 

### Device & build information

* Device: iPhone 15 Plus running iOS 17.4.1
* Build version: 9000 (41885)
* First seen version: I can reproduce this bug in all the TestFlight Nightly builds available on my phone, back to 9000 (38873). I can also reproduce in the TestFlight Beta version 125, but I _can’t_ reproduce in the regular App Store version 125.3.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-9154)

**Comment by nbhasin2** [comment]
I tried it on v126.1 and was seeing the new tab in the private tab tray. @cpeterso are you still seeing this in the newer version?

**Comment by cpeterso** [comment]
> First seen version: I can reproduce this bug in all the TestFlight Nightly builds available on my phone, back to 9000 (38873). I can also reproduce in the TestFlight Beta version 125, but I can’t reproduce in the regular App Store version 125.3.

@nbhasin2: Are you testing TestFlight Beta v126.1 or the App Store's v126.1?

I can reproduce in TestFlight Beta v126.0 (41677) and TestFlight Nightly 9000 (42142), but not the App Store's v126.1 (41973). There seems to be some difference between the TestFlight Beta and Nightly builds and the App Store builds.

**Comment by data-sync-user** [comment]
➤ Alina Moldovan commented:

Validated this issue using all above:

**Comment by data-sync-user** [comment]
➤ Chris Peterson commented:

AFAICT, your video shows the same steps that I use to reproduce, but I can still reproduce in v9000 (42376). I don’t know what I’m doing differently. Since you can’t reproduce in v127 or v9000 and I can’t reproduce in v127 from the App Store, maybe my v9000 profile has some different settings or an experiment?

**Comment by data-sync-user** [comment]
➤ Alexandru Farcasanu commented:

I picked up this ticket and investigated it but I can’t even reproduce it.

Chris Peterson may you compare your profile settings, for both? Unlikely to be this thing the issue but will see. Thank you in advance.

**Comment by cpeterso** [comment]
Good news! I can no longer reproduce this bug. I bisected the fix to TestFlight build 42407.

**Comment by data-sync-user** [comment]
➤ Alexandru Farcasanu commented:

Chris Peterson awesome! Happy to see that! Thank you!

Also, based on the Alina Moldovan comment, we can close this ticket as already fixed.

cc: Norberto Andres Furlan
