### ISSUE TITLE
x.com website loading glitch after FF update

### ISSUE THREAD

**Issue by DianaABarladeanu** [mozilla-mobile/firefox-ios#20319]
**Steps to reproduce**

1. Make sure you have installed 126.0(41677) FF build.
1. Go to x.com and set the "strict" tracking protection option --> the website doesn't load.
1. Update to 126.1 (41973) build and observe.

**Expected behavior**
x.com website loads instantly.

**Actual behavior**
x.com website doesn't load instantly, only after refresh.

**Device & build information**

* Device: iPad Air 3rd gen (17.5)
* Build version: v126.1 (41973)
* First seen version: ? 
Notes
Attachments: 

https://github.com/mozilla-mobile/firefox-ios/assets/151131988/d9296326-0b4c-4c4c-bffc-c535e9d27932

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-9173)

**Comment by data-sync-user** [comment]
➤ Nishant Bhasin commented:

Razvan Litianu this is the same bug we discussed, we sync up tomorrow to look into it. Just assigning you as an FYI

**Comment by data-sync-user** [comment]
➤ Nishant Bhasin commented:

https://github.com/mozilla-mobile/firefox-ios/pull/20423 ( https://github.com/mozilla-mobile/firefox-ios/pull/20423|smart-link ) 

The steps have been added to the PR 

My steps

    Open Firefox v126
    Go to x.com
    Enable strict mode
    Close and upgrade to the nightly version or the next Firefox v12x with your commit
    Open Firefox and expect x.com to work

**Comment by data-sync-user** [comment]
➤ Alina Moldovan commented:

Validated this issue using the latest v9000 version (42376). The issue still reproduces.  

Steps: 

  1. Fresh install an older version of v9000 (to ensure the x.com ( http://c.com ) page is not loaded) - used v9000 (40331) build 
  2. Set ETP to strict  t
  3. Tried to load x.com ( http://x.com ) => page is not loaded 
  4. Upgraded the FF version to the latest version v9000 (42376).

Result: The page is not reloaded until the refresh page is tapped 

!Skype_Video5.mp4|width=41.66666666666667%,alt="Skype_Video5.mp4"!

**Comment by data-sync-user** [comment]
➤ Nishant Bhasin commented:

Alina Moldovan, could you please test with the new nightly that came out yesterday

**Comment by data-sync-user** [comment]
➤ Alina Moldovan commented:

Validated as fixed using v9000 (42632) using iPhone 14+ (16.0.3), iPhone 15+ (17.4.1) &iPad Pro 4th Gen (17.2). 

Not able to reproduce this issue anymore. 

!Skype_Video9.mp4|width=41.666666666666664%,alt="Skype_Video9.mp4"!

**Comment by data-sync-user** [comment]
➤ Alina Moldovan commented:

Validated this issue using FF v128 (42648). 

!IMG_0748.MOV|width=41.66666666666667%,alt="IMG_0748.MOV"!
