### ISSUE TITLE
[Focus] `www.x.com` doesn't work on Focus after updating to `v126.1 (41979)`

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/firefox-ios#20320]
# Prerequisites 
Make sure that the `Social` option is enabled in the ETP menu.

## Steps to reproduce
1. Install v126.0 (41601).
1. Open Focus and access `www.x.com`.
1. Observe that `Something went wrong` error is displayed.
1. Update Focus to v126.1 (41979).
1. Open Focus and check (the Social option should still be on, on the ETP menu)
1. Access `www.x.com`.
### Expected behavior
`www.x.com` should work without problems after the update.
### Actual behavior
`www.x.com` doesn't work on Focus after the update as the `Something went wrong` error is displayed.
### Device & build information

* Device: iPhone 13 Pro (15.7.1), iPhone 15 Pro (17.4.1) 
* Build version: v126.0 (41601)-v126.1 (41979). 
* First seen version: N/A 
### Notes
Please note that this issue cannot be reproduced on a fresh install for Focus on v126.1 (41979).
Attachments: 

https://github.com/mozilla-mobile/firefox-ios/assets/42831109/0ac819de-513e-4826-9551-fed2b69f00fe

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-9172)

**Comment by data-sync-user** [comment]
➤ Nishant Bhasin commented:

cc Razvan Litianu

**Comment by abodea** [comment]
Reproducible on v127 (42449) too.

**Comment by data-sync-user** [comment]
➤ Razvan Litianu commented:

Follow-up update, it seems there’s no update rule mechanism for Focus. I’ll check further

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Verified as fixed on v128 (42664) with iPhone 15 Pro (17.5.1).

Please note that I did update from v126 (41601) to v128 (42664) without issues.
