### ISSUE TITLE
[Tab tray refactor] "Tab closed - Undo"  toast message glitch (intermittent)

### ISSUE THREAD

**Issue by DianaABarladeanu** [mozilla-mobile/firefox-ios#20340]
Steps to reproduce

1. Make sure you have some tabs in tab tray.
1. Long tap on a tab to open context menu.
1. Choose to close the tab and observe the toast message.

Expected behavior
"Tab closed - Undo" toast message is displayed once.

Actual behavior
"Tab closed - Undo" toast message seems to be doubled/has a glitch in some cases.

Device & build information

* Device: iPhone 15 (17.4); iPhone 15+ (17.4)
* Build version: v127 (42000)
* First seen version: ? 

Notes
Attachments: 
https://github.com/mozilla-mobile/firefox-ios/assets/151131988/b6576308-6314-44a5-96c1-59843ce7150a

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-9180)

**Comment by tisumi99** [comment]
The toast message is indeed being called twice.  Most of the time the duplicates appear simulataneously and we don't see the duplicates but every once in a while there is a short delay between the duplicates and we see the glitch.  I will submit a PR/fix for this shortly.

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v9000 (42506), with iPhone 15 (17.4.1).

!RPReplay_Final1717585546.mp4|width=590,height=1280,alt="RPReplay_Final1717585546.mp4"!

**Comment by data-sync-user** [comment]
➤ Adina Petridean commented:

Verified as fixed on Firefox 128.0 (42711), with iPhone 14 Pro Max (16.2).
