### ISSUE TITLE
Suggestion to move bootstrap.sh to the correct directory or Update README.md

### ISSUE THREAD

**Issue by stevenbertolucci** [mozilla-mobile/firefox-ios#20348]
While building the code, I ran into an error that prevented me from running bootstrap.sh in the firefox-ios directory. When I `cd` into `firefox-ios` and ran the command `sh ./bootstrap.sh`, that file doesn't exist in firefox-ios sub-directory. I got a 'file doesn't exist' error. It turns out the file exists in the parent (or root) directory. I would like to suggest moving bootstrap.sh into the firefox-ios sub-directory.

Another suggestion if bootstrap.sh shouldn't be moving to firefox-ios sub-directory, is to update README.md to remove the `cd firefox-ios`:

![github](https://github.com/mozilla-mobile/firefox-ios/assets/13703308/6e0729f9-7237-4837-9d4f-3253f46794f0)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-9187)

**Comment by data-sync-user** [comment]
➤ Nishant Bhasin commented:

cc Sophie Amin // Cyndi Chin tbd for who to pic
