### ISSUE TITLE
[iPad Multi-Window] - Request desktop/mobile site setting doesn't apply to both windows

### ISSUE THREAD

**Issue by DianaABarladeanu** [mozilla-mobile/firefox-ios#20439]
**Steps to reproduce**

1. Launch FF and open two FF windows with split-view.
1. Open the same website on both windows.
1. On the first window, tap on "request mobile site" from hamburger menu. 

**Expected behavior**
The webpages from both windows reload in mobile site mode.

**Actual behavior**
Only the active webpage reloads in mobile site mode.

**Device & build information**

* Device: iPad Air 3rd gen (17.5)
* Build version: v9000 (42263)
* First seen version: ? 
 
Notes
Attachments: 

https://github.com/mozilla-mobile/firefox-ios/assets/151131988/15b06914-3b7b-49f4-a593-19f5bfb45411

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-9225)

**Comment by data-sync-user** [comment]
➤ Matt Reagan commented:

This is expected (at least for now). We generally treat each window independently for most of the browser-specific settings, including mobile vs desktop. This could be something we revisit to change the treatment but it would probably need to happen post-MVP. Closing for now but if anyone has concerns/questions LMK. Thank you

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

As it might be worked on later, setting this issue to open based on the comment below.

**Comment by data-sync-user** [comment]
➤ Matt Reagan commented:

Andrei Bodea This is not a defect and we have no plans currently to change it, so we should close this ticket. If we ever do revisit this we’d be filing dev tasks on the next epic to track the work there.
