### ISSUE TITLE
Decrease Spacing between site title and URL on TwoLineImageOverlayCell

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#20512]
The space between the title and the URL is visually too far apart. Design has requested we decrease the spacing.

![Screenshot 2024-05-31 at 4 33 41 PM](https://github.com/mozilla-mobile/firefox-ios/assets/5545720/808515e2-97e3-43a6-bf9a-e0e2bafadc3e)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-9265)

**Comment by dataports** [comment]
@tisumi99 Feel free to pick up this issue!

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Validated on v9000 (43238), with iPhone 15 (17.5).

!ImportedPhoto.741793991.247873.jpeg|width=1179,height=2556,alt="ImportedPhoto.741793991.247873.jpeg"!

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Validated on v129 (43512), with iPhone 15 (17.5).
