### ISSUE TITLE
[iPad Multi-Window] - Opening a new website via drag and drop URL doesn't open a new tab [Slide over mode]

### ISSUE THREAD

**Issue by DianaABarladeanu** [mozilla-mobile/firefox-ios#20526]
**Steps to reproduce**
1. Launch FF and go into slide over mode.
2. On window 1 open any website and then go to the homepage.
3. On window 2 (tap to become active) open any website then drag and drop the URL to window 1.

**Expected behavior**
On Window 1 there should be a new tab opened with the new URL.

**Actual behavior**
Opening a new website via drag and drop URL doesn't open a new tab.

**Device & build information**
* Device: iPad Air 3rd gen (17.5)
* Build version: v9000 (42407)
* First seen version: ? 

Notes
Attachments: 

https://github.com/mozilla-mobile/firefox-ios/assets/151131988/63c812e4-3839-479f-bf9d-d0cb83541266

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-9271)

**Comment by data-sync-user** [comment]
➤ Matt Reagan commented:

Dup of https://mozilla-hub.atlassian.net/browse/FXIOS-9223 ( https://mozilla-hub.atlassian.net/browse/FXIOS-9223|smart-link )
