### ISSUE TITLE
Multywinddow

### ISSUE THREAD

**Issue by jozimastar** [mozilla-mobile/firefox-ios#20553]
![IMG!UNITO-UNDERSCORE!0342](https://github.com/mozilla-mobile/firefox-ios/assets/97891289/2ceca222-7b41-4d13-9722-08a75d7f8ebc)

### User Problem
> can’t open 2 Firefox windows side by side in the same time in iPadOS 17.5 , it makes it very hard to transfer big amount of data and requires to use other browsers which get complicated quickly 

### Ideas for Solution
>  make an option for this feature to support iPadOS

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-9279)

**Comment by data-sync-user** [comment]
➤ Norberto Andres Furlan commented:

Hi! This feature is coming soon (Around FX 128).
