### ISSUE TITLE
Update close button on bottom sheets (light mode only)

### ISSUE THREAD

**Issue by cwzilla** [mozilla-mobile/firefox-ios#20593]
Hi team,

I'm looking to update the close button icon that's currently used on bottom sheets in light mode.
What's changed is the circular background is darker to accommodate for the new bottom sheet background color (`layer3`).

Please see the attached file for the new asset.

Thanks!

[crossCircleFillExtraLargeLight.pdf](https://github.com/user-attachments/files/15744300/crossCircleFillExtraLargeLight.pdf)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-9302)

**Comment by data-sync-user** [comment]
➤ Tushar Chitnavis commented:

Please verify that close button image is darker on onboarding, microsurvey or any view which has close button.
For reference:

!Screenshot 2024-06-17 at 5.26.42 PM.png|width=754,height=655,alt="Screenshot 2024-06-17 at 5.26.42 PM.png"!

Thank you!

**Comment by data-sync-user** [comment]
➤ Crystal Wong commented:

Tushar Chitnavis Looks great, thanks!

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Validated on v128 (43061), with iPhone 15 (17.4).
