### ISSUE TITLE
Copy option is missing from share menu

### ISSUE THREAD

**Issue by dragosb01** [mozilla-mobile/firefox-ios#20649]
## Steps to reproduce
Run automation test: XCUITests/DownloadsTests#testShareDownloadedFile
or
Follow the steps from this TC:
https://testrail.stage.mozaws.net/index.php?/cases/view/2306901
### Expected behavior
Copy should be available as an option 
### Actual behavior
Copy option is missing from share menu. See attached screenshots. One taken from main, one from 128.

### Device & build information
* Device:  iPhone 15, iOS 17.5 simulator
* Build version:  129.0
* First seen version: Yes
### Notes
Attachments: 
<img width="391" alt="Screenshot 2024-06-14 at 09 51 58" src="https://github.com/mozilla-mobile/firefox-ios/assets/134391433/46a87199-03ba-4d14-a4d7-e02269b5194b">
<img width="384" alt="Screenshot 2024-06-14 at 10 11 07" src="https://github.com/mozilla-mobile/firefox-ios/assets/134391433/be0581f6-7e6c-4043-bd27-95ab01151a52">

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-9320)

**Comment by dragosb01** [comment]
Automation tests affected: testShareDownloadedFile, testLongPressOnDownloadedFile

**Comment by dragosb01** [comment]
Issue fixed, closing ticket.

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v130 (44347), with iPhone 15 (17.5).

!ImportedPhoto.745145881.798978.jpeg|width=1179,height=2556,alt="ImportedPhoto.745145881.798978.jpeg"!
