### ISSUE TITLE
Switch ownership of some glean metrics

### ISSUE THREAD

**Issue by tarikeshaq** [mozilla-mobile/firefox-ios#20642]
There are a few glean metrics owned by me, but as I offboard those should be switched over. I'm switching them over mhammond

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-9317)

**Comment by data-sync-user** [comment]
➤ Laurie Marceau commented:

Closing since PR was merged a while ago
