### ISSUE TITLE
Display buttons in settings centered

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#20668]
![IMG!UNITO-UNDERSCORE!0028](https://github.com/mozilla-mobile/firefox-ios/assets/4530/5c09f611-46b3-470d-9b38-196c2528f550)

![IMG!UNITO-UNDERSCORE!0035](https://github.com/mozilla-mobile/firefox-ios/assets/4530/4ebbb28b-902d-41a6-b404-2ca033ce8e73)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-9334)

**Comment by data-sync-user** [comment]
➤ Winnie Teichmann commented:

Alexandru Farcasanu yes, the label is aligned to center but the cell content is not displayed centered. And yes, there are a places in our settings where the button label is not displayed centered with large dynamic type. All of these should be fixed in this task.

**Comment by anna-yeddi** [comment]
Marking it as `access-S4` because the inconsistency may affect users with cognitive disabilities. Thank you for reporting it!

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Validated on v9000 (43308), with iPhone 15 (17.5).

!ImportedPhoto.742113786.348243.jpeg|width=1179,height=2556,alt="ImportedPhoto.742113786.348243.jpeg"!

!ImportedPhoto.742113786.347333.jpeg|width=1179,height=2556,alt="ImportedPhoto.742113786.347333.jpeg"!

!ImportedPhoto.742113786.345991.jpeg|width=1179,height=2556,alt="ImportedPhoto.742113786.345991.jpeg"!

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Validated on v129 (43415), with iPhone 15 (17.5).
