### ISSUE TITLE
[Tab tray refactor] UI glitch then moving the tab position in tab tray

### ISSUE THREAD

**Issue by alinamoldovan84** [mozilla-mobile/firefox-ios#20702]
## Steps to reproduce
1. Make sure you have several tabs in the tab tray.
1. Switch the position of a tab and observe.

### Expected behavior
The tabs switch positions with no issue. The thumbnails load correctly.

### Actual behavior
Sometimes the thumbnails blink for a short period

### Device & build information
* Device: iPhone 15+ (17.4.1), iPad Pro 4th Gen (17.2)  
* Build version: 127.1 (42781) 
* First seen version: ? 
    1. Notes
Attachments: 

https://github.com/mozilla-mobile/firefox-ios/assets/124251579/f4be6377-01b1-4ee8-87b3-c60ac29597fe

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-9348)

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v9000 (46854), with iPhone 15 (17.6)

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v133 (47343), with iPhone 16 (18.1)
