### ISSUE TITLE
Shortcuts are incorrectly displayed on homepage when switching from landscape to portrait mode

### ISSUE THREAD

**Issue by alinamoldovan84** [mozilla-mobile/firefox-ios#20703]
## Steps to reproduce
1. Make sure you have a long list of shortcuts set to be displayed on 2 rows 
2. Switch the device to landscape mode
3. Switch the device from landscape mode to portrait mode
4. Check the shortcuts list

### Expected behavior
Shortcuts are displayed on 2 rows 

### Actual behavior
Shortcuts are displayed on 4 rows 

### Device & build information
* Device: 15+ (17.4.1), iPad Pro 4th Gen (17.2) 
* Build version: 127.1 (42781) 
* First seen version: ? 
### Notes
Attachments: 

https://github.com/mozilla-mobile/firefox-ios/assets/124251579/d04aaf75-65a3-4135-b751-b59f088affda

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-9347)

**Comment by data-sync-user** [comment]
➤ Matt Lichtenstein commented:

In the video, there also seems to be some extra spacing added between Shortcuts and Jump Back In. Maybe related

**Comment by data-sync-user** [comment]
➤ Matt Lichtenstein commented:

I can consistently reproduce on V127.1 but am unable to reproduce on v129. Alina Moldovan are you able to repro on v129?
