### ISSUE TITLE
Login to Firefox Sync account not working with uninformative error message.

### ISSUE THREAD

**Issue by ErikSchliep** [mozilla-mobile/firefox-ios#20715]
## Steps to reproduce

- Use firefox on iOS / iPhone
- Go to menu
- Select username
- Select manage account
- Follow login routine
  - Use 1Password to auto fill username and password
  - Paste 2FA code from clipboard (1P put it there automatically)
- Getting stuck at 2FA code entry

### Expected behavior

- Getting successfully logged in

### Actual behavior

- Not getting logged in with error messages (see screenshot below)

### Device & build information
* Device: ? iPhone 14 Pro / iOS 17.5.1
* Build version: ? Firefox 127.0 (42448)
* First seen version: ? Firefox 127.0 (42448)
### Notes
Attachments: 

![IMG_0702](https://github.com/mozilla-mobile/firefox-ios/assets/30728716/72e5837d-bc36-44ae-83fa-4abaa031ffb0)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-9354)

**Comment by afurlan-firefox** [comment]
Hi @ErikSchliep! Thanks for reporting this. Is this happening on accounts.firefox.com? or in a staging site? Can you share a video if possible?

**Comment by data-sync-user** [comment]
➤ Norberto Andres Furlan commented:

Andrei Bodea can you try to reproduce? Thanks!

**Comment by ErikSchliep** [comment]
> Hi @ErikSchliep! Thanks for reporting this. Is this happening on accounts.firefox.com? or in a staging site? Can you share a video if possible?

Sure, here is a video. For some reason, the keyboard isn't recorded in all ocasions and since I was now logged in via the QR Code, I had to log-out first. But from that point on, it's pretty much the same workflow as described above.

https://github.com/mozilla-mobile/firefox-ios/assets/30728716/35798916-cd3e-4720-8e4b-e01e57b90fba

**Comment by Tomatoshadow2** [comment]
Also occurs on Firefox beta iOS version 128.0 (42823)

**Comment by data-sync-user** [comment]
➤ Norberto Andres Furlan commented:

Hi! The problem was identified and solved. I will land in production on June 26th. Thanks!

**Comment by afurlan-firefox** [comment]
@ErikSchliep if you sign our from the browser and sign in again, you shouldn't see the error again. Can you confirm? Thanks!

**Comment by ErikSchliep** [comment]
> @ErikSchliep if you sign out from the browser and sign in again, you shouldn't see the error again. Can you confirm? Thanks!

Yes, I can confirm it works like a charm now. Thanks!

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v128 (43061), with iPhone 15 (17.4).
