### ISSUE TITLE
[iPad Multi-Window] "Jump Back In" section is not synchronized between multiple windows 

### ISSUE THREAD

**Issue by alinamoldovan84** [mozilla-mobile/firefox-ios#20718]
## Steps to reproduce
1. Have at least 2 open FF windows 
2. Window1: open a website 
3. Window1: Open the homepage and check the "Jump Back In" section
4. Window2: Open the homepage and check the "Jump Back In" section

### Expected behavior
The "Jump Back In" section is synchronized between the two windows 

### Actual behavior
The "Jump Back In" section is not synchronized between the two windows 

### Device & build information
* Device: iPad Pro 4th Gen (17.2) 
* Build version: v128 (42823) 
* First seen version: ? 
### Notes
Attachments: 

https://github.com/mozilla-mobile/firefox-ios/assets/124251579/19817551-bf7f-44c9-82ae-764c3a568099

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-9356)

**Comment by data-sync-user** [comment]
➤ Matt Reagan commented:

Alina Moldovan Right now each Jump Back In view model references the individual window’s tab manager. So in other words the Jump Back In sections aren’t intended to be synchronized against a universal/app-wide set of tabs, only the tabs for the associated window for that homepage.

Let me know if that aligns with what you’re seeing if you still think there may be a bug/defect here. (cc Norberto Andres Furlan)

**Comment by data-sync-user** [comment]
➤ Alina Moldovan commented:

Closing bug as per the previous comment.
