### ISSUE TITLE
Refactor the RustRemoteTabs to directly use TabsStore instead of Tabs.swift

### ISSUE THREAD

**Issue by skhamis** [mozilla-mobile/firefox-ios#20775]
[RustRemoteTabs](https://github.com/mozilla-mobile/firefox-ios/blob/dbe87a88a4332c6b994acd9fb439ced5b1b5881f/firefox-ios/Storage/Rust/RustRemoteTabs.swift#L18) uses a wrapper for application services APIs called Tabs.swift https://github.com/mozilla/application-services/blob/main/components/tabs/ios/Tabs/Tabs.swift

It doesn't seem to do us much good and adds a layer of indirection needed for us to implement new APIs and debug issues with tabs. We should remove the wrapper and have `RustRemoteTabs` directly open the store.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-9385)

**Comment by data-sync-user** [comment]
➤ Norberto Andres Furlan commented:

Sammy Khamis can you clarify what is this affecting to see if we need to run any regression testing? Thanks!

**Comment by data-sync-user** [comment]
➤ Sammy Khamis commented:

Ideally nothing will change! This is really just removing a layer of code that, probably at the time had some extra logic, but is just a simple wrapper around the code that lives in application services. For regression testing the main feature that uses this is:

  * Tab Syncing, Remote Tabs panel (seeing tabs from iOS on other platforms, and vice-versa)

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Validated on v9000 (43308), with iPhone 15 (17.5).

No issues encountered with tab syncing or remote tabs panel feature.

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Validated on v129 (43576), with iPhone 15 (17.5).

**Comment by skhamis** [comment]
Closing as fixed and verified
