### ISSUE TITLE
[Regression] Closing all private tabs does not keep user in private browsing

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/firefox-ios#20841]
[Steps]
Go to private mode and open several tabs

[Expected]
After closing all tabs user is in the Tab Tray view, within Private mode

[Actual]
After closing all tabs user is in homescreen in regular mode

This started to happen in main branch on Jun. 28th after this commit: e772acadc35e2592492db1bb5dc62f7679edc822

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-9411)

**Comment by data-sync-user** [comment]
➤ Sophie Amin commented:

Fixed here: https://github.com/mozilla-mobile/firefox-ios/pull/20845 ( https://github.com/mozilla-mobile/firefox-ios/pull/20845|smart-link )

**Comment by isabelrios** [comment]
Automated test failing due to the issue: [testCloseAllTabsPrivateMode](https://github.com/mozilla-mobile/firefox-ios/blob/bd589c194fbb5f16bc3748a276762f92b0ce4185/firefox-ios/firefox-ios-tests/Tests/XCUITests/TopTabsTest.swift#L173)

**Comment by isabelrios** [comment]
Closing this issue for now because the PR causing the failure was reverted. Ticket to update the test is already in place for mobile test eng team

**Comment by data-sync-user** [comment]
➤ Adina Petridean commented:

Verified as fixed on v9000(43298) with iPhone 14 Pro Max (iOS 16.2).

!PB.mp4|width=886,height=1920,alt="PB.mp4"!

**Comment by riddlerboss248** [comment]
This issue still persists when a user close tabs by long pressing the tab icon.

When closing out the last tab in private mode but long pressing it will not keep user in private mode. This also contributes to the “jump back in” section on the home page stops working. It’s like it’s stuck in between private mode and non private mode.
