### ISSUE TITLE
Weird display of "Addresses" section - no address is displayed

### ISSUE THREAD

**Issue by DianaABarladeanu** [mozilla-mobile/firefox-ios#20864]
**Steps to reproduce**

1. Install FF, login with a valid account that has some saved addresses.
1. Go to the addresses section and observe.

**Expected behavior**
The addresses section is correctly displayed, the saved addresses are listed.

**Actual behavior**
The addresses are not displayed, the "save and fill addresses" string is positioned at the center of the page.

**Device & build information**

* Device: iPhone 15 (17.4), iPad Air 3rd gen (17.5).
* Build version: v9000 (43147)
* First seen version: ?
 
Notes
Attachments: 

https://github.com/mozilla-mobile/firefox-ios/assets/151131988/6bcc25ac-75f4-4a37-a579-4481176b3c10

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-9423)

**Comment by data-sync-user** [comment]
➤ Matt Lichtenstein commented:

Noticed that this only seems to happen when using the Firefox Beta scheme since this commit ( https://github.com/mozilla-mobile/firefox-ios/commit/464b520d2e3d2b9036f70f501167ab808ae36c4f )

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v129 (43631), with iPhone 15 (17.5).
