### ISSUE TITLE
[regression] Homepage is rendered as a white or gray page after switching tabs

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/firefox-ios#20892]
## Steps to reproduce

1. Install and run a TestFlight Nightly build.
2. Open a new homepage tab.
3. Switch to another tab (or open a second tab if you had no other tabs opened).
4. Switch back to the homepage tab from step 2.

### Expected behavior

Firefox should display the homepage.

### Actual behavior

The homepage is rendered as a white or gray page.

### Device & build information
* Device: iPhone 15 Plus running iOS 17.5.1
* Build version: I'm currently running TestFlight Nightly build 9000 (43203).
* First seen version: **This bug is a regression in TestFlight Nightly build 9000 (94991).** The previous TestFlight Nightly build, 9000 (42953), displays the homepage correctly.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-9440)

**Comment by cpeterso** [comment]
Here is a screenshot:

![image](https://github.com/mozilla-mobile/firefox-ios/assets/629193/333dbc32-0d19-4587-b416-a937796f80ea)

**Comment by data-sync-user** [comment]
➤ Norberto Andres Furlan commented:

Andrei Bodea this issue should be fixed. Can you confirm?

**Comment by cpeterso** [comment]
I can’t reproduce this bug in build 9000 (43470). 👍

**Comment by cpeterso** [comment]
This bug was fixed in build 9000 (43238).

**Comment by data-sync-user** [comment]
➤ Adina Petridean commented:

Verified as fixed on v9000(43516) with iPhone 14 Pro Max (iOS 16.2).

**Comment by data-sync-user** [comment]
➤ Adina Petridean commented:

Verified as fixed on Firefox 132.0(46208) with iPhone 14 Pro Max (iOS 16.2).
