### ISSUE TITLE
[Access][Dynamic text] "Continue" button is not scaled correctly in Password Manager Onboarding screen 

### ISSUE THREAD

**Issue by alinamoldovan84** [mozilla-mobile/firefox-ios#20909]
## Steps to reproduce
1. Make sure the device is set to use Larger Text set to the max size 
1. Fresh install the FF app 
1. Navigate to Settings -> Passwords 
1. Check the Manager Onboarding screen 

### Expected behavior
All elements of the  Manager Onboarding screen are correctly scaled 

### Actual behavior
 The "Continue" button is not scaled correctly in the Password Manager Onboarding screen 

### Device & build information
* Device: iPhone 15+ (17.4.1) 
* Build version: v128 (43182) 
* First seen version: ? 
### Notes
Attachments: 

![image](https://github.com/mozilla-mobile/firefox-ios/assets/124251579/c925d019-e0b5-42b7-9a88-f3eef8ed70e5)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-9448)

**Comment by data-sync-user** [comment]
➤ Norberto Andres Furlan commented:

Andrei Bodea this is an old ticket. Can you verify and close it? Thanks!

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v131 (45403), with iPhone 15 (17.5).

!ImportedPhoto.748337188.137131.jpeg|width=1179,height=2556,alt="ImportedPhoto.748337188.137131.jpeg"!
