### ISSUE TITLE
Unresponsive tabs when trying to rearrange them (intermittent)

### ISSUE THREAD

**Issue by DianaABarladeanu** [mozilla-mobile/firefox-ios#20956]
**Steps to reproduce**

1. Install FF. Make sure to have multiple tabs in tab tray.
1. Try to switch positions between tabs.

**Expected behavior**
The tabs can be rearranged without any issues.

**Actual behavior**
Sometimes, the tabs are unresponsive when trying to move them.

**Device & build information**

* Device: iPhone 15 (17.5), iPad Air 3rd gen (17.5), iPhone SE (17.5)
* Build version: v129 (43415)
* First seen version: ? 

Notes
This issue is also reproducible with tab tray refactor enabled.

Attachments: 

https://github.com/mozilla-mobile/firefox-ios/assets/151131988/b7c3fde5-682f-4125-8773-c85857bac753

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-9466)

**Comment by data-sync-user** [comment]
➤ Norberto Andres Furlan commented:

Sophie Amin can you take a look to this one after you finish with the high priority Tab Tray bugs? I think this is happening in both cases (with/without the tab tray). I don’t think it should block us to increase.

**Comment by data-sync-user** [comment]
➤ Sophie Amin commented:

Norberto Andres Furlan Yes, can do!

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v9000 (46854), with iPhone 15 (17.6)

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Verified as fixed on v133 (47401) with iPhone 15 Pro (18.2).
