### ISSUE TITLE
An empty homepage is opened after opening the same URL/website for the second time

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/firefox-ios#20957]
## Steps to reproduce
1. Launch FF.
1. Access www.x.com.
1. Go to the tabs tray and observe the newly opened tab.
1. Tap on  the `+` button and from the homepage open again www.x.com.
### Expected behavior
The user should be redirected to that website without issues and no other tabs should be opened.
### Actual behavior
The user is redirected to the correct URL/website but a new empty homepage is opened each time.
### Device & build information

* Device: iPhone 15 pro (17.5.1). 
* Build version: v129 (43415) 
* First seen version: N/A 
### Notes
This issue can be reproduced only if the experiment is ON.
Attachments: 

https://github.com/mozilla-mobile/firefox-ios/assets/42831109/8d5761ef-8a18-424d-9d49-7a8ecb05af56

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-9467)

**Comment by data-sync-user** [comment]
➤ Matt Lichtenstein commented:

This behavior only seems to occur when navigating to a duplicate URL from the homepage (via pins/recents/bookmarks/JBI/pocket) and does not happen when entering a duplicate URL into the search bar (By duplicate URL, I mean a URL that is already open in another tab).

{quote}# Expected behavior
The user should be redirected to that website without issues and no other tabs should be opened.{quote}

Norberto Andres Furlan To clarify, is the expected behavior such that we should switch to the first tab, and close the empty tab that was created?

**Comment by data-sync-user** [comment]
➤ Razvan Litianu commented:

hey Norberto Andres Furlan , Matt is correct. Technically Andrei is opening that new tab which shows the homepage (homepage is a tab by implementation), and if you go to an existing link it will just switch to that tab, the other one (homepage) still being around.

**Comment by data-sync-user** [comment]
➤ Norberto Andres Furlan commented:

Razvan Litianu I agree, but it seems that Andrei Bodea case is adding more homepages, which shouldn't happen. If you have some time tomorrow we can jump on a quick call, but I think it is not reproducible for most of us.

**Comment by abodea** [comment]
Hello, @afurlan-firefox please note the following:

- App store version <- **128 (43182)** - the experiment is not ON meaning when opening a new page from shortcuts it will open a new page all the time

https://github.com/user-attachments/assets/0d0f1788-9143-4c6e-b719-7c9687af5e86

- Test Flight version <- **129 (43576)** - the experiment is not ON meaning when opening a new page from shortcuts it will open a new page all the time

https://github.com/user-attachments/assets/3912dab8-f675-425a-8f1b-86b3dfa1e469

- Test Flight version <- **129 (43576)** - Experiment ON the issue is reproducible.

https://github.com/user-attachments/assets/2b4a3ede-ac57-4b00-a159-959520323cab


Please note that something might be wrong with the experiment, in order to reproduce this on any version of the APP you need to make sure you have the experiment on.
I was also, able to reproduce this on the APP Store build (after enabling the experiment).
