### ISSUE TITLE
[Tab Tray refactor] - Toast messages overlap when closing multiple tabs through swipe

### ISSUE THREAD

**Issue by DianaABarladeanu** [mozilla-mobile/firefox-ios#21062]
**Steps to reproduce**

1. Have multiple tabs in tabs tray.
1. Close multiple tabs by sweeping them in a quick session.
1. Check the toast messages.

**Expected behavior**
The toast messages are displayed in row, when the new message appears, the old one is removed.

**Actual behavior**
The toast messages overlap.

Device & build information

* Device: iPhone 15 (17.5)
* Build version: v129 (43631)
* First seen version: v9000 (30588)

Notes
Attachments: 

https://github.com/user-attachments/assets/fa8293e6-b086-4d68-becf-355b7ef155b7

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-9515)

**Comment by data-sync-user** [comment]
➤ Norberto Andres Furlan commented:

Diana Andreea Barladeanu this is the expected behavior.
