### ISSUE TITLE
Firefox opens a new tab every time it regains focus

### ISSUE THREAD

**Issue by Stokestack** [mozilla-mobile/firefox-ios#21074]
## Steps to reproduce
Have some tabs open in Firefox.
Switch to another app.
Switch back to Firefox.

### Expected behavior
Firefox's state is unchanged, and it shows what I was looking at two minutes ago.

### Actual behavior
It opens a new tab upon regaining focus, which is annoying as hell when, for example, you're in the security line at the airport bouncing back and forth between your mobile boarding pass and something else.

### Device & build information
* Device: ? Multiple. iPad under OS 16.7.8. iPhone under iOS 15.8.2
* Build version: ? 128.0
* First seen version: ? no idea
### Notes
Attachments: 

https://github.com/user-attachments/assets/0c1300c2-70bc-4266-a676-9b87dda55a43

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-9520)

**Comment by mattreaganmozilla** [comment]
@Stokestack Hi, can you let me know what your setting is for Opening Screen? (Go to Settings > Homepage, then at the top see which option is checked for 'Opening Screen')

**Comment by Stokestack** [comment]
Thanks for the follow-up. Here you go.
![Opening](https://github.com/user-attachments/assets/c3ad612f-9aba-4d42-b1bc-23b1f46f4426)

**Comment by mattreaganmozilla** [comment]
@Stokestack Is it the homepage you're seeing open? If so you might try switching that setting to `Last Tab` to see if that resolves the problem for you.

**Comment by Stokestack** [comment]
It is, thanks. I don't consider returning focus to Firefox "opening" it though. I would expect this control to dictate what Firefox shows upon launch, when it has no open tabs.

I also question defaulting to this behavior; it's highly disruptive and contrary to that of any other application I can remember.

**Comment by mattreaganmozilla** [comment]
@Stokestack I'll definitely share that feedback with the team, thanks; can you confirm if changing this setting does, in fact, resolve the unwanted behavior for you? Just wanted to be sure I understood if that was the root problem.

**Comment by Stokestack** [comment]
Thanks! Yes, I should have mentioned that: It does look like it eliminates that behavior.

**Comment by mattreaganmozilla** [comment]
Going to close since it sounds like this is resolved but please feel free to update if there are any other issues
