### ISSUE TITLE
[a11y] Microsurvey's sheet is not communicating its group label

### ISSUE THREAD

**Issue by anna-yeddi** [mozilla-mobile/firefox-ios#21219]
## Steps to reproduce
1. Ensure VoiceOver is running
2. Navigate to Fx New Tab page, review it at least twice to trigger the microsurvey
3. Confirm a microsurvey invitation has appeared (`Help us make Firefox better...`)
4. Navigate to and focus `Continue` button 
5. Using VoiceOver, activate the `Continue` button and observe the VO announcement

### Expected behavior
1. VoiceOver indicates in some way that the sheet opened is, in fact, related to a microsurvey, for example:
    1. The sheet grabber could be announced as `Close survey sheet` - this would be beneficial to also communicate the purpose of this control clearer, besides marking that this is, in fact, a `survey` content. This approach was used by the Translations sheet and would also be beneficial for consistency across the app. _Note:_ since the sheet could be expanded by using the same grabber, the accessible label for the sheet grabber could be `Survey sheet grabber` too, or similar

### Actual behavior
1. VoiceOver is announcing `Sheet Grabber`. No announcement for any grouping / sheet label is done when the sheet appears.

### Device & build information
* Device: iPhone 15 Pro, iOS 17.5.1
* Build version: Fx Beta build 9000 (43786) (Nightly)
### Notes
Attachments: 

![VoiceOver output showing the "Sheet Grabber" label announcement](https://github.com/user-attachments/assets/2c787118-841c-4263-b9be-bbc81d48336b)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-9622)

**Comment by anna-yeddi** [comment]
![VoiceOver output for the sheet grabber button on the Survey Complete page](https://github.com/user-attachments/assets/d72d58cc-7360-4a00-a11b-193f5fbca053)
Just in case, clarifying: same applies to the Survey complete page

**Comment by anna-yeddi** [comment]
Removed a copy-pasted `* First seen version: Fx release` from the initial comment.

**Comment by data-sync-user** [comment]
➤ Cyndi Chin commented:

ayeddi The sheet grabber a11y labels and details are determined by system. Would an alternative workaround be to announce Survey when the bottom sheet appears?

**Comment by data-sync-user** [comment]
➤ ayeddi commented:

I just tried on the today’s build 43876 and it didn’t announce Survey for me. Maybe different iOS builds or speed of localization and label injection plays role here?

If the Survey is announced when the bottom sheet appears, the issue is resolved.

**Comment by data-sync-user** [comment]
➤ Cyndi Chin commented:

ayeddi Sorry for the confusion, I meant I tested it in my development build and it appears with the sheet grabber. I’m planning on getting some of the a11y tickets in tomorrow’s nightly, so I’ll ping you for another review when that’s done. Thanks for clarifying this ticket for me. I’m good to go on this one!

**Comment by anna-yeddi** [comment]
The issue is fixed - the sheet grabber's announcement is now prefixed with `Survey` and is announced by VO as follows: `Survey, Sheet Grabber`. Thank you for resolving the issue, @cyndichin !

**Comment by data-sync-user** [comment]
➤ Cyndi Chin commented:

Reviewed and confirmed by ayeddi moving ticket to Done. Diana Andreea Barladeanu Please let me know if there are any concerns with this.
