### ISSUE TITLE
[a11y] Microsurvey invitation section does not mark its heading programmatically

### ISSUE THREAD

**Issue by anna-yeddi** [mozilla-mobile/firefox-ios#21214]
## Steps to reproduce
1. Ensure VoiceOver is running
2. Navigate to Fx New Tab page and focus the top of the page
3. Using a [VoiceOver rotor gestures](https://webaim.org/articles/voiceover/mobile#rotor), activate `Headings` shortcut
4. Using a shortcut navigation gesture (swiping up or down with one finger), attempt to navigate between headings on the page and observe the VO announcement compared to the visual presentation of the page

### Expected behavior
1. Rotor shortcut allows VoiceOver to quickly navigate to all visible headings, i.e. on the screenshot attached:
    1. `Switch your default browser`
    2. `Jump back in`, `Bookmarks` and other on-screen section titles (not visible on a screenshot but present on the page)
    3. `Help up make Firefox better...`

### Actual behavior
1. There are no programmatic headings on the New Tab page - VO says `Heading not found` while trying to shortcut up/down the page.
    1. An assistive technology user won't be able to quickly navigate between sections and would have to tediously swipe through all sections' content to navigate to `Thought-provoking stories` or a microsurvey, for example. 

### Device & build information
* Device: iPhone 15 Pro, iOS 17.5.1
* Build version: Fx Beta build 9000 (43786) (Nightly)
* First seen version: Fx release
### Notes
Attachments: 

![VoiceOver output showing there are no headings on the New Tab page](https://github.com/user-attachments/assets/c95ea81c-1cf2-48e1-b5d2-840c06a6344b)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-9616)

**Comment by data-sync-user** [comment]
➤ Cyndi Chin commented:

ayeddi Just wanted to confirm, this issue still exist regardless of the microsurvey, right? We are not allowing the user to swipe between headings it seems.

**Comment by anna-yeddi** [comment]
@cyndichin yes, this issue does exist for other sections of the New Tab page, but the _invitation_ to take the Microsurvey has it too (the `Help us make Firefox better...` text). The main microsurvey screen has an appropriate heading and can be jumped to via VO rotor's shortcut

**Comment by data-sync-user** [comment]
➤ ayeddi commented:

oops, sorry Cyndi Chin replied in GitHub instead (comment below ( https://mozilla-hub.atlassian.net/browse/FXIOS-9616?focusedCommentId=914603 )).

Adding heading trait should be sufficient for this to be fixed for the microsurvey update. And then, probably, we’d need to create a copy of this bug for general Fx New Tab fix too. Whichever would work for your team the best

**Comment by data-sync-user** [comment]
➤ Cyndi Chin commented:

ayeddi Thank you for clarifying! That works, I’ll go ahead and add it for microsurvey, but notice that the expected behavior listed above won’t apply since we don’t have headings for the other sections. Let’s go ahead and open a separate ticket for the other ones to be added to backlog. I’ll use this ticket to add the heading trait for microsurvey.

**Comment by data-sync-user** [comment]
➤ ayeddi commented:

done https://github.com/mozilla-mobile/firefox-ios/issues/21271 ( https://github.com/mozilla-mobile/firefox-ios/issues/21271|smart-link )  and the title of this issue is updated

**Comment by data-sync-user** [comment]
➤ Cyndi Chin commented:

awesome, thank you ayeddi !

**Comment by anna-yeddi** [comment]
The issue is fixed - the heading is announced as such and could be accessed via the VO Roto. Thank you for the fix!

**Comment by data-sync-user** [comment]
➤ Cyndi Chin commented:

Reviewed and confirmed by ayeddi moving ticket to Done.
