### ISSUE TITLE
Extra show more option on website data management page

### ISSUE THREAD

**Issue by dragosb01** [mozilla-mobile/firefox-ios#21227]
## Steps to reproduce
1. Go to settings/data management/website data
### Expected behavior
Only website data related option should be available
### Actual behavior
An extra show more option is visible. Tapping on it makes it not be displayed anymore
### Device & build information
* Device: iPhone 15, 17.5 iOS
* Build version: 130.0, 129.0
* First seen version: Yes
### Notes
Automation test failing: DataManagementTests/testWebSiteDataOptions
Attachments: 
<img width="392" alt="Screenshot 2024-07-23 at 09 07 06" src="https://github.com/user-attachments/assets/d88f439c-cd2b-48d3-bb08-125942543d33">

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-9631)

**Comment by data-sync-user** [comment]
➤ Norberto Andres Furlan commented:

Matt Lichtenstein can you check this bug?

**Comment by data-sync-user** [comment]
➤ Matt Lichtenstein commented:

Norberto Andres Furlan sure thing!

**Comment by dragosb01** [comment]
Issue fixed. Closing ticket.
