### ISSUE TITLE
[a11y] Microsurvey's sheet includes visually hidden Activate to dismiss pop-up window that is focusable with assistive technology

### ISSUE THREAD

**Issue by anna-yeddi** [mozilla-mobile/firefox-ios#21223]
## Steps to reproduce
1. Ensure VoiceOver is running
2. Navigate to Fx New Tab page, review it at least twice to trigger the microsurvey
3. Confirm a microsurvey invitation has appeared (`Help us make Firefox better...`)
4. Navigate to and activate the `Continue` button using VoiceOver
5. Confirm the Microsurvey sheet is opened and the sheet grabber control is focused with VoiceOver
6. Using VoiceOver logical navigation gestures (swipe left-to-right with one finger), navigate from the sheet grabber control to the Firefox logo and observe the VO announcement
7. Repeat steps with Switch Control and observe the extra highlighted element

### Expected behavior
1. VoiceOver is only focusing and announcing on-screen elements.

### Actual behavior
1. VoiceOver is focusing an empty or invisible element between the sheet grabber and Fx logo. It is announcing the element as `Activate to dismiss pop-up window`. 

### Device & build information
* Device: iPhone 15 Pro, iOS 17.5.1
* Build version: Fx Beta build 9000 (43786) (Nightly)
### Notes
Attachments: 

![VoiceOver output showing the "Activate to dismiss pop-up window, Button" announcement and VO focus](https://github.com/user-attachments/assets/a63d71f4-7c38-44d2-9cfd-6f6e003c72d9)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-9629)

**Comment by anna-yeddi** [comment]
Removed a copy-pasted `* First seen version: Fx release` from the initial comment.

**Comment by data-sync-user** [comment]
➤ Cyndi Chin commented:

ayeddi Users are able to navigate and tap in that area if they would like to dismiss the modal. I believe that this is from the system since we are not coding anything specific to announce this. Let me know if this is still an issue.

**Comment by data-sync-user** [comment]
➤ Cyndi Chin commented:

Our review checker which is a bottom sheet also has this. You can demonstrate it buy going to review checker and then making sure it is at medium detent (aka 50% of the screen). 

Thanks for updating the status, I was checking to see if I can get these closed while I’m working on the higher priority one since I’m in the area.

**Comment by data-sync-user** [comment]
➤ ayeddi commented:

hmm, the Review Checker does not have a grabber at all and this activate to dismiss does not pop up that much. But in general, it opens in the full size by default, thus it’s not focusable.

That’s being said, let’s close it - the same behavior confirmed in Safari > Reading list sheet too. Thank you for investigating it!

**Comment by data-sync-user** [comment]
➤ Cyndi Chin commented:

ayeddi That was brought up when including the sheet grabber for microsurvey and apparently it was a miss. It seems going forward all modals should include it. Thank you for checking the sheet in Safari as well!

**Comment by anna-yeddi** [comment]
Closing this bug as this is currently a native iOS sheet behavior.
