### ISSUE TITLE
Microsurvey is not scrolled into view when it opens

### ISSUE THREAD

**Issue by anna-yeddi** [mozilla-mobile/firefox-ios#21233]
## Steps to reproduce
1. Ensure VoiceOver is running
2. Navigate to Fx New Tab page, review it at least twice to trigger the microsurvey
3. Confirm a microsurvey invitation has appeared (`Help us make Firefox better...`) and observe the VO announcement
4. Repeat steps with Switch Control and observe the focus highlight position
5. Repeat steps with Voice Control and observe the visual appearance of the New Tab page

### Expected behavior
1. When a microsurvey sheet appears, it is scrolled into the view, so it is clear what is being announced by VoiceOver, being focused with Switch Control, or being available to call with Voice Control.

### Actual behavior
1. When a microsurvey sheet appears, it is _not_ scrolled into the view, so it is not clear what is being announced by VoiceOver, being focused with Switch Control, or being available to call with Voice Control.
    * VoiceOver moves the focus to the microsurvey and starts announcing it, but it is visually hidden behind an on-screen keyboard (that appears for the search input when a New Tab is opened). Note: VO sends a click event that is likely to land on the on-screen item instead of the mucrosurvey at all.
    * Switch Control users would have to dismiss the keyboard to be able to see and activate the survey, because it is hidden behind an on-screen keyboard and even when the Switch Control would scroll down the page, the microsurvey is not visible and thus it won't be something a user is aware of, until they dismiss the keyboard (which may not happen, for instance, if they activate one of tiles).
    * Voice Control cannot call a microsurvey control, because it is under the keyboard. A user has to scroll the page to discover it.
 1. Note: when the microsurvey persists and remains visible when a content page is opened, there is a chance a user would become aware of it, but scrolling the microsurvey into the view above the on-screen keyboard is still crucial for an equal experience and discoverability. This issue is likely affecting users without any assistive technologies too who would not see the microsurvey behind the on-screen keyboard too.

### Device & build information
* Device: iPhone 15 Pro, iOS 17.5.1
* Build version: Fx Beta build 9000 (43854) (Nightly)
### Notes
Attachments: 

Both screenshots have a microsurvey shown under the keyboard
![VoiceOver output showing the microsurvey being announced but the VoiceOver focus is placed under the on-screen keyboard](https://github.com/user-attachments/assets/ebe0e296-8895-4050-ab84-0212f8cf2bbf)
![Voice Control showing labels for on-screen keyboard while the microsurvey is shown at the bottom of the page - it is not offered for a VC user](https://github.com/user-attachments/assets/de226b25-d01f-41b6-a39e-51122df1d23a)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-9635)

**Comment by anna-yeddi** [comment]
The issue is confirmed fixed: the VoiceOver focus does not move to the survey and the microsurvey is included in the reading order in the same way as it is visually ordered too. Thank you!

**Comment by data-sync-user** [comment]
➤ Cyndi Chin commented:

Reviewed and confirmed by ayeddi moving ticket to Done. Diana Andreea Barladeanu Please let me know if there are any concerns with this.
