### ISSUE TITLE
[Address autofill phase 2] - "Manage addresses" link is missing

### ISSUE THREAD

**Issue by DianaABarladeanu** [mozilla-mobile/firefox-ios#21258]
Prerequisites
User is enrolled in "Address autofill phase 2 beta rollout" experiment.

**Steps to reproduce**
1. Install FF. Make sure you have some saved addresses.
1. Go to: https://luke-chang.github.io/autofill-demo/basic.html and tap on  a field--->The option to open saved addresses is available .
2. Check the available options.

**Expected behavior**
 "Manage addresses" link is available.

**Actual behavior**
 "Manage addresses" link is NOT available.

**Device & build information**
* Device: iPhone 15 (17.5), iPad Air 3rd gen (17.5)
* Build version: v129 (43869)
* First seen version: ? 

Notes

Attachments: 

https://github.com/user-attachments/assets/8a919993-0339-4b5c-890a-2dfa096520ba

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-9655)

**Comment by data-sync-user** [comment]
➤ Norberto Andres Furlan commented:

Razvan Litianu can you take a look to this one?

**Comment by razvanlitianu** [comment]
hello @DianaABarladeanu, is there any chance the video is from a different bug?

**Comment by data-sync-user** [comment]
➤ Alina Moldovan commented:

Validated this issue using v131 (45602) and iPhone 15+ (18.0)
