### ISSUE TITLE
Missing private tab when switching between regular and private mode

### ISSUE THREAD

**Issue by dragosb01** [mozilla-mobile/firefox-ios#21291]
## Steps to reproduce
1. Open a new website in regular mode
2. Go to private mode and open a website there
3. Go back to regular mode and select the website from tab tray
4. Switch back to private mode
### Expected behavior
The previously website opened in private mode should be visible in tab tray
### Actual behavior
The website opened in private mode is missing. Tab tray is empty. See video attached
### Device & build information
* Device: iPhone 15, iOS 17.5
* Build version: 130.0
* First seen version: Yes
### Notes
Automation tests that caught the issue and can be executed to reproduce the bug:
PrivateBrowsingTest/testClosePrivateTabsOptionClosesPrivateTabs
PrivateBrowsingTestIpad/testClosePrivateTabsOptionClosesPrivateTabsShortCutiPad
Attachments: 

https://github.com/user-attachments/assets/51121066-c45c-4956-b1f4-42ca9713ffd6

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-9678)

**Comment by data-sync-user** [comment]
➤ Dragos Bigu commented:

Norberto Andres Furlan new issue added

**Comment by dragosb01** [comment]
Issue is not reproducing on 129.0

**Comment by data-sync-user** [comment]
➤ Matt Reagan commented:

Norberto Andres Furlan (cc Nishant Bhasin) Just at a glance so far yes it looks like we clear private tabs now as soon as you leave that mode. Disabling the new toggle fixes this behavior. I’m not 100% clear on what the expected functionality is for the new toggle but this looks like it’s working as expected.

**Comment by nbhasin2** [comment]
Yeah exactly, that's the behaviour with the (toggle on)
We close tabs as soon as user leaves private browsing so its working as intended based on the change. If the user decides to retain their tabs in private mode they can (toggle off)

**Comment by data-sync-user** [comment]
➤ Norberto Andres Furlan commented:

Ok. Dragos Bigu it seems that this is not a problem it is just a test that we need to update.

**Comment by data-sync-user** [comment]
➤ Norberto Andres Furlan commented:

If the toggle is On -> When the user switches to normal/close the app/or iOS kills is, all private tabs disappear.

If the toggle is Off -> When the user switches to normal/close the app/or iOS kills is, nothing happens.

**Comment by data-sync-user** [comment]
➤ Norberto Andres Furlan commented:

https://mozilla-hub.atlassian.net/browse/FXIOS-9519 ( https://mozilla-hub.atlassian.net/browse/FXIOS-9519|smart-link )

**Comment by data-sync-user** [comment]
➤ Matt Reagan commented:

{quote}it is just a test that we need to update{quote}

Norberto Andres Furlan Can you please confirm if this ticket should stay open to track this change (test update)? Otherwise I think this can be closed since it’s working as expected.

**Comment by dragosb01** [comment]
I will close this ticket and make the proper updates on the automation tests on a different one.
