### ISSUE TITLE
[Toolbar redesign] The keyboard cannot be closed while on the home screen (tapping anywhere should close it)

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/firefox-ios#21319]
## Steps to reproduce
1. Access FF and go to the home page.
1. Tap on the URL bar.
1. Tap anywhere to close the keyboard.
### Expected behavior
The keyboard should be closed.
### Actual behavior
The keyboard cannot be closed while on the home screen (tapping anywhere should close it)
### Device & build information

* Device: iPhone 15 Pro (17.5.1) 
* Build version: v9000 (43978) 
* First seen version: v9000 (43978) 
### Notes
Attachments: 

https://github.com/user-attachments/assets/2ab4ba5d-3e58-47d3-8bad-1e2b816027dc

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-9701)

**Comment by data-sync-user** [comment]
➤ Winnie Teichmann commented:

Should be fixed in the next nightly. Was fixed with this PR ( https://github.com/mozilla-mobile/firefox-ios/pull/21400 ).

**Comment by data-sync-user** [comment]
➤ Alina Moldovan commented:

Verified as fixed using v9000 (44546) and iPhone 15+ (17.5.1) and iPad Pro 4th Gen (7.2).

A followup issue was logged to track the '>' button in front of the address bar.
