### ISSUE TITLE
[Toolbar redesign] - URL address is de-selected when changing device orientation

### ISSUE THREAD

**Issue by DianaABarladeanu** [mozilla-mobile/firefox-ios#21318]
**Prerequisites**
User is enrolled in "New iOS toolbar" experiment treatment a.

**Steps to reproduce**

1. Open FF homepage and access a website while in portrait mode.
1. Tap on the URL bar to select the URL address.
1. Turn the device in landscape mode and observe the URL bar.

**Expected** behavior
The URL address remains selected after changing device orientation.

**Actual behavior**
The URL address does NOT remain selected after changing device orientation.
This also happens after changing from landscape to portrait mode.

**Device & build information**

* Device: iPhone 15 (17.5)
* Build version: v9000 (43978)
* First seen version: ? 

Notes

Attachments:

https://github.com/user-attachments/assets/16009466-5fc6-4672-9103-000e5b0dd7b8

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXIOS-9700)

**Comment by data-sync-user** [comment]
➤ Winnie Teichmann commented:

Should be fixed in the next nightly. Was fixed with this PR ( https://github.com/mozilla-mobile/firefox-ios/pull/21400 ).

**Comment by data-sync-user** [comment]
➤ Alina Moldovan commented:

Verified as fixed using v9000 (44546) and iPhone 15+ (17.5.1) and iPad Pro 4th Gen (7.2).

**Comment by data-sync-user** [comment]
➤ Norberto Andres Furlan commented:

Winnie Teichmann the keyboard should continue to be showed when moving to portrait. 

Andrei Bodeacan you check if I am already in landscape and we click the URL bar. Do we show the keyboard? Thanks!

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Hello, Norberto Andres Furlanplease note that if I’m already in landscape and tap on the URL, the keyboard is displayed without issues and after that when rotating into portrait mode, the keyboard is still displayed without issues and the URL is selected.

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Verified as fixed on v133 (47063) with iPhone 15 Pro (18.2).
