### ISSUE TITLE
Focus iOS can't be compiled using Xcode 16 (beta 3)

### ISSUE THREAD

**Issue by clarmso** [mozilla-mobile/firefox-ios#21310]
## Steps to reproduce

1. Install Xcode 16 (beta 3)
2. `xcodebuild build-for-testing -scheme Focus -target XCUITest -configuration FocusDebug -destination 'platform=iOS Simulator,name=iPhone 15,OS=18.0'`

### Expected behavior

Focus iOS could be compiled using Xcode 16 (beta 3).

### Actual behavior

Compilation error
```
	CompileC /Users/runner/Library/Developer/Xcode/DerivedData/Blockzilla-hatpfgxfdajndqazqgdxnrsnqxwe/Build/Intermediates.noindex/Sentry.build/FocusDebug-iphonesimulator/Sentry.build/Objects-normal/arm64/SentryCrashMonitor_CPPException.o /Users/runner/Library/Developer/Xcode/DerivedData/Blockzilla-hatpfgxfdajndqazqgdxnrsnqxwe/SourcePackages/checkouts/sentry-cocoa/Sources/SentryCrash/Recording/Monitors/SentryCrashMonitor_CPPException.cpp normal arm64 c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'Sentry' from project 'Sentry')
```

### Device & build information
* Device: N/A
* Build version: July 26 `main`
* First seen version: N/A
### Notes
Attachments: 

I tried to compile the source code using Github Actions: https://github.com/clarmso/metrics-firefox-ios/actions/runs/10117355527/job/27982140640

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-9693)

**Comment by razvanlitianu** [comment]
hi @clarmso, I am able to build with the latest Xcode 16 (beta 6)

**Comment by clarmso** [comment]
> hi @clarmso, I am able to build with the latest Xcode 16 (beta 6)

@razvanlitianu 🎉 I can compile and run the XCUITest on Xcode 16 beta 6 as well. Let me close this issue.
```
$ xcodebuild -version 
Xcode 16.0
Build version 16A5230g
```
