### ISSUE TITLE
Firefox iOS can'be be compiled using Xcode 16 (beta 3)

### ISSUE THREAD

**Issue by clarmso** [mozilla-mobile/firefox-ios#21311]
## Steps to reproduce
1. Install Xcode 15 (beta 3).
1. `xcodebuild build-for-testing -project Client.xcodeproj -scheme Fennec -configuration Fennec -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 15,OS=18.0'`

### Expected behavior
Firefox iOS can be compiled using Xcode 16.

### Actual behavior
Compilation error

```
2024-07-26T20:45:28.4626180Z CompileC /Users/runner/Library/Developer/Xcode/DerivedData/Client-hfhlbjikkmvblqfgwgvstixehrdw/Build/Intermediates.noindex/Sentry.build/Fennec-iphonesimulator/Sentry.build/Objects-normal/x86_64/SentryBacktrace.o /Users/runner/Library/Developer/Xcode/DerivedData/Client-hfhlbjikkmvblqfgwgvstixehrdw/SourcePackages/checkouts/sentry-cocoa/Sources/Sentry/SentryBacktrace.cpp normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'Sentry' from project 'Sentry')
```

### Device & build information
* Device: iPhone 15
* Build version: July 26
* First seen version: N/A
### Notes
Attachments: 

I tried to compile the source code using Github Actions: https://github.com/clarmso/metrics-firefox-ios/actions/runs/10117355527/job/27982140495

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-9692)

**Comment by data-sync-user** [comment]
➤ Razvan Litianu commented:

Update for iOS 18.0 Beta

During testing with iOS 18.0 beta, it was observed that the evaluateJavaScript method's closure signature has been updated, which introduces an error in our current implementation. The method signature needs to be modified as follows:

Before:

public override func evaluateJavaScript(_ javaScriptString: String, completionHandler: ((Any?, Error?) -> Void)? = nil)After:

open override func evaluateJavaScript(_ javaScriptString: String, completionHandler: (@MainActor (Any?, (any Error)?) -> Void)? = nil)However, changing the method signature to the new format results in compatibility issues—specifically, the code compiles in Xcode 16 but not in Xcode 15, which is not ideal for our current development setup.

Additionally, there is a new property tab in the UITab class. This property name conflicts with existing property names in some of our view controllers, necessitating a rename.
