### ISSUE TITLE
[regression] "Find in Page" bar remembers the most recent search text

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/firefox-ios#21312]
## Steps to reproduce
1. Open a page in a tab.
1. Open "Find in Page".
1. Enter some text in the find bar.
1. Open a new page in a second tab.
1. Open "Find in Page" on the second tab.

### Expected behavior
The find bar should not remember the search text from the most recent search, regardless of whether it was in the current tab or other tabs.

Can we configure the find bar to not remember the search text between tabs, even if find bars are open in multiple tabs at the same time? If not, perhaps we can clear the find bar's text when the user closes the find bar.

piratesarereal says:

> Comparing saving the text and not saving it, I would lean towards not saving it as saving it causes more issues to be resolved. We could consider resolving these issues highlighted above if there is a user group requesting it and there is a clear use case for it. But to keep it simple, we should not save the text.

> Also saving the text between tabs is redundant. So we will have to develop a feature to remember it per tab. Unsure how useful that would be. 

Isabella warns:

> if the UX/Product team eventually does decide to go with the "search text per tab" idea in the future, there is an open radar issue that will make this difficult (https://openradar.appspot.com/FB10170943). Right now the `UIFindInteraction` seems to share a global search field (the mechanism by which the text is being preserved in the first place).

### Actual behavior
The find bar remembers the search text from the previous search, from the same or other tabs. This behavior is a regression from the new `UIFindInteraction` find bar.

For comparison:

Remembers the most recent search (from any tab):

* Firefox iOS in TestFlight
* Safari iOS
* Chrome Android

Doesn’t remember the most recent search (even from the current tab):

* Firefox iOS 127.1 in the App Store
* Chrome iOS
* Firefox Android

### Device & build information
* Device: iPhone 15 Plus running iOS 17.5.1
* Build version: I can reproduce this bug in TestFlight Nightly 9000 (43906) but the regression landed earlier.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-9694)

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v9000 (44073), with iPhone 15 (17.5).

**Comment by data-sync-user** [comment]
➤ Alina Moldovan commented:

Validated as fixed on v130 (44245) & iPhone 14+ (16.0.3)
