### ISSUE TITLE
Remove the `awesomebar.{engagement, abandonment}` events

### ISSUE THREAD

**Issue by linabutler** [mozilla-mobile/firefox-ios#21337]
@dzeber has confirmed that the `awesomebar` event counts match `urlbar.{engagement, abandonment}` now, so we can remove the `awesomebar` events again!

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-9706)

**Comment by data-sync-user** [comment]
➤ Norberto Andres Furlan commented:

Should we include this as part of the Telemetry Audit? Chris Bellini

**Comment by linabutler** [comment]
This is done in #21386! 🎉
