### ISSUE TITLE
[Toolbar redesign] - No search suggestions are displayed

### ISSUE THREAD

**Issue by DianaABarladeanu** [mozilla-mobile/firefox-ios#21365]
Prerequisites
User is enrolled in "New iOS toolbar" experiment treatment a.

**Steps to reproduce**
1. Install FF.
2. Make sure that "show search suggestions" toggle is enabled in settings.
3. Go to homepage and start typing a new search.
4. Observe.

**Expected behavior**
Search suggestions are displayed.

**Actual behavior**
No search suggestions are displayed.

Device & build information
* Device: iPhone 15 (17.5)
* Build version: v9000 (44073)
* First seen version: ? 

Notes
Attachments: 

https://github.com/user-attachments/assets/88b21aa8-3e73-460a-8f5c-28e8d57ac4e7

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-9722)

**Comment by thatswinnie** [comment]
This will be implemented with [this task](https://mozilla-hub.atlassian.net/browse/FXIOS-9297).

**Comment by data-sync-user** [comment]
➤ Winnie Teichmann commented:

Should be fixed in the next nightly. Was fixed with this PR ( https://github.com/mozilla-mobile/firefox-ios/pull/21400 ).

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v9000 (44343), with iPhone 15 (17.5).

!ImportedPhoto.745164198.623211.jpeg|width=1179,height=2556,alt="ImportedPhoto.745164198.623211.jpeg"!

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v133 (47038), with iPhone 15 (17.6).
