### ISSUE TITLE
[Toolbar redesign] - Nav bar is not displayed in landscape mode

### ISSUE THREAD

**Issue by DianaABarladeanu** [mozilla-mobile/firefox-ios#21366]
Prerequisites
User is enrolled in "New iOS toolbar" experiment treatment a.

**Steps to reproduce**
1. Open FF in portrait mode and observe the nav bar which is correctly displayed.
2. Turn the device in landscape mode and observe.

**Expected behavior**
Nav bar is correctly displayed.

**Actual behavior**
Nav bar is missing.

**Device & build information**
* Device: iPhone 15 (17.5)
* Build version: V9000 (44073)
* First seen version: ? 

 Notes
Attachments: 

https://github.com/user-attachments/assets/8f5600e3-6ba1-4dcc-a692-5cc560ee6d1d

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-9723)

**Comment by thatswinnie** [comment]
The nav bar is not displayed in landscape in the release version either nor is it specified in Figma that it should be displayed in landscape. So this is not a bug but expected behaviour.
