### ISSUE TITLE
Firefox for iOS is forgetting login information and cookies after close app

### ISSUE THREAD

**Issue by oubrecht-com** [mozilla-mobile/firefox-ios#21497]
Firefox for iOS 129.1 and 130 beta are forgetting login information and cookies after force close app in iOS. 
It is the similar problem as old issue here:
[https://github.com/mozilla-mobile/firefox-ios/issues/12740#issuecomment-1643260568](https://github.com/mozilla-mobile/firefox-ios/issues/12740#issuecomment-1643260568)

- - -
This seems to be trivially reproducible via:

1. Launch app
1. Log into a website in current normal tab (e.g. Gmail)
1. Quit app & relaunch

Result: the user is logged out and must re-enter login information.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-9787)

**Comment by data-sync-user** [comment]
➤ Matt Reagan commented:

Going to close this as a duplicate since the same bug is effectively being tracked by https://mozilla-hub.atlassian.net/browse/FXIOS-9803 ( https://mozilla-hub.atlassian.net/browse/FXIOS-9803|smart-link )

**Comment by data-sync-user** [comment]
➤ Matt Reagan commented:

Very similar cookies bug to https://mozilla-hub.atlassian.net/browse/FXIOS-9803 ( https://mozilla-hub.atlassian.net/browse/FXIOS-9803|smart-link ) , both should be the same culprit and fixed by the same PR. (cc Alina Moldovan Norberto Andres Furlan )

**Comment by data-sync-user** [comment]
➤ Alina Moldovan commented:

Validated as fixed using v129.2 (44469) and iPhone 14+ (17.5.1).

**Comment by oubrecht-com** [comment]
v192.2 is OK. Thank you very much.
