### ISSUE TITLE
[Mobile Microsurveys][Enhancement] If toolbar is set at the Top, the prompt is hidden under the keyboard

### ISSUE THREAD

**Issue by alinamoldovan84** [mozilla-mobile/firefox-ios#21505]
## Steps to reproduce
1. Clean install FF 
2. Open the app -> Homepage opens 
3. Enable the Microsurvay feature flag
4. Open another homepage   

### Expected behavior
The prompt should open and be visible 

### Actual behavior
The prompt opens but it is not visible. It is hidden by the keyboard.
If the toolbar is set at the bottom the prompt is visible, it is displayed above the keyboard. 
 
### Device & build information
* Device: iPhone 15+ (17.5.1) 
* Build version: v130 (44311) 
* First seen version: ? 
### Notes
* the same problem is reproduced when the "Find on page" option is open because the keyboard is raised up. Please note that if a similar option that does not raise the keyboard, like "Zoom", is open, the Prompt is visible  

### Attachments: 

https://github.com/user-attachments/assets/e9773788-7728-42ed-84f1-6fc874bdd6d5

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-9791)

**Comment by data-sync-user** [comment]
➤ Cyndi Chin commented:

Alina Moldovan Thank you for reporting this. This experience is expected and we are aware of the experience that the microsurvey will hide behind the keyboard. The survey is meant to not be intrusive and the microsurvey will still persist in which the user can view it on other areas.

See thread discussing here: https://mozilla.slack.com/archives/C4E0W8B8E/p1721752075852999?thread_ts=1721400929.753559&cid=C4E0W8B8E ( https://mozilla.slack.com/archives/C4E0W8B8E/p1721752075852999?thread_ts=1721400929.753559&cid=C4E0W8B8E|smart-link )

**Comment by data-sync-user** [comment]
➤ Cyndi Chin commented:

See thread for confirmation from Ray Fambro on expectations. https://mozilla.slack.com/archives/C06JLPR4HHC/p1723224361609919 ( https://mozilla.slack.com/archives/C06JLPR4HHC/p1723224361609919|smart-link ) 

Let me know if any issues or if this ticket can be closed. Thanks for the thorough QA review Alina Moldovan !

**Comment by data-sync-user** [comment]
➤ Cyndi Chin commented:

Diana Andreea Barladeanu Alina Moldovan Based on the information below, closing this ticket as Cancelled. However, please let me know if you would like to continue this discussion or need more clarity!
