### ISSUE TITLE
[Toolbar redesign] - Keyboard is not raised when opening a new tab 

### ISSUE THREAD

**Issue by DianaABarladeanu** [mozilla-mobile/firefox-ios#21517]
Prerequisites
User is enrolled in "New iOS toolbar" experiment treatment a.

**Scenario 1:**
**Steps to reproduce**
1. Install FF and open a website.
2. While in tab tray, tap on "+" button to open another tab.
3. Observe.

**Expected behavior**
After tapping on "+",  homepage is opened and the keyboard pops up.
**Actual behavior**
After tapping on "+",  homepage is opened but the keyboard doesn't pop up.

**Scenario 2**
**Steps to reproduce**
1. Install FF and while on homepage, long tap on the tab tray icon.
2. Choose to open a new tab/new private tab.
3. Observe

**Expected behavior**
After tapping on "new tab"/ "new private tab",  a new homepage tab is opened and the keyboard pops up.
**Actual behavior**
After tapping on "new tab"/ "new private tab",  a new homepage tab is opened but the keyboard doesn't pop up.

**Scenario 3**
**Steps to reproduce**
1. Install FF and while on homepage, tap on "+" button from toolbar to open a new tab.
2. Observe.

**Expected behavior**
A new homepage tab is opened and the keyboard pops up.
**Actual behavior**
A new homepage tab is opened but the keyboard doesn't pop up.

Device & build information
* Device: iPhone 15 (17.5)
* Build version: ?v9000 (44362)
* First seen version: ? 

 Notes
Attachments: 

https://github.com/user-attachments/assets/9175a638-8b40-4e40-be0e-87b9f03d6332

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-9798)

**Comment by data-sync-user** [comment]
➤ Adina Petridean commented:

Verified as fixed on build 45786 with iPhone 14 Pro Max (iOS 16.2).

!keyboard.mp4|width=886,height=1920,alt="keyboard.mp4"!

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v133 (47038), with iPhone 15 (17.6).
