### ISSUE TITLE
[Toolbar redesign] - Last visited website is briefly displayed before the new one is loaded 

### ISSUE THREAD

**Issue by DianaABarladeanu** [mozilla-mobile/firefox-ios#21519]
Prerequisites
User is enrolled in "New iOS toolbar" experiment treatment a.

**Steps to reproduce**

1. Open FF and load a website.
1. In the same tab's address bar, type another URL and wait for the website to load.
1. Observe.

**Expected behavior**
The new website is instantly and correctly loaded.

**Actual behavior**
For a couple of seconds, the previous visited website is displayed, before the new one is loaded.

Device & build information

* Device: iPhone 15 (17.5)
* Build version: v9000(44362)
* First seen version: ? 

Notes
Attachments: 

https://github.com/user-attachments/assets/3771d6ae-03c7-41c6-8342-9ea1680aa067

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-9800)

**Comment by data-sync-user** [comment]
➤ Norberto Andres Furlan commented:

Diana Andreea Barladeanu this one should be something related to the connection. It seems to be the normal behavior, just slow. Can you check?

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Norberto Andres Furlan This issue doesn’t reproduce with the current toolbar.

**Comment by data-sync-user** [comment]
➤ Chris Peterson commented:

Andrei Bodea will check.

**Comment by data-sync-user** [comment]
➤ Andres Furlan commented:

Andrei Bodea can you re-verify this one?
