### ISSUE TITLE
Cookies not saved in normal browsing mode after opening and saving a tab in private mode

### ISSUE THREAD

**Issue by DianaABarladeanu** [mozilla-mobile/firefox-ios#21560]
**Steps to reproduce**

1. Access news.google.com in normal browsing and accept cookies.
1. Force close the app and observe.
1. Go to settings, disable "close private tabs" toggle.
1. Open a random website in private mode, then return to normal tab tray, to the news.google.com tab.
1. Force close the app and observe.

**Expected behavior**
Cookies on news.google.com are already accepted, the consent page doesn't show up again.

**Actual behavior**
The consent page is displayed again, cookies are not saved.

**Device & build information**

* Device: iPhone 15 (17.5)
* Build version: v129.2 (44469)
* First seen version: ? 
 
Notes
Each consent page is displayed in history when long tapping on the navigation arrow.

Attachments: 

https://github.com/user-attachments/assets/7ba20356-653b-4b9d-91a4-504034f50934

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-9815)

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Verified as fixed on v131 (45403) with iPhone 15 Pro (17.5).

I’ve tried at least 5 times with 5 fresh installs and a lot of restarts and the cookies were saved without issues.
