### ISSUE TITLE
[Toolbar redesign] Tapping outside the URL bar is not completely closing the keyboard    

### ISSUE THREAD

**Issue by alinamoldovan84** [mozilla-mobile/firefox-ios#21605]
## Steps to reproduce

1. Make sure the toolbar redesign experiment is enabled
2. Navigate to the homepage and make sure the keyboard is raised up 
3. Tap outside the address bar to close the keyboard but Make sure you are NOT tapping '>' button in front of the address bar 
4. Check the behavior 

### Expected behavior
The keyboard is closed and '>' button in front of the address bar is removed   

### Actual behavior
The keyboard is closed but the '>' button in front of the address bar is NOT removed. Therefor tapping on the magnifying glass to perform a new search is not working    

### Device & build information
* Device: 14+ (16.0.3), iPhone 15+ (17.5.1) 
* Build version: v9000 (44546) 
* First seen version: ? 
### Attachments: 

https://github.com/user-attachments/assets/15e16ab0-3de5-40e1-98bc-1ece1e1ffe37

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-9842)

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Validated on v9000 (44732), with iPhone 15 (17.5)

**Comment by data-sync-user** [comment]
➤ Adina Petridean commented:

Verified as fixed on Firefox 133.0 47063, with iPhone 14 Pro Max (iOS 16.2).
