### ISSUE TITLE
[Toolbar redesign] Private mask is missing from the tab tray icon while in Private browsing mode  

### ISSUE THREAD

**Issue by alinamoldovan84** [mozilla-mobile/firefox-ios#21601]
## Steps to reproduce

1. Make sure the toolbar redesign experiment is enabled
2. Open a new private tab 
3. Check the tab tray icon while in private browsing mode 

### Expected behavior
The private mask is displayed over the tab tray icon 

### Actual behavior
The private mask is NOT displayed over the tab tray icon 

### Device & build information
* Device: iPhone 14+ (16.0.3), iPhone 15+ (17.5.1) 
* Build version: v9000 (44546) 
* First seen version: ? 
### Notes
Attachments: 

https://github.com/user-attachments/assets/7a43839f-399c-445d-98b3-ba10eeca0a0b

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-9838)

**Comment by data-sync-user** [comment]
➤ Winnie Teichmann commented:

This will be fixed in https://mozilla-hub.atlassian.net/browse/FXIOS-9737 ( https://mozilla-hub.atlassian.net/browse/FXIOS-9737|smart-link )

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v9000 (44662), with iPhone 15 (17.5).

**Comment by data-sync-user** [comment]
➤ Adina Petridean commented:

Verified as fixed on Firefox 133.0 (47063) with iPhone 14 Pro Max (iOS 16.2).
