### ISSUE TITLE
Buddybuild links are private

### ISSUE THREAD

**Issue by bootstraponline** [mozilla-mobile/firefox-ios#2167]
Example:

- https://dashboard.buddybuild.com/apps/57bf25c0f096bc01001e21e0/build/5802a2af4269d601001d15ba

Is there a reason the builds aren't public?

**Comment by AaronMT** [comment]
Unfortunately BuddyBuild does not offer a public dashboard. It would be great if anyone could see the dashboard without needing to be part of our Github organization or even being logged in to Github or signed up to BuddyBuild. A read-only view would be very useful. (Assuming the build logs do not contain anything confidential). The good thing is, we've passed this request over to them and hopefully we'll see a public view soon.
