### ISSUE TITLE
iPhone SE original images/photos look "negative" in "night mode" after latest iOS update

### ISSUE THREAD

**Issue by IlgazC** [mozilla-mobile/firefox-ios#21720]
## Steps to reproduce
Launch Firefox iOS on iPhone 5 SE and open a website. _(update)_ **Enable "night mode"**

### Expected behavior
It should display website correctly

### Actual behavior
Images look as "negative", e.g. like a photo negative. See the attached screenshot.
![IMG!UNITO-UNDERSCORE!1755](https://github.com/user-attachments/assets/1f88fbcb-df3b-4d06-855c-6f444ea546bb)

### Device & build information
* Device: ? iPhone 5 SE ("original") MLXM2TU/A
* Build version: ? Firefox 129.2 (44469)
* First seen version: This has started right after updating to iOS 15.8.3 (very possibly security update) I am using Firefox exclusively on all my devices including iOS ones.
* ### Notes I naturally checked iOS Safari. Issue doesn't exist.
Attachments: 

![IMG!UNITO-UNDERSCORE!1755](https://github.com/user-attachments/assets/1f88fbcb-df3b-4d06-855c-6f444ea546bb)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-9905)

**Comment by data-sync-user** [comment]
➤ Norberto Andres Furlan commented:

Can you check if the Nigh Mode option inside the menu is off? Thanks!

**Comment by IlgazC** [comment]
> ➤ Norberto Andres Furlan commented:
> 
> Can you check if the Nigh Mode option inside the menu is off? Thanks!

It was "on". I actually forgot to update my bug report, it is directly related to "night mode" being "on". On iPhone, things go dark automatically at sunset, so I didn't even know/use that option. I must have accidentally turned it on.

Sorry for forgetting. I think it is still a bug, right? I even have a Mac Mini w/developer tools here and available to test anything.

**Comment by data-sync-user** [comment]
➤ Norberto Andres Furlan commented:

Our current night mode invert all images even if the web page is already on dark mode. We are working on an improvement.
