### ISSUE TITLE
Deprecated Denpendency: sentry-cocoa 8.34.0

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/firefox-ios#21742]
The release version used for sentry-cocoa (8.34.0) has been deprecated due to a bug. Our builds are failing because that is not found anymore. They suggest to upgrade to 8.35.0.

Would that be fine? or do we want to use a newer version? https://github.com/getsentry/sentry-cocoa/releases

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-9916)

**Comment by data-sync-user** [comment]
➤ Nishant Bhasin commented:

Orla Mitchell I assigned it to you as I know you are in contact with sentry, this is just a ticket to follow-up if we get an update form their side
