### ISSUE TITLE
Firefox crashes when trying to open a website in a new tab via a hyperlink

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/firefox-ios#21760]
## Steps to reproduce
1. Launch FF and access ` https://pwning.geniuscoolcat.com/1863832_side_impact_2.php ` or `https://zoso.ro/prea-multe-soferii-uita-unde-apar-accidentele/`
1. Tap on the cat image in order to be redirected or the `filmarea asta` hyperlink on the zoso.ro website shared on step 1.
### Expected behavior
The redirect should be done without issues to the new tab and the website to be opened.
### Actual behavior
Firefox crashes when trying to open a website in a new tab via a hyperlink.
### Device & build information

* Device: iPhone 13 Pro (15.7.1), iPhone 15+ (18), iPhone 15 (17.5) 
* Build version: v9000 (44818), 131 (44813) 
* First seen version: v9000 (44621) 
### Notes
Please note that this is not related to a specific website, it happens with any website that has a hyperlink with a redirection.
The issue was introduced in the build v9000 (44621).
**Not reproducible on v130 (44595).**
Attachments: 

[Crash_logs.zip](https://github.com/user-attachments/files/16850416/Crash_logs.zip)

https://github.com/user-attachments/assets/5972f86a-780b-4d68-85c8-0db8f5b12afa

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-9921)

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Verified as fixed on v131 (44858) with iPhone 13 Pro (15.7.1), iPhone 15+ (18), and iPhone 15 (17.5).
