### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by chaochaohao** [mozilla-mobile/firefox-ios#2180]
wangchao:firefox-ios wangchao$ sh ./bootstrap.sh
**\* Fetching onyx_ios
**\* Checking out Alamofire at "3.5.0"
**\* Checking out Deferred at "7d3d3230133db71544e60dfa7fa3d095361398db"
**\* Checking out Fuzi at "0.4.0"
**\* Checking out GCDWebServer at "3.3.2"
**\* Checking out ios_sdk at "v4.10.1"
**\* Checking out KIF at "v3.5.1"
**\* Checking out libPhoneNumber-iOS at "0.8.11"
**\* Checking out onepassword-extension at "d99f5d7a4c7328f8e3a8d1e7aff455d1072e0c19"
**\* Checking out onyx_ios at "0.0.3"
**\* Checking out readability at "71aa562387fa507b0bac30ae7144e1df7ba8a356"
**\* Checking out SDWebImage at "3.7.4"
**\* Checking out SnapKit at "0.22.0"
**\* Checking out SwiftKeychainWrapper at "701a27dfc4502645122f8db5e7be4479e85e831c"
**\* Checking out XCGLogger at "55613b29c09caaf1ff75d930f27e0b69115b7a56"
**\* xcodebuild output can be found in /var/folders/8j/9jfm_2xx54q89tzs0sfn7nxr0000gn/T/carthage-xcodebuild.zVALr4.log
**\* Building scheme "Alamofire iOS" in Alamofire.xcworkspace
**\* Building scheme "Deferred" in Deferred.xcodeproj
**\* Building scheme "Fuzi-iOS" in Fuzi.xcworkspace
**\* Building scheme "GCDWebServers (iOS)" in GCDWebServer.xcodeproj
**\* Building scheme "AdjustSdk" in Adjust.xcodeproj
ld: warning: embedded dylibs/frameworks only run on iOS 8 or later
ld: warning: embedded dylibs/frameworks only run on iOS 8 or later
ld: warning: embedded dylibs/frameworks only run on iOS 8 or later
ld: warning: embedded dylibs/frameworks only run on iOS 8 or later
A shell task failed with exit code 1:
error: unable to open '/Users/wangchao/Library/Developer/Xcode/DerivedData/Adjust-hkqgkqxzfjzjvigwfmpzvanzylfy/Build/Products/Release-iphoneos/AdjustSdk.framework/$(EXECUTABLE_NAME)': No such file or directory

**Comment by AaronMT** [comment]
Is this with XCode 8.0? Have you tried deleting the contents under `~/Library/Developer/Xcode/DerivedData/` and re-running the bootstrap script?
