### ISSUE TITLE
Screenshot of native error page for tab manager

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#21912]
## Steps to reproduce
1. Navigate to any new error page.
1. Click on tab tray.
1. The screenshot of tab is different than error page.

### Expected behavior
Screenshot of error page should be visible in tab tray.

### Actual behavior
Blank Page or Old error page is visible in tab tray.

* Attachments:

https://github.com/user-attachments/assets/c9623c28-b6bf-4695-942f-98a477fb5481

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-9978)

**Comment by tusharC95** [comment]
After fix video capture: 


https://github.com/user-attachments/assets/3309728f-6352-416e-9339-0686bcb378ac

**Comment by data-sync-user** [comment]
➤ Tushar Chitnavis commented:

After bug fix video capture:

!VIDEO-2024-09-18-19-26-32.mp4|width=384,height=848,alt="VIDEO-2024-09-18-19-26-32.mp4"!

**Comment by tusharC95** [comment]
After bug fix video capture:

https://github.com/user-attachments/assets/7be3fb28-c35f-4cb6-ada7-a871932c3a4a
