### ISSUE TITLE
[Favicons refactor] - Default shorcuts' favicons are smaller 

### ISSUE THREAD

**Issue by DianaABarladeanu** [mozilla-mobile/firefox-ios#21927]
**Steps to reproduce**
1. Fresh install FF.
2. Observe the default shortcuts' favicons (on homepage).

**Expected behavior**
The sizing is the same as before the refactor.

**Actual behavior**
The favicons are smaller.

**Device & build information**
* Device: iPhone 15 (17.5), iPad Pro (18)
* Build version: v131 (45098)
* First seen version: ? 

Notes
Attachments: 

![photo-collage png (1)](https://github.com/user-attachments/assets/7d875c66-6b12-4f1c-84f4-bb514ff0ca21)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-9984)

**Comment by data-sync-user** [comment]
➤ Norberto Andres Furlan commented:

Expected.

**Comment by nbhasin2** [comment]
Closing as expected with the new change that @FilippoZazzeroni merged
