### ISSUE TITLE
[Address autofill phase 2] [Telemetry] - Unable to generate  addresses.autofilled event

### ISSUE THREAD

**Issue by DianaABarladeanu** [mozilla-mobile/firefox-ios#21922]
**Prerequisites**
User is enrolled in "Address autofill phase 2 beta rollout" experiment.

 **Steps to reproduce**
1. Fresh install FF.
2. Have telemetry enabled on the device.
3. Sign in with a valid account that has some saved addresses.
4. Access https://luke-chang.github.io/autofill-demo/basic.html
5. Tap on one of the fields then tap on "use saved addresses".
6. Select an address.
7. Check the events in https://glean-debug-view-dev-237806.firebaseapp.com/pings/.

**Expected behavior**
addresses.autofilled event is registered.

**Actual behavior**
addresses.autofilled event is NOT registered.
https://dictionary.telemetry.mozilla.org/apps/firefox_ios/metrics/addresses_autofilled

**Device & build information**
* Device: iPad Air 3rd gen (17.5), iPhone 15 (17.5)
* Build version:  v131 (45098)
* First seen version: ? 

 Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-9982)

**Comment by data-sync-user** [comment]
➤ Norberto Andres Furlan commented:

Razvan Litianu can you take a look?

**Comment by data-sync-user** [comment]
➤ Issam Mani commented:

This is a regression from some code we pushed in Desktop. This should be fixed once https://bugzilla.mozilla.org/show_bug.cgi?id=1918362 ( https://bugzilla.mozilla.org/show_bug.cgi?id=1918362|smart-link )  is in Github 😃

**Comment by issammani** [comment]
Fixed in https://github.com/mozilla-mobile/firefox-ios/pull/21975

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v9000 (45403), with iPhone 15 (17.5).

!Screenshot 2024-09-18 at 12.13.24 PM.png|width=968,height=42,alt="Screenshot 2024-09-18 at 12.13.24 PM.png"!

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v131 (45514), with iPhone 15 (17.5).
