### ISSUE TITLE
Toolbar is incorrectly displayed after a specific scenario 

### ISSUE THREAD

**Issue by alinamoldovan84** [mozilla-mobile/firefox-ios#21939]
## Steps to reproduce
1. Open a new tab (a web page can be loaded)
2. Open the hamburger menu and tap on the Firefox account or 'Sync and Save Data'
3. Put the device in landscape mode 
4. Put the device in portrait mode 
5. Close the Account Page by tapping the 'Close' button 
6. Check the toolbar 

### Expected behavior
The toolbar should be correctly displayed while in portrait mode 

### Actual behavior
The toolbar's elements are displayed on a single line 

### Device & build information
* Device: iPhone 15+ (18.0), iPhone 14 (17.4.1), SE (17.5) 
* Build version: 131 (45217)
* First seen version: 127.1 or older 
### Notes
Attachments: 

https://github.com/user-attachments/assets/9ce8008d-7f1c-49d0-b0b1-dd0ded745aef

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-9989)

**Comment by data-sync-user** [comment]
➤ Sorin Paraipan commented:

I’ve tested this issue and I was able to reproduce it. Even though this is not related to the Toolbar Redesign feature, doing the steps mentioned in the bug breaks also the layout for the Toolbar Redesign.

**Comment by data-sync-user** [comment]
➤ Adina Petridean commented:

Verified as fixed on Firefox 9000 (46072) with iPhone 14 Pro Max (iOS 16.2).

!toolbarDisplayed.mp4|width=886,height=1920,alt="toolbarDisplayed.mp4"!

**Comment by data-sync-user** [comment]
➤ Adina Petridean commented:

Verified as fixed on Firefox 133.0 (47063) with iPhone 14 Pro Max (iOS 16.2).
