### ISSUE TITLE
 Auto-Completion of website URL requires multiple deletions to enter desired URL on some devices

### ISSUE THREAD

**Issue by AdinaPetridean** [mozilla-mobile/firefox-ios#21941]
## Steps to reproduce
1. Launch Firefox.
2. Enter a URL in the search bar.
3. Observe the behavior.

### Expected behavior
The URL is successfully entered.
### Actual behavior
When entering the first few letters of a website URL, the address is auto-completed automatically. Users are forced to delete the auto-completed portion multiple times to input the correct URL they intend to enter. This issue occurs on certain devices.

### Device & build information
* Device: iPhone 14 Pro Max (iOS 16.2), iPhone 15 Plus (iOS 18)
*  Build version: 45230

### Notes
Attachments: 

https://github.com/user-attachments/assets/1c8d1e4b-3c99-4401-ba0b-4997539ddb13

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-9991)

**Comment by data-sync-user** [comment]
➤ Adina Petridean commented:

Verified as fixed on FIREFOX 9000 (46072) with iPhone 14 Pro Max (iOS 16.2).

!Autocomplete.mp4|width=886,height=1920,alt="Autocomplete.mp4"!

**Comment by data-sync-user** [comment]
➤ Adina Petridean commented:

Verified as fixed on the latest Firefox 132.0 (46575) with iPhone 14 Pro Max (iOS 16.2).
