### ISSUE TITLE
Weird behavior of history groups

### ISSUE THREAD

**Issue by DianaABarladeanu** [mozilla-mobile/firefox-ios#22026]
**Steps to reproduce**

1. Fresh install FF.
1. Tap on the url bar and type "The daily beast".
1. When redirected to Google, tap on "The daily beast" search result.
1. Check the history to see if a group has been created.
1. While in "The daily beast" website, load the "The guardian.com" website.
1. Go to history and look for the "The guardian.com" entry.

**Expected behavior**
"The guardian" history entry is listed separately in history.

**Actual behavior**
"The guardian" history entry is listed in "The daily beast" group.

**Device & build information**

* Device: iPhone 15 (17.5)
* Build version: v131 (45309)
* First seen version: ? 
Notes

Attachments: 

https://github.com/user-attachments/assets/ad1844b1-8556-4b7a-a331-ff0b9193cfac

https://github.com/user-attachments/assets/ad1844b1-8556-4b7a-a331-ff0b9193cfac

https://github.com/user-attachments/assets/ad1844b1-8556-4b7a-a331-ff0b9193cfac

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-10048)

**Comment by data-sync-user** [comment]
➤ Norberto Andres Furlan commented:

Diana Andreea Barladeanu this is the expected behavior as it is starting on the google search.
