### ISSUE TITLE
Firefox Dev Edition, pop up saying firefox needs to be update in loop

### ISSUE THREAD

**Issue by boi87** [mozilla-mobile/firefox-ios#22036]
## Steps to reproduce
I just downloaded Firefox Developer edition - I'm on version 131.0b7, and if I open the About tab it says that Firefox is up to date.

![](https://github.com/user-attachments/assets/66d649d3-1bec-425c-aec2-c89376e08558)

However the annoying message you see below keeps asking me to quit Firefox to allow the update (to a previous version, it seems?).

![](https://github.com/user-attachments/assets/0e45a819-8059-42de-a15f-e0ad67b88858)

Regardless if I click on Not now or Quit and Update, the message will just disappear and re-appear every 5 minutes.
.

### Expected behavior
Firefox should quit & update, but it won't.

### Actual behavior
The message disappears just to reappear a few minutes later.

### Device & build information
* Device: MacBook Pro
* Build version: ? Mac OS 14.6 (23G80)
* First seen version: just downloaded firefox dev edition

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-10057)

**Comment by MattLichtenstein** [comment]
Hello @boi87 👋 

This is the repository for Firefox for iOS, and it looks like the issue you are having pertains to Firefox for desktop. If you would like to report an issue for Firefox for desktop, I recommend filing a bug in their issue tracker, [Bugzilla](https://bugzilla.mozilla.org/home). Also feel free to check out [support site](https://support.mozilla.org/) for additional troubleshooting.

**Comment by linabutler** [comment]
Hi @boi87! To follow up on @MattLichtenstein's comment, would you mind starting a new thread on [SUMO](https://support.mozilla.org/en-US/questions/new/firefox), please? In that thread, could you also please let us know if there's any device management software installed on your computer, like "Jamf Pro"?

This isn't a Firefox Desktop dialog (thanks for including the screenshots!), but it looks similar to [this Jamf dialog for Chrome](https://www.reddit.com/r/chrome/comments/uctaje/macos_keeps_reverting_chrome_to_version_98/).

The SUMO community can help you troubleshoot now, and also keep an eye out for others having the same issue in the future. Thanks!

**Comment by boi87** [comment]
Thank you both, moving this in Bugzilla :) link for reference -> https://bugzilla.mozilla.org/show_bug.cgi?id=1919449
