### ISSUE TITLE
Enhanced tracking protection switch is not visible when enabled from settings

### ISSUE THREAD

**Issue by dragosb01** [mozilla-mobile/firefox-ios#22053]
## Steps to reproduce
1. Open any website
2. Click on the lock icon to see the menu
3. Go to privacy settings and notice the option is enabled by default
### Expected behavior
The switch is enabled
### Actual behavior
The switch is not visible
### Notes
Attachments: 
<img width="394" alt="Screenshot 2024-09-18 at 12 04 40" src="https://github.com/user-attachments/assets/c4f187e8-2f6c-4b5d-9984-3b99ff2d4dde">

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-10063)

**Comment by clarmso** [comment]
Could we close the issue? @dicarobinho @dicarobinho

**Comment by dicarobinho** [comment]
Sure. Closed!
