### ISSUE TITLE
[Regression] - `About:blank` page/tab is opened when accessing a website with pop-up windows

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/firefox-ios#22139]
## Steps to reproduce
1. Open a (test) website that contains a pop-up window. ([Example](https://www.webroot.com/services/popuptester1.htm))
1. Tap the hamburger menu and open Settings.
1. Turn off "Block Pop-up Windows".
1. Tap "Done" to close the Settings.
1. Open a (test) website that contains a pop-up window. ([Example](https://www.webroot.com/services/popuptester1.htm))
### Expected behavior
The website should be displayed without issues and the pop-up window should be displayed.
### Actual behavior
`About:blank` page/tab is opened when accessing a website with pop-up windows
### Device & build information
* Device: iPhone 15 Pro (17.5), iPhone 15 (17.5) 
* Build version: 131 (45514) 
* First seen version: N/A 
### Notes
Note that this is a regression from https://github.com/mozilla-mobile/firefox-ios/issues/21658
Attachments: 

https://github.com/user-attachments/assets/096b5f65-cf23-42cc-9f1a-ac46417f9705

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-10112)

**Comment by nbhasin2** [comment]
I tried the following and they worked by opening popup

- https://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_win_open - Worked
- http://www.dummysoftware.com/popupdummy_testpage.html - Worked
- https://www.rrc.texas.gov/resource-center/research/gis-viewer/gis-popup-blocker-test/ - Worked 

So webroot website itself might have some issues (see below) cc @mattreaganmozilla @abodea 

<img width="573" alt="image" src="https://github.com/user-attachments/assets/4fbbd1b4-6258-479d-ab5c-66dc7a50f95d">

**Comment by issammani** [comment]
@abodea I took a quick look and can confirm what @nbhasin2 said. Everything seems to be working as expected. In the case of webroot,  the website is intentionally opening an `about:blank` page. Not sure why they do that but I think we have the correct behaviour here. Let me know if I am missing something.

![Group 7(1)](https://github.com/user-attachments/assets/b72fc9ad-9a73-4e03-83a6-eaf3d5b084a4)

**Comment by abodea** [comment]
Hello, thank you @issammani @nbhasin2 I did check this on other browsers and you are right.
Closing this issue based on the comments above.
