### ISSUE TITLE
Old (inactive?) tabs not in tab list when "Inactive Tabs" is disabled

### ISSUE THREAD

**Issue by badboy** [mozilla-mobile/firefox-ios#22155]
With the most recent v9000 build I am not seeing all open tabs in the tab list.

## Steps to reproduce

"Inactive tabs" is disabled in settings:

1. Check tab count (20)
2. Open tab list
3. See only 2 tabs

"Inactive tabs" is enabled in settings:

1. Check tab count (20)
2. Open tab list
3. See 2 active tabs,
4. Click "Inactive Tabs"
5. See the remaining 18 tabs in that list

### Expected behavior

When "Inactive Tabs" is **disabled**, the tab list should show ALL open tabs.

### Actual behavior

When "Inactive Tabs" is **disabled**, the tab list only shows what seems to be "active" tabs

### Device & build information
* Device: iPhone 14 Pro
* Build version: v9000 (45556)
* First seen version: This or maybe the previous v9000 build.

### Notes

Tab count is shown as "20":
![74BDCFA5-A00F-42F3-8974-0ADC076A32FF_4_5005_c](https://github.com/user-attachments/assets/415e2511-4d2a-4c3e-9838-1b570f017ceb)

Only 2 tabs are visible in the tab list:
![F6C08748-BA68-4E19-839F-72376F47166B_4_5005_c](https://github.com/user-attachments/assets/74cf609a-34d2-45ba-af29-3d256b1bd962)

After enabling "Inactive Tabs" the other tabs are visible as inactive:
![5D4EF48F-ABFF-4D9B-AC38-026668788D1E_4_5005_c](https://github.com/user-attachments/assets/570ced88-3b48-4afa-905d-077a58d1d4db)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-10117)

**Comment by data-sync-user** [comment]
➤ Norberto Andres Furlan commented:

Sophie Amin

**Comment by badboy** [comment]
I now can't reproduce this in build 45824 anymore. Not sure what changed though.
