### ISSUE TITLE
Unable to view synced tabs from desktop

### ISSUE THREAD

**Issue by clarmso** [mozilla-mobile/firefox-ios#22166]
## Steps to reproduce
From SyncIntegrationTests: `test_integration.py::test_sync_tabs_from_desktop`
https://storage.googleapis.com/mobile-reports/public/firefox-ios-M1/result_901/firefox-ios/firefox-ios-tests/Tests/SyncIntegrationTests/results/index.html

1. Open Firefox desktop.
1. Sign into Mozilla account.
1. Open https://www.example.com
1. Wait until sync occurs.
1. Open Firefox iOS.
1. Sign into the _same_ Mozilla account.
1. Open Settings. 
1. Tap "Sync Now". Wait until sync finishes.
1. Go to home screen and open tab tray.
1.  Open "Synced Tabs" from the tab tray.
1. Tap "Sync Tabs". Wait until sync finishes.

Note: I'm unsure if it's a issue from sync's end on stage. I cannot reproduce the issue manually on prod. Let's open this bug so that we don't forget.

### Expected behavior
"example.com" is seen from the list of synced tabs under the profile/device.

### Actual behavior
No synced tab is seen (see screenshot and screen recording) even after tapping "sync tabs" repeatedly. Not profile/device is listed.

### Device & build information
* Device: iPhone 15 iOS 17.4 simulator
* Build version:
* First seen version: release/v127 (Perhaps earlier.)
* 

### Notes
Attachments: 

Screenshot:
![Simulator Screenshot - iPhone 15 - 2024-09-08 at 23 32 08](https://github.com/user-attachments/assets/1887187d-da46-4614-be9b-4cd5d4830129)

Screen recording:
https://github.com/user-attachments/assets/85be2040-6bd6-4966-a8b0-33464fad94e3

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-10119)

**Comment by data-sync-user** [comment]
➤ Norberto Andres Furlan commented:

Andrei Bodea can you do manual QA around this to see if you can reproduce? Thanks!

**Comment by data-sync-user** [comment]
➤ Norberto Andres Furlan commented:

CC: Matt Reagan for visibility

**Comment by data-sync-user** [comment]
➤ Clare So commented:

Andrei Bodea Have you been able to reproduce this issue manually? I still encounter the same blank Synced Tabs screen the past weekend.

**Comment by clarmso** [comment]
From past weekend, I can see the synced tab again via the Sync Integration Tests. Let me close this issue for now.
<img width="372" alt="Screenshot 2024-11-04 at 3 46 18 PM" src="https://github.com/user-attachments/assets/a3cd7da8-60c3-44b8-abfb-d47ca924bd87">
