### ISSUE TITLE
A plus icon overlays the toolbar’s tab counter button

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/firefox-ios#22206]
## Steps to reproduce
I don’t have reliable STR, but I have reproduced the problem a couple times using these steps:

1. Load https://www.cnn.com/2024/09/24/science/video/octopus-hunt-with-fish-and-punch-digvid
1. Rotate the device to landscape orientation. 
1. Play the video. 
1. Make the video full screen. 
1. Exit full screen. 
1. Closely watch the toolbar’s tab counter button as you rotate the device back to portrait orientation. 

### Expected behavior
No plus button on the toolbar. 

### Actual behavior
The landscape toolbar’s plus button icon overlays the toolbar’s tab counter button. Sometimes the plus icon just flashes quickly and sometimes the plus icon sticks around. 

### Device & build information
* Device: phone 15 Plus running iOS 18.0 
* Build version: 9000 (45624) 
* First seen version: I don’t recall when I first saw this bug, but I have seen it for at least a few days. 

### Notes
Attachments: 

![image](https://github.com/user-attachments/assets/1b28dafb-c86e-4aed-92fe-8adcec1e9615)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-10135)

**Comment by data-sync-user** [comment]
➤ Norberto Andres Furlan commented:

Andrei Bodea can you check if this it happening all the time? I can’t reproduce.

**Comment by data-sync-user** [comment]
➤ Alina Moldovan commented:

Andres Furlan managed to reproduce this issue using FF v133 (47038)

!image-20241101-132023.png|width=25%,alt="image-20241101-132023.png"!

**Comment by data-sync-user** [comment]
➤ Chris Peterson commented:

Sorin reproduced this bug using the old toolbar.

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Verified as fixed on v133 (47343) with iPhone 15 Pro (18.2).
