### ISSUE TITLE
[Regression] "Inactive tabs" functionality is enforced and it cannot be disabled 

### ISSUE THREAD

**Issue by alinamoldovan84** [mozilla-mobile/firefox-ios#22231]
## Steps to reproduce
1. Fresh install the app 
1. Make sure the "Inactive tabs"  is enabled in settings (The option is ENABLED by default)
1. Set the inactive tabs timeout to 10 s
1. Open a few tabs and wait for them to be added to the "Inactive tabs" folder 
1. Navigate to settings and disable the inactive tabs toggle (Settings->Tab )
1. Check the tab tray 

### Expected behavior
The inactive tabs folder is removed and the tabs are available directly in the tab tray 

### Actual behavior
The inactive tabs folder is still present. If the user opens new tabs, the tabs are added to the inactive tab folder after 10s.

### Notes
* When updating the app from FF v130.1(45056) while the inactive tabs functionality is disabled to FFv131 (45771), the inactive tabs functionality becomes automatically enabled even if the toggle remains visually disabled in settings.  This means that in production, all users will have this option enabled once they upgrade the app to 131. 

### Device & build information
* Device: iPhone 14+(16.0.3), 15 (17.5), 14 (17.4.1), 15 Pro (17.5)  
* Build version: Beta: v131 (45771); 
* First seen version: Beta:  v131 (45771) Nightly: starting with v9000 (45732) 

Attachments: 

<

!--- Screenshots or screen recordings are very helpful for reproducing|width=200,height=183!

-->

[https://github.com/user-attachments/assets/47957443-2afd-4216-ba53-70ef4ec41347](https://github.com/user-attachments/assets/47957443-2afd-4216-ba53-70ef4ec41347)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-10144)

**Comment by data-sync-user** [comment]
➤ Clare So commented:

I could reproduce the issue on earlier builds and confirmed that I can toggle “Inactive Tabs” again at the following hashes:

  * main: 102839b7f3bd3f6f1a32fe90ad41b1f82349bfce
  * release/v131: 42952bf430aee7aa560063b0eb7d1f2168b3d97b

**Comment by cpeterso** [comment]
I see this behavior. Some of my tabs moved to the “Inactive Tabs” folder, even though my “Inactive Tabs” setting is disabled. I’m using Firefox 9000 (45786) on iOS 18.0.

**Comment by ih-codes** [comment]
@cpeterso This appears fixed on the latest beta (45824).

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v131 (45816), with iPhone 15 (17.5).
