### ISSUE TITLE
[regression] Tab tray screen doesn’t scroll to show the current tab's tile

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/firefox-ios#22259]
## Steps to reproduce
1. Open a bunch of tabs, enough that their tab tiles don’t all fit on the tab tray screen.
1. Switch to the bottom-most tab.
1. Open the tab tray screen.

### Expected behavior
The current tab's tile should be shown when opening the tab try screen.

### Actual behavior
The tab try screen's scroll position is at the top and the current tab may be off screen.

### Device & build information
* Device: iPhone 15 Plus running iOS 18.0
* Build version: 9000 (45824)
* First seen version: 9000 (45824)

### Notes
:warning: **This bug is a regression in build 9000 (45824). It is not reproducible in the previous build, 9000 (45786).**

I reported a similar bug back in March: #10857

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-10156)

**Comment by cpeterso** [comment]
If I manually enroll in the ”New Toolbar iOS” experiment’s treatment-a branch, I can no longer reproduce this bug. But after switching back to the control branch toolbar, I can reproduce this bug again.

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v9000 (46632), with iPhone 15 (17.6).

**Comment by data-sync-user** [comment]
➤ Adina Petridean commented:

Verified as fixed on v132 (46741), with iPhone 14 Pro Max (iOS 16.2).
