### ISSUE TITLE
Conform presented menu to iPad specifications in Figma

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#22283]
Right now, when we presente the menu, we just do it universally, and we have detents & everything. But the iPad designs don’t look like this. So we should update what we’re doing to match the iPad designs

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-10176)

**Comment by Piratesarereal** [comment]
The max height and max width of the menu sheet on the iPad should match the bookmarks sheet. In the attached image shown in the bugfix, it seems like it is doing it, so that works.

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Validated on v133 (47063), with iPad Air 3rd gen (17.5).
