### ISSUE TITLE
Cannot toggle between regular and private mode repeatedly

### ISSUE THREAD

**Issue by clarmso** [mozilla-mobile/firefox-ios#22295]
## Steps to reproduce
1. Open Firefox iOS
2. Tap "glasses" 👓  button.
3. Tap "glasses" button again and again.

### Expected behavior

The "glasses" button is available on the homepage. I can toggle between regular mode and private mode. This video shows the behaviour on v131:
https://github.com/user-attachments/assets/d9d24307-19d8-4726-8e94-ccc99d7a9b46

### Actual behavior

Blank page
![Simulator Screenshot - iPhone 15 Pro - 2024-10-01 at 12 03 47](https://github.com/user-attachments/assets/2e0f40a7-6b63-4852-9eac-3144d5fec83c)

Current behaviour on main:
https://github.com/user-attachments/assets/b97e26a5-9d5c-40b2-901e-0b75f93e7868

### Device & build information
* Device: iPhone 15 simulator iOS 17.5
* Build version: 
* First seen version: Sept 28, 2024 on main and v132
### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-10182)

**Comment by cyndichin** [comment]
Seems related to https://mozilla-hub.atlassian.net/browse/FXIOS-10155

**Comment by clarmso** [comment]
> Seems related to https://mozilla-hub.atlassian.net/browse/FXIOS-10155

Let me close this duplicate ticket. :)
