### ISSUE TITLE
[Tracking Protection] - The blue dot is not displayed from the first refresh when reloading the website without tracking protection while being in strict mode

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/firefox-ios#22291]
## Steps to reproduce
1. Launch FF and enable the strict tracking protection from the settings.
1. Load any website.
1. Long tap on the refresh button.
1. Tap on the Reload without Tracking Protection.
### Expected behavior
The website should reload without issues and the blue dot should be displayed to the lock ETP icon.
### Actual behavior
The blue dot is not displayed from the first refresh when reloading the website without tracking protection while being in strict mode.
### Device & build information

* Device: iPhone 15 Pro (17.5). 
* Build version: 132 (45864). 
* First seen version: N/A 
### Notes
Please note that after a refresh the dot is displayed on the lock icon.
Attachments: 

https://github.com/user-attachments/assets/a6ca3bdf-5b4d-4e65-a858-76a65a73205b

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-10181)

**Comment by data-sync-user** [comment]
➤ Matt Lichtenstein commented:

Sorin Paraipan Assigning you as this ticket is fulfilled by https://mozilla-hub.atlassian.net/browse/FXIOS-10270 ( https://mozilla-hub.atlassian.net/browse/FXIOS-10270|smart-link ) that you have in review. Would you mind updating that status/fix version for this ticket as well once it is merged. And can we add this ticket # to the PR title and description so links are created?

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v9000 (46854), with iPhone 15 (17.6).

**Comment by data-sync-user** [comment]
➤ Adina Petridean commented:

Verified as fixed on Firefox 133.0 (47063) with iPhone 14 Pro Max (iOS 16.2).
