### ISSUE TITLE
[regression] Blank page displayed before the website is loaded

### ISSUE THREAD

**Issue by DianaABarladeanu** [mozilla-mobile/firefox-ios#22322]
**Steps to reproduce**

1. Fresh install FF.
1. Start opening top sites/shortcuts/pocket articles one by one.
1. Observe

 **Expected behavior**
The websites are instantly and correctly loaded.

 **Actual behavior**
A grey blank page is briefly displayed before the website is loaded.

**Device & build information**

* Device: iPhone 15 (17.5)
* Build version: v132 (45901)
* First seen version: ? 

Notes
Attachments: 

https://github.com/user-attachments/assets/02f2228c-c94c-4af1-a46a-30119095ae29

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-10200)

**Comment by afurlan-firefox** [comment]
We won't consider this a blocker if it is only happening with top sites. Can you confirm @DianaABarladeanu ? Thanks!

**Comment by data-sync-user** [comment]
➤ Filippo Zazzeroni commented:

I managed to solve it by changing the DOM body background to transparent while loading the web view content and restoring to original color while content is loaded

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v134 (48347), with iPhone 16+(18.1).
