### ISSUE TITLE
[Favicons refactor] - Youtube alternative search engine favicon disappears after force close

### ISSUE THREAD

**Issue by DianaABarladeanu** [mozilla-mobile/firefox-ios#22360]
**Steps to reproduce**

1. Install Firefox.
1. Go to search engines and add youtube.
1. Force close.
1. Start typing in the url bar and observe the favicon in search engine list.
1. Also go to search settings and observe YT favicon there, too.

**Expected behavior**
The favicon is correctly displayed both on homepage and in settings.

**Actual behavior**
YT favicon disappears after force close.

**Device & build information**

* Device: iPhone (17.5)
* Build version: v132 (45901)
* First seen version: ? 
 Notes
Attachments: 

https://github.com/user-attachments/assets/d6eb546e-476f-4288-805b-ab5323b03c82

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-10216)

**Comment by data-sync-user** [comment]
➤ Norberto Andres Furlan commented:

ih-codes not priority but whenever you have time to take a look. Thanks!

**Comment by data-sync-user** [comment]
➤ ih-codes commented:

That’s… odd. I was able to reproduce it in the simulator first try. Occurs on subsequent launches as well without a second force quit.

Will look a bit more at this later…

!Screenshot 2024-10-07 at 2.19.56 PM.png|width=1014,height=475,alt="Screenshot 2024-10-07 at 2.19.56 PM.png"!

Dev reference YT query string:

https://www.youtube.com/results?search_query=cats

**Comment by data-sync-user** [comment]
➤ ih-codes commented:

Update: I’ve been testing other search engines. Adding Quant worked, but then adding crates.io ( http://crates.io ) gave me a letter favicon like in https://mozilla-hub.atlassian.net/browse/FXIOS-10217 ( https://mozilla-hub.atlassian.net/browse/FXIOS-10217|smart-link ) . YouTube seems to fail every time with the invisible image. I’m guessing these 2 tickets are probably related.

Will continue investigating what’s up with fetching and saving images in the search engine codepath.

**Comment by data-sync-user** [comment]
➤ ih-codes commented:

The crates.io ( http://crates.io ) issue is now here (separate problem related to HTTP headers): https://mozilla-hub.atlassian.net/browse/FXIOS-10272 ( https://mozilla-hub.atlassian.net/browse/FXIOS-10272|smart-link )

**Comment by data-sync-user** [comment]
➤ ih-codes commented:

RelMan:

This fix should be merged into the next release (which I believe will be v132).

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v132 (46701), with iPhone 15 (17.6).
