### ISSUE TITLE
Fire button no longer exists on private window

### ISSUE THREAD

**Issue by clarmso** [mozilla-mobile/firefox-ios#22384]
## Steps to reproduce
1. Open Firefox iOS.
1. Open Tab Tray and switch to private mode.
1. Tap "+" to open a private tab.
1. Tap "<" from awesome bar to minimize the keyboard.

Caught by XCUITest `ToolbarTests/testOpenNewTabButtonOnToolbar`.

### Expected behavior
The fire :fire: icon in the bottom:
![Simulator Screenshot - iPhone 15 Pro - 2024-10-03 at 15 38 50](https://github.com/user-attachments/assets/695e4b6d-985d-4ce9-bf71-46464dcb1987)

### Actual behavior
The magnifying glass :mag: icon in the bottom. The fire :fire: icon is no longer found.
![Simulator Screenshot - iPhone 15 Pro - 2024-10-03 at 13 01 25](https://github.com/user-attachments/assets/7a509285-602b-4685-a814-b3412f33e0ee)

### Device & build information
* Device: iPhone 15 iOS 17.5 simulator
* Build version: 
* First seen version: Oct 2 2024 d75728073f0fe31c9698298eb47bb2eea2513373
### Notes
Attachments: 

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-10232)

**Comment by data-sync-user** [comment]
➤ Matt Lichtenstein commented:

The actual behavior is the expected behavior. Figma specs ( https://www.figma.com/design/8fsCvtnweBkWGZ9NfL907l/__-Toolbar-Redesign?node-id=26560-203903&t=9XjbdVIDCQn7FuT0-4 ) have just been updated to reflect this.

Closing as expected behavior.
