### ISSUE TITLE
Tab opened with context menu is not the last displayed in tab tray

### ISSUE THREAD

**Issue by DianaABarladeanu** [mozilla-mobile/firefox-ios#22398]
**Steps to reproduce**

1. Open several tabs.
1. Access news.google.com and long tap on one of the articles.
1. Choose to open in a new tab.
1. Observe tab tray.

**Expected behavior**
The last opened tab is on the last position.

**Actual behavior**
The tab opened with context menu is not displayed on the last position.

**Device & build information**

* Device: iPhone 15 (17.5)
* Build version: v132 (46048)
* First seen version: ? 

Notes
Attachments: 

https://github.com/user-attachments/assets/cd3a3b5d-4c97-497b-ae4d-46192640acd6

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-10233)

**Comment by rnewman** [comment]
The tab tray scrolls to the current active tab if you toggle to Private and back again. This regressed fairly recently in TestFlight. 

As someone with hundreds of open tabs, this is incredibly frustrating 😂

**Comment by data-sync-user** [comment]
➤ Sophie Amin commented:

note to self: one is not related to diffable datasource work

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Andres Furlan Daniel Dervishi , I confirm that the correct behavior should be the one presented below. I cannot reproduce the bug anymore on 132.1, either.

**Comment by data-sync-user** [comment]
➤ Andres Furlan commented:

Isabella maybe your PR fixed this then?

**Comment by data-sync-user** [comment]
➤ Daniel Dervishi commented:

Andres Furlan Just took a look and I’m still able to reproduce the bug, albeit in main – I haven’t tried version 132.1. Thank you for clarifying the behaviour, I’ll be sure to merge the changes. Would you like me to backport them into v133?
