### ISSUE TITLE
[Toolbar redesign] The address bar's highlight color for autocomplete suggestions is dark gray instead of light blue

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/firefox-ios#22405]
## Steps to reproduce
1. Launch FF and access any website.
1. Tap on the URL bar and start writing any website.
1. Observe the highlighted color.
### Expected behavior
The address bar's highlight color for autocomplete suggestions is dark gray.
### Actual behavior
The address bar's highlight color for autocomplete suggestion is dark gray instead of light blue.
### Device & build information

* Device: iPhone 15 Pro (17.5). 
* Build version: v9000 (46072) 
* First seen version: ? 
### Notes
Attachments: 

![image](https://github.com/user-attachments/assets/a0eaa93c-5311-4ae3-81cf-357586a09fd6)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-10237)

**Comment by data-sync-user** [comment]
➤ Winnie Teichmann commented:

Andrei Bodea this looks correct to me. Please see the design specs here ( https://www.figma.com/design/8fsCvtnweBkWGZ9NfL907l/__-Toolbar-Redesign?node-id=7770-247540&t=mIoKmJRduaRuiVic-4 ).

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v9000 (46854), with iPhone 15 (17.6).
