### ISSUE TITLE
[Toolbar redesign] The reader view icon shifts around when exiting the reader view mode

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/firefox-ios#22407]
## Steps to reproduce
1. Launch FF and access any webpage.
1. Enter the reader mode and then exit the reader mode.
1. Repeat step 2 a few times in a row and observe the reader view icon.
### Expected behavior
The reader view icon should not shift around from the toolbar.
### Actual behavior
The reader view icon shifts around when exiting the reader view mode.
### Device & build information

* Device: iPhone 15 Pro (17.5). 
* Build version: v9000 (46072) 
* First seen version: ? 
### Notes
Attachments: 

https://github.com/user-attachments/assets/fca3c0b0-6405-4aa8-ac87-40d021621d01

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-10239)

**Comment by cpeterso** [comment]
When we’re exiting reader view, we also know that the original page was reader view compatible. We can use that as a hint to assume the page we’re returning to is reader compatible. We can show the reader view icon immediately to avoid the shifting toolbar layout.

**Comment by cpeterso** [comment]
Here’s a recording of the bug. 

https://github.com/user-attachments/assets/8964e8a6-c3eb-4111-aca3-877f404b62d5

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v9000 (46854), with iPhone 15 (17.6).

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v133 (47063), with iPhone SE (17.5).
