### ISSUE TITLE
Addresses are suggested to be autofill instead of passwords when user tries to login

### ISSUE THREAD

**Issue by alinamoldovan84** [mozilla-mobile/firefox-ios#22400]
## Steps to reproduce
1. Make sure you are logged into the FF app with a valid FF account and you have at least one address saved 
2. Open gmail.com (make sure you are not logged in) -> user is redirected to the accounts.google.com to login 
3. Tap on the email field 

### Expected behavior
"Use saved **password**" should be available  

### Actual behavior
"Use saved **addresses**" is available  

### Notes
- sometimes if the user taps a second time on the field the correct option is displayed 
- the issue reproduces with other websites also: facebook.com, instagram.com

### Device & build information
* Device: iPhone 14+ (16.0.3), iPhone 15+ (18.0), iPhone 15 (17.5),  iPhone 15Pro (17.5) 
* Build version: V132 (46048) 
* First seen version: V130 

Attachments: 

https://github.com/user-attachments/assets/df546e57-ef9d-4fd1-9ec2-6824e483ddcf

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-10234)

**Comment by data-sync-user** [comment]
➤ Norberto Andres Furlan commented:

Issam Mani Nishant Bhasin can you take a look to this one?

**Comment by data-sync-user** [comment]
➤ Issam Mani commented:

I think FormAutofillHelper and LoginHelper are conflicting. I will take a look.

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Verified as fixed on v132 (46208) with iPhone 15 Pro (17.5), and iPhone 15 (17.6.1).
