### ISSUE TITLE
[Toolbar redesign] The address bar's highlight color for the selected text is light gray instead of light blue

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/firefox-ios#22403]
## Steps to reproduce
1. Launch FF and access any website.
1. Tap on the URL bar/link.
1. Observe the highlighted color.
### Expected behavior
The address bar's highlight color for the selected text is light gray
### Actual behavior
The address bar's highlight color for the selected text is light gray instead of light blue
### Device & build information

* Device: iPhone 15 Pro (17.5). 
* Build version: v9000 (46072) 
* First seen version: ? 
### Notes
Attachments: 

![image](https://github.com/user-attachments/assets/4c6cdd73-d927-4ff8-82c2-d6a543ac25cd)

![image](https://github.com/user-attachments/assets/4ead9f82-cfa9-4142-ad98-04f135707480)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-10236)

**Comment by data-sync-user** [comment]
➤ Winnie Teichmann commented:

Andrei Bodea this looks correct to me. Please see the design specs here ( https://www.figma.com/design/8fsCvtnweBkWGZ9NfL907l/__-Toolbar-Redesign?node-id=7770-247540&t=mIoKmJRduaRuiVic-4 ).

**Comment by data-sync-user** [comment]
➤ Adina Petridean commented:

Verified as fixed on v9000(46586) with iPhone 14 Pro Max (iOS 16.2).

!blue.jpeg|width=430,height=932,alt="blue.jpeg"!

**Comment by data-sync-user** [comment]
➤ Adina Petridean commented:

Verified as fixed on Firefox 133.0 (47063) with iPhone 14 Pro Max (iOS 16.2).
