### ISSUE TITLE
[Toolbar redesign]- No search suggestions are displayed when url is selected

### ISSUE THREAD

**Issue by DianaABarladeanu** [mozilla-mobile/firefox-ios#22415]
Prerequisites
User is enrolled in "New iOS toolbar" experiment treatment a.

**Steps to reproduce**

1. Install FF.
1. Make sure that "show search suggestions" toggle is enabled in settings.
1. Access a website.
1. Tap on the url.
1. Observe.

**Expected behavior**
The url is selected , the keyboard pops up and the search suggestions are displayed.

**Actual behavior**
The url is selected , the keyboard pops up but the search suggestions are NOT displayed.

**Device & build information**

* Device: iPhone 15 (17.5)
* Build version: v9000 (46086)
* First seen version: ? 

Notes
Attachments: 

https://github.com/user-attachments/assets/bdd199f1-3fc3-4ef5-8a4f-0919af40b603

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-10242)

**Comment by MattLichtenstein** [comment]
@thatswinnie is waiting until the user types to show search suggestions expected behavior? It seems to behave the same with the old toolbar as well

**Comment by PARAIPAN9** [comment]
I agree with @MattLichtenstein. As far as I know, suggestions should appear when the user starts typing in the address bar.

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Norberto Andres Furlan I logged this bug taking figma design into consideration, specifically the attached screenshot, where you can see the suggestions.

!Screenshot 2024-10-22 at 4.57.48 PM.png|width=327,height=584,alt="Screenshot 2024-10-22 at 4.57.48 PM.png"!
