### ISSUE TITLE
[Toolbar redesign] - Copied address is visible only after the website has opened, not when pasted

### ISSUE THREAD

**Issue by DianaABarladeanu** [mozilla-mobile/firefox-ios#22417]
Prerequisites
User is enrolled in "New iOS toolbar" experiment treatment a.

**Steps to reproduce**

1. Install FF.
1. Access a website.
1. Tap on the url.
1. Choose to copy it.
1. Open a new tab and tap on paste  and go.
1. Observe

**Expected behavior**
The address is correctly copied and displayed after paste.

**Actual behavior**
The address is not visible after paste, but only after the website has opened.

**Device & build information**

* Device: iPhone 15 (17.5)
* Build version: v9000(46086)
* First seen version: ? 

Notes
Attachments: 

https://github.com/user-attachments/assets/247868c7-7d44-4cf6-afb0-b6f7b1a88c9b

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-10243)

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v9000 (46854), with iPhone 15 (17.6).

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v133 (47063), with iPhone SE (17.5).
