### ISSUE TITLE
[Toolbar redesign] The border is not displayed under the URL bar until scrolling

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/firefox-ios#22423]
## Steps to reproduce
1. Launch FF and access the homepage.
1. Observe that the border below the URL bar is not displayed only after scrolling.
1. Long tap on the URL bar.
### Expected behavior
The border should be displayed.
### Actual behavior
The border is not displayed under the URL bar until scrolling.
### Device & build information

* Device: iPhone 15 Pro (17.5) 
* Build version: v9000 (46086) 
* First seen version: N/A 
### Notes
Note that at the bottom is always displayed.
This occurs with the Top bar being set to top.
Also, note that when setting the Top bar to the bottom, the border is always displayed.
Attachments:

https://github.com/user-attachments/assets/b58467fa-f00d-4bff-8fe8-b154b16a4ec3

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-10247)

**Comment by data-sync-user** [comment]
➤ Winnie Teichmann commented:

Andrei Bodea according to the design specs ( https://www.figma.com/design/8fsCvtnweBkWGZ9NfL907l/__-Toolbar-Redesign?node-id=7753-238343&t=mIoKmJRduaRuiVic-4 ) the border for the address toolbar when displayed on top should only be displayed when the homepage is scrolled. So what you are seeing is correct behavior.

**Comment by data-sync-user** [comment]
➤ Aarjav Pandya commented:

I would say this is for when a user is on the website, where it should show.

**Comment by data-sync-user** [comment]
➤ Winnie Teichmann commented:

Aarjav Pandya the specs say that even on a website the border under the address toolbar should only be shown when the website is scrolled for top placement. Is this wrong in Figma? 

And as the video for this issue shows the homepage, isn’t this behaving as expected?

**Comment by data-sync-user** [comment]
➤ Aarjav Pandya commented:

Hey Winnie Teichmann, yes, you are right. I tested it out, and unlike Android, there is no option to stop the toolbar from hiding. So it works, sorry for the confusion.
