### ISSUE TITLE
[Toolbar redesign] The URL reappears when scrolling after it was deleted via `x` button

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/firefox-ios#22427]
## Steps to reproduce
1. Launch FF and access any website.
1. Tap on the URL bar and then tap on the `x` button to delete the URL.
1. Scroll up and down.
### Expected behavior
The URL should not appear until pressing the back button from the toolbar.
### Actual behavior
The URL reappears when scrolling after it was deleted via `x` button.
### Device & build information

* Device: iPhone 15 Pro (17.5) 
* Build version: v9000 (46086) 
* First seen version: N/A 
### Notes
Attachments: 

https://github.com/user-attachments/assets/d77aa8fc-91e2-4a05-9bbe-2d9b1235dc2b

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXIOS-10249)

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on. v9000 (46854), with iPhone 15 (17.6).

**Comment by data-sync-user** [comment]
➤ Adina Petridean commented:

Verified as fixed on Firefox 133.0 (47063) with iPhone 14 Pro Max (iOS 16.2).
