### ISSUE TITLE
[Toolbar redesign] The focus of the URL moves away from the domain when long tap on the URL

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/firefox-ios#22420]
## Steps to reproduce
1. Launch FF and access `https://github.com/mozilla-mobile/firefox-ios/issues/22417`
1. Observe that the `badssl.com` domain is displayed.
1. Long tap on the URL bar.
### Expected behavior
When long tap on the URL it should always display it focusing on the domain part of the URL while ensuring the color differences.
### Actual behavior
The focus of the URL moves away from the domain when a long tap on the URL
### Device & build information

* Device: iPhone 15 Pro (17.5) 
* Build version: v9000 (46086) 
* First seen version: N/A 
### Notes
Attachments:

https://github.com/user-attachments/assets/9a43eb33-5d06-44cb-9e21-241a3a1c92b6

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-10244)

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Verified as fixed on v133 (46984) with iPhone 15 Pro (18.2).
