### ISSUE TITLE
[Toolbar Redesign] - Address displayed in edit mode after opening website with QR scan

### ISSUE THREAD

**Issue by DianaABarladeanu** [mozilla-mobile/firefox-ios#22475]
Prerequisites
User is enrolled in "New iOS toolbar" experiment treatment a.

**Steps to reproduce**

1. Install FF.
1. Tap on the address toolbar to go into edit mode.
1. Tap on the QR scan icon displayed in the quick access field on the right side.
1. Scan a code in order to open a website.
1. Tap on "allow" once the prompt is displayed.
1. Observe

**Expected behavior**
The webpage is opened. The url is not selected.

**Actual behavior**
The url is displayed in edit mode and the keyboard is up.

**Device & build information**

* Device: iPhone 15 (17.6.1), iPhone SE (18.0) 
* Build version: v9000 (46259)
* First seen version: ? 

Notes

Attachments: 

[https://github.com/user-attachments/assets/28e11e02-bb25-41dd-b0eb-23bf0b68a4ee](https://github.com/user-attachments/assets/28e11e02-bb25-41dd-b0eb-23bf0b68a4ee)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-10265)

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v9000 (46854), with iPhone 15 (17.6).

**Comment by data-sync-user** [comment]
➤ Adina Petridean commented:

Verified as fixed on Firefox 133.0 (47063) with iPhone 14 Pro Max (iOS 16.2).
