### ISSUE TITLE
TabTrayViewController UI: hard to dismiss tabs

### ISSUE THREAD

**Issue by LiuDeng** [mozilla-mobile/firefox-ios#2248]
Hope you can rewrite the TabTrayViewController . The collectionview is so hard to use when have only one or two cells for we have to move finger so far to swipe to dimiss。 Look at Safari , UC Internation，Chrome。 Their tab Tray are all design for easy to use even just one or two cells.

**Comment by sleroux** [comment]
@LiuDeng You also have the option to tap in the corner of the cell to remove/close the tab. Is that a better option?

**Comment by LiuDeng** [comment]
nono. absolute not. My main point is i do not want to move my finger so far or use another hand to to this. Like most Asia people ， my hand is not big as yours， but the screen is same as yours。When use 4.7 inc or 5.5 inc iphone，we can impossible to close the first two tab on the top use just single hand

**Comment by sleroux** [comment]
Oh I see. The reach to the top of the screen to close the tab is the issue. I thought you were referring to the amount of distance needed to swipe the cell away.

I agree. I'd imagine in most cases users would be only a few tabs open on mobile devices so the interaction of reaching to the top of the screen would happen often. I think in this regard Chrome has done a good job by making the tabs full sized for easier reach. I personally find Safari's tab management pretty annoying since you have to try selecting between the other tabs.

**Comment by LiuDeng** [comment]
Sorry for my poor English and slow type speed。I once to try to write one like UC https://itunes.apple.com/us/app/uc-browser-fast-browsing-powerful/id1048518592?mt=8 It has the best user experience of the tab tray。But i fail ， it is too hard  for me to implement that。Really hope you can download and see。
The Chrome is good , Safari's tab  is not good but have a good point for also have full size so can easy to close.
I have used firefox for so long time  and really hope firfox ios can fix this。
Thank you so much for your great contribution~
Best Wishes！~

**Comment by LiuDeng** [comment]
No matter UC or Chrome like is great。 Even Safari style is acceptable~

**Comment by sleroux** [comment]
UC browser one is pretty nice. It feels very similar to navigating between apps on Android where you can scroll forwards/backs to reveal the tab you want to delete near the bottom of the screen.

I've filed a bug to investigate option: https://bugzilla.mozilla.org/show_bug.cgi?id=1319421

Thanks for the feedback!

**Comment by LiuDeng** [comment]
Yes it is。 as you mention i suddenly find uc one is really same as android app switch。
Thank you so much~！

**Comment by ionicc** [comment]
I think the setting of tabs in a 3d format such as the google chrome will be a better option but the tab management system right now Is also good in its own sense. It gives a much better overview of the contents of the page and it gives the user a much better UX.

**Comment by LiuDeng** [comment]
@ionicc do not give user too much choice  , them will feel uncomfortable for when they choose one they lose others。Just give user what is really best.

**Comment by shree007** [comment]
@sleroux Sir, instead of 2 column and multiple rows,  one column may be nice  in tabTrayViewController.

**Comment by sleroux** [comment]
@shree007 This is actually already an option! If you go to settings and turn off 'Compact Tabs' you'll see a single column layout for the cells.

**Comment by shree007** [comment]
@sleroux  Yeah got that. thanks . 

Please see this issue I filed it.    https://github.com/mozilla-mobile/firefox-ios/issues/2425
