### ISSUE TITLE
The app crashes when attempting to scan an invalid URL on specific devices

### ISSUE THREAD

**Issue by AdinaPetridean** [mozilla-mobile/firefox-ios#22505]
## Steps to reproduce
1. Install Firefox. 
1. From the search bar, tap on QR code scanner.
1. On desktop, go to https://zxing.appspot.com/generator/ select  URL and tap on "Generate" button.
1. Using the iOS mobile, scan the generated URL code from desktop.
1. Observe the behavior.

### Expected behavior
A popup with the message 'Allow Firefox to open http://? Yes/No' is displayed on the screen.

### Actual behavior
The app crashes.

### Device & build information
* Device: iPhone 14 Pro Max (iOS 16.2), iPhone 14 (16.4)
* Build version: Firefox v9000 (46300), Firefox 132.0(46292)
* First seen version: Firefox 129.0

### Notes
Please note, this issue is ONLY reproducible with invalid URLs.
This issue is not reproducible on iPhone 15 Pro (17.5) and iPhone 15(17.6).

### Attachments: 
https://github.com/user-attachments/assets/1cc4dc7f-5ea2-4b13-91ba-590b00997b18

[crash.ips.zip](https://github.com/user-attachments/files/17341792/crash.ips.zip)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-10275)

**Comment by data-sync-user** [comment]
➤ Adina Petridean commented:

Verified as fixed on v9000 (47393) and Firefox 133.0 9 (47401) with iPhone 14 Pro Max (iOS 16.2).
