### ISSUE TITLE
[Toolbar Redesign][Accessibility] `Search or enter address` is said twice while voice over is on

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/firefox-ios#22507]
## Steps to reproduce
1. Launch FF and access the homepage.
1. Turn on the voice-over.
1. Tap on the search bar on the toolbar.
### Expected behavior
`Search or enter address` should be said once while the voice-over is on.
### Actual behavior
`Search or enter address` is said twice while the voiceover is on.
### Device & build information

* Device: iPhone 15 Pro (17.5). 
* Build version: v9000 (46300) 
* First seen version: N/A 
### Notes
Attachments: 

https://github.com/user-attachments/assets/d722361b-6af2-4e70-b8ef-1ae5e82d1834

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-10277)

**Comment by data-sync-user** [comment]
➤ Adina Petridean commented:

Verified as fixed on v9000(46854) with iPhone 14 Pro Max (iOS 16.2).

!search.mp4|width=886,height=1920,alt="search.mp4"!

**Comment by data-sync-user** [comment]
➤ Adina Petridean commented:

Verified as fixed on Firefox 133.0 (47063) with iPhone 14 Pro Max (iOS 16.2).
