### ISSUE TITLE
[Toolbar Redesign]-Missing autocomplete suggestion for a word with spaces in front 

### ISSUE THREAD

**Issue by dragosb01** [mozilla-mobile/firefox-ios#22530]
## Steps to reproduce
Select the url bar and type "    moz"
### Expected behavior
"Mozilla.org" autosuggestion should appear on the url bar 
### Actual behavior
The autosuggestion is missing
### Device & build information
* Device: iPhone 15 Pro (17.5)
* Build version:  133.0
* First seen version: Yes
### Notes
Auto test: testMixedCaseAutocompletion
TC: https://mozilla.testrail.io/index.php?/cases/view/2334653
Attachments: 
<img width="376" alt="Screenshot 2024-10-14 at 14 22 34" src="https://github.com/user-attachments/assets/78b68d31-436c-4500-9744-f68688709d9a">

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-10283)

**Comment by data-sync-user** [comment]
➤ Adina Petridean commented:

Verified as fixed on v9000(46586) with iPhone 14 Pro Max (iOS 16.2).

!moz.mp4|width=886,height=1920,alt="moz.mp4"!

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v133(47063), with iPhone 15 (17.6).
