### ISSUE TITLE
Synced tabs history is not deleted if you choose "everything" option

### ISSUE THREAD

**Issue by DianaABarladeanu** [mozilla-mobile/firefox-ios#22532]
**Steps to reproduce**
1. Install FF.
2. Sync with a valid account.
3. Generate some history on desktop and sync.
4. On the phone, go to settings --> history.
5. Tap on everything --> the history section seems to be emptied.
6. Access another library section then return to history.
7. Observe.

 **Expected behavior**
All history is deleted.

 **Actual behavior**
The synced tabs history is not really deleted.
Only if you tap on the "today" or "today and yesterday" options, synced tabs history remains deleted.

 **Device & build information**
* Device: iPhone 15 (17.6.1)
* Build version: v132 (46361)
* First seen version: ?

Notes
Attachments: 

https://github.com/user-attachments/assets/a8cb1263-200e-4621-ba0b-f8e687bdf998

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-10284)

**Comment by data-sync-user** [comment]
➤ Alexandru Farcasanu commented:

I can’t reproduce this issue. After a sync with Diana, this issue seems to be fixed.
Closed!
