### ISSUE TITLE
[Toolbar Redesign] The URL is not selected after taping again on it after certain steps

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/firefox-ios#22533]
## Steps to reproduce
1. Launch FF and access any website.
2. Tap on the URL (the URL is selected) and tap on the x button.
3. Scroll (the URL reappears) 
4. Tap on the URL again.
### Expected behavior
The URL should be selected.
### Actual behavior
The URL is not selected after taping again on it after certain steps
### Device & build information
* Device: iPhone 15 Pro (17.5) 
* Build version: v9000 (46355) 
* First seen version: ? 
### Notes
Attachments: 

https://github.com/user-attachments/assets/376dbe76-b1df-4a44-9c71-c9f0e8c83af5

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-10285)

**Comment by MattLichtenstein** [comment]
The URL reappearing after being cleared via "x" was a bug that was resolved in #22427 

Closing this bug as it is no longer applicable
