### ISSUE TITLE
[Toolbar Redesign] The URL reappears when rotating from landscape to portrait mode or vice-versa after deleting it

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/firefox-ios#22540]
## Steps to reproduce
1. Launch FF and access any website.
2. Tap on the URL > Tap on the `x` button.
3. Rotate the device in landscape mode.
### Expected behavior
The URL should not reaper and the homepage should still be displayed.
### Actual behavior
The URL reappears when rotating from landscape to portrait mode or vice-versa after deleting it.
### Device & build information
* Device: iPhone 15 Pro (17.5) 
* Build version: v9000 (46355) 
* First seen version: ? 
### Notes
Attachments: 

https://github.com/user-attachments/assets/04e4e8e9-76de-4cb6-a219-64434e3a1d3f

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-10290)

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v9000 (46854), with iPhone 15 (17.6).
