### ISSUE TITLE
Carthage issue

### ISSUE THREAD

**Issue by hamilyjing** [mozilla-mobile/firefox-ios#2255]
could not download 

github "SnapKit/SnapKit"                    "0.22.0"
github "swisspol/GCDWebServer"              "3.3.2"
github "mozilla-mobile/web_metadata_ios"    "0.0.6"
github "jrendel/SwiftKeychainWrapper"       "Swift2.3"
github "thebnich/XCGLogger"                 "trycatch"

others are ok

**Comment by AaronMT** [comment]
Are you executing `bootstrap.sh` ?

This works for me.

> $ ./bootstrap.sh 
*** Fetching readability
*** Fetching web_metadata_ios
*** Fetching onyx_ios
*** Checking out Alamofire at "3.5.0"
*** Checking out Deferred at "7d3d3230133db71544e60dfa7fa3d095361398db"
*** Checking out Fuzi at "0.4.0"
*** Checking out GCDWebServer at "3.3.2"
*** Checking out ios_sdk at "v4.10.2"
*** Checking out KIF at "v3.5.1"
*** Checking out libPhoneNumber-iOS at "0.8.11"
*** Checking out onepassword-extension at "d99f5d7a4c7328f8e3a8d1e7aff455d1072e0c19"
*** Checking out onyx_ios at "0.0.5"
*** Checking out readability at "ac878bf7c15b47d67e7b947584ca108398dd48a4"
*** Checking out SDWebImage at "3.7.4"
*** Checking out SnapKit at "0.22.0"
*** Checking out SwiftKeychainWrapper at "701a27dfc4502645122f8db5e7be4479e85e831c"
*** Checking out web_metadata_ios at "0.0.6"
*** Checking out XCGLogger at "55613b29c09caaf1ff75d930f27e0b69115b7a56"

and then it enters the building scheme phase

**Comment by KeithPiTsui** [comment]
I guess your issue was about network problem, like being blocked or so.

**Comment by m13026178198** [comment]
executing bootstrap.sh. If it does not work and  you live in china ,please try to use VPN.
