### ISSUE TITLE
But

### ISSUE THREAD

**Issue by yummyyyumsss** [mozilla-mobile/firefox-ios#22574]
### Device & build information
* Device: ? 
* Build version: ? 
* First seen version: ? 
### Notes
Attachments: 

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-10305)

**Comment by mattreaganmozilla** [comment]
@yummyyyumsss Can you please include details about the bug you're experiencing? Closing in the meantime as this ticket is currently blank.
