### ISSUE TITLE
Lock icon does not appear on awesome bar for untrusted connection

### ISSUE THREAD

**Issue by clarmso** [mozilla-mobile/firefox-ios#22600]
## Steps to reproduce

1. Open www.badssl.com
2. Tap "Expired" under "Certificate".
3. Wait until the page load.
4. Look for the lock icon next to the URL.

See `XCUITests/TrackingProtectionTests/testLockIconSecureConnection`

I can reproduce the issue manually

### Expected behavior

On release/v132, the slashed lock icon is present:
![Simulator Screenshot - iPhone 15 - 2024-10-16 at 15 05 09](https://github.com/user-attachments/assets/44096ab6-a75a-4360-9e36-8f6ce82b7195)

### Actual behavior

No lock icon is seen:
![Simulator Screenshot - iPhone 15 - 2024-10-16 at 14 51 08](https://github.com/user-attachments/assets/a47dac01-ef67-41cf-a58a-d42226c88c7c)

### Device & build information
* Device: iPhone 15 simulator
* Build version: `main`
* First seen version: Oct 14 (https://github.com/mozilla-mobile/firefox-ios/pull/22474)
### Notes
Attachments: 

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-10319)

**Comment by data-sync-user** [comment]
➤ Norberto Andres Furlan commented:

Alexandru Farcasanu can you check this one? Can it be related to any change on Unified Panel?

**Comment by data-sync-user** [comment]
➤ Norberto Andres Furlan commented:

Andrei Bodea for visibility.

**Comment by clarmso** [comment]
I've confirmed that the regression occurs since this PR: https://github.com/mozilla-mobile/firefox-ios/pull/22474.

**Comment by mattreaganmozilla** [comment]
I self-assigned this ticket, will take a look as soon as I have a chance. We need to be careful that whatever fix is implemented for this does not regress the security fix added for https://mozilla-hub.atlassian.net/browse/FXIOS-7328.

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Thanks, Norberto Andres Furlanwill keep an eye on this.

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Verified as fixed on v133 (47401) with iPhone 15 Pro (18.2).
