### ISSUE TITLE
Compilation error in Xcode 16.

### ISSUE THREAD

**Issue by guojin2020** [mozilla-mobile/firefox-ios#22629]
Hey there! Thanks for using Firefox!
I followed the steps, but encountered an error in Xcode 16.

If you are having issues with using Firefox make sure to check https://support.mozilla.org/en-US/products/ios first
<img width="360" alt="image" src="https://github.com/user-attachments/assets/3aff6a8f-dba4-4c3b-87f3-862ff33620e7">
<img width="614" alt="image" src="https://github.com/user-attachments/assets/821cf8b6-b635-4c13-8dc2-a6e6970a8048">

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-10328)

**Comment by afurlan-firefox** [comment]
We don't support Xcode 16 yet, but we will do it soon. Keep an eye on it! Thanks
