### ISSUE TITLE
How to build the project

### ISSUE THREAD

**Issue by CodeLiar** [mozilla-mobile/firefox-ios#2263]
I follow the steps to build the project, but it really can not succeed;
I used xcode8 and xcode8.1 .
Which branch and which version of Swift can i used to run the project successful;
I need help.
Thanks!

**Comment by mauryat** [comment]
Hi @CodeLiar, I'm a contributor myself. Could you share the error you see when you run the project?

It [should run with Xcode 8](https://github.com/mozilla-mobile/firefox-ios/#building-the-code). Though I haven't tried running on Xcode 8.1, I think it should be fine. The project uses Swift 2.3 at the moment. But, you wouldn't have to specify it as it is already configured in the [project files](https://github.com/mozilla-mobile/firefox-ios/blob/master/Client.xcodeproj/project.pbxproj) that you get from a git clone of the project.

You could either [chat on IRC or email](https://github.com/mozilla-mobile/firefox-ios/#getting-involved) queries in the future. New issues are mainly used for discussing bugs, ideas and enhancements 😄 For now, we can continue on this issue!

**Comment by CodeLiar** [comment]
Thanks very much! Those errors disappeared now. And I don't know why. Now I need to take against   the GFW. @mauryat
