### ISSUE TITLE
[Toolbar Redesign] New toolbar's < back button is obscured by iPhone's Dynamic Island in the Homepage in landscape orientation

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/firefox-ios#22653]
## Steps to reproduce

1. Manually enroll in the iOS New Toolbar experiment on TestFlight.
2. Rotate your phone to landscape orientation.
3. Tap the toolbar's `+` button or address bar to open the Homepage.
4. Try to exit the Homepage screen.

### Expected behavior

The old toolbar has a `<` back button to exit the Homepage screen:

![image](https://github.com/user-attachments/assets/40ba0516-4a48-467d-aece-7e61a36ad681)

### Actual behavior

The new toolbar's `<` back button to exit the Homepage screen is obscured by my iPhone's Dynamic Island:

![image](https://github.com/user-attachments/assets/de9ca8e3-2e23-4790-bae7-20156ba826d7)

### Device & build information

* Device: iPhone 15 Plus running iOS 18.0.1
* Build version: TestFlight Nightly 9000 (46530)
* First seen version: I don’t know. At least more than a week ago.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-10336)

**Comment by data-sync-user** [comment]
➤ Matt Lichtenstein commented:

Hey Aarjav Pandya, do you have any recommendations here?

**Comment by data-sync-user** [comment]
➤ Aarjav Pandya commented:

Hey Matt, I have updated the padding for the app switcher here ( https://www.figma.com/design/8fsCvtnweBkWGZ9NfL907l/__-Toolbar-Redesign?node-id=26701-237983&t=Ux9GCZ0ujgfnKCn4-4 ).

**Comment by data-sync-user** [comment]
➤ Matt Lichtenstein commented:

Thanks Aarjav Pandya  - reassigning to myself

**Comment by data-sync-user** [comment]
➤ Matt Lichtenstein commented:

Aarjav Pandya was this comment meant for https://mozilla-hub.atlassian.net/browse/FXIOS-10337 ( https://mozilla-hub.atlassian.net/browse/FXIOS-10337|smart-link )

**Comment by data-sync-user** [comment]
➤ Aarjav Pandya commented:

You are right, my bad, here are the links for this one. 
Homepage - https://www.figma.com/design/8fsCvtnweBkWGZ9NfL907l/__-Toolbar-Redesign?node-id=26560-184043&t=Ux9GCZ0ujgfnKCn4-4 ( https://www.figma.com/design/8fsCvtnweBkWGZ9NfL907l/__-Toolbar-Redesign?node-id=26560-184043&t=Ux9GCZ0ujgfnKCn4-4|smart-link ) 
Webpage - https://www.figma.com/design/8fsCvtnweBkWGZ9NfL907l/__-Toolbar-Redesign?node-id=26560-189817&t=Ux9GCZ0ujgfnKCn4-4 ( https://www.figma.com/design/8fsCvtnweBkWGZ9NfL907l/__-Toolbar-Redesign?node-id=26560-189817&t=Ux9GCZ0ujgfnKCn4-4|smart-link )

**Comment by data-sync-user** [comment]
➤ Matt Lichtenstein commented:

Aarjav Pandya those links point to iPad screenshots, does landscape iPhone follow the same spec?

**Comment by data-sync-user** [comment]
➤ Aarjav Pandya commented:

Yes, iPad should follow the same designs.

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Verified as fixed on v133 (46984) with iPhone 15 Pro (18.2).
