### ISSUE TITLE
[Toolbar Redesign] iOS's app switcher handle is located inside the address field in landscape orientation

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/firefox-ios#22654]
## Steps to reproduce

1. Manually enroll in the iOS New Toolbar experiment on TestFlight.
2. Rotate your phone to landscape orientation.
3. Look at iOS's app switcher handle at the bottom edge of the screen.

### Expected behavior

The old toolbar's address field has enough vertical padding that iOS's app switcher handle is outside the address field:

![image](https://github.com/user-attachments/assets/fe7c24e1-19e6-4115-aef6-4bffe9f8bffa)

### Actual behavior

The new toolbar's address field has less vertical padding, which causes the iOS's app switcher handle to be located inside the address field:

![image](https://github.com/user-attachments/assets/50823ddd-1f50-4edd-bbda-6a8defe83031)

### Device & build information

* Device: iPhone 15 Plus running iOS 18.0.1
* Build version: TestFlight Nightly 9000 (46530)
* First seen version: I don’t know. At least more than a week ago.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-10337)

**Comment by data-sync-user** [comment]
➤ Matt Lichtenstein commented:

Hey Aarjav Pandya, do you have any recommendations here?

**Comment by data-sync-user** [comment]
➤ Norberto Andres Furlan commented:

Aarjav Pandya in my opinion the old toolbar has too much padding, but the new one at least should have a bit of padding to not conflict with the black bottom bar.

**Comment by data-sync-user** [comment]
➤ Aarjav Pandya commented:

I agree, there should be padding in this case. Here is the link to it. → https://www.figma.com/design/8fsCvtnweBkWGZ9NfL907l/__-Toolbar-Redesign?node-id=26701-237983&t=Ux9GCZ0ujgfnKCn4-4 ( https://www.figma.com/design/8fsCvtnweBkWGZ9NfL907l/__-Toolbar-Redesign?node-id=26701-237983&t=Ux9GCZ0ujgfnKCn4-4|smart-link )

**Comment by data-sync-user** [comment]
➤ Adina Petridean commented:

Verified as fixed on v9000( 46854) with iPhone 14 Pro Max (iOS 16.2).

!bbc.com.jpeg|width=932,height=430,alt="bbc.com.jpeg"!

**Comment by data-sync-user** [comment]
➤ Adina Petridean commented:

Verified as fixed on Firefox 133.0 (47063) with iPhone 14 Pro Max (iOS 16.2).
