### ISSUE TITLE
Tab tray favicons flash when long pressing a tab

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/firefox-ios#22683]
## :page_facing_up: Description
This issue is located inside the new Tab Tray implementation.

## :1234:  Steps to reproduce
1. Open the tab tray with multiple tabs opened. 
1. Long press on a tab to open a preview of the tab. 

### Expected behavior
The tabs’ favicons should not flash.

### Actual behavior
The tabs’ favicons flash before the preview opens. 

### Device & build information
* Device: iPhone 15 Plus running iOS 18.0.1
* Build version: TestFlight Nightly 9000 (46632) and Firefox 131.1
* First seen version: I don’t know. I can reproduce this bug in the oldest TestFlight 9000 build available on my iPhone, but I don’t recall noticing the flashing favicons until recently. Maybe this flashing issue was a regression from when I updated from iOS 17 to 18?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-10352)

**Comment by cpeterso** [comment]
Here is a screen recording of the flashing favicons:

https://github.com/user-attachments/assets/5d084ec8-2f78-42d1-9d72-7ba66a9e83c0

**Comment by data-sync-user** [comment]
➤ Andres Furlan commented:

I think this is fixed by Sophie Amin PR. It is already merged in nightly. Alina Moldovan can you confirm? Thanks!

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v9000 (46854), with iPhone 15 (17.6)

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v133 (47188), with iPhone 15 (17.6)
