### ISSUE TITLE
Enable Address Autofill Phase 2 by default for Canada and US

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#22707]
Enable Address Autofill Phase 2 by default for Canada and US

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-10362)

**Comment by nbhasin2** [comment]
https://github.com/mozilla-mobile/firefox-ios/blob/main/firefox-ios/Client/Frontend/Autofill/Address/AddressUtility/AddressLocaleFeatureValidator.swift#L7-L14

@issammani should double check what we did here 🤔

**Comment by data-sync-user** [comment]
➤ Issam Mani commented:

Yes. So what Nish shared enabled phase 1 by default for all CA and US users. We can do the same for phase 2 (we will need to swap this ( https://github.com/mozilla-mobile/firefox-ios/blob/c87c57212acff5cb24fb01b31a16d4340e01dd30/firefox-ios/Client/Frontend/Autofill/Address/AddressListViewModel.swift#L38 ) with the flag Nish shared ). But aren’t we at 40% right now of US and CA users for phase 2 ? I thought we want to go with the experiment until 100% and then enable by default. Maybe I am missing something Andres Furlan

**Comment by data-sync-user** [comment]
➤ Andres Furlan commented:

Issam Mani You are right, I will increase with the Nimbus rollout. Should we enable it by default on 133?

**Comment by data-sync-user** [comment]
➤ Issam Mani commented:

That works. I can open a PR to enable it by default on 133 😄
