### ISSUE TITLE
Weird animation with customize homepage button after changing the wallpaper

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#22714]
**Steps to reproduce**

1. Install FF.
1. Go to customize homepage and change the wallpaper.
1. Tap on “view“ and observe customize homepage button.

**Expected behavior**

The button’s edges are rounded. There is no weird animation happening.

**Actual behavior**
The button displays sharp corners for a second or so, then they change to rounded ones.

**Device & build information**

* Device: iPhone 15 (17.6.1)
* Build version: v132 (46741)
* First seen version: ?

Notes
Attachments:

!RPReplay_Final1729675875.mp4|width=590,height=1280,alt="RPReplay_Final1729675875.mp4"!

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXIOS-10365)

**Comment by hemche** [comment]
![IMG_0394](https://github.com/user-attachments/assets/a622a209-7258-4071-96a3-80d4baeb981a)

**Comment by data-sync-user** [comment]
➤ Alexandru Farcasanu commented:

Closed! It doesn’t reproduce anymore!
