### ISSUE TITLE
[Toolbar Redesign]Reader view button isAccessibilityElement false

### ISSUE THREAD

**Issue by dragosb01** [mozilla-mobile/firefox-ios#22733]
Reach any website where reader view can be selected.
The functionality works as expected, but the element is disabled from accessibility point of view.
Because of that on the automation level we cannot validate for example if the button is selected.

### Device & build information
* Device: iPhone 15, iOS 17.5
### Notes
Attachments: 

<img width="301" alt="Screenshot 2024-10-24 at 10 37 31" src="https://github.com/user-attachments/assets/2337ae9b-4345-423c-8b29-d36be6b715e3">
<img width="646" alt="Screenshot 2024-10-24 at 10 29 50" src="https://github.com/user-attachments/assets/562eda70-7571-4017-ba12-e38edcf72d0c">
<img width="389" alt="Screenshot 2024-10-24 at 10 29 13" src="https://github.com/user-attachments/assets/15c7639a-9e07-44ac-b0ac-810db850eb6b">

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-10376)

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Verified as fixed on v133 (46984) with iPhone 15 Pro (18.2).
