### ISSUE TITLE
Address bar shows the reader view button in PDF viewer mode

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/firefox-ios#22730]
## Steps to reproduce

1. Load https://arxiv.org/abs/2310.09423
2. See that the address bar shows the reader view button. 
3. Click the “View PDF” button.  

### Expected behavior

Firefox should open the PDF in PDF viewer mode and the reader view button should disappear because it has no effect in the PDF viewer. 

### Actual behavior

The PDF viewer opens the PDF in PDF viewer mode as expected, but the reader view button is still shown even though it has no effect in the PDF viewer. 

![image](https://github.com/user-attachments/assets/1f72c21a-afd3-4796-af04-82d31740e4f0)

### Device & build information

* Device: iPhone 15 Plus running iOS 18.0.1
* Build version: TestFlight Nightly 9000 (46530)
* First seen version: I don’t know. This bug is not a recent regression. I can reproduce it in older TestFlight builds.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-10373)

**Comment by data-sync-user** [comment]
➤ Andres Furlan commented:

Issam Mani can you take a look to this one?

**Comment by data-sync-user** [comment]
➤ Issam Mani commented:

Oops missed this. Will take a look tomorrow 😄

**Comment by data-sync-user** [comment]
➤ Issam Mani commented:

nvm it was an easy fix: https://github.com/mozilla-mobile/firefox-ios/pull/22844 ( https://github.com/mozilla-mobile/firefox-ios/pull/22844 )

**Comment by data-sync-user** [comment]
➤ Adina Petridean commented:

Verified as fixed on v9000 (47393) with iPhone 14 Pro Max (iOS 16.2).

!read button.jpeg|width=430,height=932,alt="read button.jpeg"!

**Comment by data-sync-user** [comment]
➤ Alina Moldovan commented:

Verified as fixed using FF v133.0 (47401) and iPhone 15+ (18.0) while new toolbar redesign experiment is on. 

The issue still reproduces using the old toolbar. Andres Furlan Issam Mani  Could you please confirm that this is expected?

Thanks!

**Comment by data-sync-user** [comment]
➤ Alina Moldovan commented:

Confirmed with Andres Furlan that this is at the expected behavior.
