### ISSUE TITLE
[Menu Redesign] Menu CFR's text is cut off: "Find what you need faster, fro..."

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/firefox-ios#22779]
## Steps to reproduce

1. Manually enroll in the "iOS Menu Redesign" experiment.
2. Open the menu.

### Expected behavior

"Find what you need faster, from private browsing to save actions."

@DianaABarladeanu's screenshot of the CFR on her iPhone 15:

![image](https://github.com/user-attachments/assets/018ad8cf-5a37-4a35-b5d4-25342b0ece1d)

### Actual behavior

"Find what you need faster, fro..."

My screenshot of the CFR on my iPhone 15 Plus, which has a larger screen that the iPhone 15:

![image](https://github.com/user-attachments/assets/8839511d-2e4e-4cd0-a86d-4647a912e693)

### Device & build information

* Device: iPhone 15 Plus running iOS 18.0.1
* Build version: TestFlight Nightly 9000 (46530)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-10392)

**Comment by cpeterso** [comment]
I see that Diana's screenshot is on the homepage, not a web page. (Our screenshots have different menu items.) Maybe that makes a difference?

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v133 (47343), with iPhone 16 (18.1).
