### ISSUE TITLE
[Menu Redesign] I'm signed into my Firefox Account, but the new menu shows me as signed out and won't let me sign in

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/firefox-ios#22780]
## Steps to reproduce

1. Sign into a Firefox Account.
2. Manually enroll in the "iOS Menu Redesign" experiment.
3. Open the menu.

### Expected behavior

The menu should show that I'm signed into my Firefox Account.

### Actual behavior

I'm signed into my Firefox Account, but the new menu:
1. Shows "Sign in" as if I'm not signed in.
2. Tapping "Sign in" does nothing, so how do I sign in?

![image](https://github.com/user-attachments/assets/056df2b0-0500-48c3-8796-4d830dd2af3c)

### Device & build information

* Device: iPhone 15 Plus running iOS 18.0.1
* Build version: TestFlight Nightly 9000 (46530)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-10393)

**Comment by data-sync-user** [comment]
➤ Chris Peterson commented:

works for me now
