### ISSUE TITLE
[Toolbar Redesign][Accessibility] The reader view button is read twice when selected/tapped

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/firefox-ios#22831]
**Steps to reproduce**
1. Launch FF and access any webpage with a reader view.
1. Turn on voice-over.
1. Select/double-tap on the reader view button.

**Expected behavior**
Reader view should be read only once.

**Actual behavior**
The reader view button is read twice when selected/tapped

**Device & build information**
* Device: iPhone 15 Pro (18.2) 
* Build version: v133 (46984) 
* First seen version: ? 

Notes

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXIOS-10428)

**Comment by data-sync-user** [comment]
➤ Adina Petridean commented:

Verified as fixed on Firefox 9000(47058) with iPhone 14 Pro Max (iOS 16.2).

!readerView.mp4|width=886,height=1920,alt="readerView.mp4"!
