### ISSUE TITLE
[Menu Redesign] The drag handler changes color when switching to another app and back

### ISSUE THREAD

**Issue by Piratesarereal** [mozilla-mobile/firefox-ios#22859]
## Steps to reproduce
- Open the menu
- Switch between firefox beta app and some other app. 
### Expected behavior
- the color the drag handler should not change. It should stay the same. 
### Actual behavior
- It changes when you switch back to the firefox app. 
### Device & build information
* Device: Firefox Beta
* Build version: ? 
* First seen version: ? 
### Notes
Attachments: 

[

https://github.com/user-attachments/assets/483b46fd-d4ae-4570-a790-8ece90882ed3

](url)
In the video, the second time I come back to the app, the drag handler switches color.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-10446)

**Comment by data-sync-user** [comment]
➤ Chris Peterson commented:

Aarjav says this bug only happens in light mode.

**Comment by data-sync-user** [comment]
➤ Roux Buciu commented:

see comment here ( https://mozilla-hub.atlassian.net/browse/FXIOS-10441?focusedCommentId=960728 )
