### ISSUE TITLE
[Menu Redesign] Fix UI issues for the profile icon on the menu. 

### ISSUE THREAD

**Issue by Piratesarereal** [mozilla-mobile/firefox-ios#22855]
## Steps to reproduce
- Open the menu and look at the profile icon
### Expected behavior

- The margin on the left of the profile icon needs to be 16dp. 
- Use the correct icon size for profile icon, we need to use 24*24dp icon size, but we have implemented 20*20 dp icon.
- The padding between the icon+background and sign in text should be 12dp. 

### Actual behavior

- Wrong padding and size is being used

### Device & build information
* Device: ? Firefox Beta
* Build version: ? 
* First seen version: ? 
### Notes
Attachments: 

![image](https://github.com/user-attachments/assets/0da1f976-f03d-48af-a6c7-6b3b43bd4731)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-10442)

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Validated on v133 (47343), with iPhone 16 (18.1).
