### ISSUE TITLE
[Menu Redesign] Fix the text style for secondary text for the list item 

### ISSUE THREAD

**Issue by Piratesarereal** [mozilla-mobile/firefox-ios#22856]
## Steps to reproduce

- Open the menu

### Expected behavior

- The text should look like caption 1. 

### Actual behavior

- The implemented text style looks more like caption 2 rather than caption 1.
- The code says we have implemented caption 1. 
- There is something weird going on here because we are using caption 2 styling for the highlighted parts.

### Device & build information
* Device: Firefox Beta
* Build version: ? 
* First seen version: ? 
### Notes
Attachments: 

![image](https://github.com/user-attachments/assets/af59f25e-11ce-4d84-871a-dfbd588f404f)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-10444)

**Comment by data-sync-user** [comment]
➤ Chris Peterson commented:

Aarjav says this bug is also reproducible with the old settings menu. Winnie says the code is referencing the correct caption 1 text style, but that’s not what we see in the app.

**Comment by data-sync-user** [comment]
➤ Cyndi Chin commented:

Chris Peterson What devices are you using to compare? Can you verify with the same device that was used for the Figma design?

This is what I see when I check the simulator, you can see that it looks similar to design with caption 1 and also matches with our other texts using caption 1. 
The “implemented device“ seems to be different, so the font size may look different on different devices with various resolutions.

!simulator_screenshot_16F77E0F-8BBC-4FCA-85B0-D9DA2B445A15.png|width=1179,height=2556,alt="simulator_screenshot_16F77E0F-8BBC-4FCA-85B0-D9DA2B445A15.png"!

**Comment by data-sync-user** [comment]
➤ Chris Peterson commented:

{quote}Chris Peterson What devices are you using to compare? Can you verify with the same device that was used for the Figma design?{quote}

Cyndi Chin - I was just relaying a comment from Aarjav. The differences in the text size are so small that I can’t tell whether I’m experiencing the small text bug on my iPhone. 🤓

**Comment by data-sync-user** [comment]
➤ Cyndi Chin commented:

Thanks Chris Peterson ! I got on a call with Aarjav Pandya , and it seems this issue is resolved using the latest build as well as ensuring that in Apple’s settings, the font size is configured for the default size. 

!image-20241114-201203.png|width=750,height=1334,alt="image-20241114-201203.png"!

**Comment by data-sync-user** [comment]
➤ Chris Peterson commented:

Aarjav says updating iOS on his phone fixed the menu grabber color and text size problems.
