### ISSUE TITLE
[Menu Redesign] Use the correct solid icon for the ‘remove from shortcuts’ feature

### ISSUE THREAD

**Issue by Piratesarereal** [mozilla-mobile/firefox-ios#22860]
## Steps to reproduce
- Open the menu
- Save a website to shortcuts
### Expected behavior
- a solid-filled icon should be used. [Link](https://www.figma.com/design/Kv7wWr8vH6AQrGhu9vmjdE/Mobile-Icons?node-id=3848-579&t=YlBiTU888CJYh3zn-4) to icon 
### Actual behavior
- a outlined icon is being used. 
### Device & build information
* Device: Firefox Beta
* Build version: ? 
* First seen version: ? 
### Notes
Attachments: 

![image](https://github.com/user-attachments/assets/3a9195e8-fd15-49bc-a757-d492609bb7ef)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-10447)

**Comment by data-sync-user** [comment]
➤ Adina Petridean commented:

Verified as fixed on Firefox 134.0 (48265) with iPhone 14 Pro Max (iOS 16.2).

!remove.jpeg|width=430,height=932,alt="remove.jpeg"!
