### ISSUE TITLE
[Menu Redesign] fix the height of the list items

### ISSUE THREAD

**Issue by Piratesarereal** [mozilla-mobile/firefox-ios#22861]
## Steps to reproduce

- Open the menu

### Expected behavior

- The list item with no secondary text should be atleast 44dp
- The list item with a secondary text should be atleast 62dp
- A11y requires atleast 44 dp touch target height for the list items. 

### Device & build information
* Device: Firefox Beta
* Build version: ? 
* First seen version: ? 
### Notes
Attachments: 

![image](https://github.com/user-attachments/assets/b65172de-5c83-43e2-a96c-ae97b88f9699)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-10448)

**Comment by data-sync-user** [comment]
➤ Alexandru Farcasanu commented:

The fix for this bug is in the same PR with https://mozilla-hub.atlassian.net/browse/FXIOS-10419 ( https://mozilla-hub.atlassian.net/browse/FXIOS-10419|smart-link )

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Validated on v133 (47343), with iPhone 16 (18.1).

**Comment by data-sync-user** [comment]
➤ Aarjav Pandya commented:

Hey Alexandru Farcasanu, this bug you attached is regarding the voiceover, whereas this one is for the height of the list item. This is still not fixed.

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v133 (47734), with iPhone 16+(18.1).
