### ISSUE TITLE
Video from Private Browsing Shows as Preview in App Switcher Landscape Mode After Private Browsing Tab is Closed

### ISSUE THREAD

**Issue by amooseongithub** [mozilla-mobile/firefox-ios#22864]
## Steps to reproduce

1. New Private Browsing Tab
2. Play any video in landscape full screen (YouTube for example).
3. Navigate to a tab in Firefox of an already open website, doesn't matter if private or non-private tab
4. Open any other landscape app such as a game
5. Use iOS App Switcher to see all open apps
6. ***BUG : 

### Expected behavior
Preview of Firefox in iOS App Switcher in landscape mode should be blank gray altogether because it's a private tab, OR a preview of the currently open tab if current tab isn't private.

### Actual behavior
Firefox preview shows the video from private browsing. ONLY fails to update the landscape preview, NOT the portrait. The preview is updated correctly for Portrait mode in iOS App Switcher but not for Landscape oriented. This happens even after the private tab has been closed out.

### Device & build information
* Device: iPhone 16 Pro, iOS 18.1
* Build version: ? 131.4
* First seen version: 131.4
### Notes
Attachments: 

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-10451)

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v9000 (47503), with iPhome 16+(18.1).

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v133 (47734), with iPhone 16+(18.1).
