### ISSUE TITLE
[Menu Redesign] Use the correct color for the divider line.

### ISSUE THREAD

**Issue by Piratesarereal** [mozilla-mobile/firefox-ios#22862]
### Expected behavior
- We should see #E0E0E6
### Actual behavior
- the color being used looks like #C6C6C8

### Device & build information
* Device: Firefox Beta
* Build version: ? 
* First seen version: ? 
### Notes
Attachments: 

![image](https://github.com/user-attachments/assets/9b70df9e-1367-42ba-a48c-a32848105094)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-10449)

**Comment by data-sync-user** [comment]
➤ Alexandru Farcasanu commented:

The fix for this bug is in the same PR with https://mozilla-hub.atlassian.net/browse/FXIOS-10419 ( https://mozilla-hub.atlassian.net/browse/FXIOS-10419|smart-link )

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Validated on v133 (47343), with iPhone 16 (18.1).
