### ISSUE TITLE
[Menu Redesign] On the list item, make the icon and text centre aligned. 

### ISSUE THREAD

**Issue by Piratesarereal** [mozilla-mobile/firefox-ios#22863]
## Steps to reproduce
- Open the menu
### Expected behavior
- make the icon and text centre aligned. 
### Actual behavior
- Currently the icon and text look top aligned. 
### Device & build information
* Device: Firefox Beta
* Build version: ? 
* First seen version: ? 
### Notes
Attachments: 

![image](https://github.com/user-attachments/assets/1c85c6a4-807a-48ab-881c-212ff0893866)

<img width="848" alt="Screenshot 2024-11-01 at 2 32 06 PM" src="https://github.com/user-attachments/assets/d7da08e7-b591-4e25-a76d-bbceabe547c2">
<img width="856" alt="Screenshot 2024-11-01 at 2 33 21 PM" src="https://github.com/user-attachments/assets/346ec241-42ce-4ca7-9853-4cf6a4cc9856">

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-10450)

**Comment by data-sync-user** [comment]
➤ Alexandru Farcasanu commented:

The fix for this bug is in the same PR with https://mozilla-hub.atlassian.net/browse/FXIOS-10419 ( https://mozilla-hub.atlassian.net/browse/FXIOS-10419|smart-link )

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Validated on v133 (47343), with iPhoe 16 (18.1).
