### ISSUE TITLE
__firefox__.searchQueryForField is not a function

### ISSUE THREAD

**Issue by oliviertassinari** [mozilla-mobile/firefox-ios#2288]
I'm not sure what's going on, but we havet quite some error like this
> TypeError: __firefox__.searchQueryForField is not a function. (In '__firefox__.searchQueryForField()', '__firefox__.searchQueryForField' is undefined)
  at ? (/account/new:1:32)

From that browser in production:
![capture d ecran 2016-12-19 a 10 10 08](https://cloud.githubusercontent.com/assets/3165635/21306869/63e88fb6-c5d3-11e6-96aa-c34ebe871196.png)

**Comment by Matrosskin** [comment]
@farhanpatel What was the reason for closing the issue?

**Comment by jhonny111s** [comment]
@farhanpatel i am agree with @Matrosskin  why close the issue?

i have same problem and look like a problem with header  http-equiv="X-UA-Compatible".

`<!DOCTYPE html>
<html>
<head><title>title </title><meta charset="UTF-8"/>
<meta http-equiv="X-UA-Compatible" content {snip} ...`

**Comment by janosch-x** [comment]
@farhanpatel JFYI this is still occurring

<img width="300" alt="bildschirmfoto 2018-04-30 um 10 43 09" src="https://user-images.githubusercontent.com/10758879/39420204-cf1a0a90-4c63-11e8-859b-c62ba2edeed9.png">
<img width="300" alt="bildschirmfoto 2018-04-30 um 10 44 54" src="https://user-images.githubusercontent.com/10758879/39420214-d67a3472-4c63-11e8-8587-c634c0898c9b.png">

**Comment by carolinesalib** [comment]
I got the same problem on rollbar with firefox ios 11.1 and 10.6. Both ocorres in iOS 11.3.

**Comment by skulden13** [comment]
I got the same issues from Firefox-iOS 10.6 in iOS 11.3.

**Comment by piotrd** [comment]
Same here for Firefox 11.1 in iOS 11.3

**Comment by willydee** [comment]
Also happened here on Firefox 12.1 on iOS 11.2.6. Please reopen the issue.

**Comment by davidjpfeiffer** [comment]
Same here for Firefox on iOS 11.4.1

**Comment by ovidiugabriel** [comment]
```

TypeError: __firefox__.searchQueryForField is not a function. (In '__firefox__.searchQueryForField()', '__firefox__.searchQueryForField' is undefined)
--


```
Mozilla/5.0 (iPhone; CPU iPhone OS 13_3_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) FxiOS/21.0 Mobile/15E148 Safari/605.1.15
