### ISSUE TITLE
[Menu Redesign] The accounts list item on the menu doesn't update right after signing in. 

### ISSUE THREAD

**Issue by Piratesarereal** [mozilla-mobile/firefox-ios#22885]
## Steps to reproduce
- Be in a signed-out state of app.
- Open the menu and sign in. 
- After signing in, open the menu, and you will see that it isn't signed in. 
- Reopen the menu, and you will see that you are signed in. 

### Expected behavior
- Right after signing in and opening the menu you should be signed in. 
### Actual behavior
- Right after signing in and opening the menu, you see that you are not signed in. 

### Device & build information
* Device: ? 
* Build version: ? 
* First seen version: ? 
### Notes
Attachments: 
[Video Link
](https://www.figma.com/proto/RFz9fYtotQCQuinwcZujZt/%5B%5D-Menu-Redesign?page-id=19728%3A172874&node-id=21061-175670&node-type=frame&viewport=-910%2C-2163%2C0.31&t=Gbj29TUxaLK2ddyR-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=21061%3A175670&show-proto-sidebar=1)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-10459)

**Comment by nbhasin2** [comment]
@Piratesarereal could you add the version, device as this is likely fixed in the new version of (Nightly) coming up

If you don't have access to Nightly then let us know we will inform when it lands in Beta

**Comment by Piratesarereal** [comment]
Don't have access to nightly, will check in Beta. 

It is Firefox 9000 (47291)

**Comment by data-sync-user** [comment]
➤ Chris Peterson commented:

This is a race condition between signing in and opening the menu. How would the open menu learn that the in-progress sign-in has finished signing in while the menu is open? Should we add a temporary “signing in” state to the menu?

Possibly related: Andy and I are signed in and when we open the menu for the first time in the morning, we often see the menu switch from “Sign in” to our account name after about 300 ms.

**Comment by data-sync-user** [comment]
➤ Alexandru Farcasanu commented:

For QA: for any questions, please contact me!

**Comment by data-sync-user** [comment]
➤ Alexandru Farcasanu commented:

Chris Peterson we did here an improvement. Hope it fixed the main issue about that 300 ms delay.

**Comment by data-sync-user** [comment]
➤ Chris Peterson commented:

👍 LGTM in build 9000 (47776). Thanks!

**Comment by data-sync-user** [comment]
➤ Adina Petridean commented:

Verified as fixed on Firefox 133.0 (47866) with iPhone 14 Pro Max (iOS 16.2) and iPhone 16+(18.1).
