### ISSUE TITLE
Reader View button crashes the app intermittently

### ISSUE THREAD

**Issue by clarmso** [mozilla-mobile/firefox-ios#22962]
## Steps to reproduce
Note: The crash may not be reproduced manually or via Xcode IDE. The app crashes when the reader view 📜 button from the awesome bar is tapped.

CLI command:
```
xcodebuild build-for-testing -target Client -scheme Fennec -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.5'
xcodebuild test-without-building -scheme Fennec -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.5' -testPlan FullFunctionalTestPlan ARCHS="arm64" -only-testing:XCUITests/ReadingListTests/testMarkAsReadAndUnreadFromReadingList
```

Failing XCUITests include the following:
```
        ReadingListTests.testAddToReadingListPrivateMode()
        ReadingListTests.testMarkAsReadAndUnreadFromReadingList()
        ReadingListTests.testMarkAsReadAndUreadFromReaderView()
        ReadingListTests.testOpenSavedForReadingLongPressInNewTab()
        ReadingListTests.testRemoveFromReadingList()
        ReadingListTests.testRemoveFromReadingView()
        ReadingListTests.testRemoveSavedForReadingLongPress()
```

### Expected behavior
The page is shown in reader view.

### Actual behavior
💥 The app quits.

### Device & build information
* Device: iPhone 15/14/13 simulator (iOS 17.5, 16.4 15.5 respectively)
* Build version: 
* First seen version: https://github.com/mozilla-mobile/firefox-ios/commit/6b6a02161832974c53fe756edb78bf41bc6b61ed
### Notes
Attachments: 

`ReadingListTests.testMarkAsReadAndUnreadFromReadingList`:
https://github.com/user-attachments/assets/4af2050e-8f16-43f7-8f7b-39a29d43e7e7

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-10487)

**Comment by PARAIPAN9** [comment]
QA Notes: This is primarily for automated testing (where the crash occurred), but it can also be tested manually to ensure the app does not crash anymore when tapping the reader mode button.

**Comment by dragosb01** [comment]
The automation tests are passing now.

**Comment by clarmso** [comment]
Let's close this issue. I have not seen ReadingListTests fail in the same way during automation.

**Comment by data-sync-user** [comment]
➤ Sorin Paraipan commented:

I see that it is already set to ‘Done’.

**Comment by data-sync-user** [comment]
➤ Sorin Paraipan commented:

Sorry, I am just now seeing that you’ve set it to ‘Done’. 😅
