### ISSUE TITLE
Fix errors for extension protocol conformances

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#23026]
VERY IMPORTANT!!

* `@retroactive` attribute seems to do the trick for Xcode 16.x and macOS Sequoia, but we want to make the project build for Xcode 15.x, macOS Sonoma, so we have to use a different approach.

Example:

We have this error: `Extension declares a conformance of imported type 'LabelButtonHeaderViewModel' to imported protocol 'Equatable'; this will not behave correctly if the owners of 'Client' introduce this conformance in the future` for: `extension LabelButtonHeaderViewModel: Equatable` .

A good solution that works for both would be `extension LabelButtonHeaderViewModel: Swift.Equatable` 

Please test and make sure it builds in both cases. Thanks in advance.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-10502)

**Comment by PARAIPAN9** [comment]
Hey @surajeet310, thanks for wanting to contribute. This issue was addressed in another PR and I forgot to close it. Feel free to choose other issues. Thanks again!!
