### ISSUE TITLE
[Toolbar Redesign] Reader view page doesn’t show lock icon after session restore

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/firefox-ios#23031]
## Steps to reproduce

In a TestFlight build with the new toolbar enabled:

1. Load a Wikipedia article or page that offers the reader view button
2. Tap the reader view button to enter reader mode. 
3. Force quit Firefox. 
4. Restart Firefox. 

### Expected behavior

The restored reader view page’s address bar should show a lock icon and the domain name should have posing on its left edge. 

![image](https://github.com/user-attachments/assets/852749e3-07e2-4427-a138-1465c679235f)

### Actual behavior

The restored reader view page’s address bar doesn’t show a lock icon and the domain name is flush with the left edge of the address bar. 

![image](https://github.com/user-attachments/assets/a1e82efe-844e-45d6-90c9-e707ee8f040a)

### Device & build information

* Device: iPhone 15 Plus running iOS 18.1
* Build version: Firefox 9000 (47393)

This bug only affects the new toolbar.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-10506)

**Comment by data-sync-user** [comment]
➤ Andres Furlan commented:

Lock icon won’t be displayed on reader mode for now, until further improvements. Thanks!

**Comment by data-sync-user** [comment]
➤ Adina Petridean commented:

Validated on Firefox 133.0 (47734) with iPhone 14 Pro Max (iOS 16.2).
