### ISSUE TITLE
Moved Tabs Don’t Stay Moved

### ISSUE THREAD

**Issue by datainadequate** [mozilla-mobile/firefox-ios#23038]
## Steps to reproduce

Drag a tab to a different position in the tab bar.
Tap another tab.

### Expected behavior

Tab bar is redrawn and moved tab stays in the position it was just moved to.

### Actual behavior

Tab bar is redrawn and moved tab reverts to original position.

### Device & build information
* Device: iPad Pro (12.9-inch) (3rd generation) (MTFP2B/A), iPadOS 17.6.1 (21G93)
* Build version: Firefox 132.1 (47104)
* First seen version: It’s been like this for a couple of weeks, definitely in 132.0, maybe before that.

### Notes
Attachments: 
https://github.com/user-attachments/assets/08adad4d-b7c9-47e5-ad78-4f82b6e6b6d9

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-10507)

**Comment by data-sync-user** [comment]
➤ Alexandru Farcasanu commented:

Investigated on iPad Air (4th generation), OS 17.5.1, FF version 133.0. I can’t reproduce the issue. Closed based also on a confirmation from QA.
