### ISSUE TITLE
[Menu design][Accessibility] VoiceOver focus moves outside of the action sheet when the action sheet is open

### ISSUE THREAD

**Issue by natastro** [mozilla-mobile/firefox-ios#23060]
## Prerequisites

- Turn on VoiceOver
- Turn on `treatment-a` of the iOS Menu Redesign
- Found on Firefox Beta iOS app 133.0

## Steps to reproduce

1. Open Firefox Beta iOS app
2. Open the menu from the hamburger menu icon button at the bottom of the screen
3. As the action sheet appears on screen, swipe right 3-4 times and observe VoiceOver behavior

### Expected / Actual 

The top portion above the action sheet can be available to VoiceOver with explore by touch but should not be included in VoiceOver's focus order.

Focus will start at the 'sheet grabber' at the top center of the action sheet. When a VoiceOver user swipes right, it should move to the first focus stop underneath (Sign In, Sync passwords, tabs, and more). For reference, please see the [Reading Order that's mapped out in Figma](https://www.figma.com/design/RFz9fYtotQCQuinwcZujZt/%5B%5D-Menu-Redesign?node-id=19728-177454&t=m8qQdcQJvQlVisVE-4)

### Device & build information
* Device: iPhone 15, iOS 18.1
* Build version: Firefox Beta 133.0
* First seen version: First time I've seen this issue
### Notes
Attachments: 

https://github.com/user-attachments/assets/aa0639a4-d352-416f-a624-b74cd1b48957

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-10520)

**Comment by data-sync-user** [comment]
➤ Alina Moldovan commented:

Verified  as fixed using v133 (47866) and iPhone 15+ (18.0) & 15 Pro Max (18.3)
