### ISSUE TITLE
Clean up remote tab management changes

### ISSUE THREAD

**Issue by lougeniaC64** [mozilla-mobile/firefox-ios#23075]
Remove unnecessary `self` references from [RustRemoteTabs](https://github.com/mozilla-mobile/firefox-ios/blob/main/firefox-ios/Storage/Rust/RustRemoteTabs.swift) and rename the `e` argument in `sendEventToDevice` call made in [Profile.flushTabCommands](https://github.com/mozilla-mobile/firefox-ios/blob/cca5743f8ecfe61cb0bb8947f00d08988ddbad12/firefox-ios/Providers/Profile.swift#L606) per @mattreaganmozilla's request.

Note: The argument renaming will require a breaking appServices change so addressing these changes has been separated from #22799 as to not delay landing those changes.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-10532)

**Comment by mattreaganmozilla** [comment]
> Note: The argument renaming will require a breaking appServices change so addressing these changes has been separated from https://github.com/mozilla-mobile/firefox-ios/pull/22799 as to not delay landing those changes.

@lougeniaC64 If the change is nontrivial for any reason, I'd say it's fine to close this; the previous PR suggestions were very minor and entirely for readability/stylistic reasons. Definitely not a big eal. Thank you for filing/tracking this, however. 🙏
