### ISSUE TITLE
[Password Generator] The use a strong password menu is not hidden in the app-switcher

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/firefox-ios#23085]
1. Install FF and access https://fill.dev/form/registration-email.
2. Write in the email.
3. Tap on the password field.
4. Tap on the Use strong password.
5. Open the iOS App-Switcher.
6. Observe that the password is not blurred/hidden.

**Expected behavior**
The Use a Strong password menu should be hidden in the app-switcher.

**Actual behavior**
The use of a strong password menu is not hidden in the app-switcher.

**Device & build information**

* Device: iPhone 15 Pro (18.2)
* Build version: v133 (47494)
* First seen version: ?

https://github.com/user-attachments/assets/9e221115-95f7-4d80-919b-156996d396ab

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-10537)

**Comment by data-sync-user** [comment]
➤ Adina Petridean commented:

Verified as fixed on v9000(48307) with iPhone 14 Pro Max (iOS 16.2).

!AppSwitcher.mp4|width=886,height=1920,alt="AppSwitcher.mp4"!

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v134 (48423), with iPhone 15 (17.6).
