### ISSUE TITLE
**Problem description**

### ISSUE THREAD

**Issue by sangshanrupesh** [mozilla-mobile/firefox-ios#23303]
**Problem description**

Let's say a user uploads a dataset and then want to export it. She/He/They can then go to the top of the screen and click on **SAVE AS**. This window will pop-up:

<img width="612" alt="Captura de pantalla 2024-04-24 a la(s) 11 42 09" src="https://github.com/okfn/opendataeditor/assets/20649846/a09b4550-d634-4195-ac03-92dbee92a55c">

As a user with non-technical background I would expect the ODE to show me the window to select location on my . Is it possible to do this @roll? Also, how is the data save on laptop? Zip file with more than one csv (for tabular data, for example)?

_Originally posted by @romicolman in https://github.com/okfn/opendataeditor/issues/344_

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-10649)

**Comment by lmarceau** [comment]
Hello, this seems to relate to another project than Firefox iOS. You mention saving data on laptop, which we don't handle as this project is solely made to work on iPhone. If you aimed to open this issue for Firefox Desktop, you should open your issue on [SUMO](https://support.mozilla.org/en-US/). Thank you!
