### ISSUE TITLE
Sharing bookmarks to Mail uses the current tab's information mixed with the bookmark information

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#23339]
If you share a link saved to your bookmarks, then choose Mail, we see the selected tab’s title in the subtitle line and body.

Example below (note mash up of facebook and wikipedia)

!library sharing bug.PNG|width=1179,height=2556,alt="library sharing bug.PNG"!

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXIOS-10668)

**Comment by cpeterso** [comment]
This bug was a regression in Nightly 9000 (47686). The Share button copies the URL correctly in the previous build, Nightly 9000 (47636).

**Comment by cpeterso** [comment]
Though I am not sharing from a bookmark to another app. I’m using the new toolbar’s Share button to copy the URL so I could paste it into another app.

**Comment by data-sync-user** [comment]
➤ Isabella commented:

Caused by https://mozilla-hub.atlassian.net/browse/FXIOS-10646 ( https://mozilla-hub.atlassian.net/browse/FXIOS-10646|smart-link )

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v134 (48607), with iPhone 15 (17.6).
