### ISSUE TITLE
[Toolbar Redesign] Reader View button disappears after opening a link in a new tab

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/firefox-ios#23343]
## Steps to reproduce

1. Enable the new toolbar. 
2. Open a Wikipedia article. 
3. See the Reader View button in the address bar. 
4. Long press a link on the page. 
5. Select “Open in New Tab”.

### Expected behavior

The Reader View button should not disappear. 

### Actual behavior

The Reader View button disappears.

https://github.com/user-attachments/assets/cbd08e02-4656-4ab2-b27c-fb576c2ad8c7

### Device & build information

* Device: iPhone 15 Plus running iOS 18.1
* Build version: Nightly 9000 (47935)
* First seen version: This bug is a regression in Nightly 9000 (45007).

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-10670)

**Comment by data-sync-user** [comment]
➤ Alina Moldovan commented:

Verified as fixed using v134 (48974) and iPhone 15+ (18.2).

[^ScreenRecording_12-17-2024 11-58-16_1.MP4]
