### ISSUE TITLE
[Toolbar Redesign] Add 8dp padding on the right of the URL. 

### ISSUE THREAD

**Issue by Piratesarereal** [mozilla-mobile/firefox-ios#23489]
Adding an 8dp padding on the right of the URL. [Figma Link](https://www.figma.com/design/8fsCvtnweBkWGZ9NfL907l/__-Toolbar-Redesign?node-id=26560-189757&t=z4hSqe1UHfGz5kEV-4)
<img width="818" alt="Screenshot 2024-11-29 at 4 01 56 PM" src="https://github.com/user-attachments/assets/c399b8c1-f65f-40fc-815f-3a9734ce49cc">

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-10768)

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Validated on 134 (48607), with iPhone 15 (17.6).
