### ISSUE TITLE
In leu of https://github.com/multiformats/js-multiformats/pull/261 landing, this PR uses the nodejs crypto library to create a streaming sha256 hasher.

### ISSUE THREAD

**Issue by sangshanrupesh** [mozilla-mobile/firefox-ios#23496]
In leu of https://github.com/multiformats/js-multiformats/pull/261 landing, this PR uses the nodejs crypto library to create a streaming sha256 hasher.

Before:

```console
$ ipfs-car hash snow.car 
node:internal/fs/promises:516
    throw new ERR_FS_FILE_TOO_LARGE(size);
          ^

RangeError [ERR_FS_FILE_TOO_LARGE]: File size (11998084756) is greater than 2 GiB
    at readFileHandle (node:internal/fs/promises:516:11)
    at async Module.hash (file:///usr/local/lib/node_modules/ipfs-car/cmd/hash.js:13:13) {
  code: 'ERR_FS_FILE_TOO_LARGE'
}

Node.js v20.11.0
```

After:

```console
$ ipfs-car hash snow.car
bagbaierabdsb7q55nozng74qw267etolakl4jwrszyjb5elw43zercwmowva
```

(Note: `snow.car` is an 11GB CAR)

resolves https://github.com/web3-storage/ipfs-car/issues/158

_Originally posted by @alanshaw in https://github.com/storacha/ipfs-car/pull/162_

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-10771)

**Comment by nbhasin2** [comment]
Closing, as unrelated to our project
