### ISSUE TITLE
Crash when opening bookmarks

### ISSUE THREAD

**Issue by dragosb01** [mozilla-mobile/firefox-ios#23549]
## Steps to reproduce
1. Open the app 
2. Open the menu and select bookmarks
3. Wait for few seconds
### Expected behavior
The app doesn't crash
### Actual behavior
The app crashes
### Device & build information
* Device: iPhone 16, 18.1 OS simulator
* Build version: 135

### Notes
Attachments: 

https://github.com/user-attachments/assets/aeb394a0-6b5b-4191-a21f-f6d9ec6d1cc5

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-10795)

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v9000 (48681), with iPhone 15 (17.6).

**Comment by dragosb01** [comment]
Issue fixed
