### ISSUE TITLE
Duplicated history entries

### ISSUE THREAD

**Issue by clarmso** [mozilla-mobile/firefox-ios#23711]
## Steps to reproduce
1. Tap hamburger 🍔 menu. Select "History".
2. Tap trash can icon 🗑️ and select *Everything* from the popover. Tap "Done".
3. On a tab, open www.mozilla.org.
4. Tap hamburger 🍔 menu. Select "History".

### Expected behavior
Only one entry on Mozilla.

### Actual behavior
Two identical entries on Mozilla.
![Simulator Screenshot - iPhone 16 - 2024-12-11 at 23 56 09](https://github.com/user-attachments/assets/97f22be5-fe71-4769-83a8-5dc2fee42c78)

### Device & build information
* Device: ? 
* Build version: ? 
* First seen version: ? 
### Notes
Attachments: 

Video of the steps:
https://github.com/user-attachments/assets/84f0a438-7078-405d-baee-dddffc118ffc

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-10868)

**Comment by data-sync-user** [comment]
➤ Isabella commented:

Closed (duplicate).
