### ISSUE TITLE
App crashes every time I open it

### ISSUE THREAD

**Issue by timwis** [mozilla-mobile/firefox-ios#23822]
## Steps to reproduce
Open the app via the app icon or app switcher 

### Expected behavior
App opens

### Actual behavior
All-white splash screen with Firefox logo shows for a second, then the app disappears

### Device & build information
* Device: iPhone 14 Pro, iOS 18.2 (22C5125e) 
* Build version: unknown as I can't open Firefox, but the App Store does not have an 'update' button, and the App Store description says 133.3 
* First seen version: 2 days ago, and haven't updated since (no updates available) 
### Notes
Attachments: 

https://github.com/user-attachments/assets/a9ab0a26-fe5c-424c-881c-cad8a2eb6ef5

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-10907)

**Comment by lukeajtodd** [comment]
Same issue here, uninstalled and reinstalled with no change.

iPhone 15 Pro
iOS v18.2
MTV53ZD/A

Noticed it a couple of days ago.

**Comment by nbhasin2** [comment]
Hi, @timwis you are using Apple iOS 18.2 Beta

This crash is related to the 18.2 Beta and although we have a fix coming in next version I would highly recommend upgrading to RC version of iOS 18.2

**Comment by timwis** [comment]
Yes I'm on the beta. Okay sure, I'll update my OS and see if that fixes it.

**Comment by timwis** [comment]
Just to say that upgrading my OS to 18.3 send to have resolved the issue. Thanks again.
