### ISSUE TITLE
Q: Is it ok that GCDWebserver pages could be called externally?

### ISSUE THREAD

**Issue by garvankeeley** [mozilla-mobile/firefox-ios#2474]
GCDWebserver is used to serve up localhost:<some port> urls, which then trigger special in-app functions. 
Should these urls have an url param with a runtime-generated GUID to block them being called externally?
Am curious if this was considered, or is just a non-issue in general.

**Comment by thebnich** [comment]
> Should these urls have an url param with a runtime-generated GUID to block them being called externally?

Yes, and we do :)

https://github.com/mozilla-mobile/firefox-ios/blob/241395c334241abf3ddbf2ba10d0de642dbaff3a/Client/Application/WebServer.swift#L27

**Comment by garvankeeley** [comment]
Ha! Thanks, Brave is on an old fork of fx iOS, but I thought that particular code was up-to-date, I guess not.
