### ISSUE TITLE
can't build code.  with xcode8 . and iOS 10.2. Simulator.

### ISSUE THREAD

**Issue by TandyTian** [mozilla-mobile/firefox-ios#2487]
I download the code , but can't build code.  with xcode8 and iOS 10.2. Simulator.    

![5e81aa3d-72f9-42d3-ac24-f2e5536bc6c1](https://cloud.githubusercontent.com/assets/12858575/23545122/07dbf982-0035-11e7-8554-4e4b2b8ee4a7.png)

**Comment by aaron-elkins** [comment]
Please try below before you build the Xcode project:

```
cd firefox-ios
sh ./bootstrap.sh
```

**Comment by aaron-elkins** [comment]
If you still encounter any build failure, try run below after running `sh ./bootstrap.sh` in the repo root directory:

```
carthage build --platform ios
```

**Comment by farhanpatel** [comment]
If aaron's advice doesnt work. Feel free to reopen this 😄

**Comment by TandyTian** [comment]
It doesn't work。must need convert to swift 3 ？

**Comment by farhanpatel** [comment]
Yes you'll need a clean folder. Also if you are in China someone else mentioned that the firewall blocks one of the dependencies from installing.

**Comment by mitulmarsonia** [comment]
I have same issue. i have try your given above solution but does not work.
