### ISSUE TITLE
Why does not the version of the SDWebImage library be updated to 4.0.0?

### ISSUE THREAD

**Issue by codergelly** [mozilla-mobile/firefox-ios#2534]
Why does not the version of the SDWebImage library be updated to 4.0.0? Older versions of WebImage can not generate dynamic libraries. kind of hard.

**Comment by AaronMT** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1384159

Need a little bit of refactoring but there's no other reason other than we haven't gotten to updating our dependencies in a while.

**Comment by jhugman** [comment]
Upgraded to 4.1.0.
