### ISSUE TITLE
I get 5 errors when I convert the Swift 2 code to 3.x in Xcode 8.3 in Sierra.  What to do?

### ISSUE THREAD

**Issue by shyamalschandra** [mozilla-mobile/firefox-ios#2593]
Will this version of firefox-ios be updated for Swift 3.x?  Thanks!

![screen shot 2017-04-04 at 11 54 02 am](https://cloud.githubusercontent.com/assets/9545735/24668701/72505a4a-192d-11e7-9909-bf24e1968781.png)

**Comment by yonglam** [comment]
It's swift 3 now. Make sure you build Fennec target.

**Comment by KelCodesStuff** [comment]
@yonglam I build the Fennec target and I got the same errors when converting to Swift 3. 
I also get a fatal error Failed to create/update the scheme table. Aborting.

**Comment by focusspan** [comment]
I skipped the converting to Swift 3 syntax dialog and just built the Fennec target, that worked.

**Comment by garvankeeley** [comment]
Seems to be ok now, closing.
