### ISSUE TITLE
Responsibility for JavaScript reliability

### ISSUE THREAD

**Issue by MikeMcl** [mozilla-mobile/firefox-ios#2660]
Here is an example showing how a basic array operation fails in Firefox for iOS running on iOS 10.3.1 (the most recent stable release)

```js
var arr = [0, 2147483648];
arr.shift();              // arr is [2147483648]
arr[1] = 1;               // arr is [2147483648, 1]
console.log(arr); 
// arr should be [2147483648, 1], but is [2147483648]
```

I understand that the issue is with WebKit but ultimately that is an implementation detail. 

Is it possible to patch this in some way or perhaps warn users that JavaScript code may not work as reliably as they might expect?

**Comment by garvankeeley** [comment]
There isn't anything we can do here. The JS engine is completely in Apple's domain.
