### ISSUE TITLE
Consider adding firefox-ios to the Swift source compatibility suite

### ISSUE THREAD

**Issue by slavapestov** [mozilla-mobile/firefox-ios#2704]
We would greatly appreciate it -- details at https://swift.org/source-compatibility/

**Comment by suxiaoxinxin** [comment]
屏幕快照 2017-05-07 下午9.28.59.png

**Comment by st3fan** [comment]
Unfortunately we depend on Carthage, which is currently not supported by the *Swift Source Compatibilty Suite* project.
