### ISSUE TITLE
How to add extensions ? 

### ISSUE THREAD

**Issue by ColorsSoftwarePvtLtd** [mozilla-mobile/firefox-ios#2875]
I am able run the code.But i do not understand how /where to add extensions.Please guide me.Thanks in advance

**Comment by ColorsSoftwarePvtLtd** [comment]
Extensions adding

**Comment by ExE-Boss** [comment]
Extensions sadly aren’t supposed yet and probably won’t be for some time.

[Here’s a link to a Reddit post where I discussed this with a Mozilla tech support employee.](https://www.reddit.com/r/firefox/comments/6jjmbf/comment/djesayj)
