### ISSUE TITLE
daringfireball.net favicon not showing up

### ISSUE THREAD

**Issue by farhanpatel** [mozilla-mobile/firefox-ios#3193]
@garvankeeley adding this bug, editing to link to buddybuild feedback

 [Link to buddybuild feedback from build 6123](https://dashboard.buddybuild.com/apps/57bf25c0f096bc01001e21e0/feedback?fid=59c09b203a598b00015e7f55&bnum=6123)

**Comment by garvankeeley** [comment]
This site has a favicon: https://daringfireball.net/favicon.ico
