### ISSUE TITLE
Firefox ipad2 form submit target=_blank empty post array

### ISSUE THREAD

**Issue by crc1** [mozilla-mobile/firefox-ios#3217]
In Firefox on ipad2 form submit with target=_blank causes post array to be blank.

**Comment by Raidersvalle13** [comment]
Firefox slow update and crashes on my computer

**Comment by sposmen** [comment]
@AaronMT we have the same issue... any suggested workaround?

**Comment by jdolle** [comment]
Same issue on ios and also through instagram on ios, so I think it's a bug with a dependency.
