### ISSUE TITLE
ScreenGraph evolution

### ISSUE THREAD

**Issue by jhugman** [mozilla-mobile/firefox-ios#3272]
#### Preamble
`ScreenGraph.swift` is a way of describing an iOS app as a graph of screen states. It is written with `XCUITest` and GameplayKit. 

Its primary use case is to make setup and tear down of UI tests trivial and less brittle.

This issue identifies a number of issues with `ScreenGraph`, problems test authors have identified, and potential fixes for them. It does not intend to go into the implementation details.

### Introduction
`ScreenGraph.swift` has been a great success. Since we've introduced it the QA folk have really taken to it, making our UI tests much more readable, and less brittle in the face of changing UI.

This is well and good, however, the intention of `ScreenGraph` is not just to make testing easier: 

 * to serve as an easily readable way of describing the UI of the app, either as the raw swift file `FxScreenGraph.swift`, or as an image. 
 * capable of
 driving the localization screenshots process. These attempt to represent all strings the user will see that are shipped by the app. They _need_ to be comprehensive.

![pre-photon-graph](https://user-images.githubusercontent.com/99338/31352950-87feaaba-ad28-11e7-8e36-40d54b6874e9.png)

However there are a bunch of times where we'd like to improve things. 

 * there is no internal way of **representing actions that change the app state**. e.g. switching to and from Private Browsing Mode.
 * there is no internal way of **representing parameterized actions that change the app state** e.g. 
 * there is no way of representing **multiple actions that achieve the same thing**. e.g. opening a URL by typing it into the URL bar or long pressing and pasting from the URL bar.
 * there is no real way of **representing actions that changes the graph**. e.g. some of the graph is not accessible if the passcode is not set.

All of these things have led to hacks and compromises: 

 * hacking the shape of the graph, most notably in the duplication of the graph nodes for `BrowserTab` and `HomeScreenPanels`. 
 * many menus and context menus aren't very well represented in the graph. e.g. alternative user routes to do things, and thus not well tested, or represented in screenshots.
 * adding progressively more methods to the `navigator` extension,  e.g. `openURL`, increasing test and L10n screenshot complexity.
 * lots of brittle tests trying to work with the hacked up graph and hacked up navigator.
 * makes the process of writing screenshot code more and more labor intensive.

And these hacks, have lead to graphs (and thus tests) that have not been especially easy to grok, or re-use (e.g. for screenshots).

![post-photon-graph](https://user-images.githubusercontent.com/99338/31352988-a6661d08-ad28-11e7-872f-8530672c1c52.png)

The rest of this document introduces some concepts, and API to solve these problems.

#### Rename existing concepts

- `Scene` becomes: `ScreenState`.
- `createScene` becomes: `addScreenState`
- In gesture methods, `to:` becomes `transitionTo:` [not yet implemented]

```swift
let map = ScreenGraph()
map.addScreenState(LoadedTab) { screenState in 
  screenState.tap(app.button("TabToolbar.menuButton"), transitionTo: LoadedTabMenu)
  screenState.noop(transitionTo: URLBarAvailable)
  screenState.tap(app.buttons["TabLocationView.pageOptionsButton"], transitionTo: PageOptionsMenu)
}
```
#### New concept: `UserState`
These are objects representing the user's mental model of the state of the app.

They are a way of communicating data from the tests to the graph.

```swift
class FxState: UserState {
  var url = ""
  var hasPasscode = false
  var tabCount = 0
  var isPrivate = false
}

let map = ScreenGraph()
map.initialUserState = FxState()
```

`userState` is available from the `navigator`. The `BaseTestCase` should probably make `userState` available as a property.

```swift
navigator.userState.url = "https://mozilla.com"
XCTAssertFalse(navigator.userState.isPrivate)
```

The user state is supposed to very simple, and very easy to evolve as you write your tests.

The user state can record the state of the app as it transitions into the screen state.

```swift
map.addScreenState(LoadedTab) { screenState in
  …
  screenState.onEnter() { userState in 
    userState.url = app.textField.text()
  }
  …
}
```

#### New concept: `ScreenAction` nodes
These are nodes on the graph that represent actions the user might take. They can represent multiple ways to do the same thing; they can read or write the `userState`.

Actions do not need to be added to the `map`, but can be created as gestures. You might think of them as named gestures.

Actions can read and write to the `userState`.

```swift
map.addScreenState(TabTray) {
  screenState.tap(app.button["tabTray.privateBrowsingMask"], forAction: TogglePBM) { userState in 
    userState.isPrivate = !userState.isPrivate
  }
}
```

Tests can perform actions using the `navigator`.

```swift
navigator.performAction(TogglePBM)
navigator.toggleOn(userState.isPrivate, withAction: TogglePBM)
navigator.toggleOff(userState.isPrivate, withAction: TogglePBM)
```

Actions can be lead to other actions, which may transition to screen states. These might be thought of "aliases", but are really action nodes which only have other action nodes joined to them.

```swift
map.addScreenState(URLBarAvailable) { screenState in
  screenState.gesture(forAction: TypeURLAction, LoadURLAction, transitionTo: LoadedTab) { userState in 
    let urlString = userState.url
    let urlBar = app.textField["URLBar"]
    urlBar.tap()
    urlBar.type("\(urlString)\r")  
  }

  screenState.gesture(forAction: PasteURLAction, LoadURLAction, transitionTo: LoadedTab) { userState in 
    let urlString = userState.url
    let urlBar = app.textField["URLBar"]

    UIPasteboard.general.string = urlString

    urlBar.longPress()
    app.menuButton["pasteURL"].tap()
  }
}
``` 

Tests may use the `navigator` to perform the task, with whichever action is quickest; or a specific action to achieve the task.

```swift
navigator.userState.url = "https://mozilla.com"
navigator.performAction(LoadURLAction)

navigator.performAction(TypeURLAction)
XCTAssertTrue(navigator.userState.url.beginsWith("https://mozilla.com"))
```

Screen actions can also have code run each time they are performed.
```swift
map.addScreenAction(LoadURLAction) { userState in
  userState.tabCount += 1
}
```

Screen Actions can optionally lead directly to `ScreenState`s.

```swift
map.addScreenAction(LoadURLAction, transitionTo: LoadedTab)
```

Without leading to a screen state, the final screen state of the navigator is to return to the state from which the action was taken. `dismissOnUse` is respected, so in the chain `BrowserTab` -> `BrowserTabMenu` -> `ToggleNoImageMode`, if `BrowserTabMenu` is `dismissOnUse`, then the navigator would assume the screen would reset to `BrowserTab`.

#### New concept: predicates
These are based on the well known `NSPredicate`.

##### Using predicates to change the navigable graph.
Building on `userState` and Screen Actions, predicates enable us to describe the application more fully, and enable the `navigator` to choose different routes through the graph based upon the `userState`. 

Recall: transitions between screen states, and between screen actions and between screen actions and screen states are all edges on the same graph.

Predicates are string queries over the `userState` object. Edges can be made conditional on the `userState`.

```swift
map.addScreenState(SettingsScreen) { screenState in 
  …
  let passcodeSettings = table.cells["TouchIDPasscode"]
  screenState.tap(passcodeSettings, PasscodeSettingsOn, if: "hasPasscode == true")
  screenState.tap(passcodeSettings, PasscodeSettingsOff, if: "hasPasscode == false")
  …
}
```

This might allow the test author to: 

```swift
navigator.userState.passcode = "1234"
navigator.performAction(EnablePasscodeAction)
```

##### Predicate generalizes `screenState.existsWhen`
We are more used to seeing predicates when applied to `XCUIElement`s, especially around waiting for elements to appear or disappear. 

```swift
map.addScreenState(LoadedTab) { screenState in
  …
  // wait for the progress bar to disappear.
  screenState.onEnterWaitFor("exists != true", element: app.progressBars(boundBy: 1))
  …
}
```

`element` can be `Any` object.

There is some limited functionality to wait for an element if a `userState` predicate is true.

```swift
screenState.onEnterWaitFor("exists != true", element: app.progressBars(boundBy: 1), if: "loadNormally == false")
```

### Request for Comments
None of this is implemented.

Implementation effort is relatively low; tests are currently being updated for photon. The L10N screenshots have not been started. We should make these changes sooner rather than later.

 * Have I missed any use cases?
 * Does the proposed API solve the use cases we need to solve?
 * Can the proposed API be nicer for–/more usable by– test authors?

**Comment by npark-mozilla** [comment]
@jhugman this is the logical progression of FxScreenGraph, and can't wait to try it out when it's implemented.  Looks great!

First, a fairly simple question regarding the existing FxScreenGraph:
- just want to double check the noop() method - if transition from A to B is noop(), this means that the state remains in A unless asked to go to B, right?

Now for above proposal:
- about ScreenAction, proposal says we can concatenate a series of ScreenActions to change state.   So can we say "go from State A to B, by using ScreenAction 1 and 2 and 3... and n" or "go from State A to B, and first action _has to be_ ScreenAction 1, but it's up to you after that?"  This will clear up the ambiguities and unintentional UI actions.

- Can map.addScreenState() take parameters in addition to the ScreenState name? for example, if  map.createScene(BrowserTab) can somehow take URL parameters via lazy loading of some sort, and do things like navigator.goto(BrowserTab, "www.mozilla.com"), then it would make things a lot easy and not assume there is a hardcoded URL.

- this is more of a nice to have, but one of the issues while debugging test with fxscreengraph was that you can't always step through the navigation, since the graph is drawn initially.  It would be nice if we have a separate class that contains the error strings, and we can reference them on fxscreengraph in various places where code might fail.

- can predicates and screenactions be visualized in the graph converter tool?

**Comment by jhugman** [comment]
### `noop`

If a screen state `A` has a `noop` to another state `B` (or action), then you can `goto(A)` without going to `B`. If you ask to `goto(B)` from `A` then nothing visible will happen on screen.

### Action chains

As I'm coming to understand actions, I'm going to say that:

- actions are nodes with only one outward edge.
- that edge can lead to another action
- the navigator will always begin and end a `goto` or `performAction` on a `ScreenState`, not on an action.

So considering:

```swift
map.addScreenState(BrowserTab) { screenState in
    screenState.tap(app.textFields["url"], to: URLBarOpen)

    screenState.gesture(forAction: Action.LoadURLByPasting, Action.LoadURL) { userState in
        UIPasteboard.general.string = userState.url ?? defaultURL
        app.textFields["url"].press(forDuration: 1.0)
        app.sheets.element(boundBy: 0).buttons.element(boundBy: 0).tap()
    }
}
```

and

```swift
map.addScreenState(URLBarOpen) { screenState in
    screenState.gesture(forAction: Action.LoadURLByTyping, Action.LoadURL) { userState in
        let urlString = userState.url ?? defaultURL
        app.textFields["address"].typeText("\(urlString)\r")
    }
}
```

then `LoadURLByPasting` and `LoadURLByTyping` can be performed seperately, or automatically selected depending on where in the app the navigator is.

Because we know which state the app will end up in, we can then add:

```swift
map.addScreenAction(Action.LoadURL, transitionTo: BrowserTab) { userState in
    // NOP
}
```

So, a fully worked example, a single action:

```swift
navigator.userState.url = "https://example.com"
navigator.performAction(Action.LoadURLByPasting)
```

would cause the navigator to:

 - `LoadURLByPasting`, where the contents of the `userState.url` is used.
 - `LoadURL`, the NOP
 - `BrowserTab`, the final screen state of the app.


Sidebar: Actions are best thought of as _labelled edges_ between screen states, so we should probably somehow enforce uniqueness of the `LoadURLByPasting` and `LoadURLByTyping`. How can we change the API to indicate this?

In the case of an action — or chain of actions — not explicitly ending at another `ScreenState`, then the state the action came from is used, as if the state was exited and then returned to.

So, without declaring the action `LoadURL` transitioning to `BrowserTab`, then performing `LoadURLByTyping` would land the navigator back at `URLBarOpen`.

We should respect `dismissOnUse = true` so menus would work as expected:

```swift
map.addScreenState(BrowserTabMenu) { screenState in
    screenState.dismissOnUse = true

    screenState.tap(app.cells["menu-NightMode"], forAction: Action.ToggleNightMode) { userState in
        userState.nightMode = !userState.nightMode
    }
}
```

From `BrowserTab`:

```swift
navigator.performAction(Action.ToggleNightMode)
```

the navigator would go 

 - `BrowserTab`
 - `BrowserTabMenu`
 - `ToggleNightMode`
 - `BrowserTab` – because `dismissOnUse=true` for `BrowserTabMenu`.

### Point by point

> about ScreenAction, proposal says we can concatenate a series of ScreenActions to change state.
> So can we say "go from State A to B, by using ScreenAction 1 and 2 and 3... and n" or "go from State A to B, and first action _has to be_ ScreenAction 1, but it's up to you after that?"  This will clear up the ambiguities and unintentional UI actions.  

Can you give me some examples where this might be useful?

Currently we can get the navigator to go to one place, then the other by using consecutive navigator commands. Are you asking to combine those somehow?

There may be ways of combining actions, which probably shouldn't be allowed:

```
screenState.tap(app.button("menu-NewTab"), forAction: OpenURLInNewTab, LoadURLByPasting)
```

then:

```swift
navigator.userState.url = "http://www.mozilla.com"
navigator.performAction(Action.OpenURLInNewTab)
```

These break the mental model of actions being labelled edges.

> Also, it would be nice if we can set dismissOnUse() as part of UserState.  There may be cases where going back is possible, but really you shouldn't.

Can you give me some examples where this might be useful? If this is never advisable, then should you just not wire it together like that?

I'm not wedded to the name `userState`, but it's meant to be the user's model of a given session or part of a session. In reality, it's a communication channel between the imperative tests and the declarative graph.

> Can map.addScreenState() take parameters in addition to the ScreenState name? for example, if  `map.createScene(BrowserTab)` can somehow take URL parameters via lazy loading of some sort, and do things like navigator.goto(BrowserTab, "www.mozilla.com"), then it would make things a lot easy and not assume there is a hardcoded URL.

Do this with the `userState`. See above examples of `LoadURLByPasting` which reads `userState.url`. Hardcoding for within the graph goes away.

```swift
navigator.userState.url = "http://www.mozilla.com"
navigator.performAction(Action.LoadURL)
```

> this is more of a nice to have, but one of the issues while debugging test with fxscreengraph was that you can't always step through the navigation, since the graph is drawn initially.  It would be nice if we have a separate class that contains the error strings, and we can reference them on fxscreengraph in various places where code might fail.

Two things:

 - You should never see errors is the `ScreenGraph` class. The errors should be showing up in either the test (where you called the `goto`, or in the `FxScreenGraph` class).
 - Would a `plan` or `dryRun` method help?, e.g. 

 ```swift
func plan(goto: String) -> [String]
func plan(performAction: String) -> [String]

print(navigator.plan(goto: SettingScreen))
 ```

> can predicates and screenactions be visualized in the graph converter tool?

Yes! 

Was thinking: 

 - the conditional edges marked as dotted lines, perhaps with the predicate text showing.
 - the actions showing as nodes of a different shape or color to screen states.

@npark-mozilla

**Comment by jhugman** [comment]
>> If a screen state A has a noop to another state B (or action), then you can goto(A) without going to B. If you ask to goto(B) from A then nothing visible will happen on screen.

> What if you are in B, and you say goto(A)?  would it know that A = B when noop() is specified in A only? (or should I specifiy noop(A) in B's state description as well?

In the previous usage, `noop` was a convenient way of doing an `include`; as in: you can compose screen states in multiple re-usable parts. I started thinking about an `include` format, but couldn't think of a better syntax as a simple function.

```swift

func makeURLBarAvailable(_ screenState: ScreenState<FxUserState>) {
  screenSate.press(app.textField["url"], forDuration: 2, to: URLBarLongPressMenu)
}

map.addScreenState(BrowserTab) { screenState in 
  makeURLBarAvailable(screenState)
  makeToolBarAvailable(screenState)
}

map.addScreenState(NewTabScreen) { screenState in 
  makeURLBarAvailable(screenState)
}
```



> I just realized that regarding screenaction, my confusion came from this declaration in map.addScreenState(BrowserTab) example above:
```screenState.gesture(forAction: Action.LoadURLByTyping, Action.LoadURL) ```
So this means "following set of actions defines Action.LoadURLByTyping, and it leads to Action.LoadURL action" right?  If so, it would make it more clear if we have to: parameter between, like old Objective-c, like (maybe this syntax is deprecated now): 
```screenState.gesture(forAction: Action.LoadURLByTyping, to: Action.LoadURL) ```

Yeah, adding a name to the argument is definitely possible, but I'm not completely sure what it is yet.

```swift
screenState.gesture(forAction: Action.LoadURLByTyping, implementing: Action.LoadURL) { userState in 
  // do the thing.
}
```

Should it be `to`, `implementing`, `as`, `alias`?

Also: currently we can have arbitrarily long chains of actions. In practice, will we ever need more than a chain of two?

>>>    Also, it would be nice if we can set dismissOnUse() as part of UserState. There may be cases >>where going back is possible, but really you shouldn't.

>>Can you give me some examples where this might be useful? If this is never advisable, then should you just not wire it together like that?

>I was thinking about case where Screengraph decides going back is the optimal path, for example,

>A -> B -> C.
>I want to go to E.
>Screengraph decides that C -> B -> E is faster than C -> D1 -> D2 -> D3 ->E
>But going back to B will change state.
>But you're right, I guess in this case, it's simpler to outline the paths to E, rather than having additional logic inside screengraph.

I'm still a bit confused. Could you give me concrete examples from your use with FxScreenGraph and Firefox for iOS.


> For the error strings, I was thinking about something even simpler, like, If I'm in State A, and want to go to B using action C, it should give me error messages when action C fails for whatever reason, and the error message should output the exact UI action that failed, like "could not go to State B because ui action x failed, last successful UI action was y" without adding error checks directly into state definitions. BUT in past weeks, I noticed this is already implemented for the most part. 

Yeah, the failures are reported in `FxScreenGraph.swift` and the test itself. Unfortunately, Xcode often doesn't report the second place the failure occurred, so you don't get nice reporting within the IDE.

> It would be nice if it had more details, like last successful action, (but this is not absolutely needed)

I can report a lot to the console. It's especially easy to report to `NSLog` or standard out.

What details would you like?

**Comment by npark-mozilla** [comment]
>> Should it be to, implementing, as, alias?

I guess 'to' would be straightforward?

>> I'm still a bit confused. Could you give me concrete examples from your use with FxScreenGraph and Firefox for iOS.

Oh, I was just saying that I got the rationale and we don't need to do anything here.

>> I can report a lot to the console. It's especially easy to report to NSLog or standard out.
What details would you like?

It would help if it lists the current state that it is in now, last successful UI action, and the intended destination state (maybe this one is already shown in the error log)

**Comment by farhanpatel** [comment]
I think this is probably addressed somewhere else. Closing this.
