### ISSUE TITLE
Little too close to the bottom. 

### ISSUE THREAD

**Issue by farhanpatel** [mozilla-mobile/firefox-ios#3363]
Little too close to the bottom. 

![screenshot](https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/57bf25c0f096bc01001e21e0/59e911e6e4d6b10001729871/74a48832-81d1-4b00-8de2-1dcfed7bbbba.jpg)

 [Link to buddybuild feedback from build 7173](https://dashboard.buddybuild.com/apps/57bf25c0f096bc01001e21e0/feedback?fid=59e97394f4025c000144c64e&bnum=7173)

**Comment by garvankeeley** [comment]
Oops, I clicked the github issue button on the BB feedback, closing
