### ISSUE TITLE
readerModeBar (and status bar) should hide on scrolling down.

### ISSUE THREAD

**Issue by aranasaurus** [mozilla-mobile/firefox-ios#3451]
Currently when using reader mode, the readerModeBar and status bar are always visible (and light-colored). I expect reader mode to be full screen with no chrome whatsoever (like Safari). 

I went looking through the BrowserViewController and didn’t see anything related to scroll events, so if it’s not possible to hide the bar completely, it’d be nice if it at least respected the dark mode toggle. Currently if you turn on reader mode and set it to dark, you’re stuck with a bright light-gray bar at the top along with the default status bar.

**Comment by cpeterso** [comment]
Fennec hides the address bar when scrolling in the normal page view, so it's surprising that it does not hide the reader mode toolbar when scrolling. Reader mode is supposed to be about removing all UI distractions. :)

**Comment by garvankeeley** [comment]
@cpeterso we use bugzilla, I recommend filing there for traction on this issue.

**Comment by cpeterso** [comment]
oops! Thanks. I have now filed [bug 1442857](https://bugzilla.mozilla.org/show_bug.cgi?id=1442857) for this issue.
