### ISSUE TITLE
Remote Debugging

### ISSUE THREAD

**Issue by davidolen** [mozilla-mobile/firefox-ios#3521]
Is there a way to remote debug web applications running in firefox-ios?

WebIDE seems not work for firefox-ios.

**Comment by ExE-Boss** [comment]
That isn’t currently implemented and I don’t know if Apple would allow it, but if you have a Mac (costs a lot of money) and Xcode with the Apple Software Developer License (costs 100$ a year), you can do remote debugging using Safari.

**Comment by davidolen** [comment]
Thanks! Hope this can be added in some day.
