### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by xuxueyong** [mozilla-mobile/firefox-ios#3559]
Share module compiled, reported No such module SwiftyJSON, hoping to give advice, how to do it

**Comment by MatrixMiaou** [comment]
I got the same issue as u.

**Comment by JeromeTW** [comment]
+1

**Comment by HornMichaelS** [comment]
Did you follow all of the code in [Building the Code](https://github.com/mozilla-mobile/firefox-ios#building-the-code), including installing carthage and running the bootstrap script?

**Comment by mkjfeng01** [comment]
same issue

**Comment by garvankeeley** [comment]
To the reporters, please indicate if you have followed the advice above in https://github.com/mozilla-mobile/firefox-ios/issues/3559#issuecomment-359638438
This project will not build without following the build instructions.

**Comment by evgeniyd** [comment]
Also, look through the `bootstrap.sh`'s output and make sure there is no errors during the setup.

**Comment by tomhutchi** [comment]
> Also, look through the `bootstrap.sh`'s output and make sure there is no errors during the setup.

Please note if your `Xcode Command Line Tools` are not setup correctly then `bootstrap.sh` will not pull in the dependencies such as SwiftyJSON correctly. This can get mangled if you have multiple versions of Xcode installed.

**Comment by anthonycmain** [comment]
Looking carefully this happened because I was getting the error:

Unrecognized arguments: --cache-builds

My Carthage was not up to date I have to manually remove it and reinstall using brew as the upgrade wasnt working

brew uninstall carthage
brew install carthage

**Comment by shyamrox** [comment]
@anthonycmain 's solution worked for me.
