### ISSUE TITLE
Cannot rearrange/move tabs.

### ISSUE THREAD

**Issue by Novantix** [mozilla-mobile/firefox-ios#3573]
The ability for moving, rearranging and possibly even pinning frequently use tabs in the tab bar so it does not disappear when scrolling to other tabs would be excellent.

 I want to learn programming to be able to start contributing to Firefox on ios but as of yet I am not of ability to do so. 

Anyone that could possibly implement this feature would be fantastic!

**Comment by garvankeeley** [comment]
is now available on master
