### ISSUE TITLE
I want to know how the WKWebView used in this project keeps cookies,

### ISSUE THREAD

**Issue by lotus-lotus** [mozilla-mobile/firefox-ios#3613]
I want to know how the WKWebView used in this project keeps cookies,in (https://stackoverflow.com/questions/38098567/update-wkwebview-cookie-values),It didn't solve my problem. This will result in switching the network.(Switch 4G WIFi or Switch WIFi 4G),Causes web page blank, calls redirection method.(-didReceiveServerRedirectForProvisionalNavigation),I hope you can refer to your project and help me solve it.Heartfelt thanks.

**Comment by made2k** [comment]
I was playing around with that looking at if third party cookies are accepted and from what I found was no, they are not. I attempted to allow them by setting the value for `cookieAcceptPolicy` on the configurations process pool but that didn't change anything. 

You can see here https://github.com/WebKit/webkit/blob/c637754ee7dfca6142e441d2040026903fee0c1f/Source/WebKit/UIProcess/API/Cocoa/WKProcessPool.mm#L200 the value I was attempting to set. One thing to note, is I have block third party cookies set in Settings->Safari so maybe that sets the value for WKWebView.

**Comment by farhanpatel** [comment]
`cookieAcceptPolicy` should let you set the configuration for the cookies. If you'd like to access the cookies look for the cookieStore.
