### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by VectauryPernic** [mozilla-mobile/firefox-ios#3734]
Share module compiled, reported : 
Module compiled with Swift 4.0.3 cannot be imported in Swift 3.3: .../firefox-ios-master/Carthage/Build/iOS/SwiftyJSON.framework/Modules/SwiftyJSON.swiftmodule/x86_64.swiftmodule,
hoping to give advice, how to do it

**Comment by alexzhaobin** [comment]
I have same issue after upgrade XCode to Version 9.3 (9E145).

**Comment by anatoliykant** [comment]
They fixed this error.
Thanks, mozila team!

**Comment by anatoliykant** [comment]
You need to download this repository again.
