### ISSUE TITLE
I update my XCode and 'Carthage Update' but scheme "Fuzi" build failed

### ISSUE THREAD

**Issue by victorylau** [mozilla-mobile/firefox-ios#3832]
Xcode version : 9.3
Carthage version: 0.29.0

![image](https://user-images.githubusercontent.com/12857363/38858789-2f1ae18a-425f-11e8-9f86-16cf260fd7e4.png)

**Comment by LarsChen** [comment]
change Fuzi  version to "2.0.2",Fuzi remove wrapping libxml2 modulemap for Xcode 9.3 in this version!

**Comment by victorylau** [comment]
@LarsChen Thanks!  it works for me!
