### ISSUE TITLE
Does anybody know where logins are stored for FireFox in iOS i.e. login.json location?

### ISSUE THREAD

**Issue by cyberfunk** [mozilla-mobile/firefox-ios#3883]
Hello can anyone point me to the location of the logins.json file for FireFox mobile app? In particular I use iFile file explorer in iOS so a file path is what I'm looking for. Auto-fill doesn't work with synced passwords and I'd like to get to the bottom of it. I filed an issue at Mozilla but don't expect to hear back as it's been a while. 

If I add a password through the mobile app Auto-fill works just fine for that specific password but synced desktop passwords will not auto-fill. I'd like to inspect the logins.json and see if mobile Firefox is adding any additional code to mobile created login entries vs. desktop synced login entries. Any help is much appreciated.

**Comment by Jageen** [comment]
It might be stored in keychain instead of json file.
are you familiar with iOS development ?

**Comment by garvankeeley** [comment]
In an sqlcipher encrypted file called logins.db

**Comment by Thuta13** [comment]
Thank you. It solved my problem too.

**Comment by cyberfunk** [comment]
garvankeeley Do you have any tips on manually migrating passwords from desktop to iOS. FireFox will not sync passwords to iOS that have previously been deleted even if you restore them manually on desktop. Something to do with timestamps associated with the deletion of the passwords and sync on iOS. I need to update my iOS passwords manually. Desktop shows over 200 passwords iOS shows none. Re-syncing, disconnecting and deleting and then re-installing the iOS app do not solve my issue.
