### ISSUE TITLE
__firefox__.searchQueryForField is not a function

### ISSUE THREAD

**Issue by Matrosskin** [mozilla-mobile/firefox-ios#3884]
Hello Guys. Does anybody able to provide details/reasons about closing the issue https://github.com/mozilla-mobile/firefox-ios/issues/2288 ?

**Comment by FredyC** [comment]
This feels so unprofessional from @farhanpatel to close obviously repeated issue without any explanation. It is still happening almost two years later and nobody even attempts to fix it?

I am going to ping some contributors here to hopefully get an answer.

@justindarc @isabelrios @garvankeeley

**Comment by justindarc** [comment]
I don't see any steps to reproduce the error. Can someone provide them here? Thanks!

**Comment by justindarc** [comment]
@Matrosskin opened a bug in Bugzilla to track a fix: https://bugzilla.mozilla.org/show_bug.cgi?id=1523354

If you can provide STR, that would be great to verify a fix. Thanks!

**Comment by justindarc** [comment]
PR #4500

**Comment by FredyC** [comment]
Thank you @justindarc for such a prompt reaction and a fix. It felt really weird that it's being ignored like this. I do not have STR, I just saw a Sentry report once for our app, but it's great this is out the field.

**Comment by Matrosskin** [comment]
Sorry for late answer and thank you @justindarc for reaction! I also have not STR, only saw reports about error. We still have a few error reports 5 days ago but as I believe it just require some time to deliver fix to users. So I going to close the issue at the moment.
