### ISSUE TITLE
OAuth 2 authorization flow custom scheme redirect not handled

### ISSUE THREAD

**Issue by julienbodet** [mozilla-mobile/firefox-ios#3989]
I have an app using [AppAuth](https://github.com/openid/AppAuth-iOS) to perform an OAuth 2 authorization flow. AppAuth supports authorization flow in custom browsers like Firefox.

I tried to perform the authorization flow in Firefox iOS with a custom scheme redirect URI (`myapp://`) but the redirection to the app is never fired.

I had a look at `BrowserViewController+WKNavigationDelegate.swift` and I clearly see that it's not supported. Firefox doesn't seem to handle all the custom schemes other than Apple maps, App Store, mail-to, etc...

Is it the intended behaviour or might be a bug?

At least handling custom schemes and having a confirmation alert would be nice.

EDIT: Opened a bug in [Bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1470664)

**Comment by Jc692488** [comment]
Fix issues
