### ISSUE TITLE
gut out firefox gui for engine us

### ISSUE THREAD

**Issue by L2L2L** [mozilla-mobile/firefox-ios#4352]
I'm trying to use firefox-ios to host my own app, don't understand why firefox don't have something like this already for web dev. I build a app but only work on firefox desktop window engine so I'm looking to just use this code to host my web app for me so I don't have to worry about cross bowers problems.

**Comment by a2sheppy** [comment]
Firefox for iOS is using the standard WebKit API build right into the phone's OS. The engine is already available; see Apple's documentation.

Hopefully one day we will be allowed to bring Gecko to iOS. But that day has not come.

**Comment by TGTWbeacon** [comment]
* Acknowledging takes time 
* Understanding comes from forgiveness 
* Listening your trusted mentor 
* Believing in your faith
* Following your own heart
* Loving the way you are

Sorry for these irrelevant responses. But it comes from my heart.
