### ISSUE TITLE
Consider adding a “Clear Private Data when closing Firefox” toggle

### ISSUE THREAD

**Issue by TheOriginalTomO** [mozilla-mobile/firefox-ios#4505]
Hi @garvankeeley @farhanpatel and @justindarc - the privacy features of Firefox are already excellent, however including another Settings option may further enhance privacy. 

An additional “Clear Private Data when closing Firefox” toggle could automate an existing manual feature. In Data Management settings, there is the “Clear Private Data” button for users to manually select. With the proposed toggle enabled, however, this would mimic the action and behaviour of tapping the clear button by virtue of closing the app. 

I wonder if this addition is possible - in Firefox for desktop there is this option. I know there are other users that miss this option. 

Many thanks for a great app!

**Comment by justindarc** [comment]
If you enter Private Browsing mode, there's already a feature that automatically clears data on exit.
