### ISSUE TITLE
Make changing Tracking Protection settings easier

### ISSUE THREAD

**Issue by davidjb** [mozilla-mobile/firefox-ios#4511]
Filed at https://bugzilla.mozilla.org/show_bug.cgi?id=1526141

---

I use the Strict block list in Firefox for iOS to block the widest gamut of trackers; with this setting enabled, most websites work fine.  However, occasionally, there will be the odd site that doesn't function with the Strict block list but will work under the Basic block list instead, which I then fall back to using. Turning off Tracking Protection entirely is another option but means that no trackers will be blocked at all, which is an unnecessary compromise because in sites that I've encountered, the sites will operate successfully under the Basic block list instead.

So, to work around this issue, if I want to load a site in this manner, I do the following:

1. Tap Menu
1. Tap Settings
1. Scroll down and find Tracking Protection
1. Tap "Basic"
1. Tap to go back and then Done
1. Reload the page in question
1. Repeat all the above steps to re-enable the Strict block list

This is a cumbersome process to follow and prone to error in case of forgetting to re-enable the Strict block list as this setting has no visibility in the UI until you go through that many menu levels into the Settings.

I know Firefox for iOS provides the ability to reload a tab without tracking protection (eg long-tap of reload icon, tap  "Reload without Tracking Protection") or to turn off tracking protection (eg Hamburger icon —> toggle "Tracking Protection"), but both of these options require disabling tracking entirely, which is unnecessary when I know the Basic block list is sufficient to make a page work, or want to attempt using the Basic block list before having to fall back to no Tracking Protection.   

I'd like to have the ability to avoid the complexity of having to switch block lists, and ideally just temporarily for a given tab.  So, effectively the same experience as toggling Tracking Protection on/off, but rather which block list is used.

Can the ability to switch block lists & see which is in force be added to the top-level UI?  The switcher could be under the tap-and-hold menu on the Refresh icon and the UI for seeing the blocklist in use could be shown when tapping the Shield icon where tracker details are listed.

**Comment by JsonPipe** [comment]
I agree. Tracking Protection on iOS as well as Desktop is not a good user experience. Brave actually does this well. I wish Firefox would take notice.

**Comment by justindarc** [comment]
We're planning on making some changes to this feature where this requested change may no longer make sense.

**Comment by davidjb** [comment]
@justindarc Any chance you could elaborate?  If changes to tracking protection are at a planning stage, it would be great to be able to contribute to those discussions.
