### ISSUE TITLE
PassWord database location in iOS?

### ISSUE THREAD

**Issue by cyberfunk** [mozilla-mobile/firefox-ios#4526]

**Comment by cyberfunk** [comment]
Hello. On desktop FireFox for Mac logins are stored in key4.db and logins.json in the profile folder. Can you tell me the location of these files in iOS? I'm navigating with Filza and have looked through the Application folder but cannot figure out where these logins are stored. I need to update my iOS FireFox logins manually because FireFox will not sync previously deleted passwords that have been restored to desktop in iOS. I hope I explained my issue clearly.

**Comment by garvankeeley** [comment]
It is logins.db in the application group directory

**Comment by cyberfunk** [comment]
Thanks I realized logins.db is not editable and key4.db and logins.json cannot be integrated/migrated over from desktop. In the end I used a combination of the ancient ff43 extension passwords-exporter and the newer ffpass python app. It was touch and go but at long last everything is up and running again. Would love to see native password import and export on the iOS side in the future.
