### ISSUE TITLE
Feature Request: support swipe to delete for bookmarks

### ISSUE THREAD

**Issue by foss-** [mozilla-mobile/firefox-ios#4557]
Two fold report:

**1. feature request**
**Expected**
please allow deleting bookmarks by swiping right to left and then offering an option to "Delete" as red button that shows after the swipe
**Currently**
A swipe on a bookmark does nothing, which feels odd and wrong.

**2. can bookmarks on Firefox iOS be deleted at all?**
This [KB](https://support.mozilla.org/en-US/kb/how-add-and-remove-bookmarks-firefox-ios) claims it should be possible, but it doesn't seem to apply when I try following the steps in Firefox v15 on iOS 12.1.4.
**Expected**
Form the KB: Open bookmarked page, Tap page actions menu (three dots) and "Remove Bookmark"
**Currently**
I'll provide detailed steps to make sure this has any specifics that may be relevant (loosely translated from german):
1. Tap bottom right hamburger menu > Library > Desktop-Bookmarks  > Bookmarks-Bar > One_of_my_folders > some_bookmark (that's also the view where I would expecte swipe to delete functionality)
2. when pressing the page actions menu (three dots) I am offered to "Add bookmark for this page", which is quite funny as I just opened it from the bookmarks folder.

This feels like Firefox iOS seems to differentiate between bookmarks synced from desktop and bookmarks created on iOS.

That differentiation feels very wrong to me. Why would I want various bookmark structures behaving differently on different hardware. Either I am missing something here or there is quite a lot of work to be done in this area. Maybe someone with more insight can elaborate what's going on and how this is expected to be handled by users. The way it currently behaves feels like I am doing doing something very stupid and I am not sure if it's me, firefox or a combination of both which is at fault.

**Comment by farhanpatel** [comment]
We're working on being able to remove desktop bookmarks right now. This feature is more complicated due to sync.

**Comment by foss-** [comment]
Thanks for the update. Not sure though why this was closed without a commit. Is there a bugzilla item to follow?
