### ISSUE TITLE
Build failure using Xcode 10.2 Swift-5

### ISSUE THREAD

**Issue by majd-asab** [mozilla-mobile/firefox-ios#4671]
Hello folks, 
I'm not able to build the project using the latest Xcode. When I run bootstrap.sh, i get this:

> sh ./bootstrap.sh 
*** Checking out ios_sdk at "v4.17.1"
*** Checking out application-services at "v0.22.1"
*** Checking out Deferred at "35b8927c1b94ce074e10793c57e1f80d0e2227fa"
*** Checking out GCDWebServer at "3.3.2"
*** Checking out Fuzi at "2.0.2"
*** Checking out MappaMundi at "8b2001cf750768bc5d5317e3aae5cc3a43818064"
*** Checking out KIF at "v3.7.3"
*** Checking out telemetry-ios at "v1.1.0"
*** Checking out Alamofire at "4.8.2"
*** Checking out onepassword-app-extension at "bcc4cc97fed9a6e73fa204f2e61138e353cb3ef7"
*** Checking out SDWebImage at "4.1.0"
*** Checking out EarlGrey at "ce90f3ffabfb9cfcda73bcbcdd8844c47fede04e"
*** Checking out sentry-cocoa at "4.0.1"
*** Checking out SwiftKeychainWrapper at "46e5980ee7630be015aae6a6307c2fe1e8f3661d"
*** Checking out SnapKit at "3.1.2"
*** Checking out XCGLogger at "Version_4.0.0"
*** Checking out swift-protobuf at "1.3.1"
*** Checking out SwiftyJSON at "3.1.4"
*** xcodebuild output can be found in /var/folders/6g/bjt_yyrs0jn31x6pwnn71g080000gn/T/carthage-xcodebuild.Cg4cIg.log
*** Valid cache found for Alamofire, skipping build
*** No cache found for Deferred, building with all downstream dependencies
*** No cache found for EarlGrey, building with all downstream dependencies
*** No cache found for Fuzi, building with all downstream dependencies
*** No cache found for GCDWebServer, building with all downstream dependencies
*** Valid cache found for ios_sdk, skipping build
*** No cache found for KIF, building with all downstream dependencies
*** No cache found for MappaMundi, building with all downstream dependencies
*** No cache found for onepassword-app-extension, building with all downstream dependencies
*** No cache found for SDWebImage, building with all downstream dependencies
*** Valid cache found for sentry-cocoa, skipping build
*** No cache found for SnapKit, building with all downstream dependencies
*** No cache found for swift-protobuf, building with all downstream dependencies
*** No cache found for SwiftKeychainWrapper, building with all downstream dependencies
*** No cache found for SwiftyJSON, building with all downstream dependencies
*** No cache found for telemetry-ios, building with all downstream dependencies
*** No cache found for XCGLogger, building with all downstream dependencies
*** Downloading application-services.framework binary at "v0.22.1"
***  Skipped installing application-services.framework binary due to the error:
	"Incompatible Swift version - framework was built with 4.2.1 (swiftlang-1000.11.42 clang-1000.11.45.1) and the local version is 5.0 (swiftlang-1001.0.69.5 clang-1001.0.46.3)."
    Falling back to building from the source
*** Building scheme "Deferred" in Deferred.xcodeproj
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project  /Users/user/openSource/firefox-ios/Carthage/Checkouts/Deferred/Deferred.xcodeproj -scheme Deferred -configuration Release -derivedDataPath /Users/user/Library/Caches/org.carthage.CarthageKit/DerivedData/10.2_10E125/Deferred/35b8927c1b94ce074e10793c57e1f80d0e2227fa -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/6g/bjt_yyrs0jn31x6pwnn71g080000gn/T/Deferred SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/user/openSource/firefox-ios/Carthage/Checkouts/Deferred)
This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/6g/bjt_yyrs0jn31x6pwnn71g080000gn/T/carthage-xcodebuild.Cg4cIg.log

Anybody had any luck?

**Comment by vinayakparmar92** [comment]
@mafeld I am facing the same issue. Can you suggest what fix you applied please?
