### ISSUE TITLE
Reader view should switch to a darker theme when using Night Mode

### ISSUE THREAD

**Issue by farhanpatel** [mozilla-mobile/firefox-ios#4700]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1415109

Build: 10.0 (7617)
Device: iPad mini 4
iOS: 11.1

Steps to reproduce:
1. Go to bbc.com
2. Open the menu and turn "Night Mode" On
3. Open an article
4. Tap on the Reader View icon

Actual results:
- The content in Reader View is bright as the default theme is "Light".

Suggested solution:
- When using Night Mode we should use as default the "Dark" theme in Reader View.

**Comment by farhanpatel** [comment]
remove controlling dark/light mode from reader view and instead just do what night mode is doing.

**Comment by peterkos** [comment]
I'd love to take this on! 

I would also assume the theme switches between night<->day/sepia as the user switches dark mode on/off?

**Comment by isabelrios** [comment]
Asking @garvankeeley to clarify the question so that @peterkos could take this issue if still interested...Thanks!

**Comment by garvankeeley** [comment]
Yikes we left this a while to reply, but yes it is ok to take.

**Comment by csuciu** [comment]
Verified as fixed on master aaf14a9.
