### ISSUE TITLE
unable to save image (rotating the screen fixes it)

### ISSUE THREAD

**Issue by farhanpatel** [mozilla-mobile/firefox-ios#4701]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1417132

Version 10.1 (7709)

STR:

- go to http://design.firefox.com/people/smartell/quantum/firefox-quantum_launch-poster_24x36.jpg
- try to save the image. long press does nothing. hamburger menu doesn't have anything that seems appropriate. ellipsis menu has "share page" that doesn't include "save image".
- ellipsis menu, copy URL. open safari. paste url, go. share icon has "save image" as first option.

Expected:

- some way to save image

**Comment by SimonBasca** [comment]
Tested on iPhone X (11.4) on 16.0 (14732). In am unable to reproduce this issue.
