### ISSUE TITLE
view-source:// URLs should open in Firefox.

### ISSUE THREAD

**Issue by farhanpatel** [mozilla-mobile/firefox-ios#4702]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1424813

As per tweet: https://twitter.com/aardrian/status/939519977362771969

we should allow view-source:// links to open in Firefox.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2064)

**Comment by farhanpatel** [comment]
This will require the following strings
"View Page Source"

**Comment by data-sync-user** [comment]
➤ Tiffanie Shakespeare commented:

Removing needs ux label - this is a feature request/product improvement which should be a project that flows through our product road map.
