### ISSUE TITLE
NSString+Utils's randomAlphanumericStringWithLength should probably never be used

### ISSUE THREAD

**Issue by farhanpatel** [mozilla-mobile/firefox-ios#4709]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1471296

I came across https://github.com/mozilla-mobile/firefox-ios/blob/13186294f11b9bfc3279f94d7497ffcf6691a7a8/FxA/FxA/NSString%2BUtils.m by accident, and while it's hardly an issue that actually matters (it's a function nobody should call, and thankfully nobody calls it), it's probably worth deleting.

Given that this is in a directory with a bunch of crypto code, someone would be forgiven for thinking this uses cryptographically secure RNG. It does not.

It doesn't even use a good non-cryptographically secure RNG (`rand()` is pretty terrible).

Anyway, as mentioned, AFAICT nothing calls this so it should just be a matter of deleting it? Hopefully?

**Comment by justindarc** [comment]
@farhanpatel does that `FxA` Xcode project live in its own repo anywhere else or does it only exist in our repo?
