### ISSUE TITLE
Allow Request Desktop Site to be set permanently

### ISSUE THREAD

**Issue by farhanpatel** [mozilla-mobile/firefox-ios#4710]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1473884

Perhaps this is a setting, perhaps it's an mode (like Night Mode).

When the user is using an iPad / large screen — especially with a keyboard, there is plenty of real estate on the screen to display a desktop version of the site.

Sites sniffing iOS user agents tend to give more compact versions of the site, and also nag dialogs to install the iOS app.

Submitted on behalf of a contributor.

**Comment by bryanbell** [comment]
!(https://mozilla.invisionapp.com/static-signed/live-embed/22240415/358313233/1/latest/T6tw73oETtwIJdkKynvcPtRIfG6Gw4YDZAKAmWWWmffVqcaRyvK1N01fSZ3heqw5GHGucvhC6SU9PLUyg2Oe0QlE/Artboard-2x.png)

**Comment by bryanbell** [comment]
Mockup: https://mozilla.invisionapp.com/share/ZURK6G9TSVN

![mockup](https://mozilla.invisionapp.com/static-signed/live-embed/22240415/358313233/1/latest/T6tw73oETtwIJdkKynvcPtRIfG6Gw4YDZAKAmWWWmffVqcaRyvK1N01fSZ3heqw5GHGucvhC6SU9PLUyg2Oe0QlE/Artboard-2x.png)
