### ISSUE TITLE
Visual Indicator for Hide Images

### ISSUE THREAD

**Issue by farhanpatel** [mozilla-mobile/firefox-ios#4712]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1481914

Created attachment 8998605
fullsizeoutput_6290.jpeg

I accidentally flipped the switch for "Hide Images", and got to the point of rebooting my phone and preparing to open a bug report when I finally clued in. 

It feels like hide images may need some visual indicator (like the tracking protection icon) when it is activated. 

In the attached screenshot, Hide Images is on, but it's impossible to tell if there was a bug with loading images, or if Hide Images is active.

**Comment by garvankeeley** [comment]
Prototype of re-using PB badge for this: https://github.com/garvankeeley/firefox-ios/tree/garvan/toolbar-badge

**Comment by bryanbell** [comment]
![Image](https://mozilla.invisionapp.com/static-signed/live-embed/22240415/357977912/1/latest/xHT9y8Hc0k377fE3EdwZb4qHNweih14hDBG2FOaEtjdZNcLKnZqsfqRcpN9TlEL458j2kWzgVEvdpSiMmCVlu5glE/Artboard-2x.png)

**Comment by bryanbell** [comment]
Here are two new parts you'll need to finish this feature, a mask for chomping out space over the existing icon that needs to be color matched to the backdrop that icon is found on, and a blue badge.
[badge-mask.pdf](https://github.com/mozilla-mobile/firefox-ios/files/3092032/badge-mask.pdf)
[Uploading badge.pdf…]()
