### ISSUE TITLE
History Panel: Icons appear disabled while the text and disclosure appear enabled

### ISSUE THREAD

**Issue by farhanpatel** [mozilla-mobile/firefox-ios#4726]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1536124

Created attachment 9051728
Screenshot 2019-03-18 at 16.59.12.png

Master
Steps
-Have some history, close some websites

Actual
Recently closed icon and Clear Recent History icons are shown in grey while the text is black since the option is already active.
Please see screenshot attached

Expected
Both icon and string should be shown with similar color.

**Comment by garvankeeley** [comment]
Essentially, the icon, text, and disclosure indicator should have a the same color for enabled and disabled state.
