### ISSUE TITLE
Settings for New Tab and Home: deselecting Custom URL should not clear it

### ISSUE THREAD

**Issue by farhanpatel** [mozilla-mobile/firefox-ios#4730]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1541559

STR:
1) open Settings>New Tab
2) Set a custom URL (i.e. http://www.example.com)
3) tap a different cell (i.e. Firefox Home)
4) Bug: custom URL is cleared

Expected behaviour: custom URL is kept, just not checked off.

Dev note: StringSetting onConfigureCell() does the setting of the checkmark on/off by making it transparent:
 cell.tintColor = self.persister.readPersistedValue() != nil ? UIColor.theme.tableView.rowActionAccessory : UIColor.clear

**Comment by nick130586** [comment]
What should happen when we check it off, leave the screen, then open it again? Should the custom URL field be cleared then?

**Comment by garvankeeley** [comment]
https://github.com/mozilla-mobile/firefox-ios/commit/a7a1a2a9803b13c83e23a1b0ad28ecde6d1bec14 is a partial fix, retaining the typed url while the user hasn't exited the view.
