### ISSUE TITLE
Constant HTTP basic auth prompts on www.rr18xx.com

### ISSUE THREAD

**Issue by farhanpatel** [mozilla-mobile/firefox-ios#4731]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1542017

As reported by ckarlof, the site www.rr18xx.com constantly prompts for HTTP basic auth credentials. We can register for an account to test here:

http://www.rr18xx.com/cgi-pub/cxd_user_reg.cgi

**Comment by garvankeeley** [comment]
The WKNSURLAuthenticationChallenge.protectionSpace.host is reported as `www.paypalobjects.com`. This is a site configuration bug IMO.

**Comment by garvankeeley** [comment]
Broken as of this commit: https://github.com/mozilla-mobile/firefox-ios/pull/4504
