### ISSUE TITLE
Wrong FxA will be displayed after updating to 16.0(14696).  FxA 'A' is diplayed instead of FxA 'B'

### ISSUE THREAD

**Issue by farhanpatel** [mozilla-mobile/firefox-ios#4734]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1542192

Build 16.0(14696)
Device iPhone SE iOS 11.4.1

Preconditions:
- Log in with FxA A on build 16.0(14696)
- Delete build 16.0(14696)

1.Install Mozilla iOS 15.0(13894)
2.Create account FxA B and confirm the sign in registration
3.Update to 16.0(14696)
4.Tap on on "hamburger" sign and check the account email address 
5.Go to the account management page

Actual result:
Firefox for iOS will be displayed that it's syncing with FxA A. Going to the Account Management page will display that FxA B is connected, the sync is correctly performed with this account

Expected result:
Firefox for iOS should display that it's syncing with FxA B in both hamburger menu and account management page.

Notes:
Update from 15.0(13894) to 16.0(14696) 
Update from 15.1(14275) to 16.0(14696)
Not reproducible when updating to 16.0(14696) after factory device reset

**Comment by garvankeeley** [comment]
This is a blocker for weekly syncfest testing, because users are going to stop testing when it appears the wrong FxA account is syncing, and thus is a security risk.
