### ISSUE TITLE
Onboarding pagination dots are no longer tappable, should be

### ISSUE THREAD

**Issue by farhanpatel** [mozilla-mobile/firefox-ios#4745]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1400937

The pagination dots in the updated onboarding tour are no longer tappable. They should be.

https://developer.apple.com/documentation/uikit/uipagecontrol

**Comment by aserdobintsev** [comment]
Onboarding pagination dots are tappable now. 
I've just checked on iPhone 7 iOS 12.3.1, iPad Pro Simulator 12.9 inch 3rd generation iOS 12.2, iPhon XR Simulator iOS 12.2.
This issue should be closed.

**Comment by dnarcese** [comment]
Our new onboarding doesn't have pagination dots anymore.
