### ISSUE TITLE
Cannot copy version

### ISSUE THREAD

**Issue by farhanpatel** [mozilla-mobile/firefox-ios#4751]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1534856

User Agent: Mozilla/5.0 (X11; Linux x86_64; rv:65.0) Gecko/20100101 Firefox/65.0

Steps to reproduce:

User is asked what version of the browser he is using.

Actual results:

User finds it in Settings, but what meager version information he sees can't even be copied off the screen. He is forced to make a screenshot.
And furthermore, he gives up and gets much more information from 
https://whatsmybrowser.org/b/KWYCXMP !
Like e.g., the name of the browser too.

Expected results:

See also Bug 1229387.

**Comment by akarataev** [comment]
I'm looking at this if nobody is against.
