### ISSUE TITLE
[FxA] iOS not displayed as connected device on Android 9

### ISSUE THREAD

**Issue by farhanpatel** [mozilla-mobile/firefox-ios#4756]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1543104

From:
https://github.com/mozilla/fxa/issues/760

STR:

1. Sign in on iOS, Android and Windows 10 with the same account.
2. Go to Manage Accounts - Devices & Apps and observe the connected devices.

Expected results:

All devices should be displayed.

Actual results:

On Android, the iOS device is not displayed, it appears that none is connected.

**Comment by garvankeeley** [comment]
Do we know if this is reproducible? @SimonBasca can you try?

**Comment by SimonBasca** [comment]
This is no longer reproducible with latest Android.
