### ISSUE TITLE
[XCUITests] Fix testSavedLoginAutofilled

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/firefox-ios#4764]
This test is part of the Smoketest and is failing looks like due to a change in the LinkedIn page used. See failure[ here](https://dashboard.buddybuild.com/apps/57bf25c0f096bc01001e21e0/build/5cad401225a6a2000170a6e1/test/627e6a5b-e71a-48ca-9dab-8709a0015f8a/0bc762a6-03b8-49a1-9377-8a3b273dc070)

**Comment by isabelrios** [comment]
Removing assignment since this test is going to be fixed by using a fixture website instead of a real one. That would imply more work and @kglazko will be taking a look at it

**Comment by kglazko** [comment]
PS Assigning to self via comment, don't have permission to self-assign
