### ISSUE TITLE
Re-enable bookmarks keyword search

### ISSUE THREAD

**Issue by justindarc** [mozilla-mobile/firefox-ios#4779]
Previously, we had support for bookmarks keyword searches in the AwesomeBar. To continue to support this, we will need the following issue in application-services to be resolved:

https://github.com/mozilla/application-services/issues/953

**Comment by swrobel** [comment]
FYI this was resolved upstream!

**Comment by DougAK** [comment]
> FYI this was resolved upstream!
So in which version should we see the keyword search working again? It's not working for me in v19.0 (16042) on iOS13.1.

**Comment by lohfu** [comment]
Any progress on this?

**Comment by AlbanSagouis** [comment]
I believe this issue has been solved. Thank you!

**Comment by athomasmoz** [comment]
Closing as this functionality is now available
