### ISSUE TITLE
Add a whats new in the applications menu

### ISSUE THREAD

**Issue by farhanpatel** [mozilla-mobile/firefox-ios#4788]
Needs a string "whats new"

**Comment by farhanpatel** [comment]
@bryanbell We'll need an icon for the application menu

**Comment by bryanbell** [comment]
Step one: add a link to What's New in the About section of the Settings.

**Comment by bryanbell** [comment]
![Mockup](https://mozilla.invisionapp.com/static-signed/live-embed/22240415/373947399/1/latest/z696lEK71UEVkL0FdAqUb8Zwj0bWbwlYSG5lE1gCTqSOOlEkgHngXjPsDJ3u45SblEvO2xq5qa2VRHDEMHAVuVFvBQlE/Artboard-2x.png)
