### ISSUE TITLE
"Your Library" vs. "Library"

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/firefox-ios#4814]
In Firefox for iOS you use the term "Your Library". The "Fenix" team made the decision to drop the "Your" from the "Your Library" string:

https://github.com/mozilla-mobile/fenix/issues/469#issuecomment-480400794

I suggest to use the same name on Android and iOS to be consistent.

**Comment by justindarc** [comment]
UX decided to not make this change on iOS. Closing.
