### ISSUE TITLE
ERROR WebserverLogin with iPhone IOS12.2, Firefox APP Version 16.0(14732)

### ISSUE THREAD

**Issue by kBilgram** [mozilla-mobile/firefox-ios#4820]
**WebserverLogin with iPhone IOS 12.2, Firefox APP Version 16.0(14732)**

With the NEW update on  Firefox or  IOS this week a **login to a webserver will be accept** but the **LOGIN page continus popup.** 

**Test account to a AXIS camera,  I do also have the problem on a other webserver**
http://wkastecher.dyndns.info:4711
User: demo
PWD: demo33

**Further tests on  iPhone IOS 12.2** 
-Safari APP ok
-Google Chrome APP ok
-Firefox 16.0(14732)  Err continus login popup window

 **Windows7** 
-Google Chrome ok
-Firefox ok

** Antroid**
-Firefox App ok

Please have a look on it. If you need furhter assistance. let me know.
I think, we do need a APP update.
Klaus

**Comment by nicoonline** [comment]
Same here...

**Comment by nicoonline** [comment]
Even with an automatic refresh every 15 seconds, there is a pop up every 15s

**Comment by nicoonline** [comment]
Has been fixed on https://github.com/mozilla-mobile/firefox-ios/commit/5518eda55fae7d05fb3d0853b35cd82a81bfea4c

**Comment by kBilgram** [comment]
Thank you, very much.

Regards Klaus

Klaus Bilgram
Käsgasse 23
88171 Weiler im Allgäu
Deutschland

Klaus.Bilgram@Wasserkraft.net<mailto:Klaus.Bilgram@Wasserkraft.net>


Von: nicoonline [mailto:notifications@github.com]
Gesendet: Sonntag, 21. April 2019 09:24
An: mozilla-mobile/firefox-ios <firefox-ios@noreply.github.com>
Cc: Klaus Bilgram <Klaus.Bilgram@wasserkraft.net>; Author <author@noreply.github.com>
Betreff: Re: [mozilla-mobile/firefox-ios] ERROR WebserverLogin with iPhone IOS12.2, Firefox APP Version 16.0(14732) (#4820)


Has been fixed on 5518eda<https://github.com/mozilla-mobile/firefox-ios/commit/5518eda55fae7d05fb3d0853b35cd82a81bfea4c>

**Comment by garvankeeley** [comment]
Marking closed fixed as of 16.1, please re-open if it re-occurs with that release.
