### ISSUE TITLE
Crash when disabling TP for a website

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/firefox-ios#4824]
This has started to happen after commit [5ecd936](https://github.com/mozilla-mobile/firefox-ios/commit/5ecd936491ebdaa4418df3e92f3622d3895333a4)

All the TP tests are affected. See for example [this test ](https://github.com/mozilla-mobile/firefox-ios/blob/4730536f913bae9e4817bd1fb03832c2bae29ba1/XCUITests/TrackingProtectionTests.swift#L157)

So far I have not been able to repro on real devices but all sims are affected.

**Comment by isabelrios** [comment]
See [BB logs ](https://dashboard.buddybuild.com/apps/57bf25c0f096bc01001e21e0/build/5cbd12114b07930001a1fec5#tests)

**Comment by SimonBasca** [comment]
Manage to reproduce this manually on iPhone 8( 11.4) iPhone X(11.4) iPhone XS (12.0). 

Steps to reproduce:
1. Go to olx.ro or any website that uses trakers
2. Tap on the shield icon in the URL bar
3. Tap "Disable for this site"

Actual results:
- Fennec will crash. After restarting Fennec the app will continue crashing.

**Comment by isabelrios** [comment]
The crash happens in [ContentBlocker.swift](https://github.com/mozilla-mobile/firefox-ios/blob/378dafbb715ed98cd361ef04da73292c62f9fd92/content-blocker-lib-ios/src/ContentBlocker.swift#L259) and it is: `Thread 1: Assertion failed:`

**Comment by garvankeeley** [comment]
Thanks, fixing now. This will only crash in debug builds. In release the Content Blocker will silently not load.

**Comment by isabelrios** [comment]
I see...

> In release, the Content Blocker will silently not load the strict tracking protection list. So if a user uses the whitelist and strict TP mode, the strict list will not load, and it will behave like basic TP mode.

The problem in release is also due to this issue or it is always that way?

And, well just to doubled checked that tests are running on BB on this branch, both UI and XCUITests are green again :)
