### ISSUE TITLE
Add support for making Firefox the default browser

### ISSUE THREAD

**Issue by Jeehut** [mozilla-mobile/firefox-ios#4829]
I've just read [this article](https://medium.com/spacebrowser/how-to-set-the-default-browser-on-ios-6d8ebc9cc9b) where the developers of [Space Browser](https://www.spacebrowser.io/) found an interesting way how users can actually set their default browser in iOS with a small trick. Basically, the steps required are:

1. Open the Settings app
2. Tap "Screen Time"
3. Tap "Content & Privacy Restrictions"
4. Tap "Allowed Apps"
5. Turn off "Safari"

This way, Safari won't be opened any more when links are clicked in any app starting with `http://` or `https://`. But currently, although I have Firefox installed and would like to use it as my default browser on my iPhone, clicking links won't do anything with this setup.

To make this work, Firefox needs to add `http://` and `https://` as custom URL schemes according to the post. I haven't tried it myself yet, but they report it's working and since it wouldn't hurt to add these custom schemes anyway, I feel it's worth a try.

**Comment by justindarc** [comment]
We'd like to try to do this for Beta only initially.

**Comment by F3000** [comment]
Is this a public beta ?

**Comment by justindarc** [comment]
@F3000 https://www.mozilla.org/en-US/firefox/ios/testflight/

**Comment by F3000** [comment]
Thanks . Do you have free spots at the Moment ?

**Comment by malj** [comment]
Any updates on this? Apparently it's a valid workaround, as demonstrated by [Gherkin browser](https://apps.apple.com/us/app/gherkin-new-default-browser/id1476254336) specifically created to test this feature.[<sup>[1]</sup>](https://community.brave.com/t/default-browser-on-ios/32358/8)

**Comment by mattdutson** [comment]
Would also love an update. An inability to set as the default is the single reason I don't use Firefox on iOS (I assume this is true for many people).

**Comment by Uffje** [comment]
This sounds very interesting, love to hear when/if this gets implemented.

**Comment by athomasmoz** [comment]
Closing ticket. Apple is expected to allow this functionality in iOS 14+, so no need to enable the workaround.
