### ISSUE TITLE
Update bottom toolbar tabbed navigation icons for v17

### ISSUE THREAD

**Issue by csuciu** [mozilla-mobile/firefox-ios#4841]
![Screen_Shot_2019-04-25_at_15 20 01-1](https://user-images.githubusercontent.com/1866605/56735621-9d062580-676e-11e9-9650-5308df6526e7.jpg)

**Comment by garvankeeley** [comment]
@bryanbell I measured the icon and it is the same width as the other icons, so it appears to be as-designed. Do you have any suggestion how to improve the appearance?

**Comment by garvankeeley** [comment]
new icons [icons.zip](https://github.com/mozilla-mobile/firefox-ios/files/3173095/icons.zip)
