### ISSUE TITLE
Copying version to clipboard makes debug menu hard to access

### ISSUE THREAD

**Issue by justindarc** [mozilla-mobile/firefox-ios#4843]
We get a popup when the app version is tapped to notify that we've copied to the clipboard. However, this makes it painful to tap the version 5 times to get to the debug menu.

**Comment by akarataev** [comment]
@justindarc hello,

Maybe it makes sense to create a separate page with debug menu? How it works on iOS:
 
![Untitled](https://user-images.githubusercontent.com/35783149/56808792-018eb680-683b-11e9-8b4a-5e565a4b4bf4.png)

**Comment by justindarc** [comment]
We already have a prefpane in the iOS settings app that includes some debug options, but they serve a different purpose than the in-app settings. We cannot use the iOS Settings app to do the things we do in-app. The solution here I think is to make the "copy version" feature require a long-press instead of a tap.

**Comment by akarataev** [comment]
@justindarc Sorry, I have not accurately formulated my thought. The idea is to make a new table row for debugging page at firefox settings screen. By analogy with the way in the settings of iOS made the transition to your own debugging page.

**Comment by justindarc** [comment]
Ahh ok, I see what you mean now. Yeah, that's another good option. I'd have to run this by our UX people first to see if they'd be ok with the change.

**Comment by farhanpatel** [comment]
The plan is to move the debug menu to enable after 5 taps to the "about" header

**Comment by akarataev** [comment]
I’ll look at this if nobody is against.

**Comment by justindarc** [comment]
@akarataev go for it! Thanks!
