### ISSUE TITLE
FXIOS-67 ⁃ [XCUITests] Refactor existing test for bookmarks appear in awesomebar searches

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/firefox-ios#4846]
There are no tests for covering that as far as I remember. It would be easy to add one test and good to have that check

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2098)

**Comment by kglazko** [comment]
Test already exists in Smoketests, it can be modified for best practices such as having variables for URLs etc.

**Comment by kglazko** [comment]
I may also add a part that makes sure that the star icons are present. Or will just refactor this test overall.

**Comment by isabelrios** [comment]
Let's close this old issue for now and open if needed in the future
