### ISSUE TITLE
iCloud bookmarks possible?

### ISSUE THREAD

**Issue by F3000** [mozilla-mobile/firefox-ios#4862]
Is something like that possible ?: 

https://addons.mozilla.org/de/firefox/addon/icloud-bookmarks/

**Comment by farhanpatel** [comment]
It might be possible to install this on desktop. and then sign into Firefox sync on both your desktop and Firefox iOS to sync those bookmarks back to iOS. 
Unfortunately this is an extension made by Apple and not something we can build ourselves.
