### ISSUE TITLE
FXIOS-69 ⁃ [UI Tests] Bookmarks test suite does not compile

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/firefox-ios#4882]
UITests are not running, there are several error in the Bookmarks that do not allow the compilation: 
`Use of undeclared type 'BookmarkBufferStorage'`
`Use of undeclared type 'BookmarkMirrorItem'`

This is the [file](https://github.com/mozilla-mobile/firefox-ios/blob/master/UITests/BookmarksPanelTests.swift#L25) where the errors appear

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2100)

**Comment by isabelrios** [comment]
@justindarc I guess this is due to the changes around Bookmarks...could you please help me debugging this...not sure how to fix this...Thanks!

**Comment by justindarc** [comment]
@isabelrios I would delete the failing tests that reference `BookmarkBufferStorage` and `BookmarkMirrorItem`. None of that code exists anymore.

**Comment by justindarc** [comment]
Actually, in this particular case, it looks like all that stuff is being used to create a bookmark and insert it into the DB. The new way to do that is:

```
profile.places.createBookmark(parentGUID: BookmarkRoots.MobileFolderGUID, url: "http://example.com", title: "example")
```

**Comment by justindarc** [comment]
You can also create a folder or a separator like this now:

```
profile.places.createFolder(parentGUID: BookmarkRoots.MobileFolderGUID, title: "foo")
```

```
profile.places.createSeparator(parentGUID: BookmarkRoots.MobileFolderGUID)
```

NOTE: all of the above mentioned new APIs also accept an optional `position:` argument in case you want to insert them in a specific order in the folder

**Comment by isabelrios** [comment]
👍 I will try to fix them that way. Thanks for the help here!

**Comment by isabelrios** [comment]
This is unblocked now, the UI test suite is running except for the Bookmark test suite which is disabled until this is done

**Comment by isabelrios** [comment]
Let's close this as UI tests in this test suite are not running. Once it is enabled back, let's open new issues as needed
