### ISSUE TITLE
[XCUITests] Modify tests accessing Bookmark panel according to latest implementation

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/firefox-ios#4884]
Now saved bookmarks are not created directly in the Bookmark panel, instead they are saved into a Mobile Bookmarks folder. 
Tests need to be modified to access correctly to this new folder for doing all the necessary checks.

<img width="263" alt="Screenshot 2019-05-03 at 11 05 18" src="https://user-images.githubusercontent.com/1897507/57128345-62feda00-6d93-11e9-8576-7c2063794bbc.png">
<img width="263" alt="Screenshot 2019-05-03 at 11 05 25" src="https://user-images.githubusercontent.com/1897507/57128349-66926100-6d93-11e9-8698-aac3890eb6b3.png">

This would require changes not only on the Bookmarks test suite but on more test suites. 
Also UI tests will need to be adapted.

**Comment by isabelrios** [comment]
@justindarc asking you just to double check that this is the expected behavior...thanks!

**Comment by justindarc** [comment]
This is the new correct behavior.

**Comment by isabelrios** [comment]
It would be needed to create a new screen in the Graph and an action to go to that screen by tapping on: `app.cells.staticTexts["Mobile Bookmarks"]`

**Comment by isabelrios** [comment]
Closed by #4893
