### ISSUE TITLE
In some languages the Reader List, Bookmarks and Downloads strings are overlapping their icons 

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/firefox-ios#4892]
This is a regression on beta 17.x 15036 it was shown fine before. 
iPhone 6s
Looks like now there is less space for that strings/icons...

Please see screenshot attached.
![IMG-2629](https://user-images.githubusercontent.com/1897507/57155903-eb559d00-6ddc-11e9-9c6f-9fb7c4730455.PNG)

Same device in English
<img width="323" alt="Screenshot 2019-05-03 at 19 52 38" src="https://user-images.githubusercontent.com/1897507/57155969-0de7b600-6ddd-11e9-9fa0-f5410747b769.png">

**Comment by isabelrios** [comment]
It is already P1 but would like to highlight that other languages are also affected, Romanian and French.
See screenshot...
![IMG_2693](https://user-images.githubusercontent.com/1897507/57316654-94123e00-70f6-11e9-96a9-4988dd02e3e6.PNG)

**Comment by garvankeeley** [comment]
It should be much better now
<img width="355" alt="Screen Shot 2019-05-08 at 1 05 49 PM" src="https://user-images.githubusercontent.com/5495083/57393872-13088480-7192-11e9-9b8b-e2892e30412c.png">

**Comment by garvankeeley** [comment]
With the latest fixes, I am not sure how much more we can do to address this.
The label will first shrink to try and fit, and then get ellipsis.

**Comment by garvankeeley** [comment]
They can no longer overlap, so marking this closed.
