### ISSUE TITLE
Choosing search engine for word selections

### ISSUE THREAD

**Issue by anders-burov** [mozilla-mobile/firefox-ios#4896]
When selecting words in Firefox a pop up appears suggesting to ‘Search with Firefox’, this opens a new tab with the words being searched by the default engine. Firefox provides a way to add several search engines, so it’s seems only logical to have an option to choose some other one. The use case can be to search a translation of the word, to lookup the term in the wikipedia, etc.

**Comment by farhanpatel** [comment]
Unfortunately because there are too many menu items adding them all to the popup would make the menu larger than it is possible to display

**Comment by anders-burov** [comment]
@farhanpatel, but it has not have to be on the same menu, rather one selects 'Search with Firefox' and then gets another menu with choices. The whole thing can be also enabled based on a setting flag.
