### ISSUE TITLE
Tab title in Tab Tray is confusing

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/firefox-ios#4900]
Master but also seen in older builds.

Steps
Open new tab and go to Tab Tray

Actual
Tabs title show 'Open New Tab'
<img width="284" alt="Screenshot 2019-05-06 at 13 04 08" src="https://user-images.githubusercontent.com/1897507/57222271-3b617900-7002-11e9-8e81-b67280151fec.png">

Expected
I'm not sure about the expected behavior. Tests are expecting 'Home' and so they are failing now, but checking older builds I can see the same behavior as now so I'm really confused about the expected result.

In any case, IMHO that Open New Tab title does not make much sense...Should it be Home or a different one? or it is just fine as it is :)
We need to know the expected string to fix the automated tests accordingly.

Thanks!

**Comment by garvankeeley** [comment]
Agree this is a poor title choice. cc @bryanbell

**Comment by bryanbell** [comment]
Simply "Home" serves the need.
