### ISSUE TITLE
Keyword search no longer work

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#4911]
Build: 17.0 (15036) 
Device: iPhone 7
iOS: 12.2

Preconditions:
- From Desktop, setup a few keywords search by right clicking on a search field and "Add keyword for this search".

Steps to reproduce:
1. Tap on the URL bar and type one of the keywords added from the preconditions followed by a search term and type "Go".

Actual results: 
- Tapping "Go" will result in search on the default search engine. 

Expected results: 
- Firefox should return all results for the search term, conducted trough the search engine saved by the keyword.

Notes:
- Last good build 17.0 (14949)
- First bad build 17.0 (15013)

**Comment by kewisch** [comment]
Duplicate of #4779 ?

**Comment by SimonBasca** [comment]
Duplicate of #4779
