### ISSUE TITLE
Web development tools (noob)

### ISSUE THREAD

**Issue by ju-dev-fr** [mozilla-mobile/firefox-ios#4917]
Hello,

I really need a great tool for web development (web page source code + css editing, first) on my iPad Pro. The best tool I found is "inspect browser" but it's not perfect. So I would like to make my own tool based on firefox. I'm not an iOS developer and I don't know where to start in the source code...

Could you help me please ?
Does anyone know how to start for a noob ?

• The best file path to create a "module" (and a blank file would be appreciated)
• How to edit the way firefox is rendering the page
• ...

Thank you for your help, I start reading the documentation now :-)

**Comment by farhanpatel** [comment]
The Firefox desktop browser has a WebIDE with a responsive design mode which you can set to mimic an iPad screen size. Unfortunately this is not something we would build in Firefox iOS
