### ISSUE TITLE
[iPad] Firefox crashes when tapping on Clear Recent History

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#4930]
Test testClearRecentHistory() is failing and the issue was also reproduced manually.
Link to test:
- https://github.com/mozilla-mobile/firefox-ios/blob/master/XCUITests/HistoryTests.swift#L238

Build: 17.0 (15036)
Device: iPad Air 2
iOS: 12.1.1

Steps to reproduce:
1. Go to Library -> History
2. Tap on Clear Recent History

Actual results:
- Firefox will crash.

Note:
- Issue is only reproducible on iPad.

**Comment by garvankeeley** [comment]
The wrong popover style is used on iPad, fixing it now...

**Comment by garvankeeley** [comment]
Fixed by https://github.com/mozilla-mobile/firefox-ios/pull/4932
