### ISSUE TITLE
[UI Tests] Tests are broken - the app is launched but closed after one sec

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/firefox-ios#4931]
This issue has been hidden by issue #4882. The build was not compiling and so this error was not shown. 

The last time the tests work is in this commit 4252965fac07d77f440edc4dd9a4506d2aa99816 something has changed after it affecting how the tests are launched. 
I have tried to find the exact commit where tests started to fail but there are a few commits in which I can't build due to the error `No such module 'Deferred'` 
So the first commit in which I see the current behavior is commit cad5ac5485b68b94efa9157cec2505e226191983

All commits are from May 2nd.

@justindarc since this is the beginning of a few commits from you, do you have any idea of what could be the cause of this? Thanks!

**Comment by justindarc** [comment]
I'm gonna need a bit more detail here. Is there a crash report or a log?

**Comment by isabelrios** [comment]
It is really strange, there is no error shown when this happens..I will check if there are any logs generated that could be useful...

**Comment by isabelrios** [comment]
Let's see if there is something useful here: 
[uitestslogs.docx](https://github.com/mozilla-mobile/firefox-ios/files/3158080/uitestslogs.docx)

**Comment by justindarc** [comment]
KIF is missing.

**Comment by justindarc** [comment]
```
2019-05-08 17:23:34.687574+0200 Client[14287:2879178] (dlopen_preflight(/Users/isabelrios/Library/Developer/Xcode/DerivedData/Client-bswgjixueueihjcwrblwnrbihtah/Build/Products/Fennec-iphonesimulator/Client.app/PlugIns/UITests.xctest/UITests): Library not loaded: @rpath/KIF.framework/KIF
  Referenced from: /Users/isabelrios/Library/Developer/Xcode/DerivedData/Client-bswgjixueueihjcwrblwnrbihtah/Build/Products/Fennec-iphonesimulator/Client.app/PlugIns/UITests.xctest/UITests
  Reason: image not found)
```
