### ISSUE TITLE
Loading indicator gets stuck when switching between Library panels

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#4945]
Build: 17.0 (15125)
Device: iPhone 7
iOS: 12.2

Steps to reproduce:
1. Go to Library -> History -> Synced devices
2. Tab on Bookmark panel
3. Tap on History panel 
4. Repeat steps 2) and 3)

Actual results:
- The loading throttle will be stuck. 

[ScreenRecording_05-09-2019 11-30-27.zip](https://github.com/mozilla-mobile/firefox-ios/files/3161051/ScreenRecording_05-09-2019.11-30-27.zip)

**Comment by garvankeeley** [comment]
I think this is specific to Synced Devices panel.

**Comment by sindhugudivada** [comment]
@farhanpatel  is this still available to work on?
