### ISSUE TITLE
[iOS 13]'Open in external app' dialog is not displayed after scanning an email QR code

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#4946]
Build: 17.0 (15125)
Device: iPhone 7
iOS: 12.2

Steps to reproduce: 
1.  Go to http://zxing.appspot.com/generator/ and generate an email QR  code
2.  Open a new tab
3. Tap on the URL bar 
4. Scan the QR code

Actual results:
- The 'Open in external app' dialog is not displayed. After visiting a webpage in the same tab the dialog will be displayed.

**Comment by sindhugudivada** [comment]
@farhanpatel is this available to work on?

**Comment by sindhugudivada** [comment]
@SimonBasca Can I pick this to work on?

**Comment by SimonBasca** [comment]
@sindhugudivada this is no longer reproducible. After scanning a  email QR code the 'Open in external app' dialog is displayed. 

Tested on 17.3 (15323), 18.0 (15456) and latest master f8abb8c35f0

**Comment by SimonBasca** [comment]
This is reproducible on the latest beta 19.0(16028) on devices with iOS beta only (13.1b2).

**Comment by garvankeeley** [comment]
Scan QR code seems broken to me, it is showing the home screen rather than returning to the webview so the code can be scanned.
