### ISSUE TITLE
Add 'Recently Bookmarked' list under root bookmarks folders

### ISSUE THREAD

**Issue by justindarc** [mozilla-mobile/firefox-ios#4965]
Depends on https://github.com/mozilla/application-services/issues/1129

**Comment by bryanbell** [comment]
Mockup https://mozilla.invisionapp.com/share/WGRY3YCMS5J#/362568376_Bookmarks

1[Mockup](https://mozilla.invisionapp.com/static-signed/live-embed/22240415/362568376/4/latest/H1c97S4NAYryYaflE2Z8HwFVI0AvadRfhGMvaSoRKMmSlEzjbTS8VUYcXKR1QiffOXfPypNVzZLHAKM8eCOpN8YAlE/Bookmarks-2x.png)

**Comment by garvankeeley** [comment]
The is ready on the app services side, I can help hook this up if it is available to work on.

**Comment by justindarc** [comment]
@garvankeeley go for it :-)
