### ISSUE TITLE
Update onboarding slides with content aligned with Project Trailhead

### ISSUE THREAD

**Issue by kwillowhawk** [mozilla-mobile/firefox-ios#4966]
New text and logos will be needed for the July release

**Comment by kwillowhawk** [comment]
Per scope meeting held 14 May with EPM:
We will determine with QA/l10n/UX if content/strings/images will be available to integrate into a point release for v17 prior to 28 May for a possible point release to be submitted to the App store for a public release on 4 June (when the Desktop v67.0.5 point release drops).
If not, then we'll target the v18 normal release cadence for alignment.

**Comment by farhanpatel** [comment]
Updated the strings. https://github.com/mozilla-mobile/firefox-ios/commit/10fca338bbb61ffceb7514b23f0064924a77844b

I'll close this bug once we land the new images

**Comment by garvankeeley** [comment]
According to @ryanfeeley the button on the second slide should go to
`https://accounts.firefox.com/?action=email&service=sync`

**Comment by ryanfeeley** [comment]
extra parameters like style=trailhead will be required too, see @stomlinson for details

**Comment by farhanpatel** [comment]
fixed in https://github.com/mozilla-mobile/firefox-ios/commit/eb56bc94141e1c5467cbca8d36517a57feef2d04
