### ISSUE TITLE
Google favicon is displayed in tabs tray after visiting google.com and going back to Home

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#4968]
Build: 17.0 (15191)
Device: iPad Air 2
iOS: 11.4

Preconditions:
- New tab is set to Firefox Home
- Home is set to Firefox Home

Steps to reproduce:
1. Go to google.com
2. Open the hamburger menu 
3. Tap Home button
4. Open tabs tray

Actual results:
- Google favicon is displayed in tabs tray. 

Notes:
- Not a recent regression, reproducible in 16.2.

**Comment by Logomorph** [comment]
This can also be reproduced by opening a new tab with the aforementioned preconditions, navigating to any website and the going back.
