### ISSUE TITLE
Firefox will crash when trying to re-arrange an unloaded tab

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#4971]
Build: 17.0 (15191)
Device: iPad Air 2
iOS: 11.4

Preconditions:
- New tab set to custom URL: "twitter.com"

Steps to reproduce:
1. Open about 13 tabs
2. Go to tabs tray
3. Long press on the last tab and try to move it in the first position

Actual results:
- Firefox will crash when trying to re-arrange an unloaded tab.

[Untitled.mov.zip](https://github.com/mozilla-mobile/firefox-ios/files/3183230/Untitled.mov.zip)

**Comment by garvankeeley** [comment]
I get this exception `objc[97299]: pthread_rwlock_rdlock failed`

```
#1	0x00000001134a8158 in objc_exception_throw ()
#2	0x00000001145b90bc in _CFThrowFormattedException ()
#3	0x000000011461d6e2 in -[__NSDictionaryM setObject:forKeyedSubscript:] ()
#4	0x0000000116e748d1 in -[UICollectionView _updateReorderingTargetPosition:forced:] ()
#5	0x0000000116e7552c in -[UICollectionView updateInteractiveMovementTargetPosition:] ()
#6	0x000000011712ad6a in -[_UICollectionViewDragDestinationController _reorderingDisplayLinkDidTick] ()
#7	0x000000010fcd8850 in CA::Display::DisplayLink::dispatch_items(unsigned long long, unsigned long long, unsigned long long) ()
#8	0x000000010fe1aa12 in display_timer_callback(__CFMachPort*, void*, long, void*) ()

```

**Comment by SimonBasca** [comment]
This is also reproducible when re-arranging unloaded tabs in Top Tabs for iPad.
