### ISSUE TITLE
Sharing login protected pdf not working

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#4995]
Logged via: https://bugzilla.mozilla.org/show_bug.cgi?id=1549337

Steps to reproduce:

Viewing a pdf file on TUM's moodle. (login required)
Trying to share this site to another app or exporting it as a pdf results in a corrupted pdf.

Actual results:

Viewing the document worked as expected.
The exported file is corrupt (not openable by pdf viewers).
Original file size: 150904 bytes
Corrupted file size: 32728 bytes

Expected results:

The document should have been exported correctly.

**Comment by SimonBasca** [comment]
Yes only students are able Go create an account. I found a course, where you can login as a guest and try to download pdfs.
(„Anmelden als Gast“ -> „Ja“)
https://www.moodle.tum.de/course/view.php?id=42050

With Firefox there is the same issue in this course.
With Safari everything works as expected.

**Comment by farhanpatel** [comment]
Can we check this again with the latest master

**Comment by SimonBasca** [comment]
This is fixed in latest master 7352b83c6. I manage successfully shared the login protected PDF via AirDrop. This was not possible in 17.3 (15323).
