### ISSUE TITLE
FxA settings webview has links that aren't clickable

### ISSUE THREAD

**Issue by garvankeeley** [mozilla-mobile/firefox-ios#4998]
The link *these authentication apps* in this description is not clickable:
<img width="327" alt="image" src="https://user-images.githubusercontent.com/5495083/57932134-32856880-7888-11e9-927e-b93e918fb673.png">

There are more on this page, such as in Account recovery.

**Comment by garvankeeley** [comment]
We should handle these in the delegate for this FxA webview, triggering the settings to close, and open a new tab in the browser with the link.

**Comment by garvankeeley** [comment]
@vbudhram can you take a look at this?

**Comment by dnarcese** [comment]
Fixed in #5639
