### ISSUE TITLE
New tab - Bookmarks list

### ISSUE THREAD

**Issue by Phil57** [mozilla-mobile/firefox-ios#5003]
With the update to have sync between desktop and mobile for bookmarks, it is not possible to have a view of the bookmarks when opening a new tab as before.

We can only choose between "Top sites" and "Blank page/Custom URL".
I find the the bookmarks view useful on a mobile device when opening a tab, can it be added back as an option ?

**Comment by foss-** [comment]
I do see bookmarks as option under "Your Library" as first option followed by History, Reading List and Downloads when opening a new tab. In Settings I see "Firefox Home" "Blank Page" and "Custom URL" as options. Not sure about this issue. @Phil57 could you send a screenshot of what you are seeing?

**Comment by Phil57** [comment]
@foss- I have that too in the Library.
But when opening a new tab you have to

- open a tab
- open the library
- go to the bookmarks
- click on the bookmark of your choice

Before when opening a tab, you had the bookmarks list directly in the tab without the need for the extra clics. This should be added back as an option in addition to the existing top list, blank or custom URL.

It's not a huge deal but I find it practical on a mobile device.

**Comment by justindarc** [comment]
This is not possible to support any more due to the restructuring of the views in order to prepare for full-featured bookmark management coming in v18. We are also going to be adding a "Recently Bookmarked" list to the Library panel.

**Comment by foss-** [comment]
That's awesome to hear that Mozilla is working on improved bookmark management. It is something that users expect from a browser. I wonder if there are plans for Firefox to clean up the overall bookmark structure? https://bugzilla.mozilla.org/show_bug.cgi?id=1552843

**Comment by anders-burov** [comment]
@justindarc 
As mentioned here https://github.com/mozilla-mobile/firefox-ios/issues/1390#issuecomment-249703420 previously one could have used this feature to quickly access bookmarklets the same way it is done in safari. For example to open a video in a full screen (not possible by default on youtube) or skip an ad. Do you consider supporting this workflow in v18? It has been a very useful shortcut for at least some customizability of a mobile firefox.

**Comment by nathandines** [comment]
@justindarc Just wanted to add my voice to this issue. This was really nice, as it provided me with a really focused entrypoint to the sites which I regularly visit.

I see [here](https://github.com/mozilla-mobile/firefox-ios/issues/5003#issuecomment-494465418) that you've said that the views won't support this feature anymore, but an alternative might be if Firefox introduced something like a `bookmarks://` URL scheme. Users could potentially then specify `bookmarks://Mobile Bookmarks/` as a custom URL if they wanted. I'm not sure if it's a feasible capability for the browser, but I think it could be a decent middle-ground.
