### ISSUE TITLE
Add support for custom URL schemes when typed into the URL bar

### ISSUE THREAD

**Issue by andreiburov** [mozilla-mobile/firefox-ios#5004]
A lot of apps on iOS define their own custom URL Schemes https://developer.apple.com/documentation/uikit/core_app/allowing_apps_and_websites_to_link_to_your_content/defining_a_custom_url_scheme_for_your_app.

To run the specified app its URL can be provided in Safari, for example after typing shortcuts:// a shortcut app will be opened. In Firefox it leads to a search in the specified search engine.

Could you please add support to the custom URL Schemes to match the behavior of Safari?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2113)

**Comment by lmarceau** [comment]
Since only `data-sync-user` has commented on the issue after the `Stalebot` GitHub action (which triggered the removal of the `stale` label) I’ll close this issue for now. Please let us know if you think this issue needs to be reopened, we'll gladly do so. Thank you!
