### ISSUE TITLE
FXIOS-85 ⁃ Tab Overview: Scrolling and rubberbanding lags/hangs and is not fluid

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#5011]
Logged via: https://bugzilla.mozilla.org/show_bug.cgi?id=1552656

Firefox 17 for iOS (iPhone)

STR:

1.) Switch to Tab Overview
2.) Scroll up/down

Actual: Scrolling and rubberbanding lags/hangs and is not fluid.

Expected: Fluid scrolling and Rubberbanding.

A screencast is attached.
https://bug1552656.bmoattachments.org/attachment.cgi?id=9065878

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2114)

**Comment by lmarceau** [comment]
UI has changed and I believe this doesn't apply anymore 🧹. Let me know if this shouldn't be closed
