### ISSUE TITLE
 QR Code scanner in Firefox for iOS sends data to default search provider

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#5012]
Logged via:
https://bugzilla.mozilla.org/show_bug.cgi?id=1552807

Steps to reproduce:

1. Generate QR code on https://qifi.org/ with SSID + WPA-Key
2. Scan QR code in FF
3. Payload of QR code goes to default search provider

Actual results:

Credentials are sent to a 3rd party - I guess FF should just open the URL, if any, is in the QR payload and otherwise ignore it.

Expected results:

Ignore unload payload or issue a warning but don't send it to 3rd parties by default.

**Comment by justindarc** [comment]
A QR code can either contain text or a URL. In this case, the QR code contains text with the specified WiFi info. When scanning a QR code into Firefox for iOS, there's nothing else we can do with the contents of the QR code besides open the URL or search for the text.

**Comment by eimann** [comment]
Well, you either ignore text and only react on URLs or at least try to be a bit privacy-aware in this case and ignore known embedded credentials :)

**Comment by justindarc** [comment]
And do what with it? It seems to me that the use case for embedding wifi credentials into a QR code is to share them publicly, no? I guess I don't understand what the concern is if the contents go to your default search provider. Also, if you know that the QR code has wifi credentials, why would you scan it into your mobile browser?

**Comment by eimann** [comment]
Maybe it helps to explain the background:
- User went ahead and scanned the QR code at location which is not publicly reachable
- User complained about Google opening (default search provider)
- Helpdesk was puzzled by this kind of error report
- Further research revealed that user remembered "my browser is showing an icon which looks like a QR code", which made them use Firefox to scan the QR code
- Helpdesk was concerned that using Firefox will transmit network credentials to a 3rd party (I will assume here that it was only transmitted to the default search provider, not to Telemetry) and reported it to corporate security
- Helpdesk modified QR code with a hint to use the OS-provided camera application and not 3rd party applications to scan the QR code

Whilst this is arguably also a UI/UX issue, it can be programmatically solved by detecting certain QR code payloads and display a warning/hint to the user that this is not supported or will be transmitted to a 3rd party.

**Comment by justindarc** [comment]
Chrome for iOS does basically the same thing though except that it stops short of submitting the search request (it simply places the encoded string into the address bar). This is the least-used feature in the app and so I'm not inclined to special case this. I could perhaps get on board with doing what Chrome for iOS does (put the text in the address bar but not submit the search automatically). It still doesn't seem like that is a great UX though either. The only way these types of QR codes can possibly work at all on iOS is if the user opens the iOS Camera app and points at the QR code. The only reason we put this feature in the app is to specifically let users scan QR codes that contain legitimate URLs. The behavior to search with the default search engine when the QR code contains anything else is just a best attempt at a graceful fallback.
