### ISSUE TITLE
3D Touch on Firefox for iOS?

### ISSUE THREAD

**Issue by Victorio115** [mozilla-mobile/firefox-ios#5020]
I have said that on [a post](https://www.reddit.com/r/firefox/comments/bsa1yf/3d_touch_on_firefox_for_ios/) on [r/Firefox](https://www.reddit.com/r/firefox/) but [someone told me that I have to say it here](https://www.reddit.com/r/firefox/comments/bsa1yf/3d_touch_on_firefox_for_ios/eokjaa0/)...  
  
3D Touch is an accessibility function that is available on some iPhone models, which consists of touching and, applying a little bit of pressure on the screen, on a picture, a link, or another kind of element to have a quick preview.  
  
![3d Touch](https://user-images.githubusercontent.com/50971728/58294862-25cdac80-7d81-11e9-9e91-bf7b50dab6b5.GIF)  
3D Touch  
  
That function seems doesn't work on Firefox for iOS.  
  
![3d Touch isn't present on Fireox iOS](https://user-images.githubusercontent.com/50971728/58294923-747b4680-7d81-11e9-9721-fea91209d428.GIF)
Trying to use 3D Touch on Firefox for iOS.
  
Do you have plans of adding that feature in a future update?, I hope yes.  
  
Those GIF's are screen recordings that I upload previously on [that Reddit Post](https://www.reddit.com/r/firefox/comments/bsa1yf/3d_touch_on_firefox_for_ios/), converted to GIF's, by the way.

**Comment by justindarc** [comment]
We anticipate Apple will be deprecating/ending support for 3D touch in future devices, so this is not something we plan on implementing.
