### ISSUE TITLE
[XCUITests] - Desktop mode tests remove old commented tests under Navigation Test Suite

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/firefox-ios#5021]
There have been new tests added: DesktoMode tests \o/ thanks @garvankeeley!

They are working fine on iPhone sim but not on iPad sim. When the page loads it shows Desktop_UA instead of Mobile_UA, I guess that's fine, could you please confirm @garvankeeley ?. We would need to modify the tests for the iPad case with conditionals.

Also, all tests are enabled now in the Smoketest suite, we need to identify the one that better suits with the smoke test defined in Test Rail [https://testrail.stage.mozaws.net/index.php?/cases/view/10965&group_by=cases:section_id&group_order=asc&group_id=1118](url) and keep only that enabled in the Smoketest suite and disabled from the general one.

Lastly, in the past we had these tests running as part of the [Navigation test](https://github.com/mozilla-mobile/firefox-ios/blob/master/XCUITests/NavigationTest.swift) suite, but got disabled due to their instability as they were relying on real websites and the app was not behaving consistently. We would need to finally remove them since these test will be replaced by the new ones.

**Comment by garvankeeley** [comment]
It should be the same UA on ipad, so that test might be catching a bug. I’ll take a look.

**Comment by isabelrios** [comment]
There has been some work to fix part of this issue. 

These tests are running only on iPhone sim, so no need to fix them for iPad. They are going to be disabled from Smoketest once PR #5079 lands. So the only pending work would be the last part:
```
Lastly, in the past we had these tests running as part of the Navigation test suite, but got disabled due to their instability as they were relying on real websites and the app was not behaving consistently. We would need to finally remove them since these test will be replaced by the new ones.
```

**Comment by SimonBasca** [comment]
@isabelrios the only thing needed here would be to clean-up the NavigationTest suite or remove it?

**Comment by isabelrios** [comment]
@SimonBasca yes, in the past we had the desktop mode tests in the Navigation test suite. They are disabled now. With the new DesktopMode test suite, I think those can be finally removed from there.

**Comment by isabelrios** [comment]
@SimonBasca there is one more fix to do regarding these desktop mode tests...there is a [new test](https://github.com/mozilla-mobile/firefox-ios/blob/master/XCUITests/DesktopModeTests.swift#L7) crashing on iPad due to a [missing line](https://github.com/mozilla-mobile/firefox-ios/blob/master/XCUITests/DesktopModeTests.swift#L25) since these tests are running only on iPhone sim. If you want to do the fix in the same PR, that would be great, thanks!

**Comment by garvankeeley** [comment]
That test is intended to be on iPhone and iPad, I'll do a PR to update it.
