### ISSUE TITLE
"Clear text" is not selectable. It overlaps with the Page Action button when the URL bar is in focus

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#5022]
"Clear text" is not selectable . It overlaps with the Page Action button when the URL bar is in focus. When the button is selected (see screenshot) VoiceOver reads "Page Action button".

![IMG_681FA3277E34-1](https://user-images.githubusercontent.com/32130829/58324222-efe70180-7e2e-11e9-828e-3db2b258aa61.jpeg)

**Comment by garvankeeley** [comment]
Fixed by #5057
