### ISSUE TITLE
[Regression] Tapping sites in library panels does not dismiss Library

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/firefox-ios#5027]
This is happening on latest master ed4ac1b. 

1. Selection Reader View option shows `Network connection lost` error (this is not 100% repro).
 - Steps
Open www.mozilla.org
Tap on Reader View option

- Actual
The error below is shown
![Screenshot 2019-05-27 at 13 32 37](https://user-images.githubusercontent.com/1897507/58417068-f7531880-8083-11e9-86ec-ea394e6e1019.png)

- Expected 
The Reading List menu is open

2. Clicking on an item in the Reading List view does not launch it
- Steps
Go to Reading list, having at least one item there
Click on it

- Actual
The website is loaded behind the Reader List panel

- Expected
The Reading List panel menu is closed and the website is open in foreground (at least this is the previous behavior)

3. iPad: the menu is not updated until you go to a different Panel. The menu is always shown, so that seems to be the issue. Please see video: https://youtu.be/WS7wskU2lP4

**Comment by isabelrios** [comment]
As discussed during triage, new issue #5049 open for the first issue in the list. This issue will track the other two issues:

2.  Clicking on an item in the Reading List view does not launch it

    Steps
    Go to Reading list, having at least one item there
    Click on it

    Actual
    The website is loaded behind the Reader List panel

    Expected
    The Reading List panel menu is closed and the website is open in foreground (at least this is the previous behavior)

3.    iPad: the menu is not updated until you go to a different Panel. The menu is always shown, so that seems to be the issue. Please see video: https://youtu.be/WS7wskU2lP4

**Comment by SimonBasca** [comment]
I was unable tor reproduce this issue. Also trie to simulate a slow internet connection and Reader mode still works.

**Comment by isabelrios** [comment]
There was a misunderstanding here, this issue should be kept open since scenarios 2 and 3 are still open. For the first scenario, not reproducible, there is a different issue open

**Comment by justindarc** [comment]
Renaming this to deal with the 2nd issue reported above. I'll move the 3rd issue (Reading List not auto-refreshing) to a new issue.
