### ISSUE TITLE
[dynamic fonts, tableview cells] headings in Firefox Settings don't respect Larger Text iOS accessibility setting

### ISSUE THREAD

**Issue by asadotzler** [mozilla-mobile/firefox-ios#5032]
If you set Larger Text in iOS's Accessibility settings and load the Firefox Settings panel, you'll see that the settings are all large text but the settings headers remain small.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2116)

**Comment by data-sync-user** [comment]
➤ Asa Dotzler commented:

This is an accessibility S2
