### ISSUE TITLE
Misleading link in release notes pointing Web developers to Gecko version 16 Release Notes

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#5035]
Logged via: https://bugzilla.mozilla.org/show_bug.cgi?id=1553566

User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0

Steps to reproduce:

1) Enter https://www.mozilla.org/en-US/firefox/ios/16.0/releasenotes/
2) Click "Developer Information" at right bottom of page

Actual results:

It leads to https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/16 which is the ordinary (Gecko) Firefox 16's (October 2012) release notes for developers.

Expected results:

Considering the fact that iOS Firefox uses "Webkit engine", it can point to current version of Webkit release notes or a KB article explaining this fact.

**Comment by SimonBasca** [comment]
We have some more reports of misleading or missing release notes logged via: https://bugzilla.mozilla.org/show_bug.cgi?id=1578744. 

Steps to reproduce:

Went to the following URLs :

https://www.mozilla.org/en-US/firefox/ios/16.0/system-requirements/
https://www.mozilla.org/en-US/firefox/ios/16.0/releasenotes/
https://www.mozilla.org/en-US/firefox/ios/18.2/system-requirements/
https://www.mozilla.org/en-US/firefox/ios/18.2/releasenotes/

Actual results:

... and, only the ones, for iOS v16.0, were there -- I got the equivalent, of a "404"-error .

Expected results:

... please provide, for iOS v18.2 !

**Comment by farhanpatel** [comment]
@athomasmoz

**Comment by athomasmoz** [comment]
Closing. It's been moved to the mozilla.org:: release notes project in bugzilla https://bugzilla.mozilla.org/show_bug.cgi?id=1553566
