### ISSUE TITLE
Empty history layaout does not appear when removing Recent history

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/firefox-ios#5040]
Seen on latest master
-Have some history
-Go to history panel and click on Clear Recent history, last hour

Actual
Please see screenshot attached
![IMG_2921](https://user-images.githubusercontent.com/1897507/58493276-db7a7000-8172-11e9-8dc3-c5ad5d0ed101.PNG)

Expected
The empty history layout should be shown

**Comment by flbaue** [comment]
Hi, I created a pull request to fix this issue. Please have a look.
