### ISSUE TITLE
Password Auth Http and password for web form 

### ISSUE THREAD

**Issue by nicoonline** [mozilla-mobile/firefox-ios#5043]
Hey there! 

Issue related to saved password
iOS Firefox doesn’t make the difference between password used for http Auth and web forms.

Accessing a webpage with two authentification : 
- http Auth 
- classic login password on a webpage 

mixes up the login/password.

**Comment by justindarc** [comment]
@nicoonline can you please provide a sample URL where this behavior happens?

**Comment by nicoonline** [comment]
Difficult to provide URL's as  this is on our internal server.

This the http auth login.

![image](https://user-images.githubusercontent.com/2115195/58897425-92896500-86f8-11e9-80ae-e8b4a18b274b.png)

on IOS the correct username is replaced with the login used on the next web-form
![image](https://user-images.githubusercontent.com/2115195/58897512-c2386d00-86f8-11e9-9939-0ea1bc70ac64.png)

**Comment by nicoonline** [comment]
if you want to test it, i need to provide a test environment :)

**Comment by mnoorenberghe** [comment]
You can test with https://httpbin.org/basic-auth/user/passwd (replace `user` and `passwd` with other values if you want).

This is supported on Firefox Desktop. HTTP auth passwords should have a `null` `formSubmitURL` and the `httpRealm` should contain the realm string as described in [RFC2617](https://www.ietf.org/rfc/rfc2617.txt) and in the [`nsILoginInfo` API docs](https://searchfox.org/mozilla-central/rev/9eb2f739c165b4e294929f7b99fbb4d90f8a396b/toolkit/components/passwordmgr/nsILoginInfo.idl#22-45).

When querying for logins you should look for ones with a `null` `formSubmitURL` when filling an HTTP auth prompt whereas you need a `null` `httpRealm` when trying to fill a password field in a webpage.

**Comment by justindarc** [comment]
Thanks for the info @mnoorenberghe !

**Comment by nicoonline** [comment]
Any updates ?

**Comment by nicoonline** [comment]
Still nok on 18.1
Can you reopen ?

**Comment by nicoonline** [comment]
when i need to have the http_auth login , i got the webform login.
