### ISSUE TITLE
Search tabs confused with URL bar search (i.e. awesome bar search)

### ISSUE THREAD

**Issue by garvankeeley** [mozilla-mobile/firefox-ios#5052]
The search tabs is too prominent and matches muscle memory for search bar. Search tabs would be used very little, yet is presented like a common use item.
We should only reveal search tabs on a pull down action on the tabs tray..

**Comment by garvankeeley** [comment]
Or maybe we should remove it, and regular search shows matches in current tabs.

**Comment by athomasmoz** [comment]
@bryanbell are you actively looking into this? I'm wondering if it should be in progress or moved to the backlog?

**Comment by athomasmoz** [comment]
Closing this & linking from #5661, as it will be covered in that ticket
