### ISSUE TITLE
[XCUITests] Recent bookmark list -PR #5064- needs a test 

### ISSUE THREAD

**Issue by garvankeeley** [mozilla-mobile/firefox-ios#5065]
See #5064. 

This is what it looks like
<img width="377" alt="image" src="https://user-images.githubusercontent.com/5495083/58639913-fd383c00-82c5-11e9-90ff-44f12e0219e7.png">

**Comment by isabelrios** [comment]
Yeah, just opened issue #5062 for that ;) Closing this as dup
