### ISSUE TITLE
Wire up Sentry logging to Rust logger

### ISSUE THREAD

**Issue by justindarc** [mozilla-mobile/firefox-ios#5070]
Self-explanatory. Probably need to limit it to only warnings/errors.

**Comment by sindhugudivada** [comment]
@justindarc is this still available for some one to grab and work on. I 'm interested?

**Comment by justindarc** [comment]
@sindhugudivada I would prefer if you picked from one of the issues marked "Contributor OK":
https://github.com/mozilla-mobile/firefox-ios/issues?q=is%3Aopen+is%3Aissue+label%3A%22Contributor+OK+%F0%9F%A4%9D%22

The reason being, there is more detail involved in this work that is unfortunately not yet documented in this issue.

**Comment by sindhugudivada** [comment]
There are some Contributor OK and Open bugs. But most of them have pull requests for them and not reproducible.

**Comment by justindarc** [comment]
@sindhugudivada please take another look at this list again. Anything marked P1 or P2 is higher priority and should most definitely be reproducible:

https://github.com/mozilla-mobile/firefox-ios/issues?q=is%3Aopen+is%3Aissue+label%3A%22Contributor+OK+%F0%9F%A4%9D%22

Example: https://github.com/mozilla-mobile/firefox-ios/issues/5104
