### ISSUE TITLE
Startup icon gets cropped while phone/skype call is running in background

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#5072]
# Environment:

  * iPhone 7
  * iOS 12.2

# Steps to reproduce:

  1. shutdown Firefox for iOS
  2. call with Skype
  3. back to home screen
  4. run Firefox for iOS

# Actual result

Startup screen is shown, but the middle of the Firefox icon gets cropped
Attached screenshot shows the difference between usual startup screen (left) and affected case (right)

# Expected result

Startup screen is shown and the full Firefox icon is shown

# Other info

This issue doesn't happen on iPhone XS + iOS 12.2.
The difference I see is that, indicator for phone call (at the top of the screen) is shown differently between iPhone 7 (that doesn't have notch) and iPhone XS (that has notch).

![image](https://user-images.githubusercontent.com/32130829/58689905-f7f3f380-8390-11e9-9704-03de245d5575.png)

**Comment by SimonBasca** [comment]
I seen other apps like, Testflight who have the same behavior but also, other apps like Lockwise, Chrome who stretch to the top on the splash screen.

**Comment by justindarc** [comment]
To address this issue, the splash screen should not show the top status bar (to follow what apps like Lockwise and Chrome are doing).
