### ISSUE TITLE
On iOS, new firefox icon gets incorrect orange background

### ISSUE THREAD

**Issue by dianehuang11** [mozilla-mobile/firefox-ios#5090]
STEPS TO REPRODUCE
1. Open Firefox Browser on iOS
2. New tab/Top sites will have Firefox icon

EXPECTED RESULTS
* Clear background with new logo

ACTUAL RESULTS

![IMG_0074](https://user-images.githubusercontent.com/28498717/58985148-b310f800-87a8-11e9-8710-ce3beb391b3f.jpg)

**Comment by dnarcese** [comment]
This was fixed in https://github.com/mozilla-mobile/firefox-ios/commit/7942981ad1f2100d8a6bfbb62ad77184e7e3fe06
