### ISSUE TITLE
Add delete of Recent Bookmarks

### ISSUE THREAD

**Issue by garvankeeley** [mozilla-mobile/firefox-ios#5094]
Currently these aren't editable. An edit button would be nice at the root level.

**Comment by sindhugudivada** [comment]
@garvankeeley  is this available to work on ?

**Comment by garvankeeley** [comment]
Oops I should assign this to myself to make it clearer I am taking it. 

There is a Label called 'Contributor Ok' that has good bugs to pick from:
https://github.com/mozilla-mobile/firefox-ios/issues?q=is%3Aissue+is%3Aopen+label%3A%22Contributor+OK+%F0%9F%A4%9D%22

**Comment by garvankeeley** [comment]
Fixed by https://github.com/mozilla-mobile/firefox-ios/pull/5121
