### ISSUE TITLE
[fxa sign in] Change links to FxA login form to email first form

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla-mobile/firefox-ios#5096]
The FxA email first form (action=email&style=trailhead) will have the ecosystem promo at the bottom, but the login form will not. We would like to replace links to signin with /action=email

**Comment by ryanfeeley** [comment]
See iOS: https://github.com/mozilla-mobile/fenix/issues/3232

**Comment by garvankeeley** [comment]
The long scrollable page is a tad unattractive
<img width="321" alt="image" src="https://user-images.githubusercontent.com/5495083/59372401-6c298200-8d15-11e9-8851-0b4ef34daef6.png">

**Comment by garvankeeley** [comment]
Without trailhead style:

<img width="323" alt="image" src="https://user-images.githubusercontent.com/5495083/59372440-83686f80-8d15-11e9-936a-a6adf44e1dc7.png">

**Comment by ryanfeeley** [comment]
It's being tightened up a bit by @dannycoates. I would follow Google's lead and just show the icons, but they have no equity at this point.

**Comment by garvankeeley** [comment]
Should we do the first iteration of this patch as non-trailhead style?
We can update to use the trailhead style, when it is ready.

**Comment by ryanfeeley** [comment]
It will be ready within days, confirm with Danny.

**Comment by ryanfeeley** [comment]
See: https://github.com/mozilla/fxa/pull/1568

**Comment by garvankeeley** [comment]
mozilla/fxa#1568 appears to be landed, this scrolling page style is as-intended
