### ISSUE TITLE
"Add bookmarks" do not work if they are not added with full "https://" or "http://" URL

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#5099]
Build: 7a4a8b0d6
Device: iPhone Xr 
iOS: 12.2

Steps to reproduce:
1. Go to Library -> Bookmarks -> Mobile Bookmarks
2. Tap "Edit"
3. Tap "+" button
4. Tap "New Bookmark"
5. Type the title
6. In the URL field type "google.com"
7. Tap "Save"

Actual results:
- The bookmark is not saved. When typing in the URL filed "https://google.com", the Bookmark is correctly added.

**Comment by quangDecember** [comment]
Seems like a MozillaAppServices error
debugging result
```
PlacesError
  ▿ urlParseError : 1 element
    - message : "Error parsing URL: relative URL without a base"
```
