### ISSUE TITLE
Remove Find In Page from menu when viewing a PDF

### ISSUE THREAD

**Issue by tbenst** [mozilla-mobile/firefox-ios#5104]
To reproduce:
   - Open a pdf on iOS Firefox
   - Search for a word that appears
   - Open same pdf in safari
   - Search for same word
   -  See word get highlighted

**Comment by farhanpatel** [comment]
unfortunately we do not have the ability to support this feature. We'll remove the option from the menu.

**Comment by sindhugudivada** [comment]
@farhanpatel  is this open to take? Is there an "INPROGRESS" status that I can set to as soon as I start coding?

**Comment by sindhugudivada** [comment]
@farhanpatel while I m working on removing the menu, let me ask you this. You mentioned that "Find in page" feature can't be supported.  Is there any limitation. Or am I missing something? I thought that it could be supported just like it's done in Desktop app. I like to understand , learn and help out if it's okay.

**Comment by tbenst** [comment]
@farhanpatel can I turn this into a feature request then? Perhaps the architecture of the code makes this difficult but I have a hard time believing that it's impossible--standard functionality on Safari and Chrome for iOS, and every desktop browser I've tried.

**Comment by farhanpatel** [comment]
I could not get this to work on Chrome iOS either. Are you sure it worked for you?
I understand that this is frustrating and you're right this is pretty basic functionality. But unfortunately Apple doesn't provide the low level access for us to build this feature. I think this is the same issue in Chrome iOS as well where the feature appears greyed out when trying to access find in page on a PDF

**Comment by tbenst** [comment]
@farhanpatel my apologies you’re right, doesn’t work on chrome either nor Opera nor Edge on iOS. Wow I’m sorry to hear Apple doesn’t permit this, how ridiculous and anti-competitive.

**Comment by sindhugudivada** [comment]
@farhanpatel When I tried to set-up dev environment, I 'm running into issues. I have XCodeToolchain: Swift 5.0 Snapshot 2018-12-09 (a) set up as well. I still keep getting that SWIFT_VERSION_5 is not set-up etc. Do you recommend me raising an issue, so that others can see and give me feedback?
