### ISSUE TITLE
Downloads placeholder too high on iPhone SE

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla-mobile/firefox-ios#5111]
Tiny phone, yes, but this graphic should be lower than it is.
![IMG_0087](https://user-images.githubusercontent.com/68213/59202264-19f82d80-8b6a-11e9-9b9a-a92ee8804022.PNG)

**Comment by garvankeeley** [comment]
Can't repro on master, closing
<img width="321" alt="image" src="https://user-images.githubusercontent.com/5495083/59371490-279ce700-8d13-11e9-8271-c2a054e4fe19.png">
