### ISSUE TITLE
[META] iOS 13: Connect our dark theme to the new system dark theme

### ISSUE THREAD

**Issue by F3000** [mozilla-mobile/firefox-ios#5122]
**Vision:**
As an iOS user, I want Firefox's theme to be dark or light depending on what my system setting is, so that I can control the theme across apps in one place

**Summary:**
This story is to add the option for users to have dark/light theme match the system setting. Details in [PRD](https://docs.google.com/document/d/1ZB7JX4GkI6RoNE0OxKMsSeWRJuwdjr4eqehuT1jfjxc/edit#)

**Success Metrics:**
Increased dark theme usages due to easier discoverability of the feature

**Stories:**
* #5566 
* #5567
* #5568
* #5569
* #5570
* #5571
* #5621 
* #5622

**Comment by farhanpatel** [comment]
I think it makes sense to remove our automatic brightness setting and use the system notifications for dark theme

**Comment by bryanbell** [comment]
Mockup of Changes needed:
https://mozilla.invisionapp.com/share/UPU3KD1SBDX
