### ISSUE TITLE
Pocket 'Trending' icon is black in dark theme

### ISSUE THREAD

**Issue by justindarc** [mozilla-mobile/firefox-ios#5123]
![image (1)](https://user-images.githubusercontent.com/207595/59311184-9aa45000-8c76-11e9-80b3-ef9d0689a7a9.png)

**Comment by sindhugudivada** [comment]
@justindarc is there a different color  icon available in the source code already?  I like to help on this issue.

**Comment by justindarc** [comment]
@sindhugudivada we have an extension method on `UIImage` called `tinted(withColor: UIColor)` that we use to alter the colors of our icons. However, I don't know what color this needs to be yet as this issue requires input from UX first.

**Comment by sindhugudivada** [comment]
@justindarc Is there an UX team that gives input. Or we can put different colors, and put the screenshots here and then we can make a call?

**Comment by justindarc** [comment]
@sindhugudivada we have UX people. I'll get input on it.

**Comment by sindhugudivada** [comment]
@justindarc When I tried to set-up dev environment, I 'm running into issues.  I have XCodeToolchain: Swift 5.0 Snapshot 2018-12-09 (a) set up as well.  I still keep getting that SWIFT_VERSION_5 is not set-up etc. Do you recommend me raising an issue, so that others can see and give me feedback?

**Comment by SimonBasca** [comment]
Verifying as fix on 18.0(15680)
