### ISSUE TITLE
The sync account seems isolated from that of my macbook version of firefox

### ISSUE THREAD

**Issue by yzhanginwa** [mozilla-mobile/firefox-ios#5124]
I downloaded macbook version of firefox first. Then I created sync account in it. The sync works fine.

Then I installed ios Firefox on my iphone 8plus. After It's installed I tried to sync with the same email account. But ios firefox prompted that the account does not exist I need to register. So I did so with the same email account. The syncing on ios looks fine.

But the sync between my macbook firefox and ios firefox does work. It seems the 2 sync account with the same email are not related with each other. 

This problem happened about 2 weeks ago and I've tried different ways but all failed.

Anyone has any insight on this issue?  

Thanks 
Ethan

**Comment by justindarc** [comment]
@yzhanginwa two things I can think of that might be the issue:
- On Desktop, go to `about:config` and check the value of `identity.fxaccounts.autoconfig.uri`. If you have a value in this preference, please report back with it here (this allows Desktop to change the Sync server)
- On iOS, the app *should* be pointed at the main production Sync server. However, for Chinese locales, we point to a different server in China

I can't think of any other configuration change that would cause the two to point at different servers, but please report back here if either of those apply to you. Thanks!

**Comment by justindarc** [comment]
@yzhanginwa do either of those two apply to you?

**Comment by yzhanginwa** [comment]
Hi justindarc

Thanks very much for your reply!

On my Macbook version of firefox, the value for  identity.fxaccounts.autoconfig.uri is blank. 
On my iPhone version of firefox, the about:config showed nothing.

**Comment by yzhanginwa** [comment]
IMO, the sync servers should have the common knowledge about the sync accounts/emails. The email should be an unique key across all the sync servers.

**Comment by farhanpatel** [comment]
We could expose the sync URIs in the Debug menus. This would make it clearer to people where exactly they are syncing to

**Comment by yzhanginwa** [comment]
@farhanpatel 

Thanks for your response! That could definitely help. 

For now what can I do to sync between my iphone and macbook?

**Comment by yzhanginwa** [comment]
@justindarc Now what can I exactly do to sync?

**Comment by justindarc** [comment]
@yzhanginwa it is hard to say what the problem is. If you want, you can try creating a new FxA account and sign into it on both devices. If that doesn't work, I'm not sure what is happening.

**Comment by yzhanginwa** [comment]
What is the sync server of the  iphone firefox? I could try to set  the same server in my macbook firefox "identity.fxaccounts.autoconfig.uri".

**Comment by justindarc** [comment]
@yzhanginwa the "autoconfig" for both desktop and iOS is `https://accounts.firefox.com`. If that pref is blank, then it should already be pointed at it.

**Comment by yzhanginwa** [comment]
Thanks  @justindarc !   How do I explicitly set up  the sync url on my iPhone firefox?

**Comment by justindarc** [comment]
Unfortunately, I think you may need to wait for v18.0 to be released which should be VERY soon. But, once you have v18.0, here are the direction to access the hidden pref:

1. Sign out of your FxA account
2. Go into the settings menu and tap the "Version 18.0" under "About" 5 times (or until you see all the new debug options appear)
3. Scroll back to the top under "Firefox Account" and tap "Advanced Sync Settings"
4. Enter `https://accounts.firefox.com` in the "Custom Autoconfig URI" field, then turn on the "Use Custom Autoconfig" switch

![Screen Shot 2019-07-02 at 10 22 36 AM](https://user-images.githubusercontent.com/207595/60520464-71924080-9cb3-11e9-8613-d008cf75c912.png)
![Screen Shot 2019-07-02 at 10 22 41 AM](https://user-images.githubusercontent.com/207595/60520466-71924080-9cb3-11e9-87d9-e7261d676abf.png)
![Screen Shot 2019-07-02 at 10 23 01 AM](https://user-images.githubusercontent.com/207595/60520467-71924080-9cb3-11e9-9072-6f32dfbc63de.png)

**Comment by yzhanginwa** [comment]
Thank you so much @justindarc !

**Comment by yzhanginwa** [comment]
Just updated the iPhone version of firefox. It's v18.1 already. Followed your instruction  and it worked like a charm.  Thanks a lot!
