### ISSUE TITLE
[iPad] Tab not scrolled into view after changing device orientation in tabs tray and opening a new tab

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#5127]
Build: 18.0 ()
Device: iPad Air 2
iOS: 11.4

Steps to reproduce:
1. Open ~ 10 tabs on iPad in landscape
2. Open Tabs Tray
3. Change device orientation to portrait
4. Open a New Tab 

Actual results:
- The focused tab will not be scrolled into view.

**Comment by flbaue** [comment]
Hi, I created a pull request to fix this bug: https://github.com/mozilla-mobile/firefox-ios/pull/5186
