### ISSUE TITLE
There is no context menu shown when long pressing on Recent Bookmark

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/firefox-ios#5129]
Seen on master and beta:

**Steps**
Save a bookmark
Go to Library -> Bookmarks
Long tap on the recent bookmark tile

**Actual**
Nothing happens

**Expected** 
Similarly to what happens when long pressing in a new bookmark added into a folder, this menu should be shown:
<img width="301" alt="Screenshot 2019-06-12 at 16 37 56" src="https://user-images.githubusercontent.com/1897507/59360489-76a54500-8d30-11e9-8292-9b9660dd055d.png">

**Comment by justindarc** [comment]
Also fixing this as a part of #5100.
