### ISSUE TITLE
Switch to new tab from bookmark context menu does not dismiss the bookmark drawer

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/firefox-ios#5130]
Master and beta
**Steps**
Create a new bookmark in any folder
Long tap on the bookmark
Select Open in New Tab
When the Switch button appears, tap on it

**Actual**
It seems that nothing has happened although the new tab has been loaded behind the drawer

**Expected**
The drawer should be dismissed so that user is taken to the new tab as selected after clicking on Switch

Please see current behavior here:

[Switch.mov.zip](https://github.com/mozilla-mobile/firefox-ios/files/3281845/Switch.mov.zip)

**Comment by justindarc** [comment]
Fixing this as a part of #5100.
