### ISSUE TITLE
[fxa sign in] Push notification opt-in: show dialog prior that explains why user should opt-in

### ISSUE THREAD

**Issue by garvankeeley** [mozilla-mobile/firefox-ios#5134]
Many apps are using a 'primer' dialog that explains why the user should opt-in to push, and based on this primer dialog, can see if the user cancelled or agreed to go to the next step. 

If the user goes to view their sent tabs, or *use* send tab, we may be able to indicate that they may not have opted in to push notifications.

**Comment by farhanpatel** [comment]
@ryanfeeley any thoughts on what text we could put here?

**Comment by ryanfeeley** [comment]
This is older copy, but I think @mheubusch would still agree. We could use the same UI type as the tour (copy FPO) to open up any time the user hit an entry point to Sync. Real copy on bottom below.

<img width="675" alt="image" src="https://user-images.githubusercontent.com/68213/67717581-5f47bb00-f9a4-11e9-8af8-d4b82cb673d4.png">

**Comment by mheubusch** [comment]
@bryanbell I agree 100% with Ryan that we should use a pre-permission message so if a user is not ready to commit to Push we still have a chance to ask them again (like if they are trying to Send Tabs). Do you think the tour panel UI can support this? We could also mirror the permission prompt itself. We need a message format that supports:
Headline
Body Copy
Two buttons of equal importance/weight

**Comment by ryanfeeley** [comment]
@mheubusch Would we give the user the option to decline marketing messages in this priming screen?

**Comment by mheubusch** [comment]
@ryanfeeley Yes - I discussed with @bryanbell earlier this week. Bryan can you share your design proposal?

**Comment by athomasmoz** [comment]
Replacing this issue with #5789 to refine original description
