### ISSUE TITLE
Long-pressing the Back button in the Bookmarks panel should pop to the root

### ISSUE THREAD

**Issue by justindarc** [mozilla-mobile/firefox-ios#5135]
Self-explanatory. This is a UX optimization for users to quickly return to the root if they've navigated deep into a folder hierarchy.

**Comment by garvankeeley** [comment]
Is this a standard UI paradigm? I never knew apps did this, so I am worried about the discoverability of this, it might seem like a bug.

**Comment by justindarc** [comment]
@garvankeeley I got the 👍 from @bryanbell
