### ISSUE TITLE
[Bookmarks]Long press on the 'Back' button does not work after entering/exiting Edit mode   

### ISSUE THREAD

**Issue by csuciu** [mozilla-mobile/firefox-ios#5144]
v18.0(15530)
iPhone XS 12.3.1

1. Open Bookmarks panel.
2. Navigate to a sub-folder.
3. Enter 'Edit' Mode.
4. Exit 'Edit' Mode.
5. Long press on the 'Back' button.

Expected: Should return directly to the root of the bookmarks folders. 

Actual: Does a simple back action.

**Comment by justindarc** [comment]
Great find!
