### ISSUE TITLE
Upon clicking on Save after creating a new bookmark or folder the item is shown as in Edit mode

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/firefox-ios#5146]
Master e5f6f565be3e87764b371e409b69d45a509adc18

**Steps**
Go to Bookmarks -> Mobile Bookmarks -> `+`-> New Bookmark
Enter Title, URL and click on Save

**Actual**
After tapping on Save this is the screen shown:
![Screenshot 2019-06-14 at 10 30 43](https://user-images.githubusercontent.com/1897507/59495434-87b89800-8e8f-11e9-916c-d473d1ff22b8.png)
So, to save the bookmark, you have to click again on Save

**Expected**
I would expect directly this screen instead:
![Screenshot 2019-06-14 at 10 33 17](https://user-images.githubusercontent.com/1897507/59495585-e1b95d80-8e8f-11e9-940c-fac556657a79.png)

IMHO, once Bookmark is created just one click on Save should be enough to have it in the list, no need for an extra step

**Comment by isabelrios** [comment]
It may be the right behavior since you start adding a new bookmark from the edit menu...but would be helpful to double check, thanks!

**Comment by ezraberch** [comment]
Looking at built-in apps, there isn't complete consistency as to this kind of behavior. However, the prevalent behavior is that the "add" button is displayed outside of edit mode but hidden in edit mode, thus avoiding this issue entirely.

In the Clock app, the add button is available both in and out of edit mode; creating a new item from within edit mode does exit edit mode.

**Comment by justindarc** [comment]
After you save the new bookmark, you are still in edit mode. The bookmark you just created was, in fact, saved though. This is expected.
