### ISSUE TITLE
Firefox crashes when switching to airplane mode or when using slow internet connection

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#5162]
Build: 18.0 (15530)

So far the only clue we have is that Firefox might crash when switching to airplane mode or when using slow internet connection. This might be sync related.

**Comment by farhanpatel** [comment]
Should be fixed in https://github.com/mozilla-mobile/firefox-ios/issues/5166

**Comment by cpeterso** [comment]
I haven't seen any crashes for over a week (since 2019-06-17). 🎉
