### ISSUE TITLE
iOS 13: Use the new Desktop content mode on iPad

### ISSUE THREAD

**Issue by smashedoranges** [mozilla-mobile/firefox-ios#5165]
Apple has stated that in iOS 13 for iPad, Safari will force desktop site by default. It would be helpful to have this in Firefox for iPad also. 

https://ios.gadgethacks.com/news/youll-be-able-force-safari-use-desktop-view-by-default-for-specific-sites-ios-13-0198651/

**Comment by farhanpatel** [comment]
https://developer.apple.com/documentation/webkit/wkwebpagepreferences/contentmode?changes=latest_minor

**Comment by garvankeeley** [comment]
We have been doing this as of version 20, closing as fixed
