### ISSUE TITLE
Problems in setting up the Dev Environment

### ISSUE THREAD

**Issue by sindhugudivada** [mozilla-mobile/firefox-ios#5170]
I 'm trying to set-up the dev env. I 'm currently using Swift4.2. But I keep getting the error saying  that SWIFT_VERSION_5 is not available.

 SWIFT_VERSION '5.0' is unsupported, supported versions are: 3.0, 4.0, 4.2

I believe this Master branch is written in Swift4.2. I use XCode 10.1 .

Did any one face the same issues?

**Comment by farhanpatel** [comment]
Please try Xcode 10.2.1

**Comment by farhanpatel** [comment]
Make sure to also update carthage again once you update xcode
