### ISSUE TITLE
[XCUITests] Update Sync and Navigation tests according to new sync login page

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/firefox-ios#5171]
These tests are failing because now the FxA sync page is different:
![Screenshot 2019-06-25 at 09 50 57](https://user-images.githubusercontent.com/1897507/60079775-74a19580-96e3-11e9-9043-0be2472247c2.png)

And also because it is not accessible now. Please see printed object tree:
<img width="819" alt="Screenshot 2019-06-25 at 09 50 37" src="https://user-images.githubusercontent.com/1897507/60079807-86833880-96e3-11e9-9e3e-a4761069d2db.png">

Looks like it is not possible to type email and click on Continue button...
@garvankeeley is the new behavior intended or is there a way to expose those fields again so that we can enter data while running the tests? 

Thanks!

**Comment by garvankeeley** [comment]
This is correct behaviour, the new Trailhead style sign in form looks like that. I'll look at exposing the field.

**Comment by garvankeeley** [comment]
This works for me
```
    private func verifyFxASigninScreen() {
        waitForExistence(app.webViews.staticTexts["Enter your email"])
        XCTAssertTrue(app.navigationBars["Client.FxAContentView"].exists)
        let email = app.textFields.element(boundBy: 0)
        XCTAssertTrue(email.exists) // the email field

        // Verify the placeholdervalues here for the textFields
        let mailPlaceholder = "Email"
        let defaultMailPlaceholder = email.placeholderValue!
        XCTAssertEqual(mailPlaceholder, defaultMailPlaceholder, "The mail placeholder does not show the correct value")
        XCTAssertTrue(app.webViews.buttons["Continue"].exists)
    }
```
