### ISSUE TITLE
Maintain tab “scroll“ location and state in Reader View

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#5189]
Logged via: https://bugzilla.mozilla.org/show_bug.cgi?id=1561664

STR:
1. Visit a page you want to read, e.g. https://blog.mozilla.org/firefox/block-cryptominers-with-firefox/ (though a long read may work better)
2. Start reading the page and make it half way through the article.
3. Get distracted and go do other things on your device (iPhone or iPad)
4. Come back to find that Firefox has “quit”, meaning all tabs are reloaded.
5. Note that you have to start at the beginning of the article in Reader View instead of picking up where you left off.

In these instances, Reader View should store your location and “state” (i.e. that Reader View was turned on) when reloading the tab, and automatically turn Reader View on and scroll to the same location in the article.

(This could be a more general bug about maintaining page/scroll location _regardless of Reader View_, but I think it makes the most sense in Reader View.)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2129)

**Comment by lmarceau** [comment]
Since only `data-sync-user` has commented on the issue after the `Stalebot` GitHub action (which triggered the removal of the `stale` label) I’ll close this issue for now. Please let us know if you think this issue needs to be reopened, we'll gladly do so. Thank you!
