### ISSUE TITLE
Add Search Engine screen’s Title box uses the URL keyboard

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#5190]
Logged via: https://bugzilla.mozilla.org/show_bug.cgi?id=1417864

Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 11_0_3 like Mac OS X) AppleWebKit/604.1.38 (KHTML, like Gecko) FxiOS/10.1b7709 Mobile/15A432 Safari/604.1.38

Steps to reproduce:

1. Go to Settings
2. Select “Search”
3. Select “Add Search Engine”
4. Focus the “Title” field

Actual results:

The URL keyboard is displayed, which does not allow spaces to be entered

Expected results:

The standard keyboard (with capitalisation probably) should have been displayed to allow spaces to be entered.

**Comment by SimonBasca** [comment]
#3466

**Comment by dfperry5** [comment]
@farhanpatel @SimonBasca  -- Is this still an issue? Something I could take on? Not too experienced with open source, though i did just open a PR with some unit tests :)

**Comment by SimonBasca** [comment]
@dfperry5 This issue is still reproducible on Firefox 21.0 (16918). This is free to take if you're willing to help. If you have any questions or need guidance, you can contact @garvankeeley.

**Comment by dfperry5** [comment]
@SimonBasca - I'm gonna start working on this today!

@garvankeeley  - sorry in advance if i ask too many questions!

**Comment by dfperry5** [comment]
@garvankeeley  -- any feedback on the above commit, before I open a PR? :)

**Comment by garvankeeley** [comment]
PR looks good so far

**Comment by dfperry5** [comment]
@garvankeeley  - PR opened here: https://github.com/mozilla-mobile/firefox-ios/pull/5927

**Comment by csuciu** [comment]
Verified as fixed on master c2574a0a55.
