### ISSUE TITLE
Align Tracking Protection with Desktop. (Introduce Enhanced Tracking Protection)

### ISSUE THREAD

**Issue by farhanpatel** [mozilla-mobile/firefox-ios#5197]
We need to map our messaging and features around Tracking Protection in skyline. This will require string changes and maybe changes to the lock and shield UI

**Comment by garvankeeley** [comment]
Newer bug is a dup of this one; arbitrarily I'll close this one
https://github.com/mozilla-mobile/firefox-ios/issues/5200
