### ISSUE TITLE
[UITests] Tracking Protection tests are failing

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/firefox-ios#5203]
These three [TP tests](https://github.com/mozilla-mobile/firefox-ios/blob/master/UITests/TrackingProtectionTests.swift#L40) are failing.
If I comment part of the [checkTrackingProtection](https://github.com/mozilla-mobile/firefox-ios/blob/master/UITests/TrackingProtectionTests.swift#L89) method, then they work. Not sure why, I would like to understand if it could be due to an issue or not...
```
private func checkTrackingProtection(isBlocking: Bool, isTPDisabled: Bool = false) {
//        if !isTPDisabled {
//            if isBlocking {
//                statsIncrement = expectation(description: "stats increment")
//            } else {
//                statsZero = expectation(description: "stats zero")
//            }
//        }

        let url = "\(webRoot!)/tracking-protection-test.html"
        checkIfImageLoaded(url: url, shouldBlockImage: isBlocking)

//        if !isTPDisabled {
//            waitForExpectations(timeout: 5, handler: nil)
//        }
//
//        statsIncrement = nil
//        statsZero = nil
    }
```

@garvankeeley could you please confirm if there have been some changes that could have make the tests fail on those lines? If there is not any issue detected by them, then we could get rid of those. Thanks!

**Comment by garvankeeley** [comment]
Commenting that code out basically disables the test, any idea when it first broke?

**Comment by isabelrios** [comment]
Well, if I'm not mistaken, we still check if the image is blocked or not with `checkIfImageLoaded(url: url, shouldBlockImage: isBlocking)`

**Comment by garvankeeley** [comment]
Sorry, you are right, that still does check for the blocking being on. So it is just the stats reporting that is broken.
