### ISSUE TITLE
[XCUITest] Fix intermittent smoketest failures due to parallel testing

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/firefox-ios#5204]
This will require some investigation. But as for now there are some tests failing most of the times:

-TopTabsTestIphone.testSwitchBetweenTabsToastButton()
-TopTabsTest.testAddTabFromTabTray()
-TopTabsTest.testLongTapTabCounter()
-DragAndDropTests.testRearrangeTabsTabTray()
-SearchTests.testSearchStartAfterTypingTwoWords()

Let's try to add the necessary checks/waiting or what is needed so that we can keep running them in parallel and save run time.

**Comment by isabelrios** [comment]
@kglazko I have been adding more tests to the description of the issue. Those are the ones that fail more frequently.

**Comment by kglazko** [comment]
I have also found this test failing: PhotonActionSheetTest: testShareOptionIsShownFromShortCut

**Comment by kglazko** [comment]
ClipboardTests
testClipboardPasteAndGo
Pasteboard seems to be containing the wrong URL, one used in another test. Is the pasteboard shared across the different clones or do they each have their own?

**Comment by isabelrios** [comment]
I'm keeping track of the failures on BB and Bitrise and I rarely see that Clipboard test failing, but yes, it could be that it uses the pasteboard from another test ...not sure how that could be fixed... :S

**Comment by isabelrios** [comment]
Running your branch on Bitrise I see these failures (so far 3 out of 3 runs): 
-TopTabsTest.testAddTabFromTabTray()
-TopTabsTest.testCloseAllTabsPrivateModeUndo()

**Comment by isabelrios** [comment]
Closed by #5260
