### ISSUE TITLE
Request Desktop Site Not Remembered 

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#5213]
Logged via : https://bugzilla.mozilla.org/show_bug.cgi?id=1562450

Steps to reproduce:

Go to slickdeals.net (get mobile version)
Request Desktop Site (get desktop version)
Close tab
Go to slickdeals.net (get mobile version)

Actual results:

The request desktop site is forgotten between visits.

Expected results:

Per https://support.mozilla.org/en-US/kb/viewing-desktop-sites-firefox-ios:

"When you request a site in desktop view one time, Firefox will always show that site in desktop view every time you visit until you switch back to mobile."

This is how it used to work. Broke in past couple months.

**Comment by SimonBasca** [comment]
This issue is still reproducible with latest master and 18.0 Build 15680.

**Comment by SimonBasca** [comment]
Verifying as fixed on 18.0(15690)

**Comment by tobyjohnm** [comment]
Works for me, thanks (18.0 released to app store).
