### ISSUE TITLE
Bookmarks folders order is inconsistent with desktop

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#5214]
Logged via: https://bugzilla.mozilla.org/show_bug.cgi?id=1560863

Steps to reproduce:

Nothing, things seem to be this way by itself.

Actual results:

Bookmarks order is different than before or in desktop Windows Firefox.

Order of bookmarks folders is now:
Bookmarks Menu
Bookmarks Toolbar
Unsorted Bookmarks
Mobile Bookmarks

Reinstalled Firefox on my iPhone XR and it seems to be the same way still.

Expected results:

The order of bookmarks folders should be:
Bookmarks Toolbar
Bookmarks Menu
Unsorted Bookmarks
Mobile Bookmarks

**Comment by farhanpatel** [comment]
The order is not something we'll fix on iOS. But we'll rename unsorted to other to match desktop

**Comment by mattdutson** [comment]
@farhanpatel The iOS folder is still named "Unsorted Bookmarks." Are there still plans to rename it to "Other Bookmarks" for consistency with desktop?
