### ISSUE TITLE
Context Menu unavailable on iPadOS 13 Beta

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#5217]
Logged via : https://bugzilla.mozilla.org/show_bug.cgi?id=1562444

Steps to reproduce:
1. Long press on any link.

iPadOS 13 Beta
Firefox iOS 17.3 (15323)

Actual results:
Link hovers, turning into a new iOS 13-style Drag & Drop item.

Expected results:
Open Firefox context menu (Open in New Tab, Open in New Private Tab, Bookmark Link, etc.)

**Comment by jordanweaver** [comment]
I just wanted to add that this is also present on the iPhone (8 Plus), iOS 13.0 Beta (17A5508m). The behavior there is any long-presses will just trigger a text-selection action.

I never realized how much I use that context menu until it disappeared!

**Comment by SimonBasca** [comment]
This is fixed in iOS 13.0 beta 2.
