### ISSUE TITLE
'Recent Bookmarks' header should match other table view headers in Settings

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#5237]
Build: v18.0 (15680) 
Device: iPhone Xr
iOS: 12.3

Steps to reproduce:
1. Go to Library -> Recent Bookmarks

Actual results:
- ' Recent bookmarks ' title is not bold
- ' Recent bookmarks ' title is not centered
- ' Separator line ' is not white in Dark Theme

Expected results: 
- ' Recent Bookmarks ' header should match other table view headers in Settings. 

![Screen Shot 2019-07-04 at 3 02 17 PM](https://user-images.githubusercontent.com/32130829/60665455-291e8280-9e6d-11e9-8a09-6265459b8991.png)

![Screen Shot 2019-07-04 at 3 02 49 PM](https://user-images.githubusercontent.com/32130829/60665316-d5139e00-9e6c-11e9-9ae2-a6bc956ec7fa.png)

**Comment by farhanpatel** [comment]
@bryanbell can you attach a mock on how this should look

**Comment by SimonBasca** [comment]
Verifying as fix on as on master c2574a0a5.
