### ISSUE TITLE
[X] button doesn't clear the URL on iOS Beta 

### ISSUE THREAD

**Issue by csuciu** [mozilla-mobile/firefox-ios#5239]
v18.0(15680)
iPad Pro iOS 13 Beta 1

1. Visit a page.
2. Tap on the URL bar.
3. Tap on [X] to clear the URL.

Result: [X] button doe not work. The URL is not cleared, instead, the URL context menu is triggered.

**Comment by SimonBasca** [comment]
This is fixed in iOS 13.0 beta 2.
