### ISSUE TITLE
Sumo support page is different on iPhone and iPad

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/firefox-ios#5241]
The website shown on iPad has changed and so the test `testHelpOpensSUMOInTab`is failing.
The one shown on iPhone and on iPad before is:
![Screenshot 2019-07-05 at 09 27 19](https://user-images.githubusercontent.com/1897507/60705722-1efd9200-9f08-11e9-979a-a6d56a349d28.png)

And the one shown now on iPad is:
<img width="472" alt="Screenshot 2019-07-05 at 09 28 13" src="https://user-images.githubusercontent.com/1897507/60705735-2886fa00-9f08-11e9-88c2-fd9e0b611a71.png">

Is this the expected one? @farhanpatel if so we will modify the tests for the iPad check. Thanks!

**Comment by farhanpatel** [comment]
Looks like the ipad one is more similar to desktop. That looks like the right choice. We should update our tests
