### ISSUE TITLE
Night Mode deactivates after closing and reopening app or tab while switch is on

### ISSUE THREAD

**Issue by 1hrj** [mozilla-mobile/firefox-ios#5255]
Night mode will be on and working when the app is closed. When it reopens the webpage has reverted to normal mode but the night switch is still showing it is activated. New tabs are also opening in normal mode even while the switch is still activated from the previous tab.

This happens with each tab and every webpage. 

Switching off and back on temporarily fixes the issue for the current tab until the app is closed.

**Comment by 1hrj** [comment]
By the way, I deleted the app from my phone and reinstalled it from App Store but that did not help.

**Comment by garvankeeley** [comment]
Thanks for the report, it is an annoying bug. The dark theme is a persistent setting in the app, but the night mode is not.

**Comment by 1hrj** [comment]
Thanks so much! Firefox is the best! :D

**Comment by farhanpatel** [comment]
Fixed in https://github.com/mozilla-mobile/firefox-ios/pull/5272
