### ISSUE TITLE
Build Failed

### ISSUE THREAD

**Issue by elemanhillary** [mozilla-mobile/firefox-ios#5258]
When trying to build in Xcode, i countered this error message `Command PhaseScriptExecution failed with a nonzero exit code`. Any kind of help?

**Comment by farhanpatel** [comment]
Make sure to run ./bootstrap.sh before trying to build. Also make sure to use xcode 10.2

**Comment by garvankeeley** [comment]
Builds are not known to be failing thus closing this.
