### ISSUE TITLE
 Night Mode is enabled but new tabs show up in day mode

### ISSUE THREAD

**Issue by csuciu** [mozilla-mobile/firefox-ios#5261]
v18.1 release

1. Enable night mode from the hamburger menu.
2. Go to bbc.com.
3. Long press on a link and select "Open in New Tab".
4. "Switch" to the new tab.
 
Result: The new tab does not have the night mode theme applied. 

Initially reported here: https://bugzilla.mozilla.org/show_bug.cgi?id=1565227

"User Agent: Mozilla/5.0 (iPad; CPU OS 12_3_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) FxiOS/18.1b15719 Mobile/15E148 Safari/605.1.15

Steps to reproduce:

For my iPad Pro 10.5” 2018 and iPhone XS Max, whenever I open a new tab and go to a site (so far it is any site) night mode is off in that tab, despite being enabled in the menu. The fix is easy, I just toggle off night mode and then toggle it back on and that tab is in night mode until I close it.  

Actual results:

a new tab does not have night mode enabled. This has only been happening since I updated to version 18.1. Prior to this is was working and new tabs were defaulted into night mode. I uninstalled and reinstalled Firefox and the issue still persists. 

Expected results:

In previous updates, when I had night mode enabled from the menu, every tab defaulted into night mode no matter what site I went to. I did not see anything in the change log about this, and am unsure why if night mode is enabled that a new tab would not be wanted in night mode."

**Comment by SimonBasca** [comment]
Verifying as fix on 18.2 (158817).
