### ISSUE TITLE
"imgur.com" Desktop Site does not work

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#5262]
Logged via: https://bugzilla.mozilla.org/show_bug.cgi?id=1565095

Steps to reproduce:
1. Go to https://imgur.com/a/JqDFSAO on Firefox for iOS
2. Request the page in desktop view

Actual results: 
The visual indicator in the Page Actions menu is flickering and the page not loading. 

Note: 
- Before the persistent desktop view, the page loaded in desktop view, or, most of the time, it even loaded the direct link to the image if there was no gallery, such as https://i.imgur.com/ZACm6P1.png which was really useful.
- "https://i.imgur.com" correctly loads desktop mode in Safari.

**Comment by farhanpatel** [comment]
closing in favor of https://github.com/mozilla-mobile/firefox-ios/issues/5263
