### ISSUE TITLE
Bookmarks overlap when using large and bold text

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#5264]
This was a 1 star review. Logged via Firefox Review: 

I have vision issues. Last update does not take into account that people change their fonts for larger one and bold them for contrast. My bookmarks are unreadable as they are larger than the alloted space and overwrite above and below. Next update that makes this worse will be the end of Firefox on my phone and desktop.

Screenshot made when using Large Text and Bold Text
![IMG_BA7FFBBEE1B7-1](https://user-images.githubusercontent.com/32130829/61200708-0866f000-a6eb-11e9-8e82-142eb0a9eac7.jpeg)

**Comment by karlcow** [comment]
Yes I confirm and it's quite annoying. :) It's an issue for people like who needs specs to read from close. 

## Steps to reproduce. 

1. Go to iOS settings
2. Then in Luminosity and Display
3. Then scroll down to text size and tap
4. Move the cursor to select a larger font.
5. Go to Firefox on iOS
6. Have multiple bookmarks in your bookmark list

Actual:
All texts are overlapping each other.

Expected:
texts are readable. The UI adjusts to a larger font. 

![image](https://user-images.githubusercontent.com/505230/72765257-dcdf3800-3c2e-11ea-8851-aef6b6950700.png)
