### ISSUE TITLE
Firefox 18.1 - Password Auth Http and password for web form #5043

### ISSUE THREAD

**Issue by nicoonline** [mozilla-mobile/firefox-ios#5268]
Hello,

Still not solved on last version of Firefox 18.1
There is a missmatch between login/password of realm_auth & webforms.

**Comment by farhanpatel** [comment]
The fix hasn't landed in v18 yet. Keep an eye out for the v19 beta which should have this fix

**Comment by nicoonline** [comment]
Thanks. It's not possible to push the commit to the 18 branch ?
