### ISSUE TITLE
[Sync Integration] `pipenv check` error because `pyup.io` is down

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/firefox-ios#5276]
Builds are failing before tests are launched due to this error.
```
pipenv check
Checking PEP 508 requirements…
Passed!
Checking installed package safety…
An error occurred:
Unable to load vulnerability database
```
This is due to a site which is down. See [issue](https://github.com/pypa/pipenv/issues/3826)
If the site is not up soon, there is a workaround as commented in that issue to pass this error.

I will give sometime to the site to be fixed before applying the workaround.

**Comment by mcallaghan-bsm** [comment]
The workaround is to not run the compare against pyup DB (you wouldn't want to permanently apply that as it is subsequently not checking all security aspects as desired)

**Comment by isabelrios** [comment]
yes, that was the workaround but looks like this has been fixed from pyup side so closing this issue for now.
