### ISSUE TITLE
Possible desktop mode regression for Whatsapp Web

### ISSUE THREAD

**Issue by miketaylr** [mozilla-mobile/firefox-ios#5287]
This bug was originally reported @ https://github.com/webcompat/web-bugs/issues/36201.

STR: enabled desktop mode, try to use whatsapp web.

From the original reporter:

> Description: This website was only accessible through desktop mode on IOS, however after the new iOS update it no longer works
Steps to Reproduce:
So I’ve been using what’s app web on my phone to skip the hassle of having to carry both of my phones with me at all times, and it was working flawlessly on Firefox IOS until I decided to update to the latest version which had the following update note “Added the ability to set sites to always open in desktop mode, and badges to make it more apparent when desktop is active”

> I believe that this update broke the website and it is now no longer accessible or usable as it doesn’t believe the request is coming from a real “desktop” browser

**Comment by farhanpatel** [comment]
Should be fixed in https://github.com/mozilla-mobile/firefox-ios/pull/5277
