### ISSUE TITLE
 Sharing bit.ly shortened docs.googleusercontent links causes previous website to be shared instead.

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#5288]
Logged via: https://bugzilla.mozilla.org/show_bug.cgi?id=1569558

User Agent: Mozilla/5.0 (iPad; CPU OS 12_3_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) FxiOS/18.1b15719 Mobile/15E148 Safari/605.1.15

Steps to reproduce:

I first loaded Microsoft.com on a tab. Then I changed the link of the same tab to a bit.ly shortened docs.googleusercontent link(bit.ly/findsaloniatmec.)and loaded it.Then I clicked on the share button and share to iMessage button

Actual results:

The link being shared was of the Microsoft website, instead of the actual bit.ly links original link

Expected results:

The currently loaded docs.googleusercontent link should have been shared.Same problem persists for starting from any Google search result as well.

Video link: 
- https://drive.google.com/file/d/1sFV9qyLZAyG2IeQRyEl2x_W9E0VwPrsx/view?usp=drivesdk

**Comment by garvankeeley** [comment]
fixed by https://github.com/mozilla-mobile/firefox-ios/pull/5296
