### ISSUE TITLE
Request Desktop Site does not work correctly for m.intl.taobao.com 

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#5294]
Build: 18.2 (15817)
Device: iPhone Xr
iOS: 12.2

Steps to reproduce:
1. Copy and paste "https://item.taobao.com/item.htm?id=582193636814" in the URL 
2. The URL in the address bar has now automatically loaded for mobile: https://m.intl.taobao.com/detail/detail.html?id=582193636814
3. Request the page in desktop view

Actual results:
- "404 Not Found" error is displayed.

Note:
- Manually typing "https://item.taobao.com/item.htm?id=582193636814" in the URL and requesting Desktop Site works fine.

**Comment by SimonBasca** [comment]
Also note, Request Desktop Site does not work on "wikipedia.org". The desktop version of wikipedia is not loaded.

**Comment by dnarcese** [comment]
This will be fixed when we switch to ios13 desktop site API's.
