### ISSUE TITLE
Send Tab is missing the tablet icon, at least for iPad

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla-mobile/firefox-ios#5299]
**Current**
![IMG_0678](https://user-images.githubusercontent.com/68213/62397053-c0492980-b542-11e9-88e0-1d3282360c6a.PNG)

**Proposed** (icon used in desktop)
![Screen Shot 2019-08-01 at 9 53 14 AM](https://user-images.githubusercontent.com/68213/62397082-cd661880-b542-11e9-9a80-cfc633697138.png)

Icon available here: https://design.firefox.com/icons/viewer/#tablet

**Comment by SimonBasca** [comment]
Verifying as fix on 21.0 (16901)
