### ISSUE TITLE
YouTube (desktop mode) generated share link URL cannot be copied to clipboard

### ISSUE THREAD

**Issue by ChaiTRex** [mozilla-mobile/firefox-ios#5304]
On YouTube video pages in desktop mode, the share link URL generator does not allow you to put the URL in the clipboard

0. Go to a YouTube video in desktop mode.
0. Tap the Share button directly below the video next to the thumbs up/down buttons.
0. Try to select and copy the URL in the share dialog through iOS's normal text field editing functions.
0. Note that you can't do that.
0. Tap the copy button next to the share URL.
0. Note that the page says "Link copied to clipboard" at the bottom left corner on the screen.
0. Try to paste the URL somewhere.
0. Note that the URL isn't actually in the clipboard.

**Comment by farhanpatel** [comment]
unfortunately this is a bug on Youtube and not in Firefox.
