### ISSUE TITLE
Top sites: adding URL to top sites overwrites existing top site on the same host

### ISSUE THREAD

**Issue by csuciu** [mozilla-mobile/firefox-ios#5306]
Steps to reproduce:

Setup: Open "https://www.bbc.co.uk/news" and pin to top sites

Step 1: Open "https://www.bbc.co.uk/sport/football" and pin to top sites

Actual results:

There is now just one entry for BBC pointing to "https://www.bbc.co.uk/sport/football". The previously pinned top site "https://www.bbc.co.uk/news" has disappeared.

Also, the new pinned site shows up first on the list, which means all other pinned sites end up in unfamiliar locations (to an older person this looks like all the pinned sites have been shuffled around).

Expected results:

My pinned sites should remain as they were (including "https://www.bbc.co.uk/news") and a new pinned site "https://www.bbc.co.uk/sport/football" should appear as last in the list of pinned sites.

Source: https://bugzilla.mozilla.org/show_bug.cgi?id=1571545

**Comment by andreap007** [comment]
While fixing this issue, another problem appeared (removing one top pinned site, removes all the top sites from the same host). Should I try to fix it in the scope of this issue or create a pull request for what I have now, and open another issue?
