### ISSUE TITLE
The text in the protection details screen is tappable and remains highlighted

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#5309]
Build: 2608a54
Device: iPhone XS
iOS: 12.2

Steps to reproduce:
1. Go to Settings -> Tracking Protection 
2. Tap on the details button next to "Standard" or "Strict"
3. Tap on the the text 

Actual results: 
- The text in the protection details screen is tappable and remains highlighted.

![IMG_26CC820EF5F5-1](https://user-images.githubusercontent.com/32130829/62551420-a37b6180-b874-11e9-964b-b6dbfadde1c9.jpeg)

**Comment by garvankeeley** [comment]
Fixed by https://github.com/mozilla-mobile/firefox-ios/pull/5314
