### ISSUE TITLE
Tracking protection shield is incorrectly positioned

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#5310]
By design the tracking protection shield should be the first element to the left in the URL bar.  

Design docs:
https://mozilla.invisionapp.com/share/EPSRYMMDW3K#/screens/371655661

Screenshot: 
![IMG_71D42B2624CD-1](https://user-images.githubusercontent.com/32130829/62551853-5f3c9100-b875-11e9-8ba5-04d068eecd0f.jpeg)

**Comment by garvankeeley** [comment]
fixed in https://github.com/mozilla-mobile/firefox-ios/pull/5314
