### ISSUE TITLE
Tracking protection shield should update after disabling from settings or via long press on "Refresh" button

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#5311]
Build: 2608a54

Steps to reproduce:
1. Go to emag.ro
2. Open settings from TP menu (press on shield icon then settings)
3. Disable TP

Actual results:
- Tracking protection shield is not updating.

Expected results:
- Tracking protection shield should update and be displayed as disabled.

Note:
- The shield icon is also displayed as active after long pressing on the "Refresh" button and disabling Tracking Protection for that Tab.

**Comment by garvankeeley** [comment]
fixed in https://github.com/mozilla-mobile/firefox-ios/pull/5314
