### ISSUE TITLE
Shield icon does not respect design doc color

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#5313]
By design the shield icon should be grey when nothing is being blocked and white with a purple background when something is being blocked. 

Design docs: https://mozilla.invisionapp.com/share/EPSRYMMDW3K#/screens/371655661

**Comment by garvankeeley** [comment]
Will be fixed by https://github.com/mozilla-mobile/firefox-ios/pull/5314
