### ISSUE TITLE
"Not blocked" list is not displayed.

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#5317]
In the design docs I am also seeing a section of trackers that are not blocked. 

![image](https://user-images.githubusercontent.com/32130829/62766289-c5562d80-ba9a-11e9-8a8f-985a369f291f.png)

This is currently not implemented. Please feel free to close this issue if this is something we are not going to do.  

Design docs: https://mozilla.invisionapp.com/share/EPSRYMMDW3K#/screens/371655661

**Comment by garvankeeley** [comment]
Thanks for noticing this. We aren't doing the list of non-blocked items for the first version.

**Comment by garvankeeley** [comment]
Closing this as we don't have the necessary APIs.
