### ISSUE TITLE
Remove the "defaults.synchronize()" line in AppDelegate.swift

### ISSUE THREAD

**Issue by akshay1992kalbhor** [mozilla-mobile/firefox-ios#5323]
Hello everyone,
I wanted to start contributing to the project and while going through the source code, found out that the synchronize method on UserDefaults is unnecessary and should not be used. I have not contributed to OS before and am not sure if this is even a valid issue. If it is I would love to make the necessary changes and make this my first contribution. If its not, feel free to delete this post :)

Thanks

<img width="666" alt="Screen Shot 2019-08-12 at 6 24 15 PM" src="https://user-images.githubusercontent.com/26027678/62866458-6c9ec300-bd2e-11e9-8c34-60b34c6fcf91.png">

**Comment by garvankeeley** [comment]
Valid point!

**Comment by akshay1992kalbhor** [comment]
Ok so I found out that defaults.synchronize() is used three times in AppDelegate.swift and once in SentryIntegration.swift. Can I make the changes and bundle them in a single commits as its the same issue but in different files? Thanks

**Comment by garvankeeley** [comment]
Single commit for all of them will be fine

**Comment by akshay1992kalbhor** [comment]
Fixed with PR #5327
