### ISSUE TITLE
Disable Firefox-initiated Push Notifications and In-app Messaging

### ISSUE THREAD

**Issue by mheubusch** [mozilla-mobile/firefox-ios#5328]
As a Firefox for iOS user, I want the ability to turn off product messages so that I can use my iPhone and Firefox without interruptions from messages I did not initiate.

Acceptance Criteria

- I can access a setting to disable messages
- If I disable messages, I will no longer have messages I do not initiate from Firefox appear in-app or via Push
- If I disable messages, I will still have messages I do initiate appear in-app and via Push (for example, success messages or notifications for incoming sent tabs)

**Comment by mheubusch** [comment]
The thing I want to call out is that allowing Push Notifications improves syncing and enables Send Tabs, so we don't want users to lose that functionality if they disable Push.  I think we should consider how we might prompt users who sign in to Sync to allow Push differently than prompting users who are allowing notifications without using Sync and also consider if we should confirm intent to get notifications from users who are primarily allowing push for Sync (or, not assume intent to allow notifications).

**Comment by garvankeeley** [comment]
Maybe a setting for this would help

**Comment by athomasmoz** [comment]
Newest OS allows you to opt-out by long-pressing on the message. This could mean more users opt-out and then they don't get the sync benefits that require push

**Comment by athomasmoz** [comment]
Created #5790 to create setting for this.
