### ISSUE TITLE
Strict protection blocks less than Standard protection

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#5333]
Build: 19.0 (15910)
Device: iPhone Xr
iOS: 12.2

Steps to reproduce:
1. Go to https://cryptojackingtest.com/ with Standard Protection
2. Tap on the Shield icon
3. Tap on Social Trackers (Observe there are 4 socials trackers being blocked)
4. Set protection to Strict.
5. Go to https://cryptojackingtest.com/ 
6. Tap on the Shield icon
7. Tap on Social Trackers (Observe there are 2 socials trackers being blocked)

Actual results:
- Strict protection is  blocks less trackers than Standard protection

Expected results:
- - Strict protection should  block more trackers than Standard protection

Screenshot
- Standard Protection
![Standard](https://user-images.githubusercontent.com/32130829/63010687-8277c980-be8f-11e9-9333-977f0ee8143c.jpeg)

- Strict Protection:
![Strict](https://user-images.githubusercontent.com/32130829/63010695-84da2380-be8f-11e9-98e3-ee2654db5832.jpeg)

**Comment by garvankeeley** [comment]
This is correct behaviour unfortunately. I feel we should try to explain this in the UI somewhere. In strict, the URL loads are blocked. In this case the connect.facebook.com URL loads staticxx.facebook.com as a subresource. In default mode we allow all loads an just block cookies. In strict, connnect.facebook.com is blocked from loading, so it doesn't load its subresources.
