### ISSUE TITLE
Standard Tracking Protection does not block all Cross Site Trackers and all Social Trackers on test page

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#5334]
Build: 19.0 (15910)
Device: iPhone Xr
iOS: 12.2

Steps to reproduce:
1. Go to https://mozilla.github.io/tracking-test/disconnect.html with Standard Protection
2. Tap on the Shield icon (Observe only one Social tracker is being blocked)
3. Go to https://mozilla.github.io/tracking-test/disconnect.html with Strict Protection
4. Tap on the Shield icon (Observe 1 Cross Site Tracker and 2 Social tracker are being blocked)

Expected results:
- I would expect the same number of Social Trackers and Cross Site Trackers shoudl be blocked.

**Comment by farhanpatel** [comment]
Can we test this again on the latest master

**Comment by SimonBasca** [comment]
This issue is no longer reproducible on latest master 1bccce9f6. The same number of Social Trackers and Cross Site Trackers are being blocked on both Strict and Standard protection
