### ISSUE TITLE
ETP is not shown as active in a website until it is refreshed if ETP has been disabled and then enabled

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/firefox-ios#5337]
**Steps**
Go to a website with blocked elements: www.twitter.com
Tap on Shield icon -> Protection Settings -> Disable ETP
Go back to twitter site and verify that the icon is not shown
Go to Settings from browser tab menu -> Tracking protection and Enable ETP
Tap on Settings -> Done to go back to twitter.com

**Actual**
The shield icon does not appear after enabling ETP for a site with blocked elements until the site is not refreshed or closed/open

**Expected**
The shield icon is shown again when ETP is enabled from Settings without needing to refresh/close the open website

**Comment by farhanpatel** [comment]
We're going to leave this as is. This happens on desktop too.
