### ISSUE TITLE
Make it easier to navigate to synced tabs

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#5345]
**Vision**

As a user, I want my synced tabs to be easier to access and similar to where I find them on desktop, as I often forget they are under "History" on iOS

**Acceptance Criteria**

* The link to synced tabs is directly under "Your Library" in the menu, rather than under History
* There's a link to synced tabs on the new tab page under "Your Library"
* Probes have been added to track number of clicks on each of the library links in new tab (bookmarks, history, reading list, synced tabs, downloads), so we can determine in the future if there's a better way to order them. 

**Spec**
https://mozilla.invisionapp.com/share/A7UQ5NBTQHU#/392279706_Artboard

**Notes**
Via: ttps://twitter.com/mc_niels100/status/1161283740171198464

This would be a nice to have enhancement. The user reported that currently is hard to get to sync tabs and would like to make it easier to navigate to synced tabs.

**Comment by athomasmoz** [comment]
NOTE: The ideal end state for this ticket is the mock on the top right in the spec. The one on the left is a potential interim solution if the slider is too risky/too much effort.

**Comment by athomasmoz** [comment]
@garvankeeley @SimonBasca can you confirm which mock you followed for the solution here? Was is the "See All" version 
<img width="245" alt="image" src="https://user-images.githubusercontent.com/43346208/69073939-3636ab00-09e3-11ea-85a4-a38861057606.png">
Or the slider version
<img width="251" alt="image" src="https://user-images.githubusercontent.com/43346208/69073955-3e8ee600-09e3-11ea-8d08-6bd490d760fa.png">

I'm just trying to get the SUMO articles confirmed

**Comment by SimonBasca** [comment]
@athomasmoz, I am seeing the "See All" version in the latest master build 9741a9ec05728f

**Comment by csuciu** [comment]
The current behaviour is:
 - "See All button" button from the home page always opens "History" panel. 
 - "Your Library" button from the menu always opens the last used Library tab.
