### ISSUE TITLE
ETP label is truncated in Settings

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla-mobile/firefox-ios#5350]
The ETP setting is truncated in French, it should probably wrap in multiple lines instead

![IMG_5403](https://user-images.githubusercontent.com/1294206/63347883-00d0e180-c350-11e9-8d1e-c4b18cd498d3.PNG)

cc @Delphine

**Comment by garvankeeley** [comment]
Fixed by https://github.com/nick130586/firefox-ios/commit/b3dadd84af25572626c2ed972b5a1b73850c2356
