### ISSUE TITLE
FXIOS-130 ⁃ Feature request : Support yubico iOS SDK

### ISSUE THREAD

**Issue by F3000** [mozilla-mobile/firefox-ios#5365]
more Infos can be found here : 

https://www.yubico.com/why-yubico/for-developers/mobile-sdk-ios-sign-up/

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-130)

**Comment by reevesnick** [comment]
iOS 13.3 Beta has support for WebAuthn. This can be implement via WebKit.

Source: https://developer.apple.com/documentation/authenticationservices/aswebauthenticationsession

**Comment by timbru31** [comment]
I would also vote to close this one in favor of #5364 - we probably should support the OS API rather than bundling a SDK that only supports one security key.

**Comment by SimonBasca** [comment]
Closing https://github.com/mozilla-mobile/firefox-ios/issues/5364#issuecomment-826489193
