### ISSUE TITLE
[iOS 13] Firefox will crash after opening the Share Menu on a downloaded page

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#5369]
Build: 19.0(15967)
Device: iPad Pro
iOS: 13.0b7

Steps to reproduce:
1. Go to CNN.com and download a link
2. Go to Downloads panel and open the downloaded link in a new tab
3. Tap on the Page action menu
4. Tap "Share Page With"

Actual results:
- Firefox will be in an unresponsive state and eventually crash.

**Comment by garvankeeley** [comment]
Does non-beta crash?

**Comment by SimonBasca** [comment]
Non beta does not crash. This might get fix in upcoming iOS beta versions. I think we can leave it for now and I'll retest it.

**Comment by csuciu** [comment]
I can't reproduce on non beta iOS 13.
