### ISSUE TITLE
Add a Tab Sent notification

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla-mobile/firefox-ios#5375]
We show cute little notifications for actions like **Bookmark Added** (see below) and should add one that says **Tab Sent** when a tab is sent from within Firefox.
![bookmark added](https://user-images.githubusercontent.com/68213/63699936-ceabfd80-c7ef-11e9-9262-c8ae4754e8ec.PNG)

**Comment by farhanpatel** [comment]
Fixed
