### ISSUE TITLE
[v19] Variable %s in release version

### ISSUE THREAD

**Issue by ksmammar** [mozilla-mobile/firefox-ios#5382]
This Pontoon string has %s variable - https://pontoon.mozilla.org/ta/firefox-for-ios/firefox-ios.xliff/?status=translated&search=%E0%AE%95%E0%AF%87%E0%AE%B3%E0%AF%8D%E0%AE%B5%E0%AE%BF&string=162911

In release screenshot %s was not replaced by respective term. Link for Screenshot:  https://www.dropbox.com/sh/jbk7f8er8ukqzqf/AACfCpj6YtDE4pdA46jTvy4ea/ta/ta?dl=0&preview=iPhone+SE-04Settings-AddCustomSearchSettings-0.png&subfolder_nav_tracking=1
![image](https://user-images.githubusercontent.com/16062222/63829453-38aadb00-c987-11e9-9ae8-a74fb092b32d.png)

cc: @Delphine

**Comment by farhanpatel** [comment]
This is how it is suppose to work. Look at the example url at the bottom it also has `%s` this is part of how the url string should be formated
