### ISSUE TITLE
The Sync button from the hamburger menu is no longer displayed after enabling night mode

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#5383]
Build: 19.0 (15995)
Device: iPhone Xr
iOS: 12.2

Steps to reproduce:
1. Launch Firefox
2. Enable on Night mode from the Hamburger menu

Actual results:
- The Sync button from the hamburger menu is no longer displayed.

![IMG_0F67CCEB2C81-1](https://user-images.githubusercontent.com/32130829/63869421-ca830a00-c9c0-11e9-9da3-93bc2745aaec.jpeg)

![IMG_886E36691969-1](https://user-images.githubusercontent.com/32130829/63869427-cc4ccd80-c9c0-11e9-96a0-983aa2b1602b.jpeg)

**Comment by SimonBasca** [comment]
After closing and re-opening the hamburger menu the button will be displayed.

**Comment by isabelrios** [comment]
More info: if you close the menu and open it again, the the sync button is shown correctly. Thought that having it shown maybe the priority could be P3
