### ISSUE TITLE
Library header (Reader View and Download list) are not changing the theme correctly after enabling night mode

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#5384]
Build: 19.0 (15995)
Device: iPhone Xr
iOS: 12.2

Steps to reproduce:
1. Launch Firefox
2. Enable on Night mode from the Hamburger menu
3. Tap on the Reader mode shortcut on the homepage

Actual results:
- Library header (Reader View and Download list) are not changing the theme correctly after enabling night mode. 

![IMG_B70BBA1B6B04-1](https://user-images.githubusercontent.com/32130829/63869739-54cb6e00-c9c1-11e9-877e-3d26e10dcb11.jpeg)

**Comment by farhanpatel** [comment]
dupe
