### ISSUE TITLE
Add an event for push notifications

### ISSUE THREAD

**Issue by fbertsch** [mozilla-mobile/firefox-ios#5385]
This is a request that would inform experiment analysis. We would like to add an event that indicates a user received a push notification, and any information about that notification we have (specifically, cohort, assuming this was a Leanplum experiment).

We can discuss feasibility here. Do we have access to this data through the Leanplum SDK? Will the event show if a user doesn't open the app immediately from the push notification, but does open it some time later (perhaps after dismissing it)? Can we set the timestamp of the event to be _negative_, indicating it happened _before_ the app process started (and do we know what that length of time is)?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2161)

**Comment by farhanpatel** [comment]
We should have this data inside Leanplum if the push notification was sent from there.
