### ISSUE TITLE
Night mode: Images overlapping

### ISSUE THREAD

**Issue by wayne-zhang** [mozilla-mobile/firefox-ios#5388]
Sine upgraded to 18.2, images are overplayed/mixed. For example, on Twitter. Will attach screenshot.

**Comment by wayne-zhang** [comment]
How to attach images to issues?

**Comment by csuciu** [comment]
> How to attach images to issues?

Drag&Drop into the comment box.

**Comment by wayne-zhang** [comment]
Thanks csuciu! I am using iPhone, will logon to desktop.

**Comment by wayne-zhang** [comment]
![image2](https://user-images.githubusercontent.com/3071035/64005170-6720e580-cb42-11e9-9103-5977d0ab7469.png)
![image3](https://user-images.githubusercontent.com/3071035/64005173-68eaa900-cb42-11e9-9e8d-df95ec963842.png)
![image4](https://user-images.githubusercontent.com/3071035/64005174-6a1bd600-cb42-11e9-9efa-4ca1219b74da.png)

**Comment by wayne-zhang** [comment]
As in the screenshot, images of next tweet overlaps on the previous one.

I found this issue appeared on another website, so I don't think it's tweeter's issue. It happened since I upgraded to the latest version - 18.2 for iOS.

**Comment by farhanpatel** [comment]
Unfortunately this is a bug inside webkit and I don't think we'll be able to fix it.
