### ISSUE TITLE
FXIOS-134 ⁃ Cannot save pdf from preview screen

### ISSUE THREAD

**Issue by csuciu** [mozilla-mobile/firefox-ios#5389]
User Agent: Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36

Steps to reproduce:

1.) Tap a link to a pdf file to open it in preview.
2.) Attempt to save the pdf to the device from the preview screen.

Actual results:

There is no option to save the pdf file to the device at this point. The only option is to close the pdf and tap-and-hold the link to get the download option.

Expected results:

Either a menu option or a tap-and-hold context menu with the option to download the pdf from the preview screen.

The problem with the current way it works is that there are scenarios (the one I ran into was downloading the annual free credit report from Transunion), where once you have opened the pdf in preview, there is no way to close it and tap the link again, because if you close the pdf, the page refreshes to a different page without the link to the pdf. Using the back arrow just reloads the pdf. Tap-and-holding the back button only allows you to either go back to beginning of the process (which loses the pdf), or reload the pdf. The website is deliberately designed to only give you one shot at downloading the pdf, and no second chances. Once the pdf is opened in preview, you've reached a dead end and there is no escape hatch. Not a super common scenario, but not the first time I've run into it, just the first time it ended up being a complete dead end and I lost the pdf as a result.
Additionally, I wouldn't be surprised if the common 'workflow' for the user, when confronted with any pdf link is to tap the link, pdf opens in preview, try to save it and discover you can't, close it, tap-and-hold to download. A download-from-preview feature would cut that in half.

Thanks!

Source: https://bugzilla.mozilla.org/show_bug.cgi?id=1577228

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-134)

**Comment by bryanbell** [comment]
![UNADJUSTEDNONRAW_thumb_3906f](https://user-images.githubusercontent.com/228979/64632430-e36ec080-d3ad-11e9-9bc8-41ecead8ccfe.jpg)

I can get this contextual menu to show, only sometimes.

**Comment by blackTay** [comment]
Any updates on this? Same problem here with the newest iOS version.

**Comment by chinook77** [comment]
> 
> 
> Any updates on this? Same problem here with the newest iOS version.

This is an issue several releases back, I can't export/share a pdf with another app, I get a corrupted file. It's very annoying that Firefox for iOS is very inferior from Safari, It's always buggy. My favorite desktop browser for at least a decade.

**Comment by adam-kral** [comment]
There's a workaround: click three dots next to the url box -> share page with -> Markup. 

And in the Markup window either click Done – You'll be asked where to save the (possibly annotated) pdf – or click the share button -> Save to Files.

**Comment by nasiralamreeki** [comment]
Please improve this experience for end users

**Comment by chinook77** [comment]
Any news about fixing this bug?

**Comment by tylermneher** [comment]
Any word on this feature being addressed? It has been available as a straightforward step in Safari and Chrome iOS for sometime now.

**Comment by nasiralamreeki** [comment]
Come on Firefox IOS! So far behind Android and Desktop almost like an entirely different product.

**Comment by groner** [comment]
I've encountered several web applications where the UI to view/download a PDF isn't a link, so the context menu doesn't work. Being able to save from the PDF view would be really nice.

**Comment by nasiralamreeki** [comment]
Why was this closed when it's not resolved?

**Comment by SimonBasca** [comment]
I've tested the following use case for this issue on the latest main branch bb583f562c6:

1. Send a sample PDF to email address
2. Open the mail address in Firefox iOS
3. Open the mail containing the PDF
4. Try to save it to Files from the share sheet

This scenario is fixed. We can re-check on a new beta and if the issue is still reproducible we can re-open.

**Comment by groner** [comment]
Good to hear a fix is coming.

It's a bit confusing to see the issue closed with no explanation of the resolution. I guess your JIRA has the details, but it doesn't seem to be public. Maybe if @data-sync-user could relay the resolution it would be less confusing for those tracking the issue on github.
