### ISSUE TITLE
[Regression] Removing a pinned top site does not work

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/firefox-ios#5396]
**Steps**
Pin a top site
Long press on that top site
Tap on Context menu option: Remove Pinned Site

**Actual**
The pinned site is not removed. After tapping on Remove Pinned Site the context menu is dismissed but nothing happens

**Expected**
The pinned site is removed from the Top Sites

**Comment by garvankeeley** [comment]
We should revert https://github.com/mozilla-mobile/firefox-ios/commit/36878f95e3dd6935726aff1eda14a1d571dc1521

**Comment by isabelrios** [comment]
This is affecting beta v19.x (16028)

**Comment by garvankeeley** [comment]
https://github.com/mozilla-mobile/firefox-ios/pull/5406

**Comment by isabelrios** [comment]
And this is not reproducible on latest master 2cf1b45864733724730a95b6c65d2167ddd3ba92. Closing the issue
