### ISSUE TITLE
[iPad] Desktop site is not loaded when long pressing on reload button

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/firefox-ios#5399]
This test [`testLongPressReload`](https://github.com/mozilla-mobile/firefox-ios/blob/master/XCUITests/DesktopModeTests.swift#L9)has been working for iPad before but now is failing. Investigating when the failure started.
**Steps**
On iPad launch the test site
Long press on Reload button
Select Request Desktop site

**Actual**
`MOBILE_UA` is shown

**Expected** 
`DESKTOP_UA`is shown

@garvankeeley not sure if this is a regression or we should disable this test too for iPad as the rest of Desktop tests...

**Comment by isabelrios** [comment]
@garvankeeley could it be a regression after commit e2e148a2f178a34c8b5197b4d5a7e502f11748d9? Before it the test was working, check for example [this BB](https://dashboard.buddybuild.com/apps/57bf25c0f096bc01001e21e0/build/5d648092e82c260001b44f5d#tests) run

**Comment by garvankeeley** [comment]
IIUC, this is fixed by https://github.com/mozilla-mobile/firefox-ios/commit/62f5a9a7da9b07d345ef26a7da104279609e6f13
