### ISSUE TITLE
Update branding to be consistent across mobile

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-ios#5413]
### Vision

Branding in iOS is consistent with the rest of mobile, so that users recognize our brand across devices

### Acceptance Criteria

* All iOS updates listed in this doc have been addressed https://docs.google.com/spreadsheets/d/1hbHhihkm8za4diQ_uaTEvNcd2jWeKlSU7X2_pYtnZcM/edit?usp=sharing

**Comment by bwinton** [comment]
I've got half a patch for this already, so I could take it if no-one else wants it. 🙂
