### ISSUE TITLE
Restore content blocking

### ISSUE THREAD

**Issue by acdha** [mozilla-mobile/firefox-ios#5423]
19.0 disabled the content blocking which used to be part of Tracking Protection. After installing the update, ads are everywhere unless you enable strict mode. 

The text says nothing about this difference and it should be an independent setting both because it impacts the web experience so negatively not to have an ad blocker enabled and because strict mode breaks far more sites.

**Comment by farhanpatel** [comment]
Hi @acdha We recommend you turn on Strict mode. Strict mode is also modified in the new version and should break less around the web so you should be able to browse the web with strict mode.

**Comment by acdha** [comment]
When I said that strict mode breaks far more sites, that was because I enabled it in this release and noticed that it breaks many sites which used to work (Twitter, Reddit, etc.).

Right now, there are four choices:

1. Use Firefox and see lots of ads
2. Use Firefox and have common sites broken
3. Use Safari with Focus' content blocker
4. Use Brave

I'd like there to be an option to have Firefox work the way it did until 2 days ago, where most sites work but I don't get deluged with Outbrain crud.

**Comment by holocronweaver** [comment]
+1: This is still an issue in iPadOS 13.1. acdha’s analysis is spot on, please fix! As is ad blocking is broken in Firefox, I am going with option 3 until fixed.

**Comment by acdha** [comment]
This was separately reported and fixed in the later issue #5430 which was _not_ closed without doing analysis.
