### ISSUE TITLE
Old logo is shown in first Onboarding slide

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/firefox-ios#5434]
The new logo is shown when installing the app but it has not been changed in the onboarding slide. Not sure if that has to happen already or in the future but I guess that both logos should match...

New logo:
![Screenshot 2019-09-11 at 12 27 27](https://user-images.githubusercontent.com/1897507/64689955-a1b64680-d48f-11e9-9f9e-953b763e0eb4.png)
Onboarding:
![Screenshot 2019-09-11 at 09 41 27](https://user-images.githubusercontent.com/1897507/64690032-beeb1500-d48f-11e9-83e5-92572862f00e.png)

**Comment by garvankeeley** [comment]
@bwinton could you take a look? I can find the asset for this that needs updating

**Comment by garvankeeley** [comment]
https://github.com/mozilla-mobile/firefox-ios/tree/master/Client/Frontend/Intro/Intro.xcassets/tour-Welcome.imageset

**Comment by bwinton** [comment]
I asked Stephen for some new images, and will make a PR when I get them. 🙂
