### ISSUE TITLE
Broken build due to broken hawk dependency

### ISSUE THREAD

**Issue by psporysz** [mozilla-mobile/firefox-ios#5441]
During `./bootstrap.sh`:

```
    Updating git repository `https://github.com/eoger/rust-hawk`
error: failed to load source for a dependency on `hawk`

Caused by:
  Unable to update https://github.com/eoger/rust-hawk?branch=use-openssl#721c7d72

Caused by:
  revspec '721c7d72fb3c34d855c8563ca453e77f8e1ee9a9' not found; class=Reference (4); code=NotFound (-3)
```

I think *application-servics* has to be updated in `Cartfile`. Not sure which version is best at the moment.

**Comment by psporysz** [comment]
I've installed the Xcode 11 GM and upgraded *application-services* to `0.38.2`. The `bootstrap.sh` has finished successfully but during build in Xcode i've got:
```
[snap]/firefox-ios/Storage/Rust/RustLogins.swift:8:19: No such module 'MozillaAppServices'
```

I looked at `Carthage/Build/iOS` and there is no directory for *MozillaAppServices*.

Another problem was renamed `Carthage/Build/iOS/Leanplum.framework` to `Carthage/Build/iOS/LeanplumSDK.framework`. When i am building both dependencies off the carthcage they are producing right artifacts and when i am pointing to it as binaries hosted localy in *Cartfile* i can proceed.

**Comment by psporysz** [comment]
I've upgraded KIF dependency up to `3.7.8` (due to compilation problems on new Swift) and did the following in bootstrap.sh:
```
# XXX fix wrong location of MozillaAppServices and build it from scratch
(cd ./Carthage/Checkouts/application-services; ./build-carthage.sh)
ln -sf $(pwd)/Carthage/Build/iOS/Static/MozillaAppServices.framework Carthage/Build/iOS/

# XXX revert missing swift-protobuf, otherwise it fails during linking
carthage update $CARTHAGE_VERBOSE --platform ios --cache-builds swift-protobuf

# XXX fix wrong build on Leanplum
(cd ./Carthage/Checkouts/Leanplum-iOS-SDK; ./Tools/build.sh)
cp -r $(pwd)/Carthage/Checkouts/Leanplum-iOS-SDK/Release/Leanplum.framework Carthage/Build/iOS/
```

It let me build & run it successfully.

**Comment by garvankeeley** [comment]
The build should be working now, please re-open if not
