### ISSUE TITLE
The 3rd party search engine icon is not displayed when first tapping on the search bar on iPads

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#5442]
From bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1320917

Build: 6.0b5
Device: iPad Air 2
iOS: 10.1.1

Steps to reproduce:
1. Go to youtube.com
2. Tap on the search bar (the Add 3rd party search engine icon is not displayed)
3. Close keyboard
4. Tap on the search bar (Add 3rd party search engine icon is displayed)

Actual results:
- The Add 3rd party search engine icon is not displayed. The icon is displayed only after closing the keyboard and tapping on the search bar again.

Expected results:
- The icon should be displayed when first tapping the search bar.

See a video of the issue: https://www.youtube.com/watch?v=7ZnPicEWGXk

**Comment by farhanpatel** [comment]
We should remove this feature as its a hack that never works reliably
