### ISSUE TITLE
Use globe icon for default favicon

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla-mobile/firefox-ios#5450]
CURRENT (cropped screen of all tabs)
![IMAGE 2019-09-13 14:59:13](https://user-images.githubusercontent.com/68213/64887637-0e1f7a00-d637-11e9-80d8-555c353bf9bc.jpg)

PROPOSED
https://design.firefox.com/icons/viewer/#globe

**Comment by nishant2718** [comment]
@ryanfeeley Would you like to use that globe icon for dark mode as well? Also, the globe dimensions I've used are 20x20, 40x40, 60x60 to match the previous image's dimensions. 

Please see the following PR:
https://github.com/mozilla-mobile/firefox-ios/pull/6088

**Comment by csuciu** [comment]
Verified as fixed on master 8350f11e.
