### ISSUE TITLE
Google search in URL bar breaks after requesting for desktop site

### ISSUE THREAD

**Issue by csuciu** [mozilla-mobile/firefox-ios#5454]
v19.0 (16042)
iPad Air 3 (12.2)

1. Make sure "Google" is the default search engine.
2. Visit a site.
3. Long press on the "Reload" button and select "Request Desktop Site".
4. Type something (e.g. cat) in the URL bar and press "Go".

Expected: Google search results page is displayed.

Actual: Google home page is displayed.  

Note: Wasn't able to reproduce with other search engines.

**Comment by garvankeeley** [comment]
This will be difficult to fix, but regardless this feature will change with iOS 13 compatibility and the bug may no longer happen.

**Comment by athomasmoz** [comment]
Now that iOS 13 updates are out, is this still an issue?

**Comment by SimonBasca** [comment]
Reproduced on iPhone Xr (13.2) on build 19.0 (16042). 

The issue is no longer reproducible after re-testing on  iPhone Xr (13.2) on build 20.0 (16437).
