### ISSUE TITLE
Desktop mode site setting leaks to private browsing mode

### ISSUE THREAD

**Issue by ChaiTRex** [mozilla-mobile/firefox-ios#5458]
If, outside of private browsing mode, you request a site in desktop mode, that will be remembered and the site will be requested in desktop mode from then on.

This behavior happens even when switching to private browsing mode, which opens the user up to fingerprinting in private browsing mode, as their personalized settings from outside private browsing mode are incorrectly transmitted to websites in private browsing mode.

---

Firefox for iOS version: 19.0 (16042)
iOS version: 12.4.1

**Comment by farhanpatel** [comment]
Desktop mode uses a generic user agent. I don't think this would open you up to any more fingerprinting.

**Comment by ChaiTRex** [comment]
This does open people up to more fingerprinting. Sites have third party components, each with their own domain names for resources, each of which can now provide a different user agent string. Specific combinations of user agent strings on first party and third party domains narrows down users.

**Comment by ChaiTRex** [comment]
For example, Google, who tracks people for advertising purposes, has lots of domains people might separately set desktop or mobile mode for (youtube.com, google.com, etc), can now join that information together on any of its sites in private browsing sessions on Firefox for iOS, narrowing down users.

Perhaps a user has a unique signature in that sense. If so, they'll be uniquely identifiable.

**Comment by ChaiTRex** [comment]
This also has implications in detecting private browsing mode. If I connect to a site with two domains (one for the site, one for JavaScript and such) with separate user agent strings, the site knows two things: I've been there before and I'm on mobile. If I have no cookies set, it's very likely I'm in private browsing mode.
