### ISSUE TITLE
Issues rendering alternativeto.net (react part)

### ISSUE THREAD

**Issue by olaj** [mozilla-mobile/firefox-ios#5468]
Not sure i should be posting these kinds of issues here but we (the owners of alternativeto.net) noticed in the Brave browser that our new parts that are built with Next.js/React doesn't render at all on Firefox for iOS or Brave for iOS.

Go to https://alternativeto.net/platform/firefox/ for example and well you will only see a white page and it get caught up in some kind of loop. Seems to work fine on all other browsers mobile and desktop so there is something fishy going on.

I have no idea how to debug this on iOS, how do i go about debugging these kind of issues with Firefox for iOS? And can anyone here maybe help me to figure out what is going on?

**Comment by garvankeeley** [comment]
Does this happen with Tracking Protection turned off (long press the reload button to access that option)?

**Comment by olaj** [comment]
Yes, it seems so. 

Can also mention that we noticed this ourselves with the latest version of Brave / FF. We haven’t got any complaints about it before but we haven’t tested it ourselves either as far as I know.

**Comment by olaj** [comment]
Still have no idea here. Is there anyway to debug rendering issues in iOS browsers?

**Comment by farhanpatel** [comment]
You can try Safari on iOS. if you open Safari on your mac you can debug Safari iOS remotely

**Comment by farhanpatel** [comment]
Please reopen the bug if its still an issue only in FIrefox/Brave

**Comment by olaj** [comment]
The issue still persist. I do not have a Mac and the page works fine in Safari / Chrome / Edge.

**Comment by olaj** [comment]
Ok, i think i found the issue.

It seems to be a a history.pushState that was throwing "DataCloneError: The object can not be cloned". I don't really understand why though.

`      history.pushState(null, null, url);`

And the URL is an object containing this.

https://i.imgur.com/ljTY0yS.png

It's not my code so i'm not sure exactly what it was doing there and so on but it's what caused it. And it works fine on most browsers so i'm not sure it's a bug or not. Let me know if you want more detailed data.
