### ISSUE TITLE
Library panels: table view cells/headers borders thickness and color are inconsistent

### ISSUE THREAD

**Issue by clarknt** [mozilla-mobile/firefox-ios#5471]
# Thickness
Like it was the case with settings tables (issue #4704), some table cells and headers borders are too large or missing.

## Examples
![editbookmark](https://user-images.githubusercontent.com/24315769/65159043-78eaff80-da01-11e9-9e66-f62c045bec15.png)
![downloads](https://user-images.githubusercontent.com/24315769/65159055-7dafb380-da01-11e9-8326-bfb54f269c8d.png)

# Colors
Some of the headers borders colors are too bright in dark mode.

### Colors ok
Bookmarks headers borders colors are the same as Settings table, i.e. identical to cell borders colors. Apple's own Settings view in iOS 13 dark mode has header borders colors identical to cell borders as well.

![bookmarks](https://user-images.githubusercontent.com/24315769/65159629-66bd9100-da02-11e9-82ea-fcf7c2e969b6.png)

### Colors too bright
History header borders are brighter than cell borders.

![history](https://user-images.githubusercontent.com/24315769/65159673-73da8000-da02-11e9-8901-7d1249381f40.png)

**Comment by clarknt** [comment]
Note: if this makes it to "planned", I already have the code ready to fix borders thickness and missing borders. Can add the colors fix and submit the pull request.

**Comment by csuciu** [comment]
Verified as fixed on master 8350f11e3d.
