### ISSUE TITLE
Xcode 11: PhotonActionSheet tests are failing

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/firefox-ios#5477]
The tests in this [PhotonActionSheet test suite](https://github.com/mozilla-mobile/firefox-ios/blob/master/XCUITests/PhotonActionSheetTest.swift) are failing. Looks like the UI and also some buttons have changed and so we need to update the tests accordingly

**Comment by sindhugudivada** [comment]
@isabelrios Is some one already working on this. I would love to contribute.

**Comment by isabelrios** [comment]
Hey @sindhugudivada! so far is unassigned so you can take it! Happy you can contribute with this! :)

**Comment by sindhugudivada** [comment]
@isabelrios Do you know about this. New onboarding screens #5531 .  Is some one also already on it. I would love to build them.

**Comment by isabelrios** [comment]
@sindhugudivada I'm not sure but if it is unassigned, you can assign it to yourself so that we know there is work going on there. We usually (we try to but sometimes may forget) assign issues is somebody is working on it, if no one is assigned then it is free to take :)

**Comment by sindhugudivada** [comment]
@isabelrios  How to assign it to myself.

**Comment by isabelrios** [comment]
I assigned it to you (by going to Assignes, on the right top options). If you can't finally work on this, please remove your assignation. Thanks :) and feel free to contact me to ask questions/doubts about these tests.

**Comment by sindhugudivada** [comment]
@isabelrios  Sure, Thanks. Is there an email that I can reach out to you over.

**Comment by isabelrios** [comment]
> @isabelrios Sure, Thanks. Is there an email that I can reach out to you over.

yes, irios@mozilla.com. You may be interested in looking at the doc related to tests in the wiki:
-https://github.com/mozilla-mobile/firefox-ios/wiki/FxScreenGraph-and-XCUITest
-https://github.com/mozilla-mobile/firefox-ios/wiki/Writing-a-first-XCUI-test-from-the-scratch

**Comment by sindhugudivada** [comment]
@isabelrios  I have been able to set-up dev environment. I ran the PhotonActionSheetTest in XCode. It works successfully. I didn't notice any failure. Perhaps the failed tests are commented?  Also if you don't mind, can you show me what is PhotonAction Sheet in the UI of the browser. Thanks in advance.

**Comment by isabelrios** [comment]
Hi @sindhugudivada, happy to hear that the environment is working for you. 
Currently the photonActionSheet tests affected are commented out, see for example: https://github.com/mozilla-mobile/firefox-ios/blob/master/XCUITests/PhotonActionSheetTest.swift#L34

The UI that is failing is this one:
![Screenshot 2019-11-04 at 10 16 28](https://user-images.githubusercontent.com/1897507/68109986-38314200-feec-11e9-8d88-ef3b6f91d4e4.png)

You go there by tapping on the three dot menu while being in a website (PageAction Menu) and then selecting Share Page With option.

Hope that helps!

**Comment by isabelrios** [comment]
This is what I see when trying to get that screen (or record a test from it):
```
test encountered an error (Lost connection to testmanagerd)
```

Fyi, @garvankeeley that's the error we see, have you seen that before? any idea about the issue? Thanks!

**Comment by garvankeeley** [comment]
Sorry, no idea on that one

**Comment by isabelrios** [comment]
Looks like with the new Xcode 11.3.1 and iOS 13.3, we can access again and check the Photon Action Sheet menu. 

There is still one button that is not accessible but that one is only used in one tests. It will remain disabled but all the other tests can be enabled again. PR coming
