### ISSUE TITLE
Canvas unresponsive in browser in iOS 13.1 beta

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#5485]
Logged via: https://bugzilla.mozilla.org/show_bug.cgi?id=1581140

User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36

Steps to reproduce:

    Open the included reproduction case HTML file with an iOS 13.1 beta device
    Observe circles drawing in canvas every half a second
    Click the button to open a new website and return back to the page with canvas
    Observe the canvas not updating anymore
    Make an interaction to the page, for example scrolling, and the canvas will be updated while the interaction is active - all the circles that should be drawn while the canvas was unresponsive will be drawn at once

Testing the iOS 13.1 beta we encountered an unexpected behavior of the canvas element after opening the new window with window.location.href.

In the attached reproduction case HTML canvas is updated on a regular interval with setInterval function drawing a circle every half second. If you click on a button to open a new window and navigate back to the screen with canvas, circle drawing does not update anymore, showing that canvas rendering is broken.

If a user interaction happens, for example user scrolls up or down, then the canvas will update while the interaction is active, drawing all circles that should have been drawn while there was no interaction. This indicates that setInterval was still running in the background, which we also verified with logging. If the page is refreshed canvas still remains unresponsive and entire tab needs to be closed to restore the initial behaviour.

We were able to reproduce the issue in Firefox browser on all 3 of our iOS 13.1 Beta test devices:

    iPhone X, iOS 13.1 Public Beta 3
    iPhone 6S, iOS 13.1 Public Beta 1
    iPad 6, iPadOS 13.1 Public Beta 2

The video and code snippet with which you can easily reproduce the behaviour are included.

Actual results:

HTML canvas became unresponsive.

Expected results:

HTML canvas should not break after opening a new page with window.location.href.

**Comment by garvankeeley** [comment]
We should compare against Chrome and Safari. It would be surprising if the bug was us only.

**Comment by sirceljm-celtra** [comment]
This bug happens on all browsers on iOS13: Safari, Chrome and Firefox

**Comment by garvankeeley** [comment]
We'll close this as it isn't something we can fix on our end, thanks for the report though.
