### ISSUE TITLE
Allow deeplink handler to pass UTMs through the FxA signup flow

### ISSUE THREAD

**Issue by lwa-moz** [mozilla-mobile/firefox-ios#5492]
As a Marketer, I would like to pass advertising campaign data at time of Firefox Account signup in order to attribute marketing campaign success appropriately. Currently the FxA team accepts standard UTM field data, and associates it with users in their instance of Amplitude. We would like to append all mobile campaign deeplinks with UTM parameters.

The Mobile Marketing team has determined that UTMs are not being passed correctly through the "firefox://sign-in" deeplink for new FxA users. These parameters are being passed correctly for existing users on sign-in.

UTM parameters we would like to include are:

    utm_source
    utm_campaign
    utm_adgroup
    utm_ad
    adid

Here is a link to the Marketing QA documentation for reference: https://docs.google.com/spreadsheets/d/1fP5sw50cJJRplFgFAx8a0npRI5xzuu1i_RFwr1A7Ms8/edit#gid=975962131

**Comment by athomasmoz** [comment]
Please loop @lwa-moz in to help QA

**Comment by garvankeeley** [comment]
We  are  preserving `utm_` params according to the code: https://github.com/mozilla-mobile/firefox-ios/blob/master/Client/Frontend/Settings/FxAContentViewController.swift#L231

**Comment by lwa-moz** [comment]
@garvankeeley are we able to test this in production?

The test URL we had been using is: firefox://fxa-signin?signin=true&utm_source=push-notification&utm_medium=push-notification&utm_campaign=pn-sync-now&utm_content=baseline2

I wonder if there's an issue with the formatting of the URL, or a missing parameter that is required.

**Comment by garvankeeley** [comment]
That URL looks good to me, I was hoping you would know how to test this in prod because I am not sure how

**Comment by athomasmoz** [comment]
Investigation completed. New ticket logged to track issue https://bugzilla.mozilla.org/show_bug.cgi?id=1588630 @garvankeeley do you know offhand if this is FxA or us? I want to get the bug into the right project

**Comment by garvankeeley** [comment]
Everything looked ok on the app side, so I'll say it is FxA

**Comment by athomasmoz** [comment]
Thanks, closing this ticket and I will assign the new one to the FxA project
