### ISSUE TITLE
Text selection broken sometimes on iPadOS 13.1

### ISSUE THREAD

**Issue by ChaiTRex** [mozilla-mobile/firefox-ios#5494]
As expected, when you go to a CNN article and tap-and-hold on a word in the article, that word is selected. The same happens if you tap-and-hold on a word in this issue description. This works on iOS 12.4.1 and earlier and on iPadOS 13.1.

However, it has broken in Firefox on some sites once I upgraded to iPadOS 13.1:

* GitHub comment editing fields
* Ars Technica article text
* Google search term editing using the entry field on a mobile-version search results page

---

iOS version: iPadOS 13.1
Firefox version: 19.0 (16042)

**Comment by garvankeeley** [comment]
fixed by https://github.com/mozilla-mobile/firefox-ios/pull/5437
