### ISSUE TITLE
[UITests] App hangs on first onboarding screen (Xcode 11, iOS 13)

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/firefox-ios#5501]
The app is launched but it shows the screen incorrectly.
![Screenshot 2019-09-26 at 10 10 49](https://user-images.githubusercontent.com/1897507/65670941-9f82e900-e046-11e9-9318-9af8ad0b6691.png)

You need to scroll a little bit up to see the full screen correctly. The test hangs on that screen and after some minutes an error is shown.

[EarlGery issue.pdf](https://github.com/mozilla-mobile/firefox-ios/files/3656668/EarlGery.issue.pdf)

Looks like the [same issue](https://github.com/google/EarlGrey/issues/999) has been reported to EarlGrey so we will comment on it and follow how it evolves.

**Comment by dnarcese** [comment]
This should be fixed now that #5472 landed.
