### ISSUE TITLE
[iOS 13] After tapping on Start Browsing blank screen is shown

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/firefox-ios#5504]
The simulator shows blank screen after finishing the onboarding. Closing and opening the app fixes the issue. 
There may be an issue on our side/iOS 13 so that this unexpected behavior happens... Opening this issue to track that.

This may be the same that is affecting the UI Tests (see issue #5501)

**Comment by garvankeeley** [comment]
Duplicate of #5472
