### ISSUE TITLE
[XCUITests] Add `Everything` option to Clear Recent History

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/firefox-ios#5508]
We should add this option to the tests covering the Clear Recent History feature.
https://github.com/mozilla-mobile/firefox-ios/blob/master/XCUITests/HistoryTests.swift#L238

Or at least we should try to check that all the expected options are shown

**Comment by dfperry5** [comment]
Hi guys,

I'm pretty new to the open source world - though I've done a little. Is this an appropriate issue for a newbie like myself to take a shot at?

**Comment by dfperry5** [comment]
See above [commit](https://github.com/dfperry5/firefox-ios/commit/69a076052fa8d883193ff502a7dc6eca32e84513) - gave it a shot - please let me know if its OK to open PR :)

**Comment by isabelrios** [comment]
@dfperry5 thank you for that PR!  Let me take a look and get back to you! :) 
In the meantime, I will assign this issue to you so that there is not overlap with your work

**Comment by isabelrios** [comment]
@dfperry5 great job on that PR!! I only left a few nit comments. Please feel free to open that PR here so that it can be merged once those nits are addressed.
Thank you very much!

**Comment by dfperry5** [comment]
@isabelrios  - opened [PR -#5899 ](https://github.com/mozilla-mobile/firefox-ios/pull/5899)
