### ISSUE TITLE
iOS 13 Dark Theme Alignment

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-ios#5512]
Vision:
As an iOS user, I want Firefox's theme to be dark or light depending on what my system setting is, so that I can control the theme across apps in one place

Summary:
This story is to add the option for users to have dark/light theme match the system setting. Details in [PRD](https://docs.google.com/document/d/1ZB7JX4GkI6RoNE0OxKMsSeWRJuwdjr4eqehuT1jfjxc/edit#)

Success Metrics:
Increased dark theme usages due to easier discoverability of the feature

**Comment by athomasmoz** [comment]
Closing as duplicate #5122

**Comment by iCroupsTW** [comment]
+886975063345
jimilin78@gmail.com
