### ISSUE TITLE
The Firefox Monitor page opens zoomed in when switching orientation while going back and forward

### ISSUE THREAD

**Issue by csuciu** [mozilla-mobile/firefox-ios#5517]
v20.0 (16212)
iPhone XS Max 12.4

1. Visit https://monitor-v2.herokuapp.com/.
2. Open Bento menu.
      => the menu is displayed in full screen in portrait mode.
3. With the menu open, turn the device in landscape mode.
4. Press back to go to the previous page.
5. Switch to portrait.
6. Press forward to go to the the Monitor page.

Expected: The Bento menu is displayed in portrait mode (full screen), at least that's what happens in Safari.

Actual: The Monitor page opens zoomed in and the landscape version of the menu is displayed.

**Comment by garvankeeley** [comment]
I don't think we can fix this, it shouldn't be anything we have control over.
