### ISSUE TITLE
Build on master branch fails because of a compiler error

### ISSUE THREAD

**Issue by klymenkoo** [mozilla-mobile/firefox-ios#5525]
I've just pulled updates from master, and I tried to build the project, but it doesn't compile. There was an error introduced in #5436 that compiler complains about:
<img width="900" alt="Screen Shot 2019-10-01 at 10 24 55 PM" src="https://user-images.githubusercontent.com/26641473/66013742-51cd0d00-e49a-11e9-8b98-287657467b78.png">

https://github.com/mozilla-mobile/firefox-ios/blob/7942981ad1f2100d8a6bfbb62ad77184e7e3fe06/Client/Frontend/Browser/BrowserViewController/BrowserViewController%2BWebViewDelegates.swift#L103-L105

I'll submit a patch in few minutes.

**Comment by garvankeeley** [comment]
fixed https://github.com/mozilla-mobile/firefox-ios/commit/f6a9a2aeffcfa1abc5d0f5ca26a9e2dc43caae80
