### ISSUE TITLE
[UITests] Update EarlGrey

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/firefox-ios#5528]
We need to update EarlGrey both in Cartfile and Cartfile resolved. It has to point to master so that UI Tests run, otherwise EarlGrey fails to tap on any element and so all tests are failing.

**Comment by isabelrios** [comment]
Looks like the issue is not only that we need to update to the latest version (2) of Early Grey, there are some problems with that version. ([BB logs](https://dashboard.buddybuild.com/apps/57bf25c0f096bc01001e21e0/build/5d95cc1e4152a50001e103a3#tests) for more info)

When running for example this [Authentication test](https://github.com/mozilla-mobile/firefox-ios/blob/master/UITests/AuthenticationTests.swift#L27), it fails because EarlyGrey finds multiple matches for our `url` field in this line:
`EarlGrey.selectElement(with: grey_accessibilityID("url")).perform(grey_tap())`

If I change that and we use KIF instead, then the test works (need to change that for `url` and `address` elements:
`tester().tapView(withAccessibilityIdentifier: "url")`

This is going to require a lot of changes, since most of the tests need to start by typing something in the url/address field.

Before starting to do so, I would like to know your opinion on this. @npark-mozilla have you faced similar issues before with bigger iOS/Xcode updates? Should I just change and use KIF instead? 

@garvankeeley wondering if there is something on how the views are loaded in the latest version causing these multiple elements found for same id (although only Early Grey seems to be affected) that could cause other issues in the app. Does not look like that but wanted to double check.

Thanks!

**Comment by npark-mozilla** [comment]
Hmm, did our UI layout changed so now it has multiple elements with "url" accessibility ID?  we could find another condition that is unique to the element that we're looking for, and use `grey_allOfMatchers()`   My memory is vague, but I think we can print the DOM tree and see which ones have the `url` access. ID?

**Comment by isabelrios** [comment]
> Hmm, did our UI layout changed so now it has multiple elements with "url" accessibility ID? 

No that I'm aware of...

> we could find another condition that is unique to the element that we're looking for, and use `grey_allOfMatchers()` My memory is vague, but I think we can print the DOM tree and see which ones have the `url` access. ID?

In the past I have faced similar issues with Early Grey fixed using KIF, but I will try to use another condition to keep using EarlGrey.

Thanks for your feedback

**Comment by isabelrios** [comment]
As discussed offline, the solution found is to add that "url" is a textField:
```
EarlGrey.selectElement(with: grey_accessibilityID("url"))
                .inRoot(grey_kindOfClass(UITextField.self))
                .perform(grey_tap())
```
With that the tests work as expected...
