### ISSUE TITLE
[Unit tests] There are unit tests failures on ClientTest suite

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/firefox-ios#5530]
These are the failing tests on master:
-testDesktopUserAgent()
-testUserAgent()

See [BB logs](https://dashboard.buddybuild.com/apps/57bf25c0f096bc01001e21e0/build/5d949cb715b132000173d6e0#tests)

**Comment by akshay1992kalbhor** [comment]
The changes made to Client/Shared/UserAgent.swift in Fix #5476 may be causing the two tests to fail. Specifically the strings returned by the two methods desktopUserAgent and mobileUserAgent don't match the regular expressions in the two failing tests.
