### ISSUE TITLE
New onboarding screens

### ISSUE THREAD

**Issue by garvankeeley** [mozilla-mobile/firefox-ios#5531]
![image (1)](https://user-images.githubusercontent.com/5495083/66066515-ab275180-e517-11e9-9b45-3bece912263f.png)

**Comment by sindhugudivada** [comment]
@garvankeeley Is some one already working on these screens. I would love to contribute.

**Comment by garvankeeley** [comment]
Hi yes I am working on this

**Comment by athomasmoz** [comment]
@garvankeeley should I close #5414 in favour of this one? Note that the acceptance criteria for the original ticket includes tracking success of this by adding click counts for the buttons

**Comment by garvankeeley** [comment]
Closing as dupe of https://github.com/mozilla-mobile/firefox-ios/issues/5414
