### ISSUE TITLE
URL's with square brackets ([ ]) are not recognised as URL's

### ISSUE THREAD

**Issue by csuciu** [mozilla-mobile/firefox-ios#5538]
Steps to reproduce:

We spotted an issue with an AJAX call not returning anything. We took the AJAX URL and entered it straight into the address bar and it didn't seem to recognise it as a URL and was trying to do a Google search. When we took out the square brackets from the GET parameters it worked.

For example:
https://URL?get_per[]=17

Actual results:
Tried to do a Google search. Didn't seem to recognize it as a URL.

Expected results:
Should have returned the URL

filed via https://bugzilla.mozilla.org/show_bug.cgi?id=1585328

Note: Safari handles this correctly.

**Comment by marchiore** [comment]
Sent a PR for this.

https://github.com/mozilla-mobile/firefox-ios/pull/5572

**Comment by garvankeeley** [comment]
closed by #5572
