### ISSUE TITLE
Reader mode invisible in IOS with FF dark mode enabled

### ISSUE THREAD

**Issue by SherbetS44105** [mozilla-mobile/firefox-ios#5543]
https://imgur.com/a/qNr3TfL

by the way reader mode still works but because of the colour choice it is impossible to see in dark mode.

**Comment by rockarts** [comment]
Could you provide a bit more detail? This is what I see with night mode enabled and dark mode enabled in the latest build. I've deactivated reader mode. 

![image](https://user-images.githubusercontent.com/246441/66704631-ff31f300-ecda-11e9-9644-eac90bc32fc8.png)

**Comment by SherbetS44105** [comment]
On device one: iphone 6 plus model no NGAW2LL/A, IOS 12.4.2, Firefox version 19.1 (16203)
On device two: ipad 6th gen model no MR7J2LL/A, IOS 12.4, Firefox version 18.1 (15719)
Hope it helps!

**Comment by athomasmoz** [comment]
@SimonBasca can you try reproducing this?

**Comment by dnarcese** [comment]
@SimonBasca any luck with reproducing? I haven't been able to.

**Comment by SherbetS44105** [comment]
UPDATE: I also updated firefox to version 20 on both devices, the result was the same. After my friend tested it on his device on firefox IOS version 19 and 20, both displayed the reader mode icon correctly (their device was updated to IOS 13), this leads me to the conlcusion that this is caused by some issue pertaining to IOS 12 and not firefox itself.

**Comment by SimonBasca** [comment]
@dnarcese I was unable to reproduce this issue. Tested on iOS 12.4 and iOS 13.2 on latest master 9068934714 and on 20.1(16561).
