### ISSUE TITLE
[Regression] SAML2 authentication fails with "Invalid HTTP method (GET)"

### ISSUE THREAD

**Issue by csuciu** [mozilla-mobile/firefox-ios#5544]
Filed via https://bugzilla.mozilla.org/show_bug.cgi?id=1586333

Steps to reproduce:

I'm using IPadOS 13.1.2.
With Firefox-IOS 19.0 I was able to authenticate using Shibboleth-SSO (via SAML2).
Yesterday I've updated to Firefox-IOS 19.1.

Actual results:

With Firefox-IOS 19.1 authentication using Shibboleh-SSO (via SAML2) does not longer work. The IdP-login succeeds, but the assertion consumer service fails.

The SP logs this:
... "GET /Shibboleth.sso/SAML2/POST HTTP/1.1" 500 2130 "-" ...

The Browser displays:
opensaml::BindingException as (https://XXX/Shibboleth.sso/SAML/POST)
Invalid HTTP method (GET)

Expected results:

The assertion consumer service uses "POST" only.

So this should be logged if the assertion consumer service succeeds:
.... "POST /Shibboleth.sso/SAML2/POST HTTP/1.1" 302 913 "https://YYY/idp/profile/SAML2/Redirect/SSO?SAMLRequest=.....

Firefox-IOS 19.1 seems to rewrite the HTTP method: "POST" is replaced by "GET"!?

I've tested newest versions of "Safari" and "Firefox Klar" on IOS. Both are able to use SSO via SAML2.

**Comment by csuciu** [comment]
I’ve done some more testing and it turns out, that the error Is related to “Desktop-Webseite anfordern“.

If “Desktop-Webseite anfordern” is active on the IdPs site, the assertion request seems to be rewritten from POST to GET.

So a valid workaround is to switch to “Mobile Webseite anfordern” and to retry the authentication.

**Comment by garvankeeley** [comment]
This is  in the  webview component, so unfortunately is a wontfix (as we can't fix)
