### ISSUE TITLE
Widget not utilizing iOS 13 dark mode

### ISSUE THREAD

**Issue by csuciu** [mozilla-mobile/firefox-ios#5551]
Steps to reproduce:

Open Today Widget or long press on the Firefox home icon

Actual results:

Widget does not change colour to reflect the system-wide dark mode in iOS 13. It remains grey when it should be black.

Expected results:

Widget should change colour to black to match other dark-mode widgets.

![signal-2019-10-03-110449](https://user-images.githubusercontent.com/1866605/66377970-3e9acf80-e9bb-11e9-81c0-a0e1acb30bc5.png)

Filed via:  https://bugzilla.mozilla.org/show_bug.cgi?id=1586000.

**Comment by athomasmoz** [comment]
PR from contributor - thank you!
