### ISSUE TITLE
 Attempting to sharea downloaded file brings up empty share sheet and makes browser janky

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#5558]
Logged via : https://bugzilla.mozilla.org/show_bug.cgi?id=1584247

Attempting to share a PDF stored in the downloads section fails to populate the share sheet on iOS 13.1 and subsequently makes the browser very janky.

Video:
https://bugzilla.mozilla.org/attachment.cgi?id=9095548

**Comment by athomasmoz** [comment]
Let's timebox this one to 3 story points, if it's much larger,it may not be worth fixing

**Comment by garvankeeley** [comment]
I can't repro this, I am trying on 13.1 simulator and the share sheet is showing ok
<img width="1022" alt="image" src="https://user-images.githubusercontent.com/5495083/67780304-4db1f200-fa3c-11e9-8556-448f3871f62a.png">

**Comment by mgaudet** [comment]
I am on Version 20.0 (16437), iOS 13.1.3 on iPhone XS, and can still reproduce.

**Comment by garvankeeley** [comment]
Thanks, I see it happens only on actual devices. Odd.
