### ISSUE TITLE
[XCUITests] Drag&Drop toptabs tests fail - safari is launched

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/firefox-ios#5561]
With the recent update to iOS13 when long pressing on a toptab to activate the Drag&Drop it is very likely that Safari is launched. 

Please see this video:
https://youtu.be/XaIwZEQ1nV0

So all tests related to this feature are currently broken

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2175)

**Comment by isabelrios** [comment]
After running the tests several times looks like only this test is affected:
-testDragDropToInvalidArea

It longs tap on a top tab and tries to drop it on the tabs button (or the new tab or the private tab, I have tried all buttons in the top bar) but safari is launched when trying to drop the element close to the end of its window.

That test will be disabled until that behavior is clear and so the tests will be modified/removed accordingly

**Comment by athomasmoz** [comment]
The tests are failing due to a bug - logged as #5649
