### ISSUE TITLE
Telemetry for "dismissed-onboarding" showing optional value

### ISSUE THREAD

**Issue by garvankeeley** [mozilla-mobile/firefox-ios#5564]
```{"f":[{"v":"73704"},{"v":"action"},{"v":"press"},{"v":"dismissed-onboarding"},{"v":null},{"v":[{"v":{"f":[{"v":"slide-num"},{"v":"Optional(1)"}]}}]}]}```

https://sql.telemetry.mozilla.org/queries/65228/source

**Comment by athomasmoz** [comment]
Uplifted to v20
