### ISSUE TITLE
Add Tracking for Firefox Theme Setting

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-ios#5569]
**Vision**

As a Product Manager, I know how often dark theme is used, so that I can prioritize fixes related to the feature

**Acceptance Criteria**

* In Amplitude, I can chart how many unique users use dark theme
* In Amplitude, I can chart how many users choose to set their theme independent of the system setting (set Use System Light/Dark Mode to off)
* Data collection has been reviewed by data stewards
* Tracking respects user setting to allow tracking

**Notes**

* To get the data into Amplitude, we need to add it in Telemetry and then ask the data team to help get it into Amplitude [(create](https://bugzilla.mozilla.org/show_bug.cgi?id=1584381))

**Comment by dnarcese** [comment]
@athomasmoz For
> In Amplitude, I can chart how many unique users use dark theme

By dark theme, do you mean when the system theme setting is ON, and their system theme is set to dark? Or do you also/just want to know when the user manually sets the theme to dark?

**Comment by athomasmoz** [comment]
Thanks for reaching out. 
For the first bullet, it would include users with FF theme set to automatic and their system theme is dark and users who manually set FF theme to dark

To give some more details, the two questions I'm looking to answer are:
* What percent of overall users use dark theme? (AC 1)This information is useful for prioritizing any bugs specific to dark theme
* What percent of users have their theme set to "use system theme"? (AC 2) We may be able to get rid of the manual option if users stick with the "use system theme" option
