### ISSUE TITLE
Land Strings for Matching Theme to System Theme for Localization

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-ios#5570]
**Vision**

As a user with language set to something other than English, I want to see & understand the options for setting my Firefox theme

**Acceptance Criteria**

* Strings for the [UI updates](https://mozilla.invisionapp.com/share/UPU3KD1SBDX#/screens)  have been landed and are ready for localization
* L10n has been notified

**Comment by athomasmoz** [comment]
Thanks @dnarcese ! Did you already reach out to l10n or want me to?

**Comment by dnarcese** [comment]
@athomasmoz Once we do the string export, we will let l10n know. Normally the export will be done a few weeks before the release.

**Comment by athomasmoz** [comment]
Awesome, thanks!
