### ISSUE TITLE
Build-time error

### ISSUE THREAD

**Issue by elemanhillary** [mozilla-mobile/firefox-ios#5574]
when building Fennec in xcode it gives build-time errors, i tried following [#3559](https://github.com/mozilla-mobile/firefox-ios/issues/3559) issue but it failed to work out
Here are errors screenshot below:
<img width="1397" alt="Screen Shot 2019-10-09 at 14 15 42" src="https://user-images.githubusercontent.com/14273401/66480596-50ee3980-ea9f-11e9-9f90-060f047c46ea.png">

**Comment by garvankeeley** [comment]
Please make sure ./bootstrap.sh runs without errors

**Comment by elemanhillary** [comment]
@garvankeeley it runs without errors

**Comment by garvankeeley** [comment]
Hmm, that error in the screenshot is exactly what happens when Carthage hasn't run. Can you paste the output of bootstrap? Maybe it isn't reporting but not fully running, I'll be able to tell from that output.
