### ISSUE TITLE
Long press on address bar does not show the expected options unless that's done where there is not text

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/firefox-ios#5581]
Looks like the behavior has changed around this feature, not sure if intentionally or due to the iOS13 version.
If yo follow these steps:
-Go to url bar and type some website, ie: mozilla.org
-Long tap on it to be able to see the different options: Select, Select All, Paste, Paste & Go

The options are only available when  you long tap on the url bar where there is not text or when you go until the end of the text in the url bar.
Please see video attached.
https://youtu.be/hnmz8YR2RtA
There are automated tests related to this feature failing due to the missing options shown following the steps we used to follow. We would need to understand the current expected so that we can fix them correctly.
See some of those tests:
-[testLongPressOnAddressBar](https://github.com/mozilla-mobile/firefox-ios/blob/de77974f8f73b7cdf65d03f1093459aa85481ce4/XCUITests/NavigationTest.swift#L203)
For this test there is not Paste option, only Paste & Go is available now.
-[testCopyPasteComplete](https://github.com/mozilla-mobile/firefox-ios/blob/de77974f8f73b7cdf65d03f1093459aa85481ce4/XCUITests/SearchTest.swift#L118)

CC @garvankeeley FYi. I will disable these tests until we know how they should work now...Thanks!

**Comment by garvankeeley** [comment]
This is a bug we should fix

**Comment by garvankeeley** [comment]
This seems to be working for me, but instead of long pressing, tapping on the URL shows a context menu with Cut/Copy/Paste/Share../etc

**Comment by athomasmoz** [comment]
Note that long tap behaviour is different from just a tap

**Comment by dnarcese** [comment]
This is working for me. Long pressing as well as tapping anywhere in the url bar gives me the context menu.
@isabelrios do you know what step is failing?

**Comment by isabelrios** [comment]
Sorry @dnarcese for the delay in my answer...
There are two different context menus:
-2 Single presses on url bar when there is text shows:
![copy](https://user-images.githubusercontent.com/1897507/69826437-6536f300-1213-11ea-9dfe-944892f2f025.png)

-Long press on url bar with text, when all text is not selected shows:
![SelectAll](https://user-images.githubusercontent.com/1897507/69826459-7ed83a80-1213-11ea-9ac3-42fae3cea2ea.png)

This second context menu is the one I'm getting issues to get. It is not easy for me to go from here: 
![Nothing](https://user-images.githubusercontent.com/1897507/69826482-9e6f6300-1213-11ea-8582-bfade6a8d497.png)

to see those `Select All` and more options. Sometimes a single tap disables the selection and then a long tap launches it but it depends a lot on where/how you tap. I don't find it easy to find/use. 

Something is different showing those menus since this [automated test](https://github.com/mozilla-mobile/firefox-ios/blob/de77974f8f73b7cdf65d03f1093459aa85481ce4/XCUITests/NavigationTest.swift#L203) used to work in previous versions.

**Comment by dnarcese** [comment]
@isabelrios I don't think that we have a lot of control over the text selection behaviour, it is controlled on the OS level. I think for this bug we should just update the test to reflect the new behaviour - does that sound good to you?

**Comment by isabelrios** [comment]
Sure! Thanks for checking this @dnarcese :) 
We will update and re-enable these tests.

**Comment by isabelrios** [comment]
@athomasmoz if you agree, I think we can close this issue then. Tests will be updated and nothing else would be needed. There is already an issue for that automation task.

**Comment by athomasmoz** [comment]
Thanks for the update!
