### ISSUE TITLE
iPad iOS 13: Firefox Share menu does not respect new iOS frame

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#5587]
Build: 20.0(16347)
Device: iPad Pro 11" 
iOS: 13.1

Steps to reproduce:
1. Go to a webpage
2. Open the Page Action menu 
3. Tap "Share"
4. Tap on the Firefox release icon 

Actual results:
- The new standard iOS 13 frame will be displayed in the background. 

Note: 
- When tapping "Cancel" on the Firefox menu, the Share menu will also be dismissed.
- This is only reproducible on Firefox RC 20.0(16347). On Firefox 20.0(16347) beta version this menu looks good. 

![IMG_0024](https://user-images.githubusercontent.com/32130829/66636606-3391aa80-ec1a-11e9-8465-fa2f8fad9f02.PNG)

**Comment by garvankeeley** [comment]
Is it possible this share sheet is from an older install? If *only* Firefox RC is installed does this happen?

**Comment by SimonBasca** [comment]
I think I was on a wrong beta version when previously testing this. That's why I couldn't reproduce on the beta version. Sorry for the confusion, the issue is reproducible on both the beta version and the RC internal version 20.0(16437).

**Comment by athomasmoz** [comment]
Timebox to a 3

**Comment by garvankeeley** [comment]
This is specific to 13.1 (and newer)
