### ISSUE TITLE
Settings panel is not streched to the top

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#5588]
Build: 20.0(16347)
Device: iPhone Xr
iOS: 13.0

Steps:
1.  Open Firefox
2. Open the Hamburger menu

Actual results:
- The menu is not stretched to the top

Screenshot:
![IMG_4119](https://user-images.githubusercontent.com/32130829/66637791-6dfc4700-ec1c-11e9-80fc-ce22bba4d64e.PNG)

**Comment by hamdshah** [comment]
iOS 13 changed the model presentation.

**Comment by garvankeeley** [comment]
This is correct style for this panel on iOS 13, please re-open if you think we should look closer at it.
