### ISSUE TITLE
Top Sites section is not displayed on the tab after opening a new tab from outisde de app (Siri Shortcuts, Today Widget)

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#5589]
Build: 20.0(16347)
Device: iPhone Xr
iOS: 13.0

Preconditions
- Set up Siri shortcuts to Open New tab

Steps to reproduce:
1. Open Firefox
2. Go to youtube.com
3. Background Firefox
4. Wake up Siri and say the command to Open New Tab

Actual results:
- Top sites is not displayed on the new opened tab.

**Comment by SimonBasca** [comment]
This is also reproducible when following the STR and opening a new tab via Today Widget

**Comment by ozankaraali** [comment]
Hello, I have looked into the problem and seems that AppDelegate (profile._reopen()) is called later than SwiftData (doWork() of withConnection), therefore SwiftData's closed attribute turns true and therefore no connections created to Sqlite. 

- One hacky solution is to delete "if !self.closed" in line 164 of SwiftData.swift 
- and other might be try to reopen profile after line 176 and recreate the query of fetching top sites 
- or to not invoke SwiftData before AppDelegate.

If any of these three solutions make sense, I'd like to be assigned for the solution.
