### ISSUE TITLE
"Authorize this sign-in" dialog appears zoomed in after re-entering the app

### ISSUE THREAD

**Issue by csuciu** [mozilla-mobile/firefox-ios#5590]
v20.0(16347)
iPhone XS (13.1)

1. Try to sign into FxA with an unverified account.
2. When you get to the "Authorize this sign-in" dialog, background then foreground the app.

Result: The dialog appears zoomed in upon foregrounding and can't be zoomed out.

![Screen Shot 2019-10-11 at 12 36 05](https://user-images.githubusercontent.com/1866605/66643043-9ee17980-ec26-11e9-83be-1eb21dce158f.png)

**Comment by garvankeeley** [comment]
I can probably disable magnification for this webview.

**Comment by garvankeeley** [comment]
posted to fxa: https://github.com/mozilla/fxa/issues/2859

**Comment by garvankeeley** [comment]
Does this happen in the current release? I have a hard time getting this screen to show so I can't check on older Firefox on my device.

**Comment by garvankeeley** [comment]
Fixed by https://github.com/mozilla/fxa/pull/2866

**Comment by SimonBasca** [comment]
Verifying as fix on 20.0(16437).

**Comment by garvankeeley** [comment]
Is the STR different? Let's file another bug if so

**Comment by garvankeeley** [comment]
This should be fixed now

**Comment by csuciu** [comment]
Confirming that this is fixed in latest Beta.
