### ISSUE TITLE
Crash when unlocking the device while sharing a downloaded file

### ISSUE THREAD

**Issue by csuciu** [mozilla-mobile/firefox-ios#5594]
v20.0(16347)
iPad Pro (13.1)

1. Download a link.
2. Go to Library -> Downloads and open the downloaded link.
3. Open PAM and select "Share Page With...".
    => The Share sheet opens blank (that's issue #5558).
4. While the app is foregrounded with the Share sheet open, lock the device.
5. Unlock the device.

Result: The app crashes.

[Client-2019-10-11-130152.ips.beta.synced.zip](https://github.com/mozilla-mobile/firefox-ios/files/3717215/Client-2019-10-11-130152.ips.beta.synced.zip)

**Comment by athomasmoz** [comment]
This should be fixed by #5558
