### ISSUE TITLE
Today extension does not respect dark mode

### ISSUE THREAD

**Issue by Bunn** [mozilla-mobile/firefox-ios#5604]
Steps to reproduce:
- Change device to dark mode;
- Tap and hold on the Firefox app icon;

Expected:
- Colors would have a better contrast on dark mode

Actual result:
- Colors do not change making it hard to read.
![TodayExtension](https://user-images.githubusercontent.com/782316/66705408-2d84f200-ed1e-11e9-8027-52e184ac9c32.png)

**Comment by athomasmoz** [comment]
Could we disable it here and just keep on the homescreen?

**Comment by athomasmoz** [comment]
Looks like it can be disabled for this view. I suggest we do that, since all options are covered in the existing menu

**Comment by Bunn** [comment]
The "Go to copied link" is not available on the menu.
<img width="432" alt="66705475-067af000-ed1f-11e9-84c5-309f0ca30b73" src="https://user-images.githubusercontent.com/782316/66913428-84374800-f00c-11e9-95c1-8060aaab6e64.png">

But if this is going to be removed or not from this view I believe another issue should be opened since this one is focused on the dark/light theme on the widget, which is a problem that also happens on the widget screen.

**Comment by athomasmoz** [comment]
Yes, thanks for noting that. And for the PR!
