### ISSUE TITLE
Nordstrom.com is not loading in Firefox iOS

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#5610]
Build: 20.0(16347)
Device: iPhone Xr
iOS: 13.0

Steps to reproduce:
1. Go to Nordstrom.com

Actual results:
- Website is not loading. 

Note:
- This website is working in Safari

**Comment by karlcow** [comment]
We got a duplicate report https://github.com/webcompat/web-bugs/issues/42236

**Comment by garvankeeley** [comment]
odd that disabling ETP doesn't seem to help

**Comment by athomasmoz** [comment]
@garvankeeley did you see the comment in the web compat bug? Looks like this is why they closed it https://github.com/webcompat/web-bugs/issues/42236#issuecomment-544303633

**Comment by garvankeeley** [comment]
That mentions Fenix and desktop Safari, but more interesting is that it works on Safari iOS. It would be good to check on Chrome iOS and see what that does.

**Comment by athomasmoz** [comment]
Just tried on Chrome iOS and it worked. I wonder what's happening in FF that prevents it from loading

**Comment by garvankeeley** [comment]
No idea, here is the JS errors on that page
<img width="959" alt="image" src="https://user-images.githubusercontent.com/5495083/67329926-8c4e2680-f4e9-11e9-893f-0655e0de4838.png">

**Comment by garvankeeley** [comment]
I found the bug in HistoryStateHelper.js, working on a fix
