### ISSUE TITLE
Implement Universal link deeplink protocol

### ISSUE THREAD

**Issue by lwa-moz** [mozilla-mobile/firefox-ios#5612]
As a Marketer, I would like to create links that direct prospective users to the appstore to download the app, and direct existing users into the app to use it.

iOS provides a "Universal link" deeplinking protocol that allows for this use-case.

The process to enable this functionality is described in the Adjust documentation here: https://help.adjust.com/optimize/re-engagement/deeplinks/direct-links-for-ios

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2178)

**Comment by athomasmoz** [comment]
This may have already been implemented. Jeremy to investigate & share existing solution with marketing

**Comment by jevans-mozilla** [comment]
Currently implemented deep links are the following:
-Bookmarks
- History
- Reading List
- Downloads
- Top Sites
- New Private Tab
- Settings

I was unable to determine if Universal links through Adjust were active though

**Comment by lwa-moz** [comment]
Hey @jevans-mozilla - Universal deeplinks do appear to be working with Adjust. 

https://nn8g.adj.st/ should open the app for existing users as expected (it did on my personal device).

For the specific deep links that are currently integrated, do you have documentation for how those can be referenced in a URL? Something like "?deeplink=history" or similar?

**Comment by lmarceau** [comment]
Since only `data-sync-user` has commented on the issue after the `Stalebot` GitHub action (which triggered the removal of the `stale` label) I’ll close this issue for now. Please let us know if you think this issue needs to be reopened, we'll gladly do so. Thank you!
