### ISSUE TITLE
[XCUITests] testAccountManagementPage needs to retrieve the email code to verify account

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/firefox-ios#5613]
We need to update this test. Before we could verify the account retrieving code and uid and posting to the specific end point but now we need the six digits generated to verify a fx account and check if doing the POST to same end point works or we need to do something else.
Until then this test will be disabled.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2179)

**Comment by lmarceau** [comment]
Since only `data-sync-user` has commented on the issue after the `Stalebot` GitHub action (which triggered the removal of the `stale` label) I’ll close this issue for now. Please let us know if you think this issue needs to be reopened, we'll gladly do so. Thank you!
