### ISSUE TITLE
Accept Case Insensitive Headers

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#5624]
Logged via : https://bugzilla.mozilla.org/show_bug.cgi?id=1589211

While testing out durable sync, we discovered that iOS devices do not accept case insensitive header key names (See https://bugzilla.mozilla.org/show_bug.cgi?id=1589185). Header keys should be case insensitive (per RFC 7230). This is additionally complicated because some libraries enforce case on key names during generation, so a specific case selection can not be ensured.

**Comment by garvankeeley** [comment]
Duplicate https://github.com/mozilla-mobile/firefox-ios/issues/5619
