### ISSUE TITLE
Certain theme elements are incorrect on iPad using split-screen

### ISSUE THREAD

**Issue by cgioia** [mozilla-mobile/firefox-ios#5629]
This issue is when using an iPad app in split-screen "compact" mode. This is when the view is compressed like on an iPhone. The issues I've found:

- The new tab button, when viewed in the compact mode with the light theme, is shaded as if it were still in the iPad's top tab bar, and is too light for the background

- The status bar text, when in compact mode with the light theme, is left as white text, and is illegible on the white background

**Comment by cgioia** [comment]
I have fixes in-hand for this issue. Created this so that I can create a pull request shortly.

**Comment by garvankeeley** [comment]
<img width="300" alt="Untitled" src="https://user-images.githubusercontent.com/5495083/67323845-00d09780-f4e1-11e9-8848-d3c01b52ca56.png">

**Comment by SimonBasca** [comment]
Verifying as fix on 20.2 (16690).
