### ISSUE TITLE
Firefox is switching icons on iOS 13

### ISSUE THREAD

**Issue by tankmohit** [mozilla-mobile/firefox-ios#5646]
Opening a firefox has a new icon and going back to the home screen changed back to old Firefox icon for a second and changes back to new icon again. 

[Link to the screen recording. ](https://imgur.com/a/rUt5YwX)

**Comment by csuciu** [comment]
Another report of this issue here: https://bugzilla.mozilla.org/show_bug.cgi?id=1590702

**Comment by garvankeeley** [comment]
I had this too. It is an iOS bug, rebooting the device fixes it in most cases.
