### ISSUE TITLE
l10n "Back" is translated to "Backwards" in en-CA

### ISSUE THREAD

**Issue by dnarcese** [mozilla-mobile/firefox-ios#5650]
There are 3 strings that contain "Back" that have been translated to say "Backwards" in en-CA.

cc @Delphine

**Comment by Delphine** [comment]
Thanks Daniela!

I see the instances on Transvision here: https://transvision.mozfr.org/?recherche=Back&repo=firefox_ios&sourcelocale=en-US&locale=en-CA&search_type=strings

Looping in localizers: is there a reason for this?
CC @kyoshino and @catlee for more information around this choice.

**Comment by kyoshino** [comment]
Hi @Delphine, looks like it’s a copy from en-GB. The en-CA Firefox l10n was originally imported from en-GB so we share the same issue:

https://transvision.mozfr.org/?recherche=Back&repo=firefox_ios&sourcelocale=en-US&locale=en-GB&search_type=strings

I can fix the en-CA strings now.

**Comment by kyoshino** [comment]
@dnarcese already suggested changes on Pontoon so I just approved them. Thanks!

**Comment by dnarcese** [comment]
@kyoshino Thank you!

**Comment by kyoshino** [comment]
I just pinged en-GB localizer [Ian](https://pontoon.mozilla.org/contributors/ZPtqZjDslj8NrYXZ_OZU-RxQu_c/) on IRC.

**Comment by Delphine** [comment]
Thanks  so much everyone 😃

**Comment by kyoshino** [comment]
Ian says the en-GB l10n is fine. In the meantime I have updated the desktop and Android Firefox l10n as well, so we can close the issue now. Thanks for the heads-up!
