### ISSUE TITLE
[XCUITests] Display Settings tests need to be updated

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/firefox-ios#5656]
There have been recent changes around this feature and so tests are failing and need to be updated. Main issue with tests is that previously the switch was off and now it is on by default.

-Older screen and how tests are implemented now: 
![oldDisplaySettings](https://user-images.githubusercontent.com/1897507/67483438-1f13d000-f666-11e9-8cf7-e7042a8db4e5.png)

-New screens:
![Screenshot 2019-10-24 at 13 57 23](https://user-images.githubusercontent.com/1897507/67483505-4c607e00-f666-11e9-8913-150d41117495.png)
![Screenshot 2019-10-24 at 13 57 14](https://user-images.githubusercontent.com/1897507/67483512-4e2a4180-f666-11e9-97d3-d41264193b69.png)

**Comment by isabelrios** [comment]
@dnarcese do you expect more changes around these screens? just to start working on them or wait until the work is finished. Thanks! :)

**Comment by dnarcese** [comment]
@isabelrios No, there shouldn’t be anymore changes!
