### ISSUE TITLE
Firefox seems to mess up bluetooth controls for AIMP

### ISSUE THREAD

**Issue by chinagreenelvis** [mozilla-mobile/firefox-ios#5658]
Using AIMP media player, everything works fine until I start browsing on Firefox. I can't seem to produce this issue with any other player or browser, and I can consistently reproduce it with Firefox.

If I begin playback in AIMP and then begin browsing in firefox, the bluetooth button stops working. Pressing it once does nothing, and pressing it a second time temporarily pauses playback in AIMP, which then resumes almost instantly.

I've posted in the AIMP bugs forum for advice, and thought I should post here as well for any thoughts. I've tried disabling Firefox app permissions and notifications, and automatic media playback is disabled as well. Thanks!

**Comment by athomasmoz** [comment]
Thanks for logging. Unfortunately, this isn't something that can be fixed in the browser. It's out of our control.
