### ISSUE TITLE
Updated Tabs Design

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-ios#5661]
What

Update workflows for accessing recent tabs to make it easier for users

Why

When researching a topic online, I open multiple tabs and it can be hard to find the one I was just looking at, especially if I have tabs open from previous tasks.

PRD: https://docs.google.com/document/d/1_DaKVU-Bg5ikGRNjgSjHHuEmNNX2iN5HliYsSNeuWwQ/edit#

Relevant bugs logged to consider in new design:
* #5345 
* #4725 
* #5052

**Comment by athomasmoz** [comment]
Feedback for considering in design #5052

**Comment by bryanbell** [comment]
Initial Mockup: https://mozilla.invisionapp.com/share/YVU0A287TXK#/384813412_Artboard

**Comment by athomasmoz** [comment]
@bryanbell can you add a link to the iPad mock as well?

**Comment by nbhasin2** [comment]
Updated Mocks: https://app.abstract.com/share/1d20d3a3-fc33-4494-8fa8-55ca4eec37cf

**Comment by athomasmoz** [comment]
Closing ticket. Broken out into Chronological tabs tickets
