### ISSUE TITLE
Option to close all tabs on exit

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#5662]
Logged via : https://bugzilla.mozilla.org/show_bug.cgi?id=1590497

Steps to reproduce:

```
Swipe close Firefox app with open tabs
Re-open Firefox
```

Actual results:

Previous open tabs are always restored

Expected results:

Every other platform of Firefox has the option to close all open tabs on browser exit except the iOS one. Would be nice to have this option in iOS too.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2185)

**Comment by brampitoyo** [comment]
Clarifying question for @SimonBasca: what is the benefit of closing all tabs on exit, if you can already do this using Private Browsing, and if there’s already a button to “Close All Tabs”?

On Private Browsing Mode, tabs are closed and data are erased both when you go back to normal browsing, and when you exit Firefox.

**Comment by data-sync-user** [comment]
➤ Tiffanie Shakespeare commented:

Removing needs ux label - this is a feature request/product improvement which should be a project that flows through our product road map.

**Comment by Verdi** [comment]
Mobile is a different environment than desktop. Apps get killed in the background by the system, people kill apps to fix issues and to free up resources for other activities. At the same time most people leave mobile tabs open as reminders to themselves. If we were to do this (I'm not recommending that we do), we would also need a way to restore a previous session and a setting to control this behavior (I would also not recommend making it the default). If we were to consider this for iOS we should also consider it for Android. I don't see a reason to have different behavior in this case between mobile OSs.
