### ISSUE TITLE
[Regression] UI Tab Restore test fails

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/firefox-ios#5668]
After this latest commit 6dd7de08d017f09420f5b80e5e3ef4c0ca8d7f4e cc @garvankeeley , [testTabRestore](6dd7de08d017f09420f5b80e5e3ef4c0ca8d7f4e) is failing.

Trying to understand the changes if we should modify the test or there is a problem with latest commit causing the test to fail.
What's happening is that the restored website is not loaded.

**Comment by garvankeeley** [comment]
fixed by https://github.com/mozilla-mobile/firefox-ios/pull/5672
