### ISSUE TITLE
User agent firefox ios seems strange on ipad

### ISSUE THREAD

**Issue by numebrique** [mozilla-mobile/firefox-ios#5675]
Hi,

With last Firefox iOS version on iPad I have this user-agent :

"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15) AppleWebKit ..." instead of "Mozilla/5.0 (iPad; CPU OS 12.4 like Mac OS X) AppleWebKit ..."

[Firefox user agent MDN](https://developer.mozilla.org/fr/docs/Web/HTTP/Gecko_user_agent_string_reference)

Did you change the user agent reference in last version ?

--- Config ---
iPad Air 12.4.2
Firefox 20.0 (16437)

Thanks you !

Best regards,

Hani

**Comment by garvankeeley** [comment]
Apple did, the default UA is now desktop on iPad as of iOS 13.
