### ISSUE TITLE
Image colour being inverted

### ISSUE THREAD

**Issue by OmegaRejectz** [mozilla-mobile/firefox-ios#5676]
There’s no specific site it happens on, it’s happened on every one I’ve been on one time or another. The colour is just completely inverted and impossible to look at without killing your eyes.

**Comment by garvankeeley** [comment]
This is due to 'night mode' that tries to invert the colors on the webpage to darken them. Some images get inverted, we currently have no solution for this.

**Comment by andreicristianpetcu** [comment]
I think the issue was more a feature request. Isn't it possible to add other algorithms that don't change the image this way?
