### ISSUE TITLE
UX: Upgrade Path for New Dark Theme Settings

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-ios#5680]
**VISION**
As an existing Firefox user, I want to take advantage of the new system-wide dark theme control to set my Firefox theme

----

**ACCEPTANCE CRITERIA**

* An upgrade path to the new dark theme settings is defined for users with the following settings in v20
** Users with dark theme set to manual > light
** Users with dark theme set to manual > dark
** Users with dark theme set to automatic
* Any messaging to users about the upgrade has been defined and strings confirmed

**Comment by bryanbell** [comment]
Here's a Mockup the require changes to ship the new dark theme changes. 
https://mozilla.invisionapp.com/share/DHUNACFQAXV#/385772933_Artboard
