### ISSUE TITLE
Whatsapp has issues loading the correct website on Firefox iOS

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#5682]
Whatsapp has issues loading the correct website on Firefox iOS 

Background:
Currently on iPad (desktop view) when user tries to load whatsapp.com they are unable to do so and are presented by incompatible browser page. However, the page loads fine in Safari on the same iPad. Only thing that's different is the user agent string in Safari vs Firefox iOS app.

Safari UA - Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.1 Safari/605.1.15

Firefox iOS UA - Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15) AppleWebKit/605.1.15 (KHTML, like Gecko) FxiOS/18.0 Version/13.0.3 Safari/605.1.15

How to reproduce:

- You need to be in iOS 13
- On an iPad
- Make sure you are browsing in Desktop Mode
- Go to safari and load "web.whatsapp.com"
- Go to firefox and load "web.whatsapp.com"
- Safari whatsapp web will ask you to scan phone where as firefox version won't

Main difference that fixes the whatsapp loading issue is when I remove the `FxiOS/18.0`  from Firefox iOS UA. Then it becomes similar to Safari user agent.

Actual results:
- "https://web.whatsapp.com/" is loaded but it will display this page:

![Screen Shot 2019-10-29 at 12 41 30 PM](https://user-images.githubusercontent.com/32130829/67760150-74c2f080-fa49-11e9-8486-50e8518bbc00.png)

Expected results: 
- Going to "https://web.whatsapp.com/" should go to this page:
![IMG_0030](https://user-images.githubusercontent.com/32130829/67761736-907bc600-fa4c-11e9-875b-a1ff06644fd8.PNG)

**Comment by athomasmoz** [comment]
This issue has been reported for other sites too (Youtube, Google, Twitter & Reddit). 
In many cases, using the mobile version is not a workaround because it will ask you to download the app

Let's try to workaround the issue (send different UA) & also log with webcompat for a longer term fix

**Comment by athomasmoz** [comment]
Fix added for YouTube and Google, so this may also be fixed. Need to retest.

**Comment by garvankeeley** [comment]
https://github.com/mozilla-mobile/firefox-ios/pull/5725 may have fixed this

**Comment by SimonBasca** [comment]
@garvankeeley I tested with ca1042f05d58 on iPad Pro 13.2.3. This issue is still reproducible. Going to web.whatsapp.com will display the following screenshot. 
![Screen Shot 2019-11-27 at 11 33 50 AM](https://user-images.githubusercontent.com/32130829/69711488-d38f8e80-1109-11ea-9de5-3efd2bac6ed7.png)

Also note that going to youtube.com will display a unsupported browser message.
![Screen Shot 2019-11-27 at 11 35 08 AM](https://user-images.githubusercontent.com/32130829/69711587-fe79e280-1109-11ea-9893-578c0dab9018.png)

**Comment by athomasmoz** [comment]
Another report on this https://app.appbot.co/apps/854569-firefox-private-safe-browser/reviews/1445119994?

**Comment by athomasmoz** [comment]
In case it helps, you can quickly find reviews on this by searching the website names or for "out of date"

**Comment by dnarcese** [comment]
I just re-checked the sites and I only see the update message on WhatsApp and Reddit. On Reddit though you can still use the site it just warns that it may not work as well.

**Comment by athomasmoz** [comment]
Is there a similar fix that could work for those sites? Or would it be riskier?

**Comment by nbhasin2** [comment]
Main reason for broken website is the UA string. Hence after investigation we have few potential solution(s) that can help fix the issue:

a) We have custom user agent for any broken site we find (Eg. Whatsapp)
b) We remove a part of user agent that shows FxiOS/xy version for all desktop websites
c) Contact whatsapp or the broken website and see where things goes

**Comment by nbhasin2** [comment]
Conclusion: We'll go with having a custom user agent for any broken website. Along with this we'll do our best to reach out to the broken website if there is anything that can be done from their side.

**Comment by SimonBasca** [comment]
Verifying as fix on master c2574a
