### ISSUE TITLE
XCode can not find provisioning profile

### ISSUE THREAD

**Issue by Skylerwiernik** [mozilla-mobile/firefox-ios#5688]
I downloaded the source code and followed the steps listed in the <b>readme</b>, but I am unable to build the app on my machine. 
<img width="1387" alt="XCode Screenshot" src="https://user-images.githubusercontent.com/45213762/67822091-95189c80-fa95-11e9-8280-935364707b00.png">

**Comment by garvankeeley** [comment]
Can you build to simulator?

**Comment by muhasturk** [comment]
You are trying to deploy application to your real device, you should change provisioning profile or deploy simulator.
