### ISSUE TITLE
"Open in New Private Tab" doesn't open tab when "Close Private Tabs" is enabled

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/firefox-ios#5694]
STR:
1. Enable Settings > Close Private Tabs.
2. In a non-private browsing tab, long press on a link and select "Open in New Private Tab".
3. Do NOT switch to the new private tab using the blue popup banner.
4. Now switch to private tabs.

Result:
The new private tab is not listed. If I disable Close Private Tabs and repeat steps 2-4, the new private tab is listed as expected.

I am using Firefox Beta Version 20.0 (16410).

**Comment by KrystynaKruchkovska** [comment]
I'm able to reproduce the bug. I've also noticed that in provided scenerio, when opening new private table in step 2, blue popup banner has "Switch to new tab" instead of "Switch to new private tab". Is it a ok if I give these issues a try?

**Comment by nick130586** [comment]
> Is it a ok if I give these issues a try?

I think you can since no one else haven't mentioned it yet.

**Comment by SimonBasca** [comment]
Verifying as fix on 21.0 (16901)
