### ISSUE TITLE
keyboard collapses immediately when searching in new tab

### ISSUE THREAD

**Issue by noahhaasis** [mozilla-mobile/firefox-ios#5696]
When I open a new tab in firefox and immediately click on the search bar the keyboard appears and collapses after about a second. And because I'm already typing I oftentimes accidentally open a webpage.

![IMG_4784TRIM](https://user-images.githubusercontent.com/26230013/68120530-e8f80b00-ff05-11e9-82df-26b75f5fc6f8.gif)

**Comment by SimonBasca** [comment]
@noahhaasis are you using a 3rd party keyboard? If so, what keyboard are you using?

**Comment by noahhaasis** [comment]
No, I'm not using a third-party keyboard. I'm on IOS 12.4.2

**Comment by athomasmoz** [comment]
@SimonBasca have you been able to reproduce this one?

**Comment by SimonBasca** [comment]
@athomasmoz I am able to reproduce this but I don't believe this to be Firefox Issue. In my case I have to be really fast to reproduce this issue following the STR: 

1. Opening a new tab
2. Quickly focusing the URL bar before the the animation that scrolls into view the opened tab finishes. 

I believe that the iPad used by @noahhaasis is a bit laggy and the animation that scrolls into view the opened tab is dismissing the keyboard. @noahhaasis can you please confirm what I am saying? Also can you tell us what device are you using?

I tested on iPad Air 3 (12.4).

**Comment by noahhaasis** [comment]
I have the first iPad Air so it’s not the fastest

**Comment by dnarcese** [comment]
Dupe #5771
