### ISSUE TITLE
Cover Sheet for Firefox Updates.

### ISSUE THREAD

**Issue by bryanbell** [mozilla-mobile/firefox-ios#5697]
**Vision**

As an existing user, when I first open a Firefox after an update, I see highlights of the changes

**Acceptance Criteria**

* Firefox eng has an option to include a cover sheet for new releases
  * Cover sheet is localizable
  * Cover sheet follows a standard template, so it's simple to add in the text each release
* The cover sheet is shown the first time a user opens up the browser after an update
* If the user is opening the browser for the first time after multiple updates, only the cover sheet for the latest version is shown
* For v22, a cover sheet is included that matches the attached mocks

**Not Included**

* In future, we will want the option to add multiple cards in the cover sheet. That option doesn't need to be built out for this ticket

**Comment by bryanbell** [comment]
Mockup of the coversheet. 
https://mozilla.invisionapp.com/share/QDUNAFYUZM9#/391433147_Artboard

**Comment by athomasmoz** [comment]
Do we care about tracking??? Impressions or clicks on the "Start Browsing" button. I'm thinking no because anyone who updates will see it, and that button is their only option. Unless we're concerned over users seeing the message and then closing the app immediately

**Comment by athomasmoz** [comment]
Spec for overall feature: https://mozilla.invisionapp.com/share/JFU9PCL3GU2#/screens/387548633

**Comment by athomasmoz** [comment]
What does this look like on different screen sizes & orientations. @bryanbell to follow up

**Comment by athomasmoz** [comment]
Note since I'm not in sprint planning next week. We'd need to land strings before Friday to get them localized in time for v21 release. I consider this a "should" not a "must" for the release.

**Comment by athomasmoz** [comment]
Note: We'll need to land strings for this & send for localization by Jan 3

**Comment by athomasmoz** [comment]
Note: I have not included any tracking in this story. Since there is only one action available and all upgraded users will see the cover sheet, it's not necessary to add the extra data

**Comment by athomasmoz** [comment]
@nbhasin2 Can you (or whoever else works on this) send Joni a screenshot once it's been implemented? She'll use it in the SUMO article about the feature.

**Comment by nbhasin2** [comment]
> @nbhasin2 Can you (or whoever else works on this) send Joni a screenshot once it's been implemented? She'll use it in the SUMO article about the feature.

Will do that :)

**Comment by athomasmoz** [comment]
Thanks! Good timing - I saw you assigned yourself right as I opened the issue to comment.

**Comment by nbhasin2** [comment]
Unfortunately the following string didn't get added / translated for the upcoming release 

`What's New in Firefox 21`

We'll go with the following string which is already in the codebase and translated and we'll update the strings for next to next release.

`What's New `
