### ISSUE TITLE
Firefox is automatically switching me back to mobile sites when I've switched it to view desktop sites

### ISSUE THREAD

**Issue by ghauldidnothingwrong** [mozilla-mobile/firefox-ios#5702]
I've followed the steps for viewing desktop sites in firefox here: https://support.mozilla.org/en-US/kb/viewing-desktop-sites-firefox-ios - 

I open firefox and load into whatever website I want to view. I'll follow the steps above to view the desktop site, but whenever I open a new tab or navigate away from a webpage to a different one, firefox is automatically loading me up in the mobile site for whatever destination page I'm going to. This just started in the last few days, and I've since cleared all browsing data for firefox, uninstalled & reinstalled from the app store, but the issue continues. Firefox will not allow me to lock desktop view, and even when I've selected it, it doesn't remember the preference when changing web pages or opening new tabs. Is this normal?

**Comment by SimonBasca** [comment]
The current behavior is that desktop mode is persistent per domain. 

See : https://github.com/mozilla-mobile/firefox-ios/commit/f1a4efb62d416edb543b91011d2b423c4ef3418a

We also have a follow-up feature request to implement a global desktop mode : https://github.com/mozilla-mobile/firefox-ios/issues/5711

Thanks for your feedback.
