### ISSUE TITLE
add search code for Ecosia for germany

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/firefox-ios#5703]
The new URL should be:

>  https://www.ecosia.org/search?q={searchTerms}&tt=16eeffc4

**Comment by mkaply** [comment]
Note this should be for Germany only.

**Comment by garvankeeley** [comment]
I don't see the term `ecosia` in our codebase at all, are you sure this is an issue?

**Comment by mkaply** [comment]
It should be add Ecosia, not update Ecosia. See:

https://github.com/mozilla-mobile/android-components/pull/5059

**Comment by garvankeeley** [comment]
https://searchfox.org/mozilla-central/source/browser/components/search/extensions/ecosia/manifest.json

**Comment by garvankeeley** [comment]
This is what the icon looks like in the search bar
<img width="285" alt="image" src="https://user-images.githubusercontent.com/5495083/69370387-dbfc4b00-0c6b-11ea-834b-0103c72dfff8.png">

**Comment by mkaply** [comment]
That really doesn't blend well. 

Can you try this icon? I think iOs wants 96x96, right?
![ecosia](https://user-images.githubusercontent.com/345868/69381402-516f1800-0c7a-11ea-9b8b-3d9c9da924cd.png)

**Comment by mkaply** [comment]
I guess the background is the issue. Argh.

**Comment by SimonBasca** [comment]
Verifying as fix on 21.0 (16901)
