### ISSUE TITLE
Use BGTaskScheduler on iOS 13 to avoid forceClose crash

### ISSUE THREAD

**Issue by garvankeeley** [mozilla-mobile/firefox-ios#5704]
The app is getting killed when in background: https://github.com/mozilla/application-services/issues/1964. Likely due to timeouts on iOS 13.
~Using the new API should fix this.~
EDIT: This will make no difference, it is still 30s to complete the task.

**Comment by garvankeeley** [comment]
I supposed if we schedule two bg tasks, we can get 30s for each?

**Comment by athomasmoz** [comment]
Let's see if #5597 fixes the issue. This is a better approach to the fix, but less urgent if #5597 fixes the crash
