### ISSUE TITLE
User-Agent request header on iOS 12 shows iOS 13

### ISSUE THREAD

**Issue by stomilson** [mozilla-mobile/firefox-ios#5707]
When using the latest Firefox (20.0) on iOS 12 (we've tested iOS 12.4), the following user-agent request header value gets sent:

> Mozilla/5.0 (iPhone; CPU iPhone OS 13_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) FxiOS/20.0 Mobile/15E148 Safari/605.1.15

Note where it says "OS 13_0" there - this should be "OS 12_4" if following conventions established here: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent/Firefox

This makes it difficult to accurately filter out all browsers for iOS 12 SameSite cookie incompatibility, as noted here: https://www.chromium.org/updates/same-site/incompatible-clients

**Comment by stomilson** [comment]
What version of Firefox iOS will this fix be packaged in?

**Comment by kaylee42** [comment]
Hi, I'm working on filtering for SameSite cookie incompatibility as well - this actually broke something for me, and for now I'm just preventing SameSite=None from being put on any ffios browsers reporting ios13, but would it be possible to get a full range of ffios versions impacted by this so I'm not just excluding every version of ff reporting ios13? Thanks much for fixing this!

**Comment by garvankeeley** [comment]
This is in v21 released today

**Comment by kaylee42** [comment]
Thank you @garvankeeley ! Just to 100% confirm, this only effects major version 20, correct?
