### ISSUE TITLE
iOS 13: Add search engine button layout is broken on iPads.

### ISSUE THREAD

**Issue by shahenAnt** [mozilla-mobile/firefox-ios#5712]
Steps to reproduce:

1. Go to yahoo.com
2. Tap on the search bar
3. Type any word

Actual results:
The Add search engine button is moving with broken layout.

Expected results:
The Add search engine button shouldn't move and should keep button appearance.

![IMG_0002](https://user-images.githubusercontent.com/55664114/68209468-e2908e80-ffec-11e9-8135-e104bd977d6f.PNG)
![IMG_0004](https://user-images.githubusercontent.com/55664114/68209469-e2908e80-ffec-11e9-93d2-0850cc9c4310.PNG)

**Comment by athomasmoz** [comment]
Should we remove this, since it's available from settings? Concerns that this feature on the keyboard is unstable
