### ISSUE TITLE
User Agent is causing wrong version of Google and Youtube to be loaded

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#5713]
Build: 20.1 (16561)
Device: iPad Pro

Steps to reproduce:
1. Go to google.com

Actual results:
- I am redirected to "google.com/#spf=1572962176491"

Note:
- Safari loads the correct webview.
- Not reproducible on version 19.1 (16198)

Firefox:
![IMG_710B17F298E7-1](https://user-images.githubusercontent.com/32130829/68217549-76615b00-ffeb-11e9-9d27-05b759241fbe.jpeg)

**Comment by SimonBasca** [comment]
We are also experiencing issues with Youtube on Firefox.  We are served a incorrect website version when we try to load the Desktop Version of Youtube. 

Firefox:
![Firefox](https://user-images.githubusercontent.com/32130829/68223924-61d69000-fff6-11e9-94e6-f044b6e81e1d.PNG)

Safari:
![Safari](https://user-images.githubusercontent.com/32130829/68224010-8894c680-fff6-11e9-9b2a-050bb196b5a5.PNG)

I believe that this might be because we are not sending the correct User Agent. Below is a screenshot of the user agent served by Safari and the one served by Firefox: 

![UA](https://user-images.githubusercontent.com/32130829/68224144-bc6fec00-fff6-11e9-8e88-c7cc64347dbe.PNG)

**Comment by garvankeeley** [comment]
YouTube can be fixed by adding 'Safari/XXX' to the UA string.

**Comment by garvankeeley** [comment]
Still not working with google

**Comment by garvankeeley** [comment]
Adding `Version/7.0.3` to the UA will get the correct google page

**Comment by SimonBasca** [comment]
Verifying as fix on 21.0 (16901). Youtube and Google are correctly displayed.
