### ISSUE TITLE
ETP label is truncated in Settings

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla-mobile/firefox-ios#5714]
Following up #5350, the issue is still reproducible with 20.1 release on iOS 13.2

![image](https://user-images.githubusercontent.com/1294206/68220744-8fb4d800-ffe8-11e9-8b39-396a80e3ea80.png)

**Comment by TheoChevalier** [comment]
cc @Delphine

**Comment by SimonBasca** [comment]
Verifying as fix on 21.0 (16901)
