### ISSUE TITLE
Status bar text is white therefore invisible

### ISSUE THREAD

**Issue by kz89** [mozilla-mobile/firefox-ios#5717]
Status bar text is white therefore invisible.
I'm using iPhone 8, iOS 13.2, Firefox 20.1 (16561).
The issue doesn't occur when switching to dark mode in the app.
Attaching screenshots.
![IMG_2029](https://user-images.githubusercontent.com/18735598/68237965-820f4a80-0008-11ea-9607-68ec0b19b40b.jpeg)
![IMG_2030](https://user-images.githubusercontent.com/18735598/68237967-82a7e100-0008-11ea-9ef2-608de53c26a2.jpeg)
![IMG_2031](https://user-images.githubusercontent.com/18735598/68237969-82a7e100-0008-11ea-868e-a8c9e8278ee2.jpeg)
![IMG_2032](https://user-images.githubusercontent.com/18735598/68237970-82a7e100-0008-11ea-92aa-4535edd41b13.jpeg)

**Comment by dnarcese** [comment]
Dupe #5684
