### ISSUE TITLE
PDF export/share results in a corrupt file.

### ISSUE THREAD

**Issue by chinook77** [mozilla-mobile/firefox-ios#5721]
Hi, since several releases back, every time that I open a pdf file and share it (in order to open with another app) results in a corrupt file. It's very annoying.

**Comment by chinook77** [comment]
CRIC CRIC CRIC

**Comment by athomasmoz** [comment]
Hi @chinook77 thanks for logging. Can you provide an example of the file & workflow to help us reproduce the issue?

**Comment by garvankeeley** [comment]
Closing until we get repro file
