### ISSUE TITLE
Make it more obvious when browser gets disconnected from FxA

### ISSUE THREAD

**Issue by davismtl** [mozilla-mobile/firefox-ios#5722]
Today I noticed that my browser was disconnected from my account. This gh issue is not about understanding why I somehow got disconnected ([though I can't help but wonder if it is related to this](https://bugzilla.mozilla.org/show_bug.cgi?id=1589414)) but rather it is about making it more obvious to users when their browsers get disconnected from their account.

Since it is not obvious when the account gets disconnected, it took me 14 days to realize that it's been disconnected. 

![image](https://user-images.githubusercontent.com/19537086/68255615-93456080-ffe2-11e9-846d-217b37ef4c82.png)

On desktop, there's a yellow notification icon that appears on the hamburger menu if the browser disconnects from the account.

There is nothing in iOS:
![IMG_5844](https://user-images.githubusercontent.com/19537086/68256032-c9cfab00-ffe3-11e9-98db-c8d1d3b6fe6e.PNG)

I suspect that over 14 days, I probably opened the menu more than once without noticing that my browser was disconnected. The exclamation mark and call to action are not in any color to make that stands out. I think we can also draw more attention to this ⚠️ alert.

![IMG_5843](https://user-images.githubusercontent.com/19537086/68256104-f5529580-ffe3-11e9-9daf-02b742284ca4.PNG)

By making it more obvious to users, we can minimize the impact of any potential bugs. ~We can also make it more obvious to users if they accidentally disconnected their device from the FxA device manager.~ (edit: we don't even surface the above message when a user remotely disconnects a device)

**Comment by davismtl** [comment]
We now have 3 employees reporting that they have been disconnected from Firefox for iOS.

While we should certainly investigate to fix any underlying problems, I highly recommend prioritizing this UI/UX work so we can try to recover the 20% of users we somewhat likely lost since the summer due to this bug.

See: https://github.com/mozilla/application-services/issues/2160

**Comment by rfk** [comment]
So @davismtl, just to be clear: your Firefox for iOS is showing "Enter your password to connect" and is not syncing, but if you go to your FxA device list on the web, it still shows that device as being connected to your account?

**Comment by davismtl** [comment]
> but if you go to your FxA device list on the web, it still shows that device as being connected to your account?

Correct. It showed it as beeing inactive for 2 weeks.
