### ISSUE TITLE
Private Browsing Usage

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-ios#5730]
**What**

Add tracking to determine how often private tabs are used

**Why**

* Understand how valuable private browsing is to our users
* Estimate the impact that changes to private browsing could make

**Acceptance Criteria**

* Telemetry & Amplitude tracking has been added to understand how often private tabs are used
  * Bugzilla ticket in Data Eng can be added & assigned to Arkadius once Telemetry probes land to get the same ones in Amplitude
* Additional tracking following our existing privacy standards
* Documentation updated to reflect new tracking

**Notes**

* I've created a [ticket for Data Science](https://bugzilla.mozilla.org/show_bug.cgi?id=1594616) with details on the questions I'd like to answer, so we can get their support deciding the best way to track this (and hopefully in a way that's consistent with Fenix)

**Comment by kwillowhawk** [comment]
Our policy supports us doing this, see decision/guidance here: https://groups.google.com/forum/#!msg/mozilla.governance/7UH_MngkDx0/M5CJnx4gCAAJ
