### ISSUE TITLE
Init Leanplum SDK based language code only

### ISSUE THREAD

**Issue by lwa-moz** [mozilla-mobile/firefox-ios#5734]
Expected behavior: Leanplum SDK initializes on first run; api.leanplum.com is called on first run 
Video reference for expected behavior: https://drive.google.com/open?id=1nM917-Nz6WiUSmmWMkoMWjqj4K7fJch7

Actual behavior: Leanplum SDK fails to initialize; api.leanplum.com is not called on first run.
Screenshot of debugging tool failing to show api.leanplum.com call: 
<img width="902" alt="Screen Shot 2019-11-06 at 10 12 06 AM" src="https://user-images.githubusercontent.com/39960812/68402019-87b38000-012f-11ea-9265-9a47c4a3216c.png">

Test Environment Information: iPhone 11 Pro; iOS 13.1.3; Firefox app version is 20.0 (16437)

This behavior has been replicated on 4 separate devices. As Leanplum fails to initialize, the team is unable to identify their test devices in the Leanplum dashboard, and therefore unable to carry out critical QA efforts.

The team has not observed an appreciable decrease in the number of Firefox iOS DAU in the Leanplum dashboard, which would be expected if the Leanplum SDK was failing to initialize for all new users.

**Comment by garvankeeley** [comment]
Can you try on 20.1?

**Comment by lwa-moz** [comment]
@garvankeeley fresh install with 20.1 tested and same result; still no calls detected to api.leanplum.com.

Any idea what could be causing this?

**Comment by garvankeeley** [comment]
Any chance the setting is off for sending usage data? I wouldn't think so if it is a fresh install.

**Comment by lwa-moz** [comment]
"Send Usage Data" enabled in the test case, so we can rule that possibility out.

**Comment by garvankeeley** [comment]
I am using charles proxy also to test on my device, I see leanplum showing up no problems. This is very strange indeed.

**Comment by lwa-moz** [comment]
@garvankeeley suggests that either the work covered [here](https://github.com/mozilla-mobile/firefox-ios/commit/39b199cba9467c43dc80b30e89eeceabb5ce4d4a), or otherwise some geographic restriction, is preventing Leanplum from initializing.

The test device is located in Germany, so I'm fairly certain there's no geographic restriction causing this.

**Comment by garvankeeley** [comment]
Bug is due to locale restrictions, loosen this to init for any EN, DE, FR languages
