### ISSUE TITLE
Firefox for iOS's Top Sites should be in sync with Desktop - I just don't understand why this isn't a thing

### ISSUE THREAD

**Issue by almorithm** [mozilla-mobile/firefox-ios#5740]
Hey there! Thanks for using Firefox!

If you are having issues with using Firefox make sure to check https://support.mozilla.org/en-US/products/ios first

**Comment by athomasmoz** [comment]
Hi, thank you for sharing the feedback! This was previously considered, but we decided to keep them separate for 2 reasons:
* Expect that users have different sites that they typically visit on mobile versus on their desktop
* If there is a common site between the two, we could run into issues with pointing to the desktop URL on mobile or mobile URL on desktop, which would not be a good experience
