### ISSUE TITLE
"Tap to Begin" notfication is displayed after STR

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#5746]
Build: master 90689347
Device: iPad Pro 3rd gen
iOS: 13.1

Preconditions: 
- Logged in to FxA on desktop and iOS device
- On desktop, go to Sync settings and disable bookmark sync

Steps to reproduce:
1. On iOS, go to Settings - > Firefox Account 
2. Enable Bookmark syncing 
3. Sync

Actual results:
- Sync is working fine and the change is reflected across device but "Tap to begin" notification will be displayed periodically on iOS

**Comment by athomasmoz** [comment]
Timebox to a 3 to investigate

**Comment by guilsa** [comment]
FYI, I had Firefox installed on my iPhone iOS 13.3.1 and everything was fine. This issue (continuously getting a "Tap to begin" notification on iPhone) started once I installed FF on my iPad (iOS 11.4) and logged into my FF account from there.

**Comment by athomasmoz** [comment]
@SimonBasca can you check if this is still an issue in Firefox release version?

**Comment by SimonBasca** [comment]
This is no longer reproducible on latest main 524c4b0f4 and latest release version 27.0 (18428)
