### ISSUE TITLE
The App is crashing on accessing a website with Basic Auth enabled

### ISSUE THREAD

**Issue by hugronaphor** [mozilla-mobile/firefox-ios#5757]
Accessing a website with `htpasswd` enabled, leads to the App getting closed/minimized and unusable and can't close or switch to other tabs.

Exact example:
curl -I pubcrawls.club

```
HTTP/1.1 401 Unauthorized
Date: Wed, 13 Nov 2019 22:52:09 GMT
Server: Apache/2.4.18 (Ubuntu)
Cache-Control: no-cache, private
WWW-Authenticate: Basic realm="Hello!"
Content-Type: text/html; charset=UTF-8
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2198)

**Comment by KrystynaKruchkovska** [comment]
Any other details on the problem? Looks fine in my case, checked on master I just got the dialog to provide username/password. What version of Firefox app, what OS?

**Comment by hugronaphor** [comment]
@KrystynaKruchkovska I just rechecked after updating to Firefox version 20.1 (16561).
I now get the "Looks like Firefox crashed..." popup so I can move to other tabs but before I could not.
Still, I can't visit the site.
https://photos.app.goo.gl/9GtmbNg4whzN6Brv7

I'm on iPhone SE, with software version 13.1.3

**Comment by KrystynaKruchkovska** [comment]
Thanks for the details. 

Still, I wasn't able to reproduce with the same version. I tried with simulator and iphone 7s+.

**Comment by csuciu** [comment]
I'm not able to reproduce this issue. I tried on a few different devices including a SE running iOS 13.2. 
@hugronaphor maybe you can get a crash log and post it here.

**Comment by bastien-effetb** [comment]
Hi, same problem here on my Iphone SE (ios 13.5)

But I have the issue only if I'am connected to my firefox account.
I think it is linked to the fact that on my laptop, I saved credentials for the concerned website (but not the basic authentication credentials).
If I go on a website where credentials are not saved for the domain, it is working.
For example if I go on this url : https://jigsaw.w3.org/HTTP/Basic/ (guest, guest), it's working.

If I use the private navigation it's also working.
I'am using lockwise for my password management on the phone.

Please tell me if I can help you to reproduce this case.

**Comment by garvankeeley** [comment]
Confirmed broken for me, STR:
- go to https://jigsaw.w3.org/HTTP/Basic, enter guest/guest and agree to save password
- go to https://jigsaw.w3.org/HTTP/Digest, dialog pops up like in screenshot, tapping 'Log In' just re-shows the dialog, keeps looping and re-showing the dialog.

<img width="728" alt="image" src="https://user-images.githubusercontent.com/5495083/87184358-debcb680-c2b5-11ea-9ca7-8429301a203f.png">

**Comment by datenleck** [comment]
Firefox Daylight 33.0 (4119) is crashing on iOS 14.4.1 on pages with basic authentication (HTTP 401). Since years a disappointing indictment...

**Comment by sommerper** [comment]
I still have it. Is there a workaround?

**Comment by SimonBasca** [comment]
This crash is still occurring on the latest Firefox release version 98.2 and latest main cd20fc4afd. 
@sommerper the workaround would be to delete your saved login for the site that uses basic authentication from Settings -> Login & Passwords and login by manually typing the user and password.

**Comment by sommerper** [comment]
>  delete your saved login for the site that uses basic authentication
But the site actually has both basic authentication and a login page. So basically I should first remove the saved password and then add it again once FF doesn't crash?

**Comment by SimonBasca** [comment]
@sommerper go to Settings -> Login & Passwords search for the login for that page and delete it. After this you can login on that page by manually typing the login and password but don't save the login again. Hope this helps.

**Comment by datenleck** [comment]
For me it works now

**Comment by sommerper** [comment]
@datenleck I just checked, and you're right @datenleck, it works now.
