### ISSUE TITLE
Re-order control in search engine settings is wrong colour

### ISSUE THREAD

**Issue by dnarcese** [mozilla-mobile/firefox-ios#5762]
The re-ordering control icon follows the system theme. When the system theme and app theme are different, the icon is not very visible.
![IMG_0016](https://user-images.githubusercontent.com/11432165/68893865-0beba180-06f4-11ea-8f66-d2b9465cbc42.PNG)

**Comment by SimonBasca** [comment]
Verifying as fix on 21.0 (16901)
