### ISSUE TITLE
Address bar autounfocuses and loses what was typed sometimes after ⌘+Tab, ⌘+T

### ISSUE THREAD

**Issue by ChaiTRex** [mozilla-mobile/firefox-ios#5771]
Firefox will sometimes unfocus the address bar and throw away what was typed soon after a new tab is opened.

0. Connect an external keyboard
0. From another app, press ⌘+Tab to switch to Firefox
0. Press ⌘+T to open a new blank tab
0. Note that the address bar is focused and ready for text entry
0. Begin to type a web address or search query
0. On some occasions, Firefox will very soon after opening the new tab unfocus the address bar and erase its contents, requiring the annoying fix of focusing the address bar again and retyping what had been typed

Here is a [video demonstration (YouTube)](https://youtu.be/37RRFsxuu24).

---

Firefox for iOS 20.1 (16561)
iPadOS 13.2
Logitech K380

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2199)

**Comment by isabelrios** [comment]
Just to highlight that we are seeing similar issues while running the automated tests #5826

**Comment by dnarcese** [comment]
The problem here is that for some reason after clicking command+T and if you keep holding command, a new tab will keep opening. This issue will not occur if you are sure to release both keys after a new tab is opened. You can see in the video demo that 2 new tabs were opened instead of just one.

I will have to keep investigating to see if we are able to change the keyboard behaviour.

**Comment by dnarcese** [comment]
@isabelrios Since you are familiar with the tests, do you know if auto-focusing the address bar on a new tab is a feature on just the iPad? Or do we have that on iPhone as well (if we do, it is broken because I do not see it on my device)?

**Comment by lmarceau** [comment]
Since only `data-sync-user` has commented on the issue after the `Stalebot` GitHub action (which triggered the removal of the `stale` label) I’ll close this issue for now. Please let us know if you think this issue needs to be reopened, we'll gladly do so. Thank you!
