### ISSUE TITLE
Miscellaneous dark mode issues

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/firefox-ios#5774]
From https://twitter.com/swxxii/status/1196268185391181825

(Unclear if we can address all of these)

- [x] 1. White splash screen opening the app
- [x] 2. Typing in address bar bring up light keyboard
- [ ] 3. White flashes in blank pages, before website loads (night mode, not dark mode)
- [x] 4. White tab background when swiping from left edge
- [x] 5. White title bar background when opening settings
- [x] 6. Light keyboard when typing in tab search bar
- [ ] 7. Dark mode not applied to feedback site (webview, won't fix)
- [ ] 8. Dark mode not applied to account settings site (webview, won't fix)
- [ ] 9. Dark mode not applied to Licenses and Your Rights (webview, won't fix)
- [x] 10. Reading mode menu not using dark mode #5783 
- [ ] 11. Reading mode needs a pure black theme (yes please)

Cc to @dnarcese who has been working on a lot of dark mode issues - maybe some of these were already addressed in the upcoming release?

**Comment by swxxii** [comment]
Don’t know if you guys want to know about specific sites that aren’t in dark mode? (imagine that could be a fun game of whack-a-mole) anyway reddit i just noticed.
![91FD802A-E92A-4C16-A9C3-6A7EC9AA5408](https://user-images.githubusercontent.com/11495158/69139861-7b5afa00-0b15-11ea-96f9-68161d65b5c9.png)

**Comment by athomasmoz** [comment]
Need to break remaining items out into individual tickets

**Comment by athomasmoz** [comment]
Closing ticket as issues that were reproducible and we had the ability to fix (ie. not a webview issue) have been resolved.

**Comment by swxxii** [comment]
Thanks team I’m really impressed at your quick response to these! Perhaps 7,8,9 can be addressed with css on those respective  sites?
