### ISSUE TITLE
Move "What's new?" menu item to Settings > Help section.

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#5775]
Logged via : 
https://bugzilla.mozilla.org/show_bug.cgi?id=1596247
https://bugzilla.mozilla.org/show_bug.cgi?id=1583599#c2

User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Safari/605.1.15

Steps to reproduce:

With a recent Firefox update, Mozilla introduce a new menu item called What's new? It's totally useless and annoying. How do I to get in rid of this useless item? You can easily lookup new changes on the AppStore. Who is deciding on new features in Firefox for iOS?

Expected results:

Move "What's new?" menu item to Settings > Help section.

**Comment by athomasmoz** [comment]
Thanks for the suggestion. Closing for now pending further feedback & results on the new feature.
