### ISSUE TITLE
[iPad] Tabs tray layout is not correct when entering split screen

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#5781]
Build 20.2(16690)
Device iPad Air 3
iOS 12.4

Steps to reproduce:
1. Open a few tabs
2. Open Tabs Tray
3. Change the view to split screen

Actual results:
- The tabs tray layout is not correct. After focusing on a tab and opening tabs tray again, the layout will be correct.

**Comment by dnarcese** [comment]
Adding screenshots:

Incorrect layout:
![Simulator Screen Shot - iPad Air (3rd generation) - 2019-12-04 at 16 32 33](https://user-images.githubusercontent.com/11432165/70183432-ca776200-16b3-11ea-97e8-664cf052f813.png)

Correct layout:
![Simulator Screen Shot - iPad Air (3rd generation) - 2019-12-04 at 16 32 47](https://user-images.githubusercontent.com/11432165/70183433-ca776200-16b3-11ea-85da-46b9ac75a960.png)

**Comment by SimonBasca** [comment]
Verifying as fix on master c2574a0a5
