### ISSUE TITLE
Reader mode menu not using dark mode

### ISSUE THREAD

**Issue by dnarcese** [mozilla-mobile/firefox-ios#5783]
Breakout from #5774.

STR:
1. App is in dark theme
2. Open an article in reader mode
3. Open the reader mode options menu
Observe that the menu does not adapt to the dark theme.

![Simulator Screen Shot - iPhone X - 2019-11-20 at 11 11 23](https://user-images.githubusercontent.com/11432165/69255843-8437e400-0b86-11ea-8de7-0d1ffa377fb0.png)

**Comment by SimonBasca** [comment]
Verifying as fix on 21.0 (16901)
