### ISSUE TITLE
FXIOS-182 ⁃ add automated process to screenshot whole app in simulator and upload those for l10n consuming

### ISSUE THREAD

**Issue by lundjordan** [mozilla-mobile/firefox-ios#5787]
@JohanLorenzo - as per stefan's comments. Could be a good first place to look once we are ready to lean in.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2205)

**Comment by isabelrios** [comment]
Let me share some progress/info after conversations with @JohanLorenzo . Two options at the moment for running the screenshots tests have been explored/commented... 
- [Bitrise build ](https://app.bitrise.io/build/24d4619c27440590#?tab=artifacts)running the screenshots test and creating a zip file for each language. 
Just tried with one language, we have to understand how we could run this build for all the locales, time constrain is the main issue here. We have a 90' timeout for the builds. But there are options to run builds/workflows in parallel that we need to investigate.

- Mac Mini in MTV office to run the tests periodically via Jenkins job, for example. 
With this option running the tests at night would be an option so no time constrain in this case. This Mac was used before for running other tests but was reset and needs to be configured from the scratch.

**Comment by isabelrios** [comment]
This was implemented via Taskcluster <-> Bitrise
