### ISSUE TITLE
Push Notifications Opt-In Description

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-ios#5789]
**Vision**

As a user, I want to understand what I'm agreeing to when I'm asked to allow Firefox to send me push notifications & select which push notifications I'm interested in

----

**Acceptance Criteria**

* Before a system prompt to allow push notifications, there is an explanation of why the user should sign up

----

**Notes**

* System prompt shows up after users sign into sync
* Includes landing strings

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2206)

**Comment by bryanbell** [comment]
Mockup: https://mozilla.invisionapp.com/share/S9VCVOGEZCA#/398727031_Artboard

**Comment by athomasmoz** [comment]
@bryanbell Can you add the image files?

**Comment by athomasmoz** [comment]
Mocks: https://mozilla.invisionapp.com/share/S9VCVOGEZCA#/screens/398727031_Artboard

**Comment by lmarceau** [comment]
Since only `data-sync-user` has commented on the issue after the `Stalebot` GitHub action (which triggered the removal of the `stale` label) I’ll close this issue for now. Please let us know if you think this issue needs to be reopened, we'll gladly do so. Thank you!
