### ISSUE TITLE
Push Notification Preferences

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-ios#5790]
**Vision**

As a Firefox for iOS user, I want to change my push notification preferences for what types of notifications I receive from the browser

- - -
**Acceptance Criteria**

* At any time, user can change their preference for push notifications
* Users can choose to receive functional push notifications from accounts and/or marketing notifications

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2207)

**Comment by bryanbell** [comment]
Mockup: https://mozilla.invisionapp.com/share/VCVFY515GFE
