### ISSUE TITLE
Eventual connectivity: "Try again" button, white page when reloading page without connection

### ISSUE THREAD

**Issue by mdr-leon10** [mozilla-mobile/firefox-ios#5795]
Steps to reproduce:

I activated the airplane mode in my phone, try to load a website. The no connection screen appeared. I tapped in the try again button.

Actual results:

The screen was blank, the no internet connection page did not appear again

Expected results:

The no internet connection page should have appear again with the try again button active so the user can try to reload the page.

**Comment by mdr-leon10** [comment]
This issue is related bug 1598490 in bugzilla

**Comment by SimonBasca** [comment]
Verifying as fix on 21.0 (16901)
