### ISSUE TITLE
Background media will stop playing on iOS 13.2.3

### ISSUE THREAD

**Issue by tankmohit** [mozilla-mobile/firefox-ios#5797]
Music/ videos websites like soundcloud or invidio.us crashes in background after few seconds of playback on lock screen. 

Firefox version: Version 20.2 (16690)

**Comment by SimonBasca** [comment]
This is definitely reproducible also in Firefox iOS 21.0 (16981) by:

1. Go to soundcloud.com 
2. Play a video
3. Background the app

Actual results:
- The music will stop playing. No actual crash happens.

Note:
- This is working fine in Safari.

**Comment by dnarcese** [comment]
The OS now kills any background activity after 30 seconds, which is when the audio will stop. This behaviour is out of our control as is there is no available WebKit API to change this. All other browsers (asides from Safari) also have this behaviour.

**Comment by hichana** [comment]
Does anyone know if Apple will allow other browsers, other than Safari, to play media while the screen is locked on iOS? I am hoping to implement react-player in a webapp that plays audio files that are longer than 30 seconds (the point at which audio on Firefox mobile cuts off during lock), and right now the only thing I can think of is to tell my users to use Safari. This seems like a seriously unfair thing for Apple to do.

**Comment by acmpo6ou** [comment]
@dnarcese Interesting, so Safari makes it somehow such that it's not killed 🤔
