### ISSUE TITLE
Whats new page doesn't tell the user when there is no internet connection

### ISSUE THREAD

**Issue by csuciu** [mozilla-mobile/firefox-ios#5798]
Steps to reproduce:

Activate airplane mode, go to what is new on the menu.

Actual results:

A blank page appear

Expected results:

An alert letting the user know that there is no connection to the internet.

Originally filed here: https://bugzilla.mozilla.org/show_bug.cgi?id=1598522

**Comment by LamourBt** [comment]
I can try to take a stab at this.

**Comment by LamourBt** [comment]
@dnarcese is there a specific message that you want to be shown in this alert view? and also should we prevent new tabs from being added if there is no internet.

**Comment by dnarcese** [comment]
> @dnarcese is there a specific message that you want to be shown in this alert view? and also should we prevent new tabs from being added if there is no internet.

pinging @athomasmoz for the answer to this.

**Comment by LamourBt** [comment]
look at this PR #6173 and please let me know if the title or message string should be changed.

**Comment by brampitoyo** [comment]
@LamourBt @dnarcese I wonder if we can show an identical error page – the same one we show when webpages can’t load because there’s no internet connection?

Something like this example:
<img width="320" src="https://user-images.githubusercontent.com/51007/76472630-02ccd000-645b-11ea-95c6-473c97569f44.jpeg">

**Comment by LamourBt** [comment]
@brampitoyo sadly that decision isn't mine to make, but once the maintainers of the project reach on a decision then I would be happy to implement it. (Sorry for the late response)

**Comment by dnarcese** [comment]
@brampitoyo Yes, that looks good to me. @LamourBt Feel free to start implementing that!

**Comment by nbhasin2** [comment]
> Q. should we prevent new tabs from being added if there is no internet.

FYI - Have checked chrome and other browsers and they still allow the users to add new tabs when there is no internet connection and we currently do the same as for us its the home page. If we try to load a new page then we should show a no internet connection page. 

@brampitoyo Thoughts?

**Comment by LamourBt** [comment]
@dnarcese @brampitoyo the wanting behavior is now implemented, you can check out the PR.

**Comment by brampitoyo** [comment]
@nbhasin2 wrote:

> […] chrome and other browsers […] still allow the users to add new tabs when there is no internet connection and we currently do the same […]

Our current behaviour is correct. Even though users aren’t connected to the internet, we still want to allow them to add new tabs. In that scenario, show the connection error page – unless the new tab contains the new tab page. NTP can be shown because it works offline.
