### ISSUE TITLE
URL Doesn't Show in URL Bar Right Away

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-ios#5803]
Filed from review:

"When I put in a new URL and load it, mostly through loading the URL from another app, it doesn’t appear on the URL bar until well along the process of loading the page. Sometimes the pages don’t load at all and then the browser gives up — understandable — but if this happens on Firefox, I lose the URL. So I can’t even refresh or find it in History. In most cases the URL does show up but the delay is annoying when I want to copy the URL. Please fix!"

Version 20.2

**Comment by muhasturk** [comment]
This issue should be fixed in v21.0

Could you please check it? @athomasmoz

**Comment by SimonBasca** [comment]
This is fixed on latest master c2574a0a. It was fixed by #5823 which only landed on master.
