### ISSUE TITLE
Memory leak when opening and closing multiple tabs

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#5807]
Logged via : https://bugzilla.mozilla.org/show_bug.cgi?id=1598699

User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 Safari/537.36

Steps to reproduce:

    Open a new tab
    Load a website on it (e.g. amazon.com)
    Repeat step 1 multiple times (30-50)
    Close all tabs

Actual results:

Memory consumption went from 50MB (app fresh start) to 90MB (app with only 1 empty tab) with all tabs closed, there's clearly a memory leak somewhere in the process.

Expected results:

Memory should have stayed pretty similar to the fresh start instance, somewhere around 50-55MB.

![image](https://user-images.githubusercontent.com/32130829/69558520-0d00b680-0fb1-11ea-89ad-932f8180b876.png)

**Comment by SimonBasca** [comment]
Tested with latest master 6900c147f5c

| Device / iOS | Clean Install  | Open Amazon.com | Open 50 tabs | Close all tabs |
| : ------------- : | :-------------: |:-------------:|:-------------:|
| iPhone 8 (11.4) | 46 MB | 48 MB | 102 MB | 59 MB | 
| iPhone XS max (12.4) | 56 MB | 66 MB | 196 MB | 53 MB | 
| iPhone XS (13.1) | 56 MB | 66 MB | 182 MB | 69 MB |

**Comment by garvankeeley** [comment]
Nice investigation! Based on @SimonBasca 's findings, there is no bug. WKWebView doesn't reclaim memory immediately but it doesn't grow indefinitely
