### ISSUE TITLE
Spike: Permissions for Different Push Notifications

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-ios#5815]
**Vision**

We'd like to split apart permissions for sync push notifications and leanplum (marketing & newsletter style) updates, so that users can use sync without signing up for all notifications

**Acceptance Criteria**

This spike is to answer the questions:
* Can we give users an option of which notifications to opt-in to? How would that work with the system prompt?
* How can we avoid users opt-ing out of all push notifications, when they only mean to opt out of the marketing ones?

**Comment by dnarcese** [comment]
We can add a new settings page for notification control where we give the user the option to opt-in/out of sync notifications and leanplum notifications. We can show our own dialog before the system opt-in dialog that explains what the notifications are for and links to the settings page.

If a user opts out of leanplum notifications, it is possible to shutdown leanplum for that user until they opt back in.
