### ISSUE TITLE
Firefox loses URL when opening a link in a new tab without internet connection

### ISSUE THREAD

**Issue by GeckoEidechse** [mozilla-mobile/firefox-ios#5823]
**Expected result:**

When opening a link in a new tab without internet connection the link should pertain and not get lost.

**Actual result:**

Opening a link in a new tab without a network connection causes the address bar to be empty, therfore "losing" the URL.

**Steps to reproduce:**

Go to any website, turn on airplane mode to ensure no internet connection, long press a link and select "_Open in New Tab_". Now when switching to the tab that just opened both the site as well as the addres bar are empty.

**Additional information**

* Observed this issue ever since I started using Firefox a few months ago. The issue is still present in the newest version 20.2 (16690)

* Safari and Brave do not encounter this issue.

* Most likely closely related to #5803

***

Finally the issue is especially frustrating when browsing through a site while e.g. on the train, while opening a few links from the site in a new tab to read later.
If you now pressed "open in a new tab" while traveling through an area with no reception, the tab will not only not be loaded but worse the URL will be lost and cannot be recovered. You will have to go through the previous site again to find it unless you already closed it or the site updated its content.

**Comment by muhasturk** [comment]
It will be fixed when #5861 merged.

**Comment by SimonBasca** [comment]
Verified as fix on master c2574a0a. Opening a link in a new tab without internet connection will display the URL in the new opened tab.
