### ISSUE TITLE
Send tab: if push notifications enabled at late stage, re-register for fxa push

### ISSUE THREAD

**Issue by garvankeeley** [mozilla-mobile/firefox-ios#5837]
It appears in the code that if the user opts out of push notifications initially and then later opts in, they aren't registered for FxA push.

Possibly also validate the apns state is properly in-sync (not sure how to do this exactly).

This may account for the problem of 
<img width="368" alt="image" src="https://user-images.githubusercontent.com/5495083/69887740-6c630d00-12b6-11ea-83d6-7a6dabdfe964.png">

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2216)

**Comment by lmarceau** [comment]
Since only `data-sync-user` has commented on the issue after the `Stalebot` GitHub action (which triggered the removal of the `stale` label) I’ll close this issue for now. Please let us know if you think this issue needs to be reopened, we'll gladly do so. Thank you!
