### ISSUE TITLE
[useragent] YouTube Videos can’t played in fullscreen due to UA on iPad

### ISSUE THREAD

**Issue by F3000** [mozilla-mobile/firefox-ios#5838]
Please see the error message in the attached photo :

![F2C75C3C-F21F-4E2D-BC45-CF3BCB2E22AE](https://user-images.githubusercontent.com/8161283/69907228-631a9300-13d1-11ea-99df-f7f893f94abd.jpeg)

**Comment by muhasturk** [comment]
Clould you

**Comment by F3000** [comment]
Trie this one : https://www.youtube.com/watch?v=6pXYQ5gaPuk

**Comment by muhasturk** [comment]
It can be opened in fullscreen mode. If some embedded youtube videos did not opened fullscreen mode, because of web developer configured their iframe without allowfullscreen attribute.

So this issue is not related Firefox and can be closed.

**Comment by F3000** [comment]
I don’t think that every video producer out there did this . Every video I watch it’s the same . 


Can you send me a video that I can watch in fullscreen please ?

**Comment by muhasturk** [comment]
I can watch your posted video url in fullscreen mode. If you can't please send video that shows you could not watch in fullscreen mode in Firefox to prove it.

**Comment by F3000** [comment]
Is that proof enough ?

https://gofile.io/?c=DvzAAa

**Comment by muhasturk** [comment]
Can please share your device model, OS version and Firefox version?

**Comment by F3000** [comment]
FF 20.2 on iPad Pro 2018 , iPad os 13.2.3 

and on 

FF 20.2 on iPhone 11 Pro . iOS 13.2.3

**Comment by yusadogru** [comment]
Fullscreen mode activate after change customUserAgent to **"Mozilla/5.0 (iPad; CPU OS 13_2_3 like Mac OS X) AppleWebKit/605.1.15"** from **"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15) AppleWebKit/605.1.15"** 
On iPadOS user agent is same as on MacOS :( Also this issue discussed in apple developer forum. (https://forums.developer.apple.com/thread/119186) 

cc: @garvankeeley

**Comment by muhasturk** [comment]
@garvankeeley This problem still exist, could please provide detail about it?

**Comment by garvankeeley** [comment]
I am now seeing the issue also, on iPad the button to go fullscreen is not available.

**Comment by dnarcese** [comment]
Some things I found after a bit of investigation:
- on iphone safari, request desktop site on youtube - the video automatically goes to fullscreen and wont even play if it is minimized, as soon as you click play it maximizes
    - Fx also does that on iphone
- on ipad safari, you can play youtube video minimized and fullscreen
- adding `version` and removing `fxios/` in user agent did not fix the fullscreen problem
- safari  UA when requesting desktop site is same as the Fx ipad default
 `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.5 Safari/605.1.15`

**Comment by yusadogru** [comment]
if we use `(iPad; CPU OS 13_3 like Mac OS X)` instead of `(Macintosh; Intel Mac OS X 10.15)` on iPad, we can play youtube video fullscreen.

`Mozilla/5.0 (iPad; CPU OS 13_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) FxiOS/18.0 Mobile/15E148 Safari/605.1.15`

**Comment by nbhasin2** [comment]
Hi @yusadogru, thanks for finding the user agent that works with full screen youtube. However the useragent with "iPad" takes the user to mobile website of youtube

**Comment by yusadogru** [comment]
Hi @nbhasin2, i know this ua for mobile. But only work fullscreen like this :( 
Ps: I guess Chrome use ua with “iPad” :)

**Comment by csuciu** [comment]
Verified as fixed on latest master and Beta v24.0(17528). Youtube videos can be played in full screen.
