### ISSUE TITLE
Top Site icons change colors

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/firefox-ios#5839]
After updating to beta version 22.0 (16814), at least two generated "color swatch" thumbnails in my Top Sites change color. Specifically the thumbnail for https://news.ycombinator.com/news bookmark was orange yesterday and then pink, green, and now turquoise.

I'm running iOS 13.2.3 on an iPhone 8. I do not have Dark Mode enabled inn my system settings.

**Comment by cpeterso** [comment]
This bug sounds similar to #4698 butt I only noticed this bug starting yesterday.

**Comment by garvankeeley** [comment]
So odd! https://news.ycombinator.com/news has a favicon (Y on an orange background), but it sounds like it is behaving like it is having to 'generate' a favicon, which will assign background color based on the hash of the URL (and thus should be stable).

**Comment by cpeterso** [comment]
After I reported this bug yesterday, the icon seemed to stay the proper orange Y favicon. But after updating to beta version 21.0 (16860), I see the problem again. If I manually swipe-to-kill Firefox Beta in the iOS task switcher and relaunch Firefox Beta and open a new tab, the Y icon will change to a different random color.

**Comment by garvankeeley** [comment]
I am seeing this also, upping to a P2
