### ISSUE TITLE
library panel buttons are cut off on ios 12

### ISSUE THREAD

**Issue by nbhasin2** [mozilla-mobile/firefox-ios#5844]
The bottom bar in history tab is cut off for older model of iPhone (Eg. 6plus, 8plus)

Tested so far on 6 plus and 8 plus. The result is same. It appears normal on iPhone X. 

See below for cutoff image: 

![image](https://user-images.githubusercontent.com/8919439/70001140-84db5d80-152a-11ea-95f7-d4971523898e.png)

**Comment by nbhasin2** [comment]
After doing investigation this in theory should work fine but will need QA verification. 
While testing in iPhone Simulator (6plus, 8plus) I found that the condition that deals with fixing the bottom cutoff just doesn't work in Simulator. 

I would highly recommend if someone has an older iOS 12.x, iPhone 6 plus or 8 plus device please run the latest firefox beta.

**Comment by nbhasin2** [comment]
Steps to reproduce:
On iPhone 6, 6Plus, 8, 8Plus 
- Install latest firefox 
- Tap on hamburger menu 
- Tap on Your library 

Make sure the view is not cutoff on iOs 12.x and 13.x

**Comment by csuciu** [comment]
I tested this issue on latest master/beta and was able to reproduce it on both versions on an iPhone 7 running iOS 12.3.1.
The issue does not reproduce on similar devices running iOS 13.x

**Comment by isabelrios** [comment]
As per a conversation with @csuciu offline, looks like iPhone SE (iOS12) is not showing that menu at all, @nbhasin2 is that intentional? or maybe related to this issue too?

**Comment by nbhasin2** [comment]
@isabelri It might be related to this issue. Let me try on other devices as well. Thanks @csuciu for testing on a real device.

**Comment by garvankeeley** [comment]
iPhone SE doesn't show the text on the buttons, by-design. There is no room for the text.

**Comment by csuciu** [comment]
Verified as fixed on latest Beta.
