### ISSUE TITLE
Remove custom add search engine button in keyboard

### ISSUE THREAD

**Issue by dnarcese** [mozilla-mobile/firefox-ios#5848]
The button is raising a few other bugs (#5442 #5712) and was a hack that does not work reliably.
Removing this button does not remove the feature of adding custom search engines, it just removes an entry point to that functionality.
![Simulator Screen Shot - iPhone X - 2019-12-03 at 14 37 08](https://user-images.githubusercontent.com/11432165/70083474-6df44400-15da-11ea-839b-cb9348456b53.png)

**Comment by SimonBasca** [comment]
Verifying as fix on 21.0 (169181).
