### ISSUE TITLE
[XCUITests] Update tests after #5848 - Remove add search engine button from keyboard

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/firefox-ios#5858]
There are a few tests, [ThirdPartySearchTests](https://github.com/mozilla-mobile/firefox-ios/issues/5848)that check or use this [functionality](https://github.com/mozilla-mobile/firefox-ios/blob/master/XCUITests/ThirdPartySearchTest.swift#L109), they should be removed/updated once this PR lands.

**Comment by SimonBasca** [comment]
Fixed by 6c15c3de8c9f1ced9d7c340be8c7e00546343807
