### ISSUE TITLE
Disable url dragging on iPhones

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/firefox-ios#5859]
## Steps to reproduce
1. Launch Firefox.
2. Open any website.
3. Tap on the URL bar once.
4. The URL selected.
5. Without deselecting, it, tap and hold on the URL bar.

### Expected behavior
The magnifying glass(zoomed in on the URL bar) should be displayed.
### Actual behavior
A white bar is displayed over the URL bar(it can be dragged).
### Device information

* iOS device: **iPhone Xs Max(iOS 12.4)**
* Firefox version: **v21.0(16860)**

### Notes
- Note that if I do the same steps and then I tap once on the URL bar to deselect it, the correct behavior is displayed and the magnifying glass is displayed with a zoom effect on the URL bar.
- This issue occurs only when trying to hold a tap on the selected URL.
- Note that I tried this on **Safari** and **Chrome** but I couldn't reproduce it while the URL was selected, the magnifying glass was displayed from the first time.

![ezgif-6-29431ff95dde](https://user-images.githubusercontent.com/42831109/70227522-69a36480-175b-11ea-9502-6c22ce3b06fb.gif)

**Comment by athomasmoz** [comment]
Suspect that other browsers disable the ability to drag & drop the link. Should we do that as well?

**Comment by athomasmoz** [comment]
Plan: let's disable the ability to drag & drop unless on iPad, where the feature could be useful for split screen

**Comment by abodea** [comment]
Verified as fixed on the latest **master** build with **`iPhone Xs Max(iOS 12.4)`.**
Note that the magnifying glass is correctly displayed now on the phones no matter if the URL is selected or not.
Also, note that on the iPads this has the correct behavior and the URL can be dragged for split-screen.
