### ISSUE TITLE
The Reading list text is not fully displayed in landscape mode

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/firefox-ios#5862]
## Steps to reproduce
1. Launch Firefox.
2. Reach the `Reading List` section.
3. Turn the device in landscape mode.

### Expected behavior
The `Reading list` text should be displayed in the center or a little bit upper than the actual position.
### Actual behavior
Half of the text is behind the Library Panel Shortcuts in landscape mode, and the section cannot be scrolled.
### Device information

* iOS device: **iPhone Xs Max(iOS 12.4)**
* Firefox version: **v21.0(16860)**

![unnamed (1)](https://user-images.githubusercontent.com/42831109/70236969-b2184d80-176e-11ea-8bb5-af122309c979.jpg)
**And the full text displayed in portrait mode.**
![unnamed](https://user-images.githubusercontent.com/42831109/70236976-b5abd480-176e-11ea-98d6-c768de738022.jpg)

**Comment by csuciu** [comment]
Verified as fixed on master c2574a0.
