### ISSUE TITLE
Synced Tabs section color is incorrectly displayed for Light(iOS 12.x) and Dark(iOS 13.x) themes

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/firefox-ios#5863]
## Steps to reproduce
1. Launch Firefox.
2. Reach the library section `Synced Tabs`:
   - Case 1 using iPhone Xs(**iOS 13.2.2**) - with **dark theme on**
   - Case 2 using iPhone Xs Max(**iOS 12.4**) - with **light theme on**
3. Scroll the section.

 ### Expected behavior
The `Synced tabs` section is displayed in the right color.
### Actual behavior
The `Synced tabs` section color is incorrectly displayed.
### Device information

* iOS device: **iPhone Xs Max(iOS 12.4), iPhone Xs(iOS 13.2.2)**
* Firefox version: **v21.0(16860)**

### Notes
Note that the other sections are correctly displayed.
- On the iPhone Xs Max(**iOS 12.4**)  - with **dark theme on** - the colors are correctly displayed.
- On the iPhone Xs(**iOS 13.2.2**) - with **light theme on** - the colors are correctly displayed.

iPhone Xs(**iOS 13.2.2**) - with **dark theme on** 
![Screen Shot 2019-12-05 at 15 22 02](https://user-images.githubusercontent.com/42831109/70240142-5ac9ab80-1775-11ea-9b01-9628864de3c0.png)

 iPhone Xs Max(**iOS 12.4**) - with **light theme on**
![unnamed (2)](https://user-images.githubusercontent.com/42831109/70240157-61f0b980-1775-11ea-8b0f-4c85c011cb54.jpg)

**Comment by athomasmoz** [comment]
@SimonBasca Can you check if re-opening app make a difference? And what the theme setting is when this happens

**Comment by SimonBasca** [comment]
@athomasmoz After manually switching the theme from Light to Dark or vice versa the Synced tabs section color is incorrectly displayed. Restarting the app will cause the "Synced Tab" screen to refresh and the correct color will be displayed until the theme is changed again.

**Comment by csuciu** [comment]
Verified as fixed on master c2574a0.
