### ISSUE TITLE
Bookmarks wraps on iPhone SE

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla-mobile/firefox-ios#5864]
Low priority, as the phone was discontinued a year ago, but we should probably make sure that this doesn't wrap on an iPhone SE. Less margin between items?

![image](https://user-images.githubusercontent.com/68213/70254959-f21e0700-1753-11ea-9335-bb09258583be.png)

**Comment by garvankeeley** [comment]
We still support 64-bit iPhone 5

**Comment by athomasmoz** [comment]
Let's set up an overflow rule where it adds ellipses when string is too long
