### ISSUE TITLE
If the webpage has low-res favicon, displaying lower quality icons in Top Sites

### ISSUE THREAD

**Issue by yusadogru** [mozilla-mobile/firefox-ios#5866]
If the webpage has low-res favicon, that logo is displaying in low resolution in Top Sites. So this makes it look bad in the home page. In other browsers like Safari it's better this situation.

![Group](https://user-images.githubusercontent.com/19792753/70273832-085fad80-17bc-11ea-90b2-e4cff82953cd.png)

**Comment by SimonBasca** [comment]
Verifying as fix on master c2574a0
