### ISSUE TITLE
The `Switch` button from the toast notification is too small

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/firefox-ios#5869]
## Steps to reproduce
1. Launch Firefox.
2. Open any website.
3. Long tap on a link from the website.
4. Tap on the `Open in new tab`.

 ### Expected behavior
The `Switch` button from the toast notification should be bigger and have a better position.
### Actual behavior
The `Switch` button from the toast notification is too small.
### Device information

* iOS device: **iPhone Xs Max(iOS 12.4), iPhone Xs(iOS 13.2.2)**
* Firefox version: **v21.0(16860)**

### Notes
Note that sometimes the users can tap by mistake a little bit near the button and they will not be redirected to the page.
The toast can look better and having bigger buttons when the bottom bar is hidden.
Also, the `New tab oepend` text can be resized.
![unnamed (3)](https://user-images.githubusercontent.com/42831109/70315180-b5b8dc80-1821-11ea-8193-c1e34dc801aa.jpg)

![unnamed (4) - Copy](https://user-images.githubusercontent.com/42831109/70314876-0e3baa00-1821-11ea-9a1c-10b1cba46e76.jpg)

![unnamed](https://user-images.githubusercontent.com/42831109/70315579-90789e00-1822-11ea-8451-17f57a77159f.jpg)

**Comment by muhasturk** [comment]
In portrait mode Switch button position and size seems ok for me. Maybe we could make it bigger and with right margin in landscape mode.

**Comment by csuciu** [comment]
Verified as fixed on master c2574a0.
