### ISSUE TITLE
[iPad][iOS 12.x] Library panel buttons are cut off

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#5877]
Device: iPad Air 2
iOS: 12.3
Build: 21.0 (16901)

Steps to reproduce
1. Go to Library pane

Actual results:
- Library panel but labels are cut. 

Note:
- Issue also reproducible on master 13c33989cd7b
- Not reproducible on iPhone
![Screen Shot 2019-12-09 at 5 59 09 PM](https://user-images.githubusercontent.com/32130829/70451219-a1890f80-1aad-11ea-805a-10c9a59dce74.png)

**Comment by garvankeeley** [comment]
Looks ok on iOS 12 sim
<img width="1030" alt="image" src="https://user-images.githubusercontent.com/5495083/70472499-2f103380-1a9d-11ea-9cbb-6fd585ae44e9.png">

**Comment by garvankeeley** [comment]
Repro'd on iPad 3rd Gen 12.4 Simulator

**Comment by muhasturk** [comment]
![Simulator Screen Shot - iPad Air 2 - 2019-12-10 at 00 05 54](https://user-images.githubusercontent.com/4077401/70472852-e67a6980-1ae0-11ea-8e99-af3c91b787ac.png)

Broken on iPad Air 2 iOS 12.4

**Comment by garvankeeley** [comment]
Also broken on iPad Air 13.2.2 Sim

**Comment by SimonBasca** [comment]
Verifying as fix on 21.0 (16918)
