### ISSUE TITLE
Dragging and dropping a tab in the tabs tray search field is not possible

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#5887]
Build: 21.0 (16814)
Device: iPad Pro
iOS: 13.1

Steps to reproduce:
1. Open a tab and go to twitter.com
2. Open a new tab and go to google.com
3. Open Tabs Tray
4. Long press and drag one tab to the search field

Actual results:
- The tab is draggable to the search field but dropping it in the search field does not conduct the search for the specific tab

Expected result:
- Dropping a tab in the search field should be possible.

Note:
- Last good build 20.2 (16690)
[Untitled.mp4.zip](https://github.com/mozilla-mobile/firefox-ios/files/3945137/Untitled.mp4.zip)

**Comment by athomasmoz** [comment]
This could be a side effect of the change we had to make to fix dragging tabs in iOS 13. Marking as won't fix
