### ISSUE TITLE
[iOS 13]QR code frame is not aligned

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#5888]
Build: 21.0 (16814)
Device: iPad Pro
iOS: 13.1

Steps to reproduce:
1. Tap on the URL bar
2. Tap on the QR code

Actual results:
- The QR code frame is not alligned

![061B4C33-64C3-4189-AD84-8B12BD3BB8CA](https://user-images.githubusercontent.com/32130829/70534893-a9f05180-1b64-11ea-8412-34b80b6d04b1.jpg)

**Comment by yusadogru** [comment]
Also QRView frame is not aligned in landscape

![IMG_1935](https://user-images.githubusercontent.com/19792753/70598930-13bc3a00-1bfd-11ea-9b0d-614c28f3adc4.png)
![IMG_6964](https://user-images.githubusercontent.com/19792753/70598932-13bc3a00-1bfd-11ea-962a-25d20a66a9d5.png)

**Comment by SimonBasca** [comment]
Verifying as fix on master c2574a0a5
