### ISSUE TITLE
Weird Firefox Sync "DEBUG: Not delivered" notification

### ISSUE THREAD

**Issue by reuben** [mozilla-mobile/firefox-ios#5890]
Saw this today after some connectivity drops (WiFi died due to power outage). The notification appeared a little while after I connected to WiFi again. Not sure if it's related at all but sharing just in case. Screenshot attached below:

![IMG_5349](https://user-images.githubusercontent.com/477142/70542654-62b88f80-1b69-11ea-8e18-c977775d74be.jpg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2222)

**Comment by reuben** [comment]
(Tapping it opened the browser but didn't do anything visible once inside.)

**Comment by garvankeeley** [comment]
Thanks for reporting! This is a message only on Beta to help us debug sync issues. I am not sure what message means, but getting these reports is a start.

**Comment by athomasmoz** [comment]
Copy to sync team board for prioritization https://jira.mozilla.com/browse/SYNC-568

**Comment by isabelrios** [comment]
As commented during triage, I'm seeing similar message: `DEBUG: Error not Decrypted` on my iPhone 6s.
This is happening when I sign in in Lockwise (android) having my firefox-iOS signed in with my account.
@athomasmoz should I comment in that jira issue you copied above too? Thanks

**Comment by athomasmoz** [comment]
Yes please @isabelrios , thanks!

**Comment by lmarceau** [comment]
Since only `data-sync-user` has commented on the issue after the `Stalebot` GitHub action (which triggered the removal of the `stale` label) I’ll close this issue for now. Please let us know if you think this issue needs to be reopened, we'll gladly do so. Thank you!
