### ISSUE TITLE
Sync server's info/configuration limits aren't respected

### ISSUE THREAD

**Issue by pjenvey** [mozilla-mobile/firefox-ios#5896]
Sync servers provide a configuration of size limits enforced by the server at their [`info/configuration` endpoint](https://github.com/mozilla-mobile/firefox-ios/blob/875829d/Sync/Info.swift#L55).

Sync clients should query the server for these limits. AFAICT (and I'm not familiar with this code base so please correct me if I am wrong) this does not happen, instead the limits are [hardcoded](https://github.com/mozilla-mobile/firefox-ios/blob/dcecbb0/Sync/StorageClient.swift#L637) to the current server's values.

The new Durable Sync storage service lowers a couple of these configuration limits (so far `max_total_records` and `max_total_bytes`), making the hardcoded values incorrect. This can cause clients to always fail at writing sync batches of larger sizes.

**Comment by tublitzed** [comment]
@pjenvey - do we know at what number the batches fail for iOS? I ask as I'm seeing my 3k+ bookmarks collection work ok, so curious if you've narrowed down a ballpark threshold for failure?

It'll make this one easier to verify as fixed once this goes live.

**Comment by st3fan** [comment]
If there is an urgency for this change, could we consider to hardcode the lower limits that durable sync prefers instead of querying `/info/configuration`? That is obviously not a long term solution but may be the only thing that fits in a schedule right now.

**Comment by tublitzed** [comment]
@pjenvey - what's your level of confidence that the new ~1600 limit isn't going to need another change in the near future?

**Comment by athomasmoz** [comment]
Note: this is blocking a release for durable sync targeted for Jan 13th.

**Comment by garvankeeley** [comment]
I am not sure what endpoint to use, I tried the sync endpoint used for me,
`curl https://sync-612-us-west-2.sync.services.mozilla.com/1.5/info/configuration`,
and it returns nothing.

**Comment by athomasmoz** [comment]
@tublitzed Can you confirm that we should do the short-term fix to hard code the limit? And what the limit should be?

**Comment by tublitzed** [comment]
@athomasmoz - yes; short term fix is good for now. Let's doublecheck with @pjenvey to confirm, but pretty sure that limit should be `1666`.

**Comment by pjenvey** [comment]
That's right, the new server's limit is `1666`.

**Comment by garvankeeley** [comment]
@pjenvey for a longer term fix we can work in parallel on getting the info from the endpoint. Any idea what that URL looks like? I tried here and failed https://github.com/mozilla-mobile/firefox-ios/issues/5896#issuecomment-567957395

**Comment by pjenvey** [comment]
> @pjenvey for a longer term fix we can work in parallel on getting the info from the endpoint. Any idea what that URL looks like? I tried here and failed [#5896 (comment)](https://github.com/mozilla-mobile/firefox-ios/issues/5896#issuecomment-567957395)

The URL: https://`<sync-server>`/1.5/`<uid>`/info/configuration

It requires auth (a valid header derived from creds issued from tokenserver).

**Comment by garvankeeley** [comment]
Hmm, ok, I don't see how to hook that up in the existing code. Anyway, this code is being replaced by app-services rust component which I assume does this correctly.
