### ISSUE TITLE
'Add search engine' fields will be cleared while typing of the theme changes

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#5901]
Build: 21.0(16981)
Deice: iPhone Xr
iOS: 13.1

Pre-conditions:
- Go Setting -> Theme and set the theme to Automatically

Steps to reproduce
1. Go to Settings -> Search -> Add search engine
2. Type something in the fields
3. Wait for the theme to change or change the brightness of the iPhone

Actual results: 
- The fields will be cleared and the placeholder texts will not be displayed. 

Note:
- Going back to Setting and back to 'Add search engine' will display the placeholder text.

[Video.mp4 2.zip](https://github.com/mozilla-mobile/firefox-ios/files/3954764/Video.mp4.2.zip)

**Comment by nishant2718** [comment]
Hey, I'd like to give this a shot. I see that it's a production issue as well (iPhone 7, iOS 13.3). I will update as I make progress.

**Comment by nishant2718** [comment]
A PR's been raised for this issue - will keep this thread updated:
https://github.com/mozilla-mobile/firefox-ios/pull/6196

**Comment by nishant2718** [comment]
Here's a PR that addresses both the user input & the placeholder text being cleared when the theme changes. https://github.com/mozilla-mobile/firefox-ios/pull/6236

**Comment by csuciu** [comment]
Verified as fixed on master e5d00ff.
