### ISSUE TITLE
Error shown: UIView.isHidden must be used from main thread only

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/firefox-ios#5904]
This error is shown in [URLBarView.swift L#587](https://github.com/mozilla-mobile/firefox-ios/blob/master/Client/Frontend/Browser/URLBarView.swift#L587) when running for example this [integration test](https://github.com/mozilla-mobile/firefox-ios/blob/master/XCUITests/IntegrationTests.swift#L60). 

The error appears when the app is launched and the HomeScreen tab is shown, then the test finishes with this error.

Although nothing is seen manually or when running other tests, I'm wondering if this could cause any other issues, cc @garvankeeley

**Comment by garvankeeley** [comment]
This should have fixed it https://github.com/mozilla-mobile/firefox-ios/commit/8510feb1b048726cf5b227bdd172f345b74b5e2e
