### ISSUE TITLE
V21 splash screen not respecting dark mode

### ISSUE THREAD

**Issue by mofman** [mozilla-mobile/firefox-ios#5908]
Despite v21 apparently providing a dark splash screen this doesn’t appear to be the case.

**Comment by mofman** [comment]
![Demo](https://user-images.githubusercontent.com/3038169/70749685-c2a76580-1d24-11ea-914d-fc4f591c0f41.gif)

**Comment by dnarcese** [comment]
I believe current behaviour is that the splash screen follows the system theme and not the app theme.

**Comment by mofman** [comment]
Watch my gif, notice phone keypad is in dark mode and Firefox is in dark mode when it launches, yes splash screen is white

**Comment by csuciu** [comment]
This works fine for me on v22. 
@mofman Please reopen if you can still reproduce.

**Comment by mofman** [comment]
Yes this still happens on my phone running v22

**Comment by csuciu** [comment]
Can you please provide some info about your configuration (device/OS). Also, my understanding is that the system theme is set to dark and Firefox is set to follow the system setting. Is that correct?

**Comment by mofman** [comment]
deleting app and reinstalling fixed this issue for me...
