### ISSUE TITLE
Long email for fxa is shown with smaller text in Browser Tab Menu

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/firefox-ios#5910]
Seen on: Latest master, iPad Air (3rd generation)
**Steps**
Log in fxa with a long email
Go to Browser tab  menu

**Actual**
See screenshot attached:
![Screenshot 2019-12-13 at 11 15 51](https://user-images.githubusercontent.com/1897507/70793189-1359a580-1d9b-11ea-9fb4-471904ed96ab.png)

**Expected**
I guess there should be ellipsis to fit the text with same size as the other menu elements

**Comment by athomasmoz** [comment]
@bryanbell What are your thoughts here? Is it better to shrink the text or add ellipsis?

**Comment by brampitoyo** [comment]
@isabelrios It’s better to add ellipsis here, not shrink the text.

**Comment by isabelrios** [comment]
Yeah @brampitoyo I agree with you on adding ellipsis there. @athomasmoz what's you opinion about this?
Thanks!

**Comment by athomasmoz** [comment]
Sounds good, thanks for the detailed response & justification Bram!

**Comment by noorhashem** [comment]
When I tried to run it on iPad Air (3rd generation), it seems like it reflows to the next line. Which is one of the solutions suggested. So should we add ellipsis now? I can try to work on that.
![image](https://user-images.githubusercontent.com/11700198/77799283-20b24b80-707d-11ea-974e-b053217f8715.png)

**Comment by noorhashem** [comment]
I fixed it by adding ellipsis as discussed [Here](https://github.com/mozilla-mobile/firefox-ios/pull/6324) Please let me know if the decision to handle it differently is made.

**Comment by csuciu** [comment]
Verified as fixed on master 8350f11e3d. Ellipsis are now shown on the side of the text (email & display name)
