### ISSUE TITLE
[UX] Strict ETP Evangelism

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-ios#5913]
**Vision**

A design in place that educates users on ETP, especially that it will reduce ads

**Design Goals**

* Re-position strict ETP based on value prop to reduce ads
* Make strict ETP option more visible to users
* Educate users on the risk of site breakage and how to turn it off if a site doesn't work, rather than switching browsers

**Comment by bryanbell** [comment]
Mockups: https://mozilla.invisionapp.com/share/MUVVVLX9C35
