### ISSUE TITLE
Update Settings Page for ETP

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-ios#5926]
**Vision**

As a user, I want to understand the difference ETP options, so that I can choose the appropriate level of protection for me

----

**Acceptance Criteria**

* Tracking Protection settings page is updated to match new design & wording
  * [Mock with Strings](https://share.goabstract.com/c84b39fa-8ea8-465c-80d6-5fca21b28b6e)
  * Note: Learn more link still pointed to SUMO page currently linked
* Pop-up alert added when user turns on strict to inform them that it could cause site breakage & how to disable if needed
  * [Mock with Strings](https://share.goabstract.com/c84b39fa-8ea8-465c-80d6-5fca21b28b6e)
  * Note: "shield" should be added as alt text for icon
* Tracking is still in place to measure usage of each

**Comment by bryanbell** [comment]
Mockup: https://share.goabstract.com/c84b39fa-8ea8-465c-80d6-5fca21b28b6e?
