### ISSUE TITLE
“Use System Light/Dark Mode” is truncated

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla-mobile/firefox-ios#5934]
The “Use System Light/Dark Mode” toggle is not wrapping, and is thus truncated in French in v21.0
(cc @Delphine)

![IMG_6010](https://user-images.githubusercontent.com/1294206/71178850-4dc9b380-226f-11ea-8cea-9258b6eb90be.PNG)

**Comment by athomasmoz** [comment]
@bryanbell What should be the strategy for longer strings here? Does it make sense to truncate or wrap and how does that align with strings in other parts of the app? In other places in the app, there's a shorter title and description below.

**Comment by TheoChevalier** [comment]
If this helps, a similar case has been fixed here https://github.com/mozilla-mobile/firefox-ios/issues/5714

**Comment by djnivek** [comment]
Does this bug really needs an UX since #5714 is similar ?

**Comment by djnivek** [comment]
> Does this bug really needs an UX since #5714 is similar ? I think that we can resolve it by deleting lines limitation

@TheoChevalier

**Comment by TheoChevalier** [comment]
> > Does this bug really needs an UX since #5714 is similar ? I think that we can resolve it by deleting lines limitation
> 
> @TheoChevalier

I think this is accurate, but this is not my call to make

**Comment by brampitoyo** [comment]
When a text label absolutely can’t be short, iOS solves the problem by reflowing to the next line.

<img width="320" src="https://user-images.githubusercontent.com/51007/76380148-eecf9280-63b6-11ea-883f-9070726f28e4.jpeg"> <img width="320" src="https://user-images.githubusercontent.com/51007/76380149-f0995600-63b6-11ea-8a2c-dc731e875ae7.jpeg">
<img width="320" src="https://user-images.githubusercontent.com/51007/76380154-f3944680-63b6-11ea-9348-b299cd15fbda.jpeg"> <img width="320" src="https://user-images.githubusercontent.com/51007/76380160-f55e0a00-63b6-11ea-92af-d710459f4aac.jpeg">

@djnivek is this what you meant by “deleting lines limitation”? If so, then it sounds like a sensible approach.

**Comment by SimonBasca** [comment]
Verified fix on 28.0(18778)
