### ISSUE TITLE
FXIOS-213 ⁃ [XCUITests] New failures after Xcode 11.3 update

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/firefox-ios#5937]
There are several test suites affected:
-Tracking Protection: failure to open ETP menu from website
-Translation: Not possible to tap on the snackbar menu when loading a test site, it is possible if the site is a real one
-SyncUI: Elements in the fxa login view are not seen by the tests and so tests fail due to error in asserting the view/typing in Email field and similar
-Navigation: tests related with previous features (sync)
-HomePageSettings: error when trying to go to BrowserTabMenu

Investigating these issues and disabling the tests in the meantime...

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-213)

**Comment by isabelrios** [comment]
NewTabSettings: testChangeNewTabSettingsShowCustomURL, value in text field is not udpated with url value.

**Comment by isabelrios** [comment]
Here a list of disabled/modified tests:
-testSearchEngine
-testChangeNewTabSettingsShowCustomURL
-testBookmarksAwesomeBar -> Disabled
-testTopSitesOpenInNewPrivateTabDefaultTopSite
-testTopSitesRemoveAllDefaultTopSitesAddNewOne
-testSetCustomURLAsHome
-testSetFirefoxHomeAsHome -> Disabled
-testTypeOnGivenFields-> Disabled
-testCreateAnAccountLink
-testShowPassword
-testSyncUIFromBrowserTabMenu
-testSnackBarDisplayed
-testTranslationDisabled
-testTranslateBing

**Comment by isabelrios** [comment]
These are the tests still having a workaround or being disabled due to iOS 13.3. The rest were fixed after the 13.4 update. Most of these could be fixed too but not done yet.
-testSearchEngine
-testChangeNewTabSettingsShowCustomURL
-testBookmarksAwesomeBar -> Disabled
-testTopSitesOpenInNewPrivateTabDefaultTopSite
-testSetCustomURLAsHome
-testSetFirefoxHomeAsHome -> Disabled

**Comment by AaronMT** [comment]
I will try these out on Xcode 11.6 and see if they still fail on simulator. I'll post a PR for the ones that pass.
