### ISSUE TITLE
Land Strings for v22 Cover Sheet

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-ios#5938]
**Vision**

We want to land the strings for the cover sheet that will describe updates in the v22 release, so that we can get them localized in time for v22

**Acceptance Criteria**

* Strings landed
* Export sent for localization (has to be done by Garvan for now)

**Comment by garvankeeley** [comment]
Someone can just ping me when strings are landed and I can do the export.

**Comment by garvankeeley** [comment]
PR https://github.com/mozilla-mobile/firefox-ios/pull/5943
