### ISSUE TITLE
Autofill selection menu is incorrectly displayed in landscape

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#5945]
Build: 21.0 (16918)
Device: iPhone Xr
iOS: 13.2

Preconditions:
1. Install Lockwise
2. Set Autofill Password to use Lockwise and iCloud Keychain

Steps to reproduce
1. Change device orientation to landscape
2. On a login form, tap on the user name
3. Tap on the "Password" button above the keyboard

Actual results:
- The menu is incorrectly displayed. This issue is not reproducible in Safari

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2232)

**Comment by garvankeeley** [comment]
Can you add a screenshot, I am not seeing the bug

**Comment by SimonBasca** [comment]
Correct layout
![Screen Shot 2020-01-08 at 10 44 03 AM](https://user-images.githubusercontent.com/32130829/71963263-f088a880-3203-11ea-9298-c8b5e0e1a43b.png)

Incorrect layout when following STR
![Screen Shot 2020-01-08 at 10 43 51 AM](https://user-images.githubusercontent.com/32130829/71963302-0007f180-3204-11ea-8b35-951172739616.png)

**Comment by athomasmoz** [comment]
@kaylagalway Is this something Lockwise can control?

**Comment by kaylagalway** [comment]
> @kaylagalway Is this something Lockwise can control?

As far as I know, no. Our Credential Provider extension is not launched or triggered until one of those buttons is tapped, since you could click "iCloud Keychain" or "Cancel".

**Comment by lmarceau** [comment]
Since only `data-sync-user` has commented on the issue after the `Stalebot` GitHub action (which triggered the removal of the `stale` label) I’ll close this issue for now. Please let us know if you think this issue needs to be reopened, we'll gladly do so. Thank you!
