### ISSUE TITLE
video inverted bug

### ISSUE THREAD

**Issue by zgicg** [mozilla-mobile/firefox-ios#5954]
![file-read-763](https://user-images.githubusercontent.com/8198108/71507497-b0e6c600-28bf-11ea-94e8-4c7b871ba7b8.png)
Hey there! 
We found that Firefox was inverted in Diablo Mode when we use it watch videos!!we desperately hope that you can fix this  bug soon!

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2237)

**Comment by athomasmoz** [comment]
Hi @memoryaty thanks for logging. Marking as a P2. 

Night mode inverts page colours and looks like it isn't recognizing this as a video. As a workaround until fixed, you can try turning off Night Mode and keeping Dark Theme (setting at system level or in Firefox theme settings). The page will be shown in original colours and just the app skin will be shown dark.

**Comment by data-sync-user** [comment]
➤ Ashley Thomas commented:

Consolidating into #5819 https://mozilla-hub.atlassian.net/browse/FXIOS-2212 ( https://mozilla-hub.atlassian.net/browse/FXIOS-2212|smart-link )
