### ISSUE TITLE
Tracking protection shield icon is not updated correctly when different sites are loaded in same tab

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/firefox-ios#5956]
**Steps**
-Go to Twitter.com
-Tap on shield icon in order to disable TP
-Tap on the url bar and type a different website, for example wikipedia.com

**Expected**
The shield icon for wikipedia site should show as TP is enabled for the site

**Actual**
The shield icon shows TP as disabled although it is actually enabled.  Tapping on it the TP menu gives the option to disable TP.

<img width="200" alt="Screenshot 2019-12-27 at 12 37 00" src="https://user-images.githubusercontent.com/1897507/71515974-9d7b3100-28a6-11ea-9a98-de15e4969a6a.png">

**Comment by Logomorph** [comment]
Had a look and it only reproduces on iPhone. iPad works fine.

**Comment by nbhasin2** [comment]
I am able to reproduce this on iPad (Sim) as well. 
Redefined steps:
- (1st website) Open twitter or any other website which tracks users 
- Disable the protection on that website. The icon will change to grey with slash. (same tab) 
- (2nd website) Go to the website which doesn't track (Eg. duckduckgo or wolframalpha)
- You will see same icon as before with slash 
- (3rd Website) Go to any website whether tracked / untracked (Eg. theverge or wolframalpha) and you should see proper icon 

------

Now if you visit a tracked website as 2nd website. Then the 3rd website will show correct icon.

**Comment by csuciu** [comment]
Verified as fixed on master 1c5d2186.
