### ISSUE TITLE
Paypal displayed browser out of date mssage

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-ios#5966]
**Steps to reproduce**

1. Open Firefox
2. Open Paypal / go to a site & use paypal to purchase

**Expected Results**

Paypal site available and can be used normally

**Actual Results**

Warning that browser is out of date. Reviews suggest this makes the site unusable, and therefore users are unable to complete transactions

**Device**

Reviews mention v21 and iPad. I could not reproduce on my iphone

**Reviews**

https://app.appbot.co/apps/854569-firefox-private-safe-browser/reviews/1488917334?
https://app.appbot.co/apps/854569-firefox-private-safe-browser/reviews/1489006183?
https://app.appbot.co/apps/854569-firefox-private-safe-browser/reviews/1486853379?

**Comment by nbhasin2** [comment]
Paypal on iPad should work. Pushed a fix for this today. 
Commit as an FYI: https://github.com/mozilla-mobile/firefox-ios/commit/9db63d13f3ac2324202f727e32f19cf82f780081
