### ISSUE TITLE
Pages do not render and are not usable with Reduce Transparancy enabled

### ISSUE THREAD

**Issue by Bubbgump209** [mozilla-mobile/firefox-ios#5971]
This has been an issue for several months. Frequently (>50% of the time) FF on iOS simply doesn't render a page completely. A reload of the page does not help. IOS 13.3 (was an issue on earlier releases of iOS too) iPhone XR, FF for iOS 21 (16918).

Examples:

[Example 1](https://i.imgur.com/s9mLy1e.mp4)
[Example 2](https://i.imgur.com/GtYAieU.mp4)
[Example 3](https://i.imgur.com/dpfvZ1t.mp4)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2242)

**Comment by SimonBasca** [comment]
Hi  @Bubbgump209, thanks for your feedback. Unfortunately I am unable to reproduce this issue. Can you please check if you have any Accessibility option enabled in iOS Settings?  I am guessing this issue is not reproducible in Safari.

**Comment by Bubbgump209** [comment]
Here is a link to all of my Accessibility settings:

https://imgur.com/a/8FUuMJ8

Correct, this is not reproducible in Safari.

**Comment by SimonBasca** [comment]
Can you please try disabling Reduce Transparency and see if that changes anything?

**Comment by Bubbgump209** [comment]
The issue is not persistent, so I have disabled the option and will post back if it reoccurs.

**Comment by Bubbgump209** [comment]
It appears that if I disable that accessibility option, close Firefox, and reopen it the issue is resolved. So indeed, it appears that this is related to reduce transparency.

**Comment by data-sync-user** [comment]
➤ Asa Dotzler commented:

This is an accessibility S2
