### ISSUE TITLE
Synchronized devices form displays the Sign in/Create account buttons for a logged in user

### ISSUE THREAD

**Issue by nbhasin2** [mozilla-mobile/firefox-ios#5972]
Proper Steps:

    Tap on bottom hamburger menu button
    Tap on your library
    Go to the Synced Tabs
    Tap on create account
    After successful creation

The issue here is that right after account is created it asks for user's input on verification code. After verification code is entered and we come back to the sync'd view but FxA account still returns with needs verification instead of no action needed (FxAActionNeeded.none). After a second when user switches tab and refreshes it then returns proper (FxAActionNeeded.none) and user sees correct view.

Original issue : https://github.com/mozilla/fxa/issues/3638

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2243)

**Comment by lmarceau** [comment]
Since only `data-sync-user` has commented on the issue after the `Stalebot` GitHub action (which triggered the removal of the `stale` label) I’ll close this issue for now. Please let us know if you think this issue needs to be reopened, we'll gladly do so. Thank you!
