### ISSUE TITLE
[META] Upgrade FxA to Rust Component

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-ios#5979]
**Vision**

As a Firefox for iOS engineer, I want to upgrade FxA to the latest rust component so that I can reduce technical debt and enable new features including QR code pairing

**Acceptance Criteria**

* The latest FxA Rust component is used

**Not Included**

* This doesn't include implementing new features offered by the component

**Tickets**
[ ] #6050 
[ ] #6051 
[ ] #6052 
[ ] #6053 
[ ] #6054 
[ ] #6055 
[ ] #6056 
[ ] #6057 
[ ] #6058
[ ] #6059
[ ] #6060
[ ] #6061
[ ] #6062
[ ] #6063
[ ] #6064

[ ] https://github.com/mozilla-mobile/firefox-ios/issues/5995 Standalone account manager
[ ] #5991 Integrate Rust Component
[ ] #5992 Retrofit legacy sync swift engines to use AM session token
[ ] #5993 Session token migration for Firefox iOS
[ ] #5994 CWTS integration for Firefox iOS

**Comment by garvankeeley** [comment]
Closing as completed. yay to that.
