### ISSUE TITLE
Text replacement in location bar doesn’t require space

### ISSUE THREAD

**Issue by Ustice** [mozilla-mobile/firefox-ios#5981]
Usually when an app has a text entry, Text Replacement usually doesn’t replace the text until space is pressed. When typing in the location bar, it is immediately replaced. This causes problems for typing things that include those characters. For instance, I use https://dndbeyond.com, and I have a text replacement that converts `dnd` to `Dungeons and Dragons`. As a result, what I get is `Dungeons and Dragonsbeyond.com`.

Since it immediately makes the replacement, I can not cancel the replacement.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2244)

**Comment by sblatz** [comment]
I'm running into the same issue. I have "np" turn into "no problem" which makes navigating to npr.com impossible 😬

**Comment by kpreslan** [comment]
Me too. Horrible bug.

**Comment by SimonBasca** [comment]
More  reports of this issue at : https://bugzilla.mozilla.org/show_bug.cgi?id=1675912

**Comment by SimonBasca** [comment]
Another report at https://bugzilla.mozilla.org/show_bug.cgi?id=1708582.

**Comment by groner** [comment]
I have a text replacement for mu -> μ. Now I can't search for muppets or go to murrayscheese.com

![image](https://user-images.githubusercontent.com/47317/130663671-894b6da2-29c4-4681-8107-5d7c2260e3e4.jpeg)

**Comment by tlicklider** [comment]
Sad this is unfixed by now. Makes users choose between text replacement OR Firefox. Firefox's implementation clearly fails Apple standard behavior (requiring space to trigger text substitution.) MIght have been mitigated if Apple had a toggle to turn text replacement on/off, but the burden is on Firefox here. So you have to use Safari. Sad.

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verifying as fix on v9000 (9248). The text is no longer replace when typing in the URL bar “dnd“. 

Note: The text “dnd” will onyl be replaced after typing “.” or “space” which has the same behavior as Safari.
