### ISSUE TITLE
Show confirmation dialog for all external URL types

### ISSUE THREAD

**Issue by garvankeeley** [mozilla-mobile/firefox-ios#5985]
URL schemes such as  ftp:, feed:, photos-redirect:, music:, videos:, shareddocuments open automatically in Safari (or other external app) without confirmation from the user.

**Comment by garvankeeley** [comment]
This needs strings, but we should land this english-only if needed.

**Comment by csuciu** [comment]
Verified as fixed on master c2574a0a55.
