### ISSUE TITLE
Tapping clear-url icon inserts q character

### ISSUE THREAD

**Issue by aepton** [mozilla-mobile/firefox-ios#5987]
When entering a url, clicking the x icon to clear the current value instead enters a “q” character. It often takes several taps for the x to be captured properly, in the process generating a url that looks like “qqqqq”.

**Comment by garvankeeley** [comment]
Thanks for the report, I can't repro though
Do you have a custom keyboard installed? If so, which one? (Because you also filed https://github.com/mozilla-mobile/firefox-ios/issues/5988)

**Comment by aepton** [comment]
Yep, I'm using GBoard and this appears to be the fault of that keyboard; closing. Thanks and sorry for the false report!
