### ISSUE TITLE
[META] Push Notification Permissions

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-ios#5989]
**Vision**

As a user, I want to know why I'm being asked to allow push notifications from the browser and have the option to decide which types of notifications I receive

----

**Acceptance Criteria**

* Users are given details on what push notifications will be used for before they're asked to allow them
* Users have the option to receive push notifications for sync functionality and/or marketing updates

----

**Tickets**

[ ] #5789 Push Opt In
[ ] #5790 Push Preferences
[ ] #5836 Prompt opt in after receiving tab (Should)

**Notes**
* Similar [ticket on Fenix](https://github.com/mozilla-mobile/fenix/issues/4667)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2245)

**Comment by nbhasin2** [comment]
Ref Issue: https://github.com/mozilla-mobile/firefox-ios/issues/6189

Basically the issue above is related to an in-app message that marketing could send to ask for users to allow for push notifications in the Firefox iOS App. Currently the code is commented out as it shows a message related to FxA and why users will benefit from having push notifications enabled. 

Note
- We do not ask for push notifications when users open the app
- Currently we **Only** ask for push notifications when user logs into an FxA account

**Comment by data-sync-user** [comment]
➤ Tiffanie Shakespeare commented:

closing as we don’t use leanplum anymore. thanks!
