### ISSUE TITLE
Session token migration for Firefox iOS

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-ios#5993]
**Vision**

tbd

**Acceptance Criteria**

* tbd
* Solution is documented to help with future maintenance

**Notes**

* [Corresponding sync ticket ](https://jira.mozilla.com/browse/SYNC-565)

This more or less will be creating bindings for

`migrate_from_session_token`

in Swift and calling it from the account manager (or let the app call it).

**Comment by athomasmoz** [comment]
@garvankeeley can I close this as duplicate too?

**Comment by garvankeeley** [comment]
Closing as fixed by a-s side in https://github.com/mozilla/application-services/issues/2435
