### ISSUE TITLE
Firefox Uses Light Theme First Time After Locking

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-ios#5998]
**Steps to Reproduce**

Preconditions: System theme set to dark, Firefox theme set to match system

1. Lock your iPhone
2. Unlock iPhone
3. Open Firefox (v1)
4. Close Firefox
5. Open Firefox (v2)

**Expected Behaviour**

(v1) Firefox is shown in dark theme
(v2) Firefox is shown in dark theme

**Actual Behaviour**

(v1) Firefox is shown in light theme
(v2) Firefox is shown in dark theme

**Notes**

* Using v21.0 (16814) on iPhone 11
* This happens even if I view the app in dark theme before locking

![2020-01-08 15-57-50 2020-01-08 16_01_29](https://user-images.githubusercontent.com/43346208/72026433-483d0900-3230-11ea-8a14-ea59d0928e0d.gif)

**Comment by dnarcese** [comment]
I have been unable to reproduce this.
@SimonBasca could you try as well?

**Comment by csuciu** [comment]
I can't repro either. Tested on iPhone XS (13.3)/Firefox 21.0 and iPhone 11 (13.3) sim/latest master.

**Comment by SimonBasca** [comment]
I'm also unable to reproduce this issue on iPhone Xr (13.3)/Firefox 21.0 and latest master.

**Comment by athomasmoz** [comment]
Just tried with latest beta and can't repro. Closing ticket
