### ISSUE TITLE
iPhone SE crash: pdf displayed, switch from portrait to landscape (low repro, could just be mem issue)

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#6000]
Steps to reproduce:

1. Launch the latest version of Firefox on iOS (version 21.0) on an iPhone SE (13.3)
1. Put the iPhone in portrait
1. Open this PDF (http://help.websico.net/fr/data/rawdata/exemple_pdf.pdf)
1. Switch the iPhone to landscape

Actual results:

Firefox crashes.

Expected results:

The pdf should have been displayed in landscape.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2247)

**Comment by SimonBasca** [comment]
I wasn't able to reproduce this issue but we encountered some crashes when the device memory was almost full. I asked the user what's the status on the iPhone storage and here is the reply: 

"My iPhone is used at 58.9 Go, and it has a capacity of 64 Go.
So this may be linked.

But my iPhone has always been almost full since 2 years, and it is only with the last versions of Firefox that I have this crash.
I could not tell with which version of Firefox it has started crashing, but it could be with the latest or the version before."

**Comment by lolo2bdx** [comment]
Hello Simon,

Here is the crash log.

[Client-2020-01-10-193534.zip](https://github.com/mozilla-mobile/firefox-ios/files/4047345/Client-2020-01-10-193534.zip)

**Comment by lolo2bdx** [comment]
Hi Simon,

To help solve this bug, here is a video showing the crash of the app.

[crash_firefox_on_iOS_with_a_pdf.zip](https://github.com/mozilla-mobile/firefox-ios/files/4138616/crash_firefox_on_iOS_with_a_pdf.zip)

**Comment by lolo2bdx** [comment]
Since the v32.0, it does not crash anymore with a pdf switched to landscape !
So it looks that this problem is solved !
