### ISSUE TITLE
No warning is displayed when opening a new tab via long press on a link, without internet connection

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#6005]
Build: c2574a0a
Device: iPhone Xr
iOS: 13.3

Steps to reproduce:
1. Go to "bbc.com"
2. Put device in Airplane mode
3. Long press on a link
4. Select "Open in New Tab"
5. Switch to the tab

Actual results:
- A new empty tab is displayed with only the URL displayed.

Expected results:
- A new tab should be displayed with a "No internet connection is present." message and "Try again" button. Also after connecting to the internet, tapping "Reload" button does not load the page.

Note:
- Also reproducible on v21.0

VIdeo:
- [Issue.mov.zip](https://github.com/mozilla-mobile/firefox-ios/files/4053559/Issue.mov.zip)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2250)

**Comment by lmarceau** [comment]
Since only `data-sync-user` has commented on the issue after the `Stalebot` GitHub action (which triggered the removal of the `stale` label) I’ll close this issue for now. Please let us know if you think this issue needs to be reopened, we'll gladly do so. Thank you!
