### ISSUE TITLE
Setup Leanplum A/A Test

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-ios#6011]
**Vision**

As an iOS team member, I want to run an A/A test through the new testing strategy so that I can confirm everything works as we expect before launching an A/B test

----

**Acceptance Criteria**

* A/A test set up to launch with next release
* Ticket log & time reserved with data science team to ensure they can analyze the results

**Comment by athomasmoz** [comment]
@hlsoto get access to leanplum for folks so we can try this out

**Comment by nbhasin2** [comment]
Update: Have a meeting scheduled with LP Marketing folks for a walk-through before I test the full functionality on the device(s).

**Comment by nbhasin2** [comment]
Update: 
- Able to create a sample A/B test on Leanplum (LP)
- I am able to add a LP boolean variable in the iOS app Eg. "etpOnboarding" 
- After adding the variable as long as the developer has a device registered in Leanplum dashboard and have access to "Dev" environment the variable also gets added to LP itself
- Variables are of type Boolean, Dictionary etc. https://docs.leanplum.com/docs/instrumenting-variables-sample-ios-android
- These variables can be used to then run tests. Eg. "etpOnboarding" is a boolean variable so we can say X% will show true and remaining percentage as false. 
- When user makes A/B test on Leanplum they can use these variables those are added in the code to run tests. 

a) Come up with A/B test you want to run in Leanplum  
b) Add variable (iOS + LP dashboard) 
c) Configure the A/B test to use the variable
d) Run A/B test and see results

**Comment by nbhasin2** [comment]
Still waiting to see how we can remove the variables on these are added and are no longer required. We have reached out to LP support for this and will update once we get solid answer.

**Comment by nbhasin2** [comment]
Last piece of the puzzle is concluded as I learn that deleting variables isn't as trivial as it sounds. We need to use LP's api post to delete the variable.

**Api:** https://api.leanplum.com/api?action=deleteVars
**Docs:** https://docs.leanplum.com/docs/preserve-variables
**Curl request to delete variable: **
```
curl --location --request POST 'https://api.leanplum.com/api?action=deleteVars' \
--header 'Content-Type: application/json' \
--data-raw '{
    "appId": "APP_ID",
    "clientKey": "CLIENT_KEY",
    "apiVersion": "1.0.6",
    "vars": [
        "YOUR_VARIABLE_NAME", "ANOTHER_VAR_NAME"
    ]
}'
```

**Comment by nbhasin2** [comment]
Added all to the doc - https://github.com/mozilla-mobile/firefox-ios/wiki/Leanplum-A-B-test-setup
