### ISSUE TITLE
Onboarding Card for ETP Setting

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-ios#6012]
**Vision**

As a user (potentially coming from desktop message), I want an onboarding screen that describes my tracking protection levels, so that I know I'm being protected from the start and don't have to search for the setting later

----

**Acceptance Criteria**

* Onboarding card is shown to new users on 3rd session after install (if there's also an upgrade card for this session, it is shown after)
* Onboarding card is shown as a cover sheet for v24 after users upgrade
* Onboarding card design & strings match attached mock
  * [Mock with Strings](https://share.goabstract.com/c84b39fa-8ea8-465c-80d6-5fca21b28b6e)
* Event tracked for clicking each option on the card, including dismiss

----

**Not Included**

* This does not include updating the strings on the ETP settings page

**Comment by bryanbell** [comment]
Mockup: https://mozilla.invisionapp.com/share/MUVVVLX9C35

**Comment by athomasmoz** [comment]
Need to determine where in the onboarding flow this will go (before or after other cards)

**Comment by csuciu** [comment]
Verified as fixed on master aaf14a9 (except "Onboarding card is shown as a cover sheet for v24 after users upgrade" which will be tested when the builds are available.)

**Comment by csuciu** [comment]
Verified that "Onboarding card is shown as a cover sheet for v24 after users upgrade".
