### ISSUE TITLE
Update Shield Icon Menu to Clarify "Enabled for this site"

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-ios#6014]
It is currently ambiguous what "Enabled for this site" means on the menu that comes up whenyou click on the shield icon. 

**Notes**

* This is larger because it uses a native switch, which doesn't allow string to wrap. So we need to make a larger change than just a new string
* This will need to be localized before launching. New string shouldn't be merged until next release

**Comment by bryanbell** [comment]
Mockup: https://mozilla.invisionapp.com/share/ETVW2M4UK7Y

**Comment by SimonBasca** [comment]
Verified fix on master 9b3f393c4.
