### ISSUE TITLE
IPv6 addresses not identified as valid URLs

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#6015]
Steps to reproduce:

Navigate to an IPv6 address like "http://[2a01:4f8:c0c:4925::10]".

Actual results:

Firefox submits the address to Google as a search term.

Expected results:

The browser should have navigated to the IPv6 address.

Via  : https://bugzilla.mozilla.org/show_bug.cgi?id=1608732

Notes:
- This is not reproducible on Chrome. 
- Reproducible in Safari.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2253)

**Comment by lmarceau** [comment]
Since only `data-sync-user` has commented on the issue after the `Stalebot` GitHub action (which triggered the removal of the `stale` label) I’ll close this issue for now. Please let us know if you think this issue needs to be reopened, we'll gladly do so. Thank you!
