### ISSUE TITLE
Land Low Risk Focus PRs

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-ios#6047]
Contributors have submitted valuable PRs to Focus, let's see what we can release

**Acceptance Criteria**

* Look into PRs
* Land low-risk, low-effort PRs

**Comment by nbhasin2** [comment]
a) https://github.com/mozilla-mobile/focus-ios/pull/1659 - Add Mozilla Code of Conduct
b) https://github.com/mozilla-mobile/focus-ios/pull/1665 - Update README.md
PRs are merged into Firefox Focus

**Comment by nbhasin2** [comment]
Going to mark it as Done
