### ISSUE TITLE
[FxA Upgrade] User is able to sign-in to their Firefox account on iOS

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-ios#6050]
Blocked on: https://jira.mozilla.com/browse/SYNC-621

**Vision**

Maintain sign in functionality after FxA upgrade

**Acceptance Criteria**

* Login has been upgraded to use the new FxA rust component
* User is able to log-in through all log-in workflows
* Existing probes are still available for analysis

**Notes**

This does not include choose-what-to-sync

**Comment by garvankeeley** [comment]
Fixed by 818e4cea879247d7a89ac9a69304754812c569bd
