### ISSUE TITLE
[FxA Upgrade] User is able to sign-out of their Firefox account on iOS

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-ios#6051]
Blocked on: https://jira.mozilla.com/browse/SYNC-622

**Vision**

Maintain sign in functionality after FxA upgrade

**Acceptance Criteria**

* Sign out has been upgraded to use the new FxA rust component
* User is able to sign out
  * Workflow always goes through preferences
  * Test case where account is in a bad state: password reset, delete account
* User is logged out and the associated device is destroyed
* Existing probes are still available for analysis

**Comment by garvankeeley** [comment]
Satisfied after enough testing this is working ok in the rust branch, so closing.
