### ISSUE TITLE
[FxA Upgrade] Allow user to CWTS during login

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-ios#6052]
Blocked on: https://jira.mozilla.com/browse/SYNC-623

**Vision**

Maintain Choose-What-To-Sync functionality after FxA upgrade

**Acceptance Criteria**

* Content presents a Choose-What-To-Sync dialog to the user
  * Native dialogue needs to continue to work
* User's CWTS choices are respected and the required sync engines are confirmed disabled in the settings menu
* Existing probes are still available for analysis

**Comment by garvankeeley** [comment]
Fixed as part of previous work
