### ISSUE TITLE
[FxA Upgrade] User can navigate to acct mgmt without entering password

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-ios#6053]
Blocked on: https://jira.mozilla.com/browse/SYNC-624

**Vision**

Maintain account functionality after FxA upgrade

**Acceptance Criteria**

* When clicking on "Manage account" in the Settings menu, the user is not prompted for their password
* Existing probes are still available for analysis

**Notes**

Only a 1, because the implementation will be done as part as CWTS (same mechanism).

**Comment by garvankeeley** [comment]
fixed by 484387dffce25fb1a4e820a3728e01ab8a467a18
