### ISSUE TITLE
[FxA Upgrade] Show the user's profile

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-ios#6054]
Blocked on: https://jira.mozilla.com/browse/SYNC-625

**Vision**

Maintain profile functionality after FxA upgrade

**Acceptance Criteria**

* The user's profile is visible (avatar, display name) in preferences & application menu
* Accurately show account state, even when offline & when you start the app
* Existing probes are still available for analysis

**Comment by garvankeeley** [comment]
fixed by 484387dffce25fb1a4e820a3728e01ab8a467a18
