### ISSUE TITLE
[FxA Upgrade] "Device Connected" notifications

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-ios#6057]
Blocked on: https://jira.mozilla.com/browse/SYNC-628

**Vision**

Maintain device list functionality after FxA upgrade

**Acceptance Criteria**

* When another device connects on the account, a notification is shown to the user
* Existing probes are still available for analysis

**Comment by garvankeeley** [comment]
Fixed by 54ac664d3fe76d4afcb5ef7696fb5cb5d9302642
