### ISSUE TITLE
[FxA Upgrade] "Device Disconnected" notifications

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-ios#6058]
Blocked on: https://jira.mozilla.com/browse/SYNC-629

**Vision**

Maintain device notifications after FxA upgrade

**Acceptance Criteria**

* Show notification when a device disconnects or is destroyed
* Log-out locally if the disconnected device is ours
* Existing probes are still available for analysis

**Notes**

Only a 1, because same work unit as #6057 . This should happen automatically once you disconnect not after token sessions are over.

**Comment by garvankeeley** [comment]
Fixed by 54ac664d3fe76d4afcb5ef7696fb5cb5d9302642

**Comment by garvankeeley** [comment]
Device is not disconnecting when it is the local device. This needs to happen for both background push, and for when the app is in the foreground.

**Comment by garvankeeley** [comment]
Fixed by f00d85012d21d547defae83cb02208ba2f74e803
