### ISSUE TITLE
[FxA Upgrade] Sync data is syncing

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-ios#6059]
Blocked on: https://jira.mozilla.com/browse/SYNC-630

**Vision**

Maintain sync functionality after FxA upgrade

**Acceptance Criteria**

* Both the legacy (history, tabs) and rust (logins) sync properly.
* Existing probes are still available for analysis

**Notes**
We might need to add some Rust endpoints to craft a token server token (yes) from our OAuth tokens.

**Comment by garvankeeley** [comment]
Fixed by Ed as part of related work. Mostly this is a QA task.
