### ISSUE TITLE
[FxA Upgrade] Account state migration

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-ios#6062]
Blocked on: https://jira.mozilla.com/browse/SYNC-633

**Vision**

Maintain account states after FxA upgrade

**Acceptance Criteria**

* After updating the Firefox iOS app, the user is still logged in to the same account. Incorrect states (reconnection needed, email unverified) are replicated
* Existing probes are still available for analysis

**Notes**

Fenix has prior art, we should be able to expose the same rust endpoints!

**Comment by garvankeeley** [comment]
Fixed as part of other work
