### ISSUE TITLE
[FxA Upgrade] Device state migration

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-ios#6063]
Blocked on: https://jira.mozilla.com/browse/SYNC-635

**Vision**

Maintain account states after FxA upgrade

**Acceptance Criteria**

* After updating the Firefox iOS app, the device name is unchanged and the device still works as a send-tab target.
* Anything that we are no longer caching has been identified to ensure it doesn't break existing functionality
* Existing probes are still available for analysis

**Notes**

The session token migration takes care of this, there might be nothing to do here.

**Comment by garvankeeley** [comment]
Fixed by 818e4cea879247d7a89ac9a69304754812c569bd
