### ISSUE TITLE
App can be configured to use alternate account backend servers

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-ios#6064]
Blocked on: https://jira.mozilla.com/browse/SYNC-636

**Vision**

Maintain account functionality after FxA upgrade

**Acceptance Criteria**

* Ability to log-in on a different Firefox Account instance than production.
* If user self-hosts half the system, we need to ensure that doesn't break
* Existing probes are still available for analysis

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2261)

**Comment by lmarceau** [comment]
Since only `data-sync-user` has commented on the issue after the `Stalebot` GitHub action (which triggered the removal of the `stale` label) I’ll close this issue for now. Please let us know if you think this issue needs to be reopened, we'll gladly do so. Thank you!
