### ISSUE TITLE
GitHub reports : github reports no longer old versions of Firefox 

### ISSUE THREAD

**Issue by F3000** [mozilla-mobile/firefox-ios#6070]
See here for more details 

![9BE2EA22-86A8-4723-9289-024BF455B19D](https://user-images.githubusercontent.com/8161283/73128926-e4f4fa00-3fd7-11ea-98b8-87ef6602208e.jpeg)

Because of this error I can’t upload pictures in issues etc..

**Comment by F3000** [comment]
This issue also exist on reddit 

![B235FD0F-95F9-4B1D-AC8D-E55027B232B3](https://user-images.githubusercontent.com/8161283/73128988-c263e080-3fd9-11ea-8147-7cf4fd78c42d.jpeg)

**Comment by csuciu** [comment]
This issue occurs only in the desktop versions of the sites.

**Comment by F3000** [comment]
Which is standard on iPad OS

**Comment by tanderson1992** [comment]
GitHub still shows the message on FF 21.0 iPad iOS 13.3, even when mobile site is requested. The warning goes away on Reddit.

**Comment by softvision-sergiulogigan** [comment]
I have opened https://bugzilla.mozilla.org/show_bug.cgi?id=1614597 and added this one to the See also list.
@csuciu, you can close this as a Duplicate of the BZ one.

**Comment by csuciu** [comment]
Thanks @softvision-sergiulogigan

**Comment by softvision-oana-arbuzov** [comment]
@tanderson1992, @F3000, @csuciu does this still reproduces on iPad for Github and Reddit? 
I'm not able to reproduce it on iPod.
![IMG_0077](https://user-images.githubusercontent.com/12184325/110644162-7fed6b00-81bd-11eb-952a-9df019a022e4.PNG)
![IMG_0078](https://user-images.githubusercontent.com/12184325/110644167-81b72e80-81bd-11eb-8635-f146c676f964.PNG)

**Tested with:**
Browser / Version: Firefox Daylight 31.0 (3537)
Operating System: iPod touch iOS 12.5.1 (1136 x 640 pixels (~326 ppi pixel density)

**Comment by SimonBasca** [comment]
I am not reproducing the issue on iPad Pro (14.4) on v32.1 (3961) on none of the mentioned sites.

**Comment by wachabaha** [comment]
- ****_[![Uploading 111154636...]]()_****

**Comment by wachabaha** [comment]
-

**Comment by wachabaha** [comment]
@F3000
