### ISSUE TITLE
FxA Send Tab from desktop to iOS: Firefox Sync "DEBUG: Error notDecrypted"

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/firefox-ios#6072]
My Firefox desktop's "Send Tab to Device" menu lists five identically-named "Firefox Beta on Chris's iPhone" devices.

When I try to send a tab from Firefox desktop (74 Nighty on macOS 10.15.2) to Firefox iOS (beta version 21.0 (16901)), an iOS notification pops up on my lock screen: `Firefox Sync "DEBUG: Error notDecrypted"`. The sent tab is not opened in Firefox iOS. This error happens every time for three of the five "Firefox Beta on Chris's iPhone" device names. The tab is successfully sent and opened for one of the device names. The fifth device name reports no error and doesn't open the tab.

**Comment by csuciu** [comment]
Similar issue reported in #5890

**Comment by garvankeeley** [comment]
Closing as we have a new FxA implementation landing for v25 (next release) and this bug should be gone.
