### ISSUE TITLE
Make it possible to disable link previews on iOS 13

### ISSUE THREAD

**Issue by nil4** [mozilla-mobile/firefox-ios#6078]
Using Firefox 21.0 (16918) on iOS 13.3, when tapping-and-holding a link to open the context menu to copy/share the link, an intrusive popup preview of the linked page is displayed, pushing the context menu off-screen.

To copy/share the link, one must swipe up to reduce the size of the link preview every time.  Another unintended consequence is that copying a link loads the target page. 

The preview popup cannot be disabled in Firefox, but it *can* in Safari. Please consider adding an option to disable it, or even better, a default-off setting, fitting for a privacy-conscious browser. 

### Steps to reproduce

Open https://mozilla.org. For reference, the page looks similar to:

![0_mozilla_org](https://user-images.githubusercontent.com/139133/73285563-8194e300-41f6-11ea-9d07-2b67e6798939.png)

Tap-and-hold the *Firefox for iOS* button in the middle of the page to display the link context menu.

The link preview popup appears, occupying most of the screen; note the share/copy link options are pushed off the screen:

![1_firefox_copy_link_invisible](https://user-images.githubusercontent.com/139133/73286276-92922400-41f7-11ea-93d4-5cd35ae52dbd.png)

Swipe up to shrink the link preview popup, which makes room for the context menu. One must do this every time to access the share/copy options:

![2_firefox_copy_link_visible_after_drag_up](https://user-images.githubusercontent.com/139133/73286344-b3f31000-41f7-11ea-8f56-5503356caaf3.png)

### Expected behavior

Similar to Safari, allow disabling the link preview popup permanently. Ideally, disable the link previews by default to protect user privacy, unless they opt-in to them explicitly.

As a reference point, Safari shows a *Hide preview* option, highlighted below:
![3_safari_option_hide_preview](https://user-images.githubusercontent.com/139133/73286523-fa486f00-41f7-11ea-9040-d9038154aa4e.png)

Clicking it collapses *and* disables further preview popups. Once disabled, tap-and-holding any other link shows only the context menu options but leaves out the preview until manually re-enabled:

![3_safari_copy_link_visible_when_hidden](https://user-images.githubusercontent.com/139133/73286760-688d3180-41f8-11ea-860d-c7bc8d1a8b79.png)

### Observed behavior

To access the options to download/copy/share a link, one must swipe up to reduce the size of the link preview every time, when using Firefox.  

Loading the link target every time wastes battery, bandwidth, and impacts user privacy unnecessarily. None of this should happen unless the user explicitly opts-in to have such previews displayed.

**Comment by nil4** [comment]
Also reproduces on version 22.0 (17157).

**Comment by cscgh** [comment]
This would appear to be due to a commit by garvinkeeley in approval of a change made for #5616/#5737 re: “Showing a preview brings the context menu closer to the bottom of the screen for easier use, and brings us closer to parity with Safari.”, Nov 12 for inclusion in v21, to BrowserViewController+WebViewDelegates.swift 

This change implemented the preview view but omitted the Safari “hide preview” option.

Can the negative privacy implementations of this change make this a high priority issue? The inability to identify a link target before clicking on it or having the browser ‘click’ it for you is not insignificant. It will take me longer than seriousness demands to do it myself lacking familiarity with the process, project, non-trivial git, xcode, and IOS development. Thank you so much for your work.

—csc

**Comment by cscgh** [comment]
Backed out c829026 in a local copy and built w/ defaults w/o additional warnings. Ran simulated on iPad Air 3 and iPhone 11 Pro Max, 13.3 and 13.2 respectively.  Context menu without previews again.  Made the change in a forked repository but figuring out the rules on participation, pull/review/discuss requests, et al. Hope to discuss getting previews backed out in a quicker update until a corresponding hide option can be created.

**Comment by cscgh** [comment]
Of note, the content menu previewView is also launching directly into authorization/authentication processes when the target link demands it, disrupting the browsing session is the process.

**Comment by nil4** [comment]
Still reproduces on v23.0 (17297). 
Is there some idea about a timeline for a fix to be integrated?

**Comment by nil4** [comment]
Still reproduces as reported on v24.1 (17574)

**Comment by nil4** [comment]
Thank you very much, @cscgh and @garvankeeley! 
Much appreciated.

**Comment by cscgh** [comment]
> Thank you very much, @cscgh and @garvankeeley!
> Much appreciated.

That thanks goes to @q2r5 for adding the opt-out configuration in a hurry. Thank you!

**Comment by csuciu** [comment]
Verified as fixed on master 6865276c8f4c.

**Comment by garvankeeley** [comment]
This will land for v26, not v25, to allow time for L10N on the string changes.

**Comment by djeedai** [comment]
Hi, @garvankeeley this change was reverted 5 years ago without explanation as far as I can see from the issue timeline. Can the issue be reopened? This is a privacy concern, and FF is behaving worst than Safari here. Thanks

**Comment by Foxbolts** [comment]
Hey @djeedai - would you mind describing the exact issue you are having?

If you are referring to disabling context menu link previews, there is a setting to do this if you go to Settings > Browsing > Disable "Show Link Previews"

If you are referring to some of the menu actions requiring a scroll to navigate to, this is standard iOS behavior, however, we have done some work recently to [shorten context menu link title's](https://github.com/mozilla-mobile/firefox-ios/issues/25895) and [shrink the size of the preview](https://github.com/mozilla-mobile/firefox-ios/issues/25896) which should make these actions more discoverable and easier to navigate to.

Let me know if this helps, or if you still have an issue!

**Comment by djeedai** [comment]
@Foxbolts I was indeed referring to disabling preview. Your suggestion works, thanks! I had not found that option previously, and my searches only pointed me to this GitHub issue. Glad to know there was a separate change for it! Thanks

**Comment by GregDMeyer** [comment]
> If you are referring to disabling context menu link previews, there is a setting to do this if you go to Settings > Browsing > Disable "Show Link Previews"

Does this option still exist? I can't seem to find it in the settings. (Indeed, I can't find the "Browsing" submenu...)

**Comment by Foxbolts** [comment]
> > If you are referring to disabling context menu link previews, there is a setting to do this if you go to Settings > Browsing > Disable "Show Link Previews"
> 
> Does this option still exist? I can't seem to find it in the settings. (Indeed, I can't find the "Browsing" submenu...)

Hey @GregDMeyer, the `browsing` submenu should be near the top of the app settings page. See video below

https://github.com/user-attachments/assets/e02135ad-8531-4ebb-9b26-c1cfbc23ab2e

**Comment by GregDMeyer** [comment]
whoops, i'm using firefox focus. sorry for the confusion!
