### ISSUE TITLE
FXIOS-254 ⁃ Cmd-Click should open link in a new tab

### ISSUE THREAD

**Issue by paulrouget** [mozilla-mobile/firefox-ios#6083]
When using a hardware keyboard, clicking on a link with the Cmd key pressed should open the link in a new tab.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2271)

**Comment by SimonBasca** [comment]
In Firefox, when holding cmd on a hardware keyboard and tapping or clicking with a hardware mouse on a link, the link will open in the same tab. In Safari when doing the exact same steps the link will open in a new tab.

**Comment by lmarceau** [comment]
Hello @paulrouget,
I just worked on the keyboard + tap on link shortcuts in this PR: https://github.com/mozilla-mobile/firefox-ios/pull/9606
The following shortcuts should work now on the main branch, to be release in v96 (v41):
- Open link in background -> Command + Tap link
- Open link in new tab -> Command + Shift + Tap link
- Download link -> Option + Tap link

**Comment by paulrouget** [comment]
@lmarceau thank you!

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Confirming that all the shortcuts are working as expected in v104.1 (16952)

Open link in background -> Command + Tap link ✅ 
Open link in new tab -> Command + Shift + Tap link ✅ 
Download link -> Option + Tap link ✅
