### ISSUE TITLE
Are iOS users getting disconnect from Sync?

### ISSUE THREAD

**Issue by garvankeeley** [mozilla-mobile/firefox-ios#6085]
Duplicating from https://github.com/mozilla/application-services/issues/2160

@eoger has a likely cause, described here: https://github.com/mozilla/application-services/issues/2160#issuecomment-579676083

Error states should  transition to 'same' not 'disconnected'

**Comment by 211217613** [comment]
I get periodically disconnected from Firefox sync only on iOS devices and can't even use Firefox sync on my iPad even thought it can sync.
