### ISSUE TITLE
Screen Time Limits not effective in Firefox

### ISSUE THREAD

**Issue by Uffje** [mozilla-mobile/firefox-ios#6091]
I have an issue with Firefox and Screen Time.

I have set a limit of half an hour to a specific website. In Safari it registers each specific website, where Firefox is registered as one app and can't be split up in websites. This makes the time limit useless. I see this is also apparent in the MacOS version of Firefox.

Is this something Firefox can improve on or will it be a privacy issue or is it limited to apples Safari?

**Comment by athomasmoz** [comment]
Thank you for the report. Unfortunately, this functionality is not yet available to browsers outside Safari. We are actively monitoring updates for the OS and are interested to implement this functionality if made available in the future.

**Comment by jenniferrospad-wf** [comment]
There's an API for this now: https://developer.apple.com/documentation/screentime
