### ISSUE TITLE
Sign in to sync requires code sent via e-mail while blocking access to e-mail

### ISSUE THREAD

**Issue by ChaiTRex** [mozilla-mobile/firefox-ios#6096]
After entering my e-mail address and password to Firefox's sync service, Firefox asks for a code sent to my e-mail address. I'm logged into my e-mail **in Firefox**, so it's pretty inaccessible while a modal dialog asking for a code sent to my e-mail makes it impossible to use the rest of the browser.

Perhaps this sign in would be better done as a new page.

---

Firefox for iOS 22.0 (17157)
iPadOS 13.3.1

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2274)

**Comment by athomasmoz** [comment]
@ryanfeeley Any recommendations on how to handle this?

**Comment by ryanfeeley** [comment]
Without offering an unverified state on iOS (where you can verify later like on desktop) this is a tricky one. I don't imagine it affects many users, though we would have no way of knowing (aside from comparing verification success rates). Do you imagine there are many users using Firefox on iOS as their primary email client?

**Comment by lmarceau** [comment]
Since only `data-sync-user` has commented on the issue after the `Stalebot` GitHub action (which triggered the removal of the `stale` label) I’ll close this issue for now. Please let us know if you think this issue needs to be reopened, we'll gladly do so. Thank you!
