### ISSUE TITLE
FXIOS-261 ⁃  Support WebAuthn / FIDO for Firefox for iOS

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#6100]
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:73.0) Gecko/20100101 Firefox/73.0

Steps to reproduce:

iOS 13.1 and up support Webauthn authentication in Safari and embedded Safari by default for all NFC supporting iPhone (at least iPhone 8 and up). Since Firefox for iOS also uses Safari internally, I'd expect it to support WebAuthn as well.

Go to one of the many demo sites for WebAuthn (https://webauthn.io/).

Actual results:

If you go to a demo site, it shows "WebAuthn not supported". WebAuthn detection is based on feature detection on this site, not on user agent sniffing: the required JS APIs are not available.

Expected results:

Firefox should enabled the WebAuthn/FIDO APIs for the embedded Safari and support the capabilities of the underlying platform.

Requested via: 
- https://bugzilla.mozilla.org/show_bug.cgi?id=1612412

![image](https://user-images.githubusercontent.com/32130829/74158858-7d6bbb00-4c23-11ea-897a-4b6449a87f6c.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-261)

**Comment by SimonBasca** [comment]
The behavior from Firefox is also reproducible on Google Chrome.

**Comment by timbru31** [comment]
This seems to be a nicer/more detailed issue duplicate of #5365

**Comment by SimonBasca** [comment]
Closing https://github.com/mozilla-mobile/firefox-ios/issues/5364#issuecomment-826489193
