### ISSUE TITLE
Land Strings for ETP Updates

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-ios#6101]
**Vision**

Updated ETP strings have been landed & localization has kicked off

----

**Acceptance Criteria**

* Strings for ETP onboarding card landed in repo
* Updated settings page strings have landed in repo
  * [Mock with Strings](https://share.goabstract.com/c84b39fa-8ea8-465c-80d6-5fca21b28b6e)
* L10n (Jeff) informed of new strings

----

**Not Included**

* This does not include creating the onboarding card

**Comment by nbhasin2** [comment]
<img width="821" alt="image" src="https://user-images.githubusercontent.com/8919439/75296666-d2025f00-57fb-11ea-8ea6-e418758afe05.png">

Some strings have been updated and here is a mock from abstract. cc @bryanbell @athomasmoz
