### ISSUE TITLE
Make cover sheet optional per release

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-ios#6107]
**Vision**

As an FX iOS team member, I want to decide whether or not a cover sheet should be shown for a given release based on whether or not there are changes that users need to know about

----

**Acceptance Criteria**

* Each new version has the option to show a cover sheet
  * By default, no cover sheet will be shown
* There is a step in our process to decide whether or not one should be added

**Comment by nbhasin2** [comment]
Added Top level feature flag per version - Enable / Disable the cover sheet. Eg. We made a change and want to show it as part of cover sheet update. We require setting flag per version. We maintain a list of versions in the app on when to show the coversheet.

^ Discussed and agreed upon by the team.
