### ISSUE TITLE
Feature Request: UX to change the folder of Bookmarked Tab

### ISSUE THREAD

**Issue by sahil48** [mozilla-mobile/firefox-ios#6111]
When the blue bar shows up to acknowledge that a page was bookmarked, please add a button in the blue bar that can be tapped to change the folder in which the bookmark is assigned.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2278)

**Comment by lmarceau** [comment]
The Jira task has the same information contained as the Github issue
