### ISSUE TITLE
FXIOS-267 ⁃ Could Not Edit Newly Added Folder Name

### ISSUE THREAD

**Issue by muhasturk** [mozilla-mobile/firefox-ios#6120]
1. Launch the app
3. Go to Bookmarks
3. Tap on Edit
4. Tap on +
5. Tap on "New folder"
6. Enter any name and tap Save
7. Tap on newly created new folder
8. Select "mobile bookmarks" and any folder
9. Tap Save

Save button does not respond.

Below closure never called. I could not figured it out why.
https://github.com/mozilla-mobile/firefox-ios/blob/e774029b4e112341cfab88efac6d9be0a8c75b28/Storage/Rust/RustPlaces.swift#L66-L86

Environment
v22.0
Same behaviour on master branch

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-267)

**Comment by shyamrox** [comment]
I just cloned the master branch, and I can't duplicate this.

**Comment by dominickhera** [comment]
I know it's been a while but I judged wanted to add that I haven't been able to replicate this bug either. 

Tested on iPhone 12 Pro

**Comment by SimonBasca** [comment]
Unable to reproduce on v32.0 (3841). Feel free to re-open if the issue is still reproducible.
