### ISSUE TITLE
iOS auto correct/predict dictionary is updated in Private Browsing mode

### ISSUE THREAD

**Issue by garvankeeley** [mozilla-mobile/firefox-ios#6121]
Moved from https://bugzilla.mozilla.org/show_bug.cgi?id=1610195

Steps to reproduce:
Enter an unusual word in a text field in a Private Browsing tab multiple times.
This is a squishy repro, as I can see the symptom and am pretty sure of the cause, but can't figure out any way of reproducing on demand (nothing I do in any app has an immediate effect on the iOS prediction behavior). I believe it is possible but unlikely that I am not using Private Browsing consistently, thus invalidating this report.
Actual results:
Non-Firefox apps start to suggest that word when entering text.
Expected results:
Text entered in Private Browsing tabs should not be considered for predictive keyboard updates.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2282)

**Comment by athomasmoz** [comment]
Need to investigate if this is something we can control.

**Comment by SimonBasca** [comment]
I've manage to reproduce the issue on iPhone Xr (13.3).

1. Go to iOS Settings -> Keyboards -> Enable predictive text
2. Go to Wikipedia.org in Private Browsing
3. Tap on the text field
4. Make sure En keyboard is selected
5. Type "Mongol"

Actual results:
- Predictive words are are displayed.

Note:
- In Chrome in Private browsing following the STR will have the same actual results.
- Predictive words are only displayed when typing in text field while browsing on a page.
