### ISSUE TITLE
L10n - Strings in Manage Account & Devices Page does not fit the screen in other languages than English

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/firefox-ios#6130]
This  is reproducible latest beta **v22.x** (17157) and **master**. It is not screen related since it is this way in **iPhone 6s** or **iPhone X**.

**Steps**
Set the device in Spanish or Romanian
Sign in with a valid FxAccount
Go to Settings -> FxA email -> Manage Account & Devices

**Actual**
Please see screenshot attached
![IMG_5307](https://user-images.githubusercontent.com/1897507/74744862-3e60e980-5263-11ea-93ea-9613670a7ce3.PNG)

**Expected**
All the strings fit the screen properly
<img width="200" alt="Screenshot 2020-02-18 at 15 26 56" src="https://user-images.githubusercontent.com/1897507/74744827-2b4e1980-5263-11ea-8908-5693a522188e.png">

**Comment by brampitoyo** [comment]
@isabelrios This is definitely a bug, and there are a few ways to address it.

Our first preference (Plan A) is to fit as much text as possible by making the horizontal space wider. On iPad, this might be easy. But on a narrow phone, it’s not possible. So let’s move on to Plan B.

Plan B: reflow text to the next line, as shown below in “Dark Appearance Dims Wallpaper”.

<img width="320" src="https://user-images.githubusercontent.com/51007/76379368-c21a7b80-63b4-11ea-8991-eab14d248cf8.jpeg">

Plan C: show ellipsis on the side of the text, as shown below:

<img width="320" src="https://user-images.githubusercontent.com/51007/76379715-c4c9a080-63b5-11ea-894d-252fb6e1612c.png">

**Comment by isabelrios** [comment]
Thanks @brampitoyo from jumping in giving options to fix this! 
Let me ask also @athomasmoz about her point of view here. If I'm not mistaken I remember plan C working in the past, if not, I would say is the option more similar to other views.

Since we have to many options there I would not go to plan B, the screen may look very crowded 😓

**Comment by athomasmoz** [comment]
@brampitoyo which option were you suggesting here?

**Comment by brampitoyo** [comment]
@athomasmoz @isabelrios My preferred approach is B (reflow text to next line).

**Comment by athomasmoz** [comment]
This issue is in the FxA Webview. Need to raise on their side

**Comment by athomasmoz** [comment]
Closing this ticket as it needs to be fixed on FxA side. Ticket created here https://github.com/mozilla/application-services/issues/2798

**Comment by csuciu** [comment]
This issue was fixed on the FxA side and was verified.
