### ISSUE TITLE
UI: Weird Camera View on QR Reader

### ISSUE THREAD

**Issue by muhasturk** [mozilla-mobile/firefox-ios#6134]
- Open Firefox (on BrowserViewController)
- Rotate Phone landscape mode
- Open QR Reader (QRCodeViewController will load)

Problem 1
- Camera view is weird, because of `videoPreviewLayer.connection?.videoOrientation` was not initial set.

Problem 2
- ScanBorder view position and sizes are wrong.

https://mylifebox.com/shr/1018e7f6-e6d3-4676-a210-f43eaae4b679&language=tr

`willAnimateRotation(to:duration:)` used here which is deprecated iOS 8.0
https://github.com/mozilla-mobile/firefox-ios/blob/70ed7e4c30575956ab8d8d08875d38d3635a9794/Client/Frontend/Browser/QRCodeViewController.swift#L228

https://developer.apple.com/documentation/uikit/uiviewcontroller/1621458-willanimaterotation

**Comment by csuciu** [comment]
Verified as fixed on master aaf14a98c7.
