### ISSUE TITLE
[Regression] Link in a child window is not created

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/firefox-ios#6135]
Adding Regression since this started to happen after this very recent commit: 4c3cf89

There is this automated test failing: [testWriteToChildPoupTab()](https://github.com/mozilla-mobile/firefox-ios/blob/master/XCUITests/NavigationTest.swift#L385)
This is the [testing site](https://github.com/mozilla-mobile/firefox-ios/blob/master/test-fixtures/test-window-opener.html)  used  in the test.

Looks like the script in that site is not working to show the link that should be created.

**Before** this issue:
<img width="100" alt="Screenshot 2020-02-19 at 10 13 01" src="https://user-images.githubusercontent.com/1897507/74819871-56874600-5301-11ea-8041-85dca0bc5d72.png">

And **after**: 
<img width="100" alt="Screenshot 2020-02-19 at 10 12 21" src="https://user-images.githubusercontent.com/1897507/74819904-656df880-5301-11ea-9e1d-7ff377fc1b92.png">

cc @garvankeeley, as the test owner :) is this expected after that change or there is actually a bug? Thank you in advance!

**Comment by garvankeeley** [comment]
Interesting, seems like a bug to me

**Comment by garvankeeley** [comment]
This PR will fix it https://github.com/mozilla-mobile/firefox-ios/pull/6252

**Comment by isabelrios** [comment]
@garvankeeley yes, I tried and that PR fixes the issue. Tests passing both on iPhone an iPad. Thanks!
