### ISSUE TITLE
Internationalization: ErrorPageHelper Does Not Respect Device Language

### ISSUE THREAD

**Issue by muhasturk** [mozilla-mobile/firefox-ios#6136]
localizedDescription does not return suitable description for Turkish language.

- Change device language Turkish
- Open Firefox
- Close your internet connection or just simply turn on flight mode.
- Try to open any website
- Error description will be localized English rather than Turkish.

https://github.com/mozilla-mobile/firefox-ios/blob/a49c6f94d92fac3742f4d29f5f0d950f5002e7b7/Client/Frontend/InternalSchemeHandler/ErrorPageHelper.swift#L246

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2283)

**Comment by muhasturk** [comment]
Based on my research, error returned by `webView(_:didFailProvisionalNavigation:withError:)` does not have localized description. Just returns English error. 

We should check error code before using it and return custom error message something like below.

In ErrorPageHelper -> loadPage function
![Screen Shot 2020-02-19 at 16 15 56](https://user-images.githubusercontent.com/4077401/74837709-26f13180-5333-11ea-9b08-23269643940d.png)

**Comment by athomasmoz** [comment]
Thanks for logging. The solution for this is likely to add our own string and localize it.

**Comment by lmarceau** [comment]
Since only `data-sync-user` has commented on the issue after the `Stalebot` GitHub action (which triggered the removal of the `stale` label) I’ll close this issue for now. Please let us know if you think this issue needs to be reopened, we'll gladly do so. Thank you!
