### ISSUE TITLE
SPIKE: Adding Shield Icon to Alert

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-ios#6144]
**Acceptance Criteria**

* We know whether or not an icon can be included in an alert, while allowing the rest of the string to be translated
* We know how much effort it would be to add an icon in an alert

**Comment by nbhasin2** [comment]
<img width="515" alt="image" src="https://user-images.githubusercontent.com/8919439/75197649-c136e800-572c-11ea-8d53-6ba64ed6d37a.png">

@athomasmoz Adding a vector icon in the the english string is possible but translations for these strings is not trivial and require more work and we'll then need to figure out on where to put the icon in the string for a different language.

**Comment by athomasmoz** [comment]
Thanks for the investigation @nbhasin2 . For #6101 let's go without the icon then. The mock has been updated to a string without it.

**Comment by nbhasin2** [comment]
Sounds good @athomasmoz 👍

**Comment by nbhasin2** [comment]
@bryanbell As an fyi
