### ISSUE TITLE
The Change Passcode and Require Passcode options are not grayed out when Passcode is OFF

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/firefox-ios#6151]
## Steps to reproduce
1. Launch Firefox.
2. Reach settings and then `Face ID & Passwords`.
3. Turn the passcode OFF.
4. Observe the `Change Passcode` and `Require Passcode`.
### Expected behavior
The `Change Passcode` and `Require Passcode` options should be grayed out while the Passcode is OFF.
### Actual behavior
The `Change Passcode` and `Require Passcode` options are not grayed out when the Passcode is OFF.
### Device information

* Device: **iPad Pro (13.3)**
* Fenix version: **v23.0(17297)**

![unnamed](https://user-images.githubusercontent.com/42831109/75146046-e57dcf00-5702-11ea-8499-8c48621294ba.jpg)

**Comment by nishant2718** [comment]
I see this issue in prod on iPhone as well. I'll start looking into it.

**Comment by vphong** [comment]
I think I've pinpointed the problem on this. 

When a passcode is added or removed, we call this selector using NotificationCenter.
https://github.com/mozilla-mobile/firefox-ios/blob/512e03c0e9625269de5ed5ac4d9c3e58638b8dcf/Client/Frontend/AuthenticationManager/AuthenticationSettingsViewController.swift#L325-L329

but `generateSettings()` does not do anything with the notification. https://github.com/mozilla-mobile/firefox-ios/blob/512e03c0e9625269de5ed5ac4d9c3e58638b8dcf/Client/Frontend/AuthenticationManager/AuthenticationSettingsViewController.swift#L236-L242

I'm not totally sure about the best way to expose/send the notification to `generateSettings()`, so I hesitate to work on a fix. Any thoughts?

**Comment by KrystynaKruchkovska** [comment]
There is an open request already, textLabel?.textColor = UIColor.theme.tableView.rowText set after correct one.

**Comment by vphong** [comment]
Apologies, you're right! #6250 does fix the problem.

**Comment by dnarcese** [comment]
Fixed in #6250
