### ISSUE TITLE
Home "Custom URL" placeholder text is barely visible

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#6152]
Build: 23.0(17297)
Device: iPhone X
iOS: 13.3

Preconditions:
- Set theme to Manual Light.
- Set iOS theme to Dark.

Steps to reproduce:
1. Go to Settings -> Home
2. Check the "Custom URL" placeholder text

Actual results:
- The placeholder text is barley visible.

Expected results:
- The placeholder text should be visible.

![Screen Shot 2020-02-24 at 2 00 24 PM](https://user-images.githubusercontent.com/32130829/75150958-3e069980-570e-11ea-907a-c67e714db682.png)

**Comment by aaskrv** [comment]
Hi! Can you assign me to this? @SimonBasca

**Comment by csuciu** [comment]
Verified as fixed on master 5ba3e95. The text is displayed correctly.
