### ISSUE TITLE
Filter logins field has wrong text color in Light theme

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#6154]
Build: 23.0(17297)
Device: iPhone X
iOS: 13.3

Preconditions:
- Set theme to Manual Light.
- Set iOS theme to Dark.

Steps to reproduce:
1. Go to Settings -> Login & Passwords
2. Type in the "Filter" field

Actual results:
- The search icon in the "Filter" filed and the text is white in Light theme

![Screen Shot 2020-02-24 at 2 00 37 PM](https://user-images.githubusercontent.com/32130829/75150892-10215500-570e-11ea-9a24-e772d547e7b5.png)

**Comment by garvankeeley** [comment]
Reverted patch due to build error

**Comment by csuciu** [comment]
Verified as fixed on master b813a4c9b.
