### ISSUE TITLE
[FxA Upgrade] Investigate: Upgrade while user account in needs verification state goes to disconnected

### ISSUE THREAD

**Issue by garvankeeley** [mozilla-mobile/firefox-ios#6159]
We need to ensure that a user account that is not yet verified, when they upgrade the app to the new FxA, the account goes into a disconnected state.

This ticket is for the work of investigating what happens in this scenario currently.

**Comment by garvankeeley** [comment]
cc @rbillings

**Comment by AnaMedinac** [comment]
How would the disconnected state look like from the user stand point? Would it have a visible badge such as the yellow triangle, with a call to action to either `Reconnect` or `Verify Account`?

@athomasmoz Any thoughts on the user behaviour here?

**Comment by garvankeeley** [comment]
In general, the disconnected state is a silent state (app will be in the state where the user needs to 'sign in' to FxA). If the disconnected state is due to some error state that we can catch (such as a failure upgrading the FxA tokens from the old to the new OAuth token), we should show a caution badge on the app menu, and the account will appear like the user hasn't signed in.

**Comment by garvankeeley** [comment]
Ideally, in this case we would show the caution badge on the app menu, but because it is a super-rare edge case, and I don't know it is easily detectable, putting the user in the state where they have to sign in to sync seems ok (since they were stuck in the sign-in stage before the upgrade, there is no functional difference). Not sure yet what we can do as I haven't tried this case yet.

**Comment by athomasmoz** [comment]
Ok thanks. So you're saying that if we can identify a user is in a disconnected state, we will show a caution badge on the app menu. If we can't catch it, then what happens? 

And the particular circumstance in this ticket sounds pretty edgy. It's just if a user starts sign in, but doesn't verify their account and then upgrades, right?

**Comment by garvankeeley** [comment]
> Ok thanks. So you're saying that if we can identify a user is in a disconnected state, we will show a caution badge on the app menu. If we can't catch it, then what happens?

I should clarify, if we can identify the user was not in a disconnected state before upgrading, and then was moved to the disconnected state, we should try to catch this error and show a caution badge on the app menu. Hopefully we can do that for this particular issue too. If the error state is silent, we can decide if we should dig down (typically in collaboration with app-services) to try and capture the error. 

> And the particular circumstance in this ticket sounds pretty edgy. It's just if a user starts sign in, but doesn't verify their account and then upgrades, right?

Seems like an extreme edge case, and also we aren't regressing the user significantly (if we can't show a caution badge) because they were never connected to FxA/Sync.

**Comment by garvankeeley** [comment]
Moving this to QA verify so they can test and report back their findings.

**Comment by csuciu** [comment]
Tested the following:
*Case 1
User creates a new account on v23.0 but doesn't verify it. v23.0 shows the caution badge in the app menu. 
After upgrading to v23.1 latest Beta the user gets into the disconnected state and the badge is no longer shown. Going through the sign in flow, the email appears prefilled and sync works correctly after verifying the account.

*Case 2
User signs in with an existing account on v23.0 but doesn't verify it. The account appears as disconnected and there is no badge in the app menu.
After upgrading to v23.1 latest Beta the account is still disconnected and there's no badge. Going through the sign in flow, the email appears prefilled and sync works correctly after verifying the account.

**Comment by garvankeeley** [comment]
Ok thanks, I'll close this issue as working as expected
