### ISSUE TITLE
firefox beta version 23.0 (17297) not firing event (js?)

### ISSUE THREAD

**Issue by RobiBue** [mozilla-mobile/firefox-ios#6163]
I use the bcbsal.org website often, and noticed that there is an issue with events not firing on the iOS firefox versions. I am currently using the testflight Beta release 23.0 (17297) and already on the previous version I noticed it.
Problem is as follows:
on www.bcbsal.org
at the top of the website is a blue menu bar with "_my_BlueCross ˅" , "Find a Doctor ˅" , " _my_Health ˅" and so on.
To start explaining, I use the windows version first, then the iOS version.
On the windows version, In firefox 73.0.1 (latest version), upon click this menu fires once, and on second click on same menu, it closes as expected, but another click and consecutive ones do nothing unless the mouse is placed on a different menu item, but with the same results as previously mentioned. So on one hand this is a problem that the website needs to address.

On iOS on the other hand, I use an iPad with firefox beta version 23.0 (17297) and the menu never fires. In other words: I can not access Benefits summary or Resources under the _my_BlueCross menu item, Self Service or Benefits under Find a Doctor, and so on. I am also sending this message to the bcbsal development team, since I have the feeling that the problem lies within the implementation of the menu script, but also seems to have discrepancies between the two firefox versions.
![bcbsal](https://user-images.githubusercontent.com/52974977/75219882-a5026d80-5763-11ea-8eba-5ebb02b995ef.png)

**Comment by SimonBasca** [comment]
Hi @RobiBue, thanks for your feedback. Unfortunately the site is not loading on my side. I tried on iPad Air 3 (13.3) and also on desktop on Safari and on Firefox. I am inclined to think this is a site issue. If the site starts loading, can you please check if the issue is reproducible in Safari?

If it's not reproducible in Safari please re-open the issue. Thanks

**Comment by RobiBue** [comment]
The site reacts (or rather doesn’t) the same way on Firefox and Safari. Google chrome OTOH works as it is supposed to. Personally, I don’t like chrome or safari, although safari is embedded in iOS by default . 

I am not sure how to reopen it.
