### ISSUE TITLE
What's new page give "Page not found" message on Firefox 23.0 (17297)

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#6166]
Build: 23.0 (17297)
Device: iPhone Xr
iOS: 13.3

Steps to reproduce:
1. Clean install Firefox 23.0 (17297)
2. Open the menu
3. Tap the "What's new" button

Actual results:
- A "Page not found" message is displayed.

Note:
- Refreshing the page changes the message language.

![Screen Shot 2020-02-25 at 5 21 10 PM](https://user-images.githubusercontent.com/32130829/75261545-e6425e00-57f3-11ea-9db8-7349d61d732e.png)

**Comment by jonichan** [comment]
I've published a page and it's loading from my end now. Please let me know if you're still seeing issues.

**Comment by athomasmoz** [comment]
@SimonBasca do you mind checking if this has resolved the issue?

**Comment by RobiBue** [comment]
Issue is resolved. The page doesn’t explain much, but it doesn’t end up as “page not found”. (When I ran into this issue after the beta release, I landed on a  es-AR file not found page)
Thanks joni.
