### ISSUE TITLE
[iPad] New ETP title is not shown completly on iPad

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/firefox-ios#6168]
Seen on latest master:  a1b9751

**Steps**
Go to any website and tap on the shield icon

**Actual**
The ETP title shown is "Enhanced Tracking"
<img width="494" alt="Screenshot 2020-02-25 at 12 07 29" src="https://user-images.githubusercontent.com/1897507/75269594-746d1300-57f9-11ea-92ef-2c62e1a08b11.png">

**Expected**
The ETP tittle should be "Enhanced Tracking protection OFF/ON for this site."
![Screenshot 2020-02-25 at 12 07 37](https://user-images.githubusercontent.com/1897507/75269552-63bc9d00-57f9-11ea-806e-8e01fe08fb93.png)

**Comment by csuciu** [comment]
Verified as fixed on latest master and Beta v24.0(17528). The ETP title is correctly shown.
