### ISSUE TITLE
[FxA] "Missing clientId" when trying to login again (after using fxa web view 'Sign Out')

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/firefox-ios#6175]
## Steps to reproduce
1. Login on iOS.
2. Tap on the Firefox account(where the email is displayed).
3. Tap on the `Manage Account & Devices`.
4. On the top tap on the `Sign out` button.
5. Try to login again.
### Expected behavior
The login is successfully made and the FF account is displayed.
### Actual behavior
After adding the correct account data and tapping on `signin` the `Missing clientId` error is displayed no matter how many times you tap on the sign-in button.
### Device information

* Device: **iPhone X(13.2.2)**
* Fenix version: **v23.1(17325)**

### Notes
Note that after restarting the app or after trying to add the credentials in order to log in again, eventually the login is successfully made.

![IMG_0019](https://user-images.githubusercontent.com/42831109/75350578-70033180-58af-11ea-9052-406787e78eae.PNG)

**Comment by garvankeeley** [comment]
Although this button will be removed soon, until then the behaviour is fixed in the latest beta.
