### ISSUE TITLE
[FxA Upgrade] "Could not load page." error after using web view 'Sign Out' button 

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/firefox-ios#6176]
## Steps to reproduce
1. Login on iOS.
2. Tap on the Firefox account(where the email is displayed).
3. Tap on the `Manage Account & Devices`.
4. On the top tap on the `Sign out` button.
5. Go back to Firefox Account and tap on `Disconnect Sync`.
5. Tap on the hamburger menu and access settings.
6. Tap on `Sign in to Sync`.
### Expected behavior
The Sign-in page is correctly displayed.
### Actual behavior
`Could not load page.` error is displayed every time when trying to access `Sign in to Sync` from settings.
### Device information

* Device: **iPhone X(13.2.2)**
* Fenix version: **v23.1(17325)**

### Notes
Note that after restarting the app the error is still displayed. The login cannot be made from the settings.

![IMG_20200226_155410](https://user-images.githubusercontent.com/42831109/75355502-464e0880-58b7-11ea-9b32-3523b6ddf88b.jpg)

**Comment by garvankeeley** [comment]
That in-content 'Sign Out' button might be a bug that it appears. It isn't on release, filed it https://github.com/mozilla-mobile/firefox-ios/issues/6178

**Comment by csuciu** [comment]
This also happens when trying to reconnect after changing the password. (Asking to reconnect after changing the pass looks like a bug - filed it #6187 )

**Comment by garvankeeley** [comment]
Although this button will be removed soon, until then the behaviour is fixed in the latest beta.
