### ISSUE TITLE
[FxA] The keyboard does not popup when tapping on the "Sign in" button(without selecting the password field)

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/firefox-ios#6177]
## Prerequisites 
Make sure you are logged in.
## Steps to reproduce
1. Logout from the FF account.
2. Access the hamburger menu and tap on the `Sign in to Sync`.
3. The email is displayed, without tapping on the `password` field tap on the `Sign in` button.

### Expected behavior
The keyboard should popup and the text selector should also be displayed on the `password` field.
### Actual behavior
`Valid password required` error is displayed but the keyboard does not popup.
### Device information

* Device: **iPhone X(13.2.2)**
* Fenix version: **v23.1(17325)**

### Notes
On Fenix FxA page when trying those steps, the keyboard pops up creating a more simple flow for the user in order to log in.

![Screenshot 2020-02-26 at 17 03 03](https://user-images.githubusercontent.com/42831109/75357727-819e0680-58ba-11ea-854e-98afd9f140e9.png)

**Comment by garvankeeley** [comment]
>     1. Logout from the FF account. 
>     2. Access the hamburger menu and tap on the `Sign in to Sync`.
>     3. The email is displayed, without tapping on the `password` field tap on the `Sign in` button.

I can see your point, that it might be a bit more convenient to put focus on the text field at this point. However, I have not seen this as a practice on iOS, so we don't want to do anything unusual here. (I could imagine it could cause accessibility problems, users don't expect the side effect of putting focus on a button, to move focus to a text field). I think the keyboard should only popup if a user has tapped on text field and we shouldn't special-case this.
