### ISSUE TITLE
[FxA Upgrade] FxA Web View shows an in-content 'Sign Out' button, it shouldn't

### ISSUE THREAD

**Issue by garvankeeley** [mozilla-mobile/firefox-ios#6178]
<img width="315" alt="image" src="https://user-images.githubusercontent.com/5495083/75357990-3535d500-5880-11ea-9b7c-f410b0852bba.png">

Suddenly a 'Sign Out' button has appeared, this isn't on our release versions so I assume this is not intentional

**Comment by athomasmoz** [comment]
This needs to be fixed on the FxA side mozilla/fxa#4284

**Comment by vbudhram** [comment]
@garvankeeley I tested this with a local build of what is on master and did not see the sign-out error. Is there a specific version or steps needed to reproduce?

![Screen Shot 2020-03-03 at 5 35 17 PM](https://user-images.githubusercontent.com/1295288/75826423-76911d80-5d75-11ea-9346-f17b82aa4b25.png)

**Comment by garvankeeley** [comment]
Either on the 23.1 public beta, or use the `rust-integration` branch

**Comment by garvankeeley** [comment]
FxA side has fixed this https://github.com/mozilla/fxa/issues/4284

**Comment by garvankeeley** [comment]
New fix is here: https://github.com/mozilla/fxa/pull/4510
