### ISSUE TITLE
SPIKE: Improve Buddy Build / Release time of the app

### ISSUE THREAD

**Issue by nbhasin2** [mozilla-mobile/firefox-ios#6181]
Currently buddybuild takes anywhere between 25 ~ 40 min to build the app and doesn't report any test failures until its fully finished. If any tests fail then we have to do it all over again. 

I am proposing this issue as an issue where we improve our pipeline and make it faster (if possible) or atleast look into options on how to make faster builds. 

----

**Acceptance Criteria**

* Recommendation to reduce buddy build times

**Comment by garvankeeley** [comment]
Partially a cost issue, we could pay for more builders.

**Comment by nbhasin2** [comment]
### Context:

Current build times range from 23min to 45min and below are the findings and some proposed solutions we can try to reduce it

### Findings:

1. We currently have 6 build machines which support multiple apps (see below) and when they all build multiple branches build at the same time we are limited by the number of machines available 
    - Firefox iOS
    - Focus
    - FPN
    - XViewer
2. Highest priority is given to the master branch of the app(s) and then its sub branches. Lowest priority is given to the branches from the forks which causes delays in PR build. 
3. The carthage checkout and build takes almost 6min ~ 10 min 
4. Another thing I found is that even after pushing carthage folder in my tests buddybuild was still pulling carthage dependencies. This is likely a bug on their side but its still time consuming. 

### Proposed solution(s):

1. Increase the number of build machines to 10 
2. Cache carthage - guaranteed decrease inin time
    - Push carthage folder - Tried but found issues
    - Custom rome cache setup which we did before but will give it another shot - [worth trying] - [https://github.com/tmspzz/Rome](https://github.com/tmspzz/Rome)

### Follow-up ticket
https://github.com/mozilla-mobile/firefox-ios/issues/6299
