### ISSUE TITLE
[FxA Upgrade] Support China server URLs

### ISSUE THREAD

**Issue by garvankeeley** [mozilla-mobile/firefox-ios#6182]
I don't think this is being used anymore: https://github.com/mozilla-mobile/firefox-ios/blob/master/Account/FirefoxAccountConfiguration.swift#L20

We need China server URLs to be used when in that locale

**Comment by garvankeeley** [comment]
From slack convo, that configuration block can be deleted from the code, and the constructor for Fx accounts needs to be 
`FxAConfig(contentUrl: "https://accounts.firefox.com.cn", clientId: sameclientid, redirectUri: sameredirectUri)`

**Comment by garvankeeley** [comment]
Unknown if the China servers are up-to-date with the main servers to support our current setup. Need to follow-up with Sync team.

**Comment by garvankeeley** [comment]
App-services is working on https://github.com/mozilla/application-services/issues/2735

**Comment by garvankeeley** [comment]
Fixed client-side in 6e95f7912d5bef9974dd2afd87f8e6c08748a63c

**Comment by l-hedgehog** [comment]
> Unknown if the China servers are up-to-date with the main servers to support our current setup. Need to follow-up with Sync team.

Hi, our changes were rebased onto FxA train-159 and went into production on Feb. 27th, our ops @xjc2694 made the config/db changes as described in https://bugzil.la/1609455, with the `redirectUri` being `https://accounts.firefox.com.cn/oauth/success/1b1a3e44c54fbb58`, per suggestions from @rfk in a #synced-client-integrations thread.

Please let me know if more changes are necessary on our side. Thanks!

**Comment by garvankeeley** [comment]
Thanks! Releasing in today's beta to testers

**Comment by bli-mozbj** [comment]
New installation of Firefox for iOS 23.1(17361)  + FxA China server (train-159)
Failed to sync bookmarks and logins from the server after sign in.
Bookmarks and logins panel are empty.

Here are the log files:
[sync.20200304T173027+0800.log](https://github.com/mozilla-mobile/firefox-ios/files/4286602/sync.20200304T173027%2B0800.log)
[browser.20200304T173027+0800.log](https://github.com/mozilla-mobile/firefox-ios/files/4286601/browser.20200304T173027%2B0800.log)

Newly added bookmarks cannot be synced to other devices too.

**Comment by garvankeeley** [comment]
Closed by #6213
