### ISSUE TITLE
History Panel Clear Recent History Everything Does Not Remove Recently Closed Tabs

### ISSUE THREAD

**Issue by muhasturk** [mozilla-mobile/firefox-ios#6184]
- Open History Panel
- Tap "Clear Recent History"
- Choose "Everything"
- History will be removed but "Recently Closed" tabs still exist.

![Simulator Screen Shot - 11 Pro Max - 2020-02-27 at 10 29 40](https://user-images.githubusercontent.com/4077401/75421857-451aeb00-594c-11ea-90a6-0347d13e116e.png)

**Comment by csuciu** [comment]
Verified as fixed on master 324fc94a0. "Recently Closed" tabs list is cleared when clearing all history.
