### ISSUE TITLE
[FxA Upgrade] User is requested to enter the password to reconnect after sucessfully changing it

### ISSUE THREAD

**Issue by csuciu** [mozilla-mobile/firefox-ios#6187]
1. On iOS go to the accounts management page and change the account password.
2. Open the hamburger menu check FxA status.

Expected: The user appears connected.

Actual: The user is asked to enter the password to reconnect.

This is behaviour change vs v23.0 which automatically reconnects the account upon changing the password

**Comment by garvankeeley** [comment]
fixed by https://github.com/mozilla/application-services/pull/2744

**Comment by csuciu** [comment]
Verified as fixed on v23.1 (17397). FxA no longer needs re-authentication after changing the password
