### ISSUE TITLE
[FxA upgrade] Changes to display name and/or account picture are not reflected in the app UI until restarting it

### ISSUE THREAD

**Issue by csuciu** [mozilla-mobile/firefox-ios#6190]
1. Open the account management page on iOS.
2. Add a display name and/or an account picture.
3. Exit the account management page and check the hamburger menu and the settings page.

Expected: The picture and the name are displayed in both places.

Actual: The picture and the name are visible only after restarting the browser.

**Comment by garvankeeley** [comment]
For #2, where is the display name reflected in the UI?
EDIT: nvm, it is in the app menu sync title, I see now

**Comment by mirunacurtean** [comment]
Also applies to syncing updates to device name and photo across devices, from Desktop (windows 10 -64 bit with FF 74.0) and Android (8.0.0 with Fennec 68.5.0)  to iOS. 
Tested with iPhone 13.3.1. When display name or photo are updated from windows or android and manual sync is performed, the changes are applied only after iOS app restart.

**Comment by nbhasin2** [comment]
This issue is related to https://github.com/mozilla/application-services/issues/2902
Waiting on new Application Service Lib

**Comment by SimonBasca** [comment]
Verified fixed on 25.0 (17793)
