### ISSUE TITLE
WebXR/XRViewer push notification service broken

### ISSUE THREAD

**Issue by garvankeeley** [mozilla-mobile/firefox-ios#6193]
The WebXR branch doesn't have a working push notification service. It might be something our team has to jump on and help with.

I suggest creating a fresh branch with a minimal set of changes to rename Firefox iOS to XRViewer (a non-trivial task, as there are a lot of changes needed), and seeing if the push notification system can be setup.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2293)

**Comment by athomasmoz** [comment]
@blairmacintyre Is this still broken on WebXR viewer?

**Comment by lmarceau** [comment]
Since only `data-sync-user` has commented on the issue after the `Stalebot` GitHub action (which triggered the removal of the `stale` label) I’ll close this issue for now. Please let us know if you think this issue needs to be reopened, we'll gladly do so. Thank you!
