### ISSUE TITLE
FXIOS-281 ⁃ Pocket Event Count

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-ios#6195]
**Vision**

As a Product Manager, I want to know how often Pocket articles are being picked, so that I can ensure it's giving users value on our new tab page & see the effect of changes in design

- - -
**Acceptance Criteria**

* Counts on pocket article clicks tracked
* None of the data collected includes information on what article a user clicked

**Questions to Answer with Data**

* Count to let us know what percent of users click on a Pocket article
* Count to let us know the click-through-rate (how many pocket articles are clicked on compared to new tab opens)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-281)

**Comment by data-sync-user** [comment]
➤ Jeremy Evans commented:

Will need tracking event keys for these

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verified fix on v32.0 (3823).
