### ISSUE TITLE
[FxA Upgrade] Send to device from share sheet not working

### ISSUE THREAD

**Issue by garvankeeley** [mozilla-mobile/firefox-ios#6201]
Note this should be an easy fix, the new RustFirefoxAccount needs to be initialized.

**Comment by garvankeeley** [comment]
Fixed in a183b2445885bedb8f6eedba0eee3487f1878962

**Comment by csuciu** [comment]
Verified as fixed on v23.1 (17397). Send to device from share sheet it's now working.
