### ISSUE TITLE
Placeholder text does not follow dynamic font sizing

### ISSUE THREAD

**Issue by dnarcese** [mozilla-mobile/firefox-ios#6206]
The placeholder text `Custom URL` is always a constant text size instead of following the user's setting, making it look different than the other text on the page.

Examples: 
New Tab settings and Home Page settings
![IMG_D49C47CE0F85-2](https://user-images.githubusercontent.com/11432165/75816008-5efc6980-5d62-11ea-8d75-a4fe97924021.jpeg)
![IMG_D49C47CE0F85-1](https://user-images.githubusercontent.com/11432165/75816029-66237780-5d62-11ea-8335-13c7f7107311.jpeg)

**Comment by vphong** [comment]
Hey, I'm looking into this. It seems like all that has to be done is specifying the `textField`'s font using `DynamicFontHelper` like so: https://github.com/vphong/firefox-ios/blob/ab57004d1bf47e9aee198bcad166a3c24f001cc0/Client/Frontend/Settings/SettingsTableViewController.swift#L367

This is what it looks like now, after setting a larger font in the Accessibility settings: 
| Home Page Settings | New Tab Settings |
|-------|-------------|
|![Simulator Screen Shot - iPhone 11 Pro Max - 2020-03-06 at 18 08 48](https://user-images.githubusercontent.com/13925498/76134747-9292fa00-5fd5-11ea-9d26-ff58b97894e2.png) | ![Simulator Screen Shot - iPhone 11 Pro Max - 2020-03-06 at 17 53 55](https://user-images.githubusercontent.com/13925498/76134654-c6b9eb00-5fd4-11ea-89cc-1c7768b33e49.png)|

I'm not totally sure if the `textField` itself can be dynamically resized. Does this look ok so far though?

**Comment by dnarcese** [comment]
@vphong The font looks good, but we would also want to make sure that the height of the row is dynamically changing as well

**Comment by tfiosecmtv** [comment]
I built the app using simulator, it seems fine
<img width="354" alt="Screen Shot 2020-03-17 at 18 07 54" src="https://user-images.githubusercontent.com/39702928/76858988-41f38a80-687a-11ea-8578-8c421c68091e.png">
