### ISSUE TITLE
[fxa upgrade] Send Tab device picker does not dismiss after (successfully) sending a tab

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/firefox-ios#6207]
I successfully sent a tab from Beta 23.1 (17361) to my (macOS) desktop. However, the Send Tab device picker on my iPhone did not disappear after hitting _Send_. It just sits there with an active spinner in the top right.

**Comment by garvankeeley** [comment]
Confirmed.

**Comment by garvankeeley** [comment]
Fixed by 1536214b1e69cd700b89859588bea22d8023f3c8

**Comment by csuciu** [comment]
Verified as fixed on v23.1(17400). Send Tab device picker is successfully dismissed after sending a tab.
