### ISSUE TITLE
[FxA Upgrade] Sign in form "Could not load page" when trying to sign in from Firefox Account Settings menu

### ISSUE THREAD

**Issue by mirunacurtean** [mozilla-mobile/firefox-ios#6211]
**Steps to reproduce**
1. Install Firefox Beta (v23.1)
2. Open app and go through Welcome to Firefox flow without signing in. (Next> Start browsing)
3. Once rexaching Firefox app home screen navigate to Settings> Firefox Account. 
4. Tap on the Sign in to Sync button. 
 
**Expected result:** 
"Enter your Email/Continue to Firefox Sync" page is loaded and user has to enter a valid email to continue sign flow. 

**Actual results:**
Could not load page. error is displayed every time when trying to access Sign in to Sync from settings.

**Device information**
Device: iPhone X(13.2.2)

**Notes**
While ticket 6167 has been logged for this issue occuring after using Sign out button from Manage Account this test has been performed this flow has no precondition besides installing the app. 

![Could not load](https://user-images.githubusercontent.com/53306802/75883887-7142da00-5e2c-11ea-81f7-120301974bf8.gif)

**Comment by garvankeeley** [comment]
fixed by #6217

**Comment by mirunacurtean** [comment]
Issue verified as fixed on iPhone X(13.2.2) and iPhone 8 (13.2.3) on Beta 23.1(17397).  
After tapping on the 'Sign in to Sync' button from the Settings menu the "Enter your Email" or "Sign in to Continue to Firefox sync" page is loaded.
