### ISSUE TITLE
[FxA Upgrade] Sync options which were deselected during Create Account flow are still showing as switched on in Firefox Account Sync settings

### ISSUE THREAD

**Issue by mirunacurtean** [mozilla-mobile/firefox-ios#6212]
**Steps to reproduce**
1. Install Firefox Beta (v23.1)
2. Open app in Welcome to Firefox flow choose to Sign up.  
3. In the Create Account flow enter a valid email, password and age for the registration form and tap to Continue. 
4. Reach CWTS screen a deselect between 1 to 3 of the sync preferences. 
5. Finish up account verification and then reach iOS FF app home screen. 
6. Open menu and go to Settings> Firefox Account and view Sync Settings. 
 
**Expected result:** 
Sync options that are deselected during account creation are switched off. 

**Actual results:**
All Sync options are switched on. 

**Device information:**
Device: iPhone X(13.2.2)

Notes: 
This also occurs when creating an account from Synced Tabs menu. 

![CWTS options are not saved in browser after account creation](https://user-images.githubusercontent.com/53306802/75891036-e1a32880-5e37-11ea-9311-54e47837173c.gif)

**Comment by garvankeeley** [comment]
Fixed by #6219

**Comment by mirunacurtean** [comment]
This appears to be fixed in Beta 23.1(17397), after performing an additional account Sync Now. 
Verified on iPhone X(13.2.2) and iPhone 8 (13.2.3) by: keeping all options selected, deselecting them all, deselecting a couple of options.
