### ISSUE TITLE
A/A Test in Leanplum

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-ios#6216]
**Vision**

Confirm that we can measure results of multivariate tests in Leanplum

----

**Acceptance Criteria**

* Two identical user experiences with different group names are launched in the app through Leanplum
* Data Science has been given the group names to test analysis in Leanplum
* Test does not interfere with upcoming iOS releases

**Comment by nbhasin2** [comment]
For our basic test I have the following setup:
variable: showOnboardingScreen
type: Boolean (default value = true)
usage: Idea is to show or hide onboarding screen with the value that comes from server
On the server you can configure how many users you want to set the value to be true / false
Note: The value itself will only be printed in the logs and user should not see any changes in the UI.

**Comment by athomasmoz** [comment]
Hey @nbhasin2 when would we see this launch? Is it a button you push some time after the release?

**Comment by nbhasin2** [comment]
@athomasmoz, Ideally as soon as we release the app. We won't have any audience hence until users get the new app.

I made a simple A/B test under Nish's AB test in Leanplum that we can change into a proper AA test.
