### ISSUE TITLE
[fxa upgrade] Disconnect account, FxAccountManager in authenticationProblem state

### ISSUE THREAD

**Issue by garvankeeley** [mozilla-mobile/firefox-ios#6220]
STR: connect account, then disconnect account using Settings, restart the app.
RESULT: caution symbol on app menu (because FxAccountManager reports hasAccount() is true, and its state as `authenticationProblem`)
EXPECTED: hasAccount() to be false

**Comment by garvankeeley** [comment]
@eoger can you review https://github.com/mozilla-mobile/firefox-ios/blob/rust-integration/Client/Helpers/FxALoginHelper.swift#L154
and see if we are doing disconnect properly?

**Comment by garvankeeley** [comment]
Fixed on a-s side https://github.com/mozilla/application-services/issues/2754

**Comment by csuciu** [comment]
Verified as fixed on v23.1 (17397). Account appears signed out after disconnecting and re-starting the app. Also I was able to sign in with a different account after the previous steps.
