### ISSUE TITLE
[fxa upgrade] Decide what to do about re-auth case for FxAWebView

### ISSUE THREAD

**Issue by garvankeeley** [mozilla-mobile/firefox-ios#6221]
We have a todo to handle the re-auth case when tapping on the account:
https://github.com/mozilla-mobile/firefox-ios/blob/rust-integration/Client/Frontend/Settings/AppSettingsOptions.swift#L349

We also need to figure out how to test this.

cc @eoger

**Comment by eoger** [comment]
For this case you'd have to start an OAuth flow again, so in your specific case I assume launch the webview.

**Comment by garvankeeley** [comment]
Launching webview as recommended. Fixed in fc9145f34068ee89d67127bc5b36d7a2e4c599a8
