### ISSUE TITLE
[FxA Upgrade] Account needs to be manually synced again after login in order to show previous sync settings updates

### ISSUE THREAD

**Issue by mirunacurtean** [mozilla-mobile/firefox-ios#6222]
**Builds tested on:** 
FF Beta 23.1 (17361)
FF Release 23.0 (17297)

**Device information**
iOS: iPhone X(13.2.2)

**Steps to reproduce:**
1. Install on iOS Beta 23.1 FF app. 
2. Sign in with FF account. 
3. Navigate to Settings> Firefox Account and switch Sync settings. 
4. Return to Settings and make sure that sync is performed and then from Firefox Account tap to Disconnect Sync.
5. Sign in again and navigate to Firefox Account to view Sync Settings. 

**Expected result:** 
Account is synced after sign in and and the sync settings toggle buttons reflect the state of the setting as updated before sign out. 

**Actual results:**
Any changes made before disconnect to sync settings are saved and displayed correctly after sign in without additional syncing needed. 

**Note:** In production on 23.0 (17297) sync settings are saved before disconnect and upon reaching 
Firefox Account menu it can be noticed that sync settings are toggled on or off correctly without additional sync being needed. 

![Sync-settings](https://user-images.githubusercontent.com/53306802/75991034-7cfed100-5efe-11ea-922a-2a2be976bf24.gif)

**Comment by garvankeeley** [comment]
Fixed by https://github.com/mozilla-mobile/firefox-ios/pull/6219

**Comment by mirunacurtean** [comment]
Verified fixed on Beta 23.1(17397) across iPhone X(13.2.2) and iPhone 8 (13.2.3). 
Sync settings are saved after being switched off or on. 
Selected preferences are on after app restart and signout/sign in as well. 

![Create account flow 2 CWTS-are-synced](https://user-images.githubusercontent.com/53306802/76083404-35d41700-5fb6-11ea-8525-6368b447db5f.gif)
