### ISSUE TITLE
[Fxa Upgrade] [CWTS] Updates to sync settings are not synced across multiple devices on iOS 13

### ISSUE THREAD

**Issue by mirunacurtean** [mozilla-mobile/firefox-ios#6227]
**Build:** 
iOS: FF Beta 23.1 (17361)
Windows: FF 73.01
Android (Fennec): FF 68.5.0

**Device information:**
iPhone X(13.2.2)
Windows PRO 10 64-bit
Android 8.0.0

**Preconditions:** 
Existing FF account is signed in on multiple devices. 

**Steps to reproduce:**
1. On iOS launch Beta 23.1 (17361) and go to Settings>Firefox Account. 
2. Modify sync options toogle for any of the sync settings and return to Settings menu to SYnc now.
3. After iOS sync has finished navigate to Sync menu on android and about:preferences#sync on Windows. 
4. Sync Now on Android and Windows and check that the same sync settings selected on iOS are selected on Windows and Android as well. 

**Expected result:** 
Any options that have been selected on iOS are reflected on Android and Windows browsers as well after being modified and synced. 

**Actual results:**
Different or not all sync settings are synced off on Android and Windows. See attachments below. 

**Notes:** 
This might also be fixed by #6223 but I logged it in order to verify the fix in the new build. 

Sync options on iOS
![SYNC-settings-modified-on-iOS](https://user-images.githubusercontent.com/53306802/76008288-11c1f880-5f18-11ea-8ba6-d4259f6fed03.gif)

Sync setting on windows after sync now. 
![Synced options on Windows](https://user-images.githubusercontent.com/53306802/76008308-1b4b6080-5f18-11ea-83c4-62067a2fba21.PNG)

Sync options on Android after sync now.
![Android sync options selected](https://user-images.githubusercontent.com/53306802/76008366-361dd500-5f18-11ea-8957-cb8affae6d7a.jpeg)

**Comment by garvankeeley** [comment]
Can you re-test on 17397? Thanks

**Comment by mirunacurtean** [comment]
Between iOS 12.4 to Windows 10 64-bit and Android 8.0.0 syncs modified settings between devices on the new build but on iOS 13.2.2 the updated that I make on iOS are not performed or not performed correctly over to desktop and android.

**Comment by mirunacurtean** [comment]
Could no longer reproduce on Beta 23.1 (17416) with iPhone x (13.3)
1. Account created with all CTWS options selected and signed in on multiple devices (ios. desktop and android). 
Switched off/ on sections were synced as expected across all devices and OSes. 
2. Account created with all CWTS switched off and and then signed in on multiple devices (desktop and adnroid fennec and fenix). Sync setting updates are synced across devices. 
3. Account created with half the options selected and then synced across Desktop and Android too. Sync setting updates are synced across devices.

**Comment by athomasmoz** [comment]
Thanks for rechecking. Closing as no longer reproducible. Note that we still have a similar issue open #6241
