### ISSUE TITLE
[FxA Upgrade]FxA management page gets automatically dismissed after changing password

### ISSUE THREAD

**Issue by csuciu** [mozilla-mobile/firefox-ios#6229]
v23.1 (17397)

Steps:
1.  Open the FxA management page.
2. Change the account password.

Expected: The user is returned to the management page after changing the password. Also, a banner notifying the user that the password was changed successfully is displayed.

Actual: The FxA management page gets dismissed immediately after changing the password and the user it returned to the Firefox home page.

Here's how it looks on v23.0:
![Screen Shot 2020-03-06 at 11 33 51](https://user-images.githubusercontent.com/1866605/76073140-d966fc80-5fa1-11ea-8839-e65e05bc457e.png)

**Comment by garvankeeley** [comment]
fixed by fc9145f34068ee89d67127bc5b36d7a2e4c599a8

**Comment by csuciu** [comment]
Verified as fixed on v23.1(17400). The FxA management page is no longer dismissed after changing the account password.
