### ISSUE TITLE
[FxA Upgrade] User is stuck in sign in flow instead of being directed to Create Account flow when trying to 'Use a different account' to sign in

### ISSUE THREAD

**Issue by mirunacurtean** [mozilla-mobile/firefox-ios#6230]
**Steps to reproduce:**

1. Install Firefox Beta v23.1 ((17397) and launch it.
2. Choose to Sign up and go through the Create account flow with valid data and verify the account. 
3. After account is verified and signed in, in the browser navigate to Settings> FireFox Account> Manage Account and Disconnect Sync. 
4. Use any of the Sign in entry points from the app (Synced Tabs, Home menu, Settings) to try and sign up with a new account. 
5. In 'Sign in' screen the previous email address is already added. Tap "Use a different account" to enter an email which is not associated with an existing account
5. Tap to Continue. 

**Expected result:** 
Enter Create Account form.

**Actual results:**
User is returned to 'Sign in to Continue to Firefox' screen where the password is requested to Sign In. 
When trying to add a password the "Incorrect password" error tooltip is shown. 

**Device information:**
iPhone X(13.2.2)
iPhone 8 (13.2.3)

**Notes:**
1. This issue has been reproduced 6/10.
2. This also occurs if initially the user signs in in the Welcome to Firefox flow or if signing in later on from any of the browser sign in entry points. After disconnecting from the first account and trying to sign in with a different one the user is not directed to create account form. The repro rate is lower for this scenario. 
3. Also occurs after sign out when trying to sign up in the 'Synced tabs> Create an account' flow.
4. Also occurs some of the time after app install. in Welcome to Firefox flow when trying to "use a different account" than the one initially inputted. 

In the attached GIF I was initially logged in with mcurtean+21@mozilla.com and after sign out I tried using mcurtean+22@mozilla.com which is not associated with an existing account. 

![Create new account flow is not working when you disconnect one account and then try to create another ](https://user-images.githubusercontent.com/53306802/76073497-5a25f880-5fa2-11ea-82a0-b25d6b3f4927.gif)

**Comment by garvankeeley** [comment]
I am having difficulty reproducing this. @csuciu can you try?

**Comment by csuciu** [comment]
I tried to repro several times but wasn't able to. @mirunacurtean Can you please check this o  latest Beta?

**Comment by mirunacurtean** [comment]
Indeed, after updating both device OS and Ff version, I can no longer reproduce this on Beta 23.1 (17416) using iPhone X (13.3). 
I've tried using the Welcome to Firefox sign in flow, to change the email midway through and it went successfully into Create account flow. 
Also tested after disconnecting from the app, by signing up with a new account from all the sign in entry points. 
I have no permissions so I'd appreciate it if you could update this issue (change/take off tags) . Thank you!

**Comment by athomasmoz** [comment]
Thanks for rechecking. Closing as working now
