### ISSUE TITLE
[fxa upgrade] Share sheet > Send tab devices list is updated only after re-starting the app

### ISSUE THREAD

**Issue by csuciu** [mozilla-mobile/firefox-ios#6231]
v23.1 (17397)

Steps:
1. Sign in with the same account on desktop and iOS.
2. On iOS, check the devices list from Share Sheet > Send Tab. 
         > the desktop device is correctly listed.
3. On desktop, disconnect the account.
4. Check  again the devices list from Share Sheet > Send Tab. 

Expected: There is no device listed.

Actual: The device still appears in the list. The list gets cleared only after restarting the app.

Note: This issue is not reproducible if the list is open via Send Tab Menu item and also, it is not reproducible on v23.0 release.

**Comment by garvankeeley** [comment]
Fixed by #6231

**Comment by csuciu** [comment]
Verified as fixed on Beta 23.1(17416). The Send Tab devices list is updated correctly.
