### ISSUE TITLE
Facebook marketplace listings open about:blank tabs 

### ISSUE THREAD

**Issue by evelyn-marie** [mozilla-mobile/firefox-ios#6234]
When browsing Facebook on FF iOS, browsing to the Marketplace and clicking on a listing instead loads a new tab with "about;blank" and nothing else. Was reported on SUMO: https://support.mozilla.org/en-US/questions/1281432#answer-1295720 and I replicated it on my device as well. 

Fully updated iOS and FF.

**Comment by dnarcese** [comment]
This is caused by #6117

**Comment by csuciu** [comment]
Verified as fixed on master e5d00ffb3. The content is correctly loaded in a new tab when clicking on a listing in Facebook marketplace.
