### ISSUE TITLE
Update URL for 'New' title in Trending on Pocket section

### ISSUE THREAD

**Issue by kanhema** [mozilla-mobile/firefox-ios#6235]
Current URL: https://getpocket.com/explore/trending?src=ff_ios&cdn=0
New URL: https://getpocket.com/explore?src=ff_ios&cdn=0

Acceptance Criteria

• Users clicking on the "More" title under "Trending on Pocket" will be taken to the /explore landing page. 
• Landing page can be updated without requiring additional changes to Firefox for iOS.

**Comment by athomasmoz** [comment]
Hey @kanhema can you confirm what change is needed from our side. Is there a different URL we should be using?

**Comment by kanhema** [comment]
We're setting up a redirect URL to use here, will update once it's ready.

**Comment by kanhema** [comment]
Here's the new URL for "More"

![File](https://user-images.githubusercontent.com/1165377/78131318-2dd38f80-741b-11ea-833d-a47fc5353426.jpg)

**Comment by kanhema** [comment]
Thanks! @kaylagalway @athomasmoz

**Comment by SimonBasca** [comment]
Verifying as fix on 25.0 (17758).
