### ISSUE TITLE
Losing tabs after re-opening app

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-ios#6239]
Reports have been coming in that tabs are lost after re-opening the app. This can be a big impact for users who have a lot of tabs open and/or are keeping a tab open to refer back to. 

A few examples from the app store:
https://appbot.co/apps/854569-internet-browser-firefox/reviews/1569463848
https://appbot.co/apps/854569-internet-browser-firefox/reviews/1563405190
https://appbot.co/apps/854569-internet-browser-firefox/reviews/1521728188

**Steps to Reproduce**

_Intermittent_
1. Open a number of tabs
2. Close the app
3. Open the app

**Expected Behaviour**
App opens and tabs are still present

**Actual Behaviour**
App opens and tabs are gone

**Comment by garvankeeley** [comment]
The restore tabs logic might be out-of-date, or too sensitive to crashes due to Sync being killed while in background: https://github.com/mozilla-mobile/firefox-ios/blob/master/Client/Frontend/Browser/BrowserViewController.swift#L539

**Comment by athomasmoz** [comment]
Potential solution could be to prompt users if we think a tab is crashing. 
This could be related to sync crashing. Can we test crashing sync and seeing if it stops tabs from restoring tabs

**Comment by SimonBasca** [comment]
We tested this intensively on devices using iOS 13.x and iOS 14.x but so far we haven't been able to find STR. We will keep trying to reproduce

**Comment by athomasmoz** [comment]
Thanks, @SimonBasca . I can close at cannot reproduce and keep an eye on the reviews to see if the issue continues

**Comment by SimonBasca** [comment]
@athomasmoz do you have any idea from where the reports are coming from? I remember seeing a some of them from Chinese users. It might be something that's on the China version, we are using a different server there. It's just a hunch, I may be wrong.

**Comment by garvankeeley** [comment]
This is a puzzle. Tab restoration doesn't use sync. I can't think of why China would have more instances of this happening.
