### ISSUE TITLE
[CWTS] Extra sync item appears selected at manual Sync Now on Desktop and Android

### ISSUE THREAD

**Issue by mirunacurtean** [mozilla-mobile/firefox-ios#6241]
**Build:**
iOS: Release 23.0 (17297) and Beta 23.1(17416)
Windows: 74.0 (64-bit)
Android: Fennec 38.5.0 and Fenix 3.2.1 

**Device information:**
iPhone X 13.2.2 and iPhone X 12.4
Windows PRO 10 64-bit
Android 8.0.0

**Preconditions:**
Create FF account where only only sync options is selected. 

**Steps to reproduce:**
1. Sign in with account on iOS and verify that only one sync options is selected (ex: Bookmarks). Perform a Sync Now on iOS to make sure the settings is saved. 
2. Sign in with the same account on Desktop and Android FF browsers. 
3. Navigate on each to sync settings page  (Desktop: about:preferences#sync ; Android three dots menu> Settings> Firefox Account).
4. After automatic sync  has been performed on windows and Android perform a manual sync as well. 

**Expected results:**
Only the sync setting saved on iOS is synced over to Desktop and Android after automatic or manual sync. 

**Actual results:**
Automatic sync should have transferred the sync settings which have been saved on iOS to Desktop and Android. 
On Desktop after automatic sync 'Bookmarks' option is selected but after performing the manual sync as well the 'History' option is also on without being selected on iOS. 
On Android, on Fennec, both 'Bookmarks' and 'History' are selected after automatic sync but after manual sync the History options is deselected. 
On Android on Fenix only the expected 'Bookmark' option is selected after both automatic and manual sync so it works as intended. 

**Notes:**
1. After performing an additional sync on iOS and the again on Desktop and Android the 'History' option is no longer selected, the change being reverted.
2. While bookmarks are indeed synced from iOS to Windows and Android (when checking the Bookmark section) history is not, so this appears to be an issue only at UI level. 
3. A sync error was received on when testing with Beta 23.1 on iOS when performing the manual sync on Desktop. "DEBUG: Error messegeIncomplete"

![Sync-mcurtean30](https://user-images.githubusercontent.com/53306802/76319544-0db32380-62e8-11ea-9f29-b7028b5fa9dc.gif)

![Extra option added at iOS to Desktop sync](https://user-images.githubusercontent.com/53306802/76319582-1ad01280-62e8-11ea-9e97-e316147a2776.gif)

![Sync error on iOS after 2nd SYNC now on Desktop gif](https://user-images.githubusercontent.com/53306802/76319079-57e7d500-62e7-11ea-9959-87b83a44d8bd.jpg)

**Comment by garvankeeley** [comment]
Is this a regression from v23.0 release?

**Comment by mirunacurtean** [comment]
No, this also occurs on Release 23.0 (17297) and that is why I did not add the [FxA upgrade] tag.

**Comment by garvankeeley** [comment]
Ok thanks! I'll remove the tag i added

**Comment by mirunacurtean** [comment]
Re-tested on iPhone x  13.3.1 with Beta 23.1(17416) and Windows Pro 10 64-bit with Ff 74.0 and Android 8.0.0 with Fenix 4.0.0/ Fennec 68.5.0 and this issue no longer occurs.

**Comment by athomasmoz** [comment]
Closing as not reproducible
