### ISSUE TITLE
Add Onboarding Event

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-ios#6242]
**Vision**

Count events during first run onboarding to understand how the cards are working & prep for future A/B testing of cards

**Acceptance Criteria**

* Event counts in place to understand how onboarding is performing ([approach](https://docs.google.com/document/d/1bGJz32iEeehpQZR2cPaO1xaUefjnWo1Lw46R6o0bhgg/edit#))
* Tracking is in line with our privacy policy
* Events go to both telemetry & Amplitude

**Notes**

* Since we are updating the onboarding cards, we should work with data science to determine what an appropriate naming scheme is. For example, should we call them "card 1" & "card 2"? Or "welcome card" and "sync card"?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2298)

**Comment by nbhasin2** [comment]
**Note:** This is not for release v25 but is required for Data science to further gather their information in further releases.

**Todo:** Basically we need to understand and do some investigation with Leanplum on how we can attach an **Experiment Identifier** to list of events or A-B test that tells us about the users those were part in those experiment through **temporary device identifier**.

**Experiment Identifier (EI):** This can be either a simple number we assign an experiment. Ex if we want to run an experiment for how many users sign in on onboarding screen we can assign that a simple number # (Ex 1234)

 **Temporary Device Identifier (TDI)**: TDI will be used to identify users those were part of the experiment

**Proposal / Investigation:**
a) Find out if we can add another property (Experiment Identifier) on the all / some events we send to Leanplum or any other platform ?
b) Find out what Temporary Device Identifier we can attach for running the experiment on Leanplum or any other platform.
c) If a) and b) is possible then can we funnel users those who participated in a specific Experiment

**Comment by lmarceau** [comment]
Since only `data-sync-user` has commented on the issue after the `Stalebot` GitHub action (which triggered the removal of the `stale` label) I’ll close this issue for now. Please let us know if you think this issue needs to be reopened, we'll gladly do so. Thank you!
