### ISSUE TITLE
[FxA Upgrade] Starting app offline, account incorrectly appears signed out

### ISSUE THREAD

**Issue by mirunacurtean** [mozilla-mobile/firefox-ios#6254]
**Build:**
Firefox Beta 23.1(17435) and 23.1 (17435)

**Affected platforms:**
iPhone X (13.3)

**Repro rate:**
3/10 

**Steps to reproduce:**
1. Sign in with account on iOS device. 
2. Close app. 
3. Turn WIFI/internet connection off. 
4. Restart FF app. 
5. View account state. 

**Expected results:** 
On Firefox Release 23.0(17297) the account state is preserved, the account still shows as signed in in hamburger menu and settings.  Same should apply to Beta 23.1(17435) when app is restarted while offline. 

Example in GIF
![Account-state-when-offline-release](https://user-images.githubusercontent.com/53306802/76437331-1546fb00-63c2-11ea-86bf-67b7ec7588ba.gif)

**Actual Results:**
Account does not show as signed in and instead the "Sign in with sync' button in Hamburger menu. 
In settings menu, under Firefox account the account name is empty. 

![Account-state-when-offline-Beta](https://user-images.githubusercontent.com/53306802/76437381-27c13480-63c2-11ea-96b1-39df3b16b11d.gif)

**Comment by garvankeeley** [comment]
fixed by e4a096148909235e61f2e055c6f3332a82c19fae

**Comment by csuciu** [comment]
Verified as fixed on Beta 23.1 (17476). The account state is preserved after staring the app with no internet connection.
