### ISSUE TITLE
[FxA Upgrade] iOS Beta to Fennec: Send Tab not supported

### ISSUE THREAD

**Issue by mirunacurtean** [mozilla-mobile/firefox-ios#6261]
**Build:**
Firefox Beta 23.1(17435)
Fennec 68.5.0

**Affected platforms:**
iPhone X (13.3)
Android 8.0.0

**Repro rate: 
3/5 accounts**
 
**Steps to reproduce:**

1.Create an account on iOS Beta 23.1(17435) with all CWTS synced.
2. Sign in with account on Android and verify that automatic sync is performed in Account settings ad that devices all listed in Devices&apps section from Manage account on both devices. 
3. **On iOS** open a random tab and after performing a Sync Now on both devices send tab to Android. 

**Expected results:**
When sending a tab from iOS **release version 23.0** to a synced Fennec account a notification containing the tab URL is received on the Android device and the user can choose what browser to open it with. 

Expected behavior
![Firefox release to Android fennec example](https://user-images.githubusercontent.com/53306802/76524862-7975c780-6473-11ea-9188-de109869307d.gif)

**Actual Results:**
Tab sent from iOS Beta to Fennec is not received. 

**Additional notes:**
1. Tested the following paths:
- iOS FF Beta menu>Open tab Three dots menu> Share page with> select Firefox Beta browser > Send to Device> Firefox
- iOS FF Beta menu>Open tab Three dots menu >Send to Device> Firefox 
- Safari> open tab> share icon select Firefox Beta browser> Send to Device> Firefox 
2. Did not receive tab on Android Fennec even after manually syncing both devices. 
3. Signed out and signed back in on both devices and tab is still not sent successfuly from iOS to Android fennec. 
4. **Used the same account to test behavior between Release iOS to Fennec and Beta iOS to Fennec.**

**Comment by abodea** [comment]
A long time ago I tested the send tab from Fenix and Fire TV and this is expected to not be received on Fennec.
Fennec use the old sent tab back-end where Fenix, Fire TV and I believe Firefox for iOS uses the new one, and they are not compatible with each other. 
Desktop uses both the new and old ones, which explain why it works with everybody.

**Comment by garvankeeley** [comment]
The Sync team says this is expected behaviour.
@athomasmoz This seems like a product decision as to whether we try and solve this so I'll gladly defer this hot potato over to you.

**Comment by athomasmoz** [comment]
Thanks both for confirming! I will close the bug as working as expected. I don't think there is a need to add this scope in given it works for desktop & Fenix.
