### ISSUE TITLE
FXIOS-290 ⁃ The sync button is barely seen after disabling the dark theme in hamburger menu

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/firefox-ios#6262]
## Steps to reproduce
1. Launch Firefox Beta and login with valid credentials.
2. Open the hamburger menu.
3. Tap on the Sync icon and then fast tap on the `Enable Night Mode`.
4. Close the Hamburger menu and wait for the sync to be completed.
5. Re-open the hamburger menu 
6. Disable the `night mode`.

### Expected behavior
The sync color button should be black(while the light theme is enabled).
### Actual behavior
The sync color button is white and it is barely seen.
### Device information

* Device: **iPhone 8 (12.2.3).**
* Fenix version: **Latest Beta 23.1(17435).**

![IMG-0178](https://user-images.githubusercontent.com/42831109/76539992-32470100-648a-11ea-9d8a-85fc84abcae7.gif)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2300)

**Comment by brampitoyo** [comment]
@abodea I can also confirm that this problem happens the other way around.

- If night mode goes from ON → OFF, the sync icon colour stays light
- If night mode goes from OFF → ON, the sync icon colour stays dark

In fact, the icon colour doesn’t adapt to the colour scheme, until you close and reopen the main menu.
