### ISSUE TITLE
The webpage is not opened in the correct browser when sending from Beta to RC

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/firefox-ios#6263]
## Prerequisites
Install the FF RC and FF Beta.
## Steps to reproduce
1. Launch FF Beta(latest).
2. Open any website
3. Tap on the 3 dot menu and share page with.
4. From the app, list select FF RC.
5. From the next screen tap open in Firefox.
### Expected behavior
The webpage should be opened in the FF RC.
### Actual behavior
The webpage is opened in FF beta(latest).
### Device information

* Device: **iPhone 8 (12.2.3).**
* Fenix version: **Latest Beta 23.1(17435).**

### Notes
When sending from FF RC to FF beta the website is correctly opened.
![IMG-0174](https://user-images.githubusercontent.com/42831109/76540644-14c66700-648b-11ea-8022-dd0014eb9d78.gif)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2301)

**Comment by lmarceau** [comment]
Since only `data-sync-user` has commented on the issue after the `Stalebot` GitHub action (which triggered the removal of the `stale` label) I’ll close this issue for now. Please let us know if you think this issue needs to be reopened, we'll gladly do so. Thank you!
