### ISSUE TITLE
There is no prompt/pop-up informing the user that the internet connection is OFF when trying to sync

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/firefox-ios#6267]
## Steps to reproduce
1. Launch Firefox and log in with valid credentials.
2. Access the hamburger menu where the sync button is displayed or the settings menu where the settings menu is displayed.
3. Tap on the sync button.
### Expected behavior
There should be a prompt/pop-up informing the user that the internet connection is OFF or very low and the sync cannot be completed.
### Actual behavior
Nothing happens, and the button doesn't have functionality. 
### Device information

* Device: **iPhone 8 (13.2.3)**
* Version: **Latest Beta 23.1(17435)**

### Notes
![VID-20200313-124938](https://user-images.githubusercontent.com/42831109/76622966-367f2700-653b-11ea-936b-fee36a68abf3.gif)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2303)

**Comment by brampitoyo** [comment]
@abodea In this case, it’s ok not to show any notification.

- When connection is offline, no webpage will load
- Users are much more likely to open webpages than performing manual sync action
- Therefore, it’s very likely that users will realise that their connection is offline _first_, before they perform manual sync

**Comment by data-sync-user** [comment]
➤ Tiffanie Shakespeare commented:

we no longer have a sync button in the menu.
