### ISSUE TITLE
The `The Internet connection appears to be offline` error text is not fully displayed

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/firefox-ios#6269]
## Steps to reproduce
1. Launch Firefox and access any page `www.youtube.com` for example.
2. Close Firefox and turn off the internet connection.
3. Re-launch Firefox.
4. Observe the `Internet connection` message error.
### Expected behavior
The `The Internet connection appears to be offline` error text should be fully displayed.
### Actual behavior
The `The Internet connection appears to be offline` error text should be fully displayed.
### Device information

* Device: **iPhone 8 (13.2.3)**
* Version: **Latest Beta 23.1(17435)**

![1584112351084](https://user-images.githubusercontent.com/42831109/76633801-fa08f680-654d-11ea-903d-1a5b9a2d4468.JPEG)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2304)

**Comment by lmarceau** [comment]
Since only `data-sync-user` has commented on the issue after the `Stalebot` GitHub action (which triggered the removal of the `stale` label) I’ll close this issue for now. Please let us know if you think this issue needs to be reopened, we'll gladly do so. Thank you!
