### ISSUE TITLE
App crash when changing text size

### ISSUE THREAD

**Issue by dnarcese** [mozilla-mobile/firefox-ios#6271]
STR
1. Open bookmarks panel
2. Go to iOS settings and change the text size
3. Go back to firefox

On Beta 23.1 (17416) the app crashes and the crash reporter dialog pops up.
On Release 23.0, the app _does not_ crash but the bookmark panel closes.

**Comment by vphong** [comment]
Xcode traces it back to this function, only when the app is reloaded. https://github.com/mozilla-mobile/firefox-ios/blob/512e03c0e9625269de5ed5ac4d9c3e58638b8dcf/Client/Frontend/Widgets/SiteTableViewController.swift#L192-L205
specifically line 201, https://github.com/mozilla-mobile/firefox-ios/blob/512e03c0e9625269de5ed5ac4d9c3e58638b8dcf/Client/Frontend/Widgets/SiteTableViewController.swift#L201

After investigating the `.DynamicFontChanged` notification in BookmarksPanel.swift, I think there's a dispatch queue issue in updating the UI. I believe the notification is being set when it should be from the Settings app, without issue, but when Firefox comes back into focus and TableView reapplies its theme, the app crashes.

**Comment by isabelrios** [comment]
@csuciu would you mind trying to reproduce this on v23, latest beta (v25) and master? 
Thank you in advance!

**Comment by SimonBasca** [comment]
This issue is still reproducible on master e7fec5797, on beta 25.0 (17678),  release 24.1 and also 23.0 on iPhone 8  (13.4.1) by following the STR: 

    Open bookmarks panel
    Go to iOS settings and change the text size
    Go back to firefox

[Client  4-15-20, 7-52 PM.crash.zip](https://github.com/mozilla-mobile/firefox-ios/files/4482643/Client.4-15-20.7-52.PM.crash.zip)

**Comment by SimonBasca** [comment]
Verifying as fix on main 89b961b. The crash no longer occurs.
