### ISSUE TITLE
web.whatsapp.com is not working on iPad anymore

### ISSUE THREAD

**Issue by canova** [mozilla-mobile/firefox-ios#6272]
When I navigate to web.whatsapp.com, I see a message that says “WhatsApp works with Safari 9+”. And it doesn’t let me get in the app. Previously it was working fine. Probably they are looking at the user agent and determine this. Is there a chance recently the user agent changed? When I checked the Chrome’s user agent I saw this: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_5) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.1.1 Safari/605.1.15` There is a `Version/X.Y.Z` part additionally. Adding a version (But keeping the FxiOS/23.0 at the same time) might solve the issue maybe? But not sure if that makes sense.

My user agent: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15) AppleWebKit/605.1.15 (KHTML, like Gecko) FxiOS/23.0 Safari/605.1.15`
Firefox version: Version 23.0 (17297)
iOS version: 13.3.1

**Comment by yusadogru** [comment]
Almost same issue #5838 

<img width="754" alt="Screen Shot 2020-03-17 at 15 57 11" src="https://user-images.githubusercontent.com/19792753/76858210-0059e400-6868-11ea-9372-59429985d06a.png">

**Comment by csuciu** [comment]
Verified as fixed on latest master and Beta v24.0(17528). web.whatsapp.com works correctly on iPads.
