### ISSUE TITLE
FXIOS-296 ⁃ [L10N][Bookmarks Panel] some strings are not translated

### ISSUE THREAD

**Issue by bli-mozbj** [mozilla-mobile/firefox-ios#6283]
Env:
---------------------
Firefox for iOS Beta 23.1(17476)
iPhone 6Plus  iOS 12.4.5  
Language: Simplified Chinese / Traditional Chinese / Japanese 

Steps to reproduce:
-----------------------
1. Open menu panel 
2. Go to "Your Library" -> Bookmarks
3. Choose a folder which is not empty
4. Swipe left to delete the folder
==> The string "Delete" is not translated.
5. Tap on "Delete" 
==> Strings in the pop up window are not translated.

![delete](https://user-images.githubusercontent.com/25242209/76937499-dec42f80-692f-11ea-8dcf-bdffe99fca4d.png)
![folder-not-empty](https://user-images.githubusercontent.com/25242209/76937538-edaae200-692f-11ea-9607-033a4c93fff1.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2305)

**Comment by dnarcese** [comment]
@SimonBasca can you check if this is still an issue?

**Comment by SimonBasca** [comment]
This issue is no longer reproducible on v9000 (6773). I verified on : Simplified Chinese / Traditional Chinese / Japanese.
