### ISSUE TITLE
Unable to share links in Documents app or open "rhttp://" links

### ISSUE THREAD

**Issue by tankmohit** [mozilla-mobile/firefox-ios#6290]
Hi, I am trying to download some media files using Firefox on my iPhone.
These files contain photos, mp3s and videos.
For the mp3 and video files Firefox starts streaming it instead of downloading it.
In safari there is a workaround to save any file using Documents app and to do that you need to change URL from "http(s)://" to "rhttp(s)://" and it will open the Documents app and starts downloading.

Link to the official documentation : https://helpspot.readdle.com/documents/index.php?pg=kb.page&id=1213

I have tested above method in other browsers such as Brave and Edge for iOS. And it works perfectly fine, while in Firefox, it is unable to resolve "rhttp://" URL handler to open in Documents.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2308)

**Comment by lmarceau** [comment]
Since only `data-sync-user` has commented on the issue after the `Stalebot` GitHub action (which triggered the removal of the `stale` label) I’ll close this issue for now. Please let us know if you think this issue needs to be reopened, we'll gladly do so. Thank you!
