### ISSUE TITLE
FXIOS-300 ⁃ Send a full desktop user agent string when asking for desktop mode

### ISSUE THREAD

**Issue by karlcow** [mozilla-mobile/firefox-ios#6291]
currently fxios 23 still sends the `FxiOS/23.0` keyword instead of the full desktop UA string when desktop mode is requested.
This creates issue for certain sites.

see https://github.com/webcompat/web-bugs/issues/49715

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2309)

**Comment by porsche613** [comment]
Thanks, it has been fixed preliminary in Fx 25.0: https://github.com/mozilla-mobile/firefox-ios/commit/5bd7a74ff896d4d641ba892611c886d89ede94ce
