### ISSUE TITLE
Logins&Passwords - Select all button is visible or cropped even if not active 

### ISSUE THREAD

**Issue by yusadogru** [mozilla-mobile/firefox-ios#6292]
<img width="514" alt="Screen Shot 2020-03-19 at 12 31 32" src="https://user-images.githubusercontent.com/19792753/77053851-007cef80-69e0-11ea-972d-48e9cf240c9e.png">
<img width="514" alt="Screen Shot 2020-03-19 at 12 46 33" src="https://user-images.githubusercontent.com/19792753/77053947-286c5300-69e0-11ea-80e7-20c2819eeec9.png">

**Comment by csuciu** [comment]
Verified as fixed on master 5ba3e95. "Select all" button is no longer visible.
