### ISSUE TITLE
Durable Sync + Firefox iOS < 20.x: Message Users to Upgrade

### ISSUE THREAD

**Issue by davismtl** [mozilla-mobile/firefox-ios#6294]
### Context
We found an issue last fall that caused Firefox for iOS to crash when pointed at the new Durable Sync service. The problem ([outlined in detail here](https://github.com/mozilla-services/syncstorage-rs/issues/293)) was [fixed here](https://github.com/mozilla-mobile/firefox-ios/pull/5620) and went live with the 20.0 release of Firefox-ios.

The issue was deemed critical at the time due to the fact that it not only caused Sync to fail, but also completely crashed Firefox. We decided to move forward with the release of Durable Sync for new users due to the fact that brand new Sync users are also significantly less likely to be on legacy Firefox-ios versions.

That brings us to today, as we look to migrate existing users. We estimate roughly 3.6% of Firefox iOS users **that Sync** are on versions prior to 20.0. [See chart here.](https://analytics.amplitude.com/mozilla-corp/chart/xksucgx) Though important enough on iOS, this represents a [very small amount of users](https://analytics.amplitude.com/mozilla-corp/chart/ed5fe2i) of overall Sync users (for context).

The approach now is to:

1. Confirm that this is actually still an issue. A lot has changed since we originally found this issue in the codebase; it’s worth confirming the problem before coordinating efforts to fix.

We have a [PI request on file](https://jira.mozilla.com/browse/PI-536) and have confirmed as of Mar 19 that we have a working build (that's < than v20). We’ve been told to expect results by March 20, EOD.

2. If we do in fact still see the previous crashes, we plan to move forward with the plan to [return an error code](https://github.com/mozilla-services/services-engineering/issues/11) from the sync service to prevent crashes. **We’ll need to also coordinate messaging for users here that they’ll need to upgrade their version of Firefox to continue to use sync.** This will prevent the browser from crashing but obviously is also not ideal. We investigated other options here and this was deemed to be preferable.

### Request

Start messaging Firefox iOS users that are on versions <20 to upgrade. Hopefully, this can be done with Leanplum or else I suspect we might not have any options. I also suppose that this might also depend on when Leanplum was integrated. 

You can see the break down of the [ua_versions being used below v20 here](https://analytics.amplitude.com/mozilla-corp/chart/y4997xo). You'll notice that [about half of users on a version <20 are on version 14.](https://analytics.amplitude.com/mozilla-corp/chart/y4997xo)

### FAQ

**When is the migration to durable sync planned for existing users?**
Starting mid-April

**How long will the migration take?**
Anywhere between 2.5-5 months. (best vs worst case)

**Why are we starting in April?**
A few reasons:
- It's the next step in our migration. All new Sync registrations will already be landing on the new durable storage. (and everything is going well)
- We were initially hoping to beat the summer slump that causes some amount of users to lose data more than during the rest of the year. This may no longer be applicable since schools are already closing. But then again, it's still unclear how the Corona virus will impact things so the sooner is likely still the better.
- The sooner we upgrade, the sooner we provide a more reliable sync experience to all of our users.

**Comment by tublitzed** [comment]
@davismtl for the record here, we just got confirmation this AM [that this is still an issue](https://jira.mozilla.com/browse/PI-536).

**Comment by tublitzed** [comment]
@athomasmoz - this has been tested, and confirmed that it will crash firefox for users on affected versions (before 20.0).

**Comment by brampitoyo** [comment]
Is there a user-facing messaging component to this issue? What might our notification look like? Is there prior art that we can reuse for this particular scenario?

**Comment by davismtl** [comment]
There have been discussions and it has been decided that there will not be any messaging.

It has brought to light that we may want to create new messaging capabilities for the future where we can inform users that they need to upgrade to the latest Firefox. To my knowledge, an issue has not been opened for that.

**Comment by brampitoyo** [comment]
@davismtl Thanks! Yes. Let’s open a new issue specifically for upgrading to the latest version.
