### ISSUE TITLE
The home icon on a new tab is barely visible in PB with dark mode enabled

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/firefox-ios#6304]
### Prerequisites
The dark them should be turned ON.

## Steps to reproduce
1. Launch Firefox.
2. Open a new tab in PB.
3. Observe the `home` icon.
### Expected behavior
The globe icon should be more visible on PB with dark theme on.
### Device & build information
* Device: **iPhone X (13.3.1**
* Build version: **Beta 24.0 (17528).**
### Notes
Attachments: 

![Screenshot 2020-03-24 at 17 03 04](https://user-images.githubusercontent.com/42831109/77441378-0d3f8000-6df2-11ea-8de9-8559f2ed2fa7.png)

**Comment by brampitoyo** [comment]
@abodea Is it possible to vary the icon depending on colour scheme?

For instance:

- If theme = `light`, default icon fill should be `#20123a`
- If theme = `dark`, default icon fill should be `#f9f9fa`
- If theme = `private`… etc. etc.

**Comment by abodea** [comment]
Hello, @brampitoyo the `#20123a` is for both themes dark and light so I think this also applies for the private browsing.
 The color is not changed to  `#f9f9fa` when the dark theme is selected.

**Comment by brampitoyo** [comment]
@abodea I wonder whether we can change the colour of the icon, depending on the browser theme? If yes, then we can solve this problem easily.

When the theme is light, make the icon fill dark. If the theme is dark or private, make the icon fill light.

**Comment by nishant2718** [comment]
I've looked into this issue a bit ~

For iOS 13, tint color changes via code have become a painpoint. We can try different image assets for light/dark mode. For example, see the screenshots below (consider that icon a temp for demo purposes):

<img width="460" alt="image" src="https://user-images.githubusercontent.com/36939381/77855107-6295db80-71bc-11ea-8f0e-57ecc9318344.png">

And this is a simple update for the asset catalog as well:

<img width="426" alt="image" src="https://user-images.githubusercontent.com/36939381/77855209-f7003e00-71bc-11ea-8ff7-38b1e2b8c3e7.png">


If provided "dark mode" assets, this is a simple fix.

**Comment by brampitoyo** [comment]
@nishant2718 @abodea Ok. Here are the dark theme assets:

![website-dark](https://user-images.githubusercontent.com/51007/77864579-ea93e800-7285-11ea-8ad7-38ced31aab2e.png)
![website-dark@2x](https://user-images.githubusercontent.com/51007/77864580-eb2c7e80-7285-11ea-9d16-4e36b79ca477.png)
![website-dark@3x](https://user-images.githubusercontent.com/51007/77864581-ebc51500-7285-11ea-8fe6-262fedf068ef.png)

To be extra sure that the icon matches between light and dark themes, please check and replace our light themes assets with the ones below, if necessary:

![website](https://user-images.githubusercontent.com/51007/77864634-3c3c7280-7286-11ea-9024-01dc870c67fb.png)
![website@2x](https://user-images.githubusercontent.com/51007/77864636-3d6d9f80-7286-11ea-8d88-b1ff9a6aba1c.png)
![website@3x](https://user-images.githubusercontent.com/51007/77864637-3d6d9f80-7286-11ea-81c3-925050f5628b.png)

**Comment by nishant2718** [comment]
Thanks for providing those assets @brampitoyo! 

@abodea  While doing a quick smoke test, I noticed that `Dark Mode` isn't consistently respected on iPad prior to this default favicon ticket. For example, with dark mode enabled, notice the tab background, history panel, and home background:
<img width="865" alt="image" src="https://user-images.githubusercontent.com/36939381/77915040-cecc1a00-7264-11ea-9038-3363ee693533.png">
 
This causes the favicon to blend in with the white tab background on iPads only on `Dark Mode`:
<img width="847" alt="image" src="https://user-images.githubusercontent.com/36939381/77915260-2a96a300-7265-11ea-9deb-38ec504a524c.png">

Would you like a fix for that in a separate ticket?

**Comment by nbhasin2** [comment]
@nishant2718 
Issue regarding favicon blends with white tab will happen for both iPad and iPhone hence my suggestion would be to fix it in this issue as this aligns with the title of home icon not visible for dark theme. (See the home icon below in screenshot) 

**Why this happens:**
It happens because the icons are white (as the iOS system theme is dark) but when the user manually overrides the theme to white you'll need account for that. 
**How to fix it:**
This will require you to update code where fevicon is set to make sure we account for that manual override. Ping us on Riot if you need any more information and I'll keep an eye for it 😊
**Testing:**
Our team might not have all devices so lets test on both iPhone + iPad simulators before putting out for ready for QA. 

<img width="400" alt="image" src="https://user-images.githubusercontent.com/8919439/77991128-0e404800-72f1-11ea-8059-b22adfca2c36.png">

**Comment by csuciu** [comment]
Verifying as fixed on master 340e7b5.
