### ISSUE TITLE
"Firefox Accounts" text is not displayed on the accounts settings in portrait mode

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/firefox-ios#6307]
## Steps to reproduce
1. Launch Firefox and login with valid credentials.
2. Access `Manage account & Devices`.
3. Observe the icon from the top.
### Expected behavior
The `Firefox Accounts` text should be displayed.
### Actual behavior
"Firefox Accounts" text is not displayed on the accounts settings in portrait mode
### Device & build information
* Device: **iPhone X (13.3.1)**
Build version: **Beta 24.0 (17528).**
### Notes
Attachments: 
![IMG-0202](https://user-images.githubusercontent.com/42831109/77560358-0aae5a80-6ec6-11ea-99e2-b150e629072c.gif)

**Comment by dnarcese** [comment]
Dupe #5596. Closing as wont fix!
