### ISSUE TITLE
The keyboard is not minimized after saving the display name

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/firefox-ios#6309]
## Steps to reproduce
1. Launch FF and login with valid credentials.
2. Access `Manage Account & Devices`.
3. Set the display name.
4. Observe the keyboard.
### Expected behavior
The keyboard should be minimized after the displayed name was successfully changed.
### Actual behavior
The keyboard is not minimized after saving the display name.
### Device & build information
* Device: **iPhone X (13.3.1)**
* Build version: **Beta 24.0 (17528).**
### Notes
Note that because of the keyboard still being displayed the notification regarding the recent save is not displayed(being at the top).
The notification from the top can be displayed only by manual scrolling.
Attachments: 
![FullSizeRender](https://user-images.githubusercontent.com/42831109/77563848-7d213980-6eca-11ea-98b4-be8911e65144.gif)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2314)

**Comment by RemakingEden** [comment]
Reproduced on:
* iPhone 8
* iOS 13.3.1
* Firefox 24.0 (17560)

**Comment by LamourBt** [comment]
I will look at this bug.

**Comment by LamourBt** [comment]
Sorry that it took long, I was trying to fix another PR that was reverted.

**Comment by lmarceau** [comment]
Since only `data-sync-user` has commented on the issue after the `Stalebot` GitHub action (which triggered the removal of the `stale` label) I’ll close this issue for now. Please let us know if you think this issue needs to be reopened, we'll gladly do so. Thank you!
