### ISSUE TITLE
FxAccount info is not displayed in Settings if that menu is open quickly

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/firefox-ios#6311]
## Steps to reproduce
Login using a valid account. 
After the successful login on Homescreen go to Browser tab menu -> Settings. This has to be done quickly
### Expected behavior
The account is shown in  settings
### Actual behavior
Please see screenshot attached
![Screenshot 2020-03-25 at 19 22 31](https://user-images.githubusercontent.com/1897507/77591307-f41cf900-6eef-11ea-86b7-dce5df635304.png)

### Device & build information
* Device: iPhone 11, 13.3
* Build version: master 5ba3e95

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2315)

**Comment by isabelrios** [comment]
This can be reproduced manually and when running the automated tests.

**Comment by isabelrios** [comment]
This issue is preventing sync integration tests to pass. Although is affecting only the tests that starts signing in on Mobile. There is no way to recover from the state in the screenshot. No matter if you wait, change screen...while running automated tests, there is no workaround for this.

Manually if you see the issue, so far I have been able to go to correct state waiting or changing screen and going back to Settings view but I'm worried we are always hitting this while running tests, it may be a timing issue, something with stage server... but it could also be a particular scenario we are reaching there....

**Comment by isabelrios** [comment]
There was a separate issue, looking similar, affecting the sync int tests, but that has been closed. 
This issue is then less critical, since you are not stuck on that screen if you get by any change. After a few seconds or chanign to another screen, the account is properly shown.

**Comment by lmarceau** [comment]
Since only `data-sync-user` has commented on the issue after the `Stalebot` GitHub action (which triggered the removal of the `stale` label) I’ll close this issue for now. Please let us know if you think this issue needs to be reopened, we'll gladly do so. Thank you!
