### ISSUE TITLE
FXIOS-311 ⁃ Videos from arte.tv do not play in fullscreen

### ISSUE THREAD

**Issue by foss-** [mozilla-mobile/firefox-ios#6323]
## Steps to reproduce

1. Open any video on arte.tv e.g. https://www.arte.tv/de/videos/076622-000-A/joan-miro-farben-feuer-freiheit/
2. once the video is playing there is an icon to switch to fullscreen on the bottom right, press that icon

### Expected behavior

Video should switch to fullscreen

### Actual behavior

Video continues to play in "normal" mode

### Device & build information
* Device: iOS 13.4, iPhone XR
* Build version: Firefox 24

Not sure if this has ever worked. Fullscreen button works when used on Safari on iOS 13.4 so not a general problem with the website or video.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-311)

**Comment by RemakingEden** [comment]
Reproduced on:
* iPhone 8
* iOS 13.3.1
* Firefox 24.00 (17560)

Also tested Safari and Chrome, the full screen is working correctly on these two browsers.

**Comment by foss-** [comment]
Persisting with iOS Firefox v25. Tested further and observed that fullscreen on arte tv works as expected, when opened on an iPad on iOS 12.4.6. Was wondering if this was a problem introduced with and limited to iOS 13.

**Comment by MarcelNehring** [comment]
The same problem exists on other sites like tagesschau.de.

Firefox 29.1 (3022)
iPadOS 14.2

**Comment by foss-** [comment]
Interestingly with iOS 14.2 videos on tagesschau.de work on an iPhone in fullscreen.

**Comment by MarcelNehring** [comment]
On iPadOS none of the controls work. Neither switching to fullscreen, nor mute, play/pause or settings.

**Comment by foss-** [comment]
iOS 14.4.1
Firefox 33.0 (4119)

Not sure if this got fixed on arte side (by fixing the player they are using) or by Mozilla. Anyhow, another bug gone - closing.

**Comment by sgoger** [comment]
@foss- this has been fixed on ARTE side on the 23/03
