### ISSUE TITLE
Website fails to load in Firefox iOS - Mobile site, but works in Firefox Focus iOS/Safari

### ISSUE THREAD

**Issue by csuciu** [mozilla-mobile/firefox-ios#6327]
Steps to reproduce:
1. Go to https://www.partnersfcu.org/
2. Type in anything in the username field (ex: "test")
3. Click the "LOGIN" button

Actual results:

https://partnersonlinebanking.partnersfcu.org/OnlineBanking/AOP/Password.aspx fails to load with the attached error:
error on line 79 at column 271: xmlParseEntityRef: no name

Expected results:

Page should have loaded without any errors as it does with Firefox Focus for iOS and Firefox for iPad (or other browsers tested including Chrome for iOS, Brave for iOS).

NOTE: I believe this may be related to the User Agent String that Firefox in iOS is using. See the following StackOverflow post: https://stackoverflow.com/questions/60609174/user-agent-ios-iphone-in-firefox Interestingly, Firefox uses "'CPU OS" while Firefox Focus uses "'CPU iPhone OS" as described in the post.

![IMG_0753](https://user-images.githubusercontent.com/1866605/77907486-6136e280-7292-11ea-9f37-23e67c2475bb.jpg)

Originally reported here: https://bugzilla.mozilla.org/show_bug.cgi?id=1625581

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2320)

**Comment by RemakingEden** [comment]
Reproduced this on:
* iPhone 8
* iOS 13.3.1

I have tried to look into the user agent string however I cannot see that this is causing the issue (May be I am not looking correctly though). I have recreated my exact user Firefox iOS agent string on my laptop with an user agent switcher. This still works correctly on both Chrome and Firefox.

**Comment by lmarceau** [comment]
@csuciu This seems fine on latest main 7bf455c419d93d73e76fa1cf268c8c67eca743e6. Can this be retested?

**Comment by csuciu** [comment]
No longer reproducible on latest main. Closing.
