### ISSUE TITLE
Add app suite dashboard to hamburger menu

### ISSUE THREAD

**Issue by OddHouseGames** [mozilla-mobile/firefox-ios#6333]
Mozilla/Firefox has a robust and powerful suite of tools/apps which many users are unaware of. Adding access to these items (as seen in desktop Firefox menu) is a great way to remind users of available tools and leverage full suite of Mozilla products.

**Proposed Process**

- Add app dashboard menu item and icon (as seen on Firefox Monitor website) to hamburger menu, taking you to menu page with access to full suite of available tools

- Firefox Monitor
- Firefox Send
- Firefox Lockwise
- Pocket

**Benefits:**
- Take the onus off of the user to remember where and how to access unique range of products 
- Fully leverage the power of the Firefox family and increase adoption of available tools 
- Increase parity with Desktop Firefox

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2321)

**Comment by lmarceau** [comment]
Since only `data-sync-user` has commented on the issue after the `Stalebot` GitHub action (which triggered the removal of the `stale` label) I’ll close this issue for now. Please let us know if you think this issue needs to be reopened, we'll gladly do so. Thank you!
