### ISSUE TITLE
FXIOS-320 ⁃ [a11y] No indication of selected tab in tabs list with VoiceOver

### ISSUE THREAD

**Issue by jcsteh** [mozilla-mobile/firefox-ios#6343]
STR:

1. Open at least 2 tabs.
1. Turn on VoiceOver.
1. Tap the Tabs button, then double tap to activate.
1. Swipe right through the elements.
  * Expected: VoiceOver should say "selected" before the selected tab.
  * Actual: It doesn't. There is no indication of which tab is selected.

Note: We will need to land strings for translation here too

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-320)

**Comment by jcsteh** [comment]
P1 for accessibility because this is information that is not exposed to VoiceOver users, but is readily available to other users.

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verified fix on v33.0 (4119)
