### ISSUE TITLE
Error when setting a custom FxA server URL

### ISSUE THREAD

**Issue by rfk** [mozilla-mobile/firefox-ios#6347]
## Steps to reproduce

* Build from latest master and launch in the simulator (I am on `b813a4` and executed the "Fennec" project on "iPhone 11")
* Go into settings and click the version number five times to access the secret developer menu
* Go to "Advanced Sync Settings"
* Enter a value for the custom accounts server (e.g. https://accounts.stage.mozaws.net)
* Toggle the "Use custom Autoconfig" option to true

### Expected behavior

* Firefox for iOS fetches and uses the autoconfig bundle from the configured server.

### Actual behavior

* I get a breakpoint with message: `Thread 23: Exception: "Modifications to the layout engine must not be performed from a background thread after it has been accessed from the main thread."`
* The backtrace blames [this line](https://github.com/mozilla-mobile/firefox-ios/blob/b813a4c9bb3c49ea696c5098a6ad942ea4944ecf/Client/Frontend/Settings/AdvancedAccountSettingViewController.swift#L72) where it tries to remove any existing account.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2327)

**Comment by rfk** [comment]
(Even if I had succeeded in setting this config option, it's not clear to me whether it would have actually worked with the new RustFxA stuff anyway, given the way that object is initialized).

**Comment by lmarceau** [comment]
Since only `data-sync-user` has commented on the issue after the `Stalebot` GitHub action (which triggered the removal of the `stale` label) I’ll close this issue for now. Please let us know if you think this issue needs to be reopened, we'll gladly do so. Thank you!
