### ISSUE TITLE
Local sync data choices are re-uploaded on every sync, potentially overwriting more recent choices made elsewhere

### ISSUE THREAD

**Issue by rfk** [mozilla-mobile/firefox-ios#6350]
## Steps to reproduce

* Connect Firefox for iOS and a Desktop browser to the same account. Start with the account configured to sync all datatypes by default.
* On the iOS device, go into account settings and disable bookmarks syncing. Force a sync to ensure it gets written to the server.
* On the desktop device, go into sync settings, force a sync, and observe that it detects that bookmark syncing is disabled.
* On the desktop device, re-enable bookmark syncing and force a sync.
* On the Firefox for iOS device, force a sync.

### Expected behavior

* The Firefox for iOS device detects that bookmark syncing has been re-enabled.

### Actual behavior

* The Firefox for iOS device disables bookmark syncing and writes that change back to the account, disabling it for all devices.

I also saw similar behaviour for engines that get explicitly enabled on Firefox for iOS. For example, if I start out with logins sync disabled, then go into Firefox for iOS prefs and enable it, then Firefox for iOS will re-apply that enablement on each subsequent sync, overwriting any attempts to turn off logins sync from other devices.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2328)

**Comment by rfk** [comment]
I added a bit of logging to help diagnose the issue here, and this conditional in the `HasMetaGlobal` state appears to get triggered on every sync:

* https://github.com/mozilla-mobile/firefox-ios/blob/master/Sync/SyncStateMachine.swift#L843-L851


Basically, if Firefox for iOS needs to apply a change to the set of enabled engines, then it appears to apply that change and upload a new metglobal record on every subsequent sync. I expect that this line is supposed to clear that "I have pending changes to enabled engines" state after applying it once:

* https://github.com/mozilla-mobile/firefox-ios/blob/b813a4c9bb3c49ea696c5098a6ad942ea4944ecf/Sync/SyncStateMachine.swift#L848

But perhaps that is somehow not being persisted correctly?

**Comment by rfk** [comment]
From slack conversation: there are a couple of places where we set the `enginesEnablements` field on the `syncAuthState` in order to pass data from prefs into the sync state machine, but it's not obvious where this field gets set back to `nil` after the changes are successfully applied. Maybe it's being persisted as a field on the `syncAuthState` and re-applied on every sync?

**Comment by lmarceau** [comment]
Since only `data-sync-user` has commented on the issue after the `Stalebot` GitHub action (which triggered the removal of the `stale` label) I’ll close this issue for now. Please let us know if you think this issue needs to be reopened, we'll gladly do so. Thank you!
