### ISSUE TITLE
[FxA Upgrade] Sent tab from Firefox Android (not Fenix): no push notification

### ISSUE THREAD

**Issue by garvankeeley** [mozilla-mobile/firefox-ios#6351]
This is expected behaviour, Firefox Android does not support pushing sent tab notifications to iOS with the new rust app-services FxA. Send tabs will be received when Firefox iOS performs a sync in foreground.

Also, Firefox Android doesn't reflect the correct device name for iOS. I will verify this is expected.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2329)

**Comment by garvankeeley** [comment]
This is a wont-fix AFAIK, as the bug is on the Android side and no fix is planned for this issue.

**Comment by athomasmoz** [comment]
From the user's perspective, this means that they will not be notified a tab has been received from Fennec when they are not in the Firefox app. The next time they open the app, the tab will be shown. This bug won't be fixed for release, I've marked it a lower priority for 2 reasons:
* The main use case is sending between a single user's different devices, which is more likely to be desktop or iPad
* The user will still receive their tab when the app is opened

**Comment by lmarceau** [comment]
Since only `data-sync-user` has commented on the issue after the `Stalebot` GitHub action (which triggered the removal of the `stale` label) I’ll close this issue for now. Please let us know if you think this issue needs to be reopened, we'll gladly do so. Thank you!
