### ISSUE TITLE
FXIOS-327 ⁃ Text visibility issues in Settings page when forcing Light theme

### ISSUE THREAD

**Issue by csuciu** [mozilla-mobile/firefox-ios#6352]
master 8350f11e3d
iPhone 11 Pro 13.3

1. Enable iOS Dark theme.
2. Enable Light theme in Firefox settings. 
3. in Firefox settings, check the Theme, Search and Data Management pages.

Results: In this pages, only the sections titles are visible.

<img width="1360" alt="Screenshot 2020-04-01 at 15 36 05" src="https://user-images.githubusercontent.com/1866605/78240768-1f9f7500-74e8-11ea-8c7c-5db960107321.png">

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2330)

**Comment by dnarcese** [comment]
@csuciu does the text reappear when you re-open this page? Or restart the app? Or is the only way to fix it to change the theme back.

**Comment by csuciu** [comment]
@dnarcese the only way to fix it is to change the theme back. Restarting the app doesn't change anything.

**Comment by ciccioska** [comment]
A problem on this is also available if you set the App to use the system theme. In this transition, with the App opened and in the background, the colour of the menu is not correct.
![IMG_4388](https://user-images.githubusercontent.com/7107130/82086763-4a880600-96ef-11ea-8df7-894b2e386db9.jpeg)

**Comment by tomislaveric** [comment]
I could reproduce the issue, i've created a PR with a one liner fix! https://github.com/mozilla-mobile/firefox-ios/pull/6678 
enjoy!
