### ISSUE TITLE
FXIOS-328 ⁃ Long email or display name breaks the FxA management page

### ISSUE THREAD

**Issue by csuciu** [mozilla-mobile/firefox-ios#6353]
master 8350f11
iPhone 11 Pro 13.3

1.  Create an account using a long email or add a long display name to an existing one.
2. Check the FxA management page.

Result: The page expands outside the viewport and can't be zoomed out. Also the left side of the page becomes truncated.
![Screen Shot 2020-04-02 at 14 39 48](https://user-images.githubusercontent.com/1866605/78245678-8e80cc00-74f0-11ea-8a74-9fc6fcd3a251.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2331)

**Comment by garvankeeley** [comment]
Filed to FxA https://github.com/mozilla/fxa/issues/4775

**Comment by lmarceau** [comment]
Page UI isn't the same anymore and ticket was closed on FXA side
![Simulator Screen Shot - iPhone 11 - 2022-01-11 at 18 06 13](https://user-images.githubusercontent.com/11338480/149035512-ca6692c1-5643-4f76-a222-455ca3f11e38.png)
