### ISSUE TITLE
UI issues on the Tracking Protection settings page when switching orientation

### ISSUE THREAD

**Issue by csuciu** [mozilla-mobile/firefox-ios#6354]
master 8350f11
iPhone 11 Pro 13.3

Note: Follow up to #6146

Case 1:
1. While in portrait mode, open the Tracking Protection settings page.
2. Switch to landscape.

Result: The checkmark overlaps the label.
![Screen Shot 2020-04-02 at 15 34 38](https://user-images.githubusercontent.com/1866605/78249835-a7d94680-74f7-11ea-9b42-543dd6f81b95.png)

Case 2:
1. While in landscape mode, open the Tracking Protection settings page.
2. Switch to portrait.

Result: Incorrect text indentation.
![Screen Shot 2020-04-02 at 15 42 55](https://user-images.githubusercontent.com/1866605/78250628-c8ee6700-74f8-11ea-9d60-ba2bfd67de35.png)

**Comment by yusadogru** [comment]
Actually this issue fixed on version 25.x 
#6146 

<img width="712" alt="Screen Shot 2020-04-02 at 16 06 03" src="https://user-images.githubusercontent.com/19792753/78252767-09031900-74fc-11ea-9e50-e707081bd7e2.png">

**Comment by csuciu** [comment]
Hey @yusadogru, this was tested on the latest master build, which has your commit. Not sure what's going on but I can reproduce the issues mentioned above.

**Comment by csuciu** [comment]
This is not reproducible on latest Beta/master. Closing as wfm.
