### ISSUE TITLE
Sync notification error

### ISSUE THREAD

**Issue by cainy-a** [mozilla-mobile/firefox-ios#6357]
## Steps to reproduce
?
### Expected behavior
Notification related to Firefox sync 
### Actual behavior
Broken notification 
### Device & build information
* Device: iPod Touch 6
* Build version: 17361
### Notes
Attachments: 
![99EAAC4A-9020-4A2C-BD8F-EDA59721AA28](https://user-images.githubusercontent.com/19270622/78266014-1c62b400-74fd-11ea-9295-cd2c2dd1ac92.jpeg)

**Comment by garvankeeley** [comment]
Thanks for using the beta! This should be fixed in the later releases.
