### ISSUE TITLE
Password Management Events

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-ios#6368]
#### Description & Product Manager / Data Scientist User Story
- As a product owner, I want to know how users interact with features related to logins and what features they find most useful.

#### What questions will you answer with this data?
- How often users let their browser save their logins?
- How often do users manage their saved logins?
- What login management features are used most frequently?
- What login management features are not used often (so we can determine whether we need to remove or enhance them)

#### What probes (suggested, if applicable)
- [ ] choose whether Firefox will remember logins
- [ ] sync logins
- [ ] view Logins in settings
- [ ] open an individual login
- [ ] copy a login
- [ ] view a password
- [ ] User says yes/no to saving a login on a site

### Acceptance Criteria
- Event pings can be queried via re:dash or in Amplitude
- We are sending telemetry events for the actions listed in the requirements
- We have documented the telemetry
- We have asked a data steward to [review](https://github.com/mozilla/data-review/blob/master/request.md) the telemetry

### Notes

* Fenix ticket for reference: https://github.com/mozilla-mobile/fenix/issues/5586
* Data science ticket: https://jira.mozilla.com/browse/DO-190

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2333)

**Comment by lmarceau** [comment]
Since only `data-sync-user` has commented on the issue after the `Stalebot` GitHub action (which triggered the removal of the `stale` label) I’ll close this issue for now. Please let us know if you think this issue needs to be reopened, we'll gladly do so. Thank you!
