### ISSUE TITLE
if legal to develop personal app based on Firefox and released it on App store

### ISSUE THREAD

**Issue by junpengqiu** [mozilla-mobile/firefox-ios#6372]
Recently, I am doing a side project which is building an IOS app based on the src code of Firefox-ios. Is that legal? 
As far as I understand, Firefox (both app and src code) is free and open to use and develop even for commercial purpose, right? 
Thanks!

**Comment by aaskrv** [comment]
I recommend you to review the [MPL 2.0](https://github.com/mozilla-mobile/firefox-ios/blob/master/LICENSE). As long as I understood, it does permit you to use its source code for personal use but with some restrictions: you must provide the source code for your app (make it open-source) and release it under the same MPL license. Please correct me if I'm wrong.
