### ISSUE TITLE
[UI Tests] Tests fail to compile and the test suite fails

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/firefox-ios#6376]
## Steps to reproduce
Launch any of the [UI Tests](https://github.com/mozilla-mobile/firefox-ios/tree/master/UITests)
### Expected behavior
Tests start running and pass
### Actual behavior
Test suite does not compile and so the test execution is stopped.

This is the error: `[Client] Assertion failed: Shouldn't attempt to migrate bookmarks after opening Rust places.db: file Storage/Rust/RustPlaces.swift, line 126`
And so this is the [line](https://github.com/mozilla-mobile/firefox-ios/blob/master/Storage/Rust/RustPlaces.swift#L126) causing problems

If that line is commented, then tests work as before. @garvankeeley does this make sense to you? Any idea how to  fix/workaround this?
Full BB logs [here](https://dashboard.buddybuild.com/apps/57bf25c0f096bc01001e21e0/build/5e892d906d712b0001e96b1f#logs)
Thanks!

**Comment by garvankeeley** [comment]
I think I am going to remove the migration code, it is old, and with no tests for it, I am skeptical it still works as expected with the new Rust FxA system in place.
