### ISSUE TITLE
Consider adding `RustBookmarksTests` to match the existing `RustLoginsTests`

### ISSUE THREAD

**Issue by rfk** [mozilla-mobile/firefox-ios#6384]
Over in https://github.com/mozilla/application-services/issues/2720 we've done some work to make it easier to run the firefox-ios unittests against a locally-modified version of application-services. The idea is that this can help give us earlier warning of potential downstream bustage before we actually cut a release.

To test it out I made a couple of deliberately-broken forks of application-services, then ran the firefox-ios test suite to see whether it would detect the problem.

When I deliberately broke the logins component, this caused the firefox-ios test suite to fail thanks to the basic logins-storage smoketests in [RustLoginsTest.swift](https://github.com/mozilla-mobile/firefox-ios/blob/master/StorageTests/RustLoginsTests.swift). But when I deliberately broke the places component in a similar way, it was not detected.

Obviously it's not the job of the firefox-ios test suite to ensure that application-services code is working as expected, and I would not expect to see an elaborate bookmarks test suite in this repo. But would you consider adding a small set of "can we load a bookmarks db and read/write it" tests for bookmarks in the same style as you current have for logins, as an additional defense against integration problems?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2338)

**Comment by lmarceau** [comment]
Since only `data-sync-user` has commented on the issue after the `Stalebot` GitHub action (which triggered the removal of the `stale` label) I’ll close this issue for now. Please let us know if you think this issue needs to be reopened, we'll gladly do so. Thank you!
