### ISSUE TITLE
Module compiled with Swift 5.1.3 cannot be imported by the Swift 5.2 compiler

### ISSUE THREAD

**Issue by aaskrv** [mozilla-mobile/firefox-ios#6385]
I have just pulled updates from master, but faced a problem with building the project. Has anyone encountered this?

### Steps to reproduce
Build the project

### Expected behavior
Successful build

### Actual behavior
Build Failed with error message saying:

> Module compiled with Swift 5.1.3 cannot be imported by the Swift 5.2 compiler

### Device & build information
* Device: Xcode - version 11.4 (11E146)
Simulator: iPhone 11 Pro (13.4)

### Attachments
<img width="1149" alt="image" src="https://user-images.githubusercontent.com/16909370/78657317-6a572d80-78ea-11ea-8936-73ffeab121bf.png">

**Comment by aaskrv** [comment]
One possible solution that I found:
https://stackoverflow.com/questions/58654714/module-compiled-with-swift-5-1-cannot-be-imported-by-the-swift-5-1-2-compiler
As it suggests the solution might be to set BUILD_LIBRARY_FOR_DISTRIBUTION to YES.

**Comment by garvankeeley** [comment]
What is your output of bootstrap.sh? It looks like that setup script failed in your case.

**Comment by garvankeeley** [comment]
Feel free to re-open if your problem isn't fixed by bootstrap

**Comment by aaskrv** [comment]
@garvankeeley thanks for the help, problem was with the setup script
