### ISSUE TITLE
issues encountered trying to build firefox-ios webxr

### ISSUE THREAD

**Issue by machenmusik** [mozilla-mobile/firefox-ios#6396]
## Steps to reproduce

Starting with a new Mac, 
with only Xcode, node/npm installed, 
switching to webxr branch,
and following the build instructions,
issues encountered trying to build firefox-ios webxr...

unmentioned but required tools
- gyp https://github.com/mogemimi/pomdog/wiki/How-to-Install-GYP
- ninja https://github.com/ninja-build/ninja/releases
- -cargo-
- rust (which should install cargo) https://doc.rust-lang.org/book/ch01-01-installation.html
- `~/.cargo/bin/rustup target add x86_64-apple-ios`
- `~/.cargo/bin/rustup target add aarch64-apple-ios`
- protoc http://google.github.io/proto-lens/installing-protoc.html
- protoc-gen-swift https://github.com/apple/swift-protobuf/blob/master/Documentation/PLUGIN.md

too-new versions requiring Cartfile changes
- `github "Leanplum/Leanplum-iOS-SDK"     == 2.6.4`

required buildfile corrections
- Storage: MozillaAppServices.framework is in Carthage/Build/iOS/Static

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2339)

**Comment by blairmacintyre** [comment]
Note:  this branch only builds with XCode 11.3.1 or earlier.   Newer versions will fail because of conflicts with various dependencies.  

Solution:  merge the latest changes from `master` into `webxr`

**Comment by lmarceau** [comment]
Since only `data-sync-user` has commented on the issue after the `Stalebot` GitHub action (which triggered the removal of the `stale` label) I’ll close this issue for now. Please let us know if you think this issue needs to be reopened, we'll gladly do so. Thank you!
