### ISSUE TITLE
Replace optional search engine Yandex Market for Ukraine

### ISSUE THREAD

**Issue by csuciu** [mozilla-mobile/firefox-ios#6397]
Since the Yandex services are officially banned in Ukraine and it's not possible to use it directly without bypassing via VPN, please replace current optional e-commerce search Yandex Market with Hotline, which was previously agreed and set in Firefox Desktop and Android

Original report: https://bugzilla.mozilla.org/show_bug.cgi?id=1628704

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2340)

**Comment by nick130586** [comment]
This one duplicates #6464

**Comment by lmarceau** [comment]
Since only `data-sync-user` has commented on the issue after the `Stalebot` GitHub action (which triggered the removal of the `stale` label) I’ll close this issue for now. Please let us know if you think this issue needs to be reopened, we'll gladly do so. Thank you!
