### ISSUE TITLE
Default mail is opened instead of the selected mail app after scanning an email QR code

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#6402]
Build: 25.0 (17678)
Device: iPhone 7
iOS: 13.4.1

Steps to reproduce:

1. Go to http://zxing.appspot.com/generator/ and generate an email QR code
2. Open a new tab
3. Tap on the URL bar
4. Scan the QR code

Actual results:

- After scanning an email QR code the default mail app is opened, not the selected app from Settings. 

Note: 
- This is only reproducible when using QR code to send a email

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2342)

**Comment by lmarceau** [comment]
Since only `data-sync-user` has commented on the issue after the `Stalebot` GitHub action (which triggered the removal of the `stale` label) I’ll close this issue for now. Please let us know if you think this issue needs to be reopened, we'll gladly do so. Thank you!
