### ISSUE TITLE
Clearing the Login search field will select a different login entry than the desired one

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#6403]
## Steps to reproduce
1. Go to Menu-> Logins & Passwords
2. Tap "Edit"
3. Search for a login via the search field
4. Tap on the login result
5. Clear the search field by tapping "Cancel" or "x"
### Expected behavior
- The searched login should be selected
### Actual behavior
- The first entry in the login list is selected
### Device & build information
* Device: iPad Pro 13.2.3
* Build version: 25.0 (17678)
### Notes
- Repeating the STR will sometimes crash the app.

Attachments: 
- [Client-2020-04-14-121817.ips.beta.zip](https://github.com/mozilla-mobile/firefox-ios/files/4476486/Client-2020-04-14-121817.ips.beta.zip)

Video Link
- [Video1.mp4.zip](https://github.com/mozilla-mobile/firefox-ios/files/6816334/Video1.mp4.zip)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2343)

**Comment by lmarceau** [comment]
Since only `data-sync-user` has commented on the issue after the `Stalebot` GitHub action (which triggered the removal of the `stale` label) I’ll close this issue for now. Please let us know if you think this issue needs to be reopened, we'll gladly do so. Thank you!
