### ISSUE TITLE
FXIOS-345 ⁃ [XCUITests] Add tests for Chronological tabs order feature

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/firefox-ios#6405]
There is the Chronological Tabs feature coming soon.
See issues: #6338, #6256 
New  automated tests will be needed to cover this feature. 
This issue is to track that work

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2344)

**Comment by isabelrios** [comment]
All info in issue #6204

**Comment by SimonBasca** [comment]
I think this is not in scope as the feature is behind flag and disabled by default on main. Feel free to re-open if you disagree @isabelrios.
