### ISSUE TITLE
Favicon background turns green

### ISSUE THREAD

**Issue by garvankeeley** [mozilla-mobile/firefox-ios#6409]
Moved from https://bugzilla.mozilla.org/show_bug.cgi?id=1626073

I've noticed that when I unlock my iPad and switch to Firefox, often one or more background tabs have green favicons. Switching to the tab fixes the issue but then, maybe a minute or two later after the device locks and I unlock it, another tab will have a green favicon. Here are two screenshots 4 minutes apart.

<img width="1100" alt="image" src="https://user-images.githubusercontent.com/5495083/79348665-49529600-7f03-11ea-85dc-69a1e3c7946d.png">

<img width="1099" alt="image" src="https://user-images.githubusercontent.com/5495083/79348684-52436780-7f03-11ea-9137-07f4b1abdcd2.png">

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2346)

**Comment by ZKTKZ** [comment]
It seems that the default favicon background colors are set to green: https://github.com/mozilla-mobile/firefox-ios/blob/76faae8c6c94e22c8fbc0de72e2d06f615738e2c/Storage/SQL/SQLiteHistoryFavicons.swift#L13

**Comment by garvankeeley** [comment]
I just grabbed '025295' from that list and it is blue (also '27d9d2').

**Comment by garvankeeley** [comment]
I see that the color is set in two places, which seems odd, I would have expected this in one place in the Favicon code, not also the SQL backend code: https://github.com/mozilla-mobile/firefox-ios/search?q=DefaultFaviconBackgroundColors&unscoped_q=DefaultFaviconBackgroundColors

**Comment by ZKTKZ** [comment]
Ah, my bad. I just sampled the first few colors. I'll update my comment.

**Comment by OrlaM** [comment]
Not sure if this was still an issue but at the very least it will be gone in v110.
