### ISSUE TITLE
URL shown in punycode

### ISSUE THREAD

**Issue by garvankeeley** [mozilla-mobile/firefox-ios#6410]
moved from https://bugzilla.mozilla.org/show_bug.cgi?id=1625657

Steps to reproduce:
When you run a site at http://ссср.com/ in iOS it converts it into http://xn--p1abaa.com/
Actual results:
it converts it into punycode.
Expected results:
the domain should appear properly in browsers just like in windows

They would not be able to differentiate b/w http://осср.com and http://ссср.com/ since all the URL are similar looking starting with http://xn--
leading to URL spoofing. Every platform should show the same URL - not just windows.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2347)

**Comment by nbhasin2** [comment]
Look to see if there are any more people complaining about it?
And, see if it comes up again.

**Comment by metastable-void** [comment]
Any progress on this?
