### ISSUE TITLE
Translation toggle is cut-off

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla-mobile/firefox-ios#6414]
The “Translation” section in preferences has layout issues in French

![IMG_6159](https://user-images.githubusercontent.com/1294206/79389047-23121200-7f66-11ea-99ac-cdbbd0db36dd.PNG)

### Device & build information
* Device: iPhone X
* Build version: 25.0 (17610)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2348)

**Comment by nbhasin2** [comment]
Investigate to turn off translations in Beta

**Comment by lmarceau** [comment]
Since only `data-sync-user` has commented on the issue after the `Stalebot` GitHub action (which triggered the removal of the `stale` label) I’ll close this issue for now. Please let us know if you think this issue needs to be reopened, we'll gladly do so. Thank you!
