### ISSUE TITLE
ETP label is truncated in ETP panel

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla-mobile/firefox-ios#6415]
“Enhanced Tracking Protection is ON for this site.” label is truncated in French

![IMG_6160](https://user-images.githubusercontent.com/1294206/79393346-11803880-7f6d-11ea-8751-ced5f5c64e3e.PNG)

### Device & build information
* Device: iPhone X
* Build version: 25.0 (17610)

**Comment by isabelrios** [comment]
I  think this is a dup of: https://github.com/mozilla-mobile/firefox-ios/issues/6355

**Comment by isabelrios** [comment]
Also similar to #6416
