### ISSUE TITLE
Text overflowing in "Offer translation" setting (it locale)

### ISSUE THREAD

**Issue by kitsunenosaraT** [mozilla-mobile/firefox-ios#6417]
## Steps to reproduce
In Firefox iOS, Italian locale, go to Settings > Translation settings.

### Expected behavior
The text next to the toggle button field "Offer Translation" should be neatly inside the field.

### Actual behavior
The text slightly overflows (see attachment).

### Device & build information
* Device: ?
* Build version: 25.0 (17610)
### Notes
Attachments: 
<img width="375" alt="iPhone 8-04Settings-TranslationSettings-0" src="https://user-images.githubusercontent.com/14000019/79456209-631cd780-7fee-11ea-8b79-becd208ba3de.png">

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2350)

**Comment by nbhasin2** [comment]
Investigate to turn off translations in Beta

**Comment by lmarceau** [comment]
Since only `data-sync-user` has commented on the issue after the `Stalebot` GitHub action (which triggered the removal of the `stale` label) I’ll close this issue for now. Please let us know if you think this issue needs to be reopened, we'll gladly do so. Thank you!
