### ISSUE TITLE
Land strings for updated onboarding cards

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-ios#6433]
**Vision**

Strings for the updated oonbaording cards have been sent for localization

**Acceptance Criteria**

* New strings landed in repo (strings in [spec](https://app.abstract.com/share/fb3066fc-2401-48a1-951d-609eb81c3913))
* Strings are in addition to the current onboarding strings, they are not replacing them
* PR created for localization
* Jeff & l10n team informed of new strings

**Not Included**

* This does not include implementing the updated cards

**Comment by nbhasin2** [comment]
We have a new fast search string that might not be in the mockups yet but have been approved.

Fast Search
Search suggestions get you to websites faster.

**Comment by nbhasin2** [comment]
Updating the Automatic Privacy description string as discussed below. cc @betsymi @athomasmoz 

**New String:** Enhanced Tracking Protection blocks malware and stops trackers.

Ref Discussion: https://github.com/mozilla-l10n/firefoxios-l10n/pull/92#discussion_r418532711
