### ISSUE TITLE
QR Code Pairing Events

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-ios#6436]
**Vision**

As a Product Manager, I want tracking in place to measure the success of the QR code pairing feature and determine if changes are needed

----

**Acceptance Criteria**

* Telemetry & Amplitude events in place to analyze results of QR code pairing based on [success criteria](https://docs.google.com/document/d/1sWvj0ewqIofn1zUM0cofC3wiQTbwx9AuH1hp25Xh8vA/edit#heading=h.79ad2m9je1va)
* Data science & data stewards have signed off on approach

**Comment by kaylagalway** [comment]
[This doc](https://docs.google.com/document/d/1sWvj0ewqIofn1zUM0cofC3wiQTbwx9AuH1hp25Xh8vA/edit?ts=5ec4052d#heading=h.79ad2m9je1va) lists the telemetry changes for breach alerts. Below is a summary of the changes.

When user is authenticated successfully after logging in, the following events should be sent:
- If QR code sign in:
    - Category: "firefox_account"
    - Object: "connected"
    - Method: "pairing"
- If Email sign in:
    - Category: "firefox_account"
    - Object: "connected"
    - Method: "email"

Additionally, we want to track when users click sign in to sync to launch the new FirefoxAccountViewController, along with what location in the app that flow is launched from:
- Category: "firefox_account"
- Object(location from which sing in was launched): ("app_menu" | "settings" | onboarding | …)
- Method: "tap"

There should also be a disconnected event when a user initiates logout:
- Category: "firefox_account"
- Object: "disconnected"
- Method: null

**Comment by irrationalagent** [comment]
@kaylagalway this looks like an accurate summary of what we need. there is one more (optional) measurement that I recommend: a boolean added to the `core` ping that indicates whether or not sync is currently signed into. This could be relevant to measuring the success of QR codes if we care about knowing whether or not the *proportion* of clients signed in changes after QR scanning is implemented. 

However, it would also mean that we would have to implement that boolean before the QR feature is shipped. Which may or may not be possible. If we can't do that, then I would argue that it would still be a useful general-purpose measurement to have, but it won't be directly relevant to measuring the success of pairing.

**Comment by kaylagalway** [comment]
For QA verification - I have a PR open to add a doc explains the process for testing glean events here: https://github.com/mozilla-mobile/firefox-ios/pull/6732
