### ISSUE TITLE
Partially blank or fully blank content area

### ISSUE THREAD

**Issue by arthuredelstein** [mozilla-mobile/firefox-ios#6443]
After I browse for a while, pages suddenly appear partially or completely blank. The length of the page seems to be preserved -- it still scrolls, and longer pages scroll further. This happened on a number of pages and websites; I haven't noticed a pattern.

Here's a partially blank content area:

![IMG_4552](https://user-images.githubusercontent.com/355566/79930609-cf884400-83fd-11ea-8baf-bd15da498737.png)

Here's a completely blank content area:

![IMG_4553](https://user-images.githubusercontent.com/355566/79930611-d1ea9e00-83fd-11ea-9cf7-18b36b5e4e0e.png)

Interestingly, if I hit the Back button, I can still see pages in my history and they aren't blanked out, even if I reload those pages. But then if I hit the forward button, the new pages remain blank.

If I force-quit Firefox iOS by double-tapped the home button and dismissing it, and then restart Firefox, then the same pages render properly when they are restored.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2353)

**Comment by athomasmoz** [comment]
This is a known issue with the WebKit component we use. Follow-up items:
* Is it related to other tabs open
* Investigate to see if we can identify when this happens and reload the page
