### ISSUE TITLE
FXIOS-358 ⁃  URL bar rendering out of place and without text on iPad Pro 11" (2nd Generation)

### ISSUE THREAD

**Issue by csuciu** [mozilla-mobile/firefox-ios#6446]
See https://bugzilla.mozilla.org/show_bug.cgi?id=1628077

With the new (2nd Generation) iPad Pro 11", running iOS 13.4 with Firefox version 24.1 (17574), Firefox is rendering the URL bar incorrectly. See attached screen shots.

![1](https://user-images.githubusercontent.com/1866605/79991460-02dcd880-84bb-11ea-8d46-d9f455bc0c74.png)
![2](https://user-images.githubusercontent.com/1866605/79991467-0708f600-84bb-11ea-9b69-c580b96d05e9.png)
We could not reproduce this issue on iPad Pro 11" 1st Generation

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2355)

**Comment by athomasmoz** [comment]
Need to determine if this is reproducible on simulator, or if we need to gt the physical device to test & fix

**Comment by SimonBasca** [comment]
I was unable to reproduce this issue with simulator iPad Pro 11'' 2nd gen (13.4.1) on latest master f57c1903597b7 and branch v24.x ed6d3f0c3.
