### ISSUE TITLE
FXIOS-359 ⁃ Sometimes title is not displayed on tab on iPad Pro 11" (2nd Generation)

### ISSUE THREAD

**Issue by csuciu** [mozilla-mobile/firefox-ios#6447]
See https://bugzilla.mozilla.org/show_bug.cgi?id=1628209

With the new (2nd Generation) iPad Pro 11", running iOS 13.4 with Firefox version 24.1 (17574), Firefox sometimes does not display the tab title on the tab. I can't seem to reproduce this on demand. I hit the bug sometimes when switching from private browsing to non-private browsing mode.
![3](https://user-images.githubusercontent.com/1866605/79992254-e8efc580-84bb-11ea-926d-b59c9ab84503.jpg)
We could not reproduce this issue on iPad Pro 11" 1st Generation.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2356)

**Comment by csuciu** [comment]
See https://bugzilla.mozilla.org/show_bug.cgi?id=1628209

**Comment by dnarcese** [comment]
Covered in #8942
