### ISSUE TITLE
FXIOS-362 ⁃ Update the Wiki (Refactor Docs) from within the app to Wiki

### ISSUE THREAD

**Issue by nbhasin2** [mozilla-mobile/firefox-ios#6453]
Combine the following documents and move them to Wiki

Contributing: 
https://github.com/mozilla-mobile/firefox-ios/blob/master/CONTRIBUTING.md

Docs inside the folder should move to Wiki except for Telemetry: 
https://github.com/mozilla-mobile/firefox-ios/tree/master/Docs

Update: 
https://github.com/mozilla-mobile/firefox-ios/wiki/Firefox-iOS-contribution-(Starter-Guide)

https://github.com/mozilla-mobile/firefox-ios/blob/master/README.md

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2359)

**Comment by ahmedrezik** [comment]
Hello, I currently decided working on this issue but need a to ask a few questions.
Do you need to combine all of the above documents into a new single wiki page? or should I amend the Firefox-iOS-contributions-(Starter-Guide) page

**Comment by nbhasin2** [comment]
Hi @ahmedrezik, Yes, have a new combined doc(s) that we can likely organize it in a single or multiple doc.

Our goal is to put the it all in the wiki so best option would be combine it in an markdown file and upload here as I believe you might not have permission to modify wiki. 

Let me know if you think this approach works and if you have any more questions. 

Thanks :)
