### ISSUE TITLE
Add Extra field for Foreground Events (verify with Glean)

### ISSUE THREAD

**Issue by fbertsch** [mozilla-mobile/firefox-ios#6457]
Bug here: https://bugzilla.mozilla.org/show_bug.cgi?id=1632651

**Background** 

As an org we're sending more events to Amplitude than we expected when we signed the contract last year. Firefox iOS is sending a large number of events (~18% of our total), with two events accounting for 90% of their total - App Foreground and App Background.

App Background event will be turned off. We need to ensure that foreground event is being fired correctly and is useful for analysis. Is there any way we can reduce their volume?

**Acceptance Criteria**

* Add a new extra field on this event that indicates the cause of foreground events

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2361)

**Comment by fbertsch** [comment]
cc @garvankeeley

**Comment by fbertsch** [comment]
For reference, we've seen >850MM total events for foreground/background. The next largest event is `action.tap.private-browsing-button` with ~16.5MM events, so foreground/background are firing ~27x as often.

Is it important for you all to track every single session, even with no in-between events? If not, and these events are merely useful for tracking user activity per-day (for e.g. retention, MAU, etc.), then a technique we're using with FxA is to send just the first event per-user. For you all that would bring the volume down significantly, to ~2MM per-day (saving us ~700MM events per-month).

**Comment by fbertsch** [comment]
Running a quick analysis from a single day of data:
![image](https://user-images.githubusercontent.com/20819040/80381165-86f1e000-886e-11ea-96d3-498f70fa2700.png)

For FxA, we're starting a process of just sending 1 `cert_signed` event per-user per-day. What this will do is still give accurate numbers for e.g. DAU/WAU/retention, but it will _not_ give correct values for the number of `cert_signed` events they send. However they never actually need that analysis, all they send that event for is to indicate the user was active on that day.

If that is what the foreground and background events are used for, I'm hoping we can make the same change. There would be no changes on the client, but before we send the data to Amplitude, we would send just the first foreground and first background events from each client.

I've looked through the analyses in Amplitude and don't see anything specific that uses foreground/background events, so it looks like that may be an acceptable compromise.

**Comment by garvankeeley** [comment]
> For reference, we've seen >850MM total events for foreground/background. The next largest event is `action.tap.private-browsing-button` with ~16.5MM events, so foreground/background are firing ~27x as often.

The 2nd largest event should be new tab I would think (by a large margin over other events). But it does seem reasonable that the home button is pressed 27x more that the private browsing button yeah, many of people never use PB mode. 'New tab' should be happening a lot though.

**Comment by st3fan** [comment]
I don't have a lot of context re this discussion but I do want to add that background/foreground events do not just happen when the user pushes the app into the background. They also happen when  a notification appears, when the control center is pulled down, when the share sheet is opened and possibly even a few more cases.

**Comment by garvankeeley** [comment]
Agreed with Stefan's comment, I should have mentioned that. Those reasons are why it is valid to happen so frequently.

**Comment by fbertsch** [comment]
Great, this is _very_ helpful context. Is there information within the event that indicates what kind of activity is was?

I'm wondering if we can filter to what we might consider _useful_ indicators of activity for these clients. Notifications appearing is probably not useful, unless they then go and open the app; in which case we would record a "standard" foreground event.

Does iOS also have the concept of custom tabs that Android does?

**Comment by garvankeeley** [comment]
> Great, this is _very_ helpful context. Is there information within the event that indicates what kind of activity is was?

Not that I am aware of, once we get this triaged and assigned to an eng they might -fingers crossed- find something useful if they dig around. (My gut feel is that there is no way to know).
If we could find out the event type, we could do as you suggested and consider only tracking certain types of events.

> Does iOS also have the concept of custom tabs that Android does?

I don't think so, what is a custom tab?

**Comment by fbertsch** [comment]
Okay, I was hoping we could fix this on our end, but it doesn't sound like that's the case.

@garvankeeley, custom tabs are what opens when someone opens a web page from a different app. It uses the default web browser but doesn't actually open the browser application as a whole, the tab stays within the app.

**Comment by fbertsch** [comment]
Hi All, can we get a new `extra` field on this event that indicates the cause of foreground/background? At the very least we need a tag that indicates the ones we're interested in.

**Comment by garvankeeley** [comment]
Looking at the APIs I only see https://developer.apple.com/documentation/uikit/uiapplication/state which has `active`, `inactive`, and `background`, maybe we could research the difference between the latter two, or at least add that as a field?

**Comment by garvankeeley** [comment]
There is no way to quickly add this field. I don't see why we couldn't migrate to Glean for the next iOS release, in which case it can be addressed there.

Tech note: Telemetry-ios closes the ping file in appWillResignActive() and sends in didEnterBackground, https://github.com/mozilla-mobile/telemetry-ios/blob/master/Telemetry/AppEvents.swift#L33
CorePingBuilder.endSession() could possibly be used to query and write an application state measurement, but we would need to verify data is arriving correctly.

**Comment by fbertsch** [comment]
@garvankeeley That is a reasonable compromise. Let's wait until we're on Glean and revisit. I appreciate you looking into it!

**Comment by lmarceau** [comment]
Since only `data-sync-user` has commented on the issue after the `Stalebot` GitHub action (which triggered the removal of the `stale` label) I’ll close this issue for now. Please let us know if you think this issue needs to be reopened, we'll gladly do so. Thank you!
