### ISSUE TITLE
FXIOS-366 ⁃ notDecrypted receiving a tab

### ISSUE THREAD

**Issue by eoger** [mozilla-mobile/firefox-ios#6460]
Using the latest beta 25.0 (17610), I'm getting a `Error: notDecrypted` notification when receiving a tab from Desktop nightly.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2363)

**Comment by garvankeeley** [comment]
Any theories as to why? Or if there is something we can do to recover from that state? I assume it is persistently bad for you and not an intermittent thing

**Comment by garvankeeley** [comment]
Was the Beta upgraded from prev such that you were already signed-in to sync? Or could this be a migration problem. This debug error is new, in the past it would just say "Tap to begin", and we had regular reports of that error in the past. Any guess as whether this is a new issue or might it be the old "Tap to begin" bug resurfaced as this error?

**Comment by eoger** [comment]
> Any theories as to why? Or if there is something we can do to recover from that state? I assume it is persistently bad for you and not an intermittent thing

Not sure, maybe we should log more information, because it could be related to a lot of things currently.

**Comment by garvankeeley** [comment]
Do you have more than one build installed? Both beta and release?

**Comment by eoger** [comment]
Only one build (not Firefox release installed), and I can reproduce reliably.

**Comment by garvankeeley** [comment]
A new v25 beta will be out within the hour. It will be interesting to see if that fixes it.

**Comment by athomasmoz** [comment]
Was able to successfully receive a tab iPhone 11 with beta 17793 and OS 13.3.1. Sending from Nightly 77.0a1

**Comment by garvankeeley** [comment]
Same but seems intermittent, sometimes no tab is received. However, an intermittent response would not relate to this bug.

**Comment by garvankeeley** [comment]
Closing this seems to be a false alarm, I can't repro, but I was definitely in a state where the logins and passwords screen was empty.

**Comment by eoger** [comment]
> Closing as this seems to be a false alarm, I can't repro, but I was definitely in a state where the logins and passwords screen was empty.

Did you mean to close another bug?

**Comment by garvankeeley** [comment]
Sorry yeah

**Comment by garvankeeley** [comment]
Removing release blocker tag as we only have this report so far on Beta. It is being heavily tested by QA and so far it is looking ok.

**Comment by garvankeeley** [comment]
The error has now changed to showing this error https://searchfox.org/mozilla-mobile/source/application-services/components/fxa-client/src/device.rs#148

**Comment by eoger** [comment]
Opened a PR that *might* fix the problem: https://github.com/mozilla/application-services/pull/3065

**Comment by garvankeeley** [comment]
Confirming that testing the a-s patch above fixes the error seen on iOS. The patch catches the decryption error and resets the necessary keys.

**Comment by eoger** [comment]
Update: we're still seeing issues such as "Could not find refresh token" (it should ALWAYS be present).

I found some errors `Access to item attempted while keychain is locked` in the console.

**Comment by eoger** [comment]
Update: https://github.com/mozilla/application-services/issues/3083 seems to be the culprit here.
