### ISSUE TITLE
Discovery: Privacy By Default

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-ios#6461]
**Vision**

Try giving Firefox users more privacy from the start to remove any negative stigma on needing privacy and turn it into a differentiator for our browser on iOS.

**Details**

Full details in the [PRD](https://docs.google.com/document/d/1k4PHgSi8F_HIxlmOH0pK_SOz1UVWobvEMvjVLrdsC2I/edit#)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2364)

**Comment by lmarceau** [comment]
Since only `data-sync-user` has commented on the issue after the `Stalebot` GitHub action (which triggered the removal of the `stale` label) I’ll close this issue for now. Please let us know if you think this issue needs to be reopened, we'll gladly do so. Thank you!
