### ISSUE TITLE
www.asahi.com - no redirection to the mobile version.

### ISSUE THREAD

**Issue by karlcow** [mozilla-mobile/firefox-ios#6463]
## Steps to reproduce
1. go to http://www.asahi.com/ajw/

### Expected behavior
 be redirected to http://www.asahi.com/sp/ajw/

### Actual behavior
stay on http://www.asahi.com/ajw/

### Device & build information
* Device: iphone xs
* Build version: version 24.1 17574

### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2366)

**Comment by lmarceau** [comment]
@csuciu @SimonBasca This seems fine on latest main 7bf455c419d93d73e76fa1cf268c8c67eca743e6. Can this be retested?

https://user-images.githubusercontent.com/11338480/173401596-16541407-9149-4adb-bd8f-2356e9a4db74.mp4

**Comment by csuciu** [comment]
No longer reproducible on latest main. Closing.
