### ISSUE TITLE
Settings Search Options: Replace Yandex Market with Hotline

### ISSUE THREAD

**Issue by garvankeeley** [mozilla-mobile/firefox-ios#6464]
bugzilla bug https://bugzilla.mozilla.org/show_bug.cgi?id=1628704

Since the Yandex services are officially banned in Ukraine and it's not possible to use it directly without bypassing via VPN, please replace current optional e-commerce search Yandex Market with Hotline, which was previously agreed and set in Firefox Desktop and Android.

**Comment by csuciu** [comment]
Verifying as fixed on master c7a498f4d.
