### ISSUE TITLE
v25 beta: disconnecting and reconnecting account not connecting properly

### ISSUE THREAD

**Issue by garvankeeley** [mozilla-mobile/firefox-ios#6469]
## Steps to reproduce
- connect to FxA
- disconnect account, and sign in again, wait a few seconds to allow sign in
- kill app and restart app

### Expected behavior
- You are signed in if you tap on the app menu

### Actual behavior
- Not signed in, tapping on app menu shows that user is not signed in to account properly

**Comment by SimonBasca** [comment]
This issue is not reproducible on version 25.0(17793).
