### ISSUE TITLE
Logins not synced

### ISSUE THREAD

**Issue by garvankeeley** [mozilla-mobile/firefox-ios#6472]
## Steps to reproduce
- install v25 beta
- signin to FxA account that has some logins saved

### Expected behavior
- logins are shown

### Actual behavior
- no logins and passwords shown

**Comment by garvankeeley** [comment]
@athomasmoz this is a blocker, not sure the cause just yet, hopefully a quick fix for something that was unhooked.

**Comment by garvankeeley** [comment]
Closing, I can't repro this now.

**Comment by SimonBasca** [comment]
@garvankeeley is this the behavior you were experiencing in this issue? 
[Untitled.mov.zip](https://github.com/mozilla-mobile/firefox-ios/files/4551425/Untitled.mov.zip)

**Comment by garvankeeley** [comment]
Yes that is it!! Any idea how to repro? Does the app stay in that state?

**Comment by SimonBasca** [comment]
I just found new STR to reproduce this issue
1. Install 25.0 (17793)
2. Log in to FxA
3. Disconnect FxA
4. Reconnect FxA
5. Go to a login form and save a login
6. Go to Login Screen

Actual results:
- The login screen is not populated. Only a loading throttle is displayed. See https://github.com/mozilla-mobile/firefox-ios/files/4551425/Untitled.mov.zip

**Comment by SimonBasca** [comment]
Verified fix on 25.0 (17803).
