### ISSUE TITLE
Send tab not working after not agreeing to notifications, then enabling

### ISSUE THREAD

**Issue by garvankeeley** [mozilla-mobile/firefox-ios#6475]
## Steps to reproduce
* sign in to FxA
* say no to enabling push notifications
* got to device settings and enable notifications for the app
* restart the app
* send a tab to the device

### Expected behavior
* tab should be received

### Actual behavior
* tab not received

v24 and v25 both exhibited the same problem, so this isn't a regression.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2368)

**Comment by AnaMedinac** [comment]
@garvankeeley Does it work if you click "Sync Now", and is it only not working for the first tab and subsequent ones are received automatically? 

Or would the user have to sign out, then back in?

**Comment by garvankeeley** [comment]
We don't get tabs on Sync now, the sync process is not hooked up to consume the queued sent tabs, when we migrate the sync engine to rust I would like if we hooked that up (I am not actually sure if app-services lib supports this). 

User would have to sign out and in to retrigger the push notification setup. I don't think it is hard to hook this up, just need someone on our side to tackle this
