### ISSUE TITLE
FXIOS-374 ⁃ Remove translations feature from BETA

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-ios#6476]
**Vision**

Translation feature is not available until we have confirmed the privacy policy from Google for the feature and can share with our users

**Acceptance Criteria**

* Translations feature is not shown in beta
* Github bugs related to translations feature are closed as won't fix

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-374)

**Comment by garvankeeley** [comment]
This is the commit to revert https://github.com/mozilla-mobile/firefox-ios/commit/2cfe0981fa93145ccc88ab96dbd0877351ec381f

**Comment by SimonBasca** [comment]
The Translation feature is still shown in the latest beta 28.1 (19225). 

@garvankeeley could you please take a look and see if this should be uplifted.

**Comment by garvankeeley** [comment]
Thanks for checking that, 28.1 is identical to 28.0, but without adjust and with handling for default browser, the latter I don't know when we will be able to test that in iOS 14.

**Comment by SimonBasca** [comment]
Removed on beta 29.0(2609).
