### ISSUE TITLE
Push notification service while app in background less reliable with RustFxA

### ISSUE THREAD

**Issue by garvankeeley** [mozilla-mobile/firefox-ios#6478]
As of v25 with RustFxA the push notification service seems to be responding less frequently than it did previously with the app in the background. Concretely I can send 10 tabs and 2-3 won't arrive, with the release  I might see 1 not arrive. I am on iPhone 8 for testing.

In the past there was a problem with slow startup of the service: https://stackoverflow.com/questions/48500724/ios-notification-service-extension-will-be-killed-due-to-sluggish-startup

I am not seeing those springboard messages in the log so I can't say conclusively what is causing this.

This only happens on non-debugging builds. Thus it requires a beta to test this.

**Comment by garvankeeley** [comment]
Debugging tips: use the Console.app and filter for things such as
- APNS messages
- messages with `notificationservice` or `firefoxbeta.notificationservice`
- add public os_log messages like `os_log("%{public}@", log: OSLog(subsystem: "org.mozilla.firefox", category: "firefoxnotificationservice"), type: OSLogType.debug, "Push received!")`

Note that https://developer.apple.com/library/archive/technotes/tn2265/_index.html has some tips but the advice about installing a debugging profile doesn't apply for iOS 10 and higher.

**Comment by garvankeeley** [comment]
This is a debug session sending tab from desktop to my iPhone 8, showing the console messages that display when a tab is successful, and in one case, a tab did not arrive and the console is blank.
![notificationservice](https://user-images.githubusercontent.com/5495083/80542246-a7a75c00-897a-11ea-83cc-6089a79ff91d.gif)

**Comment by eoger** [comment]
Tracking issue on a-s: https://github.com/mozilla/application-services/issues/3097
Autopush investigation: https://github.com/mozilla-services/autopush/issues/1383

**Comment by rfk** [comment]
The two issues linked above have been closed, @garvankeeley are you able to see any difference from your side of things after that?

**Comment by garvankeeley** [comment]
No difference that I have seen so far since that was reported and a few minor a-s releases have been cut. I don't believe my original comment to be an accurate description. Receiving tabs is so unreliable/spotty that my statement that 'v24.1 was more reliable than v25.x' is unlikely to be true. –they likely equally unreliable if tested enough.
After getting a better understanding of logging APNS on-device (https://github.com/mozilla-mobile/firefox-ios/issues/6478#issuecomment-620880032) I am convinced my problem is the push notification is not sent to the device when tabs don't arrive. Every time a tab fails to arrive, I also fail to see iOS APNS daemon logging messages on the device.

**Comment by garvankeeley** [comment]
@csuciu @SimonBasca with the app in background can you send a bunch of tabs to it and report your success rates? I'll try it too. What can make this hard to repro is that it seems to work completely fine sometimes, but once it starts to drop tabs I seem to be able to repro it no problem for the next 30 mins.

**Comment by SimonBasca** [comment]
Tested on v 25.1 (17881) with the app. 

** Case 1) - Send tab to iOS from a new tab on desktop with Firefox iOS closed from app switcher.

1. On desktop -> open a new tab ->google search "Google 1" -> Send tab
2. On desktop -> open a new tab ->google search "Google 2" -> Send tab
3. On desktop -> open a new tab ->google search "Google 3" -> Send tab
4. On desktop -> open a new tab ->google search "Google 4" -> Send tab
5. On desktop -> open a new tab ->google search "Google 5" -> Send tab
6. On desktop -> open a new tab ->google search "Google 6" -> Send tab
7. On desktop -> open a new tab ->google search "Google 7" -> Send tab
8. On desktop -> open a new tab ->google search "Google 8" -> Send tab
9. On desktop -> open a new tab ->google search "Google 9" -> Send tab
10. On desktop -> open a new tab ->google search "Google 10" -> Send tab


** Case 2) - Send tab to iOS from the same tab on desktop with Firefox iOS closed from app switcher.

1. On desktop -> open a new tab ->google search "Google 1" -> Send tab
2. On desktop -> in the same tab ->google search "Google 2" -> Send tab
3. On desktop -> in the same tab ->google search "Google 3" -> Send tab
4. On desktop -> in the same tab ->google search "Google 4" -> Send tab
5. On desktop -> in the same tab ->google search "Google 5" -> Send tab
6. On desktop -> in the same tab ->google search "Google 6" -> Send tab
7. On desktop -> in the same tab ->google search "Google 7" -> Send tab
8. On desktop -> in the same tab ->google search "Google 8" -> Send tab
9. On desktop -> in the same tab ->google search "Google 9" -> Send tab
10. On desktop -> in the same tab ->google search "Google 10" -> Send tab

Case 1) works 100%.
Case 2) works 60% - 80% of the time. The 5th and the 8th tab out of 10 sometimes fail to send in my case.

**Comment by SimonBasca** [comment]
Also got a sync failed log on desktop while sending a tab which didn't get received on iOS. 

[Untitled.zip](https://github.com/mozilla-mobile/firefox-ios/files/4634277/Untitled.zip)

**Comment by rfk** [comment]
> Also got a sync failed log on desktop while sending a tab which didn't get received on iOS.

Looks like some "HMAC Mismatch" errors in your desktop sync log:

```
1589544443657	Sync.Engine.Tabs	WARN	Error decrypting record: HMACMismatch: Record SHA256 HMAC mismatch: should be 57073e0125f9ab66371600765f850051659754416f5486276fc41c11804a155b, is 30512f3b88dc01dae24892135af0d1fad5019ca14927957bb7f754785fbf7cda(resource://services-sync/util.js:69:5) JS Stack trace: HMACMismatch@util.js:69:5
throwHMACMismatch@util.js:304:11
decrypt@record.js:191:13
_maybeReconcile@engines.js:1392:20
_processIncoming/<@engines.js:1225:49
yieldingForEach@async.js:151:22
```

And

```
1589544445369	Sync.Engine.History	WARN	Error decrypting record: HMACMismatch: Record SHA256 HMAC mismatch: should be 6cbaa787c40ed97a4518e6d888ee6ff2c868dd7e4a8dc17828d6fdec823d1bdf, is acb12d0e4c1685cbd9443a7c3391b9cad1b849fc11c0c55d821dde6a6f6dd5c7(resource://services-sync/util.js:69:5) JS Stack trace: HMACMismatch@util.js:69:5
throwHMACMismatch@util.js:304:11
decrypt@record.js:191:13
_maybeReconcile@engines.js:1392:20
_processIncoming/<@engines.js:1324:51
yieldingForEach@async.js:151:22
_processIncoming@engines.js:1323:21
1589544445369	Sync.Engine.History	INFO	Records: 1 applied, 0 successfully, 1 failed to apply, 0 newly failed to apply, 0 reconciled.
```

That's concerning, as these should never happen in practice unless there's a buggy client connected to the account. I'm not sure if they could be related to the failure to send a tab though - the same log does seem to show a successful send of a tab.

**Comment by rfk** [comment]
@SimonBasca if you still have the desktop profile that produced the above sync error log, is it able to sync correctly or does it continue to produce an error log on each sync?

**Comment by SimonBasca** [comment]
@rfk I am still able to correctly sync bookmarks, history, synced tabs with that profile. The "sync fail" was a one time event when I was trying to test this issue.

**Comment by SimonBasca** [comment]
Tested on v 26.0 (18092).

Repeated the tested scenarios and push notifications seem more reliable when the app is in background.
