### ISSUE TITLE
SQLiteHistory.generateDefaultFavicon crashing

### ISSUE THREAD

**Issue by garvankeeley** [mozilla-mobile/firefox-ios#6480]
It looks like `defaultFaviconImageCache` is accessed from two threads.

Screenshot of the crash report 
<img width="906" alt="image" src="https://user-images.githubusercontent.com/5495083/80545322-138cc300-8981-11ea-813f-161c2718e9bd.png">

**Comment by SimonBasca** [comment]
We didn't encountered any crash in the history panel while testing 25.1 (17865).
