### ISSUE TITLE
Crash in Authenticator.findMatchingCredentialsForChallenge(_:fromLoginsProvider:) ()

### ISSUE THREAD

**Issue by garvankeeley** [mozilla-mobile/firefox-ios#6481]
I suspect this should be calling back on the main thread. The off-main thread nature of this is suspect as the app has minimal support for non-main thread behaviour.

Crash report in Xcode
<img width="885" alt="image" src="https://user-images.githubusercontent.com/5495083/80545422-3e771700-8981-11ea-9d27-07e71a93a507.png">

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2371)

**Comment by data-sync-user** [comment]
➤ Laurie Marceau commented:

Still happening as of v101. Number of occurrences is pretty low.

**Comment by lmarceau** [comment]
Closing it as duplicate in favor of https://github.com/mozilla-mobile/firefox-ios/issues/8429 which contains a little bit more information
