### ISSUE TITLE
Crash in DownloadQueue, appears to be threading related

### ISSUE THREAD

**Issue by garvankeeley** [mozilla-mobile/firefox-ios#6483]
This appears to be doing work off-main, which I doubt is supported, likely shared access to an array is crashing.

<img width="498" alt="image" src="https://user-images.githubusercontent.com/5495083/80545859-5307df00-8982-11ea-91d8-ff691850d952.png">

**Comment by garvankeeley** [comment]
QA: please re-test the downloads feature to make sure nothing major is broken. Try to find a larger file to download that takes more than a few seconds to download. Thanks

**Comment by SimonBasca** [comment]
This issue is verified fix on 25.0 (17861).  I did not encounterd any crash while testing, but I encounter a strange issue #6561 .
