### ISSUE TITLE
sync_disconnected push notification not sent between desktop and iOS

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#6485]
## Steps to reproduce
When disconnecting an account on desktop or mobile, there's no sync_disconnected push notification received on the other end.
### Device & build information
* Device: iPhone 7 (13.4)
* Build version: 25.0 (17793)
### Notes
https://bugzilla.mozilla.org/show_bug.cgi?id=1497170

**Comment by garvankeeley** [comment]
@eoger can you confirm if this is known/expected behaviour in terms of filtering messages on the server-side?

**Comment by eoger** [comment]
I believe Desktop and Android would not show you the "device disconnected" notification indeed. It is a special case for iOS (that I think we could remove), however these do process the `sync_disconnected` push message silently.

**Comment by athomasmoz** [comment]
This is expected behaviour. When we were discussing how it should behave, UX suggested that we limit the number of notifications sent, so we only send ‘Sync Connected’ notifs.
