### ISSUE TITLE
Battery consumption in the app is creeping up as of v24

### ISSUE THREAD

**Issue by garvankeeley** [mozilla-mobile/firefox-ios#6487]
This needs investigation

<img width="719" alt="image" src="https://user-images.githubusercontent.com/5495083/80602334-fbf32000-89fc-11ea-85c9-e80c25cfc0db.png">

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2372)

**Comment by garvankeeley** [comment]
Disk write are trending upward, I suspect it is related
<img width="740" alt="image" src="https://user-images.githubusercontent.com/5495083/80602917-bb47d680-89fd-11ea-9d27-f3503f21e9d7.png">

**Comment by nasiralamreeki** [comment]
Any action on this?
