### ISSUE TITLE
[sec] Reader mode bugzilla bug#1633140

### ISSUE THREAD

**Issue by garvankeeley** [mozilla-mobile/firefox-ios#6493]
Security bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1633140

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2374)

**Comment by data-sync-user** [comment]
➤ Laurie Marceau commented:

Closed here since tracked with https://github.com/mozilla-mobile/firefox-ios/issues/6946 ( https://github.com/mozilla-mobile/firefox-ios/issues/6946|smart-link ) (not sec issue)
