### ISSUE TITLE
Test case needed for disconnect and reconnect FxA

### ISSUE THREAD

**Issue by garvankeeley** [mozilla-mobile/firefox-ios#6495]
I am not sure how we will set this up, maybe with a mock account, but it would be good to have a test for disconnecting and reconnecting FxA and ensuring that the logins DB and other items in the profile are still healthy.

**Comment by isabelrios** [comment]
Blocked due to #6554

**Comment by isabelrios** [comment]
Removing Blocked label since PR #6901 fixes the problem preventing us to continue with this development
