### ISSUE TITLE
FXIOS-387 ⁃ [UX] Set Firefox as Default Browser

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-ios#6499]
**Vision**

As a user, I want to set Firefox as my default browser, so that links automatically open in it and I don't need to use both Safari and Firefox

----

**Acceptance Criteria**

* Firefox meets requirements to be a default and is registered
* We have a clearly articulated value prop for setting Firefox as your default browser
* Messaging ready to inform users how to set us as a default

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-387)

**Comment by megabacon** [comment]
No longer a rumor:  https://9to5mac.com/2020/06/22/ios-14-default-apps/

**Comment by junbio** [comment]
Seems to take the form of an entitlement that needs to be [given](https://developer.apple.com/forums/thread/650027):

> -  Applications will need to take the new Managed Entitlement 'com.apple.developer.default-web-browser'.
> -  Applications must comply with a set of minimum functional criteria for handling web links and allowing user control of page navigation.
>
>Applications will need to take the new Managed Entitlement 'com.apple.developer.default-web-browser'.
 Applications must comply with a set of minimum functional criteria for handling web links and allowing user control of page navigation.

**Comment by brampitoyo** [comment]
Update from Apple:
> For the Default Web Browser entitlement, please use "default-browser-requests@apple.com"

**Comment by malj** [comment]
Any ETA on this?

**Comment by snachx** [comment]
Apple official document for this:
https://developer.apple.com/documentation/xcode/allowing_apps_and_websites_to_link_to_your_content/preparing_your_app_to_be_the_default_browser_or_email_client

**Comment by data-sync-user** [comment]
➤ Ashley Thomas commented:

No updates from Apple. Based on when they release new versions in previous years, we expect September

**Comment by data-sync-user** [comment]
➤ Ashley Thomas commented:

Current mocks (in progress) https://mozilla.invisionapp.com/share/U6Y7EZWRMYT#/screens/426504376

**Comment by data-sync-user** [comment]
➤ Ashley Thomas commented:

UX completed.

**Comment by malj** [comment]
Where can the implementation be tracked?
