### ISSUE TITLE
FXIOS-389 ⁃ [META] iPad Multi-Tasking

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-ios#6501]
**Vision**

As a user, I can see another app at the same time as Firefox for multi-tasking

----

**Acceptance Criteria**

* Slide Over supported
* Split View supported
* Picture in Picture mode supported

----

**Links**

* Specs from Apple https://developer.apple.com/design/human-interface-guidelines/ios/system-capabilities/multitasking/

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2377)

**Comment by lmarceau** [comment]
Closing here since issue is closed in JIRA
