### ISSUE TITLE
`crashedLastLaunch` is being reported in the core ping

### ISSUE THREAD

**Issue by fbertsch** [mozilla-mobile/firefox-ios#6502]
We're receiving a field from Firefox iOS which has `settings.crashedLastLaunch`. However you all aren't reporting any other settings in the core ping, and we don't even have that in the schema. Was this field supposed to go in the mobile-event ping? That has a `settings` field.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2378)

**Comment by garvankeeley** [comment]
How do we define what goes in a `core` vs `event` ping? My guess is that event pings are sent lots of times while the app is in a session? If so then `core` is where this would go, this data is only updated once per app launch. I think the fact is a `setting` is incorrect in terms of naming it.

**Comment by fbertsch** [comment]
@garvankeeley really up to you all, the core ping should be lighter and is sent frequently. The event ping should be sent after sessions.

**Comment by lmarceau** [comment]
Since only `data-sync-user` has commented on the issue after the `Stalebot` GitHub action (which triggered the removal of the `stale` label) I’ll close this issue for now. Please let us know if you think this issue needs to be reopened, we'll gladly do so. Thank you!
