### ISSUE TITLE
Turn on Sync Page

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-ios#6505]
**Vision**

As an existing Firefox user, I want to sign into my account on iOS without having to type my credentials, so I can quickly access everything stored in my account on my iOS device

**Acceptance Criteria**

* There is a new turn on sync page that matches the attached [spec](https://app.abstract.com/share/c4d5475f-4f5e-4c4e-9bf3-1aefa06e0ce6?collectionId=73540397-d5d0-4c35-98dc-eef53bc6a961&collectionLayerId=3b61eac3-361c-4b70-b643-acabfb8ba9ee&present=true&preview=false&sha=5c1075fc981b18c245df481e633585c7364cfa0b)
* All sign in buttons/links within the app point to the new "Turn on Sync" page
* Event added (following our privacy guidelines) on the below buttons to help compare usability of the two options
  * Clicks on "Ready to Scan" button
  * Clicks on "Use Email Instead" button

**Comment by lime124** [comment]
@apbitner can you provide a list of access points to the that QR page(linked in comment 0) that need to be updated? Eng needs this before May 18th. Thanks!

**Comment by apbitner** [comment]
The full spec shows the different entry points - https://share.goabstract.com/c4d5475f-4f5e-4c4e-9bf3-1aefa06e0ce6

They known ones are onboarding, settings, synced tabs and send tabs. Basically any page that links to the current login w/ email screen, should now point to the new screen where the user chooses between QR code and email. If any other entry points are found please let me know.

**Comment by apbitner** [comment]
We've received an updated illustration for this screen form the UX Systems team. It's been updated in the spec, but I'm attaching the SVG here as well.

[illustration-qr-scan.svg.zip](https://github.com/mozilla-mobile/firefox-ios/files/4611644/illustration-qr-scan.svg.zip)

**Comment by SimonBasca** [comment]
Verified fix on 26.0 (18036). 

Tested: 
- There is a new turn on sync page that matches the attached spec
- All sign in buttons/links within the app point to the new "Turn on Sync" page
