### ISSUE TITLE
Scan QR Code for Sync Login

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-ios#6506]
**Vision**

As an existing Firefox user, I want to sign into my account on iOS without having to type my credentials, so I can quickly access everything stored in my account on my iOS device

**Acceptance Criteria**

* Existing users can scan a QR code to sign into sync in FF iOS
* QR code screen matches the [spec](https://app.abstract.com/share/c4d5475f-4f5e-4c4e-9bf3-1aefa06e0ce6?collectionId=73540397-d5d0-4c35-98dc-eef53bc6a961&collectionLayerId=ccacd1f0-c2f7-4bb3-81ea-6c6abaaeba6b&present=true&preview=false&sha=5c1075fc981b18c245df481e633585c7364cfa0b)
* Workflows leading in and out of the QR code screen match the [spec](https://app.abstract.com/share/c4d5475f-4f5e-4c4e-9bf3-1aefa06e0ce6?collectionId=73540397-d5d0-4c35-98dc-eef53bc6a961&collectionLayerId=4ff72f89-7d1b-4bd6-9656-12dd16bd6665&present=true&preview=false&sha=5c1075fc981b18c245df481e633585c7364cfa0b)
* Telemetry events added to help us ensure the QR code pairing flow is working for people and has a higher completion rate than the email sign in flow (confirm new events with data team)
  * Event to determine that QR code pairing is successful

**Comment by SimonBasca** [comment]
Verified fix on 26.0 (18036). [Tests](https://testrail.stage.mozaws.net/index.php?/tests/view/2587052&group_by=cases:section_id&group_order=asc&group_id=4381) executed and passed
