### ISSUE TITLE
FXIOS-397 ⁃ [META] Glean

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-ios#6517]
**Vision**

Glean is used to capture events within FF for iOS

**Why**

Switching to Glean will move us off the legacy Telemetry client and bring us in line with what other products are using across Mozilla. This means our data is better maintained and we can take advantage of the new features including automated dashboards (GUD) and automated documentation

**Tickets**

[ ] #6259 
[ ] #6515 
[ ] #6516
[ ] #6518

**Comment by data-sync-user** [comment]
➤ Ashley Thomas commented:

Closing as this will now be tracked in Jira epic
