### ISSUE TITLE
play.google.com - Unable to buy videos 

### ISSUE THREAD

**Issue by karlcow** [mozilla-mobile/firefox-ios#6528]
## Steps to reproduce
1. Go to https://play.google.com (logged in/payment info set through bank credit card)
2. Select a video
3. Try to buy it.

### Expected behavior
redirected to the 3d secure auth page of the bank.

### Actual behavior
Get a blank page.

### Device & build information
* Device: iOS 13.3.1
* Build version: Firefox iOS 24.1

### Notes
1. Working with Safari
2. https://github.com/webcompat/web-bugs/issues/52225

**Comment by dnarcese** [comment]
Need to investigate what is causing this and make sure it isn't affecting other sites as well.

**Comment by karlcow** [comment]
@magsout more questions about the issue you reported on webcompat. 😁

**Comment by magsout** [comment]
@dnarcese I don’t have an iPad. I get this issue on iPhone. What does ETP mean?

**Comment by magsout** [comment]
@dnarcese if needed I can test on other websites with 3D secure.

**Comment by karlcow** [comment]
@magsout ETP = Enhanced Tracking Protection

**Comment by magsout** [comment]
@karlcow thanks.

then, I tried with and without ETP and everything is working now.  so maybe a temporary bug? 

anyway, thanks.
