### ISSUE TITLE
FXIOS-405 ⁃ Blank tab is displayed after opening a link via external app without https/http (e.g. Telegram)

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#6530]
###  Steps to reproduce:

Set Firefox as the default browser in another app's settings (telegram, feedly, etc) then tap a link which has omitted the http/https (e.g. "google.com")

### Actual results:

- A blank tab is displayed.

Expected results:

- The webpage should load.

### Device & build information
* Device: iPhone Xr (13.4.1)
* Build version: 25.0 (17803)
### Notes
- Opening "https://google.com" will open Safari regardless of the selected browser in Telegram.
Attachments: 
- https://bugzilla.mozilla.org/show_bug.cgi?id=1633633

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2390)

**Comment by brandoncote** [comment]
I was the original bugzilla submitter and while most of the above info is correct, I don't understand the above note which says "Opening https://google.com will open Safari regardless of the selected browser in Telegram."

This isn't the case for me (I just tested to be sure) and I never included anything like that in my bugzilla submission.

**Comment by SimonBasca** [comment]
@brandoncote the added note was a behavior I noticed.

Correcting my note:
Typing "Https://yahoo.com" and tapping on the link will open Safari.
Typing "https://yahoo.com" and tapping on the link will open Firefox.

Can you confirm this @brandoncote ?

**Comment by brandoncote** [comment]
> @brandoncote the added note was a behavior I noticed.
> 
> 
> 
> Correcting my note:
> 
> Typing "Https://yahoo.com" and tapping on the link will open Safari.
> 
> Typing "https://yahoo.com" and tapping on the link will open Firefox.
> 
> 
> 
> Can you confirm this @brandoncote ?

Oh I see now. Yes, telegram doesn't always respect its own default browser setting when the url begins with an uppercase "H".  How odd.
