### ISSUE TITLE
Product detail webpage is not updated

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#6531]
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.113 Safari/537.36

Actual results:

https://product-details.mozilla.org/1.0/mobile_versions.json has the iOS version listed as 12.1 and the current version should be 24.1.
Is there any chance this can get updated and remain a reliable source to retrieve the latest version number for iOS?

Atachments: 
https://bugzilla.mozilla.org/show_bug.cgi?id=1632749

**Comment by ranasr** [comment]
Hi,
Any update on this?
Thanks

**Comment by ranasr** [comment]
Thanks team!
Will this continue to be updated in the future?
We rely on this data to verify the latest iOS version and it would be really helpful if this is consistently updated.

Cheers

**Comment by jevans-mozilla** [comment]
Will be handled by release management in following bug:
https://bugzilla.mozilla.org/show_bug.cgi?id=1643121

**Comment by jevans-mozilla** [comment]
@ranasr Ongoing solution tracked on bugzilla, closing this for now.
