### ISSUE TITLE
Automated Testing for QR Code Pairing

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-ios#6533]
Automated tests in place to ensure QR code pairing does not break in future releases

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2391)

**Comment by isabelrios** [comment]
See issue https://github.com/mozilla-mobile/firefox-ios/issues/6506 for more info

**Comment by SimonBasca** [comment]
From what I investigated and the discussion here (https://stackoverflow.com/questions/25486080/how-to-access-ios-simulator-camera) it is not possible to access the camera in simulator and thus  cannot access the QR Scanner without adding extra code to tap in the camera. (http://zacstewart.com/2018/10/09/mocking-the-isight-camera-in-the-ios-simulator.html.)

I'll take a closer look once the code for #6506 lands.

**Comment by isabelrios** [comment]
Investigating a few more options: https://iosexample.com/mock-uiimagepickercontroller-for-testing-camera-based-ui-in-simulator/

**Comment by lmarceau** [comment]
Since only `data-sync-user` has commented on the issue after the `Stalebot` GitHub action (which triggered the removal of the `stale` label) I’ll close this issue for now. Please let us know if you think this issue needs to be reopened, we'll gladly do so. Thank you!
