### ISSUE TITLE
FXIOS-409 ⁃ [RTL] Intro tour needs to follow RTL rules

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#6537]
Note: the indicator is OK but swiping is NOT.

![image](https://user-images.githubusercontent.com/32130829/81167253-97f0ce80-8f9d-11ea-98b2-90fa841b197f.png)

Via: https://bugzilla.mozilla.org/show_bug.cgi?id=1271051

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2392)

**Comment by ItielMaN** [comment]
I'm not sure if this is relevant anymore, I can't see this UI in action.

**Comment by lmarceau** [comment]
Closing since onboarding isn't swappable anymore
