### ISSUE TITLE
[RTL] Top Tab Support

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#6539]
Properly support RTL for TopTabs.

![Screen Shot 2020-05-06 at 2 10 29 PM](https://user-images.githubusercontent.com/32130829/81170470-6c70e280-8fa3-11ea-96bd-2e1fcce991de.png)

Via : https://bugzilla.mozilla.org/show_bug.cgi?id=1443133

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2394)

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verifying as fix on 9000 (8950).
