### ISSUE TITLE
Can't switch to global sync service after 25.0

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-ios#6550]
A number of concerns from users have come up regarding the global sync service in v25
* can not switch to global sync service after 25.0
* Version 25.0 cannot switch to global synchronization service, although the "use local service" switch has been turned off.
* I can not switch to global sync service after 25.0 though I have turned off the "local sync service" switch
* can NOT switch to global service (standard service) after disable the local service option on V25.0.

**Comment by bli-mozbj** [comment]
1. Install v25.1(17865)
2. Goto  Settings, and turn off the "use local service" switch.
3. Open the Login page
  ==> It's the global synchronization service, which is the rgiht behavior.
4. Exit Firefox and kill the browser thread in background.
5. Launch Firefox again
6. Goto Settings
  ==> The "use local service" switch is turned off, which is correct.

7. Open the login page
  ==> It's the China-hosted synchronization service, which is **NOT** right.

8. Turn on and then turn off the "use local service" switch
9. Open the login page
   ==> It's the global synchronization service, which is the rgiht behavior.

**Comment by garvankeeley** [comment]
Thanks for testing that! I can't reproduce that bug so far, I'll keep trying
![china-server](https://user-images.githubusercontent.com/5495083/81415360-59325400-9116-11ea-85e4-018c765dab39.gif)

**Comment by garvankeeley** [comment]
@bli-mozbj can you try again on the new beta (17881) and see if it is fixed? thanks!

**Comment by garvankeeley** [comment]
@csuciu @SimonBasca can you try repro? Thanks

**Comment by bli-mozbj** [comment]
Fixed on v25.1 (17881).

**Comment by SimonBasca** [comment]
Confirming that this is working as expected on v25.1 (17881).
