### ISSUE TITLE
FXIOS-421 ⁃ "Tap to begin" receiving multiple tabs

### ISSUE THREAD

**Issue by eoger** [mozilla-mobile/firefox-ios#6552]
What I did:

- Send 6 tabs (using CMD+click on macOS) to my iPhone.
- Got all "Tap to begin" notifications on my phone.

I believe this is the cause: https://sentry-fm.prod.mozaws.net/mozilla/firefox-ios-v250/issues/282222/?query=app.device%3A%22c78c312590e17d0bdbeee1e347d3f2922aff8613%22

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2404)

**Comment by athomasmoz** [comment]
Not reproducible. Marking as lower priority until we hear any other reports or can reproduce

**Comment by eoger** [comment]
Should be reproducible if you try sending multiple tabs on Desktop, using Cmd+Click to select multiple tabs.
