### ISSUE TITLE
[Chronological Tabs] Tab Ordering & Grouping - Data side

### ISSUE THREAD

**Issue by dnarcese** [mozilla-mobile/firefox-ios#6553]
Extend the ViewModel so that the data is structured into sections - Today, Yesterday, Last Week, Older. 

----

**Acceptance Criteria**
* The ViewModel receives the tab data and orders based on last used time into sections
   * today, yesterday, last week, older
* each section is allowed to be empty 
   *  If a user doesn't have tabs in one of the timeframe groupings it is not shown. For example, if they have no tabs from today, they will not see a "Today" section)
* Changes are not visible to the user in next release (on a feature branch)
* For MVP, the new tab experience will replace the old one for iPhone/iPod users (not iPad)

**Comment by dnarcese** [comment]
For QA: 
Please test
- Selected tab moves to the top of the list
- New tabs add to the top of the list
- Section header disappears if no tabs open in that section
- Ordering and grouping persists when closing and opening the app
- Delete all tabs, open new tab, close tab (swiping and long pressing on tab is not implemented)


Known issues:
- Private tabs not implemented yet (they will be mixed in with the normal tabs)
- On devices not on iOS 13, the view will not be dismissible by swiping down (we will be adding a Close button next)
- This beta is only in English

**Comment by csuciu** [comment]
Testing in progress, thanks for the details @dnarcese.

**Comment by SimonBasca** [comment]
Verified fix on branch "chronological-tabs 5f69dc6562": 

Selected tab moves to the top of the list
New tabs add to the top of the list
Section header disappears if no tabs open in that section
Ordering and grouping persists when closing and opening the app
