### ISSUE TITLE
China sync service: always show toggle to use global server

### ISSUE THREAD

**Issue by garvankeeley** [mozilla-mobile/firefox-ios#6559]
The toggle switch in settings to use the non-china server only shows up when not signed in to the account, so there is no way to see (AFAIK) what that setting is set to. I find this extremely confusing.

It should show at all times, and if toggled while signed-in, show a dialog:

"Changing the server requires signing out of your account, proceed? Ok/Cancel"

**Comment by garvankeeley** [comment]
IMO UX isn't needed here as the work required is straightforward. If we want to do a different UX ticket to rethink this settings UI we should separate that out.

**Comment by garvankeeley** [comment]
I suspect without this, the server might be switching under-the-hood and breaking sync, and there is no way for the users to verify that this setting is set correctly.

**Comment by SimonBasca** [comment]
Verified fix on 26.0 (18036). [Tests](https://testrail.stage.mozaws.net/index.php?/runs/view/29908&group_by=cases:section_id&group_order=asc)executed and passed.
