### ISSUE TITLE
Download snack bar missbehaves after steps

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#6561]
## Steps to reproduce
1. Go to speed.hetzner.de
2. Tap on "100MB.bin"
3. Tap "Download" 
4. Lock the device
5. Unlock the device
6. Tap "x" icon on the download snack bar
7. Tap "Cancel"
8.  Tap on "100MB.bin" to download the file
9. Tap "Download" 
### Expected behavior
- The download snack bar should 
### Actual behavior
- The download will resume from the canceled progress but will exceed the download limit in the snackbar.
- When the download will finished, I received a "Download fail" message but the file was downloaded in Library.
### Device & build information
* Device: iPhone Xr 
* Build version: 25.0 (17861)
### Notes
- After step 7) downloading a different file will cause the snackbar to misbehave.
- After restarting the app the snackbar will work as expected. 
- Also reproducible on v24.0.
Attachments: 
- VIdeo: 
[Untitled.mov.zip](https://github.com/mozilla-mobile/firefox-ios/files/4592868/Untitled.mov.zip)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2405)

**Comment by lmarceau** [comment]
Since only `data-sync-user` has commented on the issue after the `Stalebot` GitHub action (which triggered the removal of the `stale` label) I’ll close this issue for now. Please let us know if you think this issue needs to be reopened, we'll gladly do so. Thank you!
