### ISSUE TITLE
Send tab is not working after disconnecting device via Account Management page but will work after restarting the app

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#6562]
## Preconditions
1. Log in to FxA on device A.
2. Login to FxA on device B.
3. On device B, go to Account Management Page -> Devices & App, and tap "Disconnect" for the current device.
4. Log in to FxA on device A.

## Steps to reproduce
1. On device A, go to "github.com".
2. Open Page Action Menu.
3. Tap "Send to device"
4. Select device B from the list

### Expected behavior
- Tab should be sent across iOS devices
### Actual behavior
- Tab is not sent. After restarting the app on device B, the tab will be sent.

### Device & build information
* Device A : iPhone SE (11.4.1)
* Device B : iPhone 7 (13.4)
* Build version: 25.0 (17861)
### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2406)

**Comment by athomasmoz** [comment]
@SimonBasca sync team couldn't reproduce this. There was also some confusion over the steps to reproduce. If you have disconnected device A, then there shouldn't be an option to send tab to device B. Is that the bug?

**Comment by SimonBasca** [comment]
@athomasmoz Sorry for the confusion. There seems to be a mistake in step 4). 

Correcting step 4): Log in to FxA on device A. I am also correcting this step in the description

**Comment by lmarceau** [comment]
Since only `data-sync-user` has commented on the issue after the `Stalebot` GitHub action (which triggered the removal of the `stale` label) I’ll close this issue for now. Please let us know if you think this issue needs to be reopened, we'll gladly do so. Thank you!
