### ISSUE TITLE
Test that Glean data is being sent correctly

### ISSUE THREAD

**Issue by kaylagalway** [mozilla-mobile/firefox-ios#6563]
Vision

After a couple of weeks of data collection, we have to test that Glean events are coming in correctly

Background

After Glean is added to Firefox, we will need to release a beta release so that data events can be sent from the application.  After at least a couple of weeks worth of data collection, we need to review that everything is being sent correctly. 

This step will be done after these tickets are complete:
https://github.com/mozilla-mobile/firefox-ios/issues/6516
https://github.com/mozilla-mobile/firefox-ios/issues/6518
https://github.com/mozilla-mobile/firefox-ios/issues/6515

Acceptance Criteria

- All data events are being sent through Glean correctly

**Comment by jevans-mozilla** [comment]
During this ticket, could we check in with the Glean binary size.  Initial reports are that the Glean library is taking up to 10% of the FF binary size.
