### ISSUE TITLE
"Send to device" in Share menu not working for some apps

### ISSUE THREAD

**Issue by joachimesque** [mozilla-mobile/firefox-ios#6580]
## Steps to reproduce

- Have Firefox for iOS on iOS device, logged in with FxA
- Have Firefox on macOS desktop computer, logged in with FxA
- Case 1, on iOS:
    * Open Safari
    * tap on Share icon
    * tap on iOS Firefox icon in the menu
    * tap "Send to device" in the Firefox for iOS menu ("Envoyer à l'appareil" in French)
    * tap on your desktop device name
    -> the link is sent to Firefox on the desktop computer
- Case 2, on iOS:
    * Open any other app (Slack, Tweetbot…)
    * press on a link to make the app menu appear
    * tap "Share…"
    * tap on iOS Firefox icon in the Share menu
    * tap "Send to device" in the Firefox for iOS menu ("Envoyer à l'appareil" in French)
    * tap on your desktop device name
    -> the link is ***not*** sent to Firefox on the Desktop computer

### Expected behavior

The link should be sent to Firefox on the desktop computer when shared from any app

### Actual behavior

The link is sent when shared from Safari or Firefox for iOS (Case 1) but not when shared from any other app (Case 2)

### Device & build information
* Device: iPhone SE
* Build version: Version 25.0 (17803)

### Notes
This bug appeared recently, perhaps starting at version 25.

Along whit this bug, I noticed some delay in the refreshing of the menu listing all devices, when sharing a link.

**Comment by mems** [comment]
I have this issue with Twitter: try to share a tweet link directly in Twitter doesn't work, but open the link in Safari first (Twitter tweet : Share link > Open in Safari) then share the link

**Comment by SimonBasca** [comment]
This should be fixed by #6670 in the next release. Closing for now
