### ISSUE TITLE
 Firefox on ios no longer imports certificates

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#6583]
User Agent: Mozilla/5.0 (X11; Linux x86_64; rv:75.0) Gecko/20100101 Firefox/75.0

Steps to reproduce:

Firefox on iOS used to be able to import .p12 or .pem certificates. Version 25 no longer does.

Actual results:

You get an option to download the cert but not to import it. Opening the downloaded file in Firefox gives only a blank screen.

Expected results:

Should give you the option to install the cert.

Via : https://bugzilla.mozilla.org/show_bug.cgi?id=1636018

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2414)

**Comment by lmarceau** [comment]
Since only `data-sync-user` has commented on the issue after the `Stalebot` GitHub action (which triggered the removal of the `stale` label) I’ll close this issue for now. Please let us know if you think this issue needs to be reopened, we'll gladly do so. Thank you!
