### ISSUE TITLE
Battery consumption is high when using Firefox.

### ISSUE THREAD

**Issue by snz2** [mozilla-mobile/firefox-ios#6584]
Battery consumption is high when using Firefox.

Comparison App: Safari
Tested:

1. Tracking on / off
1. Pop-up block on / off
1. firefox sync on / off

Firefox and Safari have been tested multiple times on the same website for a long time.

Safari 1 hour average consumption 15 ~ 20%
Firefox 1 hour average consumption 40-60%

I think this has some problems.

Suddenly, a situation in which 20 percent is reduced in 10 minutes also occurs and the phone becomes very hot. When using Firefox. Safari has no symptoms at all in the same environment. I'm a Firefox fan for over 20 years and I'm seriously worried about the mobile battery issue ...

If there is no progress, I will move this issue to Bugzilla.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2415)

**Comment by garvankeeley** [comment]
agreed on this, related to
https://github.com/mozilla-mobile/firefox-ios/issues/6487
https://github.com/mozilla-mobile/firefox-ios/issues/6612

**Comment by vectro** [comment]
I am experiencing this issue.

However, I don’t see it when the phone is on Low Power Mode. I have no idea why that might be though.

**Comment by nasiralamreeki** [comment]
Firefox for iOS is the top battery consuming app on my phone and most of that's background activity.

**Comment by John-Polo** [comment]
I have a similar problem, but it doesn't seem to be background, it's when it's running on screen. If I watch 20 minutes of youtube, my battery charge drops 20%. If do a bunch of surfing and scrolling over a couple of minutes, the charges drops 1 or 2%. I'm using the latest versions of Firefox and Firefox Focus and in Focus, the youtube viewing also depletes battery quickly.
