### ISSUE TITLE
UTMs not being passed into Amplitude from Leanplum campaign

### ISSUE THREAD

**Issue by isa-mobile** [mozilla-mobile/firefox-ios#6590]
## Steps to reproduce
Generate test campaign from Leanplum with deeplink to FxA signup flow. 
Deeplink should have appended UTM parameters.

Some test campaigns were sent on the week of May 3rd. Here are the links:
https://www.leanplum.com/dashboard2/5432682399399936/composer/914975608/summary
https://www.leanplum.com/dashboard2/5432682399399936/composer/917045045/summary

### Expected behavior
After clicking on the In App banner, the user lands on the FxA Sign Up page, creates an account and the utms should make sure this conversion is correctly attributed to the campaign, in Amplitude.
![Screenshot 2020-04-23 at 12 01 16](https://user-images.githubusercontent.com/65237974/81712580-0db0da80-9475-11ea-8cba-abded6255f3d.png)

### Actual behavior
When checking Amplitude, we notice a huge discrepancy between numbers there and on Leanplum. As numbers on Amplitude are extremely low, there's a high probabilty that the UTMs are not being passed correctly.

### Device & build information
This campaign was sent in the release app, to highly active users, fwith a diverse range of device models and builds. 

### Notes
Attachments: 
The issue is documented here: https://docs.google.com/document/d/1SPZQYgbbp1j7tRp4QGHlFA7cCC3bQlTCCbB5waekzTg/edit#.

**Comment by athomasmoz** [comment]
Had a similar issue in #5492 which was sent to FxA. Need to determine if this is something we can fix or on the FxA side. First step is to check that
