### ISSUE TITLE
[glean] increases binary size by 10%, increased startup time, make it static lib

### ISSUE THREAD

**Issue by garvankeeley** [mozilla-mobile/firefox-ios#6598]
The startup time is the priority issue.  Related to #6915 

x-ref to https://github.com/mozilla/glean/issues/878

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2419)

**Comment by garvankeeley** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1637539

**Comment by lmarceau** [comment]
Since only `data-sync-user` has commented on the issue after the `Stalebot` GitHub action (which triggered the removal of the `stale` label) I’ll close this issue for now. Please let us know if you think this issue needs to be reopened, we'll gladly do so. Thank you!
