### ISSUE TITLE
Ensure password prompt modal matches the current tab

### ISSUE THREAD

**Issue by garvankeeley** [mozilla-mobile/firefox-ios#6602]
Moved from https://bugzilla.mozilla.org/show_bug.cgi?id=1631071

This is the Firefox for iOS version of bug 791594 since it will certainly need its own fix

+++ This bug was initially created as a clone of Bug #791594 +++

Demo: http://lcamtuf.coredump.cx/authspoof/

You show a window-modal HTTP auth prompt visually tied to a particular tab before updating the address bar. This can have bad consequences when somebody navigates a trustworthy window to a malicious location. This seems rather undesirable.

Possible fix: update the address bar and hide the original document before showing the prompt?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2420)

**Comment by lmarceau** [comment]
Since only `data-sync-user` has commented on the issue after the `Stalebot` GitHub action (which triggered the removal of the `stale` label) I’ll close this issue for now. Please let us know if you think this issue needs to be reopened, we'll gladly do so. Thank you!
