### ISSUE TITLE
Viewed images do not properly scale: should not maximize width

### ISSUE THREAD

**Issue by csuciu** [mozilla-mobile/firefox-ios#6608]
Steps to reproduce:

```
View the image at this URL: http://caseyconnor.org/pub/image/800x1600.png
rotate phone in to landscape mode
observe that image is scaled to the full width of the screen
using a two-fingered zoom, shrink the size of the image
observe that the image is forced to be the full width of the screen
```

Actual results:

By forcing the use of the full width, this prevents the user from including more vertical content of the image.

Attached are demonstration screen captures:

img1 -- the image in vertical mode
img2 -- the image after phone is rotated (the scroll is not at the top of the image; not sure if that's a bug in itself)
img3 -- the image after scrolling to the top of the image
img4 -- the image in the middle of a two-fingered zoom -- this is where it should stay, but instead it immediately returns to the img3 state after the zoom is released.

Expected results:

The image should not be force scaled to the full width of the screen if the user has intentionally scaled it themselves: it contradicts a clear intention of the user and only serves to frustrate.

The use-case for me: I sometimes read sheet music from the phone, and it is often more readable in landscape mode, but often requires a slight shrinking of the image to fit more of the music on the screen. This is made impossible by this behavior, which frequently makes a suitable presentation of the image impossible.

Originally reported here: https://bugzilla.mozilla.org/show_bug.cgi?id=1637436

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2423)

**Comment by chconnor** [comment]
Still happening (tested on iPad (FF 36) and iPhone (earlier version) -- I don't have more recent devices to test on).
