### ISSUE TITLE
FXIOS-448 ⁃ [Investigation] Evaluate L10N box as part of CI process

### ISSUE THREAD

**Issue by jevans-mozilla** [mozilla-mobile/firefox-ios#6609]
Right now we have a system that is dedicated to providing L10N translations.

This investigation would be to identify: 
- how to access the server
- evaluate OS version + Upgrade frequency
- evaluate Xcode version + Upgrade frequency
- Is the system part of a backup process
- What would be the emergency contact if the system goes down
- Are the scripts functioning properly
- Do we have team expertise to update scripts?

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-448)

**Comment by athomasmoz** [comment]
First step is to determine why we have custom l10n scripts

**Comment by garvankeeley** [comment]
https://github.com/mozilla-mobile/firefox-ios/wiki/String-Export---l10n

**Comment by data-sync-user** [comment]
➤ Ashley Thomas commented:

Hey [~jboek@mozilla.com] is this investigation completed?
