### ISSUE TITLE
Tracking Protection TabContentBlocker URL.publicSuffixFromHost perf problem

### ISSUE THREAD

**Issue by garvankeeley** [mozilla-mobile/firefox-ios#6612]
One of the top battery gobblers in the energy consumption report is this, is a bug, this _should_ be near-zero impact

![](https://user-images.githubusercontent.com/5495083/81972694-f8f95180-95f0-11ea-9645-22be10e9617e.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2424)

**Comment by garvankeeley** [comment]
A circular buffer of recent lookups could drop this to zero-cost:
<img width="253" alt="image" src="https://user-images.githubusercontent.com/5495083/81973939-de27dc80-95f2-11ea-9a6f-c6d6c3667677.png">

**Comment by nasiralamreeki** [comment]
Any action on this?
