### ISSUE TITLE
Latest master a34ba81f524 does not start

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#6615]
## Steps to reproduce
1. Install latest master a34ba81f524 on device
2. Launch master a34ba81f524

### Device & build information
* Device: iPhone Xr
* Build version: a34ba81f524

![Screen Shot 2020-05-15 at 2 51 06 PM](https://user-images.githubusercontent.com/32130829/82047461-8c975480-96bb-11ea-842b-0adcd69db1f8.png)

**Comment by nbhasin2** [comment]
Basically we are relying on Leanplum to Start and show onboarding screen. In debug mode unless you have Leanplum setup locally to start it will show white screen. I'll add a debug mode to help cope with white screen issue. 

P.S. It won't happen in Production as we always start Leanplum and are also handling case where there is no internet connection.

**Comment by isabelrios** [comment]
Automated tests are affected by this issue too @nbhasin2 . In the XCUI we bypass this screen and only 5 are affected but all UI that have to go trough the UI onboarding are affected...

**Comment by SimonBasca** [comment]
Verified fix on 1665a1c9.
