### ISSUE TITLE
FXIOS-455 ⁃  URL bar should be moveable to bottom on Firefox for iOS

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#6621]
Steps to reproduce:

Launch Firefox for iOS
Try to reach the URL Bar with one hand
Try to find a setting to move the URL bar to the bottom

Actual results:

I could not reach the URL bar comfortably
There was no setting to move it to the bottom

Expected results:

Considering how tall iPhones have gotten, there should be a setting to move the URL bar to the bottom, just like on Firefox for Android.

Feature request from : https://bugzilla.mozilla.org/show_bug.cgi?id=1638543

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2428)

**Comment by athomasmoz** [comment]
@brampitoyo see bugzilla link for input from user (related to #5912)

**Comment by GeckoEidechse** [comment]
With Fenix (which has the URL bar at the bottom by default) now having rolled out fully on Android I think it's time to consider this issue again. The search button added with the `28.0` release was a nice addition but I'd say it would make sense to add the option of moving the URL bar to ensure a consistent UI between the iOS and Android version of Firefox.

**Comment by drearyworlds** [comment]
I would very much like this. Especially with the newest iPhones screen sizes being enormous, one handed use is almost impossible.

**Comment by athomasmoz** [comment]
Thank you for the feedback. Leaving this ticket open as the bottom nav bar feature is still under consideration. In the meantime, I want to share a few changes coming out to avoid reaching across the screen with your thumb:
* #6918 will focus the URL bar and popup the keyboard any time a new tab is opened, removing the step of clicking on the URL bar
* #6846 adds a button on the bottom nav that will focus the URL bar and pop up the keyboard on a new tab page

**Comment by Uffje** [comment]
@athomasmoz those additions you mentioned are not very useful, I think. I find myself more often needing the urlbar when I am actually in an existing webpage and want to change to another webpage (without having a new tab or deleting the current one). Even if there was a search icon in the bottom in existing pages, my I is drawn to the urlbar and probably will be trying to reach it there anyway, instead of the icon in the bottom.

**Comment by AkashKrDutta** [comment]
Would very much appreciate this feature. That is a game changer for me at least.

**Comment by brampitoyo** [comment]
Posting a very early, alpha exploration of bottom-oriented address bar on two scenarios:

- While viewing websites
- While searching or entering address

Keep in mind that everything might – and will probably – change. But these explorations give a rough an idea of how a bottom-oriented address bar might coexist alongside a navigation bar (which is also bottom-oriented).

### While viewing websites

| Light theme | Dark theme |
| --- | --- |
| <img width="375" alt="Light@2x" src="https://user-images.githubusercontent.com/51007/97830346-7fd1f000-1d31-11eb-8303-778aa681f183.png"> | <img width="375" alt="Dark@2x" src="https://user-images.githubusercontent.com/51007/97830348-81031d00-1d31-11eb-8be7-ec29084c543c.png"> |

### While searching or entering address

| Light theme | Dark theme |
| --- | --- |
| <img width="375" alt="Light@2x" src="https://user-images.githubusercontent.com/51007/97830384-a4c66300-1d31-11eb-8dfc-a8f7a65ef662.png"> | <img width="375" alt="Dark@2x" src="https://user-images.githubusercontent.com/51007/97830386-a5f79000-1d31-11eb-846f-f639eb4dca0d.png"> |

**Comment by Uffje** [comment]
@brampitoyo this looks already amazing and would work great. On android on the other hand it is kind of baked together. The arrow keys in my opinion are not very necessary as one can swipe back and forth (this might be important for those who don’t know about swiping, on the other hand android doesn’t have them either) and I like how on android it is taking up less space. 

None the less, happy to see you are working on this!

**Comment by johncatral** [comment]
Any updates on this?  I had to switch to an iPhone for work and was using Firefox mobile on Android where the URL/address bar at the bottom.  It was very useful down on the bottom that I was surprised that Firefox on iOS didn't have this feature, too. :(

**Comment by athomasmoz** [comment]
Thanks for the feedback and for following up. The work is currently in design - we have a few enhancements to the design based on learnings from trying it on Firefox on Android.

**Comment by Duckbilled** [comment]
@athomasmoz can we find this in the project section to follow it and do you have a vague projection? 

I understand it might take a while, but really looking forward to it. Great to see you update here as well!

**Comment by GeckoEidechse** [comment]
With iOS15 [Safari will gain the ability to move the URL bar to the bottom of the screen](https://9to5mac.com/2021/08/18/change-ios-15-safari-address-search-bar-iphone/).

Just alone for parity reasons this feature should be given more consideration.

**Comment by DarrienG** [comment]
Now that refresh is in the URL bar with the latest update, this would be better than ever. Having to reach all the way up to the top of the screen when wanting to refresh is very frustrating.

**Comment by GeckoEidechse** [comment]
I highly recommend the Firefox iOS team to give Safari on iOS 15 a try. With bottom URL bar and its benefits like easy to reach controls and dependent features like swiping the URL bar left/right to switch tabs or up to see the tab overview, Safari has achieved a leap in speeding up workflows.

I hope to see Firefox on iOS follow suite soon as well <3

**Comment by dnarcese** [comment]
tracking on #9422

**Comment by Dennismn** [comment]
The address bar for the normal FF app is at the bottom, but this one remain on top. Makes it awkward to use especially as most popular browsers have the option to move the address bar.

**Comment by lmarceau** [comment]
@Dennismn there's an option in the settings to move the URL bar to your preference (either top or bottom).

**Comment by Dennismn** [comment]
> @Dennismn there's an option in the settings to move the URL bar to your preference (either top or bottom).

Sorry I thought this was the thread for Firefox Focus. Which remains at the top and there's no option to change it.

**Comment by lmarceau** [comment]
@Dennismn no problem, you can open a feature request on the Focus GitHub [here](https://github.com/mozilla-mobile/focus-ios/issues/new/choose) if you wish to!

**Comment by saralilyb** [comment]
> @Dennismn there's an option in the settings to move the URL bar to your preference (either top or bottom).

This is not present in the latest Firefox on iPadOS in the App Store at the time of this posting.

**Comment by gattillynx** [comment]
There is still no option on iPadOS as of time of posting.
