### ISSUE TITLE
Investigation: Beta for specific group

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-ios#6631]
**Vision**

We have determined how to get a beta build for chronological tabs out to a select group without sending to the full beta audience

**Acceptance Criteria**

* Need to be able to send to external folks for diary study
* Need to be able to share with internal folks (eng + QA + UX) for extra testing

**Comment by dnarcese** [comment]
We are able to create a group of testers on TestFlight and then add anyone to it. We can then send a build to just that group and our internal testers. It should also create a public link to make it easy to install (for diary studies).
