### ISSUE TITLE
Breach Alerts Logic Spike

### ISSUE THREAD

**Issue by vphong** [mozilla-mobile/firefox-ios#6642]
To add Monitor support to the Firefox iOS app, i.e. alert a signed in user that their password(s) have been breached, we must:

## Backend Spike
- We will have to query breach list 
- We will have to compare user's local passwords to breach list
- We will have to notify the user that they have been breached

**Comment by vphong** [comment]
Current tickets resulting from this spike:
#6643 #6644

**Comment by vphong** [comment]
Here is the spike for the UI and design portions of this feature:
#6645

**Comment by kaylagalway** [comment]
More tickets created related to this spike: 
Testing BreachAlertsManager: #6705 
Refactor LoginsViewController to MVVM: #6706
