### ISSUE TITLE
Send to Device from share extension not working

### ISSUE THREAD

**Issue by eoger** [mozilla-mobile/firefox-ios#6647]
## Steps to reproduce

1. Install the [Hackers for Hacker News](https://apps.apple.com/gb/app/hackers-for-hacker-news/id603503901) app.
2. Click on any article (should bring the Comments view).
3. On the top right of the view, click the [Share icon](https://is4-ssl.mzstatic.com/image/thumb/Purple113/v4/e9/79/40/e97940f7-94b5-125f-7206-0bc05cc7810a/pr_source.png/300x0w.png), choose Firefox and send the article to any device.

EDIT:[garvan] STR should be the same as open url in Safari then open share menu, choose Firefox, choose 'Send To Device'. 

### Expected behavior

A tab arrives on the other device.

### Actual behavior

The tab never arrives, note that doing Share -> Open in Firefox *then* sending the tab from there works.

**Comment by garvankeeley** [comment]
What version were you on? It is working on master when I tried it now

**Comment by eoger** [comment]
Latest Beta for me.

**Comment by garvankeeley** [comment]
This code won't wait for FxAccountManager.initialize() to complete. When the extension is first shown, it calls that, and assuming that is just a few ticks to complete, the assumption was by the time the user tapped to show the device share screen it would be complete. I'll make sure to wait for that event to complete.

**Comment by garvankeeley** [comment]
To be clear, I only ever check this in Safari, there should be no difference what parent app is used to run the app extension. Or if there is I will eat my hat.

**Comment by SimonBasca** [comment]
@garvankeeley this is working for Case 1) but fails to send the tab for Case 2).

Case 1)
1. Go to a link in Safari
2. Tap Share button -> Firefox extension -> Send Tab -> Select a device

Case 2)
1. Open Hackers for Hacker News app.
2. Tap on an article
3. Tap Share button -> Firefox extension -> Send Tab -> Select a device

Also note that trying to send a link from chrome via send tab from the Firefox extension does not populate the device list.

**Comment by SimonBasca** [comment]
I created a separate issue #6670. Feel free to close #6670 if you decide to re-open this issue.

**Comment by SimonBasca** [comment]
This is verified fixed on 26.0 (18092) for Safari. For the rest of the apps the fix will be on verified on #6670
