### ISSUE TITLE
Webview not dismissed after signing in to FxA with email credentials

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#6653]
## Steps to reproduce
1. Go to Settings -> Sing in to Sync
2. Tap "Use email"
3. Input the correct credentials
### Expected behavior
- The webview should be dismissed and the user should be logged in to FxA.
### Actual behavior
- The spinning throttle is displayed.
- The webview is not dismissed.
### Device & build information
* Device: iPhone Xr
* Build version: 26.0 (18007)
### Notes
- The flow seems correct after manually dismissing the page by tapping "Cancel" and sync seems to also be working correctly

**Comment by garvankeeley** [comment]
I see this is doing modal navigations where I would expect stack navigations to happen. Looking at it.

**Comment by garvankeeley** [comment]
Me playing with this:
https://gist.github.com/garvankeeley/f8dd632b342517a137763d7c620ca28f

**Comment by SimonBasca** [comment]
Verified fix on 26.0 (18036).
