### ISSUE TITLE
"Turn on Sync" string is missing, also instructions labels are missing in dark mode

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#6654]
## Steps to reproduce
1. Go to Settings -> Sing in to Sync
### Expected behavior
- Page should match [specs](https://app.abstract.com/share/c4d5475f-4f5e-4c4e-9bf3-1aefa06e0ce6?collectionId=73540397-d5d0-4c35-98dc-eef53bc6a961&collectionLayerId=3b61eac3-361c-4b70-b643-acabfb8ba9ee&present=true&preview=false&sha=5c1075fc981b18c245df481e633585c7364cfa0b) 
### Actual behavior
- "Turn on Sync" string is missing from the top page.

![Screen Shot 2020-05-21 at 4 54 49 PM](https://user-images.githubusercontent.com/32130829/82565911-d7194500-9b83-11ea-96f5-487b50eda0d5.png)

**Comment by garvankeeley** [comment]
I see this in dark mode
![Screenshot 2020-05-21 at 10 45 01 AM](https://user-images.githubusercontent.com/5495083/82581478-a1ae3080-9b5e-11ea-9af1-38cf45140597.png)

**Comment by SimonBasca** [comment]
Verified fix on 26.0 (18036) for both light and dark mode.
