### ISSUE TITLE
FxA signin navigation: QR/email VCs should have back and close buttons

### ISSUE THREAD

**Issue by garvankeeley** [mozilla-mobile/firefox-ios#6658]
FirefoxAccountSignInViewController (the Sign in to FxA dialog) is used to show an initial screen that then allows navigation to QR code signin or Email signin. The bug is that these are (1) not consistently push+pop navigation and (2) the title bar buttons are not correct.

Expected:
- FirefoxAccountSignInViewController uses push navigation to children (QR and email login)
- Children have this in the navigation title bar: `<Back          Close`. Left bar button is back, right bar button is close.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2432)

**Comment by data-sync-user** [comment]
➤ Tiffanie Shakespeare commented:

the UI has been redesigned and I don’t see this issue any more. please re-open and provide screenshots if you’re still encountering it. thanks!
