### ISSUE TITLE
FXIOS-465 ⁃ FxA web view memory leak

### ISSUE THREAD

**Issue by garvankeeley** [mozilla-mobile/firefox-ios#6662]
I see this webview being leaked when debugging (attaching to the webview with Safari).

<img width="756" alt="image" src="https://user-images.githubusercontent.com/5495083/82590379-99a8bd80-9b6b-11ea-8e3f-5410a36822a0.png">

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-465)

**Comment by kaylagalway** [comment]
@garvankeeley Just locally checked out the commit on master before my QR code work was merged and opened the memory graph debugger, and it seems this view controller was leaking before those changes. I'm still going to try to figure out where it is coming from, but for now it seems to me like this is not a regression.

**Comment by tsuiyuenhong** [comment]
Hi, @garvankeeley. I found that FxAWebViewController exists a memory leak.

```self -> webview -> configuration -> userContentController -> self```

**Comment by garvankeeley** [comment]
Nice find!

**Comment by tsuiyuenhong** [comment]
> Nice find! Do you want me to assign the bug to you?

OK, I have created a PR -> https://github.com/mozilla-mobile/firefox-ios/pull/7071
