### ISSUE TITLE
A/B Test New Onboarding Cards don't respect theme

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#6668]
## Steps to reproduce
1. Change the theme from Light to Dark by tapping on the "Enable Night mode button"
2. Tap on Show Tour in the settings -> The theme is Light the onboarding
3. Restart the app
4. Tap on Show Tour in the settings -> The text is not visible (see screenshot)
### Expected behavior
- Theming should be respected on the onboarding cards
### Actual behavior
- The theme on the onboarding is not correct and also the text is not visible.

![Screen Shot 2020-05-22 at 1 31 24 PM](https://user-images.githubusercontent.com/32130829/82659927-1e5e0f00-9c32-11ea-9d56-56fdb1418c82.png)

### Device & build information
* Device: iPhone 7
* Build version: 13.4.1
### Notes
Attachments:

**Comment by athomasmoz** [comment]
I also experienced this. Opening the first onboarding screen when in dark mode, the text is not visible (this is on release version card, not the new one)
![image](https://user-images.githubusercontent.com/43346208/82704032-93791680-9c29-11ea-90eb-8ac6820518dc.png)

**Comment by SimonBasca** [comment]
@nbhasin2 I am still reproducing this issue following the exact STR from the description on both  beta and master a0849545cea. Can you please take a look and let me know if this issue needs to be re-open or should I log a new one.

**Comment by SimonBasca** [comment]
Verified fix on 26.0 (18064).
