### ISSUE TITLE
Remove "Create an account" button from sync tabs

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#6669]
## Preconditions
- Logged out of FxA
## Steps to reproduce
1. Launch Firefox
2. Go to Synced tabs
### Expected behavior
- Create account should be removed as it goes trough the same flow as "Sign in"

### Device & build information
* Device: iPhone 7
* Build version: 26.0 (18036)
### Notes
Attachments: 
![Screen Shot 2020-05-22 at 2 52 13 PM](https://user-images.githubusercontent.com/32130829/82665155-e065e880-9c3b-11ea-8764-64d258c80384.png)

**Comment by athomasmoz** [comment]
Closing as duplicate, we will address this in #6504
