### ISSUE TITLE
 Send to Device from share extension not working except Safari

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#6670]
## Steps to reproduce

1. Install the [Hackers for Hacker News](https://apps.apple.com/gb/app/hackers-for-hacker-news/id603503901) app.
2. Click on any article (should bring the Comments view).
3. On the top right of the view, click the [Share icon](https://is4-ssl.mzstatic.com/image/thumb/Purple113/v4/e9/79/40/e97940f7-94b5-125f-7206-0bc05cc7810a/pr_source.png/300x0w.png), choose Firefox and send the article to any device.

### Expected behavior

A tab arrives on the other device.

### Actual behavior

The tab never arrives, note that doing Share -> Open in Firefox *then* sending the tab from there works.

**Comment by garvankeeley** [comment]
What app version?

**Comment by SimonBasca** [comment]
Build: 26.0 (18036)
Device: iPhone 7

**Comment by SimonBasca** [comment]
Also note that trying to send a link from Chrome via send tab from the Firefox extension does not populate the device list.

**Comment by garvankeeley** [comment]
Can you check if this worked in prev version(s)?

**Comment by SimonBasca** [comment]
This was working on build 24.1 (17574).
First bad build is 25.0 (17610).

**Comment by garvankeeley** [comment]
Is a regression, so marking as high priority.

**Comment by csuciu** [comment]
Other reports of this issue:
https://bugzilla.mozilla.org/show_bug.cgi?id=1641695
https://bugzilla.mozilla.org/show_bug.cgi?id=1638897

**Comment by GeckoEidechse** [comment]
To add to this:

I have the same issue on an iPhone SE (2016) with Firefox version 26.0 (18099)

Apps tested:

* ✓ Safari: Works fine
* ✓ Firefox: Works fine (both using the sharesheet and `Send to device` directly)
* ❌ YouTube: Tab does not arrive
* ❌ Apple Mail: Tab does not arrive
* ❌ Signal: Tab does not arrive

**Comment by SimonBasca** [comment]
Verified fixed on master 59f18801. Tested for Youtube and Hackers for Hacker News.
