### ISSUE TITLE
New "Debug: Error" message shown when receiving push notifications

### ISSUE THREAD

**Issue by csuciu** [mozilla-mobile/firefox-ios#6671]
Beta v26.0 (18036)
iPhone 11 Pro (13.3)

* Send a tab from latest desktop Nightly to latest iOS Beta

Expected: The push notification is received correctly.

Actual: Most of the times, the tab does not arrive on iOS. When it does, this message is displayed:

<img width="372" alt="Screenshot 2020-05-22 at 17 30 09" src="https://user-images.githubusercontent.com/1866605/82678263-f67ea380-9c51-11ea-9c5b-82de6540f680.png">

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2433)

**Comment by garvankeeley** [comment]
This is correct, on beta we show the push error, but not on release.

**Comment by garvankeeley** [comment]
Filed to a-s: https://github.com/mozilla/application-services/issues/3145

**Comment by SimonBasca** [comment]
Similar issue #6682

**Comment by rfk** [comment]
@csuciu if you're still able to reproduce this error message, could you please try looking in the [Browser Console](https://developer.mozilla.org/en-US/docs/Tools/Browser_Console) on desktop while you're sending the tabs? I expect you should see some log messages about sending the tab, and it will either say "via FxA Commands" or "via Sync".

If you see messages about "via Sync", the that will explain the source of the strange notification text, as noted in https://github.com/mozilla/application-services/issues/3145#issuecomment-635146167.

**Comment by rfk** [comment]
> Actual: Most of the times, the tab does not arrive on iOS. When it does, this message is displayed:

Also, to clarify: when you see this debug notification, does the sent tab successfully arrive and get opened on the device?

**Comment by lmarceau** [comment]
Since only `data-sync-user` has commented on the issue after the `Stalebot` GitHub action (which triggered the removal of the `stale` label) I’ll close this issue for now. Please let us know if you think this issue needs to be reopened, we'll gladly do so. Thank you!
