### ISSUE TITLE
navigator.geolocation.getCurrentPosition not working

### ISSUE THREAD

**Issue by bastien-effetb** [mozilla-mobile/firefox-ios#6672]
## Steps to reproduce
Go on a website that uses navigator.geolocation.getCurrentPosition to request user position
For example this fiddle : https://jsfiddle.net/1m63tjs0/1/
Click "Try me"

### Expected behavior
The browser should ask for permission and if the user agrees give access to its position

### Actual behavior
No permission is asked and no position is returned, error code 1, Origin does not have permission to use Geolocation service

### Device & build information
* Device: Iphone SE (2020), ios 13.5
* Build version:

**Comment by garvankeeley** [comment]
Can't repro, check your system permissions to see if you have previously denied location access to the app..

**Comment by bastien-effetb** [comment]
I did not denied location, so that's why I opened this issue...

**Comment by SimonBasca** [comment]
@garvankeeley we also have this issue logged #6199 which might be related to this one.

**Comment by garvankeeley** [comment]
Interesting. Let's keep the earlier issue open and see if we can get STR.

**Comment by gregattraf** [comment]
Thank you, this totally solved my problem!
