### ISSUE TITLE
[Telemetry Audit] - Coreping telemetry is delaying or misrepresenting when we see the first install event from iOS

### ISSUE THREAD

**Issue by nbhasin2** [mozilla-mobile/firefox-ios#6674]
Working with Datascience it seems that the iOS Coreping is not sending events right away and there is a delay. 

This might get resolved when we full incorporate Glean. However investigation should be done to ensure that Coreping doesn't delay the events (specially for first install).

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2434)

**Comment by data-sync-user** [comment]
➤ Ashley Thomas commented:

[~tlong@mozilla.com] Do you know if this is still an issue now that we've switched to Glean?

**Comment by data-sync-user** [comment]
➤ Travis Long commented:

We still see this a little with Glean, but the timeframe is much better.  We should be seeing 1st ping from Glean from the majority of users in less than a day and most users by 7 days.  https://sql.telemetry.mozilla.org/queries/76776/source#191369 ( https://sql.telemetry.mozilla.org/queries/76776/source#191369 )

This is very similar to the first ping timings we see in Fenix with Glean: https://sql.telemetry.mozilla.org/queries/76775/source#191382 ( https://sql.telemetry.mozilla.org/queries/76775/source#191382 )

**Comment by lmarceau** [comment]
Since only `data-sync-user` has commented on the issue after the `Stalebot` GitHub action (which triggered the removal of the `stale` label) I’ll close this issue for now. Please let us know if you think this issue needs to be reopened, we'll gladly do so. Thank you!
