### ISSUE TITLE
FXIOS-25 ⁃ [Telemetry Audit] - Resolve discrepancy between events in telemetry platforms we use for iOS

### ISSUE THREAD

**Issue by nbhasin2** [mozilla-mobile/firefox-ios#6675]
**Overview**
Currently we are seeing discrepancy between events between Leanplum and our core telemetry. 

It would be best to audit the events for all platforms which we use in the iOS app and try to align the events. 

**Engineering Background**
Currently we send events to Leanplum & Amplitude dashboards.
- Leanplum events get sent through their SDK 
- Amplitude events get sent through our UnifiedTelemetry class which also deals in sending coreping events.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2435)

**Comment by garvankeeley** [comment]
Can you describe what the discrepancy is?

**Comment by nbhasin2** [comment]
There was a test experiment whose data showed about 80% discrepancy in Views on the “Sign up/Sign in” Page, for iOS, between Amplitude and Leanplum (Amp showing less views).

**Comment by nbhasin2** [comment]
This was done by the Marketing folks and there is moz internal doc which has more details into it but the 80% discrepancy should give a general idea.

**Comment by garvankeeley** [comment]
I'd have to look again, but Amplitude data looked very suspicious to me in terms of user event counts, it was reporting things like reader mode being used comparably to new tab, which when we used to have redash, they were different by a huge magnitude (like 1000x). Intuitively the redash numbers make more sense than what I have seen in Amplitude.

**Comment by nbhasin2** [comment]
This is what I don't really get. To me the real data is what comes from iTunes Dashboard but that doesn't scale well

**Comment by garvankeeley** [comment]
That dashboard is great for validating our data against, I trust that the most.

**Comment by data-sync-user** [comment]
➤ Ashley Thomas commented:

Closing as won't do
