### ISSUE TITLE
FXIOS-24 ⁃ Search bar in Library:History

### ISSUE THREAD

**Issue by aj0413** [mozilla-mobile/firefox-ios#6680]
### Why/User Benefit/User Problem

* User's shouldn't need to scroll to find something in history list.
* Feature parity with chromium solutions
* Filters history list based on search entered (ie. show all StackOverflow results)

### Acceptance Criteria (how do I know when I’m done?)

Should mirror history search on Firefox stable for PC

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2436)

**Comment by sindhugudivada** [comment]
@aj0413 Are there UI mocks available for this feature?

**Comment by GeckoEidechse** [comment]
Not the one who originally opened this issue but I agree with the need for a possibility to search the browsing history.

Here's a mockup:

![mockup](https://user-images.githubusercontent.com/40122905/93922588-6c833c00-fd12-11ea-9536-5f878947a211.PNG)

based on how the interface looks in Safari:

![safari](https://user-images.githubusercontent.com/40122905/93922607-7147f000-fd12-11ea-9191-8f513df2d2a8.PNG)

**Comment by sindhugudivada** [comment]
@GeckoEidechse Is some one else already working on this? How does Mozilla team prioritize which ones should be developed by their engineering team Vs open source developers. Also may I know what is the ETA for this feature.

**Comment by GeckoEidechse** [comment]
@sindhugudivada, no idea. I'm not affiliated with neither the Firefox iOS dev team nor Mozilla in general.

**Comment by SimonBasca** [comment]
More requests at https://bugzilla.mozilla.org/show_bug.cgi?id=1687100.

**Comment by dnarcese** [comment]
tracking in https://mozilla-hub.atlassian.net/browse/FXIOS-3067
