### ISSUE TITLE
"Debug: Error messageIncomplete" is displayed when changing sync settings

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#6682]
## Preconditions:
1. Log in to FxA on device A. 
2. Login to FxA on device B and background the app.
## Steps to reproduce
1. On device A, go to Settings -> Tap on the Firefox Account 
2. Uncheck to sync History, Open Tabs, Logins
### Actual behavior
- After a few minutes, on device B, a notification is received with the message in the screenshot
### Device & build information
* Device A - iPad Pro 3rd gen / 13.4
* device B - iPhone Xr / 13.3  
* Build version: 26.0 (18049)
### Notes
- After tapping sync on device B and while sync is running, restarting the app from app switcher will sometimes cause a crash.
Attachments:
- Possibly related to : https://sentry-fm.prod.mozaws.net/mozilla/firefox-ios-v260/issues/293055/?query=is%3Aunresolved

![Screen Shot 2020-05-25 at 4 00 51 PM](https://user-images.githubusercontent.com/32130829/82815009-ec9eaf80-9ea0-11ea-80e2-9e7cc8e2432f.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2437)

**Comment by lmarceau** [comment]
Since only `data-sync-user` has commented on the issue after the `Stalebot` GitHub action (which triggered the removal of the `stale` label) I’ll close this issue for now. Please let us know if you think this issue needs to be reopened, we'll gladly do so. Thank you!
