### ISSUE TITLE
QR Pairing: firefox.com.cn/pair when use China-hosted services.

### ISSUE THREAD

**Issue by garvankeeley** [mozilla-mobile/firefox-ios#6687]
<img width="439" alt="image" src="https://user-images.githubusercontent.com/5495083/82915163-689b0500-9f3e-11ea-8ce2-930082763b41.png">

**Comment by rfk** [comment]
The FxAccountManager class should have a `getPairingAuthorityURL` method that you can use to obtain an appropriate URL in a generic fashion.

**Comment by garvankeeley** [comment]
Thanks Ryan, I'll switch to using that

**Comment by SimonBasca** [comment]
Verified fix on 26.0 (18092)
