### ISSUE TITLE
Documenting A/B test flow

### ISSUE THREAD

**Issue by jevans-mozilla** [mozilla-mobile/firefox-ios#6690]
**Vision**

Anyone on the team can setup an A/B test using Leanplum and we have an understanding of what would be needed to use a different multivariate tool in future

**Acceptance Criteria**

* How to implement and add an A/B test using Leanplum has been documented
* Documentation will be used internally

**Comment by nbhasin2** [comment]
Added internal doc with A/B test architecture and Leanplum setup.

https://docs.google.com/document/d/1UYmzd-Y3g0CMw3pqV60b-LF5HVptcuQ5EdwSMd53flc/edit?usp=sharing

I could likely add more things but need to figure out best way to organize the information. Will likely do it in multiple docs.
