### ISSUE TITLE
Refactor LoginsViewController to use MVVM

### ISSUE THREAD

**Issue by kaylagalway** [mozilla-mobile/firefox-ios#6706]
LoginsViewController currently does more than a ViewController should. This ticket is for the work related to adding a View Model for this VC and moving the business logic to it.

**Comment by LamourBt** [comment]
I would love to help with that initiative even though there is someone assigned.

**Comment by kaylagalway** [comment]
Hi @LamourBt ! This ticket was created to be included in a chunk of feature work @vphong is working on during their internship with us.  

If you're specifically interested in converting a view controller to MVVM, that's an initiative we have across the code base right now. Would you be interested in working on another one if I send some View Controller file candidates your way?

**Comment by kaylagalway** [comment]
I've put two files that I think would be great options below. Feel free to make an issue and assign yourself for whichever one you prefer:

`FxAWebViewController` - This is the authentication view controller for sync account sign in and viewing account settings. It has a web view and does some logic around whether the user launched this after pairing with a login qr code, or if they are launching email login, or viewing their sync settings page. 
`FirefoxHomeViewController` - This is the View Controller that you see when you launch a new tab in firefox. It has a lot going on and could definitely use the addition of a View Model.

**Comment by LamourBt** [comment]
Hi @kaylagalway, I will start with the top one and we can track the progress within #6716
