### ISSUE TITLE
[Today Widget] Update current widget strings/colours

### ISSUE THREAD

**Issue by dnarcese** [mozilla-mobile/firefox-ios#6708]
- [x] Update button colours
- [x] Update button strings
- [x] Update widget title string
- [x] Ensure colours change correctly for dark mode
- [ ] ~Add telemetry to know how often users are clicking each of the buttons~

Mocks:
https://github.com/mozilla-mobile/firefox-ios/issues/6661#issuecomment-634356845

**Comment by csuciu** [comment]
Verifying as fixed on master c7a498f4d.
