### ISSUE TITLE
FXIOS-9 ⁃ Specify Python major version in readme

### ISSUE THREAD

**Issue by kaylagalway** [mozilla-mobile/firefox-ios#6712]
Due to recent Glean additions in #6577, we need to specify what major version of Python is required for our scripts.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2440)

**Comment by travis79** [comment]
@kaylagalway glean_parser requires at least [Python version 3.5](https://github.com/mozilla/glean_parser/blob/e245f8f4e9cc4f5c18afac3e672183275b70d441/setup.py#L16)

**Comment by garvankeeley** [comment]
So there is no issue with Python-2.7 being the default python on OS X? Is python 3 on OS X?
The virtual env takes care of the fact the environment is 2.7?
I have python 3, but it looks like I installed it from homebrew at some point, I can't use my mac as reference.

**Comment by travis79** [comment]
After looking into this, in order to use the SDK generator script (glean_parser), we do require Python 3.5 to generate the metrics.  Glean itself has no such requirement, so it only really needs to be there for the generation step.  On MacOS, this requires installing via homebrew or similar and ensuring Python3 is in the PATH.

**Comment by garvankeeley** [comment]
Interesting, Catalina now includes python3 sort-of-by-default. Once /usr/bin/python3 is run for the first time the user is asked to install it: https://apple.stackexchange.com/questions/376077/is-usr-bin-python3-provided-with-macos-catalina

**Comment by garvankeeley** [comment]
I tried removing homebrew python3 and using the default python3, and I got Python 3.7.3 installed.

**Comment by travis79** [comment]
> Interesting, Catalina now includes python3 sort-of-by-default. Once /usr/bin/python3 is run for the first time the user is asked to install it: [apple.stackexchange.com/questions/376077/is-usr-bin-python3-provided-with-macos-catalina](https://apple.stackexchange.com/questions/376077/is-usr-bin-python3-provided-with-macos-catalina)

This is very cool, I did not know this!
