### ISSUE TITLE
Firefox for iOS crashes when adding an account picture

### ISSUE THREAD

**Issue by vasilicatamas** [mozilla-mobile/firefox-ios#6729]
**Build**
Stage [Train 1.173.0]
Prod [Train 1.172.0]

**Affected platforms**
iOS 13.4.1

**Affected versions**
Firefox for iOS 26.0 (18099)

**Steps to reproduce**
1. Launch Firefox and login using a Firefox account.
2. Go to https://accounts.stage.mozaws.net/settings/
3. Click "Add" button from the Account picture area.
4. Click “Upload” button.

**Expected results**
The avatar is successfully changed .

**Actual Results**
Firefox app stops working and crashes.

![issue4](https://user-images.githubusercontent.com/18114210/83550233-332e8280-a50f-11ea-87a9-b341e0069084.gif)

**Comment by SimonBasca** [comment]
First bad build 26.0 (18007)
Last good build 26.0 (17983)

**Comment by csuciu** [comment]
Verified as fixed on master c7a498f4d.
