### ISSUE TITLE
[Private browsing] Open apps preview should hide all screens in private browsing

### ISSUE THREAD

**Issue by AmyYLee** [mozilla-mobile/firefox-ios#6730]
1. Go to private opened tabs view (clear all opened private tabs)
2. Double tap home button (or swipe up) to scroll through open apps

Expected:
Hides private opened tabs homescreen

Actual:
Shows private opened tabs homescreen

Note: When a new tab is opened in private mode, this should also be hidden as well in the open apps view.

![File (1)](https://user-images.githubusercontent.com/5992746/83552398-b207c900-a4d7-11ea-93c8-164b400c964a.jpg)
![IMG_0025](https://user-images.githubusercontent.com/5992746/83552402-b2a05f80-a4d7-11ea-8dcd-8b23e19f5590.PNG)

**Comment by athomasmoz** [comment]
@AmyYLee thanks for logging, any recommendation on what the greyed out view should look like? This one from DUO is interesting (dark screen with logo)
![image](https://user-images.githubusercontent.com/43346208/83810446-02645f80-a66d-11ea-9c55-68314cf717ba.png)

**Comment by athomasmoz** [comment]
>Note: When a new tab is opened in private mode, this should also be hidden as well in the open apps view.
This is currently hidden. Do you recommend using the same greyed out screen in the open tabs view?

**Comment by AmyYLee** [comment]
> > Note: When a new tab is opened in private mode, this should also be hidden as well in the open apps view.
> > This is currently hidden. Do you recommend using the same greyed out screen in the open tabs view?

Please use Ink 90 #1D1133 and it should cover the entire window including search bar. Please see reference below
![Screen Shot 2020-06-08 at 15 14 38](https://user-images.githubusercontent.com/5992746/84070869-d01f6e80-a99a-11ea-9417-ee50d6167132.png)

**Comment by hariszaman** [comment]
Ink90 is #0f1126 on iOS

https://github.com/mozilla-mobile/firefox-ios/blob/9b3f393c4d4601416fa9898693bc1f7a5878ae36/Client/Frontend/photon-colors.swift#L95

**Comment by hariszaman** [comment]
With color changed and edges scaled to fit the whole screen it looks like this

[
![Simulator Screen Shot - iPhone 11 - 2020-06-09 at 15 34 24](https://user-images.githubusercontent.com/4822440/84152133-edbd0880-aa6c-11ea-9e46-dcdb0856e3d7.png)
]

**Comment by AmyYLee** [comment]
@hariszaman This looks good to me. Thanks.

**Comment by SimonBasca** [comment]
Verified fixed on main 89b961b1ce

**Comment by data-sync-user** [comment]
> **Laurie Marceau** commented from Jira:

This was caused by the fix implemented for [https://mozilla-hub.atlassian.net/browse/FXIOS-14874](https://mozilla-hub.atlassian.net/browse/FXIOS-14874|smart-link) 

We’ll revert the fix for that bug, in other words, going back to previous behavior
