### ISSUE TITLE
ETP Coversheet not showing up on 3rd launch in Prod v26.x

### ISSUE THREAD

**Issue by nbhasin2** [mozilla-mobile/firefox-ios#6731]
The ETP coversheet shows up on fresh install only in debug mode but not in prod
## Steps to reproduce
- Fresh install v26.0 version of the app 
- launch v26.0 version of the app from app store 
- on the 3rd launch you should see the ETP coversheet

### Expected behavior
- No coversheet is shown on 3rd launch

### Actual behavior
- ETP coversheet shows on 3rd launch 

### Device & build information
* Device: iPhone 11 Pro
* Build version: 18099
### Notes
Attachments: 

![image](https://user-images.githubusercontent.com/8919439/83565585-a7a3fa00-a4ec-11ea-8afc-55dcb172cf39.png)

**Comment by SimonBasca** [comment]
Tested on v26.0 (18099) and 27.0 (18428).
Tested on iPad Pro 3rd gen 11 inch (13.4.1), iPhone XS max (13.5), iPhone SE (11.4).

I was unable to reproduce this issue.
