### ISSUE TITLE
[Chronological Tabs] Support for private tabs

### ISSUE THREAD

**Issue by dnarcese** [mozilla-mobile/firefox-ios#6735]
**Vision**
As a user, I want to be able to open new private tabs and see my existing private tabs.

---
**Acceptance Criteria**
- [ ] private tabs button is added to bottom toolbar
- [ ] clicking private tab button switches to a view with only the private tabs
 - if none, show empty list for now
- [ ] clicking Private Browsing Mode from long pressing tab tray correctly switches to private mode in the tab tray

**Comment by dnarcese** [comment]
Firefox Beta build 0.0.1 (18307) has this.

**Comment by SimonBasca** [comment]
Tested on iPhone Xr (13.5), iPad Pro (13.3) iPhone SE (11.4).

Verifying as fix on 0.0.1 (18307) for all the above Acceptance Criteria.
