### ISSUE TITLE
White loading pages in night mode

### ISSUE THREAD

**Issue by cantonalex** [mozilla-mobile/firefox-ios#6739]
## Steps to reproduce
Enter night mode and open Firefox app after force quit

### Expected behavior
Page load should be black

### Actual behavior
White page load 

### Device & build information
* Device: iPhone X 
* Build version: iOS 13.5
### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2443)

**Comment by kelimuttu** [comment]
This issue is mentioned by a user on Twitter recently: https://twitter.com/SaintCanSin/status/1609702494401069057
