### ISSUE TITLE
Glean: delete user ping

### ISSUE THREAD

**Issue by garvankeeley** [mozilla-mobile/firefox-ios#6746]
Implement feature to delete user, using the Glean deletion ping.

**Comment by garvankeeley** [comment]
fixed by https://github.com/mozilla-mobile/firefox-ios/pull/6577
Needs QA verification

**Comment by garvankeeley** [comment]
cc  @athomasmoz, because once this is verified we are GDPR compliant IIUC

**Comment by SimonBasca** [comment]
Tested on v26.0 (18099). 

A baseline ping is received in the Glean dashboard after disableing "Send Usage Data" and when "Send Usage Data" is disabled no other ping is received. Also after enabling the baseline pings are received with a different "document_id:". 

Please let me know if there is anything else that reqiuers testing on this.
