### ISSUE TITLE
[glean] Verify DAU in v26

### ISSUE THREAD

**Issue by garvankeeley** [mozilla-mobile/firefox-ios#6747]
We need to verify the Glean DAU matches the old telemetry DAU.
v26.0 has Glean hooked up to report DAU so we can compare it.

**Comment by travis79** [comment]
FYI, the Glean team was planning on taking this on as part of our validation of the initial integration.  We would be more than happy to share the results of our analysis.  We typically like to see about a week of data to account for any weekly seasonality, and it looks like we have enough to get started by next week.

**Comment by garvankeeley** [comment]
We should check DAU numbers now if we can (assuming that is easy to look up), they should match for v26.0; this bug is for looking at comparative DAU for v26.0-only with old telemetry.
It will take a long time for Glean DAU to fully match old telemetry as adoption of the new version takes time, some people never upgrade, or skip versions, and some of our DAU is from Firefox iOS versions that can't be updated due to device OS restrictions, etc.

I think product should look at what the expected DAU drop will be (which should be easy-ish to estimate, we have dashboards for all that info I mentioned).

**Comment by garvankeeley** [comment]
Travis did a graph in redash https://sql.telemetry.mozilla.org/queries/71790/source#180190, the numbers are more than acceptable for the purposes of this issue (which was to ensure no obvious breakage), they are 3% higher in Glean than old telemetry.

**Comment by garvankeeley** [comment]
cc @athomasmoz, see last comment, Glean DAU looking good
