### ISSUE TITLE
Re-register for push notifications if FxA reports the subscription as expired

### ISSUE THREAD

**Issue by rfk** [mozilla-mobile/firefox-ios#6752]
Ref https://github.com/mozilla/application-services/issues/3127#issuecomment-639109631.

When refreshing the FxA device list, firefox-ios can check whether the push subscription it registered with the FxA server is still in good standing. If not, then the FxA server will flag it as expired, which can be checked via the `subscriptionExpired` property on the device record. We're also looking at whether we can [automatically fire a notification](https://github.com/mozilla/application-services/issues/3199) when the FxA component detects this state.

If Firefox finds itself in this state, it should assume that its connection to APNS or the autopush service has gone bad, and should try to repair it. I think treating it similar to a [push decryption failure](https://github.com/mozilla-mobile/firefox-ios/blob/a9558954fc930d1eb25f4494fd989f45e0d1bc66/Account/FxAPushMessageHandler.swift#L58) should help.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2446)

**Comment by tarikeshaq** [comment]
This outdated and is already done, see https://github.com/mozilla-mobile/firefox-ios/blob/e80d2b1ead135046230c4197bb31f0a9bca9629e/Client/Application/AppDelegate%2BPushNotifications.swift#L56

**Comment by tarikeshaq** [comment]
Should be safe to close, closing the jira equivalent
