### ISSUE TITLE
PushNotificationSetup may not recovery from failure to update FxA device record

### ISSUE THREAD

**Issue by rfk** [mozilla-mobile/firefox-ios#6753]
So I was poking around in [RustFxA/PushNotificationSetup.swift] and noticed something that didn't feel quite right, please feel welcome to close this if I've misunderstood what's happening.

After successfully registering with APNS, this code does the following:

1. Checks that it hasn't previously setup push with this APNS token ([here](https://github.com/mozilla-mobile/firefox-ios/blob/a9558954fc930d1eb25f4494fd989f45e0d1bc66/RustFxA/PushNotificationSetup.swift#L17))
2. Registers the APNS token with autopush ([here](https://github.com/mozilla-mobile/firefox-ios/blob/a9558954fc930d1eb25f4494fd989f45e0d1bc66/RustFxA/PushNotificationSetup.swift#L24))
3.  Records that it was previously setup push with this APNS token ([here](https://github.com/mozilla-mobile/firefox-ios/blob/a9558954fc930d1eb25f4494fd989f45e0d1bc66/RustFxA/PushNotificationSetup.swift#L27))
4. Updates the FxA device record with the push subscription ([here](https://github.com/mozilla-mobile/firefox-ios/blob/a9558954fc930d1eb25f4494fd989f45e0d1bc66/RustFxA/PushNotificationSetup.swift#L31))

If step (4) happens to fail due to e.g. a server error, I don't think there's any mechanism for trying again. Even if we do get triggered to re-enter this function, we'll exit at step (1) because we already recorded success at step (3).

I wonder if it's worth re-arranging steps (3) and (4) so that we only write that the token was successfully registered, if we've set up *all* of the push-related infrastructure.

Alternately, maybe we could expand https://github.com/mozilla-mobile/firefox-ios/issues/6752 to also check for the "our device record doesn't have a push subscription at all" case.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2447)

**Comment by lmarceau** [comment]
Since only `data-sync-user` has commented on the issue after the `Stalebot` GitHub action (which triggered the removal of the `stale` label) I’ll close this issue for now. Please let us know if you think this issue needs to be reopened, we'll gladly do so. Thank you!
