### ISSUE TITLE
Command-click on links should open them into a new tab

### ISSUE THREAD

**Issue by a2sheppy** [mozilla-mobile/firefox-ios#6755]
When a physical keyboard is in use, such as the Magic Keyboard for the iPad Pro, clicking a link with the command key held down should open the link into a new tab. This would match our behavior on desktop Firefox.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2448)

**Comment by tech189** [comment]
This has been fixed by #7209 and works for me!
