### ISSUE TITLE
[Chronological tabs] Misaligned tabs title

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/firefox-ios#6761]
## Steps to reproduce
Have several tabs open in previous build

### Expected behavior
All tabs are shown fine with the new design

### Actual behavior
There are some tabs that are not aligned (2nd and 5th). Please see screenshot.
![IMG_7309](https://user-images.githubusercontent.com/1897507/84115587-9730d980-aa2e-11ea-9435-a119338feb8e.PNG)

### Device & build information
* Device: iPhone 6
* Build version: TF 0.0.1

**Comment by isabelrios** [comment]
Somthing similar happens when going to landscape mode and then back to portrait mode. Some tabs that were correctly shown on portrait are misaligned after being in landscape mode.
Please let me know if you prefer a separate issue for that particular scenario.

**Comment by dnarcese** [comment]
This should be fixed in https://github.com/mozilla-mobile/firefox-ios/commit/c578a246dec352528309eb6557012504a0bb130d

**Comment by SimonBasca** [comment]
Verified fix on chronological-tabs branch e2edfa7.
