### ISSUE TITLE
FXIOS-495 ⁃ [Chronological tabs] Undo closing all tabs causes issues in the UI

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/firefox-ios#6762]
## Steps to reproduce
Have several tabs open
Tap on the trash icon to close all tabs
Close all tabs
Tab on the Undo button and go back to see all tabs open

### Expected behavior
All tabs are shown as they were before trying to close them

### Actual behavior
The tabs are misaligned and the fav icon for each one has dissapeard

### Device & build information
* Device: iPhone 6s
* Build version: 0.0.1

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-495)

**Comment by data-sync-user** [comment]
➤ Ashley Thomas commented:

Alignment has been fixed. Favicons still need to be fixed

**Comment by isabelrios** [comment]
Closing since a new one has been open related to this: https://github.com/mozilla-mobile/firefox-ios/issues/7547
