### ISSUE TITLE
[Today Widget] "Go to copied link" string appears cut off

### ISSUE THREAD

**Issue by csuciu** [mozilla-mobile/firefox-ios#6763]
iPhone 11 Pro (13.3)
master c7a498f4d

1. Open the app and copy a link.
2. Go to Today Widget and check the "Go to copied link" string.

Result: The string appears cut off.
<img width="378" alt="Screenshot 2020-06-09 at 15 15 00" src="https://user-images.githubusercontent.com/1866605/84148253-628d4400-aa67-11ea-91c6-646faeb581ab.png">

**Comment by SimonBasca** [comment]
Verified fixed in main 89b961b1ce
