### ISSUE TITLE
[Today Widget] Copied link color is too light when iOS Light mode is enable

### ISSUE THREAD

**Issue by csuciu** [mozilla-mobile/firefox-ios#6764]
iPhone 11 Pro (13.3)
master c7a498f

1. Enable Light mode in iOS settings.
1. Open the app and copy a link.
2. Go to Today Widget and check the color of the copied link.

Result: The color of the link is too light making the link barely visible.
<img width="378" alt="Screenshot 2020-06-09 at 15 15 00" src="https://user-images.githubusercontent.com/1866605/84148990-6f5e6780-aa68-11ea-85da-c388bd9cd957.png">

**Comment by SimonBasca** [comment]
Verified fix on main 89b961b1ce
