### ISSUE TITLE
[Today Widget] The widget doesn't strech properly when positiond at the bottom of the screen

### ISSUE THREAD

**Issue by csuciu** [mozilla-mobile/firefox-ios#6765]
iPhone 11 Pro (13.3)
master c7a498f

1. Enable four widgets.
2. Make sure the Fennec is the fourth one and it's displayed at the bottom of the screen.
3. Check the widget.

Result: The widget does not stretch properly making the icons look oval.
<img width="379" alt="Screenshot 2020-06-09 at 16 00 41" src="https://user-images.githubusercontent.com/1866605/84150403-7edeb000-aa6a-11ea-8e6a-f9846794524c.png">

**Comment by dnarcese** [comment]
The Today widget has a new design starting in v28.0 this shouldn't be an issue anymore.
