### ISSUE TITLE
[Today Widget]Button strings are no loger displayed after copying a link

### ISSUE THREAD

**Issue by csuciu** [mozilla-mobile/firefox-ios#6766]
iPhone 11 Pro (13.3)
master c7a498f

* Check the widget on the device mentioned above.

Result: The buttons strings are missing. 
Tested also on an iPhone 8 (13.3.1) and the strings are displayed correctly.

<img width="378" alt="Screenshot 2020-06-09 at 15 15 00" src="https://user-images.githubusercontent.com/1866605/84152947-f6faa500-aa6d-11ea-9029-88945df2bb03.png">

**Comment by csuciu** [comment]
Actually this happens on all devices when the "copied link" section is displayed in the widget.

**Comment by SimonBasca** [comment]
Verified fix on main 89b961b1ce8, on iPad Pro 3rd gen (13.4).
