### ISSUE TITLE
Top sites are displayed on four rows after unlocking the phone and changing orientation

### ISSUE THREAD

**Issue by csuciu** [mozilla-mobile/firefox-ios#6767]
iPhone 11 Pro (13.3)
master c7a498f

1. Put the device in landscape mode while in the Home screen.
2. Lock the device
3. Unlock the device.
4. Switch to portrait.

Result: Top Sites are displayed on four rows although the default two rows option is enabled.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2450)

**Comment by lmarceau** [comment]
@csuciu I think this is now fixed

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Marking as verified fix on main 42bb8dc61447541b984f21b33c8ae72e996899ea
