### ISSUE TITLE
[Chronological Tabs] < iOS 13 Add Close button

### ISSUE THREAD

**Issue by dnarcese** [mozilla-mobile/firefox-ios#6768]
On devices with iOS 11 or 12, the new popover style view controller is not available and will default to a fullscreen view. This means users will not be able to swipe down the Tab view like in iOS 13. 

**Acceptance Criteria**
- Close button in top left of tab tray
- Close button will dismiss the tab tray

**Comment by SimonBasca** [comment]
Verified fixed on iPhone SE (11.4), iPhone 6 (11.x / 12.x), iPhone X (12.x).
