### ISSUE TITLE
[Chronological tabs] Home page title is missaligned after STR

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#6771]
## Steps to reproduce
1. Open Tabs Tray
2. Tap "X" to close the default opened tab
3. Tap "+" to open a new tab
4. Open Tabs Tray
### Expected behavior
- The title should be aligned. 
### Device & build information
* Device: iPhone Xr (13.4)
* Build version: 18218
### Notes
See also #6761
Attachments: 
![Screen Shot 2020-06-10 at 11 12 11](https://user-images.githubusercontent.com/32130829/84243711-44791f80-ab0b-11ea-8fe5-1954b3f762ab.png)

**Comment by dnarcese** [comment]
This should be fixed in https://github.com/mozilla-mobile/firefox-ios/commit/c578a246dec352528309eb6557012504a0bb130d

**Comment by SimonBasca** [comment]
Verified fix on chronological-tabs branch e2edfa7.
