### ISSUE TITLE
(WebXR) Sessions terminating due to lack of / broken wakelock

### ISSUE THREAD

**Issue by machenmusik** [mozilla-mobile/firefox-ios#6778]
## Steps to reproduce
Use the webxr branch (or released WebXR Viewer 2.0) with any WebXR AR experience.
Let it sit there.

### Expected behavior
Wakelock prevents phone from sleeping during AR session.

### Actual behavior
Phone screen dims and then phone locks due to lack of / broken wakelock.

### Device & build information
* Device: iPhone X
* Build version: WebXR Viewer 2.0
### Notes

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2453)

**Comment by blairmacintyre** [comment]
I don't know if Firefox has wakelock built in for other things (video watching, for example);  could probably be piggybacked on it.

**Comment by lmarceau** [comment]
Since only `data-sync-user` has commented on the issue after the `Stalebot` GitHub action (which triggered the removal of the `stale` label) I’ll close this issue for now. Please let us know if you think this issue needs to be reopened, we'll gladly do so. Thank you!
