### ISSUE TITLE
[Sync Integration Tests] FxA accounts used are not verified, login is not completed

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/firefox-ios#6780]
Although the stage account used in the tests is reported as verified:
```
root:plugin.py:93 Created: FxAccount(email='pytest-c1be16d2bf@restmail.net', password='SIxUGuRm')

root:plugin.py:101 Verified: FxAccount(email='pytest-c1be16d2bf@restmail.net', password='SIxUGuRm')
```

Looks like it is not. Something has changed since a few days ago(about one week) there is an extra step in which the set up needs to be finished:
<img width="309" alt="imagen" src="https://user-images.githubusercontent.com/1897507/84357679-5e2b6d00-abc6-11ea-99e2-bd50bb94ff60.png">

That's on Desktop, on Mobile we see the screen waiting for an authentication code to be entered.

Tracking from the file shown in the log [showing the account as verified](https://github.com/mozilla/pytest-fxa/blob/master/pytest_fxa/plugin.py#L88) to where/how the account is verified, I got to this [core.py line](https://github.com/mozilla/PyFxA/blob/master/fxa/core.py#L222).

I will try to get more info and investigate deeper, but in the meantime there are a few questions...
-is this the new workflow?
-does the account need to be authenticated in addition to verified? Not sure if that makes sense but saw this commet [# note: not authenticated](https://github.com/mozilla/PyFxA/blob/master/fxa/core.py#L222): 
```
def verify_email_code(self, code):
        return self.client.verify_email_code(self.uid, code)  # note: not authenticated
```

-are there other/similar tests affected?

While investigating I would appreciate some insights here from @rfk.
Also, sorry @davehunt to ping you here too but since you put together all these pieces at the very beginning you may have good input to this. 
Thank you very much in advance!

**Comment by isabelrios** [comment]
View on Mobile:
![imagen](https://user-images.githubusercontent.com/1897507/84398234-feea4e80-abff-11ea-858b-653f9e4036d9.png)

**Comment by isabelrios** [comment]
I was able to reproduce that on latest Nightly 79 with my mozilla account, but only once.
Even this only happened once, I think there might be some steps in which we can reproduce this. Trying to find out more

**Comment by isabelrios** [comment]
More info trying to debug and get more info about this issue. 
This is the POST sent by the test to verify the account (not sure if all the info is there, I got it while Nightly was running)
[browser_Archive [20-06-11 21-31-24].pdf](https://github.com/mozilla-mobile/firefox-ios/files/4766951/browser_Archive.20-06-11.21-31-24.pdf)
Note that after that POST there is not any error recieved, it stays there until Nightly is closed due to the timing set by the tests. Having it longer open, does not make any difference

Also, if manually I click on Resend code, then the account is verified. It is the first time trying to be verified when it fails.

**Comment by rfk** [comment]
Sorry that I somehow missed your ping on this @isabelrios; it's not clear from the discussion above whether we ever figured out what was happening here, but wanted to check since the issue has been closed - did you end up getting this working?

**Comment by isabelrios** [comment]
Hi @rfk! no worries, I opened a bugzilla bug but then after a few days all started to work...looked like a temporary issue affecting stage servers. At the moment the tests are working and finally I'm closing all the related issues... if this or similar issues happen again, I will let you know. Thanks!
