### ISSUE TITLE
Universal Acceptance issue for displaying IDNs

### ISSUE THREAD

**Issue by UA2018** [mozilla-mobile/firefox-ios#6797]
I am reaching out to you to inform about an Universal Acceptance issue your clients are experiencing with these kinds of Internationalized Domain Names (IDNs). 

http://xn--b1amarcd.com/ - uses Verisign IDN table for Bulgarian. I will call it D1
https://xn--d1al8j4a.com/ - uses Verisign IDN table for Cyrillic. I will call it D2

D1 display correctly (in Cyrillic form) in Firefox. When you copy it, it pastes in Punycode form.
D2 displays in Punycode form everywhere.

Is there any way to fix the issue and make these types of domains work fully Universal Acceptance compliant in Unicode as well?

Kindly please look into and fix this issue.

To find out more information on new domain names and email addresses please visit www.uasg.tech. 

You might find the information there helpful as you work to fix this problem. 

Universal Acceptance (UA) is the state where all valid domain names and email addresses are accepted, validated, stored, processed and displayed correctly and consistently by all Internet-enabled applications, devices and systems. 

Become UA Acceptance Ready: https://uasg.tech/become-universal-acceptance-ready/

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2457)

**Comment by lmarceau** [comment]
Since only `data-sync-user` has commented on the issue after the `Stalebot` GitHub action (which triggered the removal of the `stale` label) I’ll close this issue for now. Please let us know if you think this issue needs to be reopened, we'll gladly do so. Thank you!

**Comment by simevidas** [comment]
@lmarceau I just started a new blog at https://šime.eu. On iOS, my domain name is displayed correctly in the URL bar in Chrome, and Safari, but not in Firefox. What is preventing Firefox from behaving like the other browsers? I thought that iOS browsers are merely ”Safari skins”*.

(*I know that Mozilla probably plans to release a Gecko-based version of Firefox on iOS in the EU, but that hasn’t happened yet.)

<img width="1202" alt="Screenshot 2024-01-28 at 19 39 41" src="https://github.com/mozilla-mobile/firefox-ios/assets/716405/b1a91968-0b96-4092-84b7-7f601b83886b">

**Comment by lmarceau** [comment]
There's probably some URL formatting (either with the domain or subdomain) we're handling differently to display the URL in the bar. Would need to pinpoint exactly why/where this is happening, but those are my initial thoughts seeing this issue
