### ISSUE TITLE
Typing in the search/address bar has bad interaction with autocomplete

### ISSUE THREAD

**Issue by james-culp** [mozilla-mobile/firefox-ios#6801]
## Steps to reproduce

Start typing in the address/search bar: perhaps the letter "s"

### Expected behavior

The user sees "s", with suggested completion URLs starting with "s". Example: "s[mile.amazon.com]".

(Brackets note auto-completed suggestion.)

### Actual behavior

The "s" is matched with completion URLs, but is separately run through an auto-correct algorithm. "S" auto-corrects to "a", resulting in "a[mile.amazon.com]".

### Device & build information
* Device: iPhone 11 Pro, 13.5.1
* Build version: Version 26.0 (18099)

### Notes

There seems to be a timeout, because if I type quickly, I can type "sm" quickly, and end up with "sm[ile.amazon.com]"

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2458)

**Comment by lmarceau** [comment]
Since only `data-sync-user` has commented on the issue after the `Stalebot` GitHub action (which triggered the removal of the `stale` label) I’ll close this issue for now. Please let us know if you think this issue needs to be reopened, we'll gladly do so. Thank you!
