### ISSUE TITLE
FXIOS-522 ⁃ Showing the widget on long press is superfluous

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#6807]
Steps to reproduce:

1. Long press the Firefox icon

Actual results:

A menu and a widget pop up, the widget being redundant as all features of it are already in the menu

I have attached an image that shows the redundancy quite clearly

Expected results:

Only the menu should pop up

![image](https://user-images.githubusercontent.com/32130829/84768273-a985b700-afdc-11ea-8209-5bbc1b6b2812.png)

Note:
- Chrome shows Top Sites in widget and QR, Open New Tab, New Private tab in 3D Touch menu option. We show the same option in both the Widget and the 3DT options

Requested via : https://bugzilla.mozilla.org/show_bug.cgi?id=1644884

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2460)

**Comment by athomasmoz** [comment]
Note: we should check the behaviour on iOS 14 for this when considering a solution

**Comment by brampitoyo** [comment]
@SimonBasca Actually, will it be possible to not show the widget on long-press, and just rely on showing the menu items?

In this context, the menu item looks more integrated (less out of place) with the rest of the long-press interface, when compared to the widget. I’d be ok if the widget isn’t included.
