### ISSUE TITLE
Unable to save image to the camera roll from "pixiv.net"

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#6812]
Steps to reproduce:

1.Open a specific web page (in my case it was pixiv.net)
2.Press and hold an image to open the menu.
3.Press Save Image.

Actual results:

Images are not saved to the Camera Roll.

Expected results:

The image is saved to the camera roll.
### Device & build information
* Device: iPhone Xr (13.5)
* Build version: 27.0(build18321)
 Requested via : https://bugzilla.mozilla.org/show_bug.cgi?id=1646635

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2463)

**Comment by SimonBasca** [comment]
Still reproducible on v27.0 (18428) on iPhone Xr (13.5). 

Go to pixiv.net
Long press on an image
Tap "Save image"

Note:
1. This is working in Safari.
2. In Safari on pixiv.net, long pressing on a image will show option "Add to photos" rather than "Save image" in Firefox.

**Comment by SimonBasca** [comment]
Duplicate of #7366

**Comment by SimonBasca** [comment]
This issue is still reproducible after https://github.com/mozilla-mobile/firefox-ios/issues/7350

**Comment by lmarceau** [comment]
Since only `data-sync-user` has commented on the issue after the `Stalebot` GitHub action (which triggered the removal of the `stale` label) I’ll close this issue for now. Please let us know if you think this issue needs to be reopened, we'll gladly do so. Thank you!
