### ISSUE TITLE
Iteration 2: A/B Test Onboarding

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-ios#6815]
**Vision**

I want to determine what version of onboarding is a good balance of introducing users to the app, having them log in, and gets them to value quickly

**Acceptance Criteria**

* A/B test set up to compare 2 versions of onboarding
* Control version is what we have live today
* Variant version includes version 1 intro card and version 2 sync card
  * [Mocks](https://app.abstract.com/share/fb3066fc-2401-48a1-951d-609eb81c3913?collectionId=912f4b7f-895d-40ec-b7c9-0a2c9cd5af8e&collectionLayerId=af580f68-c30c-4813-b50b-d0e37f1e5710&present=true&preview=false&sha=ba61072ad045dd3a6fd440b48d85519594ffc23b)
  * _Note: this card matches the one used in our last test, so strings should already be available and localized_

**Comment by nbhasin2** [comment]
**More info:** For A/B test Iteration 2 we use the same control but for variant we switch to show same WelcomeV1 but SyncV2
- Control:  WelcomeV1 + SyncV1 
- Variant: WelcomeV1 + SyncV2 

**LP Variable name:** onboardingABTestV2
 
**LP Variable Type:** Bool
- True:  Control
- False: Variant

**Comment by SimonBasca** [comment]
Verified fix on v28.0 (18809).
