### ISSUE TITLE
Cannot log into Google when hardware U2F is enabled (and Google Authenticator as a fallback)

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#6822]
Steps to reproduce:

I'm using Firefox v26.0 (18099) under iOS 12.1.1.

    1 .Visit Google.com
    2. Click 'Sign in'
    3. Fill in the username, click 'Next'
    4. Fill in the password, click 'Next'
    5. Delete cookies, repeat 1-4
    6. In Private Browsing, repeat 1-4

Actual results:

After confirming my password, I was redirected to https://accounts.google.com/signin/v2/identifier?passive=1209600&continue=https%3A%2F%2Faccounts.google.com%2F&followup=https%3A%2F%2Faccounts.google.com%2F&flowName=GlifWebSignIn&flowEntry=ServiceLogin asking me for my username again (which by the way still didn't work).

Expected results:

Successfully logged in and redirected to Google front page.

Video : https://bugzilla.mozilla.org/attachment.cgi?id=9157043

VIa : https://bugzilla.mozilla.org/show_bug.cgi?id=1645661

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2467)

**Comment by SimonBasca** [comment]
Note from reporter: 
@Simon Yup, just confirmed that removing the hardware tokens from my Google account fixed the issue. I guess it's somehow related to Google not being able to correctly detect navigator.credentials capabilities. My GitLab account has also got both Google Authenticator and hardware U2F, and it's able to tell that only the former is available on my phone. Using only Google Authenticator was fine, it asked me for my OTP and logged me in without any problem. And btw Google+hardware U2F+OTP works in Safari.

**Comment by Frederick888** [comment]
Sorry but I think the title should've been something like 'Cannot log into Google when hardware U2F is enabled (and Google Authenticator as a fallback)', as I mentioned that

> Using only Google Authenticator was fine, it asked me for my OTP and logged me in without any problem.

**Comment by lmarceau** [comment]
Since only `data-sync-user` has commented on the issue after the `Stalebot` GitHub action (which triggered the removal of the `stale` label) I’ll close this issue for now. Please let us know if you think this issue needs to be reopened, we'll gladly do so. Thank you!
