### ISSUE TITLE
Download doesn't stop after closing page doesn't appear in the downloads section

### ISSUE THREAD

**Issue by BigSamSampson** [mozilla-mobile/firefox-ios#6823]
## Steps to reproduce
1. Open app
2. Go to the https://www.futurehosting.com/network-test-files/
3. Click button to download test file 100 MB
4. Close current page
5. Click Home button
6. Go to the downloads folder
### Expected behavior
User expects that in the downloads section the current download will be displayed and he will have the opportunity to cancel it.
### Actual behavior
The current download continues, but is not displayed anywhere. User unable to cancel download.
### Device & build information
* Device: iPhone 8 Plus
* Build version: 22.0

### Notes
When user clear all tabs, it makes impossible to cancel or pause download.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2468)

**Comment by sindhugudivada** [comment]
@dnarcese  Is this open for picking up and working? Please let me know. I would love to give a try.

**Comment by dnarcese** [comment]
@sindhugudivada yes! Thank you for your interest - we welcome the help.

**Comment by sindhugudivada** [comment]
@dnarcese  I am thinking of using NotificationCenter. Upon triggering of closing the tabs, we can trigger an event to which the Download thread can subscribe to. Up on receiving this event, Download may be cancelled. Does this approach sound right?

**Comment by garvankeeley** [comment]
NotificationCenter for cross-thread messaging sounds like a good choice.

**Comment by lmarceau** [comment]
Since only `data-sync-user` has commented on the issue after the `Stalebot` GitHub action (which triggered the removal of the `stale` label) I’ll close this issue for now. Please let us know if you think this issue needs to be reopened, we'll gladly do so. Thank you!
