### ISSUE TITLE
[Chronological tabs] tab tray background

### ISSUE THREAD

**Issue by dnarcese** [mozilla-mobile/firefox-ios#6826]
There are some colour changes requested for the app background when in the tab tray

Current:
![IMG_1D51E397C8C4-1](https://user-images.githubusercontent.com/11432165/85331009-565fa880-b4a3-11ea-8f02-6ee8a82a6e94.jpeg)

Expected:
![IMG_531EE5C02D02-1](https://user-images.githubusercontent.com/11432165/85331062-6ecfc300-b4a3-11ea-8c65-45bedae90fdb.jpeg)

Specifically, we want the background to be a darker colour and the previous screen to stay the same colour

**Comment by SimonBasca** [comment]
Tab background has been changed according to screenshot.

Tested on iPhone Xr (13.5) on branch chronologcal-tabs 6988e8fcf1e.

**Comment by SimonBasca** [comment]
Please note that this issue can be affected by https://github.com/mozilla-mobile/firefox-ios/issues/6772#issuecomment-659418661.
