### ISSUE TITLE
Blank Screen on Firefox Startup

### ISSUE THREAD

**Issue by nbhasin2** [mozilla-mobile/firefox-ios#6844]
STR
- Fresh Install Firefox 27.0 beta and install 
- Open 

Expected 
- Show onboarding screen 

Actual
- Blank screen on 1st launch

**Comment by dnarcese** [comment]
For documentation: 
I have not seen this issue yet after ~10 fresh installs. I am on iOS 13.5.1 on iPhone 11

**Comment by SimonBasca** [comment]
We tested this on 27.0 (18383) and were unable to reproduce the issue. I noticed it has a patch. @nbhasin2 can this be safely closed?

**Comment by nbhasin2** [comment]
@SimonBasca I would say 18383 will have a bug where if you fresh install app and open it without internet. It'll show white screen. That bug is fixed with my patch in build **18428** 

Could you try the above build please. Thanks :)

**Comment by SimonBasca** [comment]
Verified fixed on 27.0 (18428).
