### ISSUE TITLE
Constant Crash when updating Account picture 

### ISSUE THREAD

**Issue by RyanGoudie** [mozilla-mobile/firefox-ios#6845]
## Steps to reproduce
1. Access personal account 
2. Access manage account and devices
3. Attempt to change account picture 

### Expected behavior
Should update the account picture 

### Actual behavior
App Crashes and kicks user to IOS home screen

### Device & build information
* Device: Iphone XR 
* Build version: Most upto date version of IOS and Firefox
### Notes
Attachments: Error occured with a range of photos with a range of sizes and file types

**Comment by SimonBasca** [comment]
We have fix #6729 for this that should go in version 27.0. What version are you using @RyanGoudie ?

**Comment by RyanGoudie** [comment]
Just gave that read , I’m on 26.0 all good then , sorry for waste of time
