### ISSUE TITLE
Search icon on new tab toolbar

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-ios#6846]
### Vision

As a user, I want a button on the bottom toolbar to start a search so that I can access the search bar without stretching my thumb across to the top of the screen

### Acceptance Criteria

* Search icon added to the bottom toolbar in portrait ([mock](https://app.abstract.com/share/32f6c003-3908-4ca5-81e7-37137c04eee3?collectionLayerId=f5518f50-f1e3-4e72-92ac-bd51a887eaca&mode=design))
* Tracking adding for number of clicks on the search icon and the searchbar from the homescreen to compare usage
  * Tracking must follow privacy policy
  * Should confirm with data science if this should go to Amplitude or just internal telemetry

### Not included

* The icon should only be included on the toolbar in the new tab screen. It should not appear in the toolbar when scrolling a webpage
* A/B test not needed as success will be measured based on clicks of new button
* This does not include iPad, as there is no bottom toolbar

**Not Included**

* This is not needed in landscape mode, so changes are only needed for portrait

**Comment by joeyg** [comment]
@athomasmoz Where would I be able to get the icon for this task?

**Comment by nbhasin2** [comment]
**Update:** We have contributor PR https://github.com/mozilla-mobile/firefox-ios/pull/6853#pullrequestreview-438898421 up which allows user to start start from the bottom search icon. 

**Next up:** We need to find the events that comply with our Privacy Policy that should track number of clicks for new search icon button.

**Comment by nbhasin2** [comment]
Reopened the issue as we still need to add events for it.

**Comment by nbhasin2** [comment]
Add a new counter event to the new search button as we currently have one for the action bar

**Comment by SimonBasca** [comment]
Verifying as fix on master 010453407c58 on iPhone Xr (13.5), iPad Pro (13.4), iPhone SE (11.4)
