### ISSUE TITLE
FXIOS-547 ⁃ UI for New Tab Link on Toolbar (Portrait)

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-ios#6847]
### Why/User Benefit/User Problem

As a user, I want to quickly start another search while keep my current tab open for later

### Acceptance Criteria

* Plus icon added to the bottom nav bar when a webpage is open ([spec](https://docs.google.com/document/d/1n0UDbk2UexFB360uoGLwIvjkaMaQ_ZyXmmLTigBfJ3g/edit#heading=h.p1cuc1sh5ua))
  * Clicking the plus icon will take users to a fresh tab with keyboard up
  * Refresh option moved to page actions menu
* Change is hidden behind feature flag pending A/B test
* Change can be turned on by setting that shows only in debug mode

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-547)

**Comment by dnarcese** [comment]
@brampitoyo does this button also appear on the home page?

**Comment by athomasmoz** [comment]
@dnarcese The idea behind the toolbar icons is:
* Magnifying glass appears when you are already in a fresh tab
* New tab icon appears when you're on a webpage, so that you can start a new search without losing your current page

Given that information, I would assume that magnifying glass shows on homepage.

**Comment by brampitoyo** [comment]
Hi @dnarcese – @athomasmoz is correct!

On New Tab Page (home page, Firefox Home), the magnifying glass icon shows up.

On web pages, the plus icon shows up.

**Comment by SimonBasca** [comment]
Verified fix on c91e958de43. 

Found some issues related to this feature: #7213 and #7212
