### ISSUE TITLE
The page is displayed with Night Mode after it was previously disabled

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#6855]
## Steps to reproduce
1. Go to "google.com"
2. From the Hamburger menu, enable Night Mode
3. Search for something on Google
4. Disable Night Mode
5. Hit "Back" to go to the previous page
### Expected behavior
- On the previous page should be Night Mode should be disabled.
### Actual behavior
- The previous page is displayed with Night Mode.
### Device & build information
* Device: iPad Pro 3rd gen (13.4)
* Build version: 27.0 (18428)
### Notes
Attachments: 

![Screen Shot 2020-06-25 at 4 42 14 PM](https://user-images.githubusercontent.com/32130829/85731063-dc2d5f00-b702-11ea-9575-29ac998cc03d.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2474)

**Comment by garvankeeley** [comment]
Not too surprising as this feature is implemented with JS and I suspect has problems toggling on/off with cached pages in the history.

**Comment by lmarceau** [comment]
Since only `data-sync-user` has commented on the issue after the `Stalebot` GitHub action (which triggered the removal of the `stale` label) I’ll close this issue for now. Please let us know if you think this issue needs to be reopened, we'll gladly do so. Thank you!
