### ISSUE TITLE
FXIOS-549 ⁃ The onboarding picture should include a tablet too

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/firefox-ios#6857]
### Why/User Benefit/User Problem
As a Firefox user, I want to know all the available devices where I can use the browser.
### Acceptance Criteria (how do I know when I’m done?)
A tablet is displayed on the onboarding picture.

https://app.abstract.com/share/fb3066fc-2401-48a1-951d-609eb81c3913

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2475)

**Comment by brampitoyo** [comment]
I don’t think this is a big issue. However, should @apbitner have some time to create a tablet device illustration, we can solve this issue.

**Comment by apbitner** [comment]
I don't think the intent of that screen was to communicate all of the devices that Firefox is available on, but I'll ping @shorlander, the creator of the illustration.
