### ISSUE TITLE
[iPad] Snack bar needs safe area

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#6859]
## Steps to reproduce
1. Go to a page
2. Open the Page action menu
3. Tap "Copy link"
### Expected behavior
- Snack bar should have safe area
### Actual behavior
Snack bar does no have safe area
### Device & build information
* Device: iPad Pro 3rd gen
* Build version: 27.0 (18383)

![Screen Shot 2020-06-25 at 7 01 11 PM](https://user-images.githubusercontent.com/32130829/85755239-6f23c480-b716-11ea-8f9b-f83f34069d40.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2477)

**Comment by jevans-mozilla** [comment]
I wasn't aware of iPad honoring Safe-Area constraints.  Part of this fix could provide an update if this is now the case as it will have implications in other areas as well as future UX designs

**Comment by lmarceau** [comment]
Since only `data-sync-user` has commented on the issue after the `Stalebot` GitHub action (which triggered the removal of the `stale` label) I’ll close this issue for now. Please let us know if you think this issue needs to be reopened, we'll gladly do so. Thank you!
