### ISSUE TITLE
ETP option in Reload contextual menu is truncated in French

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla-mobile/firefox-ios#6867]
“Reload Without Tracking Protection” option in reload contextual menu is truncated in French

Full string is “Actualiser sans protection contre le pistage“
Same with “Reload With Tracking Protection” (Actualiser avec la protection contre le pistage)

![IMG_CF288DA5D79A-1](https://user-images.githubusercontent.com/1294206/85739050-64f2cd80-b6f8-11ea-97a2-025400c82a23.jpeg)

### Device & build information
* Device: iPhone X
* Build version: 27.0 (18383)

**Comment by SimonBasca** [comment]
Verified fix on iPhone SE (11.4) on master 01045340 on EN. The text reflows to the next line (with the same text size)
Noted: Checked on a small screen device because on main 01045340 there is no localization.
