### ISSUE TITLE
FXIOS-559 ⁃ Extraneous vertical slashes in main nav UI

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#6878]
Steps to reproduce:

Latest update seems to add extraneous vertical slashes to the UI that look like a bug/error as it is very cluttered.

There is no reason to have the vertical slash the shield and lock are separate icons, as is the reader button and 3 dots.

Please re-examine the UI/UX here as it is terribly cluttered and serves only to make main nav UI seem busy.

It does not contribute to an easy to navigate UI as now there is just so much happening there

Please disable this or give me the option of disabling.

Screenshot: 
https://bugzilla.mozilla.org/attachment.cgi?id=9159782

Requested via : https://bugzilla.mozilla.org/show_bug.cgi?id=1648842

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2479)

**Comment by garvankeeley** [comment]
I think the color on these may have changed at some point, they were likely less noticeable before but have always been there.
