### ISSUE TITLE
FXIOS-561 ⁃ Remove Adjust

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-ios#6882]
**Vision**

Adjust has been removed from Firefox for iOS as it may cause confusion over what user data is being collected

**Acceptance Criteria**

* Adjust has been removed
* Confirm link pointing users to monitor still work
  * `firefox://open-url?url=https://monitor.firefox.com?utm_source=leanplum-push-notification-EN-FreshlyLapsed-Monitor-v1`
  * `firefox://open-url?url=https://monitor.firefox.com`
* Confirm links from website to the app store still work https://www.mozilla.org/en-CA/firefox/mobile/
* Documentation (including our privacy policy) has been updated to reflect changes

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-561)

**Comment by csuciu** [comment]
We managed to verify that the following is working:
*Confirm link pointing users to monitor still work
 *firefox://open-url?url=https://monitor.firefox.com?utm_source=leanplum-push-notification-EN-FreshlyLapsed-Monitor-v1
 *firefox://open-url?url=https://monitor.firefox.com
*Confirm links from website to the app store still work https://www.mozilla.org/en-CA/firefox/mobile/

Regarding the documentation, "Adjust" is still mentioned in the "Privacy Policy". Not sure what other docs should be checked. @athomasmoz can you please clarify this.
