### ISSUE TITLE
Remove SwiftyJSON Dependency

### ISSUE THREAD

**Issue by nbhasin2** [mozilla-mobile/firefox-ios#6885]
Remove the SwiftyJSON dependency as iOS JSON parsing is good enough that we don't really need SwiftyJSON which hasn't been updated in a while. The following files has SwiftyJSON imports:

* \[ ] `SyncAuthState.swift`
* \[ ] `TokenServerToken.swift`
* \[ ] `PushClient.swift`
* \[ ] `PushRegistrationAPI.swift`
* \[ ] `PushRemoteError.swift`
* \[ ] `PushRegistration.swift`
* \[ ] `JSONExtensions.swift`
* \[ ] `Functions.swift`
* \[ ] `KeychainCache.swift`
* \[ ] `KeychainStore.swift`
* \[ ] `NetworkUtils.swift`
* \[ ] `RemoteDevices.swift`
* \[ ] `Clients.swift`
* \[ ] `SyncQueue.swift`
* \[ ] `SQLiteHistoryFavicons.swift`
* \[ ] `SQLiteRemoteClientsAndTabs.swift`
* \[ ] `ClientsSynchronizer.swift`
* \[ ] `HistorySynchronizer.swift`
* \[ ] `Info.swift`
* \[ ] `SyncMeta.swift`
* \[ ] `State.swift`
* \[ ] `EnvelopeJSON.swift`
* \[ ] `EncryptedJSON.swift`
* \[ ] `CleartextPayloadJSON.swift`
* \[ ] `KeysPayload.swift`
* \[ ] `ClientPayload.swift`
* \[ ] `HistoryPayload.swift`
* \[ ] `LoginPayload.swift`
* \[ ] `TabsPayload.swift`
* \[ ] `SyncTelemetryUtils.swift`
* \[ ] `Keys.swift`
* \[ ] `StorageClient.swift`
* \[ ] `SyncTelemetry.swift`
* \[ ] `FxATelemetryTests.swift`
* \[ ] `SyncCommandsTests.swift`
* \[ ] `Mocking.swift`
* \[ ] `MockSyncServer.swift`
* \[ ] `HistorySyncronizerTests.swift`
* \[ ] `InfoTests.swift`
* \[ ] `MetaGlobalTests.swift`
* \[ ] `RecordTests.swift`
* \[ ] `BatchingClientTests.swift`
* \[ ] `StorageClientTests,swift`

It seems not all files with import use SwiftyJSON. First task is to clean up imports of SwiftyJSON. Then we can create subsequent task to remove SwiftyJSON in particular files.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2480)

**Comment by lmarceau** [comment]
By merging the PR the issue was closed 🥲I needed to reopen since there's still other `import SwiftyJSON` in the code that I see. It's good progress thought on this issue thanks to @muhasturk !

**Comment by piofusco** [comment]
I think this needs to be updated. Unless there's something else keeping track?

**Comment by lmarceau** [comment]
I updated the list of remaining files containing SwiftJSON usage. Hopefully didn't miss any, but if we get through this list we should be in good shape to remove this dependency.

If anyone wants to start working on this issue, I think starting with SyncTelemetryUtils and SyncTelemetry could be a good place to start. We should be able to write unit tests before removing the SwiftyJSON dependency in that area to be then able to modify this part of the code with confidence. Let me know if any more detail is needed on this issue.

**Comment by data-sync-user** [comment]
➤ Laurie Marceau commented:

Closing since this work is tracked with epic https://mozilla-hub.atlassian.net/browse/FXIOS-5856 ( https://mozilla-hub.atlassian.net/browse/FXIOS-5856|smart-link )
