### ISSUE TITLE
[Regression] Bookmarks are not displayed after changing text size from iOS settings

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#6891]
## Steps to reproduce
1. Open bookmarks panel
2. Go to iOS settings and change the text size
3. Go back to Firefox

### Expected behavior
- Bookmarks should have increased font size
### Actual behavior
- Bookmarks are not displayed. After switching the panel the bookmarks will be displayed.
### Device & build information
* Device: iPhone XS max (13.4)
* Build version: main 89b961b
### Notes
- Regression from #6271
Attachments: 
[Text size issue.mov.zip](https://github.com/mozilla-mobile/firefox-ios/files/4850565/Text.size.issue.mov.zip)

**Comment by garvankeeley** [comment]
Can you re-check on master? 5ede4687199b1e0b104f128a8bbb46491707cfd9 might fix this

**Comment by SimonBasca** [comment]
This is no longer reproducible on latest main f7c9bf7ccf
