### ISSUE TITLE
[iPad] Increase spacing between "New Search" text and "Go to copied link"

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#6892]
## Steps to reproduce
1. Go to Today Widget on iPad
### Expected behavior
- Spacing should be increased to better differentiate "New Search" text and "Go to copied link"
### Actual behavior
Spacing between "New Search" text and "Go to copied link" is small.
### Device & build information
* Device: iPad Pro 11 inch (13.4
* Build version: main 89b961b1ce
### Notes
This seems to be iPad specific. On iPhone the spacing looks good.
Attachments: 
![Screen Shot 2020-06-30 at 12 55 16 PM](https://user-images.githubusercontent.com/32130829/86113292-bb358700-bad1-11ea-87e7-0ae48e1eb541.png)

**Comment by noorhashem** [comment]
Issue is no longer relevant because design changed and got implemented. we are using a new go to copied button for next release.
