### ISSUE TITLE
New Tab Button UI (landscape)

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-ios#6893]
### Vision

As a user viewing a webpage, I want a button to start a brand new search in a new tab so that I can quick start another search while keeping my current tab open for later

### Acceptance Criteria

* A new tab button has been added to nav bar in landscape mode [spec](https://docs.google.com/document/d/1n0UDbk2UexFB360uoGLwIvjkaMaQ_ZyXmmLTigBfJ3g/edit#heading=h.p1cuc1sh5ua) (landscape only)
  * New tab button on toolbar in landscape mode
  * Button opens to a new tab with the keyboard up, ready to type in URL bar
* Ensure a11y standards are met

### Not included

* Solution for portrait mode will be a separate ticket
* Telemetry in #6886

**Comment by nbhasin2** [comment]
@isabelrios @SimonBasca I did a local accessibility test on my simulator and things seemed fine. If you find anything related to ➕ button on the URL bar in landscape mode do let me.

**Comment by SimonBasca** [comment]
Verified fixed.
Tested on iPhone Xr (13.5), iPhone SE (11.4), iPhone 8 (13.5), iPad Pro 3rd gen (13.4) on main 340e7b534.

**Comment by SimonBasca** [comment]
@nbhasin2 I found this minor issue related to the New Tab Button UI (landscape) https://github.com/mozilla-mobile/firefox-ios/issues/6987. Feel free to close it if you feel that it's not an issue.
