### ISSUE TITLE
Data Deletion Evaluation for Focus

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-ios#6894]
**Vision**

Confirm current Focus iOS approach allows user to delete data

**Acceptance Criteria**

* Determination on whether additional work is needed to enable users to delete all their data in Focus

**Comment by kaylagalway** [comment]
We do need to make changes to Focus in order for users to delete any previously collected data.

In Firefox Focus there is currently a stop collecting data button. When you click it and you're using legacy telemetry, it doesn't delete the data, it just stops collecting it and rotates the client id.  

To remedy this, we would need to incorporate the Glean framework into Firefox Focus and add the same deletion ping that was added to Firefox iOS. 

@athomasmoz @jevans-mozilla
