### ISSUE TITLE
Determine impact of new IDFA rules iOS14

### ISSUE THREAD

**Issue by nbhasin2** [mozilla-mobile/firefox-ios#6898]
Previously, IDFA was turned on for users by default and had to be manually turned off. With iOS 14, that is no longer the case.

Instead, users must opt-in to use IDFA. When they do, they’ll receive a permission dialogue asking for permission to “track you across apps and websites owned by other companies.”

Find out how this affects iOS Firefox and libs we currently use?

**Comment by hlsoto** [comment]
test comment to see if/when it appears in the "synced" Jira ticket

**Comment by nbhasin2** [comment]
I have summarized IDFA changes for iOS 14 in the following article 

https://medium.com/@nish.bhasin/how-to-get-idfa-in-ios14-54f7ea02aa42

**Comment by data-sync-user** [comment]
➤ Hilda Soto commented:

testing comment to see how it appears in GitHub
