### ISSUE TITLE
Best Buy website won't load

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-ios#6909]
## Steps to reproduce

1. Google Best Buy in Canada
2. Open search result for www.bestbuy.ca/en-ca

### Expected behavior

Best Buy homepage loads and is usable

### Actual behavior

Only a few elements on the page load

### Device & build information
* Device: iPhone 11
* Build version: 0.0.1

### Notes
Attachments:

**Comment by athomasmoz** [comment]
@SimonBasca can I ask you to try reproducing this? I think it could be a high priority if the underlying issue affects other sites as well

**Comment by pmlarocque** [comment]
Just a note that it was doing the same thing in the previous version.

Sometimes it will load but very slowly. Something it will crash the whole browser and you'll need to quit firefox and restart (app will become unresponsive)

That being said, I have the same behavior in ios safari. Think it is more a problem with bestbuy site than firefox itself.

**Comment by SimonBasca** [comment]
Tested on latest main c9eedf6 and v27.0 (18428) on iPhone Xr (13.5). I was unable to reproduce any crash but I did experience some very laggy scrolling and page not fully loading behavior which seems to be related to www.bestbuy.ca/en-ca and not Firefox iOS. The same behavior seems to be present in Safari only on www.bestbuy.ca/en-ca.

**Comment by athomasmoz** [comment]
Thank you for testing. Given the same issue exists on Safari and its expected that the fix needs to be on the website's side, I'm closing the ticket.
