### ISSUE TITLE
Investigate Opportunities to Reduce Startup Time

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-ios#6915]
**Vision**

As a user, I want Firefox to open quickly, so that I can run a search and find an answer while on the go

----

**Acceptance Criteria**

* Document benchmark statistics on what we should be aiming for (perceived and real)
* Documented ideas for reducing startup time
* Ideas include estimated impact, effort, and any caveats

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2484)

**Comment by tsuiyuenhong** [comment]
[Improving iOS Startup Performance with Binary Layout Optimizations]( https://www.facebook.com/atscaleevents/videos/664302790740440/)

**Comment by garvankeeley** [comment]
Our main opportunity is to reduce the impact of adding glean, which is tracked here https://bugzilla.mozilla.org/show_bug.cgi?id=1637539

**Comment by garvankeeley** [comment]
We should also switch our own build from having dylibs for:
Account.framework/       Shared.framework/        Storage.framework/       Sync.framework/          SyncTelemetry.framework/

This then means app extensions will have to link in sets of files, which isn't terrible.

**Comment by athomasmoz** [comment]
@garvankeeley to create tickets for the items in the comments
