### ISSUE TITLE
FXIOS-587 ⁃ Search Engine Logo

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-ios#6917]
**Vision**

As a user, I want some indication that I can search directly in the URL bar, so I don’t need to visit my search engine landing page first

**Acceptance Criteria**

* When the address bar is blank and not selected: a search provider icon should appear before the label “Search or enter address”. This icon helps indicate the fact that this space can be utilised for informational searches
* When you are on a webpage and the URL bar is in the search bar; the search provider icon is not shown
* This functionality is consistent on iPhone and iPad
* Behaviour and design match [spec](https://www.figma.com/file/lfgj15zbNkL9Pp4hdZGJgp/Proton-Mobile-UI?node-id=104%3A19549)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-587)

**Comment by kaylagalway** [comment]
Are there assets for each search engine logo? @athomasmoz

**Comment by data-sync-user** [comment]
➤ Ashley Thomas commented:

Notes from UX/eng collab:

  * We will maintain existing functionality for clicking on an alternate search engine for this ticket - when you click the search engine, it will execute with the terms already in the search bar
  * Additional ticket needs to count clicks on alternate search engines

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verified fix on main 99a9e5e2a02.
