### ISSUE TITLE
FXIOS-588 ⁃ Open Tab in Attentive Mode

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-ios#6918]
**Vision**

As a user, I want the keyboard to come up whenever I open a new tab, so that I can start typing my search in as few steps as possible

**Acceptance Criteria**

* When a user opens the new tab page, the URL bar is focused (and keyboard is up)
* Clicking the back arrow will dismiss the keyboard and unfocus the search bar
* Scrolling the new tab page will dismiss the keyboard and unfocus the search bar
* Should be added for both iPhone and iPad
* [Spec](https://docs.google.com/document/d/131M_To14-n551H7CUnOtL7JUO2E8H2awRBgkJMW4CFY/edit#heading=h.fsrg6zz06qoy) (attentive mode)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2485)

**Comment by athomasmoz** [comment]
Confirmed that an A/B test is not needed for this one. Removing question from description

**Comment by puresick** [comment]
Maybe a setting to this would be useful if someone does not like this behavior, i.e. does not want to have the searchbar focused and the keyboard shown on a new tab?

**Comment by data-sync-user** [comment]
➤ Jeremy Evans commented:

Could use investigation ticket to determine the code  health around keyboard popup

**Comment by data-sync-user** [comment]
➤ Ashley Thomas commented:

Need to investigate how we can unfocus the search bar when scrolling? [~jboek@mozilla.com] will take a look in spare cycles before planning

**Comment by wachabaha** [comment]
- @![image](https://user-images.githubusercontent.com/69654154/111129334-41b5ca00-8576-11eb-8526-b391647b6912.jpeg)
