### ISSUE TITLE
Not syncing all passwords in my ios device

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#6921]
Steps to reproduce:

1. Sign in on desktop
2. Sign in on mobile (iPhone)
3. Sync

Actual results:

When using app on mobile

    all tabs and bookmark synced correctly
    NOT all user and passwords were synced

Expected results:

Every user and pw must have been synced

Device: iPhone SE (2020)
iOS version: 13.5.1
Via Bugzilla : https://bugzilla.mozilla.org/show_bug.cgi?id=1649814

**Comment by SimonBasca** [comment]
We were unable to reproduce this issue but we will still monitor it and try to reproduce.

**Comment by athomasmoz** [comment]
Closing as not reproducible. Please re-open if it happens again
