### ISSUE TITLE
FXIOS-591 ⁃ Sending multiple tabs to Firefox for iOS only sends one of the tabs

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#6922]
Steps to reproduce:

    Select 4 tabs on Firefox on my laptop.
    Right-click on the last tab
    Click "send 4 tabs to device"
    Choose my iPhone from the list

Actual results:

Only one of the tabs gets sent to my iPhone. The other three don't show up.

Expected results:

All four tabs should have been sent to my iPhone.

Bugzilla: 
https://bugzilla.mozilla.org/show_bug.cgi?id=1650283

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2487)

**Comment by SimonBasca** [comment]
QA Note:
- After repeating the STR a second time, I don't receive any tab, only four "Tap to Begin" push notifications.
- Trying to send a tab at a time still works.

**Comment by athomasmoz** [comment]
Need to get debugging info and then send to Sync team
