### ISSUE TITLE
Amazon - The text input field is offset and partially covers the text

### ISSUE THREAD

**Issue by BigSamSampson** [mozilla-mobile/firefox-ios#6924]
## Steps to reproduce
1. Open Amazon.com
2. Sign In 
3. Search for "YETI Rambler 20 oz Tumbler" in the header or the page
4. Open product 
5. Select Color: Camo (the second option color in list of colors)
6. Tap on "Add to Wedding Registry" Button at the right side of the screen 
7. Enter text in input fields
### Expected behavior
The text should fit into the input fields
### Actual behavior
The text input fields are offset and partially cover the text.
### Device & build information
* Device:  Apple iPad 5 (2017) - iPadOS 13.5.1, Wi-Fi
* Build version: 22.0 (17157)
### Notes
Attachments: 

![Bug4511627_IMG_0756](https://user-images.githubusercontent.com/66958331/86807941-07109f00-c083-11ea-853e-5b1df30202b3.png)

**Comment by athomasmoz** [comment]
Thanks for logging. Unfortunately, this is not something we can fix in our side.
