### ISSUE TITLE
FXIOS-594 ⁃ [UX] Homescreen Widget

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-ios#6925]
**Vision**

Add useful functionality to the users home screen to help them run quick lookups and complete their common tasks

**Background**

To complete a common task in the browser right now, users need to find the app on their homescreen, open it, and navigate to the site they want / enter a search. Apple’s new iOS widgets allow us to pull the most used functionality right to a users homescreen and update it based on the time of day. 

How might we enable users to start their most common tasks directly from their homescreen

**Acceptance Criteria**

* Design created for today widget that provides users value from Firefox directly on their homescreen

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-594)

**Comment by brampitoyo** [comment]
I am assigning this issue to @AmyYLee.

**Comment by data-sync-user** [comment]
➤ Ashley Thomas commented:

Current mocks (in progress) https://app.abstract.com/share/6eb2f2ec-3975-455b-9770-9488d05d8b5c?mode=design&sha=f8080095340ff01b249ebc94b1169f85dfdbca3f
