### ISSUE TITLE
FXIOS-595 ⁃ [Focus] youtube says browser "not supported"

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-ios#6928]
https://github.com/mozilla-mobile/focus-ios/issues/1707

Our approach on Firefox was to change the UA on iPad.

**Comment by jevans-mozilla** [comment]
unable to reproduce, could QA see if this is still an active issue?

**Comment by SimonBasca** [comment]
Not reproducible on sim iPhone 11 build version 294e9e3346549.
