### ISSUE TITLE
FXIOS-599 ⁃ [Focus] Submit Focus as Default Browser

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-ios#6929]
**Vision**

As a user, I can set Focus as my default browser

**Acceptance Criteria**

* Users can set focus as their default browser

**Tasks**

* Submit up to test flight

[https://github.com/mozilla-mobile/focus-ios/issues/1709](https://github.com/mozilla-mobile/focus-ios/issues/1709)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-599)

**Comment by data-sync-user** [comment]
➤ Ashley Thomas commented:

We received approval from Apple. Remaining is to add entitlements and create a build

**Comment by boek** [comment]
We now have Bitrise automatically creating a build whenever we tag a new release. Current build is available on Testflight with the default browser entitlement

**Comment by stevenphaedonos** [comment]
Would it be possible to be granted access to the TestFlight? I am aware of https://www.mozilla.org/en-US/firefox/ios/testflight/ but could not find the Focus equivalent.

**Comment by SimonBasca** [comment]
Verified fix on 8.1.8 (4098)
