### ISSUE TITLE
FXIOS-598 ⁃ [Focus] Support for iOS 14

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-ios#6930]
https://github.com/mozilla-mobile/focus-ios/issues/1710

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-598)

**Comment by SimonBasca** [comment]
Currently we have a issue an issue that is blocking us from building Focus for iOS. As soon as issue https://github.com/mozilla-mobile/firefox-ios/issues/6981#issuecomment-674785132 is fixed we can start testing the support for iOS 14.

**Comment by SimonBasca** [comment]
Verified fixed on 8.5.1 (4084). 
Tested core functionality works on iOS 14
Identified issues with Focus on iOS 14 but none of them are iOS 14 specific.

**Comment by athomasmoz** [comment]
Thanks, closing as verified
