### ISSUE TITLE
[Today Widget] Go to copied link

### ISSUE THREAD

**Issue by brampitoyo** [mozilla-mobile/firefox-ios#6935]
### Why/User Benefit/User Problem

- All users: I want to open a link or search for a keyword that I have copied to my clipboard.
- iOS 14 users: I want to do these things, and still know that Firefox protects my privacy by only reading the clipboard when it needs to.

### Behaviour

- The widget will be less smart: it no longer shows URL
    - On iOS 14, showing the URL necessarily involves Firefox reading the clipboard. When this happens, the system will show a heads-up notification. When shown repeatedly, these notifications are not only annoying, they also breach users’ sense of trust and privacy
    - On iOS 13 and below, the design will follow the example that iOS 14 has set. This way, we only collect the minimum amount of data required to be useful
- When the widget is tapped, the same thing should happen as they currently do today
    - On iOS 14, the system will show a heads-up notification: “Firefox pasted from [Origin_App]”
    - On iOS 13 and below, the system will not show this notification

### Visual Design

“Go to copied link” should look like another circle button – aligned with the other three widget items.

<img width="375" src="https://user-images.githubusercontent.com/51007/86866106-6d99c980-c124-11ea-90e5-01edf792d1ca.png"> <img width="375" src="https://user-images.githubusercontent.com/51007/86868316-91f7a500-c128-11ea-94c3-d7e5d8c3d04f.png">

Size: 5

**Comment by brampitoyo** [comment]
CC @noorhashem & @nbhasin2.

**Comment by noorhashem** [comment]
@brampitoyo so after discussions with Nishant, we see that we can only read the clipboard for URLs once the user clicks the button so it's user-inflected and we take their consent to read into the clipboard instead of reading it every time the view re-appear. the notification will keep on showing on any occasion you read the clipboard so it's unavoidable.

**Comment by noorhashem** [comment]
@brampitoyo  can you send me the assets for the new button please?

**Comment by brampitoyo** [comment]
@noorhashem We have a similar-looking asset currently used in our Today View Widget to indicate “Go to copied link”:

<img width="320" src="https://user-images.githubusercontent.com/51007/87259437-6cd7ad80-c4ff-11ea-8a39-01d829966d76.jpeg">

Let’s reuse this icon and not come up with a new one.

**Comment by noorhashem** [comment]
@brampitoyo  can I have the pdf file as you did with the search and private search last time with the rounded button ? I only have the standalone copy icon right now, I can make the rounded button programmatically but would be faster and more polished to just use the asset.

**Comment by brampitoyo** [comment]
@noorhashem For sure! Sorry for the delay. Here’s the PDF file for this asset.

[go-to-copied-link.pdf](https://github.com/mozilla-mobile/firefox-ios/files/4916903/go-to-copied-link.pdf)

**Comment by noorhashem** [comment]
@brampitoyo  thanks a lot! I noticed that in the new dark mode mockups, you had the icons in white ->  turn into a black version (new search & copied link) can you send me the dark versions as well, since the last mockup had the same icons in both light/dark mode so i didn't change icons when modes changed, just changed texts.

**Comment by athomasmoz** [comment]
@brampitoyo What should happen where there is no URL in the clipboard? (ie. don't show button if no URL in clipboard / show notification if clicked)

**Comment by brampitoyo** [comment]
@noorhashem I see!

Would you like dark icons for the search asset, as well? Sorry, I thought that you’d be able to easily change the value!

They are both here:

- [search-dark.pdf](https://github.com/mozilla-mobile/firefox-ios/files/4922833/search-dark.pdf)
- [go-to-copied-link-dark.pdf](https://github.com/mozilla-mobile/firefox-ios/files/4922834/go-to-copied-link-dark.pdf)

@athomasmoz When Noor and I talked last week, we think that we can make the icon disappear (e.g. don’t show asset) if there's nothing in the toolbar.

Now, I’m not so sure anymore. If the act of reading the clipboard will cause a system notification to appear (“Firefox pasted from [App_Name], do we still want to do it in order to determine whether to show the icon or not?

If we can’t do it in a way that doesn’t make people feel “scared”, I propose showing this “Go to link” button at all times. If there is nothing on the clipboard, then we simply do nothing. It feels kind of “dumb” that way, but we may also avoid the need to read the clipboard until the point where we really need it (ie. when Firefox opens and the clipboard content needs to be pasted).

@noorhashem @nbhasin2 Is there a way for us to determine whether the clipboard is empty or not empty, without triggering the system notification?

**Comment by noorhashem** [comment]
@brampitoyo I could only change values if I had transparent Icons, I can then invert the colors, but I couldn't with the current designs.

as for the button status in case nothing was on clipboard, there is a function that can check if there's nothing in the clipboard or not and it doesn't invoke the notification. we'll use that and hide it if there is nothing in clipboard.

**Comment by brampitoyo** [comment]
> […] there is a function that can check if there's nothing in the clipboard or not and it doesn't invoke the notification. we'll use that and hide it if there is nothing in clipboard and test it out.

@noorhashem That sounds excellent. Thanks!

**Comment by SimonBasca** [comment]
Verified fixed on 28.0 (18809). Tested on iPhone XS Max (14.0b2), iPhone Xr (13.5), iPhone SE (11.4).
