### ISSUE TITLE
Today Widget Compatibility on iOS 14

### ISSUE THREAD

**Issue by brampitoyo** [mozilla-mobile/firefox-ios#6936]
### Why/User Benefit/User Problem

Firefox has many shortcuts that make my life easier, and I want to quickly access them from my home screen in iOS 14.

### Visual Design

It’s tempting to port our iOS 13 (left) visual design to iOS 14 (right) straight up, without any modification other than to reduce the text size of the button labels.

<img width="375" src="https://user-images.githubusercontent.com/51007/86869649-0af7fc00-c12b-11ea-8c69-c4be9a84b020.png"> <img width="375" src="https://user-images.githubusercontent.com/51007/86870082-dafd2880-c12b-11ea-87bb-ee62219245a1.png">

Right away, you’ll notice a few problems:

1. Mystery meat navigation. It’s not clear what each icon does, because it’s not labelled.
2. When seen alongside other icons on the home screen, the items look too much like app icons, and not enough like actions.

Taking those factors into consideration, I think that we should think about these things before moving forward:

1. Think of what actions would have value on the home screen. Those that fit the home screen may be different from those that fit the Today View.
2. Match the look and feel to iOS 14’s updated visual style.

### Strawman mock

<img width="375" src="https://user-images.githubusercontent.com/51007/86870022-ba34d300-c12b-11ea-8890-280436fac9d3.png">

**Comment by brampitoyo** [comment]
CC @noorhashem @nbhasin2

**Comment by noorhashem** [comment]
@brampitoyo  I do agree with you regarding this `When seen alongside other icons on the home screen, the items look too much like app icons, and not enough like actions.`

so maybe we can go with the new mockups to give the impression that's an action.

**Comment by brampitoyo** [comment]
CC @AmyYLee

**Comment by athomasmoz** [comment]
Closing this ticket as design has been completed. Implementation will be done in #7073
