### ISSUE TITLE
 Whatsapp.com - White line appears on the main page after changing device orientation

### ISSUE THREAD

**Issue by BigSamSampson** [mozilla-mobile/firefox-ios#6937]
## Steps to reproduce
1. Open Firefox.
2. Tap on "Search or enter address" field.
3. Type address "whatsapp.com".
4. Tap on "go" button.
5. Turn device into landscape orientation.
6. Turn device into portrait orientation.
### Expected behavior
Main page is displayed correctly and fit the area of browser.
### Actual behavior
White line appears at the right side of the main page after changing device orientation and main page does not fit the area of a browser.
### Device & build information
* Device: Apple iPhone 6S - iOS 13.5.1, Wi-Fi

* Build version: 22.0 (17157)
### Notes
Attachments: 

![Bug4510976_photo_2020-06-18_16-34-24](https://user-images.githubusercontent.com/66958331/86885075-4da2df80-c0fd-11ea-8829-f448a598980b.jpg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2490)

**Comment by muhasturk** [comment]
What do you mean "Open Yanni app." on first step?

![image](https://user-images.githubusercontent.com/4077401/86949839-ef571a80-c157-11ea-9c3e-fa2c6b4b0dea.png)

**Comment by garvankeeley** [comment]
I wonder if Safari and Chrome do the same, might be a site compat issue

**Comment by lmarceau** [comment]
@csuciu @SimonBasca This seems fine on latest main 7bf455c419d93d73e76fa1cf268c8c67eca743e6. Can this be retested?

https://user-images.githubusercontent.com/11338480/173401926-4898f03e-4faf-4436-9667-01ebe8cdb718.mp4

**Comment by csuciu** [comment]
No longer reproducible on latest main. Closing.
