### ISSUE TITLE
Update wiki docs related to testing

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/firefox-ios#6941]
There is old info in several docs:
https://github.com/mozilla-mobile/firefox-ios/wiki/Writing-a-first-XCUI-test-from-the-scratch
https://github.com/mozilla-mobile/firefox-ios/wiki/Automated-UI-Tests
https://github.com/mozilla-mobile/firefox-ios/wiki/FxScreenGraph-and-XCUITest
https://github.com/mozilla-mobile/firefox-ios/wiki/Bitrise-General-Info
https://github.com/mozilla-mobile/firefox-ios/wiki/Screenshots-for-Localization

I would like to made the changes there to have more reliable information

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2493)

**Comment by lmarceau** [comment]
Since only `data-sync-user` has commented on the issue after the `Stalebot` GitHub action (which triggered the removal of the `stale` label) I’ll close this issue for now. Please let us know if you think this issue needs to be reopened, we'll gladly do so. Thank you!
