### ISSUE TITLE
HTML Injection on ReaderMode Page (needs to be in WKContentWorld)

### ISSUE THREAD

**Issue by garvankeeley** [mozilla-mobile/firefox-ios#6946]
Moved from https://bugzilla.mozilla.org/show_bug.cgi?id=1633140

See the original bug for full repro steps. Because reader mode is in the JS context of the page, any JS build-in functions can be overriden to mess with the reader mode JS. This is a known limitation of JS injection with WKWebView, and is not considered a sec issue in this case.

The iOS 14 WKContentWorld should resolve this.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2494)

**Comment by diracdeltas** [comment]
@garvankeeley this is how Brave is proposing to fix this: https://github.com/brave/brave-ios/pull/4209/files
