### ISSUE TITLE
Crash After Opening The Folder In Bookmarks And Pressing The Save Button

### ISSUE THREAD

**Issue by BigSamSampson** [mozilla-mobile/firefox-ios#6948]
## Steps to reproduce
Folders are opened by coming to the Bookmarks area
The opened folders are clicked and rearranged.
It is relocated again.
Press the Save button

### Expected behavior
It is expected to work as targed
### Actual behavior
Crash After Opening The Folder In Bookmarks And Pressing The Save Button
### Device & build information
* Device: Iphone X 
* Build version: ?
### Notes
Attachments: 

[vıdeo.zip](https://github.com/mozilla-mobile/firefox-ios/files/4912219/video.zip)

**Comment by BigSamSampson** [comment]
Vıdeo

**Comment by BigSamSampson** [comment]
Video

**Comment by SimonBasca** [comment]
@BigSamSampson Is this still an issue? You can try adding a video by compressing the video file and by dragging and droping it in a comment or by uploading the video and pasting the link.

**Comment by BigSamSampson** [comment]
@SimonBasca Yes This problem still continues.

**Comment by SimonBasca** [comment]
Verified fix on main d05c904702490
