### ISSUE TITLE
FXIOS-618 ⁃ Incorrect mime type for .usdz and .reality files, resulting in AR QuickLook not working

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#6963]
Steps to reproduce:

1. Open https://modelviewer.dev/examples/augmented-reality.html
2. Select ... menu and "Request Mobile Site"
3. Click the little AR button

For Chrome, the fix consisted of marking USDZ files (and .REALITY) files with the correct mime type so that iOS detects it as a proper file to invoke QuickLook for.

This seems to be related to https://bugzilla.mozilla.org/show_bug.cgi?id=1528147 which is marked as "FIXED" but the behaviour is still incorrect.

Actual results:

Firefox downloads the USDZ file

Expected results:

AR QuickLook opens and shows 3D model in AR
Works in Safari
Works in Chrome on iOS

Bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1652011

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-618)

**Comment by SimonBasca** [comment]
This issue is still reproducible on latest main d05c90470. @garvankeeley @q2r5 can you please take a look and let me know if I should log a new issue or re-open this one.

**Comment by garvankeeley** [comment]
Let's re-open until we have the fix confirmed.

**Comment by SimonBasca** [comment]
Verified fix on f455fe6d542b and 28.2 (2470)
