### ISSUE TITLE
FXIOS-621 ⁃ [XCUITests] Update tests on main to work on iOS14

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/firefox-ios#6969]
There was a first run of automated tests on that branch and there are some issues to fix with them. 

1- The Copy cell in the share sheet menu has changed to a button. Example:

app.collectionViews.cells["Copy"] has changed to app.collectionViews.buttons["Copy"]

2- There is a new toast shown when text has been copied. This toast is shown at the top of the app so it overlaps with some buttons. Tests are failing finding those buttons. We would need to wait until that toast disappears to continue with the test. Some examples:

Search and Save buttons
<img width="315" alt="Captura de pantalla 2020-07-13 a las 10 02 00" src="https://user-images.githubusercontent.com/1897507/87443805-4183ba00-c5f6-11ea-977e-a02606241405.png">

Page Action Menu button (here it is already going out but it completely overlaps that button)
<img width="334" alt="Captura de pantalla 2020-07-13 a las 9 54 32" src="https://user-images.githubusercontent.com/1897507/87443841-4fd1d600-c5f6-11ea-9a9f-a470b4127350.png">

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-621)

**Comment by isabelrios** [comment]
Closing this one since the iOS14 branch has been merged into main, tests are working on main. If there are new issues on iOS14 once main is moved to that environment, let's open new issues

**Comment by isabelrios** [comment]
Re-opening this issue. Tests are working on main while it uses iOS 13.5/13.6 sims but some tests will fail when we update the sims to iOS14.

Changes described in the description are still needed.
But now we can follow a new approach. So that we can keep working on iOS 14 stuff without breaking current tests, let's use a condition, for example for the share sheet menu that has changed:
```
 if #available(iOS 14.0, *) {
            waitForExistence(app.collectionViews.buttons["Copy"], timeout: 10)
        } else {
            waitForExistence(app.cells["Copy"], timeout: 10)
        }
```
That way we can have tests working on both environments and avoid issues when the transition happens

**Comment by isabelrios** [comment]
There may be other tests affected by the Switch Your Default Browser menu in Homescreen, like for example:
- [testLibraryShortcutHomePage](https://github.com/mozilla-mobile/firefox-ios/blob/main/XCUITests/LibraryTests.swift#L29): this test checks the existence of the Bookmark, Reading List, Download and Sync buttons. Since the new menu takes most of the Homescreen, those buttons are not visible. It would be needed to dismiss it for this test.

**Comment by isabelrios** [comment]
Bitrise failures on iPhone 8, iOS14:
 https://addons-testing.bitrise.io/builds/12973c31e7ae4c7c/testreport/8ef333cf-4ff8-4e96-a945-d8d7e8bd7451/testsuite/0/testcases?status=failed

Let's prioritize them please

**Comment by isabelrios** [comment]
TrackingProtection tests may be affected too, we need the snackbar with the Copied information to dissapear before clicking on the Shield icon.

An easy way to fix that would be to wait until the PAM is shown: 
`waitForExistence(app.buttons["TabLocationView.pageOptionsButton"])`

**Comment by SimonBasca** [comment]
NewTabSettingsTest.testChangeNewTabSettingsShowCustomURL() and DataManagementTests.testWebSiteDataEnterFirstTime() are working locally. Let's investigate leave them for now and investigate why are they failing on Bitrise.
