### ISSUE TITLE
Closing one tab in private mode causes the session information to be removed from all other tabs.

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#6979]
Reproduced on (iPhone 8, iOS Version 12.4, Firefox Version 27.0 (18428))

1.) Open a Website in Private Mode
2.) Login to that Website
3.) Open a new private Tab
4.) Close the new Tab
5.) Submit any Form on the Page from Tab1

And you will get thrown back to the login Page of that Site.

Logged via : https://bugzilla.mozilla.org/show_bug.cgi?id=1652658

**Comment by garvankeeley** [comment]
Removing 'P1' as I confirmed this isn't a regression. I can repro the issue.

**Comment by SimonBasca** [comment]
Verified fix on main d05c90470
