### ISSUE TITLE
FXIOS-630 ⁃ Firefox Focus - Fix issue for building on a device

### ISSUE THREAD

**Issue by nbhasin2** [mozilla-mobile/firefox-ios#6981]
Focus has issues related to building on a device. It could very well be an XCode issue but so far needs investigation. 

Early investigation: Development Profiles were expired which have been re-generated but still when building towards a device XCode tries to look for Distribution profiles which should not be the case.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-630)

**Comment by jevans-mozilla** [comment]
This appears to be working for dev team, Can QA check out to see if this is working now?

**Comment by SimonBasca** [comment]
We are still getting a provision profile error. Here is a screenshot from Xcode 11.6 (11E708) when trying to build on actual device. Also Catalin (csuciu@mozilla.com) is getting the same error.

<img width="1278" alt="Screenshot 2020-08-17 at 12 44 41" src="https://user-images.githubusercontent.com/32130829/90383684-268ae680-e089-11ea-8a14-c5d36198a63d.png">

**Comment by athomasmoz** [comment]
@nbhasin2 Heads up, looks like this one is still broken for QA

**Comment by nbhasin2** [comment]
@SimonBasca - Try now to build Focus, if there are issues related to your laptop cert that we can easily fix but this should now build on your device.

**Comment by SimonBasca** [comment]
we are still having issues while building on 11.6 (11E708). Seems to be related to provisioning profiles. Maybe refreshing the certificates might work. 
<img width="1226" alt="Screenshot 2020-09-01 at 14 35 15" src="https://user-images.githubusercontent.com/32130829/91844687-92ac4380-ec60-11ea-9f90-5c6b523afbed.png">
<img width="1144" alt="Screenshot 2020-09-01 at 14 36 39" src="https://user-images.githubusercontent.com/32130829/91844699-96d86100-ec60-11ea-9015-404ca9e98027.png">

**Comment by SimonBasca** [comment]
This is working with 2ade8f3c0b01 on Xcode 11.6 (11E708)
