### ISSUE TITLE
BLOB download handling not working?

### ISSUE THREAD

**Issue by AaronMT** [mozilla-mobile/firefox-ios#6983]
Richard and I are tackling some UI automation. We're using the link provided in [1] which is [2] which should generate a text blob on download link tap but we're not seeing that. No download prompt is initiated (Firefox Desktop will trigger a download prompt with the test-case). Tested on main (30277355b765982626151d4d4be347c4f4c1d26a)

[1] https://github.com/mozilla-mobile/firefox-ios/issues/6465
[2] http://bennadel.github.io/JavaScript-Demos/demos/href-download-text-blob/

Not sure if it's the test-case or an issue with download handling in the app.

**Comment by AaronMT** [comment]
(@garvankeeley – is blob handling fully supported here?)

**Comment by garvankeeley** [comment]
I am using this URL to test it http://bennadel.github.io/JavaScript-Demos/demos/href-download-text-blob/
Long-press on the 'Download Text' button and select download to perform the app's download feature.

**Comment by AaronMT** [comment]
Long-tap to select "Download Link" seems to work.

**Comment by garvankeeley** [comment]
@kaylagalway useful test case in this bug
