### ISSUE TITLE
FXIOS-634 ⁃ Search icons should be displayed on Blank Tab as New Tab

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#6986]
## Preconditions:
- Set New Tab as Blank page
## Steps to reproduce
1. Open a new tab
2. Dismiss the keyboard
### Expected behavior
- Search icons should be displayed.
### Actual behavior
- Reload button is displayed
### Device & build information
* Device: iPhone Xr
* Build version: 340e7b534bb
### Notes
Attachments: 
![Screen Shot 2020-07-16 at 3 00 49 PM](https://user-images.githubusercontent.com/32130829/87668666-28edde00-c775-11ea-8ffd-3a35ea2dbc0c.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-634)

**Comment by nbhasin2** [comment]
https://github.com/mozilla-mobile/firefox-ios/pull/7038 - This PR should fix it.

**Comment by SimonBasca** [comment]
Verified fix on main 15e1359cda38d4c7e9356aef66c7395bcd257e35.
