### ISSUE TITLE
FXIOS-635 ⁃ The URL bar is focused when a custom URL is set to open in a New Tab

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#6987]
## Preconditions
- Set "google.com" as custom URL for New Tab
## Steps to reproduce
1. Change device orientation to landscape
2. Open a new tab via the "+" button
### Expected behavior
- The URL bar should not be focused when opening a new tab when a custom URL is set to open in a New Tab.
### Actual behavior
- The URL bar is focused when a custom URL is set to open in a New Tab.
### Device & build information
* Device: iPhone Xr
* Build version: 340e7b534
### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-635)

**Comment by SimonBasca** [comment]
Note: This should also be fixed when opening a new tab from Today Widget or 3D Touch when a custom URL is set to open in a New Tab.

**Comment by athomasmoz** [comment]
This behaviour should be considered in #6918 as well

**Comment by dominickhera** [comment]
from a quick look into the issue it seems to be stemming from the file `BrowserViewController+TabToolbarDelegate.swift` where the function `tabToolbarDidPressAddNewTab` is calling `focusLocationTextField(forTab: tabManager.selectedTab)` which is causing the app to focus on the url bar every time. 

working on a fix now.

**Comment by dominickhera** [comment]
@SimonBasca (my apologies as this is my first time contributing to the project) are there any other instances where the url bar *should be* focused ? as if there aren't then i can probably just remove that focus call in add new tab.

**Comment by SimonBasca** [comment]
@dominickhera This issue is specific when New Tab is set to open a custom URL. 
The URL bar should not be focused when opening a new tab if New Tab is set to open a custom URL. We need this when we open a New Tab via long press on Firefox logo on home screen (3DTouch) or via Today Widget or when opening a new tab via the "+" button from landscape orientation.

If New Tab is set to "Blank Page" or "Firefox Home" the URL bar should focus when opening a New Tab as specified in #6918

cc @athomasmoz to confirm if we need this behavior.

**Comment by dominickhera** [comment]
Got it, will adjust fix accordingly! Thanks

**Comment by dnarcese** [comment]
This bug has been fixed with attentive mode changes.
