### ISSUE TITLE
[l10n][v28]l10n for release

### ISSUE THREAD

**Issue by Delphine** [mozilla-mobile/firefox-ios#6991]
(CC @nbhasin2)

l10n deadline for v28 is July 23rd, so localizers will be working and testing until then.
On my side, we mostly need screenshots to be updated with the latest strings until that deadline (I think that's something to loop in @isabelrios and/or @JohanLorenzo, because I'm unaware of the files to touch for this).

Concerning adding/removing locales: I can update this issue early July 23rd with the latest information. Current progress of locales can be found here: https://pontoon.mozilla.org/projects/firefox-for-ios/

Note that we don't need to track progress for now as things are still moving a lot (we ship locales once they hit the 20% completion no matter what - so even if they aren't at 100%). The removal/addition of locales should be done on July 23rd once we hit that l10n deadline. Let me know if you have any questions/concerns!

**Comment by Delphine** [comment]
You can find below the current list of locales that can ship with v28. 
Please update this file with the needed locale codes, on both master and v28: https://github.com/mozilla-mobile/firefox-ios/blob/master/shipping_locales.txt
Note I believe there are other files to update as well to reflect this, but I am unaware which ones exactly :) 

Quick breakdown: 
* We're dropping "si" (Sinhala) from builds this time around (community can not support the project anymore and has asked for this). 
* We're adding two locales: "sat-Olck" (Santali) and "Tamazight" ("zgh")

Here is the current list for v28 and master:

af
--
an
anp
ar
ast
az
bg
bn
br
bs
ca
co
cs
cy
da
de
dsb
el
en-CA
en-GB
en-US
eo
es
es-AR
es-CL
es-MX
eu
fa
fi
fr
ga-IE
gd
gl
gu-IN
he
hi-IN
hr
hsb
hu
hy-AM
ia
id
is
it
ja
jv
ka
kab
kk
km
kn
ko
lo
lt
lv
ml
mr
ms
my
nb-NO
ne-NP
nl
nn-NO
oc
or
pa-IN
pl
pt-BR
pt-PT
rm
ro
ru
sat-Olck
ses
sk
sl
sq
su
sv-SE
ta
te
th
tl
tr
uk
ur
uz
vi
zgh
zh-CN
zh-TW

**Comment by isabelrios** [comment]
Thanks @Delphine!

> We're adding two locales: "sat-Olck" (Santali) and "Tamazight" ("zgh")

Both locales are already added to the [file](https://github.com/mozilla-mobile/firefox-ios/blob/main/l10n-screenshots-config.yml) And, there are already screenshots for both locales
I think that's all we need....

**Comment by dnarcese** [comment]
I've update `shipping_locales.txt` as well in #7025

**Comment by Delphine** [comment]
> Thanks @Delphine!
> 
> > We're adding two locales: "sat-Olck" (Santali) and "Tamazight" ("zgh")
> 
> Both locales are already added to the [file](https://github.com/mozilla-mobile/firefox-ios/blob/main/l10n-screenshots-config.yml) And, there are already screenshots for both locales
> I think that's all we need....

Yes, we are good for screenshots. 
Thanks Isabel and Daniela!
