### ISSUE TITLE
FXIOS-639 ⁃ javascript urls incorrectly ask to open in external app

### ISSUE THREAD

**Issue by garvankeeley** [mozilla-mobile/firefox-ios#6995]
## Steps to reproduce
- type in URL bar: "javascript:"
- shows alert asking to 'Open in external app?'

### Expected behavior
- show our standard error page 'A server with the specified hostname not found'

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-639)

**Comment by renatoviana12** [comment]
Can I pick this up?

**Comment by SimonBasca** [comment]
Verified fix on main 5a12ecf69dd

**Comment by fasiha** [comment]
This seems to be happening for me, Firefox Daylight 39.0 (6519), iOS 14.8.1, see video below, with `javascript:alert("hi")` (but I also noticed this with actual bookmarklets):

https://user-images.githubusercontent.com/37649/142347403-48c9f796-3e20-4089-ad88-f4ad9128610b.MP4

**Comment by fasiha** [comment]
Gently pinging @garvankeeley and @SimonBasca, sorry for the spam, wanted to see if this was the right place to report a potential regression (see my [comment above](https://github.com/mozilla-mobile/firefox-ios/issues/6995#issuecomment-972490562)) of this feature, or if I should report it on Jira, or if I should maybe open a new issue?

**Comment by SimonBasca** [comment]
@fasiha thanks for  letting us know. I've logged a new issue here https://github.com/mozilla-mobile/firefox-ios/issues/9546
