### ISSUE TITLE
FXIOS-640 ⁃ Show about:blank in URL bar for window.open

### ISSUE THREAD

**Issue by garvankeeley** [mozilla-mobile/firefox-ios#7000]
https://bugzilla.mozilla.org/show_bug.cgi?id=1634597

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-640)

**Comment by SimonBasca** [comment]
Tested on main 855dca83c on iPhone Xr 13.5

@garvankeeley I am not seeing "about:blank" in URL  after following the STR:
1. Go to blank.html
2. Click "Click me"

Is this the correct behaviour? 

![Picture_2020_08_18T14_46_09_460Z](https://user-images.githubusercontent.com/32130829/90528080-e73cc280-e17a-11ea-8bab-3309879e5ced.jpeg)

**Comment by SimonBasca** [comment]
Fixed on c8e1817
