### ISSUE TITLE
Use JS to Identify when webviews have completely finished rendering for screenshots

### ISSUE THREAD

**Issue by kaylagalway** [mozilla-mobile/firefox-ios#7003]
We currently observe when users navigate within or to a new page with WebKit's delegate function and set an arbitrary dispatch delay before taking a screenshot in order to ideally have the page load in time. With varying connections, the page still will not load completely before a screenshot is taken and the screenshot could appear blank or with a loading icon.

Ideally we would switch to using Javascript to identify when a page's graphics have loaded enough for a screenshot to be taken.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2499)

**Comment by garvankeeley** [comment]
We could use the readyState interactive/completed along with a debounce to use those events to grab a screenshot. Keeping in mind SPA JS (history.pushState nav) like youtube.com won't work with that. See also https://github.com/mozilla-mobile/firefox-ios/wiki/WKWebView-navigation-and-security-considerations
