### ISSUE TITLE
FXIOS-644 ⁃ [Chron Tabs] Tab Tray Navigation Menu

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-ios#7006]
**Vision**

As a Firefox iOS user, I want a navigation menu for different sets of tabs similar to how I navigate in other apps so that I can easily find & move between them

**Acceptance Criteria**

_In Chronological Tabs version_

* Navigation menu added to tab tray that include regular, private, and synced tabs that matches [spec](https://app.abstract.com/share/29777b57-be9d-402c-a0c7-2608b2c16356?mode=design&sha=66fee7d2294d46c941cefeaa4c407f31f8838ec2)
* Current private tabs switcher removed
* Counts tracked for clicking each item in the menu, so we can ensure users are getting value out of having the nav menu in a prime location

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-644)

**Comment by topotropic** [comment]
@dnarcese I updated the design slightly, you should be able to inspect the Abstract file.

Updates:
- bigger thumbnails
- title over two lines
- delete icon in bottom bar on the left

https://share.goabstract.com/39a20292-cc77-43fb-9a04-98662afa5f8b?mode=build&sha=c3081577a7b36a6332013462974065acbf89580e

**Comment by athomasmoz** [comment]
Thanks for the update! Note that the changes have been broken into new tickets:
* bigger thumbnails & title over two lines #7063 
* delete icon in bottom bar on the left #7008

**Comment by dnarcese** [comment]
@topotropic Could you send the pdf of the Synced Tabs icon? It's the only icon we don't yet have in the app.

**Comment by dnarcese** [comment]
@topotropic I am picking up this issue again and wanted to check in on the synced tabs icon

**Comment by dnarcese** [comment]
@brampitoyo are you able to provide the synced tabs icon?

**Comment by brampitoyo** [comment]
@dnarcese For sure!

- [synced-tabs.svg](https://drive.google.com/file/d/1VeQpNE5xbU51Qzv4dEUfpKwaKP7dKZPA/view)
- [synced-tabs.pdf](https://drive.google.com/file/d/1RPENibDM5b8-_pBTDq669K6iZFeRNPEc/view)
