### ISSUE TITLE
FXIOS-645 ⁃ [Chron Tabs] Tab Swipe Menu

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-ios#7007]
**Vision**

As a user, I want an easily discoverable way to perform actions on a tab including share/sent/close, so that I don't need to open each page that I want to act on

**Acceptance Criteria**

_In Chronological Tabs view_

* Swipe menu added to the tab tray ( [spec](https://app.abstract.com/share/29777b57-be9d-402c-a0c7-2608b2c16356?mode=design&sha=66fee7d2294d46c941cefeaa4c407f31f8838ec2))
* Counts added to glean for each of the available actions to determine if they are all needed

**Success Criteria**

We don't see a drop in page (tab) actions after moving to chronological tabs

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-645)

**Comment by csuciu** [comment]
Verified as fixed on v30.0 (3242)
