### ISSUE TITLE
FXIOS-647 ⁃ [Chron Tabs] Trash Can moved to bottom left

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-ios#7008]
**Vision**

Trash can is moved to top right of the tab tray so that users don't accidentally click it and to prepare for the tabs action menu

**Acceptance Criteria**

_In Chronological Tabs view_

* Trash can option moved to bottom left of tabs tray [matching spec](https://app.abstract.com/share/29777b57-be9d-402c-a0c7-2608b2c16356?mode=design&sha=66fee7d2294d46c941cefeaa4c407f31f8838ec2)
* Counts of trash can usage are tracked to better understand tab  behaviour

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-647)

**Comment by SimonBasca** [comment]
Verified fix on "chronological - tabs" branch 5adc3a470. The trash can has been moved as requested.
