### ISSUE TITLE
FXIOS-646 ⁃ [Chron Tabs] "New Tab" copy added to button

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-ios#7009]
**Vision**

As a Firefox for iOS user, I want copy for the plus button on the tab tray so that I'm aware of what it does

**Acceptance Criteria**

* "New Tab" copy added to plus button matching [spec](https://app.abstract.com/share/29777b57-be9d-402c-a0c7-2608b2c16356?mode=design&sha=66fee7d2294d46c941cefeaa4c407f31f8838ec2)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-646)

**Comment by dnarcese** [comment]
This should be done after #7006

**Comment by SimonBasca** [comment]
Verified fix on "chronological - tabs" branch 5adc3a4. The trash can has been moved as requested.
