### ISSUE TITLE
First tour "Sign Up" and "Sign In" follow the same flow

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#7011]
## Steps to reproduce
1. Open First tour from settings
2. Tap "Sign In" or "Sign up"
### Expected behavior
- Tapping "Sign up" should take the user to account creation flow.
- Tapping "Sign in" should take the user to log in flow.
My suggestion would be to add only one button something like "Connect to your Firefox Account".
### Actual behavior
- The user is take to the sign in via QR code flow.
### Device & build information
* Device: iPhone Xr (13.5)
* Build version: main 1c259d6e4e
### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2501)

**Comment by athomasmoz** [comment]
This should be addressed in #6815

**Comment by lmarceau** [comment]
Since only `data-sync-user` has commented on the issue after the `Stalebot` GitHub action (which triggered the removal of the `stale` label) I’ll close this issue for now. Please let us know if you think this issue needs to be reopened, we'll gladly do so. Thank you!
