### ISSUE TITLE
FXIOS-650 ⁃ Pastes from clipboard after closing a tab [iOS 14 Support]

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#7012]
## Preconditions
- Go to settings and enable "Offer to Open Copied link"
## Steps to reproduce
1. Go to Safari and copy a link
2. Go to Firefox Tabs Tray
3. Close the default opened tab

### Device & build information
* Device: iPhone XS Max
* Build version: 14.0b2
### Notes
Similar issue https://github.com/mozilla-mobile/firefox-ios/issues/6932

[Untitled.mov.zip](https://github.com/mozilla-mobile/firefox-ios/files/4958555/Untitled.mov.zip)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2502)

**Comment by garvankeeley** [comment]
I see in the video it keeps showing the message that paste happened
<img width="476" alt="image" src="https://user-images.githubusercontent.com/5495083/88944813-31591500-d25b-11ea-86cb-eb466dd455cb.png">
