### ISSUE TITLE
FXIOS-655 ⁃ [Focus] Upgrade to Glean

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-ios#7019]
**Vision**

Glean has been integrated into Focus, allowing users to delete previously collected data when they turn off "send usage data"

**Acceptance Criteria**

* Basic Glean integration + the legacy ID added to Focus

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-655)

**Comment by data-sync-user** [comment]
➤ Ashley Thomas commented:

[~athomas@mozilla.com] to confirm with Travis on what we need to do with old telemetry

**Comment by data-sync-user** [comment]
➤ Jeremy Evans commented:

https://github.com/mozilla-mobile/firefox-ios/pull/6577 ( https://github.com/mozilla-mobile/firefox-ios/pull/6577 )
This was the original work completed in Firefox

**Comment by data-sync-user** [comment]
➤ Ashley Thomas commented:

Note from Travis: You can just add Glean, but you will need to be sure and record the legacy ID in Glean

**Comment by SimonBasca** [comment]
@athomasmoz any idea on how to test this?

I tried typing in notes "Firefox Focus://glean?tagPings=Simon-glean-Test" and tapping on it to see the device in Glean dashboard. So far that's not working.
