### ISSUE TITLE
Add ability to "reload without caching" (long press gesture on reload button)

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#7024]
Steps to reproduce:

Long press of the reaload button

Actual results:

A menu pops up showing
Request desktop version
Reload without tracking protection

Expected results:

Also allow to reload "without using the cache". Similarly to what Ctrl + F5 does on the desktop version.
This simplifies testing in webdevelopment and is an intuitive approach to desktop behaviour. Instead of having to navigate through the settings and delete all data of a website.

Via : https://bugzilla.mozilla.org/show_bug.cgi?id=1653811

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2505)

**Comment by athomasmoz** [comment]
Idea - do this through a keyboard shortcut, as it's for a very savvy user

**Comment by amereid** [comment]
Hello, is this issue still valid btw? If so i'd like to be assigned this issue if possible.

**Comment by athomasmoz** [comment]
Hi @amereid thanks for offering to help! Yes, this problem is still relevant to solve, however we're testing a change that moves the refresh options into the page actions menu #6847 . Because of that, it might be good to start with the keyboard shortcut suggestion to solve this

**Comment by amereid** [comment]
I started looking at adding a keyboard shortcut for "reloading tab without cache" and i have one question, should tab.reloadFromOrigin() be triggered for a cache-less reload? I'm only wondering because command+r already triggers tab.reload which calls reloadFromOrigin() if there is no error page. This would make the new keyboard shortcut redundant since command+r would behave like the new keyboard shortcut.

**Comment by griffinreding** [comment]
Please close per #6009

**Comment by MincDev** [comment]
> Reopened since needs QA. It can be tested the shortcut appears in the discoverability shortcuts on iPad, and that the shortcuts Ctrl + F5 indeed reload the tabs without cache.

@lmarceau does this require something from my side?

**Comment by lmarceau** [comment]
@MincDev no! Our team of QA will be picking this up shortly to test the changes. Thanks

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Marking as verified fix on 108 (22578). 

Note that the shortcuts are not functional with magic trackpad. This issue is tracked at https://github.com/mozilla-mobile/firefox-ios/issues/12479 ( https://github.com/mozilla-mobile/firefox-ios/issues/12479|smart-link )

**Comment by efojs** [comment]
Hi! Is it in production already? I have iOS 15.0.2, latest Firefox (111.1?) and can't find/see it

**Comment by lmarceau** [comment]
@efojs yes it's supposed to be released. You don't see the shortcut when holding the `cmd` button? Does pressing `ctrl + F5` reloads without cache?

**Comment by efojs** [comment]
> holding the cmd button?

On iOS? Is it for debug mode when paired with computer?
I thought it's for basic usage, just when you want hard reload.

**Comment by lmarceau** [comment]
The "reload without cache" keyboard shortcut works when you have a keyboard paired with your iOS device (either a phone or iPad). If you press `ctrl + F5` it normally reloads without the cache. I was asking the last two questions since you mentioned you couldn't find the said feature.

**Comment by efojs** [comment]
Oh, nice. Thank you. I don't have external keyboard.
I was looking for this: "long press gesture on reload button" (from the issue title).

**Comment by MincDev** [comment]
> Oh, nice. Thank you. I don't have external keyboard.
> 
> I was looking for this: "long press gesture on reload button" (from the issue title).

@efojs this was in my original PR, but the requirement was changed to the keyboard reload.

**Comment by efojs** [comment]
It's a pity. Would be handy to have it on long tap or in the menu

**Comment by lmarceau** [comment]
If you wish you can open another feature request and link to this one, since this one was modified then done/closed. Thank you for raising this!
