### ISSUE TITLE
FXIOS-668 ⁃ Determine if any actions in our app cause permission tracking popups

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-ios#7039]
**Vision**

As an Firefox for iOS user, I want to be comfortable with any permissions I've given to the app and that they are only used when necessary

**Acceptance Criteria**

* App has been tested to determine if any actions cause permission tracking popups
* Actions have been documented so that we can determine if the popup is a bug or if we are accessing something unnecessarily

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-668)

**Comment by sblatz** [comment]
Starting my investigation on this. 

### Pasting from Clipboard
1. In settings, enable "Offer to open copied links" (this seems to be off by default, so may not be a big issue!)
2. Go to new tab experience (with a link already on your clipboard).

Sometimes you'll be given a snackbar at the bottom offering to go to the website, and the system dialog at the top says Firefox pasted from Safari (this would be expected).

However, if I now go to settings, or background the app, and come back, the snackbar is no longer there but **we keep accessing the clipboard**.

My recommendation here is that we always show the snackbar if we're accessing the clipboard so there's no misinterpretation of _why_ we're accessing it.

**Comment by sblatz** [comment]
I'm going to close this as my investigation is over. @athomasmoz I have filed a follow-up for the clipboard ticket as I think that's the only action item [here](https://github.com/mozilla-mobile/firefox-ios/issues/7058) :)
