### ISSUE TITLE
Missing telemetry when updating to Glean

### ISSUE THREAD

**Issue by garvankeeley** [mozilla-mobile/firefox-ios#7040]
These metrics are missing from Glean

Uninstrumented metric recorded: action, add, trackingProtectionSafelist, , nil
Uninstrumented metric recorded: action, drag, locationBar, , nil
Uninstrumented metric recorded: action, drag, tab, tab-tray, nil
Uninstrumented metric recorded: action, drag, tab, top-tabs, nil
Uninstrumented metric recorded: action, drop, tab, tab-tray, nil
Uninstrumented metric recorded: action, open, whatsNew, , nil
Uninstrumented metric recorded: action, press, dismissETPCoverSheetAndGoToSettings, , nil
Uninstrumented metric recorded: action, press, dismissedETPCoverSheet, , nil
Uninstrumented metric recorded: action, press, dismissedOnboarding, , Optional(["slide-num": 1])
Uninstrumented metric recorded: action, press, dismissedOnboardingEmailLogin, , Optional(["slide-...
Uninstrumented metric recorded: action, press, dismissedOnboardingSignUp, , Optional(["slide-num"...
Uninstrumented metric recorded: action, press, keyCommand, , Optional(["action": "close-tab"])
Uninstrumented metric recorded: action, press, setting, theme-automatically, nil
Uninstrumented metric recorded: action, press, tab, , nil
Uninstrumented metric recorded: action, press, tabSearch, , nil
Uninstrumented metric recorded: action, press, tabToolbar, tab-view, nil
Uninstrumented metric recorded: action, press, trackingProtectionMenu, , nil
Uninstrumented metric recorded: action, tap, chinaServerSwitch, , nil
Uninstrumented metric recorded: action, tap, download, downloads-panel, nil
Uninstrumented metric recorded: action, tap, downloadLinkButton, , nil
Uninstrumented metric recorded: action, tap, privateBrowsingButton, , Optional(["is-private": "tr...
Uninstrumented metric recorded: action, view, downloadsPanel, home-panel-tab-button, nil
Uninstrumented metric recorded: enrollment, add, experimentEnrollment, , Optional(["Experiment id...
Uninstrumented metric recorded: firefoxAccount, emailLogin, accountConnected, , nil
Uninstrumented metric recorded: firefoxAccount, qrPairing, accountConnected, , nil
Uninstrumented metric recorded: firefoxAccount, qrPairing, appMenu, , Optional(["flow_type": "ema...
Uninstrumented metric recorded: firefoxAccount, qrPairing, onboarding, , Optional(["flow_type": "...
Uninstrumented metric recorded: firefoxAccount, tap, appMenu, , Optional(["flow_type": "pairing"])
Uninstrumented metric recorded: firefoxAccount, tap, onboarding, , Optional(["flow_type": "pairin...
Uninstrumented metric recorded: firefoxAccount, view, appMenu, , nil
Uninstrumented metric recorded: firefoxAccount, view, onboarding, , nil
Uninstrumented metric recorded: firefoxAccount, view, settings, , nil

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2508)

**Comment by garvankeeley** [comment]
@athomasmoz looks like a lot missing

**Comment by athomasmoz** [comment]
I would like to run through these with @magorlick as part of https://jira.mozilla.com/browse/DS-722 . That way we can decide what makes the most sense to include rather than just adding them all because they were in legacy telemetry.

**Comment by lmarceau** [comment]
Since only `data-sync-user` has commented on the issue after the `Stalebot` GitHub action (which triggered the removal of the `stale` label) I’ll close this issue for now. Please let us know if you think this issue needs to be reopened, we'll gladly do so. Thank you!
