### ISSUE TITLE
FXIOS-672 ⁃ [XCUITest] New test for the search button

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/firefox-ios#7044]
There is a new search button added to the bottom bar. It would be nice to have a test to check its functionality.

New UI:
![IMG_7703](https://user-images.githubusercontent.com/1897507/88687705-e1fad380-d0f8-11ea-99b6-e6bbdd980b65.PNG)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-672)

**Comment by AaronMT** [comment]
Test-Rail: https://testrail.stage.mozaws.net/index.php?/cases/view/966835&group_by=cases:section_id&group_order=asc&group_id=118970
