### ISSUE TITLE
[XCUITests] Add test for the new search logo

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/firefox-ios#7046]
Based on issue #6917 we may need to add UI tests to cover that area.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2509)

**Comment by lmarceau** [comment]
Since only `data-sync-user` has commented on the issue after the `Stalebot` GitHub action (which triggered the removal of the `stale` label) I’ll close this issue for now. Please let us know if you think this issue needs to be reopened, we'll gladly do so. Thank you!
