### ISSUE TITLE
FXIOS-675 ⁃ Update getting started Wiki for iOS14 changes

### ISSUE THREAD

**Issue by nbhasin2** [mozilla-mobile/firefox-ios#7047]
- Update the Readme to support iOS14 Branch and how to build using XCode 12 Beta(s)
- Make sure iOS14 branch is upto date with our latest release

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2510)

**Comment by garvankeeley** [comment]
Current problem: https://github.com/mozilla-mobile/firefox-ios/issues/7052
