### ISSUE TITLE
Sometimes fails to show error page on websites without servers

### ISSUE THREAD

**Issue by vphong** [mozilla-mobile/firefox-ios#7055]
## Steps to reproduce

On a slow internet connection, go to an invalid website such as https://www.abcdefghii.com/ and wait for it to load.

Expected behavior | Actual behavior
-|-
![image](https://user-images.githubusercontent.com/13925498/88975686-7e46e680-d26f-11ea-9906-f5ecc98374a7.png) | Forever loading: ![Simulator Screen Shot - iPhone SE (2nd generation) - 2020-07-30 at 14 18 54](https://user-images.githubusercontent.com/13925498/88975754-9e76a580-d26f-11ea-9bb6-79828741496e.png) 

### Device & build information
* Device: iPhone SE 2nd Gen Simulator
* Build version: ?

### Notes
- Over half of the times I try to go to an invalid URL, the browser appears to be forever loading
- I set a breakpoint in `didFailProvisionalNavigation` to investigate. https://github.com/mozilla-mobile/firefox-ios/blob/e84d14f08e1ac6dc8fe7fcd12e54d3e2a82dd1c8/Client/Frontend/Browser/BrowserViewController/BrowserViewController%2BWebViewDelegates.swift#L585-L609
- I can step over everything in this function smoothly until the end, when this cast seems to fail(?) but goes into the `if let` anyway. <img width="1001" alt="Screen Shot 2020-07-30 at 12 43 22 PM" src="https://user-images.githubusercontent.com/13925498/88977073-09c17700-d272-11ea-81a7-8053d5e06755.png">
  - oddly, `po url` results in the below, conflicting with `e url` above:

``` swift
(lldb) po url
▿ https://abreach.com/
  - _url : https://abreach.com/
```
- so I stepped into `ErrorPageHelper.loadPage()` but I get kicked out immediately because of this guard and probably the invalid url. https://github.com/mozilla-mobile/firefox-ios/blob/76faae8c6c94e22c8fbc0de72e2d06f615738e2c/Client/Frontend/InternalSchemeHandler/ErrorPageHelper.swift#L232-L235
  - specifically, `e webView.url` is `nil` so the guard makes the function return.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2512)

**Comment by lmarceau** [comment]
Since only `data-sync-user` has commented on the issue after the `Stalebot` GitHub action (which triggered the removal of the `stale` label) I’ll close this issue for now. Please let us know if you think this issue needs to be reopened, we'll gladly do so. Thank you!
