### ISSUE TITLE
FXIOS-683 ⁃ Add version name to about section

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-ios#7057]
**Vision**

Version name is added alongside the version number to the about section

**Acceptance Criteria**

* Version name can be preserved through multiple releases
* Version name should not be localized
* Format should be `Firefox <version-name> <version-number> (<build-number>)`
* Version name can show in both beta & release

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-683)

**Comment by mei-loo** [comment]
will you clarify if the word "version" goes with the <version-number>? 

Such as:
Firefox <version-name> <version-number> (<build-number>)
and it would read: Firefox Daylight Version 30.0 (123456)

if so, that looks good :)

In terms of where it shows, whichever is easier to implement.

**Comment by SimonBasca** [comment]
Verified fix on f455fe6d542b. Version name, number and build number added.
