### ISSUE TITLE
[webxr] XRViewerPose views returns both left and right eyes for devices with one view

### ISSUE THREAD

**Issue by De-Panther** [mozilla-mobile/firefox-ios#7061]
## Steps to reproduce
Open this page in WebXR Viewer
https://de-panther.github.io/unity-webxr-export
Enter AR session
Try to select and drag the sphere and boxes.
It doesn't work, as there are two cameras/views (one with small viewport), and the specific method that was used in Unity for touch events works only with one camera.

### Expected behavior
The user should be able to drag the boxes and the sphere.

### Actual behavior
Drag doesn't work.

### Device & build information
* Device: iPhone XR, iOS 13.6
* Build version: The current store version
### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2515)

**Comment by lmarceau** [comment]
Since only `data-sync-user` has commented on the issue after the `Stalebot` GitHub action (which triggered the removal of the `stale` label) I’ll close this issue for now. Please let us know if you think this issue needs to be reopened, we'll gladly do so. Thank you!
