### ISSUE TITLE
FXIOS-687 ⁃ [Chron Tabs] Increase tab line item size

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-ios#7063]
**Vision**

As a user with tabs open to compare products while shopping, I want a bigger thumbnail & longer page title for each tabt o help me identify them

**Acceptance Criteria**

* Tab line item size is increased to match [updated design](https://app.abstract.com/share/39a20292-cc77-43fb-9a04-98662afa5f8b?mode=build&sha=c3081577a7b36a6332013462974065acbf89580e)
* Tab page title is expanded to 2 lines
* Bigger thumbnail image
* Larger font sizes supported

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-687)

**Comment by sblatz** [comment]
Updated: 

<img width=300 src=https://user-images.githubusercontent.com/4400286/89468592-b301e480-d72c-11ea-8122-5fd916377f54.png>

**Comment by SimonBasca** [comment]
Verified fix on 85d439c08. 
For the "Larger font sizes supported" I logged #7119
