### ISSUE TITLE
FXIOS-691 ⁃ Top Sites Widget for iOS 14

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-ios#7067]
**Vision**

As an iOS 14 user, I want to add my top sites to my homescreen, so I can open them with a single click

**Acceptance Criteria**

* Top sites widget in medium size is available for iOS 14 users
* Widget matches [spec](https://share.goabstract.com/dd1d6116-9d8a-4073-a76e-cc1d9d20bd0a)
* Widget gallery matches [spec](https://share.goabstract.com/dd1d6116-9d8a-4073-a76e-cc1d9d20bd0a)

**Not Included**

Time based top sites is not included

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-691)

**Comment by SimonBasca** [comment]
Verified fixed on main ca2f5c98dd and 29.0 (2721).
