### ISSUE TITLE
FXIOS-693 ⁃ Quick View (tabs only) iOS 14 Widget

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-ios#7069]
**Vision**

As an iOS 14 user, I want links to my favourite websites added to my homescreen, so I can open them with a single click

**Acceptance Criteria**

* Medium & large size widgets that show open tabs are available in the iOS 14 widget gallery
* Widget matches spec: [medium](https://share.goabstract.com/53a2d93c-6d32-4812-b7c0-e59a02d473bc), [large](https://share.goabstract.com/775726de-0e92-49c0-9d5c-384c5dcd9625?mode=design)

**Not Included**

* This doesn't include the option to show recent bookmarks instead of open tabs

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-693)

**Comment by athomasmoz** [comment]
@sblatz After updating Amy on our meeting yesterday and reviewing the priorities, I cut down this ticket to only be recent tabs. I will create a new ticket for the option to display recent bookmarks instead.

**Comment by SimonBasca** [comment]
Verified fixed on 29.0(2721) and main ca2f5c98dd
