### ISSUE TITLE
FXIOS-696 ⁃ Search Quick Links widget for iOS 14 (Medium)

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-ios#7073]
**Vision**

As an iOS 14 user, I want a shortcut from my homescreen to start searches and open URLs in Firefox

**Acceptance Criteria**

* Medium size Firefox search quick actions widget is available to users on iOS 14+
* There are actions to search, private search, open copied URL (when exists on clipboard), and clear private tabs
* Design & functionality matches [spec](https://share.goabstract.com/a21346ac-39ee-426d-b120-0922cf3bdb1a)

**Not Included**

This ticket does not include the small sized search quick links widget. It is covered in #7064

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-696)

**Comment by SimonBasca** [comment]
@athomasmoz I found the article you were mentioning : https://support.mozilla.org/pl/kb/add-firefox-widget-your-home-screen. On my side I can't seem to find the widget after long pressing on the home screen(see video[CBUI0493.mov.zip](https://github.com/mozilla-mobile/firefox-ios/files/5195445/CBUI0493.mov.zip)). 

I am on the iOS14 branch with latest commit d140a444ae54e on iPhone XS Max (14.0b7).
[CBUI0493.mov.zip](https://github.com/mozilla-mobile/firefox-ios/files/5195445/CBUI0493.mov.zip)

**Comment by SimonBasca** [comment]
Updating Notes: I am able to see the widget on sim iPhone XS (14.0) on main-dev ec13f42830 but not on same actual device.

**Comment by SimonBasca** [comment]
Verified fix on 29.0 (2609).
