### ISSUE TITLE
FXIOS-697 ⁃ Inform users of the option to set Firefox as their default browser

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-ios#7089]
**Vision**

As a Firefox for iOS user, I want to be informed as soon as I'm able to set Firefox as my default browser, so that I can use a single browser on the device for a consistent experience whether opening from the homescreen or through clicking on a link in another app

**Acceptance Criteria**

* A card with call-to-action to set Firefox as your default browser appears on top of “Top Sites”. This call-to-action deep links into the Firefox OS level settings, where users can set Firefox as their default.
  * Title string: `Set Firefox as your default browser`
  * Content string: `You can set links to open automatically in Firefox.`
  * Button string: `Go to Settings`
  * Button deeplinks into Firefox OS level settings
* Card is only visible to iOS 14+ users
* Design details
  * [Abstract](https://share.goabstract.com/c7d2a29b-6ad6-4cb7-a042-309c1aa41d26)

|iPhone: Portrait orientation|iPhone: Landscape orientation|iPad|
|----|----|----|
|![](https://user-images.githubusercontent.com/51007/89356907-20a11700-d713-11ea-9d77-695480b78b9e.png)|![](https://user-images.githubusercontent.com/51007/89356908-23037100-d713-11ea-971e-dfc39bffe677.png)|![](https://user-images.githubusercontent.com/51007/89356867-f8b1b380-d712-11ea-945e-a96df0c9bafc.png)|

Alternate design with Firefox logo:

|iPhone: Portrait orientation|iPhone: Landscape orientation|iPad|
|----|----|----|
|![](https://user-images.githubusercontent.com/51007/89858954-f3150b80-dbf3-11ea-8fb0-9b7fdaaae3ad.png)|![](https://user-images.githubusercontent.com/51007/89858968-fdcfa080-dbf3-11ea-84a3-4135a3147060.png)|![](https://user-images.githubusercontent.com/51007/89858977-00ca9100-dbf4-11ea-92d6-19dd541657e1.png)|

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-697)

**Comment by brampitoyo** [comment]
Assigning @betsymi to acknowledge and double-check strings.

**Comment by brampitoyo** [comment]
Added alternate design with Firefox logo. You should also see the same alternate design posted on Abstract and the Feasibility Review document.

**Comment by SimonBasca** [comment]
Verified fixed on iPhone XS (14.0b8), iPad Pro 11 inch (14.0b8) and iPhone Xr (13.6) on main-dev ec13f42830.
