### ISSUE TITLE
FXIOS-699 ⁃ Land strings for iOS 14 Widgets

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-ios#7091]
**Acceptance Criteria**

* All strings for the MVP iOS 14 widgets have landed in our repo
  * #7073 - Medium: Quick Actions
  * #7064 - Small: Quick Action (Regular Search, Private Search, Close Private Tabs, Go To Copied Link)  
  * #7067 - Medium: Top Sites
  * #7069 - Medium & Large: Quick View
  * #7068 - Pocket
* L10n team is informed of the new widgets for localization

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-699)

**Comment by data-sync-user** [comment]
➤ Ashley Thomas commented:

[~bmikel@mozilla.com] [~amlee@mozilla.com] Can you add the accessibility strings/hints to the mocks?

**Comment by betsymi** [comment]
Before these strings are sent to l10n, would it be possible for me to take a look to verify they're correct? Not sure the best way to do that. Normally I request screen shots, but I know there are quite a few for this one.
