### ISSUE TITLE
FXIOS-700 ⁃ Land Strings for Default Browser

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-ios#7092]
**Acceptance Criteria**

* All strings for the [default browser](https://app.abstract.com/share/c7d2a29b-6ad6-4cb7-a042-309c1aa41d26) have landed in our repo
* L10n team is informed of the new widgets for localization

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-700)

**Comment by betsymi** [comment]
before these strings are sent to l10n, would it be possible for me to take a look to verify they're correct? Could you post a screenshot here?
