### ISSUE TITLE
FXIOS-701 ⁃ Track counts on usage of widgets to determine success

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#7097]
**Vision**

As a PM, I want to know how often each widget is used, so I can prioritize enhancements and fixes for popular widgets and determine if there are any we should turn off

**Acceptance Criteria**

* We can determine how often users come into the app from each widget action (Glean)
  * For example, we know how many users clicked "open a private tab" in the quick links widget
* Tracking is run through [data science](https://jira.mozilla.com/browse/DO-310) and data stewards

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-701)

**Comment by garvankeeley** [comment]
SyncTelemetry is using prefs to store events when in extensions, which the main app consumes. Look at 'pickle' and 'unpickle' and how these are used.
https://github.com/mozilla-mobile/firefox-ios/blob/41de75409d5e568ebe3e0f059fe30c60651abcae/SyncTelemetry/SyncTelemetryEvents.swift#L62-L62

**Comment by sblatz** [comment]
I'm going to send the widget action (close private tabs, open copied link, open tab, top site, etc.) as well as the *size* of the widget the action was from (as an extra)

**Comment by SimonBasca** [comment]
Verified fixed on 30.0 (3279).
