### ISSUE TITLE
FXIOS-732 ⁃ Setting to use staging servers disappeared?

### ISSUE THREAD

**Issue by tublitzed** [mozilla-mobile/firefox-ios#7101]
## Steps to reproduce

We've been following [these steps](https://mozilla.github.io/ecosystem-platform/docs/process/using-the-staging-environment#ios) to test changes to the sync server against iOS in staging. 

I recently went to do a test, and found that the "Debug: use stage servers" option no longer exists! Did it move somewhere else that I might not be looking?

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-732)

**Comment by garvankeeley** [comment]
Correct it is now in `Advanced Sync Settings`, which appears after tapping the version 5x

<img width="379" alt="image" src="https://user-images.githubusercontent.com/5495083/90274346-63a76c80-de2e-11ea-8138-45a3e91fe206.png">

**Comment by garvankeeley** [comment]
Also that page says to go to `Accounts Menu > Settings`, that should say `App Menu > Settings`.

@tublitzed do you have edit access to that page?

**Comment by tublitzed** [comment]
Aha! Great, thanks Garvan. I do have access to edit it, and I'll handle that via https://github.com/mozilla/ecosystem-platform/issues/97
