### ISSUE TITLE
Refactor and search for any VCs which are not using dequeueReusableCell

### ISSUE THREAD

**Issue by vphong** [mozilla-mobile/firefox-ios#7103]
Note: This ticket might not contain all areas where are not using dequeueResuableCell so it is assumed that while working on it we’ll look into areas of our app that we might have missed.

It may be in our best interest to change cell inits to `dequeueReusableCell` in longer TableViews for performance enhancement. Linked below are examples of places that initialize the cell from scratch - there may be more, but these were what I could find. Maybe not all of them need to be refactored, but at least `LoginsList` should be as users may theoretically have thousands of saved logins.

[https://github.com/mozilla-mobile/firefox-ios/blob/3e06234b46c74a8f4c8c160ad05367ac7e05c683/Client/Frontend/Login%20Management/LoginListViewController.swift#L592](https://github.com/mozilla-mobile/firefox-ios/blob/3e06234b46c74a8f4c8c160ad05367ac7e05c683/Client/Frontend/Login%20Management/LoginListViewController.swift#L592)

[https://github.com/mozilla-mobile/firefox-ios/blob/76faae8c6c94e22c8fbc0de72e2d06f615738e2c/Client/Frontend/Settings/LoginDetailViewController.swift#L133](https://github.com/mozilla-mobile/firefox-ios/blob/76faae8c6c94e22c8fbc0de72e2d06f615738e2c/Client/Frontend/Settings/LoginDetailViewController.swift#L133)

[https://github.com/mozilla-mobile/firefox-ios/blob/cba695104f81b321d8798653c3fb6a42b8c41ae3/Client/Frontend/Widgets/PhotonActionSheet/TrackingProtectionMenu.swift#L25](https://github.com/mozilla-mobile/firefox-ios/blob/cba695104f81b321d8798653c3fb6a42b8c41ae3/Client/Frontend/Widgets/PhotonActionSheet/TrackingProtectionMenu.swift#L25)

[https://github.com/mozilla-mobile/firefox-ios/blob/cba695104f81b321d8798653c3fb6a42b8c41ae3/Client/Frontend/Theme/ThemedWidgets.swift#L36](https://github.com/mozilla-mobile/firefox-ios/blob/cba695104f81b321d8798653c3fb6a42b8c41ae3/Client/Frontend/Theme/ThemedWidgets.swift#L36)

and many other instances of `let cell = ThemedTableViewCell()`.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2520)

**Comment by data-sync-user** [comment]
➤ Laurie Marceau commented:

Closing this since we have an epic for this instead https://mozilla-hub.atlassian.net/browse/FXIOS-6632 ( https://mozilla-hub.atlassian.net/browse/FXIOS-6632|smart-link )
