### ISSUE TITLE
FXIOS-735 ⁃ (iOS 14) iPad doesn’t show the menu items in landscape mode

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-ios#7104]
## Steps to reproduce

1. Open Firefox
2. Open Menu

### Expected behavior

Menu is displayed with a number of options

### Actual behavior

Menu is blank

### Device & build information
* Device: iPad
* OS version: 14 beta 3

### Notes
Attachments: 
![image](https://user-images.githubusercontent.com/43346208/89662060-5c112200-d888-11ea-9b73-ffa49ac26876.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-735)

**Comment by athomasmoz** [comment]
Only in landscape. Happens in both light & dark mode

**Comment by dnarcese** [comment]
Fixed in iOS beta 6!

**Comment by csuciu** [comment]
Confirming that this is fixed in latest iOS Beta.
