### ISSUE TITLE
FXIOS-742 ⁃ Land String for ETP Update

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-ios#7113]
**Acceptance Criteria**

* [String in the shield menu for describing what is blocked](https://docs.google.com/document/d/1xsCsG5BJ39aN6G7x8Vty4-PnCj_5cm2qTVCIloF670M/edit#heading=h.m7ftnp752km3) has landed
* L10n team is informed about the new string to kickoff localization process

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-742)

**Comment by betsymi** [comment]
Before these strings are sent to l10n, would it be possible for me to take a look to verify they're correct? Could you post screenshots here?
