### ISSUE TITLE
New ways to archive web pages

### ISSUE THREAD

**Issue by kaylagalway** [mozilla-mobile/firefox-ios#7117]
You can now create web archive files to be loaded later

* Start using the web view `createWebArchiveData` function
  * We can write data from this function to disk
  * Can then convert it back later by fetching the file from disk, example function: 
```
func loadWebArchive(from localFile: URL) {
guard let data = try? Data(contentsOf: localFile),
let baseURL = URL(string: "about: blank"),
let mimeType = UTType.webArchive.preferredMIMEType else {
return
}
webView.load(data, mimeType: mimeType, characterEncodingName: "utf-8", baseURL: baseURL)
} 
  * You can watch more about how this works approx 22 mins into WWDC20 "Discover WKWebView Enhancements" video
* This is important for us in a number of ways. Right now we can only store the URL of a page, so if the app is backgrounded and killed by the OS, every page has to reload when the app is launched again. This means a poor offline experience, such as when a user has queued up a bunch of pages to read when entering the subway.
* We currently do not limit the number of live in-memory WKWebViews. A better app design would be to limit to 10 live WKWebViews, and then anything over that gets archived and restored on-demand. The old UIWebView had this as an explicit recommendation in the docs.



┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2523)

**Comment by data-sync-user** [comment]
➤ Orla Mitchell commented:

After some investigation I was able to get this to work but it doesn’t do what we hoped it would. It archives the content of the page and no more. This means interactionState is still needed to store the session data related to the tab itself so iOS 14 users will still need to rely on the old system.

This is still worthwhile doing, for the memory pressure and offline use case reasons listed above, but I would like to hold off until after the current webview refactor work has gone live so we can make sure that is stable first.
