### ISSUE TITLE
Scanning Feature Authentication for Firefox Sync iOS 500 Internal Server error

### ISSUE THREAD

**Issue by jhhlim** [mozilla-mobile/firefox-ios#7120]
## Steps to reproduce
1.Open up Firefox app on Mobile 
2. Open up Firefox Browser on Laptop and select Connect to Another Device
3. On Browser--select 'Show Code' button
4. On Firefox App go to bottom right and select 'Sign in to Sync' 
5. Select Ready to Scan

### Expected behavior
The QR code scan should say "Invalid Code" on the Firefox Mobile app or at least have a more user-friendly way to enable users to use Firefox sync tool on multiple platforms (from mobile, laptop, PC, etc) instead of throwing a 500 internal server error on my Firefox Browser (using windows laptop) and then exiting the mobile app. Having more user friendly transitions for users not used to Firefox--particularly new users or existing users from long time back, would greatly increase the total amount of Firefox users.
### Actual behavior

When scanning this QR code via Mobile Phone, it generates internal 500 server error 90% of the time when attempting to scan. I tried this test 9 out of 10 times and it failed. ON the 10th try, had to make sure my camera app scanned the ENTIRE QR code with great accuracy for it to work.

### Device & build information
* Device 1: Windows 10,
* Build version: 10.0.19041 Build 19041

* Device 2: Iphone XR
* Build version: iOS 13.6
### Notes
Attachments: See attachments

![FirefoxBug8-11-2020](https://user-images.githubusercontent.com/31980053/89940805-f2b64980-dbce-11ea-86e9-213b6f379dc5.jpg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2525)

**Comment by athomasmoz** [comment]
@SimonBasca Can you try reproducing this on the specific device? 
cc @rfk Are you seeing these elsewhere?

**Comment by rfk** [comment]
Thanks for flagging this, I'm not aware of widespread failures here, but I'll see if I can reproduce.

**Comment by SimonBasca** [comment]
This issue is reproducible when trying to scan the  QR code from a desktop using windows environment with a iOS device. On my side I am getting this error. 

![Screen Shot 2020-08-17 at 14 00 05](https://user-images.githubusercontent.com/32130829/90389308-fbf15b80-e091-11ea-834c-d4c3f39755f1.png)

Tested with iPhone Xr (13.6) on Firefox 28.0 (18809) and Desktop Windows 10 on Firefox 79.0.

**Comment by rfk** [comment]
The `channel_id` error typically indicates that you've scanned a QR code that was meant for something else, rather than the one shown by visiting https://firefox.com/pair. Unfortunately the FxA signing flow sometimes uses a different QR code for different purposes.
