### ISSUE TITLE
FXIOS-779 ⁃ Empty logins view after switching to a different app

### ISSUE THREAD

**Issue by csuciu** [mozilla-mobile/firefox-ios#7123]
master cd7ef45128/current release (v28.0) 
iPhone 11 Pro 13.3

1. Open the Logins view via Menu => Logins & Passwords.
2. Tap on an saved login to enter the login details view.
3. Switch to a different app then switch back to Firefox.

Result: The user is returned to the logins list view which is empty (the loading throbber is shown but the list doesn't populate )

Note: This issue doesn't occur if entering Logins & Passwords via the Settings page. In this case, following the STR the user is presented the Settings page when returning to Firefox.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-779)

**Comment by vphong** [comment]
Trying to reproduce this - this is what I get. Instead of going back to the Logins & Passwords list, the content just blurs. Can you confirm this on the latest build @csuciu?
![IMG_0013](https://user-images.githubusercontent.com/13925498/90455627-65ca2f00-e0ab-11ea-9679-d40257082a60.PNG)

**Comment by csuciu** [comment]
@vphong Confirming that, on latest master, the content blurs when returning to the app. After that, when I try to interact with the app, it crashes.
This is the crash report:
[Client-2020-08-18-200445.ips.zip](https://github.com/mozilla-mobile/firefox-ios/files/5091792/Client-2020-08-18-200445.ips.zip)

**Comment by vphong** [comment]
Thank you @csuciu!

**Comment by csuciu** [comment]
Verifying as fixed on master c91e958de.
