### ISSUE TITLE
FXIOS-778 ⁃ Update ETP based on ITP

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-ios#7128]
**Vision**

As a Firefox user, I want to understand what ETP is doing to protect me and have the option to turn it off if it may fix breakage on a site I'm using

**Acceptance Criteria**

* Users can turn ETP off in the shield menu for a page when in strict
* Users don't have the option to turn off ETP in the shield menu for a page when in standard
* The "Blocked" section in the shield menu has been updated to describe what's being blocked instead of listing trackers. This is because we don't know all the cookies that ITP is blocking
* The "Reload Without Tracking Protection" item in the refresh long-press menu (or in the page actions menu after #6847) is only available when a user is in strict
* SUMO article updates: https://docs.google.com/document/d/1-ODYXXo1t2nl-DRMV1FMUGmNy5kL2-SBe2LGGitgvCk/edit#

([mock](https://docs.google.com/document/d/1xsCsG5BJ39aN6G7x8Vty4-PnCj_5cm2qTVCIloF670M/edit#heading=h.xlsvv1n4d1ao))

**Notes**

* Both standard and strict were kept as options so that users will still have protection from Firefox, even if they turn ITP off at the device level
* The reason for removing the off button in standard is because it's unlikely that standard would break functionality on a site that ITP wouldn't break. ITP cannot be turned off per site or per app.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-778)

**Comment by dnarcese** [comment]
Edge case: What happens if the user turns ETP off for a page in Strict mode, and then changes to Standard mode?

**Comment by athomasmoz** [comment]
Some functionality on pages can break with tracking protection on, which was the original reason behind allowing users to turn it off for a particular page - if it's turned off, then it may fix whatever issue their seeing. ITP has similar tracking protection to standard ETP and it's unlikely that turning ETP off for a page when in standard mode will have an impact on whether or not the page is broken. My recommendation would be to keep ETP off for that page in case:
* The user switches back to strict
* The user has ITP turned off across the device, in which case turning ETP off for the page could have an impact

cc @betsymi @lime124

**Comment by SimonBasca** [comment]
Verified fix on master 8481016f9 and beta 29.0 (2639).
