### ISSUE TITLE
FXIOS-775 ⁃ Feature Flag iOS 14 Issues

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-ios#7133]
**Vision**

As a user on iOS 14+, I want iOS 14 features within Firefox to be available as soon as I upgrade, so that I can set my default browser and download widgets right away

As a user not on iOS 14, I don't want to see features not available to me yet

**Acceptance Criteria**

* As soon as iOS 14 release is out, default browser card & setting item are displayed are available for iOS 14+ users
* A release is not needed to get the features out to users

**Use Cases**

* As a user on iOS 13 v28, I do not see the default browser card & setting item. After I upgrade to iOS 14 and open Firefox, I will see the default browser card & setting item
* As a iOS 14 beta user on Firefox beta, I do not see the default browser card

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-775)

**Comment by garvankeeley** [comment]
>  default browser and download widgets right away

Could these be separated as issues? The "default browser" is supportable with Xcode 11.x builds, which is the current release version of Xcode (and is used for the 28.x release branch). We can continue to upload 28.x point releases to the AppStore with changes to improve the default browser support. 
WidgetKit is only supported with Xcode 12 builds, which is still in beta and we haven't stabilized the build systems for this yet (for instance automated testing doesn't run).

We should clarify with this ticket, what version of Xcode are looking to support for this issue?

**Comment by nbhasin2** [comment]
For iOS14 we have discovered that we are taking users to correct Default Browser settings area. Hence we have feature flagged Default Browser work for iOS14 and above.

**Comment by SimonBasca** [comment]
Verified fixed on 28.2 (2470). After updating from iOS 13.7 to iOS 14.0 the Default Browser card and settings are displayed correctly.

The "Default Browser" card and settings are not displayed on devices with iOS < 14
