### ISSUE TITLE
Switch from dylibs to static libs from Storage, Shared, etc

### ISSUE THREAD

**Issue by garvankeeley** [mozilla-mobile/firefox-ios#7134]
For greater startup performance we should switch our own build from having dylibs for:
Account.framework/ Shared.framework/ Storage.framework/ Sync.framework/ SyncTelemetry.framework/

Ideally we could find a way to measure this prior to release.

Related #6915

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2528)

**Comment by garvankeeley** [comment]
Might be a good time to look at better tooling for this like https://github.com/tuist/tuist

**Comment by lmarceau** [comment]
Since only `data-sync-user` has commented on the issue after the `Stalebot` GitHub action (which triggered the removal of the `stale` label) I’ll close this issue for now. Please let us know if you think this issue needs to be reopened, we'll gladly do so. Thank you!
