### ISSUE TITLE
Remove Universal Links

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-ios#7138]
**Acceptance Criteria**

* The following universal links have been removed:
  * "applinks:confirm.accounts.firefox.com",
  * "applinks:confirm.accounts.stage.mozaws.net",
  * "applinks:latest.dev.lcip.org",
  * "applinks:nightly.dev.lcip.org",
  * "applinks:rzte.adj.st",
  * "applinks:nn8g.adj.st"
* Marketing and accounts team have been informed of the change and impact

**Comment by nbhasin2** [comment]
Note: We can remove all these universal links cc @garvankeeley has confirmed it. 

Make sure to remove adjust in future as well. For now we can keep it.
