### ISSUE TITLE
Keyboard still active after auto-filling login form

### ISSUE THREAD

**Issue by kpetremann** [mozilla-mobile/firefox-ios#7143]
## Steps to reproduce
In a login form on any website, auto-fill password (using keychain or an app like keepassium).

### Expected behavior
After the login form is filled, the keyboard should disappear.

### Actual behavior
The keyboard remains active after filling the login form (this is Safari behaviour).

### Device & build information
* Device: iPad pro
* Build version: 13.6.1

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2529)

**Comment by lmarceau** [comment]
Since only `data-sync-user` has commented on the issue after the `Stalebot` GitHub action (which triggered the removal of the `stale` label) I’ll close this issue for now. Please let us know if you think this issue needs to be reopened, we'll gladly do so. Thank you!
