### ISSUE TITLE
FXIOS-767 ⁃ Allow opening a link in a New Tab by pressing Command ⌘ + Click

### ISSUE THREAD

**Issue by jamielinux** [mozilla-mobile/firefox-ios#7147]
### Why/User Benefit/User Problem

**_iOS Safari_** lets you open a link in a New Tab by pressing **Command ⌘ + Click**.

On **_Firefox for iOS_**, pressing **Command ⌘** doesn't make a difference when clicking a link (ie, the link always opens in the current tab).

### Acceptance Criteria (how do I know when I’m done?)

When you can click on a link while holding **Command ⌘** to open it in a New Tab.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-767)

**Comment by Franciscosty** [comment]
You can also open link in new tab by using the Mac keyboard shortcut: Hold down the COMMAND key and then click on the link you wish to open. The shortcut is the same for both Safari and Chrome. This shortcut will automatically open the link in a new tab adjacent to your current tab.

**Comment by dnarcese** [comment]
Fixed in #7209
