### ISSUE TITLE
FXIOS-764 ⁃ Tracking in Place to Measure Success of Default Browser

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-ios#7151]
**Vision**

As a PM, I want have tracking in place for default browser usage, so that 

**Acceptance Criteria**

* We can see how many people clicked on the "Got to Settings" in the card on new tab in Glean
* We can see how many people clicked on the X in the card on new tab in Glean
* We can see how many people clicked on the "Set as Default Browser" menu item in Glean
* We can determine that users have us set as default browser (may be best guess)
* Tracking is run through [data science](https://jira.mozilla.com/browse/DO-309) and data stewards

**Notes**

Questions to measure success:
* Is the box on the new tab screen helping users find the default browser option?
* Is the line item in settings helping users find the default browser option?
* How many people setting us as the default browser?
* What's the impact of having a default browser option?

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-764)

**Comment by sblatz** [comment]
I think we can track when users enter the app through a deep link off http:// or https://

**Comment by sblatz** [comment]
We could also flag the first time we get this deep link that they at **one point** were default, in case we want to message these users differently.

**Comment by nbhasin2** [comment]
There are multiple options for this that require deeper discussion and understanding on how iOS14 changes work. 
For now we can start with adding events to Dismiss Button + Go To Settings button. 

@sblatz has good idea and we should either make another ticket to look into that. 

@athomasmoz what do you think?

**Comment by athomasmoz** [comment]
The first 3 bullets in the acceptance criteria cover adding events for the UI elements that were added. It sounds like you're suggesting we move the 4th acceptance criteria "We can determine that users have us set as default browser" to a separate ticket. Can I suggest timeboxing a look into Sawyer's suggestion before removing that bullet point? It's probably the most important one in this ticket if we can do it.

**Comment by nbhasin2** [comment]
I'll tag @dnarcese and ask if she'll be okay with it. I can help out too with that. 

We'll definitely do first 3 bullet points in adding events to UI elements.

**Comment by dnarcese** [comment]
Yes, it is okay with me if we timepox that.

**Comment by data-sync-user** [comment]
➤ Ashley Thomas commented:

[~darcese@mozilla.com] Another question on this. For the tracking on first 3 items (card on new tab + menu item), is it simple to have those sent to Leanplum as well as Glean? Or would that add more effort to this ticket?
