### ISSUE TITLE
FXIOS-756 ⁃ Reload button is displayed instead of search icon after locking and unlocking the deivce

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#7167]
## Preconditions:
- Set New Tab as Blank page
## Steps to reproduce
1. Open a new tab
2. Lock the device
3. Unlock the device
### Expected behavior
- Search icons should be displayed.
### Actual behavior
- Reload button is displayed
### Device & build information
* Device: iPhone Xr
* Build version: 15e1359cda38d
### Notes
Attachments: 
![87668666-28edde00-c775-11ea-8ffd-3a35ea2dbc0c](https://user-images.githubusercontent.com/32130829/90648981-d9527480-e242-11ea-8452-7103aae87e81.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-756)

**Comment by SimonBasca** [comment]
This is also reproducible on about:home Top Tabs on latest master 0f06c3cbdc

**Comment by data-sync-user** [comment]
➤ Ashley Thomas commented:

This happens with the new tab button too.

**Comment by nbhasin2** [comment]
cc - https://github.com/mozilla-mobile/firefox-ios/issues/7542

**Comment by SimonBasca** [comment]
Verified fix on 29.1 (2966).
