### ISSUE TITLE
FXIOS-755 ⁃ [Focus] Remove Adjust

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-ios#7172]
**Vision**

Remove Adjust from Focus iOS as it's not being used and could cause confusion over what user data is being tracked

**Acceptance Criteria**

* Adjust removed from Focus
* Confirm links from website to the app store still work
* Documentation (including our privacy policy) has been updated to reflect changes

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-755)

**Comment by nbhasin2** [comment]
https://github.com/mozilla-mobile/firefox-ios/pull/7215/commits/f4a40073794e8a9fc4c16c95acf7b558ff818c3e

This ^ should give you an example on how to remove Adjust. Its from Firefox iOS.
