### ISSUE TITLE
Close Private Tabs option is not hidden from the Widget after tapping Clear Private Tabs

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#7207]
## Steps to reproduce
1. Go to Private Browsing and visit "youtube.com"
2. Background Firefox 
3. Go to Today Widget 
4. Tap "Close private tabs"
### Expected behavior
- As per https://github.com/mozilla-mobile/firefox-ios/issues/6794#issuecomment-649238882 after tapping "Clear Private Tabs" button and the tabs are cleared the "Close Private Tabs" option should be  hidden.
### Actual behavior
- Close Private Tabs option is not hidden from the Widget after tapping Clear Private Tabs
### Device & build information
* Device: iPhone Xr (13.5)
* Build version: 0f06c3cbdcece8c20cbef992868fcb21c0469b19
### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2533)

**Comment by athomasmoz** [comment]
@AmyYLee How do you feel about the "close private tabs" link showing up, even if there are no tabs. Sounds like it was cut from the initial scope, how important do you feel this functionality is for the feature?

**Comment by lmarceau** [comment]
Since only `data-sync-user` has commented on the issue after the `Stalebot` GitHub action (which triggered the removal of the `stale` label) I’ll close this issue for now. Please let us know if you think this issue needs to be reopened, we'll gladly do so. Thank you!
