### ISSUE TITLE
FXIOS-798 ⁃ Firefox is opened after tapping Clear Private Tabs

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#7208]
## Steps to reproduce
1. Go to Private Browsing and visit "youtube.com"
2. Background Firefox
3. Go to Today Widget
4. Tap "Close private tabs"
### Expected behavior
- As per https://github.com/mozilla-mobile/firefox-ios/issues/6794#issuecomment-644167092 the browser should not open after tapping Clear Private Tabs from the Today Widget. 
### Actual behavior
- Firefox is opened after tapping Clear Private Tabs and the tabs are cleared.
### Device & build information
* Device: iPhone Xr (13.5)
* Build version: 0f06c3cb
### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-798)

**Comment by dnarcese** [comment]
There is no way we can provide this functionality without opening the app.
