### ISSUE TITLE
FXIOS-803 ⁃ Reload button is displayed instead of New Tab button after locking and unlocking the deivce

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#7212]
## Steps to reproduce
1. Open a new tab
2. Go to "youtube.com"
3. Lock the device
4. Unlock the device
### Expected behavior
- "New Tab button" should be displayed.
### Actual behavior
- Reload button is displayed
### Device & build information
* Device: iPhone Xr
* Build version: 0f06c3cb
### Notes
Possibly the same issue as #7167
Attachments: 
![Screen Shot 2020-08-25 at 18 25 36](https://user-images.githubusercontent.com/32130829/91194048-7eb48f00-e700-11ea-9964-f4e979372604.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2535)

**Comment by athomasmoz** [comment]
Blocking #6974
