### ISSUE TITLE
FXIOS-802 ⁃ Reload buttonis displayed in the URL bar on about:home Top Sites after locking and unlocking the device

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#7213]
## Steps to reproduce:
1. Go to "imdb.com"
2. Lock the device
3. Unlock the device
### Actual behavior
- The reload button is displayed in the URL bar. Seems to be from iPad UI on iPhone
### Device & build information
* Device: iPhone Xr
* Build version: 0f06c3cbdcece
### Notes
Attachments: 
![Screen Shot 2020-08-25 at 18 25 36](https://user-images.githubusercontent.com/32130829/91194760-1e721d00-e701-11ea-96bc-e9fb25eb0e5e.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2536)

**Comment by athomasmoz** [comment]
The reload button should not be shown until #6847 is released, where the refresh button in the bottom nav bar is replaced by a plus icon.

**Comment by isabelrios** [comment]
This also happens when setting the app to background and foreground
