### ISSUE TITLE
FXIOS-804 ⁃ [SUMO] Remove mention of Adjust from documentation

### ISSUE THREAD

**Issue by garvankeeley** [mozilla-mobile/firefox-ios#7214]
Our Settings screen links to this help doc which mentions Adjust https://support.mozilla.org/1/mobile/28.0/iOS/en/adjust

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-804)

**Comment by data-sync-user** [comment]
➤ Ashley Thomas commented:

Issue has been sent to SUMO to update.

**Comment by athomasmoz** [comment]
Re-opening to keep track of status

**Comment by data-sync-user** [comment]
➤ Joni Chan commented:

SUMO article (https://support.mozilla.org/en-US/kb/send-usage-data-firefox-mobile-browsers) ( https://support.mozilla.org/en-US/kb/send-usage-data-firefox-mobile-browsers) ) was updated on 8/26 to remove mentions of Firefox for iOS and Focus using Adjust. Let me know if we need to make additional changes.
