### ISSUE TITLE
FXIOS-810 ⁃ Dropdown Menu Items Disappear upon hover

### ISSUE THREAD

**Issue by ComradeHadi** [mozilla-mobile/firefox-ios#7221]
## Steps to reproduce
Open a dashboard with a drop down menu. 
Hover the menu items individually

### Expected behavior
Menu items should be visible

### Actual behavior
Menu items disappear

### Device & build information
* Device: MacOS 
* Build version: MacOS High Sierra Build 10.13.6
### Notes
Attachments: 
![image](https://user-images.githubusercontent.com/5107279/91317513-ff11d900-e76e-11ea-9118-f4933b1fd2f3.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-810)

**Comment by kbrosnan** [comment]
This Github project is for Firefox running on iOS devices. Looking at this report it looks to be a problem with Firefox running on MacOS with a website. We evaluate website problems at the WebCompat project. Please open an issue at https://webcompat.com/issues/new
