### ISSUE TITLE
Theme for Private Browsing Mode

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-ios#7222]
**Vision**

As a user, I want visual indicators when I'm in private browsing mode, so that I can quickly confirm that what I'm doing is private

**Acceptance Criteria**

* Theme in private browsing mode has been updated to match [mocks](https://app.abstract.com/share/5083fce2-665e-45e5-9078-b9bc4f295e03?mode=design&sha=3a4d186d95407cb1b70206f4216fcdd349218481)
* The PBM theme is used regardless of whether users have their theme set to dark or light
* Note: does not include adding the PBM button to urlbar

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2538)

**Comment by dnarcese** [comment]
@brampitoyo Is there concern about adding another icon onto the urlbar for smaller screens? Do we need to account for this in anyway?
<img width="374" alt="Screen Shot 2020-11-17 at 5 10 58 PM" src="https://user-images.githubusercontent.com/11432165/99456829-fe18bf80-28f7-11eb-8a36-74d3cd261659.png">

**Comment by athomasmoz** [comment]
@dnarcese I can help clarify that. The goal of this ticket was strictly to update the theming, so adding that icon is not part of it. That's part of a different idea explored at the same time for making it easier to switch between private & regular.

**Comment by lmarceau** [comment]
Since only `data-sync-user` has commented on the issue after the `Stalebot` GitHub action (which triggered the removal of the `stale` label) I’ll close this issue for now. Please let us know if you think this issue needs to be reopened, we'll gladly do so. Thank you!
