### ISSUE TITLE
FXIOS-813 ⁃ stack misalignment crash on simulator builds

### ISSUE THREAD

**Issue by garvankeeley** [mozilla-mobile/firefox-ios#7224]
~This appears to be due to the static linkage of A-S lib and FxA lib, and that they both contain openssl statically, most likely different versions of the lib.~ Nope, I thought removing the second openssl lib fixed it, but it still crashes.
```
#0	0x00007fff520d0b16 in stack_not_16_byte_aligned_error ()
#1	0x00007ffee3c66e40 in 0x7ffee3c66e40 ()
#2	0x000000010cbe0977 in std::panicking::try::do_call::h42fb9278cac0022b [inlined] at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libstd/panicking.rs:331
#3	0x000000010cbe095f in std::panicking::try::h6217f006a885832d at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libstd/panicking.rs:274
#4	0x000000010cbe2625 in std::panic::catch_unwind::h7a759416d6887ece [inlined] at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libstd/panic.rs:394
#5	0x000000010cbe25f4 in ffi_support::call_with_result_impl::hfc3f440e07dcf545 at /Users/distiller/.cargo/registry/src/github.com-1ecc6299db9ec823/ffi-support-0.4.0/src/lib.rs:224
#6	0x000000010cbd53bc in ffi_support::call_with_result::h34b01352eacdb505 [inlined] at /Users/distiller/.cargo/registry/src/github.com-1ecc6299db9ec823/ffi-support-0.4.0/src/lib.rs:192
#7	0x000000010cbd539d in ffi_support::handle_map::ConcurrentHandleMap$LT$T$GT$::insert_with_result::he2bc373a8b39bcd8 [inlined] at /Users/distiller/.cargo/registry/src/github.com-1ecc6299db9ec823/ffi-support-0.4.0/src/handle_map.rs:1008
#8	0x000000010cbd539d in sync15_passwords_state_new_with_salt at /Users/distiller/project/components/logins/ffi/src/lib.rs:50
#9	0x000000010ca7b4ff in closure #1 in LoginsStorage.doOpen(_:salt:) [inlined] at /Users/distiller/project/components/logins/ios/Logins/LoginsStorage.swift:119
```

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-813)

**Comment by garvankeeley** [comment]
If I change the linker order of Glean.framework this crash stops.
On the left is the crashing `otool -L Client`, on the right, no crash
<img width="1610" alt="image" src="https://user-images.githubusercontent.com/5495083/91357598-81c28480-e7bf-11ea-876b-e4908bce8b85.png">

**Comment by garvankeeley** [comment]
This is the PR that had project changes that started triggering the crash on xcode 11.6. https://github.com/mozilla-mobile/firefox-ios/pull/7218. The last commit has the workaround.

**Comment by garvankeeley** [comment]
We are freezing further development on `main` until we understand this. The PR #7218 (which provides iOS 14 compatibility for the team) that both triggered this and has the workaround for this case is on `main-dev`, which is a temp branch that all dev work will take place on until we decide things are stable and can return to `main`.

**Comment by garvankeeley** [comment]
FYI cc @eoger @vladikoff. Two rust libs in the project, one static and the other dynamic is turning out to be fragile.

**Comment by badboy** [comment]
What are the steps to reproduce this?

I buit the latest code from the `main` branch, but not sure how to trigger the crash. 

The crash as shown in the above stacktrace is happening in application-service's code. I suspect that re-ordering the libs is mainly a workaround by accident, but this might easily reappear.
Other bug reports on the internet suggest that this might be due to simd, not sure if any of a-s' dependencies uses that or uses special compiler flags.

**Comment by garvankeeley** [comment]
PR #7218 is needed, and revert f672018, or manually re-add Glean.framework to Client>Build Phases> Link Binary with Libraries 
<img width="1055" alt="image" src="https://user-images.githubusercontent.com/5495083/91449531-3b196c80-e849-11ea-8696-98a8721928a6.png">

**Comment by garvankeeley** [comment]
Or if there is tooling you are familiar with to re-order the link order on the binary that would do also, I am not sure how to do this with `install_name_tool`.

**Comment by badboy** [comment]
with main-dev and a reverted f672018 it crashes indeed.

**Comment by badboy** [comment]
Looking for this crash in other projects stuff like [this](https://github.com/JGRennison/OpenTTD-patches/commit/0a027a279d692103f0aeb89e3786ae132d30be85) turns up.
They managed to work around this with `-fno-stack-check`.

What made you reach to re-order where Glean is linked?
So far this looks to me as if a-s is misaligned.
(Not saying Glean is necessarily right, but I'm also not sure what we can do about it)

**Comment by garvankeeley** [comment]
> What made you reach to re-order where Glean is linked?
Was experimenting with linking to see if it changed the nature of the bug, it went away when I did that.

**Comment by rfk** [comment]
[This tweet](https://twitter.com/fxcoudert/status/1244299269068251137) seems to suggest this may be a recurring issue with XCode :-/

**Comment by garvankeeley** [comment]
Fixed as of unified AS+glean lib
