### ISSUE TITLE
Firefox account tab still shows the connected account after deleting it

### ISSUE THREAD

**Issue by vasilicatamas** [mozilla-mobile/firefox-ios#7227]
**Notes**
This is a follow up issue for [6164](https://github.com/mozilla/fxa/issues/6164)

**Build**
FxA Production [Train 1.185.1]

**Affected platforms**
iOS 13.6 

**Steps to reproduce**

1. Login on iOS using a Firefox account.
1. Navigate to Accounts Settings and delete the account.

**Expected results**
The view controller is dismissed.

**Actual Results**
After deleting the account the user is redirected to Firefox Account tab from where the account is not yet disconnected.

![issue11](https://user-images.githubusercontent.com/18114210/90898154-ea2ff100-e3ce-11ea-8509-cd89fcdc4a93.gif)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2541)

**Comment by athomasmoz** [comment]
Need to determine:
* Is this just a UI issue that looks like you are still signed in and will go away once you close the app
* Is the user actually still signed in and can access information & make changes to the account

**Comment by SimonBasca** [comment]
This seems to be a UI issue.
After closing the Firefox Account page the FxA is disconnected and deleted from the app. 

![ezgif-6-42090d4ce131](https://user-images.githubusercontent.com/32130829/91468326-81e38280-e89a-11ea-9976-7baf4414c76d.gif)

**Comment by athomasmoz** [comment]
Thank you for confirming! Moving this to a P2 in the up next list

**Comment by nbhasin2** [comment]
We have a message saying that account got deleted. I am going to take a look at logs and find if we get any callback that can be used as we are no longer taking users out of this view when they delete account. 

<img width="327" alt="image" src="https://user-images.githubusercontent.com/8919439/118551793-198c4800-b72c-11eb-9f88-84382ca9f9c1.png">

**Comment by lmarceau** [comment]
Tested and for me I stayed logged in even after the account deletion. When coming back from the fxA view I could see the "Sync now" button. 

See video (sorry I was searching for my password, you can skip some part of the video). 

https://user-images.githubusercontent.com/11338480/149603256-7434bfbb-5bf9-4734-a8f8-60ee643ac0e2.mp4

So it seems the issue isn't just UI related anymore. Firefox-iOS still thinks the account exists.

https://user-images.githubusercontent.com/11338480/149603281-3a608137-ba2e-4eac-a899-60d6b88b2b52.mp4
