### ISSUE TITLE
Remove static openssl lib, high risk of sudden compiler breakage or crash

### ISSUE THREAD

**Issue by garvankeeley** [mozilla-mobile/firefox-ios#7231]
x-ref to https://github.com/mozilla/application-services/issues/3546

Fx-ios has an old version of openssl statically linked into the app for push message decryption. This is high risk of becoming binary incompatible which might mean we can't link the project, or worse, it links and then crashes at runtime.

This can be replaced with A-S lib calls.
A-S team would be the driver and we could assist where possible to get it landed.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2543)

**Comment by skhamis** [comment]
OpenSSL has now been removed
