### ISSUE TITLE
FXIOS-821 ⁃ SUMO Articles for v29

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-ios#7232]
**Vision**

As a user, I want to know what's new in v29

**Acceptance Criteria**

* What's New summary article ([draft](https://docs.google.com/document/d/1Ey5ZEKjJB4Nu5BgAnFAYPOAlq__I3M1UhPrMGYFRW-M/edit?ts=5f47c4d4#))

* 

  * Default browser
  * iOS 14 Widgets
  * Updates to iOS 13 widget
* Instructions on setting Firefox as your default browser ([draft](https://docs.google.com/document/d/1Z1XQPlUWf4s-zMsi_h2i0QTVnnTTHmHncjkCepImpMY/edit))
* iOS 14 Widgets article ([draft](https://docs.google.com/document/d/1rzX43KYsevjaYuqX9thKd6jW4CzuSE92MVzaTrEh_Ys/edit#heading=h.y18oufflqab2))
* Updates to iOS 13 widget article (no draft yet)
  * Updated screenshots
  * Either combine this with iOS 14 widgets article, or note in this article that these widgets changed in iOS 14 and point to that article

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-821)

**Comment by data-sync-user** [comment]
➤ Ashley Thomas commented:

[~hsoto@mozilla.com] notes on these for while I'm out

  * There is a link in the app pointing to the what's new articles, which then links to the other articles. That means these have to be ready when v29 launches.
  * Default Browser article - link to this article on the sumo site should be sent to marketing when ready, so it can be included in their material

  * Widgets article - I have mocks in there now, these should be replaced by proper screenshots when ready
