### ISSUE TITLE
FXIOS-820 ⁃ #7233 - [SUMO] ETP SUMO Article Updates

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-ios#7233]
**Vision**

A few changes have been made to our ETP UI and functionality. SUMO article should reflect the changes

**Acceptance Criteria**

* ETP SUMO article has been updated to reflect changes made in #7128 to incorporate Apple's ITP

**Notes**

* Changes added as suggestions in this draft https://docs.google.com/document/d/1-ODYXXo1t2nl-DRMV1FMUGmNy5kL2-SBe2LGGitgvCk/edit#

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-820)

**Comment by data-sync-user** [comment]
➤ Ashley Thomas commented:

Article ready https://support.mozilla.org/en-US/kb/enhanced-tracking-protection-firefox-ios
