### ISSUE TITLE
FXIOS-822 ⁃ Not

### ISSUE THREAD

**Issue by mazid12345** [mozilla-mobile/firefox-ios#7234]
### Not included

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-822)

**Comment by baileyr146** [comment]
Can I ask a question? I need help W3C patent licenses for MIT is it better than Apache licenses 2.0 can anyone tell me? W3C my legal work  MIT ? It’s hard to understand? When you get five software companies wanting you to sign with them ?

**Comment by vphong** [comment]
Your question will be better answered on https://chat.mozilla.org/ :)
