### ISSUE TITLE
FXIOS-843 ⁃ Issue with strange glitch effect with continuosuly scrolling down

### ISSUE THREAD

**Issue by SathyaseelanRamachandran** [mozilla-mobile/firefox-ios#7257]
### Device & build information
* Device: iOS 14
* Build version: iOS version 14.6.1
![glitch](https://user-images.githubusercontent.com/50044265/91999657-36841500-ed6f-11ea-983e-9ac3622b03e4.png)

### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2545)

**Comment by dnarcese** [comment]
@SathyaseelanRamachandran is this still happening? If it is, is it only occurring on a specific website, or all sites?

**Comment by SimonBasca** [comment]
Also my guess is that this is related to Night mode. @SathyaseelanRamachandran do you have Night mode enabled when this happens?

**Comment by data-sync-user** [comment]
➤ Daniela Arcese commented:

Closing for now until more info is given.
