### ISSUE TITLE
FXIOS-845 ⁃ Focus Default Browser setup does not load url

### ISSUE THREAD

**Issue by nbhasin2** [mozilla-mobile/firefox-ios#7260]
Focus doesn't open url when coming from another app. It opens focus app but doesn't load URL

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-845)

**Comment by SimonBasca** [comment]
Verified fix on 8.1.6 (4126). This was verified by disabling Safari from Screen Time and deleting all other browsers except Focus.
