### ISSUE TITLE
Pull to go back should have dark background in dark mode

### ISSUE THREAD

**Issue by james-culp** [mozilla-mobile/firefox-ios#7264]
### Why/User Benefit/User Problem

The dark mode in Firefox on iOS is nice, and I enjoy using it. 

When I use the pull gesture from the left side of the screen to return to the previous page of my history, I temporarily see a bright white screen. This is very off putting when I'm in a dark room, and using Firefox dark mode to reduce eye glare. 

Firefox should show a black/dark screen instead of a white one when in dark mode to avoid irritating users' eyes. 

### Acceptance Criteria (how do I know when I’m done?)

This is accepted when I have no flash of bright white when navigating backwards in my history while in dark mode. 

### Not included

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2547)

**Comment by bong0** [comment]
This is something that fixing would impact some people's health even!
People that suffer under an ongoing migraine attack for example can be extremely irritated by those flashes that increases pain even more (let alone delayed sleep)

**Comment by lmarceau** [comment]
Since only `data-sync-user` has commented on the issue after the `Stalebot` GitHub action (which triggered the removal of the `stale` label) I’ll close this issue for now. Please let us know if you think this issue needs to be reopened, we'll gladly do so. Thank you!
