### ISSUE TITLE
Synced tabs don't work after re-signing in, until firefox-ios is restarted

### ISSUE THREAD

**Issue by thomcc** [mozilla-mobile/firefox-ios#7267]
## Steps to reproduce

1. Delete a Firefox account remotely. (I suspect this step is not required, and any method of switching accounts will do it, but who knows, these are the steps I took. Note that I waited a long time between steps 1 and 2 also, but that seems irrelevant).
2. Sign into a new account on iOS. (I used the pairing flow, but don't know if that matters)
3. Sync (on iOS).
4. Check same account on Desktop Firefox, and look at Synced Tabs, but find nothing.

(This would be kind of bad if it happens with just a "disconnect account remotely but it signs back in" flow. This wasn't what happened to me, but it's similar enough that I'd be skeptical).

### Expected behavior

Sync tabs should be available on Desktop Firefox.

### Actual behavior

Sync tabs are not available on Desktop Firefox, as no tabs record gets submitted to the server (according to about:sync).

Restarting fixed the issue, though.

### Device & build information
* Device: iPhone Xs max running 13.6.1
* Build version: 28.0 (18809)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2548)

**Comment by SimonBasca** [comment]
I can confirm that this is still an issue on v34.1 (5186) by following the STR.
1. Create a new FxA on iOS
2. Sync account on desktop
3. Try syncing bookmarks between device

Actual results:
- The bookmark do not sync, also synced tabs do not work. After restarting Firefox on iOS sync start working as expected.

**Comment by lmarceau** [comment]
Since only `data-sync-user` has commented on the issue after the `Stalebot` GitHub action (which triggered the removal of the `stale` label) I’ll close this issue for now. Please let us know if you think this issue needs to be reopened, we'll gladly do so. Thank you!
