### ISSUE TITLE
[XCUITests] Investigate UI tests for the different widgets iOS14

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/firefox-ios#7280]
Let's add this ticket to try to add some automation for the different widgets:
-Top Sites
-Quick Search 
-Quick View (tabs only)
...

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2549)

**Comment by isabelrios** [comment]
Would like to share the info here. It is possible to create a XCUITest for this. I started by recordig the steps and then customizating them. I drafted a test: 
<img width="893" alt="Captura de pantalla 2020-09-22 a las 12 23 07" src="https://user-images.githubusercontent.com/1897507/93871096-68352f80-fcce-11ea-9f0b-9fee5811b555.png">


The widget button is called `Fennec (userName)` which will be different for each env, this is something to work on still so that test works in all envs and CI

**Comment by AaronMT** [comment]
Oh this looks fragile. There might be behavior changes on iPadOS14 too.

**Comment by lmarceau** [comment]
Since only `data-sync-user` has commented on the issue after the `Stalebot` GitHub action (which triggered the removal of the `stale` label) I’ll close this issue for now. Please let us know if you think this issue needs to be reopened, we'll gladly do so. Thank you!
