### ISSUE TITLE
FXIOS-870 ⁃ [XCUITest] Add a new test for "Switch your Default Browser"

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/firefox-ios#7285]
On iOS 14 there will be this option when the app is launched after fresh install. 
![Captura de pantalla 2020-09-10 a las 18 07 51](https://user-images.githubusercontent.com/1897507/92760302-ce49ba80-f390-11ea-8f39-642ceceb1285.png)

It would be nice to have at least two tests:
1-Tapping on 'x' button dismisses the menu
2-Tapping on 'Going to Settings' button, takes user there and there is switch that can be enabled/disabled

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-870)

**Comment by isabelrios** [comment]
Note:
In Lockwise there was a test that dealt with the app itself and settings. It may good to have that in mind when we start working on this test.
https://github.com/mozilla-lockwise/lockwise-ios/blob/master/LockwiseXCUITests/LockwiseXCUITests.swift#L269
https://github.com/mozilla-lockwise/lockwise-ios/blob/master/LockwiseXCUITests/LockwiseScreenGraph.swift#L309

There might be some similarities we could use

**Comment by AaronMT** [comment]
We can add a test that asserts the existence of the default browser card on the home-screen, but I don't think we can check for the existence of the default browser setting in Settings due to lack of having all the required entitlements at run-time in a testing environment.

**Comment by isabelrios** [comment]
@AaronMT  we may be able to implement the test completely as I can see these screen while runnin the app on iPhone sim:
![Simulator Screen Shot - iPhone 8 - 2020-09-18 at 12 18 09](https://user-images.githubusercontent.com/1897507/93587711-981cc400-f9aa-11ea-923d-6978b70067d9.png)
![Simulator Screen Shot - iPhone 8 - 2020-09-18 at 12 30 02](https://user-images.githubusercontent.com/1897507/93587804-bb477380-f9aa-11ea-8a6f-2908dcda9ad2.png)

**Comment by AaronMT** [comment]
Yeah I see that too now. I'm in a Xcode 12 GM environment now 👍 – I'll continue on this
