### ISSUE TITLE
FXIOS-881 ⁃ Bad Request; Missing OAuth parameter: channel_id - When scanning QR code to link device to Firefox Account

### ISSUE THREAD

**Issue by FoxRunTime** [mozilla-mobile/firefox-ios#7296]
## Steps to reproduce
Install Firefox from the App Store
Engage account creation/login
Attempt to scan QR code to sign in

### Expected behavior
Account should pair up just fine

### Actual behavior
![IMG_0250](https://user-images.githubusercontent.com/22801221/93014767-ba2dd500-f5ab-11ea-9211-f55431bbe729.PNG)
This error cannot be rectifed by trying again or relaunching Firefox for iOS.

### Device & build information
* Device: Apple iPhone X (A1901, FQAC2B/A)
* Build version: iOS 13.7 (17H35)
* Firefox for iOS version: 28.1 (19225)
### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-881)

**Comment by inkychris** [comment]
Experiencing the same issue on android.
## Device:
- Sony Xperia 5ii (XQ-AS52)
- Android 10 (58.0.A.28.51)

## App:
- Firefox Browser (daylight)
- 84.1.2 build #2015783147
- AC: 67.0.14 - 8b9aabdda
- GV: 84.0.2-20201223151259
- AS: 67.0.0

**Comment by SimonBasca** [comment]
@inkychris are you still experiencing this issue?

**Comment by hacker** [comment]
I did experience it on iOS and I've just checked and it worked.

**Comment by SimonBasca** [comment]
It seems this is working fine now on iPhone Xr (14.3) v30.0 (3279). I will close the issue and will re-open if it occurs again.

**Comment by inkychris** [comment]
@SimonBasca sorry, only just tested this. Appears to still be an issue on Android, although it looks like there hasn't been an update to the app itself.

**Comment by softvision-miralobontiu** [comment]
I did not encounter the crash on the 1/6 Nightly build.
I've tested on Google Pixel (Android 10), Samsung Galaxy tab S6 (Android 10), and on OnePlus 5T (Android 10).

**Comment by SimonBasca** [comment]
@inkychris could you please let us know from what desktop OS are you trying to pair from?

**Comment by inkychris** [comment]
Hi, the android app updated to 84.1.3 over night and now and the pairing works as expected!

**Comment by K2adir** [comment]
Having this problem on 
android 10
IpadOs 14.2 
both running current latest firefox

**Comment by kaldown** [comment]
Just wanted to try firefox.
Yet get problems from the beginning, which I can't pass through.
Maybe next time =(

**Comment by groner** [comment]
I just hit this issue setting up firefox sync for the first time in a long time (or maybe ever).

Coming from the enrollment process, my desktop is at a URL starting with
    https://accounts.firefox.com/post_verify/
Scanning the QR code generated here with the "Turn on Sync" UI in firefox for iOS gets the above error.
Scanning the QR code with the iOS camera and then opening the link in firefox just shows a blank screen.

If I scan the QR code generated at 
    https://firefox.com/pair
using the "Turn on Sync" UI in firefox for iOS, then the setup is successful.

It seems like the links generated from the /post_verify/ page aren't being recognized in the "Turn on Sync" UI. Even an error screen asking the user to go to /pair/ would be an improvement for the people who run into this.

**Comment by Bauda** [comment]
> 
> 
> I just hit this issue setting up firefox sync for the first time in a long time (or maybe ever).
> 
> Coming from the enrollment process, my desktop is at a URL starting with
> https://accounts.firefox.com/post_verify/
> Scanning the QR code generated here with the "Turn on Sync" UI in firefox for iOS gets the above error.
> Scanning the QR code with the iOS camera and then opening the link in firefox just shows a blank screen.
> 
> If I scan the QR code generated at
> https://firefox.com/pair
> using the "Turn on Sync" UI in firefox for iOS, then the setup is successful.
> 
> It seems like the links generated from the /post_verify/ page aren't being recognized in the "Turn on Sync" UI. Even an error screen asking the user to go to /pair/ would be an improvement for the people who run into this.

Same problem and same solution on Firefox Nightly for Android.
