### ISSUE TITLE
FXIOS-895 ⁃ Siri shortcuts option in settings has been disabled for iOS lower than 14

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/firefox-ios#7311]
## Steps to reproduce
Get latest build from master
Open Settings
Go to Siri Shortcut
### Expected behavior
All options are in Settings
### Actual behavior
Siri Shortcuts settings is not shown on iOS 13 or any lower than 14
### Device & build information
* Device: Any
* Build version: Lower than 14

We realized about this thanks to this automated test: [testOpenSiriOption](https://github.com/mozilla-mobile/firefox-ios/blob/main/XCUITests/SettingsTest.swift#L27)

We see the condition to hide this setting on iOS lower than iOS 14 on a r[ecent commit](https://github.com/mozilla-mobile/firefox-ios/commit/adfb32d843856471b9c61fc24ef0bf43fcf8ba00#diff-95dc5abad5394ff7fd7f3c0975d6f3f7R59), but wondering if this is a mistake or this will be the implementation from now on @nbhasin2 
We can fix that or update the test, but would need to know the decision about that. Thanks!

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-895)

**Comment by dnarcese** [comment]
Fixed in #7315

**Comment by SimonBasca** [comment]
Verified fix on 28.2 (2470)
