### ISSUE TITLE
FXIOS-897 ⁃ Closing a tab via long pressing on Tab Counter will display "X" icon instead of "Reload" icon

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#7313]
## Steps to reproduce
1. Open a tab and go to "google.com"
2. Open a new tab
3. Long press on the Tab Counter
4. Tap on "Close Tab"
### Expected behavior
- The "Reload" button should be displayed.
### Actual behavior
- The "X" icon is displayed.
### Device & build information
* Device: iPhone XS (14.0b8)
* Build version: 28.2 (2451)
### Notes
Attachments: 
[Video.mp4.zip](https://github.com/mozilla-mobile/firefox-ios/files/5226172/Video.mp4.zip)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-897)

**Comment by deepal15** [comment]
@SimonBasca Issue seems to be fixed on latest commit "3d5506a4222f8f83e5712f5b18cd0b1a08e37682".
could you please confirm?

**Comment by SimonBasca** [comment]
Confirming that this no longer reproducible on latest main 79d3bca7b124.
