### ISSUE TITLE
FXIOS-898 ⁃ 28.2 missing L10N for default browser onboarding card

### ISSUE THREAD

**Issue by garvankeeley** [mozilla-mobile/firefox-ios#7314]
<img width="404" alt="image" src="https://user-images.githubusercontent.com/5495083/93234854-d1ef8f80-f74a-11ea-8a6b-35d61072ed9c.png">

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-898)

**Comment by garvankeeley** [comment]
possible problems:
- there is a space in the `tableName`, and I don't think the scripts support that, that will create a .strings file of the same name https://github.com/mozilla-mobile/firefox-ios/blob/0055f21e26d4a27d69bf3a743283fe6afd768c04/Client/Frontend/Strings.swift#L894-L894
- tableName: seems to be used in our code for extensions, and should be blank otherwise for the main binary strings
- `extension String` instead of `extension Strings`, should be fixed but probably isn't the bug. I tried changing this locally and it didn't fix the bug

**Comment by SimonBasca** [comment]
Verified fix on 29.0 (2639) fo ES, FR, DE, RO, JA.
