### ISSUE TITLE
FXIOS-909 ⁃ Link into Firefox in the settings app

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-ios#7326]
**Vision**

As a marketer, I want to message users to let them know about the new option to set Firefox as their default browser, and sent them directly to where they can change it

**Acceptance Criteria**

* Link set up that can be used in a marketing campaign and sends users into the page in settings app where users can set Firefox as the default browser

**Notes**

Suggested approach from Nish: Ex. we can add a new deeplink that triggers our code so when users open an email campaign with custom firefox:// deeplink -> app opens -> settings open to allow users in setting default browser

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-909)

**Comment by cbonacuse** [comment]
@dnarcese & @athomasmoz - just to clarify, this should be for a push campaign in Leanplum (not necessarily for email). I was OOO and just saw this today, sorry for the delay!
