### ISSUE TITLE
FXIOS-914 ⁃ There seems to be a publishing problem with [SCR39](https://www.w3.org/WAI/WCAG21/Techniques/client-side-script/SCR39), it stops after the example.

### ISSUE THREAD

**Issue by anubes19** [mozilla-mobile/firefox-ios#7332]
There seems to be a publishing problem with [SCR39](https://www.w3.org/WAI/WCAG21/Techniques/client-side-script/SCR39), it stops after the example.

I'd guess there's a code issue after the example, but I can't see it from a quick scan.

__Originally posted by @alastc in https://github.com/w3c/wcag/issues/1395__

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-914)

**Comment by alastc** [comment]
I got a ping about this, but it is an issue copied from a W3C repo, not relevant here.  I think it's an odd form of spam from @anubes19

**Comment by garvankeeley** [comment]
That user has opened 4 spam issues today in our repo.
