### ISSUE TITLE
FXIOS-921 ⁃ "Unable to open this link" message is displayed when opening a link from Skype in Firefox as default browser

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#7340]
## Preconditions:
- Set Firefox as default broser
## Steps to reproduce
1. Open Skype messenger
2. Tap on a link from a conversation
### Expected behavior
- Link should open in Firefox
### Actual behavior
- "Unable to open this link" message is displayed. After changing the default browser to Safari, the link is correctly opened in Safari.
### Device & build information
* Device: iPhone Xr 14.0
* Build version: 28.2 (2470)
### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-921)

**Comment by dnarcese** [comment]
@SimonBasca this works for me now. Can you test again?

**Comment by SimonBasca** [comment]
This seems to be working fine on v31.0 (3537).
