### ISSUE TITLE
FXIOS-922 ⁃ [Regression] Find in Page does not show the number of matches

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/firefox-ios#7341]
Failure detected by automated test running as part as the [Smoketest](https://app.bitrise.io/build/12973c31e7ae4c7c#?tab=log: ): [FindFromMenu](https://github.com/mozilla-mobile/firefox-ios/blob/main/XCUITests/FindInPageTest.swift#L36)

## Steps to reproduce
Go to a web site
Tap on PAM -> Find in Page
Type any char or word that appears several times

### Expected behavior
There is 1/1 if there is one match or 1/2 if there are two and so on
### Actual behavior
That 1/x part is not shown on iOS14

### Device & build information
* Device: iPhone 8
* Build version: main
### Notes
Attachments: Please see screenshot attached
![Simulator Screen Shot - iPhone 8 - 2020-09-18 at 12 21 15](https://user-images.githubusercontent.com/1897507/93587323-02813480-f9aa-11ea-8ee9-a0a7fd2ca9e8.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-922)

**Comment by data-sync-user** [comment]
➤ Ashley Thomas commented:

Should change to use native webkit, but that's only supported on iOS14+

**Comment by dnarcese** [comment]
Fixed in https://github.com/mozilla-mobile/firefox-ios/pull/7387

**Comment by SimonBasca** [comment]
Verified fix on 8f59ee4e2b1.
