### ISSUE TITLE
FXIOS-923 ⁃ [iOS14][Regression] Autofill user and password not working on latest main

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#7342]
## Preconditions
- Save a login and password for e.g. "github.com"
## Steps to reproduce
1. Go to "github.com/login"
### Expected behavior
- User and password should autofill
### Actual behavior
- User and password field are empty
### Device & build information
* Device: iPhone Xr (14.0)
* Build version: d20f1a2cf1a0
### Notes
- Not reproducible on 28.2 (2470) with iOS 14.0
- Not reproducible on main d20f1a2cf1 with iOS 13.7 
Attachments:

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-923)

**Comment by data-sync-user** [comment]
➤ Ashley Thomas commented:

Suspect this broke with security updates in v29

**Comment by SimonBasca** [comment]
This is working with the fix from 6abd15ba4.

**Comment by SimonBasca** [comment]
Verified on main 8f59ee4e
