### ISSUE TITLE
Can’t focus location bar with external keyboard shortcut when New Tab is set as Blank Tab

### ISSUE THREAD

**Issue by charlieegan3** [mozilla-mobile/firefox-ios#7349]
## Steps to reproduce
Press cmd+L on a tab with a webpage open

### Expected behaviour
Focus moves to and remains in the location bar

### Actual behaviour
Focus is immediately lost

### Device & build information
* Device: iPad Pro with Magic Keyboard 
* Build version: 28.2 2470

### Notes
In the animation you can see me repeatedly press cmd+L only to have the focus immediately lost.

Attachments: 
![D8A0D87F-4A26-4284-9FBA-7F6E982C3276](https://user-images.githubusercontent.com/1774239/93625161-64a55e00-f9d9-11ea-87ee-e70394000ec6.gif)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2555)

**Comment by athomasmoz** [comment]
This may be related to #7364 or have a similar fix

**Comment by SimonBasca** [comment]
@charlieegan3 this issue is no longer reproducible on my side, are you still able to reproduce?

**Comment by charlieegan3** [comment]
I am still able to replicate on that version :(

https://user-images.githubusercontent.com/1774239/126526532-1a00013d-a550-4aaa-a4b0-1946648e3f11.MP4

**Comment by SimonBasca** [comment]
I've manage to reproduce the issue but only after some specific steps:
Preconditions:
- Go to Settings -> New Tab -> Set homepage as blank tab
STR:
1. Go to github.com
2. Background Firefox
3. Foreground Firefox
4. Press cmd+L
Actual results:
- Focus is immediately lost in the URL bar

@charlieegan3 could you please confirm that after going to  Settings -> New Tab and changing to Firefox Home the issue will no longer be reproducible?

**Comment by charlieegan3** [comment]
Hi Simon. Yes, I can confirm that the behaviour is not reproducible when using FF Home are the new tab page.
