### ISSUE TITLE
FXIOS-929 ⁃ PhotoLib Crash on 28.2

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-ios#7350]
A new crash has come up with v28.2

If it's determine that this is happening often and has a noticeable impact for users, it should be fixed for v29

https://sentry-fm.prod.mozaws.net/mozilla/firefox-ios-280/issues/355758/?query=release%3A%22org.mozilla.ios.Firefox-28.2%22

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-929)

**Comment by garvankeeley** [comment]
```NSPhotoLibraryUsageDescription > This app has crashed because it attempted to access privacy-sensitive data without a usage description.  The app's Info.plist must contain an NSPhotoLibraryUsageDescription key with a string value explaining to the user how the app uses this data.```

**Comment by athomasmoz** [comment]
Steps to reproduce from user

> I’m on an iPad Pro 2020 release 11in (brand new) and have the latest system software and the latest app software but when I go to google image and click on one to ‘save image’ it crashes, doesn’t save the image and returns to my Home Screen. The app has full access to my photos and I don’t have the same issue at all on safari on the same iPad. Nor do I have an issue on Firefox on my Samsung S9 phone

**Comment by data-sync-user** [comment]
➤ Ashley Thomas commented:

#942 may also be steps to reproduce the crash

**Comment by athomasmoz** [comment]
Note for QA: There are more steps to reproduce in #7366

**Comment by SimonBasca** [comment]
Verified fixed on 29.0 (2740).
