### ISSUE TITLE
Glean `bookmarks.add` metric isn't capturing the same labels as legacy

### ISSUE THREAD

**Issue by travis79** [mozilla-mobile/firefox-ios#7351]
During my validation of the initial migration of legacy metrics to Glean metrics, I was looking at [bookmarks added broken down by location added from](https://sql.telemetry.mozilla.org/queries/73714#184357). 

In some cases we are seeing legacy count things that Glean is not, as in the case of the `context-menu` and `tab-tray` locations.  Meanwhile, we see counts in Glean for `__other__` for location that do not have corresponding legacy counts.  Based on the places where we have counts from both Glean and legacy (`activity-stream` and `page-action-menu`), my hypothesis is that Glean is recording the `context-menu` and `tab-tray` counts as `__other__`.  The ratio of legacy to Glean counts seems to support this as the `__other__` recorded by Glean is pretty close to the ratio of the `context-menu` + `tab-tray` counts of legacy. 

I'm not really sure how this is possible, since both legacy and Glean metrics are being recorded through the same section of code using the same labels, but it's worth looking into as we have time to ensure the best possible resolution in the data.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2556)

**Comment by lmarceau** [comment]
Since only `data-sync-user` has commented on the issue after the `Stalebot` GitHub action (which triggered the removal of the `stale` label) I’ll close this issue for now. Please let us know if you think this issue needs to be reopened, we'll gladly do so. Thank you!
