### ISSUE TITLE
FXIOS-934 ⁃ [Regression] App is closed when trying to visit a expired SSL certificate site

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/firefox-ios#7356]
## Steps to reproduce
Go to "https://expired.badssl.com/" -> Tap on Advanced -> Tap on Visit site anyway
### Expected behavior
The site is open and it shows: 
![IMG_50DBFD3738A4-1](https://user-images.githubusercontent.com/1897507/93759945-6d7d7600-fc0b-11ea-8108-b9bce2536834.jpeg)

### Actual behavior
The app is closed upon clicking on Visite site anyway. 

### Device & build information
* Device: iPhone 8
* Build version: iOS14
### Notes

See automated test failing due to this: [testSSL()](https://github.com/mozilla-mobile/firefox-ios/blob/main/XCUITests/NavigationTest.swift#L368)
This was working before until the update to iOS14

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-934)

**Comment by SimonBasca** [comment]
This is working with the fix from 6abd15ba4

**Comment by SimonBasca** [comment]
Verified fix on latest main 8f59e
