### ISSUE TITLE
FXIOS-936 ⁃ [L10n] In some languages (DE, FR) the close button for the Switch Your Default Browser is very close to the text

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/firefox-ios#7360]
## Steps to reproduce
Launch the app in DE or FR
### Expected behavior
The screen shows fine
### Actual behavior
The 'x' button for the Switch Your Default Browser has almost no margin with the text
### Device & build information
* Device: iPhone 8
* Build version: v29 beta
### Notes
Attachments: See screenshots
![SwitchYourDefaultBrowser DEPNG](https://user-images.githubusercontent.com/1897507/93821637-1e613080-fc5f-11ea-9715-ce1ec54d2a77.PNG)

![SwitchYourDefaultBrowser](https://user-images.githubusercontent.com/1897507/93821533-f83b9080-fc5e-11ea-8b2f-fecd7ad999c1.PNG)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-936)

**Comment by athomasmoz** [comment]
@brampitoyo What's your recommendation for this one? Should we add padding above or on the right of the text?

**Comment by SimonBasca** [comment]
Verified fix on 29.0 (2639).
