### ISSUE TITLE
FXIOS-937 ⁃ Compiler error on build:  No such module 'SwiftyJSON'

### ISSUE THREAD

**Issue by rpappalax** [mozilla-mobile/firefox-ios#7361]
## Steps to reproduce
1.  clone firefox-ios
2. run `./bootstrap`
3. Observe the following `*** Checking out SwiftyJSON at "5.0.0"`
4. Open XCode
5. Clear cache
6. Build project

### Expected behavior
7. project builds w/out error

### Actual behavior
7. Swift compiler error: `No such module 'SwiftyJSON'`

### Device & build information
* Device:  
* Build version: ?
### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-937)

**Comment by rpappalax** [comment]
This was happening on Xcode 12.2 beta for me, but I'm not longer seeing it on GM 12.0

**Comment by AhmSaeed** [comment]
@rpappalax I have the same issue with MacBook Intel based processor and Xcode 12.5.1, How to solve it?
