### ISSUE TITLE
FXIOS-944 ⁃ iOS 14 Widgets are not localized

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#7368]
**Steps to Reproduce:**

1. Add widgets to your homescreen (quick links, top sites, open tabs)
1. Change language to something other than English
1. View widgets on the homescreen

**Expected behaviour**

Widgets match the current language

**Actual behaviour**

Widgets are in English

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-944)

**Comment by SimonBasca** [comment]
@nbhasin2 It seems that we are missing some locales for Spanish (ES). The"Search in Firefox" and "Search in Private Browsing" strings are not localized. See screenshot.
![IMG_5825](https://user-images.githubusercontent.com/32130829/95217140-87b67700-07fb-11eb-8c2f-32ca9f5cb6c1.PNG)


For other locales (DE,  FR, RO) the strings are correct.  

![IMG_5826](https://user-images.githubusercontent.com/32130829/95217315-b896ac00-07fb-11eb-9bd5-0a98305bcdbe.PNG)

![IMG_5827](https://user-images.githubusercontent.com/32130829/95217246-a3ba1880-07fb-11eb-9a68-2865e6121ed0.PNG)

**Comment by SimonBasca** [comment]
Verified fixed on 29.0(2817) except for #7485.
