### ISSUE TITLE
FXIOS-963 ⁃ Missing '>' in Set as Default Browser option in Settings menu

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/firefox-ios#7391]
## Steps to reproduce
Using iOS14 and Firefox beta or main a98d6d134fa79482359678044f0afaae9ff19e27, go to Settings Menu
### Expected behavior
All options in Settings have the same format: SettningName > 
### Actual behavior
The Set as Default Browser option is missing the '>'
### Device & build information
* Device: iPhone 6s
* Build version: Firefox beta v29.x(2649)

### Notes
Attachments: See images below in different languages
![IMG_8306](https://user-images.githubusercontent.com/1897507/94243778-2bf50f80-ff18-11ea-8885-3ace1e2f5c40.PNG)
![IMG_8305](https://user-images.githubusercontent.com/1897507/94243781-2d263c80-ff18-11ea-8ee7-c2a8de564151.PNG)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2561)

**Comment by deepal15** [comment]
@isabelrios Do the app needs to display ">" for all other Settings options(Set as Default Browser, Privacy Policy, Show Tour, Send Feedback, Help, etc) or just for "Set as Default Browser"?

**Comment by data-sync-user** [comment]
➤ Ashley Thomas commented:

[~bpitoyo@mozilla.com] Are you on board with adding this arrow?
