### ISSUE TITLE
FXIOS-965 ⁃ Data urls do not load

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/firefox-ios#7393]
Issue found thanks to automated test part of the [SecurityTest suite](https://github.com/mozilla-mobile/firefox-ios/blob/main/UITests/SecurityTests.swift#L128)
## Steps to reproduce
Try to open a data url, for example: 
data:text/plain;base64,SGVsbG8sIFdvcmxkIQ==
or
data:text/html,%3Ch1%3EHello%2C%20World!%3C%2Fh1%3E

### Expected behavior
The website is open

### Actual behavior
The website is not loaded

### Device & build information
* Device: iPhone 6s
* Build version: beta v29.x or main branch
### Notes
See: https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URIs for more info.

There is one type of data url that is loading: data:,Hello%2C%20World! but not the others.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-965)

**Comment by garvankeeley** [comment]
Seems like WKWebView is blocking data: URL top-level loads, and only allowing subresources on the page to be 'data:' URL.
Safari is blocking all data URLs on https://www-archive.mozilla.org/quality/networking/testing/datatests.html.

**Comment by athomasmoz** [comment]
Thanks for following up Garvan. @isabelrios sounds like we can remove/update that test. Do you want me to leave this bug open to capture that task? If not, I'll close in favour of following Apple's security practices.

**Comment by isabelrios** [comment]
Thanks Garvan and Ashley, we will remove the test then, I will create a specific automation ticket for that one and close this.
