### ISSUE TITLE
FXIOS-975 ⁃ [Unit Test] There are unit tests failing constantly and/or intermittently

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/firefox-ios#7411]
Main branch is failing constantaly as well as PRs too when running these unit tests:
- testApplyRecords | XCTAssertEqual failed: ("1") is not equal to ("0")
- testBookmarks | failed - Should not have failed to get mock bookmarks

Intermittent:
- testCompareBreaches | XCTAssertNotNil failed
- testBlankPopUpUrl as described [here](https://github.com/mozilla-mobile/firefox-ios/issues/7307)

Having main branch red due to this failures could mask other real issues, even compilation errors because red is not an alarm signal for us anymore if the status is always red.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-975)

**Comment by data-sync-user** [comment]
➤ Ashley Thomas commented:

Before v29 we should ensure these are not failing due to bugs. The unit tests themselves can be fixed after

**Comment by isabelrios** [comment]
Simon and myself have been taking a look at these tests. Let us share some info about those tests here:
    

- testApplyRecords | XCTAssertEqual failed: ("1") is not equal to ("0")

This test is failing in [line260](https://github.com/mozilla-mobile/firefox-ios/blob/main/SyncTests/HistorySynchronizerTests.swift#L260). Looks like the number of entries is fine but fails to the the number of remote visits... We are not sure about what that is checking but so far no feature has been seen as broken


- testBookmarks | failed - Should not have failed to get mock bookmarks 

Bookmarks are not added to the mobile bookmark when running the test. This is NOT reproducible manually. If that the only case covered by this test, looks like we are safe 


- testCompareBreaches | XCTAssertNotNil failed

Looks like there are no breaches entries added in this test and that's why it is failing. We haven't found a way to test this, how to force a login entry to be breached and so appear and be tested. But the feeling is that the breaches alerts may not be appearing

I know the team is busy, so we can go ahead and disable them until there is more time to investigate and fix them. What do you think @athomasmoz @nbhasin2?

**Comment by athomasmoz** [comment]
Thanks @isabelrios ! That sounds like a good plan to me

**Comment by isabelrios** [comment]
Tests are being disabled in PR #7458 
I would suggest to open an issue to investigate the Breach alert failure...that does not look like needs an update but that something is not working well to retrieve the breach alerts/status
