### ISSUE TITLE
FXIOS-976 ⁃ Firefox 29.0 (2687) continuously crashes on startup

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#7413]
## Steps to reproduce
1. Launch Firefox (2687)
### Expected behavior
- Firefox should launch.
### Actual behavior
- Firefox continuously crashes.
### Device & build information
* Device: iPhone Xr (14.0)
* Build version: 29.0 (2687)
### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-976)

**Comment by data-sync-user** [comment]
➤ Ashley Thomas commented:

Idea: this could be the static library change.

**Comment by SimonBasca** [comment]
Fixed on latest beta 29.0 (2721).
