### ISSUE TITLE
FXIOS-977 ⁃ Link sharing via whatsapp is not working in Firefox. Works fine in Chrome

### ISSUE THREAD

**Issue by BigSamSampson** [mozilla-mobile/firefox-ios#7414]
## Steps to reproduce
1. Launch the app
2. Visit “ https://www.aspor.com.tr/turkiye-kupasi/kupatv/turkiye-kupasi/trabzonspor-2-0-alanyaspor-genis-mac-ozeti#”
3. Tap on whatsapp icon available below the video
### Expected behavior
User should ve able to share the link via whatsapp
### Actual behavior
Nothing happens when user clicks on Whatsapp
### Device & build information
* Device: iPhone 7+
* Build version: 14.0
### Notes
Attachments: 
[RPReplay-Final1601383610.zip](https://github.com/mozilla-mobile/firefox-ios/files/5299066/RPReplay-Final1601383610.zip)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-977)

**Comment by kathishivaramreddy** [comment]
PR for this has been raised https://github.com/mozilla-mobile/firefox-ios/pull/7505

**Comment by SimonBasca** [comment]
Verified fix on v34.0 (4795)
