### ISSUE TITLE
[XCUITests] Fix Navigation test: testLongPressLinkOptions

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/firefox-ios#7419]
This test is failing lately. See for example: 
https://dashboard.buddybuild.com/apps/57bf25c0f096bc01001e21e0/build/5f743e5d11d1a700010d890f/test/b98da044-fbc4-43cb-a37d-679c232bcfd7/74408648-4b05-446c-a4a6-9bfd38c6b1eb

Even though the correct screen is shown in the screenshots there, the test fails. We need to investigate how to better check that the test verifies what it is supposed to verify correctly.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2564)

**Comment by lmarceau** [comment]
Since only `data-sync-user` has commented on the issue after the `Stalebot` GitHub action (which triggered the removal of the `stale` label) I’ll close this issue for now. Please let us know if you think this issue needs to be reopened, we'll gladly do so. Thank you!
