### ISSUE TITLE
FXIOS-986 ⁃ Icon and title of tab doesn't show in open tabs widget

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-ios#7423]
## Steps to reproduce

1. Leave a tab open for awhile
2. Download the Firefox Open Tabs widget (I'm using size medium)
3. View the widget

### Expected behavior

Open tabs are displayed with the icon and title of each

### Actual behavior

For some tabs, the icon and/or title are missing

### Device & build information
* Device: iPhone 11
* Build version: 2719

### Notes
Attachments: 
![image](https://user-images.githubusercontent.com/43346208/94737148-36e9de80-0322-11eb-9597-cf5dd503c2bb.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-986)

**Comment by csuciu** [comment]
I can't reproduce this issues on latest master. Verifying as fixed.
