### ISSUE TITLE
FXIOS-990 ⁃ Set default browser panel description is cut-off in French

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla-mobile/firefox-ios#7429]
## Steps to reproduce

Open v29.0, check the message on homescreen

### Expected behavior

The description fits in French

### Actual behavior

The description abruptly cuts before "automatically in Firefox"

### Device & build information
* Device: iPhone X
* Build version: 29.0 (2667)

![signal-2020-10-01-105200](https://user-images.githubusercontent.com/1294206/94790094-bb456b80-03cd-11eb-8f54-40ae28e05c18.png)

cc @Delphine

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-990)

**Comment by data-sync-user** [comment]
➤ Ashley Thomas commented:

[~bmikel@mozilla.com] [~bpitoyo@mozilla.com] What are your thoughts on a solution for this? Should we shrink the text size or make the box larger?

**Comment by data-sync-user** [comment]
➤ Bram Pitoyo commented:

[~athomas@mozilla.com] [~bmikel@mozilla.com] I think the right solution is to make the box taller to fit one more line of heading (not wider, as it will bleed over the edge of the screen).

Yes, the box will then appear very tall on phones the size of my iPhone SE 1st generation, but my device is in the vanishing minority. Most iPhone devices out there should be tall enough to handle the height of this box. 

The font size can be the same as we have currently.

**Comment by SimonBasca** [comment]
Fixed on 29.0 (2817).
