### ISSUE TITLE
FXIOS-991 ⁃ Blank tabs are displayed after re-opening the app

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#7430]
## Steps to reproduce
1. Open  a few tabs e.g: "youbtube.com","google.com","news.google.com","cnn.com","youbtube.com".
2. Open tabs tray
3. Tap on "Close all tabs"
4. Tap "Undo Close Tabs"
5. Close Firefox from app switcher
6. Open Firefox
7. Tap on each of the tab to check that it's displayed correctly.
8. Restart Firefox.
### Expected behavior
- Tabs are correctly restored.
### Actual behavior
- Tabs are restored but are blank.
### Device & build information
* Device: iPhone Xr (14.0)
* Build version: 29.0 (2721)
### Notes
- After step 6) the last used tab is blank. After step 8) all the tabs are blank
Attachments:

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-991)

**Comment by data-sync-user** [comment]
➤ Ashley Thomas commented:

[~sbasca@mozilla.com]will try to find consistently reproducible steps

[~rpappalardo@mozilla.com] will check if we have automated tests around this

**Comment by data-sync-user** [comment]
➤ Richard Pappalardo commented:

We do have an automated test, but it only covers steps 1-4: https://github.com/mozilla-mobile/firefox-ios/blob/76faae8c6c94e22c8fbc0de72e2d06f615738e2c/XCUITests/TopTabsTest.swift#L112

**Comment by SimonBasca** [comment]
I was able to reproduce this issue 5 out of 5 times following the STR and starting Firefox from a clean install. We also have other examples of this issue happening. #7449

**Comment by csuciu** [comment]
I can constantly reproduce this issue following this steps:

1. Have only two default tabs open (the second one is focused).
2. Go to the app switcher and close the app.
3. Re-open the app.
4. Switch to the first tab.

Result: The first tab is empty (the thumbnail in tabs tray is correct).
Please check the video:
https://www.youtube.com/watch?v=3tepxc5ND4w

In most cases, if I re-open the app again, both tabs are blank.

iPhone 11 Pro (iOS 13.5)
v29.0 (2785)

**Comment by SimonBasca** [comment]
Verified fix on 29.0(2817).
