### ISSUE TITLE
FXIOS-992 ⁃ Open Tabs Widget for open tabs is not correctly populated after STR

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#7431]
## Preconditions:
- On iOS 14 add the Open Tabs Widget
- Launch Firefox
- Open 5 tabs with the following sites: "youbtube.com","google.com","news.google.com","cnn.com","youbtube.com".
## Steps to reproduce
1. Check the Widget
2. Close Firefox from app switcher
3. Re-open Firefox
4. Check the Widget
### Expected behavior
- The widget should be populated with the opened tabs.
### Actual behavior
- Only the last opened tab will be displayed.. After reloading all the opened tabs, the Widget will be correctly populated.
### Device & build information
* Device: iPhone Xr (14.0)
* Build version: 29.0 (2721)
### Notes
Attachments: 
[Video.mp4.zip](https://github.com/mozilla-mobile/firefox-ios/files/5312592/Video.mp4.zip)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-992)

**Comment by athomasmoz** [comment]
This may be fixed with tabs bug fixes. @boek will check

**Comment by SimonBasca** [comment]
Fixed on b37631c5400

**Comment by csuciu** [comment]
Verified as fixed on v29.2(3106)
