### ISSUE TITLE
FXIOS-993 ⁃ Localization not loading in latest v29 builds

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#7432]
From Delphine:

A contributor has reached out to me because he received Beta 29.0 build 2719 via Testflight this morning, and all locales have disappeared (it’s only available in English). Is anything wrong still with importing our v29 strings back?

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-993)

**Comment by nbhasin2** [comment]
This should be resolved in new Firefox Beta Build v29(1340) and above

**Comment by SimonBasca** [comment]
Verified fix on 29.0 (2785).
