### ISSUE TITLE
FXIOS-994 ⁃ Stop and reload actions don't match icons

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#7433]
On the latest iPad build, it looks like the Reload and Stop icons are swapped. (So I’m seeing the “X”, and when I tap it the page reloads and the icon switches briefly to the circle-arrow, then back to the “X” when the page is done loading…)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-994)

**Comment by csuciu** [comment]
Verifying as fixed on v29 (2785).
