### ISSUE TITLE
FXIOS-998 ⁃ [UI Test] Remove data url test

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/firefox-ios#7437]
According to issue https://github.com/mozilla-mobile/firefox-ios/issues/7393 there are some types of data url not supported anymore by WKWebView. So, we would need to remove this test.

https://github.com/mozilla-mobile/firefox-ios/blob/main/UITests/SecurityTests.swift#L128

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-998)

**Comment by kathishivaramreddy** [comment]
I have creaated PR for this https://github.com/mozilla-mobile/firefox-ios/pull/7487

**Comment by AaronMT** [comment]
Thanks for the contribution https://github.com/mozilla-mobile/firefox-ios/pull/7487
