### ISSUE TITLE
FXIOS-1004 ⁃ Text not localizable under Quick Action widget, appears in English only

### ISSUE THREAD

**Issue by Delphine** [mozilla-mobile/firefox-ios#7443]
## Steps to reproduce
* Set your device in any locale other than en-US (French, in my case)
* Install the Firefox Quick Action widget
* Press the widget for a while to get the option to modify the widget. Then click that - and then click "Quick action" to get a list of options

### Expected behavior
All sub-menu strings are localizable

### Actual behavior
Strings appear unlocalizable in sub-menu (see screenshot below). Only the "Cancel" button can be localized.

### Device & build information
* Device: iPod Touch - seventh generation, iOS 14.0.1
* Build version: Firefox Beta (Daylight 29.0, 2740)

### Notes
Screenshot: 
![ios](https://user-images.githubusercontent.com/399020/94976665-879c3b80-04ca-11eb-9794-ae202d7b936a.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1004)

**Comment by q2r5** [comment]
[QuickLinkSelection.intentdefinition](https://github.com/mozilla-mobile/firefox-ios/blob/main/WidgetKit/SearchQuickLinksSmall/QuickLinkSelection.intentdefinition) is the file that needs to be localized for this.

**Comment by dnarcese** [comment]
This should be fixed in #8050
