### ISSUE TITLE
FXIOS-1005 ⁃ Video window only displays black if switching orientation from portrait to landscape

### ISSUE THREAD

**Issue by benediktms** [mozilla-mobile/firefox-ios#7444]
## Steps to reproduce
Go to a website that would display a video in a HTML video element and in a modal (e.g.: the video on the retool website https://retool.com/)

### Expected behavior
Switching between portrait and landscape will display the video normally in each orientation

### Actual behavior
After switching to landscape the screen goes black. Switching back to portrait does not fix this, the only way to get the video to play is to quit Firefox.

### Device & build information
* Device: iPhone X
* Build version: 28.2
### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1005)

**Comment by SimonBasca** [comment]
I've manage to reproduce this issue on Firefox Beta 29.0 (2740). Note that his issue is not reproducible in Safari.

**Comment by dnarcese** [comment]
Is this still reproducible on v32?

**Comment by SimonBasca** [comment]
This issue is no longer reproducible on v34.0 (4900). We should re-open if it's reproducible again.
