### ISSUE TITLE
FXIOS-1008 ⁃ Restore tabs prompt is lost when opening links from other apps

### ISSUE THREAD

**Issue by rnewman** [mozilla-mobile/firefox-ios#7447]
## Steps to reproduce

1. Get Firefox to lose tabs on startup.
2. Click a link in a compatible app (e.g., Feedly, Tweetbot) or use "Open Later" to queue tabs to open.

### Expected behavior

1. The "Oops!" dialog should appear and allow tabs to be restored.
2. The external link should be added to the restored set.

### Actual behavior

1. The "Oops" dialog appears for a moment and is automatically dismissed.
2. Only the queued external links will be opened.

### Device & build information
* Device: iPhone 10
* Build version: 2719

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1008)

**Comment by aaronraimist** [comment]
Still happening on 2817
