### ISSUE TITLE
FXIOS-1009 ⁃ Restoring last tab is broken: white screen

### ISSUE THREAD

**Issue by rnewman** [mozilla-mobile/firefox-ios#7449]
## Steps to reproduce

1. Open a few tabs. Load pages.
2. Swipe Firefox away.
3. Reopen Firefox.

### Expected behavior

1. Last open tab loads.

### Actual behavior

1. Blank white screen, no URL in URL bar.
2. Actual title and page preview are visible for the affected tab in the tab switcher.
3. Switching to another tab will load that tab, but switching back never works.
4. Rather than a "Reload" button, the bottom bar shows a "Search" icon.

### Device & build information
* Device: iPhone X
* Build version: 2719

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1009)

**Comment by isabelrios** [comment]
I'm also seeing a white tab when opening a new one after opening Firefox from background, not sure if the reason would be the same. I will try to get clear steps

**Comment by SimonBasca** [comment]
Verified fix on 29.0(2817).
