### ISSUE TITLE
FXIOS-1014 ⁃ External keyboard not working on iPad

### ISSUE THREAD

**Issue by dnarcese** [mozilla-mobile/firefox-ios#7454]
Reported from https://matrix.to/#/!gMQVpNwAUiSZoqZRPe:mozilla.org/$ROSdgtK2Nnr5K2dhPHzEI1oFFgaoRNPdvp-s38UxkZQ?via=mozilla.org&via=matrix.org&via=raim.ist

## Steps to reproduce
1. Connect external keyboard to iPad
2. Try typing in Firefox
### Expected behavior
Input is received correctly
### Actual behavior
No input is received.
### Device & build information
* Device:  iPad Pro 10.5"
* Build version: Beta 29.0 (2740)
### Notes
Not a hardware issue because the keyboard is working in other apps.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1014)

**Comment by aaronraimist** [comment]
I can confirm this is fixed in 29.0 (2817)
