### ISSUE TITLE
FXIOS-1019 ⁃ Print to PDF

### ISSUE THREAD

**Issue by nasiralamreeki** [mozilla-mobile/firefox-ios#7459]
Safari for iOS allows pages to be printed to a PDF file and Firefox for Desktop Allows this but Firefox for iOS doesn't?

Being able to print pages to PDF is beneficial and should be brought to Firefox for iOS.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1019)

**Comment by SimonBasca** [comment]
This seems to be the same issue as #5389.
