### ISSUE TITLE
FXIOS-1020 ⁃ Keyboard input not working on simulator running iOS 14

### ISSUE THREAD

**Issue by vauxhall** [mozilla-mobile/firefox-ios#7460]
## Steps to reproduce
- Launch app using Fennec scheme on a simulator running on iOS 14
- Try to type on any input field or search bar

### Expected behavior
- Input appearing on input field

### Actual behavior
- Input field is empty

### Device & build information
* Device: Simulator running iOS 14
* Build version: Built from scratch with latest commit on main branch (d9a38baec87ad48ccaa6aca99b849fb042520b10)
### Notes
- The keyboard doesn't even appear when an input field becomes first responder (not even after toggling "Software Keyboard" with Command + K). But there is a work around to make the keyboard appear:

- Open Firefox app on Simulator, type on search bar
- Wait to see keyboard is not appearing and input is not being received on the search bar
- Go to Home (Send Firefox app to the background)
- Open Spotlight from Home and start typing on the search bar
- Wait for keyboard to appear
- Click cancel to dismiss Spotlight
- Go back to Firefox
- Click on search bar
- Wait for keyboard to appear
- You can click directly on the keyboard and the input will be received on the search bar, but if you trying typing directly from your laptop's keyboard input won't be received

Attachments:

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1020)

**Comment by boek** [comment]
This should be fixed with #7454
