### ISSUE TITLE
FXIOS-1024 ⁃ Save bookmark to folder

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#7464]
**Vision**

As a bookmarks user, I would like to save my bookmark to a specific folder, so that I know where to find it in future (on both desktop and iOS)

**Acceptance Criteria**

* Every time a bookmark has been added, a snackbar appears: “Bookmark added”
* There is an “Edit” action to the side of this snackbar – this action makes Firefox for iOS consistent with both Android and Desktop
* When "Edit" in the snackbar is tapped, it opens the **existing** “Edit Bookmark” interface. This will allow people to save bookmark to a specific folder, and to rename the bookmark if desired.
* Counts are added in Glean for clicks on the "Edit" button in the snackbar as a way to measure success

Mockups [https://www.figma.com/file/RTkm6nICWCoKXKou2uDPfe/Bookmarks?node-id=111%3A0](https://www.figma.com/file/RTkm6nICWCoKXKou2uDPfe/Bookmarks?node-id=111%3A0)
 (Also see the subsequent frame – there are two on the page).

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1024)

**Comment by data-sync-user** [comment]
➤ Ashley Thomas commented:

[~bpitoyo@mozilla.com] I added a few TBD items to think about here.

**Comment by brampitoyo** [comment]
### Mockups

https://www.figma.com/file/RTkm6nICWCoKXKou2uDPfe/Bookmarks?node-id=111%3A0

(Also see the subsequent frame – there are two on the page).

### Behaviour

- Every time a bookmark has been added, a snackbar appears: “Bookmark added”
- Add an “Edit” action to the side of this snackbar – this action makes Firefox for iOS consistent with both Android and Desktop
- When tapped, go to our existing “Edit Bookmark” interface. This will allow people to save bookmark to a specific folder, and to rename the bookmark if desired.

**Comment by data-sync-user** [comment]
➤ Roux Buciu commented:

Just a heads up [~bpitoyo@mozilla.com], instead of having "Cancel" on the top left as per the spec, that button will display an X. This will keep this page looking consistent with the X that shows up in the Library Panel when in bookmark edit mode.

**Comment by data-sync-user** [comment]
➤ Bram Pitoyo commented:

[~gbuciu@mozilla.com] Ah! I didn’t realise that our Bookmarks edit mode has an ‘x’ instead of a ‘Cancel’. An inherited design artefact that I missed.

Actually, I wonder if it would be better if we change that edit mode, replacing the ‘x’ with a ‘Cancel’? It’s more consistent with the way iOS handles things.

If it’s not easy to do, then making it an ‘x’ everywhere does seem like a good idea.

Thanks heaps for thinking about consistency!

**Comment by data-sync-user** [comment]
➤ Roux Buciu commented:

[~bpitoyo@mozilla.com] We can make that change, but it would have to be it's own ticket. If you'll remember, the reason we did that was because of the ellipse in localization issue we were having ("Bac..rds"). There's been some changes since that work was done on the Library Panel that might make allow this to work properly with localization, now, so we can definitely look into that, but, again, that would require it's own ticket and would be outside the scope of this, I'd say.

**Comment by SimonBasca** [comment]
@electricRGB can this issue be closed or is it still work in progress? I see that the patch landed on main 628e2beafb

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

I can see that this is fully implemented on v34.1 (5146). Marking as verified fix on v34.1 (5146).
