### ISSUE TITLE
FXIOS-1025 ⁃ WASM not loading in browser

### ISSUE THREAD

**Issue by rootVIII** [mozilla-mobile/firefox-ios#7465]
Version 28.2 (2470)
Device: Iphone 6+

I have a WASM being served on my private LAN and I can see it/play it on all devices except for mobile phone.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1025)

**Comment by dnarcese** [comment]
@rootVIII is this still reproducible on the latest version, v32? Is this also a problem on other mobile browsers, or just Firefox?

**Comment by rootVIII** [comment]
Hi @dnarcese  Actually thanks for reminding me. I eventually did get WASM to load on Firefox. However, the initial problem was due to the size of my WASM. I believe it was too large for a mobile browser. So that particular project never actually loaded on mobile, but others have. Can close this...
