### ISSUE TITLE
Today Widget - there's no space between the text and the bottom edge

### ISSUE THREAD

**Issue by csuciu** [mozilla-mobile/firefox-ios#7467]
iPad Air (iOS 14.0.1)
v29 (2785)

* Check the Today Widget on an iPad running iOS 14

Result: There's no space between the buttons names and the bottom edge.

<img width="298" alt="Screenshot 2020-10-07 at 14 31 13" src="https://user-images.githubusercontent.com/1866605/95326689-a1af9280-08ab-11eb-8fbf-9281d5405130.png">

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2571)

**Comment by lmarceau** [comment]
Since only `data-sync-user` has commented on the issue after the `Stalebot` GitHub action (which triggered the removal of the `stale` label) I’ll close this issue for now. Please let us know if you think this issue needs to be reopened, we'll gladly do so. Thank you!
