### ISSUE TITLE
FXIOS-1028 ⁃ Crash while loading logins after backgrounding and restoring Firefox

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#7468]
## Steps to reproduce
1. Go to Setting -> Login
2. Tap on the "Filter" field
3. Background Firefox
4. Restore Firefox
### Expected behavior
- Firefox should be correctly displayed in foreground.
### Actual behavior
- Firefox will crash.
### Device & build information
* Device: iPhone Xr (14.0)
* Build version: 29.0 (2785)
### Notes
Attachments: 
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/32130829/95332621-5ea5ed00-08b4-11eb-9d33-866cd72fef7c.gif)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1028)

**Comment by data-sync-user** [comment]
➤ Ashley Thomas commented:

[~nbhasin@mozilla.com]to check if tabs fix addresses this issue

**Comment by nbhasin2** [comment]
This is still an issue and will require a fix

**Comment by Jasminol** [comment]
Click the menu button Fx57menu , click Help and select Restart with Add-ons Disabled…. Firefox will start up with the Firefox Safe Mode dialog.

Note: You can also start Firefox in Safe Mode by holding down the shift key while starting Firefox.
When the Firefox Safe Mode window appears, press the button Start in Safe Mode.
After Firefox starts in Safe Mode, test for your problem.  https://www.myaarpmedicare.review/

**Comment by SimonBasca** [comment]
Verified fix on 29.0 (2966)
