### ISSUE TITLE
[a11y] iOS 14: VoiceOver continually reports message about pasting when focused on the address bar

### ISSUE THREAD

**Issue by jcsteh** [mozilla-mobile/firefox-ios#7476]
In iOS 14, VoiceOver now reports when an app pastes content from another app. Unfortunately, this causes problems in Firefox when focused on the address bar.

STR:

1. Copy text from another app (not Firefox) to the pasteboard.
2. Turn on VoiceOver.
3. Open Firefox.
    - Expected: VoiceOver should say "Firefox, Address bar, [URL], text field"
    - Actual: VoiceOver repeatedly says "Firefox pasted from [app]" or "Paste occurred"

I initially suspected this might be related to Firefox's "Offer to Open Copied Links, When Opening Firefox" setting. However, disabling this doesn't fix it. I guess it could also be related to paste and go. Hopefully, there's some way we can make this only paste when the user opens the app/initiates paste and go.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2572)

**Comment by jcsteh** [comment]
Originally reported by another user on Twitter (but I see this all the time myself): https://twitter.com/RealJimLockwood/status/1312482371862630401

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verifying as fix on main 228b77b9a89f133417cb748fcf720fb01e6b6f1a.

When VoiceOver is active and the “Firefox pasted from [app]" or "Paste occurred", voiceover will only say the message once.
