### ISSUE TITLE
[XCUITests] Move existing performance tests in ScreenGraph suite to the one to be created for Performance

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/firefox-ios#7479]
There are a few performance tests defined to measure the time it takes to load a website by pasting or typing in the URL bar:

[testChainedActionPerf1](https://github.com/mozilla-mobile/firefox-ios/blob/855dca83cf5833b45895e9909c69510b30c9cfa2/XCUITests/ScreenGraphTest.swift#L71)

[testChainedActionPerf2](https://github.com/mozilla-mobile/firefox-ios/blob/855dca83cf5833b45895e9909c69510b30c9cfa2/XCUITests/ScreenGraphTest.swift#L80)

It may be interesting to add these two tests to the new Performance test suite that is being defined/implemented by the test-eng team

cc FYi @AaronMT and @rpappalax

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2573)

**Comment by lmarceau** [comment]
Since only `data-sync-user` has commented on the issue after the `Stalebot` GitHub action (which triggered the removal of the `stale` label) I’ll close this issue for now. Please let us know if you think this issue needs to be reopened, we'll gladly do so. Thank you!
