### ISSUE TITLE
FXIOS-1045 ⁃ The"Search in Firefox" and "Search in Private Tab" strings are not localized in ES

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#7484]
**Steps to Reproduce:**

1. Add widgets to your homescreen (quick links, top sites, open tabs)
1. Change language to ES
1. View widgets on the homescreen

**Expected behavior**

The"Search in Firefox" and "Search in Private Tab" strings are not localized for Quick Action Small and Medium Widget.

**Actual behavior**

The"Search in Firefox" and "Search in Private Tab" strings are not localized for ES.

Note
- For other locales (DE, FR, RO) the strings are correct.

Screenshot.
![image](https://user-images.githubusercontent.com/32130829/95573756-9b98ed80-0a34-11eb-8bad-3643b2453503.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1045)

**Comment by dnarcese** [comment]
dupe #7485
