### ISSUE TITLE
FXIOS-1044 ⁃ The "Search in Firefox" and "Search in Private Tab" strings are not localized for ES.

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#7485]
**Steps to Reproduce:**

1. Add Quick Action widgets (Small and Medium) to your homescreen
2. Change language to ES
3. View widgets on the homescreen

**Expected behavior**

The"Search in Firefox" and "Search in Private Tab" strings are not localized for Quick Action Small and Medium Widget.

**Actual behavior**

The"Search in Firefox" and "Search in Private Tab" strings are not localized for ES.

Note
- For other locales (DE, FR, RO) the strings are correct.

Screenshot.
![image](https://user-images.githubusercontent.com/32130829/95573756-9b98ed80-0a34-11eb-8bad-3643b2453503.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1044)

**Comment by nbhasin2** [comment]
@SimonBasca Could you try `29.0 (2826)` it seems to be a cache issue that was not pushing proper l10n strings

**Comment by SimonBasca** [comment]
@nbhasin2 This is verified fixed on the latest build 29.0 (2826).
