### ISSUE TITLE
[webc-57060] www.rch.org.au - Design and functionality is broken on the site

### ISSUE THREAD

**Issue by karlcow** [mozilla-mobile/firefox-ios#7489]
**URL**: https://www.rch.org.au/clinicalguide/

**Browser / Version**: Firefox iOS 28.0
**Operating System**: iOS 13.6.1
**Tested Another Browser**: Yes Safari

**Problem type**: Site is not usable
**Description**: Buttons or links not working
**Steps to Reproduce**:
Works normally on Safari on iOS 

Initially reported on https://github.com/webcompat/web-bugs/issues/57060

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2575)

**Comment by lmarceau** [comment]
@csuciu @SimonBasca This seems fine on latest main https://github.com/mozilla-mobile/firefox-ios/commit/7bf455c419d93d73e76fa1cf268c8c67eca743e6. Can this be tested?
