### ISSUE TITLE
FXIOS-1052 ⁃ Glean lib iOS has excessive energy consumption

### ISSUE THREAD

**Issue by jevans-mozilla** [mozilla-mobile/firefox-ios#7493]
https://bugzilla.mozilla.org/show_bug.cgi?id=1666267

Garvan was the initial reporter for this issue, we have been asked for answers to the following questions to validate how to move forward:
1) it is still an issue? 
2) is it possible to get access to the data?
3) is there a way to measure this locally?

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1052)

**Comment by boek** [comment]
It looks like Glean is much quieter in v29. We're going to close this for now and will continue to monitor.
