### ISSUE TITLE
FXIOS-1056 ⁃ Updating from previous version will set Safari as default browser

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#7497]
## Preconditions
- Fresh install a previous version e.g. 28.2
- Set Firefox 28.2 as default browser
## Steps to reproduce
1. Update from 28.2 to v 29.0
### Expected behavior
- Firefox is set as default browser
### Actual behavior
- Safari is set as default browser after updating from previous version
### Device & build information
* Device: iPhone Xr 
* Build version: 29.0 (2848)
### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1056)

**Comment by data-sync-user** [comment]
➤ Daniela Arcese commented:

This was an iOS issue that was fixed in iOS 14.2
