### ISSUE TITLE
When downloading iOS configuration or management profiles, they are not added to Settings

### ISSUE THREAD

**Issue by kaylagalway** [mozilla-mobile/firefox-ios#7501]
Steps to reproduce:

* have Firefox set as default browser or open a web page in Firefox with a device profile download link
* click a link to download a configuration profile or device management profile for iOS
* it stays in downloads but there is no way for it to be saved to settings or opened in settings so that it is added to your list of profiles to be used

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2577)

**Comment by dnarcese** [comment]
We should check if this works in other browsers (other than Safari). Otherwise, this may be a functionality that only works in Safari.

**Comment by SimonBasca** [comment]
This issue is also reproducible in Chrome for iOS. When downloading iOS configuration or management profiles, they are not added to Settings.

**Comment by cat0x1f** [comment]
hey guys i noticed iOS is able to install a profile in a third-party app.
So can this project add a function like this?
![7E2B2DF7-89D2-4BAB-BAB2-7BF1EB1E033A](https://user-images.githubusercontent.com/72690879/210134571-5b3f92c9-ccf0-4dd0-8a6b-98332351a86c.png)
Can it open a pop-up web window after downloading a mobile profile?
And it will install a profile for device.
