### ISSUE TITLE
Desktop site shown instead of mobile

### ISSUE THREAD

**Issue by xyrer** [mozilla-mobile/firefox-ios#7512]
## Steps to reproduce
Go to https://www.apple.com/shop/buy-iphone/iphone-11
### Expected behavior
Show mobile version of the page
### Actual behavior
Shows desktop version of the page
### Device & build information
* Device: iPhone 11 pro Max
* Build version: Daylight 29.0 (2860)
### Notes
Tested the same page on safari and chrome for ios, both show it correctly on the same device
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2580)

**Comment by nasiralamreeki** [comment]
I can reproduce this on Firefox for iOS on iOS 14.

**Comment by SimonBasca** [comment]
Copying https://www.apple.com/shop/buy-iphone/iphone-11 in Safari will display the mobile version.
Copying https://www.apple.com/shop/buy-iphone/iphone-11 in Firefox will display the desktop version

**Comment by lmarceau** [comment]
Since only `data-sync-user` has commented on the issue after the `Stalebot` GitHub action (which triggered the removal of the `stale` label) I’ll close this issue for now. Please let us know if you think this issue needs to be reopened, we'll gladly do so. Thank you!
