### ISSUE TITLE
FXIOS-1073 ⁃ iPadOS Version reload button opens new tab

### ISSUE THREAD

**Issue by PerkyMcSkittles** [mozilla-mobile/firefox-ios#7515]
## Steps to reproduce
For me, I updated the browser to version 29 and anytime I click reload a new tab opens and the current tab does not reload. May be related to issue 1063, but this is how it shows on the iPad as opposed to the iPhone. I can still reload with the option in the ... menu. 

### Expected behavior
When I click reload I expect the page to reload

### Actual behavior
When I click the reload icon on my iPad it opens a new tab instead. 

### Device & build information
* Device: 2018 IPad Pro 11”
* Build version: 29
### Notes
Attachments: 
Video [link here](https://imgur.com/a/y3YjE99)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1073)

**Comment by SusanKRinWA** [comment]
same issue for me on both iPad2017 and iPad2019 running iPadOS 14.1

**Comment by SimonBasca** [comment]
Also reproducible on 29.1 (3022).

**Comment by athomasmoz** [comment]
@SimonBasca can you confirm that it's no longer reproducible on 29.1 without enabling that option in the debug menu?

**Comment by SimonBasca** [comment]
@athomasmoz  this is not reproducible with a clean install on v29.1 (3022), without enabling the "New tab toolbar button" from the debug menu on iPad.

**Comment by athomasmoz** [comment]
Thanks! I will close this, but link from the + button epic to make sure its fixed if we decide to go that route.
