### ISSUE TITLE
FXIOS-1078 ⁃ Firefox - The application crashes when we say Save Picture after long pressing on any image under the title of Images

### ISSUE THREAD

**Issue by BigSamSampson** [mozilla-mobile/firefox-ios#7520]
**Test Description:**

N / OK - After searching any text, after long pressing on any visual under the title Images, the application crashes when we say Save Picture. The same happens on the Picture detail page.

1. **Test Steps:**
2. The application opens
3. Anything is searched
4. Go to the visuals
5. Pressed long
6. Click Save Picture from the menu
7. It appears to be a crash.

Test Devices :  
APPLE   Iphone 6 Plus    12.2
APPLE   Iphone 6           IOS v11.4.1
APPLE   Iphone 6 Plus    IOS v12.4.2 

**Attachments:** 
![image](https://user-images.githubusercontent.com/66958331/96604168-768e5f80-12fd-11eb-8f17-8b58876f0c18.png)

**Comment by BigSamSampson** [comment]
Firefox 28.2(2470)

[firefox_save_image.zip](https://github.com/mozilla-mobile/firefox-ios/files/5409594/firefox_save_image.zip)

**Comment by data-sync-user** [comment]
➤ Ashley Thomas commented:

[~sbasca@mozilla.com] Can you check if this has been resolved? I think it was supposed to be fixed with #7350

**Comment by SimonBasca** [comment]
This issue is fixed in v29.0 and 29.1. 

@BigSamSampson could you please try upgrading to the latest Firefox version. Please re-open the issue if the crash still occurs.
