### ISSUE TITLE
FXIOS-1081 ⁃ Cleanup Onboarding Experiment and Promote Winner

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#7523]
**Vision**

The winning onboarding screens are in place and the others have been cleaned up to avoid confusion in the future

**Acceptance Criteria**

* The second onboarding card shown is the new card that showed better results in the A/B test
* The first onboarding card is not changed. Both control and override were the same in the experiment
* The leanplum test and alternate options for the first and second cards have been cleaned up from the code

**Visuals**

First onboarding card

!image-2020-10-20-09-11-29-978.png|width=370,height=802!

Second onboarding card

!image-2020-10-20-09-11-22-504.png!

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1081)

**Comment by csuciu** [comment]
Verifying as fixed on v30.0 (3242)
