### ISSUE TITLE
FXIOS-1083 ⁃ [Chron Tabs] Add Probes for Chron Tabs A/B Test

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#7526]
**Vision**

As a Product Manager, I want appropriate probes in place to determine if users are happy with the updates tabs tray design

**Acceptance Criteria**

* The following probes have been added to Glean:
  * Event for opening tab tray
  * Event for opening a tab in tab tray
  * Close tab tray
  * Metrics ping should include the # of tabs a user has
* The probes have been implemented in a way that allow us to measure success metrics:
  * Time from opening tab tray to opening a tab
  * Retention
    * New user
    * Existing user
    * Users with 7 or more tabs
* New/changed events are reflected in our external documentation
* Data stewards have signed off on changes

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1083)

**Comment by SimonBasca** [comment]
Verified fix on 31.0 (3467)
