### ISSUE TITLE
 Search - Unable to find a query consisting of numbers and a dot

### ISSUE THREAD

**Issue by BigSamSampson** [mozilla-mobile/firefox-ios#7534]
## Steps to reproduce
1. Open the firefox 29.0
2. Search query consisting of numbers and a dot, for example 19.10
### Expected behavior
The search engine displays the results associated with the query
### Actual behavior
No search occurs, nothing was found, and an inappropriate query appears in the address bar and a message "The request timed out. " is displayed
### Device & build information
* Device: Apple iPhone 6S - iOS 13.3.1 , iphone 7 plus (13.7)
* Build version: firefox 29.0(2860)
![Video_53bc9fd2d93ed224be71a0f46c0a96c3](https://user-images.githubusercontent.com/66958331/96859879-b888e400-146a-11eb-958b-8dd491afa936.gif)

### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2587)

**Comment by SimonBasca** [comment]
Note : Not reproducible in Safari.

**Comment by lmarceau** [comment]
Since only `data-sync-user` has commented on the issue after the `Stalebot` GitHub action (which triggered the removal of the `stale` label) I’ll close this issue for now. Please let us know if you think this issue needs to be reopened, we'll gladly do so. Thank you!
