### ISSUE TITLE
FXIOS-1093 ⁃ mynet.com-Impossible to share via WhatsApp, link is not clickable

### ISSUE THREAD

**Issue by BigSamSampson** [mozilla-mobile/firefox-ios#7535]
## Steps to reproduce
1. Open mynet.com
2. Open burger menu
3. Click tab « Video »
4. Click on « play » on video « 23 saat once »
5. Click on WhatsApp logo for sharing
### Expected behavior
I expect that I could share website via WhatsApp
### Actual behavior
Button with WhatsApp logo is not clickable
### Device & build information
* Device:  iPhone 7 - iOS 14.0.1
iphone 7 plus ios 13.7
* Build version: firefox 29.0(2860)
### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1093)

**Comment by dnarcese** [comment]
Dupe of #7505
