### ISSUE TITLE
FXIOS-1094 ⁃ Clicking email in order to send an article results in no action

### ISSUE THREAD

**Issue by BigSamSampson** [mozilla-mobile/firefox-ios#7536]
## Steps to reproduce
1. open firefox browser
2. type in yahoo.com and search
3. select article https://www.yahoo.com/sports/esp-ns-maria-taylor-receives-support-from-colleagues-after-sharing-hate-message-225716821.html
4. click on the email icon
### Expected behavior
an email application to open in which the URL of the article is collated
### Actual behavior
nothing happens
### Device & build information
* Device: iPad Air 2
* Build version: 13.5.1
[RPReplay_Final1603363549.zip](https://github.com/mozilla-mobile/firefox-ios/files/5422189/RPReplay_Final1603363549.zip)

### Notes
Its not reproducible in Safari Browser.
Attachments:

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1094)

**Comment by dnarcese** [comment]
@BigSamSampson this is working for me now. Has it been fixed for you?

**Comment by dnarcese** [comment]
Closing for now. Can re-open if this is still an issue
