### ISSUE TITLE
FXIOS-1095 ⁃ Selecting "No" in the tabs restore prompt after crashing the app and opening an external link will still restore the tabs 

### ISSUE THREAD

**Issue by csuciu** [mozilla-mobile/firefox-ios#7537]
latest master
iPhone 11 Pro (13.5)

1. Open a few tabs.
2. Crash the app using the option from the debug menu.
3. Open a link from outlook.
4. The tabs restore prompt is displayed.
5. Select "No"
 
Result: The tabs are restored even though you chose not to.

If the app is open from the home screen after a crash, the behaviour is correct (the tabs are not restored when selecting "No" in the tabs restore prompt)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1095)

**Comment by nbhasin2** [comment]
@csuciu Not all tabs should be restored but it should still open the link you came from even if you select `No` 
Is that whats happening?

**Comment by csuciu** [comment]
You are right, only the external link is open in a new tab.
