### ISSUE TITLE
Incorrectly Assuming URL for some searches in CN

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#7538]
From a user review on v29:
Every time you want to search, as long as you type a number in front and type Chinese back to other words, the system will automatically recognize it as a web address, resulting in failure to display

https://app.appbot.co/apps/854569-firefox-private-safe-browser/reviews/2004603220?seid=20645787

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2588)

**Comment by lmarceau** [comment]
Since only `data-sync-user` has commented on the issue after the `Stalebot` GitHub action (which triggered the removal of the `stale` label) I’ll close this issue for now. Please let us know if you think this issue needs to be reopened, we'll gladly do so. Thank you!
