### ISSUE TITLE
FXIOS-1099 ⁃ Add Bitrise YML file to repo

### ISSUE THREAD

**Issue by jevans-mozilla** [mozilla-mobile/firefox-ios#7540]
┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1099)

**Comment by data-sync-user** [comment]
➤ Ashley Thomas commented:

Do in first sprint of release to give extra time for testing/baking

**Comment by data-sync-user** [comment]
➤ Nishant Bhasin commented:

This is done so going to close it
