### ISSUE TITLE
Thumbnails gone when undoing closing all tabs

### ISSUE THREAD

**Issue by dnarcese** [mozilla-mobile/firefox-ios#7547]
### STR
1) Open tab tray
2) Click trash can to delete all tabs
3) Click undo on toast to re-open those tabs

### Expected Behaviour
The thumbnails for all the sites are still there.

### Actual Behaviour
The thumbnails are all blank.

<img width="390" alt="image" src="https://user-images.githubusercontent.com/8919439/96942759-040bb400-14a4-11eb-82c3-96b3c5f9cf23.png">

_Originally posted by @nbhasin2 in https://github.com/mozilla-mobile/firefox-ios/pull/7531#issuecomment-714832876_

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2592)

**Comment by lmarceau** [comment]
Since only `data-sync-user` has commented on the issue after the `Stalebot` GitHub action (which triggered the removal of the `stale` label) I’ll close this issue for now. Please let us know if you think this issue needs to be reopened, we'll gladly do so. Thank you!
