### ISSUE TITLE
"Change password" and "require password" fields are not greyed out when inactive

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#7553]
## Steps to reproduce
1. Clean install Firefox
2. Go to Settings -> Face ID & Passcode
### Expected behavior
- "Change password" and "require password" fields should be greyed out when pass code is turned off.
### Actual behavior
- "Change password" and "require password" fields are not greyed out although  passcode protection is turned off.
### Device & build information
* Device: iPhone XS
* Build version: 29.1 (2966)
### Notes
Attachments: 
![76ebf8e1-862b-48f6-99b1-ff1f871c4efd](https://user-images.githubusercontent.com/32130829/97206503-7ab8f200-17c1-11eb-9071-b52304dd04ec.jpg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2595)

**Comment by lmarceau** [comment]
Since only `data-sync-user` has commented on the issue after the `Stalebot` GitHub action (which triggered the removal of the `stale` label) I’ll close this issue for now. Please let us know if you think this issue needs to be reopened, we'll gladly do so. Thank you!
