### ISSUE TITLE
FXIOS-1114 ⁃ [Chronologicla - Tabs] Top buttons bar does not respect theme

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#7554]
## Steps to reproduce
1. Change appearance to Dark
2. Go to "chronological-tabs"
### Expected behavior
- Top buttons bar should respect theme 
### Actual behavior
- Top buttons bar theme is light
### Device & build information
* Device: iPhone Xr (14.0)
* Build version: 5adc3a470145
### Notes
Attachments: 
![IMG_5907](https://user-images.githubusercontent.com/32130829/97207508-c7e99380-17c2-11eb-86fd-c9ef8893c620.PNG)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1114)

**Comment by brampitoyo** [comment]
@SimonBasca @dnarcese These are inspectable Figma mockups for Chronological Tabs Tray on both Light and Dark themes:

https://www.figma.com/file/IPJI0imlPqLAjISVZBTW7O/Tab-Tray

| Light theme | Dark theme |
| --- | --- |
| <img width="375" alt="Light@2x" src="https://user-images.githubusercontent.com/51007/97387742-79133980-193b-11eb-920e-9dc35282bdf7.png"> | <img width="375" alt="Dark@2x" src="https://user-images.githubusercontent.com/51007/97387748-7b759380-193b-11eb-9749-34aab7e0577f.png"> |
| No colour difference between the `base` page and the tab tray that sits `elevated` on top of it. | Apple provides [`UIUserInterfaceLevel.elevated`](UIUserInterfaceLevel.elevated) colour values, which are different from `base` level. |

To ensure compatibility with all future iOS versions, let’s implement our dark theme Chronological Tabs Tray using these system-provided elevated colour values.

**Comment by q2r5** [comment]
The only issue I see with using the system-provided colors is that dark mode didn't exist prior to iOS 12.0, and elevated colors are only 13+. So there either needs to be a fallback set of photon colors for the custom dark mode on older versions, or the minimum requirement needs bumped up from 11.4. (Oddly enough though, the `README` says the minimum supported version is 12.0.)

**Comment by brampitoyo** [comment]
@q2r5 As I understand it, our Library panel uses Photon colours and not system-provided ones. I wonder whether we can reuse the same values for the tab tray on iOS ≤12.0?

**Comment by dnarcese** [comment]
Fixed in #7557
