### ISSUE TITLE
FXIOS-1119 ⁃ [Bug] Empty Bookmarks section after update or fresh install

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/firefox-ios#7558]
## Steps to reproduce
1. Have a fresh install of Firefox 29.1 (2966)
2. Bookmark a couple of websites
3. Tap the ☰ button 
4. Tap "Your Library" check the Bookmarks section

### Expected behavior
Previously saved Bookmarks should be displayed.

### Actual behavior
Empty Bookmarks section

## Alternative Steps to reproduce
1. Have Firefox 28.1 (19225) installed and a couple of Bookmarks saved.
2. Update to Firefox 29.1 (2966)
3. Open the Bookmarks section

### Expected behavior
Previously saved Bookmarks should be available after update.

### Actual behavior
Empty Bookmarks section

### Device & build information
* Device: 
• iPhone X iOS 13.3.1
• iPhone XS Max (14.0)

* Build version: Firefox 29.1 (2966) 

### Notes
❗ Similar with #7407

Reproducible after performing the following updates
28.2 (2470) → 29.1 (2966)
29.0 (2860) → 29.1 (2966)

► Screenshot
![rsz_screenshot_2020-10-27_at_113149](https://user-images.githubusercontent.com/51314259/97283158-2dcc2e80-1848-11eb-9c2d-e4be8adb1248.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1119)

**Comment by isabelrios** [comment]
We started to see this when running our automated tests, see issue #7521 I tried to repro manually but was not able, but looks like after this issue just open there is actually something going on there. 

cc @athomasmoz since it may be a high priority issue if there are clear steps to reproduce

**Comment by SimonBasca** [comment]
Note :  Switching the panels or restarting the app does not populate the bookmark list.

**Comment by isabelrios** [comment]
I just got the update from TF to this build and yeah, my bookmarks are gone, as well as the default bookmarks folders

**Comment by data-sync-user** [comment]
➤ Nishant Bhasin commented:

This bug is caused by AppServices v65. Going to revert AppServices to an older version that we used originally for v29.

**Comment by SimonBasca** [comment]
Verified fix on 29.1 (3022)
