### ISSUE TITLE
[Bug]Confirmation snackbars are missing from the Tabs Tray

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/firefox-ios#7562]
## Prerequisites
The user should be signed in to Sync 
Have a couple of open tabs

## Steps to reproduce
1. Open the Tabs Tray
2. Use the "force touch" feature on any tab
3. Select one by one:
• Add to Bookmarks
• Send to Device
• Copy URL

### Expected behavior
From a consistency point of view, for each action mentioned in Step 3 a confirmation snackbar should be displayed.
Performing the same steps from the page view by tapping the **...** button displays confirmation snackbars.

### Actual behavior
Nothing is displayed

### Device & build information
* Device: all
* Build version: Firefox 29.1 (2966)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2597)

**Comment by brampitoyo** [comment]
Agreed. Each of those actions should show confirmation snackbars.

Since we already have a design for these snackbars, no UI will be required. This issue is ready for Engineering.

**Comment by brampitoyo** [comment]
@AndiAJ @athomasmoz I’ve found a similar issue in the address bar context menu, and have filed it on #7605.

**Comment by lmarceau** [comment]
Since only `data-sync-user` has commented on the issue after the `Stalebot` GitHub action (which triggered the removal of the `stale` label) I’ll close this issue for now. Please let us know if you think this issue needs to be reopened, we'll gladly do so. Thank you!
