### ISSUE TITLE
[Bug]Context menu "Bookmark link" options isn't updated

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/firefox-ios#7563]
## Steps to reproduce
1. Navigate to cnn.com
2. Long tap on an of the featured articles
3. Select "Bookmark link"
4. Long tap on the same article 
5. Check the context menu

### Expected behavior
Step 5. "Remove Bookmark" should be displayed instead of "Bookmark link"

### Actual behavior
Step 5. "Bookmark link" remains displayed 

### Device & build information
* Device: iPhone X iOS 13.3.1
* Build version: Firefox 29.1 (2966)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2598)

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verified fix on main 9eea0a004e02ebdce2a6acd4e48b841212aba05b.
