### ISSUE TITLE
[Bug] History items aren't displayed right away as Pinned to Top Sites 

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/firefox-ios#7564]
## Prerequisites
Have a couple of History items

## Steps to reproduce
1. Tap the ☰ button
2. Tap "Your Library" → "History"
3. Long tap on any History item
4. Select "Pin to Top Sites" from the context menu
5. Dismiss the History section
6. Check the Top Sites section from the Home screen

### Expected behavior
The desired History item should be pinned to Top Sites

### Actual behavior
The History item should isn't pinned right away to Top Sites
It gets displayed only after opening and dismissing the Tabs Tray or after you put in background and resume Firefox

### Device & build information
* Device: iPhone X iOS 13.3.1
* Build version: Firefox 29.1 (2966)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2599)

**Comment by lmarceau** [comment]
Since only `data-sync-user` has commented on the issue after the `Stalebot` GitHub action (which triggered the removal of the `stale` label) I’ll close this issue for now. Please let us know if you think this issue needs to be reopened, we'll gladly do so. Thank you!
