### ISSUE TITLE
[Bug]Custom search engines without any name can be saved

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/firefox-ios#7565]
## Steps to reproduce
1. Tap the ☰ button → "Settings"
2. Select "Search" → "Add Search Engine"
3. Leave the "Title" section empty, fill in the "URL" section with https://www.ecosia.org/search?q=%s

### Expected behavior
Error message should be displayed.
Shouldn't be able to save no named custom search engines.

### Actual behavior
A custom search engine without any name is created.

### Device & build information
* Device: iPhone X iOS 13.3.1
* Build version:  Firefox 29.1 (2966)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2600)

**Comment by lmarceau** [comment]
Since only `data-sync-user` has commented on the issue after the `Stalebot` GitHub action (which triggered the removal of the `stale` label) I’ll close this issue for now. Please let us know if you think this issue needs to be reopened, we'll gladly do so. Thank you!
