### ISSUE TITLE
[Bug]Reader mode icon moves in the URL bar after rotation

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/firefox-ios#7566]
## Steps to reproduce
1. Navigate to https://en.wikipedia.org/wiki/Main_Page
2. Check the position of the reader mode icon
3. Rotate the device to landscape view
4. Rotate the device back to portrait view

### Expected behavior
Step 4: The reader mode icon should keep its position in the URL bar
### Actual behavior
The Reader mode icon moves to the left, leaving empty space in the URL bar

### Device & build information
* Device: iPhone X iOS 13.3.1
* Build version: Firefox 29.1 (2966)

### Notes
► Screenshot before rotation
![rsz_screenshot_2020-10-27_at_161847](https://user-images.githubusercontent.com/51314259/97315265-34bb6700-1871-11eb-882b-82914b7170a5.png)

► Screenshot after rotation
![rsz_screenshot_2020-10-27_at_161918](https://user-images.githubusercontent.com/51314259/97316267-39cce600-1872-11eb-9cbc-b36e20805f48.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2601)

**Comment by SimonBasca** [comment]
Note: Also reproducible after backgrounding and restoring Firefox.

**Comment by lmarceau** [comment]
Since only `data-sync-user` has commented on the issue after the `Stalebot` GitHub action (which triggered the removal of the `stale` label) I’ll close this issue for now. Please let us know if you think this issue needs to be reopened, we'll gladly do so. Thank you!
