### ISSUE TITLE
FXIOS-1128 ⁃ Crash: Top sites widget favicon not loading

### ISSUE THREAD

**Issue by nbhasin2** [mozilla-mobile/firefox-ios#7567]
[v3NlsweMYlNaeGJPVfv53.xccrashpoint.zip](https://github.com/mozilla-mobile/firefox-ios/files/5447367/v3NlsweMYlNaeGJPVfv53.xccrashpoint.zip)

Silent widgetkit top sites crash where we were unable to fetch favicons for websites that do not have any favicon.

STR:
    Add top sites widget
    Pin a website with no favicon to Top Site

Expected result
    Widget shows default favicon or a custom one for website

Actual
    Widget doesn't show any favicon and crashes silently while fetching default favicon

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1128)

**Comment by SimonBasca** [comment]
Verified fix on 29.1 (3022)
