### ISSUE TITLE
FXIOS-1130 ⁃ [Chronological tabs] On devices < ios 13, the nav toolbar is blue

### ISSUE THREAD

**Issue by dnarcese** [mozilla-mobile/firefox-ios#7569]
## Steps to reproduce
Run chronological-tabs branch on a device on iOS lower than 13.

### Expected behavior
Nav toolbar is grey and white like the mocks.

### Actual behavior
Nav toolbar is blue
 ![](https://user-images.githubusercontent.com/11432165/97348955-4139c280-1865-11eb-84fa-674787351117.png)

### Device & build information
* Device: I used iphone SE on iOS 12.4
* Build version: ?

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1130)

**Comment by lolrepeatlol** [comment]
Unsure if this helps, but I'm 99.999% sure this is an >iOS 13 thing, not 14. :)

**Comment by dnarcese** [comment]
@lolrepeatlol thanks!

**Comment by dnarcese** [comment]
Fixed in #7557
