### ISSUE TITLE
FXIOS-1132 ⁃ [L10N] Migrate localizations to new system

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#7571]
- [x] Write script to map between `.xcloc` and the current directory structure in the l10n repo
- [x] When importing locales, check a set of required IDs and backfill with the `en` locale*
- [x] Test an export in the L10N repo to verify everything looks good
- [x] Verify we can edit pontoon Filenames. If we can't, we'll have to add that to our script.
- [x] Lock translations in Pontoon
- [x] Land PR to fix strings in this repository
- [x] Work with L10N to get a quick export and import
- [x] Document new L10N process
- [ ] (bonus) Create export / import actions on Github.

\*
```python
//required_ids = [
//    'NSCameraUsageDescription',
//    'NSLocationWhenInUseUsageDescription',
//    'NSMicrophoneUsageDescription',
//    'NSPhotoLibraryAddUsageDescription',
//    'ShortcutItemTitleNewPrivateTab',
//    'ShortcutItemTitleNewTab',
//    'ShortcutItemTitleQRCode',
//]
// backfill required properties from en locale if missing or app will crash on those locales.
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2602)

**Comment by nishant2718** [comment]
Besides Github Actions, this seems to be complete.
