### ISSUE TITLE
[Bug]Tab history still visible after clearing all history

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/firefox-ios#7573]
## Steps to reproduce
1. Visit a few websites on a single tab.
2. Go to the History menu and delete all history. (Or clear the "Browsing History" from Data Management)
3. Go back to the tab, long tap the back button.

### Expected behavior
No recent tab history should be displayed.

### Actual behavior
The tab's history is still displayed as long as you don't close the tab, even after an app restart.

### Device & build information
* Device: iPhone X iOS 13.3.1
* Build version: Firefox 29.1 (2966)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2603)

**Comment by data-sync-user** [comment]
➤ Ashley Thomas commented:

Timebox investigation to a 2

**Comment by data-sync-user** [comment]
➤ Nishant Patel commented:

Tests pending.
