### ISSUE TITLE
FXIOS-1136 ⁃ [Bug] No confirmation snackbar displayed when closing the private open tabs

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/firefox-ios#7575]
## Prerequisites
Switch to PB
Have a couple of private open tabs

## Steps to reproduce
1. Open the Tabs Tray
2. Swipe delete one of the Private open tabs
3. Close all Private tabs using the bin icon from the action bar

### Expected behavior
Steps 2 & 3: Confirmation snackbar along with undo option should be displayed 

### Actual behavior
No confirmation, can't undo the deletions

### Device & build information
* Device: iPhone X iOS 13.3.1
* Build version: Firefox 29.1 (2966)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1136)

**Comment by dnarcese** [comment]
We changed this behaviour to not allow undo for private tabs.
