### ISSUE TITLE
FXIOS-1137 ⁃ [Bug] Empty Reading list icons should be white

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/firefox-ios#7576]
## Prerequisites
Dark theme should be used
Don't have any item saved to the Reading list

## Steps to reproduce
1. Open the "Reading list"
2. Check the icons color from the description

### Expected behavior
From a consistency point of view the color of the icons should be the same as the one's from:

► Reader mode view ![rsz_1e494391-7e72-416f-b203-305a7c99edb4](https://user-images.githubusercontent.com/51314259/97416144-be6d4200-190e-11eb-9739-6b75d4da58b2.png)

► ⋮ Page Action Menu ![rsz_20cf99d3f-18a1-433f-a105-ad329f37dc8b](https://user-images.githubusercontent.com/51314259/97416536-3b98b700-190f-11eb-852d-ea567d4c6dcc.png)

### Actual behavior
Black icons displayed in the empty Reading list description
![rsz_f7a30092-a641-4654-b8db-d37352518009](https://user-images.githubusercontent.com/51314259/97416762-887c8d80-190f-11eb-831f-83ea0cbb4938.png)

### Device & build information
* Device: iPhone X iOS 13.3.1
* Build version: Firefox 29.1 (2966)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2605)

**Comment by SimonBasca** [comment]
This issue is no longer reproducible on v9000 (21167) or v106 (20813). It was possibly fixed by https://github.com/mozilla-mobile/firefox-ios/issues/11825. Please re-open if it's still an issue on your side.
