### ISSUE TITLE
[Bug] Download not initiated on https://file-examples.com/ after tapping the download button

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/firefox-ios#7577]
## Steps to reproduce
1. Navigate to https://file-examples.com/index.php/sample-documents-download/sample-pdf-download/
2. Tap the "Download sample pdf file" next to one of the listed samples

### Expected behavior
The download of the desired file should be initiated

### Actual behavior
Nothing happens

### Device & build information
* Device: iPhone X iOS 13.3.1
* Build version: Firefox 29.1 (2966)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2606)

**Comment by lmarceau** [comment]
Since only `data-sync-user` has commented on the issue after the `Stalebot` GitHub action (which triggered the removal of the `stale` label) I’ll close this issue for now. Please let us know if you think this issue needs to be reopened, we'll gladly do so. Thank you!
