### ISSUE TITLE
[Bug] Enhanced tracking protection doesn't match desktop/android

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/firefox-ios#7579]
## Prerequisites
You can either set ETP to Standard or Strict

## Steps to reproduce
1. Navigate to https://senglehardt.com/test/trackingprotection/test_pages/
2. Tap on Fingerprinting ONLY
3. Tap on Cryptomining ONLY
4. Tap on Fingerprinting and Cryptomining

### Expected behavior
Fingerprinting and Cryptomining should always be blocked with either Standard or Strict ETP

### Actual behavior
Nothing is blocked

### Device & build information
* Device:  iPhone X iOS 13.3.1
* Build version: Firefox 29.1 (2966)

### Notes
✔️ Checked theverge.com and cnn.com and it seems that it works properly  
✔️ Both Fenix and Firefox for Desktop block properly the content from https://senglehardt.com/test/trackingprotection/test_pages/
❗ Didn't check all option from the above mentioned website

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2607)

**Comment by lmarceau** [comment]
Since only `data-sync-user` has commented on the issue after the `Stalebot` GitHub action (which triggered the removal of the `stale` label) I’ll close this issue for now. Please let us know if you think this issue needs to be reopened, we'll gladly do so. Thank you!
