### ISSUE TITLE
[Bug]Firefox crashes after pasting a link in the "Search Tabs" text box while in re-arranging mode

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/firefox-ios#7581]
## Prerequisites
Have a link copied to clipboard
Have a couple of open tabs

## Steps to reproduce
1. Open the Tabs Tray
1. Long tap to re-arrange on of the open tabs
1. While holding and moving the desired tab, tap the "Search Tabs" text box
1. Long tap the "Search Tabs" text box
1. Tap "Paste" from the context menu

### Expected behavior
Step 3 and 4 - No action should be allowed when tabs are in re-arranging mode

### Actual behavior
Step 3 and 4 - Can tap and paste anything in the  "Search Tabs" text box
Step 5 - Crash :boom:

### Device & build information
* Device: iPhone X iOS 13.3.1
* Build version: Firefox 29.1 (2966)

### Notes
Sentry ID: **`c3b318c49d7acb0a02aebae7505ccafbdb095ee9`**

► Video
![img-0237-Q2gtFFf8-K7Mj](https://user-images.githubusercontent.com/51314259/97430331-6a1f8d80-1921-11eb-8479-509b013ab234.gif)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2609)

**Comment by athomasmoz** [comment]
Previously decided that the solution to this is to not allow the paste in search bar action while re-arranging tabs. Other actions are not allowed

**Comment by athomasmoz** [comment]
Let's look at frequency of this crash in sentry to decide on priority. @boek
