### ISSUE TITLE
[Bug] Save login prompt isn't displayed for a couple of web sites

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/firefox-ios#7583]
## Steps to reproduce
1. Navigate to gmail.com and log in with a valid account
2. Navigate to instagram.com and log in with a valid account
3. Navigate to twitter.com and log in with a valid account
4. Navigate to facebook.com.com and log in with a valid account

### Expected behavior
After successfully logging in, the don't save/save login prompt should be displayed

### Actual behavior
The don't save/save login prompt isn't displayed after logging in to the above mentioned websites

### Device & build information
* Device: iPhone X iOS 13.3.1
* Build version: Firefox 29.1 (2966)

### Notes
✔️ Got displayed on the following websites:
• yahoo.com 
• goo.gl/vi7z6

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2610)

**Comment by data-sync-user** [comment]
➤ Ashley Thomas commented:

Timebox investigation to 1

**Comment by data-sync-user** [comment]
➤ Daniela Arcese commented:

Investigation so far:

The save login prompt is shown in LoginsHelper.userContentController. But this is not getting called in the broken sites because the WKScriptMessage is not being received from the site.

scriptMessageHandlerName expects "loginsManagerMessageHandler"

**Comment by data-sync-user** [comment]
➤ Jeremy Evans commented:

Review if issue exists on Brave
[~jeevans@mozilla.com]  to reach out to WebCompat team for guidance

**Comment by data-sync-user** [comment]
➤ Nishant Bhasin commented:

I checked Brave browser and after logging into gmail they also didn't display the dialog to don't save username / password.

**Comment by lmarceau** [comment]
Since only `data-sync-user` has commented on the issue after the `Stalebot` GitHub action (which triggered the removal of the `stale` label) I’ll close this issue for now. Please let us know if you think this issue needs to be reopened, we'll gladly do so. Thank you!
