### ISSUE TITLE
FXIOS-1147 ⁃ [Bug] YouTube doesn't switch back from desktop site

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/firefox-ios#7586]
## Steps to reproduce
1 Load youtube.com
2 Switch Desktop site on.
3. Switch Desktop site off.

### Expected behavior
The mobile site is displayed.

### Actual behavior
The desktop site still displayed.

### Device & build information
* Device: iPhone X iOS 13.3.1
* Build version: Firefox 29.1 (2966)

### Notes
Similar issue got recently fixed on Fenix [#3903](https://github.com/mozilla-mobile/fenix/issues/3903)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1147)

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verified fix on v33.0 (4031).
