### ISSUE TITLE
[Bug]Sync settings are updated only after force close + resume

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/firefox-ios#7592]
## Prerequisites
The user should be signed in to sync on:
• Firefox for Desktop
• Firefox for Android

## Steps to reproduce
1. On Firefox for Desktop disable the "Bookmarks" option
2. Sync the devices
3. Check the sync settings on Firefox for iOS
4. Firefox for Android disable the "History" option
5. Sync  the devices
6. Check the sync settings on Firefox for iOS

### Expected behavior
Steps 3 & 6 - The Sync settings are properly updated

### Actual behavior
Steps 3 & 6 - The Sync settings aren't updated

### Device & build information
* Device: iPhone X iOS 13.3.1
* Build version: Firefox 29.1 (3022)

### Notes
✔️ The sync settings on both Firefox for Android & Firefox for Desktop are properly updated.
❓  On Firefox for iOS you need to force close and only afterwards the sync settings are updated.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2616)

**Comment by SimonBasca** [comment]
This issue is still reproducible after following the STR on v31.0 (3537) on iPhone Xr 14.4.

**Comment by lmarceau** [comment]
Since only `data-sync-user` has commented on the issue after the `Stalebot` GitHub action (which triggered the removal of the `stale` label) I’ll close this issue for now. Please let us know if you think this issue needs to be reopened, we'll gladly do so. Thank you!
