### ISSUE TITLE
FXIOS-1154 ⁃ [Chronological tabs][XCUI Tests] Missing IDs for elements

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/firefox-ios#7593]
In order to keep a good practice with our tests and so that they keep working to get screenshots, we would need IDs to the elements in the new Tab Tray.

This is how the elements look like now:
```
 NavigationBar, 0x600001917e20, {{0.0, 40.0}, {375.0, 56.0}}, identifier: 'Open Tabs'
                  StaticText, 0x600001917d40, {{145.0, 58.0}, {85.0, 20.5}}, label: 'Open Tabs'
                Other, 0x600001917c60, {{0.0, 40.0}, {375.0, 627.0}}
                  Other, 0x600001917b80, {{0.0, 40.0}, {375.0, 627.0}}
                    Other, 0x600001917aa0, {{0.0, 40.0}, {375.0, 627.0}}
                      Other, 0x6000019179c0, {{0.0, 96.0}, {375.0, 32.0}}
                        SegmentedControl, 0x6000019178e0, {{20.0, 96.0}, {335.0, 32.0}}
                          Button, 0x600001917800, {{20.0, 96.0}, {111.0, 32.0}}, label: '1', Selected
                          Button, 0x600001917720, {{132.0, 96.0}, {111.0, 32.0}}, label: 'smallPrivateMask'
                          Button, 0x600001917640, {{244.0, 96.0}, {111.0, 32.0}}, label: 'panelIconSyncedTabs'
                      Table, 0x600001917560, {{0.0, 128.0}, {375.0, 495.0}}
                        Other, 0x600001916300, {{0.0, 128.0}, {375.0, 40.5}}, identifier: 'TODAY — OCT 29, 2020'
                          StaticText, 0x600001916680, {{15.0, 148.0}, {345.0, 14.5}}, label: 'TODAY — OCT 29, 2020'
                        Cell, 0x600001938000, {{0.0, 168.5}, {375.0, 112.5}}
                          Other, 0x6000019380e0, {{0.0, 280.5}, {375.0, 0.5}}
                          Image, 0x6000019381c0, {{20.0, 174.5}, {100.0, 100.5}}
                          StaticText, 0x6000019382a0, {{140.0, 186.5}, {179.0, 44.0}}, label: 'Home'
                          StaticText, 0x600001938380, {{140.0, 230.5}, {195.0, 14.5}}, label: ' '
                          Button, 0x600001938460, {{335.0, 213.0}, {24.0, 24.0}}, label: 'tab close'
                        Other, 0x600001938540, {{0.0, 281.0}, {375.0, 0.0}}
                        Other, 0x600001938620, {{0.0, 281.0}, {375.0, 0.0}}
                        Other, 0x600001938700, {{0.0, 281.0}, {375.0, 0.0}}
                      Toolbar, 0x6000019387e0, {{0.0, 623.0}, {375.0, 44.0}}, identifier: 'Toolbar', label: 'Toolbar'
                        Other, 0x6000019388c0, {{0.0, 623.0}, {375.0, 44.0}}
                          Other, 0x6000019389a0, {{0.0, 623.0}, {359.0, 44.0}}
                            Button, 0x600001938a80, {{0.0, 623.0}, {45.0, 44.0}}
                            Button, 0x600001938b60, {{258.5, 628.0}, {100.5, 34.0}}
                              StaticText, 0x600001938c40, {{258.5, 628.0}, {0.0, 0.0}}
                              StaticText, 0x600001938d20, {{258.5, 633.0}, {66.5, 24.0}}, label: 'New Tab'
```

I have tried to add ID for `New Tab '+' ` in [TabTrayButtonExtensions.swift](https://github.com/mozilla-mobile/firefox-ios/blob/76faae8c6c94e22c8fbc0de72e2d06f615738e2c/Client/Frontend/Browser/TabTrayButtonExtensions.swift#L35) file by adding:
`newTab.accessibilityIdentifier = "newTabButtonTabTray" `

And similarly for the Private Mode, Close button and so on but that does not seem to work. I used to add the IDs this way before but there may be some changes I'm not aware of :( 

@dnarcese could you please point us to the correct place/way to do this? 
Thanks!

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1154)

**Comment by isabelrios** [comment]
Oh Just found out how to add it for the Close Tab button (the trash icon). Adding `button.accessibilityIdentifier = "closeTabsTabTray"` after this [line](https://github.com/mozilla-mobile/firefox-ios/blob/chronological-tabs/Client/Frontend/Browser/Tabs/TabTableViewCell.swift#L14), will work.

I will keep looking to similarly add the other missing IDs: 
- New Tab button 
- Private Mode Button 
- Number of tabs button
- Sync tabs button
- For each tab, the corresponding close button

**Comment by isabelrios** [comment]
> Oh Just found out how to add it for the Close Tab button (the trash icon). Adding `button.accessibilityIdentifier = "closeTabsTabTray"` after this [line](https://github.com/mozilla-mobile/firefox-ios/blob/chronological-tabs/Client/Frontend/Browser/Tabs/TabTableViewCell.swift#L14), will work.

This is wrong, that adds the ID to the last bullet above: For each tab, the corresponding close button.

To keep the list updated:
I will keep looking to similarly add the other missing IDs:

- 
-     New Tab button
-     Private Mode Button
-     Number of tabs button
-     Sync tabs button
-     Close Tabs button

**Comment by isabelrios** [comment]
So this is the place to add the IDs for `New Tab +` and `Close Tabs `(trash icon) buttons.
https://github.com/mozilla-mobile/firefox-ios/blob/chronological-tabs/Client/Frontend/Browser/Tabs/TabTrayV2ViewController.swift#L56
On L57: `addTabButton.accessibilityIdentifier = "newTabTabTray"`
And on L61: `closeAllTabsButton.accessibilityIdentifier = "closeAllTabsTabTray"`

**Comment by dnarcese** [comment]
-  New Tab button
https://github.com/mozilla-mobile/firefox-ios/blob/chronological-tabs/Client/Frontend/Browser/Tabs/TabTrayV2ViewController.swift#L56

Navigation Menu: https://github.com/mozilla-mobile/firefox-ios/blob/chronological-tabs/Client/Frontend/Browser/Tabs/TabTrayV2ViewController.swift#L48 
-   Private Mode Button
-  Number of tabs button
-   Sync tabs button
These buttons are part of a UISegmentedControl. Not sure how to add accessibility ids to those.

-  Close All Tabs button
https://github.com/mozilla-mobile/firefox-ios/blob/chronological-tabs/Client/Frontend/Browser/Tabs/TabTrayV2ViewController.swift#L58

- Close button on each tab
https://github.com/mozilla-mobile/firefox-ios/blob/chronological-tabs/Client/Frontend/Browser/Tabs/TabTableViewCell.swift#L11

**Comment by isabelrios** [comment]
Thanks Daniela, yeah those three I'm not sure either. I will try to add an ID for the UISegmentControl but if that's not possible, there is another option. Since there is an ID for the navigation bar (Open Tabs) I can select those three buttons by their position with `element(boundBy: x)` and that will work for the screenshots tests too.

**Comment by isabelrios** [comment]
Closing, IDs added in PR #7599
