### ISSUE TITLE
Intermittent battery life issues, possibly related to sync

### ISSUE THREAD

**Issue by Apocalypsing** [mozilla-mobile/firefox-ios#7598]
## Issue description
I recently set up Firefox sync on a new phone. Since doing this I have noticed high battery usage from time to time when using Firefox, it seems like it's using up 100% CPU time as my phone gets very warm in the process. If I switch to another app, battery usage returns to normal levels and my phone soon cools down. But if I switch back to Firefox, it can cause issues again. Seems like it's related to sync, as this wasn't an issue for me prior to setting up sync again, and when I do force a manual resync in the menu, it seems to coincide with this higher battery usage.

### Steps to reproduce
* Set up sync on your device
* Browse normally and observe
* Force a manual resync via menu and observe

### Expected behaviour
Battery life shouldn't be impacted much when using sync if at all, certainly not to the extent I'm seeing here.

### Device & build information
* Device: iPhone 12 (256 GB)
* iOS version: 14.1
* Build version: Firefox Daylight 29.0 (2860)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2619)

**Comment by csuciu** [comment]
I tried to reproduce this issue on an iPhone 12 (iOS 14.4) running our latest release (32.0) but wasn't able to. 

@Apocalypsing Are you still experiencing this issue on the latest releases?

**Comment by lmarceau** [comment]
Since only `data-sync-user` has commented on the issue after the `Stalebot` GitHub action (which triggered the removal of the `stale` label) I’ll close this issue for now. Please let us know if you think this issue needs to be reopened, we'll gladly do so. Thank you!
