### ISSUE TITLE
FXIOS-1163 ⁃ Search information counts

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#7602]
**Vision**

As a PM, I want visibility into how often different search activities are taking place within our app to monitor for issues and measure results of improvements to the search workflows

**Acceptance Criteria**

* Counts in Glean for follow-on and organic search in Google
* Data is inline with Fenix for simpler reporting

**Notes**

* Corresponding [Fenix tickets and PRs](https://github.com/mozilla-mobile/fenix/issues/6448)
* [Search definitions](https://docs.telemetry.mozilla.org/datasets/search.html)
* Travis or Megan can help answer questions and ensure tracking is inline with Fenix for simpler reporting

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1163)

**Comment by data-sync-user** [comment]
➤ Nishant Bhasin commented:

Search engine codes: https://docs.google.com/spreadsheets/d/1HMm9UXjfJv-uHhGU1pJlbP4ILkdpSD9w_Fd-3yOd8oY/edit#gid=1691200007

**Comment by csuciu** [comment]
Verifying as fixed on v30.0 (3279)/iPhone 11 Pro (iOS 14.2)
