### ISSUE TITLE
FXIOS-1164 ⁃ Land Strings for v30

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#7603]
**Vision**

Strings for the v30 release have been sent for localization so that we can support users in all our supported locales

Soft code freeze 12/3; hard code freeze 12/7

**Acceptance Criteria**

* Strings for all v30 tickets have landed
  * https://jira.mozilla.com/browse/FXIOS-941
  * https://jira.mozilla.com/browse/FXIOS-587
  * https://jira.mozilla.com/browse/FXIOS-1024
  * https://jira.mozilla.com/browse/FXIOS-654
  * https://jira.mozilla.com/browse/FXIOS-392

* Comment on each ticket confirming strings have landed
* Localization request has been sent for the strings

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1164)

**Comment by brampitoyo** [comment]
All the strings look good and are ready to send to localisation:

* [FXIOS-941](https://jira.mozilla.com/browse/FXIOS-941): icon only, no string required
* [FXIOS-587](https://jira.mozilla.com/browse/FXIOS-587): icon only (uses icon from search “NASCAR” bar above the keyboard, no string required
* [FXIOS-1024](https://jira.mozilla.com/browse/FXIOS-1024): string – “Edit”
    * Hopefully we’d be able to get this from other “Edit” strings used within the app.
* [FXIOS-654](https://jira.mozilla.com/browse/FXIOS-654): string – “No account? Create one to sync Firefox between devices.”
    * How to access: Main Application Menu → Sign In to Sync
* [FXIOS-392](https://jira.mozilla.com/browse/FXIOS-392): string – “Sign In to Firefox”
    * How to access: Page Actions Menu → Send to Device

**Comment by data-sync-user** [comment]
➤ Ashley Thomas commented:

[~bpitoyo@mozilla.com] Thank you for consolidating those strings into a list for us! 

[~darcese@mozilla.com] Heads up that today is our standard deadline to submit strings for V31. You may want to give Delphine a quick ping if you think it will be later
