### ISSUE TITLE
FXIOS-1166 ⁃ [Bug] Confirmation snackbars are missing from address bar context menu action: "Copy Address"

### ISSUE THREAD

**Issue by brampitoyo** [mozilla-mobile/firefox-ios#7605]
## Steps to reproduce

1. “Force touch” or long-press the address bar while a website is currently open
2. Select "Copy Address"

### Expected behavior

If you select "Copy Address" from the Page Actions Menu (⋯), it will show a confirmation snackbar. The same selection, when done from the address bar, should also show a confirmation snackbar.

### Actual behavior

Nothing is displayed

### Device & build information
* Device: all

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1166)

**Comment by SimonBasca** [comment]
Verified fix on 22c479431bdc.
