### ISSUE TITLE
FXIOS-1167 ⁃ Sign in to sync page shows an error 'could not load page'

### ISSUE THREAD

**Issue by ThePolarCat** [mozilla-mobile/firefox-ios#7607]
## Steps to reproduce
Tap on Sign in to sync

### Expected behavior
Show sign in form

### Actual behavior
Displays an error "could not load page"

### Device & build information
* Device: iPhone 5 iOS 10.4
* Build version: 14.0 (12646)

### Notes
Started happening after restoring my phone, before that I was able to sync successfully.

I can't install the latest of Firefox on my device because iOS 10.4 is the latest version I can use on my device.

I just want to sign in to sync!

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1167)

**Comment by baileyr146** [comment]
I would love for you to fix this problem for me . Tell my how much you want to fix the problem

**Comment by baileyr146** [comment]
- -

**Comment by abrasha70** [comment]
please fix this problem,
this feature is important

**Comment by lolrepeatlol** [comment]
I can't reproduce on 29.1 on iOS 14

**Comment by ThePolarCat** [comment]
Yes only on older builds, but still, it should be fixed

**Comment by abrasha70** [comment]
> I can't reproduce on 29.1 on iOS 14, I guess this is only an issue on old iOS versions with old Firefox builds?

@lolrepeatlol , the problem is this:
for iPhone 5:
- the latest iOS available is iOS 10.3.4
- the latest Firefox available for it is 14.0 (12646)

for these combination, when I go to "Sign in to Sync", I get:
error page "could not load page"

**Comment by isabelrios** [comment]
@SimonBasca could you please take a look at this issue?  if you have old devices as reported in the issue..thank you in advance!

**Comment by SimonBasca** [comment]
Unfortunately we don't have devices with iOS older than 11.4 which is the latest version we support. Even if we can get a fix the user should be able to update to an older Firefox version to get the fix and I think that's not be possible in this case.

**Comment by ThePolarCat** [comment]
I don't think the problem is baked in the build, my iPad with the software is logged in.

Accounts page also stops at the pie loader 
https://accounts.firefox.com/

**Comment by SimonBasca** [comment]
@ThePolarCat you are probably right. We are currently discussing this issue and will get back with a resolution.

**Comment by ThePolarCat** [comment]
Any plans to fix this yet?

**Comment by jevans-mozilla** [comment]
Unfortunately in 2017 the App Store no longer accepted submissions targeting 32-bit platforms.  We no longer have the ability to submit patches that would address this issue.
