### ISSUE TITLE
FXIOS-1171 ⁃ [Crhonological tabs] After visiting a site it is not shown in Home Top Sites list unless doing some extra steps

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/firefox-ios#7611]
## Steps to reproduce
Go to www.mozilla.org, wait until the page is completely loaded
Open a new tab showing the home view with top sites

### Expected behavior
Mozilla fav icon should be shown along with the default top sites

### Actual behavior
Mozilla site does not appear in Tope sites directly after going to the site. But if you:
- From home view, open tab tray and click on mozilla.org site to open it again, then open a new home tab -> Mozilla site appears in the top site list now.  

### Device & build information
* Device: iPhone 8 iOS14
* Build version: crhon tabs branch

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2623)

**Comment by dnarcese** [comment]
Is this still reproducible on v31?

**Comment by SimonBasca** [comment]
This issue is still reproducible on v 31.0 (3537) on both chronological tabs and normal tabs tray. 
[Uploading Video.mp4.zip…]()
