### ISSUE TITLE
Opened PDF will disappear if the page is not in foreground

### ISSUE THREAD

**Issue by vmoutoussamy** [mozilla-mobile/firefox-ios#7612]
## Steps to reproduce
Try to generate a French Lockdown certificate from https://media.interieur.gouv.fr/deplacement-covid-19/,
then you get a "blob" pdf. Switch app or tab or lock your phone, then get back to the pdf page. 
The pdf page will disappear
### Expected behavior
With Safari the URL will not be "blob" and the PDF will stay whatever you do.

### Actual behavior
The pdf page will disappear 

### Device & build information
* Device: Iphone7 ios 14.1
* Build version: Firefox Daylight 29.1 (3022°
### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2624)

**Comment by vmoutoussamy** [comment]
This is kind of critical since in France, we are in a lockdown situation where you have to show your certificate in "pdf" if there is any control. At the moment, with Firefox you can just loose your certificate... and you won't be able to find it back. Regenerating a new certificate is not an option.

**Comment by SimonBasca** [comment]
@vmoutoussamy thanks for the feedback. I tested this issue and found that:

## For Firefox.
- Going to https://media.interieur.gouv.fr/deplacement-covid-19/ and completing the form will display a PDF with a blob URL like in the screenshot
![Skype_Picture_2020_11_05T10_52_33_353Z](https://user-images.githubusercontent.com/32130829/98232073-dfb0dc80-1f65-11eb-941b-7d09bfd957c4.jpeg)

## For Safari.
- Going to https://media.interieur.gouv.fr/deplacement-covid-19/ and completing the form will display a PDF with the URL like in the screenshot
![Skype_Picture_2020_11_05T10_52_45_458Z](https://user-images.githubusercontent.com/32130829/98232125-f22b1600-1f65-11eb-9b7f-191e52c480e6.jpeg)

In my case after leaving Firefox and Safari in background and restoring the PDF will be lost. After some time iOS will close the app and cause the session to be lost. 

## Screenshot from Safari after restoring the PDF
![Skype_Picture_2020_11_05T10_58_47_180Z](https://user-images.githubusercontent.com/32130829/98232703-aaf15500-1f66-11eb-84e9-92087b6949f1.jpeg)

**Comment by SimonBasca** [comment]
I'm not sure if there is anything actionable on the Firefox iOS side, but we will discuss this in the next triage meeting.

**Comment by vmoutoussamy** [comment]
Please Note: 
- Safari and Firefox will lose the PDF at some point, but Safari seems to "hold it longer" than Firefox. It's based on my feeling but maybe we could come up with a precise test suite so we could compare? help would be appreciated here. 
- At least with Safari it's super easy to save the PDF locally in the smartphone, with the "share button". On Firefox it's impossible.

**Comment by SimonBasca** [comment]
Note from QA: Maybe we could priorities #5389 and do a better job at saving PDF files.

**Comment by tylermneher** [comment]
PDF is globally utilized and should not be put on back burner because of an eventual migration away from the standard.

**Comment by lmarceau** [comment]
Since only `data-sync-user` has commented on the issue after the `Stalebot` GitHub action (which triggered the removal of the `stale` label) I’ll close this issue for now. Please let us know if you think this issue needs to be reopened, we'll gladly do so. Thank you!
