### ISSUE TITLE
FXIOS-1175 ⁃ - - please fix this problem

### ISSUE THREAD

**Issue by baileyr146** [mozilla-mobile/firefox-ios#7615]
- - 

__Originally posted by @baileyr146 in https://github.com/mozilla-mobile/firefox-ios/issues/7607#issuecomment-720689553__

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1175)

**Comment by SimonBasca** [comment]
We are currently discussing and trying to fix this issue.
