### ISSUE TITLE
FXIOS-1177 ⁃ Experiment Setup: Continue typing off search suggestion

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#7617]
**Vision**

As a user performing a search, I want to send the search suggestion to the search field but allow you to keep typing additional text before performing the search, so I can add something more specific to the suggestion

**Acceptance Criteria**

* Experiment set up for #7365 [experiment plan with mocks](https://docs.google.com/document/d/16cXwOwi4H_6viiQJYK8X512Lj8CAj6bE8rI3MMMAd3c/edit#)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1177)

**Comment by brampitoyo** [comment]
I’ve added dark theme variant to our experiment plan.

**Comment by data-sync-user** [comment]
➤ Ashley Thomas commented:

Closing as won't do.

**Comment by arengoh** [comment]
Sync/Synchronizers
