### ISSUE TITLE
Double Space in UserAgent HTTP Header

### ISSUE THREAD

**Issue by sebfeslh** [mozilla-mobile/firefox-ios#7619]
## Steps to reproduce
Do HTTP requests from UserAgent to a webserver the HTTP Header UserAgent contains a double space, which is not compliant to the RFC/standards.
### Expected behavior
UserAgent should only containe single spaces
### Actual behavior
Mozilla%2f5.0%20(iPhone%3b%20CPU%20OS%2014_1%20like%20Mac%20OS%20X)%20AppleWebKit%2f605.1.15%20(KHTML,%20like%20Gecko)%20FxiOS%2f29.0**%20%20**Mobile%2f15E148%20Safari%2f605.1.15

url encoded space => %20 highlight bold in the above http request
FxiOS%2f29.0**%20%20**Mobile

### Device & build information
* Device: ?
* Build version: ?
### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2626)

**Comment by lmarceau** [comment]
Since only `data-sync-user` has commented on the issue after the `Stalebot` GitHub action (which triggered the removal of the `stale` label) I’ll close this issue for now. Please let us know if you think this issue needs to be reopened, we'll gladly do so. Thank you!
