### ISSUE TITLE
FXIOS-1184 ⁃ [Chron Tabs] Create custom bottom sheet menu

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#7624]
Add a swipe-able bottom sheet that user can dismiss by swiping down and be able show more item from Tab Tray V2 tabs.

!image-2020-11-05-15-43-39-323.png|width=285,height=383!

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1184)

**Comment by csuciu** [comment]
Verifying as fixed on v30.0 (3242)
