### ISSUE TITLE
FXIOS-1185 ⁃ [Chon Tabs] - Add ability to switch between V1 and V2 tab tray

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#7625]
For QA testing and also basic switching of Tab Tray between V1 and V2 version we should add a toggle switch to our debug menu.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1185)

**Comment by csuciu** [comment]
Verifying as fixed on v30.0 (3242)
