### ISSUE TITLE
Probes for LTV Estimation

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#7626]
**Vision**

As a DS at Mozilla, I want client_ltv added so that I can estimate relative user value based on past and expected search and ad click behavior. This behavior is revenue-generating for Firefox.

**Acceptance Criteria**

* [Client LTV](https://docs.telemetry.mozilla.org/datasets/search/client_ltv/reference.html#ltv) is being sent to Glean
* This addition has been reviewed by data stewards to confirm its implemented in a way that maintains user privacy
* This addition has been reviewed by data science to ensure it matches the definition on Fenix

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2629)

**Comment by data-sync-user** [comment]
➤ Jeremy Evans commented:

[~athomas@mozilla.com] Is the LTV something that needs to be generated, or is the value already captured in the app

**Comment by data-sync-user** [comment]
➤ Ashley Thomas commented:

[~mgorlick@mozilla.com] or [~mdroettboom@mozilla.com] do you know the answer to the above question?

**Comment by data-sync-user** [comment]
➤ Marissa Gorlick commented:

LTV will be generated post-hoc.  Thanks!

**Comment by data-sync-user** [comment]
➤ Daniela Arcese commented:

[~mgorlick@mozilla.com] If I understand correctly, the only probes needed from the iOS side are the search information counts and ad click counts (captured in other tickets); and LTV will be generated by DS using those values. In that case, this ticket is not needed as there is no other information needed from us. Can you confirm?

**Comment by data-sync-user** [comment]
➤ Marissa Gorlick commented:

That is my understanding.  [~mmccorquodale@mozilla.com] and [~xluo@mozilla.com] , can you please confirm they are collecting everything they need for LTV parity? Thanks!

**Comment by lmarceau** [comment]
Since only `data-sync-user` has commented on the issue after the `Stalebot` GitHub action (which triggered the removal of the `stale` label) I’ll close this issue for now. Please let us know if you think this issue needs to be reopened, we'll gladly do so. Thank you!
