### ISSUE TITLE
FXIOS-1197 ⁃ Widgetkit Crash in v29.1

### ISSUE THREAD

**Issue by nbhasin2** [mozilla-mobile/firefox-ios#7637]
No particular steps to reproduce but this is our top *silent crash* in widgetkit iOS v29.1

<img width="936" alt="image" src="https://user-images.githubusercontent.com/8919439/98725929-c6dc6880-2363-11eb-94c7-06bf1348cfb6.png">

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1197)

**Comment by data-sync-user** [comment]
➤ Daniela Arcese commented:

This doesn't affect the actual use of the widget for the user - only the favicon will be empty or show the first letter of the site.

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

We tested the widget functionalities and everything seems OK. Moving to QA Verified.
