### ISSUE TITLE
FXIOS-1200 ⁃ [Chronological Tabs] Landscape mode

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#7640]
Chronological Tabs was developed mainly for portrait mode and we did not alter the design to look perfect in landscape mode. Attached is an image of what it currently looks like.
Important to note is that the 'More' menu when clicking on a tab is not shown in landscape mode (and cannot be dragged up to be shown).

Short-term solution can be to lock users from being able to rotate their device while in the tab tray with long-term solution being creating new designs and altering the layout to fit in landscape mode.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1200)

**Comment by data-sync-user** [comment]
➤ Daniela Arcese commented:

cc [~athomas@mozilla.com] [~bpitoyo@mozilla.com] for opinions.

**Comment by data-sync-user** [comment]
➤ Ashley Thomas commented:

[~darcese@mozilla.com] Thanks for raising this. When deciding on a solution, I think we need to consider:

  * What is simple, fast solution to get the A/B test out the door

  * What can we do that wouldn't bias the test. For example, if users can only view the tab tray in portrait mode, that could hurt retention, which would affect the test results

**Comment by dnarcese** [comment]
Fixed in #7666

**Comment by csuciu** [comment]
Verifying as fixed on v30.0 (3242)
