### ISSUE TITLE
FXIOS-1203 ⁃ Viewing a PDF, then Share Sheet

### ISSUE THREAD

**Issue by brandoncote** [mozilla-mobile/firefox-ios#7643]
When you open a pdf link in firefox and it loads it inline, and then you use the share sheet, it sends a useless localized link. Compare with how safari does it; it sends the actual link where the PDF appeared on the web.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1203)

**Comment by SimonBasca** [comment]
Closing as duplicate of #7933
