### ISSUE TITLE
FXIOS-1207 ⁃ [Chron Tabs] Support landscape mode

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#7647]
Current solution doesn't support landscape mode and In order to accommodate landscape mode below is proposed solution

* Bottom sheet goes into full view mode
* Hide headerview
* Shrink cell size
* Make tableview scrollable

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1207)

**Comment by dnarcese** [comment]
Dupe #7640
