### ISSUE TITLE
FXIOS-1208 ⁃ Updated app now it won’t open or work don’t know how to fix I tried it all

### ISSUE THREAD

**Issue by bassnado** [mozilla-mobile/firefox-ios#7648]
### Device & build information
* Device: ?
* Build version: ?
### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1208)

**Comment by SimonBasca** [comment]
Hello, thanks for the feedback. Could you please let me know from what version did you update?

**Comment by bassnado** [comment]
iPhone XR and the version from 3 weeks ago I think just the newest iOS update

**Comment by bassnado** [comment]
Firefox 29.1 iOS 14

**Comment by bassnado** [comment]
Firefox 29.1 iOS 14

**Comment by bassnado** [comment]
Oh sorry I meant 29 to 29.1

**Comment by bassnado** [comment]
I had Firefox 29 then updated to 29.1
iOS 14.2

**Comment by SimonBasca** [comment]
Thanks for the feedback. Unfortunately I am currently unable to reproduce this issue on Firefox 29.1 (3022) and on latest beta 29.2 (3120). 

Do you have a Firefox Account set up on your device?

**Comment by bassnado** [comment]
No
Don’t have account set up

**Comment by bassnado** [comment]
Do not have account tied to browser when does next update come out

**Comment by dnarcese** [comment]
@bassnado Hello, is it working for you now?

**Comment by dnarcese** [comment]
Closing for now, will re-open if it is still an issue.
