### ISSUE TITLE
FXIOS-1211 ⁃ [Chron tabs] iPad crashes when clicking on Remove All tabs button (trash icon)

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/firefox-ios#7651]
## Steps to reproduce
Open several tabs
Go to Tab Try
Click on Trash icon
### Expected behavior
A dialog to confirm removing all tabs is shown

### Actual behavior
Upon clicking on that button the app crashes

### Device & build information
* Device: iPad Air (3rd gen)
* Build version: chron tabs latest commit be4670e05c83ea01df5bb9e1ddfb72dec52975a9

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1211)

**Comment by dnarcese** [comment]
Closing for now as chron tabs is not yet on iPad.
