### ISSUE TITLE
FXIOS-1210 ⁃ [Chron tabs] Share menu is not shown correctly on iPad

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/firefox-ios#7652]
## Steps to reproduce
Open a website
Go to Tab Tray
Swipe left on that site to bring the different options
Tap on Share

### Expected behavior
The Share menu is shown correctly

### Actual behavior
The Share menu is shown at the very bottom, only a small part is visible

### Device & build information
* Device: iPad Air (3rd gen)
* Build version: chron tabs latest commit be4670e
### Notes
Attachments: 
![Captura de pantalla 2020-11-16 a las 11 18 06](https://user-images.githubusercontent.com/1897507/99241188-ce858c80-27fd-11eb-996a-7d1dd475da4d.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1210)

**Comment by dnarcese** [comment]
Closing for now as chron tabs is not yet on iPad.
