### ISSUE TITLE
FXIOS-1221 ⁃ Firefox crashes after restarting the iPhone

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#7661]
## Steps to reproduce
1. Clean install Firefox v29.2 (3106)
2. Long press lock button and volume up
3. Turn off iPhone
4. Turn on iPhone and open Firefox v29.2 (3106)
### Actual behavior
- Crash dialog is displayed.
### Device & build information
* Device: iPhone Xr (14.1)
* Build version: 29.2 (3106)
### Notes
- No crash log is generated locally.
- Sentry ID : 76a54fac4583c043a484f71fb8c3420cf9dbf8c9
Attachments:

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1221)

**Comment by athomasmoz** [comment]
@SimonBasca is this still reproducible on 3120?

**Comment by data-sync-user** [comment]
➤ Jeremy Evans commented:

We have not been able to reproduce this with the devices we have.  Can it be reproduced easily on any other device/iOS version combinations?

**Comment by SimonBasca** [comment]
Marking as duplicate of #8023
