### ISSUE TITLE
FXIOS-1222 ⁃ [Chronological tabs] Turn off chronological tabs on iPad

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#7662]
Chronological tabs experiment should only be for iPhone right now, but it is accessible on iPad as well.

**Acceptance Criteria**

* the tab tray on iPad should still be the old one and not chronological

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1222)

**Comment by csuciu** [comment]
Verifying as fixed on v30.0 (3242)
