### ISSUE TITLE
Lag on address field focus

### ISSUE THREAD

**Issue by oyzmo** [mozilla-mobile/firefox-ios#7664]
## Steps to reproduce
Browse to a big page, eg www.cnn.com.
Scroll downwards.
Scroll back up, in order to get the address field back into view.
Click on the address field.

### Expected behavior
Address field with text selected without delay.

### Actual behavior
Address field selected, but with a varying delay (from barely noticeable to a second+).

### Device & build information
* Device: Air 4 (ios 14.2)
* Build version: 29.1 3022

### Notes
Attachments: 
Same behaviour with and without dark mode.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2641)

**Comment by lmarceau** [comment]
Since only `data-sync-user` has commented on the issue after the `Stalebot` GitHub action (which triggered the removal of the `stale` label) I’ll close this issue for now. Please let us know if you think this issue needs to be reopened, we'll gladly do so. Thank you!
