### ISSUE TITLE
FXIOS-1232 ⁃ iOS - when Firefox is default browser, FB links won't open from Messenger app..

### ISSUE THREAD

**Issue by v1sionmaster** [mozilla-mobile/firefox-ios#7671]
## Steps to reproduce
Open Messenger App - click on any shared link from Facebook.

### Expected behavior
Open Facebook App at link.

### Actual behavior
Nothing happens

### Device & build information
* Device: ? iPhone 8
* Build version: ? Firefox Daylight 29.1 (3022)
### Notes
When switching back to Safari as default browser, the links open in FB App as expected.
This does not appear to be an issue with ordinary web links which open in Firefox App without any problem
Attachments:

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1232)

**Comment by SimonBasca** [comment]
This is similar to #7340.

**Comment by v1sionmaster** [comment]
Thanks Simon J

I had seen that post but I don’t get an error message of any sort and noted the difference between links that do and don’t work when FF is default. 

I thought it was worth starting as a new issue J 

It’s impossible to test all scenario’s and I very much appreciate all you are doing to make FF a smoother experience for us!

I’ve just started using FF Nightly on Windows Desktop to resolve PDF opening issues J Might that version appear for iOS? 

Thanks again – 

Tim

**Comment by dnarcese** [comment]
@v1sionmaster this is working for me now. Has it been fixed for you?

**Comment by v1sionmaster** [comment]
Thank you! This is now working as it should :-) Very grateful for this :-)

**Comment by v1sionmaster** [comment]
Fixed
