### ISSUE TITLE
FXIOS-1234 ⁃ [Chron tabs] Empty tabs showing up in chron tabs after leaving them opened for few days

### ISSUE THREAD

**Issue by nbhasin2** [mozilla-mobile/firefox-ios#7672]
<img width="584" alt="image" src="https://user-images.githubusercontent.com/8919439/99722292-76a98880-2a7e-11eb-840c-93cf368867a4.png">

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1234)

**Comment by csuciu** [comment]
I can't reproduce this issue on v30.0 Beta builds.
