### ISSUE TITLE
FXIOS-1233 ⁃ [Chron tabs] Empty screenshot shows up in chron tabs for last week

### ISSUE THREAD

**Issue by nbhasin2** [mozilla-mobile/firefox-ios#7673]
<img width="584" alt="image" src="https://user-images.githubusercontent.com/8919439/99722562-d30ca800-2a7e-11eb-8d93-ace8ca591f7e.png">

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1233)

**Comment by isabelrios** [comment]
This is happening on beta 30.x (3242) build.
When enabling chron tabs, the tabs that were open before updating the app are shown this way. 
cc @nbhasin2 @dnarcese

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on **`Firefox Beta v30 (3274)`** using an iPhone X iOS 13.3.1

► Screenshot
![rsz_screenshot_2020-12-14_at_154327](https://user-images.githubusercontent.com/51314259/101637649-b50ae580-3a35-11eb-8aa5-068cbd81ada5.png)
