### ISSUE TITLE
FXIOS-1238 ⁃ Clearing Cookies & Cache on iOS

### ISSUE THREAD

**Issue by abanda96** [mozilla-mobile/firefox-ios#7677]
## Steps to reproduce
I cleared cache on my iPhone that's running iOS 14.2 and synced with my laptop Firefox.

### Expected behavior
I was expecting the cookies and caches to clear
### Actual behavior
Neither cookies nor cache were actually cleared 

### Device & build information
iPhone iOS 14.2
* Device: iPhone 62
* Build version: ?
### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2644)

**Comment by athomasmoz** [comment]
@SimonBasca can you see if this one is reproducible? I wasn't able to on iPhone 11 iOS 14.2

**Comment by abanda96** [comment]
Can it be an iPhone 6s specific bug? It does run iOS 14.2, like the iPhone 11 you're trying to recreate the issue.

**Comment by koobs** [comment]
@abanda96 I may have the same, related or similar issue. What are the steps (actions, buttons, etc) being taken on your device to reproduce the issue as reported?
