### ISSUE TITLE
FXIOS-1240 ⁃ Can't open links in full browser from webview

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#7679]
**Steps to reproduce:**

1. Set Firefox as your default browser
1. Open facebook messenger (instagram, or another app)
1. Click on a weblink in messenger
1. Click the share arrow

**Expected Behaviour**

There is an option to open the link in Firefox. Note: When Safari is set as default browser, there's an option to open in Safari

!image-2020-11-26-10-16-06-863.png!

**Actual Behaviour**

There are only options to share or open in alternative browsers. Note: Chrome has this behaviour too. It seems you only have the option to open in the defualt browser when its Safari

!image-2020-11-26-10-15-15-843.png!

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2646)

**Comment by SimonBasca** [comment]
Probably the same issue as #7671 and #7340
