### ISSUE TITLE
FXIOS-1245 ⁃ The address bar won’t auto-appear/hide on scrolling with a trackpad

### ISSUE THREAD

**Issue by 3c1u** [mozilla-mobile/firefox-ios#7684]
## Steps to reproduce

1. Open FIrefox for iOS on iPad with a trackpad attached.
2. Scroll to top and down using a trackpad.

### Expected behavior

When the page reaches to the top, the address bar should appear, and scrolling down should hide the address bar, same as the scrolling with fingers.

### Actual behavior

The address bar sticks or remains hidden regardless of the scroll position.

### Device & build information
* Device: iPad Air (4th gen), iPadOS 14.2
* Build version: Firefox Daylight 29.2 (3120)
### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1245)

**Comment by dnarcese** [comment]
Dupe #7860
