### ISSUE TITLE
Update the Bing search engine brand icon

### ISSUE THREAD

**Issue by Standard8** [mozilla-mobile/firefox-ios#7698]
Bing has changed its brand icon, so this needs updating on iOS.

This is the bug where we changed it on desktop:

https://bugzilla.mozilla.org/show_bug.cgi?id=1669297

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2648)

**Comment by LuckyGold7** [comment]
I see, this is a easy one as we just need to change the picture. We will update this is the next update hopefully.

**Comment by LuckyGold7** [comment]
I would like to contribute to this.

**Comment by dnarcese** [comment]
@brampitoyo need the asset for this.

**Comment by brampitoyo** [comment]
@dnarcese The Bing icon is available in these formats:


152x152:
https://www.bing.com/apple-touch-icon-precomposed.png

32x32:
https://www.bing.com/sa/simg/favicon-2x.ico

16x16:
https://www.bing.com/favicon.ico

SVG (not framed in square like other logos – I can frame it if you like):
https://share.getcloudapp.com/YEuQQ6R2

**Comment by dnarcese** [comment]
@LuckyGold7 feel free to work on this ticket - you should have everything you need now. Let me know if you have questions.

**Comment by Standard8** [comment]
> 16x16:
> https://www.bing.com/favicon.ico

This 16x16 favicon.ico is currently the old Bing icon and should not be used.

For desktop we used the 32x32 one.

**Comment by data-sync-user** [comment]
➤ Tiffanie Shakespeare commented:

Michael Verdi verified the bing icon has been updated in ios. closing
