### ISSUE TITLE
FXIOS-1264 ⁃ [Chron tabs] Title overflow: long title

### ISSUE THREAD

**Issue by nbhasin2** [mozilla-mobile/firefox-ios#7703]
<img width="584" alt="image" src="https://user-images.githubusercontent.com/8919439/99722562-d30ca800-2a7e-11eb-8d93-ace8ca591f7e.png">

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1264)

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on  **`Firefox Beta v30 (3274)`** using an  iPhone X iOS 13.3.1

► Screenshot
![rsz_screenshot_2020-12-09_at_153612](https://user-images.githubusercontent.com/51314259/101636875-9ce69680-3a34-11eb-98d3-c287831c4070.png)
