### ISSUE TITLE
FXIOS-1272 ⁃ [Bug] Request desktop site doesn't seem to be working on some websites

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/firefox-ios#7713]
## Steps to reproduce
1. Open Wikipedia from the "Top Sites" section
2. You can either:
2.1 Long Tap the "Refresh" button and tap on "Request Desktop Site"
2.2 Tap the ... button and select "Request Desktop Site"

### Expected behavior
Tapping the "Request Desktop Site" button should display the Desktop version of the website

### Actual behavior
Doesn't seem to display the Desktop version of the website

### Device & build information
* Device: iPhone X iOS 13.3.1
* Build version: v30 (3274)

### Notes
❌ Doesn't seem to be working on the following websites:
wikipedia.org
theverge.com
cnet.com
cnn.com

✔️ Works properly on the following websites:
soundcloud.com
amazon.com

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1272)

**Comment by dnarcese** [comment]
@SimonBasca can you check if this also happens on Safari?

**Comment by SimonBasca** [comment]
This seems to be a site issue. The broken sites mentioned don't work in Chrome for iOS or Edge for iOS.
