### ISSUE TITLE
FXIOS-1275 ⁃ Settings - 'Open New Tab' button in Siri Shortcuts section is not responding

### ISSUE THREAD

**Issue by BigSamSampson** [mozilla-mobile/firefox-ios#7716]
## Steps to reproduce
1. Open firefox browser
2. Tap on settings gear
3. Tap on Siri Shortcuts
4. Tap on ''Open New Tab''
### Expected behavior
Page should open when tap on button
### Actual behavior
Open New Tab button is not responding
### Device & build information
* Device: Apple iPhone 6S - iOS 14.1
* Build version:  firefox daylight 29.2 (3120)

### Notes
Attachments: 

![image](https://user-images.githubusercontent.com/66958331/101635079-92c79680-3a3a-11eb-8449-9d75c0dcb0f7.png)
![image](https://user-images.githubusercontent.com/66958331/101635126-9d822b80-3a3a-11eb-9a59-aeb31682dd75.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1275)

**Comment by dnarcese** [comment]
@BigSamSampson when you click that button in the settings it should bring up a page for Siri Settings allowing you to create the new shortcut. Do you see that behaviour?

**Comment by dnarcese** [comment]
Closing for now, will re-open if it is still an issue.
