### ISSUE TITLE
FXIOS-1277 ⁃ [Bug][Chron Tabs] "L" favicon displayed when witching to PB Home open tab

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/firefox-ios#7718]
## Prerequisites
Have a clean profile or a fresh install

## Steps to reproduce
1. Open the Tabs Tray while in Normal Browsing mode
2. Tap the PB Open Tabs icon

### Expected behavior
The Home screen screenshot should be displayed

### Actual behavior
"L" favicon is displayed for the PB Home open tab

### Device & build information
* Device: iPhone X iOS 13.3.1
* Build version: v30 (3274)

### Notes
► Video
![IMG-0259](https://user-images.githubusercontent.com/51314259/101641351-5136eb80-3a3a-11eb-91d4-79e47c637791.gif)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2655)

**Comment by dnarcese** [comment]
Maybe we can create an asset specifically for the Home page. cc @brampitoyo

**Comment by brampitoyo** [comment]
@dnarcese In our current (not Chrono) tabs tray, thumbnails for Private Tabs are generated as you enter the tray:

![RPReplay_Final1611529012](https://user-images.githubusercontent.com/51007/105646428-c4ba8c80-5f04-11eb-8ccb-01ee5eadd769.gif)

The behaviour for Chrono tabs tray should be identical to the above.

The problem with generating a hard-coded thumbnail is that people’s default home page across locales may not look identical to the en-US one (where we will most likely capture a screenshot to be used as thumbnail).

I wonder if, on private tab, it would be possible to reuse the same thumbnail from people’s normal tab? We know for sure that there is no difference between the home page of normal vs. private tabs. If we reuse the thumbnail, we can ensure that it will always look accurate, regardless of people’s locale.
