### ISSUE TITLE
FXIOS-1281 ⁃ [Widgets] Font size too large on medium sized search widget

### ISSUE THREAD

**Issue by AmyYLee** [mozilla-mobile/firefox-ios#7722]
Hi, 

The font size looks to be 15px on device. This should be 13px. Please see mock for reference. 

![Med - Search](https://user-images.githubusercontent.com/5992746/101666644-77e62980-3a1c-11eb-8e19-2d3b655212c9.png)

Thanks!

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1281)

**Comment by PraneetNeuro** [comment]
#7763

**Comment by dnarcese** [comment]
Should this font size instead follow the system settings font size? It should dynamically change size instead of being fixed to one size. cc @brampitoyo

**Comment by brampitoyo** [comment]
@dnarcese Yes. The intention was for the font size not to be hardcoded at 13px, but to be set in a system-provided text style called `UIFontTextStyleFootnote`:

- https://developer.apple.com/documentation/uikit/uifonttextstyle
- https://developer.apple.com/design/human-interface-guidelines/ios/visual-design/typography/

With this text style, 13px may be the default value, but it will scale up and down according to people’s preferences. For example, when the size has been set to `xxLarge`, footnote will be 17px.

**Comment by SimonBasca** [comment]
Verified fix on main 6917b08d

**Comment by SimonBasca** [comment]
Fixed on v34.0 (4795)

**Comment by brampitoyo** [comment]
| Default | Largest |
| --- | --- |
| <img width="320" src="https://user-images.githubusercontent.com/51007/118413264-7cf98400-b6f2-11eb-9f24-943474a89a22.jpeg"> | <img width="320" src="https://user-images.githubusercontent.com/51007/118413372-204a9900-b6f3-11eb-8a2e-aa1eb8fe278b.jpeg"> |

@dnarcese @SimonBasca Looks good, and scales dynamically!
