### ISSUE TITLE
FXIOS-1285 ⁃ ClearPrivateDataTests.testClearsCookies - UITests

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/firefox-ios#7727]
### Bitrise Test Run:
Provide a Bitrise test run report link here showcasing the problem
https://app.bitrise.io/build/1ca47af83c9e2af1#?tab=log
### Stacktrace:
file:///Users/vagrant/git/UITests/ClearPrivateDataTests.swift:CharacterRangeLen=0&EndingLineNumber=153&StartingLineNumber=153 - XCTAssertEqual failed: ("Optional("foo=bar")") is not equal to ("Optional("null")")
### Build:
Main Dec 10th

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2662)

**Comment by isabelrios** [comment]
Failed again on 26th Jan:
https://app.bitrise.io/build/a91fdac7c8a86b64#?tab=log

**Comment by isabelrios** [comment]
Failed on 27th Jan:
https://app.bitrise.io/build/48db333ae895fc53#?tab=log

**Comment by SimonBasca** [comment]
@isabelrios any idea how to fix this?

**Comment by isabelrios** [comment]
No, I really don't know what's happening... I would say to disable it for now.. :(

**Comment by isabelrios** [comment]
These UITests are not running, closing until re-enabling them
