### ISSUE TITLE
FXIOS-1287 ⁃ App not builiding on Xcode 12.2. or higher

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/firefox-ios#7728]
Just a heads up and a reminder that it is not possible to build if we update Xcode just in case that is needed.
It fails to build A-S with error:` framework was built with 5.3 (swiftlang-1200.0.29.2 clang-1200.0.30.1) and the local version is 5.3.1 (swiftlang-1200.0.41 clang-1200.0.32.8)."`

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1287)

**Comment by AaronMT** [comment]
Swift 5.3.1 / Xcode 12.2

```[3/3] Linking ContentBlockerGen
Fatal error: Unexpectedly found nil while unwrapping an Optional value: file ContentBlockerGenLib/ContentBlockerGenLib.swift, line 30
./bootstrap.sh: line 51: 24167 Illegal instruction: 4  swift run
```

**Comment by isabelrios** [comment]
There is work done fixing this in a branch for now. Check `ios-xcode12-3` branch

**Comment by dnarcese** [comment]
This should be fixed now. Will re-open if still not working.
