### ISSUE TITLE
FXIOS-1293 ⁃ [Bug][Chron Tabs]: New blank tab crash

### ISSUE THREAD

**Issue by nbhasin2** [mozilla-mobile/firefox-ios#7733]
- Set new tab to blank tab
- open new private tab
- switch back to normal tabs

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1293)

**Comment by csuciu** [comment]
Verified as fixed on v30.0 (3297)

**Comment by SimonBasca** [comment]
@nbhasin2 This seems to be reproducible with slightly different steps. See #7880
