### ISSUE TITLE
FXIOS-1295 ⁃ When chronological tabs are open and the app is minimized, the top section changes color

### ISSUE THREAD

**Issue by lolrepeatlol** [mozilla-mobile/firefox-ios#7736]
## Steps to reproduce
1. Use the beta
2. Open the chronological tab view
3. Swipe up on the Home Bar/click the home button to go home
4. Reopen the app

### Expected behavior
The top section of the app does not change color from black.

### Actual behavior
In light mode, the top section of the app changes color from black to white, and in dark mode, the top section of the app changes color from black to gray. 
### Device & build information
* Device: iPhone XS
* Build version: Beta 30.0 build 3279
### Notes
Attachments: https://imgur.com/a/96978Ez

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1295)

**Comment by isabelrios** [comment]
Closing since it is a dup of #7653

**Comment by lolrepeatlol** [comment]
> Closing since it is a dup of #7653

Apologies!
