### ISSUE TITLE
FXIOS-1296 ⁃ Crash on SwiftData.swift

### ISSUE THREAD

**Issue by muhasturk** [mozilla-mobile/firefox-ios#7737]
## Steps to reproduce
- Try to navigate following url by passing url bar.
'https://m.youtube.com/watch?v=qQ7UfwFzndk'

### Expected behavior
Navigate url properly

### Actual behavior
Crash occurred on `SwiftData.swift` line 321
```
Thread 31: Fatal error: Unexpectedly found nil while unwrapping an Optional value
```

![Screen Shot 2020-12-11 at 13 38 53](https://user-images.githubusercontent.com/4077401/101893764-4012e980-3bb6-11eb-877c-e183132f860e.png)

### Device & build information
iPhone XR - iPhone 12 Sim - iPhone 12 Max Sim 

Firefox 29.2 (3120)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2663)

**Comment by muhasturk** [comment]
@dnarcese what is the meaning of label P3?

**Comment by yusadogru** [comment]
also this crash occurs here https://m.youtube.com/watch?v=YsBe9BFIjBs

**Comment by kcome** [comment]
The [PR #9020](https://github.com/mozilla-mobile/firefox-ios/pull/9020) will fix this crash.
