### ISSUE TITLE
FXIOS-1310 ⁃ Enhanced Tracking Protection pop up not showing trackers blocked

### ISSUE THREAD

**Issue by lolrepeatlol** [mozilla-mobile/firefox-ios#7751]
## Steps to reproduce
1. Open a webpage.
2. Tap the shield in the top left.
### Expected behavior
- I see the exact trackers that were blocked.
### Actual behavior
- I see that trackers were blocked (because the shield is purple), but I don't see which trackers are blocked anymore.
### Device & build information
* Device: iPhone XS
* Build version: 30.0
### Notes
Attachments: ![image](https://user-images.githubusercontent.com/17863082/102005754-7b620500-3ce9-11eb-88f1-aa34c82c6798.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1310)

**Comment by lolrepeatlol** [comment]
Tested on an iPhone 6S and it also has the issue on 29.2.

**Comment by dnarcese** [comment]
This is intended behaviour. We changed this popup to account for Apple's ITP.

**Comment by lolrepeatlol** [comment]
> This is intended behaviour. We changed this popup to account for Apple's ITP.

Oh sorry! Does Firefox still block trackers on its own though?
