### ISSUE TITLE
FXIOS-1313 ⁃ Add Default Browser Estimates to Leanplum

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#7754]
Vision

As a PM, I want default browser information in Leanplum to avoid sending default browser messages to users who already have Firefox set as their default

Acceptance Criteria

* app_opened_as_default_browser shared with Leanplum
* settings_menu_set_as_default_browser_pressed shared with Leanplum
* Tracking has gone through data stewardship program and maintains privacy principles

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1313)

**Comment by SimonBasca** [comment]
I am seeing the following events in Leanplum:
- E_Settings_Clicked_Set_Default_Browser when I tap on the "Set as Default Browser" button from settings
- E_App_Opened_as_Default_Browser when I am opening the browser as default browser

Verified fix on 31.0 (3467).
