### ISSUE TITLE
FXIOS-1314 ⁃ FXIOS-1314 - White background in dark mode when going back gestures triggered

### ISSUE THREAD

**Issue by Toygoon** [mozilla-mobile/firefox-ios#7756]
## Steps to reproduce
1. Enable dark mode
2. Surf any website
3. Go to second page from the first page
4. Do the 'Go back gesture'
5. White background appears in dark mode

### Expected behavior
Dark background appears in dark mode when gesture triggers

### Actual behavior
White background appears in dark mode when gesture triggers

### Device & build information
* Device: iPhone 12 Pro Max
* Build version: 14.2

### Notes
Attachments: 
![F2B18E57-D25A-44AD-978D-F503E7CDB382](https://user-images.githubusercontent.com/2356036/102168960-86c55400-3ed4-11eb-90d4-0018b684976f.gif)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1314)

**Comment by dnarcese** [comment]
Dupe #7264
