### ISSUE TITLE
Login issue

### ISSUE THREAD

**Issue by ctipper** [mozilla-mobile/firefox-ios#7764]
## Steps to reproduce
1. Go to mobile.twitter.com
2. Enter login credentials
3. What next, the login button is inactive?
4. Same for my.vmware.com

Tracking protection is not the issue same with tracking protection disabled

### Expected behavior
I’d like to be able to login but this is disabled

### Actual behavior
stuck with no option to login

### Device & build information
* Device: iPhone 8 Plus
* Build version: latest release
* 
### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2671)

**Comment by lucasmartins** [comment]
same on iPhone X, Firefox Daylight 30.0 (3279)

**Comment by lucasmartins** [comment]
@ctipper did you find any workaround for this?

**Comment by ctipper** [comment]
No workaround I can find just use Safari. Also complaining to Twitter is pointless they think you just need a password reset.

**Comment by dnarcese** [comment]
@ctipper which iOS are you on? I am not seeing this issue so I am trying to find more information to be able to reproduce. Thanks

**Comment by ctipper** [comment]
iOS 14.3 attached screenshot showing inactive login button I have cleared cache
![5AC20571-15C7-4602-B81E-391746083EE4](https://user-images.githubusercontent.com/959564/105390453-f97ec900-5c10-11eb-8ec9-5d86171f08bc.jpeg)

**Comment by dnarcese** [comment]
@ctipper Did you manually enter the login credentials or is that from an autofill?

**Comment by ctipper** [comment]
Autofill?

**Comment by dnarcese** [comment]
Was the information automatically filled in from a password manager

**Comment by ctipper** [comment]
Both methods achieve same outcome

**Comment by ctipper** [comment]
I’ve identified the issue it expects user email not user ID. But not an issue anywhere else?

**Comment by ctipper** [comment]
I mentioned this above but this site is also giving me problems and it is not my credentials that are the issue https://my.vmware.com/web/vmware/login

**Comment by SimonBasca** [comment]
This issue is not reproducible on v 31.0 (3537). I was able to sign in without any issue on https://my.vmware.com/web/vmware/login. 

@ctipper feel free to re-open the issue if it still occurs on your side.

**Comment by ctipper** [comment]
I’m using v.31 and the login button is deactivated as in the Twitter case. Note that tracking protection is disabled. 
![FEF53CA4-6768-4B1D-87EB-323F5C8BA2CD](https://user-images.githubusercontent.com/959564/107013546-673eff00-6792-11eb-97cd-ac47a3fa5b88.jpeg)

**Comment by ctipper** [comment]
@SimonBasca  how to re-open 1322, I’m still seeing the issue?

**Comment by SimonBasca** [comment]
@ctipper could you please verify that the username is typed correctly without any spacing after it?

**Comment by ctipper** [comment]
I can confirm that, and it's not the issue. It is an autofill from 1Password in this case.

**Comment by ctipper** [comment]
Also tried customer ID, no change.

**Comment by ctipper** [comment]
No that has no effect either

**Comment by SimonBasca** [comment]
In my case I am seeing the following issue:

1. Go to https://my.vmware.com/web/vmware/login
2. Autofill the credentials from a 3rd party app (In my case I am using Lockwise) 
## Actual results:
- The credentials are auto filled but the "Sign In" in button is not active. After tapping on the password field and deleting a character and retyping it, the  "Sign In" in button is active.

![vmware](https://user-images.githubusercontent.com/32130829/107023697-aaf43180-67af-11eb-8a1b-252746d50ab8.gif)

Case for "twitter.com"
0. Have credentials saved in Firefox Accounts
1. Go to mobile.twitter.com/login

## Actual results:
- The credentials are auto filled but the "Sign In" in button is not active. After tapping on the "username" field and deleting a character, the  "Sign In" in button is active.

![Twitter](https://user-images.githubusercontent.com/32130829/107023611-8d26cc80-67af-11eb-8254-2b74eb021de0.gif)

## Note: 
- I am no able to test this issue using 1Password 
- In Safari Sign In button become active immediately after autofilling the credentials.

**Comment by ctipper** [comment]
I found it was the password field that was causing the issue not the user name. But glad there is a work around, form validation? No issue in Safari for what it’s worth.
