### ISSUE TITLE
No specific links are not working.

### ISSUE THREAD

**Issue by bentsionmp** [mozilla-mobile/firefox-ios#7771]
Hi,
I found out that in some 3rd party apps Links with no specific http header all low case won’t open the web page on the iOS app.

So links like web.com
Or HTTPS://web.com/ won't open any web page though it will open the app on a blank page.
But unless the link has the "https" included in the link and all in "Low Case" it will not open the web page even if it's the exact same link but one has a "Https://" and the other has "https://" please take care of this issue it's kind of annoying to copy and paste links all the time for it to work.

Thanks.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2674)

**Comment by SimonBasca** [comment]
I was able to reproduce this issue but only for HTTPS://web.com/ link.
Steps to reproduce:
1. Go to notes
2. Type "Http://yahoo.com"
3. Tap on the "Http://yahoo.com" link

Actual result: 
- Firefox will launch but the link will not be opened.

**Comment by lmarceau** [comment]
Since only `data-sync-user` has commented on the issue after the `Stalebot` GitHub action (which triggered the removal of the `stale` label) I’ll close this issue for now. Please let us know if you think this issue needs to be reopened, we'll gladly do so. Thank you!
