### ISSUE TITLE
FXIOS-1330 ⁃ [XCUITest] ActivityStreamTest - testTopSitesRemoveAllExceptPinnedClearPrivateData

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/firefox-ios#7772]
### Bitrise Test Run:
Provide a Bitrise test run report link here showcasing the problem
https://addons-testing.bitrise.io/builds/637c33d4c09d1249/testreport/a1f9561e-ee9f-4b35-bffb-bc04f0012847/testsuite/0/testcases?status=failed
### Build:
latest main

The test started by going to BrowserTab and we need to be sure the Homescreen is loaded before that.
Just by adding :
waitForExistence(app.cells["TopSitesCell"].cells.element(boundBy: 0), timeout: 3) in L#138 will solve the issue

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1330)

**Comment by gaganmastana13** [comment]
gaganpreet Singh
