### ISSUE TITLE
Saving animated gifs

### ISSUE THREAD

**Issue by bakerrlii** [mozilla-mobile/firefox-ios#7774]
The browser is no longer saving animated gifs when save image is selected

### Device & build information
* Device: iPad
* Build version: latest release version
### This worked two versions ago
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2675)

**Comment by DragoLord19D** [comment]
I have the same problem

**Comment by SimonBasca** [comment]
Confirming that this is  an issue on Firefox 30.0 (3279) on iPad. 

- Not reproducible on iPhone 
- Not reproducible in Safari on iPad
- This issue is also reproducible on v 29.0 , v29.1 and v29.2.

**Comment by lmarceau** [comment]
Since only `data-sync-user` has commented on the issue after the `Stalebot` GitHub action (which triggered the removal of the `stale` label) I’ll close this issue for now. Please let us know if you think this issue needs to be reopened, we'll gladly do so. Thank you!

**Comment by jadonk** [comment]
Not sure what is required here. Definitely an issue.

**Comment by lmarceau** [comment]
@jadonk thanks, I'll reopen a new issue linking to this one so it can get prioritized.
