### ISSUE TITLE
FXIOS-1342 ⁃ Webpages when in system dark mode render as Firefox regular mode

### ISSUE THREAD

**Issue by AdvaitThePro** [mozilla-mobile/firefox-ios#7784]
## Steps to reproduce
1. Turn on system dark mode
2. Launch Firefox
3. Open a webpage

### Expected behavior
Firefox should render the web page in Firefox night mode

### Actual behavior
Firefox renders the web page in Firefox regular mode though system is in dark mode.

### Device & build information
* Device: Apple iPhone 7
* Build version: Firefox Daylight 30.0 Build 3279

### Notes
Attachments:
[Video Link for me doing it](https://1drv.ms/v/s!AseNVVEEPqq8kFZtP7nkdIb2vwto)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1342)

**Comment by athomasmoz** [comment]
Thank you for logging. Closing as this is expected for dark mode. It's meant to match the behaviour in other apps when the system setting is dark, which turns the skin dark only. If you would like to also turn the web pages dark, you can click menu in the bottom right and Enable Night Mode.
