### ISSUE TITLE
FXIOS-1344 ⁃ DownloadFilesTests.testToastButtonToGoToDownloads - SmokeXCUITest

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/firefox-ios#7787]
### Bitrise Test Run:
Provide a Bitrise test run report link here showcasing the problem
https://addons-testing.bitrise.io/builds/d4864e59183cb7bd/testreport/77562359-4ace-4320-9254-0003922b7b72/testsuite/0/testcases?status=failed
### Stacktrace:
file:///Users/vagrant/git/XCUITests/DownloadFilesTests.swift:CharacterRangeLen=0&EndingLineNumber=188&StartingLineNumber=188 - Expect predicate exists == true for "Downloads" Button
### Build:
Dec 22nd main 3b5e4f5

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2681)

**Comment by AaronMT** [comment]
Seen again here: https://app.bitrise.io/build/c847ed8e3629500b

**Comment by isabelrios** [comment]
Also on Feb 18th: https://app.bitrise.io/build/2f941b1a47d11771#?tab=log
This is failing more often lately

**Comment by isabelrios** [comment]
Failed on March 16th: https://app.bitrise.io/build/3a1b564482339970#?tab=log

**Comment by isabelrios** [comment]
Closing, re-open if fails again
