### ISSUE TITLE
DatabaseFixtureTest.testBookmarksDatabaseFixture - XCUITest

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/firefox-ios#7789]
### Bitrise Test Run:
Provide a Bitrise test run report link here showcasing the problem
https://app.bitrise.io/build/578c17a9dac6d259#?tab=log

### Stacktrace:
file:///Users/vagrant/git/XCUITests/DatabaseFixtureTest.swift:CharacterRangeLen=0&EndingLineNumber=33&StartingLineNumber=33 - Asynchronous wait failed: Exceeded timeout of 30 seconds, with unfulfilled expectations: "Expect predicate `count == 1013` for object <XCUIElementQuery: 0x600002e98050>".

### Build:
Dec 23rd main 074a2e180

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2683)

**Comment by SimonBasca** [comment]
This test seems to be working fine locally on latest main b04d3ed46450. My opinion is that we should close this issue and re-open if it starts to fail again.

@isabelrios how do you feel about this?

**Comment by isabelrios** [comment]
Yeah the problem is that it fails on [Bitrise](https://addons-testing.bitrise.io/builds/8705aba7c007c912/testreport/591dbae6-97b2-4f71-9737-65628c28161f/testsuite/0/testcases?status=failed) very frequently :( I think that maybe increasing the timeout could work, if not, we will have to disable it.. If you agree let's try to double the timeout to 60 and see if that works. You can do that in a PR along with other tests, no need to create one only for this...

**Comment by isabelrios** [comment]
This test keeps failing on Bitrise only no matter how long we wait for the bookmarks list to appear. The list is properly shown but the test fails. Let's disable it for now and investigate what could be the issue.
