### ISSUE TITLE
FXIOS-1350 ⁃ Crash on startup

### ISSUE THREAD

**Issue by mattmactimpson** [mozilla-mobile/firefox-ios#7794]
## Steps to reproduce
Have over 300 diffarent tabs open 

install update 29 or newer

### Expected behavior
Load the tab
### Actual behavior
Crash on startup

### Device & build information
* Device: 11 pro Max
* Build version: iOS 14.3 and app version 30.0
### Notes

so since update 29 the app crashes on startup I have over 300 tabs and every time it crashes
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2684)

**Comment by data-sync-user** [comment]
➤ Daniela Arcese commented:

Needs investigation: 

  * Could this be related to ios 14.3?

**Comment by mattmactimpson** [comment]
> ➤ Daniela Arcese commented:
> 
> Needs investigation: 
> 
>   * Could this be related to ios 14.3?

This started since update 28 which I was on iOS 14 maybe 14.1 when this started

**Comment by SimonBasca** [comment]
@mattmactimpson when you tap on the tab counter what version of Tabs Tray are you seeing? 

Screenshot A
![A](https://user-images.githubusercontent.com/32130829/105180203-eac1e480-5b32-11eb-85db-c9a9f92c87ef.PNG)

Screenshot B
![B](https://user-images.githubusercontent.com/32130829/105180238-f6151000-5b32-11eb-8558-42b7b5228cc2.PNG)

**Comment by mattmactimpson** [comment]
> @mattmactimpson when you tap on the tab counter what version of Tabs Tray are you seeing? 
> 
> 
> 
> ## Screenshot A
> 
> ![A](https://user-images.githubusercontent.com/32130829/105180203-eac1e480-5b32-11eb-85db-c9a9f92c87ef.PNG)
> 
> 
> 
> ## Screenshot B
> 
> ![B](https://user-images.githubusercontent.com/32130829/105180238-f6151000-5b32-11eb-8558-42b7b5228cc2.PNG)
> 
> 
> 
> 

I was seeing screenshot B before it started crashing
