### ISSUE TITLE
FXIOS-1361 ⁃ I can't build using Xcode 12.0

### ISSUE THREAD

**Issue by NewBunny96** [mozilla-mobile/firefox-ios#7804]
I am followed the steps. But, I can't get successful build. Seems, I am missing soothing  that's not listed in **Building the code**.

I tried last release **firefox-ios-30.0** as well. Latest one and last release builds with exactly same error.

**Build input file cannot be found**

https://ibb.co/3NQQvQP

So, I deleted the unknown files in each target and builded again then I got below error,

**Type 'GleanMetrics' has no member 'ReadingList'**

https://ibb.co/TT86mvr

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2687)

**Comment by AaronMT** [comment]
Hello @NewBunny96, have you tried the following?

Building the code
-----------------

1. Install the latest [Xcode developer tools](https://developer.apple.com/xcode/downloads/) from Apple.
1. Install Carthage, Node, and a Python 3 virtualenv for localization scripts:
    ```shell
    brew update
    brew install carthage
    brew install node
    pip3 install virtualenv
    ```
1. Clone the repository:
    ```shell
    git clone https://github.com/mozilla-mobile/firefox-ios
    ```
1. Pull in the project dependencies:
    ```shell
    cd firefox-ios
    sh ./bootstrap.sh
    ```
1. Open `Client.xcodeproj` in Xcode.
1. Build the `Fennec` scheme in Xcode.

**Comment by NewBunny96** [comment]
@AaronMT 

Yes, Now I tried with `xcode 12.4` also tried to build using `xcode 12.3 ` and the branch is `ios-xcode12-3`; The error. But got this error, 

https://github.com/mozilla-mobile/firefox-ios/issues/8703

**Comment by AaronMT** [comment]
I would suggest trying Xcode 12.5 as that is the latest we support and building the **main** branch. I would also try running **bootstrap.sh --force** to wipe out any residual older build data in your environment. Outside of that, it just sounds like an environmental issue with your machine.
