### ISSUE TITLE
Test Strict ETP by Default in PBM

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#7821]
**Vision**

As a Firefox for iOS user, I want the benefits of ETP (less ads, more privacy) when in private browsing mode without having to go looking for them and know the lingo

**Acceptance Criteria**

* Split test setup where:
  * Control gets current experience (standard by default)
  * Treatment gets strict ETP by default when in PBM 

{panel:bgColor=#eae6ff}
[Experiment Brief](https://docs.google.com/document/d/1pIjgjZ23naVKwR7hPnkEuBMrUujS9kFK5ee9uaC-GYQ/edit#)
{panel}

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2692)

**Comment by data-sync-user** [comment]
➤ Daniela Arcese commented:

🚩 Flag added

test

**Comment by sarik20** [comment]
> ➤ Daniela Arcese commented:
> 
> 🚩 Flag added
> 
> test
