### ISSUE TITLE
FXIOS-1395 ⁃ [iPad] Closing and re-opening Firefox causes issues in URL bar

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#7837]
## Steps to reproduce
1. Go to Youtube.com
2. Close the app from app switcher
3. Re-open the app
### Expected behavior
- The URL bar should be in the correct position.
### Actual behavior
- The URL bar is not the correct position.
### Device & build information
* Device: iPad Pro (14.0)
* Build version: 22c479431
### Notes
- Issue is not reproducible before commit 0467e8400
Attachments: 
![Picture_2021_01_11T14_03_30_103Z](https://user-images.githubusercontent.com/32130829/104192306-51564c80-5427-11eb-9472-443a94d6c42f.jpeg)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1395)

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verified fix on 7e54b8b95
