### ISSUE TITLE
FXIOS-1409 ⁃ Update how bookmarks are accessed in Firefox

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#7851]
┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1409)

**Comment by data-sync-user** [comment]
➤ Nishant Bhasin commented:

Finally got ApplicationServices to work on Firefox iOS with XCode 12.3 as well. Basically starting from XCode 12.3 it requires us to have validate workspace option in pbxproj but nowhere in Apple's documentation or whats new section for new XCode does it say that we need to set this variable. Once we set the variable everything works with dynamic A~S lib compiled against XCode 12.3 (locally)

These libs are published to my repo until we get proper build from A~S CI pipeline. I made a PR for this but it requires some cleanup before it can be merged.

Apple's framework system has become more complicated with introduction of new architectures. Apple is moving towards xcframeworks (introduced about 2 years ago in wwdc) which I'll do some research into as it might be beneficial to use them moving forward.

**Comment by data-sync-user** [comment]
➤ Nishant Bhasin commented:

Update verify-ios script on application services repo and have A~S framework build dynamically

PR: https://github.com/mozilla/application-services/pull/3822

**Comment by data-sync-user** [comment]
➤ Nishant Bhasin commented:

Firefox iOS

  * Changed firefox-ios project to support dynamically linked binary: https://github.com/mozilla-mobile/firefox-ios/pull/7869
  * Added an XCode 12.3 based workflow to BR yml file: https://github.com/mozilla-mobile/firefox-ios/pull/7864 ( https://github.com/mozilla-mobile/firefox-ios/pull/7864 )
  * Made a branch that fully supports XCode 12.3 with locally built A~S frameworks: https://github.com/nbhasin2/firefox-ios/tree/nb/XCode_12_3_update ( https://github.com/nbhasin2/firefox-ios/tree/nb/XCode_12_3_update )

**Comment by data-sync-user** [comment]
➤ Nishant Bhasin commented:

Submitted a PR to update XCode 12.3 on CirecleCI so that we can get an official A~S framework: https://github.com/mozilla/application-services/pull/3825 ( https://github.com/mozilla/application-services/pull/3825 )

**Comment by data-sync-user** [comment]
➤ Nishant Bhasin commented:

Next steps:

When A~S spins out a new build with XCode 12.3 and as long as it works we can look into moving our main branch to support 12.3 (officially)

  * Update Firefox-iOS Carthage file to support latest XCode 12.3 while merging in XCode_12_3_update to main branch.
  * Update BR yml file to latest XCode 12.3

**Comment by data-sync-user** [comment]
➤ Nishant Bhasin commented:

Bumped this issue as a 5 for the amount of investigation and effort required but now when it rolls over to next sprint we can just make it a 2 or even 1. 

As we are mostly waiting for drop of new A~S framework.

**Comment by rfk** [comment]
@nbhasin2 thanks again for pushing through on this work! I'm curious, do you have a good sense of how the switch to dynamic appservices affected overall app size and/or performance?

**Comment by nbhasin2** [comment]
> @nbhasin2 thanks again for pushing through on this work! I'm curious, do you have a good sense of how the switch to dynamic appservices affected overall app size and/or performance?

@rfk You are more than welcome and thank you for helping out as well. From my understanding and prior experience with dynamic libs it will reduce app size but startup performance can take a hit on older phones due to runtime linking.

While testing on an iPhone 11 pro I didn't see any difference in performance at all. 

In upcoming week or so the plan is to push out Firefox iOS Beta with latest 69.0.0 and get some feedback on performance and lookout for bugs 🤞

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verified fix on main dc14c075. The basic functionality of bookmarks was verified and works as expected.
