### ISSUE TITLE
FXIOS-1413 ⁃ testPocketEnabledByDefault is failing intermitently on Bitrise

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#7855]
This bug is to re-enable testPocketEnabledByDefault. I currently disabled it because I found several issues with the test:

1. There are two cases that need to be handled for iPhone: 
- When the default browser card is displayed this assertion https://github.com/mozilla-mobile/firefox-ios/blob/807cb6629c2e075d747d3df3ef64fc6eb3c9f069/XCUITests/PocketTests.swift#L15 is equal to 2
- When the default browser card is not displayed this assertion (https://github.com/mozilla-mobile/firefox-ios/blob/807cb6629c2e075d747d3df3ef64fc6eb3c9f069/XCUITests/PocketTests.swift#L15 is equal to 6

2. There are two cases that need to be handled for iPad: 
- When the default browser card is displayed this assertion https://github.com/mozilla-mobile/firefox-ios/blob/807cb6629c2e075d747d3df3ef64fc6eb3c9f069/XCUITests/PocketTests.swift#L17 is equal to 7
- When the default browser card is not displayed this assertion https://github.com/mozilla-mobile/firefox-ios/blob/807cb6629c2e075d747d3df3ef64fc6eb3c9f069/XCUITests/PocketTests.swift#L17 is equal to 10

3. When this element https://github.com/mozilla-mobile/firefox-ios/blob/807cb6629c2e075d747d3df3ef64fc6eb3c9f069/XCUITests/PocketTests.swift#L32 is tapped the pocket page does not open.

4. This assertion https://github.com/mozilla-mobile/firefox-ios/blob/807cb6629c2e075d747d3df3ef64fc6eb3c9f069/XCUITests/PocketTests.swift#L35 should fail because there is no page open and the URL bar is empty, but it does not fail.

Solution: 
1. Change element https://github.com/mozilla-mobile/firefox-ios/blob/807cb6629c2e075d747d3df3ef64fc6eb3c9f069/XCUITests/PocketTests.swift#L15
2. Change element https://github.com/mozilla-mobile/firefox-ios/blob/807cb6629c2e075d747d3df3ef64fc6eb3c9f069/XCUITests/PocketTests.swift#L32
3. Fix failing assertions

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2698)

**Comment by isabelrios** [comment]
Tests running successfully on Bitrise, closing for now
