### ISSUE TITLE
[iPad] Tab counter refreshes when switching tabs when tab counter displayes infinty simbol

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#7861]
## Steps to reproduce
- Have  over 100 tabs open.
## Steps to reproduce
1. Switch between tabs
### Actual behavior
- The tab counter refreshes every time a tab is switched.
### Device & build information
* Device: iPad Pro (14.0)
* Build version: 30.0 (279) and main cdef061
### Notes
Attachments:
[Video.mp4.zip](https://github.com/mozilla-mobile/firefox-ios/files/5850909/Video.mp4.zip)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2700)

**Comment by lmarceau** [comment]
Since only `data-sync-user` has commented on the issue after the `Stalebot` GitHub action (which triggered the removal of the `stale` label) I’ll close this issue for now. Please let us know if you think this issue needs to be reopened, we'll gladly do so. Thank you!
