### ISSUE TITLE
FXIOS-1420 ⁃ [UnitTest] This unit test is failing intermittently quite often on Bitrise: TabManagerStoreTests.testAddedTabsAreStored()

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/firefox-ios#7867]
See for example this build logs: https://app.bitrise.io/build/f4aabc2ab5b572ff#?tab=log

[Failure](https://addons-testing.bitrise.io/builds/f4aabc2ab5b572ff/testreport/891f3ea0-0e67-4a3d-96ae-b7c4aea4fed2/testsuite/3/testcases?status=failed): `file:///Users/vagrant/git/ClientTests/TabManagerStoreTests.swift:CharacterRangeLen=0&EndingLineNumber=97&StartingLineNumber=97 - Asynchronous wait failed: Exceeded timeout of 2 seconds, with unfulfilled expectations: "saved".`

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2702)

**Comment by ryersonjames** [comment]
Yes

**Comment by isabelrios** [comment]
Failied again on March 8th. See logs: https://addons-testing.bitrise.io/builds/b8e70b710955591c/testreport/f11c97eb-f293-4bd0-acaf-964d351fc815/testsuite/0/testcases?status=failed

**Comment by isabelrios** [comment]
Failed on March 9th. [Logs](https://addons-testing.bitrise.io/builds/79aa5a565f414985/testreport/d7dfed87-0f67-4862-b27d-314e8d1ffdd2/testsuite/3/testcases?status=failed):
file:///Users/vagrant/git/ClientTests/TabManagerStoreTests.swift:CharacterRangeLen=0&EndingLineNumber=86&StartingLineNumber=86 - Asynchronous wait failed: Exceeded timeout of 2 seconds, with unfulfilled expectations: "saved".

cc FYi, just in case there is a real problem with this @nbhasin2 @dnarcese @boek

**Comment by isabelrios** [comment]
Failed on March 15th on PR: https://app.bitrise.io/build/a26efb08a8df53bf#?tab=log

**Comment by isabelrios** [comment]
Failed again on main March 18th: https://addons-testing.bitrise.io/builds/2749fd3ef03e8e41/testreport/a5517e5b-b8e2-4758-b337-c949fca4140a/testsuite/2/testcases?status=failed

**Comment by isabelrios** [comment]
Failed March 22nd on PR: https://app.bitrise.io/build/c94519fd96c6b2ec#?tab=artifacts

**Comment by isabelrios** [comment]
Failed on main March 23rd: https://addons-testing.bitrise.io/builds/2f309059c9d83415/summary?status=failed
