### ISSUE TITLE
FXIOS-1424 ⁃ [Chronological Tabs] Crash when tapping “Go to Copied link” and following the STR

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#7872]
## Preconditions
1. Have a link copied to clipboard
2. Have all tabs in Normal Browsing and Private Browsing closed
3. Have Firefox closed from app switcher
## Steps to reproduce
1. Tap “Go to Copied link” from Today Widget or Quick action Widget
2. Close the Opened tabs in Normal Browsing
3. Close Firefox from app switcher
4. Tap “Go to Copied link” from Today Widget or Quick action Widget
5. Switch to Private Browsing
6. Switch to Normal Browsing
7. Close the Opened tabs in Normal Browsing
8. Repeat steps 3) to 7)
### Actual behavior
- Firefox will crash. 
### Device & build information
* Device: iPhone XR (14.3)
* Build version: 30.0 (3279)
### Notes
- Crash log can be found here: https://sentry-fm.prod.mozaws.net/mozilla/firefox-ios-300/issues/622352/?query=app.device%3A%22ff4804176359ed9d9df2225c57bdd2175d45793e%22
- No crash log is generated locally. 
Attachments: 
Video link : https://www.youtube.com/watch?v=oajhcPDT_YQ

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2703)

**Comment by dnarcese** [comment]
Could this be #7733 ?
