### ISSUE TITLE
FXIOS-1423 ⁃ Tabs are not Closed when tapping “Close Private tabs” via Today Widget

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#7873]
## Steps to reproduce
1. Open a tab in Private Browsing and go to Youtube
2. Background Firefox
3. Tap the “Close Private tabs” via Today Widget
### Expected behavior
- The Private tab should be closed.
### Actual behavior
- The Private tab is not closed
### Device & build information
* Device: iPhone Xr (14.3)
* Build version: 30.0 (3279)
### Notes
- Tabs are closed when tapping “Close Private tabs” from Quick Action Widget (Medium)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2704)

**Comment by dnarcese** [comment]
Notes: This is on the old iOS 13 widget on iOS 14 device.
