### ISSUE TITLE
Media Capture through getUserMedia does not work

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/firefox-ios#7879]
(This issue was specifically reported because of audio capture not working on https://hubs.mozilla.org - it is probably a good idea to investigate that in more detail

According to https://webkit.org/blog/11353/mediarecorder-api/ there should now be support on iOS 14.3 and newer for capturing audio via `navigator.mediaDevices.getUserMedia` in `WKWebView` based applications like Firefox iOS.

One site that uses this functionality is https://hubs.mozilla.org - Even though the site asks for audio access, and the audio permission prompt shows, no audio seems to be streaming after that. This functionality does work in Chrome, which is also `WKWebView` based, so I am wondering if Firefox iOS is missing something.

It is unclear what is going wrong, but the above blog post links to the following document with technical requirements that may give more hints.

https://developer.apple.com/documentation/avfoundation/cameras_and_media_capture/requesting_authorization_for_media_capture_on_ios

I think it may also be good to hook up a web inspector to Firefox iOS when it is opening https://hubs.mozilla.org to see if there may be a web compatibility or API-use issue.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2707)

**Comment by lmarceau** [comment]
Since only `data-sync-user` has commented on the issue after the `Stalebot` GitHub action (which triggered the removal of the `stale` label) I’ll close this issue for now. Please let us know if you think this issue needs to be reopened, we'll gladly do so. Thank you!
