### ISSUE TITLE
FXIOS-1435 ⁃ Face ID dialog is not displayed when tapping on the "Login & Passcode" screen with Face ID enabled

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#7887]
## Preconditions:
- Go to Settings -> Face ID & Passcode -> Turn On Passcode and enable "Use Face ID" to access logins
- Go to "Login & Passcode" screen and check that Face ID is working as expected
## Steps to reproduce
1. Restart the device
2. Go to "Login & Passcode" screen
### Expected behavior
- Face ID dialog should be displayed when tapping on the "Login & Passcode" screen.
### Actual behavior
- Face ID dialog is not displayed when tapping on the "Login & Passcode" screen.
### Device & build information
* Device: iPhone Xr (14.3)
* Build version: 31.0 (3467)
### Notes
- The issue is not reproducible when using Passcode authentication with Face ID disabled.
- The issue is reproducible after disabling and re-enabling "Face ID" to access logins screen
## Attachments: 

- Before restart
![Gif 1](https://user-images.githubusercontent.com/32130829/105722893-ce58ea00-5f2e-11eb-95f3-c6698b80b0f4.gif)

- After restart
![Gif](https://user-images.githubusercontent.com/32130829/105722650-918cf300-5f2e-11eb-8fb0-cde645c3f34a.gif)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1435)

**Comment by athomasmoz** [comment]
@SimonBasca Does this mean that users cannot get to their "Login & Passwords" page or that they need to use their passcode instead of face id to access it?

**Comment by SimonBasca** [comment]
@athomasmoz they would need to disable the "Face ID" authentication or remove the login protection completely in order to get to the "Login & Passcode". The "Login & Passcode" screen is not accessible while "Face ID" is enabled. 

It's my feeling that this would be a bad experience because the normal user will not be able to immediately figure out what the issue is and how to work around it.

**Comment by data-sync-user** [comment]
➤ Ashley Thomas commented:

Timebox to a 3

**Comment by boek** [comment]
@SimonBasca are you able to reproduce this on iOS 14.4?

**Comment by SimonBasca** [comment]
@boek I am no longer reproducing the issue following the STR from the description on iOS 14.4 or lower iOS version. I will re-open if the issue is reproducible again.
