### ISSUE TITLE
"Open link in external app" dialog is not displayed on About:Home

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#7899]
## Steps to reproduce
1. Open a new tab with Top Sites displayed
2. In the URL bar, type "mailto:example@gmail.com" and hit go
### Expected behavior
- "Open link in external app" dialog should be displayed on About:Home
### Actual behavior
- "Open link in external app" dialog is not displayed on About:Home. After loading a page in the same tab, the dialog will be displayed.
### Device & build information
* Device: iPhone Xr (14.3)
* Build version: 31.0 (3467)
### Notes
- The "Open link in external app" dialog is displayed when typing "mailto:example@gmail.com" in the URL bar on a webpage e.g. "google.com"
- This issue is not a recent regression.
Attachments: 
[Video.mp4.zip](https://github.com/mozilla-mobile/firefox-ios/files/5879905/Video.mp4.zip)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2716)

**Comment by SimonBasca** [comment]
We should also cover https://github.com/mozilla-mobile/firefox-ios/issues/8576#issuecomment-847760496 when fixing this issue.

**Comment by lmarceau** [comment]
Since only `data-sync-user` has commented on the issue after the `Stalebot` GitHub action (which triggered the removal of the `stale` label) I’ll close this issue for now. Please let us know if you think this issue needs to be reopened, we'll gladly do so. Thank you!
