### ISSUE TITLE
FXIOS-1445 - Logins are incorrectly selected after clearing the "Filter" field

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#7900]
## Steps to reproduce
1. Go to login screen
2. Tap "Edit"
3. Tap on the "Filter" field
4. Type a word that filters the login list and returns a few results
5. Select the results
6. Tap "Cancel"
### Expected behavior
- Logins should be correctly selected
### Actual behavior
- Different logins are selected
### Device & build information
* Device: iPhone Xr (14.3)
* Build version: 31.0 (3467)
* ### Notes
Attachments: 
[Video.mp4.zip](https://github.com/mozilla-mobile/firefox-ios/files/5880105/Video.mp4.zip)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2717)

**Comment by lmarceau** [comment]
Since only `data-sync-user` has commented on the issue after the `Stalebot` GitHub action (which triggered the removal of the `stale` label) I’ll close this issue for now. Please let us know if you think this issue needs to be reopened, we'll gladly do so. Thank you!
