### ISSUE TITLE
FXIOS-1456 ⁃ Files cannot be shared from Browser on iOS

### ISSUE THREAD

**Issue by bentsionmp** [mozilla-mobile/firefox-ios#7933]
There's a big issue with the browser not being able to send files from the browser itself.
When trying to share a downloaded file from the Firefox browser app it will only send a path from the file system instead of the file itself.
For example when trying to share a downloaded PDF it will send something like that:

file:///private/var/mobile/Containers/Data/Application/A722-4516-AB70-4CDBD36FDB7A/tmp/TempDocs/PDF%20Project.pdf

The only way to share a file is to go from the browser to the Firefox download folder in the files app and share it from there.
It's very annoying because people who love the browser cannot be as productive with it as they would be with safari browser for example.

Please fix this so we can use it as we should.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1456)

**Comment by SimonBasca** [comment]
Confirming that this is an issue on v31.0 (3537). 
Steps to reproduce: 
1. Go to google.com and search for "sample PDF"
2. Tap on a PDF file
3. Open the Page Action Menu
4. Tap Share
5. Select an app to send the link (e.g FB Messenger)

Actual results:
- "file:///private/var/mobile/Containers/Data/Application/94F8EA87-84B4-4AFF-A757-287E1DC3C8C0/tmp/TempDocs/sample.pdf" is sent on Mesenger

Expected results:
- A valid link should be sent.

Note:
- Safari sends a valid link after following the STR.

**Comment by HanKruiger** [comment]
I can confirm this. This is not a new issue, it has been around for a while.
I would like to clarify that my use case is a bit different though. I expect the file to be shareable to the Files app as a file. Not as a web link.

## Steps to reproduce

1. Visit a URL that serves a PDF file.
2. Open the Page Action Menu
3. Tap Share

## Expected results

- I can see the 'Save to Files' action.

Screenshot from how it behaves in Safari: 
![safari](https://user-images.githubusercontent.com/2293252/107531863-8b994200-6bbd-11eb-8e53-1bb749e9d5b2.jpeg)

## Actual results

- I cannot see the 'Save to Files' action.

Screenshot from how it behaves in Firefox:
![ff](https://user-images.githubusercontent.com/2293252/107532160-e337ad80-6bbd-11eb-9a8a-2bce67e736c6.jpeg)

Note that I *have* tried to add an action in the 'Edit Actions' menu..

**Comment by SimonBasca** [comment]
Fixed on main bb583f562c.

**Comment by bentsionmp** [comment]
Thank you for everyone who participated in fixing this issue 🙏🏼
