### ISSUE TITLE
FXIOS-1460 ⁃ Remove 1Passowrd string from info.plist in l10n exports

### ISSUE THREAD

**Issue by boek** [mozilla-mobile/firefox-ios#7937]
For some reason Xcode 12 is including this string in the export. Let's make sure it doesn't get included again

for good measure let's remove it from the import as well

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2721)

**Comment by data-sync-user** [comment]
➤ Daniela Arcese commented:

We want to do this before our next string export
