### ISSUE TITLE
[XCUITest] Modify tests accordingly once Google is added as a top site by default

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/firefox-ios#7953]
There are several tests that may be affected by this change. Mainly in ActivityStream Test suite.

Depens on PR that has to be open but WIP

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2723)

**Comment by isabelrios** [comment]
See [Jira ticket](https://jira.mozilla.com/browse/FXIOS-1223) for that. Note that this will be available only in US

**Comment by SimonBasca** [comment]
@isabelrios do you think this is still something we should land?

**Comment by lmarceau** [comment]
Since only `data-sync-user` has commented on the issue after the `Stalebot` GitHub action (which triggered the removal of the `stale` label) I’ll close this issue for now. Please let us know if you think this issue needs to be reopened, we'll gladly do so. Thank you!
