### ISSUE TITLE
FXIOS-1471 ⁃ Increased blank space around URL bar after updating to v31

### ISSUE THREAD

**Issue by struq** [mozilla-mobile/firefox-ios#7956]
## Steps to reproduce
Open any webpage

### Expected behavior
The amount of blank space above and below the URL bar should be the same as before the update.

### Actual behavior
There is more blank space above and below the URL bar for no apparent purpose.

### Device & build information
* Device: iPhone 6s, iPad Pro 
* Build version: 31.0 (3537)

### Notes
Attachments: 
![IMG_399BEE8E88BD-1](https://user-images.githubusercontent.com/2097707/107407941-4d762280-6ad8-11eb-84d7-8e6240dcaf8b.jpeg)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1471)

**Comment by dnarcese** [comment]
The reason for this is that we made the urlbar text size dynamic. The space became larger to account for the larger urlbar when the text size is bigger. 

To fix this, the space around the urlbar would also need to dynamically resize.

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verified fix on v33.0 (4031)
