### ISSUE TITLE
FXIOS-1477 ⁃ Top bar height increased

### ISSUE THREAD

**Issue by Geo1088** [mozilla-mobile/firefox-ios#7966]
(The feedback section of the app is apparently defunct, so I figured I'd submit an issue here - hopefully this is okay. Sorry if not.)

The last update I got seems to have increased the height of the top bar with the URL and page actions. Especially since I'm on a first generation SE, making the bar larger just to add padding to the top and bottom of the URL box seems an unfortunate design change to me. 

App settings reports version Firefox Daylight 31.0 (3537). Screenshots in portrait and landscape are attached.

![portrait mode screenshot](https://user-images.githubusercontent.com/4165301/107607588-a8f2fe00-6c07-11eb-9675-8e9d396bde79.png)

![landscape mode screenshot](https://user-images.githubusercontent.com/4165301/107607595-aee8df00-6c07-11eb-961b-e1bee2f6bc40.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1477)

**Comment by dnarcese** [comment]
Dupe #7956
