### ISSUE TITLE
FXIOS-1480 ⁃ iPhone Tabs Tray Refresh

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#7970]
**Vision**

As Firefox user on iPhone, I want an easy way to find, close, and open new tabs, so that I can start new tasks, while keep information open in existing tabs to return to later

**Acceptance Criteria**

* Tabs as a tray
* Tabs and private tabs as menu at the top
* Remove search tabs
* Move trash can over to avoid accidental clicks

**Not Included**

* Changing tabs from tiles to a list view is not included
* Chronological ordering of tabs is not included
* Moving synced tabs to tabs tray is not included

**Spec**

[Figma](https://www.figma.com/file/lfgj15zbNkL9Pp4hdZGJgp/Proton-Mobile-UI?node-id=101%3A3907)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1480)

**Comment by data-sync-user** [comment]
➤ Daniela Arcese commented:

A contributor created a PR for this #8091. Let's take a look before starting this

**Comment by SimonBasca** [comment]
Verified fix on v34.0 (4722).
