### ISSUE TITLE
FXIOS-1482 ⁃ Move Synced Tabs to Tabs Tray

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#7972]
**Vision**

As a user of Firefox across multiple platforms, I want a quick way to find my tabs open on other devices, so that I can start a task on one device and pick it up on another

**Acceptance Criteria**

* Add to menu at the top of tabs tray
* Remove from library tray
* Pull down to refresh functionality retained
* Button added to refresh synced tabs
* Replace synced tabs on new tab page with History
* Done for both iPhone and iPad
* Counts added in FXIOS-1519 are updated to match the new location

**Spec**

[Updated Menu on Tabs Tray](https://www.figma.com/file/lfgj15zbNkL9Pp4hdZGJgp/Proton-Mobile-UI?node-id=338%3A27251)

[Updated New Tab Page](https://www.figma.com/file/lfgj15zbNkL9Pp4hdZGJgp/Proton-Mobile-UI?node-id=104%3A19556)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1482)

**Comment by data-sync-user** [comment]
➤ Daniela Arcese commented:

A contributor created a PR for this #8091

**Comment by SimonBasca** [comment]
Verified fix on v34.0 (4551)
