### ISSUE TITLE
FXIOS-1483 ⁃ Open Tabs & Synced Tabs in Search Suggestions

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#7973]
**Vision**

As a Firefox user on iPhone & iPad, I want open tabs and synced tabs included in my search suggestions, so that if I've left open the page I'm looking for, it's easy to find it again when I redo my search

**Acceptance Criteria**

* Include open tabs in search suggestions
* Include synced tabs in search suggestions
* Add icons next to search suggestion types (bookmarks, synced tabs, open tabs)

* Reformat Bookmarks search suggestion to have the same style as open tabs
* This should be done for iPhone and iPad

**Spec**

[Figma](https://www.figma.com/file/lfgj15zbNkL9Pp4hdZGJgp/Proton-Mobile-UI?node-id=337%3A34232)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1483)

**Comment by SimonBasca** [comment]
Verified fix on v34.0 (4551).
