### ISSUE TITLE
FXIOS-1485 ⁃ Switch to system-native Pull-down Menu

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#7976]
**Vision**

As a user, I want to see more components that are familiar to me to make it easier for me to find what I am looking for and get what I need to do done.

**Acceptance Criteria**

* Use the system-native Pulldown menu for:
Application menu [Figma](https://www.figma.com/file/lfgj15zbNkL9Pp4hdZGJgp/Proton-Mobile-UI?node-id=339%3A27332)
Page Actions menu [Figma](https://www.figma.com/file/lfgj15zbNkL9Pp4hdZGJgp/Proton-Mobile-UI?node-id=422%3A1)
* on iPhone _and_ iPad
* for dark and light mode
* ensure accessibility is not broken
* toggles are replaced with text and icon
Instead of a toggle changing when the menu item is tapped, the icon and text will change.

ex. if you click "Block Images" menu item, the text changes to "Show Images" and the icon changes.

App menu:
                -Turn on Night Mode / Turn off Night Mode (use existing moon icon for both 
                -Block Images / Show Images (same icon for block, new icon for show) [Figma](https://www.figma.com/file/lfgj15zbNkL9Pp4hdZGJgp/Proton-Mobile-UI?node-id=339%3A27332)

Page actions menu:
                 -Request Desktop Site / Request Mobile Site (desktop icon, mobile icon) [Figma](https://www.figma.com/file/lfgj15zbNkL9Pp4hdZGJgp/Proton-Mobile-UI?node-id=422%3A1)

Note: this includes moving the icons to the right of the menu item

Note: For iOS < 14 where it is not supported, fallback to Action Sheets (iOS) and Popovers (iPadOS).

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1485)

**Comment by data-sync-user** [comment]
➤ Ashley Thomas commented:

Note: We should test this with a screen reader

**Comment by SimonBasca** [comment]
Verified fix on v34.0 (4722)
