### ISSUE TITLE
FXIOS-1487 ⁃ Rename and reorder menu items

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#7977]
**Vision**

As a user, I want a more cohesive look & feel when I switch between desktop and mobile.

**Acceptance Criteria**

* The ordering of menu items and the naming match the mocks for
Application menu [Figma](https://www.figma.com/file/lfgj15zbNkL9Pp4hdZGJgp/Proton-Mobile-UI?node-id=339%3A27236)
Page Actions menu [Figma](https://www.figma.com/file/lfgj15zbNkL9Pp4hdZGJgp/Proton-Mobile-UI?node-id=422%3A0)
* For both iPhone and iPad

See [spreadsheet](https://docs.google.com/spreadsheets/d/1RMB_AGwzJjRbJ_ixye7hAOh1w3Vd0UWiy73zN_3nfd4/edit#gid=0) for string changes.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1487)

**Comment by SimonBasca** [comment]
Verified fix on v34.0 (4722)
