### ISSUE TITLE
FXIOS-1486 ⁃ Replace icons with new iconset

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#7978]
**Vision**

As a user, I want a more cohesive look & feel when I switch between desktop and mobile.

**Acceptance Criteria**

New icons are used for the following:

* Address bar (e.g. Tracking Protections, lock, page actions)
* Toolbar (e.g. Back, Forward, Refresh, Tabs)
* Settings (e.g. Sync)
* Tabs Tray (e.g. Tabs, Private Tabs, Synced Tabs)
* Library Tray (e.g. Bookmarks, History, Reading List, Downloads, Bookmarks Folder)
* New Tab Page (e.g. Top Sites, Your Library)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1486)

**Comment by SimonBasca** [comment]
Verified fix on v34.0 (4722)
