### ISSUE TITLE
FXIOS-1489 ⁃ iPad tab strip design

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#7979]
**Vision**

As a user, I want a more cohesive look & feel when I switch between desktop and mobile.

**Acceptance Criteria**

The top tab strip is updated according to the mocks. The new changes include:

* “Floating tab” design
* Background colour change
* Selected tab change

Applies to both light and dark theme.

Notes

* keep current resizing logic
* doesn't include adding "Playing" indicator

[Figma](https://www.figma.com/file/lfgj15zbNkL9Pp4hdZGJgp/Proton-Mobile-UI?node-id=339%3A34122)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1489)

**Comment by SimonBasca** [comment]
Verified fix on v34.0 (4227)
