### ISSUE TITLE
FXIOS-1491 ⁃ Switch to system-native controls for Library Tray

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#7981]
**Vision**

As a user, I want to see more components that are familiar to me to make it easier for me to find what I am looking for and get what I need to do done.

**Acceptance Criteria**

* The library tray buttons are moved to a segmented control at the top of the panel.
* for iPhone and iPad

[Figma](https://www.figma.com/file/lfgj15zbNkL9Pp4hdZGJgp/Proton-Mobile-UI?node-id=104%3A17964)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1491)

**Comment by data-sync-user** [comment]
➤ Nishant Bhasin commented:

This should be wrapped up today and maybe 1 point of work left

**Comment by SimonBasca** [comment]
Verified fix on v34.0 (4722)
