### ISSUE TITLE
FXIOS-1490 ⁃ Switch to system-native view for Library Tray

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#7982]
**Vision**

As a user, I want to see more components that are familiar to me to make it easier for me to find what I am looking for and get what I need to do done.

**Acceptance Criteria**

The Library Tray uses a system-native view instead of a custom view.

* swipe down to dismiss
* for iOS < 13.0 add "x" button to top left
* for both iPhone and iPad

[Figma](https://www.figma.com/file/lfgj15zbNkL9Pp4hdZGJgp/Proton-Mobile-UI?node-id=104%3A17964)

**Notes**

Does not include moving the buttons to the top. (#7981)

Accessibility is covered in #6346

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1490)

**Comment by data-sync-user** [comment]
➤ Ashley Thomas commented:

We should test if this fixes #6346 (FXIOS-323)

**Comment by SimonBasca** [comment]
Verified fix on v34.0 (4722).
