### ISSUE TITLE
FF 31.0 crash when accessing https with auth realm

### ISSUE THREAD

**Issue by nicoonline** [mozilla-mobile/firefox-ios#7985]
FF Crash on requesting a https URL with a password authentification.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2732)

**Comment by nicoonline** [comment]
Bug already in FF30

**Comment by SimonBasca** [comment]
@nicoonline could you please provide an example site?

**Comment by nicoonline** [comment]
i can provide an example in private message

**Comment by SimonBasca** [comment]
You can send me an email at sbasca@mozilla.com.

**Comment by SimonBasca** [comment]
@nicoonline I was unable to reproduce the issue on the provided URL. Could you please let me know what device and iOS version are you using?

**Comment by nicoonline** [comment]
Hello on IPAD/Iphone IOS 14.4

**Comment by SimonBasca** [comment]
Unfortunately I am still unable to reproduce. Upon vising the provided URL the page loads correctly and the "Authentication Required" prompt is displayed. Maybe the crash happens after authentication with correct credentials. 

@nicoonline If you could provide the crash log, it would be very helpful in debugging this issue. Here are some instructions on how to get the crashlog : https://help.getpocket.com/article/1098-how-to-find-the-iphone-ipad-app-crash-logs.

The Firefox app is listed as "Client" in the crash log list.

**Comment by nicoonline** [comment]
sent by mail

**Comment by nicoonline** [comment]
Did you have a look ?

**Comment by dnarcese** [comment]
@nicoonline  We have added this to our backlog and can update you when we start investigating, thanks.

**Comment by nicoonline** [comment]
Any news ?
