### ISSUE TITLE
FXIOS-1500 ⁃ Simplify steps and workflows in Bitrise.yml

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/firefox-ios#7998]
For example when we run the tests workflows (run unit test -> smoketest) there is a slack and deploy step for each workflow, we would need only on at the end.
Using this issue also to try to reduce the bitrise.yml file by removing unnecessary/old/not used workflows.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2733)

**Comment by Dalvin12d** [comment]
Enhance

**Comment by isabelrios** [comment]
This is an ongoing task, for example with recent [PR](https://github.com/mozilla-mobile/firefox-ios/pull/8031) some old workflows were removed.
More improvements coming soon.
