### ISSUE TITLE
Password Autofill on Domain.com.Au

### ISSUE THREAD

**Issue by fowl2** [mozilla-mobile/firefox-ios#8003]
## Steps to reproduce
1. Log in to domain.com.AU, saving the password 
1. Log out
1. Attempt to log in

### Expected behavior
Logged in with saved password 

### Actual behavior
User/Password is auto filled but cleared when "log in" button is tapped. 

![image](https://user-images.githubusercontent.com/12844147/108447013-3fcc5400-72b3-11eb-9126-1db0c1660827.png)
![image](https://user-images.githubusercontent.com/12844147/108447032-478bf880-72b3-11eb-8b29-814480a49d2d.png)

### Device & build information
* Device: iPhone 12 A2403
* Build version: Firefox Daylight 31.0 (3537), iOS 14.5 beta 2 (18E5154f)
    1. Notes
This works in Safari (iOS) + iCloud Keychain

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2734)

**Comment by dnarcese** [comment]
Can we check if this reproduces on other sites as well?

**Comment by SimonBasca** [comment]
I was able to reproduce this issue on another sited (e.g bancamp.com). 
STR:
1. Go to bancamp.com 
2. Tap "Login" after the user and password were autofilled

Actual results:
- The user is not logged in and is prompted to enter user and password.

![Skype_Picture_2021_03_03T09_12_25_454Z](https://user-images.githubusercontent.com/32130829/109782410-886c0180-7c11-11eb-9f1d-4e17abe0a9ef.jpeg)

Note:
- After manually typing the username and password, the captcha is displayed and the user is able to login correclty. 
- Seems similar to https://github.com/mozilla-mobile/firefox-ios/issues/7764#issuecomment-773952856

**Comment by SimonBasca** [comment]
Some more reports of this issue also on https://app.clickup.com/login.
