### ISSUE TITLE
FXIOS-1510 ⁃ [XCUITests] testSetDefaultBrowser needs to be updated

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/firefox-ios#8022]
After recent changes the Default Browser card in main view is different. The Setting options is not there anymore, you have to click on Learn More and then go to Settings.

That changes should be reflected in the test to have it green again.
Link to the test: https://github.com/mozilla-mobile/firefox-ios/blob/main/XCUITests/SettingsTest.swift#L32

And the line where it fails: https://github.com/mozilla-mobile/firefox-ios/blob/main/XCUITests/SettingsTest.swift#L36

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1510)

**Comment by kaansariveli** [comment]
Hi,

This test assumes that Safari is the first option in the list but when i run the test i get this: 
![image](https://user-images.githubusercontent.com/17482092/110233958-1b25dc80-7f41-11eb-865e-e719f00533c6.png)
Is it because of the os version or the scheme (Fennec)?

**Comment by isabelrios** [comment]
FYI @SimonBasca This was fixed in a previous PR, the Learn More part, but we would need to check that comment above ^

**Comment by SimonBasca** [comment]
We should update and re-enable this test after https://github.com/mozilla-mobile/firefox-ios/issues/8595 is fixed
