### ISSUE TITLE
FXIOS-1512 ⁃ New Default Browser card is cut on iPhone SE 1st gen

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#8024]
## Steps to reproduce
1. Fresh install Firefox 32.0 on iPhone SE
2. Tap on"Learn more" 
### Expected behavior
- The card should fit the screen
### Actual behavior
- The default browser card is cut.
### Device & build information
* Device: iPhone SE 1st gen (14.1)
* Build version: 32.0 (3815)
### Notes
Attachments: 
![Default browser](https://user-images.githubusercontent.com/32130829/108867878-50a3ff00-75fe-11eb-8f77-aabdfe56a36a.jpeg)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1512)

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verified fix on v32.0 (3841).
