### ISSUE TITLE
FXIOS-1513 ⁃ Default Browser Onboarding Card gets themes mixed up

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#8025]
## Steps to reproduce
1. Clean install v32.0
2. From the hamburger menu, enable Night Mode
3. Tap on "Learn more" button on the Default Browser Onboarding Card
4. Dismiss the card by tapping the "X" button
5. From the hamburger menu, disable Night Mode
6. Tap on "Learn more" button on the Default Browser Onboarding Card
### Expected behavior
- The theme should be respected in the onboarding card.
### Actual behavior
- The theme should is mixed between light and dark
### Device & build information
* Device: iPhone Xr (14.4)
* Build version: 32.0 (3815)
### Notes
Attachments: 
![Picture_2021_02_23T16_02_36_760Z](https://user-images.githubusercontent.com/32130829/108870986-59e29b00-7601-11eb-84ba-189f8e10ff52.jpeg)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1513)

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verified fix on main 99a9e5e2a0
