### ISSUE TITLE
Crash after tapping on "Set as default browser" button from Settings

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#8026]
## Steps to reproduce
1. Upgrade from v31.0 to 32.0 
2. Tap on Settings -> Set as Default Browser
3. Return to Firefox via app switcher
### Expected behavior
- Firefox should not crash.
### Actual behavior
- After returning to Firefox, the app crashed.
### Device & build information
* Device: iPhone Xr (14.4)
* Build version: 32.0 (3815)
### Notes
- Before the app crashed, I noticed the "Syncing" spinning throttle in settings.
- The crash only occurred once and was unable to reproduce.
Attachments: 
[Client-2021-02-23-125324.ips.beta.zip](https://github.com/mozilla-mobile/firefox-ios/files/6030238/Client-2021-02-23-125324.ips.beta.zip)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2738)

**Comment by nbhasin2** [comment]
@SimonBasca I tried as well and couldn't reproduce, it might have been related to sync

**Comment by dnarcese** [comment]
After completing #7588, we can check if this is related to sync

**Comment by dnarcese** [comment]
Added a ticket for tracking # of tabs closed #8045

**Comment by lmarceau** [comment]
Since only `data-sync-user` has commented on the issue after the `Stalebot` GitHub action (which triggered the removal of the `stale` label) I’ll close this issue for now. Please let us know if you think this issue needs to be reopened, we'll gladly do so. Thank you!
