### ISSUE TITLE
Crash after tapping "Close all tabs"

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#8032]
## Steps to reproduce
1. Have over 150 tabs opened
2. Open Chronological tabs 
3. Tap "Close all tabs"
### Expected behavior
- All tabs should be closed.
### Actual behavior
- After tapping the "close tabs" button, Firefox hangs for a few seconds and after it crashes.
### Device & build information
* Device: iPhone Xr (14.4)
* Build version: 32.0 (3823)
### Note
- I've reproduced the issue only once.
Attachments: 
[Client-2021-02-24-142520.ips.beta.zip](https://github.com/mozilla-mobile/firefox-ios/files/6035977/Client-2021-02-24-142520.ips.beta.zip)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2739)

**Comment by dnarcese** [comment]
Added a ticket for tracking # of tabs closed #8045

**Comment by lmarceau** [comment]
Since only `data-sync-user` has commented on the issue after the `Stalebot` GitHub action (which triggered the removal of the `stale` label) I’ll close this issue for now. Please let us know if you think this issue needs to be reopened, we'll gladly do so. Thank you!
