### ISSUE TITLE
QR scan camera won't open if the app was backgrounded wsith an app menu open

### ISSUE THREAD

**Issue by csuciu** [mozilla-mobile/firefox-ios#8033]
iPhone 12 (iOS 14.4)
v32.0 (3823)

1. Open a web page.
2. Open the three dot menu.
3. Background the app while the menu is still open.
4. Long press on the FF home screen icon and select"Scan QR Code"

Expected: The scan QR code camera opens.

Actual: The camera does not open. Instead, the app is foregrounded with the menu still open.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2740)

**Comment by lmarceau** [comment]
Since only `data-sync-user` has commented on the issue after the `Stalebot` GitHub action (which triggered the removal of the `stale` label) I’ll close this issue for now. Please let us know if you think this issue needs to be reopened, we'll gladly do so. Thank you!
