### ISSUE TITLE
Add # of tabs closed to "close all tabs" tracking

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#8045]
**Vision**

As a PM, I want to know how many tabs users are closing when they use the "close all tabs" button" so that I can make the experience better.

**Acceptance Criteria**

Tracking already exists for clicking the close all tabs button. 
Add an 'extras' field that includes how many tabs were closed.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2743)

**Comment by lmarceau** [comment]
Since only `data-sync-user` has commented on the issue after the `Stalebot` GitHub action (which triggered the removal of the `stale` label) I’ll close this issue for now. Please let us know if you think this issue needs to be reopened, we'll gladly do so. Thank you!
