### ISSUE TITLE
Find in page does not scroll

### ISSUE THREAD

**Issue by katrikm** [mozilla-mobile/firefox-ios#8052]
## Steps to reproduce
Open web page https://www.notebookcheck.net/Mobile-Processors-Benchmark-List.2436.0.html
Use Find in page function and try to find: j3355
One result should be found.

### Expected behavior
Browser scrolls to found text and highlights it

### Actual behavior
Browser does not scroll to found text

### Device & build information
* Device: iPad mini 5
* Build version: Firefox Daylight 32.0 (3841)
### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2745)

**Comment by SimonBasca** [comment]
Confirming that this is and issue on the mentioned sited and it's also reproducible on iPhone. So far the issue is only reproducible on the mentioned site. 

In Firefox, the results appears highlighted but the page does not scroll to the result.
In Safari, the results is correctly displayed and the page scrolls to the result.

**Comment by ksy36** [comment]
We've got three more reports with the same issue:

https://github.com/webcompat/web-bugs/issues/70913 - Searching comments on youtube.com (For example https://m.youtube.com/watch?v=6FRzmTY7wrk)

https://github.com/webcompat/web-bugs/issues/71880 - Lodash documentation (https://lodash.com/docs)

https://github.com/webcompat/web-bugs/issues/71161 - archiveofourown.org

**Comment by lmarceau** [comment]
Since only `data-sync-user` has commented on the issue after the `Stalebot` GitHub action (which triggered the removal of the `stale` label) I’ll close this issue for now. Please let us know if you think this issue needs to be reopened, we'll gladly do so. Thank you!
