### ISSUE TITLE
Firefox no longer appearing in share menu

### ISSUE THREAD

**Issue by nixoye** [mozilla-mobile/firefox-ios#8054]
I used to use the Send to Device option from the share menu regardless of what app I'm on but Firefox is no longer appearing in the share menu. Using the latest ios version on an iphone 10s

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2747)

**Comment by SimonBasca** [comment]
@NIXOYE could you please provide an example of an app where you are experiencing this issue?

**Comment by NIXOYE** [comment]
Every app. Firefox is no longer appearing in the share menu and clicking More to try and add it doesn’t work it doesn’t appear at all

**Comment by n-thumann** [comment]
I have the same issue, running iOS 14.4 on iPhone XR with Firefox 32.0.
The only situation I've found to consistently reproduce this is trying to share [this page](https://www.daenischesbettenlager.de/sofa-teestrup-2-sitzer-recamiere-hellgrau) in Safari. I have absolutely no idea what's so special about this one, but in other apps or on other websites I wasn't able to reproduce this behavior.
When I open this site in Safari and open the Share Sheet, Firefox is not there. When I dismiss it and open it up again, it's there as expected. When I reload the page or force quit Safari and open the Share Sheet again, Firefox is again not there. Only after opening the Share Sheet a second time, it's there. ✌️
I also noticed that this affects other apps too: Twitter, Signal, Snapchat, etc. are also only visible after opening the Share Sheet for a second time, so it's probably iOS's fault.

**Comment by SimonBasca** [comment]
I was unable to reproduce this issue with Firefox 32.0 (3841) with iPhone Xr (14.4). On my side, the Firefox extension is appearing correctly in other apps when I tap the "Share" button.

**Comment by nhoizey** [comment]
I have the same issue on an iPhone Xs with iOS 14.4.

Firefox disappeared from the share sheet a few days ago, came back 2 days later, and is now gone again.

I use Firefox as my default browser, and I'm connected to my sync account. I use the share sheet a lot everyday to send links to a new tab on another device.

**Comment by n-thumann** [comment]
I was also to reproduce this consistently on [this page](https://support.google.com/youtube#topic=9257498).
See [this video](https://user-images.githubusercontent.com/46975855/109806552-1e5d5780-7c25-11eb-97c9-6030e668a6b9.mp4) for a demo :)

**Comment by dnarcese** [comment]
Let's look into this and see if there is anything we can fix, but it may just be an iOS bug.

**Comment by lmarceau** [comment]
Since only `data-sync-user` has commented on the issue after the `Stalebot` GitHub action (which triggered the removal of the `stale` label) I’ll close this issue for now. Please let us know if you think this issue needs to be reopened, we'll gladly do so. Thank you!
