### ISSUE TITLE
FXIOS-1533 ⁃ App crashed when open any website

### ISSUE THREAD

**Issue by trongnhan68** [mozilla-mobile/firefox-ios#8058]
## Steps to reproduce
Open google/facebook or any website
<img width="778" alt="Screen Shot 2021-03-01 at 11 56 54" src="https://user-images.githubusercontent.com/9714340/109487524-e2a47f80-7ab6-11eb-8c16-d4e25e76c35c.png">

### Expected behavior
no crash

### Actual behavior
crash

### Device & build information
* Device: Iphone 11 - iOS 14.2
* Build version: commit 506fcc1ff on master branch.
### Notes
Attachments: 
<img width="778" alt="Screen Shot 2021-03-01 at 11 56 54" src="https://user-images.githubusercontent.com/9714340/109487626-0c5da680-7ab7-11eb-95a8-0263adfbf35b.png">

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1533)

**Comment by isabelrios** [comment]
I think this is related to this [PR](https://github.com/mozilla-mobile/firefox-ios/pull/7858)

@trongnhan68 could you please try to update to latest iOS 14.4? Thanks and sorry for the inconvenience...

**Comment by SimonBasca** [comment]
Issue reproducible on sim iPhone 11 (14.2) on main a907073f5d4. 
<img width="939" alt="image" src="https://user-images.githubusercontent.com/32130829/109515153-707c6c80-7aaf-11eb-96cd-d7e4ee11556e.png">

**Comment by trongnhan68** [comment]
Hi @isabelrios , 
Thanks for your response, 
Follow comment of @SimonBasca , and my reproduce in ios 12. App running well.
But in iOS 14.1/  14.2, crash was happened. 

Could you please ask him double check this issue? Because I think we could missed some bugs in others iOS version.

Thanks,

**Comment by isabelrios** [comment]
Yeah, Simon checked on iOS 14.2. If the cause is the one I suspect in that PR, 14.0, 14.1 and 14.2 will be affected. With iOS 14.4 this issue is not happening.
