### ISSUE TITLE
FXIOS-1536 ⁃ Trouble debugging since v32.x

### ISSUE THREAD

**Issue by gutley** [mozilla-mobile/firefox-ios#8062]
This is related to https://github.com/mozilla-mobile/firefox-ios/discussions/8061, but is different and more problematic

Since I updated my fork of Firefox from being based on v31.x (Xcode 12.1) to any branch that supports Xcode 12.4 (v32.x and main) then in some parts of the code has become impossible to evaluate anything in the debugger. e.g something as simple as "po someVariable". When I do that I get:

expression produced error: error: virtual filesystem overlay file '/Users/distiller/Library/Developer/Xcode/DerivedData/MozillaAppServices-bipzktbxzgyaszczooummqayiqbw/Build/Intermediates.noindex/MozillaAppServices.build/all-product-headers.yaml' not found

So it looks like the non-existent build info for MozillaAppServices stops the debugger dead.

I've not yet figured out why this only affects some code and not everywhere, but it seems to affect my own stuff, not the app or the 'normal' embedded frameworks.

I guess the entire build shouldn't have any references to hard-coded paths on other people's Macs ?

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1536)

**Comment by gutley** [comment]
Some more info.

Most of my code exists in a framework as part of the client project (similar to the Shared and Sync frameworks). If the first breakpoint to be triggered in the app is in my code I get the 'virtual filesystem overlay file ' error in the debugger and can't do any 'po whatever' for code in my framework. Breakpoints in Client, Shared and Sync work as expected.

If a different breakpoint triggers elsewhere in the Firefox code first (Shared, Client etc), then when my code's breakpoints trigger 'po' works as expected.

The only main difference between my framework and Shared/Sync is that I wasn't using an Obj-C bridging header. After adding an empty one things work more consistently. e.g in this code:

            URLSession.shared.dataTask(with: request) { (data, response, error) in
                let httpResponse = response as? HTTPURLResponse
                let statusCode = httpResponse?.statusCode ?? 0
......
     }

If I break at the let statusCode = ... line and 'po httpResponse' then this happens the first time:

Printing description of httpResponse:
expression produced error: error: /var/folders/j7/7h6ptzh137q458q5y9ypl9g40000gp/T/expr172-89151c..swift:1:66: error: cannot find 'invalid' in scope
Swift._DebuggerSupport.stringForPrintObject(Swift.UnsafePointer<<invalid>>(bitPattern: 0x114d67b80)!.pointee)
                                                                 ^~~~~~~

error: /var/folders/j7/7h6ptzh137q458q5y9ypl9g40000gp/T/expr172-89151c..swift:1:64: error: adjacent operators are in non-associative precedence group 'BitwiseShiftPrecedence'
Swift._DebuggerSupport.stringForPrintObject(Swift.UnsafePointer<<invalid>>(bitPattern: 0x114d67b80)!.pointee)

But repeating the command works correctly.

So I've settled for this for now as its better than the original problem, but it would be nice for the build to not have any requirement on '/Users/distiller/... MozillaAppServices.build/all-product-headers.yaml' being expected to be accessible.

**Comment by nbhasin2** [comment]
Hi @gutley in Firefox v32.x we made changes to the way `MozillaAppServices.framework` is linked. Now everything should be dynamically linked. 

I would suggest clearing derived data and doing a fresh clone of Firefox iOS (main) and running `./bootstrap.sh`.

Let us know if this fixes it or requires more investigation.

**Comment by dnarcese** [comment]
We can re-open this issue if the problem still exists.
