### ISSUE TITLE
FXIOS-1554 ⁃ input type=date fires a change event before user can select a date on iPad iOS 14.4

### ISSUE THREAD

**Issue by bbrown-spsu** [mozilla-mobile/firefox-ios#8083]
## Steps to reproduce
Use this page: https://jsfiddle.net/e8ngLvmp/ or build a page with input type=date and no value attribute: `<input type="date" name="date1" id="date1">`
Hook the change event:
```
document.getElementById("date1").addEventListener("change",function() {
	alert('Change event signaled; value='+document.getElementById("date1").value);
});
```
Load the page using an iPad running iOS 14.4 and Firefox for iOS 32 and touch or tap the date input element.

### Expected behavior
The alert is shown after the user has selected a date using the date picker and the alert displays the selected date.
### Actual behavior
The change event is fired as soon as the input field is tapped, the alert displays the current date, and the date picker is not shown until the alert is dismissed.  Regardless of the date selected in the date picker, the input element shows the current date.
### Device & build information
* Device: iPad (7th generation) Model Number MW772LL/A  running iOS 14.4
* Build version: Firefox Daylight 32.0 (3841)
### Notes
This failure occurs only in the case that the case where the input element has no value attribute.  The date picker is focused on the current date, which is the only reasonable thing to do, but the current date is also set as a value on the input element and the change event signaled.  _That_ is the error.

There is a working example here: https://jsfiddle.net/e8ngLvmp/  It works as expected in Firefox on Win10 and fails as described on the iPad.  <strike>This failure seems to appear only with an iPad, and not with iPhone, although I rely on the report of another for that information.</strike>  Now occurs with at least some iPhones.

I conjecture that this is actually an iOS problem, but a mere mortal has no way to report it to Apple.  Perhaps you can confirm my conjecture and get Apple's attention, or correct Firefox if that's where the error lies.  Thanks!
Attachments:

**Comment by dnarcese** [comment]
Closing as a webkit issue
