### ISSUE TITLE
FXIOS-1562 ⁃ DownloadFilesTests.testDownloadFilesTest - SmokeXCUITest

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/firefox-ios#8094]
### Bitrise Test Run:
Provide a Bitrise test run report link here showcasing the problem
https://addons-testing.bitrise.io/builds/68b37347118aba83/testreport/82ee50ad-a9f9-4a92-8f9f-91bc733fbba5/testsuite/0/testcases?status=failed

### Stacktrace:
`file:///Users/vagrant/git/XCUITests/BaseTestCase.swift:CharacterRangeLen=0&EndingLineNumber=126&StartingLineNumber=126 - Expect predicate exists != true for ProgressIndicator`
### Build:
Main: 45c08250616f06aea4304c8ce660cbcf67df474f
March 8th

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2760)

**Comment by SimonBasca** [comment]
Failed on 31 March https://app.bitrise.io/build/c3e630e57a23ee57#?tab=log.

**Comment by isabelrios** [comment]
This test has not failed lately. Closing for now
