### ISSUE TITLE
FXIOS-1565 ⁃ Don't show engine logo if a URL is displayed in the URL bar

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#8099]
## Steps to reproduce
1. Go to wikipedia.org
2. Tap on the URL bar
### Expected behavior
When you are on a webpage and the URL bar is in the search bar; the search provider icon is not shown as mentioned in #6917
### Actual behavior
- The search engine logo should not be displayed if a URL is displayed in the search bar.
### Device & build information
* Device: iPhone 12 (14.4)
* Build version: main 99a9e5e2a0
### Notes
Attachments: 
<img width="432" alt="image" src="https://user-images.githubusercontent.com/32130829/110469457-5875a000-80e2-11eb-9516-3d206021230b.png">

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1565)

**Comment by dnarcese** [comment]
@brampitoyo Can you clarify what the behaviour here should be?

**Comment by brampitoyo** [comment]
@dnarcese @SimonBasca This is an intended behaviour.

Showing the search engine logo in the address bar every time it’s selected will help people realise that they can use this space for all their searches.

For comparison, here’s what things look like on Fenix:

<img width="360" src="https://user-images.githubusercontent.com/51007/111105819-aabe3180-85b8-11eb-8245-0527d31df870.png">

**Comment by SimonBasca** [comment]
Thanks for clarifying @brampitoyo.

**Comment by wachabaha** [comment]
****_[]()_****

**Comment by wachabaha** [comment]
___[![image](https://user-images.githubusercontent.com/69654154/111134243-b5a6a100-857b-11eb-984d-a46dce8e59f1.jpeg)](https://github.com/mozilla-mobile/firefox-ios/issues/8099#issuecomment-799275660)___

**Comment by wachabaha** [comment]
_[](https://github.com/mozilla-mobile/firefox-ios/issues/8099#issuecomment-799275660)_~~`****

**Comment by wachabaha** [comment]
__

**Comment by wachabaha** [comment]
https://github.com/mozilla-mobile/firefox-ios/issues/8099#issuecomment-799278327[](https://github.com/mozilla-mobile/firefox-ios/issues/8099#issuecomment-799278327)

**Comment by wachabaha** [comment]
Uñ
