### ISSUE TITLE
FXIOS-1570 ⁃ Switch Your Default Browser onboarding card is shown on iOS < 14

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/firefox-ios#8106]
Reported in #mobile channel. 

**Summary**

Default browser onboarding card is being shown to users who are not eligible to set Firefox as their default. Card should only be shown to users on iOS 14+ who have not clicked the default browser option on the new tab page

**Preconditions**

* Be on an iOS version below 14

Steps to Reproduce

1. Download Firefox
2. Open the app 3 separate times

**Expected Behaviour**

App opens as usual. No default browser onboarding card is displayed.

**Actual Behaviour**

Onboarding card is shown that informs users they can set Firefox as their default browser

![Image from iOS](https://user-images.githubusercontent.com/1897507/110652622-d4dcb180-81bc-11eb-9ec9-b5e64252718a.png)
![Image from iOS (1)](https://user-images.githubusercontent.com/1897507/110652655-db6b2900-81bc-11eb-9756-ce8f686541cb.png)

**Device & build information**

* Device: iPhone SE 12.3.1

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1570)

**Comment by isabelrios** [comment]
@SimonBasca could you please try to reproduce and give some steps for this issue? Thanks! 🙏

**Comment by data-sync-user** [comment]
➤ Nishant Bhasin commented:

[~sbasca@mozilla.com] I have uploaded v32.1 (3937) to AppStore (Beta + Prod) which fixes this issue. Could you please take a look at it and let me know if this build is good to push out to users?

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on **`Firefox v32.1 (3937)`** using an iPhone 10 (iOS 13.4)
