### ISSUE TITLE
Synchronisation between Mobile and Desktop Apps

### ISSUE THREAD

**Issue by dnet890** [mozilla-mobile/firefox-ios#8108]
Hi
I found your browser is quite good. I have a question: I know bookmarks between Firefox on Desktop can be synced on iOS and Android. Is there any possibility to sync recent browsing history as well?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2762)

**Comment by dnarcese** [comment]
Hi @dtantono, in your Firefox Sync settings, do you have History selected? We do currently have the functionality to sync History, but it is optional and needs to be selected.

**Comment by esperecyan** [comment]
My iPhone also does not sync history.
Bookmarks, open tabs, and login information are synced, and the ability to send tabs to another device works fine.
The history on devices other than iPhone shows up in my iPhone history, but the history I view in Firefox on iPhone does not sync to Firefox on another device.

### Device & build information
* Device: iPhone 6s Plus / iPhone XS Max / iOS 14.4.2
* Build version: Firefox Daylight 33.0 (4119)

#### Desktop
* Window 10 2004
* Firefox 87.0

**Comment by esperecyan** [comment]
The problem of history not syncing from Firefox on iPhone to Firefox on Windows was fixed before I knew it.

### Device & build information
* Device: iPhone XS Max / iOS 16.1.2
* Product Info: Firefox 107.3 (23248)

#### Desktop
* Window 10 22H2
* Firefox 108.0

**Comment by esperecyan** [comment]
The problem appeared to have recurred, but Firefox on the iPhone was in a state of session expiration for web services ( https://github.com/mozilla-mobile/firefox-ios/issues/12279 / https://github.com/mozilla-mobile/firefox-ios/issues/12034 / https://github.com/mozilla-mobile/firefox-ios/issues/12028 ), which was repaired after a forced restart.

**Comment by esperecyan** [comment]
This problem seems to have reappeared in Firefox 108.1 (24234) on iOS.
History will not sync unless I sync manually.
