### ISSUE TITLE
FXIOS-1572 ⁃ Default Browser onboarding should only show for eligible users

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#8109]
**Summary**

Default browser onboarding card is being shown to users who are not eligible to set Firefox as their default. Card should only be shown to users on iOS 14+ who have not clicked the default browser option on the new tab page

**Preconditions**

* Be on an iOS version below 14

Steps to Reproduce

1. Download Firefox
2. Open the app 3 separate times

**Actual Behaviour**

Onboarding card is shown that informs users they can set Firefox as their default browser

**Expected Behaviour**

App opens as usual. No default browser onboarding card is displayed.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1572)

**Comment by dnarcese** [comment]
duplicate of #8106
