### ISSUE TITLE
[XCUITests] Add test to check the onboarding car showing up when it is expected

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/firefox-ios#8118]
This is an important feature since it will help to switch to firefox as default browser. It would be nice to have a test to cover this.

The onboarding card should appear the third time the app is launched.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2763)

**Comment by lmarceau** [comment]
Since only `data-sync-user` has commented on the issue after the `Stalebot` GitHub action (which triggered the removal of the `stale` label) I’ll close this issue for now. Please let us know if you think this issue needs to be reopened, we'll gladly do so. Thank you!
