### ISSUE TITLE
FXIOS-1577 ⁃ [Bug] Difficult to perform a new QR code scan

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/firefox-ios#8120]
## Steps to reproduce
1. Tap the URL bar and afterwards tap the "QR scan" button
2. After the scan is done and the website is properly loaded tap the the URL bar
3. Tap again the "QR scan" button

### Expected behavior
Step 3: The user should be able to scan again a QR code

### Actual behavior
Step 3: Tapping the  "QR scan" button actually opens the text (link) selection toolbar
You need to tap a couple of times the  "QR scan" button to be able to perform a new scan (the text (link) selection toolbar appears and disappears after each tap of the   "QR scan" button)

### Device & build information
* Device: iPhone 10 (iOS 13.4)
* Build version: Firefox v32.1 (3937)

### Notes
► Video 
![IMG-0263](https://user-images.githubusercontent.com/51314259/110773395-6142af00-8265-11eb-9bf2-cf0d67253083.gif)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1577)

**Comment by dnarcese** [comment]
I wasn't able to reproduce this on iOS 14. @AndiAJ can you investigate if this is ios 13 specific?

**Comment by AndiAJ** [comment]
I've also checked this matter on `Firefox Daylight 32.0 (3841)` using a iPhone 6s (iOS 14.4) and wasn't able to repro it.
I don't have any other devices, and would kindly ask @csuciu or @SimonBasca to check if it's iOS 13 specific ☺️

**Comment by SimonBasca** [comment]
This issue is no longer reproducible on iOS 13.x devices.
