### ISSUE TITLE
[Bug] Images are not reloaded after re-enabling "Block images"

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/firefox-ios#8121]
## Steps to reproduce
1. Navigate to soundcloud.com
2. Tap to play any of the featured songs
3. Enabled "Block images" from the ☰ button
4. Tap back
5. Disable "Block images" from the ☰ button

### Expected behavior
Step 5: The images of the featured songs should be properly displayed

### Actual behavior
Step 5: The images of the featured songs aren't properly displayed
A placeholder is displayed instead

### Device & build information
* Device: iPhone 10 (iOS 13.4)
* Build version: Firefox v32.1 (3937)

### Notes
► Video 
![IMG-0264](https://user-images.githubusercontent.com/51314259/110776100-5a696b80-8268-11eb-896f-f2250c88fb5e.gif)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2765)

**Comment by lmarceau** [comment]
Since only `data-sync-user` has commented on the issue after the `Stalebot` GitHub action (which triggered the removal of the `stale` label) I’ll close this issue for now. Please let us know if you think this issue needs to be reopened, we'll gladly do so. Thank you!
