### ISSUE TITLE
[Bug] Reader mode color choice isn't saved after either changing the Font type or the Font size

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/firefox-ios#8123]
## Prerequisites
Device Appearance Setting should be set to Dark
Firefox Theme should be set to use System Light/Dark Mode

## Steps to reproduce
1. Navigate to a website that supports reader mode
2. Enable reader mode (will have black color)
3. Chance the color choice to white or sepia
4. Swipe up and down the page content
5. Tap the appearance button
6. You can either change the Font type or the Font size

### Expected behavior
The website's color should remain as set in step 3

### Actual behavior
The website's color is changed automatically back to black (step 2)

### Device & build information
* Device: iPhone 10 (iOS 13.4)
* Build version: Firefox v32.1 (3937)

### Notes
► Video 
![IMG-0267](https://user-images.githubusercontent.com/51314259/110780926-edf16b00-826d-11eb-9681-3fa5a1b97c63.gif)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2766)

**Comment by lmarceau** [comment]
Since only `data-sync-user` has commented on the issue after the `Stalebot` GitHub action (which triggered the removal of the `stale` label) I’ll close this issue for now. Please let us know if you think this issue needs to be reopened, we'll gladly do so. Thank you!
