### ISSUE TITLE
Default browser onboarding card showing for existing users

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#8129]
**Steps to reproduce**
1. Open Firefox (may need to do this 3 times?)

**Actual Behaviour**
Default browser onboarding card is displayed

**Expected behaviour**
Firefox opens as usual. Default browser onboarding card should show on the 3rd run for new users

**Device Info**

* iPhone 11
* iOS 14.4
* FF v32

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2769)

**Comment by AaronMT** [comment]
For a fresh install of 32.1, I see the card after 3 browser launches.

**Comment by nbhasin2** [comment]
Hi @AaronMT, thanks for taking this on, what build number you are testing with? 
I am on Firefox Beta 3961 and only see the card on 3rd session

**Comment by AaronMT** [comment]
> I am on Firefox Beta 3961 and only see the card on 3rd session

Exact same build.
