### ISSUE TITLE
FXIOS-1585 ⁃ Estimate effort involved in disabling our Leanplum integration

### ISSUE THREAD

**Issue by krupa-raj** [mozilla-mobile/firefox-ios#8131]
We are looking for an assessment of how leanplum is integrated into iOS and the effort it would take to turn it all off. Once the estimates are in I will file any necessary follow up issues. Thanks!

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2770)

**Comment by nbhasin2** [comment]
Work just to remove leanplum would be a 3 pointer 
With a follow-on ticket of 2 points to make sure nothing is broken and we test our changes. 

Note: This does not include estimation for what service or component leanplum will be replaced with.
