### ISSUE TITLE
FXIOS-1587 ⁃ Close All Option to close all tabs/windows at once

### ISSUE THREAD

**Issue by DarkRick01** [mozilla-mobile/firefox-ios#8136]
### Why/User Benefit/User Problem

As a user I would like to close all tabs at once because closing one by one is really tedious. Also it gets to the point that I have hundreds of tabs open and I want an easy way to get rid of them all.

### Acceptance Criteria (how do I know when I’m done?)

Once there is a button which functionality is to close all tabs at once

### Not included

Currently, there is no button to close all tabs at once.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1587)

**Comment by dnarcese** [comment]
@DarkRick01 hello, in the tabs tray, there is a trash can button that allows you to close all of your tabs! Let me know if that functionality is what you are looking for.
