### ISSUE TITLE
FXIOS-1591 ⁃ Bug report

### ISSUE THREAD

**Issue by Flyboy95** [mozilla-mobile/firefox-ios#8142]
### Device & build information
* Device: ?
* Build version: ?
### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1591)

**Comment by wachabaha** [comment]
https://github.com/mozilla-mobile/firefox-ios/issues/8142

**Comment by wachabaha** [comment]
> ## Steps to reproduce
> 
> ### Expected behavior
> 
> ### Actual behavior
> 
> ### Device & build information
> * Device: ?
> * Build version: ?
> ### Notes
> Attachments:
> 
> ┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1591)
>

**Comment by wachabaha** [comment]
- **_[![image](https://user-@**
**images.githubusercontent.com/69654154/111160090-0f1dc880-859a-11eb-91e0-3d1e675c3e5a.jpeg)]()_**
