### ISSUE TITLE
FXIOS-1600 ⁃ merge

### ISSUE THREAD

**Issue by Dalvin12d** [mozilla-mobile/firefox-ios#8159]
Y'all are amazing

__Originally posted by @Dalvin12d in https://github.com/firstcontributions/first-contributions

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1600)

**Comment by Dalvin12d** [comment]
> Y'all are amazing
> 
> __Originally posted by @Dalvin12d in https://github.com/firstcontributions/first-contributions/issues/37501__

**Comment by andjeraj** [comment]
- [ ] -

**Comment by andjeraj** [comment]
- [ ] -
