### ISSUE TITLE
Configure CI to add a build secret for NIMBUS_URL

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#8162]
Details in SDK-211

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2779)

**Comment by lmarceau** [comment]
Since only `data-sync-user` has commented on the issue after the `Stalebot` GitHub action (which triggered the removal of the `stale` label) I’ll close this issue for now. Please let us know if you think this issue needs to be reopened, we'll gladly do so. Thank you!
