### ISSUE TITLE
Get build secret for NIMBUS_URL into NimbusRemoteSettings

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#8163]
See SDK-212 for details

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2780)

**Comment by data-sync-user** [comment]
➤ James Hugman commented:

Fenix is using https://firefox.settings.services.mozilla.com/

I'd also like to be able to override that for local development with:

nimbus.remote-settings.url=https://settings.stage.mozaws.net

**Comment by lmarceau** [comment]
Since only `data-sync-user` has commented on the issue after the `Stalebot` GitHub action (which triggered the removal of the `stale` label) I’ll close this issue for now. Please let us know if you think this issue needs to be reopened, we'll gladly do so. Thank you!
