### ISSUE TITLE
FXIOS-1614 ⁃ Error in the Mobile App

### ISSUE THREAD

**Issue by Rusira1234** [mozilla-mobile/firefox-ios#8180]
Sometimes the Mozila FireFox account gets stucked :(

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2788)

**Comment by dnarcese** [comment]
@Rusira1234 can you provide more details about when it is getting stuck? And maybe some steps to reproduce the issue

**Comment by data-sync-user** [comment]
➤ Daniela Arcese commented:

Closing for now until more info is provided.
