### ISSUE TITLE
Integrate Phone/Tablet search codes for Bing

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#8182]
In order to evaluate the revenue opportunity presented by iPad, we should integrate independent iPad/tablet specific search codes such that we can source revenue reporting by device type from our search partners.

Currently, we receive the greatest detail of reporting from Bing. It is recommended that we start with Bing codes.

These codes will need to be sourced from the partner. Once they are received, Product work can begin to integrate these device specific codes.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2789)

**Comment by lmarceau** [comment]
Since only `data-sync-user` has commented on the issue after the `Stalebot` GitHub action (which triggered the removal of the `stale` label) I’ll close this issue for now. Please let us know if you think this issue needs to be reopened, we'll gladly do so. Thank you!
