### ISSUE TITLE
FXIOS-1616 ⁃ [Crash] Firefox crashes after tapping on the "Share" button on a unloaded tab

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#8184]
## Preconditions:
1. Enable chronological tabs
2. Open tab 1) and go to Goolg.com
3. Open tab 2) and go to Twitter.com
4. Close Firefox from app switcher
## Steps to reproduce
1. Open Firefox
2. Open Chronological tabs
3. Swipe left on tab 1) with google.com
4. Tap on "More" 
5. Tap "Share"
### Actual behavior
- Firefox crashes.
### Device & build information
* Device: iPhone Xr (14.4)
* Build version: 33.0 (4031)
### Notes
- Note that after swiping on the tab, the first "Share" button from the swipe menu is not functional. After reloading the tab the button works fine and Firefox does not crash.
- This crash is also reproducible on v32.1
Attachments: 
 - [Video.mp4.zip](https://github.com/mozilla-mobile/firefox-ios/files/6183855/Video.mp4.zip)
- [Client-2021-03-22.ips.beta.zip](https://github.com/mozilla-mobile/firefox-ios/files/6183879/Client-2021-03-22.ips.beta.zip)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2790)

**Comment by kcome** [comment]
@SimonBasca I created a [PR](https://github.com/mozilla-mobile/firefox-ios/pull/9103) to fix this issue.

Reason for crash is unloaded tab doesn't have webView so the Print activity couldn't be added.

**Comment by kcome** [comment]
We can close this issue as version v38.0 released.

**Comment by SimonBasca** [comment]
Thanks for the contribution @kcome. This issue is fixed on v38.0 6157.
