### ISSUE TITLE
FXIOS-1617 ⁃ Search suggestion is all bold until done typing

### ISSUE THREAD

**Issue by dnarcese** [mozilla-mobile/firefox-ios#8186]
**STR**
1) type a search
2) observe suggestions

**Expected**
Only the suggestion part is bolded

**Actual**
Whole suggestion flashes bold while typing

https://user-images.githubusercontent.com/8919439/111697227-b05f8580-880b-11eb-8bd4-d3dc92d00b9e.mov

_Originally posted by @nbhasin2 in https://github.com/mozilla-mobile/firefox-ios/issues/8151#issuecomment-802297393_

**Comment by SimonBasca** [comment]
Verified fix on v34.0 (4722)
