### ISSUE TITLE
FXIOS-1621 ⁃ DesktopModeTestsIphone.testPrivateModeOffAlsoRemovesFromNormalMode() - XCUITest

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/firefox-ios#8189]
### Bitrise Test Run:
Provide a Bitrise test run report link here showcasing the problem
https://app.bitrise.io/build/ca083450367a60d1#?tab=log
### Stacktrace:
file:///Users/vagrant/git/XCUITests/DesktopModeTests.swift:CharacterRangeLen=0&EndingLineNumber=125&StartingLineNumber=125 - Failed to get matching snapshot: No matches found for Elements matching predicate '"Reload" IN identifiers' from inpu
### Build:
Main March 22nd

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2792)

**Comment by SimonBasca** [comment]
Closing as discussed on https://github.com/mozilla-mobile/firefox-ios/pull/8204#issuecomment-1103722276
