### ISSUE TITLE
FXIOS-1630 ⁃ Remove icons from the side of New Tab Page headings: Top Sites, Your Library and Pocket

### ISSUE THREAD

**Issue by brampitoyo** [mozilla-mobile/firefox-ios#8200]
Only includes removing the icons beside the headings, NOT adding the History tile.

[https://www.figma.com/file/lfgj15zbNkL9Pp4hdZGJgp/Proton-Mobile-UI?node-id=104%3A19556](https://www.figma.com/file/lfgj15zbNkL9Pp4hdZGJgp/Proton-Mobile-UI?node-id=104%3A19556)

cc @dnarcese

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2797)

**Comment by data-sync-user** [comment]
➤ Daniela Arcese commented:

Estimating 2 to make sure those icons aren't used anywhere else in the app.

**Comment by data-sync-user** [comment]
➤ Nishant Bhasin commented:

[~gbuciu@mozilla.com] I believe I removed these in your PR while working on updating Firefox Home View shortcuts as part of moving sync view to tab tray

Do check to see if I missed anything but thought I'd let you know of the changes I made in your PR

https://github.com/mozilla-mobile/firefox-ios/pull/8298 ( https://github.com/mozilla-mobile/firefox-ios/pull/8298 )
