### ISSUE TITLE
FXIOS-1631 ⁃ Replace iPadOS Library toolbar icon with Bookmarks Menu

### ISSUE THREAD

**Issue by brampitoyo** [mozilla-mobile/firefox-ios#8202]
**Vision**

The library icon on the iPad toolbar is replaced with a bookmarks icon, which we assume is more valuable and recognizable to users. Additionally, this is important because it keeps us inline with desktop

**Background**

This toolbar icon, which is a Bookmark-with-line (we call it Bookmarks Menu), uses the same asset as the one used inside the Library Tray and Main Application Menu to indicate “Bookmarks” – the place.

It’s different from the Bookmark star icon that appears without a line underneath. This icon appears in the Page Actions menu and indicate the action “Add to Bookmark”, not the place.

**Acceptance Criteria**

* Your Library button is remove from toolbar on iPad
* Bookmarks button is added in its place
  * See [spec](https://www.figma.com/file/lfgj15zbNkL9Pp4hdZGJgp/Proton-Mobile-UI?node-id=339%3A39693) for button design
  * Clicking the bookmarks button will open to bookmarks within the library tray

https://www.figma.com/file/lfgj15zbNkL9Pp4hdZGJgp/Proton-Mobile-UI?node-id=339%3A39693

cc @dnarcese

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1631)

**Comment by SimonBasca** [comment]
Verified fix on v34.0 (4722)
