### ISSUE TITLE
[Intermitent] Crash when clearing a website’s data twice in quick succession  

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#8203]
## Steps to reproduce
1. Go to Settings -> Data Management -> Website Data
2. Filter to a website whose data you want to clear
3. Tap the ⛔️ button
4. Tap the “Delete” button -> There’s a brief delay before it disappears from the list.
5. Hit the ⛔️ and “Delete” buttons again
### Actual behavior
- Firefox crashes.
### Device & build information
* Device: iPhone Xr (14.4)
* Build version: 33.0 (4031)
### Notes
- Same issue from past builds #7031
## Attachments: 
- [Video.mp4.zip](https://github.com/mozilla-mobile/firefox-ios/files/6195869/Video.mp4.zip)
- [Client-2021-03-24-141246.ips.beta.zip](https://github.com/mozilla-mobile/firefox-ios/files/6197032/Client-2021-03-24-141246.ips.beta.zip)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2799)

**Comment by SimonBasca** [comment]
Note: I am reproducing the issue more easy after restarting the device and following the STR.

**Comment by lmarceau** [comment]
Since only `data-sync-user` has commented on the issue after the `Stalebot` GitHub action (which triggered the removal of the `stale` label) I’ll close this issue for now. Please let us know if you think this issue needs to be reopened, we'll gladly do so. Thank you!
