### ISSUE TITLE
FXIOS-1634 ⁃ New Tab Page stretch goal: recolour backgrounds

### ISSUE THREAD

**Issue by brampitoyo** [mozilla-mobile/firefox-ios#8206]
https://www.figma.com/file/WboC4Dn9iu9wie2GodfSAg/Post-MR1?node-id=631%3A27544

| Element | Theme | Current | Proposed |
| --- | --- | --- | --- |
| New Tab Page background | Light | `white` | `Light Grey 10` `#f9f9fb` |
|  | Dark | `#29282d` | `Dark Grey 60` `#2b2a33` |
| Shortcut Tile background | Light | `transparent` | `white` |
|  | Dark | `transparent` | `Dark Grey 30` `#42414d` |

<img width="850" alt="new-tab-page" src="https://user-images.githubusercontent.com/51007/117913618-d00bb980-b335-11eb-85dd-793bc460e4a4.png">

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1634)

**Comment by brampitoyo** [comment]
Corrected the Figma link and added a screenshot.

**Comment by SimonBasca** [comment]
Verified fix on main 70fdda04ee
