### ISSUE TITLE
FXIOS-1635 ⁃ New Tab Page stretch goal: change text styles and colours

### ISSUE THREAD

**Issue by brampitoyo** [mozilla-mobile/firefox-ios#8207]
Figma: https://www.figma.com/file/WboC4Dn9iu9wie2GodfSAg/Post-MR1?node-id=631%3A27544
## Text styles

| Element | Proposed |
| --- | --- |
| Headings | Title 3 [`UIFontTextStyleTitle3`](https://developer.apple.com/documentation/uikit/uifonttextstyle) || Headings | 
| Links to the side of headings (e.g. “More”) | Subheadline [`UIFontTextStyleSubheadline`](https://developer.apple.com/documentation/uikit/uifonttextstylesubheadline) |
| Pocket article text | Subheadline [`UIFontTextStyleSubheadline`](https://developer.apple.com/documentation/uikit/uifonttextstylesubheadline) |
| Shortcut tile labels | Caption 1 [`UIFontTextStyleCaption1`](https://developer.apple.com/documentation/uikit/uifonttextstylecaption1) |

## Colours

| Element | Theme | Proposed |
| --- | --- | --- |
| Text and headings (this also applies to Pocket) | Light | `Dark Grey 90` `#15141a` |
|  | Dark | `Light Grey 05` `#fbfbfe` |
| Links to the side of headings (e.g. “More” – this also applies to Pocket) | Light | `Blue 50` `#0060df` |
|  | Dark | `Blue 20` `#00ddff` |
| Pin icon | Light | `Dark Grey 05` `#5b5b67` | 
|  | Dark | `Light Grey 05` `#fbfbfe` |

<img width="850" alt="new-tab-page" src="https://user-images.githubusercontent.com/51007/117913736-00535800-b336-11eb-8aa3-87560887462b.png">

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1635)

**Comment by brampitoyo** [comment]
Corrected the Figma link and added a screenshot.

**Comment by SimonBasca** [comment]
Verified fix on main 70fdda04eeb4d06eac05a6b4eb12943cf3a06f9d. Text and colors have been changed according to design.
