### ISSUE TITLE
FXIOS-1636 ⁃ New Tab Page stretch goal: add shadow to shortcut tiles

### ISSUE THREAD

**Issue by brampitoyo** [mozilla-mobile/firefox-ios#8208]
Figma: https://www.figma.com/file/WboC4Dn9iu9wie2GodfSAg/Post-MR1?node-id=631%3A27544

| Element | Theme | Proposed |
| --- | --- | --- |
| Shortcut tile shadow | Light | `Drop shadow Radius: 6 pt, Offset: 0 pt 2 pt, rgba 0.23, 0.22, 0.27, 0.2` |
|  | Dark | `Drop shadow Radius: 6 pt, Offset: 0 pt 2 pt, rgba 0.11, 0.11, 0.13, 0.5` |

Inspect the `Tile` object using Figma to see full shadow values.

<img width="344" alt="Screen Shot 2021-05-12 at 3 34 40 PM" src="https://user-images.githubusercontent.com/51007/117914598-c84d1480-b337-11eb-99a9-ad9e4762d9ce.png"> <img width="352" alt="Screen Shot 2021-05-12 at 3 36 56 PM" src="https://user-images.githubusercontent.com/51007/117914681-ec105a80-b337-11eb-8ec7-83f8d3d824f7.png">

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1636)

**Comment by brampitoyo** [comment]
Corrected the Figma link and added a screenshot.

**Comment by SimonBasca** [comment]
Verified fix on main 70fdda0
