### ISSUE TITLE
FXIOS-1637 ⁃ New Tab Page stretch goal: reorder the position of History

### ISSUE THREAD

**Issue by brampitoyo** [mozilla-mobile/firefox-ios#8209]
Figma: https://www.figma.com/file/lfgj15zbNkL9Pp4hdZGJgp/Proton-Mobile-UI?node-id=631%3A27544

History used to be the last (4th) item on the list, taking the place of Synced Tabs. We’d like to reorder its position to be the 2nd item on the list.

The new order is (left to right):

- Bookmarks
- History
- Downloads
- Reading List

This mirrors the ordering in both the Library Tray, and the Main Application Menu.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1637)

**Comment by data-sync-user** [comment]
➤ Nishant Bhasin commented:

This should also be done.

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verified fix on main 70fdda0
