### ISSUE TITLE
FXIOS-1639 ⁃ New Tab Page stretch goal: Restyle and resize shortcut tiles

### ISSUE THREAD

**Issue by brampitoyo** [mozilla-mobile/firefox-ios#8210]
Figma: https://www.figma.com/file/WboC4Dn9iu9wie2GodfSAg/Post-MR1?node-id=631%3A27544

- Library shortcut tiles are currently sized and styled differently than all other shortcut tiles. Let’s make them identical.
- Shortcut tiles currently have content that fill the whole container. Let’s resize them so they’re smaller.

### Shape

| Element | Current | Proposed |
| --- | --- | --- |
| Library tiles | Oval | Rounded rect, border radius 8 with smooth corner |
| Shortcut tiles | Rounded rect, border radius 4 with smooth corner | Rounded rect, border radius 8 with smooth corner |

### Size of Content

| Element | Current | Proposed |
| --- | --- | --- |
| Library tiles content | 16×16px | 24×24px (same as all other icons within the app), centred in container |
| Shortcut tiles content | Fill container, no padding | 36×36px, centred in container, border radius 4 with smooth corner |

<img width="360" alt="Screen Shot 2021-05-12 at 3 28 01 PM" src="https://user-images.githubusercontent.com/51007/117914105-b74fd380-b336-11eb-95e5-6aeed6f9bcc6.png"> <img width="360" alt="Screen Shot 2021-05-12 at 3 27 36 PM" src="https://user-images.githubusercontent.com/51007/117914108-bae35a80-b336-11eb-92f2-f267b5143f7b.png">

### Background colour
All shortcut tiles, including Library ones, should have the same background colours. This is already addressed by #8206.

### Library icon colours

From left to right:

| Element | Proposed |
| --- | --- |
| Bookmarks | `Blue 40` `#0090ed` |
| History | `Violet 50` `#9059ff` |
| Downloads | `Green 60` `#2ac3a2` |
| Reading List | `Pink 40` `#ff4aa2` |

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1639)

**Comment by brampitoyo** [comment]
Corrected the Figma link and added screenshots.

**Comment by SimonBasca** [comment]
Verified fix on main 70fdda04ee
