### ISSUE TITLE
FXIOS-1638 ⁃ New Tab Page stretch goal: remove "See All" link from Your Library

### ISSUE THREAD

**Issue by brampitoyo** [mozilla-mobile/firefox-ios#8211]
Figma: https://www.figma.com/file/lfgj15zbNkL9Pp4hdZGJgp/Proton-Mobile-UI?node-id=631%3A27544

Previously, Your Library contains one extra item: History.

Now that History is visible in this section, it no longer makes sense to have a link to “See All”. Let’s remove it.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1638)

**Comment by data-sync-user** [comment]
➤ Nishant Bhasin commented:

This should already be done, please make sure we don't have it for iPad

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verified fix on main 70fdda0. There are no shortcuts for iPad on home screen.
