### ISSUE TITLE
FXIOS-1640 ⁃ New Tab Page stretch goal: rename and restyle Pocket

### ISSUE THREAD

**Issue by brampitoyo** [mozilla-mobile/firefox-ios#8212]
Figma: https://www.figma.com/file/WboC4Dn9iu9wie2GodfSAg/Post-MR1?node-id=631%3A27544

| Element | Current | Proposed |
| --- | --- | --- |
| Section name | Trending on Pocket | Recommended by Pocket |
| Heading and link style and colours | Custom `#ef4056` | Identical to other headings and links on the page |

We will look at restyling how Pocket content looks (sitename, heading, trending, etc.), a little later.

<img width="849" alt="Screen Shot 2021-05-12 at 3 33 00 PM" src="https://user-images.githubusercontent.com/51007/117914381-58d72500-b337-11eb-965f-279ae8509ee8.png">

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1640)

**Comment by brampitoyo** [comment]
Corrected the Figma link and added a screenshot.

**Comment by SimonBasca** [comment]
Found one issue related to this change: https://github.com/mozilla-mobile/firefox-ios/issues/8658
