### ISSUE TITLE
[Crash] Firefox crashed in background

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#8213]
## Steps to reproduce
1. Launch Firefox beta
2. Opened a new tab
3. Do a google search
4. Tap "Back" button to go to previous page
5. Background Firefox
6. Open Whats app
### Actual behavior
- "Firefox has crashed" dialog was displayed after opening Whats app. 
### Device & build information
* Device: iPhone Xr (14.4)
* Build version: 33.0 (4119)
### Notes
- This issue only happened once and was not able to reproduce again.
Attachments: 
[Client-2021-03-25-110441.ips.beta.zip](https://github.com/mozilla-mobile/firefox-ios/files/6204346/Client-2021-03-25-110441.ips.beta.zip)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2800)

**Comment by lmarceau** [comment]
Since only `data-sync-user` has commented on the issue after the `Stalebot` GitHub action (which triggered the removal of the `stale` label) I’ll close this issue for now. Please let us know if you think this issue needs to be reopened, we'll gladly do so. Thank you!
