### ISSUE TITLE
FXIOS-1642 ⁃ [XCUITests] Update the rest of the XCUITests in the Fennec_XCUITests test plan after latest changes in the app

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/firefox-ios#8214]
Tests for the Smoketest plan are already fixed, but we need to fix also all the tests for the full test plan after [PR ](https://github.com/mozilla-mobile/firefox-ios/commit/1c4cb34a6366e27cee8f2d31293f0793832db34e)landed.

Now the app starts with the URL Bar focused and that changes the way all tests start.
Using a new action in the FxScreenGraph would help to manage this by canceling the open url bar and going to homescreen so that test starts as before.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1642)

**Comment by isabelrios** [comment]
@AaronMT I'm afraid the sync int tests are also affected... :(

**Comment by SimonBasca** [comment]
https://github.com/mozilla-mobile/firefox-ios/pull/8299

**Comment by SimonBasca** [comment]
https://github.com/mozilla-mobile/firefox-ios/pull/8316
