### ISSUE TITLE
Send Nimbus details to Sentry for crash reporting

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#8220]
The applications crash reporting tool (Sentry, for example) should include the experiment enrollment information (ex: experiment id, branch)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2804)

**Comment by lmarceau** [comment]
Since only `data-sync-user` has commented on the issue after the `Stalebot` GitHub action (which triggered the removal of the `stale` label) I’ll close this issue for now. Please let us know if you think this issue needs to be reopened, we'll gladly do so. Thank you!
