### ISSUE TITLE
FXIOS-1648 ⁃ withoutMobilePrefix is Totally wrong!

### ISSUE THREAD

**Issue by gutley** [mozilla-mobile/firefox-ios#8227]
https://github.com/mozilla-mobile/firefox-ios/blob/1ed201be5724280a1bb7b98506decfac601d0de1/Client/Frontend/Browser/Tab.swift#L782

withoutMobilePrefix is not doing what it is meant to do at all. What it actually does is remove the first occurrence of "m." or "mobile." from the host

e.g 

    let url = URL(string: "http://www.plum.com")!.withoutMobilePrefix()

URL is now "http://www.plucom"

🤦‍♂️

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1648)

**Comment by gutley** [comment]
It should really be splitting the host by ".' and then finding the first element that matches "m" or "mobile".

But even then it needs to be careful to not to leave just a TLD behind. i.e you don't want
"mobile.co.uk" becoming "co.uk"

**Comment by boek** [comment]
We can probably use https://publicsuffix.org. It's distributed with the MPL so we should be fine including it.
