### ISSUE TITLE
FXIOS-1650 ⁃ Picture in Picture broken Firefox 33.0 for youtube in desktop mode

### ISSUE THREAD

**Issue by thomasmaurel** [mozilla-mobile/firefox-ios#8232]
## Steps to reproduce

picture in picture mode seems to be broken. If you watch a video from youtube in desktop mode then press the home button.

### Expected behavior

When watching a video and pressing the home button, Firefox used to switch to picture in picture and I could watch the video while doing something else.

### Actual behavior

Firefox just stop the video and it disapear instead of swithcing to picture in picture mode

### Device & build information
* Device: Iphone SE with IOS 14.4.1
* Build version: 33.0
### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1650)

**Comment by SimonBasca** [comment]
In my case the issue is also reproducible on Safari. I am inclined to say that this is an iOS issue. 
@thomasmaurel could you also check if the issue is reproducible in Safari?

**Comment by thomasmaurel** [comment]
@SimonBasca: Yes, I can reproduce the same issue on Safari but Picture in Picture mode is working fine on Chrome IOS.

**Comment by dnarcese** [comment]
@thomasmaurel which site isn't working for you? YouTube intentionally blocks PiP, but other sites should be working fine.

**Comment by thomasmaurel** [comment]
@dnarcese: It was youtube in desktop mode. This use to work fine with the previous version Firefox but it's not working anymore on 33.0. I've tried other websites and picture in picture mode seems to be working.
