### ISSUE TITLE
FXIOS-1653 ⁃ PhotonActionSheetTest.testShareOptionIsShownFromShortCut - SmokeTest

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/firefox-ios#8236]
### Bitrise Test Run:
Provide a Bitrise test run report link here showcasing the problem
https://app.bitrise.io/build/125ed6b80f4a28cc#?tab=log
### Stacktrace:
file:///Users/vagrant/git/XCUITests/PhotonActionSheetTest.swift:CharacterRangeLen=0&EndingLineNumber=54&StartingLineNumber=54 - Expect predicate exists == true for "Copy" Button
### Build:
Main March 26th

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1653)

**Comment by isabelrios** [comment]
I think in this test would be fixed by adding a timeout [here](https://github.com/mozilla-mobile/firefox-ios/blob/d10f4efa2a191e6d525dd1577439ba9fe0ddb468/XCUITests/PhotonActionSheetTest.swift#L48)

**Comment by SimonBasca** [comment]
Failed on March 31 https://app.bitrise.io/build/826e35d67767a3ec#?tab=log.

**Comment by AaronMT** [comment]
> Failed on March 31 https://app.bitrise.io/build/826e35d67767a3ec#?tab=log.

I suppose we should bump the wait time? (@SimonBasca can you take this?)
