### ISSUE TITLE
FXIOS-1654 ⁃ [Unit Test]TabManagerStoreTests.testPrivateTabsAreArchived 

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/firefox-ios#8237]
### Bitrise Test Run:
Provide a Bitrise test run report link here showcasing the problem
https://addons-testing.bitrise.io/builds/125ed6b80f4a28cc/testreport/a145e583-e3dd-4116-a1a9-a136be5b56cc/testsuite/2/testcases?status=failed
### Stacktrace:
file:///Users/vagrant/git/ClientTests/TabManagerStoreTests.swift:CharacterRangeLen=0&EndingLineNumber=57&StartingLineNumber=57 - XCTAssertEqual failed: ("3") is not equal to ("2")
### Build:
Main March 26th

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2807)

**Comment by SimonBasca** [comment]
Failed on March 31 https://app.bitrise.io/build/55120f7d9736193f#?tab=log.

**Comment by SimonBasca** [comment]
Failed on April 1st https://app.bitrise.io/build/0c62a514d07479b8#?tab=log

**Comment by electricRGB** [comment]
IS that a joke?

**Comment by isabelrios** [comment]
> IS that a joke? :P

@electricRGB Does not look like that ;) it failed again on a PR (not related) on April 5th:
https://addons-testing.bitrise.io/builds/173df12c4492c8b9/testreport/ace887b1-8955-4935-b36f-7b7582ff3509/testsuite/3/testcases?status=failed
`file:///Users/vagrant/git/ClientTests/TabManagerStoreTests.swift:CharacterRangeLen=0&EndingLineNumber=57&StartingLineNumber=57 - XCTAssertEqual failed: ("3") is not equal to ("2")`

Unit tests are not our area of expertise, if it keep failing and we don't find how to fix it easily, we will disable it

**Comment by isabelrios** [comment]
Failed again on April 8th: https://addons-testing.bitrise.io/builds/f5454f45ae7055e3/testreport/569c14ec-b927-4bbb-96c1-f72c0186e926/testsuite/5/testcases?status=failed

**Comment by isabelrios** [comment]
Failed on April 12th: https://app.bitrise.io/build/08c2579d0d278e83#?tab=log

**Comment by isabelrios** [comment]
Failed on April 13th on main: https://addons-testing.bitrise.io/builds/6fce886c8e6139ae/testreport/bbb93f18-c8c0-45fb-b467-ad9cdfed3bc6/testsuite/0/testcases?status=failed

**Comment by isabelrios** [comment]
@electricRGB @nbhasin2 this unit test is failing often, would you mind taking a look in case there is something happening I would not like to just disable it in case it is detecting something wrong... Thanks!

**Comment by nbhasin2** [comment]
@isabelrios I am going to take a look at this, for now as a trial I am re-running here https://app.bitrise.io/build/10c64c32316e3478#?tab=log

**Comment by isabelrios** [comment]
Failed on April 19th on main: https://app.bitrise.io/build/4da78ec0a420eb2d#?tab=log

**Comment by isabelrios** [comment]
Failed on May 6th on main: https://app.bitrise.io/build/eff7ab57c204c4b2#?tab=log

**Comment by isabelrios** [comment]
Failed on May 14th on main: https://app.bitrise.io/build/7e4847e8b2c6e30b#?tab=log

**Comment by SimonBasca** [comment]
Failed on May 27th on main : https://app.bitrise.io/build/d89ca8490a0951df#?tab=log.

**Comment by isabelrios** [comment]
These UITests are not running, closing until re-enabling them
