### ISSUE TITLE
FXIOS-1657 ⁃ DownloadFilesTests.downloadBLOBFile - SmokeTest

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/firefox-ios#8250]
### Bitrise Test Run:
Provide a Bitrise test run report link here showcasing the problem
https://addons-testing.bitrise.io/builds/144002f5ebfa468e/testreport/3a5c7cf1-93cb-47c8-b644-5bfb9366face/testsuite/0/testcases?status=failed
### Stacktrace:
file:///Users/vagrant/git/XCUITests/BaseTestCase.swift:CharacterRangeLen=0&EndingLineNumber=126&StartingLineNumber=126 - Expect predicate exists != true for ProgressIndicator
### Build:
CommonBuild-UItest-XCUISmoketest March 30th

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1657)

**Comment by AaronMT** [comment]
Fixed via https://github.com/mozilla-mobile/firefox-ios/commit/3c1bced53a4c14f4e4dc826043d19538ecc46cc7
