### ISSUE TITLE
FXIOS-1658 ⁃ The append arrow is mirrored on v34.0 (4203)

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#8252]
## Steps to reproduce
1. Type a search term in the URL bar
### Expected behavior
- The append arrow should show pointing to the left like in secs (https://www.figma.com/file/lfgj15zbNkL9Pp4hdZGJgp/Proton-Mobile-UI?node-id=51%3A7706)
### Actual behavior
- The arrow is pointing to the right.

![Skype_Picture_2021_03_30T11_16_50_228Z](https://user-images.githubusercontent.com/32130829/112980860-17156500-9163-11eb-90c9-8c22e25f7b43.jpeg)

### Device & build information
* Device: iPhone Xr (14.4)
* Build version: 33.0 (4203)
### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1658)

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verified fix on a753ae4ef2
