### ISSUE TITLE
FXIOS-1662 ⁃ Homescreen widget is blank

### ISSUE THREAD

**Issue by eliserichards** [mozilla-mobile/firefox-ios#8259]
## Steps to reproduce
My homescreen search widget shows the red background but no text: 
![image](https://user-images.githubusercontent.com/43795363/113223392-ad728500-924e-11eb-84ed-706e7be9e523.jpeg)

### Expected behavior
The widget has text 

### Actual behavior
No text, but the widget still works fine and it opens the browser when I click it. 

### Device & build information
* Device: iPhone 12 Pro
* Build version: Firefox Daylight 33.0 (4119)

### Notes

- I'm not sure if it's relevant, but I noticed this after updating to iOS 14.4.2
- When I long press the widget and click "edit widget" nothing happens

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1662)

**Comment by dnarcese** [comment]
Closing as a WidgetKit issue
