### ISSUE TITLE
Dark mode with a background-less site

### ISSUE THREAD

**Issue by karlcow** [mozilla-mobile/firefox-ios#8263]
## Steps to reproduce

1. go to https://amp.rte.ie/amp/1207109/
2. with dark mode enabled

### Expected behavior
Readable content
### Actual behavior
Some part of the page are black on black

### Device & build information
* Device: Firefox iOS 33.0
* Build version: iOS 14.4.1
### Notes

When the site is not setting a default background-color for the and relies on the white of the UI, when switching to dark mode the text gets dark on dark. It would be probably good to not change the background-color of the page and stays white for the default if no color has been specified.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2812)

**Comment by karlcow** [comment]
Initially reported on https://github.com/webcompat/web-bugs/issues/68979

**Comment by lmarceau** [comment]
Since only `data-sync-user` has commented on the issue after the `Stalebot` GitHub action (which triggered the removal of the `stale` label) I’ll close this issue for now. Please let us know if you think this issue needs to be reopened, we'll gladly do so. Thank you!
