### ISSUE TITLE
TopTabsTest.testLongTapTabCounter - SmokeXCUITest

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#8272]
### Bitrise Test Run:
Provide a Bitrise test run report link here showcasing the problem
https://addons-testing.bitrise.io/builds/d850be43cea5587e/testreport/a8d1b8af-3662-4561-9517-db6310a2fc07/testsuite/0/testcases?status=failed

### Stacktrace:
file:///Users/vagrant/git/XCUITests/FxScreenGraph.swift:CharacterRangeLen=0&EndingLineNumber=338&StartingLineNumber=338 - Failed to synthesize event: Failed to scroll to visible (by AX action) Button, identifier: 'TabToolbar.tabsButton', label: 'Show Tabs', value: 2, error: Error kAXErrorCannotComplete performing AXAction 2003 on element AX element pid: 10169, elementOrHash.elementID: 140183267907344.148. (Underlying Error: Error kAXErrorCannotComplete performing AXAction 2003 on element AX element pid: 10169, elementOrHash.elementID: 140183267907344.148)

### Build:
Main April 2nd b3e29dff74b00963c6bdf64849f38456ff5672a7

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2814)

**Comment by SimonBasca** [comment]
Failed on 8 April https://app.bitrise.io/build/038a140b5cfa7e26#?tab=log

**Comment by SimonBasca** [comment]
Failed on 13 April https://app.bitrise.io/build/62d9b7abc412079f#?tab=log

**Comment by lmarceau** [comment]
Since only `data-sync-user` has commented on the issue after the `Stalebot` GitHub action (which triggered the removal of the `stale` label) I’ll close this issue for now. Please let us know if you think this issue needs to be reopened, we'll gladly do so. Thank you!
