### ISSUE TITLE
FXIOS-1669 ⁃ Unable to print with window.print()

### ISSUE THREAD

**Issue by ksy36** [mozilla-mobile/firefox-ios#8274]
We've got a couple reports where printing doesn't work when using `window.print()`

## Steps to reproduce
Visit https://codepen.io/ksy36/pen/OJWmRNe and press on "Print"

### Expected behavior
Printing dialog appears

### Actual behavior
Nothing happens

### Device & build information
* Device:  iPhone X iOS 14.4, iPad Pro iOS 14.4.1
* Build version: Firefox Daylight 33.0 (4119)

### Notes
Not reproducible in Safari or Brave

Reported issues:
https://github.com/webcompat/web-bugs/issues/69114
https://github.com/webcompat/web-bugs/issues/68854

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2815)

**Comment by IanBellomy** [comment]
Hit this too — 

On iOS specifically I can display a message telling users how to print via the browser controls, but no such luck on iPad because FF doesn't identify itself there via UA, so those users just get a print button that does nothing...

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verified fix on main 48a92ef8b2c158a9758617d84cca2ee5d44d2dbc
