### ISSUE TITLE
FXIOS-1675 ⁃ Inverted images when opening Twitter via text

### ISSUE THREAD

**Issue by MilanPatel718** [mozilla-mobile/firefox-ios#8280]
## Steps to reproduce
This issue could be for other sites that show thumbnails/images, but in this case found for Twitter. Occurs when night mode in Firefox enabled.
1. Open Twitter url sent via messaging platform (app not installed)
2. When page opens, all images show inverted if night mode is toggled. Toggling off and on will fix the image display
3. Reproducible when tried again
### Expected behavior
Page should open with images displaying normally instead of inverted 
### Actual behavior
Page loads with images inverted 
### Device & build information
* Device: IPhone 12 Pro
* Build version: IOS 14.4.2, FF 33.0 (4119)
### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2818)

**Comment by little7dwarfs** [comment]
Night mode is inverting images to negative. Switching off will fix that issue.

**Comment by MilanPatel718** [comment]
Understood, don't know how feasible this is but maybe a sub toggle within might mode to keep pictures non inverted? Again, if not feasible then never mind.

**Comment by data-sync-user** [comment]
➤ Ashley Thomas commented:

Consolidating issue into ticket #5819 https://mozilla-hub.atlassian.net/browse/FXIOS-2212 ( https://mozilla-hub.atlassian.net/browse/FXIOS-2212|smart-link )
