### ISSUE TITLE
Tests with pre loaded data base content fail when being launched to run as part of a test suite

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/firefox-ios#8281]
When two tests that use a data base to preload data, like in this [test suite](https://github.com/mozilla-mobile/firefox-ios/blob/main/XCUITests/ActivityStreamTest.swift#L14), run one after the other, this error is hapening:

```
Thread 1: Fatal error: 'try!' expression unexpectedly raised an error: Error Domain=NSCocoaErrorDomain Code=4 "“db” couldn’t be removed." UserInfo={NSUserStringVariant=(
  Remove
), NSFilePath=~/Library/Developer/CoreSimulator/Devices/Device_id/data/Containers/Shared/AppGroup/App_group_id/profile.testProfile/**nimbus.db/db**, NSUnderlyingError=0x6000034e9e60 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}

```

This started to happen after the Nimbus work landed on commit: 9e1a42a3d29d11
This is the last commit tests work without this error: a753ae4ef2291b

The test works if it runs separately. 

## Steps to reproduce
Launch Activity Stream test suite
### Expected behavior
All tests pass
### Actual behavior
testTopSitesAdd fails with error described above

### Device & build information
* Device: iPhone 8 
* Build version: main

cc @jhugman and @boek since I think you are the people with more knowledge about the Nimbus integration... Thanks!

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2819)

**Comment by lmarceau** [comment]
I think this can be closed
