### ISSUE TITLE
FXIOS-1680 ⁃ Rename Top Sites to Shortcuts

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#8285]
**Vision**

To align across our browsers, we would like to change "Top Sites" to "Shortcuts"

**Acceptance Criteria**

* Keep Firefox Shortcuts widget as Firefox Shortcuts
* Change Top Sites widget name to "Website Shortcuts" (note that we do call them shortcuts in the microcopy: Add shortcuts to frequently and recently visited sites.)
* On New Tab, change "Top Sites" section heading to "Shortcuts"

**Notes**

* In the page actions menu, we have "Pin to Top Site" / "Remove Pinned Site" which will be changed as part of another ticket
* Toast popup after pinning / unpinning will be changed as part of another ticket

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1680)

**Comment by data-sync-user** [comment]
➤ Daniela Arcese commented:

We don't have the string for "Website Shortcuts"

**Comment by SimonBasca** [comment]
Verified fix on v34.0 (4722). "Top Sites" has been renamed to "Shortcuts" on New tab. 

Top Sites widget name has not been changed to "Website Shortcuts" due to missing strings as mentioned in the above comment.
