### ISSUE TITLE
FXIOS-1685 ⁃ Trying to open a tab from private mode opens in attentive mode instead of the website

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/firefox-ios#8295]
## Steps to reproduce
Go to private mode and add two tabs
Change to regular mode
Go to private mode and click on the first tab to go to its site
### Expected behavior
The website is open
### Actual behavior
The website is open for a second but then the HomePanel Screen is shown with urlBar focused
### Device & build information
* Device: iPhone 11
* Build version: main 91706655352f8cbf295975a9d707c7c9c9fa87db
### Notes
Attachments: See video

https://user-images.githubusercontent.com/1897507/114012178-49f7e100-9866-11eb-9699-aa56823bdbe2.mov

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1685)

**Comment by isabelrios** [comment]
This was found after running this automated test: [testClosePrivateTabsOptionClosesPrivateTabs](https://github.com/mozilla-mobile/firefox-ios/blob/main/XCUITests/PrivateBrowsingTest.swift#L80)

**Comment by isabelrios** [comment]
Let's try in the regular tab tray not in chron tab and also with regular mode tabs

**Comment by isabelrios** [comment]
Same behaviour with new tab tray: 

https://user-images.githubusercontent.com/1897507/114067286-f359c980-989c-11eb-866b-ecda816438f9.mov

**Comment by isabelrios** [comment]
It also happens the other way around, going from private tabs and opening regular tab

**Comment by SimonBasca** [comment]
Fixed in v34.0 (4772)
