### ISSUE TITLE
[XCUITests] Add variables for each accessibility ID

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/firefox-ios#8301]
It will be a nice to have and a great improvement to have all the accessibility identifiers as variables in a separate file so that in case we need to change it, it will be only in one place.

See for example this part of one test: https://github.com/mozilla-mobile/firefox-ios/blob/main/XCUITests/TopTabsTest.swift#L123 there is an ID that is used several times in the same tests, in the test suite and also in the screengraph.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2826)

**Comment by lmarceau** [comment]
Since only `data-sync-user` has commented on the issue after the `Stalebot` GitHub action (which triggered the removal of the `stale` label) I’ll close this issue for now. Please let us know if you think this issue needs to be reopened, we'll gladly do so. Thank you!
