### ISSUE TITLE
FXIOS-1689 ⁃ [Regression] Misaligned text in History Panel View

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/firefox-ios#8305]
## Steps to reproduce
Go to History Panel
### Expected behavior
The text is shown correctly aligned for all options
### Actual behavior
The labels are not correctly aligned. Please see screenshot below
### Device & build information
* Device: iPhone 11
* Build version: main 041c854
### Notes
This may be a regression after commit 041c854
Attachments: 
![Simulator Screen Shot - iPhone 11 Pro - 2021-04-09 at 12 35 17](https://user-images.githubusercontent.com/1897507/114168363-76782f80-9930-11eb-8c91-270772fe6bdd.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1689)

**Comment by SimonBasca** [comment]
Verified fix on main a3a736cfe5
