### ISSUE TITLE
[Regression] Incorrect size for fav icon in Recently closed view

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/firefox-ios#8306]
## Steps to reproduce
Go to a site and close it
Then go to History Panel -> Recently closed
### Expected behavior
The text and icon for each closed site is shown correctly
### Actual behavior
The fav icon is bigger than expected
### Device & build information
* Device: iPhone 11
* Build version: main 041c854
### Notes
This may be a regression after commit 041c854
Attachments: 
![Simulator Screen Shot - iPhone 11 Pro - 2021-04-09 at 12 41 18](https://user-images.githubusercontent.com/1897507/114168885-29488d80-9931-11eb-9da5-81ec019f51b0.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2827)

**Comment by lmarceau** [comment]
Since only `data-sync-user` has commented on the issue after the `Stalebot` GitHub action (which triggered the removal of the `stale` label) I’ll close this issue for now. Please let us know if you think this issue needs to be reopened, we'll gladly do so. Thank you!
