### ISSUE TITLE
Address bar flashes blank and white when scrolling

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/firefox-ios#8315]
## Steps to reproduce
Quickly scroll the page up and down on some sites in landscape orientation (particularly on https://news.ycombinator.com/news).

### Expected behavior
The address bar should not flash different colors. 

### Actual behavior
The left and right ends of the address bar change color from white to black intermittently. See the attached screenshot.

I believe this is a regression in Firefox Beta 34.0.0 because I can’t  reproduce the problem in that latest non-beta version Firefox 33.0 (4119). 

### Device & build information
* Device: iOS 14.4.2 on an iPhone 12.
* Build version: Firefox Beta 34.0.0 (4203).

### Notes
Attachments: 

![1FBD99C2-97ED-4C04-87C0-634293AB598B](https://user-images.githubusercontent.com/629193/114296047-e33d1800-9a5d-11eb-880b-2380a90424eb.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2831)

**Comment by dnarcese** [comment]
This is a theme related issue. Happens when your iOS theme is dark but the app theme is light.

**Comment by cpeterso** [comment]
> This is a theme related issue. Happens when your iOS theme is dark but the app theme is light.

AFAIK, this is not the case on my iPhone: my iOS theme is "Light" and my Firefox theme setting is "Use System Light/Dark Mode".

**Comment by cpeterso** [comment]
Closing because I can no longer reproduce this bug.
