### ISSUE TITLE
Search with Firefox Does Not Work in a PDF Page

### ISSUE THREAD

**Issue by tillchen** [mozilla-mobile/firefox-ios#8318]
## Steps to reproduce

1. Open any PDF page (e.g. https://arxiv.org/pdf/1512.03385.pdf).
2. Select a random word/phrase.
3. Tap on "Search with Firefox".

### Expected behavior

A new tab with the search result is open.

### Actual behavior

A new tab with only the search engine homepage is open, e.g. https://www.google.com/webhp?ie=utf-8&oe=utf-8&client=firefox-b-1-m

### Device & build information
* Device: iPhone XR
* Build version: Firefox Daylight 33.0 (4119)

### Notes
Attachments: 

https://user-images.githubusercontent.com/35601483/114370847-36a78700-9b80-11eb-8dc0-2cd32dcf4a96.MP4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2832)

**Comment by lmarceau** [comment]
Since only `data-sync-user` has commented on the issue after the `Stalebot` GitHub action (which triggered the removal of the `stale` label) I’ll close this issue for now. Please let us know if you think this issue needs to be reopened, we'll gladly do so. Thank you!
