### ISSUE TITLE
FXIOS-1699 ⁃ ActivityStream.testTopSitesOpenInNewPrivateTabDefaultTopSite - SmokeXCUITest

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/firefox-ios#8321]
### Bitrise Test Run:
Provide a Bitrise test run report link here showcasing the problem
https://addons-testing.bitrise.io/builds/72c46f764b4cfb74/testreport/b0a7ce78-328c-4404-97a8-761e422be28d/testsuite/0/testcases?status=failed
### Stacktrace:
file:///Users/vagrant/git/XCUITests/FxScreenGraph.swift:CharacterRangeLen=0&EndingLineNumber=476&StartingLineNumber=476 - Failed to synthesize event: Failed to scroll to visible (by AX action) Button, identifier: 'TabToolbar.tabsButton', label: 'Show Tabs', value: 1, error: Error kAXErrorCannotComplete performing AXAction 2003 on element AX element pid: 8604, elementOrHash.elementID: 140294559759936.147. (Underlying Error: Error kAXErrorCannotComplete performing AXAction 2003 on element AX element pid: 8604, elementOrHash.elementID: 140294559759936.147)

The app stays in the main page before closing the urlBar focused. This test usually fails as part of PR or scheduled builds but not when running the RunUnitTest workflow that also runs the Smoketest
### Build:
CommonBuild-UITest-Smoketest on April 13th

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2833)

**Comment by adamgolding33** [comment]
[]()

**Comment by isabelrios** [comment]
Closing, re-open if fails again
