### ISSUE TITLE
FXIOS-1701 ⁃ 😎 1670127

### ISSUE THREAD

**Issue by boek** [mozilla-mobile/firefox-ios#8324]
https://bugzilla.mozilla.org/show_bug.cgi?id=1670127

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1701)

**Comment by SimonBasca** [comment]
@boek I don't have access for this bug. Could you please provide access if this issue has STR and can be tested? Thanks

**Comment by SimonBasca** [comment]
Fixed in v34.0(4920)
