### ISSUE TITLE
FXIOS-1706 ⁃ 247sports.com - login is not performed when credentials are pre-registered

### ISSUE THREAD

**Issue by karlcow** [mozilla-mobile/firefox-ios#8328]
## Steps to reproduce
1. Go to https://247sports.com/college/duke/login/
2. with an account pre-saved

### Expected behavior
login in the site

### Actual behavior
The login is not perfomed if the credentials are previously saved and autofilled.
If I delete/edit the credentials and manually type them the login is performed.

### Device & build information
* Device: iPad
* Build version: 14.2.2
### Notes
see https://github.com/webcompat/web-bugs/issues/69550

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1706)

**Comment by SimonBasca** [comment]
Seems like this issue is a duplicate of #8003.

**Comment by SimonBasca** [comment]
@karlcow fell free to re-open if you believe this is a different issue.

**Comment by digitarenet** [comment]
Also in this website the same issue with previously saved credentials:

 https://app.clickup.com/login
