### ISSUE TITLE
FXIOS-1707 ⁃ Disable all Leanplum integrations on iOS

### ISSUE THREAD

**Issue by krupa-raj** [mozilla-mobile/firefox-ios#8331]
Mozilla has decided to not renew our Leanplum contract for 2021-22. The current contract will expire on May 31, 2021. We need to turn off any Leanplum integrations in our products by that date. Note that this is for all mozilla products on iOS.

Pls also see: https://github.com/mozilla-mobile/firefox-ios/issues/8131

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1707)

**Comment by data-sync-user** [comment]
➤ Daniela Arcese commented:

We need to make sure that current builds out there with Leanplum will not break once Leanplum expires.
