### ISSUE TITLE
Reader mode is failing time to time on the same page

### ISSUE THREAD

**Issue by karlcow** [mozilla-mobile/firefox-ios#8332]
## Steps to reproduce
1. Go to https://www.bloomberg.com/news/articles/2021-04-03/u-k-says-astrazeneca-shot-safe-even-after-7-blood-clot-deaths
2. activate reader mode

### Expected behavior
the reader mode version of the page is displayed.

### Actual behavior
Sometimes it works, sometimes it fails, and a part of the style element is displayed.

### Device & build information
Browser / Version: Firefox iOS 33.0
Operating System: iOS 14.4.2

See https://github.com/webcompat/web-bugs/issues/69629

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2836)

**Comment by lmarceau** [comment]
Since only `data-sync-user` has commented on the issue after the `Stalebot` GitHub action (which triggered the removal of the `stale` label) I’ll close this issue for now. Please let us know if you think this issue needs to be reopened, we'll gladly do so. Thank you!
