### ISSUE TITLE
FXIOS-1709 ⁃ Authentication.testPromptPassCodeUponReentry - Smoketest

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/firefox-ios#8333]
### Bitrise Test Run:
Provide a Bitrise test run report link here showcasing the problem
https://addons-testing.bitrise.io/builds/b962ec085c7b2e57/testreport/fa905929-2509-4893-934e-6a947387e0d8/testsuite/0/testcases?status=failed
### Stacktrace:
file:///Users/vagrant/git/XCUITests/AuthenticationTest.swift:CharacterRangeLen=0&EndingLineNumber=61&StartingLineNumber=61 - Expect predicate exists == true for "Enter Passcode" NavigationBar
### Build:
Main April 15h, running the daily scheduled CommonBuild-UITests-Smoketest workflow

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1709)

**Comment by SimonBasca** [comment]
Failed on May 24 https://app.bitrise.io/build/1c8d6a9755c5a9dd#?tab=log.
