### ISSUE TITLE
Page fails to load fully

### ISSUE THREAD

**Issue by softvision-oana-arbuzov** [mozilla-mobile/firefox-ios#8337]
## Steps to reproduce
1. Navigate to https://laurentperrinet.github.io/brassens-md/albums/brassens_1.html
2. Scroll down the page until reaching "Le Parapluie" section.
3. Observe the page under the section.

### Expected behavior
Other sections are displayed.

### Actual behavior
Blank page is displayed.

### Device & build information
* Device: iPod touch iOS 12.5.2 (1136 x 640 pixels (~326 ppi pixel density)
* Build version: Firefox iOS 33.0

### Notes
1. The issue does not occur on Chrome and Safari.
2. Screenshot attached.
![image](https://user-images.githubusercontent.com/12184325/113606597-e9438b00-9650-11eb-91b1-5cc2a79841c3.png)
3. Previously reported https://github.com/webcompat/web-bugs/issues/69398

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2839)

**Comment by dnarcese** [comment]
Let's prioritize an investigation into this. Timebox to a 1
