### ISSUE TITLE
FXIOS-1715 ⁃ Investigate missing strings in latest export

### ISSUE THREAD

**Issue by boek** [mozilla-mobile/firefox-ios#8338]
In the latest string export it looks like 8 strings got removed.

I did a little investigation by manually changing both the .strings and .xml files and running imports and exports and wasn't able to reproduce it. This leads me to believe that I must have done something in my environment during the export.

In the next export we should write something to log out anything that is getting removed to make catching an issue like this easier.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2840)

**Comment by Delphine** [comment]
Thanks Jeff!
Flod mentioned here that there were 18 that got removed, so flagging here just in case.
Maybe some of the 18 were actually intentionally removed?

**Comment by boek** [comment]
@Delphine Do we have a list of the 18 strings? I can check to make sure

**Comment by flodolo** [comment]
You might be able to get it out of these two commits
https://github.com/mozilla-l10n/firefoxios-l10n/commit/f23faad13da440e617e1a9b5b68e16227038e338#diff-2ad8a7049d7c5511ac254f5f51fe70a046ebd884729056f0fe57f5160d467153
https://github.com/mozilla-l10n/firefoxios-l10n/commit/944eb182ae24d109ab7caf2c74b21fd0f99d5133#diff-2ad8a7049d7c5511ac254f5f51fe70a046ebd884729056f0fe57f5160d467153

What happens in Pontoon is quite weird, as those strings get rejected and the string show up as untranslated. So, I went in and re-approved them one by one, to only leave things that were actually untranslated before the new content.

**Comment by boek** [comment]
Attempting a new export I noticed some new missing strings
https://github.com/mozilla-l10n/firefoxios-l10n/pull/112/commits/32743899a8350415fec55a171e195f1db136d673

Looking in the Firefox iOS repo it looked like those strings were removed from the .strings file. I'm not sure why they got removed but when I re-imported them they re-appeared and I was able to do a successful export. 

I will modify the script to do one localization at a time and try to see if that helps next time.

**Comment by boek** [comment]
So after some more investigation came to the conclusion that we imported and exported out of order. We have since re-added all of the strings that got removed [here](https://github.com/mozilla-l10n/firefoxios-l10n/pull/113) and now have clean exports and imports again.
