### ISSUE TITLE
FXIOS-1714 ⁃ [l10n tooling] Create script that will commit each locale as a separate commit

### ISSUE THREAD

**Issue by boek** [mozilla-mobile/firefox-ios#8339]
In the last two exports we committed the whole changeset in one commit. Let's breach each locale into an individual commit.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2841)

**Comment by nishant2718** [comment]
This is actually done, and [documented here](https://github.com/mozilla-mobile/firefox-ios/wiki/Localization-Process) under the Exports section.
