### ISSUE TITLE
FXIOS-1716 ⁃ Add `Sync Now` button to new Sync Tab Tray

### ISSUE THREAD

**Issue by nbhasin2** [mozilla-mobile/firefox-ios#8341]
**Vision**

As a user, I want an option to refresh my synced tabs list, so that I can get the latest tabs open on my other devices on my phone

**Background**

We have hidden the following sync now button as the new Sync Tab Tray doesn't do anything visually when we tab the button. In order to fully support the button we need to implement additional `Loading` indicator that informs user when Sync actually happens and finishes

**Acceptance Criteria**

* A button to trigger syncing with other devices is added to synced tabs view
* A loading indicator is shown when syncing
* Exact copy and design follows [spec](https://www.figma.com/file/WboC4Dn9iu9wie2GodfSAg/Post-MR1?node-id=51%3A7703)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1716)

**Comment by data-sync-user** [comment]
➤ Nishant Bhasin commented:

I am wondering how should we proceed with this as this ticket requires some UX work and our current implementation does sync.

  * we naturally sync when user connects a syncable account
  * we also sync when user opens tab tray and goes to sync view
  * we also sync when user pulls down to refresh on the sync tab tray

The sync now button at the bottom in the view does sync but it doesn't inform user that sync has begun / ended in any way.

[~bpitoyo@mozilla.com] [~athomas@mozilla.com] Should we come back to it as a part of MR2? or Should we add a new UX flow? 

I'll wait for your input on this.

**Comment by data-sync-user** [comment]
➤ Ashley Thomas commented:

[~nbhasin@mozilla.com] I didn't realize we were able to do the 3rd one - sync when user pulls down to refresh on the sync tab tray. Since we have that as a way for users to manually trigger sync, I think we can remove this ticket from the sprint and wait for UX input.

**Comment by data-sync-user** [comment]
➤ Nishant Bhasin commented:

Sounds good [~athomas@mozilla.com] 

Moved this to top of backlog but if thats not the correct place then feel free to move it to its correct place cc [~darcese@mozilla.com]

**Comment by data-sync-user** [comment]
➤ Ashley Thomas commented:

Note that if we require new strings for this one, we may need to delay releasing to v35.

**Comment by data-sync-user** [comment]
➤ Nishant Patel commented:

Raised a PR to address this; https://github.com/mozilla-mobile/firefox-ios/pull/8582. ( https://github.com/mozilla-mobile/firefox-ios/pull/8582. )

**Comment by data-sync-user** [comment]
➤ Nishant Patel commented:

The PRs been merged, and will work with [~bpitoyo@mozilla.com] for a design review before moving to QA.

**Comment by data-sync-user** [comment]
➤ Nishant Patel commented:

Raised another PR to address the unauthenticated case; https://github.com/mozilla-mobile/firefox-ios/pull/8599.  ( https://github.com/mozilla-mobile/firefox-ios/pull/8599. )

Screenshots have been attached above.

**Comment by data-sync-user** [comment]
➤ Nishant Patel commented:

Added some landscape screenshots as well.

**Comment by data-sync-user** [comment]
➤ Nishant Patel commented:

Moved over to QA. To verify, please see the design spec and this comment here https://github.com/mozilla-mobile/firefox-ios/pull/8599#issuecomment-851069866. ( https://github.com/mozilla-mobile/firefox-ios/pull/8599#issuecomment-851069866. )

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verified fix on main 70fdda04.

**Comment by SimonBasca** [comment]
Verified fix on v34.1 (5146).
