### ISSUE TITLE
Follow Up #8322 - [XCUITests] Fix tests on iPad for the full test plan

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#8343]
After looking at the test run from #8322, I saw that most of the tests are failing because of this line:

`file:///Users/vagrant/git/XCUITests/FxScreenGraph.swift:CharacterRangeLen=0&EndingLineNumber=958&StartingLineNumber=958 - Failed to synthesize event: Failed to scroll to visible (by AX action) TextField, identifier: 'url', label: 'Address Bar', placeholderValue: 'Search or enter address', error: Error kAXErrorCannotComplete performing AXAction 2003 on element AX element pid: 5542, elementOrHash.elementID: 140624653584896.182. (Underlying Error: Error kAXErrorCannotComplete performing AXAction 2003 on element AX element pid: 5542, elementOrHash.elementID: 140624653584896.182)`

These are the test failing due to the mentioned issue: 

- testTopSitesRemoveAllExceptPinnedClearPrivateData

- testBookmarkingUI()
- testUndoDeleteBookmark()

- testClipboard()

- testLongPressReload()

- test4EnsureSchemeIncludedAutocompletion()
- test5NoMatches()

- testDeleteDownloadedFile()
- testDownloadBLOBFile()
- testDownloadFileContextMenu()
- testDownloadMoreThanOneFile()
- testLongPressOnDownloadedFile()
- testShareDownloadedFile()

- testDragAndDropHomeTab()
- testRearrangeTabs()
- testRearrangeTabsPrivateMode()
- testRearrangeTabsTabTrayIsKeptinTopTabs()

- testBarDissapearsWhenOpeningTabsTray()
- testBarDissapearsWhenReloading()
- testFindFromSelection()
- testFindInLargeDoc()
- testFindInPageResultsPageShowHideContent()
- testFindInPageTwoWordsSearch()
- testFindInPageTwoWordsSearchLargeDoc()
- testQueryWithNoMatches()

- testAllOptionsArePresent()
- testLongTapOptionsRecentlyClosedItem()
- testOpenInNewPrivateTabRecentlyClosedItem()
- testOpenInNewTabRecentlyClosedItem()
- testPrivateClosedSiteDoesNotAppearOnRecentlyClosed()
- testRecentlyClosedOptionAvailable()

- testCopyLink()
- testCopyLinkPrivateMode()
- testDownloadLink()
- testLongPressLinkOptionsPrivateMode()
- testLongPressOnAddressBar()
- testNavigation()
- testShareLink()
- testShareLinkPrivateMode()

- testNightModeUI()

- testSendToDeviceFromPageOptionsMenu()
- testShareOptionIsShown()
- testShareSheetOpenAndCancel()
- testShareSheetSendToDevice()

- testClearIndexedDB()
- testClosePrivateTabsOptionClosesPrivateTabs()
- testPrivateTabDoesNotTrackHistory()
- testTabCountShowsOnlyNormalOrPrivateTabCount()
- testClosePrivateTabsOptionClosesPrivateTabsShortCutiPad()
- testiPadDirectAccessPrivateModeBrowserTab()

- testAddToReadingListFromPageOptionsMenu()
- testAddToReadingListPrivateMode()
- testMarkAsReadAndUnreadFromReadingList()
- testMarkAsReadAndUreadFromReaderView()
- testOpenSavedForReadingLongPressInNewTab()
- testRemoveFromReadingList()
- testRemoveFromReadingView()
- testRemoveSavedForReadingLongPress()

- testDeleteLogin()
- testDoNotSaveLogin()
- testSavedLoginSelectUnselect()
- testSearchLogin()

- testSearchWithFirefoxOption()

- testClearURLTextUsingBackspace()
- testRevealToolbarWhenTappingOnStatusbar()
- testAddTabFromContext()
- testCloseAllTabs()
- testCloseAllTabsPrivateMode()
- testCloseOneTab()
- testSwitchBetweenTabs()
- testTopSitesScrollToVisible()
- testMenuWhenThereAreBlockedElements()

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2842)

**Comment by lmarceau** [comment]
Since only `data-sync-user` has commented on the issue after the `Stalebot` GitHub action (which triggered the removal of the `stale` label) I’ll close this issue for now. Please let us know if you think this issue needs to be reopened, we'll gladly do so. Thank you!
