### ISSUE TITLE
[XCUITests] Add test for the sync button in the new tab tray view

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/firefox-ios#8351]
As per the new UI:
![Captura de pantalla 2021-04-19 a las 16 14 34](https://user-images.githubusercontent.com/1897507/115250966-5ca5cc00-a12a-11eb-8962-767659e4acd4.png)

It would be nice to add a test for that new icon and its functionality

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2845)

**Comment by lmarceau** [comment]
Since only `data-sync-user` has commented on the issue after the `Stalebot` GitHub action (which triggered the removal of the `stale` label) I’ll close this issue for now. Please let us know if you think this issue needs to be reopened, we'll gladly do so. Thank you!
