### ISSUE TITLE
FXIOS-1729 ⁃ [Regression]Top Sites label iPad homescreen view is not aliged

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/firefox-ios#8357]
This looks like a regression after the new Tabs Tray design, commit: d597475

## Steps to reproduce
Open latest main version on iPad
### Expected behavior
Homescreen view is shown as expected
### Actual behavior
Please look at the differences between the two views
### Device & build information
* Device: iPad Pro (12.9 inch) 14.4
* Build version: main
### Notes
Attachments: 
Before that commit: 
<img width="397" alt="Captura de pantalla 2021-04-20 a las 12 30 40" src="https://user-images.githubusercontent.com/1897507/115382432-f88c1200-a1d4-11eb-83b6-a78eb9076266.png">

After that commit:
<img width="397" alt="Captura de pantalla 2021-04-20 a las 12 36 55" src="https://user-images.githubusercontent.com/1897507/115382564-22ddcf80-a1d5-11eb-9d2d-963c6393df96.png">

or it may be on purpose @electricRGB? Thanks!

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2847)

**Comment by electricRGB** [comment]
Hmm. Yes, I see what you mean. I believe Nish removed the icons for the top sites and that was baked in my PR and this may have happened at that time. Definitely fixable and I'll take a look at it. :)

In playing with this, I noticed the "Top Sites" text doesn't change colour when you change theme, either. It's the same piece of work so I'll add that to this ticket. :)
