### ISSUE TITLE
FXIOS-1733 ⁃ As a user I want to be able to pick from multiple logins when autofilling a login form

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/firefox-ios#8369]
When multiple accounts are present for a website, we current autofill the first one. It is not possible to pick which account should be used.

Implement a simple UI that allows the user to choose which account should be used.

> Part of the P16107 work. Stefan will provide more detail in this ticket.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1733)

**Comment by st3fan** [comment]
@athomasmoz we are not sure if we are going to address this bug since the credential provider also provides this functionality. As in: when you have set Firefox as your password filler, you can just tap in any login field and then use the lock button to select the right credentials.

**Comment by athomasmoz** [comment]
Yes, sounds good. Closing the issue.
