### ISSUE TITLE
FXIOS-1734 ⁃ As a user I want to be able to add new accounts to the password manager manually

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/firefox-ios#8370]
When you sign in to a website, Firefox asks you if you want to remember the account used. If you confirm this, it will be added to the built-in password manager and also sync to your Firefox Account, if enabled.

This story is about adding functionality to the built-in password manager to also allow the user to manually add a new account there.

The goal is that you can simply go into _Logins & Passwords_ and add a new login from there. It would show an entry form similar to the existing detail view.

> Part of the P16107 work. Stefan will provide more detail in this ticket.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2849)

**Comment by SimonBasca** [comment]
Verified fix on main 93370062.

**Comment by SimonBasca** [comment]
Verified fix on v36.0 (5673).
