### ISSUE TITLE
Page action menu does not get updated in Private mode on new tab tray

### ISSUE THREAD

**Issue by dnarcese** [mozilla-mobile/firefox-ios#8379]
If you are in `Private mode` and try to add website to shortcuts then it isn't behaving correctly

https://user-images.githubusercontent.com/8919439/115765285-8fdb9b80-a374-11eb-8d99-67e223db8b7e.mov

P.S. Works fine for regular mode and chron tabs

_Originally posted by @nbhasin2 in https://github.com/mozilla-mobile/firefox-ios/pull/8374#issuecomment-825075525_

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2852)

**Comment by data-sync-user** [comment]
➤ Daniela Arcese commented:

Repro is a little iffy here. Sometimes it works for me sometimes it doesn't

**Comment by data-sync-user** [comment]
➤ Daniela Arcese commented:

This bug exists in v33 so is not a regression from MR1 work. Deprioritizing.

**Comment by lmarceau** [comment]
Since only `data-sync-user` has commented on the issue after the `Stalebot` GitHub action (which triggered the removal of the `stale` label) I’ll close this issue for now. Please let us know if you think this issue needs to be reopened, we'll gladly do so. Thank you!
