### ISSUE TITLE
FXIOS-1741 ⁃ [Normal Tabs Tray] The view does not scroll to the newest opened tab

### ISSUE THREAD

**Issue by Duckbilled** [mozilla-mobile/firefox-ios#8381]
In Firefox Daylight 34.0 (4551) there is a new tab interface. I don’t have issues with the new interface in general, but whenever it opens the it shows the tabs all the way at the top, which are the oldest tabs. A new tab and other recently used tabs are in the bottom. This creates the need to scroll down, which is an issue if you have a medium to large amount of tabs. 

Please consider opening the tab interface at the bottom or invert where new tabs are placed (so, new tabs at the top, old ones at the bottom).

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1741)

**Comment by SimonBasca** [comment]
@Duckbilled could you please post a screenshot of the tabs interface you are referring to?

**Comment by badboy** [comment]
I do understand the bug report, without screenshots.
I'll try to clarify:

1. Open Firefox iOS
2. Open several tabs (7+) to fill the tab overview screen
3. Now open another new tab and browse to some website
4. Click the tab overview button on the bottom

What I see: the tab overview, scrolled all the way to the top, thus having the oldest tabs visible

What I expect to see (and what happened before the last update): the tab overview, scrolled to the bottom, thus having the newest tab in view.

**Comment by SimonBasca** [comment]
@badboy we have two versions of the tab interface. 

Version A
![Version A](https://user-images.githubusercontent.com/32130829/116091194-47421c00-a6ad-11eb-9b05-7f7d282f5dd9.jpeg)


Version B
![Version B](https://user-images.githubusercontent.com/32130829/116091230-4d37fd00-a6ad-11eb-8679-793d6649bd92.jpeg)

I'm guessing you are using version A. If you wish to switch to Version B which go to Settings , tap 5 times on the version number and enable "Chronological tabs". This version will put the most recent used tabs at the top and will fix the issue you are having.

**Comment by badboy** [comment]
Ah, yeah, it's with the old tab overview (the rectangles).
Not a fan of the "chronological view" as it then changes ordering based on usage. The old view keeps it based on when the tab was opened.

So really I'd like the old behavior back where that tab view was scrolled to have the currently opened tab in view.

**Comment by Duckbilled** [comment]
@SimonBasca I was using version A as well, but have been using B for a few days now. I don't mind the new interface, but like badboy, I would prefer to order my own tabs.

**Comment by SimonBasca** [comment]
So this is a bug in the Normal Tabs Tray (Version A)

Steps to reproduce:
1. Open several tabs ~ 7 tabs
2. Open Tabs Tray

Actual results:
- After opening Tabs Tray, the view is not scrolled to the most recent opened tab.

Expected results:
- After opening Tabs Tray, the view is should be scrolled to the most recent opened tab.

Am I getting this right @Duckbilled @badboy ?

**Comment by Duckbilled** [comment]
Exactly, or the original (new tabs added below existing ones) ordering inverted (add new tabs in top left), the latter making more sense as the new interface slides up from the bottom to the top.

**Comment by athomasmoz** [comment]
Thank you for logging the issue! The expected behaviour matches what you've added in the original description - the tabs view should be scrolled to display the tab you're currently on, rather than the top of the list every time.

**Comment by isabelrios** [comment]
Using latest beta, (4551) I'm able to reproduce this issue too when there are enough tabs open in the tab tray so that you need to scroll. It is not a nice one :/ having to scroll to find the tab that you have just opened

**Comment by athomasmoz** [comment]
Agreed, I consider this a blocker.

**Comment by SimonBasca** [comment]
Verified fix on v34.0 (4722)
