### ISSUE TITLE
[Chron tabs] Tab tray has extra space between buttons and the tab list when opened in landscape orientation

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/firefox-ios#8382]
## Steps to reproduce
1. Load a page in Firefox Beta version 34.0 (4551).
1. Rotate phone to landscape orientation. 
1. Open tab tray. 

### Expected behavior
There should be no extra space between the tab tray buttons and the tab list’s “TODAY” header. 

### Actual behavior
The tab list is visible through an extra space between the tab tray buttons and the tab list’s “TODAY” header. See the attached screenshot. 

If you rotate the phone back to portrait orientation while the tab tray is open, the extra space remains in the portrait-oriented tab tray. 

### Device & build information
* Device: iPhone 12
* Build version: Firefox Beta version 34.0 (4551) on iOS 14.4.2

### Notes
Attachments: ![Uploading EF87929A-4D68-491E-BCC1-aF69EFDBDBB8E.png…]()

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2853)

**Comment by lolrepeatlol** [comment]
hey @cpeterso, seems like the screenshot didn't quite upload properly. just a heads up :)

**Comment by SimonBasca** [comment]
Uploading a video of the issue. 
[Video.mp4.zip](https://github.com/mozilla-mobile/firefox-ios/files/6375362/Video.mp4.zip)

**Comment by cpeterso** [comment]
![90DF51B0-CDC7-423E-8C86-397F0B410889](https://user-images.githubusercontent.com/629193/116168535-7bbad580-a6b7-11eb-9785-02cefe3359ca.png)

**Comment by dnarcese** [comment]
Closing as I cannot reproduce anymore

**Comment by cpeterso** [comment]
I can still reproduce this bug in Firefox TestFlight version 34.1 (5186). Here’s a new screenshot:

![2E346D3B-BD28-473F-90B2-CD9249AA2BE7](https://user-images.githubusercontent.com/629193/123599679-b968d700-d7aa-11eb-9639-d7b35829aeb8.png)

**Comment by SimonBasca** [comment]
@cpeterso I am unable to reproduce the issue on latest app store v34.2 (5301) on iOS 14.5.1. Could you please update to the latest version and let me know if the issue is still reproducible. Thanks

**Comment by cpeterso** [comment]
> @cpeterso I am unable to reproduce the issue on latest app store v34.2 (5301) on iOS 14.5.1. Could you please update to the latest version and let me know if the issue is still reproducible. Thanks

I can still reproduce the issue in the App Store version 34.2 (5301) on iOS 14.6, but only if I enable the "chronological tabs" setting (which is disabled in App Store version but enabled by default in the TestFlight Beta release):

1. Open Firefox's Settings menu.
2. Scroll to the bottom of the Settings menu.
3. Tap the "Firefox Daylight 34.2 (5301)" menu item five times to open the secret Debug menu.
4. Scroll to the bottom of the Debug settings and tap "Debug: Toggle chronological tabs ON" to enable chronological tabs.

**Comment by SimonBasca** [comment]
@dnarcese I am reproducing the issue but only after changing the device orientation to landscape and after opening chronological tabs. 

The issue is not reproducible after opening chronological tabs and changing the device orientation to landscape.
