### ISSUE TITLE
Browser page loading error iOS version

### ISSUE THREAD

**Issue by electrycmonk** [mozilla-mobile/firefox-ios#8383]
Hey folks, I accidentally started to fill out the link for the “security issues” in the iOS Firefox box instead of here. Big thumb/iPhone screen operator error.

so here is the situation. Question 1 (1st text box to fill)was briefly say what’s happening:
This occurs on several websites. Craigslist, O’Rielly auto parts, Lowe’s, Backyard chickens, tractorbynet, DuckDuckGo, Donaldson filters AND on the bug fix login page as well. This is the version of Firefox I have: Firefox Daylight 33.0 (4119)

2nd box:
Usually occurs within 2 seconds of clicking on a site, link, opening a new tab, or the automatic refresh from switching tabs or from having switched apps and the tab refreshes. It has also occurred from reboot of phone and a cold reboot. I have 2 screenshots, not sure if I can both to upload but, will try my best. (It shows they have uploaded)

3rd box:
Web page should load normally. ~50% of the time if I manually touch the screen across the actual top bar of the browser, “I highlight” the website address and then tap on the “return” button on the screens keyboard then the page will load, usually slower then normal. This has been occurring for the entire time I have had this new iPhone and freshly installed Firefox... for a whooping 18-19 days now. All updates are current. Apple is by default auto update whether or not I want this to happen “right then” instead of “hey wait till I get home tonight and do it while plugged in & on WiFi in the house.”

here are the 2 pics (fingers crossed)
![8FB4A1F4-3F6B-4F08-80DA-D295E6474309](https://user-images.githubusercontent.com/83133098/115966606-07840480-a4f4-11eb-9f67-3ef60ba6957a.png)
![FC3A3CA0-81D9-4390-BD46-EF152C691A4D](https://user-images.githubusercontent.com/83133098/115966608-09e65e80-a4f4-11eb-883c-de067648b468.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2854)

**Comment by SimonBasca** [comment]
Hello and thanks for reaching out. First of all I would like to clarify what the issue is. The issue is that after loading a link, the page is not loading, correct?

Could you please try loading the same pages in Safari and see if they load correctly?
