### ISSUE TITLE
webc-71066 - page never finishes loadign

### ISSUE THREAD

**Issue by karlcow** [mozilla-mobile/firefox-ios#8385]
## Steps to reproduce
1. Go to https://openpsychometrics.org/tests/characters/results.php?data=weGAfgU2PG

### Expected behavior
Page is loading

### Actual behavior
Page seems to never finish loading and is dark.
On Safari the page partially displays the content before being fully loaded.

### Device & build information
* Device: iPhone XS
* Build version: Firefox ios 33

### Notes
see https://github.com/webcompat/web-bugs/issues/71066

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2855)

**Comment by SimonBasca** [comment]
Also reproducible on latest beta 34.0 (4551). Disabling tracking protection has no effect, the issue is still reproducible. Also note that this issue is not reproducible in Firefox Focus 8.1.7.

**Comment by lmarceau** [comment]
Since only `data-sync-user` has commented on the issue after the `Stalebot` GitHub action (which triggered the removal of the `stale` label) I’ll close this issue for now. Please let us know if you think this issue needs to be reopened, we'll gladly do so. Thank you!
