### ISSUE TITLE
FXIOS-1745 ⁃ [Chronological Tabs] "Close tabs" and "Cancel" text is barely visible

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#8387]
## Steps to reproduce
1. Enable chronolgical tabs
1. Open tabs tray
1. Tap "Close tabs" icon
    1. Expected behavior

* The text should be visible.
    1. Actual behavior
* The text is not visible.
    1. Device & build information
* Device: iPhone Xr (14.4)
* Build version: 34.0 (4551)
    1. Notes
* This issue is reproducible in both Dark and Light theme
Attachments: 
![Picture](https://user-images.githubusercontent.com/32130829/116080064-486d4c00-a6a1-11eb-8dc3-b32865157e08.jpeg)UNITO-UNDERSCORE!2021!UNITO-UNDERSCORE!04!UNITO-UNDERSCORE!26T12!UNITO-UNDERSCORE!08!UNITO-UNDERSCORE!17!UNITO-UNDERSCORE!628Z!

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2856)

**Comment by GetToSet** [comment]
This bug is now fixed. 🎊

**Comment by SimonBasca** [comment]
Verified fix on main 431b08bc9
