### ISSUE TITLE
FXIOS-1747 ⁃ iPhone is missing from the UA string since OS 12

### ISSUE THREAD

**Issue by karlcow** [mozilla-mobile/firefox-ios#8392]
In https://github.com/webcompat/web-bugs/issues/70956

ebay.com displays a message that the browser is too old. 
We contacted eBay and someone at eBay noticed that the iPhone token was missing from the UA string.

`Mozilla/5.0 (iPhone; CPU OS 14_4_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) FxiOS/33.0 Mobile/15E148 Safari/605.1.15 `
instead of 
`Mozilla/5.0 (iPhone; CPU iPhone OS 14_4_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) FxiOS/33.0 Mobile/15E148 Safari/605.1.15 `

Looking at the previous code, it has been dropped in an unrelated commit from 12 to 13.
https://github.com/mozilla-mobile/firefox-ios/commit/bf2545e51ae22a0443c4971cf1975529e75cac1c

Was the decision taken for removing finger printing?
or is it a blooper?

We could imagine to rewrite the UA just for ebay, but we could also fix the UA string in general, depending on what we do for fingerprinting.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1747)

**Comment by data-sync-user** [comment]
➤ Karl Dubost commented:

https://github.com/mozilla-mobile/firefox-ios/pull/8419

**Comment by SimonBasca** [comment]
Fixed on v34.0 (4795).
