### ISSUE TITLE
Firefox no longer offers to open copied links

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/firefox-ios#8395]
## Steps to reproduce

I have the “Offer to Open Copied Links” setting enabled, but neither Firefox 33.0 (4119) nor Firefox Beta 34.0 (4551) on iOS 14.4.2 or iOS 14.5 offer to open copied links.

1. Copy a URL link in another app (such as Pocket).
2. Launch or switch to Firefox with the link on your clipboard.
3. You should see a popup warning like “Firefox copied from Pocket”.
4. Click the ➕ button to open a new tab.

### Expected behavior

A popup asking if I'd like to open the link on my clipboard should pop up either when switching to Firefox or in the new tab screen. (This feature has been broken for weeks or months before I noticed recently. I don't remember whether the popup popped up immediately when switching to Firefox or just on the new tab screen.)

### Actual behavior

I see the popup warning about “Firefox copied from Pocket” but I no longer get the popup asking to open the clipboard link.

### Device & build information

* Device: iPhone 12
* Build version: Firefox 33.0 (4119) and Firefox Beta 34.0 (4551) on iOS 14.4.2 and iOS 14.5

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2858)

**Comment by SimonBasca** [comment]
Confirming that this is an issue on 33.0 (4119) and 34.0 (4551). Last good build is 32.1 (3937).

**Comment by kcome** [comment]
The root cause is found. I created a [PR](https://github.com/mozilla-mobile/firefox-ios/pull/9031) for this issue. @cpeterso @SimonBasca

**Comment by cpeterso** [comment]
@kcome - Thanks for fixing this bug! I'm glad this feature will be returning. It's very handy.

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Marking verified fix on main a9d1f4e090a7d0b62e1d89c588de87c35cc8ca66

Note: While testing this issue a regression was found https://github.com/mozilla-mobile/firefox-ios/issues/9967 ( https://github.com/mozilla-mobile/firefox-ios/issues/9967|smart-link )
