### ISSUE TITLE
Background pages automatically scrolled to bottom when switched to

### ISSUE THREAD

**Issue by bnoctis** [mozilla-mobile/firefox-ios#8403]
## Steps to reproduce

(*Not steadily reproducible*) Open a few links in the background, browse through some other tabs, maybe go to other apps to make the browser backgrounded, then switch to the opened in background tabs.

### Expected behavior

Page loads at its top.

### Actual behavior

Page scrolled to its bottom.

### Device & build information
* Device: iPhone 11, iOS 14.4
* Build version: Firefox Daylight 33.0 (4119)
### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2861)

**Comment by SimonBasca** [comment]
@bnoctis I am unable to reproduce this issue on v33.0 (4119) or latest beta 34.0 (4795). Could you lease provide some site examples where this is happening?

**Comment by bnoctis** [comment]
@SimonBasca I'd like to, but it's jumping out now and then, and a list hasn't been collected yet. I'll update once met again.

**Comment by SimonBasca** [comment]
@bnoctis Also if you manage to catch a screen recording of this issue it would be very helpful.

**Comment by bnoctis** [comment]
Here comes the first encounter: entered smart2pay.com, turned to other pages waiting for it to load, came back, voilà - at the bottom.

@SimonBasca Unlikely - I wouldn't know it until I see it, but then would be late. And I can't keep screen logging on that long. Is there some way I could get some "debug output" though?

**Comment by lmarceau** [comment]
Since only `data-sync-user` has commented on the issue after the `Stalebot` GitHub action (which triggered the removal of the `stale` label) I’ll close this issue for now. Please let us know if you think this issue needs to be reopened, we'll gladly do so. Thank you!
