### ISSUE TITLE
FXIOS-1754 ⁃ Add back Home option to the app menu

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/firefox-ios#8404]
The menu option was removed but not completely and after checking with product and UX, it is better to get it back:

Figma mockup: https://www.figma.com/file/lfgj15zbNkL9Pp4hdZGJgp/MR1?node-id=339%3A27332
Home icon: https://www.figma.com/file/UJ5BsuvpQOADF3EPyfvtyv/Icons-WIP?node-id=2244%3A1451

Adding Bug and eng-auto-found labels since this was caught by [HomePageSettingsUI](https://github.com/mozilla-mobile/firefox-ios/blob/main/XCUITests/HomePageSettingsUITest.swift#L130) automated tests as described in Issue #8398

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1754)

**Comment by SimonBasca** [comment]
Verified fix on v34.0 (4722)
