### ISSUE TITLE
FXIOS-1760 ⁃ XCode 12.5 Support

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#8421]
A~S and MappaMundi needs updating to support new XCode 12.5

I was able to build A~S on XCode 12.5 and if someone wants to try out use the following version in Cartfile and also Carfile.resolved.

```java
gitHub "nbhasin2/application-services" "75.2.0b3"
```

Next up is our in-house lib MappaMundi that failed which we should be able to fix (see the error in image below)

^ This is fixed on master branch 

```java
github "mozilla-mobile/MappaMundi" "master"
```

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1760)

**Comment by data-sync-user** [comment]
➤ Nishant Bhasin commented:

Updated: Cartfile

github "getsentry/sentry-cocoa"             ~> 4.2
github "SnapKit/SnapKit"                    ~> 5.0
github "SDWebImage/SDWebImage"              ~> 5.0
github "swisspol/GCDWebServer"              ~> 3.3
github "kif-framework/KIF"                  "v3.7.11"
github "mozilla-mobile/onepassword-app-extension"    "add-framework-support"
github "jrendel/SwiftKeychainWrapper"       ~> 3.2.0
github "DaveWoodCom/XCGLogger"              ~> 7.0
github "cezheng/Fuzi"                       ~> 3.0
github "SwiftyJSON/SwiftyJSON"              ~> 5.0
github "mozilla-mobile/telemetry-ios"      ~> 1.1
github "mozilla-mobile/MappaMundi"          "master"
github "Leanplum/Leanplum-iOS-SDK"          ~> 2.7.2
github "mozilla-services/shavar-prod-lists" "86.0"# Use release version of application-services
gitHub "nbhasin2/application-services"     "75.2.0b3"Updated: Carfile.resolved

github "DaveWoodCom/XCGLogger" "7.0.0"
github "Dev1an/A-Star" "3.0.0-beta-1"
github "Leanplum/Leanplum-iOS-SDK" "2.7.2"
github "SDWebImage/SDWebImage" "5.4.0"
github "SnapKit/SnapKit" "5.0.1"
github "SwiftyJSON/SwiftyJSON" "5.0.0"
github "apple/swift-protobuf" "1.9.0"
github "cezheng/Fuzi" "3.1.1"
github "getsentry/sentry-cocoa" "4.4.3"
github "jrendel/SwiftKeychainWrapper" "3.4.0"
github "kif-framework/KIF" "v3.7.11"
github "mozilla-mobile/MappaMundi" "master"
github "mozilla-mobile/onepassword-app-extension" "68a9d932a6373ca045984fbf4fb9a25aee43284c"
github "mozilla-mobile/telemetry-ios" "v1.1.3"
github "mozilla-services/shavar-prod-lists" "56e01bfb2ee84349289e33ea785dea0946fe0030"
gitHub "nbhasin2/application-services" "75.2.0b3"
github "swisspol/GCDWebServer" "3.5.3"

**Comment by vauxhall** [comment]
MappaMundi issue might be addressed by adding support to SwiftPackageManager.
There is an open PR already considering it: https://github.com/mozilla-mobile/MappaMundi/pull/19

**Comment by muhasturk** [comment]
any ETA for supporting Xcode 12.5? 😳
