### ISSUE TITLE
FXIOS-1761 ⁃ [regression] Edit button for Bookmarks is gone

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#8422]
With the new Library panel redesign, a Done button was introduced on the top right. This replaced the Edit button when inside a bookmark folder.

**Acceptance Criteria**

* when inside a bookmark folder, the top right button says Edit
* the top left still says Back
* on the main Bookmark page, the top right button still says Done

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1761)

**Comment by SimonBasca** [comment]
Verified fix on v34.0 (4722)
