### ISSUE TITLE
Sharing to another application does not always work

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#8426]
Steps to reproduce
1. Open an article on any webpage
2. In page actions menu, click "Share"
3. Choose to share to Instapaper

**Expected results**
Article is opened in Instapaper (try on Safari for example)

**Actual results**
Nothing happens

**Device details**

* iPhone X
* iOS 14.4.2
* Firefox 33.1

Note that this is reported to work on Safari

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2866)

**Comment by SimonBasca** [comment]
I was unable to reproduce the issue sharing an article to Instapaper via Firefox v33.1 and v34.0 (4680)

**Comment by lmarceau** [comment]
Since only `data-sync-user` has commented on the issue after the `Stalebot` GitHub action (which triggered the removal of the `stale` label) I’ll close this issue for now. Please let us know if you think this issue needs to be reopened, we'll gladly do so. Thank you!
