### ISSUE TITLE
FXIOS-1772 ⁃ There is no spacing from the top bookmark panel

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#8431]
## Steps to reproduce
1. Go to bookmark panel
### Expected behavior
- There should be spacing from the Bookmark menu folder to the top bookmark panel as in the design docs. 
### Actual behavior
- There is no spacing from the Bookmark menu folder to the top bookmark panel as in the design docs. 
### Device & build information
* Device: iPhone Xr 14.4
* Build version: 34. (4722)
### Notes
Attachments: 
[Design docs](https://www.figma.com/file/lfgj15zbNkL9Pp4hdZGJgp/MR1?node-id=104%3A17964)

<img width="372" alt="image" src="https://user-images.githubusercontent.com/32130829/117121378-2b213780-ad9d-11eb-9d80-f90bebaea1d5.png">

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1772)

**Comment by dnarcese** [comment]
@SimonBasca could you clarify which space you are referring to?

**Comment by SimonBasca** [comment]
@dnarcese we can close this. I was referring to the spacing between the "bookmark menu" and the top library buttons but it seems they match the design docs perfectly. Sorry for the confusion.
