### ISSUE TITLE
FXIOS-1777 ⁃ New tab counter asset seems smaller

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#8437]
## Steps to reproduce
1. Open Firefox
2. Check the tab counter
### Expected behavior
- The tab counter should have larger height. 
### Actual behavior
- The tab counter asset seems to have a smaller height
### Device & build information
* Device: iPhone Xr 14.4
* Build version: 34.0 (4722)
### Notes
Attachments: 
<img width="375" alt="image" src="https://user-images.githubusercontent.com/32130829/117155162-35efc280-adc5-11eb-84a1-e21d68aba702.png">

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1777)

**Comment by electricRGB** [comment]
Heya, this is the new asset and it's shorter than before.
@brampitoyo can you verify this is as expected?

**Comment by brampitoyo** [comment]
@electricRGB @SimonBasca Yes, indeed. This is a new asset, which is shorter. Have a look at [this Figma artboard](https://www.figma.com/file/UJ5BsuvpQOADF3EPyfvtyv/Icons-WIP?node-id=2326%3A22).

**Comment by SimonBasca** [comment]
Thanks for clarifying. Closing the issue.
