### ISSUE TITLE
FXIOS-1782 ⁃ Can’t close Synced Tab view on iPad

### ISSUE THREAD

**Issue by dnarcese** [mozilla-mobile/firefox-ios#8443]
## Steps to reproduce
1. Open tab tray on iPad
2. Open synced tabs panel

### Expected behavior
Should be a close or done button to close the view
### Actual behavior
No way to close the view except for going back to normal or private tabs and selecting a tab
### Device & build information
* Device: ?
* Build version: v34
### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1782)

**Comment by dnarcese** [comment]
cc @brampitoyo should we add a Done button to this view?

**Comment by brampitoyo** [comment]
@dnarcese Agreed. I mocked up a “Done” action that persists in all sections of the Tabs Tray: Open, Private and Synced Tabs, on this Figma. It was not part of MR1.

https://www.figma.com/file/WboC4Dn9iu9wie2GodfSAg/Post-MR1?node-id=1501%3A1290

On iPadOS, the “Done” action replaces the position of the tab number (square symbol). If you were to press on the same spot twice, you would go in and out of the Tabs Tray.

“Done” would also push the “+” new tab action aside.

**Comment by SimonBasca** [comment]
Verified fix on main 31374a784f.

**Comment by SimonBasca** [comment]
Verified fix on v34.1 (5146).
