### ISSUE TITLE
FXIOS-1783 ⁃ Empty space in synced tab view iPad

### ISSUE THREAD

**Issue by dnarcese** [mozilla-mobile/firefox-ios#8444]
## Steps to reproduce
1. Open tab tray on iPad
2. Go to Synced tabs panel
3. Scroll list
### Expected behavior
No white space under toolbar
### Actual behavior
White space between device name and toolbar that shows the scrolling content.
![A98888DE-7B12-4139-8DFF-EEEC999DF496](https://user-images.githubusercontent.com/11432165/117222006-7442ad00-add8-11eb-8f41-6c1c651f653c.gif)

### Device & build information
* Device: ?
* Build version: 34
### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1783)

**Comment by SimonBasca** [comment]
Verified fix on v34.0 (4847).
