### ISSUE TITLE
FXIOS-1784 ⁃ No border in new Tabs Tray with white background 

### ISSUE THREAD

**Issue by nbhasin2** [mozilla-mobile/firefox-ios#8445]
After a while the tabs in new tabs tray seems to have no border which is likely due to not having screenshot.

![E6612601-93A0-4E4F-8641-984F1AB26C71](https://user-images.githubusercontent.com/8919439/117223838-90e0e400-addc-11eb-92c0-5b594273ecd1.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1784)

**Comment by SimonBasca** [comment]
This is also reproducible after undoing close all tabs.

**Comment by data-sync-user** [comment]
➤ Daniela Arcese commented:

[~bpitoyo@mozilla.com] We probably need to add a border around each tab or change the background colour of the tab; do you have a suggestion for what that should look like?

**Comment by data-sync-user** [comment]
➤ Bram Pitoyo commented:

[~darcese@mozilla.com] I think [~nbhasin@mozilla.com] has proposed a few solutions to this problem and posted it on Slack. The team picked solution #3, and I agree with that. I only added a proposal to slightly change the page background colour from earlier suggested values:

  * Light theme: from LightGrey30 #e0e0e6 to LightGrey20 #f0f0f4
  * Dark theme: from DarkGrey40 #3a3944 to DarkGrey80 #1c1b22

**Comment by SimonBasca** [comment]
Fixed on v34.0 (4795).
