### ISSUE TITLE
FXIOS-1785 ⁃ [Regression] Not possible to go back from Recently Closed menu to History view

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/firefox-ios#8446]
Bug found due to the Recently Closed History automated tests failures : 
https://github.com/mozilla-mobile/firefox-ios/blob/main/XCUITests/HistoryTests.swift#L141

## Steps to reproduce
Go to website and close it
Go to History Panel -> Recently Closed
Try to go to History Panel view
### Expected behavior
User can go back to History Panel 

### Actual behavior
Once user visits Recently Closed there is no way to see the History Panel unless the app is closed an reopen. There used to be a Back button but it has been removed

### Device & build information
* Device: iPhone 11, iOS 14
* Build version: main and latest beta 4722

### Notes
Attachments: 
https://user-images.githubusercontent.com/1897507/117261428-67fa3680-ae50-11eb-9961-57b5dac59151.mov

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1785)

**Comment by isabelrios** [comment]
The swipe gesture to remove items in that Recently Closed panel is not available

**Comment by electricRGB** [comment]
This is a larger issue. I will address it in #8453
