### ISSUE TITLE
[Bug] Long tapping empty search bar offers the option to "Copy address"

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/firefox-ios#8449]
### Prerequisites
Have a fresh install or a clean profile 

## Steps to reproduce
1. Launch Firefox and dismiss the onboarding 
2. Long click the empty search bar

### Expected behavior
"Copy address" option should not be available

### Actual behavior
"Copy address" option is available

### Device & build information
* Device: iPhone X (13.3.1)
* Build version: 34.0 (4722)

### Notes
► Video
![IMG-0277](https://user-images.githubusercontent.com/51314259/117295772-ec62ae80-ae7c-11eb-90de-a02cd0564f68.gif)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2875)

**Comment by lmarceau** [comment]
Since only `data-sync-user` has commented on the issue after the `Stalebot` GitHub action (which triggered the removal of the `stale` label) I’ll close this issue for now. Please let us know if you think this issue needs to be reopened, we'll gladly do so. Thank you!
