### ISSUE TITLE
FXIOS-1789 ⁃ [Bug] Unusable "back" and "edit" button in Library

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/firefox-ios#8450]
## Steps to reproduce
1. Open Bookmarks
2. Open any default folder
3. Tap the "History icon"
4. Tap the "Back" button 
5. Tap the "Edit" button

### Expected behavior
The "Back" button should work
❔ Not sure if the "Edit" button should be available in other Library sections

### Actual behavior
The "Back" button doesn't work
Nothing happens when tapping the "Edit" button

### Device & build information
* Device: iPhone X (13.3.1)
* Build version: 34.0 (4722)

### Notes
❗ Same behavior for downloads and reading list 

► Video
![IMG-0279](https://user-images.githubusercontent.com/51314259/117295901-161bd580-ae7d-11eb-931b-c43c938fde2b.gif)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1789)

**Comment by dnarcese** [comment]
Should be fixed with #8453
