### ISSUE TITLE
FXIOS-1791 ⁃ What's New page not found

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#8451]
## Steps to reproduce
1. Open the Hamburger menu
2. Tap on "What's New"
### Actual behavior
- "Page not found" message is displayed.
### Device & build information
* Device: iPhone SE 14.4
* Build version: 34.0 (4722)
### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1791)

**Comment by data-sync-user** [comment]
➤ Daniela Arcese commented:

I don't think the article has been published yet. This will be taken care of in FXIOS-1627
