### ISSUE TITLE
FXIOS-1790 ⁃ URL bar is not focused when opening a tab via long press on tab counter

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#8452]
## Steps to reproduce
1. Long tap on tab counter
2. Tap "New Tab"
### Expected behavior
- The new tab should open and the URL bar should be focused.
### Actual behavior
- The new tab is opened but the URL bar is not focused.
### Device & build information
* Device: iPhone SE 14.4
* Build version: 34.0 (4722)
### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1790)

**Comment by dnarcese** [comment]
Duplicate of #8488
