### ISSUE TITLE
FXIOS-1793 ⁃ Library Panel state needs to address every subview, and not just bookmarks

### ISSUE THREAD

**Issue by electricRGB** [mozilla-mobile/firefox-ios#8453]
As we can see from [this ticket](https://github.com/mozilla-mobile/firefox-ios/issues/8446) and [this ticket](https://github.com/mozilla-mobile/firefox-ios/issues/8447), the Library Panel is experiencing some navigational difficulties with updating the buttons at the top of the screen.

the LibraryPanelState needs to be updated to account for all these issues.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1793)

**Comment by SimonBasca** [comment]
#8446 is verified fixed on v34.0 (4795). @electricRGB is this issue safe to close?
