### ISSUE TITLE
Tab tray moves to selected tab on slight swipe

### ISSUE THREAD

**Issue by nbhasin2** [mozilla-mobile/firefox-ios#8454]
STR:
- Open tabs tray with few tabs from browser 
- It should automatically select the tab user is on
- Scroll to other tabs
- Slightly swipe tabs tray from top
- Scroll goes back to selected tab and we lose position 

Question: Should it remember the scroll position or go back to selected tab?

https://user-images.githubusercontent.com/8919439/117323575-02f90d80-ae5d-11eb-8906-137dd14485c0.MP4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2876)

**Comment by lmarceau** [comment]
Since only `data-sync-user` has commented on the issue after the `Stalebot` GitHub action (which triggered the removal of the `stale` label) I’ll close this issue for now. Please let us know if you think this issue needs to be reopened, we'll gladly do so. Thank you!
