### ISSUE TITLE
Refresh button has incorrect icon and no functionality after downloading a file

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#8456]
## Steps to reproduce
1. Go to https://www.thinkbroadband.com/download
2. Tap to download a file
3. Tap "Download Now" 
### Actual behavior
- Refresh button has incorrect icon and no functionality after downloading a file or canceling the download prompt
### Device & build information
* Device: iPhone Xr 14.4 
* Build version: 34.0 (4722)
### Notes
Attachments: 
![Picture_2021_05_06T13_49_52_434Z](https://user-images.githubusercontent.com/32130829/117309466-1cb14980-ae8b-11eb-8d9d-0e46bcaba673.jpeg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2877)

**Comment by dnarcese** [comment]
@SimonBasca does this happen every time a download happens? What happens when you try to click the X button?

**Comment by SimonBasca** [comment]
This issue is reproducible every time after tapping on a file to download it and the download prompt is displayed. After the download prompt is displayed tapping "cancel" or accepting to download the file will display the refresh button incorrect. Tapping the "X" button does nothing. 
After opening Tabs Tray the "Refresh" button is correctly displayed and works fine.

**Comment by lmarceau** [comment]
Since only `data-sync-user` has commented on the issue after the `Stalebot` GitHub action (which triggered the removal of the `stale` label) I’ll close this issue for now. Please let us know if you think this issue needs to be reopened, we'll gladly do so. Thank you!
