### ISSUE TITLE
Multiple Snackbar for Same URL

### ISSUE THREAD

**Issue by muhasturk** [mozilla-mobile/firefox-ios#8458]
## Steps to reproduce
- Navigate  `https://www.ensonhaber.com/ `
- Tap menu button on the top right
![Screen Shot 2021-05-06 at 17 57 26](https://user-images.githubusercontent.com/4077401/117320029-871ab780-ae94-11eb-9ea9-e8baec9d23a5.png)

- Scrool down and tap Telegram image.
- It will navigate
`https://t.me/ensonhaber`
- Multiple snackbar appears on site.
![Screen Shot 2021-05-06 at 17 56 56](https://user-images.githubusercontent.com/4077401/117319949-74a07e00-ae94-11eb-9040-4d1bd3f34447.png)

### Expected behavior
One snackbar should appear for one URL.
### Actual behavior
Multiple same snackbar appear for same URL.

### Device & build information
* Device: XR - Sim - Device independant
* Build version: Latest main branch

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2878)

**Comment by lmarceau** [comment]
Since only `data-sync-user` has commented on the issue after the `Stalebot` GitHub action (which triggered the removal of the `stale` label) I’ll close this issue for now. Please let us know if you think this issue needs to be reopened, we'll gladly do so. Thank you!
