### ISSUE TITLE
Awesomebar changes default text when scrolling

### ISSUE THREAD

**Issue by nbhasin2** [mozilla-mobile/firefox-ios#8460]
https://user-images.githubusercontent.com/8919439/117323222-b31a4680-ae5c-11eb-8a6c-9e83bfb16110.MP4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2880)

**Comment by dnarcese** [comment]
This also exists in v33.1, so is probably not a regression.

**Comment by lmarceau** [comment]
Since only `data-sync-user` has commented on the issue after the `Stalebot` GitHub action (which triggered the removal of the `stale` label) I’ll close this issue for now. Please let us know if you think this issue needs to be reopened, we'll gladly do so. Thank you!
