### ISSUE TITLE
Test Local Notification (External) as a channel to inform ios users who haven't yet set up Firefox as Default Browser that "Firefox can now be your default browser in iOS - Tap here to open settings."

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#8464]
Once Leanplum is out of our product, we will not have a solution to build and ship notifications. So we want to begin with an MVP solution by building a local notification, built as a feature of the app, (much like the onboarding flow) that gets scheduled in a user's first session and triggers if they do not set us as default 24 hours after 1st app launch. The targeting and triggering functionality of local notifications may need to be explored further and that may change the final notification plan. Based on the opportunity identified, I would like to get a recommendation on what we could do in the first version of this local notification. One key benefit of building this as a feature is that we will have full-funnel visibility from click to DoU of this notification.

Below you can see 2 notifications Brave sends within 2 hours of app install, The first one is a Default Browser prompt. This gives us a good indication of what this type of notification can look like to the user.

![](https://user-images.githubusercontent.com/33848595/112071583-4efe2600-8b2d-11eb-93d9-e009487e29ec.png)

This is a win-win feature. A user gets a clear actionable prompt to choose Firefox as their default browser while the download and the reasons behind the download are still fresh in their mind. Firefox will get more DoU if the user chooses us as default. Based on past successful Push Notification campaigns we know that sending a notification like this will lead to a higher rate of the default setting in new users and thus higher retention and DoU.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2881)

**Comment by lmarceau** [comment]
Since only `data-sync-user` has commented on the issue after the `Stalebot` GitHub action (which triggered the removal of the `stale` label) I’ll close this issue for now. Please let us know if you think this issue needs to be reopened, we'll gladly do so. Thank you!
