### ISSUE TITLE
FXIOS-1802 ⁃ Face ID is not prompted when trying to autofill paswords via Lockwise

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#8467]
## Preconditions:
- Log in to Lockwise
- Enable Lockwise in Autofill Settings
- Restart the device
## Steps to reproduce
1. Launch Firefox
2. Go to "beatport.com"
3. Tap on the login field
4. Tap on "Passwords" button above the keyboard
5. Select "Lockwise" from the list
### Device & build information
* Device: iPhone Xr (14.4)
* Build version: 34.0 (4722)
### Notes
- This issue usually occurs after restarting the device or leaving the device locked over night.
- Not reproducible in Google Chrome or Safari
Attachments: 
[Video.mp4.zip](https://github.com/mozilla-mobile/firefox-ios/files/6440450/Video.mp4.zip)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1802)

**Comment by dnarcese** [comment]
cc @st3fan

**Comment by st3fan** [comment]
Thank you @SimonBasca - I'll take a peek at this next week. I think it should probably be filed in the Lockwise-ios repository though.

**Comment by SimonBasca** [comment]
I was inclined to think this is more of a Firefox issue than a Lockwise issue because it's not reproducible in Chrome or Safari. Moved to #1250.
