### ISSUE TITLE
FXIOS-1811 ⁃ Measure Pocket Impressions and Key Metrics

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#8481]
**Vision**

Ensure appropriate tracking is in place to measure success of the Pocket sponsor tile

**Acceptance Criteria**

* Tracking in place through Glean to evaluate experiment ([full details](https://docs.google.com/document/d/1oGOECZgUJ65bAXs_BAVss4J-o7MsyU3EjSVMZPEiBKg/edit))
  * Firefox Home impressions (note: if the user has changed their home page to something else, such as Google, those views should not be counted. Only views of Firefox home should be included)
  * Pocket section impressions
  * Pocket story clicks/opens
    * Includes position value (1..10)
    * Approach for tracking these extends to sponsored tile (which may mean we need a value for sponsored/not-sponsored)
  * Turn off/on pocket stories
* New tracking has been reviewed by data stewards to ensure it follows our collection guidelines

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1811)

**Comment by data-sync-user** [comment]
➤ Roux Buciu commented:

Hi [~athomas@mozilla.com] Question about this story: what do we mean by "Firefox Home impressions" for this. Does that mean every time a user sees the FxHomePage with every new tab open, etc?

**Comment by data-sync-user** [comment]
➤ Nishant Bhasin commented:

a) Firefox Home impressions
Enhanced Firefox home page tracking event which tracks when Firefox Home is shown from awesomebar vs bottom right hamburger menu home button.

b) Pocket section impressions
Added Pocket sectionImpressions event to glean that gets sent when user opens Firefox Home and scrolls to Pocket Section or when Pocket Section is shown. This event however gets sent once per view load. It doesn't get sent again if users is in same view.

c) Pocket story clicks/opens
Added Pocket openStoryPosition as labelled counter where the label depicts the position number of pocket story that user opens

Extra: In future we can modify pocket open story event to also accept sponsored tile as another extra data. 🤞🏽

**Comment by SimonBasca** [comment]
Verified fix on v34.1 (5167) 

Check #8709, which might be a case that is not covered. Feel free to close the issue if it's not valid.

**Comment by nbhasin2** [comment]
`open_from_menu_home_button`  also counts views from opening a new tab
