### ISSUE TITLE
FXIOS-1812 ⁃ Icons Refresh - Phase 2

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#8482]
**Vision**

All iOS icons have been updating to match the new designs created for Firefox across devices

**Acceptance Criteria**

* Remaining icons from MR1 refresh have been updated

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1812)

**Comment by SimonBasca** [comment]
@brampitoyo @dnarcese could you please provide the design docs for bug verification. Thanks.

**Comment by dnarcese** [comment]
@SimonBasca I'm not sure we have any that have all the icons. I did a walkthrough of the icons with Bram for verification. I would say for testing maybe just keep an eye out while testing other things in case there are any icons that are the wrong colour, wrong size, etc.

**Comment by SimonBasca** [comment]
Verified fix on v34.0 (4879). The icons look good.
