### ISSUE TITLE
FXIOS-1820 ⁃ Attentive mode is unattentive on long press.

### ISSUE THREAD

**Issue by electricRGB** [mozilla-mobile/firefox-ios#8488]
## Steps to reproduce
1. long press tab icon
2. open new tab

### Expected behavior
It's in attentive mode

### Actual behavior
It's not in attentive mode

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1820)

**Comment by SimonBasca** [comment]
Seems to be a duplicate of #8452 which is already assigned.
