### ISSUE TITLE
FXIOS-1824 ⁃ Can’t delete website data manually

### ISSUE THREAD

**Issue by scarhead7** [mozilla-mobile/firefox-ios#8493]
## Steps to reproduce
- Open Settings -> Data Management -> Website Data
- Attempt to delete more than three entries manually

### Expected behavior
All deleted entries should disappear. 

### Actual behavior
Only three entries will be erased at a time. 

### Device & build information
* Device: iPhone 12
* Build version: Daylight 33.1 (4629)
### Notes
Attachments: 
[RPReplay_Final1620863421.zip](https://github.com/mozilla-mobile/firefox-ios/files/6469587/RPReplay_Final1620863421.zip)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1824)

**Comment by boek** [comment]
@scarhead7 Are you still able to reproduce this issue?

If so I have a couple of questions for you :)
- Which version of iOS are you running? 
- Do you have an idea of how many items are in that list if you expand it to view all items?

**Comment by SimonBasca** [comment]
Related issue https://github.com/mozilla-mobile/firefox-ios/issues/8203

**Comment by scarhead7** [comment]
@boek The issue persists, yes. I’m running iOS 14.5.1 and there are quite a few items. Possibly a few hundred.

**Comment by boek** [comment]
While I was never able to reproduce this issue, after some investigation I think we may be misusing https://developer.apple.com/documentation/webkit/wkwebsitedatastore/1532936-removedata. We could adjust this UI to be a multiselect and provide a loading state using the callback.
