### ISSUE TITLE
Minor visual glitches with Default Browser onboarding

### ISSUE THREAD

**Issue by gutley** [mozilla-mobile/firefox-ios#8505]
## Steps to reproduce
1. While the Default Browser Onboarding screen is displayed, toggle the System appearance from Dark to Light (or vice versa). Parts of the onboarding screen still show the original appearance and are hardly unreadable. E.g:
![IMG](https://user-images.githubusercontent.com/2040690/118286814-c5cef400-b4ca-11eb-8636-9cb3de7d0e11.PNG)UNITO-UNDERSCORE!0003!
1. When using Split view on an iPad, with Firefox set to the thinnest width, the Default Browser Onboarding screen gets clipped at the edges. E.g 

![IMG](https://user-images.githubusercontent.com/2040690/118287285-383fd400-b4cb-11eb-8328-2daacc6ae6cf.PNG)UNITO-UNDERSCORE!0004!

### Expected behavior
The Default Browser Onboarding screen should adapt correctly to the current screen size and Appearance without visual glitches.

### Device & build information
* Device: iPad Gen 5, but same issues on other iPads.
* Build version: 34.0

### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2889)

**Comment by SimonBasca** [comment]
Confirming that this is an issue. Looks bad when the iOS themes switches from light to dark.
![Picture_2021_05_14T15_17_02_019Z](https://user-images.githubusercontent.com/32130829/118291798-a642c600-b4e0-11eb-8f24-79c8ba4eebba.jpeg)

**Comment by lmarceau** [comment]
Since only `data-sync-user` has commented on the issue after the `Stalebot` GitHub action (which triggered the removal of the `stale` label) I’ll close this issue for now. Please let us know if you think this issue needs to be reopened, we'll gladly do so. Thank you!
