### ISSUE TITLE
 Reader mode content is broken on canalmeio.com.br

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#8509]
Environment:
Browser / Version: Firefox Daylight 34.0 (4795)
Operating System: iPod touch iOS 12.5.2 

Steps to reproduce:

```
Navigate to: https://www.canalmeio.com.br/edicoes/2021/04/09/barroso-manda-senado-desengavetar-cpi-da-pandemia/ .
Tap the "Reader mode" icon .
Observe the page .
```

Expected Behavior:
The content is displayed correctly .

Actual Behavior:
The content is broken.

Notes:

* Works as expected using Safari
* Related reader mode issue https://github.com/mozilla-mobile/firefox-ios/issues/8510

![image](https://user-images.githubusercontent.com/32130829/118465811-ef765e00-b70a-11eb-8fa0-f6ae6a6f496c.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2891)

**Comment by lmarceau** [comment]
Since only `data-sync-user` has commented on the issue after the `Stalebot` GitHub action (which triggered the removal of the `stale` label) I’ll close this issue for now. Please let us know if you think this issue needs to be reopened, we'll gladly do so. Thank you!
