### ISSUE TITLE
 Reader mode detected on dopidopi2923.wordpress.com

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#8510]
Browser / Version: Firefox Daylight 34.0 (4795)
Operating System: iPhone Xr 14.4

Steps to Reproduce:
1. Navigate to https://dopidopi2923.wordpress.com/2020/02/11/husky-chuong-294-h/
2. Tap the "Reader mode" icon.
3. Observe the page.

Expected Behavior:
- The content is displayed correctly.

Actual Behavior:
- The content is broken.

Notes:

- The page is not reader-capable in Safari.

https://bugzilla.mozilla.org/attachment.cgi?id=9214632

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2892)

**Comment by data-sync-user** [comment]
➤ Daniela Arcese commented:

This is more of an issue with how the site is setup rather than how we handle reader mode.

**Comment by lmarceau** [comment]
Since only `data-sync-user` has commented on the issue after the `Stalebot` GitHub action (which triggered the removal of the `stale` label) I’ll close this issue for now. Please let us know if you think this issue needs to be reopened, we'll gladly do so. Thank you!
