### ISSUE TITLE
Recently closed tabs are not displayed correctly

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#8514]
## Steps to reproduce
1. Open a few tabs and visit a few pages
2. Close the tabs
3. Got to Library -> History -> Recently
### Expected behavior
- Recently closed tabs should be correctly displayed.
### Actual behavior
- Favicons are not aligned and the site titles are missing.
### Device & build information
* Device: ?
* Build version: ?
### Notes
Attachments: 
[Video.mp4.zip](https://github.com/mozilla-mobile/firefox-ios/files/6494601/Skype_Video.mp4.zip)
 closed

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2894)

**Comment by lmarceau** [comment]
Since only `data-sync-user` has commented on the issue after the `Stalebot` GitHub action (which triggered the removal of the `stale` label) I’ll close this issue for now. Please let us know if you think this issue needs to be reopened, we'll gladly do so. Thank you!
