### ISSUE TITLE
[webcompat] Debug menu option for changing UA

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#8515]
**a) Firefox iOS:**

* Implement a webcompat helper feature in debug menu to help out with overriding UA
* In this debug menu we'll show:
  * Current UA for Desktop and Mobile
  * A button that lets webcompat team to override this (enable / disable)
  * Add place for team to add custom Desktop / Mobile UA!image-2021-05-17-10-54-50-539.png|width=297,height=387!
  * Once the switch is enabled it'll show option to override desktop and mobile UA
  * This would be an app wide override so opening a new tab should use overridden UA
!image-2021-05-17-10-54-50-539.png|id=cp-img!

**b) Webcompat Team:**

* When a user reports an issue with website you can try out the override from debug menu.
* Open Firefox -> Settings ~~> Tap on Firefox App version 5 times~~ > Tap on webcompat debug option
* If wecompat team is able to try out a UA that fixes this issue then we can open a ticket on Firefox iOS side to add it to the list.
Sorry I might make another ticket to implement this debug menu change instead of adding it as a part of discussion ticket just to keep things clear in terms of ticket.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2895)

**Comment by data-sync-user** [comment]
➤ Karl Dubost commented:

seeAlso https://docs.google.com/document/d/1o5uvGxHRMPHHvjI4hd3zwQsdQfAJmbo7QDJQGyUnSYc/edit#

**Comment by lmarceau** [comment]
Since only `data-sync-user` has commented on the issue after the `Stalebot` GitHub action (which triggered the removal of the `stale` label) I’ll close this issue for now. Please let us know if you think this issue needs to be reopened, we'll gladly do so. Thank you!
