### ISSUE TITLE
FXIOS-1841 ⁃ [accessibility] - Instant search text overflows for larger fonts

### ISSUE THREAD

**Issue by nbhasin2** [mozilla-mobile/firefox-ios#8518]
<img width="347" alt="Screen Shot 2021-05-17 at 2 24 11 PM" src="https://user-images.githubusercontent.com/8919439/118537936-8e0abb00-b71b-11eb-9b1b-52c8cfe557b9.png">

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1841)

**Comment by SimonBasca** [comment]
Verified fix on v34.0 (4847).
