### ISSUE TITLE
FXIOS-1843 ⁃ Tab preview is not shown in tab tray

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/firefox-ios#8524]
## Steps to reproduce
Go to tab try with tabs open from several days
### Expected behavior
Preview for each tab is shown
### Actual behavior
Only the title and fav icon is shown for each tab, the content is blank

### Device & build information
* Device: iPhone 6s
* Build version: beta 4847
### Notes
Attachments: 
![IMG_C3012D467B2F-1](https://user-images.githubusercontent.com/1897507/118642499-b8bc4880-b7db-11eb-959e-5e14ccd27a16.jpeg)

Sorry if this is duplicate, I have seen the [border issue](https://github.com/mozilla-mobile/firefox-ios/issues/8445) being fixed, but still reproducing this..

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2061)

**Comment by data-sync-user** [comment]
➤ Daniela Arcese commented:

Solutions:

  * save images to disk
  * come up with some wireframe placeholder images that we can use

**Comment by SimonBasca** [comment]
Fixed by https://github.com/mozilla-mobile/firefox-ios/pull/8847
