### ISSUE TITLE
[Accessibility] Some character are cut in search suggestions

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#8531]
## Steps to reproduce
1. Increase Large Accessibility Size to maximum
1. Tap on the URL bar
1. Type "g"
    1. Actual behavior

* The character "g" is cut in the the Search suggestions
    1. Device & build information
* Device: iPhone Xr (14.4)
* Build version: 34.0 (4847)
    1. Notes
Attachments: 
![URL bar](https://user-images.githubusercontent.com/32130829/118647181-bbbe3580-b7e9-11eb-9e56-fc9e3c9a670a.jpeg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2059)

**Comment by data-sync-user** [comment]
➤ Winnie Teichmann commented:

This is fixed in v108 already.

!Simulator Screen Shot - iPhone 14 Pro Max - 2022-11-28 at 10.38.55.png|width=1290,height=2796!
