### ISSUE TITLE
FXIOS-1853 ⁃ Fix (rename, truncate differently) back action in library

### ISSUE THREAD

**Issue by topotropic** [mozilla-mobile/firefox-ios#8533]
### Why/User Benefit/User Problem
I assume we relabeled the "Back" label for subpages in the library, so currently it read "Bac...ards" for me, which I guess means "Backwards". Would it be possible to re-label it to "Back" or not truncate it? 
<img width="382" alt="image" src="https://user-images.githubusercontent.com/353960/118667252-22485100-b7f4-11eb-9560-649566827492.png">

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1853)

**Comment by SimonBasca** [comment]
This is already fix in the latest beta version. The solution is mentioned here https://github.com/mozilla-mobile/firefox-ios/issues/8447#issuecomment-840688291.
