### ISSUE TITLE
FXIOS-1856 ⁃ Missing localization for some menu items

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#8536]
## Steps to reproduce
1. Open the hamburger menu
### Actual behavior
- Bookmarks, History, Downloads, Passwords, Turn on Night Mode are missing localization. 
### Device & build information
* Device: iPhone Xr
* Build version: 34.0 (4847)
### Notes
Attachments: 
![image](https://user-images.githubusercontent.com/32130829/118672447-ebc50300-b800-11eb-9c65-d72bf2656f77.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1856)

**Comment by Delphine** [comment]
Hello @SimonBasca. Thanks for flagging. It seems the person that has submitted these translations, did not get them approved yet by an approved manager or translator.
I will get in touch with them, so they can look over this work.
So, while this is not ideal, this isn't per say an "issue".

**Comment by SimonBasca** [comment]
@Delphine Thanks. So we can safely close this issue?

**Comment by Delphine** [comment]
Yes! And the translations should be in now (not sure if you can import them in a dot release or not)

**Comment by SimonBasca** [comment]
Fixed in v34.0 (4900)
