### ISSUE TITLE
Can only print in portrait

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#8538]
Copying over from Bugzilla https://bugzilla.mozilla.org/show_bug.cgi?id=1711594

Firefox for iOS only lets me print this in portrait but Safari lets me print it in landscape: http://shared.confessionsofahomeschooler.com/momstuff/deskmate.pdf

Latest version of Firefox for iOS on an updated iPhone 7.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2058)

**Comment by data-sync-user** [comment]
➤ Daniela Arcese commented:

Lets timebox an investigation to a 2 and then decide what the best solution should be.

**Comment by lmarceau** [comment]
Since only `data-sync-user` has commented on the issue after the `Stalebot` GitHub action (which triggered the removal of the `stale` label) I’ll close this issue for now. Please let us know if you think this issue needs to be reopened, we'll gladly do so. Thank you!
