### ISSUE TITLE
FXIOS-1858 ⁃ Ugly Photon Action Sheet on v34 branch

### ISSUE THREAD

**Issue by gutley** [mozilla-mobile/firefox-ios#8539]
I don't know if this is intended (I hope not), but on an iPad this looks ugly compared to the the equivalent on v33 and hard to differentiate touch targets.

<img width="695" alt="image" src="https://user-images.githubusercontent.com/2040690/118682257-31310280-b7f8-11eb-9532-0c24f474df2c.png">

Built from commit 0347f2fba077ef80292b8ea1ccdd0548b20dd61c

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1858)

**Comment by gutley** [comment]
It seems it is that this was caused by 0347f2f. With the previous commit it looks like this:
<img width="719" alt="image" src="https://user-images.githubusercontent.com/2040690/118683340-380c4500-b7f9-11eb-99a8-f53e6091f053.png">

**Comment by isabelrios** [comment]
Thanks for logging this issue but it is a dup of issue #8525
