### ISSUE TITLE
[Bug / Improvement] - Photon action sheet popover on iPad has top cutoff for single item

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#8550]
Below is an image of iPad with popover view for requesting mobile site when you long press on refresh icon. It has a slight cutoff on top. Fixing this requires us to add another check for single item and increase padding.

!image-2021-05-19-15-27-06-752.png|width=373,height=108!

Suggestion: Refactor popover views to accommodate this change.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2053)

**Comment by lmarceau** [comment]
Since only `data-sync-user` has commented on the issue after the `Stalebot` GitHub action (which triggered the removal of the `stale` label) I’ll close this issue for now. Please let us know if you think this issue needs to be reopened, we'll gladly do so. Thank you!
