### ISSUE TITLE
FXIOS-1866 ⁃ TopTabsTestIphone.testCloseTabFromLongPressTabsButton - SmokeXCUITest

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/firefox-ios#8553]
### Bitrise Test Run:
Provide a Bitrise test run report link here showcasing the problem
https://app.bitrise.io/build/fc2c5d8e8e766c30#?tab=log
### Stacktrace:
file:///Users/vagrant/git/XCUITests/FxScreenGraph.swift:CharacterRangeLen=0&EndingLineNumber=333&StartingLineNumber=333 - Failed to synthesize event: Failed to scroll to visible (by AX action) Button, identifier: 'TabToolbar.tabsButton', label: 'Show Tabs', value: 2, error: Error kAXErrorCannotComplete performing AXAction 2003 on element AX element pid: 8754, elementOrHash.elementID: 140194728294496.144. (Underlying Error: Error kAXErrorCannotComplete performing AXAction 2003 on element AX element pid: 8754, elementOrHash.elementID: 140194728294496.144)
### Build:
Main on May 19th: 7f0563e

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2051)

**Comment by isabelrios** [comment]
Failed again on May 20th: 8db7e907d3daa94024270618c23f0c616fba5629

**Comment by AaronMT** [comment]
Seeing this in my PR with the new Github Action (! so it is indeed catching things) https://github.com/mozilla-mobile/firefox-ios/pull/8600/checks?check_run_id=2706630557

**Comment by isabelrios** [comment]
Closing for now
