### ISSUE TITLE
[iPad] Incorrect resize of tabs when changing device orientation

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#8554]
## Steps to reproduce
1. Launch Firefox in portrait
2. Open a few tabs
3. Open Tabs Tray
4. Change device orientation to landscape
5. Change back to portrait
### Actual behavior
- The tabs resize incorrect when changing device orientation in tabs tray.
### Device & build information
* Device: iPad Pro 14.5
* Build version: 34.0 (4879)
### Notes
Attachments: 
![Skype_Picture_2021_05_20T09_41_45_722Z](https://user-images.githubusercontent.com/32130829/118958039-b7208b00-b969-11eb-8e34-02cabc9fd55a.jpeg)

![Skype_Picture_2021_05_20T09_41_52_754Z](https://user-images.githubusercontent.com/32130829/118958084-c0115c80-b969-11eb-968d-0cc5fcf32fef.jpeg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2050)

**Comment by lmarceau** [comment]
Since only `data-sync-user` has commented on the issue after the `Stalebot` GitHub action (which triggered the removal of the `stale` label) I’ll close this issue for now. Please let us know if you think this issue needs to be reopened, we'll gladly do so. Thank you!
