### ISSUE TITLE
FXIOS-1868 ⁃ "What's new" article is mentioning the search engine icon but it's not displayed in the URL bar on the RC version of 34.0 (4879).

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#8555]
## Steps to reproduce
1. Open Hamburger menu
2. Tap "What's new" page
### Expected behavior
- Search engine logo should be displayed in the URL bar. See https://github.com/mozilla-mobile/firefox-ios/issues/6917
### Actual behavior
- The "Whats new page" article is mentioning https://github.com/mozilla-mobile/firefox-ios/issues/6917 but the search engine is not displayed in the URL bar on the RC version of 34.0 (4879).
### Device & build information
* Device: iPhone Xr
* Build version: 34.0 (4879)
### Notes
- The search engine logo is present in the URL bar on the beta version 34.0 (4879) but not on the RC v34.0 (4879)
- Also note that this feature should be added as it is mentioned in the What's New page.
Attachments: 

**Beta version 34.0 (4879)**
![Skype_Picture_2021_05_20T10_58_00_243Z](https://user-images.githubusercontent.com/32130829/118967535-83e2f980-b973-11eb-86ed-53d5803d1b02.jpeg)

**RC version 34.0 (4879)**
![Skype_Picture_2021_05_20T10_58_04_442Z](https://user-images.githubusercontent.com/32130829/118967572-8cd3cb00-b973-11eb-9e29-db8aaa4b8239.jpeg)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1868)

**Comment by dnarcese** [comment]
@SimonBasca both builds are the same so its weird that they would have different behaviour. Maybe there is a bug there?

**Comment by SimonBasca** [comment]
@dnarcese I tried with a clean install on both builds. On the beta version the search engine icon is displayed and on the release the search icon is not displayed.

**Comment by SimonBasca** [comment]
Verified fix on v34.0 (4900).
