### ISSUE TITLE
[iPad] Tab title is not updated

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#8556]
## Steps to reproduce
1. Open a new tab
2. Go to Youtube
3. Tap "Back" to previous page button
### Expected behavior
- Tab title should be "Home"
### Actual behavior
- The tabs title is "Youtube".
### Device & build information
* Device: iPad Pro (14.5)
* Build version: 
### Notes
Attachments: 

![Skype_Picture_2021_05_20T11_07_18_239Z](https://user-images.githubusercontent.com/32130829/118968560-bd683480-b974-11eb-9ee3-3dbe083dd65e.jpeg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2049)

**Comment by SimonBasca** [comment]
Steps to reproduce

1. Open a new tab
2. Go to Youtube
3. Close app from app switcher
4. Launch Firefox
5. Tap "Back" to previous page button

**Comment by lmarceau** [comment]
Since only `data-sync-user` has commented on the issue after the `Stalebot` GitHub action (which triggered the removal of the `stale` label) I’ll close this issue for now. Please let us know if you think this issue needs to be reopened, we'll gladly do so. Thank you!
