### ISSUE TITLE
FXIOS-1870 ⁃ Tab Title can become unreadable when System Appearance changes

### ISSUE THREAD

**Issue by gutley** [mozilla-mobile/firefox-ios#8557]
## Steps to reproduce
On an iPad:

1. Create 2 tabs
2. Toggle system appearance from Light to dark (or sit then until it automatically happens!)
3. Click on the non-active tab
4. It gets drawn with white text on a white background

(See see recording)

A similar thing happens when going from Dark to Light mode, but with dark text on a dark background

### Expected behavior
It should draw with light text on a dark background
### Actual behavior
It draws with light text on a light background

### Device & build information
* Device: iPad (any)
* Build version: From f06f4c960d03600ac3f7ab897c64e8e0dcd0d83b, but possibly been there longer
### Notes
Attachments: 
Going from Light to dark:
https://user-images.githubusercontent.com/2040690/118990082-7d0bb500-b97a-11eb-8434-24457767a69f.mov

Going from Dark to Light:
<img width="926" alt="image" src="https://user-images.githubusercontent.com/2040690/118990936-38344e00-b97b-11eb-95e1-af56c0693edc.png">

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1870)

**Comment by swrobel** [comment]
Seeing the same issue. Firefox 34 on iPad. The white on white effect is sporadic. 
![image](https://user-images.githubusercontent.com/157270/121292495-e8241980-c89e-11eb-841d-30599302272a.jpeg)

**Comment by SimonBasca** [comment]
Verified fix on v34.1 (5146)
