### ISSUE TITLE
Night Mode vs Appearance changes anomaly 

### ISSUE THREAD

**Issue by gutley** [mozilla-mobile/firefox-ios#8558]
## Steps to reproduce
Start out with iPad in Light Appearance and Night Mode turned off.
Turn on Night mode
Switch to Dark Appearance
Switch back to Light Appearance

Here's a recording - I spilt the view to have Maps app next to it to make it obvious when Dark Appearance was actually active

https://user-images.githubusercontent.com/2040690/119008117-c8798f80-b989-11eb-81d5-737d5f119e9c.mov

### Expected behavior
The non-web based UI should still be in Night mode
### Actual behavior
The non-web ui changes to non-night mode while the Web content is still in Nigth mode
### Device & build information
* Device: iPAd - Any
* Build version: Using f06f4c960d03600ac3f7ab897c64e8e0dcd0d83b, but probably been around before then
### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2048)

**Comment by dnarcese** [comment]
This is expected behaviour. Currently, the app theme is separate from night mode. If you Theme setting is set to "system" then when your phone enters light mode, Firefox will too, but we still respect your night mode setting independently.
