### ISSUE TITLE
Create PDF - Text can't read

### ISSUE THREAD

**Issue by BigSamSampson** [mozilla-mobile/firefox-ios#8559]
## Steps to reproduce
1. Open the firefox 
2. go to www.slamdunk.ru
3. Tap on button share
4. Select "Create PDF"
### Expected behavior
PDF page have text which can read
### Actual behavior
PDF page have text which can't read
### Device & build information
* Device: iPhone 5S - iOS 12.2 , iphone 7 plus - iOS 14.5.1
* Build version: firefox daylight 33.1.4629
### Notes
Attachments: 
![image](https://user-images.githubusercontent.com/66958331/119012157-72631700-b99e-11eb-8e91-e42a3cc5b58d.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2047)

**Comment by dnarcese** [comment]
Can also reproduce by clicking share > Markup. The title and date at the top are overlapping. 
Not reproducible in Safari.

**Comment by lmarceau** [comment]
Since only `data-sync-user` has commented on the issue after the `Stalebot` GitHub action (which triggered the removal of the `stale` label) I’ll close this issue for now. Please let us know if you think this issue needs to be reopened, we'll gladly do so. Thank you!
