### ISSUE TITLE
FXIOS-1873 ⁃ TestSQLiteHistoryTransactionUpdate.testUpdateInTransaction - Unit test

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/firefox-ios#8562]
This unit test is intermittently failing.

### Bitrise Test Run:
Provide a Bitrise test run report link here showcasing the problem
https://app.bitrise.io/build/a36e74a284f42b4e#?tab=log

### Stacktrace:
ile:///Users/vagrant/git/StorageTests/TestSQLiteHistory.swift:CharacterRangeLen=0&EndingLineNumber=1644&StartingLineNumber=1644 - XCTAssertTrue failed

### Build:
Main May 20th 8db7e907d3daa94024270618c23f0c616fba5629

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1873)

**Comment by SimonBasca** [comment]
Failed on 24 May https://app.bitrise.io/build/1c8d6a9755c5a9dd#?tab=log
