### ISSUE TITLE
Arrow keys do not work in the location bar when fully selected

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-ios#8565]
Reported from https://github.com/mozilla-mobile/focus-ios/issues/1848#issuecomment-845582018

## Steps to reproduce:

1. Visit a web page
2. Make the Location Bar active by typing ⌘-L
3. Press → (Right Arrow) to move the cursor to the end of the (fully) selected URL

## Expected

The text in the Location Bar is not selected anymore, the cursor is at the end and you can type to append text to the URL.

## Actual

Nothing happens.

Interestingly ⌘-→ and Control-e do work correctly but it is expected that simply typing → (Right Arrow) has the same effect: this works in any other iOS and Mac application.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2046)

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verifying as fix on v110 (26107).
