### ISSUE TITLE
[Accessibility] Long website titles are cut in home panel context menu

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#8569]
## Steps to reproduce
1. Increase text size to maximum 
1. Long press on a website shortcut that has a long title
    1. Device & build information

* Device: iPad Pro 3rd generation (14.5)
* Build version: 34.0 (4900)
    1. Notes
Attachments: 
![0CC58B03-DF0B-49BA-BE95-E64B4844041A](https://user-images.githubusercontent.com/32130829/119345947-3b447c80-bca2-11eb-948d-2e063f304e9e.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2044)

**Comment by data-sync-user** [comment]
➤ Tiffanie Shakespeare commented:

Laurie Marceau it looks like you tagged ‘needs-ux’. can you help me understand what the ask is? thanks!

**Comment by data-sync-user** [comment]
➤ Laurie Marceau commented:

Tiffanie Shakespeare Not sure why I added that 😬 I removed the label.

**Comment by data-sync-user** [comment]
➤ Catalin Suciu commented:

Verifying as fixed on v9000 (22848)
