### ISSUE TITLE
FXIOS-1883 ⁃ [Test Failure] - testUpdateInTransaction

### ISSUE THREAD

**Issue by nbhasin2** [mozilla-mobile/firefox-ios#8574]
This test has been failing in a lot of PRs even when its not related hence making an issue to capture work involved to fix it. 

```
Failing tests:
	StorageTests:
		TestSQLiteHistoryTransactionUpdate.testUpdateInTransaction()
```

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1883)

**Comment by electricRGB** [comment]
Closing this as @q2r5 has made a PR that fixes it. :)
