### ISSUE TITLE
FXIOS-1884 ⁃ External links Snackbar doesn't show without a WebView

### ISSUE THREAD

**Issue by gutley** [mozilla-mobile/firefox-ios#8576]
## Steps to reproduce

1. Close any Tabs and leave yourself on the Firefox Home Screen (with Top Site, Pocket etc)
2. Click the address bar and then click the Scan QR code button
3. Scan a QR code that will generate an external link (e.g sms or mailto)

### Expected behavior
It should ask if I want to open the external link in the 'Snackbar' alert

### Actual behavior
Other than the page load status bar showing a constant ~10% completion, nothing happens.

To trigger the alert you have to click on a URL in that Firefox Home Screen, at which point it will show the Snackbar

See screen recording below

### Device & build information
* Device: Any Device
* Build version: 33.1 (4629)
### Notes
Attachments: 

https://user-images.githubusercontent.com/2040690/119478585-d3487180-bd47-11eb-933a-ee2a2a49ff41.mov

Here is q QR code for the simple "sms:1234"
<img width="223" alt="image" src="https://user-images.githubusercontent.com/2040690/119478829-0ab71e00-bd48-11eb-8117-646d57c23616.png">

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1884)

**Comment by SimonBasca** [comment]
This seems to be the same as #7899. @gutley can we close this as we are already tracking the issue?

**Comment by gutley** [comment]
> This seems to be the same as #7899. @gutley can we close this as we are already tracking the issue?

Sure, but maybe link back to here to ensure the QR-code scanning use case isn't missed
