### ISSUE TITLE
Update Bitrise to get rid of leanplum variable setup 

### ISSUE THREAD

**Issue by nbhasin2** [mozilla-mobile/firefox-ios#8579]
Lets remove leanplum variable setup from bitrise yml

We can remove the following: 

a) https://github.com/mozilla-mobile/firefox-ios/blob/935c84f99c12fd5893e5987bd2bfa12093eab6c5/bitrise.yml#L851-L879

b) https://github.com/mozilla-mobile/firefox-ios/blob/935c84f99c12fd5893e5987bd2bfa12093eab6c5/bitrise.yml#L1708-L1723

c) We should also update Bitrise to remove leanplum secrets

_Originally posted by @nbhasin2 in https://github.com/mozilla-mobile/firefox-ios/issues/8561#issuecomment-847949142_

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2042)

**Comment by data-sync-user** [comment]
➤ Nishant Patel commented:

Raised a PR to address this https://github.com/mozilla-mobile/firefox-ios/pull/8584. ( https://github.com/mozilla-mobile/firefox-ios/pull/8584. )
