### ISSUE TITLE
FXIOS-1886 ⁃ Update Camera Description and Microphone string

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#8580]
Update the following string in our app and send for localization.

a) NSCameraUsageDescription:

【 highlighted #0747a6 】**Firefox uses your camera to scan QR codes and take photos and video.**【 end highlighted 】

b) NSMicrophoneUsageDescription:

**【 highlighted #0747a6 】Firefox uses your microphone to record and upload audio.【 end highlighted 】**

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1886)

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verified fix for the camera permission on main fa52d3d9b.

For the microphone permission there seems to be a bug. See https://jira.mozilla.com/browse/FXIOS-1897

**Comment by SimonBasca** [comment]
Verified fix on v34.1 (5146) for both strings, camera and microphone.
