### ISSUE TITLE
FXIOS-1891 ⁃ Update shavar lists to point to branch 89 - after June 1st

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/firefox-ios#8587]
We currently are on 86, in order to update normalized lists have to be created manually. Since the 89 version is planned for June 1st and Se Yeon will work on creating those lists, we can update to that one.

For more info see this [thread on Focus](https://github.com/mozilla-mobile/focus-ios/pull/1855#discussion_r640725841).

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1891)

**Comment by SimonBasca** [comment]
Tracking protection tests executed at https://testrail.stage.mozaws.net/index.php?/runs/view/44246&group_by=cases:section_id&group_order=asc&group_id=5994. 

Verifyng as fix on v34.1 (5146).
