### ISSUE TITLE
Remove Snapkit

### ISSUE THREAD

**Issue by boek** [mozilla-mobile/firefox-ios#8592]
* [x] `RustFxA/FirefoxAccountSignInViewController.swift`
* [ ] `Client/Extensions/SnapKitExtensions.swift`
* [x] `Client/Frontend/DefaultBrowserOnboarding/DefaultBrowserOnboardingViewController.swift`
* [x] `Client/BottomSheet/BottomSheetViewController.swift`
* [ ] `Client/Frontend/AuthenticationManager/PasscodeViews.swift`
* [ ] `Client/Frontend/AuthenticationManager/BasePasscodeViewController.swift`
* [ ] `Client/Frontend/AuthenticationManager/PagingPasscodeViewController.swift`
* [ ] `Client/Frontend/AuthenticationManager/PasscodeEntryViewController.swift`
* [x] `Client/Frontend/AuthenticationManager/SensitiveViewController.swift`
* [ ] `Client/Frontend/Browser/Tabs/ChronologicalTabsViewController.swift`
* [ ] `Client/Frontend/Browser/Tabs/TabMoreMenuViewController.swift`
* [ ] `Client/Frontend/Browser/Tabs/TabTableViewCell.swift`
* [x] `Client/Frontend/Browser/Tabs/EmptyPrivateTabsView.swift`
* [ ] `Client/Frontend/Browser/Tabs/TabTableViewHeader.swift`
* [ ] `Client/Frontend/Browser/Tabs/TabMoreMenuHeader.swift`
* [x] `Client/Frontend/Browser/Tabs/TabTrayViewController.swift`
* [x] `Client/Frontend/Browser/Tabs/RemoteTabsPanel.swift`
* [x] `Client/Frontend/Browser/BackForwardListAnimator.swift`
* [x] `Client/Frontend/Browser/BackForwardListViewController.swift`
* [x] `Client/Frontend/Browser/BackForwardTableViewCell.swift`
* [ ] `Client/Frontend/Browser/BrowserViewController/BrowserViewController+FindInPage.swift`
* [ ] `Client/Frontend/Browser/BrowserViewController/BrowserViewController+WebViewDelegates.swift`
* [ ] `Client/Frontend/Browser/BrowserViewController.swift`
* [ ] `Client/Frontend/Browser/ButtonToast.swift`
* [ ] `Client/Frontend/Browser/DownloadToast.swift`
* [ ] `Client/Frontend/Browser/FindInPageBar.swift`
* [x] `Client/Frontend/Browser/QRCodeViewController.swift`
* [x] `Client/Frontend/Browser/ReaderModeBarView.swift`
* [ ] `Client/Frontend/Browser/SearchViewController.swift`
* [ ] `Client/Frontend/Browser/SimpleToast.swift`
* [ ] `Client/Frontend/Browser/TabLocationView.swift`
* [ ] `Client/Frontend/Browser/TabPeekViewController.swift`
* [ ] `Client/Frontend/Browser/TabToolbar.swift`
* [ ] `Client/Frontend/Browser/GridTabViewController.swift`
* [x] `Client/Frontend/Browser/Toast.swift`
* [x] `Client/Frontend/Browser/TopTabsViewController.swift`
* [x] `Client/Frontend/Browser/TopTabsViews.swift`
* [ ] `Client/Frontend/Browser/URLBarView.swift`
* [ ] `Client/Frontend/Extensions/DevicePickerViewController.swift`
* [x] `Client/Frontend/Extensions/InstructionsViewController.swift`
* [ ] `Client/Frontend/Home/FirefoxHomeViewController.swift`
* [ ] `Client/Frontend/Widgets/FirefoxHomeHighlightCell.swift`
* [ ] `Client/Frontend/Home/FirefoxHomeTopSitesCell.swift`
* [ ] `Client/Frontend/Home/DefaultBrowserCard.swift`
* [ ] `Client/Frontend/Home/ASFooterView.swift`
* [ ] `Client/Frontend/Home/ASHeaderView.swift`
* [ ] `Client/Frontend/Home/ASLibraryCell.swift`
* [ ] `Client/Frontend/Home/LibraryShortcutView.swift`
* [x] `Client/Frontend/EnhancedTrackingProtection/ETPCoverSheetViewController.swift`
* [ ] `Client/Frontend/Update/UpdateViewController.swift`
* [ ] `Client/Frontend/Update/UpdateCoverSheetTableViewCell.swift`
* [x] `Client/Frontend/Intro/IntroViewController.swift`
* [x] `Client/Frontend/Intro/IntroScreenSyncView.swift`
* [x] `Client/Frontend/Intro/IntroScreenWelcomeView.swift`
* [x] `Client/Frontend/Library/DownloadsPanel.swift`
* [x] `Client/Frontend/Library/HistoryPanel.swift`
* [x] `Client/Frontend/Library/LibraryViewController/LibraryViewController.swift`
* [x] `Client/Frontend/Library/ReaderPanel.swift`
* [x] `Client/Frontend/Library/RecentlyClosedTabsPanel.swift`
* [x] `Client/Frontend/Library/LibraryPanelButton.swift`
* [ ] `Client/Frontend/Login Management/LoginListViewController.swift`
* [ ] `Client/Frontend/Login Management/LoginListTableViewCell.swift`
* [ ] `Client/Frontend/Settings/LoginDetailViewController.swift`
* [ ] `Client/Frontend/Login Management/LoginDetailTableViewCell.swift`
* [ ] `Client/Frontend/Login Management/NoLoginsView.swift`
* [ ] `Client/Frontend/Login Management/BreachAlertsDetailView.swift`
* [x] `Client/Frontend/Reader/ReaderModeStyleViewController.swift`
* [ ] `Client/Frontend/Settings/ContentBlockerSettingViewController.swift`
* [ ] `Client/Frontend/Settings/AppSettingsOptions.swift`
* [ ] `Client/Frontend/Settings/CustomSearchViewController.swift`
* [ ] `Client/Frontend/Settings/SettingsContentViewController.swift`
* [ ] `Client/Frontend/Settings/SettingsLoadingView.swift`
* [ ] `Client/Frontend/Settings/SettingsTableViewController.swift`
* [ ] `Client/Frontend/Settings/ThemeSettingsController.swift`
* [ ] `Client/Frontend/Settings/WebsiteDataManagementViewController.swift`
* [ ] `Client/Frontend/Settings/WebsiteDataSearchResultsViewController.swift`
* [ ] `Client/Frontend/Theme/ThemedWidgets.swift`
* [x] `Client/Frontend/Widgets/PhotonActionSheet/PhotonActionSheet.swift`
* [x] `Client/Frontend/Widgets/PhotonActionSheet/PhotonActionSheetCell.swift`
* [x] `Client/Frontend/Widgets/PhotonActionSheet/PhotonActionSheetWidgets.swift`
* [x] `Client/Frontend/Widgets/PhotonActionSheet/SyncMenuButton.swift`
* [ ] `Client/Frontend/Widgets/PhotonActionSheet/TrackingProtectionMenu.swift`
* [x] `Client/Frontend/Widgets/BadgeIcon.swift`
* [ ] `Client/Frontend/Widgets/DrawerViewController.swift`
* [x] `Client/Frontend/Widgets/ErrorToast.swift`
* [x] `Client/Frontend/Widgets/HistoryBackButton.swift`
* [x] `Client/Frontend/Widgets/OneLineCellAndFooter.swift`
* [ ] `Client/Frontend/Widgets/SearchInputView.swift`
* [x] `Client/Frontend/Widgets/SiteTableViewController.swift`
* [ ] `Client/Frontend/Widgets/SnackBar.swift`
* [ ] `Client/Frontend/Widgets/TabsButton.swift`
* [ ] `Client/Frontend/Widgets/TextFieldTableViewCell.swift`
* [x] `Client/Frontend/Widgets/TwoLineCellAndFooter.swift`
* [x] `Client/Frontend/Widgets/NewTabButton.swift`
* [x] `Extensions/Today/TodayViewController.swift`
* [x] `Extensions/Today/ImageButtonWithLabel.swift`
* [x] `Extensions/Today/ButtonWithSublabel.swift`
* [ ] `Extensions/ShareTo/InitialViewController.swift`
* [x] `Extensions/ShareTo/ShareViewController.swift`

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2040)

**Comment by data-sync-user** [comment]
➤ Yoana Rios Diaz commented:

Items that should be a ticket on its own because SnapKit is used in a many places:

  * Client/Frontend/Browser/URLBarView.swift 
  * Client/Frontend/Browser/Tabs/RemoteTabsPanel.swift
  * Client/Frontend/Browser/BrowserViewController.swift
  * Client/Frontend/Reader/ReaderModeStyleViewController.swift

**Comment by data-sync-user** [comment]
➤ Laurie Marceau commented:

Closing task since this will be tracked with epic https://mozilla-hub.atlassian.net/browse/FXIOS-5418 ( https://mozilla-hub.atlassian.net/browse/FXIOS-5418|smart-link )  instead
