### ISSUE TITLE
FXIOS-1893 ⁃ Build is failing due to missing libswiftXCTest in the MappaMundi dependency.

### ISSUE THREAD

**Issue by LeonidCBR** [mozilla-mobile/firefox-ios#8593]
Output of a command "**sh ./bootstrap.sh**":

	Building scheme "MappaMundi" in MappaMundi.xcodeproj
	Build Failed
		Task failed with exit code 65...

Log file:

	ld: library not found for -lswiftXCTest
	clang: error: linker command failed with exit code 1 (use -v to see invocation)
	** ARCHIVE FAILED **

Reason:

	Cartfile.resolved has an old commit version
	(github "mozilla-mobile/MappaMundi" "1d17845e4bd6077d790aca5a2b4a468f19567934")

In the last verified commit of MappaMundi libswiftXCTest was replaced by libXCTestSwiftSupport.

Using github "mozilla-mobile/MappaMundi" "9e8ad3ce7a45e2431e551420602f0eeb4300b2a6" in Cartfile.resolved fixes this problem.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2039)

**Comment by dnarcese** [comment]
Related to #8421

**Comment by lmarceau** [comment]
Closing since #8421 was fixed.
