### ISSUE TITLE
FXIOS-1894 ⁃ TestNewTabSettingsTest.testChangeNewTabSettingsShowCustomURL()

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#8594]
### Bitrise Test Run:
Provide a Bitrise test run report link here showcasing the problem
https://app.bitrise.io/build/d89ca8490a0951df#?tab=log
### Stacktrace:
file:///Users/vagrant/git/XCUITests/NewTabSettings.swift:CharacterRangeLen=0&EndingLineNumber=60&StartingLineNumber=60 - Failed to synthesize event: Failed to scroll to visible (by AX action) Button, identifier: 'TabToolbar.menuButton', label: 'Menu', error: Error kAXErrorCannotComplete performing AXAction 2003 on element AX element pid: 8564, elementOrHash.elementID: 140537377407680.144. (Underlying Error: Error kAXErrorCannotComplete performing AXAction 2003 on element AX element pid: 8564, elementOrHash.elementID: 140537377407680.144)
### Build:
12b3a96f3cf5b05959f64923466e6b3f20018865

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2038)

**Comment by isabelrios** [comment]
Closing for now
