### ISSUE TITLE
Unable to add bookmark as subfolder when the folder is created

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#8597]
## Steps to reproduce
1. Go to Bookmarks -> Mobile Bookmarks and tap "+" button
2. Create one folder "Folder 1"
3. Tap "+" button
4. Tap "New Folder"
5. Type "Folder 2"
6. Try adding "Folder 2" as sub folder for "Folder 1"
### Actual behavior
- The option to add "Folder 2" as sub folder for "Folder 1" is unavailable when creating "Folder 2". After creating "Folder 2", it can be added as sub folder "Folder 1".
### Device & build information
* Device: iPhone 8 (14.4)
* Build version: 2db78a49c166
### Notes
- After creating "Folder 2", it can be added as sub folder "Folder 1".
- Same issue when creating bookmarks https://github.com/mozilla-mobile/firefox-ios/issues/8652
Attachments: 
<img width="418" alt="image" src="https://user-images.githubusercontent.com/32130829/119981352-347d7880-bfc6-11eb-81cf-1357d975f6c1.png">

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2037)

**Comment by lmarceau** [comment]
Since only `data-sync-user` has commented on the issue after the `Stalebot` GitHub action (which triggered the removal of the `stale` label) I’ll close this issue for now. Please let us know if you think this issue needs to be reopened, we'll gladly do so. Thank you!
