### ISSUE TITLE
FXIOS-1899 ⁃ Japanese translation of "History" in Firefox Daylight v34 (4920) is incorrect 

### ISSUE THREAD

**Issue by Ryo-ryomac** [mozilla-mobile/firefox-ios#8604]
## Steps to reproduce
1) Set the iOS device to Japanese environment. 
2) Open Firefox v34 (4920) for iOS 
3) Open the hamburger menu at the bottom right of the screen .

### Expected behavior
Japanese meaning "History" is displayed as "履歴" .
That's the style, even for the desktop version of Firefox. 

### Actual behavior
"History" is displayed as "歴史" 

### Device & build information
* Device: iOS 
* Build version: Firefox Daylight v34(4920) 
### Notes
Attachments: 
![20210530-Firefox34-iOS](https://user-images.githubusercontent.com/85042059/120087757-986a8300-c125-11eb-9126-212171739dbb.PNG)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1899)

**Comment by data-sync-user** [comment]
➤ Daniela Arcese commented:

[~dlebedel@mozilla.com] what is the process for issues like these? Do you have a way of verifying if the translation is wrong and then getting it corrected?

**Comment by Delphine** [comment]
@dnarcese I checked against our tool Transvision, and it appears the term should in fact be updated: https://transvision.mozfr.org/?recherche=%E5%B1%A5%E6%AD%B4&repo=gecko_strings&sourcelocale=ja&locale=en-US&search_type=strings
I will contact localizer about this and let you know once this is resolved

**Comment by marsf** [comment]
It's my fault. I've just fixed it on Pontoon.
Thank you!

**Comment by Ryo-ryomac** [comment]
Thank you very much
