### ISSUE TITLE
Unable to share on WhatsApp or Bip from Firefox browser

### ISSUE THREAD

**Issue by BigSamSampson** [mozilla-mobile/firefox-ios#8606]
## Steps to reproduce
1-Open firefox browser 
2-The following pdf file is opened via Bip
https://www.download.p4c.philips.com/files/h/hd9630_90/hd9630_90_rbl_tur.pdf
3-Click on ''share page with''  from the menu
4-Select the Bip application and click the ''share'' button.
### Expected behavior
the file must be shared in Bip app without displaying error , the following url should be shared;
https://www.download.p4c.philips.com/files/h/hd9630_90/hd9630_90_rbl_tur.pdf 
### Actual behavior
When sharing the pdf file, it directly shares the path of the file from which the pdf was downloaded.
Error message appears when sharing files from firefox browser to Bip app , the following url has been shared; 
file:///private/var/mobile/Containers/Data/Application/64241768-91A0-482B-8053-02B785B6638E/tmp/TempDocs/hd9630_90_rbl_tur.pdf 
### Device & build information
* Device: iphone 7 plus - ios 14.5.1 , iphone 7 - ios 13.7
* Build version: Firefox Daylight 33.1(4629)
### Notes
Attachments: 
![image](https://user-images.githubusercontent.com/66958331/120180708-c5499380-c214-11eb-9ede-4984de7f0982.png)

![image](https://user-images.githubusercontent.com/66958331/120181783-389fd500-c216-11eb-91ee-4548faf68ff4.png)

https://user-images.githubusercontent.com/66958331/120181449-c0d1aa80-c215-11eb-879f-f162610bf947.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2035)

**Comment by lmarceau** [comment]
Since only `data-sync-user` has commented on the issue after the `Stalebot` GitHub action (which triggered the removal of the `stale` label) I’ll close this issue for now. Please let us know if you think this issue needs to be reopened, we'll gladly do so. Thank you!
