### ISSUE TITLE
[Placeholder] Test Removing Default Browser Onboarding

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#8611]
**Vision**

To understand if the default browser onboarding card is effective and worth showing to all new users

**Acceptance Criteria**

* A/B Experiment set up where
  * Control is current experience (onboarding card shown to new users on 3rd run without FF set as default)
  * Treatment is no default browser onboarding card is shown
* Metrics in place to measure results (should be existing)
  * Clicks on "Go To Settings" on the default browser onboarding card
  * Clicks to dismiss the defualt browser onboarding card
  * Open browser as default probe

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2034)

**Comment by lmarceau** [comment]
Since only `data-sync-user` has commented on the issue after the `Stalebot` GitHub action (which triggered the removal of the `stale` label) I’ll close this issue for now. Please let us know if you think this issue needs to be reopened, we'll gladly do so. Thank you!
