### ISSUE TITLE
FXIOS-1903 ⁃ A/B Test Default Browser Onboarding Card

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#8612]
**Vision**

To determine if an updated design that will look better across more device sizes and versions will hurt out sign-up rate for default browser

**Acceptance Criteria**

* A/B test set up for the onboarding card where:
  * Control uses the current behaviour & design of the default browser onboarding card
  * Treatment uses the current behaviour & [new design](https://www.figma.com/file/3ICmMVvNYMbPV0gfVWCij5/Default-Browser?node-id=702%3A5385) for the default browser onboarding card
* Confirmed that all metrics needed to measure success are available
  * Clicks on Go To Settings from the default browser onboarding card
  * Open as default browser metric
  * Metric to identify the test group
* Both dark and light mode should be supported for both experiment groups
* All device types (including iPad) should be supported for both experiment groups
* All locales should be supported for both experiment groups
* Only users with the flag on to be in studies & send usage data are included in the A/B test

**Notes**

* Design https://www.figma.com/file/3ICmMVvNYMbPV0gfVWCij5/Default-Browser?node-id=702%3A5385
* Experiment Brief: https://docs.google.com/document/d/1UHKm_ko0zl_Q31aNwQwux2GK3-00IuVm55DJZs9mh1U/edit#

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1903)

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

I am unable to see the new on-boarding design on v34.1(5186). I have enabled both "Send Usage Data" and "Studies" from Settings.

Tapping on the "Learn More" button on the default browser card from the homepage does not show the new on-boarding card. I am seeing the old one with the the image. See screenshot.

[~jboek@mozilla.com] am I missing any steps in seeing the new card?

**Comment by dnarcese** [comment]
@SimonBasca my understanding is that we still have to turn the test on on the Nimbus side.

**Comment by SimonBasca** [comment]
@dnarcese thanks for the quick answer. So for now this cannot be tested?

**Comment by dnarcese** [comment]
I'll let @boek confirm that.

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

I discussed with the nimbus testing team about this, they will verify the issue.
