### ISSUE TITLE
FXIOS-1905 ⁃ Adds a device-tablet to the webcompat reporting URL

### ISSUE THREAD

**Issue by karlcow** [mozilla-mobile/firefox-ios#8614]
### Why/User Benefit/User Problem
Currently when users are reporting issues with Firefox iOS on iPad. it is very hard to guees if it is an ipad or iphone type device.

### Acceptance Criteria (how do I know when I’m done?)
When this code knows how to discriminate in between iPad and Mobile.
https://github.com/mozilla-mobile/firefox-ios/blob/579af98fd99116b6bd481503de649c6d301ddf2c/Shared/SupportUtils.swift#L27

### Not included
I'll provide a patch.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1905)

**Comment by karlcow** [comment]
@dnarcese https://github.com/mozilla-mobile/firefox-ios/pull/8615/
Pull request done for this.

**Comment by SimonBasca** [comment]
Verified fix on main 70fdda04eeb4d06e

**Comment by SimonBasca** [comment]
Verified fix on v34.1 (5146)
