### ISSUE TITLE
FXIOS-1908 ⁃ When clicking start broswing on the tour page it sends you to firefox china

### ISSUE THREAD

**Issue by bruhdev1290** [mozilla-mobile/firefox-ios#8620]
## Steps to reproduce

Go to settings 

Go to show your option 

Click next

Then click start Broswing

### Expected behavior 

It should not open up the firefox china page

### Actual behavior
It shows the firefox china page
### Device & build information
* Device: iPhone se 2nd gen
* Build version: 34.0 (4920

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1908)

**Comment by dnarcese** [comment]
@bruhdev1290 what locale is your phone set to?

**Comment by bruhdev1290** [comment]
Fixed this issue by reinstalling Firefox
