### ISSUE TITLE
testDefaultBrowser is failing because there is no "Default browser" option on Bitrise

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#8627]
## Steps to reproduce
1. Check https://addons-testing.bitrise.io/builds/f127217a91f3f7cd/testreport/3406315b-01cb-4f81-87fa-a84869fd1e20/testsuite/0/testcases?status=failed 
### Expected behavior
- From what I understand, testDefaultBrowser should be working on Bitrise. The entitlement should be added back in on BR so any BR builds will behave properly. See https://github.com/mozilla-mobile/firefox-ios/pull/8513
### Actual results:
- testDefaultBrowser is failing on Bitrise because there is no "Default browser" option.
Attachments: 
Bitrise screenshot
![image](https://user-images.githubusercontent.com/32130829/120621596-ae9a7b00-c466-11eb-92cd-7a85d424f377.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2028)

**Comment by SimonBasca** [comment]
@electricRGB could you please take a look at this when you have time? It's not something with high priority. Thank you.

**Comment by lmarceau** [comment]
Since only `data-sync-user` has commented on the issue after the `Stalebot` GitHub action (which triggered the removal of the `stale` label) I’ll close this issue for now. Please let us know if you think this issue needs to be reopened, we'll gladly do so. Thank you!
