### ISSUE TITLE
Provide a notification that window pop up is blocked on request

### ISSUE THREAD

**Issue by karlcow** [mozilla-mobile/firefox-ios#8637]
## Steps to reproduce
1. Go to https://app.diagrams.net/?src=about
2. tap on Google Drive
3. tap on Authorize

### Expected behavior
A notification saying that window popup are blocked and giving the possibility to unblock them.

### Actual behavior
Nothing.

### Device & build information
* Device: iPhone XS
* Build version: Firefox v34 on ios 14.6
### Notes
Attachments: This is working on Chrome iOS

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2025)

**Comment by karlcow** [comment]
originally from https://github.com/webcompat/web-bugs/issues/69632

**Comment by lmarceau** [comment]
Since only `data-sync-user` has commented on the issue after the `Stalebot` GitHub action (which triggered the removal of the `stale` label) I’ll close this issue for now. Please let us know if you think this issue needs to be reopened, we'll gladly do so. Thank you!
