### ISSUE TITLE
FXIOS-1915 ⁃ Studies ‘Learn More’ Button not working

### ISSUE THREAD

**Issue by BrightScreenTV** [mozilla-mobile/firefox-ios#8639]
## Steps to reproduce
Go to settings in Firefox iOS and tap 'learn more' in the Studies setting.

### Expected behavior
To see a summary or detailed info on Studies

### Actual behavior
User is redirected to a page with "unapproved content".

### Device & build information
* Device: ? iPhone X
* Build version: ? 34.0 (4920)
### Notes
Attachments: ![image](https://user-images.githubusercontent.com/67185910/120764918-90895500-c510-11eb-86c8-83e5ea236768.jpeg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2024)

**Comment by data-sync-user** [comment]
➤ Daniela Arcese commented:

The topic for URLforTopic should be set to “+how-opt-out-studies-firefox-ios+ ( https://support.mozilla.org/1/mobile/%VERSION%/%OS%/%LOCALE%/kb/how-opt-out-studies-firefox-ios )”
