### ISSUE TITLE
[Bug] First tap on menu opens it in wrong position

### ISSUE THREAD

**Issue by eliserichards** [mozilla-mobile/firefox-ios#8645]
## Steps to reproduce
I'm trying to repro this but it only seemed to happen once. Worth noting that this was the first time I opened the app since it updated to Firefox Daylight 34.0 (4920)

1. Firefox is closed. Click on a link from Messages
2. While the page is loading, click the hamburger menu 
3. Menu shows up in the top left (couldn't tell what the anchor was) 
4. Closing and opening the menu shows normal behavior, and I couldn't get it to show this bug again 

### Expected behavior
Menu is anchored to the hamburger button

### Actual behavior
Menu is in the wrong place 
![image](https://user-images.githubusercontent.com/43795363/120899106-a754a800-c5f3-11eb-943d-6d1c31a1d2e1.png)

### Device & build information
* Device: iPhone 12 Pro
* Build version: Firefox Daylight 34.0 (4920)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2023)

**Comment by SimonBasca** [comment]
I was able to reproduce the issue. In my case it seems it happens once after upgrading to the latest Firefox version: 
1. Installing v33.1
2. Launch v33.1 and dismiss on-boarding
3. Upgrade to v34.0
4. Open the hamburger menu

**Comment by lmarceau** [comment]
I think this issue doesn't happen anymore @SimonBasca ? It's been a while since I've seen it

**Comment by SimonBasca** [comment]
I was unable to reproduce this issue by following the [STR](https://github.com/mozilla-mobile/firefox-ios/issues/8645#issuecomment-855776280) and upgrading from v100.1 to v101.0 or by clean installing latest main 42bb8dc61447541b984f21b33c8ae72e996899ea.
Let's re-open if the issue is reproducible again.
