### ISSUE TITLE
Tab widths shrink and are unusable as more tabs are opened.

### ISSUE THREAD

**Issue by jmiguy** [mozilla-mobile/firefox-ios#8648]
On an iPad mini the firefox tabs get narrower and narrower as more tabs are opened, so much so, that after about 15-20 tabs being opened, they are too narrow to read, or to click on without closing the tab/web page. They become completely unusable.

### Acceptance Criteria
* Minimum tab width value should be 76
* Tabs become side scrollable if not all tabs fit with a 76 width

### Device & build information
* Device: ipad mini
* Build version: ?
Firefox Daylight 34.0 (4920)

## 

    1. Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2022)

**Comment by SimonBasca** [comment]
Thanks for the feedback, this seems like a major issue for iPad users. We will discus and triage the issue accordingly.

**Comment by nhnt11** [comment]
FYI, I got this feedback from a frustrated iOS user too, it seems to make Firefox extremely difficult to use on their iPad.

**Comment by trodrigues** [comment]
I can confirm this. It actually made me switch to a different browser on iPad for the time being. This is what it looks like:

![E31Lo6qXwAcMC9n](https://user-images.githubusercontent.com/38177/123940064-1924d500-d999-11eb-8f2c-eb717d334715.jpeg)

A huge contrast to what it was like before 
![IMG_0002](https://user-images.githubusercontent.com/38177/123940834-d8798b80-d999-11eb-9fb2-45cf4bc86477.PNG)

**Comment by SimonBasca** [comment]
Verified fix on v35.0 (5884).

**Comment by trodrigues** [comment]
The fix that was applied here ensures the close button always appears but the tabs still become extremely small and mostly unreadable.

**Comment by penidris** [comment]
Why has this issue been closed? The tab width problem remains and has not been fixed.
