### ISSUE TITLE
FXIOS-1920 ⁃ [Bug] Tab counter over 3 digits gets cut off

### ISSUE THREAD

**Issue by eliserichards** [mozilla-mobile/firefox-ios#8650]
## Steps to reproduce
1. Have more than 99 tabs open 
2. Open the tabs tray, see the tab counter under "Open Tabs"

### Expected behavior
Should this be an infinity sign over 99 tabs? (That's the behavior on Android)

### Actual behavior
The three digit number is cut off on the sides of the tab counter:

![image](https://user-images.githubusercontent.com/43795363/120940018-99308580-c6e0-11eb-8423-2f50e2483d55.jpeg)

(Please don't judge me for the number of open tabs that I have...)

### Device & build information
* Device: iPhone 12 Pro, iOS 14.4.2
* Build version: Firefox Daylight 34.0 (4920)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1920)

**Comment by SimonBasca** [comment]
Verified fix on v34.1 (5146).
