### ISSUE TITLE
FXIOS-1921 ⁃ Bookmarks - Unable to select folder while adding a new bookmark

### ISSUE THREAD

**Issue by BigSamSampson** [mozilla-mobile/firefox-ios#8652]
## Steps to reproduce
1. Open firefox browser
2. Navigate to Bookmarks
3. Tap on [Edit]
4. Tap on plus icon
5. Tap on [New bookmark]
6. Enter valid title and url
7. Tap on choosing folder
### Expected behavior
User can choose a folder to save a new bookmark
### Actual behavior
Unable to select folder while adding a new bookmark
### Device & build information
* Device: iphone 7 plus - ios 14.5.1
* Build version: firefox daylight 34.0(4920)
### Notes
Attachments: 
![image](https://user-images.githubusercontent.com/66958331/120967819-aa28d780-c770-11eb-9b7e-8f9eae7ba0f0.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1921)

**Comment by SimonBasca** [comment]
Thank you for the feed back. We currently are tracking this issue. Marking as duplicate of #8597.
