### ISSUE TITLE
Increase spacing between website shortcuts and "Library" title

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#8657]
## Steps to reproduce
1. Go to Settings -> Home -> Set Top Site Rows to 4
2. Go to home tab
### Expected behavior
- There should be more spacing between the website shortcuts and the "Library" title
### Device & build information
* Device: iPhone Xr (14.4)
* Build version: 70fdda04eeb
### Notes
Attachments: 

![image](https://user-images.githubusercontent.com/32130829/121046854-c3f10b80-c7be-11eb-9df3-1f6aba6f4b83.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2020)

**Comment by data-sync-user** [comment]
➤ Daniela Arcese commented:

Related to FXIOS-1925
