### ISSUE TITLE
[iPad] Pocket title is overlapping website shortcuts 

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#8658]
## Steps to reproduce
1. Go to Settings -> Home -> Set Top Site rows to 4
2. Enable Pocket articles
3. Check the Home tab 
### Actual behavior:
- "Recommended from Pocket" text is overlapping the website shortcuts.
### Device & build information
* Device: iPad Pro (14.6)
* Build version:  70fdda04eeb4d06e
### Notes
Attachments: 
![Screen Shot 2021-06-07 at 18 48 06](https://user-images.githubusercontent.com/32130829/121050063-f0a62280-c7c0-11eb-9798-85be48e09a5f.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2019)

**Comment by lmarceau** [comment]
@SimonBasca I think we'll be able to close this one, I can't reproduce this issue anymore.

**Comment by SimonBasca** [comment]
It's safe to close this issue. I am no longer reproducing the issue on iPad Pro (15.1) on latest main a3362e72675e9c2386afbbb594d96b9d027b3fbd
