### ISSUE TITLE
[Support] - Update XCode to 12.5

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#8666]
Adding support ticket that was required to update to XCode 12.5 as the new A~S

For this ticket we updated BR to latest XCode and made sure all tests pass.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2014)

**Comment by gutley** [comment]
See #8674 which started once I started using Xcode 12.5
