### ISSUE TITLE
Swift compiler crashes when building optimised builds on branch v34.1

### ISSUE THREAD

**Issue by gutley** [mozilla-mobile/firefox-ios#8674]
I just updated to using the v34.1 branch and Xcode 12.5. Everything built and worked fine until I tried to do an optimised build.

Now the Swift compiler crashes while compiling some of the files in the Shared framework. I tried cleaning the build folder, restarting Xcode/the entire Mac and nothing helped, other than to set SWIFT_OPTIMIZATION_LEVEL = -Onone (which is not a great long-term solution).

It crashes with:
 `error: Illegal instruction: 4 (in target 'Shared' from project 'Client')`

I've attached the entire build log in case it gives any more help. Search for "Illegal instruction"
[Build target Shared_2021-06-09T15-58-23.txt](https://github.com/mozilla-mobile/firefox-ios/files/6624964/Build.target.Shared_2021-06-09T15-58-23.txt)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2011)

**Comment by ecotopian** [comment]
Hi all! I've stumbled about the same why working on our fork. 

I've been triaging this and it seems the Swift compiler crashes at optimizing this huge static array in [effective_tld_names.swift](https://github.com/mozilla-mobile/firefox-ios/blob/main/Shared/effective_tld_names.swift)

Having less entries in that array will make archive work. I suggest you load that dynamically instead.

**Comment by gutley** [comment]
@ecotopian Good investigation.

In the short term this diff will fix the crash without having to rewrite lots of other code and the unit tests

```
diff --git a/Shared/effective_tld_names.swift b/Shared/effective_tld_names.swift
index 034d99c53..0794c7826 100644
--- a/Shared/effective_tld_names.swift
+++ b/Shared/effective_tld_names.swift
@@ -2,7 +2,7 @@
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */
 
-let ETLD_NAMES_LIST = [
+fileprivate let ETLD_NAMES_LIST_PART_1 = [
    "ac",
    "com.ac",
    "edu.ac",
@@ -4996,7 +4996,10 @@ let ETLD_NAMES_LIST = [
    "school.nz",
    "om",
    "co.om",
-   "com.om",
+   "com.om"
+]
+
+fileprivate let ETLD_NAMES_LIST_PART_2 = [
    "edu.om",
    "gov.om",
    "med.om",
@@ -9175,3 +9178,6 @@ let ETLD_NAMES_LIST = [
    "enterprisecloud.nu"
 ]
 
+// The Swift compiler (as of Xcode 12.5) will crash if ETLD_NAMES_LIST is a single array.
+// It is happy to build it this way though.
+let ETLD_NAMES_LIST = ETLD_NAMES_LIST_PART_1 + ETLD_NAMES_LIST_PART_2

```

Basically it chops the array into two roughly equal sub-parts and then joins them to form the end result.

Its not great though at it requires twice the storage (Part1 + Part2 + (combined))
