### ISSUE TITLE
Bug: Login with QR Code Stuck

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#8689]
**Steps to Reproduce**

1. Fresh install of Firefox on iPad or iPhone
2. Be logged in on desktop
3. Go to "Back up and sync data" from the menu
4. Go to firefox.com/pair on desktop to display the QR code
5. Click Ready to Scan on mobile and scan the QR code
6. Confirm pairing on mobile
7. Approve device on desktop

**Expected Results**

Workflow closes on mobile and you are logged in

**Actual Results**

You remain on the screen waiting for approval. If you close the workflow, you are actually logged in.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2009)

**Comment by SimonBasca** [comment]
I've manage to reproduce the issue on v34.1 (5146) after quickly confirming the paring on mobile and also quickly approving the device on desktop. This causes the screen on mobile not to dismiss but  the user is logged in correctly.
