### ISSUE TITLE
Hamburger menu opens in the wrong position in landscape mode

### ISSUE THREAD

**Issue by csuciu** [mozilla-mobile/firefox-ios#8696]
v34.1 (5146)
iPhone 12 (14.4.2)

1. Open the app.
2. Open the Hamburger menu while in landscape mode.

Result: The menu opens in the wrong position overlapping the Url bar.
![2021_06_11T08_39_56_671Z](https://user-images.githubusercontent.com/1866605/121661941-6eae4600-caad-11eb-8702-c7884eca626e.jpeg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2007)

**Comment by data-sync-user** [comment]
➤ Chris Peterson commented:

I can’t reproduce this bug in Firefox iOS v98.0 (8233) TestFlight on iPhone 12 with iOS 15.4.
