### ISSUE TITLE
FXIOS-1946 ⁃ Tapping on the "Switch your Default Browser" banner and returning to Firefox makes the URL bar unusable 

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#8697]
## Steps to reproduce
1. Clean install Firefox 34.1
2. Visit Facebook.com
3. Close the app and re-open 3 times until the "Switch your Default Browser" banner is displayed.
4. Tap "Go to Settings"
5. Return to Firefox 
6. Tap on the URL bar
### Expected behavior
- The URL bar should be focused
### Actual behavior
- The URL bar cannot be focused.
### Device & build information
* Device: iPhone Xr (14.5)
* Build version: 34.1 (5146)
### Notes
- Not reproducible on v34.0 (4920)
Attachments: 
[Video.mp4.zip](https://github.com/mozilla-mobile/firefox-ios/files/6637504/Video.mp4.zip)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1946)

**Comment by isabelrios** [comment]
I can reproduce the URL bar unusable without thapping in the Switch to default browser, just by opening a site from top sites, then tap on the url bar

**Comment by SimonBasca** [comment]
Fixed by https://github.com/mozilla-mobile/firefox-ios/pull/8702.

**Comment by SimonBasca** [comment]
Verified fix on v34.1 (5146).
