### ISSUE TITLE
FXIOS-1961 ⁃ [XCUITests] Fix stack for NewXcodeVersions workflow

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/firefox-ios#8708]
There was an automatic PR created and merged after detecting the new xcode 13.0.x version available on Bitrise. 
But for some reason, I'm still debugging, the PR was not created correctly.
It changed the old xcode version: `12.5` for `13` instead of `13.0`, see [change](https://github.com/mozilla-mobile/firefox-ios/commit/2ff2f79a8dcb813b0b7647898a58073ce80e09f7#diff-61d1ee831cb1df242161a7d23171914a1d5d628c7659b52db957d80a9394bd68L1534) in commit

![Captura de pantalla 2021-06-14 a las 12 38 55](https://user-images.githubusercontent.com/1897507/121879782-8257e780-cd0d-11eb-8639-fc573341cb6d.png)

So the scheduled build to check the New xcode versions is not building now due to this error.
cc FYi, @rpappalax, @AaronMT

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1961)

**Comment by AaronMT** [comment]
Is this still a problem? I guess I'm confused, I see `osx-code-13.x` in `.bitrise.yml` for `NewXcodeVersions` on `main`

**Comment by AaronMT** [comment]
I think you can try

`'{0}.x'.format('.'.join(largest.split('.')[0:2]))`

Full line

`return '{0}.x'.format('.'.join(largest.split('.')[0:2]))` in the return of https://github.com/mozilla-mobile/firefox-ios/blob/main/test-fixtures/update.py#L53-L63

```Python
>>> print('{0}.x'.format('.'.join("13.0.0".split('.')[0:2])))
13.0.x
```
```Python
>>> print('{0}.x'.format('.'.join("12.5.0".split('.')[0:2])))
12.5.x
```
