### ISSUE TITLE
FXIOS-1963 ⁃ Closing a tab, browser goes to the first tab open. 

### ISSUE THREAD

**Issue by Shawon4877** [mozilla-mobile/firefox-ios#8711]
When you close a tab on iOS Firefox version, it chooses to take you to the very first tab rather than keeping on the previous tab.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1963)

**Comment by SimonBasca** [comment]
Thanks for the feedback, we are currently tracking this issue at #7441. Closing as duplicate.
