### ISSUE TITLE
FXIOS-1964 ⁃ Sign in/up page shows up when trying to access "Manage Account & Devices" instead of the 'accounts.firefox.com/settings' page

### ISSUE THREAD

**Issue by bli-mozbj** [mozilla-mobile/firefox-ios#8712]
## Steps to reproduce
1. Sign in Fxa
2. Goto Settings -> Firefox Account -> Manage Account & Devices 

### Expected behavior
Open the 'accounts.firefox.com/settings' page

### Actual behavior
Open the Sign In / Sign Up page w/o login

### Device & build information
* Device: iPhone 6 , iOS 12.5.1
* Build version:  Firefox v34.1(5186)
### Notes
Attachments: 

https://user-images.githubusercontent.com/25242209/121998226-24df9b80-cdde-11eb-964e-c111cc4cf589.mp4

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1964)

**Comment by dnarcese** [comment]
Closing as this is expected behaviour
