### ISSUE TITLE
[iPad] Top Tabs does not resize correctly after changing device from portrait to landscape

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#8713]
## Steps to reproduce
1. In landscape open several tabs to fill the top tabs bar
1. Change orientation to portrait
1. Open a new tab
1. Change device orientation to landscape
    1. Expected behavior

* The tabs should resize 
    1. Actual behavior
* The tabs do not resize
    1. Device & build information
* Device: iPad Pro (14.6)
* Build version: 34.1 (5167)
    1. Notes
* After steps 2), tapping on the URL bar and dismissing the URL bar focus will resize the tabs.
Attachments: 
[Video.mp4.zip](https://github.com/mozilla-mobile/firefox-ios/files/6654286/Video.mp4.zip)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-1997)

**Comment by SimonBasca** [comment]
This issue is also reproducible when switching to a different app and switching back to firefox.

https://user-images.githubusercontent.com/32130829/135085677-0d3e209b-a06f-49f2-962f-219add183470.MP4

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Verified as fixed on v9000 (35359) with iPad Pro (15.7).
