### ISSUE TITLE
[iPad] Empty tab title changes from "Home" to "Open New tab"

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#8716]
## Steps to reproduce
1. Open an empty tab
2. Close Firefox from app switcher
3. Launch Firefox
### Expected behavior
- Tab title should be home
### Actual behavior
- Tab title changes to "Open New Tab"
### Device & build information
* Device: iPad pro
* Build version: 34.1 (5167)
### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-1995)

**Comment by lmarceau** [comment]
I think this is now fixed from a PR for https://github.com/mozilla-mobile/firefox-ios/issues/8942

**Comment by SimonBasca** [comment]
Verifying as fixed on main 42920ddd19.

**Comment by HaBiMuc** [comment]
Hi all,
any news on this issues? Have the same (?) problems. Details posted
