### ISSUE TITLE
Improve behaviour of 'X' on iPad tab strip

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#8720]
I am not able to close the other tabs I have open in the tab strip without having to click on the tab first, for the 'x' to show up.

**Acceptance Criteria**

* When the tab widths (other than current tab) are > 148, show the 'x' on every tab
* When the tab widths  are <148, do not show the 'x'
* 'x' is always shown on active tab (current behaviour)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-1993)

**Comment by SimonBasca** [comment]
Verified fix on 35.0 (5448).
