### ISSUE TITLE
[crash] Firefox crashes reliably when opening a youtube link

### ISSUE THREAD

**Issue by lnyng** [mozilla-mobile/firefox-ios#8723]
## Steps to reproduce
- Copy https://youtu.be/1Fb0Kn2bVtM
- Go to normal mode
- Click address bar
- Click Paste & Go

### Expected behavior
A Youtube video page opens successfully.

### Actual behavior
Browser crashes immediately.

### Device & build information
* Device: iPhone Xs (14.6)
* Build version: Firefox Daylight 34.0 (4920)
### Notes
Only happens on normal mode. Does not crash on privacy mode.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-1991)

**Comment by SimonBasca** [comment]
I was able to reproduce the issue on latest beta v34.1 (5186) with the link mentioned in the issue.

**Comment by SimonBasca** [comment]
Note: I tried copying several links from the the YouTube app and pasting them in Firefox iOS. So far this is the only link that crashes.

**Comment by kcome** [comment]
a [pull request](https://github.com/mozilla-mobile/firefox-ios/pull/9020) is created to fix this issue.

**Comment by kcome** [comment]
@SimonBasca I created a PR for this issue. currently the PR stopped at "First-time contributors need a maintainer to approve running workflows." could you help on this? Thanks.

**Comment by SimonBasca** [comment]
@kcome thank you so much for your contribution. The pull requests you landed need to be reviewed by a developer if everything is fine we will merge them. I'll get in touch with the team and ask for the review.

**Comment by SimonBasca** [comment]
This issue should have been closed when the PR was merged. Closing now as verified fix on v98.0 (8233) and it's already fixed in release 97.0.
