### ISSUE TITLE
Closing tabs, moves the active tab to beginning of list

### ISSUE THREAD

**Issue by dnarcese** [mozilla-mobile/firefox-ios#8725]
## Steps to reproduce
Close tabs at the end of the tab strip on iPad or iPhone

### Expected behavior
The selected tab should be the next in the list
### Actual behavior
It jumps to a tab at the beginning of the list ( i think it is going to the last fully loaded page, so if I have a bunch of inactive tabs, it won't select those)
### Device & build information
* Device: 2018 iPad Pro, iPhone 11 Pro, iPhone XS (all running iOS 14.8)
* Build version: 34.0
### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-1989)

**Comment by data-sync-user** [comment]
➤ Daniela Arcese commented:

We should select the next tab in the list, regardless of whether it has been loaded or not.
