### ISSUE TITLE
FXIOS-1976 ⁃ Firefox iOS Tab records aren't appearing in Fenix synced tabs

### ISSUE THREAD

**Issue by lougeniaC64** [mozilla-mobile/firefox-ios#8726]
This issue represent sthe ios work associated with [this app services tab syncing issue](https://github.com/mozilla/application-services/issues/3892). 

In short, there was a schema mismatch in which fenix wasn't able to parse tab records created in firefox ios because app services expects the `RemoteTab` `lastUsed` field to be an integer and ios was populating that field with stringified floats (see [here](https://github.com/mozilla-mobile/firefox-ios/blob/f70d448f1a53d98671a4043a6debeb6d72aaf91b/Sync/Synchronizers/TabsSynchronizer.swift#L202)).  On the app services side, we will be adding logic to handle both integer and float values but we also want to update the ios code so that `lastUsed` isn't a string.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1976)

**Comment by SimonBasca** [comment]
Verified fix on Firefox iOS main 3b9c2d558f08e80 and latest Fenix 91.a01. Tested between Galaxy A71 (11), iPhone Xr (14.5), iPad Pro (14.6) and mackbook pro (11.4). Sync tabs works correctly between the mentioned devices.

**Comment by SimonBasca** [comment]
Note form QA : Found this issue while testing - https://github.com/mozilla-mobile/firefox-ios/issues/8792.

**Comment by dnarcese** [comment]
I am wondering if issue #8792 is really an iOS issue or a Android one?
