### ISSUE TITLE
FXIOS-1978 ⁃ Firefox 34.1 is not displaying images

### ISSUE THREAD

**Issue by abceleung** [mozilla-mobile/firefox-ios#8730]
## Steps to reproduce
Try to load any page with images. 
I tested using Google image search, xkcd, 4chan and danbooru.
### Expected behavior
Images loaded successfully.
### Actual behavior
Cannot load images; Blank rectangles are shown instead.
### Device & build information
* Device: iPhone XR 
* Build version: iOS 14.6
### Notes
I strongly suspect that this is caused by the latest update (released yesterday, I think) because my Firefox was functionally normally until today.
Other browsers (namely Chrome and Safari) do not have this issue.
I also opened a Reddit thread here:
https://www.reddit.com/r/firefox/comments/o1lsg2/firefox_ios_is_not_displaying_images/

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1978)

**Comment by SimonBasca** [comment]
@abceleung could you please check the Hamburger menu and tap "Show images". It seems like the Hide images feature is enabled.

**Comment by abceleung** [comment]
> 
> 
> @abceleung could you please check the Hamburger menu and tap "Show images". It seems like the Hide images feature is enabled. Let me know if you are still experiencing issue after this

It worked, thanks!
(Though why is Hide Images enabled by default? lol)

**Comment by SimonBasca** [comment]
@abceleung that shouldn't be enabled by default. I just retested the steps with a clean install an upgrading from previous version. On my side the issue is not reproducible and Block images is disabled by default. 

Is there any change the switch was flipped by mistake?

**Comment by abceleung** [comment]
> 
> 
> @abceleung that shouldn't be enabled by default. I just retested the steps with a clean install an upgrading from previous version. On my side the issue is not reproducible and Block images is disabled by default.
> 
> Is there any change the switch was flipped by mistake?

Yea I might have flipped it by mistake. 
But I can't really remember now.

**Comment by msdrigg** [comment]
I had this same issue. If I accidentally clicked 'hide images' I wasnt aware. I had to find this GitHub issue to know how to fix it. It has been frustrating, but I don't know how to address this best. Maybe make the setting more visible? Or ask the user to confirm hiding images the first time?

**Comment by ksy36** [comment]
We've got several reports about this problem, and I also experienced this issue on my phone (I have not clicked "Hide images", it was enabled by default)

**Comment by SimonBasca** [comment]
@ksy36 do the reports say the Firefox version on which the issue is reproducible? Is it still happening in v35.0(5448)?

**Comment by ksy36** [comment]
Hi @SimonBasca, the 3 reports were on Firefox iOS 34.2. I think my version was 34.2 as well when I experienced the problem. I've updated it to 35.0 (5448) yesterday and it's not reproducible. So perhaps it was a one-time issue.
