### ISSUE TITLE
FXIOS-1979 ⁃ Update expiry date for Glean metrics and release in 34.2

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#8735]
**Background**

As a Product Manager, I want metrics in place for app features, so that I can understand which are most valuable and what areas of the app may need improvement

When transitioning to Glean last year, most metrics were given a 1 year expiry date. That date is coming up July 1st. If we do not update the expiry dates for the metrics we are actively using, then they will expire and no data will be available until we add them back in

**Acceptance Criteria**

* Ensure the glean metrics that we still use do not expire
* New expiry date should be 6-12 months to ensure we continue to revisit metrics and keep only the ones we need
* Release finished rollout before July 1st expiry date
* What's New page and Release Notes should point to the previous version, as those are the more relevant changes for users to know about

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1979)

**Comment by SimonBasca** [comment]
Verified only that the "What's New" page and "Release Notes" should point to the previous version. Also checked that glean is working as expected.
