### ISSUE TITLE
Tabs on iPadOS wont close

### ISSUE THREAD

**Issue by fernando9431** [mozilla-mobile/firefox-ios#8741]
## Steps to reproduce
Open more than one tab
### Expected behavior
Close the tab when x is pressed
### Actual behavior
Tabs won’t close unless the app is restarted, but the tabs has to be closed in the 30 seconds after the restart, because if the time is up the behavior repeats itself and the whole process has to be done again.
### Device & build information
* Device: iPad 8 with iPadOS 14.6
* Build version: 5186
### Notes

Attachments: 
Link with the video when I replicate the bug
https://share.icloud.com/photos/0gD9Cq21KIWFXEFwWlRaOq6ag

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-1984)

**Comment by data-sync-user** [comment]
➤ Daniela Arcese commented:

Duplicate FXIOS-2033

**Comment by jcaplan** [comment]
CMD+w still works if you have a keyboard. Otherwise it’s unusable. I also find opening new tabs is a bit wonky since the update. Often instead of one tab, you get two tabs where one is empty. This is very annoying coupled with the inability to close the extra tab.
