### ISSUE TITLE
New tab '+' button is hard to tap

### ISSUE THREAD

**Issue by huonw** [mozilla-mobile/firefox-ios#8755]
Thanks for Firefox for iOS 👍 

## Steps to reproduce

1. open 'Open tabs' drawer
2. observe that the new tab '+' button is in the bottom right and has a fairly small tap target
3. tapping this button while holding the phone one handed in my right hand requires a contortion of my thumb (and/or shifting my grip), and I miss the first time, usually
4. also observe that the Close All Tabs 🗑️ button is in the bottom left, and is easier to tap in that grip

<img width="320" src="https://user-images.githubusercontent.com/1203825/123016236-7fe04680-d40d-11eb-86de-833572a5f8c6.jpeg" />

### Expected behavior

I open new tabs very often, and close all tabs very rarely (never), so it'd be great if the new tab button was easier to hit. For instance, since there's nothing else in the bottom bar, it seems like it could have a large tap target, be much wider and/or be in the centre.

### Actual behavior

My thumb needs to get more flexible.

### Device & build information
* Device: iPhone 8 plus
* Build version: Firefox Daylight 34.1 (5186)
### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2914)

**Comment by hafta** [comment]
I agree. The new tab button placement and size is awkward to use on a phone.

**Comment by jeremygc** [comment]
I have this problem too. I find myself tapping the plus icon multiple times trying to get a new tab open

**Comment by data-sync-user** [comment]
➤ Tiffanie Shakespeare commented:

daniela - can someone check that tap area is meeting min touch target requirements?

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Verified as fixed on v9000 (20530) with iPhone 13 Pro (15.1.1).

**Comment by abodea** [comment]
Hello, @jeremygc, @hafta, @huonw! Thank you for commenting and helping!
Please note that I verified this o the latest master changes and it will take some time until it will end up in the next release, but now the actionable area for the `+` button is way bigger, you can update this ticket once you get the next update if everything is fine on your side. 
I verified it on iPhone 13 Pro Max (15.1.1) being pretty big, it was not hard for me to hit the `+` button.

**Comment by data-sync-user** [comment]
➤ Tiffanie Shakespeare commented:

removing “flag” and needs-ux label.
