### ISSUE TITLE
Favicons overlap page titles and URLs in History view in landscape orientation

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/firefox-ios#8766]
## Steps to reproduce

1. Make sure you have some browsing history so your History view is not empty.
2. Open History view.
3. Rotate your phone to landscape orientation.

### Expected behavior

Favicons should be to the left of page titles and URLs in History list in landscape orientation, just like in portrait orientation.

### Actual behavior

Favicons overlap page titles and URLs in History list in landscape orientation. See the attached screenshot.

### Device & build information
* Device: iOS 14.6 on iPhone 12
* Build version: Firefox Beta 34.1 (5186)

### Notes
Attachments: 

![History_screenshot](https://user-images.githubusercontent.com/629193/123340934-efcff900-d501-11eb-905a-1a19f5ef9d98.jpg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2917)

**Comment by data-sync-user** [comment]
➤ Daniela Arcese commented:

Duplicate of https://mozilla-hub.atlassian.net/browse/FXIOS-2948 ( https://mozilla-hub.atlassian.net/browse/FXIOS-2948|smart-link )
