### ISSUE TITLE
Menu icons cutoff in Slide Over view

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#8771]
When Firefox on iPad is in Slide Over view, the icons in the app menu and page action menu are not showing.

!Simulator Screen Shot - iPad Pro (9.7-inch) - 2021-06-24 at 12.03.58.png|width=200,height=183!

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2916)

**Comment by lmarceau** [comment]
Since only `data-sync-user` has commented on the issue after the `Stalebot` GitHub action (which triggered the removal of the `stale` label) I’ll close this issue for now. Please let us know if you think this issue needs to be reopened, we'll gladly do so. Thank you!
