### ISSUE TITLE
aspor.com-Link sharing via whatsapp is not working in Yaani. Works fine in Chrome

### ISSUE THREAD

**Issue by BigSamSampson** [mozilla-mobile/firefox-ios#8789]
## Steps to reproduce
1. Launch the firefox
2. Visit “ https://www.aspor.com.tr/turkiye-kupasi/kupatv/turkiye-kupasi/trabzonspor-2-0-alanyaspor-genis-mac-ozeti#”
3. Tap on whatsapp icon available below the video
### Expected behavior
User should ve able to share the link via whatsapp
### Actual behavior
Nothing happens when user clicks on Whatsapp
### Device & build information
* Device: iphone 7 plus - ios 14.6
iPhone 7 - iOS 13.5.1
* Build version: daylight 34.2(5301)
### Notes
Attachments: 
![image](https://user-images.githubusercontent.com/66958331/124087886-1e4a5880-da5b-11eb-9690-90805f551ba4.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2921)

**Comment by SimonBasca** [comment]
I am unable to reproduce the issue on latest v34.2(5301). On my side tapping on the "what's app" icon opens what's app. @BigSamSampson is his working is Safari on your side?
