### ISSUE TITLE
[Keyboard] Pressing cmd + R duplicates the opened tab

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#8790]
## Steps to reproduce
1. Go to youtube.com
2. Press cmd+R two times
### Expected behavior
- The page should reload.
### Actual behavior
After pressing the first time on cm+R, the page reloads. After pressing again on cmd+R the youtube tab is duplicated.
### Device & build information
* Device: iPad Pro (14.6)
* Build version: 3b9c2d558f08e
### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2922)

**Comment by gutley** [comment]
Seems related to #7519 . Basically its the way the code deals with having the command key down when loading urls. (See my big comment in that ticket)

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verified fix on v37.0 (5922).
