### ISSUE TITLE
Deleting all incognito tabs will show incorrect number of deleted tabs

### ISSUE THREAD

**Issue by nates** [mozilla-mobile/firefox-ios#8794]
## Steps to reproduce
1. Have some normal tabs open and some incognito tabs open
2. Delete all incognito tabs
3. Go back to a normal tab and the toast will show the amount of normal tabs you have open
### Expected behavior
Toast says amount of normal tabs open.
### Actual behavior
Toast should say amount of incognito tabs closed.
### Device & build information
* Device: iPhone 11
* Build version: Firefox latest
### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2926)

**Comment by data-sync-user** [comment]
➤ Daniela Arcese commented:

I noticed that the toast also allows you to Undo closing the tabs. But when you click Undo, nothing happens.

**Comment by data-sync-user** [comment]
➤ Daniela Arcese commented:

Closing this in favor of #8818, which will cover this bug as well.
