### ISSUE TITLE
Update the layout of the Logins & Passwords table rows

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/firefox-ios#8809]
Let's give the rows in the Logins & Passwords list a better layout. Right now they are extremely packed with no spacing between the rows and the two lines of text.

Talking to @lime124 about this, we thought it would be a good idea to give the rows in this list the same style as the History list, except without the site icon.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2933)

**Comment by SimonBasca** [comment]
Verified fix on main 9337006208b1b.

**Comment by SimonBasca** [comment]
Verified fix on v36.0(5673)
