### ISSUE TITLE
Issues in the new homescreen design

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/firefox-ios#8814]
1-Reading List title is not shown completely in some locales
2-Text in Recently saved item does not fit its space
## Steps to reproduce
Use the device in Spanish
### Expected behavior
All titles are shown correctly or there is way to see them
### Actual behavior
The title is cut off
### Device & build information
* Device: iPhone 6s, iPhone 8
* Build version: v35.x (5440)
### Notes
Attachments: 
![IMG_0392](https://user-images.githubusercontent.com/1897507/124954862-d311e600-e016-11eb-8013-cb1bdd0f4626.PNG)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2934)

**Comment by data-sync-user** [comment]
➤ Daniela Arcese commented:

Can we add certain gesture telemetry events to see if users are trying to slide on the title or long press to read more.

**Comment by oscar345** [comment]
What version of Firefox on iOS are you using?

**Comment by oscar345** [comment]
How are you able to run version 35.x? I only see version 34.1 on TestFlight?

**Comment by data-sync-user** [comment]
➤ Daniela Arcese commented:

For Recently Saved items, let’s add ellipsis if the text is ever longer than the cell.

**Comment by csuciu** [comment]
Verified as fixed on latest master.
