### ISSUE TITLE
Smart invert doesn’t turn off in Firefox

### ISSUE THREAD

**Issue by DieNand** [mozilla-mobile/firefox-ios#8820]
I turned on smart invert using accessibility shortcut on my iPad mini 5, then switched to another app and turned it off. When I came back to Firefox it stays inverted

## Steps to reproduce
Use accessibility shortcut (tap home button 3 times) to turn on smart invert in Firefox. Switch to another app. Use the same shortcut to turn it off. Switch back to Firefox and notice everything is still inverted.

### Expected behavior
Colours should be inverted in Firefox when smart invert is on in settings and uninverted when it is off.

### Actual behavior
Colours stay inverted in Firefox when smart invert is off in settings. It stays inverted even after hard reset of device. I cannot get the colours to return to being uninverted at all currently.

### Device & build information
* Device: iPad mini 5
* Build version: 34.2
* iPad OS: 14.6
### Notes
Attachments: 
Here you can turn on smart invert accessibility feature
![928B44F3-CF1E-4117-8CED-44EFA4D5D3B4](https://user-images.githubusercontent.com/10383716/124999940-7848b080-e04f-11eb-945c-6b04d4f378eb.jpeg)

Smart invert is off
![ED7E734B-072C-4B9E-AF3E-0D7FF5E28836](https://user-images.githubusercontent.com/10383716/124999959-85fe3600-e04f-11eb-8ea3-c261cadc1cfe.jpeg)

Result in Firefox
![6C051D65-055E-4056-86B9-2D0351789E95](https://user-images.githubusercontent.com/10383716/124999986-96aeac00-e04f-11eb-94df-2e954cd34835.jpeg)

Result in Safari
![74596A1D-0642-480B-A317-E00FAA268664](https://user-images.githubusercontent.com/10383716/125000010-ac23d600-e04f-11eb-9b3d-f8b61ee73d4b.jpeg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2938)

**Comment by SimonBasca** [comment]
@DieNand could you please check if Night mode is active in Firefox iOS by pressing on the hamburger menu?

**Comment by DieNand** [comment]
Hey, it was probably on when I did the tests last night. (It is scheduled to turn on after 22:00.) I can confirm that my colours are still inverted when it is off though.

I’m not as sure as I was when I reported this that it is related to Smart Invert but I know that I first noticed it when I turned it on once.

**Comment by SimonBasca** [comment]
@DieNand Thanks for the feedback, unfortunately I am unable to reproduce the issue following the STR on iPad pro 14.6 on Firefox iOS 34.2. I will keep trying to reproduce the issue but you could try opening Firefox, tap on the hamburger menu, tap on "Turn on Night Mode" and tap again to "Turn off Night Mode". I think this might fix the issue for you.

**Comment by DieNand** [comment]
Your suggestion seems to have solved the issue for me. Thanks!
