### ISSUE TITLE
Favicons overlap with the text in "Recently Closed" list

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#8833]
## Steps to reproduce
1. Close a few page to populate the "Recently Closed" list
2. Go to History -> Recently Closed list
3. Change device orientation to landscape.
### Actual behavior
- Some favicons overlap with the text.
### Device & build information
* Device: iPhone Xr (14.5)
* Build version: 35.0 (5448)
### Notes
- Note that some favicons are enlarged and overlap with the text in portrait view also
Attachments: 
![IMG_7131](https://user-images.githubusercontent.com/32130829/125312276-cce47800-e33c-11eb-85bd-d1516b72e21a.PNG)
![IMG_7130](https://user-images.githubusercontent.com/32130829/125312284-ceae3b80-e33c-11eb-93f7-28072f8fd058.PNG)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2948)

**Comment by csuciu** [comment]
Verified as fixed on latest master.
