### ISSUE TITLE
Shortcuts cannot be added to NTP in private browsing

### ISSUE THREAD

**Issue by mcl21014** [mozilla-mobile/firefox-ios#8836]
iOS version: 14.7 beta 5
Device: iPhone 12 Pro Max
Firefox version: 35.0 beta
Adding a shortcut in standard browsing works as intended. Attempting to add a webpage shortcut to the new tab page results in private browsing results in nothing changing on the new tab page. A question to raise is if this is an iOS limitation, or a bug in Firefox itself. The bug happens in v34.2 stable as well.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2950)

**Comment by SimonBasca** [comment]
Confirming that this is an issue on latest v35.0 (5448).

**Comment by SimonBasca** [comment]
Note that the issue only reproducible if the user is logged in to FxA. If the user does not have FxA setup, the pages can be added to shortcuts in Private Browsing.
