### ISSUE TITLE
[Login] Login/Password Edits are not immediatly reflected in view

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/firefox-ios#8860]
## Steps to reproduce
1. Have a login stored
1. Go to Edit it 
1. Change the Username 
1. Tap on Done
    1. Expected behavior
The Username is changed according to the new text entered
    1. Actual behavior
The Username is changed while writing but when tapping on Done, the change is undo and the original username is shown

If you leave the login view and enter again then the change is applied

### Device & build information
* Device: iPhone 11 OS 14.5
* Build version: main
    1. Notes
Attachments: 
https://user-images.githubusercontent.com/1897507/125796499-3a0613ba-2d3e-4a1f-9f4f-bac67db0aea3.mov

Issue found by this UI automated test: [testEditingDetailUpdatesPassword](https://github.com/mozilla-mobile/firefox-ios/blob/main/UITests/LoginManagerTests.swift#L591)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2964)

**Comment by isabelrios** [comment]
It is happening in beta v35.x it is still a regression but does not look related to the credential autofill work. sorry for the confusion. I think we can remove that label and drecrease the priority

**Comment by SimonBasca** [comment]
Other report of this issue here https://github.com/mozilla-mobile/firefox-ios/issues/10213
See comments for more details: https://github.com/mozilla-mobile/firefox-ios/issues/10213#issuecomment-1066633612
