### ISSUE TITLE
Once the keyboard (auto opens due to auto selecting address bar) is closed on homepage, the bottom menu bar should come back up

### ISSUE THREAD

**Issue by jhay4** [mozilla-mobile/firefox-ios#8862]
### User Problem
I know this year an update made going to the home page automatically select the address bar to type. In theory that sounds cool but it has made my experience feel really inconvenient.

The bottom bar that has the tabs menu and settings has become inaccessible unless you reach up to the top left corner to hit the back button. I am constantly opening new tabs to my hone page so that the next time I open the app, I have my top sites and tabs all a click away. Sure, I use the address bar but not nearly as often as my saved top sites or currently opened tabs.

The reason this should be implemented is because it makes doing some other things inconvenient now. This has negatively impacted my experience and I’ve been a Firefox user since the beginning. 

### Ideas for Solution
I’m trying to meet in the middle here and feel I’ve come up with a solution that accomplishes that. When a user currently moves the home page (swipes or uses their thumb to move down the page) the keyboard closes. This would be a great time to bring the bottom bar back up to access.
![38340B7A-DB79-41B5-8EDD-29EB95C5D831](https://user-images.githubusercontent.com/87494760/125845831-bb85faa8-1020-4e97-9118-eb19542b3400.jpeg)

Currently, when the keyboard closes you are forced to still reach up to the top left corner to hit the back button to bring that bottom bar onto the screen. It should come up when the keyboard closes because why not? This makes it more convenient for users who access the home page without intent to search the address bar, and there’s a lot you can do from the homepage besides that. Also, the keyboard only comes back if you click the address bar once it was closed. Not to mention users that want the address bar has that option in the first place when it auto pops up on open.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2966)

**Comment by gutley** [comment]
Personally I dislike the address bar being automatically focused. Those of us that like to be able to see their Top sites and Pocket feed at launch/new tab have to hit the back button to do so.

**Comment by jhay4** [comment]
Same here. It’s definitely lowered the quality of my experience using the browser. I’m not sure why it wasn’t made a setting option you can toggle on/off. 

Mozilla made a home page with a lot of options on it, and although the top sites are for the most part available in one tap, if you have 4 rows, the last row is partially cut off and then your bookmarks, history, downloads, and reading list shortcuts are not very much of a shortcut anymore. And as you mentioned the pocket section is always completely hidden.

I actually use pocket more than I imagined I would when it was first introduced, but I’ve definitely used it much less over the last few months due to it being more of an inconvenience to access. Really wish they just gave us the option to either have easy access to the address bar (currently implemented), or easy access to the entirety of the homepage. Unfortunately, I’ve tried to get used to it before bringing it up but I’ve discovered you can’t really have it both ways. Auto address bar selection means a worse experience for accessing the rest.

**Comment by jhay4** [comment]
I’m actually going to close this and just straight up ask for a setting option because now that I know for sure I’m not alone I feel we deserve that option, considering it was something I feel not many complained about when it was in its previous state. Thanks for commenting @gutley feel free to support the new request if you’d like.
