### ISSUE TITLE
[L10nScreenshots] Task: index-task-generate-screenshots is failing

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/firefox-ios#8871]
The builds to generate the screenshots are working and those are taken correctly. But the process to download and store them in the .latest link are failing with this error:
```
taskcluster:error] Pulling docker image has failed.
[taskcluster:error] Error: Could not find a task associated with "taskgraph.cache.level-3.docker-images.v2.index-task.latest" namespace. Indexed task not found
---
* method:     findTask
* errorCode:  ResourceNotFound
* statusCode: 404
* time:       2021-07-19T08:08:52.184Z
[taskcluster 2021-07-19 08:08:52.223Z] Unsuccessful task run with exit code: -1 completed in 0.891 seconds

```
See link: https://firefox-ci-tc.services.mozilla.com/tasks/GXga9I2DS0qYD0mQKqgNDw

Could this be related to the work related to have same environment for Focus? The [PR](https://github.com/mozilla-mobile/focus-ios/commit/9a3c8cac36d70a00cdf6f44ef5e22f0ddc560687) just landed, it could be a coincidence but I'm afraid it is not :( 
@bhearsum @escapewindow please let me know if you know how to fix this 🙏

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2975)

**Comment by escapewindow** [comment]
This was due to an expired docker-image task in the [taskgraph repo](https://treeherder.mozilla.org/jobs?repo=taskgraph). I [add-new-jobs'ed the docker-image tasks](https://treeherder.mozilla.org/jobs?repo=taskgraph&revision=81f2a1a09e9b0fc1b6c66fd452e065440793c175) and reran the failing task. [Green](https://firefox-ci-tc.services.mozilla.com/tasks/GXga9I2DS0qYD0mQKqgNDw).

**Comment by isabelrios** [comment]
> This was due to an expired docker-image task in the [taskgraph repo](https://treeherder.mozilla.org/jobs?repo=taskgraph). I [add-new-jobs'ed the docker-image tasks](https://treeherder.mozilla.org/jobs?repo=taskgraph&revision=81f2a1a09e9b0fc1b6c66fd452e065440793c175) and reran the failing task. [Green](https://firefox-ci-tc.services.mozilla.com/tasks/GXga9I2DS0qYD0mQKqgNDw).

Thank you @escapewindow, yeah, it is green now
