### ISSUE TITLE
Autofill fails when credentials are added for desktop version of the site and the user is directed to the mobile version

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#8872]
## Steps to reproduce
1. Go to Login screen 
1. Tap the "+" icon
1. Type a webpage e.g. "facebook.com" 
1. Type a username and password and hit save
1. Long tap on the website and tap "Open and fill"
    1. Expected behavior

* The page is loaded with the credentials should be auto filled
    1. Actual behavior
* The page is loaded but the credentials are not auto completed.
    1. Device & build information
* Device: main 9337006
* Build version: iPhone Xr (14.5)
    1. Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2976)

**Comment by st3fan** [comment]
@SimonBasca I think we should find out how this works on Android and if we should be smart enough to go from `m.facebook.com` to `facebook.com` when we pick a login.

**Comment by SimonBasca** [comment]
@st3fan I checked with the Android team and they don't have the ability to manually add logins from the login screen. The only similar ability to add manual login is via iOS Settings -> Passwords and add a login to Keychain but after adding the login it does not auto fill when visiting Facebook in Safari.

**Comment by st3fan** [comment]
I removed the P16107 label here because this is an old bug not related to the native autofill work. We should fix this though. I think the "Open & Fill" request gets confused because of the redirect from facebook.com to m.facebook.com.
