### ISSUE TITLE
Extra radio button is diplayed in login list after tappind on Filter field

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#8875]
## Steps to reproduce
1. Go to Logins
2. Tap "Edit"
3. Tap on the "Filter" field
4. Dismiss the Filter filed
5. Pull down the login list by swiping down  
### Actual behavior
- An extra radio button is diplayed.
### Device & build information
* Device: iPhone Xr (14.5)
* Build version: 933700620
### Notes
Attachments: 
[video.mp4.zip](https://github.com/mozilla-mobile/firefox-ios/files/6840800/video.mp4.zip)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2978)

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verified fix on main 627116c2
