### ISSUE TITLE
Firefox crashes when switching between Bookmarks and History library shortcuts

### ISSUE THREAD

**Issue by toomm1** [mozilla-mobile/firefox-ios#8877]
When you click on Chronicle then Firefox crashes every now and then. Or you first click e.g. on Bookmarks and then on History then Firefox crashes.
Version 35.0

iPhone 12 Pro
Firefox Version 35.0

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2980)

**Comment by dnarcese** [comment]
@toomm1 Can you clarify what Chronicle is? Is it a site in your Shortcuts section that you are trying to access?
And where are you clicking on Bookmarks and History - from the home page or from the menu?

**Comment by toomm1** [comment]
when i start the app. in app, below, are the following button, "Lesezeichen", "Chronik", "Downloads", "Leseliste".
When i klick on the Button "Leseliste" und than on the Button "Chronik", than crash Firefox

**Comment by SimonBasca** [comment]
I think this is the History list. I will try to reproduce the crash by switching the bookmark and history list.

**Comment by SimonBasca** [comment]
@toomm1 It would be very helpful if you could crash the app and after go to iOS Settings -> Privacy -> Analytics & Improvements -> Analytics Data, search for the crash log and share it with us. The crash log name looks something like (Client - "current date".ips.beta)

**Comment by toomm1** [comment]
[ips.zip](https://github.com/mozilla-mobile/firefox-ios/files/6944106/ips.zip)

**Comment by csuciu** [comment]
I am able to reproduce this crash constantly by repeatedly switching between Bookmarks and History lists via the Home page.

1.  Open the Home page.
2. Tap on the Bookmarks button from Your Library section.
3. Press on Done to dismiss the Library panel and go back to the Home page.
4. In the Home page press on the History button.
5. Repeat 2 to 4.

Result: The app crashes.

[Client-2021-08-06-145725.ips.beta.zip](https://github.com/mozilla-mobile/firefox-ios/files/6945408/Client-2021-08-06-145725.ips.beta.zip)
