### ISSUE TITLE
Reopening tabs after crash also reopens private tabs

### ISSUE THREAD

**Issue by igorklochko** [mozilla-mobile/firefox-ios#8881]
## Steps to reproduce
1 - Open a tab in private view 
2 - get browser to crash
3 - open it again
4 - On the "firefox has crashed, would you like to restore tabs" promt click "yes"

### Expected behavior
Private tabs are not reopened

### Actual behavior
Tabs are reopened

### Device & build information
* Device: iPhone 12/iPad Pro 2020 11"
* Build version: iOS 15 beta 3 - 19A5297e
    1. Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2984)

**Comment by data-sync-user** [comment]
➤ Daniela Arcese commented:

We should see how Android and desktop handle this.

**Comment by data-sync-user** [comment]
➤ Daniela Arcese commented:

Let’s move forward the functionality of NOT re-opening private tabs after a crash.
