### ISSUE TITLE
Firefox crashes when restoring from background

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#8883]
From user feedback on slack: 
I have the beta ios on my ipad and noticed Firefox is frozen and ultimately crashes „sometimes“ when I resume it from background. Can‘t provide more info except that it needs to spend some more time (few minutes) in the background and be maybe 3rd/4th in the background queue.

Notes:
Device: iPad pro, ios 15.
- 27 tabs open.

Crash logs:
- [Archive.zip](https://github.com/mozilla-mobile/firefox-ios/files/6849179/Archive.zip)
- link to crashlog : https://drive.google.com/drive/folders/1KwkGiaQblHyEE1T6yCx7U63XFKgWzbBI

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2986)

**Comment by lokan** [comment]
I have the same issue on iOS 15 and iPadOS 15. Firefox crashes when restoring from background even with two tabs open.
