### ISSUE TITLE
Images not loading in Firefox Daylight 35.0 (5448) for iOS

### ISSUE THREAD

**Issue by galecore** [mozilla-mobile/firefox-ios#8885]
![2EA7E150-6B97-4C1E-A1E4-A2EE5A74F6F2](https://user-images.githubusercontent.com/12109150/126379270-9c297586-a887-4dd9-9db2-8442d46dabde.png)
## Steps to reproduce
Search anything via google and click on “images” tab. 
### Expected behavior
Images are loaded
### Actual behavior
Images are not loaded
### Device & build information
* Device: IPhone 11 pro max 
* Build version: Firefox Daylight 35.0 (5448)
### Notes

For some reason images are not loading after the last update.
I'm running firefox on iphone 11 pro max with iOS 14.6.

Website does not matter, tried google image search and wikipedia. Also tried several wifi networks and LTE. Web pages load successfully, no images though. Video streams are played as normal.

Attachments: 

Screenshot linked below as proof. 
![D7766500-2F56-4343-9419-ED02307B9AAC](https://user-images.githubusercontent.com/12109150/126379023-2f14df70-3368-4098-9156-2991aa8c2367.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2987)

**Comment by ksy36** [comment]
This is the same issue as https://github.com/mozilla-mobile/firefox-ios/issues/8730 where "Hide images" was enabled by default for some users (I have also experienced the problem). Opening the Hamburger menu and tapping "Show images" should fix the issue. 

@galecore do you recall flipping "Hide images" by mistake/accident, or was it enabled by default?

**Comment by galecore** [comment]
No, i guess it was enabled by default after the update. Did not even know it was possible to hide images in firefox. 
After flipping it back, everything works as expected. 

Thank you for you help :)

**Comment by data-sync-user** [comment]
➤ Daniela Arcese commented:

We should investigate whether our menu updates changed some default setting here.
