### ISSUE TITLE
User profile page on spotify.com is empty on Firefox on iPad

### ISSUE THREAD

**Issue by ksy36** [mozilla-mobile/firefox-ios#8886]
## Steps to reproduce
Open https://open.spotify.com/user/ei7ehalnr019wn820gwnu6ykm in Firefox on an iPad and observe the page

### Expected behavior
User profile page loads and their playlists/followers displayed 

### Actual behavior
Page is empty

### Device & build information
* Device: iPad Pro, iOS 14.6
* Build version: Firefox Daylight 35.0 (5448)

### Notes
the same issue is present on https://open.spotify.com

Attachments: 

![IMG](https://user-images.githubusercontent.com/1303908/126388303-840f7701-2008-49bd-99b7-43331cf06910.PNG)UNITO-UNDERSCORE!0077!

(originally reported in https://github.com/webcompat/web-bugs/issues/79806)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2988)

**Comment by SimonBasca** [comment]
Confirming that this is an issue on v35.0 (5448). 
Note: 
- The site works well in Chrome and Safari. 
- After loading the mobile version of the site in safari the page will load correctly.

**Comment by data-sync-user** [comment]
➤ Daniela Arcese commented:

Seems to be a user agent problem.
