### ISSUE TITLE
Shortcut icons appearing cut off with new design

### ISSUE THREAD

**Issue by eritbh** [mozilla-mobile/firefox-ios#8888]
## Steps to reproduce

Have a shortcut for Youtube or Github and view the shortcuts panel.

### Expected behavior

The colored background behind each website's icon should extend beyond the edge of the icon logo.

### Actual behavior

The colored background ends exactly at the edge of the icon, leading to the shortcuts appearing cut-off or incomplete.

### Device & build information
* Device: iPhone SE (1st generation) iOS 14.6
* Build version: Firefox Daylight 35.0 (5448)
### Notes
I'm not sure what standard favicon sizes are nowadays, but if the white padding around each icon is intended, I'd expect FF to display a favicon that doesn't extend to the edge of the colored space, though I'd personally prefer that the colored background stretch to the edge of the tile instead so the icons dont have to be further shrunk. 

Attachments: 
![Screenshot of the issue](https://user-images.githubusercontent.com/4165301/126404467-89cade8c-cc21-4752-bdab-4edf99299648.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2989)

**Comment by data-sync-user** [comment]
➤ Tiffanie Shakespeare commented:

removing needs-ux, the padding is intended. this is an eng fix, ux doesn’t supply the icons for top sites.
