### ISSUE TITLE
Pressing "cmd+alt+tab" should dismiss Tabs Tray

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#8891]
## Steps to reproduce
1. Press "cmd+alt+tab"
2. Repeat step 1)
### Expected behavior
- After pressing "cmd+alt+tab" the first time, tabs tray is opened. After pressing "cmd+alt+tab" a second time tabs tray should close.
### Actual behavior
After pressing "cmd+alt+tab" a second time tabs tray remains open
### Device & build information
* Device: iPad Pro (14.6)
* Build version: 350 (5448) and main 1a19bf4
### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2992)

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verified fix on main 552d8a8
