### ISSUE TITLE
[Hardware Mouse] Context menu is not displayed when long clicking on a link

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#8892]
## Steps to reproduce
1. Go to new.google.com
1. Long click on a link
    1. Expected behavior

* Context menu should be shown.
    1. Actual behavior
* Context menu is not displayed.
    1. Device & build information
* Device: iPad Pro 14.6
* Build version: 35.0(5448) and main 1a19bf4
    1. Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2993)

**Comment by dnarcese** [comment]
@SimonBasca can I get a screenshot of this issue? Is it specific to google.com?

**Comment by SimonBasca** [comment]
This issue is not website specific. It's only reproducible with hardware mouse when long clicking  on a link. The context menu is not show, only the preview is displayed. 

[video (1).mp4.zip](https://github.com/mozilla-mobile/firefox-ios/files/6905850/video.1.mp4.zip)
