### ISSUE TITLE
[Telemetry] “HomePage” is always show regardless of whether a user sets New Tab to

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#8913]
Regardless of whether a user sets New Tab to Firefox Home, Blank or a custom URL, “HomePage” is always returned in Proxyman.

### Screenshot:
![image](https://user-images.githubusercontent.com/32130829/127163051-d4d1b205-116e-4d9d-8e5b-d5166201c3ae.png)

### Build :
* main c9c09d9a72ca9

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3007)

**Comment by nishant2718** [comment]
It looks like this metric isn't expired, so wondering why it doesn't appear in the dashboard?
```
new_tab_experience:
    type: string
    description: |
      The name of the view that the user wants to see on new tabs.
      For example History, Homepage or Blank. It is used to measure
      usage of this feature, to see how effective feature promotion
      campaigns are and to establish a baseline number for when we
      introduce the new Activity Stream features.
    bugs:
      - https://bugzilla.mozilla.org/show_bug.cgi?id=1644846
    data_reviews:
      - https://bugzilla.mozilla.org/show_bug.cgi?id=1644846
    notification_emails:
      - fx-ios-data-stewards@mozilla.com
    expires: "2022-01-01"
```

Will discuss with product.

**Comment by dnarcese** [comment]
I am seeing other values coming in on Looker https://mozilla.cloud.looker.com/x/jVKC9djnWAC5kEXtwP1cSG

We should use this ticket as an investigation into why we are not seeing it in other places
