### ISSUE TITLE
Google Search suggestion are incorrect

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#8929]
## Steps to reproduce
1. Tap on the url bar
2. Type "d"
### Expected behavior
- Search suggestion should be like on Google
![screebshot](https://user-images.githubusercontent.com/32130829/127670901-a900e329-aa45-47e1-add2-1233ad7f185f.PNG)

### Actual behavior
- Search suggestion are incorrect
![screenshot 2](https://user-images.githubusercontent.com/32130829/127670926-33591cb7-0d48-44c2-b8d0-938d529455e1.PNG)

### Device & build information
* Device: iPhone Xr (14.5.1)
* Build version: 36.0 (5673)
### Notes
- This is not a recent regression, it's reproducible in older builds also
Attachments:

┆Issue is synchronized with this [Jiraserver Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3013)

**Comment by data-sync-user** [comment]
➤ Daniela Arcese commented:

This is expected behaviour. Some of the results on Google are sponsored results which we will not show.
