### ISSUE TITLE
Replace Firefox-specific passcode with native device authentication

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/firefox-ios#8934]
> This ticket is part of the AutoFill Credential Provider work

Drop support for the Firefox-specific Passcode and instead rely on the native device authentication.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3016)

**Comment by st3fan** [comment]
I claimed this ticket because I already have a work in progress branch with these changes.

**Comment by SimonBasca** [comment]
Verified fix on main aadb92acb and beta 95.0 (6528). Testes executed and passed at https://testrail.stage.mozaws.net/index.php?/tests/view/3823007
