### ISSUE TITLE
Do not suggest autofill credentials if the user has not set a device passcode

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/firefox-ios#8936]
> This ticket is part of the AutoFill Credential Provider work

In the Autofill Credential Provider, do not suggest any credentials if the user has not set a device passcode.

Because this can change over time, check `LAContext().canEvaluatePolicy(.deviceOwnerAuthentication)` every time the extension is asked to provide suggestions.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3017)

**Comment by st3fan** [comment]
Closing this with https://github.com/mozilla-mobile/firefox-ios/issues/8937 where this work is done.

**Comment by SimonBasca** [comment]
Verified fix on v95 (6528)
