### ISSUE TITLE
Tab titles and icons disappear in Firefox for iOS

### ISSUE THREAD

**Issue by Gpwidin** [mozilla-mobile/firefox-ios#8942]
## Steps to reproduce
Typically occurs after re-boot; also after using other apps for extended period
### Expected behavior
Titles and icons appear in the header for each site
### Actual behavior
Icons and sometimes also titles disappear, leaving only the default globe icon
### Device & build information
* Device: ? iPad Pro 10.5
* Build version: ? Firefox Daylight 35.0 (5448)
### Notes
Running iOS 14.7.1, but this has been happening since sometime like 14.5.  Icons and titles appear again as each individual site is accessed, but then disappear sporadically, as noted above.
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3023)

**Comment by SimonBasca** [comment]
Thanks for the feedback, could you post a screenshot of the issue?

**Comment by Gpwidin** [comment]
Simon,
Here's one pic showing that there are some icons showing, but many are
missing.  In this pic, the first 2 characters of the title of each site are
visible, but the icon is usually missing and replaced only by the default
globe icon.  I don't have a pic of the case where BOTH titles and icons are
missing, but I will get one once the problem recurs, and also send that to
you.
Thanks for responding so quickly,
     Greg

[image: image.jpeg]

**Comment by Gpwidin** [comment]
Simon,
As promised, here is a further screen shot showing before and after of the
disappearing icons in Firefox for iOS.

This is an example of what happens sometimes, where _both_ icons and the
alphanumeric designator for the tabs disappear, leaving only the generic
globe icons.  Unfortunately, the sites shown in the two views are not
identical, but all the sites in the second view were showing both icons and
designators before they, too, disappeared.  FWIW, the only sites which show
up with alpha designators in the second view are Google (“0-“ and “Ax”) and
Apple (“Sy” and “IC”).

Hope this is helpful, and further demonstration that there really is a
problem here.
FWIW, I tried numerous different apps, both Apple and others, to get the
disappearance to occur.  Only restarting did the trick here, though I am
virtually certain that it has also occurred when running some other app and
then returning to Firefox, but without re-starting OR powering off.
     Greg

Original header with intact icons
[image: image.png]

Header with missing icons after power off and restart
[image: image.png]

**Comment by SimonBasca** [comment]
@Gpwidin something happened to the attachment and I am unable to view them. Could you please try re-attaching them?

**Comment by SimonBasca** [comment]
Still no luck seeing the images. Could you please go to https://github.com/mozilla-mobile/firefox-ios/issues/8942, drag and drop the pictures in a comment. Thanks.

**Comment by Gpwidin** [comment]
![71B60E81-27E0-4748-B1BB-9A1B38EAEDD8](https://user-images.githubusercontent.com/88335124/128351109-925bd408-2928-4d6f-8bda-56be4c479370.jpeg)
![C1748AEE-22A7-4EDA-A711-E4EC73AF4134](https://user-images.githubusercontent.com/88335124/128351112-6c7baa0a-1d50-4aea-af4d-8a1b12bc8de5.jpeg)

Simon,
Let me know if this works.
    Greg

**Comment by Gpwidin** [comment]
Done, 1 hr ago.  I can see the images in GitHub so assume they are OK.
Note that the 1st and 2nd images are transposed as uploaded.  The bottom is
the original appearance of the address bar; the top is the appearance after
(most of) the alpha identifiers and non-generic icons are lost.
     GW

**Comment by SimonBasca** [comment]
Thanks, the images are good. We will discuss the issue with the team and triage it accordingly.

**Comment by dnarcese** [comment]
More info #8984

**Comment by Gpwidin** [comment]
Now, even the close X’s are missing.
![AE2620C4-E73B-4DD0-8DB3-8A6536754E1D](https://user-images.githubusercontent.com/88335124/129562325-f5a3d5be-1539-494f-adce-da6fe127c17d.jpeg)

**Comment by Gpwidin** [comment]
Firefox iOS Version 36 supposed to solve tab previews being missing.
See screen shot below—they still are gone after re-boot!  Same configuration as original post, except for update to Version 36. :-(

![7DC73227-C1A1-4929-BD6D-C0E54AD4218D](https://user-images.githubusercontent.com/88335124/129754882-604f56bc-6822-4f63-afd3-183a1624c0fa.jpeg)

**Comment by Gpwidin** [comment]
Now on iOS 14.8, Firefox for iOS v 37.  Still iPad Pro 10.5.
Still same problem—icons disappeared after reboot.
Considering using another browser…

**Comment by Gpwidin** [comment]
NOW on iOS 15.0, Firefox for iOS v 37, still iPad Pro 10.5.
STILL same problem—icons disappeared after reboot.
Approaching 2 months since I posted about a problem that had been ongoing for some time…

**Comment by Gpwidin** [comment]
I have discovered that a reliable to cause _almost_ all icons to disappear is to force close the app and then restart.  I say “almost” because this appears to retain the icon for the site one is on—or maybe this is just because that site gets re-opened (if the new Home “feature” is disabled) when Firefox restarts.  Same configuration as above: iOS 15, v 37, iPad Pro 10.5.

**Comment by Gpwidin** [comment]
In iOS 15, going split screen and adding Messages screen to Firefox, then back to only Firefox also wipes out favicons and text on tabs.

**Comment by Gpwidin** [comment]
Tied resetting all settings.  After re-start and reconnect, force-closing Firefox still results in lost favicons.  No improvement.

**Comment by Gpwidin** [comment]
Re-reading my previous comment, I realize that it might not be clear what I did.  I tried resetting all _iOS_ settings.  Pretty drastic, but I had seen that other users having problems in iOS with other apps had had success by doing this.  So, since nothing seemed to be happening with fixing this bug, I was curious about whether it might be something specific to my individual iPad.  As I said in the previous comment, this produced no improvement.
So, the problem continues.  Current configuration is iPad Pro 10.5, iOS 15.0.1, Firefox Daylight 38.1.

**Comment by Gpwidin** [comment]
Problem persists.
Daylight 38.1, iPadOS 15.0.2, iPad Pro 10.5.

**Comment by tech189** [comment]
Still an issue in v39.0

**Comment by SimonBasca** [comment]
Verified fix on main 3854167149a
We also found a new issue while testing -> https://github.com/mozilla-mobile/firefox-ios/issues/9548

**Comment by SimonBasca** [comment]
Verified fix on 40.0 (6528)

**Comment by HaBiMuc** [comment]
Hi,
any news on this issue? I‘ve still this problem with Firefox 108.1 (24234) with iPadOS 16.2 on an iPad Air (5. Generation)
Thanks
HaBiMuc

**Comment by lmarceau** [comment]
Hello @HaBiMuc, since this issue was closed I would recommend opening a new one [here](https://github.com/mozilla-mobile/firefox-ios/issues/new/choose). Thank you!
