### ISSUE TITLE
Request desktop site doesn't work with most sites

### ISSUE THREAD

**Issue by bpsib** [mozilla-mobile/firefox-ios#8945]
The request desktop site feature fails to work with websites that use responsive design. This makes Firefox iOS useless for me. I often like to use the desktop layout. An example is on this site (GitHub) so I can see in advance if an issue has comments and how many.

Safari has a zoom out feature that can get the desktop layout on sites that use responsive design. Firefox should either fix the request desktop site feature or add a zoom out feature.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3025)

**Comment by data-sync-user** [comment]
➤ Daniela Arcese commented:

This can be solved with a zoom feature https://mozilla-hub.atlassian.net/browse/FXIOS-2618 ( https://mozilla-hub.atlassian.net/browse/FXIOS-2618|smart-link )

**Comment by bpsib** [comment]
> 
> 
> ➤ Daniela Arcese commented:
> 
> This can be solved with a zoom feature https://mozilla-hub.atlassian.net/browse/FXIOS-2618 ( [https://mozilla-hub.atlassian.net/browse/FXIOS-2618|smart-link](https://mozilla-hub.atlassian.net/browse/FXIOS-2618%7Csmart-link) )

Link not accessible

**Comment by dnarcese** [comment]
@bpsib https://github.com/mozilla-mobile/firefox-ios/issues/7596
