### ISSUE TITLE
Unable to close tab by clicking X on iOS

### ISSUE THREAD

**Issue by dethier1958** [mozilla-mobile/firefox-ios#8949]
Using Firefox on iPhone or iPad. Tapping the close button on the tab (the X on the right end of the tab) does not close the tab. This started with the recent update to the new style of tabs on iOS.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3029)

**Comment by dnarcese** [comment]
Duplicate of #8613
