### ISSUE TITLE
Opening a new tab add the page to the Jump in section when new tab is set as custom URL

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#8956]
## Preconditions
* Set new tab as custom url e.g: "google.com"
* Enable "Jump In" section
  1. Steps to reproduce

1. Open a new tab
    1. Expected behavior

* We should have a flag for the "Jump in" section to not be displayed for users who have New Tab as custom URLs.
    1. Actual behavior
* Every time a new tab is opened the page is added to the Jump in section
    1. Device & build information
* Device: iPad Pro (14.6)
* Build version: 36.0(5718)
    1. Notes
Attachments: 
[video.mp4.zip](https://github.com/mozilla-mobile/firefox-ios/files/6930379/video.mp4.zip)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3037)

**Comment by data-sync-user** [comment]
➤ Daniela Arcese commented:

It is okay if we have the new tab page in Jump Back In, but we should filter out any duplicates in case a user opened more than one new tab and never went back to them.
