### ISSUE TITLE
Switch is glitchy when switching between normal and private browsing

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#8957]
## Steps to reproduce
1. Open a tab in normal browsing
1. Open tabs tray
1. Open a tab in Private Browsing
1. Switch between normal and private browsing
    1. Actual behavior

* The switch moving between normal and private browsing is glitchy
    1. Device & build information
* Device: iPhone Xr (14.6)
* Build version: 36.0 (5718)
    1. Notes
Attachments: 
[video.mp4.zip](https://github.com/mozilla-mobile/firefox-ios/files/6930477/video.mp4.zip)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3038)

**Comment by dnarcese** [comment]
@SimonBasca can you clarify where the glitch is? I am not noticing anything obvious from the video.

**Comment by isabelrios** [comment]
Sorry I closed it by mistake. If you look at the tab counter or the mask buttons at the toolbar, the buttons move horizontally, like they vibrate.
