### ISSUE TITLE
Closing last Private Tab leaves you unable to create more when New Tab is set to blank

### ISSUE THREAD

**Issue by tmalloy** [mozilla-mobile/firefox-ios#8982]
## Steps to reproduce
Have New Tab set to Blank

1. Have a blank new tab open in Normal Mode
1. Navigate to screen showing all private tabs.
1. Close them all individually (not using trash can icon bottom left)

### Expected behavior
Keyboard should not appear.

### Actual behavior
Keyboard appears, covering the “+” button to create new private tab.

### Device & build information
* Device: iPhone 11 Pro Max
* Build version: 35.0 as shown in the App Store.
    1. Notes
Attachments: 
![E2F203D9-A828-435F-B15F-1F36E3B61965](https://user-images.githubusercontent.com/45194/128905828-170229ca-9f4d-4a2e-be37-c7fab27280c1.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3062)

**Comment by dnarcese** [comment]
@tmalloy Could you try to reproduce this on v36 which is releasing this week? I am unable to reproduce with that version.

**Comment by tmalloy** [comment]
@dnarcese I just updated to v36 and am still seeing the same issue. In case I wasn’t clear describing the steps, I made a video showing me swiping closed the last private tab.

https://user-images.githubusercontent.com/45194/129213577-367f71b5-cb83-45d7-af43-fd7511b441a3.mov

![7AED05CC-AA09-432A-9920-5A2C288634B8](https://user-images.githubusercontent.com/45194/129213595-99194098-d617-4e3a-bad6-ec83d003c8ff.png)

**Comment by dnarcese** [comment]
@tmalloy could you share what your settings are for New Tab and Home? I am still unable to reproduce this so I am thinking there is something else specific going on.

**Comment by tmalloy** [comment]
@dnarcese sure thing, here you go! 
![3FC91A48-1B85-4419-A1DA-D05DCDA5C8FA](https://user-images.githubusercontent.com/45194/129245888-5a2e5f10-12e1-46e9-8057-2f6f76c49db7.jpeg)

**Comment by tmalloy** [comment]
I just found another necessary factor to reproduce, you must also have no open non-private tabs.
