### ISSUE TITLE
pocket titles are large and not readable

### ISSUE THREAD

**Issue by karlcow** [mozilla-mobile/firefox-ios#8986]
## Steps to reproduce
1. Set in system preferences of ios. Settings -> Luminosité et Affichage (the blue icon with the two AA. Light and Display?) -> Text Size -> Make the text bigger.  (This is useful for people with bad eyesights)
2. Open Firefox iOS
3. activate the Pocket suggestions
4. Create a new tab  
5. Scroll to the pocket suggestions

### Expected behavior
Read the titles under the photos

### Actual behavior
The large text of the title is not readable. 

### Device & build information
* Device: iphone XS
* Build version: 35.0 (5448)
### Notes
Attachments: 
![pocket-issue-firefox-ios](https://user-images.githubusercontent.com/505230/129145834-f4d6a945-637c-46bb-987b-123ab15a94ff.jpg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3070)

**Comment by data-sync-user** [comment]
➤ Daniela Arcese commented:

This is covered in #8617
