### ISSUE TITLE
Youtube.com - It is impossible to share a video via Email

### ISSUE THREAD

**Issue by BigSamSampson** [mozilla-mobile/firefox-ios#8990]
## Steps to reproduce
1. Open testing firefox browser
1. Go to Youtube.com
1. Open any video
1. Tap on Share
    1. Expected behavior
The user expects to be able to share some video using Email.
    1. Actual behavior
Share menu closes and the user cannot share video using Email.
    1. Device & build information

* Device: Apple iPhone 8 Plus - iOS 14.6
* Build version: firefox daylight 36.0.5732
    1. Notes
Attachments: 
![image](https://user-images.githubusercontent.com/66958331/129575994-309fc51e-98ff-4718-b6e2-4b2d66fff985.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3073)

**Comment by data-sync-user** [comment]
➤ Daniela Arcese commented:

The problem is that we aren’t supporting the link format mailto:?
