### ISSUE TITLE
Live.com - The picture is zooming after scrolling down

### ISSUE THREAD

**Issue by BigSamSampson** [mozilla-mobile/firefox-ios#9000]
## Steps to reproduce
1. Navigate to URL http://Live.com
2. Scroll down.
### Expected behavior
The picture is not zooming after scrolling.
### Actual behavior
The picture is zooming after scrolling.
### Device & build information
* Device: Apple iPhone XS - iOS 14.5
* Build version: 36.0.5732
### Notes
Attachments: 
![image](https://user-images.githubusercontent.com/66958331/129885181-70b81142-8a04-4357-b7b4-b158ae51f7cc.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3082)

**Comment by data-sync-user** [comment]
➤ Daniela Arcese commented:

This just seems to be the way the website is setup. Going to close as a non-issue.
