### ISSUE TITLE
URL with uppercase schema is silently ignored when opened from a QR code scanned by the camera

### ISSUE THREAD

**Issue by huonw** [mozilla-mobile/firefox-ios#9013]
## Steps to reproduce

QR code containing `HTTPS://MOZILLA.ORG`
![image](https://user-images.githubusercontent.com/1203825/130407467-779d107a-8f33-48a3-86d6-d5ec3489c1c5.png)

1. Open Camera app and scan the first image
2. Click on the "open in Firefox" notification
3. Note that the phone switches to Firefox, but the URL doesn't open

### Expected behavior

The URL should be opened, as it is with a lower-case schema, and as it is if Safari is the default browser.

Demo: QR code containing `https://MOZILLA.ORG` (note lowercase schema)
![image](https://user-images.githubusercontent.com/1203825/130407532-40f741fa-c001-4a16-b2aa-2f0d6181bd01.png)

Video:

https://user-images.githubusercontent.com/1203825/130408278-e5eab23b-6a99-40ac-a6d4-5e9143371922.mov

### Actual behavior

The URL doesn't open, and Firefox just sits displaying the most recent page, e.g. this video shows me scanning the first QR code above having left Firefox at https://github.com

Video:

https://user-images.githubusercontent.com/1203825/130408141-59ff5933-dd44-449d-8f01-9bd25cf4b260.mov

### Device & build information
* Device: iPhone 8+
* Build version: Firefox Daylight 36.0 (5732)
### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3094)

**Comment by gutley** [comment]
Seems a duplicate of https://github.com/mozilla-mobile/firefox-ios/issues/8864

**Comment by huonw** [comment]
That does seem to be the case!
