### ISSUE TITLE
iOS 15 support

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#9024]
As a user who has upgraded to iOS 15, I want to keep using Firefox as I was before upgrading, with no new crashes or breaking features.

As a developer submitting an app for iOS 15, I want all the tools to be upgraded so that I can submit without problems and on time.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3103)

**Comment by ORIOLESFan02** [comment]
I just updated to iOS 15 yesterday. I don't notice any problems with firefox. The only thing is that there's still no option to have the address bar at the bottom of the screen like Safari and the Android version of Firefox has,

**Comment by c-thun** [comment]
Firefox repeatedly keeps crashing on iOS 15 Beta 8 (has been crashing from Beta 1). In addition, if it is able to tint status bar based on website background/theme color, it would match the modern aesthetic of Safari better.
