### ISSUE TITLE
Bookmark Search

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#9035]
**Vision**

As a user who saves a lot of bookmarks, I want the ability to search through my bookmarks, so that I can find the page I want to open without sifting through too many other items

**Acceptance Criteria**

* Search bar added to bookmarks panel
* Search bar will always be at the top of the bookmarks panel with placeholder text “Search Bookmarks”
  * should not show on any other panel
* Searching will display results for bookmarks in all folders, including desktop

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3107)

**Comment by Blackberryzh** [comment]
Coming from Google Chrome, this is my largest issue with Firefox on iOS

**Comment by data-sync-user** [comment]
➤ Laurie Marceau commented:

Questions: 

  * How are the search results sorted when they appear? By title? By url? By date? 
  * When a user makes a search query, should it filter only on the title, or also on the bookmark url?

**Comment by plwt** [comment]
User feedback: https://support.mozilla.org/en-US/questions/1377036

**Comment by data-sync-user** [comment]
➤ Ashley Thomas commented:

Closing as duplicate of https://mozilla-hub.atlassian.net/browse/FXMUX-215 ( https://mozilla-hub.atlassian.net/browse/FXMUX-215|smart-link )
