### ISSUE TITLE
Opening a New Tab automatically opens the keyboard

### ISSUE THREAD

**Issue by ORIOLESFan02** [mozilla-mobile/firefox-ios#9036]
## Steps to reproduce
Open a new tab
### Expected behavior
Show the new tab screen and do nothing else.
### Actual behavior
Shows the new tab screen, but the keyboard opens up and you have to tap the back arrow at the very top on the left to get out of it.
### Device & build information
* Device: iPhone X
* Build version: 36.0 (5372)
### Notes: 
Just annoying in my opinion. I wish there would be an option or a fix to this problem. I would attach a screen recording, but the screen recording doesn’t show swipes or taps, so it may be hard to know where you’d be looking at.
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3108)

**Comment by ORIOLESFan02** [comment]
Just noticed that something similar was posted here (#8954), but that was with an iPad. Will look to see if there are any more reports either with an edit or a new comment.

**Comment by ORIOLESFan02** [comment]
#9037 also has something very similar to what's happening to me, so I just wanted to add that here as well.

**Comment by dnarcese** [comment]
Opening the keyboard on new tab is a feature we have added. There is a bug though that we are working on fixing to get out of the URL bar when you scroll down on the page instead of always having to click the back button.

**Comment by ORIOLESFan02** [comment]
> Opening the keyboard on new tab is a feature we have added.

Would there ever be an option to disable this feature if we didn’t want it in later versions of the software?
