### ISSUE TITLE
New ETP panel truncated in French

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla-mobile/firefox-ios#9048]
## Steps to reproduce

Click the shield icon in the address bar, "Protection renforcée contre le pistage" toggle is truncated.

### Device & build information
* Device: iPhone X
* Build version: 5916
### Notes
Attachments: 
![IMG_7390](https://user-images.githubusercontent.com/1294206/131821516-27bf5aa6-c5c7-40cb-a01b-47cf0304b3b9.PNG)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3116)

**Comment by data-sync-user** [comment]
➤ Nishant Patel commented:

PR for this - https://github.com/mozilla-mobile/firefox-ios/pull/9067 ( https://github.com/mozilla-mobile/firefox-ios/pull/9067|smart-link )

**Comment by isabelrios** [comment]
Italian is also affected by this issue

**Comment by electricRGB** [comment]
[PR](https://github.com/mozilla-mobile/firefox-ios/pull/9100) for a fix
