### ISSUE TITLE
ETP menu is incorrectly displayed after switching orientation

### ISSUE THREAD

**Issue by csuciu** [mozilla-mobile/firefox-ios#9049]
v37.0 (5922)
iPhone 12 Pro (14.6)

1. While in portrait mode tap on the shield icon to open the ETP menu.
2. Switch to landscape.
3. Switch back to portrait.

Expected: The menu respects the bottom safe area.

Actual: The menu is incorrectly displayed and it occupies the safe area.

Should the menu be dismissed when changing orientation to avoid this kind of display issues?
[Skype_Video.mp4.zip](https://github.com/mozilla-mobile/firefox-ios/files/7098172/Skype_Video.mp4.zip)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3117)

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verified fix on 37.0 (5971)
