### ISSUE TITLE
Unable to scroll on long untrusted connection details

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#9051]
## Steps to reproduce
1. Go to badssl.com
2. Tap on the "lock icon"
3. Tap on "insecure connection"
4. Try scrolling
### Expected behavior
- The view should be scrollable
### Actual behavior
- The view is not scrollable
### Device & build information
* Device: iPhone Xr (14.6)
* Build version: 37.0 (5922)
### Notes
Attachments: 
<img width="365" alt="image" src="https://user-images.githubusercontent.com/32130829/131839863-2e7f56ab-67ff-43ff-96ee-d1d50edaf733.png">

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3119)

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verified fix on main 42bb8dc61447541b984f21b33c8ae72e996899ea
