### ISSUE TITLE
A Reload icon that acts like the Home button is displayed on phones in landscape & on iPads

### ISSUE THREAD

**Issue by csuciu** [mozilla-mobile/firefox-ios#9053]
v37.0 (5922)
iPhone 12 Pro (14.6)

1. Visit a page on iPad or on iPhone in landscape mode.
   => A Reload icon is displayed on the left side of the URL bar.
2. Tap on it.

Actual: The Homepage opens.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3121)

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verified fix on v37.0 (5971)
