### ISSUE TITLE
Home button still shows up in the App menu

### ISSUE THREAD

**Issue by csuciu** [mozilla-mobile/firefox-ios#9054]
v37.0 (5922)
iPhone 12 Pro (14.6)

1. Open the App menu.

Expected: There should be no "Home" item in the menu since the button was moved to the toolbar.

Actual: Home button is still listed in the App menu.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3122)

**Comment by data-sync-user** [comment]
➤ Nishant Patel commented:

See https://github.com/mozilla-mobile/firefox-ios/pull/9064 ( https://github.com/mozilla-mobile/firefox-ios/pull/9064|smart-link ) .

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verified fix on 37.0 (5971)
