### ISSUE TITLE
Issue with file export on Firefox iOS

### ISSUE THREAD

**Issue by cam1170** [mozilla-mobile/firefox-ios#9057]
When Firefox uses the “export file” feature and sends the file (like a PDF) to the share sheet for websites which require authentication, like for school, it exports the file received assuming I’m not logged in. For instance, if the file location is at a URL that requires authentication to access. This isn’t the same as Safari’s behavior, where I get the correct file. Is this an issue with the Safari engine used in Firefox?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3124)

**Comment by dnarcese** [comment]
Duplicate of #6069
