### ISSUE TITLE
Picture-in-picture mode fails with YouTube

### ISSUE THREAD

**Issue by ChaiTRex** [mozilla-mobile/firefox-ios#9062]
With YouTube, entering picture-in-picture mode almost immediately exits picture-in-picture mode and then plays video that's not centered in the video frame.

## Steps to reproduce

1. Watch a YouTube video.
2. Switch to full-screen mode.
3. Switch to picture-in-picture mode.

### Expected behavior

Video plays in picture-in-picture mode.

### Actual behavior

Video immediately switches back to normal in-browser playing with video centered on the center of the page, even though the video frame is at the top of the page.

If I time it just right, I can press the picture-in-picture button and then press the home button to get sustained picture-in-picture mode outside Firefox, but if the timing is wrong, it fails.

### Device & build information
* Device: iPhone 7
* Build version: Firefox Daylight 36.0 (5732)
### Notes
Attachments: Demonstration video

https://user-images.githubusercontent.com/23159282/132077460-d23e2f26-84b3-44ac-88e1-4adc65e9c769.MP4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3126)

**Comment by zosjub-3kExza-derwim** [comment]
О

**Comment by dnarcese** [comment]
This is a youtube limitation

**Comment by ChaiTRex** [comment]
No, this isn't a YouTube limitation. YouTube isn't involved in making the video picture-in-picture, so YouTube cannot fail at what it is not doing.
