### ISSUE TITLE
[XCUITest] Add new test to cover the home button

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/firefox-ios#9072]
There is a new Home button in the toolbar. 
It would be nice to have an automated test to cover its functionality

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3128)

**Comment by isabelrios** [comment]
@AaronMT This is the automated test we were talking about last week. Would you like to work on this? Thanks!

**Comment by AaronMT** [comment]
WIP

Landscape bug button missing
https://github.com/mozilla-mobile/firefox-ios/issues/9076

TestRail: [Test Case ](https://testrail.stage.mozaws.net/index.php?/cases/view/1512611&group_by=cases:section_id&group_order=asc&group_id=227694)
