### ISSUE TITLE
[Crash] Password autofill is broken

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#9073]
## Preconditions
* Log in to FxA
* Enable auto fill passwords for Firefox beta 37.0 (5922)
  1. Steps to reproduce

1. Go to a login form (In my case I opened a login form in Safari)
1. Tap on "Passwords"
1. Select Firefox Beta
    1. Expected behavior

* The login list should be populated.
    1. Actual behavior
* After step 3) going to Firefox Settings -> Passwords will cause the app to crash
    1. Device & build information
* Device: iPhone 12 Pro (14.7)
* Build version: 37. 0(5922)
    1. Notes
Attachments: 
[video.mp4.zip](https://github.com/mozilla-mobile/firefox-ios/files/7115687/video.mp4.zip)

[Client-2021-09-03-192916.ips.beta.zip](https://github.com/mozilla-mobile/firefox-ios/files/7115701/Client-2021-09-03-192916.ips.beta.zip)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3129)

**Comment by st3fan** [comment]
I'll investigate what is going on here

**Comment by st3fan** [comment]
@SimonBasca i can't reproduce this .. have you encountered this again? Do we have a crash report in the crash explorer?

**Comment by SimonBasca** [comment]
This issue is no longer reproducible on v95 (6631) or v9000 (6845)

**Comment by SimonBasca** [comment]
@st3fan This was the crashlog when the issue was reproduced 
[Client-2021-09-03-192916.ips.beta.zip](https://github.com/mozilla-mobile/firefox-ios/files/7595629/Client-2021-09-03-192916.ips.beta.zip)
