### ISSUE TITLE
Home Button missing from tab toolbar in landscape

### ISSUE THREAD

**Issue by AaronMT** [mozilla-mobile/firefox-ios#9076]
Build: 03e2623be927739557a9bb209afa3fff182d8680 

![Simulator Screen Shot - iPhone 12 - 2021-09-07 at 15 55 58](https://user-images.githubusercontent.com/102331/132403462-2b0550db-3475-4c44-ab21-026c9097db6d.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3134)

**Comment by isabelrios** [comment]
@AaronMT I think this is fixed in latest main... thanks to this commit: 3a88629cb415c576388b554255c75b81a7940341

![Simulator Screen Shot - iPhone 11 - 2021-09-08 at 11 16 39](https://user-images.githubusercontent.com/1897507/132482662-de329a58-4539-473e-a706-8877942a6813.png)

**Comment by AaronMT** [comment]
I'll re-test

**Comment by AaronMT** [comment]
It exists on the bar now for the purposes of this bug.
