### ISSUE TITLE
iPad - Search icon is not enabled

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/firefox-ios#9079]
## Steps to reproduce
On iPad launch the app and close url bar focused

### Expected behavior
All available buttons (except for back and forward) should be active

### Actual behavior
Search icon, magnifier glass is not enabled.

### Device & build information
* Device: iPad
* Build version: latest main

### Notes
See iPad screenshot versus iPhone:
![Captura de pantalla 2021-09-08 a las 12 48 55](https://user-images.githubusercontent.com/1897507/132498013-53394c75-03c7-48d2-8d2a-9b1313e500b7.png)
![Simulator Screen Shot - iPhone 11 - 2021-09-08 at 13 01 25](https://user-images.githubusercontent.com/1897507/132498190-f32bad63-095a-4016-9d49-2c4da2df0d75.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3135)

**Comment by SimonBasca** [comment]
This is also reproducible in beta 37.0 (5971)

**Comment by data-sync-user** [comment]
➤ Daniela Arcese commented:

This search icon should not even show up on iPad (as per original issue #6846)
