### ISSUE TITLE
Long press on Home button opens "Request desktop site" menu

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#9080]
## Steps to reproduce
1. Go to "Youtube.com"
2. Long press on the Home button
### Expected behavior
- No menu should open.
### Actual behavior
- "Reload desktop site " menu opens.
### Device & build information
* Device: iPhone 12 Pro (14.7)
* Build version: 37. 0(5971)
### Notes
Attachments: 
![Screenshot](https://user-images.githubusercontent.com/32130829/132537150-c4dcc514-2c6f-43b7-a021-28f6eef25f0e.jpeg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3136)

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verified fix on main 6d2f1b4cbe546aacc398436223f19d7592295c5c.
