### ISSUE TITLE
Home Button is considered reload in landscape (?)

### ISSUE THREAD

**Issue by AaronMT** [mozilla-mobile/firefox-ios#9083]
Build: 431b08bc
visit twitter.com, rotate phone

(@nishant2718)

```Swift
Other, 0x600002fa0000, {{0.0, 0.0}, {844.0, 54.0}}
                      Button, 0x600002fa00e0, {{57.0, 5.0}, {44.0, 44.0}}, identifier: 'URLBarView.backButton', label: 'Back'
                      Button, 0x600002fa01c0, {{101.0, 5.0}, {44.0, 44.0}}, label: 'Forward', Disabled
                      Button, 0x600002fa02a0, {{145.0, 5.0}, {44.0, 44.0}}, label: 'Reload'
```

Tapping this 'reload' button takes me to the home screen.

```Swift
XCUIDevice.shared.orientation = .landscapeLeft
print(app.debugDescription)
XCTAssertTrue(app.buttons["Reload"].exists)
app.buttons["Reload"].tap()
navigator.nowAt(NewTabScreen)
```

Expected the button/label to reflect 'Home'. Is it possible that the previous reload button is still code?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3139)

**Comment by isabelrios** [comment]
@AaronMT can we close this issue after latest changes in main?

**Comment by AaronMT** [comment]
Which? (@nishant2718 ?)

**Comment by isabelrios** [comment]
That homebutton is considered reload in landscape. A few fixes landed, not sure if this is still an issue..

**Comment by SimonBasca** [comment]
Tapping on the home button in landscape take the user to the home page. For the case when long pressing on home button we have this issue #9080
