### ISSUE TITLE
Quick-search engine icons are not available

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/firefox-ios#9084]
## Steps to reproduce
Go to Search menu in settings
Tap on Add Search Engine option
Add a search engine, for example:
-Name: Mozilla Engine
-URL: https://developer.mozilla.org/search?q=%s
Tap on Save
Open a new tab and type any word, for example: window

### Expected behavior
The new created search engine is available:
![IMG_6971CAB6A7EA-1](https://user-images.githubusercontent.com/1897507/132548857-885c9933-1d53-4e76-a265-a79c5cc18e64.jpeg)

### Actual behavior
There are no search engines list available
![Simulator Screen Shot - iPhone 11 - 2021-09-08 at 18 26 18](https://user-images.githubusercontent.com/1897507/132548558-3aa0c40e-cb4d-45f6-9961-135576ac1f67.png)

### Device & build information
* Device: iPhone and iPad
* Build version: latest main 431b08b  , not reproducible on Beta

Has something changed around this feature or is this a Regression?
There are two automated tests failing due to that.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3140)

**Comment by SimonBasca** [comment]
Confirming this bug is reproducible on latest main 431b08b

**Comment by isabelrios** [comment]
I think this should be prioritized since for some reason the menu has dissapear and as far as we know this is not a new requirement, is that right?
cc @athomasmoz

**Comment by isabelrios** [comment]
@nishant2718, @nbhasin2, this is the commit where the issue started: https://github.com/mozilla-mobile/firefox-ios/commit/e961bfdb5d2acd7a30f094538002f08b67908337

Hope it makes sense to undestand why and how to fix it a bit bettter :)

**Comment by SimonBasca** [comment]
Verified fix on v38.1 (6216).

**Comment by p-m-j** [comment]
I have 38.1 according to AppStore but this bug is still present.

**Comment by SimonBasca** [comment]
@p-m-j could you please post a video of the issue? Also on what ios version are you reproducing?

**Comment by p-m-j** [comment]
@SimonBasca was 14.7.1, updated to 15.0.1 issue still present.

No video but hopefuly these images are enough?

<img src="https://user-images.githubusercontent.com/2056399/136210989-70ab2c2b-cf52-443d-98e2-928f9685e535.PNG" width="400"/>

<img src="https://user-images.githubusercontent.com/2056399/136211001-f5edf60a-fe16-48ce-9ed3-b867dc143dc6.PNG" width="400"/>
