### ISSUE TITLE
Firefox Crashes Randomly on iOS 15

### ISSUE THREAD

**Issue by c-thun** [mozilla-mobile/firefox-ios#9096]
## Steps to reproduce
Doesn't seem to be happening because of a fixed set of actions. The only constant is that Firefox crashes at least once per browsing session.

### Expected behavior
For the web browser to not crash

### Actual behavior
Randomly crashes. On opening again, a message is received "Well that was embarrassing. Would you like to reopen your old tabs?"

### Device & build information
* Device: iPhone 12
* Build version: Firefox 37.0 (5971)

!image-20210923-211219.png|width=2706,height=452!

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3149)

**Comment by csuciu** [comment]
Hi @c-thun! Is it possible for you to get a crash log from your device and attach it here?

Thanks!

**Comment by c-thun** [comment]
How to do that? I would be glad to but don't know the steps.

**Comment by csuciu** [comment]
Thanks c-thun. We'll try to find clear steps to reproduce.

**Comment by ORIOLESFan02** [comment]
Can confirm that it crashes a lot on iOS 15.

**Comment by caravinci** [comment]
Observed the same behaviour on iPhone SE (2nd gen) - Firefox Daylight 37.0 (5971)

**Comment by c-thun** [comment]
Somehow the frequency of crashes has significantly reduced (gone?) on iOS 15 RC. Could others confirm as well? Maybe this was an iOS side bug?

**Comment by caravinci** [comment]
Still seeing issues in iOS 15.0 (19A344)

**Comment by rootwarrior** [comment]
Firefox has been crashing randomly  for me for  weeks now on the latest beta builds of iOS 15 (and now RC 1, 15.0 (19A344).

On a 2016 iPhone SE
Latest Firefox Daylight 37.0 (5971)

I'm not positive on how to check for the crash logs requested, but nothing for Firefox shows up under: Settings / Privacy / Analytics & Improvements / Analytics Data.

**Comment by c-thun** [comment]
> Firefox has been crashing randomly  for me for  weeks now on the latest beta builds of iOS 15 (and now RC 1, 15.0 (19A344).
> 
> 
> 
> On a 2016 iPhone SE
> 
> Latest Firefox Daylight 37.0 (5971)
> 
> 
> 
> I'm not positive on how to check for the crash logs requested, but nothing for Firefox shows up under: Settings / Privacy / Analytics & Improvements / Analytics Data. 

Firefox iOS app is not named as Firefox in the Analytics Data. It is named as "Client"

**Comment by rootwarrior** [comment]
> Firefox iOS app is not named as Firefox in the Analytics Data. It is named as "Client"

Thanks... Good thing FF on iOS gives the crash reports an intuitive name... </sarc>

3 of my crash reports:
[Firefox-crashreports-rootwarrior.zip](https://github.com/mozilla-mobile/firefox-ios/files/7197508/Firefox-crashreports-rootwarrior.zip)

**Comment by c-thun** [comment]
iOS 15 is releasing today. This bug might need to be fixed slightly quicker. 

As an update on the status, even when you let Firefox restore tabs before the crash, it always seems to "forget" one or two tabs that never get recovered so you also lose part of your browser history. Really fun!

**Comment by irr123** [comment]
Same problem, logs looks similar with @rootwarrior
[Client-2021-09-21-025133.zip](https://github.com/mozilla-mobile/firefox-ios/files/7199436/Client-2021-09-21-025133.zip)

It happens on released iOS 15, iPhone XR.

**Comment by awkwardpause101** [comment]
Happens to me, too -- iPhone 12 Pro, FireFox 37.0.

**Comment by Kiesp** [comment]
Happy to hear it's not just me. Sad that it seems to be a problem for a lot of people.
iOS 15 (not beta, but also happened while on public beta)
iPhone 11
Attached a log from newly reinstalled app.
[Client-2021-09-21-213855.zip](https://github.com/mozilla-mobile/firefox-ios/files/7205819/Client-2021-09-21-213855.zip)

**Comment by Yuntao99** [comment]
I too has this issue. iPhone 6s (MKT82LL/A) iOS 15 (19A346). Firefox Daylight 37.0 (5971)

**Comment by ORIOLESFan02** [comment]
Here are my logs from about 2 days ago while running iOS 15.
[Client-2021-09-20-125717.zip](https://github.com/mozilla-mobile/firefox-ios/files/7211418/Client-2021-09-20-125717.zip)
iPhone X and was on the GM of iOS 15.

**Comment by sean-m-sweeney** [comment]
I'm getting consistent crashes since updating to iOS 15 yesterday. Just happened twice in a row trying to access American Express. iPhone 12 Mini here.
[Client-2021-09-22-135409.ips.zip](https://github.com/mozilla-mobile/firefox-ios/files/7212862/Client-2021-09-22-135409.ips.zip)

**Comment by ORIOLESFan02** [comment]
> Here are my logs from about 2 days ago while running iOS 15.
> [Client-2021-09-20-125717.zip](https://github.com/mozilla-mobile/firefox-ios/files/7211418/Client-2021-09-20-125717.zip)
> iPhone X and was on the GM of iOS 15.



I got more logs. This just happened about 2 hours ago.

[Client-2021-09-22-124114.zip](https://github.com/mozilla-mobile/firefox-ios/files/7213016/Client-2021-09-22-124114.zip)

**Comment by LeoniePhiline** [comment]
It’s crashing for me constantly, too. Seems like random occurrences, no fixed reproduction path. 

IPhone 11 Pro Max, iOS 15.0; updated Firefox

**Comment by Dignity1337** [comment]
I‘m having the same issue.
I just updated to iOS 15.0 on iPhone 7 and I use Firefox Daylight 37.0 (5971). Firefox crashes constantly. Basically everything that I want to do like opening a link or tapping a button will result in a crash.

**Comment by isabelrios** [comment]
I can repro this issue too on Release: v35 (5448) iPhone 12, iOS 15. 
Logs
[Client-2021-09-23-103956.ips.zip](https://github.com/mozilla-mobile/firefox-ios/files/7216103/Client-2021-09-23-103956.ips.zip)
:

I have always seen this crash when clicking on tabs counter to go to tab tray

I'm updating to v37 and will try on beta too.

**Comment by fowl2** [comment]
Still occurring with 

iOS 15.1 public beta 1 19B5042h
Firefox Daylight 37.0 (5971)

**Comment by data-sync-user** [comment]
➤ Daniela Arcese commented:

Thanks for all the feedback and crash logs, the team is actively investigating.

**Comment by Starker3** [comment]
I've been experiencing the same issue. It has decreased in frequency as the new Beta versions were released, but was still occurring in the latest 15.0 GM verion. I've attached 5 logs (Not sure if all of them are crash logs or maybe some other logs are included as well)
[Client-2021-09-23-164711.zip](https://github.com/mozilla-mobile/firefox-ios/files/7220816/Client-2021-09-23-164711.zip)
[Client-2021-09-18-094720.zip](https://github.com/mozilla-mobile/firefox-ios/files/7220817/Client-2021-09-18-094720.zip)
[Client-2021-09-22-170135.zip](https://github.com/mozilla-mobile/firefox-ios/files/7220818/Client-2021-09-22-170135.zip)
[Client-2021-09-23-144526.zip](https://github.com/mozilla-mobile/firefox-ios/files/7220819/Client-2021-09-23-144526.zip)
[Client-2021-09-18-095007.zip](https://github.com/mozilla-mobile/firefox-ios/files/7220820/Client-2021-09-18-095007.zip)

I've updated to the 15.1 Beta, so if it happens again I'll upload the latest crash logs

**Comment by InfiniteCookie** [comment]
I'm having this problem too, and was directed here to help.....but I am not a beta user and don't know how to find/generate/share crash logs.  Can someone point me to a guide to doing so, or do you already have all the data you need?

Behavior started on iOS 15 update last week, on iPhone running FF Daylight 37.0 as default browser.  Crashes often on opening new tabs or links, private and normal windows, usually keep about 4-6 tabs open in private and normal windows to review/refresh frequently, and on opening, those tabs accurately open but also one or two other tabs open from my personal web site--not designated as home page on any device using this FF account.

**Comment by rootwarrior** [comment]
> I'm having this problem too, and was directed here to help.....but I am not a beta user and don't know how to find/generate/share crash logs. Can someone point me to a guide to doing so, or do you already have all the data you need?

Go to: Settings / Privacy / Analytics & Improvements / Analytics Data.

Look for the entries marked "Client."

**Comment by InfiniteCookie** [comment]
Thanks.  Will set up uploads in a few hours when I have access to computer again.

**Comment by InfiniteCookie** [comment]
Sounds like there is already a fix; please reply to let me know if my crash logs are still useful.

**Comment by csuciu** [comment]
Thank you all for your feedback! 
This crash is currently verified as fixed on the latest TF build (6157).

**Comment by c-thun** [comment]
Is there an ETA on the release of the fixed build?
Thank you all so much, Mozilla team, for such a prompt and timely fix! And thanks to all the other commenters who were so forthcoming in sharing their crash logs as well :)

**Comment by rootwarrior** [comment]
I just got Firefox 38 (build 6157) on my phone... =-O

**Comment by nbhasin2** [comment]
Hi, this should be fixed in v38 which just got released.

**Comment by c-thun** [comment]
Crashed again for me. This time with no tabs open and on Version 38.0.
Here are the logs -

[Client-2021-09-30-124241.zip](https://github.com/mozilla-mobile/firefox-ios/files/7257476/Client-2021-09-30-124241.zip)

**Comment by csuciu** [comment]
@c-thun Can you please file a new issue for this last crash. Also do you mind sharing in the new issue, if you remember, what did you do before the app crashed (~STRs)?

**Comment by c-thun** [comment]
Sure, I'll create a new issue for this with steps to reproduce

**Comment by kthecoder** [comment]
App crashes when I do absolutely anything. Every five minutes or so of use.
