### ISSUE TITLE
"S>XL" size measurements are not visible on "Size guide" table with "Night mode"

### ISSUE THREAD

**Issue by softvision-oana-arbuzov** [mozilla-mobile/firefox-ios#9116]
## Prerequisites
"Night mode" is enabled.

## Steps to reproduce
1. Navigate to https://oldnavy.gap.com/browse/product.do?pid=706330052#pdp-page-content
1. Scroll down the page until reaching "Size" section.
1. Tap "Size Guide" button.
1. Observe the "Waist" measurements.

### Expected behavior
The measurements are visible for all sizes.

### Actual behavior
The measurements are not visible for "S>XL" sizes.

### Device & build information
* Device: iPad Mini 4 iOS 14.6 (1536 x 2048 pixels (~324 ppi density))
* Build version: Firefox Daylight 36.0 (5732)

### Notes
Attachments: 
![image](https://user-images.githubusercontent.com/12184325/133276711-a805d8de-2abb-4145-93fb-09a458413598.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3164)

**Comment by lmarceau** [comment]
Latest look of this issue:

![Simulator Screen Shot - iPhone 11 - 2022-06-13 at 12 47 03](https://user-images.githubusercontent.com/11338480/173403992-dc9a96d0-d0ef-44a9-88cf-eae19cfe09b4.png)
