### ISSUE TITLE
Pull to Refresh

### ISSUE THREAD

**Issue by aakash-kap** [mozilla-mobile/firefox-ios#9118]
### User Problem
> All major iOS web browsers (Safari, Brave, Chrome, upcoming Edge Chromium) have pull to refresh as a convenient way to refresh a webpage. Now that the reload button has been replaced with the Homepage button, it makes sense to support pull to refresh.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3166)

**Comment by data-sync-user** [comment]
➤ Nishant Patel commented:

Raised a PR https://github.com/mozilla-mobile/firefox-ios/pull/9136 ( https://github.com/mozilla-mobile/firefox-ios/pull/9136|smart-link ) .  

I am open to adding Telemetry to this feature Daniela Arcese Ashley Thomas . Let me know anytime!

**Comment by data-sync-user** [comment]
➤ Daniela Arcese commented:

Nishant Patel telemetry would be great!

**Comment by data-sync-user** [comment]
➤ Nishant Patel commented:

TODO: 

  * Have it behind a flag

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verified fix on 38.0 (6122).

**Comment by ayfine** [comment]
Please add a setting to disable this. Useful feature 9 times out of 10 but it is very easy (for me, at least) to accidentally refresh pages with form data that should not be refreshed. I've modified my own scrolling behavior but it still happens.
