### ISSUE TITLE
Cannot build project using Release mode Xcode 12.5.1

### ISSUE THREAD

**Issue by muhasturk** [mozilla-mobile/firefox-ios#9128]
## Steps to reproduce

- git pull
- sh bootstrap.sh --force
- Run `Firefox.scheme`

### Expected behavior
Build successfully

### Actual behavior
```
Module 'SwiftyJSON' was created for incompatible target arm64-apple-ios11.4: /Users/tcmhasturk/Documents/Work/firefox-ios/Carthage/Build/iOS/SwiftyJSON.framework/Modules/SwiftyJSON.swiftmodule/arm64.swiftmodule
```

### Device & build information
Xcode Version 12.5.1 (12E507) App Store
macOS 11.5.2 (20G95)

### Notes
Could not build project on Release mode. Fennec scheme which using "Debug.xcconfig" builds fine.
Main difference between Debug and Release config is ONLY_ACTIVE_ARCH variable.

#### Possible Solution
We should use xcframework or change ONLY_ACTIVE_ARCH = YES even on Release mode.

Do you guys have any other solution for this situation?

##### See
https://stackoverflow.com/a/64139830/3022613

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3174)

**Comment by dnarcese** [comment]
@muhasturk is there a reason you need to build the Firefox scheme and Fennec is not sufficient?

**Comment by muhasturk** [comment]
I've forked version and need to build on release mode. How do you build release mode?
