### ISSUE TITLE
Empty space in landscape toolbar

### ISSUE THREAD

**Issue by dnarcese** [mozilla-mobile/firefox-ios#9130]
## Steps to reproduce
Turn iPhone landscape 
### Expected behavior
No empty space beside + button
### Actual behavior
Empty space looks like there is a missing button
![image](https://user-images.githubusercontent.com/11432165/133670276-2489f5f4-532c-4d38-ae92-8df7c1e09312.png)
### Device & build information
* Device: ?
* Build version: ?
### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3175)

**Comment by SimonBasca** [comment]
Verified fix on v38.0 6157
