### ISSUE TITLE
Close all tabs does not work on iPad

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/firefox-ios#9131]
iPad Air 4th generation, main: 
00b709c

1. Open several tabs
2. Go to Tab Tray -> Click on Trash icon -> Close All Tabs

**Expected**
User is taken to the homescreen view and there is a snackBar button given the option to Undo the action

**Actual**
Nothing happens when clicking on the Trash icon. User stays in Tab Tray, tabs are not removed

Issue found by automated test: https://github.com/mozilla-mobile/firefox-ios/blob/main/XCUITests/TopTabsTest.swift#L118 that runs as part of the Smoketest for iPad

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3177)

**Comment by data-sync-user** [comment]
➤ Nishant Bhasin commented:

Note: For private tabs user will not see undo option
