### ISSUE TITLE
Full Webpage Screenshots

### ISSUE THREAD

**Issue by aakash-kap** [mozilla-mobile/firefox-ios#9138]
### User Problem
> Major browsers (Safari, Chrome, Edge) support taking full page screenshots using the native iOS functionality. Alternatively, Brave Browser allows for a "Create PDF" option that does the same thing effectively. Would be a good addition for Firefox to have as well. 

Firefox 
![image](https://user-images.githubusercontent.com/42250009/133918684-4a25d28d-dab1-433a-9828-a6b8a2e160f1.png)

Edge
![image](https://user-images.githubusercontent.com/42250009/133918687-303b6b8b-aa27-425e-9be8-4e3dcac69b0c.png)

Safari
![image](https://user-images.githubusercontent.com/42250009/133918689-53cdc8e9-c58c-4f47-b96c-6d079fe51715.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3181)

**Comment by q2r5** [comment]
The full page screenshot functionality requires #8897 and implementing [`screenshotService(_:generatePDFRepresentationWithCompletion:)`](https://developer.apple.com/documentation/uikit/uiscreenshotservicedelegate/3213937-screenshotservice). Creating a PDF of the page just requires calling [`createPDF(completionHandler:)`](https://developer.apple.com/documentation/webkit/wkwebview/3650490-createpdf) on the web view, but is an iOS 14 minimum.

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Marking as verified fix on v109 (25431)
