### ISSUE TITLE
Firefox Enhanced Tracking Protection

### ISSUE THREAD

**Issue by imnotabr** [mozilla-mobile/firefox-ios#9140]
Firefox's Enhanced Tracking Protection uses disconnect.me's tracking protection list https://github.com/disconnectme/disconnect-tracking-protection/blob/master/entities.json.

Where is this file located in the Firefox iOS source code?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3182)

**Comment by dnarcese** [comment]
@imnotabr we pull the data from https://github.com/mozilla-services/shavar-prod-lists
