### ISSUE TITLE
New tab open in wrong location on tab bar

### ISSUE THREAD

**Issue by abhishekk07** [mozilla-mobile/firefox-ios#9146]
## Steps to reproduce
1. Have multiple tabs open
1. Open new tab.

### Expected behavior
New tab should open at the end of the tab bar(last position)

### Actual behavior
New tab is created in (last position -1) location, after tab loads the website it moves to last position 

### Device & build information
* Device: IPad 7th Gen 
* Build version: Firefox Daylight 37.0 (5971)
    1. Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3186)

**Comment by abhishekk07** [comment]
https://user-images.githubusercontent.com/38587833/134136549-d5509c4f-91de-459e-95d7-bacdae03997e.MP4

**Comment by dnarcese** [comment]
@SimonBasca i couldn't reproduce this. Could you try to find more reliable STR?
