### ISSUE TITLE
Start at Home testing

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#9149]
We are getting a lot of user reports that the app is always opening to the homepage. Our intended functionality was that it would only open to home after 4 hours of inactivity, or on a cold start of the app.

Can we get more focused testing on this feature to discover hidden bugs?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3190)

**Comment by ShonFrazier** [comment]
This is happening again. A couple weeks ago, it was always the third tab rather than the first tab. I usually switch to the first tab before exiting. Sometimes I don’t. Regardless, ff would return to the third.

I closed lots of tabs, left three open, but now I get a new tab with the home page.

**Comment by SimonBasca** [comment]
@ShonFrazier I believe this is the intended behavior. If the option "Homepage after four hours of inactivity" is enabled, Firefox will open a new tab after 4 hours of inactivity. If a new empty tab is opened, after four hours of inactivity, at startup, Firefox will always switch to the empty homepage tab. 

There is an option to always open the last visited tab. This can be enabled from Settings -> Homepage -> Tap "Last Tab". Hope this solves your issues.

**Comment by ShonFrazier** [comment]
I put that setting on "Last Page" when this feature first arrived earlier this year. I check today and it has reverted to "homepage after four hours..."

I suppose that means I should create an issue for the reverted setting.
