### ISSUE TITLE
Safari iPad Mini sends a mobile UA string, instead of desktop UA string.

### ISSUE THREAD

**Issue by karlcow** [mozilla-mobile/firefox-ios#9150]
We need to double check this. 
Currently the Safari Tech Preview emulator for responsive design sends

1. Desktop UA for iPad
1. Mobile UA for iPad mini

```
# iPad Mini
Mozilla/5.0 (iPad; CPU iPhone OS 13_1_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.1 Mobile/15E148 Safari/604.1

# iPad
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.1 Safari/605.1.15
```

If I'm not mistaken, currently Firefox iOS sends Desktop UA for Firefox on all iPad.

Could someone with access to devices iPad Mini and iPad could confirm what safari and firefox are sending?
You may go to http://echo.opera.com/

This induces probably webcompat reports 
https://github.com/webcompat/web-bugs/issues/87535

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3192)

**Comment by karlcow** [comment]
An additional issue here. Site starts to send unsupported because the desktop UA is hardcoded instead of reflecting the version of WebKitView on the device. 

https://github.com/mozilla-mobile/firefox-ios/blob/6d141891851838f98097c9c99c1f6e6d1bce44b9/Shared/UserAgent.swift#L51-L53

This is what is happening on https://github.com/webcompat/web-bugs/issues/91501

**Comment by lmarceau** [comment]
Latest state on this ticket: On iPad mini we currently have `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1 Safari/605.1.15` User Agent, so the same as iPad.
