### ISSUE TITLE
Clicking X in address bar as page loads reloads the page

### ISSUE THREAD

**Issue by djfuzzy** [mozilla-mobile/firefox-ios#9153]
## Steps to reproduce
1. Browse to a website
2. As it loads, click the X button in the address bar.

### Expected behavior
The page reloads

### Actual behavior
The page load should stop

### Device & build information
* Device: iPhone 12
* Build version: 5971
### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3193)

**Comment by dnarcese** [comment]
duplicate of #8988
