### ISSUE TITLE
Lock icon shows as insecure after coming back to a site

### ISSUE THREAD

**Issue by topotropic** [mozilla-mobile/firefox-ios#9157]
## Steps to reproduce

1. Open Twitter.com
2. Put Firefox in the background
3. Come back to the app after a while so that the tab doesn't reload

### Expected behavior
The lock icon visualizes a secure state

### Actual behavior
The lock icon visualizes an insecure state (crossed through)

### Device & build information
* Device: 
* Build version: 37.0
### Notes
Attachments: 
<img width="438" alt="image" src="https://user-images.githubusercontent.com/353960/134415575-98649836-80f9-4b57-8a5b-114f1788ddba.png">

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3197)

**Comment by SimonBasca** [comment]
Fixed in https://github.com/mozilla-mobile/firefox-ios/pull/9349

**Comment by SimonBasca** [comment]
Verified fix on 39.0 (6442)
