### ISSUE TITLE
Attentive mode is not dismissed when taping on the home page (landscape mode)

### ISSUE THREAD

**Issue by csuciu** [mozilla-mobile/firefox-ios#9175]
v38.0 (6122)
iPhone 12 Pro (iOS 15)

1. Put the phone in landscape mode.
2. Open a new home tab.
       => The new tab opens with the address bar focused and the keyboard visible. 
3. Click on any blank space on the home page.

Expected: The address bar should be unfocused and keyboard should disappear.

Actual: Nothing happens. The address bar is still focused and keyboard still visible.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3208)

**Comment by data-sync-user** [comment]
➤ Nishant Patel commented:

Is that blank space in the area where the default browser card prompt shows?

**Comment by csuciu** [comment]
I've marked the areas on the screenshot bellow
![2021_09_27_0](https://user-images.githubusercontent.com/1866605/134912185-78002325-5f9e-43e7-a6b6-ceeff5a7cec3.png)

**Comment by nishant2718** [comment]
Have you already dismissed it once by tapping in portrait, and then turned to landscape and tried tap to dismiss?

**Comment by csuciu** [comment]
I dismissed it in portrait, then switched to landscape and opened a new home tab, then tried to dismiss the keyboard by tapping on the page.

**Comment by dnarcese** [comment]
duplicate #10134
