### ISSUE TITLE
The view is not scrolled to the selected tab in tabs tray

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#9176]
## Steps to reproduce
1. Open a few tab to enable scrolling in tabs tray
2. Select the last tab
3. Open tabs tray
### Expected behavior
- the view should be scrolled to the selected tab
### Actual behavior
- the view is at the first tab
### Device & build information
* Device: iPhone 12 Pro 
* Build version: 38.0(6122)
### Notes
Attachments: 
![052273EF-9919-485C-8DF1-F3EF3EDBE064](https://user-images.githubusercontent.com/32130829/134927480-8db904d4-1701-407e-a16f-14e3dc54b618.jpeg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3209)

**Comment by athomasmoz** [comment]
@SimonBasca thanks for logging. Is this a regression in v38?

**Comment by csuciu** [comment]
@athomasmoz Yes, this is a regression that was introduced between v37.0 (5971) and v38.0 (6036) TF builds.

**Comment by SimonBasca** [comment]
Verified fix on v 38.0 (6157).
