### ISSUE TITLE
Don't enter attentive mode when tapping the home button

### ISSUE THREAD

**Issue by Verdi** [mozilla-mobile/firefox-ios#9183]
### User Problem
> If I tap the home button in order to use the new home page features I am partially blocked by attentive mode. Since I can easily tap the address bar if I want to search, I'd like to use the new home page features without attentive mode getting in the way.

### Ideas for Solution
> Don't use attentive mode when tapping the home button. This will also align the home button behavior with Fenix.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3214)

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verifying as fix on main 440f1aee29106b7
