### ISSUE TITLE
iOS15: Crash when tapping undo after closing all regular tabs and hitting the tab tray button

### ISSUE THREAD

**Issue by nishant2718** [mozilla-mobile/firefox-ios#9184]
## Steps to reproduce
1. Have a few tabs open (non-private)
2. Tap the trash icon and close all tabs
3. Tap undo on the toast. 
4. Hit the tab tray button.
5. Observe the crash
### Expected behavior
Should open tab tray. 
### Actual behavior
Crash.
### Device & build information
* Device: 12 mini, iOS 15.0
* Build version: v37, 5971.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3215)

**Comment by csuciu** [comment]
Following this steps, I can reproduce reliably this crash on v38.0 (6122) on iOS 15. 
This crash also occurs if, after step #3, instead of hitting the tabs tray button you tap on the address bar and start typing  something.
