### ISSUE TITLE
New page every time app opens

### ISSUE THREAD

**Issue by csuciu** [mozilla-mobile/firefox-ios#9186]
Cloned from https://bugzilla.mozilla.org/show_bug.cgi?id=1731577

Steps to reproduce:

I opened Firefox IOS

Actual results:

A new (and additional window) was opened

Expected results:

I don't want an additional new window. If this is behaviour by design, I want an option for Firefox IOS to open the last page I was on. Otherwise I just get multiple windows, which I keep having to close. It's irritating.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3216)

**Comment by hardascii** [comment]
Here is an example of the behavior.

https://user-images.githubusercontent.com/55703003/135722879-55d2d22a-ad53-43a4-a3d8-85cc56b0a309.mp4
