### ISSUE TITLE
Crash when trying to re-arrange tabs 

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#9193]
## Steps to reproduce
1. Open a few tabs ( 10 tabs or more)
2. Long press on a tab from the top of the list
3. Drag it to the bottom of the list 
4. Drop the tab at the bottom 
### Expected behavior
- dragging and dropping the tab should be possible without crashing the app.
### Actual behavior
- the app crashes 
### Device & build information
* Device: iPhone 12 (14.8)
* Build version: 38.0 (6122)
### Notes
Attachments: 

https://user-images.githubusercontent.com/32130829/135082134-9805c7f0-ad76-426e-b551-a9181236014b.MOV

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3220)

**Comment by csuciu** [comment]
[Client-2021-09-28-143248.ips.beta.zip](https://github.com/mozilla-mobile/firefox-ios/files/7243807/Client-2021-09-28-143248.ips.beta.zip)

**Comment by data-sync-user** [comment]
➤ Nishant Bhasin commented:

Fixed: https://github.com/mozilla-mobile/firefox-ios/pull/9189 ( https://github.com/mozilla-mobile/firefox-ios/pull/9189|smart-link )
