### ISSUE TITLE
Support SPM as a dependency manager

### ISSUE THREAD

**Issue by muhasturk** [mozilla-mobile/firefox-ios#9194]
Do you plan to support / move Swift Package Manager as a dependency manager?

## Supported Deps
["getsentry/sentry-cocoa"](https://docs.sentry.io/platforms/apple/guides/ios/install/swift-package-manager/)
["SnapKit/SnapKit"](https://github.com/SnapKit/SnapKit#swift-package-manager)
["SDWebImage/SDWebImage"](https://github.com/SDWebImage/SDWebImage/wiki/Installation-Guide#installation-with-swift-package-manager-xcode-11)
["kif-framework/KIF"](https://github.com/kif-framework/KIF/blob/master/Package.swift)
["jrendel/SwiftKeychainWrapper"](https://github.com/jrendel/SwiftKeychainWrapper#swift-package-manager)
["DaveWoodCom/XCGLogger"](https://github.com/DaveWoodCom/XCGLogger#swift-package-manager)
["cezheng/Fuzi"](https://github.com/cezheng/Fuzi/blob/master/Package.swift)
["SwiftyJSON/SwiftyJSON"](https://github.com/SwiftyJSON/SwiftyJSON#swift-package-manager)

### Not Supported
"swisspol/GCDWebServer"

### Mozilla
"mozilla-mobile/onepassword-app-extension"
"mozilla-mobile/telemetry-ios"
"mozilla-mobile/MappaMundi"
"mozilla-services/shavar-prod-lists"

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3221)

**Comment by lmarceau** [comment]
Closing this since we have a ticket for it :) https://github.com/mozilla-mobile/firefox-ios/issues/9859
PR is linked in that ticket. Will be merged this week.
