### ISSUE TITLE
Wrong number of Top Sites rows after switching orientation

### ISSUE THREAD

**Issue by csuciu** [mozilla-mobile/firefox-ios#9196]
v38 (6122)
iPhone 12 Pro (15)
iPhone 6S (13.7)

Prerequisites:
*Make sure Top Sites are set to be displayed on 2 rows.
*Close all tabs and restart the app.

1. While in Home tab switch to landscape mode.
2. Tap on one of the top sites to open it.
3. Tap on "+" to open a new  Home tab.
4. Observe the number of Top Sites rows.
5. Switch back to portrait.
6. Observe the number of Top Sites rows.

Expected: After step 4, Top sites should be displayed on 1 row. After step 6, Top Sites should be on 2 rows.

Actual: After step 4, Top sites are displayed on 2 rows. After step 6, Top Sites are displayed on 4 rows.

Sometimes this issue reproduces much easier just by switching between portrait to landscape and back.

https://user-images.githubusercontent.com/1866605/135098974-0370672c-ecc5-4df9-b034-b36add466966.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3222)

**Comment by lmarceau** [comment]
@csuciu This should be fixed as well now

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verified fix on main 42bb8dc61447541b984f21b33c8ae72e996899ea
