### ISSUE TITLE
Opening a new tab in the tabs tray visually shows it 2nd to last position

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#9204]
Steps to reproduce:
1. Open up a few tabs
2. Close a tab from the tabs tray view
3. Open a tab from the tabs tray view (v1)
4. Return to the tabs tray (v2)

Expected behaviour:
v1: tab appears in the last position in the tabs tray
v2: tab is in the last position in the tabs tray

Actual behaviour:
v1: tab appears in the **2nd to last** position in the tabs tray
v2: tab is in the last position in the tabs tray

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3225)

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verified fix on 94bcc52a1c and 95 (6631).

**Comment by lmarceau** [comment]
I'll reopen this since I notice if you have only one tab in the tab tray, and click + to open a second tab, then the tab is still added at the 2nd to last position :(

https://user-images.githubusercontent.com/11338480/142446422-77aa4b6a-fae4-434d-bfe0-0915c21a1e9b.mp4

**Comment by SimonBasca** [comment]
Thanks for the fix @lmarceau. We can mark this as verified fix on main ebf342fcc for also the case covered in https://github.com/mozilla-mobile/firefox-ios/issues/9204#issuecomment-972979579

**Comment by SimonBasca** [comment]
Verified fix on v40 (6861)
