### ISSUE TITLE
[iPad] The focus is not dismissed on the url bar when pressing the “hide keyboard” button on the virtual keyboard on iPad

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#9210]
## Steps to reproduce
1. Open a new tab
1. Tap the “hide keyboard” button on the virtual keyboard on iPad
### Expected behavior

* The focus on the url bar should be dismissed
### Actual behavior
* When pressing the “hide keyboard” button on the virtual keyboard on iPad, the focus is not dismissed on the url bar.
### Device & build information
* Device: iPad Pro 14.6
* Build version: 38.0 (6157)
### Notes
Attachments: 
![A2FF2288-41F0-4969-90C9-8AFD1D664349](https://user-images.githubusercontent.com/32130829/135236031-061a4fe1-23fa-47c5-817e-7de812c799f7.jpeg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3227)

**Comment by struq** [comment]
This has not been fixed, still requires attention. v109.0 (25841)
