### ISSUE TITLE
Only start on home after 4+ hours of inactivity

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#9222]
**Background**

Initial requirement was to start on new tab on cold start or 4+ hours of inactivity. When the change to start on new tab on cold start was released, we saw concerns from users that suggested this was happening more often than intended. This may be in part because the system can at any point run low on memory or battery and decide to close the app, so then when you switch back to the app, you'd ideally see the last tab, but you see new tab instead.

**Acceptance Criteria**

* By default, 
  * App starts on new tab after 4+ hours of inactivity
  * App starts at last spot if opened after <4 hours of inactivity
* If a user changes the setting to always or never start on new tab, that is respected

**Notes**

Current behaviour is that app starts always starts on last location

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3234)

**Comment by ShonFrazier** [comment]
I am not a fan of this behavior. I don't like that this behavior suddenly arrived in an update as a new default.

> If a user changes the setting...

Does this setting exist, or does it need to be added.

**Comment by athomasmoz** [comment]
Thank you for the feedback. Yes, this ticket goes along with a setting that is currently being built out with options for when to start on home.

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Marking as verified fix on v40.0 (6861)

**Comment by ShonFrazier** [comment]
I'm experiencing the "new tab showing the start page" functionality on 40.1 (7037) and would rather not. I don't have any data for blaming the time logic. I can't find the setting (has it deployed?) to disable this feature.

**Comment by electricRGB** [comment]
Heya @ShonFrazier. The setting can be found in Settings > Homepage > Opening Screen. Set that to "Last Tab" and you'll be on your last tab when you open FX

**Comment by nook24** [comment]
I really don’t know why this has to be enabled by default. Took me some time to find the solution to disable this
https://github.com/mozilla-mobile/firefox-ios/issues/9222#issuecomment-998044246

sorry for the spam
