### ISSUE TITLE
Additional Search Enginers/Providers not available

### ISSUE THREAD

**Issue by sneakernuts** [mozilla-mobile/firefox-ios#9227]
## Steps to reproduce

1. Setup multiple search providers
2. Open a new tab
3. Start typing search term in address bar

### Expected behavior
1. Ability to pick which search provider to use

### Actual behavior
1. The only search provider available is the default one
2. Unable to select additional search providers (usually appears on top of iOS keyboard)

### Device & build information
* Device: iPhone 8, on iOS 15
* Build version: Firefox Daylight 38.0 (6157)
### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3237)

**Comment by nishant2718** [comment]
Addressed with https://github.com/mozilla-mobile/firefox-ios/pull/9236!
