### ISSUE TITLE
Crash on Opening Firefox

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/firefox-ios#9232]
## Steps to reproduce
I opened Firefox but did not open any page. Swiped up to Home Screen. After some time, opened Firefox again. It crashed.

### Expected behavior
Firefox should not crash

### Actual behavior
Crashed with "This was embarrassing. Do you want to restore previous session?"

### Device & build information
* Device: iPhone 12
* Build version: 38.0 (6157)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3239)

**Comment by c-thun** [comment]
Crash Logs
[Client-2021-09-30-124241.zip](https://github.com/mozilla-mobile/firefox-ios/files/7262402/Client-2021-09-30-124241.zip)

**Comment by nishant2718** [comment]
This would be an example of a deadlock runLoop crash.
