### ISSUE TITLE
Disable start at home for v38.1

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#9237]
The 4hr inactivity counter doesn't currently work and Firefox iOS always starts on home at cold start. 

In this ticket for v38.1 we'll go back to same tab where we were when user started Firefox iOS from cold start. 

Improvement ticket for v39.0 Only start on home after 4+ hours of inactivity

https://mozilla-hub.atlassian.net/browse/FXIOS-3234 - #9222

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3242)

**Comment by SimonBasca** [comment]
Verified fix on v38.1. (6216)
