### ISSUE TITLE
Password and last modified rows separators are shown and delete item row separator is not full width on initial saved login detail load

### ISSUE THREAD

**Issue by michaelbiv** [mozilla-mobile/firefox-ios#9240]
## Steps to reproduce
1. Tap the menu button
2. Tap Passwords
3. Tap a saved login
4. Swipe down to view control center or background Firefox
5. Dismiss control center or foreground Firefox

### Expected behavior
- Password and last modified row separators should be hidden on initial load (as is when returning from background)
- Delete item row separator should be full width on initial load (as is when returning from background)

### Actual behavior
- Password and last modified row separators are visible on initial load, but hidden when Firefox returns to foreground
- Delete item row separator is not full width on initial load, but is full width when Firefox returns to foreground

### Device & build information
* Device: iPhone 12 Pro Max
* Simulators: iPhone 13 Pro, iPhone 13 Pro Max
* Build version: [85d8ceb](https://github.com/mozilla-mobile/firefox-ios/commit/85d8ceb33321b0697157357706eecbd4f66812fa)

### Notes
Attachments: 
Steps to reproduce:
![steps](https://user-images.githubusercontent.com/829610/135766638-5e365b03-01cd-444b-a760-4290a302b8fe.gif)

Initial load:
![initial-load](https://user-images.githubusercontent.com/829610/135766647-d56427e7-41e0-4be8-a9fa-0d22df828ccf.png)

Restore from background:
![restored-from-background](https://user-images.githubusercontent.com/829610/135766653-082b6cb5-c0ca-48aa-8ebd-80acd2b21e84.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3244)

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verifying as fix on main da7a6a4d1ed3630f60e307a623f3d8956e6184c3
