### ISSUE TITLE
Text in 'Switch Your Default Browser' pop-up is not visible in Night Mode

### ISSUE THREAD

**Issue by mMARUF** [mozilla-mobile/firefox-ios#9252]
### Steps to reproduce

1) Open Firefox beta in iPhone using TestFlight
2) We see a pop-up “switch your default browser”
3) Click on ‘Learn More’
4) A pop-up will open where we see some text
5) Close the pop up
5) Now, from the bottom menu select the 'Turn On Night Mode' option
6) Again, click on ‘Learn More’  of  “switch your default browser” pop up

### Expected behaviour

Text in the pop-up is should be visible on the Night mode.

### Actual behaviour

We see that the the text in the pop-up is not visible when we are on the Night mode. But, when we switch off the Night Mode, the text of the pop-up is visible

### Device name

iPhone SE 2020

### IOS version

15.0.1

### Firefox release type

Firefox Beta

### Firefox version

Mozilla/5.0 (iPhone; CPU iPhone OS 15_0_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) FxiOS/38.1  Mobile/15E148 Safari/605.1.15

### Window Size
375X601

### Screenshot

![Text in 'Switch Your Default Browser' pop-up is not visible in Night Mode](https://user-images.githubusercontent.com/45368054/136074694-63d38081-0a44-4dd1-8c21-5cd737e3f563.gif)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3252)
┆Link To Issue: https://mozilla-hub.atlassian.net/browse/FXIOS-3252

**Comment by lmarceau** [comment]
@SimonBasca I think this can be closed?

**Comment by SimonBasca** [comment]
This issue is no longer reproducible on latest main v9000 (21404)
