### ISSUE TITLE
Menu fading animation does not look good while switching themes from menu  

### ISSUE THREAD

**Issue by mMARUF** [mozilla-mobile/firefox-ios#9255]
### Steps to reproduce

1) Open Firefox beta in iPhone using TestFlight
2) Visit google..com
3) Switch between Night mode and light mode from the menu
5) We will see a menu disappearing animation after switching between themes 

### Expected behaviour

The menu disappearing animation does not look good as it fades slowly. After switching between themes the menu should disappear immediately 

### Actual behaviour

The menu disappearing animation after slowly fades. 

### Device name

iPhone SE 2020

### IOS version

15.0.1

### Firefox release type

Firefox Beta

### Firefox version

Mozilla/5.0 (iPhone; CPU iPhone OS 15_0_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) FxiOS/38.1  Mobile/15E148 Safari/605.1.15

### Window Size
375X601

### Screenshot

![ezgif com-gif-maker](https://user-images.githubusercontent.com/45368054/136085032-5dbcc8e1-eda3-4f29-a6d9-becf6db52ee4.gif)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3255)

**Comment by data-sync-user** [comment]
➤ Daniela Arcese commented:

Test if this is fixed in 109

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

This issue is still reproducible on 109 (25431).
