### ISSUE TITLE
Canvas game is unresponsive on an iPad

### ISSUE THREAD

**Issue by ksy36** [mozilla-mobile/firefox-ios#9262]
## Steps to reproduce
Visit https://www.timestables.com/my-smart-horse.html?play in Firefox Daylight 38.1 (6216) and press "Next".

### Expected behavior
Game starts

### Actual behavior
Game doesn't start, pressing on other buttons has no effect

### Device & build information
* Device: iPad Pro
* Build version: Firefox Daylight 38.1 (6216)

### Notes

The issue is not reproducible in Safari or Chrome on iPad. 
This was originally reported in https://github.com/webcompat/web-bugs/issues/88954
It's possible to start the game by requesting mobile site through the three dots menu, however audio doesn't seem to play.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3259)

**Comment by lmarceau** [comment]
@ksy36 This seems fine on latest App Store version v101 and on latest main https://github.com/mozilla-mobile/firefox-ios/commit/7bf455c419d93d73e76fa1cf268c8c67eca743e6.

https://user-images.githubusercontent.com/11338480/173403183-ca41e65b-3138-44db-a0fa-73d2e94f062f.mp4

**Comment by csuciu** [comment]
No longer reproducible on latest main. Closing.
