### ISSUE TITLE
Keyboard shortcut to undo closed tab not working on iPadOS

### ISSUE THREAD

**Issue by tech189** [mozilla-mobile/firefox-ios#9266]
## Steps to reproduce
- Attach a keyboard such as the Magic Keyboard to an iPad
- Close a tab (either with cmd-w or by tapping the X)
- Try to re-open the closed tab with cmd-shift-t (as is listed on [this help page](https://support.mozilla.org/en-US/kb/keyboard-shortcuts-firefox-ios))

### Expected behavior
The closed tab re-opens.

### Actual behavior
Nothing happens.

### Device & build information
* Device: iPad Pro 11-inch, iOS 15.0.1
* Build version: Firefox Daylight 38.1 (6216)

### Notes
The shortcut is also not listed when you hold down the cmd key.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3261)

**Comment by lmarceau** [comment]
Hi @tech189,
It seems the [help page](https://support.mozilla.org/en-US/kb/keyboard-shortcuts-firefox-ios) isn't reflecting what we have in the app and will have to be updated. Undoing a tab isn't currently an implemented shortcut, but I believe it's a great idea. Also, Cmd+Shift+t is the same shortcut has in desktop.  

@dnarcese What do you think?

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verified fix on main 627116c214d9d74bb5a391f59999cd4eb1f68eee. Pressing cmd-shift-t will open the last closed tab.
