### ISSUE TITLE
[iPad] Pressing the refresh button in the multitasking view closes the current web page

### ISSUE THREAD

**Issue by brangpd** [mozilla-mobile/firefox-ios#9282]
## Steps to reproduce

1. Start firefox in the multitasking view (Slide Over or Split View).
2. Go to any web page. Now a refresh button appears on the bottom.
3. Press the refresh button on the bottom

### Expected behavior

- Refresh the web page.

### Actual behavior

- The current web page is closed, and the search bar is automatically activated.

### Device & build information
* Device: iPad Air 3 14.8
* Build version: Firefox Daylight 38.1 (6216)
### Notes
Attachments:

https://user-images.githubusercontent.com/40844407/136643068-7680679c-e0eb-46d9-8b63-87d99bd59183.MP4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3264)

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verifying as fix on main c6d17c95da56477529f3bc3a1bd0dbf50d2717a5
