### ISSUE TITLE
Bottom toolbar icon size shrinks

### ISSUE THREAD

**Issue by kcome** [mozilla-mobile/firefox-ios#9288]
## Steps to reproduce
Open Firefox 
Put app in background for awhile (not sure how long), maybe 2-3hrs
Re-open the app

### Expected behavior
Bottom Toolbar shows correct status
### Actual behavior
Some buttons are shrunk in size

### Device & build information
* Device: iPhone11 iOS 15.0.2
* Build version: v38.1
### Notes
Attachments: 
![image](https://user-images.githubusercontent.com/283495/136895099-c6dce597-ad6b-40da-a390-e91d6f93a034.png)
![image](https://user-images.githubusercontent.com/283495/136895121-adb82c3f-8476-46c8-8e07-a9cb2b0529de.png)
![image](https://user-images.githubusercontent.com/283495/136895149-e0dbbafb-a0c0-4e9a-b8e9-c38af0009215.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3270)

**Comment by kcome** [comment]
This might be iOS glitch. Putting Firefox in background and re-open it will solve the issue.

I just report this in case anyone saw the same so maybe it could be reproduced or fixed.

**Comment by SimonBasca** [comment]
I've manage to easily reproduce the issue on main 4f7d48515b.
1. Launch the app 
2. Enable Pocket, Recently saved or Jump in sections on homepage to enable scrolling
3. Scroll the homepage
4. Background the app
5. Foreground the app


https://user-images.githubusercontent.com/32130829/141785422-8221937d-1188-4269-b767-ab996b0b3eda.mp4

**Comment by isabelrios** [comment]
This is also reproducible 100% when opening a site on Firefox from Focus-iOS

**Comment by lmarceau** [comment]
Reproduced as well by following those steps on simulator:

1. Open a webpage
2. Kill the app
3. Reopen the app
4. Toolbar is shrinked

Going to the home page resets the toolbar.

https://user-images.githubusercontent.com/11338480/142076985-87a492ea-bd39-48be-a7ad-8a07d452e193.mov

**Comment by isabelrios** [comment]
@dnarcese I would say to change the priority to P1 as this is now very easy to reproduce and people are reporting it.

**Comment by bli-mozbj** [comment]
I can still reproduce this issue on Firefox Beta 9000(6773).

**Comment by SimonBasca** [comment]
Also still reproducing the issue on latest main 7f7cac288086. @lmarceau could you please take a look?

**Comment by lmarceau** [comment]
Thanks @SimonBasca @bli-mozbj, I'll look into into. Note to self: simulator doesn't equal real device 🤦‍♀️

**Comment by SimonBasca** [comment]
Marking as verified fix on main ebf342fcc
