### ISSUE TITLE
Private browsing theme is displayed in Normal Browsing

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#9290]
## Preconditions:
Have 3 tabs opened in Normal Browsing: "digi.ro", "beatport.com", "google.com"
Have 1 tab opened in Private Browsing : "amazon.com"
## Steps to reproduce
1. In normal browsing, open tabs tray
2. Close all tabs via trash can (close all tabs) button
3. Tap "Undo" to restore tabs
4. Open Tabs Tray
5. Tap the "Private Browsing" button
6. Close all tabs via trash can (close all tabs) button
7. Swipe down to dismiss tabs tray
### Actual behavior
- Private browsing theme is displayed in Normal Browsing
### Device & build information
* Device: iPhone 12 (15.0)
* Build version: main  ffbab36a08044c73cf
### Notes
- Possible regression from https://github.com/mozilla-mobile/firefox-ios/issues/8818
Attachments:
[video.mp4.zip](https://github.com/mozilla-mobile/firefox-ios/files/7329975/video.mp4.zip)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3272)

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verifying as fix on main 228b77b9a89f133417cb748fcf720fb01e6b6f1a

**Comment by SimonBasca** [comment]
Verifying as fix on v98.0 (8023).
