### ISSUE TITLE
[Jump In]The big hero image is cropped on Google

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#9317]
## Steps to reproduce
1. Enable "Jump In"
1. Go to google.com
1. Open a new tab
    1. Expected behavior

* The big hero image should fit the placeholder.
    1. Actual behavior
* The big hero image is cropped.
    1. Device & build information
* Device: iPhone 12 Pro
* Build version: main 87fb882cbd7172
    1. Notes
Attachments:
![Sreenshot](https://user-images.githubusercontent.com/32130829/137489150-e1e2c79f-8d78-4328-958d-4adaee014f39.jpeg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3288)

**Comment by muhasturk** [comment]
https://github.com/mozilla-mobile/firefox-ios/issues/9317 fixes.
