### ISSUE TITLE
"Customize Homepage" button should have dark theme color.

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#9352]
## Steps to reproduce
1. Clean install Firefox
2. Change to dark theme
3. Open a new tab
4. Check "Customize Homepage"
### Expected behavior
- "Customize Homepage" should have dark theme color.
### Device & build information
* Device: iPhone 12 Pro (15.0)
* Build version: 39.0 (6367)
### Notes
Attachments:
![Screenshot](https://user-images.githubusercontent.com/32130829/137896560-a28e93b3-69b5-4726-9eff-6dd1bee45ee3.jpeg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3319)

**Comment by electricRGB** [comment]
@topotropic Can you provide a link to a dark mode design? There was no dark mode included in the original[ design link](https://www.figma.com/file/am9EJGg6ow29PXWkc9jcOH/MR2?node-id=2155%3A35451).
