### ISSUE TITLE
Firefox share extension top toolbar is transparent

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#9361]
## Steps to reproduce
1. Long press on a top site shortcut
2. Tap "Share"
3. Select the "Firefox" extension
### Expected behavior
- Top toolbar is transparent
### Device & build information
* Device: iPhone 12 Pro (15.0.2)
* Build version: 39.0 (6428)
### Notes
Attachments:
![screenshot](https://user-images.githubusercontent.com/32130829/137954758-818e8b5d-57ca-4cd5-a3e9-adc11391cf59.jpeg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3325)

**Comment by lmarceau** [comment]
Note: This can only be tested on iPhone at the moment due to the bug #9806

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verified fix on iPhone 12 Pro (15.2) on main 6d2f1b4cbe546aacc398436223f19d7592295c5c
