### ISSUE TITLE
Account image is displayed instead of Block image icon.

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#9366]
## Preconditions:
- Log in to FxA
- Have an image set in account management page.
## Steps to reproduce
1. Close Firefox from app switcher if it was previously opened
2. Launch Firefox (6442)
3. Open the hamburger menu
### Expected behavior
- Block image icon should be displayed next to the "Block image text"
### Actual behavior
- Account image is displayed instead
### Device & build information
* Device: iPhone 12 Pro (15.0.2)
* Build version: 39.0 (6442)
### Notes
Attachments: 

https://user-images.githubusercontent.com/32130829/138056676-a8e27203-1833-441a-8f82-c7e6ab2f3d26.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3327)

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verified fix on main a6296227978396824b8094c63980a039db4c8af2

**Comment by SimonBasca** [comment]
Verified fix on v98.0 (8023).
