### ISSUE TITLE
[Experiment] The CFR message is anchored to the wrong sections after the Jump Back in section is displayed

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla-mobile/firefox-ios#9367]
## Preconditions
- Have the **Firefox Beta 39 (6442)** installed through TestFlight.
- Have the Firefox Browser not set as default.

## Steps to reproduce
1. Start the Firefox App and open the Settings menu.
2. Scroll down the page and tap the Firefox Daylight 39.0 string 5 times.
3. Scroll down the page and tap the Experiments option.
4. Tap the Edit button and toggle the `Use Preview Collection` option.
5. Fully close and reopen the app.
6. Navigate back to the Experiments menu and tap the Edit button.
7. Tap the Reset button and tap the back button.
8. Tap the `All Users HomeScreen iOS` entry and tap the `control` branch.
9. Fully close and reopen the app.
10. Navigate to a website and open a New Tab.
11. Observe the homepage.

### Expected behavior
- The keyboard is dismissed and the homepage CFR message is anchored to the `Jump Back in` section.

### Actual behavior
- The keyboard is NOT dismissed and the homepage CFR message is anchored to the `Shortcuts` section.

### Device & build information
* Device: iPhone 11 - iOS 14.7.1
* Build version: Firefox Beta 39 (6442)

### Notes
- The issue is also reproducible when the `Switch Your Default Browser` message is dismissed. And in this case the CFR message is displayed OVER the `Jump Back in` section.
- Any attempt to dismiss the keyboard dismisses the CFR message.
- The issue is NOT reproducible when using a Simulator.
- The issue is not reproducible with local v39.0 builds on a physical device.

Attachments: 
- `Switch Your Default Browser` displayed
![IMG_0026](https://user-images.githubusercontent.com/18304511/138066830-8000d52e-0511-486d-b08e-a51edcbc809f.PNG)

- `Switch Your Default Browser` not displayed
![IMG_0025](https://user-images.githubusercontent.com/18304511/138066805-86e59bfd-16a9-43de-84d1-6276e7b4fceb.PNG)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3328)

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verified fix on 9000 (6773)
