### ISSUE TITLE
[Experiment] The hompage cannot be scrolled and most elements are unusable if tabs are opened prior to experiment enrollment

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla-mobile/firefox-ios#9371]
## Preconditions
* Have the **Firefox Beta 39 (6442)** installed through TestFlight.

## Steps to reproduce
1. Install Firefox Beta from TestFlight.
1. Start Firefox. (1st time)
1. Dismiss the Onboarding slide.
1. Tap a Top Site (Shortcut) eg twitter.
1. Open a New Tab.
1. Open the Settings menu.
1. Enable Secret Menu (tap the Firefox Daylight 39.0 line 5 times).
1. Tap Experiments then tap Edit.
1. Toggle `Use Preview Collection` and tap Reset.
1. Fully close Firefox.
1. Start Firefox. (2nd time)
1. Open the Settings menu.
1. Enable Secret Menu.
1. Tap Experiments then tap Edit.
1. Tap the Reset button then go back to the previous page.
1. If enrolled in the `All Users HomeScreen iOS` experiment or the `treatment` branch of the `Home Screen Impact Assessment Experiment`, you're good to go. If enrolled in `control` branch of the `Home Screen Impact Assessment Experiment`, tap it and switch to the treatment branch.
1. Fully close Firefox.
1. Start Firefox. (3rd time)
1. Dismiss the `Switch Your Default Browser` message.
1. Dismiss the keyboard and scroll through the page or tap one of the Shortcuts.

### Expected behavior
* The CFR message is anchored to the `Jump Back in` section.
* The homepage is successfully scrolled and links can be open.

### Actual behavior
* The CFR message is not displayed anywhere in the page.
* The homepage does not react to scroll gestures and taps on links are not registered.

### Device & build information
* Device: iPhone 11 - iOS 14.7.1
* Device: iPhone 6s - iOS 15.0.2
* Build version: Firefox Beta 39 (6442)

### Notes
* The keyboard works as expected and you can write strings or dismiss it..
* The issue is NOT reproducible when using a Simulator. When using a simulator the CFR message is displayed bun only after a second and the page can be successfully scrolled after that.
* The issue is not reproducible with accessibility gestures.
* The issue is not reproducible with local v39.0 builds on a physical device.

Attachments: 

* When the screen recording seems to be stuck, that's me trying to scroll or tap on things in the page. [Link to screen recording](https://drive.google.com/file/d/1w--I3vLiHqD-_qr6bl3-s6UTuncShe3d/view?usp=sharing).
* Adding an additional screen recording with accessibility gestures. [Link to screen recording](https://drive.google.com/file/d/1w3zvTzFkBeQdLMxRf3r_jPbC9ojbKYdk/view?usp=sharing).

Link to [JIRA issue](https://mozilla-hub.atlassian.net/browse/FXIOS-3332).

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3332)

**Comment by athomasmoz** [comment]
@SoftVision-CiprianMuresan I'm unable to reproduce. I can see the CFR message and can scroll the homepage. Is this bug consistent for you or happening intermittently?

**Comment by athomasmoz** [comment]
I am on iOS 15.0.2, so maybe that makes a difference

**Comment by SoftVision-CiprianMuresan** [comment]
> 
> 
> @SoftVision-CiprianMuresan I'm unable to reproduce. I can see the CFR message and can scroll the homepage. Is this bug consistent for you or happening intermittently?

I'm able to reliably reproduce this on my device and I have successfully reproduced this on an iPhone 6s, iOS 15.0.2 as well.
That being said, it looks like I've missed a pretty important step. The issue is reproducible only on the 3rd start up of the app when the `Set to Default` message is also displayed.

I've updated the STR to be more verbose and everyone should have an easier time to repro.

Given the extra step that I haven't noticed until someone else tried to repro, it looks like this is easier to reproduce while the experiments are in the Nimbus Preview collection, as this implies an additional restart for the experiment to be enabled.

The risk of this issue should be considerably less now, given the need for 3 very specific start-ups. But it could still happen in the wild given our feature to [show the homepage after 4 hours of inactivity](https://mozilla-hub.atlassian.net/browse/FXIOS-1739).

**Comment by nbhasin2** [comment]
The only way I was able to reproduce this bug is by setting the following in 3rd steps where we have 4 PROD experiments being shown in BETA for some reason. That should not happen. 

![image](https://user-images.githubusercontent.com/8919439/138359502-6591a1e0-5a4a-410b-8455-b2eafa04d440.png)
![image](https://user-images.githubusercontent.com/8919439/138359507-367a61d1-85cc-4197-b310-ac708d861655.png)
![image](https://user-images.githubusercontent.com/8919439/138359566-bbc5d396-1755-4324-9041-192d0f8131cb.png)
![image](https://user-images.githubusercontent.com/8919439/138359519-0b8eb27b-211b-4f5e-aea8-56de5c69fb66.png)

**Comment by nbhasin2** [comment]
Good part is I was able to reproduce this issue. 
The part which isn't right is we have PROD experiments being shown in the following page for BETA build. 

<table> 
  <tr>
      <td><img src="https://user-images.githubusercontent.com/8919439/138359757-d22605de-8043-43b4-a56e-823ca5867fe0.png" alt="3" width = 450px></td>
  </tr>
