### ISSUE TITLE
Import all locales for FxiOS releases

### ISSUE THREAD

**Issue by Delphine** [mozilla-mobile/firefox-ios#9379]
As for Focus iOS, we are going to want to start importing all locales no matter their l10n completion, once they start working on Pontoon.
@st3fan : We used to edit [shipping_locales.txt](https://github.com/mozilla-mobile/firefox-ios/blob/main/shipping_locales.txt) for this (I don't know though if anything else needed to be done on iOS side). Will the process be different from now on, as I believe it now is for Focus for iOS?

CC @electricRGB and @nishant2718

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3339)

**Comment by Delphine** [comment]
@dnarcese @jevans-mozilla I remember this being aimed for v40 release.
Any updates on when this can start being done? thanks

**Comment by dnarcese** [comment]
@Delphine we didn't get to it for v40, planning for next release 1/11.

**Comment by Delphine** [comment]
Ok thanks for the heads-up. Just want to emphasize that in the meantime localizers are working actively on these locales, so great news that it will get into next release.

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Daniela Arcese Just to clarify this should be tested on v41.0?

**Comment by data-sync-user** [comment]
➤ Nishant Patel commented:

Simion Basca This has just been fixed and is ready to review on main.
