### ISSUE TITLE
Inactive tabs/recently closed menus are not shown correctly

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/firefox-ios#9391]
iPone 12, iOS 15 beta: 39 (6442)

## Steps to reproduce
I have had the beta updated several times from TF, with open tabs between the updates. Regular use of the app

### Expected behavior
The menu is shown fine, with their icons and without overlap

### Actual behavior
Please see the screenshot attached

![IMG_ECC95A52BAB9-1](https://user-images.githubusercontent.com/1897507/138325386-e5a634e3-d67f-4da1-93ec-31f9acf102b7.jpeg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3346)

**Comment by dnarcese** [comment]
Closing as this is an old design
