### ISSUE TITLE
iOS status bar and the divider lines are barely visible in the Settings screen when using Light mode

### ISSUE THREAD

**Issue by csuciu** [mozilla-mobile/firefox-ios#9397]
v39.0 (6467)
iPhone 12 Pro (15.0.2)

1.  Go to iOS Settings => Theme and switch to Light mode.
1. Observe the iOS status bar and the divider lines.

Result: The status bar and the divider lines are barely visible

![Skype!UNITO-UNDERSCORE!Picture!UNITO-UNDERSCORE!2021!UNITO-UNDERSCORE!10!UNITO-UNDERSCORE!22T06!UNITO-UNDERSCORE!48!UNITO-UNDERSCORE!13!UNITO-UNDERSCORE!998Z](https://user-images.githubusercontent.com/1866605/138406453-0a874e75-2665-4225-a755-ed9b8b6c848c.jpeg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3351)

**Comment by dnarcese** [comment]
@csuciu is this still reproducible after #9382
