### ISSUE TITLE
Removing SnapKit Pt3

### ISSUE THREAD

**Issue by nishant2718** [mozilla-mobile/firefox-ios#9410]
### Tech Debt
Continuing our journey of removing SnapKit, here's another list of possibly low effort/low impact files to hit:
- BottomSheetViewController.swift
- SensitiveViewController.swift
- QRCodeViewController.swift
- ReaderModeBarView.swift
- LibraryShortcutView.swift
- LoginListTableViewCell.swift
- LoginDetailViewController.swift
- NoLoginsView.swift
- CredentialListViewController.swift

### Ideas for Solution
Replace these with Layout Anchors. 

### Note
For whoever takes this on, feel free to split this ticket into two PRs (~4-5 files per PR).

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3360)

**Comment by muhasturk** [comment]
What is our motivation to removing SnapKit?

**Comment by nishant2718** [comment]
@muhasturk In general, the less 3rd party dependencies we have, the better. We'll have more control with native solutions. And we can avoid breaking updates when new versions are released.

**Comment by OneUpWallStreet** [comment]
@nishant2718 will it be ok if I make a PR removing SnapKit from a single file? Also, are we allowed to make any changes to any part of the codebase like for e.g. the settings view?

**Comment by nishant2718** [comment]
hey @OneUpWallStreet ! One file per PR is also okay. I'd prefer at least 3 files changed per PR for snapKit related items, but if you'd like to do on file just to see what the contribution process is like, that's fine! 

As for your second question, yes absolutely! Usually, contributions address a github issue. But there's other types of contributions made, like addressing warnings/deprecations or general code cleanup. 

Feel free to contribute in any way! And one of us will get to your PR shortly after :)

**Comment by data-sync-user** [comment]
➤ Laurie Marceau commented:

For QA, the Logins & Password view can be checked so there’s no regression

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Moving this issue to verified fix on v9000 (87435). Checked on iPad Pro(15.3)p and iPhone 12 Pro (15.4). The login screen is displayed and has correct functionality.
