### ISSUE TITLE
Move search bar to bottom

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#9422]
As a user, I would like the ability to have my search bar at the bottom so that I do not have to reach all the way to the top, which can be hard on my large device.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3362)

**Comment by data-sync-user** [comment]
➤ Laurie Marceau commented:

For testing, this is not on the main branch. I have created a Nightly (Build #7961 ( https://app.bitrise.io/build/b95985f7-24e1-4155-ac08-763244e55d71#?tab=log )). This has a lot of changes so wanted to make sure all was ok before merging in main.

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Tested on iPhone 12 pro (15.2), iPhone 13 mini(15.1), iPhone 11 (14.8). On iPhone we didn’t encountered any issues

Note: We’ve found a blocker as this feature is broken on iPad https://github.com/mozilla-mobile/firefox-ios/issues/10083 ( https://github.com/mozilla-mobile/firefox-ios/issues/10083|smart-link )

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Tested on iPad Pro (15.2), iPhone 12 Pro (15.1), simulator iPhone 11 (14.8)
Verifying as fix on v98.0 (8184).

**Comment by GeckoEidechse** [comment]
Confirmed working on iPhone SE 1st gen, version `Firefox Dayligh 98.0 (8233)` :D
