### ISSUE TITLE
Awesome bar results glitch while typing a website that matches the result

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/firefox-ios#9423]
Main: 7eeb1b7

## Steps to reproduce
Open a website
Open a new tab and start typing the same website that was just opened

### Expected behavior
The awesombar is some fine

### Actual behavior
While typing, the awesome bar results present glitches

### Device & build information
* Device: iPhone 11
* Build version: OS 15
    1. Notes
Please see video

https://user-images.githubusercontent.com/1897507/139257387-d7203ac5-66c5-4f47-bedc-dea57a202573.mov

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3367)

**Comment by dnarcese** [comment]
Are you referring to the favicons?
