### ISSUE TITLE
[Accessibility] New tab page accessibility: Dynamic section heights

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#9425]
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3369)

**Comment by data-sync-user** [comment]
➤ Laurie Marceau commented:

For QA, we can make sure that the home page sections is sizing properly when dynamic type is enabled (from accessibility settings). Only recently visited section should not resize.

**Comment by SimonBasca** [comment]
Marking as verified fix on main 176a0f8578a78e652407b322e5bf2176e616e636.
Note: we've logged one issue that can improve "Large text" accessibility for homepage : https://github.com/mozilla-mobile/firefox-ios/issues/10923
