### ISSUE TITLE
Rating Prompt

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#9428]
As a product manager, I want to receive more feedback from users and provide them a fast and easy way to do so right from the app.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3371)

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Tested on 96.0 (7210), on  Firefox Beta 96.0 (7210) and latest main 90ed4859c4215f8 build locally.

I was unable to manually display the Rating Prompt after the following scenario:

  1. Install Firefox 96.0 (7210)
  2. Open tabs tray
  3. Close the app
  4. Set date from the current day to next day (e.g from 30.12 to 31.12)
  5. Open the app
  6. Open tabs tray
  7. Close the app
  8. Set date from the current day to next day (e.g from 31.12 to 01.01)
  9. Repeat steps 5) to 8 ) until reaching the 06.01 date. This way the condition “*CDOU value of 5 in the last 7 days”* is true. 

After doing the mentioned scenario the rating prompt should be displayed upon opening tab tray. So far I was unable to manually display the Rating Prompt.

Laurie Marceau could you please confirm if this scenarios is correct and could you please advise how to make the prompt display?

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

The rating prompt will only appear on app store build. This will be tested on v96.0 when it will be released.

**Comment by data-sync-user** [comment]
➤ Laurie Marceau commented:

Simion Basca It was decided that we need to make a new build for v96 to remove the Rating Prompt. It will be introduced in v97 instead. The Setting item to go directly to the App Store will stay in v96 thought.

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Tested on v96.0 (7353). The user is correctly directed to the “review” screen from app store when tapping on “Rate App” via settings. The rest of the acceptance criteria will be  checked on v97.

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Moving this issue to “Done” in favor of https://mozilla-hub.atlassian.net/browse/FXIOS-3561 ( https://mozilla-hub.atlassian.net/browse/FXIOS-3561|smart-link )

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Daniela Arcese Laurie Marceau I’ve logged https://github.com/mozilla-mobile/firefox-ios/issues/10011 ( https://github.com/mozilla-mobile/firefox-ios/issues/10011|smart-link ) . I think the issue is that the CDOU value is incorrect when Tracking Protection is set to strict and in my case the Rating Prompt is displayed too early. 
Note that I am still investigating this issue and will get back when I’m finished testing all the acceptance criteria.

Laurie Marceau do you know if there is a place where we keep track of the CDOU value?

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

I’ve logged https://github.com/mozilla-mobile/firefox-ios/issues/10012 ( https://github.com/mozilla-mobile/firefox-ios/issues/10012|smart-link ) for the following conditions:

  * Firefox as default browser or
  * signed into sync or
  * added 5 sites to mobile bookmarks or
  * pinned 2 sites to shortcuts or

I’ve logged https://github.com/mozilla-mobile/firefox-ios/issues/10011 ( https://github.com/mozilla-mobile/firefox-ios/issues/10011|smart-link ) for the following conditions:

  * changed default search engine from Google or
  * set TP to strict

**Comment by lmarceau** [comment]
@SimonBasca The CDOU isn't tracked anywhere at the moment. It's only in the code itself and unless debugging it's not accessible.
