### ISSUE TITLE
The `Jump Back in` section is not populated with the current tabs after the section is re-enabled in a new session

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla-mobile/firefox-ios#9430]
## Preconditions
- Have the **Firefox 39 (6519)** installed through TestFlight.
- Be enrolled in the `All Users HomeScreen iOS` rollout.

## Steps to reproduce
1. Start the Firefox App and navigate to a website.
2. Open a New Tab and tap the `Customize Homepage` button.
3. Untoggle the `Jump Back in` option and fully close the app.
4. Reopen the app and tap the `Customize Homepage` button.
5. Toggle the `Jump Back in` option and tap the `Done` button.
6. Scroll up the page and observe the `Jump Back in` section.

### Expected behavior
- The current tab is displayed as a card in the section.

### Actual behavior
- The section is empty.

### Device & build information
* Device: iPhone 11 - iOS 14.7.1
* Build version: Firefox Release 39 (6519)

### Notes
- The issue is also reproducible when enrolled in the `Home Screen Impact Assessment Experiment`.
- The Jump Back in section is successfully populated when navigating to a New Tab, or after the phone is locked and unlocked, or if the app is sent to background then brought back into foreground, or if the app is closed and reopened.
- The issue is also reproducible on the latest Firefox Beta 95 (6528) build.

Attachments: 
- Screen recording of the issue

https://user-images.githubusercontent.com/18304511/139447296-1553d2e8-1d54-428a-8b38-b91890b3b8a7.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3373)

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verifying as fix on main fb4aceb17aaefa61f. This issue is no longer reproducible following the STR

Laurie Marceau while I was testing this issue I found a crash that might be a regression. Could you take a look when you have time. Thanks.
https://github.com/mozilla-mobile/firefox-ios/issues/9650 ( https://github.com/mozilla-mobile/firefox-ios/issues/9650|smart-link )
