### ISSUE TITLE
Default browser is reset to Safari after transferring data from old device or icloud backoup

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#9433]
## Steps to reproduce
1. Set your default browser to Firefox (or Focus)
1. Upgrade to a new device and choose to transfer data from the old device or restore backup from icloud
1. Check what the default browser is set to
    1. Expected behavior

* The default browser should be Firefox
    1. Actual behavior
Default browser is reset to Safari after transferring data from old device or restored from icloud backup
    1. Device & build information
* Build version: 38.1 (6216)
    1. Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3376)

**Comment by lmarceau** [comment]
Curious to know, does this happen as well with other browsers that aren't Safari? Like Chrome or else?

**Comment by SimonBasca** [comment]
@lmarceau the issue is also reproducible with Chrome set as default browser. After transferring data from old device or restored from icloud backup the default browser will be changed to Safari.

**Comment by lmarceau** [comment]
@SimonBasca It looks like this is an OS limitation that we can do nothing about. Unless Apple wants to be nice with us and avoid changing back the default browser 🥲
