### ISSUE TITLE
Long Press Options Change Language

### ISSUE THREAD

**Issue by sajadgoudarzi** [mozilla-mobile/firefox-ios#9434]
Hello There, 

How Can I change long press options language such as "open link" , "Share..." , "Add to photos" and ... inside a tab?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3377)

**Comment by dnarcese** [comment]
@sajadgoudarzi Is the language on that menu not matching the rest of your app?
