### ISSUE TITLE
Reading List - Unable to open pdf documents in reading list

### ISSUE THREAD

**Issue by BigSamSampson** [mozilla-mobile/firefox-ios#9439]
## Steps to reproduce
1. Open firefox browser
2. Type ‘ the secret pdf’ or name of any pdf document
3. Tap on pdf search result
4. Tap Menu button at top right of the page
5. Tap Add to Reading List
6. Tap Reading List
7. Tap thebookhub.01.weebly.com or the link to pdf document
### Expected behavior
The pdf document would open in Reader view
### Actual behavior
The pdf document was unable to open in reader view
### Device & build information
* Device: Apple iPhone 7 - iOS 14.7.1, Wi-Fi
* Build version: firefox daylight 38.1.6216
### Notes
Attachments: 
![image](https://user-images.githubusercontent.com/66958331/139840726-ee483018-fa86-4ee1-b3b2-168dc6ec14ac.png)

![image](https://user-images.githubusercontent.com/66958331/139840811-6b56a045-debc-4bbd-be96-6243b1f95797.png)

![image](https://user-images.githubusercontent.com/66958331/139840845-4357ee24-c883-4f0f-b52d-ffddee626f25.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3379)

**Comment by lmarceau** [comment]
This seems to relate to https://github.com/mozilla-mobile/firefox-ios/issues/9429

**Comment by dnarcese** [comment]
PDFs are not compatible with reader mode. The bug here is that we are allowing the user to add it to their reading list. #9500
