### ISSUE TITLE
Download button is not persistent in Data Management Settings after enabeling it and going back to Settings

### ISSUE THREAD

**Issue by BigSamSampson** [mozilla-mobile/firefox-ios#9440]
## Steps to reproduce
1. Go to the firefox browser
2. Tap on settings
3. Tap on Data Management
4.Move the slider to the on position - download files
5. Tap on the arrow from top to back
6. Again tap on Data Management
### Expected behavior
the slider should remain where it is set and you can download the file
### Actual behavior
after pressing the back arrow, the slider crawls, the file is not loaded
### Device & build information
* Device: Apple iPhone 6S - iOS 15
* Build version: firefox daylight 38.1.6216
### Notes
Attachments: 
![image](https://user-images.githubusercontent.com/66958331/139844231-c4f53e17-95ef-4882-bc4d-40ecf81fcd44.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3380)

**Comment by dnarcese** [comment]
This is intended behaviour. The default for downloaded files should be off so the user wont accidentally clear them.
