### ISSUE TITLE
New tab - Section "your library" is not displayed

### ISSUE THREAD

**Issue by BigSamSampson** [mozilla-mobile/firefox-ios#9441]
## Steps to reproduce
1. Open the firefox browser
2. Tap on new tab
### Expected behavior
The user expects the section to be displayed on the iPad.
### Actual behavior
Section "your library" is not displayed
### Device & build information
* Device: Apple iPad Air 2 Wi-Fi - iPadOS 14.4.2
* Build version: firefox daylight 38.1.6216
### Notes
Attachments: 

https://user-images.githubusercontent.com/66958331/139859919-a219cbbf-af4a-4039-a44e-1d67869c7303.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3381)

**Comment by dnarcese** [comment]
This is intentional behaviour
