### ISSUE TITLE
Extra padding in bookmark and history panel

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#9444]
## Steps to reproduce
1. Go to Bookmark panel or History panel
2. Observe the top and bottom padding of bookmark folders
### Actual behavior
- There is an extra padding top and bottom.
### Device & build information
* Device: iPhone 12 Pro  (15.1)
* Build version: 95 (6528)
### Notes
Attachments:
![Skype_Picture_2021_11_02T15_13_47_325Z](https://user-images.githubusercontent.com/32130829/139875271-2398bf0f-7d09-4acd-9fad-bc3857da270e.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3383)

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verified fix on main 6d2f1b4cbe546aacc398436223f19d7592295c5c.
