### ISSUE TITLE
Incorrect tab title is displayed after tapping "Home" button

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#9446]
## Steps to reproduce
1. Go to google.com
2. Tap on the "home" button or the navigation "back" arrow
3. Open tabs tray
4. observe the tab title
### Expected behavior
- Tab title should be "Home"
### Actual behavior
- Tab title is "Google"
### Device & build information
* Device: iPhone 12 Pro (15.1)
* Build version: 95 (6528)
### Notes
Attachments:
![Picture_2021_11_02T15_35_19_845Z](https://user-images.githubusercontent.com/32130829/139879042-d5b48e3e-607a-47b4-bd84-70e3a9ea856b.jpeg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3385)

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

This issue is still reproducible on latest main f841cd0f34fb8f0ba3cf3da8b12e53d174c7432a. 
Nishant Bhasin is this a “won’t fix” issue or it got moved to QA Needed by mistake? I don’t see a PR attached to it.

**Comment by data-sync-user** [comment]
➤ Nishant Bhasin commented:

Simion Basca I was hoping this would have been fixed by fixing the screenshot issue but we removed that fix (due to a crash) and put this issue in QA column to check if it works without it. 

We should reopen it this. Thanks for checking it.

**Comment by junbio** [comment]
This bug occurs for any tab that was restored and has the same root cause as #8395. So committing #9031 should also fix this issue.

**Comment by nbhasin2** [comment]
https://user-images.githubusercontent.com/8919439/153931827-74b2ca3c-2093-441d-b7bf-c145f3f4b6b7.mov

Hi, @SimonBasca could you try the main branch and let me know if you still encounter this issue

**Comment by SimonBasca** [comment]
I'm no longer reproducing the issue on latest main e2f1c7db78b1cf610216dee1c0126f9e5d735baf. Marking as verified fix.
