### ISSUE TITLE
Javascript private member methods cause error

### ISSUE THREAD

**Issue by RobbieS82** [mozilla-mobile/firefox-ios#9454]
## Steps to reproduce
Go to https://jsfiddle.net/hjxqrnt3/6/ in Firefox for iOS and view the console.

### Expected behavior
The output pane should show "abc" and "def" on two separate lines.

### Actual behavior
The console reports an unexpected error:  SyntaxError: Unexpected private name #showSecret. Cannot parse class method with private name."

### Device & build information
* Device: iPhone 11
* Build version: 14.8
    1. Notes
Attachments: 
Firefox Daylight 38.1 (6216)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3395)

**Comment by dnarcese** [comment]
Let's check if this works in Safari

**Comment by nbhasin2** [comment]
Hi, I just checked Firefox 39.0 and can see 

abc 
def

![image](https://user-images.githubusercontent.com/8919439/140381442-b57f5f02-6c9a-4a80-a165-c11e0a3518d0.jpeg)
