### ISSUE TITLE
Onboarding screen to logins is not localized

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#9465]
## Preconditions:
* Disable biometrics and passcode to unlock device if previously enabled.
  1. Steps to reproduce

1. Go to Settings -> Login
    1. Actual behavior

* Onboarding screen to logins is not localized 
    1. Device & build information
* Device: iPhone 12 Pro (15.1)
* Build version: 95 (6528)
    1. Notes
Attachments:
![Screenshot](https://user-images.githubusercontent.com/32130829/140287035-b9ad8379-ad28-4b1f-a310-f589a730d1f3.jpeg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3403)

**Comment by Delphine** [comment]
This seems to be a string on Nightly. It has not been exposed for l10n for v95/v40

@dnarcese I was told there were no strings for v40 when I checked at string freeze date. Should this have been exposed? Otherwise, can we make sure it doesn't get into beta? thanks

**Comment by st3fan** [comment]
This has been taken care of with https://github.com/mozilla-l10n/firefoxios-l10n/pull/120

I don't think a beta build with these strings has gone out yet after the above PR landed though. @SimonBasca I'll leave this bug open until we can confirm?

**Comment by SimonBasca** [comment]
@st3fan this is still an issue on v40 (6861) RC
![screenshot](https://user-images.githubusercontent.com/32130829/143407671-4d9cbbd5-5170-4dc8-9589-1fcd02110154.jpeg)
.

**Comment by dnarcese** [comment]
We are doing our string import on 11/29. Let's check again then.
