### ISSUE TITLE
Autofill is not working

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#9467]
## Steps to reproduce
1. Enable auto fill for Firefox
2. Launch Firefox
3. Go to "Facebook.com"
4. Tap on the login field
5. Tap on "Passwords" button
6. Select Firefox
7. Select a login from the list
### Expected behavior
- The password and username should be autofilled. 
### Actual behavior
- The password and username is not filled. 
### Device & build information
* Device: iPhone XR 15.1
* Build version: 40.0 6563
### Notes
Attachments: 

https://user-images.githubusercontent.com/32130829/140303369-03ad6a7d-4945-404d-858d-d99ceeb1fa48.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3405)

**Comment by st3fan** [comment]
This was the result of an incorrect provisioning profile for `org.mozilla.ios.FirefoxBeta.CredentialProvider` where the team prefix of the keychain access group was incorrectly set. As a result the Credential Provider could not load the username and password.

**Comment by SimonBasca** [comment]
Verified fix on beta 95 (6631)
