### ISSUE TITLE
Login list does not display username

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#9468]
## Steps to reproduce
1. Enable autofill
2. Go to "Facebook.com"
3. Tap on the username field
4. Tap on the "Passwords" button
5. Scroll trough the list
### Expected behavior
- The domain and username should be displayed in the list
### Actual behavior
- Only the  domain is displayed in the list
### Device & build information
* Device: iPhone XR 15.1
* Build version: 40. 0 (6563)
### Notes
Attachments: 

https://user-images.githubusercontent.com/32130829/140303851-c8c99f15-9272-48e8-b325-ebaa63d1710f.mov

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3406)

**Comment by st3fan** [comment]
This was the result of an incorrect provisioning profile for `org.mozilla.ios.FirefoxBeta.CredentialProvider` where the team prefix of the keychain access group was incorrectly set. As a result the Credential Provider could not load the username and password.

**Comment by SimonBasca** [comment]
Verified fix on beta 95 6631
