### ISSUE TITLE
No new tabs showing on tab view just on search

### ISSUE THREAD

**Issue by mattmactimpson** [mozilla-mobile/firefox-ios#9471]
## Over 400 tabs and open new tab
Go into tab view and new tab does not appear 

### Device & build information
* Device: 13 pro max
* Build version: 39.0
### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3408)

**Comment by dnarcese** [comment]
@mattmactimpson are you able to provide a screenshot or screen recording?

**Comment by mattmactimpson** [comment]
https://user-images.githubusercontent.com/57722195/140383735-bfae8811-cdb1-485f-aa4e-e2ce737fa4ea.MOV
Here's a shorter clip

**Comment by mattmactimpson** [comment]
There's a good 10 sec before the tab view pops up
