### ISSUE TITLE
[Crash XCode Report] [v39] - Client: BrowserProfile BrowserSyncManager

### ISSUE THREAD

**Issue by nbhasin2** [mozilla-mobile/firefox-ios#9482]
<img width="1045" alt="Screen Shot 2021-11-08 at 2 32 11 PM" src="https://user-images.githubusercontent.com/8919439/140805820-c94a7dd2-3e13-4a30-9e7e-b32e376f926d.png">

[BY0uhr7NdJRyb2mzlR3WQd.xccrashpoint.zip](https://github.com/mozilla-mobile/firefox-ios/files/7499608/BY0uhr7NdJRyb2mzlR3WQd.xccrashpoint.zip)

<img width="1039" alt="Screen Shot 2021-11-08 at 2 33 55 PM" src="https://user-images.githubusercontent.com/8919439/140806056-565050ea-48c8-4ca8-99f7-12bf92db1f72.png">

[zx3Fg_SUC6TN-JU--REUN.xccrashpoint.zip](https://github.com/mozilla-mobile/firefox-ios/files/7499611/zx3Fg_SUC6TN-JU--REUN.xccrashpoint.zip)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3412)

**Comment by data-sync-user** [comment]
➤ Jeremy Evans commented:

Nishant Bhasin

**Comment by data-sync-user** [comment]
➤ Orla Mitchell commented:

Simion Basca This is a potentially risky change to the sync functionality. Could we add some exploratory testing for general sync functionality for v102?

**Comment by data-sync-user** [comment]
➤ Orla Mitchell commented:

Simion Basca Is the push notification still not showing or is it the tab itself that doesn’t turn up. If the push notification is not showing at all then it’s unrelated to this ticket. If the push notification shows but there are issues with the tab itself opening then it might be a regression introduced by this change.

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Orla Mitchell I am not receiving neither the push notification or the tab. Also tried sending the tab while the app was in foreground and also didn’t received the tab. Also related to push notification I’ve just logged https://mozilla-hub.atlassian.net/browse/FXIOS-4444 ( https://mozilla-hub.atlassian.net/browse/FXIOS-4444|smart-link ).

**Comment by data-sync-user** [comment]
➤ Orla Mitchell commented:

In that case I don’t believe anything in this change has contributed to that.

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Marking the issue as verified fix on v102.0 (11005) based on the discussion and the tests run for v102.0.
