### ISSUE TITLE
Sync: SwiftData.forceClose() when entering background

### ISSUE THREAD

**Issue by nbhasin2** [mozilla-mobile/firefox-ios#9484]
![](https://user-images.githubusercontent.com/8919439/140806514-67ac29a2-5dc8-451b-9b8a-d91385e606e5.png)

[CWn9O48hCciDf9Z-6549wC.xccrashpoint.zip](https://github.com/mozilla-mobile/firefox-ios/files/7499631/CWn9O48hCciDf9Z-6549wC.xccrashpoint.zip)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3414)

**Comment by data-sync-user** [comment]
➤ Laurie Marceau commented:

This could also relates to the following:

!Screen Shot 2022-01-27 at 4.21.25 PM.png|width=729,height=327!

!Screen Shot 2022-01-27 at 4.21.33 PM.png|width=804,height=350!

!Screen Shot 2022-01-27 at 4.21.44 PM.png|width=633,height=301!

Could be that there’s a general issue as to how things are implemented when we go to background.

**Comment by data-sync-user** [comment]
➤ Laurie Marceau commented:

Still happening as of v101
