### ISSUE TITLE
UIKitCore: -[UITableView _updateRowsAtIndexPaths] Sitetableviewcontroller apply theme

### ISSUE THREAD

**Issue by nbhasin2** [mozilla-mobile/firefox-ios#9486]
![width=200,height=183](https://user-images.githubusercontent.com/8919439/140806871-187c4452-d79e-48c4-b9f8-fb2a660a0bf1.png)

[DHg5fVp6kx0F9SCK1COIK-.xccrashpoint.zip](https://github.com/mozilla-mobile/firefox-ios/files/7499656/DHg5fVp6kx0F9SCK1COIK-.xccrashpoint.zip)

affecting 2000 devices

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3416)

**Comment by data-sync-user** [comment]
➤ Laurie Marceau commented:

Still occurring as of v101

**Comment by data-sync-user** [comment]
➤ Laurie Marceau commented:

Does not occur anymore as of 108.1, closing until further notice.
