### ISSUE TITLE
Recently saved items are not displayed after going to the homepage

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#9490]
## Steps to reproduce:
1. Enable Recently Saved 
2. Bookmark a page
3. Open a new tab -> Observe that the item is displayed in the Recently Saved
4. Visit a page
5. Go to the home page by tapping on the "Home" icon or navigation "back" button
### Expected behavior:
- Recently saved items should be displayed after going to homepage.
### Actual behavior:
- Recently saved items are not displayed after going to homepage.
### Device & build information:
* Device: iPhone Xr 15.1 
* Build version: 95 (6528) and main 60640b8ab718
### Notes
Attachments: 
https://user-images.githubusercontent.com/32130829/140946181-cdf706c4-68bc-4149-86d5-617d93847fcf.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3418)

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verified fix on main fb4aceb1 on iPhone Xr 15.1
