### ISSUE TITLE
Attentive mode is not dismissed when Shortcuts rows is set to 2 or less.

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#9492]
## Steps to reproduce
1. Go to Settings -> Homepage ~~> Shortcuts~~ > Set rows to 2 or 1
1. Go to Settings ~~> Homepage~~ > Disable Pocket, Jump In and Recently Saved
1. Open a new tab
1. Try swiping or tapping on the homepage to dismiss attentive mode
    1. Expected behavior

* Attentive mode should be dismissed when swiping on the homepage.
    1. Actual behavior
* Attentive mode is not dismissed when Shortcuts rows is set to 2 or less.
    1. Device & build information
* Device: iPhone Xr (15.1)
* Build version: 95 (6528) and main 60640b8
    1. Notes
Attachments:

https://user-images.githubusercontent.com/32130829/140954303-98d161d4-ec00-4182-af75-1a5682c3cd02.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3420)

**Comment by data-sync-user** [comment]
➤ Daniela Arcese commented:

Current behaviour: attentive mode will only dismiss on tap the first time; or will always dismiss if the view is scrollable.
Possible solution: check where the tap is happening and dismiss if the tap is outside of a tile or button; and dismiss on any scroll gesture
