### ISSUE TITLE
Can't log in with saved login to https://www.uniqlo.com/jp/ja/

### ISSUE THREAD

**Issue by iccub** [mozilla-mobile/firefox-ios#9498]
## Steps to reproduce
Go to https://www.uniqlo.com/jp/ja/ create account and log in to it once.
Log out and go to this site again to log in
Saved login should fill in, try to log in

### Expected behavior
Should log be im

### Actual behavior
Shows error, the error says that username and password are empty

### Device & build information
* Device: iPhone 8, iOS 14.8.1
* Build version: Firefox Daylight 39.0 (6519)
### Notes
This is a problem with LoginsHelper javascript. When credentials are set, no event is fired and if website's validation relies on `change` event to check for the filled in password, it fails.
This may happen for other websites too, it's not this website specific.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3421)

**Comment by lmarceau** [comment]
Issue was closed when I merged the PR but it still needs to be QA checked. So reopening.

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

I was able to successfully log in to the EU version of the site http://www.uniqlo.com/eu/en/ ( http://www.uniqlo.com/eu/en/|smart-link ) after previously saving the login. 

Verifying as fix on main 627116c214d9d74bb5a391f.
