### ISSUE TITLE
Add to Reading List is allowed on non-reader mode pages

### ISSUE THREAD

**Issue by dnarcese** [mozilla-mobile/firefox-ios#9500]
## Steps to reproduce
1. search something on google
2. click PAM
3. add to reading list is available
### Expected behavior
Add to reading list option should not be available because the page is not one that can be converted to reader mode.
### Actual behavior
Add to reading list option should not be in the menu
### Device & build information
* Device: ?
* Build version: ?
### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3422)

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Verified as fixed on v111 (28148) with iPhone 14 (16.1).
