### ISSUE TITLE
Can’t sync

### ISSUE THREAD

**Issue by lilarcor** [mozilla-mobile/firefox-ios#9501]
## Steps to reproduce
Turn on sync,use scan or email,you will get a blank page. 

### Device & build information
* Device: iPhone 12
* Build version: 39.0 6519
    1. Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3423)

**Comment by SimonBasca** [comment]
Thank you for reporting, could you please add a video of the issue?

**Comment by lilarcor** [comment]
https://share.icloud.com/photos/0u-wUza6-mLmgMNcdPByKP5fw

Don't know how to upload a video on github. Hope you can watch it from my shared link.

**Comment by lilarcor** [comment]
And if you try to open the site stable.dev.lcip.org/pair, you will get error page.

**Comment by dnarcese** [comment]
@lilarcor if you wait for awhile longer does the page eventually show up? Mine shows up after a couple of seconds.

**Comment by lilarcor** [comment]
@dnarcese I stayed in the page for around 5 mins, nothing happened. quite strange.

**Comment by lilarcor** [comment]
I think I found the reason, as I tried to use custom token sync server.
