### ISSUE TITLE
The view is not scrolled to the selected tab

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#9502]
## Steps to reproduce
1. Open a few tabs to enable scrolling in tabs tray
2. Open tabs tray
### Expected behavior
- The view should be scrolled to the selected tab
### Actual behavior
- The view is not scrolled to the selected tab
### Device & build information
* Device: iPhone 12 Pro (15.1)
* Build version: 95 (9076)
### Notes
Attachments:
https://user-images.githubusercontent.com/32130829/141287547-cf80885d-3ef3-42ec-99b2-6adf8b34e51d.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3424)

**Comment by dnarcese** [comment]
@SimonBasca can you test this again on the latest nightly build v9000(6756)

**Comment by isabelrios** [comment]
I have that TF build 6756 and I can reproduce it. Which version were you testing on when saw the issue @SimonBasca we can't find it 🙈

**Comment by SimonBasca** [comment]
This was reproduced in v95 (9076). It seems it's no longer an issue on latest main 524977153 and v95 (6631).

**Comment by isabelrios** [comment]
Not sure about this @SimonBasca I can reproduce the issue in latest TF build 6756 which is later than the one you mentioned above 6631...

**Comment by SimonBasca** [comment]
I retested on v9000 (6756), (6773) and latest main 7f7cac288086 and the issue is not reproducible on my side. Feel free to re-open if it's still reproducible on your side @isabelrios.

https://user-images.githubusercontent.com/32130829/142613576-8ada2db3-3ff4-4ada-a3b1-82aa5ed74214.mp4
