### ISSUE TITLE
[Crash] App crashes after signing out from sync and going to homescreen panels: bookmarks, history

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/firefox-ios#9512]
This crash has been reproduced in main and TF beta (6684)

**Steps**
-Fresh install the app, from homescreen select Settings -> Back up and Synchronise Data
-Log in with a FxA account with history/bookmarks
-Wait until the sync process finishes, go to Bookmark, History from Homepanel screen to check that everything is synced
-Log out and go to homepanel screen again and access Bookmarks, History, Downloads

**Expected**
App works as usual

**Actual**
App crashes

Part of crash log:

_dyld4 config: DYLD_ROOT_PATH=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid update: invalid number of rows in section 1. The number of rows contained in an existing section after the update (0) must be equal to the number of rows contained in that section before the update (100), plus or minus the number of rows inserted or deleted from that section (0 inserted, 0 deleted) and plus or minus the number of rows moved into or out of that section (0 moved in, 0 moved out). Table view: <UITableView: 0x7ff31a9e5400; frame = (0 0; 414 704); clipsToBounds = YES; gestureRecognizers = <NSArray: 0x60000258b960>; layer = <CALayer: 0x600002a43500>; contentOffset: {0, 0}; contentSiz_

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3433)

**Comment by SimonBasca** [comment]
I was able to reproduce the issue on latest main 94bcc52a1ca9b8d8197f6e56361639f0c1bb45a7. In my case the app crashed after step 3).

[Client-2021-11-17-124315.ips.zip](https://github.com/mozilla-mobile/firefox-ios/files/7553960/Client-2021-11-17-124315.ips.zip)

Note: Might be related to https://github.com/mozilla-mobile/firefox-ios/issues/9506

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

We were unable to reproduce the issue on Firefox 9000 (9505). We will re-open in the issue is reproduced again.
