### ISSUE TITLE
The layout of the toolbar is abnormal after upgrade to  Firefox Beta 9000 ( 6746 ) and ( 6684 )

### ISSUE THREAD

**Issue by bli-mozbj** [mozilla-mobile/firefox-ios#9514]
## Steps to reproduce
1. Open some webpage in Firefox Beta 9000 ( 6675 or earlier), such as wikipedia.
2. Upgrade to Firefox Beta 9000 ( 6746 or 6684)
3. Launch Firefox 

### Expected behavior
Layout and function of the toolbar are all well.

### Actual behavior
The layout of the toolbar is abnormal.
The buttons are all small and hard to be touched. 
Pls refer to the attachment.

### Device & build information
* Device:  iPhone 11 ,  iOS 15
* Build version:  Firefox Beta 9000 ( 6746 ) and ( 6684 )

### Notes
Attachments: 
![IMG_0821](https://user-images.githubusercontent.com/25242209/142172085-e3296aaf-48ff-4687-9af3-ddb6ea3cd7cc.PNG)

### More info
1. Focus on the address bar and come back or just go to another website, then the toolbar will be normal.
2. Firefox Beta 9000 ( 6620 ) upgrade to 9000 ( 6675 ), the layout of toolbar is normal.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3435)

**Comment by isabelrios** [comment]
this is a dup of #9288 Bottom toolbar icon size shrinks, closing as there are different ways to reproduce it in that other issue
