### ISSUE TITLE
Two selected tab when removing a tab

### ISSUE THREAD

**Issue by lmarceau** [mozilla-mobile/firefox-ios#9526]
## Steps to reproduce
Noted this while working on https://github.com/mozilla-mobile/firefox-ios/issues/9204
- Open multiple tabs
- Select a tab in the middle of the tray (so there's at least 1 tab after the selected one)
- Close a tab before the selected tab
![Double selected tab issue](https://user-images.githubusercontent.com/11338480/142502223-ba433123-4975-4e74-a146-5a0be5f0d87b.png)

### Expected behavior
Only the selected tab has the selected blue contour

### Actual behavior
Two tabs have the selected blue contour

### Device & build information
* Device: Simulator iPhone 11
* Build version: Nightly 9000 (6746)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3439)

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verified fix on main 866c5e81e3
