### ISSUE TITLE
Ctrl+tab and ctrl-shift+tab do nothing on iPad with Smart Keyboard Folio connected

### ISSUE THREAD

**Issue by hnibbit** [mozilla-mobile/firefox-ios#9532]
## Steps to reproduce
1. Open more than one tab in Firefox on iPad.
2. Press ctrl+tab or ctrl-shift+tab on iPad Smart Keyboard Folio.
### Expected behavior
Should switch to next/previous tab.
### Actual behavior
Nothing happens.
### Device & build information
* Device: iPad Pro 11 inch, running iPadOS 15.1
* Build version: Firefox Daylight 39.0 (6519)

Reproduced on two separate iPads running same version of iPadOS and Firefox.
### Notes
This worked as expected (i.e. switched between tabs) until downloading the latest Firefox update, so I assume it is a new bug introduced with this update. 
With that said, there was a different issue when switching tabs using ctrl+tab on an iPad folio previously, where using this keyboard shortcut resulted in multiple empty tabs being opened. So this has been buggy for a while, just in a different way. The old problem was, however, preferable to it not working at all.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3440)

**Comment by tech189** [comment]
Can confirm on my exact same setup - and pretty sure it worked in a previous version!

**Comment by lmarceau** [comment]
Hello! I worked on the shortcuts a bit in [PR](https://github.com/mozilla-mobile/firefox-ios/pull/9606) and [PR](https://github.com/mozilla-mobile/firefox-ios/pull/9596).
Those changes are now on main and will be released with v96 (v41). Please let me know when you get the update if this improved the tab change shortcuts!

**Comment by tech189** [comment]
Thank you very much, I can’t wait to use them when they’re released!!

If you have time, I would really appreciate it if you could also make a PR to add/fix the cmd-shift-t shortcut to undo a closed tab! (I made an issue here: #9266)

**Comment by miguelarios** [comment]
Same here this is also happening with my brydge keyboard on my iPad Pro

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verifying as fix on main 552d8a8

**Comment by hnibbit** [comment]
> Hello! I worked on the shortcuts a bit in [PR](https://github.com/mozilla-mobile/firefox-ios/pull/9606) and [PR](https://github.com/mozilla-mobile/firefox-ios/pull/9596).
> Those changes are now on main and will be released with v96 (v41). Please let me know when you get the update if this improved the tab change shortcuts!

Thank you so much! Can't wait for that update to drop!
