### ISSUE TITLE
Change long touch options languages

### ISSUE THREAD

**Issue by sajadgoudarzi** [mozilla-mobile/firefox-ios#9536]
Hello There, 

I have a problem with firefox project. I have translated all words in the project to my language but there are some suggestions when user press a long touch on a link for example that I cannot change their words to something in my own languages. 
Could you please let me know how I should do that? 

any help would be highly appreciated.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3442)

**Comment by SimonBasca** [comment]
@sajadgoudarzi thanks for reporting this issue. Could you please provide a screenshot and some exact steps on hot to reproduce this issue?
