### ISSUE TITLE
Deleted tab is added back to tab tray when a tab is moved place

### ISSUE THREAD

**Issue by lmarceau** [mozilla-mobile/firefox-ios#9538]
This bug is in the Prod app as well 🐞 It doesn't crash there thought.

## Steps to reproduce
1. Have at least 3 tabs
2. Open the tab tray
3. Delete the last tab
4. Long press one of the remaining tab and move it's place
5. The tab that was deleted is added back to the tab tray
Note: If you try to delete the weird tab, you can't (does nothing clicking on the X).

In the prod app, if you click on that deleted/added back tab, it tries to load another tab but fails. Doesn't crash.

https://user-images.githubusercontent.com/11338480/142703113-cac9ecf9-8440-4a46-92d5-b6b1adbd6561.MP4

On the main branch, if you click on that deleted/added back tab, it crashes.

https://user-images.githubusercontent.com/11338480/142703122-f6ff6700-2bf6-4cab-a3ee-51a28df1a6d2.MP4

### Expected behavior
- A tab deleted is deleted for good, even if we exchange tab in the tab tray

### Actual behavior
- The tab that was deleted is added back to the tab tray

### Device & build information
* Device: iPhone 11 
* Build version: 39.0 (6519), Prod app and main branch

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3446)

**Comment by SimonBasca** [comment]
Verified fix on v96.0 (7278).
