### ISSUE TITLE
Your Connection is not secure

### ISSUE THREAD

**Issue by Saimaiman** [mozilla-mobile/firefox-ios#9545]
hello, I'm facing the issue appears on firefox iOS[.](https://loginworldz.com/).., "Your Connection is Not Secure"... Normally browser provide option to visit the untrusted site but I didn't find such option. I tried so many solutions but unable to access my desired site.[.](https://loginwelt.com/)., kindly anyone guide me on this.
Thanks

Regards
Saim

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3449)

**Comment by SimonBasca** [comment]
@Saimaiman could you please provide some exacts steps to how this issue is reproduced? Also a link to the site that's causing issues is helpful and also checking how the site behaves in Safari.

**Comment by DarkKnight999** [comment]
I also faced the same issue. I tried a lot of things like cleaning my browser, going to default settings e.t.c. Then I Just realized that I was using some of the extensions that were corrupted. It was an AD Blocker. I just deleted them and the Issue get resolved. I would say [AVS Series](https://avsseries.com/sultan-abdul-hamid-sultan-abdulmecid-urdu-dubbed-by-ptv/) helped me a lot.
