### ISSUE TITLE
Missing (?) source information in glean ad metrics

### ISSUE THREAD

**Issue by ANich** [mozilla-mobile/firefox-ios#9547]
Hi, I'm looking to get some context on the recently added glean metrics for searches implemented in https://github.com/mozilla-mobile/firefox-ios/pull/8970 so [`browser_search_with_ads`](https://dictionary.telemetry.mozilla.org/apps/firefox_ios/metrics/browser_search_with_ads) and [`browser_search_ad_clicks`](https://dictionary.telemetry.mozilla.org/apps/firefox_ios/metrics/browser_search_ad_clicks).

I'm comparing these to metrics in other clients and I've noticed the "source" information isn't in the iOS metrics - the key format here seems to be `provider-{provider`} where in Android/Desktop for eg. we have something like `{provider}.{source}.{source`} at least for some providers. 

Is this difference intentional? I'm not 100% familiar with how we count mobile search searches. 

cc @xluo-ds

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3451)

**Comment by st3fan** [comment]
It looks like Firefox iOS does not follow the same format that Fenix uses. Specifically, this code is not present in the iOS client:

https://github.com/mozilla-mobile/android-components/blob/6c0fe91ab83614265f533b819bf406fc046b2227/components/feature/search/src/main/java/mozilla/components/feature/search/telemetry/TrackKeyInfo.kt#L28-L35

```
    /**
     * Returns the track key information into the following string format:
     * `<provider>.in-content.[sap|sap-follow-on|organic].[code|none](.[channel])?`.
     */
    fun createTrackKey(): String {
        return "${provider.lowercase(Locale.ROOT)}.in-content" +
                ".${type.lowercase(Locale.ROOT)}" +
                ".${code?.lowercase(Locale.ROOT) ?: "none"}" +
                if (!channel?.lowercase(Locale.ROOT).isNullOrBlank()) {
                    ".${channel?.lowercase(Locale.ROOT)}"
                } else ""
    }
```

I ran into this when working on the same telemetry for Focus too. We should probably aim for more consistency between the different mobile applications.

**Comment by xluo-ds** [comment]
yes, that's correct. That implementation was relatively new to give us a
better idea about the source of downstream metrics for `tagged_sap`,
`search_with_ads` and `ad_clicks`. I didn't know that it's not available on
iOS.
I assume this shouldn't pose a problem for `mobile_search_aggregates`, but
probably also good to check the implementation efforts if we want to be
aligned among platform.

**Comment by st3fan** [comment]
@xluo-ds @ANich i deleted my comment because I think it needs further investigation before I am comfortable presenting a conclusion.
