### ISSUE TITLE
Tab title and favicon is missing from empty home tab after selecting it.

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#9548]
## Steps to reproduce
1. Open a new tab
2. Open a new tab and visit "twitter.com"
3. Close the app from app switcher
4. Re-open the app
5. Tap on the empty tab with the title (Home)
### Expected behavior
- Tab title should be displayed
### Actual behavior
- Tab title and favicon is missing from empty home tab after selecting it.
### Device & build information
* Device: iPad Pro 14.8
* Build version: latest main 3854167149
### Notes
Attachments: 
[video.mp4.zip](https://github.com/mozilla-mobile/firefox-ios/files/7584078/video.mp4.zip)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3452)

**Comment by lmarceau** [comment]
@SimonBasca I think https://github.com/mozilla-mobile/firefox-ios/issues/8716 should be resolved as well. Maybe can be confirmed with this ticket? 🙏

**Comment by SimonBasca** [comment]
Verifying as fix on main 42920ddd191
