### ISSUE TITLE
Cannot properly correct a typo in the middle of search word/phrase

### ISSUE THREAD

**Issue by aevansWL** [mozilla-mobile/firefox-ios#9550]
## Steps to reproduce

1. In the address bar, purposely type a misspelled search term *in the middle* of the search phrase.
2. Correct the typo. 
3. Press enter to search.
4. Check the search phrase, noticing that the typo is strangely not corrected in the search bar on the search engine’s page.

### Expected behavior

Search bar updates to reflect the corrected typo.

### Actual behavior

Search does not update with corrected word (UNLESS you go to the end of the whole search phrase and add a space or letter).

### Device & build information
* Device: iPhone XR, iOS 15.1
* Build version: 39.0

### Notes

Attachments: https://twitter.com/amandaewriting/status/1462598133867819008?s=20
(See screen recording attached to Tweet.)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3457)

**Comment by data-sync-user** [comment]
➤ Daniela Arcese commented:

The overall bug here is that the search suggestions do not update if you change anything in the middle of the search phrase. It only updates when you add to the end.

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verified fix on main 6b01440f6274573f010b501a7c52de6d19c72bd3. The search suggestion are properly updated after correcting a typo in the middle of the search phrase.
