### ISSUE TITLE
A series of 10 numbers (for sizes) are detected as phone number

### ISSUE THREAD

**Issue by karlcow** [mozilla-mobile/firefox-ios#9553]
## Steps to reproduce
1. with Firefox on iPad
1. Go to https://holstone.com.mx/collections/jeans-hombre/products/532903?variant=32759650287663
1. Select size 30

### Expected behavior
Size 30 is selected

### Actual behavior
The widget for making a call appears

### Device & build information
* Device: iPad Mini 4 iOS 14.8 (1536 x 2048 pixels (~324 ppi density))
* Build version: Firefox Daylight 39.0 (6519)

### Notes
on macOS you need to select first to trigger the widget on calling a phone number.
I'm not sure this is a bug of Firefox iOS, it might be something for WebKitWebView.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3459)

**Comment by dnarcese** [comment]
might be the same as #8511

**Comment by DorianCoding** [comment]
The issue continues…

**Comment by data-sync-user** [comment]
➤ Nishant Patel commented:

It doesn’t seem like we can define a custom data detector and provide our own regex to WKWebViewConfiguration. 

I’ll prepare a build for Product to evaluate the experience with the changes I’m proposing before I raise a PR.

**Comment by DorianCoding** [comment]
Hello,

Also it would be great to block the detection when format detection is set as no. It is what is happening on Safari. It would at least allow websites compatible with Safari to avoid this mess before dealing with the detection itself.

**Comment by data-sync-user** [comment]
➤ Daniela Arcese commented:

Nishant Patel let’s remove phone number detection and let the site configure it

**Comment by data-sync-user** [comment]
➤ Alina Moldovan commented:

validated this issue using v9000 (32242) and iPhone 16+(16.0.1) & iPad Air 3rd Gen (16.3.1). 

Not able to preproduce the bug anymore. I can confirm that the widget for making a call appears for sites with tappable phone number
