### ISSUE TITLE
[Bug] page reloading in low power mode

### ISSUE THREAD

**Issue by eliserichards** [mozilla-mobile/firefox-ios#9554]
## Steps to reproduce
I haven't been able to repro on any site other than https://hard-drive.net. This doesn't seem to depend on ETP - it happens with ETP on and off. 

1. Have the iOS low power mode ON
1. Navigate to https://hard-drive.net 
1. Wait 5-10 seconds

### Expected behavior
The site doesn't reload

### Actual behavior
The site reloads (see video). If you keep waiting, it keeps reloading. When I turn low power mode off, it no longer reloads. 

### Device & build information
* Device: iPhone 12 Pro iOS 14.8.1
* Build version: Firefox Daylight 39.0 (6519)

### Notes
Attachments: 
https://user-images.githubusercontent.com/43795363/143179160-95badfe6-6e49-4c16-add1-e4f45398b96f.MOV

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3460)

**Comment by SimonBasca** [comment]
I was able to reproduce the issue also on v40 (6841) on iPhone 12 Pro with only one tab opened. Also note that this issue was not reproduced in Safari or Chrome
