### ISSUE TITLE
Apple pay not supported in Firefox or 3rd party browser

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#9565]
## Steps to reproduce
1. Go to https://stripe.com/en-ro/apple-pay.
2. Tap on "Try it now"
### Expected behavior
- Apple pay prompt should be displayed.
### Actual behavior
- Apple pay prompt is not displayed.
### Device & build information
* Device: iPhone 12 Pro
* Build version: 95 (6631)
### Notes
- Not working in Chrome
- Works in Safari
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3473)

**Comment by sneakernuts** [comment]
The page says - See Apple Pay in action with a test payment. 
To try it, you need Apple Pay set up and Safari, starting with iOS 10 or macOS Sierra.

I don't believe this is a bug in Firefox itself. It's not a supported config by Stripe.

**Comment by gutley** [comment]
According to [Apple's Documentation](https://developer.apple.com/documentation/apple_pay_on_the_web)

> In iOS, Apple Pay is supported in Safari and in SFSafariViewController objects

So no go for other browsers at all.

Here is Apple's own ApplePay demo page:

https://applepaydemo.apple.com

**Comment by jaraco** [comment]
I too would like this feature. I understand that Apple may not be supplying the APIs to make this possible, but it seems to me that a request from Google and/or Mozilla would carry a lot more weight than feedback directly from users. Would you consider filing a request with Apple through developer channels to offer this feature through other browsers?

**Comment by karlcow** [comment]
See https://bugs.webkit.org/show_bug.cgi?id=243423
https://github.com/WebKit/WebKit/pull/2916
