### ISSUE TITLE
Google search favion shows even if we visit to a website

### ISSUE THREAD

**Issue by mMARUF** [mozilla-mobile/firefox-ios#9584]
### Steps to reproduce
1) Open Firefox beta v95 (6899) in iPhone using TestFlight
2) Visit any website(not any seach term)

### Expected behavior
If we are visiting a website, then the favicon of that particular site should load. Or, the favicon generic website (earth icon) should load. And, if we are trying to search something, only then the default search engine favicon should load.

### Actual behavior
Though we are clearly visiting a website, not going to search for something, the favicon of google search stays. 

### Device name
iPhone SE 2020

### IOS version
15.1

### Firefox release type
Firefox Beta

### Firefox version
Mozilla/5.0 (iPhone; CPU iPhone OS 15_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) FxiOS/95  Mobile/15E148 Safari/605.1.15

### Window Size
375X547

### Screenshot
![favicon wrong](https://user-images.githubusercontent.com/45368054/144478708-9e07b920-6a24-41f7-a0a1-6112bf7256cb.PNG)

![favicon wrong 2](https://user-images.githubusercontent.com/45368054/144478974-f5a29064-7503-49e5-a79c-e510355cff0c.PNG)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3484)

**Comment by dnarcese** [comment]
This is intended behaviour. The favicon shows the search engine that would be used if you were to start a new search.
