### ISSUE TITLE
[Bug / Improvement] - Start at home is creating and selecting new tab when opening a link from any other app

### ISSUE THREAD

**Issue by nbhasin2** [mozilla-mobile/firefox-ios#9585]
- Pre Req: Make sure Firefox is your default browser and you are on latest v40
- Let the iOS FIrefox app be in background for few hrs 
- Open a new website from Messages or Mail 

Expected
- The website opened via messages should be selected 

Actual
- Website opens in the background tab in Firefox iOS and a new home tab is selected

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3485)

**Comment by willkg** [comment]
I have this problem with using the camera on a QR code and opening it in Firefox. Instead of opening the site, I get the new tab page and I have to go back to my camera and scan the QR code again.

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verified fix on v40.2 (7139). The new tab no longer opens after +4 hours of inactivity when opening a link from external app or scanning a QR code with the device camera.
