### ISSUE TITLE
Removal of non-compliant search engines

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#9591]
Firefox BD and Legal report that there are 55 search engines made available in various locales on Firefox iOS that are not compliant with our current contracts. These search engines should be removed to avoid legal risks.

A list of these engines can be found [here](https://docs.google.com/spreadsheets/d/1lO3qkbpMzhU7NxXPffZ93T7-7W0SSFxJTJwsHNqBu-s/edit?usp=sharing) (listed in red)

The volume of traffic on non-compliant search engines on Firefox iOS can be found [here](https://sql.telemetry.mozilla.org/queries/83127#205988).

In order to remove these engines, the following steps should be taken:

* Remove engines from list.json
* Remove any related XML files

Mike Kaply was on point for Engineering during the audit process and should be able to provide clarification where needed.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3491)

**Comment by flodolo** [comment]
I strongly suggest to also review the URLs for the remaining search engines, comparing them to Firefox desktop.

We used to have scripts syncing mobile (at least Firefox for Android) and desktop products, but they were probably run once or twice, then abandoned.

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Hello, does this issue needs any QA verification? 
If yes, can anyone help with what exactly needs to be checked and how?

Best regards,
Andrei

**Comment by data-sync-user** [comment]
➤ Nishant Patel commented:

Andrei Bodea I can help with that. 

This work affects what browsers are available to view when typing in a search query (but not executing) in the URLBar for a given locale. 

I tested following steps here, https://github.com/mozilla-mobile/firefox-ios/pull/9820 ( https://github.com/mozilla-mobile/firefox-ios/pull/9820|smart-link ) .

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Tested on iPhone 12 Pro (15.2). Moving to done as none of the search engines are visible on the release version 97.0 (7635) or on the latest main 9000 (8116). 
Test results can be found here.
