### ISSUE TITLE
Firefox not showing in Settings/Notifications

### ISSUE THREAD

**Issue by DanielAlcon** [mozilla-mobile/firefox-ios#9598]
## Steps to reproduce
Open Settings app in the device, go to Notifications, search for Firefox

### Expected behavior
Firefox should appear to setup the notifications

### Actual behavior
Firefox is not shown on the list of apps inside Notifications

### Device & build information
* Device: iphone 13 mini - iOS 15.1.1
* Build version: Firefox Daylight 39.0 (6519)
    1. Notes
Attachments: 
![photo](https://user-images.githubusercontent.com/18684096/145004428-c933f27f-cd48-4b4e-9496-355204f8634b.jpg)UNITO-UNDERSCORE!2021-12-07!UNITO-UNDERSCORE!10-36-48!

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3496)

**Comment by dnarcese** [comment]
Firefox won't ask to send notifications until you have signed into sync. So I would expect that it will not show up here until that has happened.

**Comment by shortspecialbus** [comment]
I am signed in and I don't see it either.  Nor do I have any notification options in firefox settings.

iPad Pro 12.9" 2021
iPadOS 15.1
Firefox Daylight 40.2 (7167)

**Comment by lmarceau** [comment]
Hello! I tried signing in and I got the notification prompt for the permission like so:
![Simulator Screen Shot - iPad Pro (9 7-inch) - 2022-01-19 at 09 52 01](https://user-images.githubusercontent.com/11338480/150155713-24f34b05-6304-407c-aab3-c9c173f5393d.png)

Can you go in the OS settings, open Firefox app settings (not in the notifications section) and tell me what you see there? If you're signed in you should have the following sections:
![IMG_5472](https://user-images.githubusercontent.com/11338480/150155872-0ff44cd7-618f-412e-a988-8e31d1a864c0.PNG)
 
If not, could you try:
- Updating to the latest version of Firefox-iOS (version 96.0 is the latest available on the App Store)
- Login out of sync and sign-in again? If you never had the notification prompt asked in the app directly, you should get it when you sign in to Sync.

**Comment by shortspecialbus** [comment]
I'll give logout/login a try, but for what it's worth, here's what I have right now:

Internal to the app:
![Firefox internal settings](https://user-images.githubusercontent.com/17860292/150161196-0491a0c6-68b9-4b36-8530-4a378f5aa629.png)

And the OS level settings for the app:
![Firefox settings](https://user-images.githubusercontent.com/17860292/150161280-e1d077e7-cf91-4b2d-9e04-536c0da59643.png)

If I'm supposed to have those options, it seems likely there's a bug of some sort.  I'll report back if signing out/in repairs it, at least.

**Comment by shortspecialbus** [comment]
Signing out and back in did bring up the prompt and I now have the option showing up in the system settings as well.  So, that's at least a workaround. I feel there's still a bug of some sort that it can't be fixed without going through that process, but hopefully that at least helps!  And thanks for the suggestion!

**Comment by lmarceau** [comment]
@shortspecialbus Thanks for testing that out! Glad it fixed it for now. Although yeah it seems you encountered an issue that resulted in not getting that permission prompt. More investigation would be needed to figure out why, nothing jumped out to me while doing a quick review of the code.

**Comment by symbolboxer** [comment]
Can confirm this issue. In my case, what caused it was that I used the "Reset All Settings" feature. This revokes every notification permission for every app and hides the option in each app's Settings panel until that app requests it again. Signing out and back in also worked for me.
