### ISSUE TITLE
History - Recently closed history is not cleared

### ISSUE THREAD

**Issue by BigSamSampson** [mozilla-mobile/firefox-ios#9624]
## Steps to reproduce
1. Click on the Home icon
2. Click on the 2nd icon (Book mark,history...)
3. Click on history
4.Click on clear recent history
5. select "today"
6. go to "Recently closed"
### Expected behavior
All the data from section RECENTLY CLOSED should be deleted as well
### Actual behavior
Data from recently closed section is not deleted
### Device & build information
* Device: Apple iPhone 7 Plus - iOS 14.8.1, Wi-Fi
* Build version: Firefox daylight 39.0(6519)
### Notes
Attachments: 
![image](https://user-images.githubusercontent.com/66958331/145851870-333cd860-3d93-4fe8-a4a2-0145aea3148a.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3510)

**Comment by csuciu** [comment]
Was able to reproduce this issue on latest v40.1 build. Note that the only option that works is "Everything". The other ones are not clearing "Recently closed" section

**Comment by data-sync-user** [comment]
➤ Daniela Arcese commented:

This is happening because currently the Recently Closed list is only a list of urls, and does not have any data on when the tab was closed. For this functionality, we would need to keep track of the date closed.

**Comment by SimonBasca** [comment]
Verifying as fix on v100.1 (9338).
