### ISSUE TITLE
Reading list - Loading of saved to reading list page never ends

### ISSUE THREAD

**Issue by BigSamSampson** [mozilla-mobile/firefox-ios#9625]
## Steps to reproduce
1. Open firefox browser
2. Go to turna.com site
3. Scroll down the page
4. Tap on Terms and conditions
5. Tap on 3 dots menu at the top right corner
6. Tap add to reading list
7. Tap Homepage icon
8. Tap Book icon
9. Tap on Reading List bookmark
10. Tap on saved page
### Expected behavior
Saved to Reading list page opens
### Actual behavior
Despite the “Loading page…” message is shown the page didn’t load
### Device & build information
* Device: Apple iPhone XR - iOS 15.1, Wi-Fi
* Build version: Daylight 39.0(6519)
### Notes
Attachments: 
![image](https://user-images.githubusercontent.com/66958331/145881223-f60afd96-e8e9-4900-a4ca-d3e8ec96f1be.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3512)

**Comment by dnarcese** [comment]
Duplicate #9429
