### ISSUE TITLE
Settings - Page items are not visible after selecting

### ISSUE THREAD

**Issue by BigSamSampson** [mozilla-mobile/firefox-ios#9626]
## Steps to reproduce
Precondition: browser theme is set to the dark mode
1. Open the firefox browser
2. Tap on the settings icon
3. Tap on 'Data Management'
4. Tap on 'Web Site Data'
5. Select the items
### Expected behavior
Page elements should be visible after selected
### Actual behavior
1. Selection circles are not shown in dark mode
2. Selected items are not visible
### Device & build information
* Device: Apple iPhone 6S - iOS 15, Wi-Fi
* Build version: Firefox Daylight 39.0(6519)
### Notes
Attachments: 
![image](https://user-images.githubusercontent.com/66958331/145885127-5093a49a-77a0-465a-aff0-13206b6cd08e.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3513)

**Comment by SimonBasca** [comment]
This issue is no longer reproducible on v9000 (21167) or v106 (20813). It was possibly fixed by https://github.com/mozilla-mobile/firefox-ios/issues/11825. Please re-open if it's still an issue on your side.
