### ISSUE TITLE
Add metric to know how many tabs users have on their device

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#9627]
Following issue [#9604](https://github.com/mozilla-mobile/firefox-ios/issues/9604), it would be great to have a way to know the number of tabs our users have opened. This would help us know how the application is used, and how efficient tab management needs to be, particularly when it comes to tabs restoration. How much users has the infinite number of tabs icon? How big is actually the infinite number of tabs for our users? 150? 200? 300? More? And how many users has that much tabs opened?

There's currently a cumulative tabs count `cumulative_count` already implemented, but it doesn't help us to answer those particular questions.

This could be done using the Glean [Quantity type](https://mozilla.github.io/glean/book/reference/metrics/quantity.html).

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3514)

**Comment by SimonBasca** [comment]
The metric ping to display the number of tabs is working correctly except for the scenario [here](https://github.com/mozilla-mobile/firefox-ios/issues/10294).

@lmarceau I'm moving this one to QA verified. Feel free to close #10294 if you don't consider it a proper use case.

**Comment by data-sync-user** [comment]
➤ Nishant Patel commented:

Andrei Bodea We’re not able to see events from this metric on Looker, https://mozilla.cloud.looker.com/explore/firefox_ios/metrics?qid=xfMhphKo4tqvSbOtROABZs&toggle=vis ( https://mozilla.cloud.looker.com/explore/firefox_ios/metrics?qid=xfMhphKo4tqvSbOtROABZs&toggle=vis ). 

But from app side, I can see that the event is definitely getting fired. Could you verify if this event is getting reported? The event fires when a user backgrounds the app. 

Verifying this will help us answer questions from https://mozilla-hub.atlassian.net/browse/FXIOS-6673 ( https://mozilla-hub.atlassian.net/browse/FXIOS-6673|smart-link ) . 

CC Daniela Arcese

**Comment by data-sync-user** [comment]
➤ Daniela Arcese commented:

I reached out to data science and the looker chart was just using the wrong channel - I can see the data now. We can use those metrics. Can you verify whether it counts inactive tabs as normal

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Hello, Daniela ArceseI did some research here are my findings:

   "labeled_counter": {
      "firefox_home_page.firefox_homepage_origin": {
        "zero-search": 1
      },
      "glean.validation.pings_submitted": {
        "baseline": 8,
        "events": 5,
        "metrics": 1
      },
      "tabs.open": {
        "normal-tab": 1
      },
      "top_sites.pressed_tile_origin": {
        "zero-search": 1
      }
    },
    "quantity": {
      "tabs.normal_tabs_quantity": 6,
      "tabs.private_tabs_quantity": 2 As you can see above tabs quantity is 6, in that moment I had 5 inactive tabs and 1 normal tab open. If this is the way we can check what you asked for, then I do believe the inactive tabs count as normal. Here you can see the event in the glean dashboard ( https://glean-debug-view-dev-237806.firebaseapp.com/pings/Shamy21/72c3edab-2840-4832-97b3-fa55aa4e0acc ).

Please note that I used the debug option in the app to set inactive tabs after 15 seconds, this is the only way to test it fast and not wait 2 weeks, I prefer to avoid changing the device data because that messes up everything.

If there is any information on how to check exactly the quantity I can test it in more detail but it would help a lot to have the string I need to look for.
