### ISSUE TITLE
Graphics do not load on ANY Website

### ISSUE THREAD

**Issue by BRUQWBMROWQURBMWQOURBMQWRBUOWQM** [mozilla-mobile/firefox-ios#9629]
## Steps to reproduce
I did nothing for this to happen - woke up to this issue

### Expected behavior
To see Icons/SVGS/PNGs/JPGs/GIFs etc etc etc - basically to see all graphics 

### Actual behavior
No graphics are loading or being processed - as seen in the screenshots I just did

### Device & build information
* Device: Iphone Se2020
* Build version: Latest version
### Notes
Attachments: 
![IMG_0702](https://user-images.githubusercontent.com/96113007/145971877-587af07c-c680-4750-86cf-3aa3cd683b63.PNG)
![IMG_0703](https://user-images.githubusercontent.com/96113007/1459
![IMG_0704](https://user-images.githubusercontent.com/96113007/145971902-db501281-590e-4105-b7d1-ab3cddca205b.PNG)
71889-e7080983-a790-4618-afe0-10556f6aeaae.PNG)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3516)

**Comment by SimonBasca** [comment]
@BRUQWBMROWQURBMWQOURBMQWRBUOWQM could you please tap on the hamburger menu and check if the "Block Images" is enabled? Also does refreshing the page or re-opening the app fixes the issue?

**Comment by BRUQWBMROWQURBMWQOURBMQWRBUOWQM** [comment]
> @BRUQWBMROWQURBMWQOURBMQWRBUOWQM could you please tap on the hamburger menu and check if the "Block Images" is enabled? Also does refreshing the page or re-opening the app fixes the issue?

Thanks . This actually fixxed this issue. I must've hit this by accident. I feel like it makes sense to add some type of indication/ pop up that gives the users some type of feedback that this feature is enabled. I know Firefox is very dev-oriented, but I'm sure the majority of users are not devs who will not use this feature. Just a suggestion for the UX-Team @ Firefox

**Comment by SimonBasca** [comment]
I've added a feature request to improve visibility and closing the issue in favor of https://github.com/mozilla-mobile/firefox-ios/issues/8885
