### ISSUE TITLE
[XCUITest] Create automated test to check Customize Homescreen feature

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/firefox-ios#9639]
There is a [manual test](https://testrail.stage.mozaws.net/index.php?/cases/view/1548138) part of the smoketest that would be nice to have automated

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3528)

**Comment by kaansariveli** [comment]
Is it possible to share the scenario steps? I don't have access to testrail or jira

**Comment by isabelrios** [comment]
Sure @kaansariveli, these are the manual steps that we would like to have covered:
|#|Step | Expected |
| ----------- | ----------- | ----------- |
|1 | Open a New Tab. | A New tab is opened.
2 | Scroll at the bottom of the page. | The page is scrolled.
3 | Tap on the "Customize Homepage" | The user is taken to the Homepage settings.

Happy to help you write the automated test if you are interested in so. Thank you!

**Comment by isabelrios** [comment]
Closed by previous PR
