### ISSUE TITLE
[Glean]"Browser_search.ad_clicks" is not recorded correctly for Google and DuckDuckGo

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#9646]
## Steps to reproduce
1. Have "Google" or "DuckDuckGo" set as default search engine
2. In the URL bar type "nike"
3. Tap on one of the ads 
4. Go to glean dashboard and check the metrics ping
### Expected behavior
- "Browser_search.ad_clicks" should be recorded after tapping on a ad.
### Actual behavior
- "Browser_search.ad_clicks" should is not recorded after tapping on a ad.
### Device & build information
* Device: iPhone Xr (15.1)
* Build version: latest main 9000(7083)
### Notes
- Note that the "Browser_search.ad_clicks" is recorded for "Google" and DuckDuckGo" in the following case:
1. Have "Google" or "DuckDuckGo" set as default search engine
2. In the URL bar type "nike"
3. Long press on a ad
4. From the long press context menu tap "open in new tab" 

Might be related to 
https://mozilla-hub.atlassian.net/browse/FXIOS-3431
https://mozilla-hub.atlassian.net/browse/FXIOS-3430

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3531)

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

This issue was no longer reproducible after https://mozilla-hub.atlassian.net/browse/FXIOS-3431 ( https://mozilla-hub.atlassian.net/browse/FXIOS-3431|smart-link )  was fixed.
