### ISSUE TITLE
[Crash] Firefox crashes when tapping on an item from the "Jump in" section

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#9650]
## Steps to reproduce
1. Enable "Jump in" section
2. Visit "amazon.com"
3. Open a new tab
4. Open Tab Tray
5. Close the "amazon.com" tab
6. Tap on the newly opened tab
7. Scroll to the "Jump in" Section 
8. Tap on "Amazon.com" title
### Expected behavior
- Jump in section should be correctly updated
### Actual behavior
- Firefox crashes.
### Device & build information
* Device: iPhone Xr (15.1)
* Build version: main fb4aceb17aaefa61f
### Notes
Attachments: 

https://user-images.githubusercontent.com/32130829/146414013-118a6881-f532-4c35-9f04-0ada5427d33e.mp4
[Client-2021-12-17-184636.ips.zip](https://github.com/mozilla-mobile/firefox-ios/files/7729056/Client-2021-12-17-184636.ips.zip)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3533)

**Comment by lmarceau** [comment]
Good catch @SimonBasca! Seems like a regression indeed. I'll have a look thanks a lot!

**Comment by SimonBasca** [comment]
Verified fix on main 02047ef01d28e2205e2ecdf16d56497132e4fda6
