### ISSUE TITLE
[Bug] - Jump back in section (incorrect tile) after close all tabs

### ISSUE THREAD

**Issue by nbhasin2** [mozilla-mobile/firefox-ios#9652]
## Steps to reproduce

- Open Firefox iOS 
- Go to any website (Ex: mozilla.org) 
- Open a new Home Tab 
- At this point you should see the jump back in section to have the website you opened (Ex: mozilla.org)
- Open tab tray and close all tabs

### Expected behavior

- Jump back section should not have any website as none of the tabs are opened 

### Actual behavior

- Jump back in section has the website which doesn't load properly (see attached video)

### Device & build information
- Device: iPhone 11 pro
- Build version: 40.1 (7037)

### Notes
Attachments: 

https://user-images.githubusercontent.com/8919439/146443421-d5f719b7-a1b2-44bf-b8d8-7d2331c93840.MP4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3534)

**Comment by lmarceau** [comment]
@nbhasin2 That was fixed with PR https://github.com/mozilla-mobile/firefox-ios/pull/9651 for issue https://github.com/mozilla-mobile/firefox-ios/issues/9650
