### ISSUE TITLE
Opening links after 4 hours of inactivity

### ISSUE THREAD

**Issue by bentsionmp** [mozilla-mobile/firefox-ios#9654]
This issue was noticed by me right after the update to Firefox 40.0
When the feature of opening a new tab after 4 hours of inactivity was introduced.
Because it was just released I hoped it would be noticed by many and therefore get fixed on the next update, but unfortunately version 40.1 came out with the same issue.

**The issue:**
_Note: this issue is only a concern if Firefox is the default browser on the iOS device._

When 4 hours of inactivity feature is turned on the feature works quite well when entering the browser directly, but when 4 hours of inactivity have past and clicking on a outside link (say from any app) it would open it in the browser but a new empty tab would open on top (due to the feature being active) and it would look like the link was never opened, which is very inconvenient.

Personally I think that there should be a difference in when to activate that feature and when not to activate it, or at least consider the new link opening as a "new tab".

Hope this gets fixed on the next update.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3535)

**Comment by SimonBasca** [comment]
Confirming that this is an issue on v40.1 (7073).

**Comment by lmarceau** [comment]
Thanks for reporting. Closing this for now since reported in https://github.com/mozilla-mobile/firefox-ios/issues/9585.
