### ISSUE TITLE
Switching to normal browsing from private browsing by pressing ⇧ ⌘ N

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#9655]
## Steps to reproduce
1. Launch Firefox in Normal Browsing
2. Press ⇧ ⌘ P  
3. Press ⇧ ⌘ N to switch to normal browsing
### Expected behavior
- User should be able to switch to normal browsing by pressing  ⇧ ⌘ N
### Actual behavior
- In both cases from step 3) a new private tab is opened.
### Device & build information
* Device: iPad air 3 (15.1)
* Build version: 02047ef01
### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3536)

**Comment by lmarceau** [comment]
@SimonBasca I looked at the code and it was specifically implemented that way. Wondering if this is a bug since it's also the same behavior in the desktop browser. What do you think?

**Comment by SimonBasca** [comment]
@lmarceau on desktop we have a different shortcut for switching to normal browsing from private browsing by pressing "⇧ ⌘ N" which is not working in Firefox iOS. I think we should implement this.

**Comment by SimonBasca** [comment]
I've edited the bug description and title. Let me know what you think @lmarceau.

**Comment by lmarceau** [comment]
Cool! Then this would be a call to make by @dnarcese if we want this behavior in the app 😄 Thanks @SimonBasca

**Comment by dnarcese** [comment]
I am good with the behaviour where ⇧ ⌘ N would always open a new normal tab and ⇧ ⌘ P would always open a new private tab

**Comment by lmarceau** [comment]
@SimonBasca just to confirm, if we implement ⇧ ⌘ N that always open a new normal tab, this means that https://github.com/mozilla-mobile/firefox-ios/issues/9656 will be obsolete correct?

**Comment by SimonBasca** [comment]
@lmarceau confirming that implementing ⇧ ⌘ N that always open a new normal tab and ⇧ ⌘ P would always open a new private tab will make https://github.com/mozilla-mobile/firefox-ios/issues/9656 obsolete. I will close https://github.com/mozilla-mobile/firefox-ios/issues/9656.

**Comment by SimonBasca** [comment]
@dnarcese I'm totally fine with this change but was wondering since this change is different form the design docs here: https://www.figma.com/file/4Vlr0idCIGQE3r9I1FnkRn/Keyboard-Shortcuts?node-id=2%3A7, should we make this change aware to someone from UX or do you think that's not necessary?

**Comment by dnarcese** [comment]
@SimonBasca i'll just make a comment on the Figma

**Comment by dnarcese** [comment]
Let's make the menu 
New Tab ⌘ T or ⇧ ⌘ N
New Private Tab ⇧ ⌘ P

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verified fix on main 627116c214d9d74bb5a391f59999cd4eb1f68eee. 

  * Pressing ⌘ T opens a new tab in the current browsing session
  * Pressing ⇧ ⌘ P will always open a new private tab
  * Pressing ⇧ ⌘ N will always open a new tab in normal browsing.
