### ISSUE TITLE
⇧ ⌘ N should open a new private tab and it doesn't

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#9656]
## Steps to reproduce
1. Press ⇧ ⌘ N
### Expected behavior
- A new private tab should be opened as mentioned in the designs https://www.figma.com/file/4Vlr0idCIGQE3r9I1FnkRn/Keyboard-Shortcuts?node-id=711%3A224
### Actual behavior
- Pressing ⇧ ⌘ N does not have any behavoiur.
### Device & build information
* Device: iPad air 3 (15.1)
* Build version: 02047ef0
### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3537)

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verified fix on main 552d8a8
