### ISSUE TITLE
Opening a Private Tab via widget after +4 hours opens a Normal tab

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#9668]
## Steps to reproduce
1. Let the iOS FIrefox app be in background for +4 hrs 
2. Open a Private Tab via 3DT Widget, Today Widget or iOS 14 Widgets
### Expected behavior
- A New Private Tab should be opened.
### Actual behavior
- A New Normal Tab is opened.
### Device & build information
* Device: iPhone Xr 15.1
* Build version: 40.2
### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3544)

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verified fix on main 228b77b9a89f133417cb748fcf720fb01e6b6f1a

**Comment by SimonBasca** [comment]
Verified fix on 98.0 (8023).
