### ISSUE TITLE
Overlay can’t be dismissed on the home page

### ISSUE THREAD

**Issue by lmarceau** [mozilla-mobile/firefox-ios#9669]
## Steps to reproduce
1. Fresh install with jump back in enabled
2. Do a search for pizza
3. Open a new tab from this search
4. QUICKLY open the tab tray before the overlay with the purple explanation shows
5. Dismiss the tab tray and observe the overlay not being dismissed

https://user-images.githubusercontent.com/11338480/146791794-303c60e4-bcbe-49d7-9d14-27316e6eda40.mp4

### Expected behavior
Overlay should be dismissed

### Actual behavior
Overlay is there and we can't interact with the home page

### Device & build information
* Device: Simulator iPhone 11 iOS 15.0
* Build version: Latest main branch 43b09c80e620f2d01369380872dc41620e99fe53

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3545)

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verified fix on main 1e73ca749
