### ISSUE TITLE
What's new page is broken for v40.2

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#9670]
## Steps to reproduce
1. Open the Hamburger menu
2. Tap on "What's new"
### Expected behavior
- Updates for v40 should be displayed.
### Actual behavior
- The page is missing.
### Device & build information
* Device: iPhone Xr 15.1
* Build version: 40.2
### Notes
- Also missing on the release version from app store.
Attachments: 
![Picture_2021_12_20T15_42_51_212Z](https://user-images.githubusercontent.com/32130829/146793960-3f80d407-178b-421e-9251-5c6f11722f51.jpeg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3546)

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

The What’s new page is working and updated correctly in the latest version 40.3 (7161)
