### ISSUE TITLE
German release notes (first line) is cut off, mixed with first item in list below

### ISSUE THREAD

**Issue by jezdez** [mozilla-mobile/firefox-ios#9688]
## Steps to reproduce
Update to recent Firefox with the Apple AppStore app

### Expected behavior
German translation of the release notes doesn't contain typos/mangling 

### Actual behavior
For some reason the first few characters of the release notes are moved to the first item in the list included in the release notes (see screenshot)

### Device & build information
* Device: iPad mini 5
* Build version: 40.2
### Notes
Attachments: 
![image](https://user-images.githubusercontent.com/1610/146991473-7e7bb0c2-88a1-4e83-8c3d-d92582426d10.jpeg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3554)

**Comment by lmarceau** [comment]
@jezdez 
So correct text would:

> Willkommen bei einer neuen Version von Firefox [...]
> - Auf des StartSeit sind in USA und Kanada [...]

Or is there any other typos that you see?

**Comment by jezdez** [comment]
> @jezdez So correct text would be:
> 
> > Willkommen bei einer neuen Version von Firefox [...]
> > 
> > * Auf des StartSeit sind in USA und Kanada [...]
> 
> Or is there any other typos that you see?

Yep, and I could swear I saw this exact error in past release notes.
