### ISSUE TITLE
Question regarding customizing firefox-ios app

### ISSUE THREAD

**Issue by mks11** [mozilla-mobile/firefox-ios#9700]
Hi,

I am tasked with creating a customized version of the browser that can have the functionality provided with a third party extension pre-installed. 

I see a folder that says 'firefox-ios/Extensions/'. Should that be my starting point? Is there any documentation on how to makes sense of it? Thank you so much!

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3562)

**Comment by lmarceau** [comment]
Hi @mks11,
Our Extensions folder contains among other things the TodayViewController and the ShareViewController which are app extensions using [NSExtensionPrincipalClass](https://developer.apple.com/documentation/bundleresources/information_property_list/nsextension/nsextensionprincipalclass). I'm not sure this is what you're currently referring to when you say "extension"?

Do you mean like an ad block extension? Or something else?

**Comment by mks11** [comment]
@lmarceau  yeah I mean to support some features out of the box in the browser. I think ad-block extension is a good example.

**Comment by mks11** [comment]
@st3fan do you have a take? thanks a bunch!

**Comment by mks11** [comment]
@lmarceau is this achievable?

**Comment by lmarceau** [comment]
Hello @mks11, 
Safari now has Web Extensions (the same you can install on Firefox Android and Firefox Desktop) but unfortunately those cannot work in custom browsers on iOS - Apple has not made those APIs available for WKWebView. We could build "extensions" in the app, but they would need to be part of the product itself.
