### ISSUE TITLE
"Pull to refresh" improvements

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#9701]
### User Problem
From comment https://github.com/mozilla-mobile/firefox-ios/issues/9118#issuecomment-999681834 it seems that some user might accidentally refresh the page while on a login form which can cause a bad user experience.

### Ideas for Solution
We could add a button to disable this option or we should improve the way this feature works.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3563)

**Comment by gutley** [comment]
Personally I can see no difference between FF and Safari in this. Not sure this warrants any changes. We 'could' run some JS before pull to refresh kicks in to see if there are any non-empty text fields on the page and offer the choice on whether to refresh, but I'm not convinced this needs another preferences option.

**Comment by shttrstckak** [comment]
Just a note as a user I am actually going to stop using Firefox iOS because this happens quite frequently, especially when scrolling back up to proof read long messages it will trigger. It is not worth the frustration of losing lengthy work typed on a virtual keyboard with two thumbs.

**Comment by Prurite** [comment]
Just tested on ipad. The page starts refreshing immediately when pulled beyond a certain distance, which may be quite undesirable if it was triggered accidentally. Changing it to **refresh on release** (as many other browsers do) will be better, as if the user realizes that (s)he has pulled too far, (s)he can pull back and stay.

**Comment by sryze** [comment]
Yes please, I too would like to be able to disable this "feature" because it often gets triggered when I don't expect, e.g. when I scroll up on YouTube and it accidentally refreshes, I lose the recommendations. I prefer to use the Refresh button manually.

**Comment by ocontant** [comment]
The pull to refresh is the most undesirable features of modern mobile browser.

The implementation fail the basic UX principle: 
- Unpredictability (it triggers involuntarily, based on invisible to the user treshold) 
- No Trigger Validation, with a way to revert back
- In forms, this is a destructive event, and there's no confirmation action. 
- No toggle button to disable it.

Sometime a form will take 80% of the screen and you need to scroll to see referential context hidden by the form, and trying to scroll up will trigger involuntarily the refresh.


Is there a plan to fix this, or provide a toggle button, or even a plugin?

**Comment by ghost** [comment]
The option of disabling this feature does not exist yet: #27092.
