### ISSUE TITLE
javascript is not working only in FF ios

### ISSUE THREAD

**Issue by chang-joon-won** [mozilla-mobile/firefox-ios#9703]
![07478A47-AF7C-405E-BCE0-FD6087006BD4](https://user-images.githubusercontent.com/19295445/147514647-d76d07d5-44b1-4c23-96f6-30e6e5de8b70.png)

above screenshot.
link is https://kdfs.jams.or.kr/co/com/EgovMenu.kci?s_url=/sj/search/sjSereClasList.kci&s_MenuId=MENU-000000000053000

sorry for korean.
in 2008 & 2007 item. down link javascript is not working only in FF for ios. chrome, edge is well.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3564)

**Comment by lmarceau** [comment]
@chang-joon-won I'm not sure to understand, are you saying download isn't working when the following icon is clicked 
![Screen Shot 2022-01-14 at 5 52 33 PM](https://user-images.githubusercontent.com/11338480/149595514-04618d8b-92b6-4001-936f-c1a68269ee6d.png)
 Or when the download all button is clicked?
![Screen Shot 2022-01-14 at 5 53 45 PM](https://user-images.githubusercontent.com/11338480/149595643-a81ffa64-699f-4a47-91ec-f419534c02f0.png)
