### ISSUE TITLE
Could Not Build on Xcode 13.2.1

### ISSUE THREAD

**Issue by muhasturk** [mozilla-mobile/firefox-ios#9713]
## Steps to reproduce

- Download Xcode 13.2.1
- `git pull`
- `sh bootstrap.sh`

### Expected behavior
> ***  Skipped installing application-services binary due to the error:
	"Incompatible Swift version - framework was built with 5.5.1 (swiftlang-1300.0.31.4 clang-1300.0.29.6) and the local version is 5.5.2 (swiftlang-1300.0.47.5 clang-1300.0.29.30)."

### Actual behavior
Build without error.

### Device & build information
macOS 11.5.2 (20G95)

### Notes
> swift-driver version: 1.26.21 Apple Swift version 5.5.2 (swiftlang-1300.0.47.5 clang-1300.0.29.30)
Target: x86_64-apple-macosx11.0

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3571)

**Comment by electricRGB** [comment]
We currently do not support Swift 5.5.2 or Xcode 13.2.1; an update to make this work should come.... soonish.

**Comment by lmarceau** [comment]
There's a PR that was opened [in A~S](https://github.com/mozilla/application-services/pull/4757) to support 13.2.1; Once that is merged we'll need another in Firefox-iOS to update A~S, Bitrise and other necessities, then we should be good to support 13.2.1.

**Comment by lmarceau** [comment]
Closing this, we can use 13.2.1 now since SPM branch was merged!
