### ISSUE TITLE
Some tab titles are not displayed in the search suggestions list

### ISSUE THREAD

**Issue by csuciu** [mozilla-mobile/firefox-ios#9716]
v96.0(7210)

After upgrading from the previous build I noticed that some Tab titles are not showing up in the search suggestion list. 

Please check the screenshot:

![Skype](https://user-images.githubusercontent.com/1866605/147928903-e6f6b2bf-2327-4161-826e-304d641ddb96.jpeg)UNITO-UNDERSCORE!Picture!UNITO-UNDERSCORE!2022!UNITO-UNDERSCORE!01!UNITO-UNDERSCORE!03T12!UNITO-UNDERSCORE!10!UNITO-UNDERSCORE!26!UNITO-UNDERSCORE!899Z!

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3573)

**Comment by dnarcese** [comment]
@csuciu are the same tabs also missing titles in the tabs tray?
