### ISSUE TITLE
Tabs misbehave after closing and rearranging tabs

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#9717]
## Steps to reproduce
1. Open four tabs: tab1, tab2, tab3, tab4
2. Open tabs tray
3. Close tab4
4. Move tab3 in 1st position -> Tab4 is displayed although it was closed
5. Tap on tab4 -> the tab appears black
6. Open tabs tray -> Tab selector is missing
### Actual behavior
- Tabs misbehave after closing and rearranging tabs. Also experienced app crash while closing and re-arranging tabs.
### Device & build information
* Device: iPhone 12 Pro (15.1)
* Build version: 40.3(7161) and 96.0 (7210) 
### Notes
- This can also lead to app crash.
Attachments: 
[Client-2022-01-03-161537.ips.zip](https://github.com/mozilla-mobile/firefox-ios/files/7802413/Client-2022-01-03-161537.ips.zip)
https://user-images.githubusercontent.com/32130829/147942380-e17ceca9-b08c-49a2-9994-b51f0d9117b9.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3574)

**Comment by nishant2718** [comment]
This issue was fixed as part of this PR: https://github.com/mozilla-mobile/firefox-ios/pull/9719.

**Comment by SimonBasca** [comment]
Verified fix on v96.0 (7278).
