### ISSUE TITLE
Setup sync server results in an empty Mozilla account login webpage

### ISSUE THREAD

**Issue by MichiFr** [mozilla-mobile/firefox-ios#9718]
## Steps to 
Set up sync server using Firefox Daylight 40.2 (7167) on iOS 15.2
After being ask to authenticate one can choose between scanning a QR code on webpage stable.dev.lcip.org/pair or proceed with using an email address
Using the webpage given above, results in an nginx server error. When trying to authenticate, with the second option, using an existing email address, I get an empty webpage in a popup (when using the starting to sync by FF menu item) or in a newly opening webpage (when called from within the FF preferences)
Both actions result in not being able to set up the sync server. No matter if I use Mozilla’s default server or my self-hosted in a docker container, providing my own URI (after envoking  the debug mode)

### Expected behavior
Getting Redirected to proper login page https://accounts.firefox.com/ to confirm my account and to finally set up the sync server.

### Actual behavior
An empty webpage with no content and no chance to login to my Mozilla account. OTH no chance to scan any QR code.

### Device & build information
* Device: iPad Pro 12.9, Running iOS 15.2
* Build version: Firefox Daylight 40.2 (7167) on iOS 15.2 from Apple store
    1. Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3575)

**Comment by dnarcese** [comment]
@MichiFr Are you able to provide a screen recording or screenshots of this issue?

**Comment by MichiFr** [comment]
Hi Daniela!

While trying to record a video of this issue, I again tested the custom sync server settings and de-activated the appropriate switch in advanced sync settings.

After this step, I re-tried to authenticate, using my Mozilla account from within the appearing popup. This process now worked like a charm. I did not enter my e-mail address and did not continue the authentication process. Anyway, the popup showed some content and was allowed to enter my credentials.

So, next try was to re-enabled my custom sync server and the issue about an empty authentication popup came back.

I will now try to record this, but will use a non existing sync server URI to not expose my private one if this is OK for you?

cu,
Michael

**Comment by MichiFr** [comment]
Here you go...
The first attempt is using no custom sync server, which will result in a properly displayed webpage BUT the content is visible only after enforcing some refresh of the webpage by doing some magic with two fingers and swiping around a little bit.

After enabling the custom sync server again (the URI does not exist!) I don’t get any webpage content. Please note that when re-entering my URL again, this does not change the game. My URL works as I’m using it on Android as well as on my Windows PCs for synchronizing bookmarks and more.

I had to upload the vid elsewhere, because of its size…
https://share.icloud.com/photos/0e58O4xkBXzQJAFPbXmNnZpFg

cu,
Michael

**Comment by MichiFr** [comment]
So still this does not work with own sync server URL. Guess Mozilla does not want us to use self-hosted sync servers?
At least this setup works with the desktop version of Firefox.

Right now I'm using Safari or iCabMobile on my iPad for this annoying issue and will stick with them.

**Comment by TWDickson** [comment]
It's still not working for me on Firefox 108.0 (23855) and the latest iOS 16.1.2 (20B110). My sync server does work on the desktop editions.

**Comment by mikeziri** [comment]
Still not working on version 110.
I set a custom Sync Token Server. Turn the checkbox on. Go back to the Sync and Save Data and when trying to login using email or scan pairing it gives me a blank login page as others mentioned.

If you turn off the Sync Token Server checkbox, it then shows the login page.
This is only on iOS. On desktop works fine.
