### ISSUE TITLE
ga-IE - Irish is not fully localized 

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#9722]
## Steps to reproduce
1. Change preferred language to ga-IE - Irish
2. Open Firefox main 63892e77b8016c2 and check the language
### Expected behavior
- Firefox should be fully localized 
### Actual behavior
- Firefox is not fully localized for ga-IE - Irish
### Device & build information
* Device: iPhone Xr (15.1)
* Build version: main 63892e77b8016c2
### Notes
Attachments: 
![image](https://user-images.githubusercontent.com/32130829/148207676-d45422f8-0293-4d24-8289-d9f9ffa5fec0.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3581)

**Comment by nishant2718** [comment]
I think this is expected. 

<img width="1021" alt="image" src="https://user-images.githubusercontent.com/36939381/148234616-0d5b5fbf-6a26-47a2-9382-d28b67a445c5.png">

I checked [Pontoon](https://pontoon.mozilla.org/teams/) and it looks like ga-IE is at 55% localization.

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Closing this issue as this is expected. The localization is fully implemented.
