### ISSUE TITLE
zgh - Tamazight localization is missing 

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#9723]
## Steps to reproduce
1. Change preferred language to zgh - Tamazight
2. Open Firefox main 63892e77b8016c2 and check the language
### Expected behavior
- Firefox should be localized 
### Actual behavior
- Firefox is not localized for zgh - Tamazight
### Device & build information
* Device: iPhone Xr (15.1)
* Build version: main 63892e77b8016c2
### Notes
Attachments: 
https://user-images.githubusercontent.com/32130829/148208157-f71692b0-3ca2-419c-be5a-6ac68792a509.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3580)

**Comment by nishant2718** [comment]
This might be expected for zgh as well. 

<img width="1034" alt="image" src="https://user-images.githubusercontent.com/36939381/148234850-0b93330f-14e1-4bb9-9e02-820abd164ad2.png">


Some languages aren't fully localized, and you can check those on [Pontoon](https://pontoon.mozilla.org/teams/).

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Nishant Patel I checked the localization here https://pontoon.mozilla.org/zgh/firefox-for-ios/firefox-ios.xliff/?string=220032 ( https://pontoon.mozilla.org/zgh/firefox-for-ios/firefox-ios.xliff/?string=220032 ). It seems that this is not fully localized but it should contain some strings that have localization. 

E.g. “Share link” from the context menu.

!image-20220106-110812.png|width=414,height=896!

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verified fix on 98.0 (8153)

**Comment by data-sync-user** [comment]
➤ Daniela Arcese commented:

Let’s remove zgh for 98 until we can figure out why Apple is rejecting our builds with it.
