### ISSUE TITLE
[iPad] Website shortcuts title overlap

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#9724]
## Steps to reproduce
1. Launch Firefox in portrait
2. Log in to FxA that contain website shortcuts with long titles
### Expected behavior
- Website shortcuts title should  not overlap
### Actual behavior
- The websites shortcut titles overlap
### Device & build information
* Device: iPad Air 2 2nd generation (15.1)
* Build version: 96.0 (7278)
### Notes
- Reproducible on devices with display of 9.7 inch and lower.
Attachments: 
![screenshot](https://user-images.githubusercontent.com/32130829/148230431-5b3c3864-d01a-4eb4-9102-aaf07d6a641c.jpeg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3582)

**Comment by dnarcese** [comment]
The issue here is how many sites are showing up per row. In portrait, there should only be 6, allowing more room for titles.

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verified fix on v96.0 (7298)
