### ISSUE TITLE
[Regression] [iPad] Re-arranging tabs in tabs tray is not reflected in Top Tabs

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#9725]
## Steps to reproduce
1. Open a tab and load a website (website1)
2. Open a second tab and load a website (website2)
3. Open Tabs Tray
4. Long press on "website1" and move it in the position of "website2"
5. Tap on a website to dismiss Tabs Tray
### Expected behavior
- After re-arranging the tabs in tabs tray, the change should be correctly reflected in Top Tabs
### Actual behavior
- After re-arranging the tabs in tabs tray, the change is not correctly reflected in Top Tabs
### Device & build information
* Device: iPad Pro 4th gen (14.4)
* Build version: 96.0 (7278)
### Notes
Attachments:

https://user-images.githubusercontent.com/32130829/148247763-6797005b-1a03-4a85-91ee-9ceeec599b83.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3584)

**Comment by SimonBasca** [comment]
This issue was previously fix in https://github.com/mozilla-mobile/firefox-ios/issues/8358.

**Comment by lmarceau** [comment]
@SimonBasca Does this relates to https://github.com/mozilla-mobile/firefox-ios/issues/9333 ? Just so we keep only one open maybe.

**Comment by SimonBasca** [comment]
@lmarceau this is the same as #9333 . Closing as duplicate, sorry for the confusion.
