### ISSUE TITLE
[Experiment] There websites added to the "Reading List" are not displayed in the "Recently Saved" section from the homepage

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla-mobile/firefox-ios#9726]
**[Prerequisites]:**
- Have a build that can access Nimbus experiments from Prod Preview.

**[Steps to reproduce]:**
1. Start the Firefox App and open the "Settings" menu.
2. Scroll down the page and tap the "Firefox Daylight 40.2" string 5 times.
3. Scroll down the page and tap the "Experiments" option.
4. Tap the "Edit" button and toggle the "Use Preview Collection" option.
5. Fully close and reopen the app.
6. Navigate back to the "Experiments" menu and tap the "Edit" button.
7. Tap the "Reset" button and tap the "Back" button.
8. Tap the "All Users HomeScreen iOS Production 100% Rollout" entry and check the "Control" branch.
9. Open a new tab and navigate to any website.
10. Tap the "Three dots" menu button and select the "Add to Reading List" option.
11. Open a new tab and observe the displayed sections.

**[Expected result]:**
- The following sections are displayed:
  - "Shortcuts"
  - "Jump Back In"
  - "Recently Saved"
  - "Recommended by Pocket"
  
**[Actual result]:**
- The "Recently Saved" section is not displayed at all.

**[Device & build information]:**
- Device: iPhone 11 - iOS 14.7.1
- Device: iPhone 6s - iOS 15.2
- Build version: Firefox Daylight 40.2 (7167)

**[Notes]:**
- If the profile has Bookmarks entries, then the "Recently Saved" section is displayed but the websites that were added to the "Reading List" are not present in the section.
- This issue is still reproducible after a browser restart.
- This issue is not reproducible on the Firefox Daylight 39.0 (6519).
- Attached a screen recording of the issue.

https://user-images.githubusercontent.com/31243259/148246812-32046805-c573-4cf4-b5e8-4bb3633757eb.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3583)

**Comment by data-sync-user** [comment]
➤ Daniela Arcese commented:

I was able to reproduce on prod v40.2 but not on beta v9000(7286)

**Comment by athomasmoz** [comment]
Is this reproducible with "All Users HomeScreen iOS Production" as well? (ie. the currently running experiment)

**Comment by Softvision-MariusComan** [comment]
Hi, @athomasmoz! I have tested this issue using the latest Firefox Daylight 40.2 (7167) installed on iPhone 6s - iOS 15.2 and I can confirm that the issue is reproducible with the "All Users HomeScreen iOS Production" experiment as well.
If you need any extra information please don't hesitate to ping me.

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

This issue is no longer reproducible on v99.0 (8654) and v9000 (8617)
