### ISSUE TITLE
Inconsistent behavior of "Jump back in" when switching between normal and private browsing

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#9729]
## Steps to reproduce
1. Open a few sites so that the "jump back in" section is displayed.
2. Switch to Private Browsing - > "jump back in" section is displayed in private browsing
3. Visit a page in Private Browsing
4. Open a new private tab -> "jump back in" section is not displayed in private browsing
5. Return to normal browsing -> "jump back in" section is not displayed in normal browsing
### Expected behavior
- My opinion is that we should no show the "jump in" section in private browsing.
### Actual behavior
- The behavior is inconsistent. 
### Device & build information
* Device: iPad Air 2 (15.1) and iPhone Xr (15.1)
* Build version: 96.0 (7278)
### Notes
Attachments: 

https://user-images.githubusercontent.com/32130829/148382895-9c163edb-4317-40f4-acb4-6cd2f923c522.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3587)

**Comment by data-sync-user** [comment]
➤ Daniela Arcese commented:

Let’s go with the suggestion of hiding Jump Back In whenever the user is in Private browsing mode.

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Laurie Marceau I am still seeing an issue here after following STR. See https://mozilla-hub.atlassian.net/browse/FXIOS-3762 ( https://mozilla-hub.atlassian.net/browse/FXIOS-3762|smart-link )
