### ISSUE TITLE
[iOS14]"CMD+" does not zoom in

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#9732]
## Steps to reproduce
1. Visit a page
2. Press "CMD+" to zoom in
### Expected behavior
- The page view should zoom in.
### Actual behavior
- The page view does not zoom in. 
### Device & build information
* Device: iPad Pro 14.8 
* Build version: 96.0 (7278)
### Notes
- "CMD -" is functional. The page zooms out.
- "CMD 0 " is functional. The page zooms to actual size.
- The issue is not reproducible on iOS 15.x
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3590)

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verified fix on main b44274ce1c06269f9bc3c1ab95b6724383a20404.
