### ISSUE TITLE
- [ ] [[@](https://discord.gg/jb)](https://discord.gg/jb)

### ISSUE THREAD

**Issue by gottoouu** [mozilla-mobile/firefox-ios#9736]
- [ ] [[@](https://discord.gg/jb)](https://discord.gg/jb)

__Originally posted by @gottoouu in https://github.com/GliaX/tourniquet/pull/2#issuecomment-1008322714__

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3592)

**Comment by lmarceau** [comment]
Hi @gottoouu, 
It seems you posted a discord invite? I'll close this for now since no other information is provided.
