### ISSUE TITLE
[Tab groups]Tabs are added to the wrong group after searching for different terms in the same tab

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#9741]
## Steps to reproduce
1. Enable tab groups 
2. Open a new tab and search for "nike"
3. Long press on a link and open in a new tab
4. Long press on a different link and open in a new tab
5. In the tab that was search for "nike", search for "puma" -> the tab is removed from the group
6. Long press on a link and open in a new tab
### Expected behavior
- The tab from step 6) should be in a new group.
### Actual behavior
- The tab from step 6) is added to the "nike" group.
### Device & build information
* Device: iPhone Xr (15.1)
* Build version: a3362e72675e9c2386afbbb594d96b9d027b3fbd
### Notes
Attachments: 
https://user-images.githubusercontent.com/32130829/148761771-53d04247-7720-4f65-bff7-0e16e77d3196.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3596)

**Comment by dnarcese** [comment]
@SimonBasca when you searched "puma", was it from the URL bar or from the google search page?

**Comment by lmarceau** [comment]
@SimonBasca does this relates to https://github.com/mozilla-mobile/firefox-ios/issues/9672 ?

**Comment by SimonBasca** [comment]
> @SimonBasca when you searched "puma", was it from the URL bar or from the google search page?
It was from the google search page.

@lmarceau I think it's the same issue as #9672. Let's close this one in favor of #9672
