### ISSUE TITLE
Instagram - Codes appears on top of the page after refreshing it

### ISSUE THREAD

**Issue by BigSamSampson** [mozilla-mobile/firefox-ios#9744]
## Steps to reproduce
1. Open firefox browser
1. Tap on add
1. Tap on +
4.Tap on Instagram Shortcut
5.Tap on Comment button
6.Refresh page
7.Tap on the back button
    1. Expected behavior
I expect not to get any code messages or unnecessary messages on the top part of the page
    1. Actual behavior
There is code messages at the top part of the page and doesn’t disappear after tapping the back button
    1. Device & build information

* Device: Apple iPhone 8 Plus - iOS 14.8
* Build version: firefox daylight 40.2(7167)

https://user-images.githubusercontent.com/66958331/148811989-492fa7e7-039b-4202-a445-18747541b34a.mp4

![image](https://user-images.githubusercontent.com/66958331/148812040-eadc24d3-84b4-4a37-ae45-fe9580095eb2.png)

### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3599)

**Comment by dnarcese** [comment]
@BigSamSampson what is your tracking protection set to? Does turning it off fix this?
