### ISSUE TITLE
Bookmarks - The browser layout is broken after holding the link and rotating the screen.

### ISSUE THREAD

**Issue by BigSamSampson** [mozilla-mobile/firefox-ios#9746]
## Steps to reproduce
1. Open the firefox browser
2. Tap on the Bookmarks button
3. Hold any link
4. Rotate the screen
5. Continue using the browser
### Expected behavior
The browser works as expected.
### Actual behavior
The browser layout is broken.
### Device & build information
* Device: Apple iPhone 11 - iOS 15.1
* Build version: firefox daylight 40.2(7167)

https://user-images.githubusercontent.com/66958331/148820822-b71bf4a9-c2ab-4c69-bdd1-28a00d8a828c.mp4

### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3601)

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verified fix on main f841cd0f34fb8f0ba3cf3da8b12e53d174c7432a.
