### ISSUE TITLE
Settings - Save button will be inactive if tapping without filling in the Search Engine fields.

### ISSUE THREAD

**Issue by BigSamSampson** [mozilla-mobile/firefox-ios#9754]
## Steps to reproduce
1. Open the firefox browser
2. Open the Settings screen
3. Tap "Search"
4. Tap "Add Search Engine"
5. Tap "Save"
6. Fill in all the fields
7. Tap "Save"
### Expected behavior
When tapping on "Save" button when the fields are empty, a message will appear that the fields are empty. After filling in all the fields, "Save" button will be active.
### Actual behavior
When tapping "Save" button when the fields are empty, "Save" button becomes inactive. After filling in all the fields, "Save" button is still inactive, tapping on it does nothing.
### Device & build information
* Device: Apple iPhone 11 - iOS 15.1
* Build version: firefox daylight 40.2(7167)
### Notes
Attachments: 

https://user-images.githubusercontent.com/66958331/148895096-ae2dc95a-8757-42a1-8d40-29c38e60def2.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3605)

**Comment by abodea** [comment]
Hi @BigSamSampson, I have a question regarding this as I'm trying to verify it.
Please note that I tried on the latest 9000 (main build) and when I reach the Search and then add search engine section, the save button is not grayed out.
When I tap on the Save button I have no prompt informing me that the fields are empty as you mentioned in the description.

Can you please give more details that might help with the verification of this bug?

**Comment by abodea** [comment]
Based on my comment below I will hold on the QA Verification.
@junbio is there a possibility to clarify the questions from above?
When entering in the Add Search engine the `back` button should be grayed out and when tapping on it to receive a prompt informing the user that no data is added?

**Comment by junbio** [comment]
>When entering in the Add Search engine the back button should be grayed out and when tapping on it to receive a prompt informing the user that no data is added?

Those were 2 possible solutions to the issue. But showing an error message would require new localization strings and disabling the button would be too much work. Simply failing silently is the fastest solution.

**Comment by lmarceau** [comment]
@dnarcese what do you think is best between the two options?

## Option 1:
Maybe we could reuse the same error message that we currently have? It would not require new strings. 
![IMG_5493](https://user-images.githubusercontent.com/11338480/151461232-82f1427f-2afc-4934-a5b1-7a388e4ab0af.PNG)
Worst case we can add new strings next time we do the update. In the meantime we still have a working fix, but it would be ideal indeed to have an error message if that button is enabled.
 
## Option 2:
Other option is to only make the Save button enabled when there's content inside the two textfields. The two textfields already conforms to UITextViewDelegate, with a `settingDidChange` closure when `textViewDidChange` is called. Maybe it would be best to have a closure in `shouldChangeTextInRange`, but then following the same logic it shouldn't be too hard to do that option 2.

**Comment by dnarcese** [comment]
@lmarceau I prefer option 2

**Comment by lmarceau** [comment]
@junbio Would you mind having a look to do option 2? Let me know if you need anything :)

**Comment by junbio** [comment]
Thanks, just opened a PR implementing option #2.

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verified fix on main 228b77b9a89f133417cb748fcf720fb01e6b6f1a

**Comment by lmarceau** [comment]
With latest PR behavior is as option 2 discussed up here. This looks like this:

https://user-images.githubusercontent.com/11338480/152891907-7bae1351-84fa-4377-859e-54d30c8fbe05.mp4

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Re-testing on iPhone 12 Pro (15.2) on main a9d1f4e090a7d0b62e1d89c588de87c35cc8ca66.
The Save button enabled when there's content inside the two textfields.
