### ISSUE TITLE
Theme - Taping on the "Manually" option switches the theme.

### ISSUE THREAD

**Issue by BigSamSampson** [mozilla-mobile/firefox-ios#9758]
## Steps to reproduce
1. Open the firefox browser
2. Open the Settings screen
3. Tap "Theme"
4. Turn off the "Use System Light/Dark mode" switch
5. Tap the "Manually" option
### Expected behavior
The option is selected, no more changes are made.
### Actual behavior
The option is selected and the theme was switched.
### Device & build information
* Device: Apple iPhone 11 - iOS 15.1
* Build version: firefox daylight 40.2(7167)

https://user-images.githubusercontent.com/66958331/148959455-c2124661-2d1a-43dd-a954-6cf2d6844c9e.mp4

### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3609)

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verified fix on main 48a92ef8b2c158a9758617d84cca2ee5d44d2dbc.
