### ISSUE TITLE
[Investigation] Bookmarks: Remove redundant or dead code in the browser schema

### ISSUE THREAD

**Issue by lougeniaC64** [mozilla-mobile/firefox-ios#9760]
Find areas on where to remove reduntant or dead code and based on that make a follow-up ticket.

Since bookmarks are synced via the AppServices sync method, it's not clear that the bookmark tables in [Storage/SQL/BrowserSchema.swift](https://github.com/mozilla-mobile/firefox-ios/blob/0dab728a700df53fe5b9883d697a13ad59e1252e/Storage/SQL/BrowserSchema.swift) are still useful. To resolve this, the tables and views in this file should be reviewed and any redundant or unnecessary code should be removed.

**Note:** The browser db tables might be necessary as long as the [bookmarks migration](https://github.com/mozilla-mobile/firefox-ios/blob/c1ff689e461c238d82c3d8600ced8c0863d4b419/Storage/Rust/RustPlaces.swift#L123) is around.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3611)

**Comment by data-sync-user** [comment]
➤ Orla Mitchell commented:

This is blocked for the moment until the sync manager work from AS is rolled out. Context in the comments of this PR https://github.com/mozilla-mobile/firefox-ios/pull/14405 ( https://github.com/mozilla-mobile/firefox-ios/pull/14405|smart-link )
