### ISSUE TITLE
Failed to extract MozillaRustComponents.xcframework.zip

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/firefox-ios#9765]
A clean checkout of the `spm` branch gives me the following error when Xcode bring the SPM dependencies up to date:

> fatalError: failed extracting 'https://125513-129966583-gh.circle-artifacts.com/0/dist/MozillaRustComponents.xcframework.zip' which is required by binary target 'MozillaRustComponents': /Users/sarentz/Library/Developer/Xcode/DerivedData/Client-ccfiyfdswuakzzclvczxupjmjmcy/SourcePackages/artifacts/extract/MozillaRustComponents is not a directory

I don't understand what is going on here - when I look at the path it complains about, it does exist and it is a directory.

Could this be a problem with how the MozillaRustComponents dependency is structured?

See also  #9766 which may or may not be related.

cc @skhamis

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3614)

**Comment by skhamis** [comment]
This definitely is a SPM bug when using binary artifacts -- I believe some of these issues go away in XCode 13.2 and I can move some of the weird mozilla rust components wrapper that was needed to prevent the binary from not downloading in time:

https://developer.apple.com/documentation/xcode-release-notes/xcode-13_2-release-notes
>Resolved an issue where Swift packages with binary targets sometimes failed with a “no such module” error when attempting to import the module of a binary target. (77465707)
