### ISSUE TITLE
Dependencies could not be resolved because no versions of 'swift-protobuf' match the requirement

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/firefox-ios#9766]
When I checkout the `spm` branch, the very first thing Xcode tries to do is to _Resolve Package Dependencies_. This process fails with the following error:

> Dependencies could not be resolved because no versions of 'swift-protobuf' match the requirement 1.18.0 and root depends on 'swift-protobuf' 1.18.0.

A minute later, Xcode tries again and then the error does not appear, but resolving dependencies fails with #9765 - unclear if this is related or not.

cc @skhamis

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3615)

**Comment by data-sync-user** [comment]
➤ Nishant Bhasin commented:

All dependencies should now be moved to SPM

**Comment by data-sync-user** [comment]
➤ Nishant Bhasin commented:

We still need to add mappa mundi to support tests but that will have its own ticket
