### ISSUE TITLE
Incremental compilation has been disabled: it is not compatible with whole module optimization

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/firefox-ios#9767]
There is a note in the build logs that says:

> Incremental compilation has been disabled: it is not compatible with whole module optimization

This is worth exploring because incremental compilation can speed up builds considerably. In the past we had to mess with the _Whole Module Optimization_ options to work around bugs in earlier versions of Swift. Maybe these options can be changed back to their defaults so that we gain _incremental compilation_.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3616)

**Comment by data-sync-user** [comment]
➤ Nishant Bhasin commented:

We have enabled it back for Firefox iOS so we should be able to close this
