### ISSUE TITLE
Fix NSKeyedUnarchiver deprecation warnings in SiteArchiver with SavedTabs

### ISSUE THREAD

**Issue by lmarceau** [mozilla-mobile/firefox-ios#9770]
A PR was made to fix the deprecation warnings [here](https://github.com/mozilla-mobile/firefox-ios/pull/9699), but this introduced a regression where tab were not restored after the app was killed and reopened. The PR was reverted [here](https://github.com/mozilla-mobile/firefox-ios/pull/9769). This means archiving/unarchiving isn't working as it should. Migration maybe also needs to be checked at for old tabs.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3619)

**Comment by lmarceau** [comment]
This concerns warnings in:
- SiteArchiver.swift `let unarchiver = try NSKeyedUnarchiver(forReadingWith: tabData)`

Might also have to look into warning:
- TabManagerStore.swift `let archiver = NSKeyedArchiver(forWritingWith: tabStateData)`

**Comment by lmarceau** [comment]
For QA, it can be tested that:
- Forward migration works: Having tabs on a prior version (before 6a0b5048121eb1690d82fa2b13235af817857e67) and going to 6a0b5048121eb1690d82fa2b13235af817857e67 or a more recent commit on `main`, all tabs are migrated properly and works fine (ex: private and normal tabs, etc)
- Backwards migration works: Having tabs on 6a0b5048121eb1690d82fa2b13235af817857e67 or a more recent commit on `main` and going to a version older than 6a0b5048121eb1690d82fa2b13235af817857e67 then all tabs are migrated properly and works fine.
- All tabs action are the same (creating tabs, moving tabs, restoring tabs with a new app session, restoring tabs from background).

**Comment by SimonBasca** [comment]
Tested by :
Case 1 - Forward migration
Checking out at commit previous commit 6a0b5048121eb1690d82fa2b13235af817857e67, 
- opening / closing normal and private tabs 
- Visiting pages
- Closing the browser and re-opening
- Leave a few tabs opened with some pages loaded

Upgrading to latest commit a07825b122cc5f6b63a77606fcdaca6a65f220cf
- Open tabs tray and checking if the tabs previously opened are correctly displayed

Case 2
From latest commit a07825b122cc5f6b63a77606fcdaca6a65f220cf
- opening / closing normal and private tabs 
- Visiting pages
- Closing the browser and re-opening
- Leave a few tabs opened with some pages loaded

Install over previous 6a0b5048121eb1690d82fa2b13235af817857e67, 
- Open tabs tray and checking if the normal and private tabs previously opened are correctly displayed displayed

Case 3
- checkout on latest main a07825b122cc5f6b63a77606fcdaca6a65f220cf -> open a few tabs
- checkout on previous commit 6a0b5048121eb1690d82fa2b13235af817857e67 -> the tabs are still open and displayed correctly
- checkout on main a07825b122cc5f6b63a77606fcdaca6a65f220cf -> tabs are no longer displayed.

@lmarceau Note that case 3) loses the tabs. Let me know if case 3) is expected or it's something that needs to be fix.

**Comment by lmarceau** [comment]
@SimonBasca did you also try going to and from a commit older than https://github.com/mozilla-mobile/firefox-ios/commit/6a0b5048121eb1690d82fa2b13235af817857e67 ? For example, dac6202d7204560bed3e27e1c9197e1144e104e7? 

About your case 3, I'm not sure I understand what would go wrong there as between https://github.com/mozilla-mobile/firefox-ios/commit/6a0b5048121eb1690d82fa2b13235af817857e67 and https://github.com/mozilla-mobile/firefox-ios/commit/a07825b122cc5f6b63a77606fcdaca6a65f220cf the tabs changes are the same. I tried reproducing the issue and couldn't yet.

**Comment by SimonBasca** [comment]
@lmarceau confirming that cases 1) and 2) are working as expected testing also with commit https://github.com/mozilla-mobile/firefox-ios/commit/dac6202d7204560bed3e27e1c9197e1144e104e7, however for case 3) I have some updates.

It seems that after:
1. Install a07825b122cc5f6b63a77606fcdaca6a65f220cf
2. Open a few tabs normal and private
3. install https://github.com/mozilla-mobile/firefox-ios/commit/dac6202d7204560bed3e27e1c9197e1144e104e7 over previous build
4. Open 2 new tabs (my case Twitter and Youtube)
5. Install a07825b122cc5f6b63a77606fcdaca6a65f220cf over previous build
Actual results
- The tabs opened at step 4) were lost

**Comment by lmarceau** [comment]
@SimonBasca we shouldn't have to support this usecase. It's the equivalent of installing a build v106.1, reverting to a previous v106.0 build, then going again to the same inital v106.1. What we want to make sure is that we can support v106 to v105, back and forth (hence why testing that we can go back and forth from https://github.com/mozilla-mobile/firefox-ios/commit/dac6202d7204560bed3e27e1c9197e1144e104e7 to latest main and back)

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Thanks Laurie if case 3 is not a valid case, I will mark the issue as verified fix on 3eeb2b3047ed551e5ea14ba92a34486273d9d94a and v106.0 (19594)

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Marking as fixed on v106.0 (19965). No tab issues were encountered while testing v106 (19965) or when upgrading from v105.1 (19787) to 106 (19965)
