### ISSUE TITLE
History cells shrink in height after first scrolling in the list.

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#9774]
## Steps to reproduce
1. Go to History
2. Scroll in the panel
### Expected behavior
- History cells should
### Actual behavior
- History cells shrink in height after first scrolling in the list.
### Device & build information
* Device: iPhone 12 Pro 15.2
* Build version: 96.0 and latest main f841cd0f34fb8f0ba3cf3da8b12e53d174c7432a
### Notes
Attachments: 

https://user-images.githubusercontent.com/32130829/149343876-a0a866e8-a0b5-4fd9-8561-75d3eee3721e.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3620)

**Comment by junbio** [comment]
In TwoLineViewCellFooter.swift, there are two sets of conflicting height constraints being added: 58 in initialViewSetup
https://github.com/mozilla-mobile/firefox-ios/blob/d08e1fbc678604f3e90f7b4565c3c46a1f7ade74/Client/Frontend/Widgets/TwoLineCellAndFooter.swift#L83

and 55 in layoutSubviews.
https://github.com/mozilla-mobile/firefox-ios/blob/d08e1fbc678604f3e90f7b4565c3c46a1f7ade74/Client/Frontend/Widgets/TwoLineCellAndFooter.swift#L149
Which one is the correct height?

**Comment by dnarcese** [comment]
@junbio lets go with 58

**Comment by csuciu** [comment]
Verifying as fixed on v97.0 (7635)
