### ISSUE TITLE
Update Pocket strings

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#9779]
The Pocket title should be updated to "Thought-Provoking Stories" and the "More" tile should say "Discover more"

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3623)

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verified fix on main 06c6d822e9c6a611bc25ec32fcf0be012d109f18.

**Comment by nishant2718** [comment]
QAed, and closing.
