### ISSUE TITLE
Refactor Top Sites

### ISSUE THREAD

**Issue by lmarceau** [mozilla-mobile/firefox-ios#9783]
FirefoxHomeViewController and Top Sites improvement to have a standardized structure and better separation of concern.

Requirements:

* Top Sites sections has it's own view model and related section code is encapsulated
* Data loading is not in FirefoxHomeViewController
* Use same structure as other sections that uses viewModel (Pocket, JumpBackIn, etc.)
* A TileManager exists that supports existing Top Sites logic - In preparation for #10125
* Unit tests for TileManager & viewModel

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3626)

**Comment by data-sync-user** [comment]
➤ Laurie Marceau commented:

For QA: we should test that top sites are still as before (no behavior change)

**Comment by data-sync-user** [comment]
➤ Laurie Marceau commented:

Note: Found one issue that reload of data doesn’t happen with contextual menu. Will be fixed in https://mozilla-hub.atlassian.net/browse/FXIOS-3832 ( https://mozilla-hub.atlassian.net/browse/FXIOS-3832|smart-link ) this sprint.

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Tested on main cd20fc4afd9 and v99.0 (8544). No behavioral change was noted on top sites and all functionalities work as expected.

Note: 

  * We’ve logged an improvement for a corner case scenario : https://github.com/mozilla-mobile/firefox-ios/issues/10289 ( https://github.com/mozilla-mobile/firefox-ios/issues/10289|smart-link ) . This behavior is also present in older versions and was not freshly introduced.
