### ISSUE TITLE
On Firefox mobile iOS when clicking “Edit Bookmarks” there is no distinction between a main folder and sub-folder

### ISSUE THREAD

**Issue by dorfli** [mozilla-mobile/firefox-ios#9789]
Is there a way to fix this? It is currently confusing, since all the folders are in a row and there is no staggering. There needs to be indentations for sub-folders.

Here is what I’m seeing that shows there is an indentations for sub folders:

https://i.redd.it/174g90o1rqa81.jpg

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3629)

**Comment by lmarceau** [comment]
Hello @dorfli, the image you linked doesn't seem to be accessible anymore. Could you please link it again on Github directly?

**Comment by lmarceau** [comment]
Actual implementation:
![image](https://user-images.githubusercontent.com/11338480/149828346-5b5db5f9-26b4-447f-9db9-b390690b89cd.png)

Suggested fix by PR: 
![image](https://user-images.githubusercontent.com/11338480/149828381-f33dd8d7-1f0e-4b76-ab3a-6056d12244c5.png)

@dnarcese I think we'll need some designers eyes on this one 👀

**Comment by dnarcese** [comment]
@topotropic what do you think of this?

**Comment by dorfli** [comment]
> @topotropic what do you think of this?

I think that suggested fix is much much better!

**Comment by lmarceau** [comment]
@dorfli Awesome 🤩 We'll be able to merge that soon then 🙏

**Comment by topotropic** [comment]
> @topotropic what do you think of this?

Yes, that makes sense. Thanks for the work @dorfli!

**Comment by abodea** [comment]
Verified as fixed on the latest **FF RC build v97 (7619)** with iPhone 13 Pro Max (15.1) and iPad mini 5 (14.1)
