### ISSUE TITLE
[XRViewer 2.0] HTTPS Page With Invalid Certificate Never Loads  

### ISSUE THREAD

**Issue by Edward-Upton** [mozilla-mobile/firefox-ios#9790]
## Steps to reproduce

Attempt to load a website using HTTPS without a valid SSL certificate.

### Expected behavior

Similar to that of the normal Firefox iOS app, where it shows a security warning.

### Actual behavior

Webpage never loads (neither the actual page nor the security warning page). It never gets past the loading page status.

### Device & build information
* Device: iPhone SE 2020
* Build version: XRViewer 2.0 (280)
### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3630)

**Comment by Creative-Ataraxia** [comment]
I'm having the same problem, anyone have a solution?

**Comment by Edward-Upton** [comment]
Never found a solution, although may be patched now (if you are using an older version)

**Comment by SimonBasca** [comment]
Thanks for the feedback. Could you please provide an URL where this issue is reproducible?

**Comment by Creative-Ataraxia** [comment]
> Never found a solution, although may be patched now (if you are using an older version)

great, how would the patching be done?
