### ISSUE TITLE
URL is not corectly displayed after visiting an article after a google search

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#9791]
## Steps to reproduce
1. Tap on the URL bar
2. Type "nike the verge" or "oppo the verge" and tap "GO"
3. Tap on the first article resulting from the search
### Expected behavior
- The URL should should be "https://www.theverge.com/2022/1/17/22887588/oppo-find-x5-leak-specs-photos-renders"
### Actual behavior
- The URL  is "google.com/amp/s/www.theverge.com/2022/1/17/22887588/oppo-find-x5-leak-specs-photos-renders"
### Device & build information
* Device: iPhone 12 Pro (15.1)
* Build version: 96.0 (7403)
### Notes
- Not reproducible with other search engines like DuckDuckGo
- Not reproducible in Safari
- Also happening on other sites when tapping on an news article resulting from a google search.
- e.g Typing "cnn russia" and visiting the link from the google search

Attachments: 

https://user-images.githubusercontent.com/32130829/149762575-3ae3a844-9fdc-4ad3-bdac-22b6eba00bda.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3631)

**Comment by nbhasin2** [comment]
@SimonBasca those are google amp pages that you get to mostly by tapping on results from google.

You can read up more about AMP here in the link below.

https://developers.google.com/amp

This is normal behaviour from google pages.

**Comment by SimonBasca** [comment]
Closing the issue based on the previous comment.
