### ISSUE TITLE
Cannot Sign in to Sync if I switch away from pairing view

### ISSUE THREAD

**Issue by dnarcese** [mozilla-mobile/firefox-ios#9807]
## Steps to reproduce
1. Make sure 2FA is enabled on your Sync account
1. In Firefox on iPhone, open Settings -> Sign in to Sync.
1. On desktop browser, navigate to "firefox.com/pair".
1. On desktop, tap "Show Code" button.
1. On iPhone, tap "Ready to Scan" button.
1. Scan QR code.
1. On iPhone, switch to authenticator app to get 2FA code to enter into prompt on desktop.
1. On iPhone, switch back to Firefox to complete setup.

### Expected behavior
Be able to finish the pairing process after switching back from the authenticator app.

### Actual behavior
I see the messages "Pairing not successful", "Unexpected error", and "The setup process was terminated." Phone does not get signed in.

### Device & build information
Firefox for iOS version: "Firefox Daylight 39.0 (6519)"
iOS version: "15.1 (10B74)"

### Notes
Attachments: 
From [https://bugzilla.mozilla.org/show_bug.cgi?id=1742316](https://bugzilla.mozilla.org/show_bug.cgi?id=1742316)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3641)

**Comment by l-hedgehog** [comment]
The error message "Unexpected error" seems to indicate it's from a WebSocket error.
https://github.com/mozilla/fxa/blob/v1.223.2/packages/fxa-content-server/app/scripts/lib/pairing-channel-client.js#L81
https://github.com/mozilla/fxa-pairing-channel/blob/v1.0.2/src/index.js#L153

**Comment by cpeterso** [comment]
I have the same problem with Firefox 96.0 (Release 7403 and TestFlight version 7278) on my iPhone 12 running iOS 15.2.1. My authenticator app (DuoMobile) is on my same iPhone, so I must switch apps to copy the auth code. Logging into FxA using my email address and password works correctly.

![image](https://user-images.githubusercontent.com/629193/150906046-45c5acde-b08b-4368-8149-b1a0d9c0137a.png)

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verified fix on main fe7143df48899790144e0a5240fd153d6a70f94a. The issue is no longer reproducible following the STR.

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verified fix on v106 (19763)

**Comment by clossmans2** [comment]
Same issue encountered here with the same steps on the following version:
Firefox 129.1 (44281)
iPhone 13 Pro - iOS 17.5.1

**Comment by cpeterso** [comment]
@clossmans2 - I tried testing Firefox 129 (on my iPhone 15 Plus and iOS 17.6.1), but I wasn't able to reproduce. When I switch away from Firefox's "Confirm pairing" screen to open my authenticator app (DuoMobile) and then switch back to Firefox, I still see the "Confirm pairing" screen and no errors.

Can you please include a screenshot of the error you encounter?
