### ISSUE TITLE
Fix UIContextMenuInteraction deprecation warnings

### ISSUE THREAD

**Issue by lmarceau** [mozilla-mobile/firefox-ios#9810]
Fix UIContextMenuInteraction deprecation warnings located in GridTabViewController. Those two deprecation warnings relates to one another.

![Screen Shot 2022-01-19 at 4 25 16 PM](https://user-images.githubusercontent.com/11338480/150216238-38d5ebab-a412-46bf-ba49-44b1c4c4c417.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3643)

**Comment by lmarceau** [comment]
Put this to be tested since the peek view will now be available for phone without 3D touch (so with a long press you can access this peek view). If you press on the tab for a short period of time you can still swap the tabs. If you press for a longer period of time then you see the peek view. The feature is only implemented on regular tabs (so not grouped tabs/inactive tabs). Doubled check with product and this was ok 👍 

Here's a video of how it looks.

https://user-images.githubusercontent.com/11338480/150596283-56a45588-250d-4a33-9e1e-85bd7988d0bd.mp4

**Comment by lmarceau** [comment]
Should test only once https://github.com/mozilla-mobile/firefox-ios/pull/9836 is merged

**Comment by lmarceau** [comment]
Reopened since needs to be tested

**Comment by lmarceau** [comment]
This will be ready to test on main since #9836 was merged 👍

**Comment by abodea** [comment]
Verified as fixed on the latest **v.97 (7635).**
Note that I verified this issue on **iPhone 13 Pro Max (15.1) and iPad mini 5 (14.1)** in both **portrait** and **landscape** mode, and it works as expected.
