### ISSUE TITLE
Fix Key window warning in TestAppDelegate

### ISSUE THREAD

**Issue by lmarceau** [mozilla-mobile/firefox-ios#9812]
Fix Key window warning in TestAppDelegate on line `defer { application.keyWindow?.layer.speed = 100.0 }`

![Screen Shot 2022-01-19 at 4 30 30 PM](https://user-images.githubusercontent.com/11338480/150216938-ea9d009a-88d4-494c-9aaf-e063f48bacd8.png)

We can probably use `UIWindow.keyWindow` for it, but needs to be tested.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3644)

**Comment by noloman** [comment]
Hi,

I can take care of this 😄 Thanks!
