### ISSUE TITLE
Fix search engine Archiving deprecations warnings

### ISSUE THREAD

**Issue by lmarceau** [mozilla-mobile/firefox-ios#9813]
Fix search engine Archiving deprecations warnings in SearchEngines.swift

![width=200,height=183](https://user-images.githubusercontent.com/11338480/150221942-c9beb62d-b051-4969-b45f-9aa2c881b04b.png)

```java
fileprivate lazy var customEngines: [OpenSearchEngine] = {
        return NSKeyedUnarchiver.unarchiveObject(withFile: self.customEngineFilePath()) as? [OpenSearchEngine] ?? []
    }()

    fileprivate func saveCustomEngines() {
        NSKeyedArchiver.archiveRootObject(customEngines, toFile: self.customEngineFilePath())
    }
```

Add unit tests

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3648)

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Laurie Marceau I noticed that this issue has a PR merged attached to it. Should we move the Jira ticket to “Done”?

**Comment by lmarceau** [comment]
@SimonBasca not yet! The PR I linked was to do some ground work to prepare for the rest of the ticket. Next time I'll create a separate ticket to make it clearer. Thanks!

**Comment by data-sync-user** [comment]
➤ Stefan Vladut commented:

for testing this it’s enough to add 1-2 custom search engines, force close the app and you should still see the search engines you’ve added, if they’re missing it’s bad

**Comment by DianaBarladeanu** [comment]
> ➤ Stefan Vladut commented:
> 
> for testing this it’s enough to add 1-2 custom search engines, force close the app and you should still see the search engines you’ve added, if they’re missing it’s bad

I tested as suggested above, no issue encountered.
