### ISSUE TITLE
Fix UIApplication.shared.statusBarFrame deprecation warning

### ISSUE THREAD

**Issue by lmarceau** [mozilla-mobile/firefox-ios#9815]
In BackForwardListViewController on line `verticalConstraints += [make.top.equalTo(self.view).offset(bvc.header.frame.height + UIApplication.shared.statusBarFrame.size.height).constraint]`

![Screen Shot 2022-01-19 at 5 03 25 PM](https://user-images.githubusercontent.com/11338480/150221390-9d45d3a9-bc09-46b3-b3f1-0b598144ab38.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3646)

**Comment by noloman** [comment]
Hi,

I think I can take care of getting rid of this warning.
How can I make sure that I'm not breaking anything? How can I test this?
Thanks!

**Comment by lmarceau** [comment]
Hi @noloman, this looks great! With both cases at bottom and up top. You can also maybe manually test that going to background and foreground works properly while having the back-forward list showing/not showing and long-pressing to show it? Just to verify the window scene activation state has no effect. 

Other than that, you can run the unit tests locally if you want before opening a PR. Thanks a lot for having a look into this issue! 🙏
