### ISSUE TITLE
Fix ChangeUserAgent Archiver deprecation warning

### ISSUE THREAD

**Issue by lmarceau** [mozilla-mobile/firefox-ios#9816]
Fix ChangeUserAgent Archiver warnings in Tab+ChangeUserAgent.swift

`if let hosts = NSKeyedUnarchiver.unarchiveObject(withFile: ChangeUserAgent.file.path) as? Set<String> {`

![width=200,height=183](https://user-images.githubusercontent.com/11338480/150221029-4a21ba78-3b3c-4033-bd49-810caa20bbd5.png)

Add unit tests

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3645)

**Comment by data-sync-user** [comment]
➤ Laurie Marceau commented:

For QA, it can be tested that changing user agent on webpages (by requesting desktop site on iPhone or mobile site on iPad) is stored properly - i.e. if we save wikipedia to be displayed as desktop version on iPhone, it will always show wikipedia in desktop version.

**Comment by DianaBarladeanu** [comment]
> ➤ Laurie Marceau commented:
> 
> For QA, it can be tested that changing user agent on webpages (by requesting desktop site on iPhone or mobile site on iPad) is stored properly - i.e. if we save wikipedia to be displayed as desktop version on iPhone, it will always show wikipedia in desktop version.

Tested as instructed above, no issues encountered.
Device: iPhone SE (15.4) Build: v9000 (32297)
