### ISSUE TITLE
The progress bar remains visible after stop loading a page

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#9828]
Steps to reproduce

1. Set network connection to "very bad network" in order to make the issue more visible
1. Visit a page e.g "github.com"
1. Tap on the "X" icon

Expected behavior

* The progress bar should not be displayed.

Actual behavior

* The progress bar remains visible.

Device & build information
Device: iPhone Xr (15.1)

Build version: main c6d17c95da56477529f3bc3a1bd0dbf50d2717a5

https://user-images.githubusercontent.com/32130829/150507131-69e5d950-8d46-40ba-880f-236c84810de1.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3654)

**Comment by lmarceau** [comment]
@SimonBasca I think this relates to https://github.com/mozilla-mobile/firefox-ios/issues/8988 ?

**Comment by SimonBasca** [comment]
@lmarceau , you're correct. It is related to #8988 but it's specific to the progress bar freezing. Feel free to close this issue if it can be fixed in the same PR.

**Comment by lmarceau** [comment]
Let's keep them open for now - let's see when this is investigated.
