### ISSUE TITLE
The page does not stop loading after tapping "X" after visiting a page from the home tab

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#9829]
Steps to reproduce

1. Set network connection to "very bad network" in order to make the issue more visible
1. Open a new tab
1. Visit a page e.g "github.com"
1. Tap on the "X" icon

Expected behavior

* The page should stop loading after tapping "X".

Actual behavior

* The page does not stop loading after tapping "X" after visiting a page from the home tab

Device & build information
Device: iPhone Xr (15.1)

Build version: main c6d17c95da56477529f3bc3a1bd0dbf50d2717a5

https://user-images.githubusercontent.com/32130829/150508114-3d47cd5b-6fa0-485c-a798-974c6da56f18.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3655)

**Comment by lmarceau** [comment]
@SimonBasca I think this relates to https://github.com/mozilla-mobile/firefox-ios/issues/8988 ?
