### ISSUE TITLE
Tabs grid view do not respect safe area in landscape on iPhone

### ISSUE THREAD

**Issue by lmarceau** [mozilla-mobile/firefox-ios#9834]
Ticket split from https://github.com/mozilla-mobile/firefox-ios/issues/9800 - Tagged with same priority.

## Steps to reproduce

1. Rotate iPhone to landscape
2. Tap tabs button

### Expected behavior

UI has margins to account for screen cutout
### Actual behavior

UI obscured by screen cutout
### Device & build information

    Device: iPhone X (iOS 15.2.1)
    Build version: Firefox Daylight 96.0 (7403)

![Screen Shot 2022-01-21 at 2 34 05 PM](https://user-images.githubusercontent.com/11338480/150593187-2310797a-3893-4836-ad20-018a05752505.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3657)

**Comment by lmarceau** [comment]
Note: with the fix from PR #9840

![Screen Shot 2022-01-25 at 11 12 49 AM](https://user-images.githubusercontent.com/11338480/151015193-37ebc3c9-9d2f-45d2-b9c0-3d7e22de2c32.png)

![Screen Shot 2022-01-25 at 11 14 24 AM](https://user-images.githubusercontent.com/11338480/151015187-e1e50b15-41c7-4123-9a49-637d53a873c7.png)

**Comment by abodea** [comment]
Verified as fixed on the latest 9000 (7670) main with iPhone 13 Pro Max (15.1).

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Verified as fixed on the latest 9000 (7670) main with iPhone 13 Pro Max (15.1).

Please note that regarding this ticket there was another one https://github.com/mozilla-mobile/firefox-ios/issues/9800 ( https://github.com/mozilla-mobile/firefox-ios/issues/9800|smart-link )  that was also verified as fixed.
