### ISSUE TITLE
Tab peek in tab tray issues

### ISSUE THREAD

**Issue by lmarceau** [mozilla-mobile/firefox-ios#9835]
- Home page shouldn't be available to add to bookmarks on tab peek
![Simulator Screen Shot - iPhone 11 - 2022-01-21 at 15 58 45](https://user-images.githubusercontent.com/11338480/150603429-1ef381de-3fa3-4709-a232-93c806ecb55c.png)

- Selecting "Close tab" should close a tab and update the tab tray count

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3658)

**Comment by csuciu** [comment]
Verifying as fixed on v97.0(7635)
