### ISSUE TITLE
Bottom Bar 

### ISSUE THREAD

**Issue by GeorgeIlias1** [mozilla-mobile/firefox-ios#9846]
On Max models it would be great for Firefox to have the search bar on bottom like the new Safari

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3664)

**Comment by lmarceau** [comment]
@GeorgeIlias1 We have a task open for this here: https://github.com/mozilla-mobile/firefox-ios/issues/9422 :)
