### ISSUE TITLE
Bookmarks folder resetting to main folder issue

### ISSUE THREAD

**Issue by lmarceau** [mozilla-mobile/firefox-ios#9856]
We received feedback from multiple sources stating that there's an issue with the bookmarks resetting to the main folder:

Slack thread: https://mozilla.slack.com/archives/CRLTUTCQK/p1643037317020700
1. > With the latest update, after selecting a bookmark from a folder, the folder reverts back to the main Bookmark page and I have to select the folder all over again.

2. > Must go through all  the bookmarks menu to get to your saved favorites every time you go to bookmarks.

3. > I’m not willing to go through multiple menus for every bookmark

4. > Why does it not remember which book mark folder I’m in?  The app defaults back out of the bookmark folder to the highest level.  Too many clicks to get where I left off. 

Is that a bug or a feature request? Let's use this ticket to investigate 🙏

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3671)

**Comment by junbio** [comment]
For what it's worth, both Safari and Chrome remember what bookmarks folder you've recently been in.

**Comment by jr-johnson-support** [comment]
Have seen related questions coming into SUMO for this. Here is an example https://support.mozilla.org/en-US/questions/1367276#answer-1482807

**Comment by jr-johnson-support** [comment]
@lmarceau I was wondering if you know whether a fix for this is landing in an upcoming release?

**Comment by lmarceau** [comment]
Not in v98 no. For priority I would ask @dnarcese

**Comment by jr-johnson-support** [comment]
👍

**Comment by jyscheng** [comment]
Hi @dnarcese
Any news on when this bug will be fixed?

I'm the guy who asked the question here:
https://support.mozilla.org/en-US/questions/1367276#answer-1482807

**Comment by dnarcese** [comment]
@jyscheng Hi, we will be getting to this in the next couple of version releases

**Comment by jyscheng** [comment]
Thanks @dnarcese for the update ... hopefully not too long of a wait.
Using Safari in the meantime, but it feels like I'm being unfaithful

**Comment by jyscheng** [comment]
@dnarcese 
Kinda disappointed that at least 2 updates afterwards, the bug is still not fixed :-(

**Comment by sgiblin1** [comment]
100 days and counting. 

Any idea when this will be fixed?

**Comment by sgiblin1** [comment]
> ➤ Simion Basca commented:
> 
> Verifying as fix on Fennec main [dff59eb](https://github.com/mozilla-mobile/firefox-ios/commit/dff59eb23d86ed77519140f41060246c969f406e). After opening a folder, the user will be take to the same folder when bookmarks panel is opened. After cold starting the app the folder will be reset to the main folder.

Nothing has been fixed.

**Comment by sgiblin1** [comment]
> @sgiblin1 Could you please tell us on which version are you?

Firefox Daylight 99.3

**Comment by lmarceau** [comment]
@sgiblin1 The fix is enclosed in version v100.1. This release is currently in progressive rollout, so to get it you need to open the Firefox for iOS app store page detail. You should see the "Update" button once the page is opened. Let us know if it works for you there!

**Comment by sgiblin1** [comment]
> @sgiblin1 The fix is enclosed in version v100.1. This release is currently in progressive rollout, so to get it you need to open the Firefox for iOS app store page detail. You should see the "Update" button once the page is opened. Let us know if it works for you there!

That did it! Thanks! Sorry, I was just checking the app update list.
