### ISSUE TITLE
Extend iOS version support or leave old versions available in AppStore

### ISSUE THREAD

**Issue by jillemash** [mozilla-mobile/firefox-ios#9864]
### User Problem
My device runs iOS 12 and is stuck with this version, since it no longer gets updates.
Although iOS 12 is not that old, I cannot use Firefox on my device, since, according to the AppStore message, iOS 13 is required.
Actually I would have liked to try Firefox Focus, to see if it would have improved my browsing experience, since this device starts to get sluggish, so it's precisely because my device is old that I want it, and not being able to get it is frustrating.

### Ideas for Solution
1. Maintain a wider range of compatible iOS version for the latest version of Firefox. But I guess this is not done because iOS (as opposed to Android) suffers from less fragmentation, and a lot of users do run the latest iOS version. So maybe it may not be worth the extra effort for a minority of user, is that it ?
2.  Keep old versions available in the AppStore. For example, I coud download Youtube, even if the latest version is not available for iOS 12, because an older version was still available to download in the AppStore. So you could keep the latest compatible version for each no-longer-supported iOS version ? Why isn't it the case ? Does it cost extra money ? Is it to ensure Firefox users run up to date versions with the latest security patches ?

Thanks.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3677)

**Comment by lmarceau** [comment]
@jillemash Even if there's the banner it's possible to download the older version of the app. You just have to click on the button and then you'll see this prompt:
![IMG_0010](https://user-images.githubusercontent.com/11338480/151210950-9a140246-1791-4c4d-bf0e-1c98f98c139e.PNG)
You can then download it and use the latest supported version on your iOS 12 device, which is version 36.0.

I'll close this issue for now, thanks!

**Comment by jillemash** [comment]
Hi,

Thanks for your quick answer.
That's interesting, so the feature is supposed to be here ?
Because, as I tried to describe, I don't get the prompt you showed, that's why I described my experience with Youtube, for which I did get this prompt.

I attached a screenshot of what I get when I click on the installation button: as opposed to what happens with Youtube, I don't have the choice of downloading an older version.

I hope you'll see this even if the ticket is now closed.

Thanks for your help.


![Firefox-iOS12-AppStore](https://user-images.githubusercontent.com/33934429/151241472-a42d843a-7302-4adc-b66a-61f648b7d905.png)

**Comment by jillemash** [comment]
Some sites suggest this ability to download the last compatible version only appears if the app has already been purchased/downloaded.
I've checked my purchase section in the App store, and indeed, YouTube appeared as downloaded a few years ago, but Firefox does not appear. (I'm primarily an Android user, I just got my hand on this old iPad, the other apps have been purchased on my even older iPod Touch 4, I guess I didn't install Firefox on this one at the time).
So the solution, according to this sites, would be to download the latest version of Firefox on a more recent iOS device (which I don't have), so that it appears in my "purchase" list, and I should be able to get the option of downloading the latest compatible version.
Can you confirm this ? If so, I guess I should address my feature request directly to Apple :). It'd be a shame I need a newer device to be able to install an app on an old device, if I have a new device, I don't need the old :(.

Thanks for your help.

**Comment by jillemash** [comment]
Ok, for anyone facing the same issue, I confirm the app must be in the purchase history to be able to download older versions.
I could get my hand on a new iOS device, I installed Firefox and Focus, and now I'm able to install the last compatible version on my old iPad mini 2.
This is very inconvenient, I'll have to do this everytime I'll need an app targeting iOS 13+, whereas a compatible version exists...

I guess that settles it (unless you have another solution for me)

Thanks for your reactivity.

**Comment by lmarceau** [comment]
@jillemash 
>So the solution, according to this sites, would be to download the latest version of Firefox on a more recent iOS device (which I don't have), so that it appears in my "purchase" list, and I should be able to get the option of downloading the latest compatible version.

Ah indeed makes sense. The screenshot I show up there is from my older iOS 12 iPhone which is on the same account as my iOS 15.0 phone. Hence I have it in my "purchase" list.

Unless I'm mistaken, this indeed seems to be an Apple thing 🤔 Not sure how we could change that. Thanks for having a look into this issue!
