### ISSUE TITLE
Remote tabs does not respect landscape safe area

### ISSUE THREAD

**Issue by junbio** [mozilla-mobile/firefox-ios#9865]
## Steps to reproduce
1. Open tabs
2. Rotate screen to landscape
3. Tap remote tabs

### Expected behavior
List of remote tabs has safe area margins

### Actual behavior
List gets cut off by screen cutout

### Device & build information
* Device: iPhone X iOS 15.2.1
* Build version: Firefox Daylight 96.0 (7403)
### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3678)

**Comment by csuciu** [comment]
Verified as fixed on v9000(7720).

**Comment by SimonBasca** [comment]
Verified fix on 98.0 (8023).
