### ISSUE TITLE
Send to Device does not respect landscape safe area

### ISSUE THREAD

**Issue by junbio** [mozilla-mobile/firefox-ios#9867]
## Prerequisite 
Must be logged in.

## Steps to reproduce
1. Open ellipsis menu in URL bar
2. Tap Send Link to Device
3. Rotate screen to landscape

### Expected behavior
Header has safe area margins

### Actual behavior
Header gets cut off by screen cutout

### Device & build information
* Device: iPhone X iOS 15.2.1
* Build version: Firefox Daylight 96.0 (7403)
### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3679)

**Comment by abodea** [comment]
Verified as fixed on the latest 9K build (7720) with iPhone 13 Pro Max (15.1).

**Comment by SimonBasca** [comment]
Verified fix on 98.0 (8023).
