### ISSUE TITLE
Empty State View for empty Reading List isn't centered

### ISSUE THREAD

**Issue by finebel** [mozilla-mobile/firefox-ios#9870]
## Steps to reproduce
Open an empty Reading List.

### Expected behavior
Empty State View should be centered.

### Actual behavior
Empty State View isn't centered (see attached screenshots).

### Device & build information
* Device: iPhone Xr
* Build version: Firefox Daylight 96.0 (7403)
### Notes
Attachments: 

![IMG_7843](https://user-images.githubusercontent.com/46824694/151242961-85bc1b0c-f32d-4b50-82fd-aff799e3a036.PNG)

![IMG_7844](https://user-images.githubusercontent.com/46824694/151242885-f226f58d-daeb-42a7-8307-d53ab3404147.PNG)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3680)

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verified fix on main a9d1f4e090a7d0b62e1d89c588de87c35cc8ca66
