### ISSUE TITLE
Send to Device has transparent navigation bar

### ISSUE THREAD

**Issue by lmarceau** [mozilla-mobile/firefox-ios#9884]
## Steps to reproduce
- Not be signed in Sync
- Go to any webpage
- Open ellipsis menu in URL bar (three dots)
- Tap Send Link to Device
- Observe page:
![Simulator Screen Shot - iPhone 11 - 2022-01-27 at 19 13 43](https://user-images.githubusercontent.com/11338480/151571628-915d5756-1206-4a4e-af39-12984ac73a52.png)

### Expected behavior
Navigation bar isn't transparent and respects Theme.

### Actual behavior
Navigation bar is transparent

### Device & build information
* Device: Simulator iOS 15.0
* Build version: Main 9c5e6d

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3688)

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Verified as fixed on the latest 9K build (7720) with iPhone 13 Pro Max (15.1)
Note that the navigation color was correctly displayed.

**Comment by SimonBasca** [comment]
Verified fix on v98.0 (8023)
