### ISSUE TITLE
Start at home bug on tabs restore

### ISSUE THREAD

**Issue by lmarceau** [mozilla-mobile/firefox-ios#9886]
## Steps to reproduce
- Trigger a tab restore ( so no tabs are present)
- Have start at home enabled
- `scanForExistingHomeTab` returns no home tab since this function is called before the restore tabs is completed
- Start at home creates a new tab

### Expected behavior
No extra home tab created

### Actual behavior
Extra home tab created since there was no tabs existing when `scanForExistingHomeTab` was called

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3689)

**Comment by lmarceau** [comment]
@dnarcese It seems there's another symptom of that bug - looks to be related, if not I guess we can create a another ticket maybe when we investigate it.

Steps:
- Have start at home enabled
- Open a website
- Kill the app
- Reopen the app
- The tab has the website title but you're on home and you can't navigate to your website. In other word, you can't access the website so the tab is useless.

https://user-images.githubusercontent.com/11338480/152819923-f20b29ff-bdae-48e2-ad47-bd3f704eecb5.MP4

Video was made on fresh install of V96

It doesn't happen every time you kill the app, but very often. Maybe it's due to the race condition?

**Comment by dnarcese** [comment]
@lmarceau I think that is this issue https://github.com/mozilla-mobile/firefox-ios/issues/9803

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verifying as fix on main 7493300c088051ed0a06d54dd5e1a6ff21cdd8a3.

After leaving the app on homepage, triggering "Start at Home"  will not create a new tab.

**Comment by SimonBasca** [comment]
Verified fix on v99.0 (8544).
