### ISSUE TITLE
# Pyre Bug

### ISSUE THREAD

**Issue by Steven9482** [mozilla-mobile/firefox-ios#9891]
# Pyre Bug

**Bug description**
The behavior of `Annotated` has been changed so that it is allowed at runtime to wrap `ClassVar` and `Final`. This change helps avoid friction with other users of annotations; see https://bugs.python.org/issue46491 for context. This change has [landed in 3.11](https://github.com/python/cpython/commit/e1abffca45b60729c460e3e2ad50c8c1946cfd4e) and has been backported to 3.9, 3.10, and `typing_extensions`. pyre should follow suit in allowing the wrapping in order to allow the friction lifting to happen in practice.

**Reproduction steps**
```python
from typing import Annotated, ClassVar, Final

class C:
    classvar: Annotated[ClassVar[int], (2, 5)] = 4
    const: Annotated[Final[int], "metadata"] = 4
```

**Expected behavior**
The above code should type check.

**Logs**
Please include any relevant logs here:

```console
antest/antest.py:4:4 Incompatible attribute type [8]: Attribute `classvar` declared in class `C` has type `typing.Annotated[ClassVar[int]]` but is used as type `int`.
antest/antest.py:5:4 Incompatible attribute type [8]: Attribute `const` declared in class `C` has type `typing.Annotated[Final[int]]` but is used as type `int`.
antest/antest.py:5:4 Invalid type [31]: Expression `typing.Annotated[Final[int]]` is not a valid type. Final cannot be nested.
```

**Additional context**
Client version: 0.9.10
Binary version: d418f5bb10fdee9648eeea3834c8ca56944bd2ce
Corresponding issue for dataclasses (incl `InitVar`) is at https://bugs.python.org/issue46511
pyright change: https://github.com/microsoft/pyright/commit/8ce7fa6e0ad883fb17407add955273bbfbe506c5
mypy bug: https://github.com/python/mypy/issues/12061
pytype bug: https://github.com/google/pytype/issues/1110

__Originally posted by @GBeauregard in https://github.com/facebook/pyre-check/issues/577__

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3692)

**Comment by lmarceau** [comment]
Closing this - This doesn't affect our repo unless I'm mistaken.
