### ISSUE TITLE
Wrong Xcode version in README.md

### ISSUE THREAD

**Issue by gutley** [mozilla-mobile/firefox-ios#9893]
The readme file in Main (and the v96.0 and v97.0) branch is wrong in saying that it works with Xcode 13.0 and Swift 5.5.

Currently Xcode 13.1 is the only version that can be used to build Firefox, alongside Swift 5.5.1.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3694)

**Comment by lmarceau** [comment]
I updated it, thanks @gutley !
