### ISSUE TITLE
Enable contributor workflow once the tests are working again after spm work

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/firefox-ios#9908]
The workflow is not running the test. Let's disable it until the build is green again
We would also need to run this only for contributors not for people in the team.

cc AaronMT

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3697)

**Comment by AaronMT** [comment]
Looks like it's disabled in actions, no code change required you can enable/disable straight from Actions if admin.

**Comment by isabelrios** [comment]
> Looks like it's disabled in actions, no code change required you can enable/disable straight from Actions if admin.

Yeah @AaronMT I did not know and learnt it yesterday. I will rename this so that we know we have to re-enable it
