### ISSUE TITLE
Disabled Unit Tests - TabManagerStoreTests

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/firefox-ios#9913]
There is [this test suite](https://github.com/mozilla-mobile/firefox-ios/blob/main/ClientTests/TabManagerStoreTests.swift) failing lately both locally and on Bitrise.
I disabled the tests so that we could  have green builds after spm work landed.
I don't think they are failing due to real bug/regression but worth checking and nice if these tests can be enabled again.

cc @lmarceau as I see you in the commit history :wink: 
Thanks!

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3699)

**Comment by lmarceau** [comment]
Stumbled on this again. This was fixed as part of [FXIOS-3619](https://mozilla-hub.atlassian.net/browse/FXIOS-3619) https://github.com/mozilla-mobile/firefox-ios/issues/9770 so I'll close it.
