### ISSUE TITLE
Unable to sign in to sync on local build

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#9914]
## Steps to reproduce
1. Build locally main dd4740af047
2. Launch the app
3. Open Settings
5. Tap Sign in to Sync
6. Select "Use email" or "Ready to scan" 
### Expected behavior
- User should be able to sign in to sync.
### Actual behavior
- Tapping "Use email" does not load the web view.
- Tapping "Ready to Scan" will allow the user to sing in but after the sign in flow, the account management button is broken and nothing is synced.
### Device & build information
* Device: main dd4740af047
* Build version: iPhone 12 Pro (15.2)
### Notes
- Sync is working on Test Flight builds.
Attachments: 
![Picture_2022_02_01T16_51_44_265Z](https://user-images.githubusercontent.com/32130829/152013212-273e9cf9-ba6b-485a-8f2d-0e9bd921336b.jpeg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3701)

**Comment by lmarceau** [comment]
@SimonBasca This relates to https://github.com/mozilla-mobile/firefox-ios/issues/9894 @nbhasin2 is currently working on resolving this 🙏

**Comment by SimonBasca** [comment]
Thanks Laurie. I'll close this one since we are tracking the work in #9894
