### ISSUE TITLE
Progress bar doesn't reset

### ISSUE THREAD

**Issue by junbio** [mozilla-mobile/firefox-ios#9915]
## Steps to reproduce
1. Visit website
2. Tap home button before page stops loading
3. Visit another website

### Expected behavior
Progress bar shows loading progress for second website

### Actual behavior
Progress bar reflects the progress of the first website before it finished loading if it was greater than the current progress

### Device & build information
* Device: iPhone X, iOS 15.3
* Build version: 96.0 (7403)
### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3702)

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verifying as fix on latest main 6b01440f6274573f010b501a7c52de6d19c72bd3. The issue is no longer reproducible following the STR

**Comment by SimonBasca** [comment]
Verifying as fix on v99.0 (8544). The issue is no longer reproducible following the STR.
