### ISSUE TITLE
VoiceOver reads wrong label for home button

### ISSUE THREAD

**Issue by junbio** [mozilla-mobile/firefox-ios#9917]
## Steps to reproduce
1. Enable VoiceOver
2. Select home button

### Expected behavior
VoiceOver reads "Home"

### Actual behavior
VoiceOver reads "Search"

### Device & build information
* Device: iPhone X (iOS 15.3)
* Build version: 96.0 (7403)
### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3703)

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verified fix on main a9d1f4e090a7d0b62e1d89c588de87c35cc8ca66.
