### ISSUE TITLE
Enhanced Tracking Protection popup does not respect screen cutout in landscape

### ISSUE THREAD

**Issue by junbio** [mozilla-mobile/firefox-ios#9919]
## Steps to reproduce
1. Navigate to site
2. Rotate screen to landscape
2. Tap lock icon
3. Tap Connection

### Expected behavior
Details popup respects screen cutout

### Actual behavior
Details overlap screen cutout

### Device & build information
* Device: iPhone X (iOS 15.3)
* Build version: 96.0 (7403)
### Notes
Attachments: 
![IMG_4259](https://user-images.githubusercontent.com/66826029/152030687-20a782ed-f63f-4c03-8049-03259af90800.PNG)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3704)

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verified fix on man 6b01440f6274573f010b501a7c52de6d19c72bd3.
