### ISSUE TITLE
Announce CFR for Voice Over users

### ISSUE THREAD

**Issue by lmarceau** [mozilla-mobile/firefox-ios#9924]
We have CFRs (contextual feature recommender) pop ups for the jump back in section and upcoming sections in the app. We should support voice over for them. When they pop over the app the context changes and we should let the user know of that. 

Our in code class for that CFR is `ContextualHintViewController`.

Apple ref: https://developer.apple.com/documentation/uikit/uiaccessibility/1615194-post && https://developer.apple.com/documentation/uikit/uiaccessibility/notification/1620176-announcement

Useful resource: https://a11y-guidelines.orange.com/en/mobile/ios/development/

Seems to be a useful thread to look at for this: https://stackoverflow.com/questions/55522345/why-is-uiaccessibility-postnotification-announcement-argument-arg-not-an

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3705)

**Comment by data-sync-user** [comment]
➤ Asa Dotzler commented:

This is an accessibility S2

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verifying as fix on main da7a6a4d1ed3630f60e307a623f3d8956e6184c3
