### ISSUE TITLE
Tacking Protection pop-up - "X" icon has incorrect theme

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#9926]
## Steps to reproduce
1. Visit a page
2. Tap on the "Lock" icon
### Expected behavior
- "X" icon has incorrect theme
### Actual behavior
- "X" icon should have  correct theme in Light theme.
### Device & build information
* Device: iPhone 12 Pro (15.2.1)
* Build version: 228b77b9a89f133417cb748fcf720fb01e6b6f1a
### Notes
Attachments: 
![screenshot](https://user-images.githubusercontent.com/32130829/152154895-15beb826-6c3d-45f6-8073-ab19df08de18.jpeg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3706)

**Comment by data-sync-user** [comment]
➤ Daniela Arcese commented:

Colours should follow design: https://www.figma.com/file/epu0Sj6mCPk7K282sNpHgI/Site?node-id=1478%3A6856 ( https://www.figma.com/file/epu0Sj6mCPk7K282sNpHgI/Site?node-id=1478%3A6856|smart-link )

**Comment by lmarceau** [comment]
@KrisRJack Here is what I got from figma for the button.

### Light
<img width="236" alt="Screen Shot 2022-06-22 at 9 57 51 AM" src="https://user-images.githubusercontent.com/11338480/175047486-97f31245-422a-4878-b631-d4007a144e73.png">

### Dark
<img width="237" alt="Screen Shot 2022-06-22 at 9 57 44 AM" src="https://user-images.githubusercontent.com/11338480/175047491-f9013952-1288-4e96-9e95-25aba8bcd5af.png">
