### ISSUE TITLE
Firefox-ios does not build on Intel and M1 - MacOS11 and MacOS12 with Xcode 13.2.1

### ISSUE THREAD

**Issue by ruchigupta19** [mozilla-mobile/firefox-ios#9931]
Hi there,
I have been trying to build firefox-ios on MacOS11 and MacOS12 on Intel and M1 machine with python3.6.8 and on both the arch platforms I am getting the following error while building the project using 
**`xcodebuild -project Client.xcodeproj -scheme Fennec CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO`**

could not find the commit 1f1aba21157b0da730a5f3c7029bfca448cbec5e in https://github.com/skhamis/rust-components-swiftxcodebuild: error: Could not resolve package dependencies: could not find the commit 1f1aba21157b0da730a5f3c7029bfca448cbec5e in https://github.com/skhamis/rust-components-swift

I even tried searching for that commit in skhamis/rust-components-swift but couldn't find anything. Can anyone help, please?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3708)

**Comment by lmarceau** [comment]
Hey @ruchigupta19, thanks for filing the issue! We experienced that problem too on some levels and are looking to solve it. We'll keep you posted as soon as we know more.

**Comment by lmarceau** [comment]
@ruchigupta19 Should be fixed with the linked PR here 🙏Thanks!
