### ISSUE TITLE
Login management UI does not stretch all the way in landscape on iPhone 

### ISSUE THREAD

**Issue by junbio** [mozilla-mobile/firefox-ios#9937]
## Steps to reproduce
1. Open menu button
2. Tap Passwords
3. Rotate phone to landscape

### Expected behavior
Cells stretch all the way

### Actual behavior
Cells have visible margins

### Device & build information
* Device: iPhone X (iOS 15.3)
* Build version: 96.0 (7403)

### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3711)

**Comment by jatinbishla** [comment]
I want to contribute in this issue
Can you please tell me, how?

**Comment by lmarceau** [comment]
Before:
![IMG_5583](https://user-images.githubusercontent.com/11338480/156453484-751867e7-a019-48a8-8978-729c812f6171.PNG)

After:
![IMG_5584](https://user-images.githubusercontent.com/11338480/156455238-9ebd80d1-d6b7-46af-b300-7a9788e77954.PNG)

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verified fix on v9000 (8617)
