### ISSUE TITLE
I can't build firefox using Xcode 13.2.1 on the main branch

### ISSUE THREAD

**Issue by pchandak1408** [mozilla-mobile/firefox-ios#9939]
Hi I checkout out branch branch & try build Fennec using xocdebuild with Xcode version 13.2.1 But I always get this below error in main branch as well -

> - nested: MozillaRustComponentsWrapper.framework
> Moving nested frameworks from Shared.framework/Frameworks/ to Client.app/Frameworks/
> - nested: SDWebImage.framework
> - nested: Sentry.framework
> - nested: SwiftyJSON_6FA7ED0ED7CD70CA_PackageProduct.framework
> Moving nested frameworks from Sync.framework/Frameworks/ to Client.app/Frameworks/
> - nested: SwiftyJSON_6FA7ED0ED7CD70CA_PackageProduct.framework
> error: The specified item could not be found in the keychain.
> error: The specified item could not be found in the keychain.
> error: The specified item could not be found in the keychain.
> error: The specified item could not be found in the keychain.
> error: The specified item could not be found in the keychain.
> error: The specified item could not be found in the keychain.
> error: The specified item could not be found in the keychain.
> error: The specified item could not be found in the keychain.
> error: The specified item could not be found in the keychain.
> error: The specified item could not be found in the keychain.
> error: The specified item could not be found in the keychain.
> error: The specified item could not be found in the keychain.
> 
> /Users/bit9qa/Library/Developer/Xcode/DerivedData/Client-hcjyypqqvcxrgudukhazmtabpaqf/SourcePackages/checkouts/sentry-cocoa/Package.swift: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 15.2.99. (in target 'Sentry' from project 'Sentry')
> /Users/bit9qa/Library/Developer/Xcode/DerivedData/Client-hcjyypqqvcxrgudukhazmtabpaqf/SourcePackages/checkouts/SDWebImage/Package.swift: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 15.2.99. (in target 'SDWebImage' from project 'SDWebImage')
> /Users/bit9qa/Library/Developer/Xcode/DerivedData/Client-hcjyypqqvcxrgudukhazmtabpaqf/SourcePackages/checkouts/sentry-cocoa/Package.swift: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 15.2.99. (in target 'SentryCrash/Reporting/Tools' from project 'Sentry')
> /Users/bit9qa/Library/Developer/Xcode/DerivedData/Client-hcjyypqqvcxrgudukhazmtabpaqf/SourcePackages/checkouts/sentry-cocoa/Package.swift: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 15.2.99. (in target 'SentryCrash/Recording/Tools' from project 'Sentry')
> /Users/bit9qa/Library/Developer/Xcode/DerivedData/Client-hcjyypqqvcxrgudukhazmtabpaqf/SourcePackages/checkouts/sentry-cocoa/Package.swift: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 15.2.99. (in target 'SentryCrash/Reporting/Filters/Tools' from project 'Sentry')
> /Users/bit9qa/Library/Developer/Xcode/DerivedData/Client-hcjyypqqvcxrgudukhazmtabpaqf/SourcePackages/checkouts/sentry-cocoa/Package.swift: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 15.2.99. (in target 'SentryCrash/Reporting/Filters' from project 'Sentry')
> /Users/bit9qa/Library/Developer/Xcode/DerivedData/Client-hcjyypqqvcxrgudukhazmtabpaqf/SourcePackages/checkouts/sentry-cocoa/Package.swift: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 15.2.99. (in target 'SentryCrash/Recording/Monitors' from project 'Sentry')
> /Users/bit9qa/Library/Developer/Xcode/DerivedData/Client-hcjyypqqvcxrgudukhazmtabpaqf/SourcePackages/checkouts/sentry-cocoa/Package.swift: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 15.2.99. (in target 'SentryCrash/Recording' from project 'Sentry')
> /Users/bit9qa/Library/Developer/Xcode/DerivedData/Client-hcjyypqqvcxrgudukhazmtabpaqf/SourcePackages/checkouts/sentry-cocoa/Package.swift: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 15.2.99. (in target 'SentryCrash/Installations' from project 'Sentry')
> /Users/bit9qa/Library/Developer/Xcode/DerivedData/Client-hcjyypqqvcxrgudukhazmtabpaqf/SourcePackages/checkouts/SDWebImage/Package.swift: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 15.2.99. (in target 'SDWebImage' from project 'SDWebImage')
> /Users/bit9qa/Library/Developer/Xcode/DerivedData/Client-hcjyypqqvcxrgudukhazmtabpaqf/SourcePackages/checkouts/sentry-cocoa/Package.swift: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 15.2.99. (in target 'Sentry' from project 'Sentry')
> ** BUILD FAILED **
> 
> The following build commands failed:
>         PhaseScriptExecution Run\ Script /Users/bit9qa/Library/Developer/Xcode/DerivedData/Client-hcjyypqqvcxrgudukhazmtabpaqf/Build/Intermediates.noindex/Client.build/Fennec-iphoneos/Client.build/Script-4368F81027955AE80013419B.sh (in target 'Client' from project 'Client')
> (1 failure)

        

I am using the following command to build - 
`xcodebuild -project Client.xcodeproj -scheme Fennec -IDEBuildOperationMaxNumberOfConcurrentCompileTasks=1 CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO`

**MacOS version** : 12.2
     
Can somebody please help on this ?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3713)

**Comment by lmarceau** [comment]
Hey @pchandak1408, thanks for filing this issue! There was recent changes in how we manage dependencies since we moved to SPM (Swift Package Manager). We're still ironing out a couple of things, one of them being that we have to update our A-S dependency: https://github.com/mozilla-mobile/firefox-ios/pull/9938

I think once this is merged you can try again and let us know? It's being actively worked on 💪

**Comment by pchandak1408** [comment]
Thanks @lmarceau for the response. Also I tried building on M1 Mac12 machine, but seeing the following error. Will that also get fixed as part of #9938  ??

`ValidateEmbeddedBinary /Users/bit9qa/Library/Developer/Xcode/DerivedData/Client-hcjyypqqvcxrgudukhazmtabpaqf/Build/Products/Fennec-iphoneos/Client.app/PlugIns/WidgetKitExtension.appex (in target 'Client' from project 'Client')
    cd /tmp/firefox-ios
    /Applications/Xcode.app/Contents/Developer/usr/bin/embeddedBinaryValidationUtility /Users/bit9qa/Library/Developer/Xcode/DerivedData/Client-hcjyypqqvcxrgudukhazmtabpaqf/Build/Products/Fennec-iphoneos/Client.app/PlugIns/WidgetKitExtension.appex -info-plist-path /Users/bit9qa/Library/Developer/Xcode/DerivedData/Client-hcjyypqqvcxrgudukhazmtabpaqf/Build/Products/Fennec-iphoneos/Client.app/Info.plist
objc[37177]: Class AMSupportURLConnectionDelegate is implemented in both /usr/lib/libauthinstall.dylib (0x1e8386b90) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x1041b82c8). One of the two will be used. Which one is undefined.
objc[37177]: Class AMSupportURLSession is implemented in both /usr/lib/libauthinstall.dylib (0x1e8386be0) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x1041b8318). One of the two will be used. Which one is undefined.
Command ValidateEmbeddedBinary failed with a nonzero exit code`

**Comment by nbhasin2** [comment]
This should be resolved by https://github.com/mozilla-mobile/firefox-ios/pull/9942 but check the main branch after we merge it and let us know if you are still unable to build or have any issues with building Firefox iOS

**Comment by pchandak1408** [comment]
I tried with the latest changes  on Mac 12 (M1 as well as Intel), however I am still facing the same issue as mentioend above. Is there something else that I need to take care of ?

**Comment by nbhasin2** [comment]
> I tried with the latest changes  on Mac 12 (M1 as well as Intel), however I am still facing the same issue as mentioend above. Is there something else that I need to take care of ?

Have you tried to reset package cache, resolve dependency for swift package and run it from XCode directly?

Package cache is stored in derived data and at times using old cache can cause this issue.

**Comment by pchandak1408** [comment]
I followed the folowing steps to build the code. Please let me know if I have missed something. Since I am running this build process for performance testing of a product via automation, building the code using xcodebuild. 
_FYI, it was working fine couple of days back with xcode 13.1 and Mac 12.1_
```rm -rf ~/Library/Developer/Xcode/DerivedData/*
sh ./bootstrap.sh
npm run build
xcodebuild -project Client.xcodeproj -scheme Fennec clean
xcodebuild -project Client.xcodeproj -scheme Fennec CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO

**Comment by lmarceau** [comment]
@pchandak1408 Out of curiosity, is there a particular reason why you're building from command line?

You can try to resolve package dependencies through command line with `xcodebuild -resolvePackageDependencies` although there's a possibility this will not work by looking at some posts [here](https://stackoverflow.com/a/67006537/9516941) and you might have delete derived data.

**Comment by pchandak1408** [comment]
Yeah actually I am building this code via an automation script for that need to build using xcodebuild command.

**Comment by pchandak1408** [comment]
If you can provide the steps to build it from Xcode ? that will help

**Comment by lmarceau** [comment]
@pchandak1408 We have steps on how to build in Xcode in the [readme](https://github.com/mozilla-mobile/firefox-ios/blob/main/README.md#building-the-code) file.
