### ISSUE TITLE
Pin to Top Sites is not working when first running the app

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#9940]
## Steps to reproduce
1. Clean install 228b77b9a89f133417cb748fcf720fb01e6b6f1a
2. Dismiss onboarding 
3. Visit "mozilla.org"
4. Open Page action menu
5. Tap "Add to shortcuts"
6. Close the tab and check the Website Shortcuts
### Expected behavior
- "mozilla.org" should be pinned to shortcuts.
### Actual behavior
- "mozilla.org" is not pinned to shortcuts.
### Device & build information
* Device: iPhone 12 Pro
* Build version: 228b77b9a89f133417cb748fcf720fb01e6b6f1a
### Notes
- This issue is causing failure of testTopSitesRemoveAllExceptPinnedClearPrivateData.
Attachments: 

https://user-images.githubusercontent.com/32130829/152361010-4169e595-5e5c-4858-aff6-fd5ed4131b3d.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3715)

**Comment by dnarcese** [comment]
@SimonBasca was the site ever added to shortcuts, before you closed the tab? Is this fixed on the next run or on the next time you pin?

**Comment by SimonBasca** [comment]
The issue is no longer reproducible on latest main 17174ac12c460013f172b8f4c35217f555bea54b
