### ISSUE TITLE
Change description of the wallpaper settings' "Tap logo to change wallpaper" switch

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#9956]
Brian Jones recommends we make the following changes to the wallpaper settings screen:

1. Change the wallpaper settings screen's description of the logo setting from `"Tap logo to change wallpaper"` to `"Change wallpaper by tapping Firefox homepage logo"`.
2. Remove the `"Cycle through and update image without leaving the homepage"` line.

Android task for this UI change: [FNXV2-19390](https://mozilla-hub.atlassian.net/browse/FNXV2-19390)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3722)

**Comment by SimonBasca** [comment]
Verified fix on v99.0 (8544)
