### ISSUE TITLE
Bitrise - Fix the Deploy workflows

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/firefox-ios#9962]
Deploy_Nightly is failing since it still runs a carthage step:
https://github.com/mozilla-mobile/firefox-ios/blob/66ba998f9db31573e9aca10bf69f2cb408c87f0f/bitrise.yml#L754

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3725)

**Comment by isabelrios** [comment]
@nbhasin2 should we just remove this and use `SPM_...` workflows instead? If so I can change the scheduled build accordingly?
https://github.com/mozilla-mobile/firefox-ios/blob/204d1e5e08e3cfe71ff5583a0288123318c45ca5/bitrise.yml#L1265

**Comment by nbhasin2** [comment]
@isabelrios we are good to remove older workflow and use the spm ones 👍🏽

**Comment by isabelrios** [comment]
Great, @nbhasin2  thanks for your quick reply... and just to double-checking before doing the change... the old **Deploy_Nightly** is the same as the new **SPM_Nightly_Beta_Only**, confused due to the beta in there.. Thanks!

**Comment by nbhasin2** [comment]
@isabelrios its the same, I added beta in there to be more clear that we only send to beta
