### ISSUE TITLE
Make sure header accessibility traits is active on headers on Firefox homepage

### ISSUE THREAD

**Issue by lmarceau** [mozilla-mobile/firefox-ios#9969]
As a user navigating with Voice over, I would like to be able to navigate using the [VoiceOver rotor](https://support.apple.com/en-ca/HT204783) header traits, so I can move from one heading to the next.

## Steps to reproduce
- Activate Voice Over.
- Select the "Headings" options
- Try to navigate with it on the home page

### Expected behavior
Should navigate sections headers

### Actual behavior
Doesn't navigate on sections headers

### Device & build information
* Device: Any
* Build version: main
### Notes
Attachments: 

https://user-images.githubusercontent.com/11338480/153015492-3e325e56-5707-43db-a181-b20be1875c84.MP4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3729)

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verified fix on main 7493300c088051ed0a06d54dd5e1a6ff21cdd8a3
