### ISSUE TITLE
Improve ReaderModeStyle ViewController by using View model

### ISSUE THREAD

**Issue by lmarceau** [mozilla-mobile/firefox-ios#9976]
ReaderModeStyleViewController now has a view model `ReaderModeStyleViewModel` (from PR https://github.com/mozilla-mobile/firefox-ios/pull/9961).
Rest of logic should go in there so the pattern is full. Also make the view controller cleaner and has clearer responsibilities.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3737)

**Comment by data-sync-user** [comment]
➤ Razvan Litianu commented:

For QA: A smoke test is needed for the screen that is embedded in a popover when tapping reader mode.

**Comment by DianaBarladeanu** [comment]
Verified on multiple websites, no issues encountered.
Device: iPhone SE (15.4), Build: v9000 (32297)
