### ISSUE TITLE
Improve Search View Controller by using View model

### ISSUE THREAD

**Issue by lmarceau** [mozilla-mobile/firefox-ios#9977]
Search view controller now has a view model `SearchViewModel` (from PR https://github.com/mozilla-mobile/firefox-ios/pull/9961).
Rest of logic should go in there so the pattern is full. Also make the view controller cleaner and has clearer responsibilities.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3736)

**Comment by data-sync-user** [comment]
➤ Cyndi Chin commented:

This code has been refactored, please verify that the search feature works as expected including search suggestions, firefox suggestions and search engines. Thank you!

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Validated on v9000 (43238), with iPhone 15 (17.5).

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Validated on v129 (43512), with iPhone 15 (17.5).
