### ISSUE TITLE
Private tabs persist over restart

### ISSUE THREAD

**Issue by ChemicalXandco** [mozilla-mobile/firefox-ios#9985]
## Steps to reproduce

1. open private tab
2. restart app

### Expected behavior

no private tabs open

### Actual behavior

the private tabs that were open before restarting are there

### Device & build information
* Device: Any
* Build version: main

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3743)

**Comment by lmarceau** [comment]
Hi @ChemicalXandco 👋 
Thanks a lot for contributing. We have an option in place for users to erase their private tabs when they leave private mode. This will erase your tab when you kill the app and avoid restoration.

![Screen Shot 2022-02-09 at 5 48 38 PM](https://user-images.githubusercontent.com/11338480/153303684-88dcaebb-1fe8-438c-9222-4405ae92f7e4.png)

Behavior with the checked option in settings.

https://user-images.githubusercontent.com/11338480/153303815-a1b1754b-f1c2-45f6-912a-5186c5010d62.mp4
