### ISSUE TITLE
Update reader mode fonts

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#9995]
To comply with our new design system, we need to update the font used in reader mode

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3750)

**Comment by tech189** [comment]
What would be the reason for removing the ability to change fonts (sans-serif/serif)? This is a useful feature which Safari also has, in fact Safari allows the user to change between 9 serif and sans-serif fonts!

**Comment by dnarcese** [comment]
I need to clarify the requirements here, tbd on whether we are removing that ability.

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Yoana Rios Diaz I am seeing the same font in reader mode. Could you please clarify what should be tested?

**Comment by data-sync-user** [comment]
➤ Yoana Rios Diaz commented:

Simion Basca The Font family are still the same *Sans-Serif* and Serif the change about the actual font we are using on the content of the page for Serif we were already using New-York and we are using SF Pro now for  Sans-Serif family instead of Fira fonts.
For test just verify that Reader mode continues to work as expected when changing the font family type

**Comment by data-sync-user** [comment]
➤ Catalin Suciu commented:

Verifying as fixed on v9000 (23491)
