### ISSUE TITLE
Add telemetry for search results

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#9996]
As a product manager, I want to understand how valuable users are finding each search bar result and how often they are opening a bookmark, history item, or tab from the search bar.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3751)

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Hello, can you please add the exact name for each event that needs to be verified?

**Comment by lmarceau** [comment]
Linking PR with: https://github.com/mozilla-mobile/firefox-ios/pull/10867

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Hello

!image-20220620-125535.png|width=398,height=205!

!image-20220620-125553.png|width=357,height=205!

Also, for counts for when a synced (aka remote) tab is opened from awesomebar the event type in glean should be temp-tabs-sync? 
I found this but I’m not sure if this is what needs to be verified 

!image-20220620-135110.png|width=532,height=114!

!image-20220620-135117.png|width=468,height=194!

**Comment by data-sync-user** [comment]
➤ Laurie Marceau commented:

Andrei Bodea 

From what I see from the code, the events should be:

Each time a user select a search result the event search_result_tap will be sent with one of the following extra history-item, remote-tab, opened-tab, bookmark-item, search-suggestion. Ex: a user select a remote tab suggestion, search_result_tap will be sent with the extra remote-tab. So in the particular case we can test that we do get history-item, remote-tab, opened-tab, bookmark-item, search-suggestion extra types on clicks of the related items.

temp-tabs-sync doesn’t relate to this PR I believe. It relates to the sync feature.

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Verified as fixed on the 102 (11255) with iPhone 13 Pro (15.1.1).
I was able to generate history-item, remote-tab, opened-tab, bookmark-item, and search-suggestion.
